SUBROUTINE GOTO_WRAPPER_TRIP(KTO)
USE MODD_TRIP
USE MODD_TRIP_DIAG
USE MODD_TRIP_GRID
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE 
INTEGER,INTENT(IN) :: KTO
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
IF (LHOOK) CALL DR_HOOK('GOTO_WRAPPER_TRIP',0,ZHOOK_HANDLE)
CALL TRIP_GOTO_MODEL(KTO)
CALL TRIP_DIAG_GOTO_MODEL(KTO)
CALL TRIP_GRID_GOTO_MODEL(KTO)
IF (LHOOK) CALL DR_HOOK('GOTO_WRAPPER_TRIP',1,ZHOOK_HANDLE)
!
END SUBROUTINE GOTO_WRAPPER_TRIP
