!######################
MODULE MODD_TRIP_DIAG
!######################
!
!!****  *MODD_TRIP_DIAG - declaration of diagnostics for TRIP scheme
!!
!!    PURPOSE
!!    -------
!
!!
!!**  IMPLICIT ARGUMENTS
!!    ------------------
!!      None 
!!
!!    REFERENCE
!!    ---------
!!
!!    AUTHOR
!!    ------
!!      B. Decharme   *Meteo France*
!!
!!    MODIFICATIONS
!!    -------------
!!      Original       21/05/08
!
!*       0.   DECLARATIONS
!             ------------
!
USE MODD_TYPE_DIAG
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE
!
TYPE TRIP_DIAG_t
!-------------------------------------------------------------------------------
!
  TYPE(DIAG)                :: TDIAG            ! current diagnostics 
!  
  TYPE(DIAG)                :: TDIAG_RUN        ! Run mean diagnostics 
!
!-------------------------------------------------------------------------------
!
END TYPE TRIP_DIAG_t
!
CONTAINS
!
SUBROUTINE TRIP_DIAG_NULLIFY(YTRIP_DIAG)
TYPE(TRIP_DIAG_t), INTENT(INOUT) :: YTRIP_DIAG
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
IF (LHOOK) CALL DR_HOOK("MODD_TRIP_DIAG:TRIP_DIAG_NULLIFY",0,ZHOOK_HANDLE)
!
NULLIFY(YTRIP_DIAG%TDIAG%XSURF_STO)
NULLIFY(YTRIP_DIAG%TDIAG%XGROUND_STO)
NULLIFY(YTRIP_DIAG%TDIAG%XFLOOD_STO)
NULLIFY(YTRIP_DIAG%TDIAG%XQDIS)
NULLIFY(YTRIP_DIAG%TDIAG%XQGF)
NULLIFY(YTRIP_DIAG%TDIAG%XVEL)
NULLIFY(YTRIP_DIAG%TDIAG%XHS)
NULLIFY(YTRIP_DIAG%TDIAG%XFF)
NULLIFY(YTRIP_DIAG%TDIAG%XHF)
NULLIFY(YTRIP_DIAG%TDIAG%XQFR)
NULLIFY(YTRIP_DIAG%TDIAG%XQRF)
NULLIFY(YTRIP_DIAG%TDIAG%XQIN)
NULLIFY(YTRIP_DIAG%TDIAG%XVFIN)
NULLIFY(YTRIP_DIAG%TDIAG%XVFOUT)
NULLIFY(YTRIP_DIAG%TDIAG%XWF)
NULLIFY(YTRIP_DIAG%TDIAG%XLF)
NULLIFY(YTRIP_DIAG%TDIAG%XHSF)
NULLIFY(YTRIP_DIAG%TDIAG%XRUNOFF)
NULLIFY(YTRIP_DIAG%TDIAG%XDRAIN)
NULLIFY(YTRIP_DIAG%TDIAG%XSOURCE)
NULLIFY(YTRIP_DIAG%TDIAG%XHGROUND)
NULLIFY(YTRIP_DIAG%TDIAG%XQGCELL)
NULLIFY(YTRIP_DIAG%TDIAG%XWTD)
NULLIFY(YTRIP_DIAG%TDIAG%XFWTD)
NULLIFY(YTRIP_DIAG%TDIAG%XHGHS)
!
NULLIFY(YTRIP_DIAG%TDIAG_RUN%XSURF_STO)
NULLIFY(YTRIP_DIAG%TDIAG_RUN%XGROUND_STO)
NULLIFY(YTRIP_DIAG%TDIAG_RUN%XFLOOD_STO)
NULLIFY(YTRIP_DIAG%TDIAG_RUN%XQDIS)
NULLIFY(YTRIP_DIAG%TDIAG_RUN%XQGF)
NULLIFY(YTRIP_DIAG%TDIAG_RUN%XVEL)
NULLIFY(YTRIP_DIAG%TDIAG_RUN%XHS)
NULLIFY(YTRIP_DIAG%TDIAG_RUN%XFF)
NULLIFY(YTRIP_DIAG%TDIAG_RUN%XHF)
NULLIFY(YTRIP_DIAG%TDIAG_RUN%XQFR)
NULLIFY(YTRIP_DIAG%TDIAG_RUN%XQRF)
NULLIFY(YTRIP_DIAG%TDIAG_RUN%XQIN)
NULLIFY(YTRIP_DIAG%TDIAG_RUN%XVFIN)
NULLIFY(YTRIP_DIAG%TDIAG_RUN%XVFOUT)
NULLIFY(YTRIP_DIAG%TDIAG_RUN%XWF)
NULLIFY(YTRIP_DIAG%TDIAG_RUN%XLF)
NULLIFY(YTRIP_DIAG%TDIAG_RUN%XHSF)
NULLIFY(YTRIP_DIAG%TDIAG_RUN%XRUNOFF)
NULLIFY(YTRIP_DIAG%TDIAG_RUN%XDRAIN)
NULLIFY(YTRIP_DIAG%TDIAG_RUN%XSOURCE)
NULLIFY(YTRIP_DIAG%TDIAG_RUN%XHGROUND)
NULLIFY(YTRIP_DIAG%TDIAG_RUN%XQGCELL)
NULLIFY(YTRIP_DIAG%TDIAG_RUN%XWTD)
NULLIFY(YTRIP_DIAG%TDIAG_RUN%XFWTD)
NULLIFY(YTRIP_DIAG%TDIAG_RUN%XHGHS)
!
IF (LHOOK) CALL DR_HOOK("MODD_TRIP_DIAG:TRIP_DIAG_NULLIFY",1,ZHOOK_HANDLE)
!
END SUBROUTINE TRIP_DIAG_NULLIFY

!
END MODULE MODD_TRIP_DIAG
