!######################
MODULE MODD_TRIP_DIAG
!######################
!
!!****  *MODD_TRIP_DIAG - declaration of diagnostics for TRIP scheme
!!
!!    PURPOSE
!!    -------
!
!!
!!**  IMPLICIT ARGUMENTS
!!    ------------------
!!      None 
!!
!!    REFERENCE
!!    ---------
!!
!!    AUTHOR
!!    ------
!!      B. Decharme   *Meteo France*
!!
!!    MODIFICATIONS
!!    -------------
!!      Original       21/05/08
!
!*       0.   DECLARATIONS
!             ------------
!
USE MODD_TYPE_DIAG
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE

TYPE TRIP_DIAG_t
!-------------------------------------------------------------------------------
!
  TYPE(DIAG)                :: TDIAG            ! current diagnostics 
!  
  TYPE(DIAG)                :: TDIAG_RUN        ! Run mean diagnostics 
!
!-------------------------------------------------------------------------------
!
END TYPE TRIP_DIAG_t
!
TYPE(TRIP_DIAG_t), ALLOCATABLE, TARGET, SAVE :: TRIP_DIAG_MODEL(:)
!
TYPE(DIAG), POINTER :: TDIAG=>NULL()
!$OMP THREADPRIVATE(TDIAG)
!
TYPE(DIAG), POINTER :: TDIAG_RUN=>NULL()
!$OMP THREADPRIVATE(TDIAG_RUN)
!
CONTAINS
!
SUBROUTINE TRIP_DIAG_GOTO_MODEL(KTO)
INTEGER, INTENT(IN) :: KTO
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
! Current model is set to model KTO
IF (LHOOK) CALL DR_HOOK('MODD_TRIP_DIAG:TRIP_DIAG_GOTO_MODEL',0,ZHOOK_HANDLE)
!
TDIAG=>TRIP_DIAG_MODEL(KTO)%TDIAG
!
TDIAG_RUN=>TRIP_DIAG_MODEL(KTO)%TDIAG_RUN
!
IF (LHOOK) CALL DR_HOOK('MODD_TRIP_DIAG:TRIP_DIAG_GOTO_MODEL',1,ZHOOK_HANDLE)
!
END SUBROUTINE TRIP_DIAG_GOTO_MODEL

SUBROUTINE TRIP_DIAG_ALLOC(KMODEL)
!
INTEGER, INTENT(IN) :: KMODEL
INTEGER :: J
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
IF (LHOOK) CALL DR_HOOK("MODD_TRIP_DIAG:TRIP_DIAG_ALLOC",0,ZHOOK_HANDLE)
!
ALLOCATE(TRIP_DIAG_MODEL(KMODEL))
!
DO J=1,KMODEL
  !
  NULLIFY(TRIP_DIAG_MODEL(J)%TDIAG%XSURF_STO)
  NULLIFY(TRIP_DIAG_MODEL(J)%TDIAG%XGROUND_STO)
  NULLIFY(TRIP_DIAG_MODEL(J)%TDIAG%XFLOOD_STO)
  NULLIFY(TRIP_DIAG_MODEL(J)%TDIAG%XQDIS)
  NULLIFY(TRIP_DIAG_MODEL(J)%TDIAG%XQGF)
  NULLIFY(TRIP_DIAG_MODEL(J)%TDIAG%XVEL)
  NULLIFY(TRIP_DIAG_MODEL(J)%TDIAG%XHS)
  NULLIFY(TRIP_DIAG_MODEL(J)%TDIAG%XFF)
  NULLIFY(TRIP_DIAG_MODEL(J)%TDIAG%XHF)
  NULLIFY(TRIP_DIAG_MODEL(J)%TDIAG%XQFR)
  NULLIFY(TRIP_DIAG_MODEL(J)%TDIAG%XQRF)
  NULLIFY(TRIP_DIAG_MODEL(J)%TDIAG%XQIN)
  NULLIFY(TRIP_DIAG_MODEL(J)%TDIAG%XVFIN)
  NULLIFY(TRIP_DIAG_MODEL(J)%TDIAG%XVFOUT)
  NULLIFY(TRIP_DIAG_MODEL(J)%TDIAG%XWF)
  NULLIFY(TRIP_DIAG_MODEL(J)%TDIAG%XLF)
  NULLIFY(TRIP_DIAG_MODEL(J)%TDIAG%XHSF)
  NULLIFY(TRIP_DIAG_MODEL(J)%TDIAG%XRUNOFF)
  NULLIFY(TRIP_DIAG_MODEL(J)%TDIAG%XDRAIN)
  NULLIFY(TRIP_DIAG_MODEL(J)%TDIAG%XSOURCE)
  NULLIFY(TRIP_DIAG_MODEL(J)%TDIAG%XHGROUND)
  NULLIFY(TRIP_DIAG_MODEL(J)%TDIAG%XQGCELL)
  NULLIFY(TRIP_DIAG_MODEL(J)%TDIAG%XWTD)
  NULLIFY(TRIP_DIAG_MODEL(J)%TDIAG%XFWTD)
  NULLIFY(TRIP_DIAG_MODEL(J)%TDIAG%XWTDRIV)
  NULLIFY(TRIP_DIAG_MODEL(J)%TDIAG%XWTDELEV)
  NULLIFY(TRIP_DIAG_MODEL(J)%TDIAG%XHGHS)
  !
  NULLIFY(TRIP_DIAG_MODEL(J)%TDIAG_RUN%XSURF_STO)
  NULLIFY(TRIP_DIAG_MODEL(J)%TDIAG_RUN%XGROUND_STO)
  NULLIFY(TRIP_DIAG_MODEL(J)%TDIAG_RUN%XFLOOD_STO)
  NULLIFY(TRIP_DIAG_MODEL(J)%TDIAG_RUN%XQDIS)
  NULLIFY(TRIP_DIAG_MODEL(J)%TDIAG_RUN%XQGF)
  NULLIFY(TRIP_DIAG_MODEL(J)%TDIAG_RUN%XVEL)
  NULLIFY(TRIP_DIAG_MODEL(J)%TDIAG_RUN%XHS)
  NULLIFY(TRIP_DIAG_MODEL(J)%TDIAG_RUN%XFF)
  NULLIFY(TRIP_DIAG_MODEL(J)%TDIAG_RUN%XHF)
  NULLIFY(TRIP_DIAG_MODEL(J)%TDIAG_RUN%XQFR)
  NULLIFY(TRIP_DIAG_MODEL(J)%TDIAG_RUN%XQRF)
  NULLIFY(TRIP_DIAG_MODEL(J)%TDIAG_RUN%XQIN)
  NULLIFY(TRIP_DIAG_MODEL(J)%TDIAG_RUN%XVFIN)
  NULLIFY(TRIP_DIAG_MODEL(J)%TDIAG_RUN%XVFOUT)
  NULLIFY(TRIP_DIAG_MODEL(J)%TDIAG_RUN%XWF)
  NULLIFY(TRIP_DIAG_MODEL(J)%TDIAG_RUN%XLF)
  NULLIFY(TRIP_DIAG_MODEL(J)%TDIAG_RUN%XHSF)
  NULLIFY(TRIP_DIAG_MODEL(J)%TDIAG_RUN%XRUNOFF)
  NULLIFY(TRIP_DIAG_MODEL(J)%TDIAG_RUN%XDRAIN)
  NULLIFY(TRIP_DIAG_MODEL(J)%TDIAG_RUN%XSOURCE)
  NULLIFY(TRIP_DIAG_MODEL(J)%TDIAG_RUN%XHGROUND)
  NULLIFY(TRIP_DIAG_MODEL(J)%TDIAG_RUN%XQGCELL)
  NULLIFY(TRIP_DIAG_MODEL(J)%TDIAG_RUN%XWTD)
  NULLIFY(TRIP_DIAG_MODEL(J)%TDIAG_RUN%XFWTD)
  NULLIFY(TRIP_DIAG_MODEL(J)%TDIAG_RUN%XWTDRIV)
  NULLIFY(TRIP_DIAG_MODEL(J)%TDIAG_RUN%XWTDELEV)
  NULLIFY(TRIP_DIAG_MODEL(J)%TDIAG_RUN%XHGHS)
  !  
ENDDO
!
IF (LHOOK) CALL DR_HOOK("MODD_TRIP_DIAG:TRIP_DIAG_ALLOC",1,ZHOOK_HANDLE)
!
END SUBROUTINE TRIP_DIAG_ALLOC

SUBROUTINE TRIP_DIAG_DEALLO
REAL(KIND=JPRB) :: ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK("MODD_TRIP_DIAG:TRIP_DIAG_DEALLO",0,ZHOOK_HANDLE)
IF (ALLOCATED(TRIP_DIAG_MODEL)) DEALLOCATE(TRIP_DIAG_MODEL)
IF (LHOOK) CALL DR_HOOK("MODD_TRIP_DIAG:TRIP_DIAG_DEALLO",1,ZHOOK_HANDLE)
END SUBROUTINE TRIP_DIAG_DEALLO
!
END MODULE MODD_TRIP_DIAG
