!     #########
      SUBROUTINE PREP_TRIP_RUN (TP, TPG, &
                                KYEAR,KMONTH,KDAY,PTIME,KLON,KLAT)
!     ####################
!
!!****  *PREP_TRIP_RUN*  
!!
!!    PURPOSE
!!    -------
!
!     Prepare TRIP variables and parameters.
!     
!!**  METHOD
!!    ------
!
!     Direct calculation
!
!!    EXTERNAL
!!    --------
!
!     None
!!
!!    IMPLICIT ARGUMENTS
!!    ------------------
!!
!!      
!!    REFERENCE
!!    ---------
!!      
!!    AUTHOR
!!    ------
!!      B. Decharme     (Meteo-France)
!!
!!    MODIFICATIONS
!!    -------------
!!      Original    27/05/08 
!-------------------------------------------------------------------------------
!
!*       0.     DECLARATIONS
!               ------------
!
!
USE MODD_TRIP, ONLY : TRIP_t
USE MODD_TRIP_GRID, ONLY : TRIP_GRID_t
!
USE MODN_TRIP, ONLY : CGROUNDW, CVIT, LFLOOD,  &
                      XCVEL, XRATMED, XTSTEP,  &
                      XTAUG_UNIF, XTAUG_UP,    &
                      XTAUG_DOWN
!
USE MODD_TRIP_PAR
USE MODD_TRIP_LISTING, ONLY : NLISTING
!
!
USE MODE_TRIP_INIT
USE MODE_RW_TRIP
!
USE MODI_ABORT_TRIP
USE MODI_GET_TRIP_GRID_CONF
USE MODI_INIT_PARAM_TRIP
USE MODI_INIT_RESTART_TRIP
USE MODI_GET_LONLAT_TRIP
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE
!
!-------------------------------------------------------------------------------
!
!*      0.1    declarations of arguments
!
!
TYPE(TRIP_t), INTENT(INOUT) :: TP
TYPE(TRIP_GRID_t), INTENT(INOUT) :: TPG
!
INTEGER,          INTENT(IN) :: KYEAR   !date UTC
INTEGER,          INTENT(IN) :: KMONTH  !date UTC
INTEGER,          INTENT(IN) :: KDAY    !date UTC
REAL,             INTENT(IN) :: PTIME   !date UTC
INTEGER,          INTENT(OUT):: KLON    ! number of points in longitude
INTEGER,          INTENT(OUT):: KLAT    ! number of points in latitude
!
!-------------------------------------------------------------------------------
!
!*      0.2    declarations of local variables
!
LOGICAL,           PARAMETER         :: LDOUBLE         =.TRUE.
!
CHARACTER(LEN=20), PARAMETER         :: YFILE_PARAM_1D  ='TRIP_PGD_1D.nc'
CHARACTER(LEN=20), PARAMETER         :: YFILE_PARAM_HD  ='TRIP_PGD_HD.nc'
CHARACTER(LEN=20), PARAMETER         :: YFILE_PARAM_12  ='TRIP_PGD_12D.nc'
CHARACTER(LEN=20), PARAMETER         :: YFILE_INIT_1D   ='TRIP_INIT_1D.nc'
CHARACTER(LEN=20), PARAMETER         :: YFILE_INIT_HD   ='TRIP_INIT_HD.nc'
CHARACTER(LEN=20), PARAMETER         :: YFILE_INIT_12   ='TRIP_INIT_12D.nc'
!
CHARACTER(LEN=20), PARAMETER         :: YFILE_PARAM     ='TRIP_PARAM.nc'
CHARACTER(LEN=20), PARAMETER         :: YFILE_PREP      ='TRIP_PREP.nc'
!
CHARACTER(LEN=20)                    :: YFILE_READ
CHARACTER(LEN=20)                    :: YFILE_READ_INIT
!
CHARACTER(LEN=20), PARAMETER         :: YFILE_FLOOD_1D  ='TRIP_SGFLOOD_1D.nc'
CHARACTER(LEN=20), PARAMETER         :: YFILE_FLOOD_HD  ='TRIP_SGFLOOD_HD.nc'
CHARACTER(LEN=20)                    :: YFILE_FLOOD_READ
!
CHARACTER(LEN=20), PARAMETER         :: YFILE_GW_HD     ='TRIP_SGAQUI_HD.nc'
CHARACTER(LEN=20), PARAMETER         :: YFILE_GW_12D    ='TRIP_SGAQUI_12D.nc'
CHARACTER(LEN=20)                    :: YFILE_GW_READ
!
CHARACTER(LEN=20)                    :: YVAR 
!
REAL, DIMENSION(:),ALLOCATABLE       :: ZLON
REAL, DIMENSION(:),ALLOCATABLE       :: ZLAT
!
REAL,DIMENSION(:,:),ALLOCATABLE      :: ZGRCN
REAL,DIMENSION(:,:),ALLOCATABLE      :: ZSEQ
REAL,DIMENSION(:,:),ALLOCATABLE      :: ZNUM_BAS
REAL,DIMENSION(:,:),ALLOCATABLE      :: ZDR_AREA
REAL,DIMENSION(:,:),ALLOCATABLE      :: ZREAD
REAL,DIMENSION(:,:),ALLOCATABLE      :: ZWORK
REAL,DIMENSION(:,:),ALLOCATABLE      :: ZLEN
REAL,DIMENSION(:,:),ALLOCATABLE      :: ZGREEN_ANT
!
REAL,DIMENSION(:,:,:),ALLOCATABLE    :: ZREAD3D
!
INTEGER,DIMENSION(:,:),ALLOCATABLE   :: IGRCN
INTEGER,DIMENSION(:,:),ALLOCATABLE   :: INEXTX
INTEGER,DIMENSION(:,:),ALLOCATABLE   :: INEXTY
!
REAL    :: ZLONMIN   ! minimum longitude (degrees)
REAL    :: ZLONMAX   ! maximum longitude (degrees)
REAL    :: ZLATMIN   ! minimum latitude  (degrees)
REAL    :: ZLATMAX   ! maximum latitude  (degrees)
REAL    :: ZGRID_RES ! 1° or 0.5° resolution
REAL    :: ZSEQMAX
!
INTEGER :: ILON,ILAT
INTEGER :: ILON_G, ILON_DEB, ILON_END
INTEGER :: ILON_G12, ILON_DEB12, ILON_END12
INTEGER :: ILAT_G, ILAT_DEB, ILAT_END
INTEGER :: ILAT_G12, ILAT_DEB12, ILAT_END12
!
INTEGER :: IWORK, IFLOOD, JLON, JLAT, INI, ILATF
!
LOGICAL :: LMASKLON, LMASKLAT
!
!-------------------------------------------------------------------------------
!Output attribut for netcdf diag file
!-------------------------------------------------------------------------------
!
 CHARACTER(LEN=50) :: YTITLE,YTIMEUNIT
!                    YTITLE    = Title of each output file
!                    YTIMEUNIT = Time unit in each output file if present
!
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
!-------------------------------------------------------------------------------
!Initilyse TRIP
!-------------------------------------------------------------------------------
!
IF (LHOOK) CALL DR_HOOK('PREP_TRIP_RUN',0,ZHOOK_HANDLE)
!
WRITE(NLISTING,*)''
WRITE(NLISTING,*)'        PREP TRIP            '
WRITE(NLISTING,*)''
!
!-------------------------------------------------------------------------------
!
IF(LFLOOD)THEN
  IF(CGROUNDW=='DEF') &
      WRITE(NLISTING,*)'! Attention, you use the flooding scheme without groundwater scheme !!!'       
  IF(CVIT /= 'VAR')THEN
    WRITE(NLISTING,*)'! You cannot use the flooding scheme without the variable velocity scheme !!!'
    CALL ABORT_TRIP('PREP_TRIP_RUN: You cannot use the flooding scheme without the variable velocity scheme')
  ENDIF
ENDIF
!
IF(CGROUNDW=='CST')THEN
  IF(XTAUG_UNIF<1.0.OR.XTAUG_UNIF>365.0)THEN
    WRITE(NLISTING,*)'! Constant transfert time value XTAUG_UNIF must be at least 1 day or inferior to 365 days !!!'
    CALL ABORT_TRIP('PREP_TRIP_RUN: Constant transfert time value must be at least 1 day or inferior to 365 days')
  ENDIF        
ENDIF
!
IF(CGROUNDW=='DIF')THEN
  IF(CVIT /= 'VAR')THEN
    WRITE(NLISTING,*)'! You cannot use the groundwater scheme without the variable velocity scheme !!!'
    CALL ABORT_TRIP('PREP_TRIP_RUN: You cannot use the groundwater scheme without the variable velocity scheme')
  ENDIF
  IF(XTAUG_UP<1.0)THEN
    WRITE(NLISTING,*)'! Upstream transfert time value XTAUG_UP must be at least 1 day !!!'
    CALL ABORT_TRIP('PREP_TRIP_RUN: Upstream transfert time value must be at least 1 day')
  ENDIF
  IF(XTAUG_DOWN>365.0)THEN
    WRITE(NLISTING,*)'! Downstream transfert time value XTAUG_DOWN must be lower than 365 days !!!'
    CALL ABORT_TRIP('PREP_TRIP_RUN: Downstream transfert time value must be lower than 365 days')
  ENDIF  
ENDIF
!
!-------------------------------------------------------------------------------
! * Read TRIP grid configuration
!-------------------------------------------------------------------------------
!
CALL GET_TRIP_GRID_CONF(TPG, &
                        ZLONMIN,ZLONMAX,ZLATMIN,ZLATMAX,ZGRID_RES,ILON,ILAT)
KLON=ILON
KLAT=ILAT
!
ALLOCATE(ZLON(KLON))
ALLOCATE(ZLAT(KLAT))
ZLON(:)=XUNDEF
ZLAT(:)=XUNDEF
!
CALL GET_LONLAT_TRIP(TPG, &
                     KLON,KLAT,ZLON,ZLAT)
!
IF(ZGRID_RES==1.0)THEN
!
  WRITE(NLISTING,*)'! 1° by 1° TRIP run !!!'
!
  ILON_G = 360
  ILAT_G = 180
  ILATF  = 31
  YFILE_READ = YFILE_PARAM_1D
  YFILE_READ_INIT = YFILE_INIT_1D
  YFILE_FLOOD_READ = YFILE_FLOOD_1D
!
ELSEIF(ZGRID_RES==0.5)THEN
!
  WRITE(NLISTING,*)'! 0.5° by 0.5° TRIP run !!!'
!
  ILON_G = 720
  ILAT_G = 360
  ILATF  = 61
  YFILE_READ = YFILE_PARAM_HD
  YFILE_READ_INIT = YFILE_INIT_HD
  YFILE_GW_READ = YFILE_GW_HD
  YFILE_FLOOD_READ = YFILE_FLOOD_HD
!
ELSEIF(ZGRID_RES < 0.09)THEN
!
  WRITE(NLISTING,*)'!!! 1/12° by 1/12° TRIP run (FRANCE) !!!'
!
  ILON_G = 180
  ILAT_G = 108
  ILON_G12 = 4320
  ILAT_G12 = 2160
  
  ILATF  = 1
  YFILE_READ = YFILE_PARAM_12
  YFILE_READ_INIT = YFILE_INIT_12
  YFILE_GW_READ = YFILE_GW_12D  
!
  IF(XRATMED==1.4)THEN
     WRITE(NLISTING,*)'! meandering ratio is the same than at 1° resolution   !!!'   
     WRITE(NLISTING,*)'! change XRATMED in namelist                           !!!'           
     CALL ABORT_TRIP('PREP_TRIP_RUN: meandering ratio not good')
  ENDIF 
!
ELSE
!
  WRITE(NLISTING,*)'! The resolution of the TRIP run is not good !!!'   
  WRITE(NLISTING,*)'! Should be 1° or 0.5° or 1/12 ° over France !!!'
  CALL ABORT_TRIP('PREP_TRIP_RUN: resolution of the TRIP run is not good')
!  
ENDIF
!
IF(CGROUNDW=='DIF')THEN
  IF(ZGRID_RES>0.5)THEN
    WRITE(NLISTING,*)'! You cannot use the groundwater scheme with another resolution than 0.5 or 1/12 !!!'
    CALL ABORT_TRIP('PREP_TRIP_RUN: You cannot use the groundwater scheme with another resolution than 0.5 or 1/12')
  ENDIF  
ENDIF  
!
LMASKLON=.FALSE.
IF(ZLONMIN/=-180..OR.ZLONMAX/=180.)LMASKLON=.TRUE.
!
LMASKLAT=.FALSE.
IF(ZLATMIN/=-180..OR.ZLATMAX/=180.)LMASKLAT=.TRUE.
!
!-------------------------------------------------------------------------------
!Allocate arguments
!-------------------------------------------------------------------------------
!
ALLOCATE(TPG%GMASK    (ILON,ILAT))
ALLOCATE(TPG%GMASK_GW (ILON,ILAT))
ALLOCATE(TPG%GMASK_GRE(ILON,ILAT))
ALLOCATE(TPG%GMASK_ANT(ILON,ILAT))
TPG%GMASK    (:,:) = .FALSE.
TPG%GMASK_GW (:,:) = .FALSE.
TPG%GMASK_GRE(:,:) = .FALSE.
TPG%GMASK_ANT(:,:) = .FALSE.
!
ALLOCATE(TPG%XAREA(ILON,ILAT))
ALLOCATE(TPG%NGRCN(ILON,ILAT))
!
ALLOCATE(ZLEN      (ILON,ILAT))
ALLOCATE(ZGRCN     (ILON,ILAT))       
ALLOCATE(ZSEQ      (ILON,ILAT))   
ALLOCATE(ZNUM_BAS  (ILON,ILAT))
ALLOCATE(ZDR_AREA  (ILON,ILAT))
ALLOCATE(ZGREEN_ANT(ILON,ILAT))
!
ALLOCATE(TP%XSURF_STO(ILON,ILAT))
!
IF(CGROUNDW/='DEF')THEN
  ALLOCATE(TP%XTAUG      (ILON,ILAT))
ELSE
  ALLOCATE(TP%XTAUG      (0,0))
ENDIF
!
IF(CGROUNDW=='CST')THEN
  ALLOCATE(TP%XGROUND_STO(ILON,ILAT))      
ELSE
  ALLOCATE(TP%XGROUND_STO(0,0))      
ENDIF
!
IF(CGROUNDW=='DIF')THEN
  ALLOCATE(TP%XHGROUND   (ILON,ILAT))
  ALLOCATE(TP%XWEFF      (ILON,ILAT))
  ALLOCATE(TP%XTRANS     (ILON,ILAT))
  ALLOCATE(TP%XNUM_AQUI  (ILON,ILAT))
  ALLOCATE(TP%XTOPO_RIV  (ILON,ILAT))
ELSE
  ALLOCATE(TP%XHGROUND   (0,0))
  ALLOCATE(TP%XWEFF      (0,0))
  ALLOCATE(TP%XTRANS     (0,0))
  ALLOCATE(TP%XNUM_AQUI  (0,0))
  ALLOCATE(TP%XTOPO_RIV  (0,0))
ENDIF
!
IF(LFLOOD.OR.CGROUNDW=='DIF')THEN
  ALLOCATE(TP%XHC_BED    (ILON,ILAT))
ELSE
  ALLOCATE(TP%XHC_BED   (0,0))
ENDIF
!
IF(LFLOOD)THEN
  ALLOCATE(TP%XN_FLOOD    (ILON,ILAT))
  ALLOCATE(TP%XFLOOD_STO  (ILON,ILAT))
  ALLOCATE(TP%XHFLOOD     (ILON,ILAT))
  ALLOCATE(TP%XFFLOOD     (ILON,ILAT))
ELSE
  ALLOCATE(TP%XN_FLOOD  (0,0))
  ALLOCATE(TP%XFLOOD_STO(0,0))
  ALLOCATE(TP%XHFLOOD   (0,0))
  ALLOCATE(TP%XFFLOOD   (0,0))
ENDIF
!
IF(CVIT=='VAR')THEN
  ALLOCATE(TP%XSLOPEBED(ILON,ILAT))      
  ALLOCATE(TP%XWIDTH   (ILON,ILAT))      
  ALLOCATE(TP%XN       (ILON,ILAT))
ELSE
  ALLOCATE(TP%XSLOPEBED(0,0))      
  ALLOCATE(TP%XWIDTH   (0,0))      
  ALLOCATE(TP%XN       (0,0))
ENDIF
!
!-------------------------------------------------------------------------------
! * Create param and init file
!-------------------------------------------------------------------------------
!
YTITLE    = 'TRIP parameters for a run'
YTIMEUNIT = '-'
CALL INIT_PARAM_TRIP(TPG, &
                     NLISTING,YFILE_PARAM,ILON,ILAT,YTITLE,YTIMEUNIT)
!
YTITLE   ='TRIP prep historical variable'
YTIMEUNIT='-'
CALL INIT_RESTART_TRIP(TPG, &
                       NLISTING,YFILE_PREP,ILON,ILAT,YTITLE,YTIMEUNIT,.FALSE.)
!
!-------------------------------------------------------------------------------
! * Compute the mask of the run
!-------------------------------------------------------------------------------        
!
IF(ZGRID_RES > 0.09)THEN      
!        
  ILON_DEB = INT(ZLONMIN/ZGRID_RES) + ILON_G/2 + 1
  ILON_END = INT(ZLONMAX/ZGRID_RES) + ILON_G/2  
  ILAT_DEB = INT(ZLATMIN/ZGRID_RES) + ILAT_G/2 + 1
  ILAT_END = INT(ZLATMAX/ZGRID_RES) + ILAT_G/2
!  
  ALLOCATE(IGRCN (ILON_G,ILAT_G))
  ALLOCATE(INEXTX(ILON_G,ILAT_G))
  ALLOCATE(INEXTY(ILON_G,ILAT_G))
  ALLOCATE(ZWORK (ILON_G,ILAT_G))
!  
ELSE
!        
  ILON_DEB = 1
  ILON_END = ILON_G
  ILAT_DEB = 1
  ILAT_END = ILAT_G
!        
  ILON_DEB12 = INT(ZLONMIN/ZGRID_RES) + ILON_G12/2 + 1
  ILON_END12 = INT(ZLONMAX/ZGRID_RES) + ILON_G12/2  
  ILAT_DEB12 = INT(ZLATMIN/ZGRID_RES) + ILAT_G12/2 + 1
  ILAT_END12 = INT(ZLATMAX/ZGRID_RES) + ILAT_G12/2
!  
  ALLOCATE(IGRCN (ILON_G12,ILAT_G12))
  ALLOCATE(INEXTX(ILON_G12,ILAT_G12))
  ALLOCATE(INEXTY(ILON_G12,ILAT_G12))
  ALLOCATE(ZWORK (ILON_G12,ILAT_G12))
!  
ENDIF
!
ALLOCATE(ZREAD(ILON_G,ILAT_G))
!
!-------------------------------------------------------------------------------
! * Compute and Read TRIP parameter
!-------------------------------------------------------------------------------        
!
IGRCN =0
INEXTX=0
INEXTY=0
!
! * Basin ID
!
YVAR ='NUM_BAS'
CALL READ_TRIP(NLISTING,YFILE_READ,YVAR,ZREAD)
ZNUM_BAS(:,:) = ZREAD(ILON_DEB:ILON_END,ILAT_DEB:ILAT_END)
!
! * Drainage Area
!
YVAR ='DR_AREA'
CALL READ_TRIP(NLISTING,YFILE_READ,YVAR,ZREAD)
ZDR_AREA(:,:) = ZREAD(ILON_DEB:ILON_END,ILAT_DEB:ILAT_END)
!
! * Flow direction
!
YVAR ='FLOWDIR'
CALL READ_TRIP(NLISTING,YFILE_READ,YVAR,ZREAD)
ZGRCN(:,:) = ZREAD(ILON_DEB:ILON_END,ILAT_DEB:ILAT_END)
WHERE(ZREAD(:,:)==XUNDEF)ZREAD(:,:)=0.0
!
IF(ZGRID_RES > 0.09)THEN      
!
  IGRCN = INT(ZREAD)
!
! * Set the distance between grids with the meandering ratio
!
  CALL SETNEXT(ILON_G,ILAT_G,IGRCN,INEXTX,INEXTY)
!
  CALL SETLEN(ILON_G,ILAT_G,IGRCN,INEXTX,INEXTY,XRATMED,ZWORK)
  ZLEN(:,:) = ZWORK(ILON_DEB:ILON_END,ILAT_DEB:ILAT_END)
!
ELSE
!
  IGRCN(ILON_DEB12:ILON_END12,ILAT_DEB12:ILAT_END12) = INT(ZREAD)
!
! * Set the distance between grids with the meandering ratio
!
  CALL SETNEXT(ILON_G12,ILAT_G12,IGRCN,INEXTX,INEXTY)
!
  CALL SETLEN(ILON_G12,ILAT_G12,IGRCN,INEXTX,INEXTY,XRATMED,ZWORK)
  ZLEN(:,:) = ZWORK(ILON_DEB12:ILON_END12,ILAT_DEB12:ILAT_END12)
!
ENDIF
!
DEALLOCATE(IGRCN )
DEALLOCATE(INEXTX)
DEALLOCATE(INEXTY)
DEALLOCATE(ZWORK )
!
! * Domain test
!
ALLOCATE(INEXTX(ILON,ILAT))
ALLOCATE(INEXTY(ILON,ILAT))
!
WHERE(ZGRCN(:,:)<XUNDEF)
      TPG%NGRCN(:,:)=INT(ZGRCN(:,:))
      TPG%GMASK(:,:)=.TRUE.
ELSEWHERE
      TPG%NGRCN(:,:)=0
      TPG%GMASK(:,:)=.FALSE.
ENDWHERE
!
CALL SETNEXT(ILON,ILAT,TPG%NGRCN,INEXTX,INEXTY,LMASKLON,LMASKLAT)
!
! * Store some param
!
YVAR ='FLOWDIR'
ZGRCN(:,:)=REAL(TPG%NGRCN(:,:))
CALL WRITE_TRIP(NLISTING,YFILE_PARAM,YVAR,TPG%GMASK,ZGRCN)
YVAR ='RIVLEN'
CALL WRITE_TRIP(NLISTING,YFILE_PARAM,YVAR,TPG%GMASK,ZLEN,ODOUBLE=LDOUBLE)
YVAR ='NUM_BAS'
CALL WRITE_TRIP(NLISTING,YFILE_PARAM,YVAR,TPG%GMASK,ZNUM_BAS)
YVAR ='DR_AREA'
CALL WRITE_TRIP(NLISTING,YFILE_PARAM,YVAR,TPG%GMASK,ZDR_AREA)
!
DEALLOCATE(INEXTX)
DEALLOCATE(INEXTY)
DEALLOCATE(ZDR_AREA)
DEALLOCATE(ZNUM_BAS)
!
! * River sequence values read
!
YVAR ='RIVSEQ'
CALL READ_TRIP(NLISTING,YFILE_READ,YVAR,ZREAD)
ZSEQ(:,:) = ZREAD(ILON_DEB:ILON_END,ILAT_DEB:ILAT_END)
!
CALL WRITE_TRIP(NLISTING,YFILE_PARAM,YVAR,TPG%GMASK,ZSEQ)
!
! * Set area size
!
CALL SETAREA(ILAT,ZLATMIN,ZGRID_RES,TPG%XAREA)
!
! * Initial river storage
!
YVAR ='SURF_STO'
CALL READ_TRIP(NLISTING,YFILE_READ_INIT,YVAR,ZREAD)
TP%XSURF_STO(:,:) = ZREAD(ILON_DEB:ILON_END,ILAT_DEB:ILAT_END)
!        
CALL WRITE_TRIP(NLISTING,YFILE_PREP,YVAR,TPG%GMASK,TP%XSURF_STO,ODOUBLE=LDOUBLE)
!
! * Greenland and Antarctic masks
!
YVAR ='GREEN_ANT'
IF(ZGRID_RES > 0.09)THEN
  CALL READ_TRIP(NLISTING,YFILE_READ,YVAR,ZREAD)
ELSE
  ZREAD(:,:)=0.0
ENDIF
ZGREEN_ANT(:,:) = ZREAD(ILON_DEB:ILON_END,ILAT_DEB:ILAT_END)
CALL WRITE_TRIP(NLISTING,YFILE_PARAM,YVAR,TPG%GMASK,ZGREEN_ANT)
DO JLAT=1,ILAT
   DO JLON=1,ILON
      IF(ZREAD(JLON,JLAT)==2.0)THEN
          TPG%GMASK_ANT(JLON,JLAT)=.TRUE.
      ELSEIF(ZREAD(JLON,JLAT)==1.0)THEN
          TPG%GMASK_GRE(JLON,JLAT)=.TRUE.
      ENDIF
   ENDDO
ENDDO
!
DEALLOCATE(ZLON)
DEALLOCATE(ZLAT)
DEALLOCATE(ZGREEN_ANT)
!
! * Variable velocity scheme parameters
!
IF(CVIT == 'VAR')THEN
!
  YVAR ='N_RIV'
  CALL READ_TRIP(NLISTING,YFILE_READ,YVAR,ZREAD)
  TP%XN(:,:) = ZREAD(ILON_DEB:ILON_END,ILAT_DEB:ILAT_END)
  CALL WRITE_TRIP(NLISTING,YFILE_PARAM,YVAR,TPG%GMASK,TP%XN)
!
  YVAR ='WIDTHRIV'
  CALL READ_TRIP(NLISTING,YFILE_READ,YVAR,ZREAD)
  TP%XWIDTH(:,:) = ZREAD(ILON_DEB:ILON_END,ILAT_DEB:ILAT_END)
  CALL WRITE_TRIP(NLISTING,YFILE_PARAM,YVAR,TPG%GMASK,TP%XWIDTH)
!
  YVAR ='SLOPERIV'
  CALL READ_TRIP(NLISTING,YFILE_READ,YVAR,ZREAD)
  TP%XSLOPEBED(:,:) = MAX(ZREAD(ILON_DEB:ILON_END,ILAT_DEB:ILAT_END),1.E-5)
  CALL WRITE_TRIP(NLISTING,YFILE_PARAM,YVAR,TPG%GMASK,TP%XSLOPEBED,ODOUBLE=LDOUBLE)  
!  
ENDIF 
!
! * Groundwater parameters
!
IF(CGROUNDW/='DEF')THEN
  TPG%GMASK_GW(:,:)=TPG%GMASK(:,:)
ENDIF
!
IF(CGROUNDW=='CST')THEN
!
  YVAR ='GROUND_STO'
  CALL READ_TRIP(NLISTING,YFILE_READ_INIT,YVAR,ZREAD)
  TP%XGROUND_STO(:,:) = ZREAD(ILON_DEB:ILON_END,ILAT_DEB:ILAT_END)
!  
  TP%XTAUG(:,:)=XTAUG_UNIF
  WHERE(TPG%GMASK_ANT(:,:).OR.TPG%GMASK_GRE(:,:))
        TP%XTAUG      (:,:)=XUNDEF
        TPG%GMASK_GW  (:,:)=.FALSE.
        TP%XGROUND_STO(:,:)=0.0
  ENDWHERE
!          
  YVAR ='TAUG'
  CALL WRITE_TRIP(NLISTING,YFILE_PARAM,YVAR,TPG%GMASK_GW,TP%XTAUG)
!  
  YVAR ='GROUND_STO'
  CALL WRITE_TRIP(NLISTING,YFILE_PREP,YVAR,TPG%GMASK_GW,TP%XGROUND_STO,ODOUBLE=LDOUBLE)
!
ELSEIF(CGROUNDW=='DIF')THEN
!
  YVAR ='NUM_AQUI'
  CALL READ_TRIP(NLISTING,YFILE_READ,YVAR,ZREAD)
  TP%XNUM_AQUI(:,:) = ZREAD(ILON_DEB:ILON_END,ILAT_DEB:ILAT_END)
!  
  WHERE(TP%XNUM_AQUI(:,:)==XUNDEF)
       TPG%GMASK_GW(:,:)=.FALSE.
  ENDWHERE
!  
  CALL WRITE_TRIP(NLISTING,YFILE_PARAM,YVAR,TPG%GMASK_GW,TP%XNUM_AQUI)  
!
  IF(ZGRID_RES > 0.09)THEN
    ZSEQMAX=5.0
  ELSE
    ZSEQMAX=10.0
  ENDIF
  TP%XTAUG(:,:)=XTAUG_DOWN+(XTAUG_UP-XTAUG_DOWN)*(ZSEQMAX-MIN(ZSEQMAX,ZSEQ(:,:)))/(ZSEQMAX-1.0)
!  
  YVAR ='TAUG'
  CALL WRITE_TRIP(NLISTING,YFILE_PARAM,YVAR,TPG%GMASK_GW,TP%XTAUG)
!
  YVAR ='WEFF'
  CALL READ_TRIP(NLISTING,YFILE_READ,YVAR,ZREAD)
  TP%XWEFF(:,:) = ZREAD(ILON_DEB:ILON_END,ILAT_DEB:ILAT_END)
  CALL WRITE_TRIP(NLISTING,YFILE_PARAM,YVAR,TPG%GMASK_GW,TP%XWEFF)
!
  YVAR ='TRANS'
  CALL READ_TRIP(NLISTING,YFILE_READ,YVAR,ZREAD)
  TP%XTRANS(:,:) = ZREAD(ILON_DEB:ILON_END,ILAT_DEB:ILAT_END)
  CALL WRITE_TRIP(NLISTING,YFILE_PARAM,YVAR,TPG%GMASK_GW,TP%XTRANS)
!
  YVAR ='TOPO_RIV'  
  CALL READ_TRIP(NLISTING,YFILE_READ,YVAR,ZREAD)  
  TP%XTOPO_RIV(:,:) = ZREAD(ILON_DEB:ILON_END,ILAT_DEB:ILAT_END)
  CALL WRITE_TRIP(NLISTING,YFILE_PARAM,YVAR,TPG%GMASK_GW,TP%XTOPO_RIV)  
!
  YVAR ='HGROUND'   
  CALL READ_TRIP(NLISTING,YFILE_READ_INIT,YVAR,ZREAD)   
  TP%XHGROUND(:,:) = ZREAD(ILON_DEB:ILON_END,ILAT_DEB:ILAT_END)
  CALL WRITE_TRIP(NLISTING,YFILE_PREP,YVAR,TPG%GMASK_GW,TP%XHGROUND,ODOUBLE=LDOUBLE)
!
  ALLOCATE(ZREAD3D(ILON_G,ILAT_G,NDIMTAB))
!
  ALLOCATE(TP%XTABGW_F (ILON,ILAT,NDIMTAB))      
  ALLOCATE(TP%XTABGW_H (ILON,ILAT,NDIMTAB))      
!  
  TP%XTABGW_F(:,:,:)= XUNDEF
  TP%XTABGW_H(:,:,:)= XUNDEF
!
  YVAR ='TABGW_F'
  CALL READ_TRIP(NLISTING,YFILE_GW_READ,YVAR,ZREAD3D(:,ILATF:ILAT_G,:))
  TP%XTABGW_F(:,:,:) = ZREAD3D(ILON_DEB:ILON_END,ILAT_DEB:ILAT_END,:)
  CALL WRITE_TRIP(NLISTING,YFILE_PARAM,YVAR,TPG%GMASK_GW,TP%XTABGW_F)
!
  YVAR ='TABGW_H'
  CALL READ_TRIP(NLISTING,YFILE_GW_READ,YVAR,ZREAD3D(:,ILATF:ILAT_G,:))
  TP%XTABGW_H(:,:,:) = ZREAD3D(ILON_DEB:ILON_END,ILAT_DEB:ILAT_END,:)
  CALL WRITE_TRIP(NLISTING,YFILE_PARAM,YVAR,TPG%GMASK_GW,TP%XTABGW_H)
!
  DEALLOCATE(ZREAD3D)
!
ENDIF
!
! * Groundwater
!
IF (LFLOOD.OR.CGROUNDW == 'DIF') THEN
!
  YVAR ='RIVDEPTH'     
  CALL READ_TRIP(NLISTING,YFILE_READ,YVAR,ZREAD)
  TP%XHC_BED(:,:) = ZREAD(ILON_DEB:ILON_END,ILAT_DEB:ILAT_END)
  WHERE(TP%XHC_BED(:,:)==0.0)
        TP%XHC_BED(:,:)=XUNDEF
  ENDWHERE
  CALL WRITE_TRIP(NLISTING,YFILE_PARAM,YVAR,TPG%GMASK,TP%XHC_BED)
!
ENDIF  
!
! * Calculate floodplains parameters
!
IF(LFLOOD)THEN
!
  YVAR ='NFLOOD'
  CALL READ_TRIP(NLISTING,YFILE_READ,YVAR,ZREAD)
  TP%XN_FLOOD(:,:) = ZREAD(ILON_DEB:ILON_END,ILAT_DEB:ILAT_END)
!
  ALLOCATE(ZREAD3D(ILON_G,ILAT_G,NDIMTAB))
!  
  ALLOCATE(TP%XTAB_F (ILON,ILAT,NDIMTAB))      
  ALLOCATE(TP%XTAB_H (ILON,ILAT,NDIMTAB))      
  ALLOCATE(TP%XTAB_VF(ILON,ILAT,NDIMTAB))  
!  
  TP%XTAB_F (:,:,:)= XUNDEF
  TP%XTAB_H (:,:,:)= XUNDEF
  TP%XTAB_VF(:,:,:)= XUNDEF
!
  YVAR ='TABF'
  CALL READ_TRIP(NLISTING,YFILE_FLOOD_READ,YVAR,ZREAD3D(:,ILATF:ILAT_G,:))
  TP%XTAB_F(:,:,:) = ZREAD3D(ILON_DEB:ILON_END,ILAT_DEB:ILAT_END,:)
  YVAR ='TABH'
  CALL READ_TRIP(NLISTING,YFILE_FLOOD_READ,YVAR,ZREAD3D(:,ILATF:ILAT_G,:))
  TP%XTAB_H(:,:,:) = ZREAD3D(ILON_DEB:ILON_END,ILAT_DEB:ILAT_END,:)
  YVAR ='TABVF'
  CALL READ_TRIP(NLISTING,YFILE_FLOOD_READ,YVAR,ZREAD3D(:,ILATF:ILAT_G,:))
  TP%XTAB_VF(:,:,:) = ZREAD3D(ILON_DEB:ILON_END,ILAT_DEB:ILAT_END,:)  
!
  DEALLOCATE(ZREAD3D)
!  
  DO JLAT=1,ILAT
     DO JLON=1,ILON
!
        WHERE(TP%XTAB_VF(JLON,JLAT,:)/=XUNDEF)    
              TP%XTAB_VF(JLON,JLAT,:)=TP%XTAB_VF(JLON,JLAT,:)*TPG%XAREA(JLON,JLAT)*XRHOLW
        ENDWHERE
!
        IF(TPG%GMASK(JLON,JLAT).AND.TP%XTAB_F(JLON,JLAT,2)>=0.95)THEN                  
          TP%XTAB_F (JLON,JLAT,:)= XUNDEF
          TP%XTAB_H (JLON,JLAT,:)= XUNDEF
          TP%XTAB_VF(JLON,JLAT,:)= XUNDEF
          TP%XN_FLOOD(JLON,JLAT) = XUNDEF
        ENDIF
!        
        IF(TP%XHC_BED(JLON,JLAT)==XUNDEF)THEN
          TP%XTAB_F  (JLON,JLAT,:) = XUNDEF
          TP%XTAB_H  (JLON,JLAT,:) = XUNDEF
          TP%XTAB_VF (JLON,JLAT,:) = XUNDEF
          TP%XN_FLOOD(JLON,JLAT)   = XUNDEF
        ENDIF
!        
     ENDDO
  ENDDO
!
  WHERE(TP%XTAB_H(:,:,1)==XUNDEF)
        TP%XN_FLOOD(:,:)=XUNDEF
  ENDWHERE
!  
  YVAR ='NFLOOD'
  CALL WRITE_TRIP(NLISTING,YFILE_PARAM,YVAR,TPG%GMASK,TP%XN_FLOOD)
!
  YVAR ='TABF'
  CALL WRITE_TRIP(NLISTING,YFILE_PARAM,YVAR,TPG%GMASK,TP%XTAB_F)
  YVAR ='TABH'
  CALL WRITE_TRIP(NLISTING,YFILE_PARAM,YVAR,TPG%GMASK,TP%XTAB_H)  
  YVAR ='TABVF'
  CALL WRITE_TRIP(NLISTING,YFILE_PARAM,YVAR,TPG%GMASK,TP%XTAB_VF)
!
! Floodplains initial variables
!
  YVAR ='FLOOD_STO'
  CALL READ_TRIP(NLISTING,YFILE_READ_INIT,YVAR,ZREAD)
  TP%XFLOOD_STO(:,:) = ZREAD(ILON_DEB:ILON_END,ILAT_DEB:ILAT_END)
  CALL WRITE_TRIP(NLISTING,YFILE_PREP,YVAR,TPG%GMASK,TP%XFLOOD_STO,ODOUBLE=LDOUBLE)          
!
  YVAR ='FFLOOD_T'
  CALL READ_TRIP(NLISTING,YFILE_READ_INIT,YVAR,ZREAD)
  TP%XFFLOOD(:,:) = ZREAD(ILON_DEB:ILON_END,ILAT_DEB:ILAT_END)
  YVAR ='FFLOOD'
  CALL WRITE_TRIP(NLISTING,YFILE_PREP,YVAR,TPG%GMASK,TP%XFFLOOD,ODOUBLE=LDOUBLE)          
!
  YVAR ='HFLOOD_T'
  CALL READ_TRIP(NLISTING,YFILE_READ_INIT,YVAR,ZREAD)
  TP%XHFLOOD(:,:) = ZREAD(ILON_DEB:ILON_END,ILAT_DEB:ILAT_END)
  YVAR ='HFLOOD'
  CALL WRITE_TRIP(NLISTING,YFILE_PREP,YVAR,TPG%GMASK,TP%XHFLOOD,ODOUBLE=LDOUBLE)          
!  
ENDIF
!
DEALLOCATE(ZREAD)
!
!-------------------------------------------------------------------------------
! * Store current start date
!-------------------------------------------------------------------------------
!
CALL WRITE_TRIP_DATE(NLISTING,YFILE_PREP,KYEAR,KMONTH,KDAY,PTIME)
!
!-------------------------------------------------------------------------------
! * END
!-------------------------------------------------------------------------------
!
WRITE(NLISTING,*)''
WRITE(NLISTING,*)'        END PREP TRIP            '
WRITE(NLISTING,*)''
IF (LHOOK) CALL DR_HOOK('PREP_TRIP_RUN',1,ZHOOK_HANDLE)
!
!-------------------------------------------------------------------------------
END SUBROUTINE PREP_TRIP_RUN
