!     #########
      SUBROUTINE TRIP_DIAG_RUN(KLISTING,KLON,KLAT,PRUNTIME)  
!     #####################################################
!
!!****  *TRIP_DIAG_RUN*  
!!
!!    PURPOSE
!!    -------
!
!     TRIP river routing run mean outputs.
!     
!!      
!!    AUTHOR
!!    ------
!!      B. Decharme
!!
!!    MODIFICATIONS
!!    -------------
!!      Original    28/05/05 
!-------------------------------------------------------------------------------
!
!*       0.     DECLARATIONS
!               ------------
!
USE MODN_TRIP,       ONLY : CGROUNDW, CVIT, LFLOOD
USE MODN_TRIP_RUN,   ONLY : LDIAG_MISC
USE MODD_TRIP_OASIS, ONLY : LCPL_LAND
!                           
USE MODD_TRIP_DIAG,  ONLY : TDIAG_RUN
USE MODD_TRIP_GRID,  ONLY : TGRID
!
USE MODE_RW_TRIP
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE
!
!*      0.1    declarations of arguments
!
INTEGER, INTENT(IN)             :: KLISTING
INTEGER, INTENT(IN)             :: KLON
INTEGER, INTENT(IN)             :: KLAT
!
REAL, INTENT(IN)                :: PRUNTIME 
!
!*      0.2    declarations of local variables
!
CHARACTER(LEN=18), PARAMETER         :: YRUN         ='TRIP_DIAG_RUN.nc'
CHARACTER(LEN=50)                    :: YFILE
CHARACTER(LEN=10)                    :: YVNAME
!
REAL,   DIMENSION(KLON,KLAT)         :: ZWRITE
LOGICAL,DIMENSION(KLON,KLAT)         :: LMASK
LOGICAL,DIMENSION(KLON,KLAT)         :: LMASK_GW
!
INTEGER :: ITNUM, ITVAL
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
!-------------------------------------------------------------------------------
!
IF (LHOOK) CALL DR_HOOK('TRIP_DIAG_RUN',0,ZHOOK_HANDLE)
!
! * Trip mask
!
LMASK(:,:) = TGRID%GMASK(:,:)
!
! * Groundwater specific mask
!
IF(CGROUNDW/='DEF')THEN
  LMASK_GW(:,:) = TGRID%GMASK_GW(:,:)        
ENDIF
!
! * Recup diag file
!
ITNUM = 1
ITVAL = 0
YFILE =YRUN
!
! * Store output in diag file
!
YVNAME = 'SURF_STO'
ZWRITE = TDIAG_RUN%XSURF_STO / PRUNTIME
CALL WRITE_TRIP(KLISTING,YFILE,YVNAME,LMASK,ZWRITE,ITNUM,ITVAL)        
!                
YVNAME = 'QDIS'
ZWRITE = TDIAG_RUN%XQDIS / PRUNTIME 
CALL WRITE_TRIP(KLISTING,YFILE,YVNAME,LMASK,ZWRITE,ITNUM,ITVAL)        
!
IF(LDIAG_MISC)THEN                
  YVNAME = 'QSIN'
  ZWRITE = TDIAG_RUN%XQIN / PRUNTIME
  CALL WRITE_TRIP(KLISTING,YFILE,YVNAME,LMASK,ZWRITE,ITNUM,ITVAL) 
ENDIF
!
IF(LCPL_LAND.AND.LDIAG_MISC)THEN                
  YVNAME = 'RUNOFF'
  ZWRITE = TDIAG_RUN%XRUNOFF !mm of water
  CALL WRITE_TRIP(KLISTING,YFILE,YVNAME,LMASK,ZWRITE,ITNUM,ITVAL)
  YVNAME = 'DRAIN'
  ZWRITE = TDIAG_RUN%XDRAIN !mm of water
  CALL WRITE_TRIP(KLISTING,YFILE,YVNAME,LMASK,ZWRITE,ITNUM,ITVAL)
ENDIF
!
IF(CGROUNDW/='DEF')THEN
  YVNAME = 'QGF'
  ZWRITE = TDIAG_RUN%XQGF / PRUNTIME 
  CALL WRITE_TRIP(KLISTING,YFILE,YVNAME,LMASK_GW,ZWRITE,ITNUM,ITVAL)        
ENDIF
!
IF(CGROUNDW=='CST')THEN                
!
  YVNAME = 'GROUND_STO'
  ZWRITE = TDIAG_RUN%XGROUND_STO / PRUNTIME
  CALL WRITE_TRIP(KLISTING,YFILE,YVNAME,LMASK,ZWRITE,ITNUM,ITVAL)        
!
ELSEIF(CGROUNDW=='DIF')THEN
!
  YVNAME = 'HGROUND'
  ZWRITE = TDIAG_RUN%XHGROUND / PRUNTIME
  CALL WRITE_TRIP(KLISTING,YFILE,YVNAME,LMASK_GW,ZWRITE,ITNUM,ITVAL)
!
  YVNAME = 'FWTD'
  ZWRITE = TDIAG_RUN%XFWTD / PRUNTIME
  CALL WRITE_TRIP(KLISTING,YFILE,YVNAME,LMASK_GW,ZWRITE,ITNUM,ITVAL)
!
  YVNAME = 'WTD'
  ZWRITE = TDIAG_RUN%XWTD / PRUNTIME
  CALL WRITE_TRIP(KLISTING,YFILE,YVNAME,LMASK_GW,ZWRITE,ITNUM,ITVAL)    
!
  IF(LDIAG_MISC)THEN                
!
    YVNAME = 'WTDRIV'
    ZWRITE = TDIAG_RUN%XWTDRIV / PRUNTIME
    CALL WRITE_TRIP(KLISTING,YFILE,YVNAME,LMASK_GW,ZWRITE,ITNUM,ITVAL)
!
    YVNAME = 'WTDELEV'
    ZWRITE = TDIAG_RUN%XWTDELEV / PRUNTIME
    CALL WRITE_TRIP(KLISTING,YFILE,YVNAME,LMASK_GW,ZWRITE,ITNUM,ITVAL)
!
    YVNAME = 'QGCELL'
    ZWRITE = TDIAG_RUN%XQGCELL / PRUNTIME
    CALL WRITE_TRIP(KLISTING,YFILE,YVNAME,LMASK_GW,ZWRITE,ITNUM,ITVAL)
!
    YVNAME = 'HGHRIV'
    ZWRITE = TDIAG_RUN%XHGHS / PRUNTIME
    CALL WRITE_TRIP(KLISTING,YFILE,YVNAME,LMASK_GW,ZWRITE,ITNUM,ITVAL)
!
  ENDIF
!
ENDIF
!
IF(CVIT=='VAR')THEN
!
  YVNAME = 'VEL'
  ZWRITE = TDIAG_RUN%XVEL / PRUNTIME
  CALL WRITE_TRIP(KLISTING,YFILE,YVNAME,LMASK,ZWRITE,ITNUM,ITVAL)        
!
  YVNAME = 'HSTREAM'
  ZWRITE = TDIAG_RUN%XHS / PRUNTIME
  CALL WRITE_TRIP(KLISTING,YFILE,YVNAME,LMASK,ZWRITE,ITNUM,ITVAL)        
!
ENDIF
!
IF(LFLOOD)THEN
!
  YVNAME = 'FFLOOD'
  ZWRITE = TDIAG_RUN%XFF / PRUNTIME
  CALL WRITE_TRIP(KLISTING,YFILE,YVNAME,LMASK,ZWRITE,ITNUM,ITVAL)        
!
  YVNAME = 'FLOOD_STO'
  ZWRITE = TDIAG_RUN%XFLOOD_STO / PRUNTIME
  CALL WRITE_TRIP(KLISTING,YFILE,YVNAME,LMASK,ZWRITE,ITNUM,ITVAL)        
!
  YVNAME = 'HFLOOD'
  ZWRITE = TDIAG_RUN%XHF / PRUNTIME
  CALL WRITE_TRIP(KLISTING,YFILE,YVNAME,LMASK,ZWRITE,ITNUM,ITVAL)        
!
  IF(LDIAG_MISC)THEN
!
    YVNAME = 'FSOURCE'
    ZWRITE = TDIAG_RUN%XSOURCE !mm of water
    CALL WRITE_TRIP(KLISTING,YFILE,YVNAME,LMASK,ZWRITE,ITNUM,ITVAL)
!
    YVNAME = 'QFR'
    ZWRITE = TDIAG_RUN%XQFR / PRUNTIME
    CALL WRITE_TRIP(KLISTING,YFILE,YVNAME,LMASK,ZWRITE,ITNUM,ITVAL)        
!                
    YVNAME = 'QRF'
    ZWRITE = TDIAG_RUN%XQRF / PRUNTIME
    CALL WRITE_TRIP(KLISTING,YFILE,YVNAME,LMASK,ZWRITE,ITNUM,ITVAL)        
!
    YVNAME = 'VFIN'
    ZWRITE = TDIAG_RUN%XVFIN / PRUNTIME
    CALL WRITE_TRIP(KLISTING,YFILE,YVNAME,LMASK,ZWRITE,ITNUM,ITVAL)        
!
    YVNAME = 'VFOUT'
    ZWRITE = TDIAG_RUN%XVFOUT / PRUNTIME
    CALL WRITE_TRIP(KLISTING,YFILE,YVNAME,LMASK,ZWRITE,ITNUM,ITVAL)        
!
    YVNAME = 'HSF'
    ZWRITE = TDIAG_RUN%XHSF / PRUNTIME
    CALL WRITE_TRIP(KLISTING,YFILE,YVNAME,LMASK,ZWRITE,ITNUM,ITVAL)        
!
    YVNAME = 'WF'
    ZWRITE = TDIAG_RUN%XWF / PRUNTIME
    CALL WRITE_TRIP(KLISTING,YFILE,YVNAME,LMASK,ZWRITE,ITNUM,ITVAL)        
!
    YVNAME = 'LF'
    ZWRITE = TDIAG_RUN%XLF / PRUNTIME
    CALL WRITE_TRIP(KLISTING,YFILE,YVNAME,LMASK,ZWRITE,ITNUM,ITVAL)       
!
  ENDIF       
!
ENDIF
!
IF (LHOOK) CALL DR_HOOK('TRIP_DIAG_RUN',1,ZHOOK_HANDLE)
!
!-------------------------------------------------------------------------------
END SUBROUTINE TRIP_DIAG_RUN
