!     #########
      SUBROUTINE TRIP_DIAG_WRITE (TPDG, TPG, &
                                  KLISTING,KLON,KLAT,KDIAG,PTSTEP_DIAG,OXIOS)  
!     ############################################################
!
!!****  *TRIP_DIAG_WRITE*  
!!
!!    PURPOSE
!!    -------
!
!     TRIP river routing outputs.
!     
!!      
!!    AUTHOR
!!    ------
!!      B. Decharme
!!
!!    MODIFICATIONS
!!    -------------
!!      Original    28/05/05 
!!      S.Sénési    08/11/16 : interface to XIOS
!-------------------------------------------------------------------------------
!
!*       0.     DECLARATIONS
!               ------------
!
!
USE MODD_TRIP_DIAG, ONLY : TRIP_DIAG_t
USE MODD_TRIP_GRID, ONLY : TRIP_GRID_t
!
USE MODN_TRIP,       ONLY : CGROUNDW, CVIT, LFLOOD
USE MODN_TRIP_RUN,   ONLY : LDIAG_MISC
USE MODD_TRIP_OASIS, ONLY : LCPL_LAND, LCPL_FLOOD
!
USE MODD_TRIP_PAR,   ONLY : XTIME_DIAG
!
#ifdef WXIOS
use XIOS
#endif
!
USE MODE_RW_TRIP
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE
!
!*      0.1    declarations of arguments
!
!
TYPE(TRIP_DIAG_t), INTENT(INOUT) :: TPDG
TYPE(TRIP_GRID_t), INTENT(INOUT) :: TPG
!
INTEGER, INTENT(IN)             :: KLISTING
INTEGER, INTENT(IN)             :: KLON
INTEGER, INTENT(IN)             :: KLAT
INTEGER, INTENT(IN)             :: KDIAG
REAL,    INTENT(IN)             :: PTSTEP_DIAG
LOGICAL, INTENT(IN)             :: OXIOS
!
!*      0.2    declarations of local variables
!
 CHARACTER(LEN=19), PARAMETER         :: YDIAG  = 'TRIP_DIAG.nc'
 CHARACTER(LEN=50)                    :: YFILE
 CHARACTER(LEN=50)                    :: YVNAME
!
REAL,   DIMENSION(KLON,KLAT)         :: ZWRITE
REAL,   DIMENSION(KLON,KLAT)         :: ZWTD
LOGICAL,DIMENSION(KLON,KLAT)         :: LMASK
LOGICAL,DIMENSION(KLON,KLAT)         :: LMASK_GW
LOGICAL,DIMENSION(KLON,KLAT)         :: LMASK_FLD
!
INTEGER :: ITNUM, ITVAL
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
!-------------------------------------------------------------------------------
!
IF (LHOOK) CALL DR_HOOK('TRIP_DIAG_WRITE',0,ZHOOK_HANDLE)
!
! * Trip mask
!
LMASK(:,:) = TPG%GMASK(:,:)
!
! * Groundwater specific mask
!
IF(CGROUNDW/='DEF')THEN
  LMASK_GW(:,:) = TPG%GMASK_GW(:,:)        
ENDIF
!
IF(LFLOOD)THEN
  LMASK_FLD(:,:) = TPG%GMASK_FLD(:,:)
ENDIF
!
!-------------------------------------------------------------------------------
!outputs attributes
!-------------------------------------------------------------------------------
!
! * Recup diag file
!
YFILE =YDIAG
!
! * Time attribut
!
ITNUM = KDIAG
!
IF (OXIOS) THEN
#ifdef WXIOS
  CALL XIOS_UPDATE_CALENDAR(KDIAG)
#endif
  ITVAL = 0
ELSE
  ITVAL = (KDIAG-1)*INT(PTSTEP_DIAG/XTIME_DIAG)
ENDIF
!
!-------------------------------------------------------------------------------
! * River mass, fluxes, and velocity
!-------------------------------------------------------------------------------
!
YVNAME = 'rivw'
ZWRITE = TPDG%TDIAG%XSURF_STO / PTSTEP_DIAG
CALL WRITE_TRIP(KLISTING,YFILE,YVNAME,LMASK,ZWRITE,ITNUM,ITVAL,OXIOS=OXIOS)   
CALL CUM_DIAG(TPDG%TDIAG%XSURF_STO,TPDG%TDIAG_RUN%XSURF_STO,LMASK)
!      
!        
YVNAME = 'rivdis'
ZWRITE = TPDG%TDIAG%XQDIS / PTSTEP_DIAG
CALL WRITE_TRIP(KLISTING,YFILE,YVNAME,LMASK,ZWRITE,ITNUM,ITVAL,OXIOS=OXIOS) 
CALL CUM_DIAG(TPDG%TDIAG%XQDIS,TPDG%TDIAG_RUN%XQDIS,LMASK)
!
YVNAME = 'rivin'
ZWRITE = TPDG%TDIAG%XQIN / PTSTEP_DIAG
CALL WRITE_TRIP(KLISTING,YFILE,YVNAME,LMASK,ZWRITE,ITNUM,ITVAL,OXIOS=OXIOS)
CALL CUM_DIAG(TPDG%TDIAG%XQIN,TPDG%TDIAG_RUN%XQIN,LMASK)
!
IF(CVIT=='VAR')THEN
!
  YVNAME = 'rivh'
  ZWRITE = TPDG%TDIAG%XHS / PTSTEP_DIAG
  CALL WRITE_TRIP(KLISTING,YFILE,YVNAME,TPG%GMASK_VEL,ZWRITE,ITNUM,ITVAL,OXIOS=OXIOS) 
  CALL CUM_DIAG(TPDG%TDIAG%XHS,TPDG%TDIAG_RUN%XHS,TPG%GMASK_VEL)
!
  YVNAME = 'rivv'
  ZWRITE = TPDG%TDIAG%XVEL / PTSTEP_DIAG
  CALL WRITE_TRIP(KLISTING,YFILE,YVNAME,LMASK,ZWRITE,ITNUM,ITVAL,OXIOS=OXIOS)
  CALL CUM_DIAG(TPDG%TDIAG%XVEL,TPDG%TDIAG_RUN%XVEL,LMASK)
!
ENDIF
!
!-------------------------------------------------------------------------------
! * Groundwater mass, fluxes, and depth
!-------------------------------------------------------------------------------
!
IF(CGROUNDW/='DEF')THEN
!          
  YVNAME = 'gw'
  ZWRITE = TPDG%TDIAG%XGROUND_STO / PTSTEP_DIAG
  CALL WRITE_TRIP(KLISTING,YFILE,YVNAME,LMASK_GW,ZWRITE,ITNUM,ITVAL,OXIOS=OXIOS) 
  CALL CUM_DIAG(TPDG%TDIAG%XGROUND_STO,TPDG%TDIAG_RUN%XGROUND_STO,LMASK_GW)
!
  YVNAME = 'gwToriv'
  ZWRITE = TPDG%TDIAG%XQGF / PTSTEP_DIAG 
  CALL WRITE_TRIP(KLISTING,YFILE,YVNAME,LMASK_GW,ZWRITE,ITNUM,ITVAL,OXIOS=OXIOS)
  CALL CUM_DIAG(TPDG%TDIAG%XQGF,TPDG%TDIAG_RUN%XQGF,LMASK_GW) 
!
ENDIF
!
!
IF(CGROUNDW=='DIF')THEN
!
  YVNAME = 'gwh'
  ZWRITE = TPDG%TDIAG%XHGROUND / PTSTEP_DIAG
  CALL WRITE_TRIP(KLISTING,YFILE,YVNAME,LMASK_GW,ZWRITE,ITNUM,ITVAL,OXIOS=OXIOS)
  CALL CUM_DIAG(TPDG%TDIAG%XHGROUND,TPDG%TDIAG_RUN%XHGROUND,LMASK_GW)
!       
  YVNAME = 'wtd'
  ZWTD   = MAX(0.0,TPDG%TDIAG%XWTD)
  ZWRITE = ZWTD / PTSTEP_DIAG 
  CALL WRITE_TRIP(KLISTING,YFILE,YVNAME,LMASK_GW,ZWRITE,ITNUM,ITVAL,OXIOS=OXIOS)
  CALL CUM_DIAG(ZWTD,TPDG%TDIAG_RUN%XWTD,LMASK_GW)
  TPDG%TDIAG%XWTD(:,:)=0.0
!
ENDIF
!
!-------------------------------------------------------------------------------
! * Floodplains
!-------------------------------------------------------------------------------
!
IF(LFLOOD)THEN
!
  YVNAME = 'fldw'
  ZWRITE = TPDG%TDIAG%XFLOOD_STO / PTSTEP_DIAG
  CALL WRITE_TRIP(KLISTING,YFILE,YVNAME,LMASK,ZWRITE,ITNUM,ITVAL,OXIOS=OXIOS)   
  CALL CUM_DIAG(TPDG%TDIAG%XFLOOD_STO,TPDG%TDIAG_RUN%XFLOOD_STO,LMASK)
!
  YVNAME = 'fldf'
  ZWRITE = TPDG%TDIAG%XFF / PTSTEP_DIAG
  CALL WRITE_TRIP(KLISTING,YFILE,YVNAME,LMASK,ZWRITE,ITNUM,ITVAL,OXIOS=OXIOS)   
  CALL CUM_DIAG(TPDG%TDIAG%XFF,TPDG%TDIAG_RUN%XFF,LMASK)
!
  YVNAME = 'fldh'
  ZWRITE = TPDG%TDIAG%XHF / PTSTEP_DIAG
  CALL WRITE_TRIP(KLISTING,YFILE,YVNAME,LMASK,ZWRITE,ITNUM,ITVAL,OXIOS=OXIOS)  
  CALL CUM_DIAG(TPDG%TDIAG%XHF,TPDG%TDIAG_RUN%XHF,LMASK)
!
ENDIF
!
!-------------------------------------------------------------------------------
! * Forcing variables can be used to force TRIP offline
!-------------------------------------------------------------------------------
!
IF(LCPL_LAND)THEN                
!  
  YVNAME = 'RUNOFF'
  ZWRITE = TPDG%TDIAG%XRUNOFF !mm of water
  CALL WRITE_TRIP(KLISTING,YFILE,YVNAME,LMASK,ZWRITE,ITNUM,ITVAL,OXIOS=OXIOS)
  CALL CUM_DIAG(TPDG%TDIAG%XRUNOFF,TPDG%TDIAG_RUN%XRUNOFF,LMASK)
!
! 
  YVNAME = 'DRAIN'
  ZWRITE = TPDG%TDIAG%XDRAIN !mm of water
  CALL WRITE_TRIP(KLISTING,YFILE,YVNAME,LMASK,ZWRITE,ITNUM,ITVAL,OXIOS=OXIOS)
  CALL CUM_DIAG(TPDG%TDIAG%XDRAIN,TPDG%TDIAG_RUN%XDRAIN,LMASK)
!
ENDIF
!
!
IF(LCPL_FLOOD)THEN
  YVNAME = 'FSOURCE'
  ZWRITE = TPDG%TDIAG%XSOURCE !mm of water
  CALL WRITE_TRIP(KLISTING,YFILE,YVNAME,LMASK,ZWRITE,ITNUM,ITVAL,OXIOS=OXIOS) 
  CALL CUM_DIAG(TPDG%TDIAG%XSOURCE,TPDG%TDIAG_RUN%XSOURCE,LMASK)
ENDIF
!
!-------------------------------------------------------------------------------
! * MISC fields
!-------------------------------------------------------------------------------
!
IF(LDIAG_MISC)THEN
!
  IF(CGROUNDW=='DIF')THEN      
!     
    YVNAME = 'gwdf'
    ZWRITE = TPDG%TDIAG%XFWTD / PTSTEP_DIAG
    CALL WRITE_TRIP(KLISTING,YFILE,YVNAME,LMASK_GW,ZWRITE,ITNUM,ITVAL,OXIOS=OXIOS)  
    CALL CUM_DIAG(TPDG%TDIAG%XFWTD,TPDG%TDIAG_RUN%XFWTD,LMASK_GW)
!   
    YVNAME = 'gwfTocell'
    ZWRITE = TPDG%TDIAG%XQGCELL / PTSTEP_DIAG 
    CALL WRITE_TRIP(KLISTING,YFILE,YVNAME,LMASK_GW,ZWRITE,ITNUM,ITVAL,OXIOS=OXIOS)
    CALL CUM_DIAG(TPDG%TDIAG%XQGCELL,TPDG%TDIAG_RUN%XQGCELL,LMASK_GW)
!       
    YVNAME = 'gwh_less_rivh'
    ZWRITE = TPDG%TDIAG%XHGHS / PTSTEP_DIAG
    CALL WRITE_TRIP(KLISTING,YFILE,YVNAME,LMASK_GW,ZWRITE,ITNUM,ITVAL,OXIOS=OXIOS)
    CALL CUM_DIAG(TPDG%TDIAG%XHGHS,TPDG%TDIAG_RUN%XHGHS,LMASK_GW)
!
  ENDIF
! 
  IF(LFLOOD)THEN
!
    YVNAME = 'fldh_less_rivh'
    ZWRITE = TPDG%TDIAG%XHSF / PTSTEP_DIAG
    CALL WRITE_TRIP(KLISTING,YFILE,YVNAME,LMASK_FLD,ZWRITE,ITNUM,ITVAL,OXIOS=OXIOS)
    CALL CUM_DIAG(TPDG%TDIAG%XHSF,TPDG%TDIAG_RUN%XHSF,LMASK_FLD)
!
    YVNAME = 'fld_width'
    ZWRITE = TPDG%TDIAG%XWF / PTSTEP_DIAG
    CALL WRITE_TRIP(KLISTING,YFILE,YVNAME,LMASK_FLD,ZWRITE,ITNUM,ITVAL,OXIOS=OXIOS)  
    CALL CUM_DIAG(TPDG%TDIAG%XWF,TPDG%TDIAG_RUN%XWF,LMASK_FLD)
!
    YVNAME = 'fld_length'
    ZWRITE = TPDG%TDIAG%XLF / PTSTEP_DIAG
    CALL WRITE_TRIP(KLISTING,YFILE,YVNAME,LMASK_FLD,ZWRITE,ITNUM,ITVAL,OXIOS=OXIOS)
    CALL CUM_DIAG(TPDG%TDIAG%XLF,TPDG%TDIAG_RUN%XLF,LMASK_FLD)
!      
  ENDIF
!
ENDIF
!
IF (LHOOK) CALL DR_HOOK('TRIP_DIAG_WRITE',1,ZHOOK_HANDLE)
!
!-------------------------------------------------------------------------------
 CONTAINS
!-------------------------------------------------------------------------------
!
SUBROUTINE CUM_DIAG(PDIAG,PRUN,OMASK)
!
USE MODD_TRIP_PAR, ONLY : XUNDEF
!
IMPLICIT NONE
!
LOGICAL, DIMENSION(:,:),INTENT(IN) :: OMASK
REAL, DIMENSION(:,:),INTENT(INOUT) :: PDIAG
REAL, DIMENSION(:,:),INTENT(OUT  ) :: PRUN
!
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
IF (LHOOK) CALL DR_HOOK('TRIP_DIAG_WRITE:CUM_DIAG',0,ZHOOK_HANDLE)
!
WHERE(OMASK(:,:))
     PRUN(:,:) = PRUN(:,:) + PDIAG(:,:)
ELSEWHERE
     PRUN(:,:) = XUNDEF
ENDWHERE

!
PDIAG(:,:) = 0.0
!
IF (LHOOK) CALL DR_HOOK('TRIP_DIAG_WRITE:CUM_DIAG',1,ZHOOK_HANDLE)
!
END SUBROUTINE CUM_DIAG
!
!-------------------------------------------------------------------------------
END SUBROUTINE TRIP_DIAG_WRITE
