!     ######
      SUBROUTINE CLOSE_FILEIN_OL
!     #######################################################
!!****  *CLOSE_FILEIN_OL* - 
!
USE MODD_OL_FILEID, ONLY : XID_IN, XVAR_TO_FILEIN, XID_VARIN

USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE
INCLUDE "netcdf.inc"

INTEGER :: JFILE, JRET
REAL(KIND=JPRB) :: ZHOOK_HANDLE

!**************************************************

IF (LHOOK) CALL DR_HOOK('CLOSE_FILEIN_OL',0,ZHOOK_HANDLE)
DO JFILE=1,SIZE(XID_IN)
  JRET=NF_CLOSE(XID_IN(JFILE))
ENDDO

DEALLOCATE(XID_IN)
DEALLOCATE(XVAR_TO_FILEIN)
DEALLOCATE(XID_VARIN)
IF (LHOOK) CALL DR_HOOK('CLOSE_FILEIN_OL',1,ZHOOK_HANDLE)

!******************************************

END SUBROUTINE CLOSE_FILEIN_OL
