!     #########
        SUBROUTINE FILL_ID_OL(IFILEID)
!     #######################################################
!!****  *FILL_ID_OL* - 
!
USE MODD_OL_FILEID,   ONLY : XID, XOUT
!
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE
!
INTEGER, INTENT(IN)    :: IFILEID
!
INTEGER*4, DIMENSION(:), ALLOCATABLE :: ITEMP
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
!------------------------------------------
!
!
IF (LHOOK) CALL DR_HOOK('FILL_ID_OL',0,ZHOOK_HANDLE)
ALLOCATE(ITEMP(XOUT))
ITEMP(SIZE(XID)+1:XOUT)=IFILEID
IF (SIZE(XID).GT.0) ITEMP(1:SIZE(XID))=XID
!
DEALLOCATE(XID)
ALLOCATE(XID(XOUT))
XID=ITEMP
!
DEALLOCATE(ITEMP)
IF (LHOOK) CALL DR_HOOK('FILL_ID_OL',1,ZHOOK_HANDLE)
!
!
!--------------------------------------

END SUBROUTINE FILL_ID_OL
