SUBROUTINE OI_TSL(IDAT,NSSSSS,PLAT,PLON,PMU0,PMU0M,IH)
!-----------------------------------------------------------------------
!
!     Computation of solar zenith angle 
!     ---------------------------------
!
!     INPUT PARAMETERS :
!
!     IDAT    : DATE in the following form => YYYYMMDD
!     NSSSSS  : TIME of the day in seconds
!     PLAT    : LATITUDE  in Degrees
!     PLON    : LONGITUDE in Degrees
!
!     OUTPUT PARAMETERS :
!
!     PMU0    : Cosine of solar zenith angle
!     PMU0M   : Cosine of solar zenith angle (mean value)
!     IH      : local time (hour)
!
!
!     J.F. Mahfouf (4/12/97) from IFS/ARPEGE routines
!                 
!
!     23/05/2009 : Fortran 90 recoding (IMPLICIT NONE + FUNCTIONS)
!
!-----------------------------------------------------------------------
!
! - Astronomical functions
!   you will find the description in the annex 1 of the documentation
!   RRS is the distance Sun-Earth
!   RDS is the declination of the Earth
!   RET is the equation of time
! 
 USE MODD_CSTS,       ONLY : XDAY, XPI
 USE MODD_ASSIM,      ONLY : REPSM, RCDTR, ITRAD
!
!
 USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
 USE PARKIND1  ,ONLY : JPRB
!
 IMPLICIT NONE
!
 INTEGER, INTENT(IN)  :: IDAT
 INTEGER, INTENT(IN)  :: NSSSSS 
 REAL, INTENT(IN)     :: PLAT, PLON
 REAL, INTENT(OUT)    :: PMU0, PMU0M
 INTEGER, INTENT(OUT) :: IH
!
 REAL :: PGEMU,   PGELAM,  RTIMTR,  ZTETA,   RDECLI,  REQTIM, RHGMT,    RSOVR,   RWSOVR, &
          RCODEC,  RSIDEC,  RCOVSR,  RSIVSR,  RTIMTRM, ZTETAM,  RDECLIM, REQTIMM, RHGMTM, &
          RSOVRM,  RWSOVRM, RCODECM, RSIDECM, RCOVSRM, RSIVSRM, ZT  
 INTEGER :: ID, IM, IA, INSSSSS
 REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
!  Angle conversions 
!      
 IF (LHOOK) CALL DR_HOOK('OI_TSL',0,ZHOOK_HANDLE)
 PGEMU=SIN(PLAT*XPI/180.)      ! sinus of latitude
 PGELAM=PLON*XPI/180.          ! longitude
!      
 ID=NDD(IDAT)
 IM=NMM(IDAT)
 IA=NCCAA(IDAT)
 RTIMTR=RTIME(IA,IM,ID,NSSSSS)
 ZTETA=RTETA(RTIMTR)
 RDECLI=RDS(ZTETA)             ! declinaison
 REQTIM=RET(ZTETA)
 RHGMT=REAL(MOD(NSSSSS,NINT(XDAY)))
 RSOVR =REQTIM+RHGMT    
 RWSOVR=RSOVR*2.*XPI/XDAY      ! hour angle
!      
 RCODEC=COS(RDECLI)
 RSIDEC=SIN(RDECLI)
!
 RCOVSR=COS(RWSOVR)
 RSIVSR=SIN(RWSOVR)
!      
 PMU0=MAX( RSIDEC*PGEMU  &
           -RCODEC*RCOVSR*SQRT(1.-PGEMU**2)*COS(PGELAM) &
           +RCODEC*RSIVSR*SQRT(1.-PGEMU**2)*SIN(PGELAM) , 0.)  
 IF (PMU0.GT.0.) THEN
   PMU0=SQRT(1224.*PMU0*PMU0 +1.)/35. ! Magnification factor
 ENDIF  
!
!     Mean angle over the previous 6 hours
!     ------------------------------------
!  
 RTIMTRM=RTIME(IA,IM,ID,NSSSSS-ITRAD)
 ZTETAM=RTETA(RTIMTRM)
 RDECLIM=RDS(ZTETAM)             ! declinaison
 REQTIMM=RET(ZTETAM)
 IF ((NSSSSS-ITRAD).LT.0) THEN
   INSSSSS=NSSSSS+86400
 ELSE
   INSSSSS=NSSSSS
 ENDIF  
 RHGMTM=REAL(MOD(INSSSSS-ITRAD,NINT(XDAY)))
 RSOVRM =REQTIMM+RHGMTM    
 RWSOVRM=RSOVRM*2.*XPI/XDAY      ! hour angle
!      
 RCODECM=COS(RDECLIM)
 RSIDECM=SIN(RDECLIM)
!
 RCOVSRM=COS(RWSOVRM)
 RSIVSRM=SIN(RWSOVRM)
!     
 PMU0M=MAX( RSIDECM*PGEMU &
            -RCODECM*RCOVSRM*SQRT(1.-PGEMU**2)*COS(PGELAM) &
            +RCODECM*RSIVSRM*SQRT(1.-PGEMU**2)*SIN(PGELAM) , 0.)  
 IF (PMU0M.GT.0.) THEN
   PMU0M=SQRT(1224.*PMU0M*PMU0M +1.)/35. ! Magnification factor
 ENDIF  
! 
!  Local time in hours
!
 ZT = (NSSSSS + PLON*RCDTR*3600.)/3600.
 IF (ZT < 0.0)  ZT = ZT + 24.
 IF (ZT > 24.0) ZT = ZT - 24.
 IH = INT(ZT)
!
IF (LHOOK) CALL DR_HOOK('OI_TSL',1,ZHOOK_HANDLE)
CONTAINS
!
FUNCTION RTETA(PTIME)
 USE MODD_CSTS, ONLY : XDAY
 IMPLICIT NONE
 REAL, INTENT(IN) :: PTIME
 REAL             :: RTETA
 REAL(KIND=JPRB) :: ZHOOK_HANDLE
 IF (LHOOK) CALL DR_HOOK('RTETA',0,ZHOOK_HANDLE)
 RTETA = PTIME/(XDAY*365.25)
IF (LHOOK) CALL DR_HOOK('RTETA',1,ZHOOK_HANDLE)
END FUNCTION RTETA
!
FUNCTION REL(PTETA)
 IMPLICIT NONE
 REAL, INTENT(IN) :: PTETA
 REAL             :: REL
 REAL(KIND=JPRB) :: ZHOOK_HANDLE
 IF (LHOOK) CALL DR_HOOK('REL',0,ZHOOK_HANDLE)
 REL = 1.7535+6.283076*PTETA
IF (LHOOK) CALL DR_HOOK('REL',1,ZHOOK_HANDLE)
END FUNCTION REL
!
FUNCTION REM(PTETA)
 IMPLICIT NONE
 REAL, INTENT(IN) :: PTETA
 REAL             :: REM
 REAL(KIND=JPRB) :: ZHOOK_HANDLE
 IF (LHOOK) CALL DR_HOOK('REM',0,ZHOOK_HANDLE)
 REM = 6.240075+6.283020*PTETA
IF (LHOOK) CALL DR_HOOK('REM',1,ZHOOK_HANDLE)
END FUNCTION REM
!
FUNCTION RLLS(PTETA)
 IMPLICIT NONE
 REAL, INTENT(IN) :: PTETA
 REAL             :: RLLS
 REAL(KIND=JPRB) :: ZHOOK_HANDLE
 IF (LHOOK) CALL DR_HOOK('RLLS',0,ZHOOK_HANDLE)
 RLLS = 4.8951+6.283076*PTETA
IF (LHOOK) CALL DR_HOOK('RLLS',1,ZHOOK_HANDLE)
END FUNCTION RLLS
!
FUNCTION RLLLS(PTETA)
 IMPLICIT NONE
 REAL, INTENT(IN) :: PTETA
 REAL             :: RLLLS, REL
 REAL(KIND=JPRB) :: ZHOOK_HANDLE
 IF (LHOOK) CALL DR_HOOK('RLLLS',0,ZHOOK_HANDLE)
 REL   = 1.7535+6.283076*PTETA
 RLLLS = 4.8952+6.283320*PTETA-0.0075*SIN(REL)  &
       -0.0326*COS(REL)-0.0003*SIN(2.*REL)+0.0002*COS(2.*REL)  
IF (LHOOK) CALL DR_HOOK('RLLLS',1,ZHOOK_HANDLE)
END FUNCTION RLLLS
!
FUNCTION RDS(PTETA)
 USE MODD_ASSIM, ONLY : REPSM
 IMPLICIT NONE
 REAL, INTENT(IN) :: PTETA
 REAL             :: RDS, RLLLS
 REAL(KIND=JPRB) :: ZHOOK_HANDLE
 IF (LHOOK) CALL DR_HOOK('RDS',0,ZHOOK_HANDLE)
 RLLLS = 4.8952+6.283320*PTETA-0.0075*SIN(REL(PTETA))  &
         -0.0326*COS(REL(PTETA))-0.0003*SIN(2.*REL(PTETA)) &
         +0.0002*COS(2.*REL(PTETA))  
 RDS   = ASIN(SIN(REPSM)*SIN(RLLLS))
IF (LHOOK) CALL DR_HOOK('RDS',1,ZHOOK_HANDLE)
END FUNCTION RDS
! 
FUNCTION RET(PTETA)
 IMPLICIT NONE
 REAL, INTENT(IN) :: PTETA
 REAL             :: RET, REM, RLLS
 REAL(KIND=JPRB) :: ZHOOK_HANDLE
 IF (LHOOK) CALL DR_HOOK('RET',0,ZHOOK_HANDLE)
 REM  = 6.240075+6.283020*PTETA
 RLLS = 4.8951+6.283076*PTETA
 RET  = 591.8*SIN(2.*RLLS)-459.4*SIN(REM) &
        +39.5*SIN(REM)*COS(2.*RLLS) &
        -12.7*SIN(4.*RLLS)-4.8*SIN(2.*REM)  
IF (LHOOK) CALL DR_HOOK('RET',1,ZHOOK_HANDLE)
END FUNCTION RET
!
FUNCTION NDD(KGRDAT)
 IMPLICIT NONE
 INTEGER, INTENT(IN) :: KGRDAT
 INTEGER             :: NDD
 REAL(KIND=JPRB) :: ZHOOK_HANDLE
 IF (LHOOK) CALL DR_HOOK('NDD',0,ZHOOK_HANDLE)
 NDD = MOD(KGRDAT,100)
IF (LHOOK) CALL DR_HOOK('NDD',1,ZHOOK_HANDLE)
END FUNCTION NDD
!
FUNCTION NMM(KGRDAT)
 IMPLICIT NONE
 INTEGER, INTENT(IN) :: KGRDAT
 INTEGER             :: NMM, NDD
 REAL(KIND=JPRB) :: ZHOOK_HANDLE
 IF (LHOOK) CALL DR_HOOK('NMM',0,ZHOOK_HANDLE)
 NDD = MOD(KGRDAT,100)
 NMM = MOD((KGRDAT-NDD)/100,100)
IF (LHOOK) CALL DR_HOOK('NMM',1,ZHOOK_HANDLE)
END FUNCTION NMM
! 
FUNCTION NCCAA(KGRDAT)
 IMPLICIT NONE
 INTEGER, INTENT(IN) :: KGRDAT
 INTEGER             :: NCCAA
 REAL(KIND=JPRB) :: ZHOOK_HANDLE
 IF (LHOOK) CALL DR_HOOK('NCCAA',0,ZHOOK_HANDLE)
 NCCAA = KGRDAT/10000
IF (LHOOK) CALL DR_HOOK('NCCAA',1,ZHOOK_HANDLE)
END FUNCTION NCCAA
! 
FUNCTION NZZAA(KAAAA,KMM)
 IMPLICIT NONE
 INTEGER, INTENT(IN) :: KAAAA,KMM
 INTEGER             :: NZZAA
 REAL(KIND=JPRB) :: ZHOOK_HANDLE
 IF (LHOOK) CALL DR_HOOK('NZZAA',0,ZHOOK_HANDLE)
 NZZAA = KAAAA-( (1-ISIGN(1,KMM-3))/2 )
IF (LHOOK) CALL DR_HOOK('NZZAA',1,ZHOOK_HANDLE)
END FUNCTION NZZAA
!
FUNCTION NZZMM(KMM)
 IMPLICIT NONE
 INTEGER, INTENT(IN) :: KMM
 INTEGER             :: NZZMM
 REAL(KIND=JPRB) :: ZHOOK_HANDLE
 IF (LHOOK) CALL DR_HOOK('NZZMM',0,ZHOOK_HANDLE)
 NZZMM = KMM+6*(1-ISIGN(1,KMM-3))
IF (LHOOK) CALL DR_HOOK('NZZMM',1,ZHOOK_HANDLE)
END FUNCTION NZZMM
!
FUNCTION RJUDAT(KAAAA,KMM,KDD)
 IMPLICIT NONE
 INTEGER, INTENT(IN) :: KAAAA,KMM,KDD
 REAL                :: RJUDAT
 INTEGER             :: NZZAA, NZZMM
 REAL(KIND=JPRB) :: ZHOOK_HANDLE
 IF (LHOOK) CALL DR_HOOK('RJUDAT',0,ZHOOK_HANDLE)
 NZZMM  = KMM+6*(1-ISIGN(1,KMM-3))
 NZZAA  = KAAAA-( (1-ISIGN(1,KMM-3))/2 )
 RJUDAT = 1720994.5 + FLOAT(2-NZZAA/100 + (NZZAA/100)/4 &
   + INT(365.25*FLOAT(NZZAA)) + INT(30.601*FLOAT(NZZMM+1)) + KDD)  
IF (LHOOK) CALL DR_HOOK('RJUDAT',1,ZHOOK_HANDLE)
END FUNCTION RJUDAT
!
FUNCTION RTIME(KAAAA,KMM,KDD,KSS)
 USE MODD_CSTS, ONLY : XDAY
 IMPLICIT NONE 
 INTEGER, INTENT(IN) :: KAAAA,KMM,KDD,KSS
 REAL                :: RTIME, RJUDAT
 INTEGER             :: NZZAA, NZZMM
 REAL(KIND=JPRB) :: ZHOOK_HANDLE
 IF (LHOOK) CALL DR_HOOK('RTIME',0,ZHOOK_HANDLE)
 NZZMM  = KMM+6*(1-ISIGN(1,KMM-3))
 NZZAA  = KAAAA-( (1-ISIGN(1,KMM-3))/2 )
 RJUDAT = 1720994.5 + FLOAT(2-NZZAA/100 + (NZZAA/100)/4 &
   + INT(365.25*FLOAT(NZZAA)) + INT(30.601*FLOAT(NZZMM+1)) + KDD)  
 RTIME  = (RJUDAT-2451545.)*XDAY+FLOAT(KSS)
IF (LHOOK) CALL DR_HOOK('RTIME',1,ZHOOK_HANDLE)
END FUNCTION RTIME

END SUBROUTINE OI_TSL




