      SUBROUTINE MXMN_MF (PARRAY,KLEN,PMAX,PMIN)
      USE PARKIND1, ONLY : JPIM, JPRB
      USE YOMHOOK , ONLY : LHOOK, DR_HOOK
      USE LFI_PRECISION, ONLY : JPDBLR
!
!*******************************************************************
!*
!*    NAME      : MXMN
!*
!*    FUNCTION  : RETURN MAXIMUM AND MINIMUM VALUES FROM AN ARRAY
!*                OF FLOATING POINT NUMBERS.
!*
!*    INPUT     : PARRAY - ARRAY OF NUMBERS
!*                KLEN   - LAST WORD OF THIS ARRAY
!*
!*    OUTPUT    : PMAX - MAXIMUM VALUE
!*                PMIN - MINIMUM VALUE
!*
!*
!*     JOHN HENNESSY, ECMWF, 22 APRIL 1985
!*
!*    Modified by Jean CLOCHARD, French DMN, January 1990.
!*    R. El Khatib 2004-10-12 MAXVAL,MINVAL
!*    F. Vana + NEC Apr-2009: OpenMP
!*
!*******************************************************************
!
!RJ       USE OML_MOD , ONLY : OML_MY_THREAD , OML_GET_NUM_THREADS
!
      IMPLICIT NONE
!
      INTEGER(KIND=JPIM) :: KLEN
      REAL (KIND=JPDBLR) :: PMAX
      REAL (KIND=JPDBLR) :: PMIN
      REAL (KIND=JPDBLR) :: PARRAY (KLEN)
      INTEGER(KIND=JPIM) :: START, END, BLOCKS, MY_THREAD, THREADS
      REAL (KIND=JPDBLR) :: PMAX_LOCAL, PMIN_LOCAL
!RJ: some omp declarations
!$    INTEGER,EXTERNAL :: OMP_GET_THREAD_NUM,OMP_GET_NUM_THREADS
!
      REAL(KIND=JPRB) :: ZHOOK_HANDLE
      IF (LHOOK) CALL DR_HOOK('MXMN_MF',0,ZHOOK_HANDLE)
      PMAX = -HUGE(PARRAY)
      PMIN = HUGE(PARRAY)
!RJ: skip oml_module, but preserve omp region
!$OMP PARALLEL                                                          &
!$OMP&PRIVATE(START,END,BLOCKS,MY_THREAD,THREADS,PMAX_LOCAL,PMIN_LOCAL)
!RJ       MY_THREAD = OML_MY_THREAD() - 1
      MY_THREAD = 0
!$    MY_THREAD = OMP_GET_THREAD_NUM()
!RJ       THREADS = OML_GET_NUM_THREADS()
      THREADS = 1
!$    THREADS = OMP_GET_NUM_THREADS()
      BLOCKS = (KLEN + THREADS) / THREADS
      START = MY_THREAD * BLOCKS + 1
      END = MIN(START+BLOCKS-1,KLEN)
      PMAX_LOCAL = MAXVAL(PARRAY(START:END))
      PMIN_LOCAL = MINVAL(PARRAY(START:END))
!$OMP CRITICAL
      PMAX = MAX(PMAX,PMAX_LOCAL)
      PMIN = MIN(PMIN,PMIN_LOCAL)
!$OMP END CRITICAL
!$OMP END PARALLEL
      IF (LHOOK) CALL DR_HOOK('MXMN_MF',1,ZHOOK_HANDLE)
      ENDSUBROUTINE MXMN_MF
