SUBROUTINE ERROR_WRITE_SURF_TXT(HREC,KRESP)
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE
!
 CHARACTER(LEN=*), INTENT(IN) :: HREC
INTEGER,          INTENT(OUT):: KRESP
REAL(KIND=JPRB) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('ERROR_WRITE_SURF_TXT',0,ZHOOK_HANDLE)
KRESP = -1
!
WRITE(*,*) ' '
WRITE(*,*) 'WARNING'
WRITE(*,*) '-------'
WRITE(*,*) ' '
WRITE(*,*) 'error when writing article', HREC
WRITE(*,*) "default value may be used; who knows?"
WRITE(*,*) ' '
!
IF (LHOOK) CALL DR_HOOK('ERROR_WRITE_SURF_TXT',1,ZHOOK_HANDLE)
!
END SUBROUTINE ERROR_WRITE_SURF_TXT
