SUBROUTINE GOTO_TRIP(KMI)
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
USE MODE_MODELN_TRIP_HANDLER
!
IMPLICIT NONE
!
INTEGER, INTENT(IN) :: KMI
!
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!!
IF (LHOOK) CALL DR_HOOK('GOTO_TRIP',0,ZHOOK_HANDLE)
CALL GOTO_MODEL_TRIP(KMI)
IF (LHOOK) CALL DR_HOOK('GOTO_TRIP',1,ZHOOK_HANDLE)
!!
END SUBROUTINE GOTO_TRIP
