C
C       FONCTION SERVANT A RENDRE FATALE OU NON UNE ERREUR DETECTEE,
C       A L'AIDE DU CODE-REPONSE COURANT, DU NIVEAU DE FILTRAGE GLOBAL,
C       ET DE L'OPTION D'ERREUR FATALE PROPRE AU FICHIER.
C       S'IL N'Y A PAS DE FICHIER (I5678=0, D'OU DIMENSIONNEMENT DE
C          *LERFAT*), LE NIVEAU DE FILTRAGE JOUE LE ROLE PRINCIPAL.
C
      INTEGER IXNIMS, I1234, I5678, I3456, IXC, IXM, IXT, IABCDE, IFGHIJ
      INTEGER IKLMNO, IPQRST, IUVWXY, IZABCD, IEFGHI
C
      LOGICAL LLMOER
C
      LLMOER (I1234,I5678)=I1234.EQ.-16.OR.
     S (I1234.NE.0.AND.(LFI%NERFAG.EQ.0.OR.(LFI%NERFAG.EQ.1
     S .AND.LFI%LERFAT(I5678))))
C
C       FONCTION DONNANT LE PLUS HAUT NIVEAU DE MESSAGERIE ACCEPTABLE
C       POUR L'UNITE LOGIQUE DE RANG "I3456" .
C       (UTILISATION DES NIVEAUX DE MESSAGERIE GLOBAL ET PROPRE AU
C        FICHIER - MEME REMARQUE QUE CI-DESSUS SI I3456=0, POUR NIVMES)
C
      IXNIMS (I3456)=MIN0 (2,2*LFI%NIMESG,
     S                 MAX0 (2*LFI%NIMESG-2,LFI%NIVMES(I3456)))
C
C       Fonctions servant a l'adressage 1D dans les tableaux CNOMAR,
C     MLGPOS et MDES1D, MTAMPD.
C
      IXC (IABCDE,IFGHIJ) = IABCDE + LFI%JPNXNA * ( IFGHIJ - 1 )
      IXM (IKLMNO,IPQRST) = IKLMNO + LFI%JPLARD * ( IPQRST - 1 )
      IXT (IUVWXY,IZABCD,IEFGHI) = IUVWXY + LFI%JPLARD *
     S ( LFI%MFACTM(IEFGHI) * IZABCD + LFI%JPNPDF * ( IEFGHI - 1 ) )
C
