MODULE ABSTRACT_ICE
IMPLICIT NONE
PRIVATE

TYPE, PUBLIC, ABSTRACT :: SEA_ICE_t
  CONTAINS
    PROCEDURE(IINIT), DEFERRED, PASS :: INIT
    PROCEDURE(IPREP), DEFERRED, PASS :: PREP
    PROCEDURE(IASSIM), DEFERRED, PASS :: ASSIM
    PROCEDURE(IRUN), DEFERRED, PASS :: RUN
    PROCEDURE(IDEALLOC), DEFERRED, PASS :: DEALLOC

    PROCEDURE(IIO), DEFERRED, PASS :: READSURF
    PROCEDURE(IIO), DEFERRED, PASS :: WRITESURF
END TYPE SEA_ICE_t

ABSTRACT INTERFACE
  SUBROUTINE IINIT(THIS)
    IMPORT :: SEA_ICE_t
    CLASS(SEA_ICE_t) :: THIS
  END SUBROUTINE IINIT

  SUBROUTINE IPREP(THIS)
    IMPORT :: SEA_ICE_t
    CLASS(SEA_ICE_t) :: THIS
  END SUBROUTINE IPREP

  SUBROUTINE IASSIM(THIS)
    IMPORT :: SEA_ICE_t
    CLASS(SEA_ICE_t) :: THIS
  END SUBROUTINE IASSIM

  SUBROUTINE IRUN(THIS)
    IMPORT :: SEA_ICE_t
    CLASS(SEA_ICE_t) :: THIS
  END SUBROUTINE IRUN

  SUBROUTINE IDEALLOC(THIS)
    IMPORT :: SEA_ICE_t
    CLASS(SEA_ICE_t) :: THIS
  END SUBROUTINE IDEALLOC

  SUBROUTINE IIO(THIS, G, HPROGRAM, KLU, KLUOUT)
    USE MODD_SFX_GRID_n, ONLY : GRID_t
    IMPORT :: SEA_ICE_t
    CLASS(SEA_ICE_t) :: THIS
    TYPE(GRID_t), INTENT(INOUT)   :: G
    CHARACTER(LEN=6),  INTENT(IN) :: HPROGRAM !< calling program
    INTEGER,           INTENT(IN) :: KLU      !< number of sea patch point
    INTEGER,           INTENT(IN) :: KLUOUT
  END SUBROUTINE IIO
END INTERFACE

END MODULE