MODULE ABSTRACT_ICE
IMPLICIT NONE
PRIVATE

TYPE, PUBLIC :: SEA_ICE_FORCING_t
    !REAL, POINTER ::
END TYPE SEA_ICE_FORCING_t

TYPE, PUBLIC :: ESM_CPL_t
  REAL, POINTER, DIMENSION(:) :: XCPL_SEA_WIND !< 10m wind speed for ESM coupling
  REAL, POINTER, DIMENSION(:) :: XCPL_SEA_FWSU !< zonal wind stress for ESM coupling
  REAL, POINTER, DIMENSION(:) :: XCPL_SEA_FWSV !< meridian wind stress for ESM coupling
  REAL, POINTER, DIMENSION(:) :: XCPL_SEA_SNET !< Solar net heat flux
  REAL, POINTER, DIMENSION(:) :: XCPL_SEA_HEAT !< Non solar net heat flux
  REAL, POINTER, DIMENSION(:) :: XCPL_SEA_EVAP !< Evaporation for ESM coupling
  REAL, POINTER, DIMENSION(:) :: XCPL_SEA_RAIN !< Rainfall for ESM coupling
  REAL, POINTER, DIMENSION(:) :: XCPL_SEA_SNOW !< Snowfall for ESM coupling
  REAL, POINTER, DIMENSION(:) :: XCPL_SEA_FWSM !< wind stress for ESM coupling
!
  REAL, POINTER, DIMENSION(:) :: XCPL_SEAICE_SNET !< Solar net heat flux for ESM coupling
  REAL, POINTER, DIMENSION(:) :: XCPL_SEAICE_HEAT !< Non solar net heat flux
  REAL, POINTER, DIMENSION(:) :: XCPL_SEAICE_EVAP !< Ice sublimation for ESM coupling
END TYPE

TYPE, PUBLIC, ABSTRACT :: SEA_ICE_t
    REAL, POINTER :: XSEABATHY(:) !< bathymetry
    REAL, POINTER :: XSST(:) !< sea surface temperature [K]
    REAL, POINTER :: XSSS(:) !< se surface salinity [K]

    LOGICAL :: LINTERPOL_SIC
    LOGICAL :: LINTERPOL_SIT
  CONTAINS
    PROCEDURE(IINIT), DEFERRED, PASS :: INIT
    PROCEDURE(IPREP), DEFERRED, PASS :: PREP
    PROCEDURE(IASSIM), DEFERRED, PASS :: ASSIM
    PROCEDURE(IRUN), DEFERRED, PASS :: RUN
    PROCEDURE(IDEALLOC), DEFERRED, PASS :: DEALLOC

    PROCEDURE(IIO_READ), DEFERRED, PASS :: READSURF
    PROCEDURE(IIO_WRITE), DEFERRED, PASS :: WRITESURF

    PROCEDURE(IRESPONSE), DEFERRED, PASS :: GET_RESPONSE

    PROCEDURE, PASS :: BIND_INPUTS
END TYPE SEA_ICE_t

ABSTRACT INTERFACE
  SUBROUTINE IINIT(THIS, HPROGRAM)
    IMPORT :: SEA_ICE_t
    CLASS(SEA_ICE_t) :: THIS
    CHARACTER(LEN=6), INTENT(IN)  :: HPROGRAM
  END SUBROUTINE IINIT

  SUBROUTINE IPREP(THIS, KLU, HPROGRAM, HATMFILE, HATMFILETYPE, HPGDFILE, HPGDFILETYPE)
    IMPORT :: SEA_ICE_t
    CLASS(SEA_ICE_t) :: THIS
    INTEGER, INTENT(IN) :: KLU
    CHARACTER(LEN=6),   INTENT(IN)  :: HPROGRAM  !< program calling surf. schemes
    CHARACTER(LEN=28),  INTENT(IN)  :: HATMFILE    !< name of the Atmospheric file
    CHARACTER(LEN=6),   INTENT(IN)  :: HATMFILETYPE!< type of the Atmospheric file
    CHARACTER(LEN=28),  INTENT(IN)  :: HPGDFILE    !< name of the PGD file
    CHARACTER(LEN=6),   INTENT(IN)  :: HPGDFILETYPE!< type of the PGD file
  END SUBROUTINE IPREP

  SUBROUTINE IASSIM(THIS)
    IMPORT :: SEA_ICE_t
    CLASS(SEA_ICE_t) :: THIS
  END SUBROUTINE IASSIM

  SUBROUTINE IRUN(THIS, HPROGRAM, PTIMEC, PTSTEP, KSTEP, ESM_CPL, PFSIC, PFSIT, PSI_FLX_DRV, PFREEZING_SST)
    IMPORT :: SEA_ICE_t, ESM_CPL_t
    CLASS(SEA_ICE_t) :: THIS
    CHARACTER(LEN=6),    INTENT(IN) :: HPROGRAM  !< program calling surf. schemes
    REAL,                INTENT(IN) :: PTIMEC    !< current duration since start of the run (s)
    REAL,                INTENT(IN) :: PTSTEP    !< surface time-step (s)
    INTEGER, INTENT(IN) :: KSTEP !< number of ice time steps within a surface time-step
    TYPE(ESM_CPL_t), INTENT(INOUT) :: ESM_CPL
    REAL, INTENT(IN) :: PFSIC(:)
    REAL, INTENT(IN) :: PFSIT(:)
    REAL, INTENT(IN) :: PSI_FLX_DRV
    REAL, INTENT(IN) :: PFREEZING_SST
  END SUBROUTINE IRUN

  SUBROUTINE IDEALLOC(THIS)
    IMPORT :: SEA_ICE_t
    CLASS(SEA_ICE_t) :: THIS
  END SUBROUTINE IDEALLOC

  SUBROUTINE IIO_READ(THIS, G, HPROGRAM, KLU, KLUOUT)
    USE MODD_SFX_GRID_n, ONLY : GRID_t
    IMPORT :: SEA_ICE_t
    CLASS(SEA_ICE_t) :: THIS
    TYPE(GRID_t), INTENT(INOUT)   :: G
    CHARACTER(LEN=6),  INTENT(IN) :: HPROGRAM !< calling program
    INTEGER,           INTENT(IN) :: KLU      !< number of sea patch point
    INTEGER,           INTENT(IN) :: KLUOUT
  END SUBROUTINE IIO_READ

  SUBROUTINE IIO_WRITE(THIS, HSELECT, HPROGRAM)
    USE MODD_SFX_GRID_n, ONLY : GRID_t
    IMPORT :: SEA_ICE_t
    CLASS(SEA_ICE_t) :: THIS
    CHARACTER(LEN=*), INTENT(IN) :: HSELECT(:)
    CHARACTER(LEN=6), INTENT(IN) :: HPROGRAM
  END SUBROUTINE IIO_WRITE

  SUBROUTINE IRESPONSE(THIS, PSIC, PTICE, PICE_ALB)
    IMPORT :: SEA_ICE_t
    CLASS(SEA_ICE_t) :: THIS
    REAL, INTENT(OUT) :: PSIC(:)
    REAL, INTENT(OUT) :: PTICE(:)
    REAL, INTENT(OUT) :: PICE_ALB(:)
  END SUBROUTINE IRESPONSE
END INTERFACE

CONTAINS

SUBROUTINE BIND_INPUTS(THIS, PSEABATHY, PSST, PSSS)
  IMPLICIT NONE
  CLASS(SEA_ICE_t) :: THIS
  REAL, POINTER, INTENT(IN) :: PSEABATHY(:)
  REAL, POINTER, INTENT(IN) :: PSST(:)
  REAL, POINTER, INTENT(IN) :: PSSS(:)

  THIS%XSEABATHY => PSEABATHY
  THIS%XSSS => PSSS
  THIS%XSST => PSST
END SUBROUTINE
END MODULE