!     #############################################################
      SUBROUTINE ALLOC_DIAG_SURF_ATM_n (DGU, DGUC, DGUP, DGUPC, U, &
                                        HPROGRAM,KSW)
!     #############################################################
!
!!    AUTHOR
!!    ------
!!      V. Masson   *Meteo France*
!!
!!    MODIFICATIONS
!!    -------------
!!      Original    01/2004
!!      Modified    01/2006 : sea flux parameterization.
!!                  08/2009 : TIME_BUDGETC for all Tile
!       B. decharme 09/2012 : XQS_TILE not initialize
!       B. decharme 04/2013 : Add EVAP and SUBL diag
!-------------------------------------------------------------------------------
!
!*       0.    DECLARATIONS
!              ------------
!
USE MODD_DIAG_n, ONLY : DIAG_t, DIAG_PATCH_t
USE MODD_SURF_ATM_n, ONLY : SURF_ATM_t
!
USE MODD_DATA_COVER_PAR, ONLY : NTILESFC
USE MODD_SURF_PAR,       ONLY : XUNDEF
                                

!
USE MODI_READ_SURF
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE
!
!*       0.1   Declarations of arguments
!              -------------------------
!
!
TYPE(DIAG_t), INTENT(INOUT) :: DGU
TYPE(DIAG_t), INTENT(INOUT) :: DGUC
TYPE(DIAG_PATCH_t), INTENT(INOUT) :: DGUP
TYPE(DIAG_PATCH_t), INTENT(INOUT) :: DGUPC
TYPE(SURF_ATM_t), INTENT(INOUT) :: U
!
 CHARACTER(LEN=6),        INTENT(IN) :: HPROGRAM  ! program calling surf. schemes
INTEGER,                 INTENT(IN) :: KSW       ! number of short-wave spectral bands
!
!*       0.2   Declarations of local variables
!              -------------------------------
!
INTEGER :: JTILE
INTEGER           :: IVERSION
INTEGER           :: IRESP          ! IRESP  : return-code if a problem appears
 CHARACTER(LEN=12) :: YREC           ! Name of the article to be read
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
!-------------------------------------------------------------------------------
!
!
! Initialization: Outputs to atmosphere over each tile:
!
IF (LHOOK) CALL DR_HOOK('ALLOC_DIAG_SURF_ATM_N',0,ZHOOK_HANDLE)
DO JTILE = 1,NTILESFC
  CALL ALLOC_DIAG(DGUP%AL(JTILE),.FALSE.,U%NSIZE_FULL,KSW)
  CALL INIT_DIAG(DGUP%AL(JTILE),.FALSE.,XUNDEF)
ENDDO
!
! Initialization: aggregated fields
!
CALL ALLOC_DIAG(DGU,.FALSE.,U%NSIZE_FULL,KSW)
CALL INIT_DIAG(DGU,.FALSE.,XUNDEF)
!
ALLOCATE(DGU%XSFCO2  (U%NSIZE_FULL))
!
ALLOCATE(DGU%XT2M_MIN_ZS    (U%NSIZE_FULL))
ALLOCATE(DGU%XQ2M_MIN_ZS    (U%NSIZE_FULL))
ALLOCATE(DGU%XHU2M_MIN_ZS   (U%NSIZE_FULL))
!
ALLOCATE(DGU%XPS                (U%NSIZE_FULL))
ALLOCATE(DGU%XRHOA              (U%NSIZE_FULL))
!
ALLOCATE(DGU%XSSO_FMU    (U%NSIZE_FULL))
ALLOCATE(DGU%XSSO_FMV    (U%NSIZE_FULL))
!
ALLOCATE(DGU%XUREF  (U%NSIZE_FULL))
ALLOCATE(DGU%XZREF  (U%NSIZE_FULL))
ALLOCATE(DGU%XTRAD  (U%NSIZE_FULL))
ALLOCATE(DGU%XEMIS  (U%NSIZE_FULL))
!
DGU%XSFCO2   = XUNDEF
!
DGU%XT2M_MIN_ZS     = XUNDEF
DGU%XQ2M_MIN_ZS     = XUNDEF
DGU%XHU2M_MIN_ZS    = XUNDEF
!
DGU%XPS                 = XUNDEF
DGU%XRHOA               = XUNDEF
!
DGU%XSSO_FMU     = XUNDEF
DGU%XSSO_FMV     = XUNDEF
!
DGU%XUREF   = XUNDEF
DGU%XZREF   = XUNDEF
DGU%XTRAD   = XUNDEF
DGU%XEMIS   = XUNDEF
!
IF (DGU%LSURF_BUDGETC) THEN
  !
  DO JTILE = 1,NTILESFC
    CALL ALLOC_DIAG(DGUPC%AL(JTILE),.TRUE.,U%NSIZE_FULL,0)
    CALL INIT_DIAG(DGUPC%AL(JTILE),.TRUE.,XUNDEF)
  ENDDO
  !
  CALL ALLOC_DIAG(DGUC,.TRUE.,U%NSIZE_FULL,0)
  !
  YREC='BUDC'
  CALL READ_SURF(HPROGRAM,YREC,DGU%LREAD_BUDGETC,IRESP)
  !
  IF (.NOT. DGU%LREAD_BUDGETC) THEN
      DGU%TIME_BUDGETC = U%TTIME
      CALL INIT_DIAG(DGUC,.TRUE.,0.0)  
  ELSEIF (DGU%LREAD_BUDGETC.AND.DGU%LRESET_BUDGETC) THEN
      DGU%TIME_BUDGETC = U%TTIME
      CALL INIT_DIAG(DGUC,.TRUE.,0.0)     
  ELSE
      YREC='TBUDC'
      CALL READ_SURF(HPROGRAM,YREC,DGU%TIME_BUDGETC,IRESP)
     YREC='RNC'
     CALL READ_SURF(HPROGRAM,YREC,DGUC%XRN,IRESP)
     YREC='HC'
     CALL READ_SURF(HPROGRAM,YREC,DGUC%XH ,IRESP)
     YREC='LEC'
     CALL READ_SURF(HPROGRAM,YREC,DGUC%XLE,IRESP)
     YREC='LEIC'
     CALL READ_SURF(HPROGRAM,YREC,DGUC%XLEI,IRESP)     
     YREC='GFLUXC'
     CALL READ_SURF(HPROGRAM,YREC,DGUC%XGFLUX ,IRESP)
     YREC='SWDC'
     CALL READ_SURF(HPROGRAM,YREC,DGUC%XSWD,IRESP)
     YREC='SWUC'
     CALL READ_SURF(HPROGRAM,YREC,DGUC%XSWU,IRESP)
     YREC='LWDC'
     CALL READ_SURF(HPROGRAM,YREC,DGUC%XLWD,IRESP)
     YREC='LWUC'
     CALL READ_SURF(HPROGRAM,YREC,DGUC%XLWU,IRESP)
     YREC='FMUC'
     CALL READ_SURF(HPROGRAM,YREC,DGUC%XFMU,IRESP)
     YREC='FMVC'
     CALL READ_SURF(HPROGRAM,YREC,DGUC%XFMV,IRESP)   
!
     CALL READ_SURF(HPROGRAM,'VERSION',IVERSION,IRESP)
      IF (IVERSION<8)THEN
         DGUC%XEVAP  = 0.0
         DGUC%XSUBL  = 0.0              
      ELSE
         YREC='EVAPC'
         CALL READ_SURF(HPROGRAM,YREC,DGUC%XEVAP,IRESP)
         YREC='SUBLC'
         CALL READ_SURF(HPROGRAM,YREC,DGUC%XSUBL,IRESP)              
      ENDIF
  !     
  ENDIF
  !
ELSE
  !
  DO JTILE=1,NTILESFC
    CALL ALLOC_DIAG(DGUPC%AL(JTILE),.TRUE.,0,0)
  ENDDO
  !
  CALL ALLOC_DIAG(DGUC,.TRUE.,0,0)
  !
ENDIF
IF (LHOOK) CALL DR_HOOK('ALLOC_DIAG_SURF_ATM_N',1,ZHOOK_HANDLE)
!
CONTAINS
!
SUBROUTINE ALLOC_DIAG(DGUI,OCUM,KSIZE1,KSIZE2)
!
TYPE(DIAG_t), INTENT(INOUT) :: DGUI
LOGICAL, INTENT(IN) :: OCUM
INTEGER, INTENT(IN) :: KSIZE1
INTEGER, INTENT(IN) :: KSIZE2
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
IF (LHOOK) CALL DR_HOOK('ALLOC_DIAG_SURF_ATM_N:ALLOC_DIAG',0,ZHOOK_HANDLE)
!
IF (.NOT.OCUM) THEN
  !
  ALLOCATE(DGUI%XRI     (KSIZE1))
  ALLOCATE(DGUI%XCD     (KSIZE1))
  ALLOCATE(DGUI%XCH     (KSIZE1))
  ALLOCATE(DGUI%XCE     (KSIZE1))
  !
  ALLOCATE(DGUI%XT2M    (KSIZE1))
  ALLOCATE(DGUI%XTS     (KSIZE1))
  ALLOCATE(DGUI%XT2M_MIN(KSIZE1))
  ALLOCATE(DGUI%XT2M_MAX(KSIZE1))
  ALLOCATE(DGUI%XQ2M    (KSIZE1))
  ALLOCATE(DGUI%XHU2M   (KSIZE1))
  ALLOCATE(DGUI%XHU2M_MIN(KSIZE1))
  ALLOCATE(DGUI%XHU2M_MAX(KSIZE1))
  ALLOCATE(DGUI%XZON10M (KSIZE1))
  ALLOCATE(DGUI%XMER10M (KSIZE1))
  !
  ALLOCATE(DGUI%XSWBD   (KSIZE1,KSIZE2))
  ALLOCATE(DGUI%XSWBU   (KSIZE1,KSIZE2))
  !
  ALLOCATE(DGUI%XQS     (KSIZE1))
  ALLOCATE(DGUI%XZ0     (KSIZE1))
  ALLOCATE(DGUI%XZ0H    (KSIZE1))
  !
  ALLOCATE(DGUI%XWIND10M(KSIZE1))
  ALLOCATE(DGUI%XWIND10M_MAX(KSIZE1))
  !  
ENDIF
!
ALLOCATE(DGUI%XRN     (KSIZE1))
ALLOCATE(DGUI%XH      (KSIZE1))
ALLOCATE(DGUI%XLE     (KSIZE1))
ALLOCATE(DGUI%XLEI    (KSIZE1))
ALLOCATE(DGUI%XGFLUX  (KSIZE1))
ALLOCATE(DGUI%XEVAP   (KSIZE1))
ALLOCATE(DGUI%XSUBL   (KSIZE1))
!
ALLOCATE(DGUI%XSWD    (KSIZE1))
ALLOCATE(DGUI%XSWU    (KSIZE1))
ALLOCATE(DGUI%XLWD    (KSIZE1))
ALLOCATE(DGUI%XLWU    (KSIZE1))
ALLOCATE(DGUI%XFMU    (KSIZE1))
ALLOCATE(DGUI%XFMV    (KSIZE1))
!
IF (LHOOK) CALL DR_HOOK('ALLOC_DIAG_SURF_ATM_N:ALLOC_DIAG',0,ZHOOK_HANDLE)
!
END SUBROUTINE ALLOC_DIAG
!
SUBROUTINE INIT_DIAG(DGUI,OCUM,PVAL)
!
TYPE(DIAG_t), INTENT(INOUT) :: DGUI
LOGICAL, INTENT(IN) :: OCUM
REAL, INTENT(IN) :: PVAL
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
IF (LHOOK) CALL DR_HOOK('ALLOC_DIAG_SURF_ATM_N:INIT_DIAG',0,ZHOOK_HANDLE)
!
IF (.NOT.OCUM) THEN
  !
  DGUI%XRI      = PVAL
  DGUI%XCD      = PVAL
  DGUI%XCH      = PVAL
  DGUI%XCE      = PVAL
  !
  DGUI%XT2M     = PVAL
  DGUI%XTS      = PVAL
  DGUI%XT2M_MIN = PVAL
  DGUI%XT2M_MAX = PVAL
  DGUI%XQ2M     = PVAL
  DGUI%XHU2M    = PVAL
  DGUI%XHU2M_MIN= PVAL
  DGUI%XHU2M_MAX= PVAL
  DGUI%XZON10M  = PVAL
  DGUI%XMER10M  = PVAL
  !
  DGUI%XSWBD    = PVAL
  DGUI%XSWBU    = PVAL
  !
  DGUI%XQS      = PVAL
  DGUI%XZ0      = PVAL
  DGUI%XZ0H     = PVAL
  !
  DGUI%XWIND10M = PVAL
  DGUI%XWIND10M_MAX = PVAL
  !  
ENDIF
!
DGUI%XRN      = PVAL
DGUI%XH       = PVAL
DGUI%XLE      = PVAL
DGUI%XLEI     = PVAL
DGUI%XGFLUX   = PVAL
DGUI%XEVAP    = PVAL
DGUI%XSUBL    = PVAL
!
DGUI%XSWD     = PVAL
DGUI%XSWU     = PVAL
DGUI%XLWD     = PVAL
DGUI%XLWU     = PVAL
DGUI%XFMU     = PVAL
DGUI%XFMV     = PVAL
!
IF (LHOOK) CALL DR_HOOK('ALLOC_DIAG_SURF_ATM_N:INIT_DIAG',0,ZHOOK_HANDLE)
!
END SUBROUTINE INIT_DIAG
!
!-------------------------------------------------------------------------------
!
END SUBROUTINE ALLOC_DIAG_SURF_ATM_n
