!     #########
      SUBROUTINE AVERAGE_DIAG(PFRAC_TILE, DUO, DGU, DGUP, DGUC, DGUPC      )                                
!     ######################################################################
!
!
!!****  *AVERAGE_DIAG*  
!!
!!    PURPOSE
!!    -------
!      Average the fluxes from the land and water surfaces depending on the
!      fraction of each surface cover type in the mesh area.
!     
!!**  METHOD
!!    ------
!
!!    EXTERNAL
!!    --------
!!
!!    IMPLICIT ARGUMENTS
!!    ------------------ 
!!
!!      
!!    REFERENCE
!!    ---------
!!      
!!    AUTHOR
!!    ------
!!    V. Masson * Meteo-France-
!!
!!    MODIFICATIONS
!!    -------------
!!      Original    06/2003
!!      Modified    08/2009 (B. Decharme) : new diag
!     02/2010 - S. Riette - Security for wind average in case of XUNDEF values
!       B. decharme 04/2013 : Add EVAP and SUBL diag
!-------------------------------------------------------------------------------
!
!*       0.     DECLARATIONS
!               ------------
!
USE MODD_DATA_COVER_PAR, ONLY : NTILESFC
!
USE MODD_DIAG_n, ONLY : DIAG_t, DIAG_PATCH_t, DIAG_OPTIONS_t
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE
!
!*      0.1    declarations of arguments
!
REAL, DIMENSION(:,:), INTENT(IN) :: PFRAC_TILE   ! Fraction in a mesh-area of 
!
TYPE(DIAG_OPTIONS_t), INTENt(INOUT) :: DUO
TYPE(DIAG_t), INTENT(INOUT) :: DGU
TYPE(DIAG_PATCH_t), INTENT(INOUT) :: DGUP
TYPE(DIAG_t), INTENT(INOUT) :: DGUC
TYPE(DIAG_PATCH_t), INTENT(INOUT) :: DGUPC
!
!*      0.2    declarations of local variables
!
REAL, DIMENSION(SIZE(PFRAC_TILE,1))    :: ZLAND, ZSEA, ZFRL
INTEGER :: JT
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!-------------------------------------------------------------------------------
!
!       1.     Grid-Box average fluxes
!              -----------------------
!
IF (LHOOK) CALL DR_HOOK('AVERAGE_DIAG',0,ZHOOK_HANDLE)
!
IF (DUO%LSURF_BUDGET) THEN
!
  DO JT = 1,NTILESFC
  !
  ! Net radiation
  !
  CALL MAKE_AVERAGE(PFRAC_TILE(:,JT),DGUP%AL(JT)%XRN,DGU%XRN,JT)
!
! Sensible heat flux
!
  CALL MAKE_AVERAGE(PFRAC_TILE(:,JT),DGUP%AL(JT)%XH,DGU%XH,JT)
!
! Total latent heat flux
!
  CALL MAKE_AVERAGE(PFRAC_TILE(:,JT),DGUP%AL(JT)%XLE,DGU%XLE,JT)
!
! Sublimation latent heat flux
!
  CALL MAKE_AVERAGE(PFRAC_TILE(:,JT),DGUP%AL(JT)%XLEI,DGU%XLEI,JT)
!
! Total evapotranspiration
!
  CALL MAKE_AVERAGE(PFRAC_TILE(:,JT),DGUP%AL(JT)%XEVAP,DGU%XEVAP,JT)
!
! Sublimation
!
  CALL MAKE_AVERAGE(PFRAC_TILE(:,JT),DGUP%AL(JT)%XSUBL,DGU%XSUBL,JT)
!
! Storage flux
!
  CALL MAKE_AVERAGE(PFRAC_TILE(:,JT),DGUP%AL(JT)%XGFLUX,DGU%XGFLUX,JT)
!
! Downwards short wave radiation
!
  CALL MAKE_AVERAGE(PFRAC_TILE(:,JT),DGUP%AL(JT)%XSWD,DGU%XSWD,JT)
!
! Upwards short wave radiation
!
  CALL MAKE_AVERAGE(PFRAC_TILE(:,JT),DGUP%AL(JT)%XSWU,DGU%XSWU,JT)
!
! Downwards long wave radiation
!
  CALL MAKE_AVERAGE(PFRAC_TILE(:,JT),DGUP%AL(JT)%XLWD,DGU%XLWD,JT)
!
! Upwards long wave radiation
!
  CALL MAKE_AVERAGE(PFRAC_TILE(:,JT),DGUP%AL(JT)%XLWU,DGU%XLWU,JT)
!
! Zonal wind stress
!
  CALL MAKE_AVERAGE(PFRAC_TILE(:,JT),DGUP%AL(JT)%XFMU,DGU%XFMU,JT)
!
! Meridian wind stress
!
  CALL MAKE_AVERAGE(PFRAC_TILE(:,JT),DGUP%AL(JT)%XFMV,DGU%XFMV,JT)
!
! Downwards short wave radiation for each spectral band
!
  CALL MAKE_AVERAGE_2D(PFRAC_TILE(:,JT),DGUP%AL(JT)%XSWBD,DGU%XSWBD,JT)
!
! Upwards short wave radiation for each spectral band
!
  CALL MAKE_AVERAGE_2D(PFRAC_TILE(:,JT),DGUP%AL(JT)%XSWBU,DGU%XSWBU,JT)
!
  ENDDO
  !
END IF
!
IF (DUO%LSURF_BUDGETC) THEN
!
  DO JT = 1,NTILESFC
  !
! Net radiation
!
  CALL MAKE_AVERAGE(PFRAC_TILE(:,JT),DGUPC%AL(JT)%XRN,DGUC%XRN,JT)
!
! Sensible heat flux
!
  CALL MAKE_AVERAGE(PFRAC_TILE(:,JT),DGUPC%AL(JT)%XH,DGUC%XH,JT)
!
! Total latent heat flux
!
  CALL MAKE_AVERAGE(PFRAC_TILE(:,JT),DGUPC%AL(JT)%XLE,DGUC%XLE,JT)
!
! Sublimation latent heat flux
!
  CALL MAKE_AVERAGE(PFRAC_TILE(:,JT),DGUPC%AL(JT)%XLEI,DGUC%XLEI,JT)
!
! Storage flux
!
  CALL MAKE_AVERAGE(PFRAC_TILE(:,JT),DGUPC%AL(JT)%XGFLUX,DGUC%XGFLUX,JT)
!
! Total evapotranspiration
!
  CALL MAKE_AVERAGE(PFRAC_TILE(:,JT),DGUPC%AL(JT)%XEVAP,DGUC%XEVAP,JT)
!
! Sublimation
!
  CALL MAKE_AVERAGE(PFRAC_TILE(:,JT),DGUPC%AL(JT)%XSUBL,DGUC%XSUBL,JT)
!
! Downwards short wave radiation
!
  CALL MAKE_AVERAGE(PFRAC_TILE(:,JT),DGUPC%AL(JT)%XSWD,DGUC%XSWD,JT)
!
! Upwards short wave radiation
!
  CALL MAKE_AVERAGE(PFRAC_TILE(:,JT),DGUPC%AL(JT)%XSWU,DGUC%XSWU,JT)
!
! Downwards long wave radiation
!
  CALL MAKE_AVERAGE(PFRAC_TILE(:,JT),DGUPC%AL(JT)%XLWD,DGUC%XLWD,JT)
!
! Upwards long wave radiation
!
  CALL MAKE_AVERAGE(PFRAC_TILE(:,JT),DGUPC%AL(JT)%XLWU,DGUC%XLWU,JT)
!
! Zonal wind stress
!
  CALL MAKE_AVERAGE(PFRAC_TILE(:,JT),DGUPC%AL(JT)%XFMU,DGUC%XFMU,JT)
!
! Meridian wind stress
!
  CALL MAKE_AVERAGE(PFRAC_TILE(:,JT),DGUPC%AL(JT)%XFMV,DGUC%XFMV,JT)
!
  ENDDO
  !
END IF
!
!-------------------------------------------------------------------------------
!
!       2.     Richardson number
!              -----------------
!
IF (DUO%N2M>=1) THEN
!
  DO JT = 1,NTILESFC
    !
    CALL MAKE_AVERAGE(PFRAC_TILE(:,JT),DGUP%AL(JT)%XRI,DGU%XRI,JT)
    !
  ENDDO
!
ENDIF
!
!-------------------------------------------------------------------------------
!
!       3.     Operational parameters at surface, 2 and 10 meters
!              --------------------------------------------------
!
!
IF (DUO%N2M>=1.OR.DUO%LSURF_BUDGET.OR.DUO%LSURF_BUDGETC) THEN
!
  DO JT = 1,NTILESFC
    !
! Surface temperature
!
    CALL MAKE_AVERAGE(PFRAC_TILE(:,JT),DGUP%AL(JT)%XTS,DGU%XTS,JT)
!
  ENDDO
  !
ENDIF
!
IF (DUO%N2M>=1) THEN
!
! Temperature at 2 meters
!
  IF (DUO%LT2MMW) THEN
    DO JT=1,NTILESFC
! Modified weighting giving increased weight to LAND temperature
      CALL  MAKE_AVERAGE_MW(PFRAC_TILE(:,JT),DGUP%AL(JT)%XT2M,DGU%XT2M,JT,ZLAND,ZSEA,ZFRL)
    ENDDO
    DO JT=1,NTILESFC
      CALL MAKE_AVERAGE_MW(PFRAC_TILE(:,JT),DGUP%AL(JT)%XT2M_MIN,DGU%XT2M_MIN,JT,ZLAND,ZSEA,ZFRL)
    ENDDO
    DO JT=1,NTILESFC      
      CALL MAKE_AVERAGE_MW(PFRAC_TILE(:,JT),DGUP%AL(JT)%XT2M_MAX,DGU%XT2M_MAX,JT,ZLAND,ZSEA,ZFRL)
    ENDDO
  ELSE
    DO JT=1,NTILESFC
      CALL MAKE_AVERAGE(PFRAC_TILE(:,JT),DGUP%AL(JT)%XT2M,DGU%XT2M,JT)
      CALL MAKE_AVERAGE(PFRAC_TILE(:,JT),DGUP%AL(JT)%XT2M_MIN,DGU%XT2M_MIN,JT)
      CALL MAKE_AVERAGE(PFRAC_TILE(:,JT),DGUP%AL(JT)%XT2M_MAX,DGU%XT2M_MAX,JT)
    ENDDO
  ENDIF
!
  DO JT=1,NTILESFC
! Relative humidity at 2 meters
!
  CALL MAKE_AVERAGE(PFRAC_TILE(:,JT),DGUP%AL(JT)%XHU2M,DGU%XHU2M,JT)
  CALL MAKE_AVERAGE(PFRAC_TILE(:,JT),DGUP%AL(JT)%XHU2M_MIN,DGU%XHU2M_MIN,JT)
  CALL MAKE_AVERAGE(PFRAC_TILE(:,JT),DGUP%AL(JT)%XHU2M_MAX,DGU%XHU2M_MAX,JT)
!
! Specific humidity at 2 meters
!
  CALL MAKE_AVERAGE(PFRAC_TILE(:,JT),DGUP%AL(JT)%XQ2M,DGU%XQ2M,JT)
!
! Wind at 10 meters
!
  CALL MAKE_AVERAGE(PFRAC_TILE(:,JT),DGUP%AL(JT)%XZON10M,DGU%XZON10M,JT)
!
  CALL MAKE_AVERAGE(PFRAC_TILE(:,JT),DGUP%AL(JT)%XMER10M,DGU%XMER10M,JT)
!
  CALL MAKE_AVERAGE(PFRAC_TILE(:,JT),DGUP%AL(JT)%XWIND10M,DGU%XWIND10M,JT)
  CALL MAKE_AVERAGE(PFRAC_TILE(:,JT),DGUP%AL(JT)%XWIND10M_MAX,DGU%XWIND10M_MAX,JT)
!
  ENDDO
  !
END IF
!-------------------------------------------------------------------------------
!
!       4.     Transfer coeffients and roughness lengths
!              -----------------------------------------
!
IF (DUO%LCOEF) THEN
!
  DO JT=1,NTILESFC
  !
  CALL MAKE_AVERAGE(PFRAC_TILE(:,JT),DGUP%AL(JT)%XCD,DGU%XCD,JT)
!
  CALL MAKE_AVERAGE(PFRAC_TILE(:,JT),DGUP%AL(JT)%XCH,DGU%XCH,JT)
!
  CALL MAKE_AVERAGE(PFRAC_TILE(:,JT),DGUP%AL(JT)%XCE,DGU%XCE,JT)
!
  CALL MAKE_AVERAGE_Z0(PFRAC_TILE(:,JT),DGU%XUREF,DGUP%AL(JT)%XZ0,DGU%XZ0,JT)
!
  CALL MAKE_AVERAGE_Z0(PFRAC_TILE(:,JT),DGU%XZREF,DGUP%AL(JT)%XZ0H,DGU%XZ0H,JT)
!
  ENDDO
  !
ENDIF
!
IF (DUO%LSURF_VARS) THEN
!
  DO JT=1,NTILESFC
    CALL MAKE_AVERAGE(PFRAC_TILE(:,JT),DGUP%AL(JT)%XQS,DGU%XQS,JT)
  ENDDO
!
ENDIF
!
IF (LHOOK) CALL DR_HOOK('AVERAGE_DIAG',1,ZHOOK_HANDLE)
!
CONTAINS
!
SUBROUTINE MAKE_AVERAGE(PFRAC,PFIELD_IN,PFIELD_OUT,KTILE)
!
USE MODD_SURF_PAR, ONLY : XUNDEF
!
IMPLICIT NONE
!
REAL, DIMENSION(:),INTENT(IN)   :: PFRAC
REAL, DIMENSION(:),INTENT(IN)   :: PFIELD_IN
REAL, DIMENSION(:), INTENT(OUT) :: PFIELD_OUT
INTEGER, INTENT(IN) :: KTILE
REAL(KIND=JPRB) :: ZHOOK_HANDLE
INTEGER :: JT
!
IF (LHOOK) CALL DR_HOOK('AVERAGE_DIAG:MAKE_AVERAGE',0,ZHOOK_HANDLE)
!
IF (KTILE==1) PFIELD_OUT(:) = 0.
!
WHERE (PFIELD_IN(:)==XUNDEF .AND. PFRAC(:)/=0.) PFIELD_OUT(:) = XUNDEF
!
WHERE (PFIELD_OUT(:)/=XUNDEF) 
  PFIELD_OUT(:) = PFIELD_OUT(:) + PFRAC(:) * PFIELD_IN(:)
END WHERE
!
IF (LHOOK) CALL DR_HOOK('AVERAGE_DIAG:MAKE_AVERAGE',1,ZHOOK_HANDLE)
!
END SUBROUTINE MAKE_AVERAGE
!
SUBROUTINE MAKE_AVERAGE_2D(PFRAC,PFIELD_IN,PFIELD_OUT,KTILE)
!
USE MODD_SURF_PAR, ONLY : XUNDEF
!
IMPLICIT NONE
!
REAL, DIMENSION(:),INTENT(IN)   :: PFRAC
REAL, DIMENSION(:,:),INTENT(IN)   :: PFIELD_IN
REAL, DIMENSION(:,:), INTENT(OUT) :: PFIELD_OUT
INTEGER, INTENT(IN) :: KTILE
REAL(KIND=JPRB) :: ZHOOK_HANDLE
INTEGER :: JT, JL
!
IF (LHOOK) CALL DR_HOOK('AVERAGE_DIAG:MAKE_AVERAGE_2D',0,ZHOOK_HANDLE)
!
IF (KTILE==1) PFIELD_OUT(:,:) = 0.
!
DO JL=1,SIZE(PFIELD_IN,2)
  WHERE (PFIELD_IN(:,JL)==XUNDEF .AND. PFRAC(:)/=0.) PFIELD_OUT(:,JL) = XUNDEF
  WHERE(PFIELD_OUT(:,JL)/=XUNDEF)
    PFIELD_OUT(:,JL) = PFIELD_OUT(:,JL) + PFRAC(:) * PFIELD_IN(:,JL)
  END WHERE
END DO
!
IF (LHOOK) CALL DR_HOOK('AVERAGE_DIAG:MAKE_AVERAGE_2D',1,ZHOOK_HANDLE)
!
END SUBROUTINE MAKE_AVERAGE_2D
!
SUBROUTINE MAKE_AVERAGE_Z0(PFRAC,PREF,PFIELD_IN,PFIELD_OUT,KTILE)
!
USE MODD_SURF_PAR, ONLY : XUNDEF
!
IMPLICIT NONE
!
REAL, DIMENSION(:),INTENT(IN)   :: PFRAC
REAL, DIMENSION(:),INTENT(IN)   :: PFIELD_IN
REAL, DIMENSION(:),INTENT(IN)   :: PREF
REAL, DIMENSION(:), INTENT(OUT) :: PFIELD_OUT
INTEGER, INTENT(IN) :: KTILE
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
IF (LHOOK) CALL DR_HOOK('AVERAGE_DIAG:MAKE_AVERAGE_Z0',0,ZHOOK_HANDLE)
!
IF (KTILE==1) PFIELD_OUT(:) = 0.
!
WHERE (PFIELD_IN(:)==XUNDEF .AND. PFRAC(:)/=0.) PFIELD_OUT(:) = XUNDEF
!
WHERE (PFIELD_OUT(:)/=XUNDEF) 
  PFIELD_OUT(:) = PFIELD_OUT(:) + PFRAC(:) * 1./(LOG(PREF(:)/PFIELD_IN(:)))**2
END WHERE
!
IF (KTILE==NTILESFC) THEN
  WHERE (PFIELD_OUT(:) == 0.)
    PFIELD_OUT(:) = XUNDEF
  ELSEWHERE (PFIELD_OUT(:)/=XUNDEF)
    PFIELD_OUT(:) = PREF(:) * EXP( - SQRT(1./PFIELD_OUT(:)) )
  ENDWHERE
ENDIF
!
IF (LHOOK) CALL DR_HOOK('AVERAGE_DIAG:MAKE_AVERAGE_Z0',1,ZHOOK_HANDLE)
!
END SUBROUTINE MAKE_AVERAGE_Z0
!
SUBROUTINE MAKE_AVERAGE_MW(PFRAC,PFIELD_IN,PFIELD_OUT,KTILE,PLAND,PSEA,PFRL)
!
USE MODD_SURF_PAR, ONLY : XUNDEF
!
IMPLICIT NONE
!
REAL, DIMENSION(:),INTENT(IN)   :: PFRAC
REAL, DIMENSION(:),INTENT(IN)   :: PFIELD_IN
REAL, DIMENSION(:),  INTENT(OUT)  :: PFIELD_OUT
INTEGER, INTENT(IN) :: KTILE
REAL, DIMENSION(:), INTENT(INOUT) :: PLAND
REAL, DIMENSION(:), INTENT(INOUT) :: PSEA
REAL, DIMENSION(:), INTENT(INOUT) :: PFRL
REAL(KIND=JPRB) :: ZHOOK_HANDLE
INTEGER :: JT
REAL, DIMENSION(SIZE(PFIELD_IN))    :: ZALFA
!
IF (LHOOK) CALL DR_HOOK('AVERAGE_DIAG:MAKE_AVERAGE_MW',0,ZHOOK_HANDLE)
!
IF (KTILE==1) THEN
  PFIELD_OUT(:) = 0.
  PSEA     (:)= 0.
  PLAND    (:)= 0.
  PFRL     (:)= 0.
ENDIF
!
WHERE (PFIELD_IN(:)==XUNDEF .AND. PFRAC(:)/=0.) PFIELD_OUT(:) = XUNDEF
!
IF (KTILE==1.OR.KTILE==2) THEN
  PSEA (:) = PSEA(:)  + PFRAC(:) * PFIELD_IN(:)
ENDIF
!
IF (KTILE==3.OR.KTILE==4) THEN
  PLAND    (:) = PLAND(:) + PFRAC(:) * PFIELD_IN(:)
  PFRL     (:) = PFRL (:) + PFRAC(:)
ENDIF
! 
IF (KTILE==4) THEN
  WHERE(ZFRL(:)>0.)
    ZLAND    (:) = ZLAND(:)/ZFRL(:)
  ENDWHERE
  WHERE(ZFRL(:)<1.)
    ZSEA     (:) = ZSEA (:)/(1.-ZFRL(:))
  ENDWHERE
  !
  ZALFA     (:) = 1. - EXP(-10.*ZFRL(:))
  !
  WHERE (PFIELD_OUT(:)/=XUNDEF) 
    PFIELD_OUT(:) = ZALFA(:) * ZLAND(:) + (1. - ZALFA(:)) * ZSEA(:)
  END WHERE
  !
ENDIF
!
IF (LHOOK) CALL DR_HOOK('AVERAGE_DIAG:MAKE_AVERAGE_MW',1,ZHOOK_HANDLE)
!
END SUBROUTINE MAKE_AVERAGE_MW
!
!-------------------------------------------------------------------------------
!
END SUBROUTINE AVERAGE_DIAG
