!     #########
      SUBROUTINE CONVERT_PATCH_ISBA (DTCO, DTI, IO, KDEC, KDEC2, PCOVER, OCOVER,&
                                     OAGRIP, HSFTYPE, OALB, MX, MT, MM, MI, MA, IP, &
                                     PSOILGRID, PWG1, PWSAT, PPERM )
!     ##############################################################
!
!!**** *CONVERT_PATCH_ISBA* 
!!
!!    PURPOSE
!!    -------
!!
!!    METHOD
!!    ------
!!   
!
!!    EXTERNAL
!!    --------
!!
!!    IMPLICIT ARGUMENTS
!!    ------------------
!!
!!    REFERENCE
!!    ---------
!!
!!    AUTHOR
!!    ------
!!
!!    S. Faroux        Meteo-France
!!
!!    MODIFICATION
!!    ------------
!!
!!    Original    16/11/10
!!      V. Masson    04/14 Garden and Greenroofs can only be initialized by ecoclimap 
!!                         in this routine (not from user specified parameters from
!!                         the nature tile, as the number of points is not the same)
!!    B. Decharme  04/2013  Add CDGAVG (method to average depth)
!!                          Soil depth = Root depth with ISBA-DF
!!                           except for bare soil pft (but limited to 1m)
!!                          With TR_ML (new radiative transfert) and modis
!!                           albedo, UV albedo not defined (conserv nrj when
!!                           coupled to atmosphere)
!!    P Samuelsson  10/2014  MEB
!!
!----------------------------------------------------------------------------
!
!*    0.     DECLARATION
!            -----------
!
!
USE MODD_DATA_COVER_n, ONLY : DATA_COVER_t
USE MODD_DATA_ISBA_n, ONLY : DATA_ISBA_t
USE MODD_ISBA_OPTIONS_n, ONLY : ISBA_OPTIONS_t
USE MODD_ISBA_INIT_n, ONLY : ISBA_INIT_PGD_t
!
USE MODD_ISBA_PARAM_n, ONLY : ISBA_PARAM_FIX_t, ISBA_PARAM_TIME_t, ISBA_PARAM_MEB_t, &
                              ISBA_PARAM_ALB_t, ISBA_PARAM_IRRIG_t
!
USE MODD_DATA_COVER_PAR, ONLY : NVEGTYPE, NVT_NO, NVT_ROCK, NVT_SNOW
!
USE MODD_TYPE_DATE_SURF
!
!
USE MODD_DATA_COVER,     ONLY : XDATA_LAI, XDATA_H_TREE,                &
                                XDATA_VEG, XDATA_Z0, XDATA_Z0_O_Z0H,    &
                                XDATA_EMIS_ECO, XDATA_GAMMA, XDATA_CV,  &
                                XDATA_RGL, XDATA_RSMIN,                 &
                                XDATA_ALBNIR_VEG, XDATA_ALBVIS_VEG,     &
                                XDATA_ALBUV_VEG,                        &
                                XDATA_ALB_VEG_NIR, XDATA_ALB_VEG_VIS,   &
                                XDATA_ALB_SOIL_NIR, XDATA_ALB_SOIL_VIS, &
                                XDATA_GMES, XDATA_BSLAI, XDATA_LAIMIN,  &
                                XDATA_SEFOLD, XDATA_GC, XDATA_WRMAX_CF, &
                                XDATA_STRESS,                           &
                                XDATA_DMAX, XDATA_F2I, XDATA_RE25,      &
                                XDATA_CE_NITRO, XDATA_CF_NITRO,         &
                                XDATA_CNA_NITRO, XDATA_DICE,            &
                                XDATA_GMES_ST, XDATA_BSLAI_ST,          &
                                XDATA_SEFOLD_ST, XDATA_GC_ST,           &
                                XDATA_DMAX_ST, XDATA_WATSUP,            &
                                XDATA_GNDLITTER,                        &
                                XDATA_RGLGV, XDATA_GAMMAGV,             &
                                XDATA_RSMINGV, XDATA_ROOT_DEPTHGV,      &
                                XDATA_WRMAX_CFGV, XDATA_LAIGV,          &
                                XDATA_Z0LITTER, XDATA_H_VEG,            &
                                XDATA_ROOT_EXTINCTIONGV,                &
                                TDATA_SEED, TDATA_REAP,XDATA_IRRIG,     &
                                XDATA_ROOT_DEPTH, XDATA_GROUND_DEPTH,   &
                                XDATA_ROOT_EXTINCTION, XDATA_ROOT_LIN
!   
!
USE MODD_TREEDRAG,       ONLY : LTREEDRAG
!
USE MODI_AV_PGD_PARAM
USE MODI_AV_PGD
USE MODI_SOIL_ALBEDO
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE
!
!*    0.1    Declaration of arguments
!            ------------------------
!
!
TYPE(DATA_COVER_t), INTENT(INOUT) :: DTCO
TYPE(DATA_ISBA_t), INTENT(INOUT) :: DTI
TYPE(ISBA_OPTIONS_t), INTENT(INOUT) :: IO
!
INTEGER,                INTENT(IN)    :: KDEC
INTEGER,                INTENT(IN)    :: KDEC2
REAL, DIMENSION(:,:),   INTENT(IN)    :: PCOVER
LOGICAL, DIMENSION(:),  INTENT(IN)    :: OCOVER
LOGICAL,                INTENT(IN)    :: OAGRIP
CHARACTER(LEN=*),       INTENT(IN)    :: HSFTYPE ! nature / garden
!
LOGICAL, INTENT(IN) :: OALB
!
TYPE(ISBA_PARAM_FIX_t), OPTIONAL, INTENT(INOUT) :: MX
TYPE(ISBA_PARAM_TIME_t), OPTIONAL, INTENT(INOUT) :: MT
TYPE(ISBA_PARAM_MEB_t), OPTIONAL, INTENT(INOUT) :: MM
TYPE(ISBA_PARAM_ALB_t), OPTIONAL, INTENT(INOUT) :: MA
TYPE(ISBA_PARAM_IRRIG_t), OPTIONAL, INTENT(INOUT) :: MI
TYPE(ISBA_INIT_PGD_t), OPTIONAL, INTENT(INOUT) :: IP
!
REAL, DIMENSION(:,:),   OPTIONAL, INTENT(IN)   :: PWG1
REAL, DIMENSION(:,:),   OPTIONAL, INTENT(IN)   :: PWSAT
REAL, DIMENSION(:),   OPTIONAL, INTENT(IN)   :: PPERM
!
REAL, DIMENSION(:)  ,   OPTIONAL, INTENT(IN)    :: PSOILGRID
!
!*    0.2    Declaration of local variables
!            ------------------------------
!
 CHARACTER(LEN=3)  :: YTREE, YNAT, YLAI, YVEG, YBAR, YDIF
!
INTEGER               :: JLAYER    ! loop counter on layers
INTEGER               :: JVEGTYPE  ! loop counter on vegtypes
!
LOGICAL               :: GDATA     ! Flag where initialization can be done
!                                  ! either with ecoclimap of data fields specified
!                                  ! by user on the natural points (GDTA=T)
!                                  ! For fields in town, only ecoclimap option
!                                  ! is treated in this routine (GDATA=F)
INTEGER               :: JJ        ! loop counter
!
INTEGER               :: ISIZE_LMEB_PATCH  ! Number of patches with MEB=true
!
REAL, ALLOCATABLE, DIMENSION(:) :: ZH_VEG
!
!
!*    0.3    Declaration of namelists
!            ------------------------
!
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!-------------------------------------------------------------------------------
!
!*    1.      Initializations
!             ---------------
!
IF (LHOOK) CALL DR_HOOK('CONVERT_PATCH_ISBA',0,ZHOOK_HANDLE)
!
IF (ASSOCIATED(DTCO%XDATA_WEIGHT)) DEALLOCATE(DTCO%XDATA_WEIGHT)
!
IF (HSFTYPE=='NAT') THEN
  YNAT='NAT'
  YTREE='TRE'
  YLAI='LAI'
  YVEG='VEG'
  YBAR='BAR'
  YDIF='DVG'
  GDATA=.TRUE.
  ISIZE_LMEB_PATCH = COUNT(IO%LMEB_PATCH(:))
ELSEIF (HSFTYPE=='GRD') THEN
  YNAT='GRD'
  YTREE='GRT'
  YLAI='GRL'
  YVEG='GRV'
  YBAR='GRB'
  YDIF='GDV'
  GDATA=.FALSE.
  ISIZE_LMEB_PATCH = 0
ENDIF
!
! vegtypes fraction
! -----------------
!
IF (PRESENT(MX)) THEN
  !
  IF (GDATA .AND. DTI%LDATA_VEGTYPE) THEN
    MX%XVEGTYPE=DTI%XPAR_VEGTYPE
  ELSE
    !classical ecoclimap case
    DO JVEGTYPE=1,NVEGTYPE
      CALL AV_PGD(DTCO, MX%XVEGTYPE(:,JVEGTYPE),PCOVER ,DTCO%XDATA_VEGTYPE(:,JVEGTYPE),YNAT,'ARI',OCOVER)
    END DO
  ENDIF
  !
  !* soil layers and root fraction
!  -----------------------------
  !
  !   compute soil layers (and root fraction if DIF)
  !
  CALL SET_GRID_PARAM(SIZE(MX%XDG,1),SIZE(MX%XDG,2),SIZE(MX%XDG,3))
!
!        D ICE
!        -----
!
  IF (IO%CISBA/='DIF') THEN
    IF (GDATA .AND. DTI%LDATA_DICE) THEN
      CALL AV_PGD_PARAM(DTI%XPAR_LAI, DTI%XPAR_VEG, &
                        MX%XD_ICE,DTI%XPAR_VEGTYPE,DTI%XPAR_DICE,YNAT,'ARI')
    ELSE
      CALL AV_PGD(DTCO, MX%XD_ICE,PCOVER,XDATA_DICE(:,:),YNAT,'ARI',OCOVER,KDECADE=KDEC)
    ENDIF
  ENDIF
!
  IF (GDATA .AND. DTI%LDATA_Z0_O_Z0H) THEN
    CALL AV_PGD_PARAM(DTI%XPAR_LAI, DTI%XPAR_VEG, &
                      MX%XZ0_O_Z0H,DTI%XPAR_VEGTYPE,DTI%XPAR_Z0_O_Z0H,YNAT,'ARI')
  ELSE
    CALL AV_PGD(DTCO, MX%XZ0_O_Z0H,PCOVER,XDATA_Z0_O_Z0H,YNAT,'ARI',OCOVER,KDECADE=KDEC)
  ENDIF
!
  IF (IO%CPHOTO/='NON'.OR.LTREEDRAG) THEN
    IF (GDATA .AND. DTI%LDATA_H_TREE) THEN
      CALL AV_PGD_PARAM(DTI%XPAR_LAI, DTI%XPAR_VEG, &
                      MX%XH_TREE,DTI%XPAR_VEGTYPE,DTI%XPAR_H_TREE,YTREE,'ARI')
    ELSE
      CALL AV_PGD(DTCO, MX%XH_TREE,PCOVER,XDATA_H_TREE(:,:),YTREE,'ARI',OCOVER,KDECADE=KDEC)
    ENDIF
  ENDIF
!
  IF (IO%CPHOTO/='NON') THEN
    !
    IF (SIZE(MX%XRE25)>0) THEN
      IF (GDATA .AND. DTI%LDATA_RE25) THEN
        CALL AV_PGD_PARAM(DTI%XPAR_LAI, DTI%XPAR_VEG, &
                      MX%XRE25,DTI%XPAR_VEGTYPE,DTI%XPAR_RE25,YNAT,'ARI')      
      ELSE
        CALL AV_PGD(DTCO, MX%XRE25,PCOVER,XDATA_RE25,YNAT,'ARI',OCOVER,KDECADE=KDEC)  
      ENDIF
    ENDIF
    !
    IF (SIZE(MX%XDMAX)>0) THEN
      IF (GDATA .AND. DTI%LDATA_DMAX) THEN
        CALL AV_PGD_PARAM(DTI%XPAR_LAI, DTI%XPAR_VEG, &
                      MX%XDMAX,DTI%XPAR_VEGTYPE,DTI%XPAR_DMAX,YTREE,'ARI')
      ELSEIF (IO%CPHOTO == 'AST' .OR. IO%CPHOTO == 'LST' .OR. IO%CPHOTO == 'NIT' .OR. IO%CPHOTO == 'NCB') THEN
        CALL AV_PGD(DTCO, MX%XDMAX,PCOVER,XDATA_DMAX_ST,YTREE,'ARI',OCOVER,KDECADE=KDEC)  
      ELSE
        CALL AV_PGD(DTCO, MX%XDMAX,PCOVER,XDATA_DMAX,YTREE,'ARI',OCOVER,KDECADE=KDEC)
      ENDIF
    ENDIF
    !
  ENDIF
!
ENDIF
!
IF (PRESENT(MT)) THEN
!
 IF (.NOT.OALB) THEN
!   VEG
!   ----
  IF (GDATA .AND. DTI%LDATA_VEG) THEN
    CALL AV_PGD_PARAM(DTI%XPAR_LAI, DTI%XPAR_VEG, MT%XVEG,DTI%XPAR_VEGTYPE,DTI%XPAR_VEG(:,KDEC2,:),YNAT,'ARI')
  ELSE
    CALL AV_PGD(DTCO, MT%XVEG,PCOVER,XDATA_VEG(:,KDEC,:),YNAT,'ARI',OCOVER,KDECADE=KDEC)
  ENDIF
!
!   LAI
!   ----
  IF (GDATA .AND. DTI%LDATA_LAI) THEN
    CALL AV_PGD_PARAM(DTI%XPAR_LAI, DTI%XPAR_VEG, &
                      MT%XLAI,DTI%XPAR_VEGTYPE,DTI%XPAR_LAI(:,KDEC2,:),YVEG,'ARI',KDECADE=KDEC2)
  ELSE
    CALL AV_PGD(DTCO, MT%XLAI,PCOVER,XDATA_LAI(:,KDEC,:),YVEG,'ARI',OCOVER,KDECADE=KDEC)
  ENDIF
!
!           EMIS
!           ----
!emis needs VEG by vegtypes is changed at this step
  IF (GDATA .AND. DTI%LDATA_EMIS) THEN
    CALL AV_PGD_PARAM(DTI%XPAR_LAI, DTI%XPAR_VEG, &
                      MT%XEMIS ,DTI%XPAR_VEGTYPE,DTI%XPAR_EMIS(:,KDEC2,:),YNAT,'ARI')
  ELSE
    CALL AV_PGD(DTCO, MT%XEMIS ,PCOVER ,XDATA_EMIS_ECO (:,KDEC,:),YNAT,'ARI',OCOVER,KDECADE=KDEC)
  ENDIF
!
!    Z0V
!    ----
  IF (GDATA .AND. DTI%LDATA_Z0) THEN
    CALL AV_PGD_PARAM(DTI%XPAR_LAI, DTI%XPAR_VEG, &
                      MT%XZ0,DTI%XPAR_VEGTYPE,DTI%XPAR_Z0(:,KDEC2,:),YNAT,'CDN')
  ELSE
    CALL AV_PGD(DTCO, MT%XZ0 ,PCOVER ,XDATA_Z0 (:,KDEC,:),YNAT,'CDN',OCOVER,KDECADE=KDEC)
  ENDIF
!
 ENDIF

  IF (GDATA .AND. DTI%LDATA_ALBNIR_VEG) THEN
    CALL AV_PGD_PARAM(DTI%XPAR_LAI, DTI%XPAR_VEG, &
                      MT%XALBNIR_VEG,DTI%XPAR_VEGTYPE,DTI%XPAR_ALBNIR_VEG,YVEG,'ARI',KDECADE=KDEC2)
  ELSEIF (IO%CALBEDO=='CM13') THEN
    CALL AV_PGD(DTCO, MT%XALBNIR_VEG,PCOVER,XDATA_ALB_VEG_NIR(:,KDEC,:),YVEG,'ARI', OCOVER,KDECADE=KDEC)    
  ELSE
    CALL AV_PGD(DTCO, MT%XALBNIR_VEG,PCOVER,XDATA_ALBNIR_VEG,YVEG,'ARI',OCOVER,KDECADE=KDEC)  
  ENDIF
!
  IF (GDATA .AND. DTI%LDATA_ALBVIS_VEG) THEN
    CALL AV_PGD_PARAM(DTI%XPAR_LAI, DTI%XPAR_VEG, &
                      MT%XALBVIS_VEG,DTI%XPAR_VEGTYPE,DTI%XPAR_ALBVIS_VEG,YVEG,'ARI',KDECADE=KDEC2)
  ELSEIF (IO%CALBEDO=='CM13') THEN
    CALL AV_PGD(DTCO, MT%XALBVIS_VEG,PCOVER,XDATA_ALB_VEG_VIS(:,KDEC,:),YVEG,'ARI',OCOVER,KDECADE=KDEC)      
  ELSE
    CALL AV_PGD(DTCO, MT%XALBVIS_VEG,PCOVER,XDATA_ALBVIS_VEG,YVEG,'ARI',OCOVER,KDECADE=KDEC)  
  ENDIF
!
  IF ((IO%CALBEDO=='CM13'.OR.IO%LTR_ML)) THEN
    MT%XALBUV_VEG(:,:)=MT%XALBVIS_VEG(:,:)
  ELSEIF (GDATA .AND. DTI%LDATA_ALBUV_VEG) THEN
    CALL AV_PGD_PARAM(DTI%XPAR_LAI, DTI%XPAR_VEG, &
                      MT%XALBUV_VEG,DTI%XPAR_VEGTYPE,DTI%XPAR_ALBUV_VEG,YVEG,'ARI',KDECADE=KDEC2)
  ELSE
    CALL AV_PGD(DTCO, MT%XALBUV_VEG,PCOVER,XDATA_ALBUV_VEG,YVEG,'ARI',OCOVER,KDECADE=KDEC)  
  ENDIF
!
 IF (.NOT.OALB) THEN
!        Other parameters
!        ----------------
  IF( SIZE(MT%XRSMIN)>0) THEN
    IF (GDATA .AND. DTI%LDATA_RSMIN) THEN
      CALL AV_PGD_PARAM(DTI%XPAR_LAI, DTI%XPAR_VEG, &
                      MT%XRSMIN,DTI%XPAR_VEGTYPE,DTI%XPAR_RSMIN,YLAI,'INV',KDECADE=KDEC2)
    ELSE
      CALL AV_PGD(DTCO, MT%XRSMIN,PCOVER,XDATA_RSMIN,YLAI,'INV',OCOVER,KDECADE=KDEC)  
    ENDIF
  ENDIF
!
  IF (GDATA .AND. DTI%LDATA_GAMMA) THEN
    CALL AV_PGD_PARAM(DTI%XPAR_LAI, DTI%XPAR_VEG, &
                      MT%XGAMMA,DTI%XPAR_VEGTYPE,DTI%XPAR_GAMMA,YVEG,'ARI',KDECADE=KDEC2)
  ELSE
    CALL AV_PGD(DTCO, MT%XGAMMA,PCOVER,XDATA_GAMMA,YVEG,'ARI',OCOVER,KDECADE=KDEC)  
  ENDIF
!
  IF (GDATA .AND. DTI%LDATA_WRMAX_CF) THEN
    CALL AV_PGD_PARAM(DTI%XPAR_LAI, DTI%XPAR_VEG, &
                      MT%XWRMAX_CF,DTI%XPAR_VEGTYPE,DTI%XPAR_WRMAX_CF,YVEG,'ARI',KDECADE=KDEC2)
  ELSE
    CALL AV_PGD(DTCO, MT%XWRMAX_CF,PCOVER,XDATA_WRMAX_CF,YVEG,'ARI',OCOVER,KDECADE=KDEC)  
  ENDIF
!
  IF (GDATA .AND. DTI%LDATA_RGL) THEN
    CALL AV_PGD_PARAM(DTI%XPAR_LAI, DTI%XPAR_VEG, &
                      MT%XRGL,DTI%XPAR_VEGTYPE,DTI%XPAR_RGL,YVEG,'ARI',KDECADE=KDEC2)
  ELSE
    CALL AV_PGD(DTCO, MT%XRGL,PCOVER,XDATA_RGL,YVEG,'ARI',OCOVER,KDECADE=KDEC)  
  ENDIF
!
  IF (GDATA .AND. DTI%LDATA_CV) THEN
    CALL AV_PGD_PARAM(DTI%XPAR_LAI, DTI%XPAR_VEG, &
                      MT%XCV,DTI%XPAR_VEGTYPE,DTI%XPAR_CV,YVEG,'INV',KDECADE=KDEC2)
  ELSE
    CALL AV_PGD(DTCO, MT%XCV,PCOVER,XDATA_CV,YVEG,'INV',OCOVER,KDECADE=KDEC)  
  ENDIF
!
  IF (ISIZE_LMEB_PATCH>0 .OR. IO%CPHOTO/='NON') THEN

    IF( SIZE(MT%XBSLAI)>0) THEN
      IF (GDATA .AND. DTI%LDATA_BSLAI) THEN
        CALL AV_PGD_PARAM(DTI%XPAR_LAI, DTI%XPAR_VEG, &
                      MT%XBSLAI,DTI%XPAR_VEGTYPE,DTI%XPAR_BSLAI,YVEG,'ARI',KDECADE=KDEC2)
      ELSEIF (IO%CPHOTO == 'AST' .OR. IO%CPHOTO == 'LST' .OR. IO%CPHOTO == 'NIT' .OR. IO%CPHOTO == 'NCB') THEN
        CALL AV_PGD(DTCO, MT%XBSLAI,PCOVER,XDATA_BSLAI_ST,YVEG,'ARI',OCOVER,KDECADE=KDEC)  
      ELSE
        CALL AV_PGD(DTCO, MT%XBSLAI,PCOVER,XDATA_BSLAI,YVEG,'ARI',OCOVER,KDECADE=KDEC)
      ENDIF
    ENDIF
  ENDIF
!
  IF (IO%CPHOTO/='NON') THEN
  !
    IF (SIZE(MT%XLAIMIN)>0) THEN
      IF (GDATA .AND. DTI%LDATA_LAIMIN) THEN
        CALL AV_PGD_PARAM(DTI%XPAR_LAI, DTI%XPAR_VEG, &
                      MT%XLAIMIN,DTI%XPAR_VEGTYPE,DTI%XPAR_LAIMIN,YVEG,'ARI',KDECADE=KDEC2)
      ELSE
        CALL AV_PGD(DTCO, MT%XLAIMIN,PCOVER,XDATA_LAIMIN,YVEG,'ARI',OCOVER,KDECADE=KDEC)  
      ENDIF
    ENDIF    
  !
    IF (SIZE(MT%XSEFOLD)>0) THEN
      IF (GDATA .AND. DTI%LDATA_SEFOLD) THEN
        CALL AV_PGD_PARAM(DTI%XPAR_LAI, DTI%XPAR_VEG, &
                      MT%XSEFOLD,DTI%XPAR_VEGTYPE,DTI%XPAR_SEFOLD,YVEG,'ARI',KDECADE=KDEC2)
      ELSEIF (IO%CPHOTO == 'AST' .OR. IO%CPHOTO == 'LST' .OR. IO%CPHOTO == 'NIT' .OR. IO%CPHOTO == 'NCB') THEN
        CALL AV_PGD(DTCO, MT%XSEFOLD,PCOVER,XDATA_SEFOLD_ST,YVEG,'ARI',OCOVER,KDECADE=KDEC)  
      ELSE
        CALL AV_PGD(DTCO, MT%XSEFOLD,PCOVER,XDATA_SEFOLD,YVEG,'ARI',OCOVER,KDECADE=KDEC)
      ENDIF
    ENDIF
    !
    IF ( SIZE(MT%XGMES)>0) THEN
      IF (GDATA .AND. DTI%LDATA_GMES) THEN
        CALL AV_PGD_PARAM(DTI%XPAR_LAI, DTI%XPAR_VEG, &
                      MT%XGMES,DTI%XPAR_VEGTYPE,DTI%XPAR_GMES,YVEG,'ARI',KDECADE=KDEC2)
      ELSEIF (IO%CPHOTO == 'AST' .OR. IO%CPHOTO == 'LST' .OR. IO%CPHOTO == 'NIT' .OR. IO%CPHOTO == 'NCB') THEN
        CALL AV_PGD(DTCO, MT%XGMES,PCOVER,XDATA_GMES_ST,YVEG,'ARI',OCOVER,KDECADE=KDEC)  
      ELSE
        CALL AV_PGD(DTCO, MT%XGMES,PCOVER,XDATA_GMES,YVEG,'ARI',OCOVER,KDECADE=KDEC)
      ENDIF
    ENDIF
    !
    IF ( SIZE(MT%XGC)>0) THEN
      IF (GDATA .AND. DTI%LDATA_GC) THEN
        CALL AV_PGD_PARAM(DTI%XPAR_LAI, DTI%XPAR_VEG, &
                          MT%XGC,DTI%XPAR_VEGTYPE,DTI%XPAR_GC,YVEG,'ARI',KDECADE=KDEC2)
      ELSEIF (IO%CPHOTO == 'AST' .OR. IO%CPHOTO == 'LST' .OR. IO%CPHOTO == 'NIT' .OR. IO%CPHOTO == 'NCB') THEN
        CALL AV_PGD(DTCO, MT%XGC,PCOVER,XDATA_GC_ST,YVEG,'ARI',OCOVER,KDECADE=KDEC)  
      ELSE
        CALL AV_PGD(DTCO, MT%XGC,PCOVER,XDATA_GC,YVEG,'ARI',OCOVER,KDECADE=KDEC)
      ENDIF
    ENDIF
    !
    IF (IO%CPHOTO/='AGS' .AND. IO%CPHOTO/='LAI') THEN
    !
      IF (SIZE(MT%XF2I)>0) THEN
        IF (GDATA .AND. DTI%LDATA_F2I) THEN
          CALL AV_PGD_PARAM(DTI%XPAR_LAI, DTI%XPAR_VEG, &
                      MT%XF2I,DTI%XPAR_VEGTYPE,DTI%XPAR_F2I,YVEG,'ARI',KDECADE=KDEC2)
        ELSE
          CALL AV_PGD(DTCO, MT%XF2I,PCOVER,XDATA_F2I,YVEG,'ARI',OCOVER,KDECADE=KDEC)  
        ENDIF
      ENDIF
      !
      IF (IO%CPHOTO=='NIT' .OR. IO%CPHOTO=='NCB') THEN
      !
        IF (SIZE(MT%XCE_NITRO)>0) THEN
          IF (GDATA .AND. DTI%LDATA_CE_NITRO) THEN
            CALL AV_PGD_PARAM(DTI%XPAR_LAI, DTI%XPAR_VEG, &
                      MT%XCE_NITRO,DTI%XPAR_VEGTYPE,DTI%XPAR_CE_NITRO,YVEG,'ARI',KDECADE=KDEC2)
          ELSE
            CALL AV_PGD(DTCO, MT%XCE_NITRO,PCOVER,XDATA_CE_NITRO,YVEG,'ARI',OCOVER,KDECADE=KDEC)  
          ENDIF
        ENDIF
        !
        IF (SIZE(MT%XCF_NITRO)>0) THEN
          IF (GDATA .AND. DTI%LDATA_CF_NITRO) THEN
            CALL AV_PGD_PARAM(DTI%XPAR_LAI, DTI%XPAR_VEG, &
                      MT%XCF_NITRO,DTI%XPAR_VEGTYPE,DTI%XPAR_CF_NITRO,YVEG,'ARI',KDECADE=KDEC2)
          ELSE
            CALL AV_PGD(DTCO, MT%XCF_NITRO,PCOVER,XDATA_CF_NITRO,YVEG,'ARI',OCOVER,KDECADE=KDEC)  
          ENDIF
        ENDIF
        !
        IF (SIZE(MT%XCNA_NITRO)>0) THEN
          IF (GDATA .AND. DTI%LDATA_CNA_NITRO) THEN
            CALL AV_PGD_PARAM(DTI%XPAR_LAI, DTI%XPAR_VEG, &
                      MT%XCNA_NITRO,DTI%XPAR_VEGTYPE,DTI%XPAR_CNA_NITRO,YVEG,'ARI',KDECADE=KDEC2)
          ELSE
            CALL AV_PGD(DTCO, MT%XCNA_NITRO,PCOVER,XDATA_CNA_NITRO,YVEG,'ARI',OCOVER,KDECADE=KDEC)  
          ENDIF
        ENDIF
        !
      ENDIF
      !
    ENDIF
    !
  ENDIF
!
!       STRESS
!       --------
  IF (SIZE(MT%LSTRESS)>0) THEN
    CALL SET_STRESS(SIZE(MT%LSTRESS,1),SIZE(MT%LSTRESS,2))      
  ENDIF
!
 ENDIF
!
ENDIF
!
IF (PRESENT(MM) .AND. .NOT.OALB) THEN
  !
!   GNDLITTER
!   ---------
  IF (GDATA .AND. DTI%LDATA_GNDLITTER) THEN
    CALL AV_PGD_PARAM(DTI%XPAR_LAI, DTI%XPAR_VEG, MM%XGNDLITTER,DTI%XPAR_VEGTYPE,&
                        DTI%XPAR_GNDLITTER(:,KDEC2,:),YNAT,'ARI',KDECADE=KDEC2)
  ELSE
    CALL AV_PGD(DTCO, MM%XGNDLITTER,PCOVER,XDATA_GNDLITTER(:,KDEC,:),YNAT,'ARI',OCOVER,KDECADE=KDEC)
  ENDIF
!
!   LAIGV
!   ----
  IF (GDATA .AND. DTI%LDATA_LAIGV) THEN
    CALL AV_PGD_PARAM(DTI%XPAR_LAI, DTI%XPAR_VEG, &
                      MM%XLAIGV,DTI%XPAR_VEGTYPE,DTI%XPAR_LAIGV(:,KDEC2,:),YVEG,'ARI',KDECADE=KDEC2)
  ELSE
    CALL AV_PGD(DTCO, MM%XLAIGV,PCOVER,XDATA_LAIGV(:,KDEC,:),YVEG,'ARI',OCOVER,KDECADE=KDEC)
  ENDIF
!
!        H_VEG
!        -----
  IF (GDATA .AND. DTI%LDATA_H_VEG) THEN
    CALL AV_PGD_PARAM(DTI%XPAR_LAI, DTI%XPAR_VEG, &
                      MM%XH_VEG,DTI%XPAR_VEGTYPE,DTI%XPAR_H_VEG(:,KDEC2,:),YVEG,'ARI',KDECADE=KDEC2)
  ELSE
    CALL AV_PGD(DTCO, MM%XH_VEG,PCOVER,XDATA_H_VEG(:,KDEC,:),YVEG,'ARI',OCOVER,KDECADE=KDEC)
  ENDIF
! In case of MEB, force 0<PH_VEG<XUNDEF for those patches where LMEB_PATCH=.T.
  IF (ISIZE_LMEB_PATCH>0)THEN
    ALLOCATE(ZH_VEG(SIZE(MM%XH_VEG,1)))
    DO JJ=1,SIZE(IO%LMEB_PATCH)
      IF(IO%LMEB_PATCH(JJ))THEN
        ZH_VEG=MM%XH_VEG(:,JJ)
        WHERE(ZH_VEG>1000.) ZH_VEG=0.
        ZH_VEG=MAX(ZH_VEG,1.0E-3)
        MM%XH_VEG(:,JJ)=ZH_VEG
      ENDIF
    ENDDO
  ENDIF
!
!    Z0LITTER
!    --------
  IF (GDATA .AND. DTI%LDATA_Z0LITTER) THEN
    CALL AV_PGD_PARAM(DTI%XPAR_LAI, DTI%XPAR_VEG, &
                      MM%XZ0LITTER,DTI%XPAR_VEGTYPE,DTI%XPAR_Z0LITTER(:,KDEC2,:),YNAT,'CDN')
  ELSE
    CALL AV_PGD(DTCO, MM%XZ0LITTER ,PCOVER ,XDATA_Z0LITTER (:,KDEC,:),YNAT,'CDN',OCOVER)
  ENDIF
!
  IF( SIZE(MM%XRSMINGV)>0) THEN
    IF (GDATA .AND. DTI%LDATA_RSMINGV) THEN
      CALL AV_PGD_PARAM(DTI%XPAR_LAI, DTI%XPAR_VEG, &
                      MM%XRSMINGV,DTI%XPAR_VEGTYPE,DTI%XPAR_RSMINGV,YLAI,'INV',KDECADE=KDEC2)
    ELSE
      CALL AV_PGD(DTCO, MM%XRSMINGV,PCOVER,XDATA_RSMINGV,YLAI,'INV',OCOVER,KDECADE=KDEC)  
    ENDIF
  ENDIF
!
  IF (GDATA .AND. DTI%LDATA_GAMMAGV) THEN
    CALL AV_PGD_PARAM(DTI%XPAR_LAI, DTI%XPAR_VEG, &
                      MM%XGAMMAGV,DTI%XPAR_VEGTYPE,DTI%XPAR_GAMMAGV,YVEG,'ARI',KDECADE=KDEC2)
  ELSE
    CALL AV_PGD(DTCO, MM%XGAMMAGV,PCOVER,XDATA_GAMMAGV,YVEG,'ARI',OCOVER,KDECADE=KDEC)  
  ENDIF
!
  IF (GDATA .AND. DTI%LDATA_WRMAX_CFGV) THEN
    CALL AV_PGD_PARAM(DTI%XPAR_LAI, DTI%XPAR_VEG, &
                      MM%XWRMAX_CFGV,DTI%XPAR_VEGTYPE,DTI%XPAR_WRMAX_CFGV,YVEG,'ARI',KDECADE=KDEC2)
  ELSE
    CALL AV_PGD(DTCO, MM%XWRMAX_CFGV,PCOVER,XDATA_WRMAX_CFGV,YVEG,'ARI',OCOVER,KDECADE=KDEC)  
  ENDIF
!
  IF (GDATA .AND. DTI%LDATA_RGLGV) THEN
    CALL AV_PGD_PARAM(DTI%XPAR_LAI, DTI%XPAR_VEG, &
                      MM%XRGLGV,DTI%XPAR_VEGTYPE,DTI%XPAR_RGLGV,YVEG,'ARI',KDECADE=KDEC2)
  ELSE
    CALL AV_PGD(DTCO, MM%XRGLGV,PCOVER,XDATA_RGLGV,YVEG,'ARI',OCOVER,KDECADE=KDEC)  
  ENDIF
!
ENDIF
!
IF (PRESENT(MI) .AND. .NOT.OALB) THEN
!
  IF ((IO%CPHOTO == 'LAI' .OR. IO%CPHOTO == 'LST' .OR. IO%CPHOTO == 'NIT' .OR. IO%CPHOTO=='NCB') .AND. OAGRIP)  THEN
  !
  ! date of seeding
  ! ---------------
  !
     IF(SIZE(MI%TSEED)>0) THEN
      CALL AV_PGD (MI%TSEED ,PCOVER,TDATA_SEED(:,:),YVEG,'MAJ',OCOVER,KDECADE=KDEC)  
     ENDIF
  !
  ! date of reaping
  ! ---------------
  !
    IF (SIZE(MI%TREAP)>0) THEN
      CALL AV_PGD (MI%TREAP ,PCOVER,TDATA_REAP(:,:),YVEG,'MAJ',OCOVER,KDECADE=KDEC)  
    ENDIF
  !
    IF (SIZE(MI%XIRRIG)>0) THEN
      IF (GDATA .AND. DTI%LDATA_IRRIG) THEN
        CALL AV_PGD_PARAM(DTI%XPAR_LAI, DTI%XPAR_VEG, &
                      MI%XIRRIG,DTI%XPAR_VEGTYPE,DTI%XPAR_IRRIG(:,KDEC2,:),YVEG,'ARI',KDECADE=KDEC2)
      ELSE
        CALL AV_PGD(DTCO, MI%XIRRIG,PCOVER,XDATA_IRRIG,YVEG,'ARI',OCOVER,KDECADE=KDEC)  
      ENDIF
    ENDIF
!
    IF (SIZE(MI%XWATSUP)>0) THEN
      IF (GDATA .AND. DTI%LDATA_WATSUP) THEN
        CALL AV_PGD_PARAM(DTI%XPAR_LAI, DTI%XPAR_VEG, &
                      MI%XWATSUP,DTI%XPAR_VEGTYPE,DTI%XPAR_WATSUP(:,KDEC2,:),YVEG,'ARI',KDECADE=KDEC2)
      ELSE
        CALL AV_PGD(DTCO, MI%XWATSUP,PCOVER,XDATA_WATSUP,YVEG,'ARI',OCOVER,KDECADE=KDEC)  
      ENDIF
    ENDIF
    !
  ENDIF
!
ENDIF
!
IF (PRESENT(MA)) THEN
!
  IF (GDATA .AND. DTI%LDATA_ALBNIR_SOIL) THEN
    CALL AV_PGD_PARAM(DTI%XPAR_LAI, DTI%XPAR_VEG, &
                      MA%XALBNIR_SOIL,DTI%XPAR_VEGTYPE,DTI%XPAR_ALBNIR_SOIL,YBAR,'ARI',KDECADE=KDEC2)
  ELSEIF (IO%CALBEDO=='CM13') THEN
    CALL AV_PGD(DTCO, MA%XALBNIR_SOIL,PCOVER,XDATA_ALB_SOIL_NIR(:,KDEC,:),YBAR,'ARI',OCOVER,KDECADE=KDEC)
  ELSE
    !CALL SOIL_ALBEDO (IO%CALBEDO, PWSAT(:,1), PWG1, IP, MA, "NIR" )
  ENDIF
!
  IF (GDATA .AND. DTI%LDATA_ALBVIS_SOIL) THEN
    CALL AV_PGD_PARAM(DTI%XPAR_LAI, DTI%XPAR_VEG, &
                      MA%XALBVIS_SOIL,DTI%XPAR_VEGTYPE,DTI%XPAR_ALBVIS_SOIL,YBAR,'ARI',KDECADE=KDEC2)
  ELSEIF (IO%CALBEDO=='CM13') THEN
    CALL AV_PGD(DTCO, MA%XALBVIS_SOIL,PCOVER,XDATA_ALB_SOIL_VIS(:,KDEC,:),YBAR,'ARI',OCOVER,KDECADE=KDEC)    
  ELSE
   !CALL SOIL_ALBEDO (IO%CALBEDO, PWSAT(:,1), PWG1, IP, MA, "VIS" )
  ENDIF
!

  IF (IO%CALBEDO=='CM13'.OR.IO%LTR_ML) THEN
    MA%XALBUV_SOIL(:,:)=MA%XALBVIS_SOIL(:,:)
  ELSEIF (GDATA .AND. DTI%LDATA_ALBUV_SOIL) THEN
    CALL AV_PGD_PARAM(DTI%XPAR_LAI, DTI%XPAR_VEG, &
                      MA%XALBUV_SOIL,DTI%XPAR_VEGTYPE,DTI%XPAR_ALBUV_SOIL,YNAT,'ARI',KDECADE=KDEC2)
  ELSE
   ! CALL SOIL_ALBEDO (IO%CALBEDO, PWSAT(:,1), PWG1, IP, MA, "UV"  )
  ENDIF
!
ENDIF
!
IF (ASSOCIATED(DTCO%XDATA_WEIGHT)) DEALLOCATE(DTCO%XDATA_WEIGHT)
!
IF (LHOOK) CALL DR_HOOK('CONVERT_PATCH_ISBA',1,ZHOOK_HANDLE)
!
!-------------------------------------------------------------------------------
CONTAINS
!-------------------------------------------------------------------------------
!
SUBROUTINE SET_STRESS(KSIZE1,KSIZE2)
!
IMPLICIT NONE
!
INTEGER, INTENT(IN) :: KSIZE1
INTEGER, INTENT(IN) :: KSIZE2
!
REAL, DIMENSION(KSIZE1,KSIZE2)   :: ZWORK
REAL, DIMENSION(KSIZE1,NVEGTYPE) :: ZSTRESS
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
IF (LHOOK) CALL DR_HOOK('CONVERT_PATCH_ISBA:SET_STRESS',0,ZHOOK_HANDLE)
!
IF (GDATA .AND. DTI%LDATA_STRESS) THEN
  ZSTRESS(:,:)=0.
  DO JVEGTYPE=1,NVEGTYPE
    WHERE (DTI%LPAR_STRESS(:,JVEGTYPE)) ZSTRESS(:,JVEGTYPE)=1.
  ENDDO
  CALL AV_PGD_PARAM(DTI%XPAR_LAI, DTI%XPAR_VEG, &
                      ZWORK,DTI%XPAR_VEGTYPE,ZSTRESS,YVEG,'ARI',KDECADE=KDEC2)
ELSE
  CALL AV_PGD(DTCO, ZWORK,PCOVER,XDATA_STRESS(:,:),YVEG,'ARI',OCOVER,KDECADE=KDEC)
ENDIF
!
WHERE (ZWORK(:,:)<0.5)
  MT%LSTRESS(:,:) = .FALSE.
ELSEWHERE
  MT%LSTRESS(:,:) = .TRUE.
END WHERE
!
IF (LHOOK) CALL DR_HOOK('CONVERT_PATCH_ISBA:SET_STRESS',1,ZHOOK_HANDLE)
END SUBROUTINE SET_STRESS
!
!-------------------------------------------------------------------------------
SUBROUTINE SET_GRID_PARAM(KNI,KGROUND,KPATCH )
!
USE MODD_SURF_PAR, ONLY : XUNDEF, NUNDEF
USE MODD_ISBA_PAR, ONLY : XPERMFRAC
!
USE MODD_REPROD_OPER, ONLY : CDGAVG, CDGDIF
!
USE MODI_INI_DATA_ROOTFRAC
USE MODI_INI_DATA_SOIL
USE MODI_PERMAFROST_DEPTH
USE MODI_ABOR1_SFX
!
IMPLICIT NONE
!
REAL, PARAMETER     :: ZPREC=1.0E+6
!
INTEGER, INTENT(IN) :: KNI
INTEGER, INTENT(IN) :: KGROUND
INTEGER, INTENT(IN) :: KPATCH
!
REAL,    DIMENSION (SIZE(XDATA_GROUND_DEPTH,1),NVEGTYPE) :: ZDATA_GROUND_DEPTH
!
REAL,    DIMENSION (KNI,KPATCH)         :: ZDTOT, ZDG2, ZROOT_EXT, ZROOT_LIN
!
INTEGER :: JJ, JL, JPATCH
!
! flags taking general surface type flag into account
LOGICAL :: GDATA_DG, GDATA_GROUND_DEPTH, GDATA_ROOT_DEPTH, GDATA_ROOTFRAC, &
           GDATA_ROOTFRACGV, GNOECO, GMEB
!-------------------------------------------------------------------------!
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
IF (LHOOK) CALL DR_HOOK('CONVERT_PATCH_ISBA:SET_GRID_PARAM',0,ZHOOK_HANDLE)
!
IF(IO%CISBA=='DIF')THEN
  IF(.NOT.PRESENT(MX)) CALL ABOR1_SFX('CONVERT_PATCH_ISBA: SET_GRID_PARAM: KWG_LAYER, PDROOT and PGD2 must be present with DIF')
 
ENDIF
!
GMEB = (PRESENT(MM) .AND. (ISIZE_LMEB_PATCH>0))
!
ZDTOT    (:,:) = XUNDEF
ZDG2     (:,:) = XUNDEF
!
MX%NWG_LAYER(:,:) = NUNDEF
MX%XROOTFRAC(:,:,:) = XUNDEF
!
ZDATA_GROUND_DEPTH(:,:) = XDATA_GROUND_DEPTH(:,:)
!
GDATA_DG           = GDATA .AND. DTI%LDATA_DG
GDATA_GROUND_DEPTH = GDATA .AND. DTI%LDATA_GROUND_DEPTH
GDATA_ROOT_DEPTH   = GDATA .AND. DTI%LDATA_ROOT_DEPTH
GDATA_ROOTFRAC     = GDATA .AND. DTI%LDATA_ROOTFRAC
GDATA_ROOTFRACGV   = GDATA .AND. DTI%LDATA_ROOTFRACGV
!
!####################################################################################
!
!CDGAVG : old for reprod = 'ARI' Arithmetic average for all depth 
!         recommended    = 'INV' Harmonic average for all depth (default)
!
!CDGDIF : old for reprod = 'SOIL' d3 soil depth from ecoclimap for isba-df
!         recommended    = 'ROOT' d2 soil depth from ecoclimap for isba-df (default)
!
!####################################################################################
!n
!DG IN NAMELIST => GROUND_DEPTH KNOWN, ROOT_DEPTH UNKNOWN 
IF (GDATA_DG) THEN
  !
  DO JLAYER=1,KGROUND
    CALL AV_PGD_PARAM(DTI%XPAR_LAI, DTI%XPAR_VEG, &
                      MX%XDG(:,JLAYER,:),DTI%XPAR_VEGTYPE,DTI%XPAR_DG(:,JLAYER,:),YNAT,CDGAVG)
  ENDDO
  !
ENDIF
!
IF(.NOT.GDATA_GROUND_DEPTH.AND.IO%CISBA=='DIF'.AND.CDGDIF=='ROOT')THEN
  !
  DO JVEGTYPE=1,NVEGTYPE
    IF(JVEGTYPE==NVT_NO)THEN
      WHERE(XDATA_GROUND_DEPTH(:,JVEGTYPE)/=XUNDEF)
        ZDATA_GROUND_DEPTH(:,JVEGTYPE) = MIN(1.0,XDATA_GROUND_DEPTH(:,JVEGTYPE))
      ENDWHERE
    ELSEIF(JVEGTYPE/=NVT_ROCK.AND.JVEGTYPE/=NVT_SNOW)THEN
      ZDATA_GROUND_DEPTH(:,JVEGTYPE) = MAX(1.0,XDATA_ROOT_DEPTH(:,JVEGTYPE))
    ELSE
      ZDATA_GROUND_DEPTH(:,JVEGTYPE) = XDATA_ROOT_DEPTH(:,JVEGTYPE)
    ENDIF
  ENDDO
  !
ENDIF
!
!CALCULATION OF GROUND_DEPTH IN ZDTOT : ECOCLMAP OR LDATA_GROUND_DEPTH
IF (IO%CISBA/='2-L') THEN 
  !
  IF (GDATA_GROUND_DEPTH .AND. (IO%CISBA=='DIF' .OR. .NOT.GDATA_DG)) THEN
    !GROUND DEPTH IN NAMELIST
    CALL AV_PGD_PARAM(DTI%XPAR_LAI, DTI%XPAR_VEG, &
                      ZDTOT(:,:),DTI%XPAR_VEGTYPE,DTI%XPAR_GROUND_DEPTH(:,:),YNAT,CDGAVG)
    !Error Due to machine precision
    WHERE(ZDTOT(:,:)/=XUNDEF) ZDTOT(:,:)=INT(ZDTOT(:,:)*ZPREC)/ZPREC
    !CONSISTENCY CHECK
    IF (GDATA_DG) ZDTOT(:,:) = MIN(ZDTOT(:,:),MX%XDG(:,KGROUND,:))
  ELSEIF (GDATA_DG) THEN
    !GROUND DEPTH FROM NAMELIST DG
    ZDTOT(:,:) = MX%XDG(:,KGROUND,:)
  ELSE
    !GROUND DEPTH FROM ECOCLMAP
    CALL AV_PGD(DTCO, ZDTOT(:,:),PCOVER,ZDATA_GROUND_DEPTH(:,:),YNAT,CDGAVG,OCOVER,KDECADE=KDEC)
    IF(IO%CISBA=='DIF'.AND.CDGDIF=='ROOT')ZDG2(:,:)=ZDTOT(:,:)
  ENDIF
  !
ENDIF
!
!CALCULATION OF GROUND_DEPTH : Permafrost depth put to 12m
IF(IO%CISBA=='DIF'.AND.IO%LPERM) CALL PERMAFROST_DEPTH(KNI,KPATCH,PPERM,ZDTOT)
!
!IN BOTH CASES, ROOT_DEPTH IS NEEDED: PUT IN DG2
IF (IO%CISBA=='DIF' .OR. .NOT.GDATA_DG) THEN
  !
  GNOECO=(GDATA_ROOT_DEPTH .AND. .NOT.GDATA_ROOTFRAC)
  IF (GNOECO) THEN
    !ROOT_DEPTH IN NAMELIST
    CALL AV_PGD_PARAM(DTI%XPAR_LAI, DTI%XPAR_VEG, &
                      ZDG2(:,:),DTI%XPAR_VEGTYPE,DTI%XPAR_ROOT_DEPTH(:,:),YNAT,CDGAVG)
    !Error Due to machine precision
    WHERE(ZDG2(:,:)/=XUNDEF) ZDG2(:,:)=INT(ZDG2(:,:)*ZPREC)/ZPREC  
    !CONSISTENCY CHECKS
    IF (DTI%LDATA_DG) ZDG2(:,:) = MIN(ZDG2(:,:),MX%XDG(:,KGROUND,:))
    ZDTOT(:,:) = MAX(ZDG2(:,:),ZDTOT(:,:))
    IF (IO%CISBA=='DIF') THEN
      CALL AV_PGD_PARAM(DTI%XPAR_LAI, DTI%XPAR_VEG, &
                      MX%XDROOT(:,:),DTI%XPAR_VEGTYPE,DTI%XPAR_ROOT_DEPTH(:,:),YDIF,CDGAVG)
     !Error Due to machine precision
      WHERE(MX%XDROOT(:,:)/=XUNDEF)
          MX%XDROOT(:,:)=INT(MX%XDROOT(:,:)*ZPREC)/ZPREC
      ENDWHERE 
       IF(CDGDIF=='ROOT')THEN
         WHERE(MX%XDROOT(:,:).NE.XUNDEF) ZDTOT(:,:) = MAX(MX%XDROOT(:,:),ZDTOT(:,:))
         WHERE(MX%XDROOT(:,:).NE.XUNDEF) ZDG2 (:,:) = MAX(MX%XDROOT(:,:),ZDG2 (:,:))
       ELSE
         CALL AV_PGD(DTCO, ZDG2(:,:),PCOVER,XDATA_ROOT_DEPTH(:,:),YNAT,CDGAVG,OCOVER,KDECADE=KDEC)
       ENDIF      
     !CONSISTENCY CHECKS
      IF (GDATA_DG) WHERE (MX%XDROOT(:,:).NE.XUNDEF) MX%XDROOT(:,:) = MIN(MX%XDROOT(:,:),MX%XDG(:,KGROUND,:))   
    ENDIF
  ELSE 
    !ROOT_DEPTH FROM ECOCLMAP
    IF (IO%CISBA=='DIF')THEN
       CALL AV_PGD(DTCO, MX%XDROOT(:,:),PCOVER,XDATA_ROOT_DEPTH(:,:),YDIF,CDGAVG,OCOVER,KDECADE=KDEC)
       IF(CDGDIF=='ROOT')THEN
         WHERE(MX%XDROOT(:,:).NE.XUNDEF) ZDTOT(:,:) = MAX(MX%XDROOT(:,:),ZDTOT(:,:))
         WHERE(MX%XDROOT(:,:).NE.XUNDEF) ZDG2 (:,:) = MAX(MX%XDROOT(:,:),ZDG2 (:,:))
       ELSE
         CALL AV_PGD(DTCO, ZDG2(:,:),PCOVER,XDATA_ROOT_DEPTH(:,:),YNAT,CDGAVG,OCOVER,KDECADE=KDEC)
       ENDIF
    ELSE
       CALL AV_PGD(DTCO, ZDG2(:,:),PCOVER,XDATA_ROOT_DEPTH(:,:),YNAT,CDGAVG,OCOVER,KDECADE=KDEC)
    ENDIF
    IF ( GDATA_GROUND_DEPTH .OR. GDATA_DG ) THEN
      ZDG2  (:,:) = MIN(ZDG2  (:,:),ZDTOT(:,:))
      IF (IO%CISBA=='DIF') WHERE (MX%XDROOT(:,:).NE.XUNDEF) MX%XDROOT(:,:) = MIN(MX%XDROOT(:,:),ZDTOT(:,:))
    ENDIF
  ENDIF
  !
  !CALCULATION OF DG IF NOT IN NAMELIST
  IF (.NOT.GDATA_DG) THEN
    !
    IF (IO%CISBA=='DIF') THEN
      IF( MAXVAL(ZDTOT,ZDTOT/=XUNDEF)>PSOILGRID(KGROUND) ) THEN
        CALL ABOR1_SFX('CONVERT_PATCH_ISBA: not enough soil layer with optimized grid')
      ENDIF
    ENDIF
    !
    WHERE(ZDG2(:,:)==XUNDEF.AND.ZDTOT(:,:)/=XUNDEF) ZDG2(:,:)=0.0 !No vegetation
    !
    !IF CISBA=DIF CALCULATES ALSO KWG_LAYER WITH USE OF SOILGRID $
    CALL INI_DATA_SOIL(IO%CISBA, MX%XDG,PROOTDEPTH=ZDG2, PSOILDEPTH=ZDTOT,&
                       PSOILGRID=PSOILGRID, KWG_LAYER=MX%NWG_LAYER )
    IF (.NOT.GNOECO.AND.IO%CISBA=='DIF'.AND.CDGDIF=='ROOT')THEN
       DO JPATCH=1,KPATCH
          DO JJ=1,KNI
             IF(IO%LPERM.AND.MX%NWG_LAYER(JJ,JPATCH)/=NUNDEF)THEN
               IF(PPERM(JJ)<XPERMFRAC) ZDG2(JJ,JPATCH)=MX%XDG(JJ,MX%NWG_LAYER(JJ,JPATCH),JPATCH)
             ELSEIF(MX%NWG_LAYER(JJ,JPATCH)/=NUNDEF)THEN
               ZDG2(JJ,JPATCH)=MX%XDG(JJ,MX%NWG_LAYER(JJ,JPATCH),JPATCH)
             ELSE
               ZDG2(JJ,JPATCH)=XUNDEF
             ENDIF
          ENDDO
       ENDDO
    ENDIF
               
    !
  ELSEIF ( IO%CISBA=='DIF') THEN
    !
    !CALCULATION OF KWG_LAYER IF DG IN NAMELIST
    IF(GDATA_GROUND_DEPTH)THEN
      DO JPATCH=1,KPATCH
        DO JJ=1,KNI
          DO JL=1,KGROUND
            IF( MX%XDG(JJ,JL,JPATCH) <= ZDTOT(JJ,JPATCH) .AND. ZDTOT(JJ,JPATCH) < XUNDEF ) &
                MX%NWG_LAYER(JJ,JPATCH) = JL
          ENDDO
        ENDDO
      ENDDO                
    ELSE
      MX%NWG_LAYER(:,:) = KGROUND
    ENDIF
    !
  ENDIF
  !
  ! DROOT AND DG2 LMITED BY KWG_LAYER
  IF (IO%CISBA=='DIF' .AND. .NOT.DTI%LDATA_ROOTFRAC) THEN
    !
    DO JPATCH=1,KPATCH
      DO JJ=1,KNI
        IF(MX%NWG_LAYER(JJ,JPATCH)/=NUNDEF) THEN
          JL = MX%NWG_LAYER(JJ,JPATCH)
          ZDG2  (JJ,JPATCH)=MIN(ZDG2  (JJ,JPATCH),MX%XDG(JJ,JL,JPATCH))
          IF (MX%XDROOT(JJ,JPATCH)/=XUNDEF) MX%XDROOT(JJ,JPATCH)=MIN(MX%XDROOT(JJ,JPATCH),MX%XDG(JJ,JL,JPATCH))    
        ENDIF
      ENDDO
    ENDDO
    !
  ENDIF
  !
ENDIF
!
!CALCULATION OF ROOTFRAC
IF (IO%CISBA=='DIF') THEN
  !
  IF (GDATA_ROOTFRAC .OR. GDATA_ROOTFRACGV) THEN
    !
    !ROOTFRACGV IN NAMELIST
    IF(GMEB)THEN
      DO JL=1,KGROUND
        CALL AV_PGD_PARAM(DTI%XPAR_LAI, DTI%XPAR_VEG, &
                      MM%XROOTFRACGV(:,JL,:),DTI%XPAR_VEGTYPE,DTI%XPAR_ROOTFRACGV(:,JL,:),YNAT,'ARI')
      ENDDO
    ENDIF
    !
    !ROOTFRAC IN NAMELIST
    DO JL=1,KGROUND
      CALL AV_PGD_PARAM(DTI%XPAR_LAI, DTI%XPAR_VEG, &
                      MX%XROOTFRAC(:,JL,:),DTI%XPAR_VEGTYPE,DTI%XPAR_ROOTFRAC(:,JL,:),YNAT,'ARI',KDECADE=KDEC)
    ENDDO
    !    
    ZDG2  (:,:)=0.0
    MX%XDROOT(:,:)=0.0    
    DO JPATCH=1,KPATCH
      DO JJ=1,KNI
        !
        !DROOT DEPENDS ON ROOTFRAC
        DO JL=KGROUND,1,-1
          IF( MX%XROOTFRAC(JJ,JL,JPATCH)>=1.0 )THEN
            ZDG2  (JJ,JPATCH) = MX%XDG(JJ,JL,JPATCH)
            MX%XDROOT(JJ,JPATCH) = MX%XDG(JJ,JL,JPATCH)
          ELSEIF (JL<KGROUND.AND.MX%XROOTFRAC(JJ,JL,JPATCH)>0.0) THEN
            IF (MX%NWG_LAYER(JJ,JPATCH)<=JL) MX%NWG_LAYER(JJ,JPATCH) = JL+1
            EXIT
          ENDIF
        ENDDO
        !
        IF(MX%XDROOT(JJ,JPATCH)==0.0.AND.ZDG2(JJ,JPATCH)==0.0)THEN
          JL=MX%NWG_LAYER(JJ,JPATCH)
          ZDG2(JJ,JPATCH)=MIN(0.6,MX%XDG(JJ,JL,JPATCH))
        ENDIF
        !
      ENDDO
    ENDDO
    !
  ELSE
    !
    !DEPENDS ON DROOT
    IF (GDATA .AND. DTI%LDATA_ROOT_LIN) THEN
      CALL AV_PGD_PARAM(DTI%XPAR_LAI, DTI%XPAR_VEG, &
                      ZROOT_LIN(:,:),DTI%XPAR_VEGTYPE,DTI%XPAR_ROOT_LIN(:,:),YDIF,'ARI')
    ELSE
      CALL AV_PGD(DTCO, ZROOT_LIN(:,:),PCOVER,XDATA_ROOT_LIN(:,:),YDIF,'ARI',OCOVER,KDECADE=KDEC)
    ENDIF
    !
    IF (GDATA .AND. DTI%LDATA_ROOT_EXTINCTION) THEN
      CALL AV_PGD_PARAM(DTI%XPAR_LAI, DTI%XPAR_VEG, &
                    ZROOT_EXT(:,:),DTI%XPAR_VEGTYPE,DTI%XPAR_ROOT_EXTINCTION(:,:),YDIF,'ARI')
    ELSE
      CALL AV_PGD(DTCO, ZROOT_EXT(:,:),PCOVER,XDATA_ROOT_EXTINCTION(:,:),YDIF,'ARI',OCOVER,KDECADE=KDEC)
    ENDIF
    !
    CALL INI_DATA_ROOTFRAC(MX%XDG,MX%XDROOT,ZROOT_EXT,ZROOT_LIN,MX%XROOTFRAC)
  ENDIF
  IF(GMEB)THEN
    IF (GDATA .AND. DTI%LDATA_ROOT_EXTINCTIONGV) THEN
      CALL AV_PGD_PARAM(DTI%XPAR_LAI, DTI%XPAR_VEG, &
                    ZROOT_EXT(:,:),DTI%XPAR_VEGTYPE,DTI%XPAR_ROOT_EXTINCTIONGV(:,:),YDIF,'ARI')
    ELSE
      CALL AV_PGD(DTCO, ZROOT_EXT(:,:),PCOVER,XDATA_ROOT_EXTINCTIONGV(:,:),YDIF,'ARI',OCOVER,KDECADE=KDEC)
    ENDIF
    !
    CALL INI_DATA_ROOTFRAC(MX%XDG,MX%XDROOT,ZROOT_EXT,ZROOT_LIN,  &
                           MM%XROOTFRACGV,OGV=GMEB)
    !
  ENDIF
  !
  MX%XDG2(:,:) = ZDG2(:,:)
  !
ENDIF
!
IF (LHOOK) CALL DR_HOOK('CONVERT_PATCH_ISBA:SET_GRID_PARAM',1,ZHOOK_HANDLE)
!
END SUBROUTINE SET_GRID_PARAM
!
!-------------------------------------------------------------------------------
END SUBROUTINE CONVERT_PATCH_ISBA
