!     #################################################################################
SUBROUTINE DEALLOC_SURF_ATM_n (B, CHE, CHF, CHI, CHS, CHU, CHT, CHW, DTI, DTT, DUU, FG, F, &
                               GB, IG, I, SG, S, UG, U, USS, SV, TG, T, TOP, TPN, WG, W)
!     #################################################################################
!
!!****  *DEALLOC_SURF_ATM_n * - Deallocate all arrays
!!
!!    PURPOSE
!!    -------
!
!!**  METHOD
!!    ------
!!
!!    REFERENCE
!!    ---------
!!      
!!
!!    AUTHOR
!!    ------
!!     V. Masson 
!!
!!    MODIFICATIONS
!!    -------------
!!      Original    01/2004
!!------------------------------------------------------------------
!

!
!
!
!
!
!
!
!
USE MODD_BEM_n, ONLY : BEM_t
USE MODD_CH_EMIS_FIELD_n, ONLY : CH_EMIS_FIELD_t
USE MODD_CH_FLAKE_n, ONLY : CH_FLAKE_t
USE MODD_CH_ISBA_n, ONLY : CH_ISBA_t
USE MODD_CH_SEAFLUX_n, ONLY : CH_SEAFLUX_t
USE MODD_CH_SURF_n, ONLY : CH_SURF_t
USE MODD_CH_TEB_n, ONLY : CH_TEB_t
USE MODD_CH_WATFLUX_n, ONLY : CH_WATFLUX_t
USE MODD_DATA_ISBA_n, ONLY : DATA_ISBA_t
USE MODD_DATA_TEB_n, ONLY : DATA_TEB_t
USE MODD_DUMMY_SURF_FIELDS_n, ONLY : DUMMY_SURF_FIELDS_t
USE MODD_FLAKE_GRID_n, ONLY : FLAKE_GRID_t
USE MODD_FLAKE_n, ONLY : FLAKE_t
USE MODD_GR_BIOG_n, ONLY : GR_BIOG_t
USE MODD_ISBA_GRID_n, ONLY : ISBA_GRID_t
USE MODD_ISBA_n, ONLY : ISBA_t
USE MODD_SEAFLUX_GRID_n, ONLY : SEAFLUX_GRID_t
USE MODD_SEAFLUX_n, ONLY : SEAFLUX_t
USE MODD_SURF_ATM_GRID_n, ONLY : SURF_ATM_GRID_t
USE MODD_SURF_ATM_n, ONLY : SURF_ATM_t
USE MODD_SURF_ATM_SSO_n, ONLY : SURF_ATM_SSO_t
USE MODD_SV_n, ONLY : SV_t
USE MODD_TEB_GRID_n, ONLY : TEB_GRID_t
USE MODD_TEB_n, ONLY : TEB_t
USE MODD_TEB_OPTION_n, ONLY : TEB_OPTIONS_t
USE MODD_TEB_PANEL_n, ONLY : TEB_PANEL_t
USE MODD_WATFLUX_GRID_n, ONLY : WATFLUX_GRID_t
USE MODD_WATFLUX_n, ONLY : WATFLUX_t
!
USE MODI_DEALLOC_SEA_n
USE MODI_DEALLOC_INLAND_WATER_n
USE MODI_DEALLOC_NATURE_n
USE MODI_DEALLOC_TOWN_n
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE
!
!*      0.1    declarations of arguments
!
!
!*      0.2    declarations of local variables
!
!-------------------------------------------------------------------------------------
!

!
TYPE(BEM_t), INTENT(INOUT) :: B
TYPE(CH_EMIS_FIELD_t), INTENT(INOUT) :: CHE
TYPE(CH_FLAKE_t), INTENT(INOUT) :: CHF
TYPE(CH_ISBA_t), INTENT(INOUT) :: CHI
TYPE(CH_SEAFLUX_t), INTENT(INOUT) :: CHS
TYPE(CH_SURF_t), INTENT(INOUT) :: CHU
TYPE(CH_TEB_t), INTENT(INOUT) :: CHT
TYPE(CH_WATFLUX_t), INTENT(INOUT) :: CHW
TYPE(DATA_ISBA_t), INTENT(INOUT) :: DTI
TYPE(DATA_TEB_t), INTENT(INOUT) :: DTT
TYPE(DUMMY_SURF_FIELDS_t), INTENT(INOUT) :: DUU
TYPE(FLAKE_GRID_t), INTENT(INOUT) :: FG
TYPE(FLAKE_t), INTENT(INOUT) :: F
TYPE(GR_BIOG_t), INTENT(INOUT) :: GB
TYPE(ISBA_GRID_t), INTENT(INOUT) :: IG
TYPE(ISBA_t), INTENT(INOUT) :: I
TYPE(SEAFLUX_GRID_t), INTENT(INOUT) :: SG
TYPE(SEAFLUX_t), INTENT(INOUT) :: S
TYPE(SURF_ATM_GRID_t), INTENT(INOUT) :: UG
TYPE(SURF_ATM_t), INTENT(INOUT) :: U
TYPE(SURF_ATM_SSO_t), INTENT(INOUT) :: USS
TYPE(SV_t), INTENT(INOUT) :: SV
TYPE(TEB_GRID_t), INTENT(INOUT) :: TG
TYPE(TEB_t), INTENT(INOUT) :: T
TYPE(TEB_OPTIONS_t), INTENT(INOUT) :: TOP
TYPE(TEB_PANEL_t), INTENT(INOUT) :: TPN
TYPE(WATFLUX_GRID_t), INTENT(INOUT) :: WG
TYPE(WATFLUX_t), INTENT(INOUT) :: W
!
REAL(KIND=JPRB) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('DEALLOC_SURF_ATM_N',0,ZHOOK_HANDLE)
IF (ASSOCIATED(U%XNATURE)) DEALLOCATE(U%XNATURE)
IF (ASSOCIATED(U%XTOWN  )) DEALLOCATE(U%XTOWN  )
IF (ASSOCIATED(U%XWATER )) DEALLOCATE(U%XWATER )
IF (ASSOCIATED(U%XSEA   )) DEALLOCATE(U%XSEA   )
!
IF (ASSOCIATED(U%LCOVER )) DEALLOCATE(U%LCOVER )
IF (ASSOCIATED(U%XCOVER )) DEALLOCATE(U%XCOVER )
IF (ASSOCIATED(U%XZS    )) DEALLOCATE(U%XZS    )
!
IF (ASSOCIATED(U%NR_NATURE)) DEALLOCATE(U%NR_NATURE)
IF (ASSOCIATED(U%NR_TOWN  )) DEALLOCATE(U%NR_TOWN  )
IF (ASSOCIATED(U%NR_WATER )) DEALLOCATE(U%NR_WATER )
IF (ASSOCIATED(U%NR_SEA   )) DEALLOCATE(U%NR_SEA   )
!
!-------------------------------------------------------------------------------------
!
IF (ASSOCIATED(UG%XGRID_PAR )) DEALLOCATE(UG%XGRID_PAR )
IF (ASSOCIATED(UG%XLAT      )) DEALLOCATE(UG%XLAT      )
IF (ASSOCIATED(UG%XLON      )) DEALLOCATE(UG%XLON      )
IF (ASSOCIATED(UG%XMESH_SIZE)) DEALLOCATE(UG%XMESH_SIZE)
IF (ASSOCIATED(UG%XJPDIR    )) DEALLOCATE(UG%XJPDIR    )
!
!-------------------------------------------------------------------------------------
!
IF (ASSOCIATED(USS%XAOSIP))     DEALLOCATE( USS%XAOSIP)
IF (ASSOCIATED(USS%XAOSIM))     DEALLOCATE( USS%XAOSIM)
IF (ASSOCIATED(USS%XAOSJP))     DEALLOCATE( USS%XAOSJP)
IF (ASSOCIATED(USS%XAOSJM))     DEALLOCATE( USS%XAOSJM)
IF (ASSOCIATED(USS%XHO2IP))     DEALLOCATE( USS%XHO2IP)
IF (ASSOCIATED(USS%XHO2IM))     DEALLOCATE( USS%XHO2IM)
IF (ASSOCIATED(USS%XHO2JP))     DEALLOCATE( USS%XHO2JP)
IF (ASSOCIATED(USS%XHO2JM))     DEALLOCATE( USS%XHO2JM)
IF (ASSOCIATED(USS%XZ0REL))     DEALLOCATE( USS%XZ0REL)
IF (ASSOCIATED(USS%XSSO_SLOPE)) DEALLOCATE( USS%XSSO_SLOPE)
IF (ASSOCIATED(USS%XSSO_ANIS))  DEALLOCATE( USS%XSSO_ANIS)
IF (ASSOCIATED(USS%XSSO_DIR))   DEALLOCATE( USS%XSSO_DIR)
IF (ASSOCIATED(USS%XSSO_STDEV)) DEALLOCATE( USS%XSSO_STDEV)
IF (ASSOCIATED(USS%XAVG_ZS))    DEALLOCATE( USS%XAVG_ZS)
IF (ASSOCIATED(USS%XSIL_ZS))    DEALLOCATE( USS%XSIL_ZS)
IF (ASSOCIATED(USS%XMAX_ZS))    DEALLOCATE( USS%XMAX_ZS)
IF (ASSOCIATED(USS%XMIN_ZS))    DEALLOCATE( USS%XMIN_ZS)
!
!-------------------------------------------------------------------------------------
!
IF (ASSOCIATED(CHE%CEMIS_AREA))   DEALLOCATE(CHE%CEMIS_AREA)
IF (ASSOCIATED(CHE%CEMIS_COMMENT))DEALLOCATE(CHE%CEMIS_COMMENT)
IF (ASSOCIATED(CHE%CEMIS_NAME))   DEALLOCATE(CHE%CEMIS_NAME)
IF (ASSOCIATED(CHE%NEMIS_TIME))   DEALLOCATE(CHE%NEMIS_TIME)
IF (ASSOCIATED(CHE%XEMIS_FIELDS)) DEALLOCATE(CHE%XEMIS_FIELDS)
IF (ASSOCIATED(CHE%TSEMISS))      DEALLOCATE(CHE%TSEMISS)
!
!-------------------------------------------------------------------------------------
!
IF (ASSOCIATED(DUU%XDUMMY_FIELDS)) DEALLOCATE( DUU%XDUMMY_FIELDS)
!
!-------------------------------------------------------------------------------------
!
IF (ASSOCIATED(SV%CSV)) DEALLOCATE(SV%CSV)
!
!-------------------------------------------------------------------------------------
!
IF (ASSOCIATED(CHU%CCH_NAMES))  DEALLOCATE(CHU%CCH_NAMES)
IF (ASSOCIATED(CHE%CEMIS_NAME)) DEALLOCATE(CHE%CEMIS_NAME)
IF (ASSOCIATED(CHE%CEMIS_AREA)) DEALLOCATE(CHE%CEMIS_AREA)
IF (ASSOCIATED(CHE%NEMIS_TIME)) DEALLOCATE(CHE%NEMIS_TIME )
IF (ASSOCIATED(CHE%TSEMISS))    DEALLOCATE(CHE%TSEMISS)
!
!-------------------------------------------------------------------------------------
!
IF (U%NDIM_SEA    >0) CALL DEALLOC_SEA_n(CHS, SG, S, U)
IF (U%NDIM_WATER  >0) CALL DEALLOC_INLAND_WATER_n(CHF, CHW, FG, F, U, WG, W)
IF (U%NDIM_NATURE >0) CALL DEALLOC_NATURE_n(CHI, DTI, GB, IG, I, U)
IF (U%NDIM_TOWN   >0) CALL DEALLOC_TOWN_n(B, CHT, DTT, U, TG, T, TOP, TPN)
IF (LHOOK) CALL DR_HOOK('DEALLOC_SURF_ATM_N',1,ZHOOK_HANDLE)
!
!--------------------------------------------------------------------------------------
!
END SUBROUTINE DEALLOC_SURF_ATM_n
