!SFX_LIC Copyright 1994-2014 CNRS, Meteo-France and Universite Paul Sabatier
!SFX_LIC This is part of the SURFEX software governed by the CeCILL-C licence
!SFX_LIC version 1. See LICENSE, CeCILL-C_V1-en.txt and CeCILL-C_V1-fr.txt  
!SFX_LIC for details. version 1.
!     #############################################################
      SUBROUTINE DEALLOC_DIAG_SURF_ATM_n (D,DC,DP,DPC)
!     #############################################################
!
!!    AUTHOR
!!    ------
!!      V. Masson   *Meteo France*
!!
!!    MODIFICATIONS
!!    -------------
!!      Original    01/2004
!!      Modified    01/2006 : sea flux parameterization.
!!      B.Decharme  04/2013 : new diags
!-------------------------------------------------------------------------------
!
!*       0.    DECLARATIONS
!              ------------
!
!
USE MODD_DATA_COVER_PAR, ONLY : NTILESFC
!
USE MODD_DIAG_n, ONLY : DIAG_t, DIAG_PATCH_t
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE
!
!*       0.1   Declarations of arguments
!              -------------------------
!
!*       0.2   Declarations of local variables
!              -------------------------------
!
!-------------------------------------------------------------------------------
!
!

!
TYPE(DIAG_t), INTENT(INOUT) :: D
TYPE(DIAG_t), INTENT(INOUT) :: DC
TYPE(DIAG_PATCH_t), INTENT(INOUT) :: DP
TYPE(DIAG_PATCH_t), INTENT(INOUT) :: DPC
!
INTEGER :: JTILE
REAL(KIND=JPRB) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('DEALLOC_DIAG_SURF_ATM_N',0,ZHOOK_HANDLE)
DO JTILE=1,NTILESFC
  DEALLOCATE(DP%AL(JTILE)%XRI     )
  DEALLOCATE(DP%AL(JTILE)%XCD     )
  DEALLOCATE(DP%AL(JTILE)%XCH     )
  DEALLOCATE(DP%AL(JTILE)%XCE     )
  DEALLOCATE(DP%AL(JTILE)%XQS     )
  DEALLOCATE(DP%AL(JTILE)%XZ0     )
  DEALLOCATE(DP%AL(JTILE)%XZ0H    )
  DEALLOCATE(DP%AL(JTILE)%XRN     )
  DEALLOCATE(DP%AL(JTILE)%XH      )
  DEALLOCATE(DP%AL(JTILE)%XLE     )
  DEALLOCATE(DP%AL(JTILE)%XLEI    )
  DEALLOCATE(DP%AL(JTILE)%XGFLUX  )
  DEALLOCATE(DP%AL(JTILE)%XEVAP   )
  DEALLOCATE(DP%AL(JTILE)%XSUBL   )
  DEALLOCATE(DP%AL(JTILE)%XT2M    )
  DEALLOCATE(DP%AL(JTILE)%XTS     )
  DEALLOCATE(DP%AL(JTILE)%XT2M_MIN)
  DEALLOCATE(DP%AL(JTILE)%XT2M_MAX)
  DEALLOCATE(DP%AL(JTILE)%XQ2M    )
  DEALLOCATE(DP%AL(JTILE)%XHU2M   )
  DEALLOCATE(DP%AL(JTILE)%XZON10M )
  DEALLOCATE(DP%AL(JTILE)%XMER10M )
  !
  DEALLOCATE(DP%AL(JTILE)%XHU2M_MIN    )
  DEALLOCATE(DP%AL(JTILE)%XHU2M_MAX   )
  DEALLOCATE(DP%AL(JTILE)%XWIND10M     )
  DEALLOCATE(DP%AL(JTILE)%XWIND10M_MAX )
  !  
  DEALLOCATE(DPC%AL(JTILE)%XRN     )
  DEALLOCATE(DPC%AL(JTILE)%XH      )
  DEALLOCATE(DPC%AL(JTILE)%XLE     )
  DEALLOCATE(DPC%AL(JTILE)%XLEI    )
  DEALLOCATE(DPC%AL(JTILE)%XGFLUX  )
  DEALLOCATE(DPC%AL(JTILE)%XEVAP   )
  DEALLOCATE(DPC%AL(JTILE)%XSUBL   )
  DEALLOCATE(DPC%AL(JTILE)%XSWD    )
  DEALLOCATE(DPC%AL(JTILE)%XSWU    )
  DEALLOCATE(DPC%AL(JTILE)%XLWD    )
  DEALLOCATE(DPC%AL(JTILE)%XLWU    )
  DEALLOCATE(DPC%AL(JTILE)%XFMU    )
  DEALLOCATE(DPC%AL(JTILE)%XFMV    )
  !
ENDDO
!
DEALLOCATE(D%XTRAD   )
DEALLOCATE(D%XEMIS   )
!
DEALLOCATE(D%XRI     )
DEALLOCATE(D%XCD     )
DEALLOCATE(D%XCH     )
DEALLOCATE(D%XCE     )
DEALLOCATE(D%XZ0     )
DEALLOCATE(D%XZ0H    )
DEALLOCATE(D%XRN     )
DEALLOCATE(D%XH      )
DEALLOCATE(D%XLE     )
DEALLOCATE(D%XLEI    )
DEALLOCATE(D%XGFLUX  )
DEALLOCATE(D%XEVAP   )
DEALLOCATE(D%XSUBL   )
DEALLOCATE(D%XT2M    )
DEALLOCATE(D%XTS     )
DEALLOCATE(D%XT2M_MIN)
DEALLOCATE(D%XT2M_MAX)
DEALLOCATE(D%XQ2M    )
DEALLOCATE(D%XHU2M   )
DEALLOCATE(D%XZON10M )
DEALLOCATE(D%XMER10M )
DEALLOCATE(D%XSFCO2  )
DEALLOCATE(D%XT2M_MIN_ZS    )
DEALLOCATE(D%XQ2M_MIN_ZS    )
DEALLOCATE(D%XHU2M_MIN_ZS   )
DEALLOCATE(D%XPS                )
DEALLOCATE(D%XRHOA              )
!
DEALLOCATE(D%XHU2M_MIN     )
DEALLOCATE(D%XHU2M_MAX     )
DEALLOCATE(D%XWIND10M      )
DEALLOCATE(D%XWIND10M_MAX  )
!
DEALLOCATE(DC%XRN     )
DEALLOCATE(DC%XH      )
DEALLOCATE(DC%XLE     )
DEALLOCATE(DC%XLEI    )
DEALLOCATE(DC%XGFLUX  )
DEALLOCATE(DC%XEVAP   )
DEALLOCATE(DC%XSUBL   )
DEALLOCATE(DC%XSWD    )
DEALLOCATE(DC%XSWU    )
DEALLOCATE(DC%XLWD    )
DEALLOCATE(DC%XLWU    )
DEALLOCATE(DC%XFMU    )
DEALLOCATE(DC%XFMV    )
!
IF (LHOOK) CALL DR_HOOK('DEALLOC_DIAG_SURF_ATM_N',1,ZHOOK_HANDLE)
! 
!-------------------------------------------------------------------------------
!
END SUBROUTINE DEALLOC_DIAG_SURF_ATM_n
