!     #################################################################################
SUBROUTINE DEALLOC_TEB_n (B, BOP, CHT, DTT, TG, T, TOP, TPN)
!     #################################################################################
!
!!****  *DEALLOC_TEB_n * - Deallocate all arrays
!!
!!    PURPOSE
!!    -------
!
!!**  METHOD
!!    ------
!!
!!    REFERENCE
!!    ---------
!!      
!!
!!    AUTHOR
!!    ------
!!     V. Masson 
!!
!!    MODIFICATIONS
!!    -------------
!!      Original    01/2004
!!      G. Pigeon   09/2012: deallocate ROUGH_WALL/ROUGH_ROOF
!!      G. Pigeon   10/2012: deallocate BEM variables
!!------------------------------------------------------------------
!

!

!
!
!
!
!
USE MODD_BEM_n, ONLY : BEM_t
USE MODD_BEM_OPTION_n, ONLY : BEM_OPTIONS_t
USE MODD_CH_TEB_n, ONLY : CH_TEB_t
USE MODD_DATA_TEB_n, ONLY : DATA_TEB_t
USE MODD_TEB_GRID_n, ONLY : TEB_GRID_t
USE MODD_TEB_n, ONLY : TEB_t
USE MODD_TEB_OPTION_n, ONLY : TEB_OPTIONS_t
USE MODD_TEB_PANEL_n, ONLY : TEB_PANEL_t
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE
!
!*      0.1    declarations of arguments
!
!
!*      0.2    declarations of local variables
!
!-------------------------------------------------------------------------------------
!

!
TYPE(BEM_t), INTENT(INOUT) :: B
TYPE(BEM_OPTIONS_t), INTENT(INOUT) :: BOP
TYPE(CH_TEB_t), INTENT(INOUT) :: CHT
TYPE(DATA_TEB_t), INTENT(INOUT) :: DTT
TYPE(TEB_GRID_t), INTENT(INOUT) :: TG
TYPE(TEB_t), INTENT(INOUT) :: T
TYPE(TEB_OPTIONS_t), INTENT(INOUT) :: TOP
TYPE(TEB_PANEL_t), INTENT(INOUT) :: TPN
!
REAL(KIND=JPRB) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('DEALLOC_TEB_N',0,ZHOOK_HANDLE)
IF (ASSOCIATED(TOP%LCOVER ))  DEALLOCATE(TOP%LCOVER )
IF (ASSOCIATED(TOP%XCOVER ))  DEALLOCATE(TOP%XCOVER )
IF (ASSOCIATED(TOP%XZS    ))  DEALLOCATE(TOP%XZS    )
!
!-------------------------------------------------------------------------------------
!
IF (ASSOCIATED(TG%XGRID_PAR )) DEALLOCATE(TG%XGRID_PAR )
IF (ASSOCIATED(TG%XLAT      )) DEALLOCATE(TG%XLAT      )
IF (ASSOCIATED(TG%XLON      )) DEALLOCATE(TG%XLON      )
IF (ASSOCIATED(TG%XMESH_SIZE)) DEALLOCATE(TG%XMESH_SIZE)
!
!-------------------------------------------------------------------------------------
!
IF(ASSOCIATED(T%XZ0_TOWN     )) DEALLOCATE(T%XZ0_TOWN     )
IF(ASSOCIATED(T%XALB_ROOF    )) DEALLOCATE(T%XALB_ROOF    )
IF(ASSOCIATED(T%XEMIS_ROOF   )) DEALLOCATE(T%XEMIS_ROOF   )
IF(ASSOCIATED(T%XALB_ROAD    )) DEALLOCATE(T%XALB_ROAD    )
IF(ASSOCIATED(T%XEMIS_ROAD   )) DEALLOCATE(T%XEMIS_ROAD   )
IF(ASSOCIATED(T%XALB_WALL    )) DEALLOCATE(T%XALB_WALL    )
IF(ASSOCIATED(T%XEMIS_WALL   )) DEALLOCATE(T%XEMIS_WALL   )
IF(ASSOCIATED(T%XBLD         )) DEALLOCATE(T%XBLD         )
IF(ASSOCIATED(T%XGARDEN      )) DEALLOCATE(T%XGARDEN      )
IF(ASSOCIATED(T%XROAD_DIR    )) DEALLOCATE(T%XROAD_DIR    )
IF(ASSOCIATED(T%XGREENROOF   )) DEALLOCATE(T%XGREENROOF   )
IF(ASSOCIATED(T%XBLD_HEIGHT  )) DEALLOCATE(T%XBLD_HEIGHT  )
IF(ASSOCIATED(T%XWALL_O_HOR  )) DEALLOCATE(T%XWALL_O_HOR  )
IF(ASSOCIATED(T%XCAN_HW_RATIO)) DEALLOCATE(T%XCAN_HW_RATIO)
IF(ASSOCIATED(T%XROAD_O_GRND))  DEALLOCATE(T%XROAD_O_GRND)
IF(ASSOCIATED(T%XGARDEN_O_GRND))DEALLOCATE(T%XGARDEN_O_GRND)
IF(ASSOCIATED(T%XWALL_O_GRND))  DEALLOCATE(T%XWALL_O_GRND)
IF(ASSOCIATED(T%XH_TRAFFIC   )) DEALLOCATE(T%XH_TRAFFIC   )
IF(ASSOCIATED(T%XLE_TRAFFIC  )) DEALLOCATE(T%XLE_TRAFFIC  )
IF(ASSOCIATED(T%XH_INDUSTRY  )) DEALLOCATE(T%XH_INDUSTRY  )
IF(ASSOCIATED(T%XLE_INDUSTRY )) DEALLOCATE(T%XLE_INDUSTRY )
IF(ASSOCIATED(T%XHC_ROOF )) DEALLOCATE(T%XHC_ROOF )
IF(ASSOCIATED(T%XTC_ROOF )) DEALLOCATE(T%XTC_ROOF )
IF(ASSOCIATED(T%XD_ROOF  )) DEALLOCATE(T%XD_ROOF  )
IF(ASSOCIATED(T%XHC_ROAD )) DEALLOCATE(T%XHC_ROAD )
IF(ASSOCIATED(T%XTC_ROAD )) DEALLOCATE(T%XTC_ROAD )
IF(ASSOCIATED(T%XD_ROAD  )) DEALLOCATE(T%XD_ROAD  )
IF(ASSOCIATED(T%XHC_WALL )) DEALLOCATE(T%XHC_WALL )
IF(ASSOCIATED(T%XTC_WALL )) DEALLOCATE(T%XTC_WALL )
IF(ASSOCIATED(T%XD_WALL  )) DEALLOCATE(T%XD_WALL  )
IF(ASSOCIATED(T%XSVF_ROAD)) DEALLOCATE(T%XSVF_ROAD)
IF(ASSOCIATED(T%XSVF_WALL)) DEALLOCATE(T%XSVF_WALL)
!
IF(ASSOCIATED(TPN%XEMIS_PANEL)) DEALLOCATE(TPN%XEMIS_PANEL)
IF(ASSOCIATED(TPN%XALB_PANEL )) DEALLOCATE(TPN%XALB_PANEL )
IF(ASSOCIATED(TPN%XEFF_PANEL )) DEALLOCATE(TPN%XEFF_PANEL )
IF(ASSOCIATED(TPN%XFRAC_PANEL)) DEALLOCATE(TPN%XFRAC_PANEL)
IF(ASSOCIATED(TPN%XTHER_PRODC_DAY)) DEALLOCATE(TPN%XTHER_PRODC_DAY)
!
IF (ASSOCIATED(T%XT_ROOF)) DEALLOCATE(T%XT_ROOF)
IF (ASSOCIATED(T%XT_ROAD)) DEALLOCATE(T%XT_ROAD)
IF (ASSOCIATED(T%XT_WALL_A)) DEALLOCATE(T%XT_WALL_A)
IF (ASSOCIATED(T%XT_WALL_B)) DEALLOCATE(T%XT_WALL_B)
IF (ASSOCIATED(T%XAC_ROOF)) DEALLOCATE(T%XAC_ROOF)
IF (ASSOCIATED(T%XAC_ROAD)) DEALLOCATE(T%XAC_ROAD)
IF (ASSOCIATED(T%XAC_WALL)) DEALLOCATE(T%XAC_WALL)
IF (ASSOCIATED(T%XAC_TOP)) DEALLOCATE(T%XAC_TOP)
IF (ASSOCIATED(T%XAC_ROOF_WAT)) DEALLOCATE(T%XAC_ROOF_WAT)
IF (ASSOCIATED(T%XAC_ROAD_WAT)) DEALLOCATE(T%XAC_ROAD_WAT)
IF (ASSOCIATED(T%XQSAT_ROOF)) DEALLOCATE(T%XQSAT_ROOF)
IF (ASSOCIATED(T%XQSAT_ROAD)) DEALLOCATE(T%XQSAT_ROAD)
IF (ASSOCIATED(T%XDELT_ROOF)) DEALLOCATE(T%XDELT_ROOF)
IF (ASSOCIATED(T%XDELT_ROAD)) DEALLOCATE(T%XDELT_ROAD)
!-------------------------------------------------------------------------------------
!
IF(ASSOCIATED(T%XAC_ROOF    ))  DEALLOCATE(T%XAC_ROOF    )
IF(ASSOCIATED(T%XAC_ROAD    ))  DEALLOCATE(T%XAC_ROAD    )
IF(ASSOCIATED(T%XAC_WALL    ))  DEALLOCATE(T%XAC_WALL    )
IF(ASSOCIATED(T%XAC_TOP     ))  DEALLOCATE(T%XAC_TOP     )
IF(ASSOCIATED(T%XAC_ROOF_WAT))  DEALLOCATE(T%XAC_ROOF_WAT)
IF(ASSOCIATED(T%XAC_ROAD_WAT))  DEALLOCATE(T%XAC_ROAD_WAT)
IF(ASSOCIATED(T%XQSAT_ROOF  ))  DEALLOCATE(T%XQSAT_ROOF  )
IF(ASSOCIATED(T%XQSAT_ROAD  ))  DEALLOCATE(T%XQSAT_ROAD  )
IF(ASSOCIATED(T%XDELT_ROOF  ))  DEALLOCATE(T%XDELT_ROOF  )
IF(ASSOCIATED(T%XDELT_ROAD  ))  DEALLOCATE(T%XDELT_ROAD  )
!
!-------------------------------------------------------------------------------------
!
IF(ASSOCIATED(CHT%XDEP))      DEALLOCATE(CHT%XDEP)
IF(ASSOCIATED(CHT%CCH_NAMES)) DEALLOCATE(CHT%CCH_NAMES)
IF(ASSOCIATED(CHT%CSV))       DEALLOCATE(CHT%CSV)
!
!-------------------------------------------------------------------------------------
!
IF(ASSOCIATED(DTT%XPAR_Z0_TOWN    )) DEALLOCATE(DTT%XPAR_Z0_TOWN    )
IF(ASSOCIATED(DTT%XPAR_BLD        )) DEALLOCATE(DTT%XPAR_BLD        )
IF(ASSOCIATED(DTT%XPAR_ALB_ROOF   )) DEALLOCATE(DTT%XPAR_ALB_ROOF   )
IF(ASSOCIATED(DTT%XPAR_EMIS_ROOF  )) DEALLOCATE(DTT%XPAR_EMIS_ROOF  )
IF(ASSOCIATED(DTT%XPAR_HC_ROOF    )) DEALLOCATE(DTT%XPAR_HC_ROOF    )
IF(ASSOCIATED(DTT%XPAR_TC_ROOF    )) DEALLOCATE(DTT%XPAR_TC_ROOF    )
IF(ASSOCIATED(DTT%XPAR_D_ROOF     )) DEALLOCATE(DTT%XPAR_D_ROOF     )
IF(ASSOCIATED(DTT%XPAR_ALB_ROAD   )) DEALLOCATE(DTT%XPAR_ALB_ROAD   )
IF(ASSOCIATED(DTT%XPAR_EMIS_ROAD  )) DEALLOCATE(DTT%XPAR_EMIS_ROAD  )
IF(ASSOCIATED(DTT%XPAR_HC_ROAD    )) DEALLOCATE(DTT%XPAR_HC_ROAD    )
IF(ASSOCIATED(DTT%XPAR_TC_ROAD    )) DEALLOCATE(DTT%XPAR_TC_ROAD    )
IF(ASSOCIATED(DTT%XPAR_D_ROAD     )) DEALLOCATE(DTT%XPAR_D_ROAD     )
IF(ASSOCIATED(DTT%XPAR_ALB_WALL   )) DEALLOCATE(DTT%XPAR_ALB_WALL   )
IF(ASSOCIATED(DTT%XPAR_EMIS_WALL  )) DEALLOCATE(DTT%XPAR_EMIS_WALL  )
IF(ASSOCIATED(DTT%XPAR_HC_WALL    )) DEALLOCATE(DTT%XPAR_HC_WALL    )
IF(ASSOCIATED(DTT%XPAR_TC_WALL    )) DEALLOCATE(DTT%XPAR_TC_WALL    )
IF(ASSOCIATED(DTT%XPAR_D_WALL     )) DEALLOCATE(DTT%XPAR_D_WALL     )
IF(ASSOCIATED(DTT%XPAR_BLD_HEIGHT )) DEALLOCATE(DTT%XPAR_BLD_HEIGHT )
IF(ASSOCIATED(DTT%XPAR_WALL_O_HOR )) DEALLOCATE(DTT%XPAR_WALL_O_HOR )
IF(ASSOCIATED(DTT%XPAR_H_TRAFFIC  )) DEALLOCATE(DTT%XPAR_H_TRAFFIC  )
IF(ASSOCIATED(DTT%XPAR_LE_TRAFFIC )) DEALLOCATE(DTT%XPAR_LE_TRAFFIC )
IF(ASSOCIATED(DTT%XPAR_H_INDUSTRY )) DEALLOCATE(DTT%XPAR_H_INDUSTRY )
IF(ASSOCIATED(DTT%XPAR_LE_INDUSTRY)) DEALLOCATE(DTT%XPAR_LE_INDUSTRY)
IF(ASSOCIATED(DTT%XPAR_GARDEN     )) DEALLOCATE(DTT%XPAR_GARDEN     )
IF(ASSOCIATED(DTT%XPAR_ROAD_DIR   )) DEALLOCATE(DTT%XPAR_ROAD_DIR   )
IF(ASSOCIATED(DTT%NPAR_BLDTYPE    )) DEALLOCATE(DTT%NPAR_BLDTYPE    )
IF(ASSOCIATED(DTT%NPAR_BLD_AGE    )) DEALLOCATE(DTT%NPAR_BLD_AGE    )
IF(ASSOCIATED(DTT%NPAR_BLDCODE    )) DEALLOCATE(DTT%NPAR_BLDCODE    )
IF(ASSOCIATED(DTT%NPAR_USETYPE    )) DEALLOCATE(DTT%NPAR_USETYPE    )
!
!-------------------------------------------------------------------------------------
!
IF(ASSOCIATED(B%XHC_FLOOR   ))  DEALLOCATE(B%XHC_FLOOR   )
IF(ASSOCIATED(B%XTC_FLOOR   ))  DEALLOCATE(B%XTC_FLOOR   )
IF(ASSOCIATED(B%XD_FLOOR    ))  DEALLOCATE(B%XD_FLOOR    )
!
IF(ASSOCIATED(B%XF_WASTE_CAN))  DEALLOCATE(B%XF_WASTE_CAN)
IF(ASSOCIATED(B%XEFF_HEAT   ))  DEALLOCATE(B%XEFF_HEAT   )
IF(ASSOCIATED(B%XQIN        ))  DEALLOCATE(B%XQIN        )
IF(ASSOCIATED(B%XQIN_FRAD   ))  DEALLOCATE(B%XQIN_FRAD   )
IF(ASSOCIATED(B%XSHGC       ))  DEALLOCATE(B%XSHGC       )
IF(ASSOCIATED(B%XU_WIN      ))  DEALLOCATE(B%XU_WIN      )
IF(ASSOCIATED(B%XTRAN_WIN   ))  DEALLOCATE(B%XTRAN_WIN   )
IF(ASSOCIATED(B%XGR         ))  DEALLOCATE(B%XGR         )
IF(ASSOCIATED(B%XFLOOR_HEIGHT)) DEALLOCATE(B%XFLOOR_HEIGHT)
IF(ASSOCIATED(B%XINF        ))  DEALLOCATE(B%XINF        )
!
IF(ASSOCIATED(B%XQIN_FLAT   ))  DEALLOCATE(B%XQIN_FLAT   )
IF(ASSOCIATED(B%XHR_TARGET  ))  DEALLOCATE(B%XHR_TARGET  )
IF(ASSOCIATED(B%XV_VENT     ))  DEALLOCATE(B%XV_VENT     )
IF(ASSOCIATED(B%XCAP_SYS_HEAT)) DEALLOCATE(B%XCAP_SYS_HEAT)
IF(ASSOCIATED(B%XCAP_SYS_RAT))  DEALLOCATE(B%XCAP_SYS_RAT)
IF(ASSOCIATED(B%XT_ADP      ))  DEALLOCATE(B%XT_ADP      )
IF(ASSOCIATED(B%XM_SYS_RAT  ))  DEALLOCATE(B%XM_SYS_RAT  )
IF(ASSOCIATED(B%XCOP_RAT    ))  DEALLOCATE(B%XCOP_RAT    )
IF(ASSOCIATED(B%XT_SIZE_MAX ))  DEALLOCATE(B%XT_SIZE_MAX )
IF(ASSOCIATED(B%XT_SIZE_MIN ))  DEALLOCATE(B%XT_SIZE_MIN )
!
IF(ASSOCIATED(B%XABS_WIN    ))  DEALLOCATE(B%XABS_WIN    )
IF(ASSOCIATED(B%XALB_WIN    ))  DEALLOCATE(B%XALB_WIN    )
IF(ASSOCIATED(B%XUGG_WIN    ))  DEALLOCATE(B%XUGG_WIN    )
IF(ASSOCIATED(B%LSHAD_DAY   ))  DEALLOCATE(B%LSHAD_DAY   )
IF(ASSOCIATED(B%LNATVENT_NIGHT)) DEALLOCATE(B%LNATVENT_NIGHT)
IF(ASSOCIATED(B%CNATVENT    ))  DEALLOCATE(B%CNATVENT)
IF(ASSOCIATED(B%LSHADE      ))  DEALLOCATE(B%LSHADE)
IF(ASSOCIATED(B%XF_WATER_COND)) DEALLOCATE(B%XF_WATER_COND)
IF(ASSOCIATED(B%XSHGC_SH    ))  DEALLOCATE(B%XSHGC_SH)

IF(ASSOCIATED(DTT%XPAR_ROUGH_ROOF ))  DEALLOCATE(DTT%XPAR_ROUGH_ROOF)
IF(ASSOCIATED(DTT%XPAR_ROUGH_WALL ))  DEALLOCATE(DTT%XPAR_ROUGH_WALL)
IF(ASSOCIATED(DTT%XPAR_RESIDENTIAL))  DEALLOCATE(DTT%XPAR_RESIDENTIAL)
IF(ASSOCIATED(T%XROUGH_ROOF ))  DEALLOCATE(T%XROUGH_ROOF)
IF(ASSOCIATED(T%XROUGH_WALL ))  DEALLOCATE(T%XROUGH_WALL)
IF(ASSOCIATED(T%XRESIDENTIAL))  DEALLOCATE(T%XRESIDENTIAL)

IF(ASSOCIATED(B%XN_FLOOR ))  DEALLOCATE(B%XN_FLOOR)
IF(ASSOCIATED(B%XGLAZ_O_BLD ))  DEALLOCATE(B%XGLAZ_O_BLD)
IF(ASSOCIATED(B%XMASS_O_BLD ))  DEALLOCATE(B%XMASS_O_BLD)
IF(ASSOCIATED(B%XFLOOR_HW_RATIO ))  DEALLOCATE(B%XFLOOR_HW_RATIO)
IF(ASSOCIATED(B%XF_FLOOR_MASS ))  DEALLOCATE(B%XF_FLOOR_MASS)
IF(ASSOCIATED(B%XF_FLOOR_WALL ))  DEALLOCATE(B%XF_FLOOR_WALL)
IF(ASSOCIATED(B%XF_FLOOR_WIN ))  DEALLOCATE(B%XF_FLOOR_WIN)
IF(ASSOCIATED(B%XF_FLOOR_ROOF ))  DEALLOCATE(B%XF_FLOOR_ROOF)
IF(ASSOCIATED(B%XF_WALL_FLOOR ))  DEALLOCATE(B%XF_WALL_FLOOR)
IF(ASSOCIATED(B%XF_WALL_MASS ))  DEALLOCATE(B%XF_WALL_MASS)
IF(ASSOCIATED(B%XF_WALL_WIN ))  DEALLOCATE(B%XF_WALL_WIN)
IF(ASSOCIATED(B%XF_WIN_FLOOR ))  DEALLOCATE(B%XF_WIN_FLOOR)
IF(ASSOCIATED(B%XF_WIN_MASS ))  DEALLOCATE(B%XF_WIN_MASS)
IF(ASSOCIATED(B%XF_WIN_WALL ))  DEALLOCATE(B%XF_WIN_WALL)
IF(ASSOCIATED(B%XF_MASS_FLOOR ))  DEALLOCATE(B%XF_MASS_FLOOR)
IF(ASSOCIATED(B%XF_MASS_WALL ))  DEALLOCATE(B%XF_MASS_WALL)
IF(ASSOCIATED(B%XF_MASS_WIN ))  DEALLOCATE(B%XF_MASS_WIN)
IF(ASSOCIATED(B%XTI_BLD ))  DEALLOCATE(B%XTI_BLD)
IF(ASSOCIATED(B%XQI_BLD ))  DEALLOCATE(B%XQI_BLD)
IF(ASSOCIATED(B%XT_FLOOR ))  DEALLOCATE(B%XT_FLOOR)
IF(ASSOCIATED(B%XT_MASS ))  DEALLOCATE(B%XT_MASS)
IF(ASSOCIATED(B%XAUX_MAX ))  DEALLOCATE(B%XAUX_MAX)
IF(ASSOCIATED(B%XT_WIN2 ))  DEALLOCATE(B%XT_WIN2)
IF(ASSOCIATED(B%XT_WIN1 ))  DEALLOCATE(B%XT_WIN1)
!
!
IF (LHOOK) CALL DR_HOOK('DEALLOC_TEB_N',1,ZHOOK_HANDLE)
!
!-------------------------------------------------------------------------------------
!
END SUBROUTINE DEALLOC_TEB_n


