!     #############################################################
      SUBROUTINE DEALLOC_DIAG_SURF_ATM_n (DGU,DGUC,DGUP,DGUPC)
!     #############################################################
!
!!    AUTHOR
!!    ------
!!      V. Masson   *Meteo France*
!!
!!    MODIFICATIONS
!!    -------------
!!      Original    01/2004
!!      Modified    01/2006 : sea flux parameterization.
!!      B.Decharme  04/2013 : new diags
!-------------------------------------------------------------------------------
!
!*       0.    DECLARATIONS
!              ------------
!
!
USE MODD_DATA_COVER_PAR, ONLY : NTILESFC
!
USE MODD_DIAG_n, ONLY : DIAG_t, DIAG_PATCH_t
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE
!
!*       0.1   Declarations of arguments
!              -------------------------
!
!*       0.2   Declarations of local variables
!              -------------------------------
!
!-------------------------------------------------------------------------------
!
!

!
TYPE(DIAG_t), INTENT(INOUT) :: DGU
TYPE(DIAG_t), INTENT(INOUT) :: DGUC
TYPE(DIAG_PATCH_t), INTENT(INOUT) :: DGUP
TYPE(DIAG_PATCH_t), INTENT(INOUT) :: DGUPC
!
INTEGER :: JTILE
REAL(KIND=JPRB) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('DEALLOC_DIAG_SURF_ATM_N',0,ZHOOK_HANDLE)
DO JTILE=1,NTILESFC
  DEALLOCATE(DGUP%AL(JTILE)%XRI     )
  DEALLOCATE(DGUP%AL(JTILE)%XCD     )
  DEALLOCATE(DGUP%AL(JTILE)%XCH     )
  DEALLOCATE(DGUP%AL(JTILE)%XCE     )
  DEALLOCATE(DGUP%AL(JTILE)%XQS     )
  DEALLOCATE(DGUP%AL(JTILE)%XZ0     )
  DEALLOCATE(DGUP%AL(JTILE)%XZ0H    )
  DEALLOCATE(DGUP%AL(JTILE)%XRN     )
  DEALLOCATE(DGUP%AL(JTILE)%XH      )
  DEALLOCATE(DGUP%AL(JTILE)%XLE     )
  DEALLOCATE(DGUP%AL(JTILE)%XLEI    )
  DEALLOCATE(DGUP%AL(JTILE)%XGFLUX  )
  DEALLOCATE(DGUP%AL(JTILE)%XEVAP   )
  DEALLOCATE(DGUP%AL(JTILE)%XSUBL   )
  DEALLOCATE(DGUP%AL(JTILE)%XT2M    )
  DEALLOCATE(DGUP%AL(JTILE)%XTS     )
  DEALLOCATE(DGUP%AL(JTILE)%XT2M_MIN)
  DEALLOCATE(DGUP%AL(JTILE)%XT2M_MAX)
  DEALLOCATE(DGUP%AL(JTILE)%XQ2M    )
  DEALLOCATE(DGUP%AL(JTILE)%XHU2M   )
  DEALLOCATE(DGUP%AL(JTILE)%XZON10M )
  DEALLOCATE(DGUP%AL(JTILE)%XMER10M )
  !
  DEALLOCATE(DGUP%AL(JTILE)%XHU2M_MIN    )
  DEALLOCATE(DGUP%AL(JTILE)%XHU2M_MAX   )
  DEALLOCATE(DGUP%AL(JTILE)%XWIND10M     )
  DEALLOCATE(DGUP%AL(JTILE)%XWIND10M_MAX )
  !  
  DEALLOCATE(DGUPC%AL(JTILE)%XRN     )
  DEALLOCATE(DGUPC%AL(JTILE)%XH      )
  DEALLOCATE(DGUPC%AL(JTILE)%XLE     )
  DEALLOCATE(DGUPC%AL(JTILE)%XLEI    )
  DEALLOCATE(DGUPC%AL(JTILE)%XGFLUX  )
  DEALLOCATE(DGUPC%AL(JTILE)%XEVAP   )
  DEALLOCATE(DGUPC%AL(JTILE)%XSUBL   )
  DEALLOCATE(DGUPC%AL(JTILE)%XSWD    )
  DEALLOCATE(DGUPC%AL(JTILE)%XSWU    )
  DEALLOCATE(DGUPC%AL(JTILE)%XLWD    )
  DEALLOCATE(DGUPC%AL(JTILE)%XLWU    )
  DEALLOCATE(DGUPC%AL(JTILE)%XFMU    )
  DEALLOCATE(DGUPC%AL(JTILE)%XFMV    )
  !
ENDDO
!
DEALLOCATE(DGU%XTRAD   )
DEALLOCATE(DGU%XEMIS   )
!
DEALLOCATE(DGU%XRI     )
DEALLOCATE(DGU%XCD     )
DEALLOCATE(DGU%XCH     )
DEALLOCATE(DGU%XCE     )
DEALLOCATE(DGU%XZ0     )
DEALLOCATE(DGU%XZ0H    )
DEALLOCATE(DGU%XRN     )
DEALLOCATE(DGU%XH      )
DEALLOCATE(DGU%XLE     )
DEALLOCATE(DGU%XLEI    )
DEALLOCATE(DGU%XGFLUX  )
DEALLOCATE(DGU%XEVAP   )
DEALLOCATE(DGU%XSUBL   )
DEALLOCATE(DGU%XT2M    )
DEALLOCATE(DGU%XTS     )
DEALLOCATE(DGU%XT2M_MIN)
DEALLOCATE(DGU%XT2M_MAX)
DEALLOCATE(DGU%XQ2M    )
DEALLOCATE(DGU%XHU2M   )
DEALLOCATE(DGU%XZON10M )
DEALLOCATE(DGU%XMER10M )
DEALLOCATE(DGU%XSFCO2  )
DEALLOCATE(DGU%XT2M_MIN_ZS    )
DEALLOCATE(DGU%XQ2M_MIN_ZS    )
DEALLOCATE(DGU%XHU2M_MIN_ZS   )
DEALLOCATE(DGU%XPS                )
DEALLOCATE(DGU%XRHOA              )
!
DEALLOCATE(DGU%XHU2M_MIN     )
DEALLOCATE(DGU%XHU2M_MAX     )
DEALLOCATE(DGU%XWIND10M      )
DEALLOCATE(DGU%XWIND10M_MAX  )
!
DEALLOCATE(DGUC%XRN     )
DEALLOCATE(DGUC%XH      )
DEALLOCATE(DGUC%XLE     )
DEALLOCATE(DGUC%XLEI    )
DEALLOCATE(DGUC%XGFLUX  )
DEALLOCATE(DGUC%XEVAP   )
DEALLOCATE(DGUC%XSUBL   )
DEALLOCATE(DGUC%XSWD    )
DEALLOCATE(DGUC%XSWU    )
DEALLOCATE(DGUC%XLWD    )
DEALLOCATE(DGUC%XLWU    )
DEALLOCATE(DGUC%XFMU    )
DEALLOCATE(DGUC%XFMV    )
!
IF (LHOOK) CALL DR_HOOK('DEALLOC_DIAG_SURF_ATM_N',1,ZHOOK_HANDLE)
! 
!-------------------------------------------------------------------------------
!
END SUBROUTINE DEALLOC_DIAG_SURF_ATM_n
