!     #################################################################################
SUBROUTINE DEALLOC_SURF_ATM_n
!     #################################################################################
!
!!****  *DEALLOC_SURF_ATM_n * - Deallocate all arrays
!!
!!    PURPOSE
!!    -------
!
!!**  METHOD
!!    ------
!!
!!    REFERENCE
!!    ---------
!!      
!!
!!    AUTHOR
!!    ------
!!     V. Masson 
!!
!!    MODIFICATIONS
!!    -------------
!!      Original    01/2004
!!------------------------------------------------------------------
!

!
USE MODD_SURF_ATM_n, ONLY : U => SURF_ATM
!
USE MODD_SURF_ATM_GRID_n, ONLY : UG => SURF_ATM_GRID
USE MODD_SURF_ATM_SSO_n, ONLY : USS => SURF_ATM_SSO
USE MODD_CH_EMIS_FIELD_n, ONLY : CHE => CH_EMIS_FIELD
USE MODD_DUMMY_SURF_FIELDS_n, ONLY : DUU => DUMMY_SURF_FIELDS
USE MODD_CH_SURF_n, ONLY : CHU => CH_SURF
USE MODD_SV_n, ONLY : SV => SV
!
USE MODI_DEALLOC_SEA_n
USE MODI_DEALLOC_INLAND_WATER_n
USE MODI_DEALLOC_NATURE_n
USE MODI_DEALLOC_TOWN_n
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE
!
!*      0.1    declarations of arguments
!
!
!*      0.2    declarations of local variables
!
!-------------------------------------------------------------------------------------
!

REAL(KIND=JPRB) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('DEALLOC_SURF_ATM_N',0,ZHOOK_HANDLE)
IF (ASSOCIATED(U%XNATURE)) DEALLOCATE(U%XNATURE)
IF (ASSOCIATED(U%XTOWN  )) DEALLOCATE(U%XTOWN  )
IF (ASSOCIATED(U%XWATER )) DEALLOCATE(U%XWATER )
IF (ASSOCIATED(U%XSEA   )) DEALLOCATE(U%XSEA   )
!
IF (ASSOCIATED(U%LCOVER )) DEALLOCATE(U%LCOVER )
IF (ASSOCIATED(U%XCOVER )) DEALLOCATE(U%XCOVER )
IF (ASSOCIATED(U%XZS    )) DEALLOCATE(U%XZS    )
!
IF (ASSOCIATED(U%NR_NATURE)) DEALLOCATE(U%NR_NATURE)
IF (ASSOCIATED(U%NR_TOWN  )) DEALLOCATE(U%NR_TOWN  )
IF (ASSOCIATED(U%NR_WATER )) DEALLOCATE(U%NR_WATER )
IF (ASSOCIATED(U%NR_SEA   )) DEALLOCATE(U%NR_SEA   )
!
!-------------------------------------------------------------------------------------
!
IF (ASSOCIATED(UG%XGRID_PAR )) DEALLOCATE(UG%XGRID_PAR )
IF (ASSOCIATED(UG%XLAT      )) DEALLOCATE(UG%XLAT      )
IF (ASSOCIATED(UG%XLON      )) DEALLOCATE(UG%XLON      )
IF (ASSOCIATED(UG%XMESH_SIZE)) DEALLOCATE(UG%XMESH_SIZE)
IF (ASSOCIATED(UG%XJPDIR    )) DEALLOCATE(UG%XJPDIR    )
!
!-------------------------------------------------------------------------------------
!
IF (ASSOCIATED(USS%XAOSIP))     DEALLOCATE( USS%XAOSIP)
IF (ASSOCIATED(USS%XAOSIM))     DEALLOCATE( USS%XAOSIM)
IF (ASSOCIATED(USS%XAOSJP))     DEALLOCATE( USS%XAOSJP)
IF (ASSOCIATED(USS%XAOSJM))     DEALLOCATE( USS%XAOSJM)
IF (ASSOCIATED(USS%XHO2IP))     DEALLOCATE( USS%XHO2IP)
IF (ASSOCIATED(USS%XHO2IM))     DEALLOCATE( USS%XHO2IM)
IF (ASSOCIATED(USS%XHO2JP))     DEALLOCATE( USS%XHO2JP)
IF (ASSOCIATED(USS%XHO2JM))     DEALLOCATE( USS%XHO2JM)
IF (ASSOCIATED(USS%XZ0REL))     DEALLOCATE( USS%XZ0REL)
IF (ASSOCIATED(USS%XSSO_SLOPE)) DEALLOCATE( USS%XSSO_SLOPE)
IF (ASSOCIATED(USS%XSSO_ANIS))  DEALLOCATE( USS%XSSO_ANIS)
IF (ASSOCIATED(USS%XSSO_DIR))   DEALLOCATE( USS%XSSO_DIR)
IF (ASSOCIATED(USS%XSSO_STDEV)) DEALLOCATE( USS%XSSO_STDEV)
IF (ASSOCIATED(USS%XAVG_ZS))    DEALLOCATE( USS%XAVG_ZS)
IF (ASSOCIATED(USS%XSIL_ZS))    DEALLOCATE( USS%XSIL_ZS)
IF (ASSOCIATED(USS%XMAX_ZS))    DEALLOCATE( USS%XMAX_ZS)
IF (ASSOCIATED(USS%XMIN_ZS))    DEALLOCATE( USS%XMIN_ZS)
!
!-------------------------------------------------------------------------------------
!
IF (ASSOCIATED(CHE%CEMIS_AREA))   DEALLOCATE(CHE%CEMIS_AREA)
IF (ASSOCIATED(CHE%CEMIS_COMMENT))DEALLOCATE(CHE%CEMIS_COMMENT)
IF (ASSOCIATED(CHE%CEMIS_NAME))   DEALLOCATE(CHE%CEMIS_NAME)
IF (ASSOCIATED(CHE%NEMIS_TIME))   DEALLOCATE(CHE%NEMIS_TIME)
IF (ASSOCIATED(CHE%XEMIS_FIELDS)) DEALLOCATE(CHE%XEMIS_FIELDS)
IF (ASSOCIATED(CHE%TSEMISS))      DEALLOCATE(CHE%TSEMISS)
!
!-------------------------------------------------------------------------------------
!
IF (ASSOCIATED(DUU%XDUMMY_FIELDS)) DEALLOCATE( DUU%XDUMMY_FIELDS)
!
!-------------------------------------------------------------------------------------
!
IF (ASSOCIATED(SV%CSV)) DEALLOCATE(SV%CSV)
!
!-------------------------------------------------------------------------------------
!
IF (ASSOCIATED(CHU%CCH_NAMES))  DEALLOCATE(CHU%CCH_NAMES)
IF (ASSOCIATED(CHE%CEMIS_NAME)) DEALLOCATE(CHE%CEMIS_NAME)
IF (ASSOCIATED(CHE%CEMIS_AREA)) DEALLOCATE(CHE%CEMIS_AREA)
IF (ASSOCIATED(CHE%NEMIS_TIME)) DEALLOCATE(CHE%NEMIS_TIME )
IF (ASSOCIATED(CHE%TSEMISS))    DEALLOCATE(CHE%TSEMISS)
!
!-------------------------------------------------------------------------------------
!
IF (U%NDIM_SEA    >0) CALL DEALLOC_SEA_n
IF (U%NDIM_WATER  >0) CALL DEALLOC_INLAND_WATER_n
IF (U%NDIM_NATURE >0) CALL DEALLOC_NATURE_n
IF (U%NDIM_TOWN   >0) CALL DEALLOC_TOWN_n
IF (LHOOK) CALL DR_HOOK('DEALLOC_SURF_ATM_N',1,ZHOOK_HANDLE)
!
!--------------------------------------------------------------------------------------
!
END SUBROUTINE DEALLOC_SURF_ATM_n
