!     #########
      SUBROUTINE DIAG_TEB_GARDEN_INIT_n (DGMTO, DGGD, DGMGD, DGEGD, TGD, &
                                         KGROUND_LAYER, &
                                         HPROGRAM,KLU,KSW)
!     #####################
!
!!****  *DIAG_TEB_GARDEN_INIT_n* - routine to initialize TEB-ISBA diagnostic variables
!!
!!    PURPOSE
!!    -------
!!
!!**  METHOD
!!    ------
!!
!!    EXTERNAL
!!    --------
!!
!!
!!    IMPLICIT ARGUMENTS
!!    ------------------
!!
!!    REFERENCE
!!    ---------
!!
!!
!!    AUTHOR
!!    ------
!!      V. Masson   *Meteo France*
!!
!!    MODIFICATIONS
!!    -------------
!!      Original    02/2003 
!!      modified    11/2003 by P. LeMoigne: surface cumulated energy budget
!!      modified    10/2004 by P. LeMoigne: surface miscellaneous fields
!!      B. Decharme    2008    New diag for water budget and allow to reset
!               cumulatives variables at the beginning of a run
!-------------------------------------------------------------------------------
!
!*       0.    DECLARATIONS
!              ------------
!
!
USE MODD_DIAG_MISC_TEB_OPTION_n, ONLY : DIAG_MISC_TEB_OPTIONS_t
USE MODD_DIAG_EVAP_ISBA_n, ONLY : DIAG_EVAP_ISBA_t
USE MODD_DIAG_ISBA_n, ONLY : DIAG_ISBA_t
USE MODD_DIAG_MISC_ISBA_n, ONLY : DIAG_MISC_ISBA_t
USE MODD_TEB_VEG_n, ONLY : TEB_VEG_PROG_t
USE MODD_ISBA_OPTIONS_n, ONLY : ISBA_OPTIONS_t
USE MODD_ISBA_PGD_n, ONLY : ISBA_PGD_t
!
USE MODD_SURF_PAR,          ONLY : XUNDEF
USE MODD_TYPE_DATE_SURF
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE
!
!*       0.1   Declarations of arguments
!              -------------------------
!
!
TYPE(DIAG_MISC_TEB_OPTIONS_t), INTENT(INOUT) :: DGMTO
TYPE(DIAG_ISBA_t), INTENT(INOUT) :: DGGD
TYPE(DIAG_EVAP_ISBA_t), INTENT(INOUT) :: DGEGD
TYPE(DIAG_MISC_ISBA_t), INTENT(INOUT) :: DGMGD
TYPE(TEB_VEG_PROG_t), INTENT(INOUT) :: TGD
!
INTEGER, INTENT(IN) :: KGROUND_LAYER
INTEGER, INTENT(IN)         :: KLU       ! size of arrays
INTEGER, INTENT(IN)         :: KSW       ! spectral bands
 CHARACTER(LEN=6), INTENT(IN):: HPROGRAM  ! program calling
!
!*       0.2   Declarations of local variables
!              -------------------------------
!
INTEGER           :: IRESP          ! IRESP  : return-code if a problem appears
 CHARACTER(LEN=12) :: YREC           ! Name of the article to be read
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
!-------------------------------------------------------------------------------
!
IF (LHOOK) CALL DR_HOOK('DIAG_TEB_GARDEN_INIT_N',0,ZHOOK_HANDLE)
!
ALLOCATE(DGGD%XRI     (KLU,1)) 
!
DGGD%XRI         = XUNDEF
!
ALLOCATE(DGGD%XCD     (KLU,1)) 
ALLOCATE(DGGD%XCH     (KLU,1)) 
ALLOCATE(DGGD%XRN     (KLU,1)) 
ALLOCATE(DGGD%XH      (KLU,1)) 
ALLOCATE(DGGD%XGFLUX  (KLU,1)) 
ALLOCATE(DGGD%XQS     (KLU,1)) 
!
DGGD%XCD         = XUNDEF
DGGD%XCH         = XUNDEF
DGGD%XRN         = XUNDEF
DGGD%XH          = XUNDEF
DGGD%XGFLUX      = XUNDEF
DGGD%XQS         = XUNDEF
!
ALLOCATE(DGGD%XLEI    (KLU,1))
!
ALLOCATE(DGEGD%XLEG    (KLU,1)) 
ALLOCATE(DGEGD%XLEGI   (KLU,1)) 
ALLOCATE(DGEGD%XLEV    (KLU,1)) 
ALLOCATE(DGEGD%XLES    (KLU,1)) 
ALLOCATE(DGEGD%XLER    (KLU,1)) 
ALLOCATE(DGEGD%XLETR   (KLU,1)) 
ALLOCATE(DGEGD%XEVAP   (KLU,1)) 
ALLOCATE(DGEGD%XDRAIN  (KLU,1)) 
ALLOCATE(DGEGD%XRUNOFF (KLU,1)) 
ALLOCATE(DGEGD%XHORT   (KLU,1)) 
ALLOCATE(DGEGD%XDRIP   (KLU,1)) 
ALLOCATE(DGEGD%XRRVEG  (KLU,1)) 
ALLOCATE(DGEGD%XMELT   (KLU,1)) 
ALLOCATE(DGEGD%XIRRIG_FLUX(KLU,1))
!
DGGD%XLEI        = XUNDEF
!
DGEGD%XLEG        = XUNDEF
DGEGD%XLEGI       = XUNDEF
DGEGD%XLEV        = XUNDEF
DGEGD%XLES        = XUNDEF
DGEGD%XLER        = XUNDEF
DGEGD%XLETR       = XUNDEF
DGEGD%XEVAP       = XUNDEF
DGEGD%XDRAIN      = XUNDEF
DGEGD%XRUNOFF     = XUNDEF
DGEGD%XHORT       = XUNDEF
DGEGD%XDRIP       = XUNDEF
DGEGD%XRRVEG      = XUNDEF
DGEGD%XMELT       = XUNDEF
DGEGD%XIRRIG_FLUX = XUNDEF
!
ALLOCATE(DGMGD%XSNOWTEMP(KLU,TGD%CUR%TSNOW%NLAYER        ,1)) 
ALLOCATE(DGMGD%XSNOWLIQ (KLU,TGD%CUR%TSNOW%NLAYER        ,1)) 

!
DGMGD%XSNOWTEMP   = XUNDEF
DGMGD%XSNOWLIQ    = XUNDEF
!
ALLOCATE(DGMGD%XHV     (KLU,1))
ALLOCATE(DGMGD%XALBT   (KLU,1)) 
!
DGMGD%XALBT             = XUNDEF
!
ALLOCATE(DGMGD%XFAPAR    (KLU,1))
ALLOCATE(DGMGD%XFAPIR    (KLU,1))
ALLOCATE(DGMGD%XFAPAR_BS (KLU,1))
ALLOCATE(DGMGD%XFAPIR_BS (KLU,1))
ALLOCATE(DGMGD%XDFAPARC  (KLU,1))
ALLOCATE(DGMGD%XDFAPIRC  (KLU,1))
ALLOCATE(DGMGD%XDLAI_EFFC(KLU,1))
!
DGMGD%XFAPAR     = XUNDEF
DGMGD%XFAPIR     = XUNDEF
DGMGD%XFAPAR_BS  = XUNDEF
DGMGD%XFAPIR_BS  = XUNDEF
DGMGD%XDFAPARC   = XUNDEF
DGMGD%XDFAPIRC   = XUNDEF
DGMGD%XDLAI_EFFC = XUNDEF
!
!* surface energy budget
!
!IF (LSURF_BUDGET) THEN
  !
  ALLOCATE(DGGD%XSWD      (KLU,1))
  ALLOCATE(DGGD%XSWU      (KLU,1))
  ALLOCATE(DGGD%XSWBD     (KLU,KSW,1))
  ALLOCATE(DGGD%XSWBU     (KLU,KSW,1))
  ALLOCATE(DGGD%XLWD      (KLU,1))
  ALLOCATE(DGGD%XLWU      (KLU,1))
  ALLOCATE(DGGD%XFMU      (KLU,1))
  ALLOCATE(DGGD%XFMV      (KLU,1))
  !
  DGGD%XSWD     = XUNDEF
  DGGD%XSWU     = XUNDEF
  DGGD%XSWBD    = XUNDEF
  DGGD%XSWBU    = XUNDEF
  DGGD%XLWD     = XUNDEF
  DGGD%XLWU     = XUNDEF
  DGGD%XFMU     = XUNDEF
  DGGD%XFMV     = XUNDEF
  !
!END IF
!
!* surface temperature and parameters at 2m
!
ALLOCATE(DGGD%XTS    (KLU,1))
DGGD%XTS     = XUNDEF
ALLOCATE(DGGD%XTSRAD (KLU,1))
DGGD%XTSRAD  = XUNDEF
!
!* miscellaneous surface fields
!
IF (DGMTO%LSURF_MISC_BUDGET) THEN
  ALLOCATE(DGMGD%XSWI    (KLU,KGROUND_LAYER,1))
  ALLOCATE(DGMGD%XTSWI   (KLU,KGROUND_LAYER,1))
  ALLOCATE(DGMGD%XTWSNOW (KLU,1))
  ALLOCATE(DGMGD%XTDSNOW (KLU,1))
  DGMGD%XSWI     = XUNDEF
  DGMGD%XTSWI    = XUNDEF
  DGMGD%XTWSNOW  = XUNDEF
  DGMGD%XTDSNOW  = XUNDEF
ELSE
  ALLOCATE(DGMGD%XSWI    (0,0,0))
  ALLOCATE(DGMGD%XTSWI   (0,0,0))
  ALLOCATE(DGMGD%XTWSNOW (0,0))
  ALLOCATE(DGMGD%XTDSNOW (0,0))
ENDIF
!
ALLOCATE(DGMGD%XALBT   (KLU,1))
!
ALLOCATE(DGEGD%XGPP    (KLU,1))
ALLOCATE(DGEGD%XRESP_AUTO  (KLU,1))
ALLOCATE(DGEGD%XRESP_ECO   (KLU,1))
!
DGMGD%XALBT    = XUNDEF
!
DGEGD%XGPP     = XUNDEF
DGEGD%XRESP_AUTO   = XUNDEF
DGEGD%XRESP_ECO    = XUNDEF  
!
!END IF
!
!* transfer coefficients
!
!IF (LCOEF) THEN
  !
  ALLOCATE(DGGD%XCE            (KLU,1))
  ALLOCATE(DGGD%XZ0_WITH_SNOW  (KLU,1))
  ALLOCATE(DGGD%XZ0H_WITH_SNOW (KLU,1))
  ALLOCATE(DGGD%XZ0EFF         (KLU,1))
  !
  DGGD%XCE            = XUNDEF
  DGGD%XZ0_WITH_SNOW  = XUNDEF
  DGGD%XZ0H_WITH_SNOW = XUNDEF
  DGGD%XZ0EFF         = XUNDEF
!END IF
!
!
!* surface humidity
!
!IF (LSURF_VARS) THEN
  ALLOCATE(DGGD%XQS            (KLU,1))
  !
  DGGD%XQS            = XUNDEF
!END IF
!
!* Irrigation threshold
!
!IF (LAGRIP) THEN
  ALLOCATE(DGMGD%XSEUIL(KLU,1))
  !
  DGMGD%XSEUIL         = XUNDEF
!END IF
!
IF (LHOOK) CALL DR_HOOK('DIAG_TEB_GARDEN_INIT_N',1,ZHOOK_HANDLE)
!
!-------------------------------------------------------------------------------
!
END SUBROUTINE DIAG_TEB_GARDEN_INIT_n
