!     #########
      SUBROUTINE DIAG_SEAFLUX_INIT_n (DGO, DSO, DGS, DGSC, OREAD_BUDGETC, S, &
                                      HPROGRAM,KLU,KSW)
!     #####################
!
!!****  *DIAG_SEAFLUX_INIT_n* - routine to initialize SEAFLUX diagnostic variables
!!
!!    PURPOSE
!!    -------
!!
!!**  METHOD
!!    ------
!!
!!    EXTERNAL
!!    --------
!!
!!
!!    IMPLICIT ARGUMENTS
!!    ------------------
!!
!!    REFERENCE
!!    ---------
!!
!!
!!    AUTHOR
!!    ------
!!      V. Masson   *Meteo France*
!!
!!    MODIFICATIONS
!!    -------------
!!      Original    01/2004 
!!      Modified    01/2006 : sea flux parameterization.
!!      Modified    08/2009 : cumulative sea flux 
!!      B. decharme 04/2013 : Add EVAP and SUBL diag
!!      S.Senesi    01/2014 : introduce fractional seaice 
!-------------------------------------------------------------------------------
!
!*       0.    DECLARATIONS
!              ------------
!
!
!
USE MODD_DIAG_OCEAN_n, ONLY : DIAG_OCEAN_t
USE MODD_DIAG_n, ONLY : DIAG_t, DIAG_OPTIONS_t
USE MODD_SEAFLUX_n, ONLY : SEAFLUX_t
!
!
!
#ifdef SFX_OL
USE MODN_IO_OFFLINE,     ONLY : LRESTART
#endif
USE MODD_SURF_PAR,       ONLY : XUNDEF
USE MODD_SFX_OASIS,      ONLY : LCPL_SEA,LCPL_SEAICE

!                                
!
!
!
USE MODI_READ_SURF
!
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE
!
!*       0.1   Declarations of arguments
!              -------------------------
!
!
!
!
TYPE(DIAG_OCEAN_t), INTENT(INOUT) :: DGO
TYPE(DIAG_OPTIONS_t), INTENT(INOUT) :: DSO
TYPE(DIAG_t), INTENT(INOUT) :: DGS
TYPE(DIAG_t), INTENT(INOUT) :: DGSC
LOGICAL, INTENT(IN) :: OREAD_BUDGETC
TYPE(SEAFLUX_t), INTENT(INOUT) :: S
!
INTEGER, INTENT(IN) :: KLU   ! size of arrays
INTEGER, INTENT(IN) :: KSW   ! number of SW spectral bands
 CHARACTER(LEN=6), INTENT(IN):: HPROGRAM  ! program calling
!
!*       0.2   Declarations of local variables
!              -------------------------------
!
INTEGER           :: IVERSION
INTEGER           :: IRESP          ! IRESP  : return-code if a problem appears
CHARACTER(LEN=12) :: YREC           ! Name of the article to be read
!
REAL(KIND=JPRB)   :: ZHOOK_HANDLE
!
!-------------------------------------------------------------------------------
!
!* surface energy budget
!
IF (LHOOK) CALL DR_HOOK('DIAG_SEAFLUX_INIT_N',0,ZHOOK_HANDLE)
ALLOCATE(DGS%XTS   (KLU))
ALLOCATE(DGS%XTSRAD(KLU))
DGS%XTS    = XUNDEF
DGS%XTSRAD = XUNDEF
!
IF (DSO%LSURF_BUDGET.OR.DSO%LSURF_BUDGETC) THEN
  ALLOCATE(DGS%XRN     (KLU))
  ALLOCATE(DGS%XH      (KLU))
  ALLOCATE(DGS%XLE     (KLU))
  ALLOCATE(DGS%XLEI    (KLU))
  ALLOCATE(DGS%XGFLUX  (KLU))
  ALLOCATE(DGS%XEVAP   (KLU))
  ALLOCATE(DGS%XSUBL   (KLU))
  ALLOCATE(DGS%XSWD    (KLU))
  ALLOCATE(DGS%XSWU    (KLU))
  ALLOCATE(DGS%XLWD    (KLU))
  ALLOCATE(DGS%XLWU    (KLU))
  ALLOCATE(DGS%XSWBD   (KLU,KSW))
  ALLOCATE(DGS%XSWBU   (KLU,KSW))
  ALLOCATE(DGS%XFMU    (KLU))
  ALLOCATE(DGS%XFMV    (KLU))
  ALLOCATE(DGS%XALBT   (KLU))  
  !
  DGS%XRN      = XUNDEF
  DGS%XH       = XUNDEF
  DGS%XLE      = XUNDEF
  DGS%XLEI     = XUNDEF
  DGS%XGFLUX   = XUNDEF
  DGS%XEVAP    = XUNDEF
  DGS%XSUBL    = XUNDEF  
  DGS%XSWD     = XUNDEF
  DGS%XSWU     = XUNDEF
  DGS%XLWD     = XUNDEF
  DGS%XLWU     = XUNDEF
  DGS%XSWBD    = XUNDEF
  DGS%XSWBU    = XUNDEF
  DGS%XFMU     = XUNDEF
  DGS%XFMV     = XUNDEF
  DGS%XALBT    = XUNDEF  
  !
ELSE
  ALLOCATE(DGS%XRN     (0))
  ALLOCATE(DGS%XH      (0))
  ALLOCATE(DGS%XLE     (0))
  ALLOCATE(DGS%XLEI    (0))
  ALLOCATE(DGS%XGFLUX  (0))
  ALLOCATE(DGS%XEVAP   (0))
  ALLOCATE(DGS%XSUBL   (0))  
  ALLOCATE(DGS%XSWD    (0))
  ALLOCATE(DGS%XSWU    (0))
  ALLOCATE(DGS%XLWD    (0))
  ALLOCATE(DGS%XLWU    (0))
  ALLOCATE(DGS%XSWBD   (0,0))
  ALLOCATE(DGS%XSWBU   (0,0))
  ALLOCATE(DGS%XFMU    (0))
  ALLOCATE(DGS%XFMV    (0))
  ALLOCATE(DGS%XALBT   (0))  
ENDIF
!
!* cumulative surface energy budget
!
#ifdef SFX_OL
IF (DSO%LSURF_BUDGETC .OR. (LRESTART .AND. .NOT.DSO%LRESET_BUDGETC)) THEN
#else
IF (DSO%LSURF_BUDGETC .OR. .NOT.DSO%LRESET_BUDGETC) THEN
#endif
!        
  ALLOCATE(DGSC%XRN   (KLU))
  ALLOCATE(DGSC%XH    (KLU))
  ALLOCATE(DGSC%XLE   (KLU))
  ALLOCATE(DGSC%XLEI  (KLU))
  ALLOCATE(DGSC%XGFLUX(KLU))
  ALLOCATE(DGSC%XEVAP (KLU))
  ALLOCATE(DGSC%XSUBL (KLU))  
  ALLOCATE(DGSC%XSWD  (KLU))
  ALLOCATE(DGSC%XSWU  (KLU))
  ALLOCATE(DGSC%XLWD  (KLU))
  ALLOCATE(DGSC%XLWU  (KLU))
  ALLOCATE(DGSC%XFMU  (KLU))
  ALLOCATE(DGSC%XFMV  (KLU))
!
  IF (.NOT. OREAD_BUDGETC) THEN        
     DGSC%XRN   = 0.0
     DGSC%XH    = 0.0
     DGSC%XLE   = 0.0
     DGSC%XLEI  = 0.0
     DGSC%XGFLUX= 0.0
     DGSC%XEVAP = 0.0
     DGSC%XSUBL = 0.0
     DGSC%XSWD  = 0.0
     DGSC%XSWU  = 0.0
     DGSC%XLWD  = 0.0
     DGSC%XLWU  = 0.0
     DGSC%XFMU  = 0.0
     DGSC%XFMV  = 0.0
  ELSEIF (OREAD_BUDGETC.AND.DSO%LRESET_BUDGETC) THEN
     DGSC%XRN   = 0.0
     DGSC%XH    = 0.0
     DGSC%XLE   = 0.0
     DGSC%XLEI  = 0.0
     DGSC%XGFLUX= 0.0
     DGSC%XEVAP = 0.0
     DGSC%XSUBL = 0.0     
     DGSC%XSWD  = 0.0
     DGSC%XSWU  = 0.0
     DGSC%XLWD  = 0.0
     DGSC%XLWU  = 0.0
     DGSC%XFMU  = 0.0
     DGSC%XFMV  = 0.0
  ELSE
     CALL READ_SURF(HPROGRAM,'VERSION',IVERSION,IRESP)    
     YREC='RNC_SEA'
     CALL READ_SURF(HPROGRAM,YREC,DGSC%XRN,IRESP)
     YREC='HC_SEA'
     CALL READ_SURF(HPROGRAM,YREC,DGSC%XH,IRESP)
     YREC='LEC_SEA'
     CALL READ_SURF(HPROGRAM,YREC,DGSC%XLE,IRESP)
     YREC='LEIC_SEA'
     CALL READ_SURF(HPROGRAM,YREC,DGSC%XLEI,IRESP) 
     YREC='GFLUXC_SEA'
     CALL READ_SURF(HPROGRAM,YREC,DGSC%XGFLUX,IRESP)
     YREC='SWDC_SEA'
     CALL READ_SURF(HPROGRAM,YREC,DGSC%XSWD,IRESP)
     YREC='SWUC_SEA'
     CALL READ_SURF(HPROGRAM,YREC,DGSC%XSWU,IRESP)
     YREC='LWDC_SEA'
     CALL READ_SURF(HPROGRAM,YREC,DGSC%XLWD,IRESP)
     YREC='LWUC_SEA'
     CALL READ_SURF(HPROGRAM,YREC,DGSC%XLWU,IRESP)
     YREC='FMUC_SEA'
     CALL READ_SURF(HPROGRAM,YREC,DGSC%XFMU,IRESP)
     YREC='FMVC_SEA'
     CALL READ_SURF(HPROGRAM,YREC,DGSC%XFMV,IRESP)
     IF (IVERSION<8)THEN
        DGSC%XEVAP     = 0.0
        DGSC%XSUBL     = 0.0              
     ELSE
        !
        YREC='EVAPC_SEA'
        CALL READ_SURF(HPROGRAM,YREC,DGSC%XEVAP,IRESP)
        YREC='SUBLC_SEA'
        CALL READ_SURF(HPROGRAM,YREC,DGSC%XSUBL,IRESP)
     ENDIF
  ENDIF   
ELSE
  ALLOCATE(DGSC%XRN   (0))
  ALLOCATE(DGSC%XH    (0))
  ALLOCATE(DGSC%XLE   (0))
  ALLOCATE(DGSC%XLEI  (0))
  ALLOCATE(DGSC%XEVAP (0))
  ALLOCATE(DGSC%XSUBL (0))  
  ALLOCATE(DGSC%XSWD  (0))
  ALLOCATE(DGSC%XSWU  (0))
  ALLOCATE(DGSC%XLWD  (0))
  ALLOCATE(DGSC%XLWU  (0))
  ALLOCATE(DGSC%XFMU  (0))
  ALLOCATE(DGSC%XFMV  (0))
ENDIF
!
!* parameters at 2m
!
IF (DSO%N2M>=1) THEN
  ALLOCATE(DGS%XRI      (KLU))
  ALLOCATE(DGS%XT2M     (KLU))
  ALLOCATE(DGS%XT2M_MIN (KLU))
  ALLOCATE(DGS%XT2M_MAX (KLU))
  ALLOCATE(DGS%XQ2M     (KLU))
  ALLOCATE(DGS%XHU2M    (KLU))
  ALLOCATE(DGS%XHU2M_MIN(KLU))
  ALLOCATE(DGS%XHU2M_MAX(KLU))
  ALLOCATE(DGS%XZON10M  (KLU))
  ALLOCATE(DGS%XMER10M  (KLU))
  ALLOCATE(DGS%XWIND10M (KLU))
  ALLOCATE(DGS%XWIND10M_MAX(KLU))
  !
  DGS%XRI      = XUNDEF
  DGS%XT2M     = XUNDEF
  DGS%XT2M_MIN = XUNDEF
  DGS%XT2M_MAX = 0.0
  DGS%XQ2M     = XUNDEF
  DGS%XHU2M    = XUNDEF
  DGS%XHU2M_MIN= XUNDEF
  DGS%XHU2M_MAX=-XUNDEF
  DGS%XZON10M  = XUNDEF
  DGS%XMER10M  = XUNDEF
  DGS%XWIND10M = XUNDEF
  DGS%XWIND10M_MAX = 0.0
ELSE
  ALLOCATE(DGS%XRI      (0))
  ALLOCATE(DGS%XT2M     (0))
  ALLOCATE(DGS%XT2M_MIN (0))
  ALLOCATE(DGS%XT2M_MAX (0))
  ALLOCATE(DGS%XQ2M     (0))
  ALLOCATE(DGS%XHU2M    (0))
  ALLOCATE(DGS%XHU2M_MIN(0))
  ALLOCATE(DGS%XHU2M_MAX(0))
  ALLOCATE(DGS%XZON10M  (0))
  ALLOCATE(DGS%XMER10M  (0))
  ALLOCATE(DGS%XWIND10M (0))
  ALLOCATE(DGS%XWIND10M_MAX(0))
END IF
!
!* transfer coefficients
!
IF (DSO%LCOEF) THEN
  ALLOCATE(DGS%XCD     (KLU))
  ALLOCATE(DGS%XCH     (KLU))
  ALLOCATE(DGS%XCE     (KLU))
  ALLOCATE(DGS%XZ0     (KLU))
  ALLOCATE(DGS%XZ0H    (KLU))
  !
  DGS%XCD      = XUNDEF
  DGS%XCH      = XUNDEF
  DGS%XCE      = XUNDEF
  DGS%XZ0      = XUNDEF
  DGS%XZ0H     = XUNDEF
ELSE
  ALLOCATE(DGS%XCD     (0))
  ALLOCATE(DGS%XCH     (0))
  ALLOCATE(DGS%XCE     (0))
  ALLOCATE(DGS%XZ0     (0))
  ALLOCATE(DGS%XZ0H    (0))
END IF
!
!
!* surface humidity
!
IF (DSO%LSURF_VARS) THEN
  ALLOCATE(DGS%XQS     (KLU))
  !
  DGS%XQS      = XUNDEF
ELSE
  ALLOCATE(DGS%XQS     (0))
END IF
!
!* ocean diag
!
IF (DGO%LDIAG_OCEAN) THEN
  ALLOCATE(DGO%XTOCMOY  (KLU))
  ALLOCATE(DGO%XSOCMOY  (KLU))
  ALLOCATE(DGO%XUOCMOY  (KLU))
  ALLOCATE(DGO%XVOCMOY  (KLU))
  ALLOCATE(DGO%XDOCMOY  (KLU))
  !
  DGO%XTOCMOY(:)=XUNDEF
  DGO%XSOCMOY(:)=XUNDEF
  DGO%XUOCMOY(:)=XUNDEF
  DGO%XVOCMOY(:)=XUNDEF
  DGO%XDOCMOY(:)=XUNDEF
ELSE
  ALLOCATE(DGO%XTOCMOY  (0))
  ALLOCATE(DGO%XSOCMOY  (0))
  ALLOCATE(DGO%XUOCMOY  (0))
  ALLOCATE(DGO%XVOCMOY  (0))
  ALLOCATE(DGO%XDOCMOY  (0))
ENDIF
!
!
!* Earth system model coupling variables
!
IF(LCPL_SEA.OR.S%LHANDLE_SIC)THEN
!        
  ALLOCATE(S%XCPL_SEA_WIND(KLU))
  ALLOCATE(S%XCPL_SEA_FWSU(KLU))
  ALLOCATE(S%XCPL_SEA_FWSV(KLU))
  ALLOCATE(S%XCPL_SEA_SNET(KLU))
  ALLOCATE(S%XCPL_SEA_HEAT(KLU))
  ALLOCATE(S%XCPL_SEA_EVAP(KLU))
  ALLOCATE(S%XCPL_SEA_RAIN(KLU))
  ALLOCATE(S%XCPL_SEA_SNOW(KLU))
  ALLOCATE(S%XCPL_SEA_FWSM(KLU))
  S%XCPL_SEA_WIND(:) = 0.0
  S%XCPL_SEA_FWSU(:) = 0.0
  S%XCPL_SEA_FWSV(:) = 0.0
  S%XCPL_SEA_SNET(:) = 0.0
  S%XCPL_SEA_HEAT(:) = 0.0
  S%XCPL_SEA_EVAP(:) = 0.0
  S%XCPL_SEA_RAIN(:) = 0.0
  S%XCPL_SEA_SNOW(:) = 0.0
  S%XCPL_SEA_FWSM(:) = 0.0
!
ELSE
  ALLOCATE(S%XCPL_SEA_WIND(0))
  ALLOCATE(S%XCPL_SEA_FWSU(0))
  ALLOCATE(S%XCPL_SEA_FWSV(0))
  ALLOCATE(S%XCPL_SEA_SNET(0))
  ALLOCATE(S%XCPL_SEA_HEAT(0))
  ALLOCATE(S%XCPL_SEA_EVAP(0))
  ALLOCATE(S%XCPL_SEA_RAIN(0))
  ALLOCATE(S%XCPL_SEA_SNOW(0))
  ALLOCATE(S%XCPL_SEA_FWSM(0))
ENDIF
!
IF (LHOOK) CALL DR_HOOK('DIAG_SEAFLUX_INIT_N',1,ZHOOK_HANDLE)
!
!-------------------------------------------------------------------------------
!
END SUBROUTINE DIAG_SEAFLUX_INIT_n
