!     #########
      SUBROUTINE DIAG_TEB_GARDEN_INIT_n(DGI, DGIP, DGEI, DGEIP, DGMI, KLU, KSNOW_LAYER)
              !     #####################
!
USE MODD_DIAG_n, ONLY : DIAG_t
USE MODD_DIAG_EVAP_ISBA_n, ONLY : DIAG_EVAP_ISBA_t
USE MODD_DIAG_MISC_ISBA_n, ONLY : DIAG_MISC_ISBA_t
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE
!
TYPE(DIAG_t), INTENT(INOUT) :: DGI
TYPE(DIAG_t), INTENT(INOUT) :: DGIP
TYPE(DIAG_EVAP_ISBA_t), INTENT(INOUT) :: DGEI
TYPE(DIAG_EVAP_ISBA_t), INTENT(INOUT) :: DGEIP
TYPE(DIAG_MISC_ISBA_t), INTENT(INOUT) :: DGMI
INTEGER, INTENT(IN) :: KLU
INTEGER, INTENT(IN) :: KSNOW_LAYER
!
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
IF (LHOOK) CALL DR_HOOK('DIAG_TEB_GARDEN_INIT',0,ZHOOK_HANDLE)
!
ALLOCATE(DGIP%XZ0(KLU))
ALLOCATE(DGIP%XZ0H(KLU))
ALLOCATE(DGIP%XZ0EFF(KLU))
ALLOCATE(DGIP%XCD(KLU))
ALLOCATE(DGIP%XCH(KLU))
ALLOCATE(DGIP%XCDN(KLU))
ALLOCATE(DGIP%XRI(KLU))
ALLOCATE(DGIP%XHUG(KLU))
ALLOCATE(DGIP%XHU(KLU))
ALLOCATE(DGIP%XQS(KLU))
!
ALLOCATE(DGI%XRN(KLU))
ALLOCATE(DGI%XH(KLU))
ALLOCATE(DGI%XGFLUX(KLU))
ALLOCATE(DGI%XLE(KLU))
ALLOCATE(DGI%XLEI(KLU))
!
ALLOCATE(DGIP%XEVAP(KLU))
ALLOCATE(DGIP%XRN(KLU))
ALLOCATE(DGIP%XGFLUX(KLU))
ALLOCATE(DGIP%XH(KLU))
ALLOCATE(DGIP%XLEI(KLU))
ALLOCATE(DGIP%XSUBL(KLU))
!
ALLOCATE(DGIP%XTS(KLU))
ALLOCATE(DGIP%XTSRAD(KLU))
ALLOCATE(DGIP%XALBT(KLU))
!
ALLOCATE(DGMI%XC1  (KLU))
ALLOCATE(DGMI%XC2  (KLU))
ALLOCATE(DGMI%XWGEQ(KLU))
ALLOCATE(DGMI%XCG  (KLU))
ALLOCATE(DGMI%XCT  (KLU))
ALLOCATE(DGMI%XRS  (KLU))
ALLOCATE(DGMI%XHV  (KLU))
ALLOCATE(DGMI%XGRNDFLUX(KLU))
ALLOCATE(DGMI%XSNOWTEMP(KLU,KSNOW_LAYER))
ALLOCATE(DGMI%XSNOWHMASS(KLU))
ALLOCATE(DGMI%XSNOWLIQ(KLU,KSNOW_LAYER))
ALLOCATE(DGMI%XSNOWDZ(KLU,KSNOW_LAYER))
ALLOCATE(DGMI%XSRSFC(KLU))
ALLOCATE(DGMI%XRRSFC(KLU))
ALLOCATE(DGMI%XRNSNOW(KLU))
ALLOCATE(DGMI%XHSNOW(KLU))
ALLOCATE(DGMI%XGFLUXSNOW(KLU))
ALLOCATE(DGMI%XHPSNOW(KLU))
ALLOCATE(DGMI%XUSTARSNOW(KLU))
ALLOCATE(DGMI%XCDSNOW(KLU))
ALLOCATE(DGMI%XCHSNOW(KLU))
!
ALLOCATE(DGEIP%XMELT(KLU))
ALLOCATE(DGEIP%XMELTADV(KLU))
ALLOCATE(DGEIP%XRESTORE(KLU))
ALLOCATE(DGEIP%XSNDRIFT(KLU))
ALLOCATE(DGEIP%XSWNET_N(KLU))
ALLOCATE(DGEIP%XSWNET_NS(KLU))
ALLOCATE(DGEIP%XLWNET_N(KLU))
!
ALLOCATE(DGEI%XLEG(KLU))
ALLOCATE(DGEI%XLEGI(KLU))
ALLOCATE(DGEI%XLEV(KLU))
ALLOCATE(DGEI%XLETR(KLU))
ALLOCATE(DGEI%XLER(KLU))
!
ALLOCATE(DGEI%XUSTAR(KLU))
!
ALLOCATE(DGEIP%XLEG(KLU))
ALLOCATE(DGEIP%XLEGI(KLU))
ALLOCATE(DGEIP%XLEV(KLU))
ALLOCATE(DGEIP%XLES(KLU))
ALLOCATE(DGEIP%XLESL(KLU))
ALLOCATE(DGEIP%XLER(KLU))
ALLOCATE(DGEIP%XLETR(KLU))
!
ALLOCATE(DGEIP%XDRIP(KLU))
ALLOCATE(DGEIP%XRRVEG(KLU))
!
ALLOCATE(DGEIP%XDRAIN(KLU))
ALLOCATE(DGEIP%XRUNOFF(KLU))
ALLOCATE(DGEIP%XHORT(KLU))
ALLOCATE(DGEIP%XQSB(KLU))
ALLOCATE(DGEIP%XIRRIG_FLUX(KLU))
!
ALLOCATE(DGEIP%XLE_FLOOD(KLU))
ALLOCATE(DGEIP%XLEI_FLOOD(KLU))
ALLOCATE(DGEIP%XPFLOOD(KLU))
ALLOCATE(DGEIP%XIFLOOD(KLU))
!
ALLOCATE(DGEIP%XGPP(KLU))
ALLOCATE(DGEIP%XRESP_ECO(KLU))
ALLOCATE(DGEIP%XRESP_AUTO(KLU))
!
IF (LHOOK) CALL DR_HOOK('DIAG_TEB_GARDEN_INIT',1,ZHOOK_HANDLE)
!
END SUBROUTINE DIAG_TEB_GARDEN_INIT_n
