!     #########
SUBROUTINE DIAG_EVAP_ISBA_n (DGEI, DGEIP, DGEIPC, DGIPC, PKD, PK, OGLACIER, OMEB_PATCH, HSNOW_SCHEME, &
                             HPHOTO,PTSTEP,KMASK,KSIZE,KPATCH,PRHOA)
!     ###############################################################################
!
!!****  *DIAG_EVAP-ISBA_n * - additional diagnostics for ISBA
!!
!!    PURPOSE
!!    -------
!
!!**  METHOD
!!    ------
!!
!!    REFERENCE
!!    ---------
!!      
!!
!!    AUTHOR
!!    ------
!!     P. LeMoigne 
!!
!!    MODIFICATIONS
!!    -------------
!!      Original    01/2004
!!                     2008      New diag
!!      B. Decharme    2012      New snow diag LESL
!!                               Add carbon fluxes diag
!!                               Add isba water budget diag
!!      B. Decharme  04/2013     add Subsurface runoff if SGH (DIF option only) 
!!                               add sublimation
!!      P Samuelsson   04/2012   MEB
!!------------------------------------------------------------------
!
!
!
USE MODD_DIAG_EVAP_ISBA_n, ONLY : DIAG_EVAP_ISBA_PATCH_t, DIAG_EVAP_ISBA_t
USE MODD_DIAG_n, ONLY : DIAG_PATCH_t
USE MODD_PACK_DIAG_ISBA, ONLY : PACK_DIAG_ISBA_t
USE MODD_PACK_ISBA, ONLY : PACK_ISBA_t
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE
!
!*      0.1    declarations of arguments
!
!
TYPE(DIAG_EVAP_ISBA_t), INTENT(INOUT) :: DGEI
TYPE(DIAG_EVAP_ISBA_PATCH_t), INTENT(INOUT) :: DGEIP
TYPE(DIAG_EVAP_ISBA_PATCH_t), INTENT(INOUT) :: DGEIPC
TYPE(DIAG_PATCH_t), INTENT(INOUT) :: DGIPC
TYPE(PACK_DIAG_ISBA_t), INTENT(INOUT) :: PKD
TYPE(PACK_ISBA_t), INTENT(INOUT) :: PK
!
LOGICAL, INTENT(IN) :: OGLACIER
LOGICAL, DIMENSION(:), INTENT(IN) :: OMEB_PATCH
 CHARACTER(LEN=*), INTENT(IN) :: HSNOW_SCHEME
!
 CHARACTER(LEN=*), INTENT(IN)      :: HPHOTO        ! type of photosynthesis
REAL,    INTENT(IN)               :: PTSTEP        ! time step
INTEGER, INTENT(IN)               :: KSIZE  
INTEGER, INTENT(IN) :: KPATCH
!
INTEGER, DIMENSION(:), INTENT(IN) :: KMASK
REAL,    DIMENSION(:), INTENT(IN) :: PRHOA         ! air density for unit change
!
INTEGER :: JJ
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
!*      0.2    declarations of local variables
!
!-------------------------------------------------------------------------------------
!
IF (LHOOK) CALL DR_HOOK('DIAG_EVAP_ISBA_N',0,ZHOOK_HANDLE)
!
IF (DGEI%LSURF_EVAP_BUDGET) THEN
!cdir nodep
  DO JJ=1,KSIZE
     !
     DGEIP%AL(KPATCH)%XLEG       (KMASK(JJ))  =  PKD%DGEIP%XLEG        (JJ)
     DGEIP%AL(KPATCH)%XLEGI      (KMASK(JJ))  =  PKD%DGEIP%XLEGI       (JJ)
     DGEIP%AL(KPATCH)%XLEV       (KMASK(JJ))  =  PKD%DGEIP%XLEV        (JJ)
     DGEIP%AL(KPATCH)%XLES       (KMASK(JJ))  =  PKD%DGEIP%XLES        (JJ)
     DGEIP%AL(KPATCH)%XLER       (KMASK(JJ))  =  PKD%DGEIP%XLER        (JJ)
     DGEIP%AL(KPATCH)%XLETR      (KMASK(JJ))  =  PKD%DGEIP%XLETR       (JJ)
     DGEIP%AL(KPATCH)%XDRAIN     (KMASK(JJ))  =  PKD%DGEIP%XDRAIN      (JJ)
     DGEIP%AL(KPATCH)%XQSB       (KMASK(JJ))  =  PKD%DGEIP%XQSB        (JJ)
     DGEIP%AL(KPATCH)%XRUNOFF    (KMASK(JJ))  =  PKD%DGEIP%XRUNOFF     (JJ)
     DGEIP%AL(KPATCH)%XHORT      (KMASK(JJ))  =  PKD%DGEIP%XHORT       (JJ)
     DGEIP%AL(KPATCH)%XDRIP      (KMASK(JJ))  =  PKD%DGEIP%XDRIP       (JJ)
     DGEIP%AL(KPATCH)%XRRVEG     (KMASK(JJ))  =  PKD%DGEIP%XRRVEG      (JJ)
     DGEIP%AL(KPATCH)%XMELT      (KMASK(JJ))  =  PKD%DGEIP%XMELT       (JJ)
     DGEIP%AL(KPATCH)%XIFLOOD    (KMASK(JJ))  =  PKD%DGEIP%XIFLOOD     (JJ)
     DGEIP%AL(KPATCH)%XPFLOOD    (KMASK(JJ))  =  PKD%DGEIP%XPFLOOD     (JJ)
     DGEIP%AL(KPATCH)%XLE_FLOOD  (KMASK(JJ))  =  PKD%DGEIP%XLE_FLOOD   (JJ)
     DGEIP%AL(KPATCH)%XLEI_FLOOD (KMASK(JJ))  =  PKD%DGEIP%XLEI_FLOOD  (JJ)
     DGEIP%AL(KPATCH)%XIRRIG_FLUX(KMASK(JJ))  =  PKD%DGEIP%XIRRIG_FLUX (JJ)
     !
     IF (OMEB_PATCH(KPATCH)) THEN
       DGEIP%AL(KPATCH)%XLEVCV  (KMASK(JJ))  =  PKD%DGEIP%XLEVCV    (JJ)
       DGEIP%AL(KPATCH)%XLESC   (KMASK(JJ))  =  PKD%DGEIP%XLESC     (JJ)
       DGEIP%AL(KPATCH)%XLETRCV (KMASK(JJ))  =  PKD%DGEIP%XLETRCV   (JJ)
       DGEIP%AL(KPATCH)%XLELITTER (KMASK(JJ)) = PKD%DGEIP%XLELITTER (JJ)
       DGEIP%AL(KPATCH)%XLELITTERI(KMASK(JJ)) = PKD%DGEIP%XLELITTERI(JJ)
       DGEIP%AL(KPATCH)%XDRIPLIT  (KMASK(JJ)) = PKD%DGEIP%XDRIPLIT  (JJ)
       DGEIP%AL(KPATCH)%XRRLIT  (KMASK(JJ))  =  PKD%DGEIP%XRRLIT    (JJ)
       DGEIP%AL(KPATCH)%XLERCV  (KMASK(JJ))  =  PKD%DGEIP%XLERCV    (JJ)
       DGEIP%AL(KPATCH)%XLE_C_A (KMASK(JJ))  =  PKD%DGEIP%XLE_C_A   (JJ)
       DGEIP%AL(KPATCH)%XLE_V_C (KMASK(JJ))  =  PKD%DGEIP%XLE_V_C   (JJ)
       DGEIP%AL(KPATCH)%XLE_G_C (KMASK(JJ))  =  PKD%DGEIP%XLE_G_C   (JJ)
       DGEIP%AL(KPATCH)%XLE_N_C (KMASK(JJ))  =  PKD%DGEIP%XLE_N_C   (JJ)
       !
       DGEIP%AL(KPATCH)%XSWNET_V    (KMASK(JJ))  =  PKD%DGEIP%XSWNET_V    (JJ)
       DGEIP%AL(KPATCH)%XSWNET_G    (KMASK(JJ))  =  PKD%DGEIP%XSWNET_G    (JJ)
       DGEIP%AL(KPATCH)%XSWNET_N    (KMASK(JJ))  =  PKD%DGEIP%XSWNET_N    (JJ)
       DGEIP%AL(KPATCH)%XSWNET_NS   (KMASK(JJ))  =  PKD%DGEIP%XSWNET_NS   (JJ)
       DGEIP%AL(KPATCH)%XLWNET_V    (KMASK(JJ))  =  PKD%DGEIP%XLWNET_V    (JJ)
       DGEIP%AL(KPATCH)%XLWNET_G    (KMASK(JJ))  =  PKD%DGEIP%XLWNET_G    (JJ)
       DGEIP%AL(KPATCH)%XLWNET_N    (KMASK(JJ))  =  PKD%DGEIP%XLWNET_N    (JJ)
       DGEIP%AL(KPATCH)%XSWDOWN_GN  (KMASK(JJ))  =  PKD%DGEIP%XSWDOWN_GN  (JJ)
       DGEIP%AL(KPATCH)%XLWDOWN_GN  (KMASK(JJ))  =  PKD%DGEIP%XLWDOWN_GN  (JJ)
       DGEIP%AL(KPATCH)%XH_V_C      (KMASK(JJ))  =  PKD%DGEIP%XH_V_C      (JJ)
       DGEIP%AL(KPATCH)%XH_G_C      (KMASK(JJ))  =  PKD%DGEIP%XH_G_C      (JJ)
       DGEIP%AL(KPATCH)%XH_C_A      (KMASK(JJ))  =  PKD%DGEIP%XH_C_A      (JJ)
       DGEIP%AL(KPATCH)%XH_N_C      (KMASK(JJ))  =  PKD%DGEIP%XH_N_C      (JJ)
       DGEIP%AL(KPATCH)%XSR_GN      (KMASK(JJ))  =  PKD%DGEIP%XSR_GN      (JJ)
       DGEIP%AL(KPATCH)%XMELTCV     (KMASK(JJ))  =  PKD%DGEIP%XMELTCV     (JJ)
       DGEIP%AL(KPATCH)%XFRZCV      (KMASK(JJ))  =  PKD%DGEIP%XFRZCV      (JJ)
     ENDIF
     !
  END DO
  !
  IF (HSNOW_SCHEME=='3-L' .OR. HSNOW_SCHEME=='CRO') THEN
!cdir nodep
     DO JJ=1,KSIZE
        DGEIP%AL(KPATCH)%XLESL    (KMASK(JJ))  =  PKD%DGEIP%XLESL       (JJ)
        DGEIP%AL(KPATCH)%XSNDRIFT (KMASK(JJ))  =  PKD%DGEIP%XSNDRIFT    (JJ)
     END DO
  END IF
  !
  IF(HPHOTO/='NON')THEN
!cdir nodep
     DO JJ=1,KSIZE
        ! Transform units from kgCO2/kgair m/s to kgCO2/m2/s
        DGEIP%AL(KPATCH)%XGPP       (KMASK(JJ))  =  PKD%DGEIP%XGPP       (JJ) * PRHOA(JJ)
        DGEIP%AL(KPATCH)%XRESP_AUTO (KMASK(JJ))  =  PKD%DGEIP%XRESP_AUTO (JJ) * PRHOA(JJ)
        DGEIP%AL(KPATCH)%XRESP_ECO  (KMASK(JJ))  =  PKD%DGEIP%XRESP_ECO  (JJ) * PRHOA(JJ)
        !
     END DO
  ELSE  
     DGEIP%AL(KPATCH)%XGPP      (:)=0.0
     DGEIP%AL(KPATCH)%XRESP_AUTO(:)=0.0
     DGEIP%AL(KPATCH)%XRESP_ECO (:)=0.0
  ENDIF
  !
  IF(DGEI%LWATER_BUDGET)THEN
!cdir nodep
     DO JJ=1,KSIZE
        DGEIP%AL(KPATCH)%XDWG   (KMASK(JJ))  =  PKD%DGEIP%XDWG   (JJ)
        DGEIP%AL(KPATCH)%XDWGI  (KMASK(JJ))  =  PKD%DGEIP%XDWGI  (JJ)
        DGEIP%AL(KPATCH)%XDWR   (KMASK(JJ))  =  PKD%DGEIP%XDWR   (JJ)
        DGEIP%AL(KPATCH)%XDSWE  (KMASK(JJ))  =  PKD%DGEIP%XDSWE  (JJ)
        DGEIP%AL(KPATCH)%XWATBUD(KMASK(JJ))  =  PKD%DGEIP%XWATBUD(JJ)
     END DO
  ENDIF
  !
END IF
!
IF (DGEI%LSURF_BUDGETC) THEN
!cdir nodep
  DO JJ=1,KSIZE
     !
     DGIPC%AL(KPATCH)%XRN        (KMASK(JJ))  =  DGIPC%AL(KPATCH)%XRN      (KMASK(JJ)) + PKD%DGIP%XRN        (JJ) * PTSTEP
     DGIPC%AL(KPATCH)%XH         (KMASK(JJ))  =  DGIPC%AL(KPATCH)%XH       (KMASK(JJ)) + PKD%DGIP%XH         (JJ) * PTSTEP
     DGIPC%AL(KPATCH)%XLE        (KMASK(JJ))  =  DGIPC%AL(KPATCH)%XLE      (KMASK(JJ)) + PK%I%R%XLE       (JJ,1) * PTSTEP
     DGIPC%AL(KPATCH)%XLEI       (KMASK(JJ))  =  DGIPC%AL(KPATCH)%XLEI     (KMASK(JJ)) + PKD%DGIP%XLEI       (JJ) * PTSTEP
     DGIPC%AL(KPATCH)%XGFLUX     (KMASK(JJ))  =  DGIPC%AL(KPATCH)%XGFLUX   (KMASK(JJ)) + PKD%DGIP%XGFLUX     (JJ) * PTSTEP
     !
     DGEIPC%AL(KPATCH)%XLEG     (KMASK(JJ))  =  DGEIPC%AL(KPATCH)%XLEG     (KMASK(JJ)) + PKD%DGEIP%XLEG       (JJ) * PTSTEP
     DGEIPC%AL(KPATCH)%XLEGI    (KMASK(JJ))  =  DGEIPC%AL(KPATCH)%XLEGI    (KMASK(JJ)) + PKD%DGEIP%XLEGI      (JJ) * PTSTEP
     DGEIPC%AL(KPATCH)%XLEV     (KMASK(JJ))  =  DGEIPC%AL(KPATCH)%XLEV     (KMASK(JJ)) + PKD%DGEIP%XLEV       (JJ) * PTSTEP
     DGEIPC%AL(KPATCH)%XLES     (KMASK(JJ))  =  DGEIPC%AL(KPATCH)%XLES     (KMASK(JJ)) + PKD%DGEIP%XLES       (JJ) * PTSTEP
     DGEIPC%AL(KPATCH)%XLER     (KMASK(JJ))  =  DGEIPC%AL(KPATCH)%XLER     (KMASK(JJ)) + PKD%DGEIP%XLER       (JJ) * PTSTEP
     DGEIPC%AL(KPATCH)%XLETR    (KMASK(JJ))  =  DGEIPC%AL(KPATCH)%XLETR    (KMASK(JJ)) + PKD%DGEIP%XLETR      (JJ) * PTSTEP
     DGIPC%AL(KPATCH)%XEVAP    (KMASK(JJ))  =  DGIPC%AL(KPATCH)%XEVAP    (KMASK(JJ)) + PKD%DGIP%XEVAP      (JJ) * PTSTEP
     DGIPC%AL(KPATCH)%XSUBL    (KMASK(JJ))  =  DGIPC%AL(KPATCH)%XSUBL    (KMASK(JJ)) + PKD%DGIP%XSUBL      (JJ) * PTSTEP
     DGEIPC%AL(KPATCH)%XDRAIN   (KMASK(JJ))  =  DGEIPC%AL(KPATCH)%XDRAIN   (KMASK(JJ)) + PKD%DGEIP%XDRAIN     (JJ) * PTSTEP
     DGEIPC%AL(KPATCH)%XQSB     (KMASK(JJ))  =  DGEIPC%AL(KPATCH)%XQSB     (KMASK(JJ)) + PKD%DGEIP%XQSB       (JJ) * PTSTEP
     DGEIPC%AL(KPATCH)%XRUNOFF  (KMASK(JJ))  =  DGEIPC%AL(KPATCH)%XRUNOFF  (KMASK(JJ)) + PKD%DGEIP%XRUNOFF    (JJ) * PTSTEP
     DGEIPC%AL(KPATCH)%XHORT    (KMASK(JJ))  =  DGEIPC%AL(KPATCH)%XHORT    (KMASK(JJ)) + PKD%DGEIP%XHORT      (JJ) * PTSTEP
     DGEIPC%AL(KPATCH)%XDRIP    (KMASK(JJ))  =  DGEIPC%AL(KPATCH)%XDRIP    (KMASK(JJ)) + PKD%DGEIP%XDRIP      (JJ) * PTSTEP
     DGEIPC%AL(KPATCH)%XRRVEG   (KMASK(JJ))  =  DGEIPC%AL(KPATCH)%XRRVEG   (KMASK(JJ)) + PKD%DGEIP%XRRVEG     (JJ) * PTSTEP
     DGEIPC%AL(KPATCH)%XMELT    (KMASK(JJ))  =  DGEIPC%AL(KPATCH)%XMELT    (KMASK(JJ)) + PKD%DGEIP%XMELT      (JJ) * PTSTEP
     DGEIPC%AL(KPATCH)%XIFLOOD  (KMASK(JJ))  =  DGEIPC%AL(KPATCH)%XIFLOOD  (KMASK(JJ)) + PKD%DGEIP%XIFLOOD    (JJ) * PTSTEP
     DGEIPC%AL(KPATCH)%XPFLOOD  (KMASK(JJ))  =  DGEIPC%AL(KPATCH)%XPFLOOD  (KMASK(JJ)) + PKD%DGEIP%XPFLOOD    (JJ) * PTSTEP
     DGEIPC%AL(KPATCH)%XLE_FLOOD(KMASK(JJ))  =  DGEIPC%AL(KPATCH)%XLE_FLOOD(KMASK(JJ)) + PKD%DGEIP%XLE_FLOOD  (JJ) * PTSTEP
     DGEIPC%AL(KPATCH)%XLEI_FLOOD (KMASK(JJ))  =  DGEIPC%AL(KPATCH)%XLEI_FLOOD (KMASK(JJ)) + PKD%DGEIP%XLEI_FLOOD (JJ) * PTSTEP
     DGEIPC%AL(KPATCH)%XIRRIG_FLUX(KMASK(JJ))  =  DGEIPC%AL(KPATCH)%XIRRIG_FLUX(KMASK(JJ)) + PKD%DGEIP%XIRRIG_FLUX(JJ) * PTSTEP
     !
     IF (OMEB_PATCH(KPATCH)) THEN
       DGEIPC%AL(KPATCH)%XLEVCV(KMASK(JJ))  = DGEIPC%AL(KPATCH)%XLEVCV(KMASK(JJ)) + PKD%DGEIP%XLEVCV    (JJ) * PTSTEP
       DGEIPC%AL(KPATCH)%XLESC (KMASK(JJ))  = DGEIPC%AL(KPATCH)%XLESC (KMASK(JJ)) + PKD%DGEIP%XLESC     (JJ) * PTSTEP
!       XLETRGVC (KMASK(JJ))  = XLETRGVC (KMASK(JJ)) + XP_LETRGV   (JJ) * PTSTEP
       DGEIPC%AL(KPATCH)%XLETRCV (KMASK(JJ))  = DGEIPC%AL(KPATCH)%XLETRCV (KMASK(JJ)) + PKD%DGEIP%XLETRCV   (JJ) * PTSTEP
!       XLERGVC  (KMASK(JJ))  = XLERGVC  (KMASK(JJ)) + XP_LERGV    (JJ) * PTSTEP
       DGEIPC%AL(KPATCH)%XLERCV(KMASK(JJ))  = DGEIPC%AL(KPATCH)%XLERCV(KMASK(JJ)) + PKD%DGEIP%XLERCV    (JJ) * PTSTEP
       DGEIPC%AL(KPATCH)%XLE_C_A(KMASK(JJ))  = DGEIPC%AL(KPATCH)%XLE_C_A(KMASK(JJ)) + PKD%DGEIP%XLE_C_A   (JJ) * PTSTEP
       DGEIPC%AL(KPATCH)%XLE_V_C(KMASK(JJ))  = DGEIPC%AL(KPATCH)%XLE_V_C(KMASK(JJ)) + PKD%DGEIP%XLE_V_C   (JJ) * PTSTEP
       DGEIPC%AL(KPATCH)%XLE_G_C(KMASK(JJ))  = DGEIPC%AL(KPATCH)%XLE_G_C(KMASK(JJ)) + PKD%DGEIP%XLE_G_C   (JJ) * PTSTEP
       DGEIPC%AL(KPATCH)%XLE_N_C(KMASK(JJ))  = DGEIPC%AL(KPATCH)%XLE_N_C(KMASK(JJ)) + PKD%DGEIP%XLE_N_C   (JJ) * PTSTEP
       !
       DGEIPC%AL(KPATCH)%XSWNET_V  (KMASK(JJ))  = DGEIPC%AL(KPATCH)%XSWNET_V  (KMASK(JJ))  + PKD%DGEIP%XSWNET_V    (JJ) * PTSTEP
       DGEIPC%AL(KPATCH)%XSWNET_G  (KMASK(JJ))  = DGEIPC%AL(KPATCH)%XSWNET_G  (KMASK(JJ))  + PKD%DGEIP%XSWNET_G    (JJ) * PTSTEP
       DGEIPC%AL(KPATCH)%XSWNET_N  (KMASK(JJ))  = DGEIPC%AL(KPATCH)%XSWNET_N  (KMASK(JJ))  + PKD%DGEIP%XSWNET_N    (JJ) * PTSTEP
       DGEIPC%AL(KPATCH)%XSWNET_NS (KMASK(JJ))  = DGEIPC%AL(KPATCH)%XSWNET_NS (KMASK(JJ))  + PKD%DGEIP%XSWNET_NS   (JJ) * PTSTEP
       DGEIPC%AL(KPATCH)%XLWNET_V  (KMASK(JJ))  = DGEIPC%AL(KPATCH)%XLWNET_V  (KMASK(JJ))  + PKD%DGEIP%XLWNET_V    (JJ) * PTSTEP
       DGEIPC%AL(KPATCH)%XLWNET_G  (KMASK(JJ))  = DGEIPC%AL(KPATCH)%XLWNET_G  (KMASK(JJ))  + PKD%DGEIP%XLWNET_G    (JJ) * PTSTEP
       DGEIPC%AL(KPATCH)%XLWNET_N  (KMASK(JJ))  = DGEIPC%AL(KPATCH)%XLWNET_N  (KMASK(JJ))  + PKD%DGEIP%XLWNET_N    (JJ) * PTSTEP
       DGEIPC%AL(KPATCH)%XSWDOWN_GN(KMASK(JJ))  = DGEIPC%AL(KPATCH)%XSWDOWN_GN(KMASK(JJ))  + PKD%DGEIP%XSWDOWN_GN  (JJ) * PTSTEP
       DGEIPC%AL(KPATCH)%XLWDOWN_GN(KMASK(JJ))  = DGEIPC%AL(KPATCH)%XLWDOWN_GN(KMASK(JJ))  + PKD%DGEIP%XLWDOWN_GN  (JJ) * PTSTEP
       DGEIPC%AL(KPATCH)%XH_V_C    (KMASK(JJ))  = DGEIPC%AL(KPATCH)%XH_V_C    (KMASK(JJ))  + PKD%DGEIP%XH_V_C      (JJ) * PTSTEP
       DGEIPC%AL(KPATCH)%XH_G_C    (KMASK(JJ))  = DGEIPC%AL(KPATCH)%XH_G_C    (KMASK(JJ))  + PKD%DGEIP%XH_G_C      (JJ) * PTSTEP
       DGEIPC%AL(KPATCH)%XH_C_A    (KMASK(JJ))  = DGEIPC%AL(KPATCH)%XH_C_A    (KMASK(JJ))  + PKD%DGEIP%XH_C_A      (JJ) * PTSTEP
       DGEIPC%AL(KPATCH)%XH_N_C    (KMASK(JJ))  = DGEIPC%AL(KPATCH)%XH_N_C    (KMASK(JJ))  + PKD%DGEIP%XH_N_C      (JJ) * PTSTEP
       DGEIPC%AL(KPATCH)%XSR_GN    (KMASK(JJ))  = DGEIPC%AL(KPATCH)%XSR_GN    (KMASK(JJ))  + PKD%DGEIP%XSR_GN      (JJ) * PTSTEP
       DGEIPC%AL(KPATCH)%XMELTCV   (KMASK(JJ))  = DGEIPC%AL(KPATCH)%XMELTCV   (KMASK(JJ))  + PKD%DGEIP%XMELTCV     (JJ) * PTSTEP
       DGEIPC%AL(KPATCH)%XFRZCV    (KMASK(JJ))  = DGEIPC%AL(KPATCH)%XFRZCV    (KMASK(JJ))  + PKD%DGEIP%XFRZCV      (JJ) * PTSTEP
     ENDIF
     !
     DGIPC%AL(KPATCH)%XSWD(KMASK(JJ))  = DGIPC%AL(KPATCH)%XSWD(KMASK(JJ)) + PKD%DGIP%XSWD(JJ) * PTSTEP
     DGIPC%AL(KPATCH)%XSWU(KMASK(JJ))  = DGIPC%AL(KPATCH)%XSWU(KMASK(JJ)) + PKD%DGIP%XSWU(JJ) * PTSTEP
     DGIPC%AL(KPATCH)%XLWD(KMASK(JJ))  = DGIPC%AL(KPATCH)%XLWD(KMASK(JJ)) + PKD%DGIP%XLWD(JJ) * PTSTEP
     DGIPC%AL(KPATCH)%XLWU(KMASK(JJ))  = DGIPC%AL(KPATCH)%XLWU(KMASK(JJ)) + PKD%DGIP%XLWU(JJ) * PTSTEP
     DGIPC%AL(KPATCH)%XFMU(KMASK(JJ))  = DGIPC%AL(KPATCH)%XFMU(KMASK(JJ)) + PKD%DGIP%XFMU(JJ) * PTSTEP
     DGIPC%AL(KPATCH)%XFMV(KMASK(JJ))  = DGIPC%AL(KPATCH)%XFMV(KMASK(JJ)) + PKD%DGIP%XFMV(JJ) * PTSTEP
     !
  END DO
  !
  IF (HSNOW_SCHEME=='3-L' .OR. HSNOW_SCHEME=='CRO') THEN
!cdir nodep
     DO JJ=1,KSIZE
        DGEIPC%AL(KPATCH)%XLESL    (KMASK(JJ)) = DGEIPC%AL(KPATCH)%XLESL    (KMASK(JJ)) + PKD%DGEIP%XLESL    (JJ) * PTSTEP
        DGEIPC%AL(KPATCH)%XSNDRIFT (KMASK(JJ)) = DGEIPC%AL(KPATCH)%XSNDRIFT (KMASK(JJ)) + PKD%DGEIP%XSNDRIFT (JJ) * PTSTEP
     END DO
  END IF
  !
  IF(HPHOTO/='NON')THEN
!cdir nodep
     DO JJ=1,KSIZE
        !Transform units from kgCO2/kgair m/s to kgCO2/m2
        DGEIPC%AL(KPATCH)%XGPP       (KMASK(JJ))  =  DGEIPC%AL(KPATCH)%XGPP       (KMASK(JJ))+  &
                PKD%DGEIP%XGPP       (JJ) * PRHOA(JJ) * PTSTEP
        DGEIPC%AL(KPATCH)%XRESP_AUTO (KMASK(JJ))  =  DGEIPC%AL(KPATCH)%XRESP_AUTO (KMASK(JJ))+  &
                PKD%DGEIP%XRESP_AUTO (JJ) * PRHOA(JJ) * PTSTEP
        DGEIPC%AL(KPATCH)%XRESP_ECO  (KMASK(JJ))  =  DGEIPC%AL(KPATCH)%XRESP_ECO  (KMASK(JJ))+  &
                PKD%DGEIP%XRESP_ECO  (JJ) * PRHOA(JJ) * PTSTEP
     END DO
  ELSE  
     DGEIPC%AL(KPATCH)%XGPP      (:)=0.0
     DGEIPC%AL(KPATCH)%XRESP_AUTO(:)=0.0
     DGEIPC%AL(KPATCH)%XRESP_ECO (:)=0.0       
  ENDIF
  !
  IF(OGLACIER)THEN
!cdir nodep
    DO JJ=1,KSIZE
       DGEIPC%AL(KPATCH)%XICEFLUX(KMASK(JJ))  = DGEIPC%AL(KPATCH)%XICEFLUX(KMASK(JJ)) + PKD%DGEIP%XICEFLUX(JJ) * PTSTEP
    END DO  
  END IF
  !  
  IF(DGEI%LWATER_BUDGET)THEN
!cdir nodep
     DO JJ=1,KSIZE
        DGEIPC%AL(KPATCH)%XDWG   (KMASK(JJ))  =  DGEIPC%AL(KPATCH)%XDWG   (KMASK(JJ)) + PKD%DGEIP%XDWG   (JJ) * PTSTEP
        DGEIPC%AL(KPATCH)%XDWGI  (KMASK(JJ))  =  DGEIPC%AL(KPATCH)%XDWGI  (KMASK(JJ)) + PKD%DGEIP%XDWGI  (JJ) * PTSTEP
        DGEIPC%AL(KPATCH)%XDWR   (KMASK(JJ))  =  DGEIPC%AL(KPATCH)%XDWR   (KMASK(JJ)) + PKD%DGEIP%XDWR   (JJ) * PTSTEP
        DGEIPC%AL(KPATCH)%XDSWE  (KMASK(JJ))  =  DGEIPC%AL(KPATCH)%XDSWE  (KMASK(JJ)) + PKD%DGEIP%XDSWE  (JJ) * PTSTEP
        DGEIPC%AL(KPATCH)%XWATBUD(KMASK(JJ))  =  DGEIPC%AL(KPATCH)%XWATBUD(KMASK(JJ)) + PKD%DGEIP%XWATBUD(JJ) * PTSTEP
     END DO
  ENDIF
  !  
END IF
IF (LHOOK) CALL DR_HOOK('DIAG_EVAP_ISBA_N',1,ZHOOK_HANDLE)
!
!-------------------------------------------------------------------------------------
!
END SUBROUTINE DIAG_EVAP_ISBA_n
