!     #########
      SUBROUTINE DIAG_TEB_VEG_INIT_n(D, DK, DE, DEK, DMI, KLU, KSNOW_LAYER)
              !     #####################
!
USE MODE_DIAG
!
USE MODD_DIAG_n, ONLY : DIAG_t
USE MODD_DIAG_EVAP_ISBA_n, ONLY : DIAG_EVAP_ISBA_t
USE MODD_DIAG_MISC_ISBA_n, ONLY : DIAG_MISC_ISBA_t
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE
!
TYPE(DIAG_t), INTENT(INOUT) :: D
TYPE(DIAG_t), INTENT(INOUT) :: DK
TYPE(DIAG_EVAP_ISBA_t), INTENT(INOUT) :: DE
TYPE(DIAG_EVAP_ISBA_t), INTENT(INOUT) :: DEK
TYPE(DIAG_MISC_ISBA_t), INTENT(INOUT) :: DMI
INTEGER, INTENT(IN) :: KLU
INTEGER, INTENT(IN) :: KSNOW_LAYER
!
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
IF (LHOOK) CALL DR_HOOK('DIAG_TEB_VEG_INIT',0,ZHOOK_HANDLE)
!
! Main diag
!
!for isba_snow_agr
ALLOCATE(D%XRN(KLU))
ALLOCATE(D%XH(KLU))
ALLOCATE(D%XLE(KLU))
ALLOCATE(D%XLEI(KLU))
ALLOCATE(D%XGFLUX(KLU))
!
!general
ALLOCATE(DK%XRN(KLU))
ALLOCATE(DK%XH(KLU))
ALLOCATE(DK%XLE(KLU))
ALLOCATE(DK%XLEI(KLU))
ALLOCATE(DK%XGFLUX(KLU))
ALLOCATE(DK%XEVAP(KLU))
ALLOCATE(DK%XSUBL(KLU))
!
!
ALLOCATE(DK%XRI(KLU))
!
ALLOCATE(DK%XCD(KLU))
ALLOCATE(DK%XCH(KLU))
ALLOCATE(DK%XZ0(KLU))
ALLOCATE(DK%XZ0H(KLU))
!
ALLOCATE(DK%XZ0EFF(KLU))
ALLOCATE(DK%XCDN(KLU))
ALLOCATE(DK%XHUG(KLU))
ALLOCATE(DK%XHU(KLU))
ALLOCATE(DK%XQS(KLU))
!
ALLOCATE(DK%XTS(KLU))
ALLOCATE(DK%XTSRAD(KLU))
ALLOCATE(DK%XALBT(KLU))
!
!---------------------------
!
! Evaporation diag
!
! for isba_snow_agr
ALLOCATE(DE%XLEG(KLU))
ALLOCATE(DE%XLEGI(KLU))
ALLOCATE(DE%XLEV(KLU))
ALLOCATE(DE%XLETR(KLU))
ALLOCATE(DE%XLER(KLU))
!
ALLOCATE(DE%XUSTAR(KLU))
!
! general
ALLOCATE(DEK%XLEG(KLU))
ALLOCATE(DEK%XLEGI(KLU))
ALLOCATE(DEK%XLEV(KLU))
ALLOCATE(DEK%XLES(KLU))
ALLOCATE(DEK%XLESL(KLU))
ALLOCATE(DEK%XLER(KLU))
ALLOCATE(DEK%XLETR(KLU))
!
ALLOCATE(DEK%XDRAIN(KLU))
ALLOCATE(DEK%XRUNOFF(KLU))
ALLOCATE(DEK%XHORT(KLU))
ALLOCATE(DEK%XQSB(KLU))
ALLOCATE(DEK%XIRRIG_FLUX(KLU))
!
ALLOCATE(DEK%XDRIP(KLU))
ALLOCATE(DEK%XRRVEG(KLU))
!
ALLOCATE(DEK%XMELT(KLU))
ALLOCATE(DEK%XMELTADV(KLU))
ALLOCATE(DEK%XRESTORE(KLU))
ALLOCATE(DEK%XSNDRIFT(KLU))
ALLOCATE(DEK%XSWNET_N(KLU))
ALLOCATE(DEK%XSWNET_NS(KLU))
ALLOCATE(DEK%XLWNET_N(KLU))
!
ALLOCATE(DEK%XLE_FLOOD(KLU))
ALLOCATE(DEK%XLEI_FLOOD(KLU))
ALLOCATE(DEK%XPFLOOD(KLU))
ALLOCATE(DEK%XIFLOOD(KLU))
!
ALLOCATE(DEK%XGPP(KLU))
ALLOCATE(DEK%XRESP_ECO(KLU))
ALLOCATE(DEK%XRESP_AUTO(KLU))
!
ALLOCATE(DEK%XRN_SN_FR   (KLU))
ALLOCATE(DEK%XH_SN_FR    (KLU))
ALLOCATE(DEK%XLEI_SN_FR  (KLU))
ALLOCATE(DEK%XLE_SN_FR   (KLU))
ALLOCATE(DEK%XGFLUX_SN_FR(KLU))
ALLOCATE(DEK%XLEG_SN_FR  (KLU))
ALLOCATE(DEK%XLEGI_SN_FR (KLU))
ALLOCATE(DEK%XLEV_SN_FR  (KLU))
ALLOCATE(DEK%XLETR_SN_FR (KLU))
ALLOCATE(DEK%XUSTAR_SN_FR(KLU))
ALLOCATE(DEK%XLER_SN_FR  (KLU))
!
!--------------------------------------
!
! Misc diag
!
ALLOCATE(DMI%XC1  (KLU))
ALLOCATE(DMI%XC2  (KLU))
ALLOCATE(DMI%XWGEQ(KLU))
ALLOCATE(DMI%XCG  (KLU))
ALLOCATE(DMI%XCT  (KLU))
ALLOCATE(DMI%XRS  (KLU))
ALLOCATE(DMI%XHV  (KLU))
ALLOCATE(DMI%XGRNDFLUX(KLU))
ALLOCATE(DMI%XSNOWTEMP(KLU,KSNOW_LAYER))
ALLOCATE(DMI%XSNOWHMASS(KLU))
ALLOCATE(DMI%XSNOWLIQ(KLU,KSNOW_LAYER))
ALLOCATE(DMI%XSNOWDZ(KLU,KSNOW_LAYER))
ALLOCATE(DMI%XSRSFC(KLU))
ALLOCATE(DMI%XRRSFC(KLU))
ALLOCATE(DMI%XRNSNOW(KLU))
ALLOCATE(DMI%XHSNOW(KLU))
ALLOCATE(DMI%XGFLUXSNOW(KLU))
ALLOCATE(DMI%XHPSNOW(KLU))
ALLOCATE(DMI%XUSTARSNOW(KLU))
ALLOCATE(DMI%XCDSNOW(KLU))
ALLOCATE(DMI%XCHSNOW(KLU))
!
IF (LHOOK) CALL DR_HOOK('DIAG_TEB_VEG_INIT',1,ZHOOK_HANDLE)
!
END SUBROUTINE DIAG_TEB_VEG_INIT_n
