!     #########
SUBROUTINE DIAG_EVAP_ISBA_n (OSURF_BUDGETC, DGEI, DGEIP, DGEIPC, DGIPC, DGEIPK, DGIPK, IRK, &
                             IO, HSNOW_SCHEME, PTSTEP, KMASK, KSIZE, KPATCH, PRHOA)
!     ###############################################################################
!
!!****  *DIAG_EVAP-ISBA_n * - additional diagnostics for ISBA
!!
!!    PURPOSE
!!    -------
!
!!**  METHOD
!!    ------
!!
!!    REFERENCE
!!    ---------
!!      
!!
!!    AUTHOR
!!    ------
!!     P. LeMoigne 
!!
!!    MODIFICATIONS
!!    -------------
!!      Original    01/2004
!!                     2008      New diag
!!      B. Decharme    2012      New snow diag LESL
!!                               Add carbon fluxes diag
!!                               Add isba water budget diag
!!      B. Decharme  04/2013     add Subsurface runoff if SGH (DIF option only) 
!!                               add sublimation
!!      P Samuelsson   04/2012   MEB
!!------------------------------------------------------------------
!
!
!
USE MODD_DIAG_EVAP_ISBA_n, ONLY : DIAG_EVAP_ISBA_PATCH_t, DIAG_EVAP_ISBA_t
USE MODD_DIAG_n, ONLY : DIAG_PATCH_t, DIAG_t
USE MODD_ISBA_n, ONLY : ISBA_PROG_t
USE MODD_ISBA_OPTIONS_n, ONLY : ISBA_OPTIONS_t
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE
!
!*      0.1    declarations of arguments
!
!
LOGICAL, INTENT(IN) :: OSURF_BUDGETC
TYPE(DIAG_EVAP_ISBA_t), INTENT(INOUT) :: DGEI
TYPE(DIAG_EVAP_ISBA_PATCH_t), INTENT(INOUT) :: DGEIP
TYPE(DIAG_EVAP_ISBA_PATCH_t), INTENT(INOUT) :: DGEIPC
TYPE(DIAG_PATCH_t), INTENT(INOUT) :: DGIPC
TYPE(DIAG_EVAP_ISBA_t), INTENT(INOUT) :: DGEIPK
TYPE(DIAG_t), INTENT(INOUT) :: DGIPK
TYPE(ISBA_PROG_t), INTENT(INOUT) :: IRK
TYPE(ISBA_OPTIONS_t), INTENT(INOUT) :: IO
!
 CHARACTER(LEN=*), INTENT(IN) :: HSNOW_SCHEME
!
REAL,    INTENT(IN)               :: PTSTEP        ! time step
INTEGER, INTENT(IN)               :: KSIZE  
INTEGER, INTENT(IN) :: KPATCH
!
INTEGER, DIMENSION(:), INTENT(IN) :: KMASK
REAL,    DIMENSION(:), INTENT(IN) :: PRHOA         ! air density for unit change
!
INTEGER :: JJ
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
!*      0.2    declarations of local variables
!
!-------------------------------------------------------------------------------------
!
IF (LHOOK) CALL DR_HOOK('DIAG_EVAP_ISBA_N',0,ZHOOK_HANDLE)
!
IF (DGEI%LSURF_EVAP_BUDGET) THEN
!cdir nodep
  DO JJ=1,KSIZE
     !
     DGEIP%AL(KPATCH)%XLEG       (KMASK(JJ)) =  DGEIPK%XLEG       (JJ)
     DGEIP%AL(KPATCH)%XLEGI      (KMASK(JJ)) =  DGEIPK%XLEGI      (JJ)
     DGEIP%AL(KPATCH)%XLEV       (KMASK(JJ)) =  DGEIPK%XLEV       (JJ)
     DGEIP%AL(KPATCH)%XLES       (KMASK(JJ)) =  DGEIPK%XLES       (JJ)
     DGEIP%AL(KPATCH)%XLER       (KMASK(JJ)) =  DGEIPK%XLER       (JJ)
     DGEIP%AL(KPATCH)%XLETR      (KMASK(JJ)) =  DGEIPK%XLETR      (JJ)
     DGEIP%AL(KPATCH)%XDRAIN     (KMASK(JJ)) =  DGEIPK%XDRAIN     (JJ)
     DGEIP%AL(KPATCH)%XQSB       (KMASK(JJ)) =  DGEIPK%XQSB       (JJ)
     DGEIP%AL(KPATCH)%XRUNOFF    (KMASK(JJ)) =  DGEIPK%XRUNOFF    (JJ)
     DGEIP%AL(KPATCH)%XHORT      (KMASK(JJ)) =  DGEIPK%XHORT      (JJ)
     DGEIP%AL(KPATCH)%XDRIP      (KMASK(JJ)) =  DGEIPK%XDRIP      (JJ)
     DGEIP%AL(KPATCH)%XRRVEG     (KMASK(JJ)) =  DGEIPK%XRRVEG     (JJ)
     DGEIP%AL(KPATCH)%XMELT      (KMASK(JJ)) =  DGEIPK%XMELT      (JJ)
     DGEIP%AL(KPATCH)%XIFLOOD    (KMASK(JJ)) =  DGEIPK%XIFLOOD    (JJ)
     DGEIP%AL(KPATCH)%XPFLOOD    (KMASK(JJ)) =  DGEIPK%XPFLOOD    (JJ)
     DGEIP%AL(KPATCH)%XLE_FLOOD  (KMASK(JJ)) =  DGEIPK%XLE_FLOOD  (JJ)
     DGEIP%AL(KPATCH)%XLEI_FLOOD (KMASK(JJ)) =  DGEIPK%XLEI_FLOOD (JJ)
     DGEIP%AL(KPATCH)%XIRRIG_FLUX(KMASK(JJ)) =  DGEIPK%XIRRIG_FLUX(JJ)
     !
     IF (IO%LMEB_PATCH(KPATCH)) THEN
       DGEIP%AL(KPATCH)%XLEVCV    (KMASK(JJ)) =  DGEIPK%XLEVCV   (JJ)
       DGEIP%AL(KPATCH)%XLESC     (KMASK(JJ)) =  DGEIPK%XLESC    (JJ)
       DGEIP%AL(KPATCH)%XLETRCV   (KMASK(JJ)) =  DGEIPK%XLETRCV  (JJ)
       DGEIP%AL(KPATCH)%XLELITTER (KMASK(JJ)) =  DGEIPK%XLELITTER (JJ)
       DGEIP%AL(KPATCH)%XLELITTERI(KMASK(JJ)) =  DGEIPK%XLELITTERI(JJ)
       DGEIP%AL(KPATCH)%XDRIPLIT  (KMASK(JJ)) =  DGEIPK%XDRIPLIT  (JJ)
       DGEIP%AL(KPATCH)%XRRLIT    (KMASK(JJ)) =  DGEIPK%XRRLIT   (JJ)
       DGEIP%AL(KPATCH)%XLERCV    (KMASK(JJ)) =  DGEIPK%XLERCV   (JJ)
       DGEIP%AL(KPATCH)%XLE_C_A   (KMASK(JJ)) =  DGEIPK%XLE_C_A  (JJ)
       DGEIP%AL(KPATCH)%XLE_V_C   (KMASK(JJ)) =  DGEIPK%XLE_V_C  (JJ)
       DGEIP%AL(KPATCH)%XLE_G_C   (KMASK(JJ)) =  DGEIPK%XLE_G_C  (JJ)
       DGEIP%AL(KPATCH)%XLE_N_C   (KMASK(JJ)) =  DGEIPK%XLE_N_C  (JJ)
       !
       DGEIP%AL(KPATCH)%XSWNET_V  (KMASK(JJ)) = DGEIPK%XSWNET_V  (JJ)
       DGEIP%AL(KPATCH)%XSWNET_G  (KMASK(JJ)) = DGEIPK%XSWNET_G  (JJ)
       DGEIP%AL(KPATCH)%XSWNET_N  (KMASK(JJ)) = DGEIPK%XSWNET_N  (JJ)
       DGEIP%AL(KPATCH)%XSWNET_NS (KMASK(JJ)) = DGEIPK%XSWNET_NS (JJ)
       DGEIP%AL(KPATCH)%XLWNET_V  (KMASK(JJ)) = DGEIPK%XLWNET_V  (JJ)
       DGEIP%AL(KPATCH)%XLWNET_G  (KMASK(JJ)) = DGEIPK%XLWNET_G  (JJ)
       DGEIP%AL(KPATCH)%XLWNET_N  (KMASK(JJ)) = DGEIPK%XLWNET_N  (JJ)
       DGEIP%AL(KPATCH)%XSWDOWN_GN(KMASK(JJ)) = DGEIPK%XSWDOWN_GN(JJ)
       DGEIP%AL(KPATCH)%XLWDOWN_GN(KMASK(JJ)) = DGEIPK%XLWDOWN_GN(JJ)
       DGEIP%AL(KPATCH)%XH_V_C    (KMASK(JJ)) = DGEIPK%XH_V_C    (JJ)
       DGEIP%AL(KPATCH)%XH_G_C    (KMASK(JJ)) = DGEIPK%XH_G_C    (JJ)
       DGEIP%AL(KPATCH)%XH_C_A    (KMASK(JJ)) = DGEIPK%XH_C_A    (JJ)
       DGEIP%AL(KPATCH)%XH_N_C    (KMASK(JJ)) = DGEIPK%XH_N_C    (JJ)
       DGEIP%AL(KPATCH)%XSR_GN    (KMASK(JJ)) = DGEIPK%XSR_GN    (JJ)
       DGEIP%AL(KPATCH)%XMELTCV   (KMASK(JJ)) = DGEIPK%XMELTCV   (JJ)
       DGEIP%AL(KPATCH)%XFRZCV    (KMASK(JJ)) = DGEIPK%XFRZCV    (JJ)
     ENDIF
     !
  END DO
  !
  IF (HSNOW_SCHEME=='3-L' .OR. HSNOW_SCHEME=='CRO') THEN
!cdir nodep
     DO JJ=1,KSIZE
        DGEIP%AL(KPATCH)%XLESL    (KMASK(JJ))  =  DGEIPK%XLESL       (JJ)
        DGEIP%AL(KPATCH)%XSNDRIFT (KMASK(JJ))  =  DGEIPK%XSNDRIFT    (JJ)
     END DO
  END IF
  !
  IF(IO%CPHOTO/='NON')THEN
!cdir nodep
     DO JJ=1,KSIZE
        ! Transform units from kgCO2/kgair m/s to kgCO2/m2/s
        DGEIP%AL(KPATCH)%XGPP       (KMASK(JJ))  =  DGEIPK%XGPP       (JJ) * PRHOA(JJ)
        DGEIP%AL(KPATCH)%XRESP_AUTO (KMASK(JJ))  =  DGEIPK%XRESP_AUTO (JJ) * PRHOA(JJ)
        DGEIP%AL(KPATCH)%XRESP_ECO  (KMASK(JJ))  =  DGEIPK%XRESP_ECO  (JJ) * PRHOA(JJ)
        !
     END DO
  ELSE  
     DGEIP%AL(KPATCH)%XGPP      (:)=0.0
     DGEIP%AL(KPATCH)%XRESP_AUTO(:)=0.0
     DGEIP%AL(KPATCH)%XRESP_ECO (:)=0.0
  ENDIF
  !
  IF(DGEI%LWATER_BUDGET)THEN
!cdir nodep
     DO JJ=1,KSIZE
        DGEIP%AL(KPATCH)%XDWG   (KMASK(JJ))  =  DGEIPK%XDWG   (JJ)
        DGEIP%AL(KPATCH)%XDWGI  (KMASK(JJ))  =  DGEIPK%XDWGI  (JJ)
        DGEIP%AL(KPATCH)%XDWR   (KMASK(JJ))  =  DGEIPK%XDWR   (JJ)
        DGEIP%AL(KPATCH)%XDSWE  (KMASK(JJ))  =  DGEIPK%XDSWE  (JJ)
        DGEIP%AL(KPATCH)%XWATBUD(KMASK(JJ))  =  DGEIPK%XWATBUD(JJ)
     END DO
  ENDIF
  !
END IF
!
IF (OSURF_BUDGETC) THEN
!cdir nodep
  DO JJ=1,KSIZE
     !
     DGIPC%AL(KPATCH)%XRN   (KMASK(JJ)) = DGIPC%AL(KPATCH)%XRN   (KMASK(JJ)) + DGIPK%XRN        (JJ) * PTSTEP
     DGIPC%AL(KPATCH)%XH    (KMASK(JJ)) = DGIPC%AL(KPATCH)%XH    (KMASK(JJ)) + DGIPK%XH         (JJ) * PTSTEP
     DGIPC%AL(KPATCH)%XLE   (KMASK(JJ)) = DGIPC%AL(KPATCH)%XLE   (KMASK(JJ)) + IRK%XLE        (JJ,1) * PTSTEP
     DGIPC%AL(KPATCH)%XLEI  (KMASK(JJ)) = DGIPC%AL(KPATCH)%XLEI  (KMASK(JJ)) + DGIPK%XLEI       (JJ) * PTSTEP
     DGIPC%AL(KPATCH)%XGFLUX(KMASK(JJ)) = DGIPC%AL(KPATCH)%XGFLUX(KMASK(JJ)) + DGIPK%XGFLUX     (JJ) * PTSTEP
     !
     DGEIPC%AL(KPATCH)%XLEG     (KMASK(JJ)) = DGEIPC%AL(KPATCH)%XLEG     (KMASK(JJ)) + DGEIPK%XLEG       (JJ) * PTSTEP
     DGEIPC%AL(KPATCH)%XLEGI    (KMASK(JJ)) = DGEIPC%AL(KPATCH)%XLEGI    (KMASK(JJ)) + DGEIPK%XLEGI      (JJ) * PTSTEP
     DGEIPC%AL(KPATCH)%XLEV     (KMASK(JJ)) = DGEIPC%AL(KPATCH)%XLEV     (KMASK(JJ)) + DGEIPK%XLEV       (JJ) * PTSTEP
     DGEIPC%AL(KPATCH)%XLES     (KMASK(JJ)) = DGEIPC%AL(KPATCH)%XLES     (KMASK(JJ)) + DGEIPK%XLES       (JJ) * PTSTEP
     DGEIPC%AL(KPATCH)%XLER     (KMASK(JJ)) = DGEIPC%AL(KPATCH)%XLER     (KMASK(JJ)) + DGEIPK%XLER       (JJ) * PTSTEP
     DGEIPC%AL(KPATCH)%XLETR    (KMASK(JJ)) = DGEIPC%AL(KPATCH)%XLETR    (KMASK(JJ)) + DGEIPK%XLETR      (JJ) * PTSTEP
     DGIPC%AL(KPATCH)%XEVAP     (KMASK(JJ)) = DGIPC%AL(KPATCH)%XEVAP     (KMASK(JJ)) + DGIPK%XEVAP       (JJ) * PTSTEP
     DGIPC%AL(KPATCH)%XSUBL     (KMASK(JJ)) = DGIPC%AL(KPATCH)%XSUBL     (KMASK(JJ)) + DGIPK%XSUBL       (JJ) * PTSTEP
     DGEIPC%AL(KPATCH)%XDRAIN   (KMASK(JJ)) = DGEIPC%AL(KPATCH)%XDRAIN   (KMASK(JJ)) + DGEIPK%XDRAIN     (JJ) * PTSTEP
     DGEIPC%AL(KPATCH)%XQSB     (KMASK(JJ)) = DGEIPC%AL(KPATCH)%XQSB     (KMASK(JJ)) + DGEIPK%XQSB       (JJ) * PTSTEP
     DGEIPC%AL(KPATCH)%XRUNOFF  (KMASK(JJ)) = DGEIPC%AL(KPATCH)%XRUNOFF  (KMASK(JJ)) + DGEIPK%XRUNOFF    (JJ) * PTSTEP
     DGEIPC%AL(KPATCH)%XHORT    (KMASK(JJ)) = DGEIPC%AL(KPATCH)%XHORT    (KMASK(JJ)) + DGEIPK%XHORT      (JJ) * PTSTEP
     DGEIPC%AL(KPATCH)%XDRIP    (KMASK(JJ)) = DGEIPC%AL(KPATCH)%XDRIP    (KMASK(JJ)) + DGEIPK%XDRIP      (JJ) * PTSTEP
     DGEIPC%AL(KPATCH)%XRRVEG   (KMASK(JJ)) = DGEIPC%AL(KPATCH)%XRRVEG   (KMASK(JJ)) + DGEIPK%XRRVEG     (JJ) * PTSTEP
     DGEIPC%AL(KPATCH)%XMELT    (KMASK(JJ)) = DGEIPC%AL(KPATCH)%XMELT    (KMASK(JJ)) + DGEIPK%XMELT      (JJ) * PTSTEP
     DGEIPC%AL(KPATCH)%XIFLOOD  (KMASK(JJ)) = DGEIPC%AL(KPATCH)%XIFLOOD  (KMASK(JJ)) + DGEIPK%XIFLOOD    (JJ) * PTSTEP
     DGEIPC%AL(KPATCH)%XPFLOOD  (KMASK(JJ)) = DGEIPC%AL(KPATCH)%XPFLOOD  (KMASK(JJ)) + DGEIPK%XPFLOOD    (JJ) * PTSTEP
     DGEIPC%AL(KPATCH)%XLE_FLOOD(KMASK(JJ)) = DGEIPC%AL(KPATCH)%XLE_FLOOD(KMASK(JJ)) + DGEIPK%XLE_FLOOD  (JJ) * PTSTEP
     DGEIPC%AL(KPATCH)%XLEI_FLOOD (KMASK(JJ)) = DGEIPC%AL(KPATCH)%XLEI_FLOOD (KMASK(JJ)) + DGEIPK%XLEI_FLOOD (JJ) * PTSTEP
     DGEIPC%AL(KPATCH)%XIRRIG_FLUX(KMASK(JJ)) = DGEIPC%AL(KPATCH)%XIRRIG_FLUX(KMASK(JJ)) + DGEIPK%XIRRIG_FLUX(JJ) * PTSTEP
     !
     IF (IO%LMEB_PATCH(KPATCH)) THEN
       DGEIPC%AL(KPATCH)%XLEVCV(KMASK(JJ))  = DGEIPC%AL(KPATCH)%XLEVCV(KMASK(JJ)) + DGEIPK%XLEVCV   (JJ) * PTSTEP
       DGEIPC%AL(KPATCH)%XLESC (KMASK(JJ))  = DGEIPC%AL(KPATCH)%XLESC (KMASK(JJ)) + DGEIPK%XLESC    (JJ) * PTSTEP
!       XLETRGVC (KMASK(JJ))  = XLETRGVC (KMASK(JJ)) + XP_LETRGV   (JJ) * PTSTEP
       DGEIPC%AL(KPATCH)%XLETRCV(KMASK(JJ)) = DGEIPC%AL(KPATCH)%XLETRCV (KMASK(JJ)) + DGEIPK%XLETRCV(JJ) * PTSTEP
!       XLERGVC  (KMASK(JJ))  = XLERGVC  (KMASK(JJ)) + XP_LERGV    (JJ) * PTSTEP
       DGEIPC%AL(KPATCH)%XLERCV(KMASK(JJ))  = DGEIPC%AL(KPATCH)%XLERCV(KMASK(JJ)) + DGEIPK%XLERCV   (JJ) * PTSTEP
       DGEIPC%AL(KPATCH)%XLE_C_A(KMASK(JJ)) = DGEIPC%AL(KPATCH)%XLE_C_A(KMASK(JJ)) + DGEIPK%XLE_C_A (JJ) * PTSTEP
       DGEIPC%AL(KPATCH)%XLE_V_C(KMASK(JJ)) = DGEIPC%AL(KPATCH)%XLE_V_C(KMASK(JJ)) + DGEIPK%XLE_V_C (JJ) * PTSTEP
       DGEIPC%AL(KPATCH)%XLE_G_C(KMASK(JJ)) = DGEIPC%AL(KPATCH)%XLE_G_C(KMASK(JJ)) + DGEIPK%XLE_G_C (JJ) * PTSTEP
       DGEIPC%AL(KPATCH)%XLE_N_C(KMASK(JJ)) = DGEIPC%AL(KPATCH)%XLE_N_C(KMASK(JJ)) + DGEIPK%XLE_N_C (JJ) * PTSTEP
       !
       DGEIPC%AL(KPATCH)%XSWNET_V  (KMASK(JJ))  = DGEIPC%AL(KPATCH)%XSWNET_V  (KMASK(JJ))  + DGEIPK%XSWNET_V    (JJ) * PTSTEP
       DGEIPC%AL(KPATCH)%XSWNET_G  (KMASK(JJ))  = DGEIPC%AL(KPATCH)%XSWNET_G  (KMASK(JJ))  + DGEIPK%XSWNET_G    (JJ) * PTSTEP
       DGEIPC%AL(KPATCH)%XSWNET_N  (KMASK(JJ))  = DGEIPC%AL(KPATCH)%XSWNET_N  (KMASK(JJ))  + DGEIPK%XSWNET_N    (JJ) * PTSTEP
       DGEIPC%AL(KPATCH)%XSWNET_NS (KMASK(JJ))  = DGEIPC%AL(KPATCH)%XSWNET_NS (KMASK(JJ))  + DGEIPK%XSWNET_NS   (JJ) * PTSTEP
       DGEIPC%AL(KPATCH)%XLWNET_V  (KMASK(JJ))  = DGEIPC%AL(KPATCH)%XLWNET_V  (KMASK(JJ))  + DGEIPK%XLWNET_V    (JJ) * PTSTEP
       DGEIPC%AL(KPATCH)%XLWNET_G  (KMASK(JJ))  = DGEIPC%AL(KPATCH)%XLWNET_G  (KMASK(JJ))  + DGEIPK%XLWNET_G    (JJ) * PTSTEP
       DGEIPC%AL(KPATCH)%XLWNET_N  (KMASK(JJ))  = DGEIPC%AL(KPATCH)%XLWNET_N  (KMASK(JJ))  + DGEIPK%XLWNET_N    (JJ) * PTSTEP
       DGEIPC%AL(KPATCH)%XSWDOWN_GN(KMASK(JJ))  = DGEIPC%AL(KPATCH)%XSWDOWN_GN(KMASK(JJ))  + DGEIPK%XSWDOWN_GN  (JJ) * PTSTEP
       DGEIPC%AL(KPATCH)%XLWDOWN_GN(KMASK(JJ))  = DGEIPC%AL(KPATCH)%XLWDOWN_GN(KMASK(JJ))  + DGEIPK%XLWDOWN_GN  (JJ) * PTSTEP
       DGEIPC%AL(KPATCH)%XH_V_C    (KMASK(JJ))  = DGEIPC%AL(KPATCH)%XH_V_C    (KMASK(JJ))  + DGEIPK%XH_V_C      (JJ) * PTSTEP
       DGEIPC%AL(KPATCH)%XH_G_C    (KMASK(JJ))  = DGEIPC%AL(KPATCH)%XH_G_C    (KMASK(JJ))  + DGEIPK%XH_G_C      (JJ) * PTSTEP
       DGEIPC%AL(KPATCH)%XH_C_A    (KMASK(JJ))  = DGEIPC%AL(KPATCH)%XH_C_A    (KMASK(JJ))  + DGEIPK%XH_C_A      (JJ) * PTSTEP
       DGEIPC%AL(KPATCH)%XH_N_C    (KMASK(JJ))  = DGEIPC%AL(KPATCH)%XH_N_C    (KMASK(JJ))  + DGEIPK%XH_N_C      (JJ) * PTSTEP
       DGEIPC%AL(KPATCH)%XSR_GN    (KMASK(JJ))  = DGEIPC%AL(KPATCH)%XSR_GN    (KMASK(JJ))  + DGEIPK%XSR_GN      (JJ) * PTSTEP
       DGEIPC%AL(KPATCH)%XMELTCV   (KMASK(JJ))  = DGEIPC%AL(KPATCH)%XMELTCV   (KMASK(JJ))  + DGEIPK%XMELTCV     (JJ) * PTSTEP
       DGEIPC%AL(KPATCH)%XFRZCV    (KMASK(JJ))  = DGEIPC%AL(KPATCH)%XFRZCV    (KMASK(JJ))  + DGEIPK%XFRZCV      (JJ) * PTSTEP
     ENDIF
     !
     DGIPC%AL(KPATCH)%XSWD(KMASK(JJ))  = DGIPC%AL(KPATCH)%XSWD(KMASK(JJ)) + DGIPK%XSWD(JJ) * PTSTEP
     DGIPC%AL(KPATCH)%XSWU(KMASK(JJ))  = DGIPC%AL(KPATCH)%XSWU(KMASK(JJ)) + DGIPK%XSWU(JJ) * PTSTEP
     DGIPC%AL(KPATCH)%XLWD(KMASK(JJ))  = DGIPC%AL(KPATCH)%XLWD(KMASK(JJ)) + DGIPK%XLWD(JJ) * PTSTEP
     DGIPC%AL(KPATCH)%XLWU(KMASK(JJ))  = DGIPC%AL(KPATCH)%XLWU(KMASK(JJ)) + DGIPK%XLWU(JJ) * PTSTEP
     DGIPC%AL(KPATCH)%XFMU(KMASK(JJ))  = DGIPC%AL(KPATCH)%XFMU(KMASK(JJ)) + DGIPK%XFMU(JJ) * PTSTEP
     DGIPC%AL(KPATCH)%XFMV(KMASK(JJ))  = DGIPC%AL(KPATCH)%XFMV(KMASK(JJ)) + DGIPK%XFMV(JJ) * PTSTEP
     !
  END DO
  !
  IF (HSNOW_SCHEME=='3-L' .OR. HSNOW_SCHEME=='CRO') THEN
!cdir nodep
     DO JJ=1,KSIZE
        DGEIPC%AL(KPATCH)%XLESL    (KMASK(JJ)) = DGEIPC%AL(KPATCH)%XLESL    (KMASK(JJ)) + DGEIPK%XLESL    (JJ) * PTSTEP
        DGEIPC%AL(KPATCH)%XSNDRIFT (KMASK(JJ)) = DGEIPC%AL(KPATCH)%XSNDRIFT (KMASK(JJ)) + DGEIPK%XSNDRIFT (JJ) * PTSTEP
     END DO
  END IF
  !
  IF(IO%CPHOTO/='NON')THEN
!cdir nodep
     DO JJ=1,KSIZE
        !Transform units from kgCO2/kgair m/s to kgCO2/m2
        DGEIPC%AL(KPATCH)%XGPP       (KMASK(JJ))  =  DGEIPC%AL(KPATCH)%XGPP       (KMASK(JJ))+  &
                DGEIPK%XGPP       (JJ) * PRHOA(JJ) * PTSTEP
        DGEIPC%AL(KPATCH)%XRESP_AUTO (KMASK(JJ))  =  DGEIPC%AL(KPATCH)%XRESP_AUTO (KMASK(JJ))+  &
                DGEIPK%XRESP_AUTO (JJ) * PRHOA(JJ) * PTSTEP
        DGEIPC%AL(KPATCH)%XRESP_ECO  (KMASK(JJ))  =  DGEIPC%AL(KPATCH)%XRESP_ECO  (KMASK(JJ))+  &
                DGEIPK%XRESP_ECO  (JJ) * PRHOA(JJ) * PTSTEP
     END DO
  ELSE  
     DGEIPC%AL(KPATCH)%XGPP      (:)=0.0
     DGEIPC%AL(KPATCH)%XRESP_AUTO(:)=0.0
     DGEIPC%AL(KPATCH)%XRESP_ECO (:)=0.0       
  ENDIF
  !
  IF(IO%LGLACIER)THEN
!cdir nodep
    DO JJ=1,KSIZE
       DGEIPC%AL(KPATCH)%XICEFLUX(KMASK(JJ))  = DGEIPC%AL(KPATCH)%XICEFLUX(KMASK(JJ)) + DGEIPK%XICEFLUX(JJ) * PTSTEP
    END DO  
  END IF
  !  
  IF(DGEI%LWATER_BUDGET)THEN
!cdir nodep
     DO JJ=1,KSIZE
        DGEIPC%AL(KPATCH)%XDWG   (KMASK(JJ))  =  DGEIPC%AL(KPATCH)%XDWG   (KMASK(JJ)) + DGEIPK%XDWG   (JJ) * PTSTEP
        DGEIPC%AL(KPATCH)%XDWGI  (KMASK(JJ))  =  DGEIPC%AL(KPATCH)%XDWGI  (KMASK(JJ)) + DGEIPK%XDWGI  (JJ) * PTSTEP
        DGEIPC%AL(KPATCH)%XDWR   (KMASK(JJ))  =  DGEIPC%AL(KPATCH)%XDWR   (KMASK(JJ)) + DGEIPK%XDWR   (JJ) * PTSTEP
        DGEIPC%AL(KPATCH)%XDSWE  (KMASK(JJ))  =  DGEIPC%AL(KPATCH)%XDSWE  (KMASK(JJ)) + DGEIPK%XDSWE  (JJ) * PTSTEP
        DGEIPC%AL(KPATCH)%XWATBUD(KMASK(JJ))  =  DGEIPC%AL(KPATCH)%XWATBUD(KMASK(JJ)) + DGEIPK%XWATBUD(JJ) * PTSTEP
     END DO
  ENDIF
  !  
END IF
IF (LHOOK) CALL DR_HOOK('DIAG_EVAP_ISBA_N',1,ZHOOK_HANDLE)
!
!-------------------------------------------------------------------------------------
!
END SUBROUTINE DIAG_EVAP_ISBA_n
