!     #########
      SUBROUTINE DIAG_FLAKE_INIT_n (OREAD_BUDGETC, DFO, DGF, DGFC, DGMF, F, &
                                    HPROGRAM,KLU,KSW)
!     #####################
!
!!****  *DIAG_FLAKE_INIT_n* - routine to initialize FLAKE diagnostic variables
!!
!!    PURPOSE
!!    -------
!!
!!**  METHOD
!!    ------
!!
!!    EXTERNAL
!!    --------
!!
!!
!!    IMPLICIT ARGUMENTS
!!    ------------------
!!
!!    REFERENCE
!!    ---------
!!
!!
!!    AUTHOR
!!    ------
!!      V. Masson   *Meteo France*
!!
!!    MODIFICATIONS
!!    -------------
!!      Original    01/2004 
!!       V.Masson   10/2013 Adds min and max 2m parameters
!!      B. Decharme  04/2013 new diag
!-------------------------------------------------------------------------------
!
!*       0.    DECLARATIONS
!              ------------
!
!
USE MODD_DIAG_n, ONLY : DIAG_t, DIAG_OPTIONS_t
USE MODD_DIAG_MISC_FLAKE_n, ONLY : DIAG_MISC_FLAKE_t
USE MODD_FLAKE_n, ONLY : FLAKE_t
!
#ifdef SFX_OL
USE MODN_IO_OFFLINE,     ONLY : LRESTART
#endif
USE MODD_SURF_PAR,       ONLY : XUNDEF
USE MODD_SFX_OASIS,      ONLY : LCPL_LAKE
!
!
!
!
USE MODI_READ_SURF
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE
!
!*       0.1   Declarations of arguments
!              -------------------------
!
!
!
TYPE(DIAG_OPTIONS_t), INTENT(INOUT) :: DFO
TYPE(DIAG_t), INTENT(INOUT) :: DGF
TYPE(DIAG_t), INTENT(INOUT) :: DGFC
TYPE(DIAG_MISC_FLAKE_t), INTENT(INOUT) :: DGMF
LOGICAL, INTENT(IN) :: OREAD_BUDGETC
TYPE(FLAKE_t), INTENT(INOUT) :: F
!
INTEGER, INTENT(IN) :: KLU   ! size of arrays
INTEGER, INTENT(IN) :: KSW   ! number of SW spectral bands
CHARACTER(LEN=6), INTENT(IN):: HPROGRAM  ! program calling
!
!*       0.2   Declarations of local variables
!              -------------------------------
!
INTEGER           :: IVERSION
INTEGER           :: IRESP          ! IRESP  : return-code if a problem appears
CHARACTER(LEN=12) :: YREC           ! Name of the article to be read
REAL(KIND=JPRB)   :: ZHOOK_HANDLE
!
!-------------------------------------------------------------------------------
!
!* surface energy budget
!
IF (LHOOK) CALL DR_HOOK('DIAG_FLAKE_INIT_N',0,ZHOOK_HANDLE)
!
ALLOCATE(DGF%XTS(KLU))
DGF%XTS = XUNDEF
!
IF (DFO%LSURF_BUDGET.OR.DFO%LSURF_BUDGETC) THEN
  ALLOCATE(DGF%XRN     (KLU))
  ALLOCATE(DGF%XH      (KLU))
  ALLOCATE(DGF%XLE     (KLU))
  ALLOCATE(DGF%XLEI    (KLU))
  ALLOCATE(DGF%XGFLUX  (KLU))
  ALLOCATE(DGF%XEVAP   (KLU))
  ALLOCATE(DGF%XSUBL   (KLU))
  ALLOCATE(DGF%XSWD    (KLU))
  ALLOCATE(DGF%XSWU    (KLU))
  ALLOCATE(DGF%XLWD    (KLU))
  ALLOCATE(DGF%XLWU    (KLU))
  ALLOCATE(DGF%XSWBD   (KLU,KSW))
  ALLOCATE(DGF%XSWBU   (KLU,KSW))
  ALLOCATE(DGF%XFMU    (KLU))
  ALLOCATE(DGF%XFMV    (KLU))
  ALLOCATE(DGF%XALBT   (KLU))
  ALLOCATE(DGF%XSWE    (KLU))
  !
  DGF%XRN      = XUNDEF
  DGF%XH       = XUNDEF
  DGF%XLE      = XUNDEF
  DGF%XLEI     = XUNDEF
  DGF%XGFLUX   = XUNDEF
  DGF%XEVAP    = XUNDEF
  DGF%XSUBL    = XUNDEF  
  DGF%XSWD     = XUNDEF
  DGF%XSWU     = XUNDEF
  DGF%XLWD     = XUNDEF
  DGF%XLWU     = XUNDEF
  DGF%XSWBD    = XUNDEF
  DGF%XSWBU    = XUNDEF
  DGF%XFMU     = XUNDEF
  DGF%XFMV     = XUNDEF
  DGF%XALBT    = XUNDEF
  DGF%XSWE     = XUNDEF
ELSE
  ALLOCATE(DGF%XRN     (0))
  ALLOCATE(DGF%XH      (0))
  ALLOCATE(DGF%XLE     (0))
  ALLOCATE(DGF%XLEI    (0))
  ALLOCATE(DGF%XGFLUX  (0))
  ALLOCATE(DGF%XEVAP   (0))
  ALLOCATE(DGF%XSUBL   (0))  
  ALLOCATE(DGF%XSWD    (0))
  ALLOCATE(DGF%XSWU    (0))
  ALLOCATE(DGF%XLWD    (0))
  ALLOCATE(DGF%XLWU    (0))
  ALLOCATE(DGF%XSWBD   (0,0))
  ALLOCATE(DGF%XSWBU   (0,0))
  ALLOCATE(DGF%XFMU    (0))
  ALLOCATE(DGF%XFMV    (0))
  ALLOCATE(DGF%XALBT   (0))
  ALLOCATE(DGF%XSWE    (0))
END IF
!
!* cumulative surface energy budget
!
#ifdef SFX_OL
IF (DFO%LSURF_BUDGETC .OR. (LRESTART .AND. .NOT.DFO%LRESET_BUDGETC)) THEN
#else
IF (DFO%LSURF_BUDGETC .OR. .NOT.DFO%LRESET_BUDGETC) THEN
#endif
!    
  ALLOCATE(DGFC%XRN   (KLU))
  ALLOCATE(DGFC%XH    (KLU))
  ALLOCATE(DGFC%XLE   (KLU))
  ALLOCATE(DGFC%XLEI  (KLU))
  ALLOCATE(DGFC%XGFLUX(KLU))
  ALLOCATE(DGFC%XEVAP (KLU))
  ALLOCATE(DGFC%XSUBL (KLU))  
  ALLOCATE(DGFC%XSWD  (KLU))
  ALLOCATE(DGFC%XSWU  (KLU))
  ALLOCATE(DGFC%XLWD  (KLU))
  ALLOCATE(DGFC%XLWU  (KLU))
  ALLOCATE(DGFC%XFMU  (KLU))
  ALLOCATE(DGFC%XFMV  (KLU))
!
  IF (.NOT. OREAD_BUDGETC) THEN        
     DGFC%XRN   = 0.0
     DGFC%XH    = 0.0
     DGFC%XLE   = 0.0
     DGFC%XLEI  = 0.0
     DGFC%XGFLUX = 0.0
     DGFC%XEVAP  = 0.0
     DGFC%XSUBL  = 0.0
     DGFC%XSWD   = 0.0
     DGFC%XSWU  = 0.0
     DGFC%XLWD  = 0.0
     DGFC%XLWU  = 0.0
     DGFC%XFMU  = 0.0
     DGFC%XFMV  = 0.0
  ELSEIF (OREAD_BUDGETC.AND.DFO%LRESET_BUDGETC) THEN
     DGFC%XRN   = 0.0
     DGFC%XH    = 0.0
     DGFC%XLE   = 0.0
     DGFC%XLEI  = 0.0
     DGFC%XGFLUX= 0.0
     DGFC%XEVAP = 0.0
     DGFC%XSUBL = 0.0     
     DGFC%XSWD  = 0.0
     DGFC%XSWU  = 0.0
     DGFC%XLWD  = 0.0
     DGFC%XLWU  = 0.0
     DGFC%XFMU  = 0.0
     DGFC%XFMV  = 0.0
  ELSE
     CALL READ_SURF(&
                    HPROGRAM,'VERSION',IVERSION,IRESP)
     IF (IVERSION<8)THEN
       DGFC%XRN   = 0.0
       DGFC%XH    = 0.0
       DGFC%XLE   = 0.0
       DGFC%XLEI  = 0.0
       DGFC%XGFLUX= 0.0
       DGFC%XEVAP = 0.0
       DGFC%XSUBL = 0.0     
       DGFC%XSWD  = 0.0
       DGFC%XSWU  = 0.0
       DGFC%XLWD  = 0.0
       DGFC%XLWU  = 0.0
       DGFC%XFMU  = 0.0
       DGFC%XFMV  = 0.0             
     ELSE
       YREC='RNC_WAT'
       CALL READ_SURF(&
                    HPROGRAM,YREC,DGFC%XRN,IRESP)
       YREC='HC_WAT'
       CALL READ_SURF(&
                    HPROGRAM,YREC,DGFC%XH,IRESP)
       YREC='LEC_WAT'
       CALL READ_SURF(&
                    HPROGRAM,YREC,DGFC%XLE,IRESP)
       YREC='LEIC_WAT'
       CALL READ_SURF(&
                    HPROGRAM,YREC,DGFC%XLEI,IRESP)     
       YREC='GFLUXC_WAT'
       CALL READ_SURF(&
                    HPROGRAM,YREC,DGFC%XGFLUX,IRESP)
       YREC='SWDC_WAT'
       CALL READ_SURF(&
                    HPROGRAM,YREC,DGFC%XSWD,IRESP)
       YREC='SWUC_WAT'
       CALL READ_SURF(&
                    HPROGRAM,YREC,DGFC%XSWU,IRESP)
       YREC='LWDC_WAT'
       CALL READ_SURF(&
                    HPROGRAM,YREC,DGFC%XLWD,IRESP)
       YREC='LWUC_WAT'
       CALL READ_SURF(&
                    HPROGRAM,YREC,DGFC%XLWU,IRESP)
       YREC='FMUC_WAT'
       CALL READ_SURF(&
                    HPROGRAM,YREC,DGFC%XFMU,IRESP)
       YREC='FMVC_WAT'
       CALL READ_SURF(&
                    HPROGRAM,YREC,DGFC%XFMV,IRESP)
       YREC='EVAPC_WAT'
        CALL READ_SURF(&
                    HPROGRAM,YREC,DGFC%XEVAP,IRESP)
        YREC='SUBLC_WAT'
        CALL READ_SURF(&
                    HPROGRAM,YREC,DGFC%XSUBL,IRESP)              
      ENDIF
!
  ENDIF   
ELSE
  ALLOCATE(DGFC%XRN   (0))
  ALLOCATE(DGFC%XH    (0))
  ALLOCATE(DGFC%XLE   (0))
  ALLOCATE(DGFC%XLEI  (0))
  ALLOCATE(DGFC%XGFLUX(0))
  ALLOCATE(DGFC%XEVAP (0))
  ALLOCATE(DGFC%XSUBL (0))  
  ALLOCATE(DGFC%XSWD  (0))
  ALLOCATE(DGFC%XSWU  (0))
  ALLOCATE(DGFC%XLWD  (0))
  ALLOCATE(DGFC%XLWU  (0))
  ALLOCATE(DGFC%XFMU  (0))
  ALLOCATE(DGFC%XFMV  (0))  
ENDIF
!
!* parameters at 2m
!
IF (DFO%N2M>=1) THEN
  ALLOCATE(DGF%XRI     (KLU))
  ALLOCATE(DGF%XT2M    (KLU))
  ALLOCATE(DGF%XT2M_MIN(KLU))
  ALLOCATE(DGF%XT2M_MAX(KLU))
  ALLOCATE(DGF%XQ2M    (KLU))
  ALLOCATE(DGF%XHU2M   (KLU))
  ALLOCATE(DGF%XHU2M_MIN(KLU))
  ALLOCATE(DGF%XHU2M_MAX(KLU))
  ALLOCATE(DGF%XZON10M (KLU))
  ALLOCATE(DGF%XMER10M (KLU))
  ALLOCATE(DGF%XWIND10M (KLU))
  ALLOCATE(DGF%XWIND10M_MAX(KLU))
  !
  DGF%XRI      = XUNDEF
  DGF%XT2M     = XUNDEF
  DGF%XT2M_MIN = XUNDEF
  DGF%XT2M_MAX = 0.0
  DGF%XQ2M     = XUNDEF
  DGF%XHU2M    = XUNDEF
  DGF%XHU2M_MIN= XUNDEF
  DGF%XHU2M_MAX=-XUNDEF
  DGF%XZON10M  = XUNDEF
  DGF%XMER10M  = XUNDEF
  DGF%XWIND10M = XUNDEF
  DGF%XWIND10M_MAX = 0.0
ELSE
  ALLOCATE(DGF%XRI      (0))
  ALLOCATE(DGF%XT2M     (0))
  ALLOCATE(DGF%XT2M_MIN (0))
  ALLOCATE(DGF%XT2M_MAX (0))
  ALLOCATE(DGF%XQ2M     (0))
  ALLOCATE(DGF%XHU2M    (0))
  ALLOCATE(DGF%XHU2M_MIN(0))
  ALLOCATE(DGF%XHU2M_MAX(0))
  ALLOCATE(DGF%XZON10M  (0))
  ALLOCATE(DGF%XMER10M  (0))
  ALLOCATE(DGF%XWIND10M (0))
  ALLOCATE(DGF%XWIND10M_MAX(0))
END IF
!
!* transfer coefficients
!
IF (DFO%LCOEF) THEN
  ALLOCATE(DGF%XCD     (KLU))
  ALLOCATE(DGF%XCH     (KLU))
  ALLOCATE(DGF%XCE     (KLU))
  ALLOCATE(DGF%XZ0     (KLU))
  ALLOCATE(DGF%XZ0H    (KLU))
  !
  DGF%XCD      = XUNDEF
  DGF%XCH      = XUNDEF
  DGF%XCE      = XUNDEF
  DGF%XZ0      = XUNDEF
  DGF%XZ0H     = XUNDEF
ELSE
  ALLOCATE(DGF%XCD     (0))
  ALLOCATE(DGF%XCH     (0))
  ALLOCATE(DGF%XCE     (0))
  ALLOCATE(DGF%XZ0     (0))
  ALLOCATE(DGF%XZ0H    (0))
END IF
!
!* surface humidity
!
IF (DFO%LSURF_VARS) THEN
  ALLOCATE(DGF%XQS     (KLU))
  !
  DGF%XQS      = XUNDEF
ELSE
  ALLOCATE(DGF%XQS     (0))
END IF
!
!* Flake temperature profile
!
IF (DGMF%LWATER_PROFILE) THEN
   ALLOCATE (DGMF%XZW_PROFILE(COUNT(DGMF%XZWAT_PROFILE/= XUNDEF))) 
   ALLOCATE (DGMF%XTW_PROFILE(COUNT(DGMF%XZWAT_PROFILE/= XUNDEF),KLU)) 
   DGMF%XZW_PROFILE=DGMF%XZWAT_PROFILE(:COUNT(DGMF%XZWAT_PROFILE /= XUNDEF))
 ELSE
   ALLOCATE (DGMF%XZW_PROFILE(0)) 
   ALLOCATE (DGMF%XTW_PROFILE(0,0)) 
 END IF
!
!* Coupling field with earth systme model
!
!
IF(LCPL_LAKE)THEN
!
  ALLOCATE(F%XCPL_FLAKE_EVAP(KLU))
  ALLOCATE(F%XCPL_FLAKE_RAIN(KLU))
  ALLOCATE(F%XCPL_FLAKE_SNOW(KLU))
  F%XCPL_FLAKE_EVAP(:) = 0.0
  F%XCPL_FLAKE_RAIN(:) = 0.0
  F%XCPL_FLAKE_SNOW(:) = 0.0
!
ELSE
!
  ALLOCATE(F%XCPL_FLAKE_EVAP(0))
  ALLOCATE(F%XCPL_FLAKE_RAIN(0))
  ALLOCATE(F%XCPL_FLAKE_SNOW(0))
!
ENDIF
!
IF (LHOOK) CALL DR_HOOK('DIAG_FLAKE_INIT_N',1,ZHOOK_HANDLE)
!
!-------------------------------------------------------------------------------
!
END SUBROUTINE DIAG_FLAKE_INIT_n
