!     #########
      SUBROUTINE DIAG_ISBA_INIT_n (CHI, DE, DEC, DEP, DEPC, DGO, D, DC, DP, DPC, DMI, DMIP, &
                                   OREAD_BUDGETC, NGB, GB, IO, NP, HSNOW_SCHEME, KSNOW_NLAYER, &
                                   KABC, HPROGRAM,KLU,KSW)
!     #####################
!
!!****  *DIAG_ISBA_INIT_n* - routine to initialize ISBA-AGS diagnostic variables
!!
!!    PURPOSE
!!    -------
!!
!!**  METHOD
!!    ------
!!
!!    EXTERNAL
!!    --------
!!
!!
!!    IMPLICIT ARGUMENTS
!!    ------------------
!!
!!    REFERENCE
!!    ---------
!!
!!
!!    AUTHOR
!!    ------
!!      V. Masson   *Meteo France*
!!
!!    MODIFICATIONS
!!    -------------
!!      Original    02/2003 
!!      modified    11/2003 by P. LeMoigne: surface cumulated energy budget
!!      modified    10/2004 by P. LeMoigne: surface miscellaneous fields
!!      B. Decharme    2008    New diag for water budget and allow to reset
!                               cumulatives variables at the beginning of a run
!!      B. Decharme 06/2009    add patch budget switch 
!!      B. Decharme 08/2009    add cummulative diag
!!      A.L. Gibelin 04/2009 : Add respiration diagnostics
!!      A.L. Gibelin 05/2009 : Add carbon spinup
!!      A.L. Gibelin 07/2009 : Suppress RDK and transform GPP as a diagnostic
!!      B. Decharme  05/12   : Carbon fluxes in diag_evap
!!      B. Decharme  10/12     Isba water budget diag
!!      B. Decharme  10/12     New diag for DIF:
!!                             F2 stress
!!                             Root zone swi, wg and wgi
!!                             swi, wg and wgi comparable to ISBA-FR-DG2 and DG3 layers
!!                             active layer thickness over permafrost
!!                             frozen layer thickness over non-permafrost
!!      B. Vincendon 02/2014 : condition added for RAD_BUDGET variables (needed for
!!                             restart mode)
!       B. decharme 04/2013 : Add new diag for coupling
!                             Delete XTSRAD (because same than XTSRAD_NAT)
!!      P. Samuelsson 10/2014: MEB
!-------------------------------------------------------------------------------
!
!*       0.0    DECLARATIONS
!              ------------
!
USE MODE_DIAG
!
USE MODD_CH_ISBA_n, ONLY : CH_ISBA_t
USE MODD_DIAG_EVAP_ISBA_n, ONLY : DIAG_EVAP_ISBA_t, DIAG_EVAP_ISBA_PATCH_t
USE MODD_DIAG_n, ONLY : DIAG_t, DIAG_PATCH_t, DIAG_OPTIONS_t
USE MODD_DIAG_MISC_ISBA_n, ONLY : DIAG_MISC_ISBA_t, DIAG_MISC_ISBA_PATCH_t
USE MODD_GR_BIOG_n, ONLY : GR_BIOG_NP_t, GR_BIOG_t
USE MODD_ISBA_OPTIONS_n, ONLY : ISBA_OPTIONS_t
USE MODD_ISBA_n, ONLY : ISBA_NP_t, ISBA_P_t
!
#ifdef SFX_OL
USE MODN_IO_OFFLINE,     ONLY : LRESTART
#endif
USE MODD_SURF_PAR,       ONLY : XUNDEF
USE MODD_TYPE_DATE_SURF
USE MODD_AGRI,           ONLY : LAGRIP
!
USE MODI_PACK_SAME_RANK
USE MODI_MAKE_CHOICE_ARRAY
USE MODI_READ_SURF
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE
!
!*       0.01   Declarations of arguments
!              -------------------------
!
TYPE(CH_ISBA_t), INTENT(INOUT) :: CHI
TYPE(DIAG_EVAP_ISBA_t), INTENT(INOUT) :: DE
TYPE(DIAG_EVAP_ISBA_t), INTENT(INOUT) :: DEC
TYPE(DIAG_EVAP_ISBA_PATCH_t), INTENT(INOUT) :: DEP
TYPE(DIAG_EVAP_ISBA_PATCH_t), INTENT(INOUT) :: DEPC
TYPE(DIAG_OPTIONS_t), INTENT(IN) :: DGO
TYPE(DIAG_t), INTENT(INOUT) :: D
TYPE(DIAG_t), INTENT(INOUT) :: DC
TYPE(DIAG_PATCH_t), INTENT(INOUT) :: DP
TYPE(DIAG_PATCH_t), INTENT(INOUT) :: DPC
TYPE(DIAG_MISC_ISBA_t), INTENT(INOUT) :: DMI
TYPE(DIAG_MISC_ISBA_PATCH_t), INTENT(INOUT) :: DMIP
LOGICAL, INTENT(IN) :: OREAD_BUDGETC
TYPE(GR_BIOG_NP_t), INTENT(INOUT) :: NGB
TYPE(GR_BIOG_t), INTENT(INOUT) :: GB
TYPE(ISBA_OPTIONS_t), INTENT(INOUT) :: IO
TYPE(ISBA_NP_t), INTENT(INOUT) :: NP
 CHARACTER(LEN=*), INTENT(IN) :: HSNOW_SCHEME
INTEGER, INTENT(IN) :: KSNOW_NLAYER
!
INTEGER, INTENT(IN) :: KABC
!
INTEGER, INTENT(IN)         :: KLU       ! size of arrays
INTEGER, INTENT(IN)         :: KSW       ! spectral bands
 CHARACTER(LEN=6), INTENT(IN):: HPROGRAM  ! program calling
!
!*       0.02   Declarations of local variables
!              -------------------------------
!
TYPE(DIAG_OPTIONS_t) :: YDO
TYPE(DIAG_EVAP_ISBA_t) :: YDE
TYPE(DIAG_MISC_ISBA_t) :: YDMI
TYPE(ISBA_P_t), POINTER :: PK
REAL, DIMENSION(:,:), ALLOCATABLE :: ZWORK
LOGICAL :: GCUMUL, GDIM
INTEGER :: JP
INTEGER           :: IVERSION, IBUG
INTEGER           :: IRESP          ! IRESP  : return-code if a problem appears
INTEGER           :: ISIZE_LMEB_PATCH   ! Number of patches where multi-energy balance should be applied
 CHARACTER(LEN=12) :: YREC           ! Name of the article to be read
 CHARACTER(LEN=5) :: YREC2
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
!-------------------------------------------------------------------------------
!
!////////////////NOT CUMULATED DIAGNOSTICS//////////////////////////////
!
!* surface energy budget
!
IF (LHOOK) CALL DR_HOOK('DIAG_ISBA_INIT_N',0,ZHOOK_HANDLE)
!
ISIZE_LMEB_PATCH=COUNT(IO%LMEB_PATCH(:))
!
YDO%LSURF_BUDGET = .TRUE.
YDO%N2M = 1
YDO%LCOEF = .TRUE.
YDO%LSURF_VARS = .TRUE.
!
YDE%LSURF_EVAP_BUDGET = .TRUE.
!
YDMI%LSURF_MISC_BUDGET = .TRUE.
!
 CALL ALLOC_BUD(YDO,D,KLU,KSW)
!
DO JP = 1,IO%NPATCH
  CALL ALLOC_BUD(YDO,DP%AL(JP),NP%AL(JP)%NSIZE_P,KSW)
  !
  ALLOCATE(DP%AL(JP)%XCDN(NP%AL(JP)%NSIZE_P))
  ALLOCATE(DP%AL(JP)%XHUG(NP%AL(JP)%NSIZE_P))
  ALLOCATE(DP%AL(JP)%XHU (NP%AL(JP)%NSIZE_P))
  !
  DP%AL(JP)%XCDN = XUNDEF
  DP%AL(JP)%XHUG = XUNDEF
  DP%AL(JP)%XHU  = XUNDEF
  !
ENDDO
!
IF (YDO%LSURF_BUDGET) THEN
  !
  ALLOCATE(D%XEVAP(KLU))
  ALLOCATE(D%XSUBL(KLU))
  D%XEVAP    = XUNDEF
  D%XSUBL    = XUNDEF
  !  
  DO JP = 1,IO%NPATCH
    ALLOCATE(DP%AL(JP)%XEVAP(NP%AL(JP)%NSIZE_P))
    ALLOCATE(DP%AL(JP)%XSUBL(NP%AL(JP)%NSIZE_P))  
    DP%AL(JP)%XEVAP = XUNDEF
    DP%AL(JP)%XSUBL = XUNDEF
  ENDDO
  !
ELSE
  !
  ALLOCATE(D%XEVAP(0))
  ALLOCATE(D%XSUBL(0))
  !  
  DO JP = 1,IO%NPATCH
    ALLOCATE(DP%AL(JP)%XEVAP(0))
    ALLOCATE(DP%AL(JP)%XSUBL(0))     
  ENDDO
  !
END IF
!
IF (YDO%N2M>=1) THEN
  !
  ALLOCATE(D%XSFCO2(KLU))
  D%XSFCO2 = XUNDEF
  DO JP = 1,IO%NPATCH
    ALLOCATE(DP%AL(JP)%XSFCO2(NP%AL(JP)%NSIZE_P))
    DP%AL(JP)%XSFCO2 = XUNDEF
  ENDDO
  !
ELSE
  !
  ALLOCATE(D%XSFCO2(0))
  DO JP=1,IO%NPATCH
    ALLOCATE(DP%AL(JP)%XSFCO2(0))
  ENDDO
  !
END IF
!
!* transfer coefficients
!
DO JP=1,IO%NPATCH
  ALLOCATE(DP%AL(JP)%XZ0EFF(NP%AL(JP)%NSIZE_P))
  DP%AL(JP)%XZ0EFF = XUNDEF
ENDDO
!
IF (YDO%LCOEF) THEN
  !
  ALLOCATE(D%XZ0EFF(KLU))
  D%XZ0EFF = XUNDEF  
  !
ELSE
  !
  ALLOCATE(D%XZ0EFF(0))
  !
END IF
!
!
!* surface temperature and parameters at 2m
!
ALLOCATE(D%XALBT(KLU))
D%XALBT = XUNDEF
DO JP=1,IO%NPATCH
  ALLOCATE(DP%AL(JP)%XTS    (NP%AL(JP)%NSIZE_P))
  ALLOCATE(DP%AL(JP)%XALBT  (NP%AL(JP)%NSIZE_P))
  ALLOCATE(DP%AL(JP)%XTSRAD (NP%AL(JP)%NSIZE_P))
  DP%AL(JP)%XTS    = XUNDEF
  DP%AL(JP)%XTSRAD = XUNDEF
  DP%AL(JP)%XALBT  = XUNDEF
ENDDO
!
!* detailed surface energy budget
!
IF (YDE%LSURF_EVAP_BUDGET) THEN
  ! 
  CALL ALLOC_EVAP_BUD(DE,KLU,0)
  DO JP = 1,IO%NPATCH
    CALL ALLOC_EVAP_BUD(DEP%AL(JP),NP%AL(JP)%NSIZE_P,NP%AL(JP)%NSIZE_P)
  ENDDO
  !
  IF (ISIZE_LMEB_PATCH>0) THEN
    !
    CALL ALLOC_MEB_BUD(DE,KLU)
    DO JP = 1,IO%NPATCH
      CALL ALLOC_MEB_BUD(DEP%AL(JP),NP%AL(JP)%NSIZE_P)
    ENDDO
    !
  ENDIF
  !
  IF(IO%LGLACIER)THEN
    ALLOCATE(DE%XICEFLUX(KLU))
    DE%XICEFLUX(:) = XUNDEF
    DO JP=1,IO%NPATCH
      ALLOCATE(DEP%AL(JP)%XICEFLUX(NP%AL(JP)%NSIZE_P))
      DEP%AL(JP)%XICEFLUX(:) = XUNDEF
    ENDDO
  ENDIF
  !  
  IF(DE%LWATER_BUDGET)THEN
    !      
    ALLOCATE(DE%XRAINFALL  (KLU))
    ALLOCATE(DE%XSNOWFALL  (KLU))
    DE%XRAINFALL   = XUNDEF
    DE%XSNOWFALL   = XUNDEF    
    !
    CALL ALLOC_WATER_BUD(DE,KLU)
    DO JP=1,IO%NPATCH
      CALL ALLOC_WATER_BUD(DEP%AL(JP),NP%AL(JP)%NSIZE_P)
    ENDDO
    ! 
  ENDIF
  !
ELSE
  !
  CALL ALLOC_EVAP_BUD(DE,0,0)
  DO JP=1,IO%NPATCH
    CALL ALLOC_EVAP_BUD(DEP%AL(JP),0,0)
  ENDDO
  !
ENDIF
!
IF (.NOT.YDE%LSURF_EVAP_BUDGET .OR. .NOT.DE%LWATER_BUDGET) THEN
  !
  ALLOCATE(DE%XRAINFALL  (0))
  ALLOCATE(DE%XSNOWFALL  (0))
  !
  CALL ALLOC_WATER_BUD(DE,0)
  DO JP=1,IO%NPATCH
    CALL ALLOC_WATER_BUD(DEP%AL(JP),0)
  ENDDO
  !
ENDIF
!
IF (.NOT.YDE%LSURF_EVAP_BUDGET .OR. ISIZE_LMEB_PATCH<=0) THEN
  !
  CALL ALLOC_MEB_BUD(DE,0)
  DO JP=1,IO%NPATCH
    CALL ALLOC_MEB_BUD(DEP%AL(JP),0)
  ENDDO
  ! 
END IF
!
IF(.NOT.YDE%LSURF_EVAP_BUDGET .OR. .NOT.IO%LGLACIER)THEN
  ALLOCATE(DE%XICEFLUX(0))
  DO JP=1,IO%NPATCH
    ALLOCATE(DEP%AL(JP)%XICEFLUX(0))
  ENDDO
ENDIF
!
!////////////////CUMULATED DIAGNOSTICS//////////////////////////////
!
!* surface cumulated energy budget
!
#ifdef SFX_OL
GCUMUL = (DGO%LSURF_BUDGETC .OR. (LRESTART .AND. .NOT.DGO%LRESET_BUDGETC))
#else
GCUMUL = (DGO%LSURF_BUDGETC .OR. .NOT.DGO%LRESET_BUDGETC)
#endif
!
IF ( GCUMUL ) THEN
  !
  !///////////////////////ALLOCATIONS//////////////////////
  !
  CALL ALLOC_EVAP_BUD(DEC,KLU,0)
  DO JP=1,IO%NPATCH
    CALL ALLOC_EVAP_BUD(DEPC%AL(JP),NP%AL(JP)%NSIZE_P,0)
  ENDDO
    !
  IF (ISIZE_LMEB_PATCH>0) THEN
    !
    CALL ALLOC_MEB_BUD(DEC,KLU)
    DO JP=1,IO%NPATCH
      CALL ALLOC_MEB_BUD(DEPC%AL(JP),NP%AL(JP)%NSIZE_P)
    ENDDO
    !
  ENDIF
  !
  CALL ALLOC_SURF_BUD(DC,0,KLU,0)
  ALLOCATE(DC%XEVAP(KLU))
  ALLOCATE(DC%XSUBL(KLU))
  DC%XEVAP    = XUNDEF
  DC%XSUBL    = XUNDEF  
  DO JP=1,IO%NPATCH
    CALL ALLOC_SURF_BUD(DPC%AL(JP),0,NP%AL(JP)%NSIZE_P,0)
    ALLOCATE(DPC%AL(JP)%XEVAP(NP%AL(JP)%NSIZE_P))
    ALLOCATE(DPC%AL(JP)%XSUBL(NP%AL(JP)%NSIZE_P))  
    DPC%AL(JP)%XEVAP = XUNDEF
    DPC%AL(JP)%XSUBL = XUNDEF 
  ENDDO
  !
  IF(IO%LGLACIER)THEN
    ALLOCATE(DEC%XICEFLUX(KLU))
    DO JP=1,IO%NPATCH
      ALLOCATE(DEPC%AL(JP)%XICEFLUX(NP%AL(JP)%NSIZE_P))
    ENDDO
  ENDIF
  !
#ifdef SFX_OL
  IF(DE%LWATER_BUDGET .OR. (LRESTART .AND. .NOT.DGO%LRESET_BUDGETC))THEN
#else
  IF(DE%LWATER_BUDGET .OR. .NOT.DGO%LRESET_BUDGETC)THEN
#endif          
    !      
    ALLOCATE(DEC%XRAINFALL  (KLU))
    ALLOCATE(DEC%XSNOWFALL  (KLU))
    !
    CALL ALLOC_WATER_BUD(DEC,KLU)
    DO JP=1,IO%NPATCH
      CALL ALLOC_WATER_BUD(DEPC%AL(JP),NP%AL(JP)%NSIZE_P)
    ENDDO
    !     
  ENDIF
  !
  !/////////////////INITIALISATIONS//////////////////////////
  !
  CALL INIT_EVAP_BUD(DEC)
  !
  IF (ISIZE_LMEB_PATCH>0) THEN
    !
    CALL INIT_MEB_BUD(DEC)
    !
  ENDIF
  !
  CALL INIT_SURF_BUD(DC,0.)
  DC%XEVAP = 0.
  DC%XSUBL = 0.
  !
  IF(IO%LGLACIER) DEC%XICEFLUX = 0.0
  !
  IF (.NOT.OREAD_BUDGETC .OR. (OREAD_BUDGETC.AND.DGO%LRESET_BUDGETC)) THEN
    !
    DO JP=1,IO%NPATCH
      CALL INIT_EVAP_BUD(DEPC%AL(JP))
    ENDDO
    !
    IF (ISIZE_LMEB_PATCH>0) THEN
      !
      DO JP=1,IO%NPATCH
        CALL INIT_MEB_BUD(DEPC%AL(JP))
      ENDDO
      !
    ENDIF
    !
    DO JP=1,IO%NPATCH
      CALL INIT_SURF_BUD(DPC%AL(JP),0.)
      DPC%AL(JP)%XEVAP = 0.
      DPC%AL(JP)%XSUBL = 0.        
    ENDDO
    !
    IF(IO%LGLACIER)THEN
       DO JP=1,IO%NPATCH
         DEPC%AL(JP)%XICEFLUX     = 0.0
       ENDDO
    ENDIF
    !
#ifdef SFX_OL
    IF(DE%LWATER_BUDGET .OR. (LRESTART .AND. .NOT.DGO%LRESET_BUDGETC))THEN
#else
    IF(DE%LWATER_BUDGET .OR. .NOT.DGO%LRESET_BUDGETC)THEN
#endif      
      !
      CALL INIT_WATER_BUD(DEC)
      DO JP=1,IO%NPATCH
        CALL INIT_WATER_BUD(DEPC%AL(JP))
      ENDDO
      !
      DEC%XRAINFALL   = 0.0
      DEC%XSNOWFALL   = 0.0
      !
    ENDIF
    !     
  ELSE
    !
    CALL READ_SURF(HPROGRAM,'VERSION',IVERSION,IRESP)
    CALL READ_SURF(HPROGRAM,'BUG ',IBUG,IRESP)
    !
    GDIM = (IVERSION>8 .OR. IVERSION==8 .AND. IBUG>0)
    !
#ifdef SFX_OL
    IF(DE%LWATER_BUDGET .OR. (LRESTART .AND. .NOT.DGO%LRESET_BUDGETC))THEN
#else
    IF(DE%LWATER_BUDGET .OR. .NOT.DGO%LRESET_BUDGETC)THEN
#endif     
      IF(IVERSION>7 .OR. IVERSION==7 .AND. IBUG>=3)THEN 
        YREC='RAINFC_ISBA'
        CALL READ_SURF(HPROGRAM,YREC,DEC%XRAINFALL,IRESP)
        YREC='SNOWFC_ISBA'
        CALL READ_SURF(HPROGRAM,YREC,DEC%XSNOWFALL,IRESP)
      ELSE
        DEC%XRAINFALL = 0.0
        DEC%XSNOWFALL = 0.0
      ENDIF
    ENDIF
    !
    IF(DGO%LPATCH_BUDGET .AND. IO%NPATCH>1)THEN
      !
      !
      IF (GDIM) THEN
        YREC2=''
      ELSEIF (IVERSION<7 .OR. IVERSION==7 .AND. IBUG<3) THEN
        YREC2='PATCH'
      ELSE
        YREC2='P'
      ENDIF
      !
      ALLOCATE(ZWORK(KLU,IO%NPATCH))
      !
      !/////////////EVAP PATCH/////////////////////////////
      !
      YREC='LEGC_'//YREC2
      CALL MAKE_CHOICE_ARRAY(HPROGRAM, IO%NPATCH, GDIM, YREC, ZWORK)
      DO JP = 1,IO%NPATCH
        CALL PACK_SAME_RANK(NP%AL(JP)%NR_P,ZWORK(:,JP),DEPC%AL(JP)%XLEG(:))
      ENDDO
      !
      YREC='LEGIC_'//YREC2
      CALL MAKE_CHOICE_ARRAY(HPROGRAM, IO%NPATCH, GDIM, YREC, ZWORK)
      DO JP = 1,IO%NPATCH
        CALL PACK_SAME_RANK(NP%AL(JP)%NR_P,ZWORK(:,JP),DEPC%AL(JP)%XLEGI(:))
      ENDDO    
      !
      YREC='LEVC_'//YREC2
      CALL MAKE_CHOICE_ARRAY(HPROGRAM, IO%NPATCH, GDIM, YREC, ZWORK)
      DO JP = 1,IO%NPATCH
        CALL PACK_SAME_RANK(NP%AL(JP)%NR_P,ZWORK(:,JP),DEPC%AL(JP)%XLEV(:))
      ENDDO
  
      !
      YREC='LESC_'//YREC2
      CALL MAKE_CHOICE_ARRAY(HPROGRAM, IO%NPATCH, GDIM, YREC, ZWORK)
      DO JP = 1,IO%NPATCH
        CALL PACK_SAME_RANK(NP%AL(JP)%NR_P,ZWORK(:,JP),DEPC%AL(JP)%XLES(:))
      ENDDO
      !
      IF(HSNOW_SCHEME=='3-L' .OR. HSNOW_SCHEME=='CRO')THEN
         IF(IVERSION>7 .OR. IVERSION==7 .AND. IBUG>=3)THEN
           !
           YREC='LESLC_'//YREC2
           CALL MAKE_CHOICE_ARRAY(HPROGRAM, IO%NPATCH, GDIM, YREC, ZWORK)
           DO JP = 1,IO%NPATCH
             CALL PACK_SAME_RANK(NP%AL(JP)%NR_P,ZWORK(:,JP),DEPC%AL(JP)%XLESL(:))
           ENDDO
           !
         ELSE
           !
           DO JP=1,IO%NPATCH
             DEPC%AL(JP)%XLESL(:) = 0.0
           ENDDO
           !
         ENDIF
         !
         IF(IVERSION>=8)THEN
           !
           YREC='SNDRIFC_'//YREC2
           CALL MAKE_CHOICE_ARRAY(HPROGRAM, IO%NPATCH, GDIM, YREC, ZWORK)
           DO JP = 1,IO%NPATCH
             CALL PACK_SAME_RANK(NP%AL(JP)%NR_P,ZWORK(:,JP),DEPC%AL(JP)%XSNDRIFT(:))
           ENDDO
           !        
         ELSE
           !
           DO JP=1,IO%NPATCH
             DEPC%AL(JP)%XSNDRIFT(:) = 0.0
           ENDDO
           !         
         ENDIF  
         !    
      ELSE
        !
        DO JP=1,IO%NPATCH
          DEPC%AL(JP)%XLESL(:) = 0.0
          DEPC%AL(JP)%XSNDRIFT(:) = 0.0
        ENDDO
        !      
      ENDIF
      !
      YREC='LERC_'//YREC2
      CALL MAKE_CHOICE_ARRAY(HPROGRAM, IO%NPATCH, GDIM, YREC, ZWORK)
      DO JP = 1,IO%NPATCH
        CALL PACK_SAME_RANK(NP%AL(JP)%NR_P,ZWORK(:,JP),DEPC%AL(JP)%XLER(:))
      ENDDO
      !    
      YREC='LETRC_'//YREC2
      CALL MAKE_CHOICE_ARRAY(HPROGRAM, IO%NPATCH, GDIM, YREC, ZWORK)
      DO JP = 1,IO%NPATCH
        CALL PACK_SAME_RANK(NP%AL(JP)%NR_P,ZWORK(:,JP),DEPC%AL(JP)%XLETR(:))
      ENDDO 
      !    
      YREC='EVAPC_'//YREC2
      CALL MAKE_CHOICE_ARRAY(HPROGRAM, IO%NPATCH, GDIM, YREC, ZWORK)
      DO JP = 1,IO%NPATCH
        CALL PACK_SAME_RANK(NP%AL(JP)%NR_P,ZWORK(:,JP),DPC%AL(JP)%XEVAP(:))
      ENDDO
      !    
      IF (IVERSION<8)THEN
        DO JP=1,IO%NPATCH
          DPC%AL(JP)%XSUBL(:) = 0.0
        ENDDO           
      ELSE
        YREC='SUBLC_'//YREC2
        CALL MAKE_CHOICE_ARRAY(HPROGRAM, IO%NPATCH, GDIM, YREC, ZWORK)
        DO JP = 1,IO%NPATCH
          CALL PACK_SAME_RANK(NP%AL(JP)%NR_P,ZWORK(:,JP),DPC%AL(JP)%XSUBL(:))
        ENDDO      
      ENDIF   
      ! 
      YREC='DRAINC_'//YREC2
      CALL MAKE_CHOICE_ARRAY(HPROGRAM, IO%NPATCH, GDIM, YREC, ZWORK)
      DO JP = 1,IO%NPATCH
        CALL PACK_SAME_RANK(NP%AL(JP)%NR_P,ZWORK(:,JP),DEPC%AL(JP)%XDRAIN(:))
      ENDDO   
      !      
      YREC='RUNOFFC_'//YREC2
      CALL MAKE_CHOICE_ARRAY(HPROGRAM, IO%NPATCH, GDIM, YREC, ZWORK)
      DO JP = 1,IO%NPATCH
        CALL PACK_SAME_RANK(NP%AL(JP)%NR_P,ZWORK(:,JP),DEPC%AL(JP)%XRUNOFF(:))
      ENDDO   
      !      
      YREC='DRIVEGC_'//YREC2
      CALL MAKE_CHOICE_ARRAY(HPROGRAM, IO%NPATCH, GDIM, YREC, ZWORK)
      DO JP = 1,IO%NPATCH
        CALL PACK_SAME_RANK(NP%AL(JP)%NR_P,ZWORK(:,JP),DEPC%AL(JP)%XDRIP(:))
      ENDDO
      !      
      YREC='RRVEGC_'//YREC2
      CALL MAKE_CHOICE_ARRAY(HPROGRAM, IO%NPATCH, GDIM, YREC, ZWORK)
      DO JP = 1,IO%NPATCH
        CALL PACK_SAME_RANK(NP%AL(JP)%NR_P,ZWORK(:,JP),DEPC%AL(JP)%XRRVEG(:))
      ENDDO  
      !      
      YREC='SNOMLTC_'//YREC2
      CALL MAKE_CHOICE_ARRAY(HPROGRAM, IO%NPATCH, GDIM, YREC, ZWORK)
      DO JP = 1,IO%NPATCH
        CALL PACK_SAME_RANK(NP%AL(JP)%NR_P,ZWORK(:,JP),DEPC%AL(JP)%XMELT(:))
      ENDDO          
      !
      IF (LAGRIP) THEN
        YREC='IRRIGC_'//YREC2
        CALL MAKE_CHOICE_ARRAY(HPROGRAM, IO%NPATCH, GDIM, YREC, ZWORK)
        DO JP = 1,IO%NPATCH
          CALL PACK_SAME_RANK(NP%AL(JP)%NR_P,ZWORK(:,JP),DEPC%AL(JP)%XIRRIG_FLUX(:))
        ENDDO          
      ELSE
        DO JP=1,IO%NPATCH
          DEPC%AL(JP)%XIRRIG_FLUX(:) = 0.0
        ENDDO                 
      ENDIF
      !
      IF(IO%CPHOTO/='NON' .AND. (IVERSION>7 .OR. IVERSION==7 .AND. IBUG>=3))THEN
        YREC='GPPC_'//YREC2
        CALL MAKE_CHOICE_ARRAY(HPROGRAM, IO%NPATCH, GDIM, YREC, ZWORK)
        DO JP = 1,IO%NPATCH
          CALL PACK_SAME_RANK(NP%AL(JP)%NR_P,ZWORK(:,JP),DEPC%AL(JP)%XGPP(:))
        ENDDO 
        !        
        YREC='RC_AUTO_'//YREC2
        CALL MAKE_CHOICE_ARRAY(HPROGRAM, IO%NPATCH, GDIM, YREC, ZWORK)
        DO JP = 1,IO%NPATCH
          CALL PACK_SAME_RANK(NP%AL(JP)%NR_P,ZWORK(:,JP),DEPC%AL(JP)%XRESP_AUTO(:))
        ENDDO
        !        
        YREC='RC_ECO_'//YREC2
        CALL MAKE_CHOICE_ARRAY(HPROGRAM, IO%NPATCH, GDIM, YREC, ZWORK)
        DO JP = 1,IO%NPATCH
          CALL PACK_SAME_RANK(NP%AL(JP)%NR_P,ZWORK(:,JP),DEPC%AL(JP)%XRESP_ECO(:))
        ENDDO         
      ELSE
        DO JP=1,IO%NPATCH
          DEPC%AL(JP)%XGPP(:) = 0.0
          DEPC%AL(JP)%XRESP_AUTO(:) = 0.0
          DEPC%AL(JP)%XRESP_ECO(:) = 0.0
        ENDDO                
      ENDIF      
      !
      IF((IO%CRUNOFF=='SGH'.AND.IO%CISBA=='DIF').AND.IVERSION>=8)THEN
        YREC='QSBC_'//YREC2
        CALL MAKE_CHOICE_ARRAY(HPROGRAM, IO%NPATCH, GDIM, YREC, ZWORK)
        DO JP = 1,IO%NPATCH
          CALL PACK_SAME_RANK(NP%AL(JP)%NR_P,ZWORK(:,JP),DEPC%AL(JP)%XQSB(:))
        ENDDO
      ELSE
        DE%XQSB = 0.0
      ENDIF
      !
      IF(IO%CHORT=='SGH'.OR.IO%CISBA=='DIF')THEN
        YREC='HORTONC_'//YREC2
        CALL MAKE_CHOICE_ARRAY(HPROGRAM, IO%NPATCH, GDIM, YREC, ZWORK)
        DO JP = 1,IO%NPATCH
          CALL PACK_SAME_RANK(NP%AL(JP)%NR_P,ZWORK(:,JP),DEPC%AL(JP)%XHORT(:))
        ENDDO          
      ELSE
        DO JP=1,IO%NPATCH
          DEPC%AL(JP)%XHORT(:) = 0.0
        ENDDO               
      ENDIF
      !
      IF(IO%LFLOOD)THEN
        YREC='IFLOODC_'//YREC2
        CALL MAKE_CHOICE_ARRAY(HPROGRAM, IO%NPATCH, GDIM, YREC, ZWORK)
        DO JP = 1,IO%NPATCH
          CALL PACK_SAME_RANK(NP%AL(JP)%NR_P,ZWORK(:,JP),DEPC%AL(JP)%XIFLOOD(:))
        ENDDO 
        !        
        YREC='PFLOODC_'//YREC2
        CALL MAKE_CHOICE_ARRAY(HPROGRAM, IO%NPATCH, GDIM, YREC, ZWORK)
        DO JP = 1,IO%NPATCH
          CALL PACK_SAME_RANK(NP%AL(JP)%NR_P,ZWORK(:,JP),DEPC%AL(JP)%XPFLOOD(:))
        ENDDO      
        !        
        YREC='LEFC_'//YREC2
        CALL MAKE_CHOICE_ARRAY(HPROGRAM, IO%NPATCH, GDIM, YREC, ZWORK)
        DO JP = 1,IO%NPATCH
          CALL PACK_SAME_RANK(NP%AL(JP)%NR_P,ZWORK(:,JP),DEPC%AL(JP)%XLE_FLOOD(:))
        ENDDO  
        !        
        YREC='LEIFC_'//YREC2
        CALL MAKE_CHOICE_ARRAY(HPROGRAM, IO%NPATCH, GDIM, YREC, ZWORK)
        DO JP = 1,IO%NPATCH
          CALL PACK_SAME_RANK(NP%AL(JP)%NR_P,ZWORK(:,JP),DEPC%AL(JP)%XLEI_FLOOD(:))
        ENDDO         
      ELSE
        DO JP=1,IO%NPATCH
          DEPC%AL(JP)%XIFLOOD(:) = 0.0
          DEPC%AL(JP)%XPFLOOD(:) = 0.0
          DEPC%AL(JP)%XLE_FLOOD(:) = 0.0
          DEPC%AL(JP)%XLEI_FLOOD(:) = 0.0
        ENDDO                
      ENDIF      
      ! 
      !       
      IF (ISIZE_LMEB_PATCH>0) THEN
        !
        YREC='LEVCVC_'//YREC2
        CALL MAKE_CHOICE_ARRAY(HPROGRAM, IO%NPATCH, GDIM, YREC, ZWORK)
        DO JP = 1,IO%NPATCH
          CALL PACK_SAME_RANK(NP%AL(JP)%NR_P,ZWORK(:,JP),DEPC%AL(JP)%XLEVCV(:))
        ENDDO
        !        
        YREC='LESCC_'//YREC2
        CALL MAKE_CHOICE_ARRAY(HPROGRAM, IO%NPATCH, GDIM, YREC, ZWORK)
        DO JP = 1,IO%NPATCH
          CALL PACK_SAME_RANK(NP%AL(JP)%NR_P,ZWORK(:,JP),DEPC%AL(JP)%XLESC(:))
        ENDDO   
        !       
        YREC='LETRCVC_'//YREC2
        CALL MAKE_CHOICE_ARRAY(HPROGRAM, IO%NPATCH, GDIM, YREC, ZWORK)
        DO JP = 1,IO%NPATCH
          CALL PACK_SAME_RANK(NP%AL(JP)%NR_P,ZWORK(:,JP),DEPC%AL(JP)%XLETRCV(:))
        ENDDO   
        !       
        YREC='LERCVC_'//YREC2
        CALL MAKE_CHOICE_ARRAY(HPROGRAM, IO%NPATCH, GDIM, YREC, ZWORK)
        DO JP = 1,IO%NPATCH
          CALL PACK_SAME_RANK(NP%AL(JP)%NR_P,ZWORK(:,JP),DEPC%AL(JP)%XLERCV(:))
        ENDDO
        !        
        YREC='LE_C_AC_'//YREC2
        CALL MAKE_CHOICE_ARRAY(HPROGRAM, IO%NPATCH, GDIM, YREC, ZWORK)
        DO JP = 1,IO%NPATCH
          CALL PACK_SAME_RANK(NP%AL(JP)%NR_P,ZWORK(:,JP),DEPC%AL(JP)%XLE_C_A(:))
        ENDDO   
        !       
        YREC='LE_V_CC_'//YREC2
        CALL MAKE_CHOICE_ARRAY(HPROGRAM, IO%NPATCH, GDIM, YREC, ZWORK)
        DO JP = 1,IO%NPATCH
          CALL PACK_SAME_RANK(NP%AL(JP)%NR_P,ZWORK(:,JP),DEPC%AL(JP)%XLE_V_C(:))
        ENDDO
        !        
        YREC='LE_G_CC_'//YREC2
        CALL MAKE_CHOICE_ARRAY(HPROGRAM, IO%NPATCH, GDIM, YREC, ZWORK)
        DO JP = 1,IO%NPATCH
          CALL PACK_SAME_RANK(NP%AL(JP)%NR_P,ZWORK(:,JP),DEPC%AL(JP)%XLE_G_C(:))
        ENDDO 
        !       
        YREC='LE_N_CC_'//YREC2
        CALL MAKE_CHOICE_ARRAY(HPROGRAM, IO%NPATCH, GDIM, YREC, ZWORK)
        DO JP = 1,IO%NPATCH
          CALL PACK_SAME_RANK(NP%AL(JP)%NR_P,ZWORK(:,JP),DEPC%AL(JP)%XLE_N_C(:))
        ENDDO          
        !
        YREC='SWNT_VC_'//YREC2
        CALL MAKE_CHOICE_ARRAY(HPROGRAM, IO%NPATCH, GDIM, YREC, ZWORK)
        DO JP = 1,IO%NPATCH
          CALL PACK_SAME_RANK(NP%AL(JP)%NR_P,ZWORK(:,JP),DEPC%AL(JP)%XSWNET_V(:))
        ENDDO  
        !        
        YREC='SWNT_GC_'//YREC2
        CALL MAKE_CHOICE_ARRAY(HPROGRAM, IO%NPATCH, GDIM, YREC, ZWORK)
        DO JP = 1,IO%NPATCH
          CALL PACK_SAME_RANK(NP%AL(JP)%NR_P,ZWORK(:,JP),DEPC%AL(JP)%XSWNET_G(:))
        ENDDO
        !        
        YREC='SWNT_NC_'//YREC2
        CALL MAKE_CHOICE_ARRAY(HPROGRAM, IO%NPATCH, GDIM, YREC, ZWORK)
        DO JP = 1,IO%NPATCH
          CALL PACK_SAME_RANK(NP%AL(JP)%NR_P,ZWORK(:,JP),DEPC%AL(JP)%XSWNET_N(:))
        ENDDO
        !        
        YREC='SWNT_NSC_'//YREC2
        CALL MAKE_CHOICE_ARRAY(HPROGRAM, IO%NPATCH, GDIM, YREC, ZWORK)
        DO JP = 1,IO%NPATCH
          CALL PACK_SAME_RANK(NP%AL(JP)%NR_P,ZWORK(:,JP),DEPC%AL(JP)%XSWNET_NS(:))
        ENDDO 
        !        
        YREC='LWNT_VC_'//YREC2
        CALL MAKE_CHOICE_ARRAY(HPROGRAM, IO%NPATCH, GDIM, YREC, ZWORK)
        DO JP = 1,IO%NPATCH
          CALL PACK_SAME_RANK(NP%AL(JP)%NR_P,ZWORK(:,JP),DEPC%AL(JP)%XLWNET_V(:))
        ENDDO 
        !        
        YREC='LWNT_GC_'//YREC2
        CALL MAKE_CHOICE_ARRAY(HPROGRAM, IO%NPATCH, GDIM, YREC, ZWORK)
        DO JP = 1,IO%NPATCH
          CALL PACK_SAME_RANK(NP%AL(JP)%NR_P,ZWORK(:,JP),DEPC%AL(JP)%XLWNET_G(:))
        ENDDO
        !        
        YREC='LWNT_NC_'//YREC2
        CALL MAKE_CHOICE_ARRAY(HPROGRAM, IO%NPATCH, GDIM, YREC, ZWORK)
        DO JP = 1,IO%NPATCH
          CALL PACK_SAME_RANK(NP%AL(JP)%NR_P,ZWORK(:,JP),DEPC%AL(JP)%XLWNET_N(:))
        ENDDO 
        !        
        YREC='SWDN_GNC_'//YREC2
        CALL MAKE_CHOICE_ARRAY(HPROGRAM, IO%NPATCH, GDIM, YREC, ZWORK)
        DO JP = 1,IO%NPATCH
          CALL PACK_SAME_RANK(NP%AL(JP)%NR_P,ZWORK(:,JP),DEPC%AL(JP)%XSWDOWN_GN(:))
        ENDDO  
        !        
        YREC='LWDN_GNC_'//YREC2
        CALL MAKE_CHOICE_ARRAY(HPROGRAM, IO%NPATCH, GDIM, YREC, ZWORK)
        DO JP = 1,IO%NPATCH
          CALL PACK_SAME_RANK(NP%AL(JP)%NR_P,ZWORK(:,JP),DEPC%AL(JP)%XLWDOWN_GN(:))
        ENDDO 
        !       
        YREC='H_V_CC_'//YREC2
        CALL MAKE_CHOICE_ARRAY(HPROGRAM, IO%NPATCH, GDIM, YREC, ZWORK)
        DO JP = 1,IO%NPATCH
          CALL PACK_SAME_RANK(NP%AL(JP)%NR_P,ZWORK(:,JP),DEPC%AL(JP)%XH_V_C(:))
        ENDDO 
        !        
        YREC='H_G_CC_'//YREC2
        CALL MAKE_CHOICE_ARRAY(HPROGRAM, IO%NPATCH, GDIM, YREC, ZWORK)
        DO JP = 1,IO%NPATCH
          CALL PACK_SAME_RANK(NP%AL(JP)%NR_P,ZWORK(:,JP),DEPC%AL(JP)%XH_G_C(:))
        ENDDO  
        !        
        YREC='H_C_AC_'//YREC2
        CALL MAKE_CHOICE_ARRAY(HPROGRAM, IO%NPATCH, GDIM, YREC, ZWORK)
        DO JP = 1,IO%NPATCH
          CALL PACK_SAME_RANK(NP%AL(JP)%NR_P,ZWORK(:,JP),DEPC%AL(JP)%XH_C_A(:))
        ENDDO       
        !      
        YREC='H_N_CC_'//YREC2
        CALL MAKE_CHOICE_ARRAY(HPROGRAM, IO%NPATCH, GDIM, YREC, ZWORK)
        DO JP = 1,IO%NPATCH
          CALL PACK_SAME_RANK(NP%AL(JP)%NR_P,ZWORK(:,JP),DEPC%AL(JP)%XH_N_C(:))
        ENDDO  
        !       
        YREC='SR_GNC_'//YREC2
        CALL MAKE_CHOICE_ARRAY(HPROGRAM, IO%NPATCH, GDIM, YREC, ZWORK)
        DO JP = 1,IO%NPATCH
          CALL PACK_SAME_RANK(NP%AL(JP)%NR_P,ZWORK(:,JP),DEPC%AL(JP)%XSR_GN(:))
        ENDDO   
        !       
        YREC='MELTCVC_'//YREC2
        CALL MAKE_CHOICE_ARRAY(HPROGRAM, IO%NPATCH, GDIM, YREC, ZWORK)
        DO JP = 1,IO%NPATCH
          CALL PACK_SAME_RANK(NP%AL(JP)%NR_P,ZWORK(:,JP),DEPC%AL(JP)%XMELTCV(:))
        ENDDO
        !        
        YREC='FRZCVC_'//YREC2
        CALL MAKE_CHOICE_ARRAY(HPROGRAM, IO%NPATCH, GDIM, YREC, ZWORK)
        DO JP = 1,IO%NPATCH
          CALL PACK_SAME_RANK(NP%AL(JP)%NR_P,ZWORK(:,JP),DEPC%AL(JP)%XFRZCV(:))
        ENDDO
        !        
      ENDIF
      !
      YREC='RNC_'//YREC2
      CALL MAKE_CHOICE_ARRAY(HPROGRAM, IO%NPATCH, GDIM, YREC, ZWORK)
      DO JP = 1,IO%NPATCH
        CALL PACK_SAME_RANK(NP%AL(JP)%NR_P,ZWORK(:,JP),DPC%AL(JP)%XRN(:))
      ENDDO
      !
      YREC='HC_'//YREC2
      CALL MAKE_CHOICE_ARRAY(HPROGRAM, IO%NPATCH, GDIM, YREC, ZWORK)
      DO JP = 1,IO%NPATCH
        CALL PACK_SAME_RANK(NP%AL(JP)%NR_P,ZWORK(:,JP),DPC%AL(JP)%XH(:))
      ENDDO  
      !      
      YREC='LEC_'//YREC2
      CALL MAKE_CHOICE_ARRAY(HPROGRAM, IO%NPATCH, GDIM, YREC, ZWORK)
      DO JP = 1,IO%NPATCH
        CALL PACK_SAME_RANK(NP%AL(JP)%NR_P,ZWORK(:,JP),DPC%AL(JP)%XLE(:))
      ENDDO   
      !       
      YREC='LEIC_'//YREC2
      CALL MAKE_CHOICE_ARRAY(HPROGRAM, IO%NPATCH, GDIM, YREC, ZWORK)
      DO JP = 1,IO%NPATCH
        CALL PACK_SAME_RANK(NP%AL(JP)%NR_P,ZWORK(:,JP),DPC%AL(JP)%XLEI(:))
      ENDDO 
      !       
      YREC='GFLUXC_'//YREC2
      CALL MAKE_CHOICE_ARRAY(HPROGRAM, IO%NPATCH, GDIM, YREC, ZWORK)
      DO JP = 1,IO%NPATCH
        CALL PACK_SAME_RANK(NP%AL(JP)%NR_P,ZWORK(:,JP),DPC%AL(JP)%XGFLUX(:))
      ENDDO         
      !      
      IF (DGO%LRAD_BUDGET) THEN
        !
        YREC='SWDC_'//YREC2
        CALL MAKE_CHOICE_ARRAY(HPROGRAM, IO%NPATCH, GDIM, YREC, ZWORK)
        DO JP = 1,IO%NPATCH
          CALL PACK_SAME_RANK(NP%AL(JP)%NR_P,ZWORK(:,JP),DPC%AL(JP)%XSWD(:))
        ENDDO
        !
        YREC='SWUC_'//YREC2
        CALL MAKE_CHOICE_ARRAY(HPROGRAM, IO%NPATCH, GDIM, YREC, ZWORK)
        DO JP = 1,IO%NPATCH
          CALL PACK_SAME_RANK(NP%AL(JP)%NR_P,ZWORK(:,JP),DPC%AL(JP)%XSWU(:))
        ENDDO 
        !        
        YREC='LWDC_'//YREC2
        CALL MAKE_CHOICE_ARRAY(HPROGRAM, IO%NPATCH, GDIM, YREC, ZWORK)
        DO JP = 1,IO%NPATCH
          CALL PACK_SAME_RANK(NP%AL(JP)%NR_P,ZWORK(:,JP),DPC%AL(JP)%XLWD(:))
        ENDDO 
        !        
        YREC='LWUC_'//YREC2
        CALL MAKE_CHOICE_ARRAY(HPROGRAM, IO%NPATCH, GDIM, YREC, ZWORK)
        DO JP = 1,IO%NPATCH
          CALL PACK_SAME_RANK(NP%AL(JP)%NR_P,ZWORK(:,JP),DPC%AL(JP)%XLWU(:))
        ENDDO
        !        
      ENDIF
      !
      YREC='FMUC_'//YREC2
      CALL MAKE_CHOICE_ARRAY(HPROGRAM, IO%NPATCH, GDIM, YREC, ZWORK)
      DO JP = 1,IO%NPATCH
        CALL PACK_SAME_RANK(NP%AL(JP)%NR_P,ZWORK(:,JP),DPC%AL(JP)%XFMU(:))
      ENDDO
      !      
      YREC='FMVC_'//YREC2
      CALL MAKE_CHOICE_ARRAY(HPROGRAM, IO%NPATCH, GDIM, YREC, ZWORK)
      DO JP = 1,IO%NPATCH
        CALL PACK_SAME_RANK(NP%AL(JP)%NR_P,ZWORK(:,JP),DPC%AL(JP)%XFMV(:))
      ENDDO   
      !
      IF(IO%LGLACIER)THEN
        YREC='ICE_FC_'//YREC2 
        CALL MAKE_CHOICE_ARRAY(HPROGRAM, IO%NPATCH, GDIM, YREC, ZWORK)
        DO JP = 1,IO%NPATCH
          CALL PACK_SAME_RANK(NP%AL(JP)%NR_P,ZWORK(:,JP),DEPC%AL(JP)%XICEFLUX(:))
        ENDDO   
      ENDIF
      !
      ! 
#ifdef SFX_OL
      IF(DE%LWATER_BUDGET .OR. (LRESTART .AND. .NOT.DGO%LRESET_BUDGETC))THEN
#else
      IF(DE%LWATER_BUDGET .OR. .NOT.DGO%LRESET_BUDGETC)THEN
#endif       
        IF(IVERSION>7 .OR. IVERSION==7 .AND. IBUG>=3)THEN 
          !
          YREC='DWGC_'//YREC2
          CALL MAKE_CHOICE_ARRAY(HPROGRAM, IO%NPATCH, GDIM, YREC, ZWORK)
          DO JP = 1,IO%NPATCH
              CALL PACK_SAME_RANK(NP%AL(JP)%NR_P,ZWORK(:,JP),DEPC%AL(JP)%XDWG(:))
          ENDDO
          !        
          YREC='DWGIC_'//YREC2
          CALL MAKE_CHOICE_ARRAY(HPROGRAM, IO%NPATCH, GDIM, YREC, ZWORK)
          DO JP = 1,IO%NPATCH
              CALL PACK_SAME_RANK(NP%AL(JP)%NR_P,ZWORK(:,JP),DEPC%AL(JP)%XDWGI(:))
          ENDDO
          !        
          YREC='DWRC_'//YREC2
          CALL MAKE_CHOICE_ARRAY(HPROGRAM, IO%NPATCH, GDIM, YREC, ZWORK)
          DO JP = 1,IO%NPATCH
              CALL PACK_SAME_RANK(NP%AL(JP)%NR_P,ZWORK(:,JP),DEPC%AL(JP)%XDWR(:))
          ENDDO
          !        
          YREC='DSWEC_'//YREC2
          CALL MAKE_CHOICE_ARRAY(HPROGRAM, IO%NPATCH, GDIM, YREC, ZWORK)
          DO JP = 1,IO%NPATCH
              CALL PACK_SAME_RANK(NP%AL(JP)%NR_P,ZWORK(:,JP),DEPC%AL(JP)%XDSWE(:))
          ENDDO  
          !        
          YREC='WATBUDC_'//YREC2
          CALL MAKE_CHOICE_ARRAY(HPROGRAM, IO%NPATCH, GDIM, YREC, ZWORK)
          DO JP = 1,IO%NPATCH
              CALL PACK_SAME_RANK(NP%AL(JP)%NR_P,ZWORK(:,JP),DEPC%AL(JP)%XWATBUD(:))
          ENDDO
          !        
         ELSE
          !
          DO JP=1,IO%NPATCH
              CALL INIT_WATER_BUD(DEPC%AL(JP))
          ENDDO        
          !       
        ENDIF
        !
        DEALLOCATE(ZWORK)
        !
      ELSE
        !
        DO JP=1,IO%NPATCH
          !
          CALL INIT_EVAP_BUD(DEPC%AL(JP))
          !
          IF (ISIZE_LMEB_PATCH>0) THEN
            CALL INIT_MEB_BUD(DEPC%AL(JP))
          ENDIF
          !
          CALL INIT_SURF_BUD(DC,0.)
          DC%XEVAP = 0.
          DC%XSUBL = 0.
          !
        ENDDO
        !
        IF(IO%LGLACIER)THEN
          DO JP=1,IO%NPATCH
            DEPC%AL(JP)%XICEFLUX=0.0
          ENDDO      
        ENDIF
        !  
#ifdef SFX_OL
        IF(DE%LWATER_BUDGET .OR. (LRESTART .AND. .NOT.DGO%LRESET_BUDGETC))THEN
#else
        IF(DE%LWATER_BUDGET .OR. .NOT.DGO%LRESET_BUDGETC)THEN
#endif        
          !
          DO JP=1,IO%NPATCH
            CALL INIT_WATER_BUD(DEPC%AL(JP))
          ENDDO
          !
        ENDIF
        !
      ENDIF
      !
    ENDIF
    !
  ENDIF
  !
ELSE
  !
  CALL ALLOC_SURF_BUD(DC,0,0,0)
  ALLOCATE(DC%XEVAP(0))
  ALLOCATE(DC%XSUBL(0))  
  !
  CALL ALLOC_EVAP_BUD(DEC,0,0)
  !
  DO JP=1,IO%NPATCH
    !
    CALL ALLOC_SURF_BUD(DPC%AL(JP),0,0,0)
    ALLOCATE(DPC%AL(JP)%XEVAP(0))
    ALLOCATE(DPC%AL(JP)%XSUBL(0))     
    !
    CALL ALLOC_EVAP_BUD(DEPC%AL(JP),0,0)
    !
  ENDDO
  !
ENDIF
!
#ifdef SFX_OL
IF(.NOT.GCUMUL .AND. (.NOT.DE%LWATER_BUDGET .OR. .NOT.LRESTART .OR. DGO%LRESET_BUDGETC))THEN
#else
IF(.NOT.GCUMUL .AND. (.NOT.DE%LWATER_BUDGET .OR. DGO%LRESET_BUDGETC))THEN
#endif
  !
  ALLOCATE(DEC%XRAINFALL  (0))
  ALLOCATE(DEC%XSNOWFALL  (0))
  ! 
  CALL ALLOC_WATER_BUD(DEC,0)
  DO JP=1,IO%NPATCH
    CALL ALLOC_WATER_BUD(DEPC%AL(JP),0)
  ENDDO
  !
ENDIF
!
IF (.NOT.GCUMUL .OR. ISIZE_LMEB_PATCH<=0) THEN
  !
  CALL ALLOC_MEB_BUD(DEC,0)  
  DO JP=1,IO%NPATCH
    CALL ALLOC_MEB_BUD(DEPC%AL(JP),0)
  ENDDO  
  !
ENDIF
!
IF(.NOT.IO%LGLACIER)THEN
  ALLOCATE(DEC%XICEFLUX(0))
  DO JP=1,IO%NPATCH
    ALLOCATE(DEPC%AL(JP)%XICEFLUX(0))
  ENDDO
ENDIF
!
!* miscellaneous surface fields
!
IF (YDMI%LSURF_MISC_BUDGET) THEN
  !
  CALL ALLOC_MISC_BUD(DMI,KLU,0,IO%NGROUND_LAYER,0)
  DO JP=1,IO%NPATCH
    CALL ALLOC_MISC_BUD(DMIP%AL(JP),NP%AL(JP)%NSIZE_P,&
                        NP%AL(JP)%NSIZE_P,IO%NGROUND_LAYER,KSNOW_NLAYER)
  ENDDO
  !
ELSE
  !
  CALL ALLOC_MISC_BUD(DMI,0,0,0,0)
  DO JP=1,IO%NPATCH
    CALL ALLOC_MISC_BUD(DMIP%AL(JP),0,0,0,0)
  ENDDO  
  !
END IF
!
!* Chemical fluxes
IF (CHI%SVI%NBEQ>0 .AND. CHI%LCH_BIO_FLUX) THEN
  ALLOCATE(GB%XFISO(KLU))
  ALLOCATE(GB%XFMONO(KLU))
  !
  GB%XFISO         = XUNDEF
  GB%XFMONO        = XUNDEF
ELSE
  ALLOCATE(GB%XFISO(0))
  ALLOCATE(GB%XFMONO(0))
ENDIF
!
IF (IO%CPHOTO/='NON') THEN
  DO JP = 1,IO%NPATCH
    ALLOCATE(NGB%AL(JP)%XIACAN(NP%AL(JP)%NSIZE_P,KABC))
    !
    NGB%AL(JP)%XIACAN        = XUNDEF
  ENDDO
  !
ELSE
  DO JP = 1,IO%NPATCH
    ALLOCATE(NGB%AL(JP)%XIACAN(0,0))
  ENDDO
ENDIF
!
IF (LHOOK) CALL DR_HOOK('DIAG_ISBA_INIT_N',1,ZHOOK_HANDLE)
!
CONTAINS
!
!
SUBROUTINE ALLOC_MISC_BUD(DMIA,KLUA,KLUAP,KNLAYER,KSNLAYER)
!
TYPE(DIAG_MISC_ISBA_t), INTENT(INOUT) :: DMIA
INTEGER, INTENT(IN) :: KLUA
INTEGER, INTENT(IN) :: KLUAP
INTEGER, INTENT(IN) :: KNLAYER
INTEGER, INTENT(IN) :: KSNLAYER
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
IF (LHOOK) CALL DR_HOOK('DIAG_ISBA_INIT_N:ALLOC_MISC_BUD',0,ZHOOK_HANDLE)
!
!////////////DIAG DEFINED BY PATCH AND AVERAGED//////////
!
ALLOCATE(DMIA%XHV           (KLUA))
!
ALLOCATE(DMIA%XSWI          (KLUA,KNLAYER))
ALLOCATE(DMIA%XTSWI         (KLUA,KNLAYER))
!
ALLOCATE(DMIA%XTWSNOW       (KLUA))
ALLOCATE(DMIA%XTDSNOW       (KLUA))
ALLOCATE(DMIA%XTTSNOW       (KLUA))
!
ALLOCATE(DMIA%XPSNG        (KLUA))
ALLOCATE(DMIA%XPSNV        (KLUA))
ALLOCATE(DMIA%XPSN         (KLUA))
!
ALLOCATE(DMIA%XFSAT        (KLUA)) 
!
ALLOCATE(DMIA%XFFG         (KLUA))
ALLOCATE(DMIA%XFFV         (KLUA))
ALLOCATE(DMIA%XFF          (KLUA))
!
IF (KLUA>0) THEN
  DMIA%XHV      = XUNDEF  
  DMIA%XSWI     = XUNDEF
  DMIA%XTSWI    = XUNDEF
  DMIA%XTWSNOW  = XUNDEF
  DMIA%XTDSNOW  = XUNDEF
  DMIA%XTTSNOW  = XUNDEF  
  DMIA%XPSNG    = XUNDEF
  DMIA%XPSNV    = XUNDEF
  DMIA%XPSN     = XUNDEF
  DMIA%XFSAT    = XUNDEF  
  DMIA%XFFG     = XUNDEF
  DMIA%XFFV     = XUNDEF
  DMIA%XFF      = XUNDEF
ENDIF
!
IF(IO%CISBA=='DIF')THEN
  ALLOCATE(DMIA%XALT(KLUA))
  ALLOCATE(DMIA%XFLT(KLUA))
  IF (KLUA>0) THEN
    DMIA%XALT     = XUNDEF
    DMIA%XFLT     = XUNDEF        
  ENDIF
ELSE
  ALLOCATE(DMIA%XALT(0))
  ALLOCATE(DMIA%XFLT(0))
ENDIF
!
!//////////////DIAG DEFINED ONLY BY PATCH//////////////
!
ALLOCATE(DMIA%XSNOWLIQ  (KLUAP,KSNLAYER))
ALLOCATE(DMIA%XSNOWTEMP (KLUAP,KSNLAYER))
ALLOCATE(DMIA%XSNOWDZ   (KLUAP,KSNLAYER))
!
IF (KLUAP>0) THEN
  DMIA%XSNOWLIQ = XUNDEF
  DMIA%XSNOWTEMP= XUNDEF
  DMIA%XSNOWDZ  = XUNDEF  
ENDIF
!
IF (LAGRIP) THEN
  ALLOCATE(DMIA%XSEUIL         (KLUAP))
  !
  IF (KLUAP>0) THEN
    DMIA%XSEUIL         = XUNDEF
  ENDIF
ELSE
  ALLOCATE(DMIA%XSEUIL(0))
ENDIF
!
IF (IO%LTR_ML) THEN
  ALLOCATE (DMIA%XFAPAR      (KLUAP))
  ALLOCATE (DMIA%XFAPIR      (KLUAP))
  ALLOCATE (DMIA%XFAPAR_BS   (KLUAP))
  ALLOCATE (DMIA%XFAPIR_BS   (KLUAP))
  ALLOCATE (DMIA%XDFAPARC    (KLUAP))
  ALLOCATE (DMIA%XDFAPIRC    (KLUAP))
  ALLOCATE (DMIA%XDLAI_EFFC  (KLUAP))
  !
  IF (KLUAP>0) THEN
    DMIA%XFAPAR      = XUNDEF
    DMIA%XFAPIR      = XUNDEF
    DMIA%XFAPAR_BS   = XUNDEF
    DMIA%XFAPIR_BS   = XUNDEF
    DMIA%XDFAPARC    = 0.
    DMIA%XDFAPIRC    = 0.
    DMIA%XDLAI_EFFC  = 0.
  ENDIF
ELSE
  ALLOCATE (DMIA%XFAPAR      (0))
  ALLOCATE (DMIA%XFAPIR      (0))
  ALLOCATE (DMIA%XFAPAR_BS   (0))
  ALLOCATE (DMIA%XFAPIR_BS   (0))
  ALLOCATE (DMIA%XDFAPARC    (0))
  ALLOCATE (DMIA%XDFAPIRC    (0))
  ALLOCATE (DMIA%XDLAI_EFFC  (0))
ENDIF
!
!
ALLOCATE(DMIA%XC1       (KLUAP))
ALLOCATE(DMIA%XC2       (KLUAP))
ALLOCATE(DMIA%XWGEQ     (KLUAP))
ALLOCATE(DMIA%XCG       (KLUAP))
ALLOCATE(DMIA%XCT       (KLUAP))
ALLOCATE(DMIA%XRS       (KLUAP))
ALLOCATE(DMIA%XGRNDFLUX (KLUAP))
ALLOCATE(DMIA%XSNOWHMASS(KLUAP))
ALLOCATE(DMIA%XSRSFC    (KLUAP))
ALLOCATE(DMIA%XRRSFC    (KLUAP))
ALLOCATE(DMIA%XRNSNOW   (KLUAP))
ALLOCATE(DMIA%XHSNOW    (KLUAP))
ALLOCATE(DMIA%XGFLUXSNOW(KLUAP))
ALLOCATE(DMIA%XHPSNOW   (KLUAP))
ALLOCATE(DMIA%XUSTARSNOW(KLUAP))
ALLOCATE(DMIA%XCDSNOW   (KLUAP))
ALLOCATE(DMIA%XCHSNOW   (KLUAP))
!
IF (KLUAP>0) THEN
  DMIA%XC1        = XUNDEF
  DMIA%XC2        = XUNDEF
  DMIA%XWGEQ      = XUNDEF
  DMIA%XCG        = XUNDEF
  DMIA%XCT        = XUNDEF
  DMIA%XRS        = XUNDEF
  DMIA%XGRNDFLUX  = XUNDEF
  DMIA%XSNOWHMASS = XUNDEF
  DMIA%XSRSFC     = XUNDEF
  DMIA%XRRSFC     = XUNDEF
  DMIA%XRNSNOW    = XUNDEF
  DMIA%XHSNOW     = XUNDEF
  DMIA%XGFLUXSNOW = XUNDEF
  DMIA%XHPSNOW    = XUNDEF
  DMIA%XUSTARSNOW = XUNDEF
  DMIA%XCDSNOW    = XUNDEF
  DMIA%XCHSNOW    = XUNDEF
ENDIF
!
!////////////DIAG DEFINED ONLY AVERAGED//////////////
!
ALLOCATE(DMIA%XLAI          (KLUA))
!
ALLOCATE(DMIA%XSOIL_SWI         (KLUA))
ALLOCATE(DMIA%XSOIL_TSWI        (KLUA))
ALLOCATE(DMIA%XSOIL_TWG         (KLUA))
ALLOCATE(DMIA%XSOIL_TWGI        (KLUA))
ALLOCATE(DMIA%XSOIL_WG          (KLUA))
ALLOCATE(DMIA%XSOIL_WGI         (KLUA))
!
IF (KLUA>0) THEN
  DMIA%XLAI     = XUNDEF        
  DMIA%XSOIL_TSWI   = XUNDEF
  DMIA%XSOIL_SWI    = XUNDEF
  DMIA%XSOIL_TWG    = XUNDEF
  DMIA%XSOIL_TWGI   = XUNDEF
  DMIA%XSOIL_WG     = XUNDEF
  DMIA%XSOIL_WGI    = XUNDEF   
ENDIF
!
IF(IO%CISBA=='DIF'.AND.DMI%LSURF_MISC_DIF)THEN
  ALLOCATE(DMIA%XFRD2_TSWI(KLUA))
  ALLOCATE(DMIA%XFRD2_TWG (KLUA))
  ALLOCATE(DMIA%XFRD2_TWGI(KLUA))
  ALLOCATE(DMIA%XFRD3_TSWI(KLUA))
  ALLOCATE(DMIA%XFRD3_TWG (KLUA))
  ALLOCATE(DMIA%XFRD3_TWGI(KLUA))
  !
  IF (KLUA>0) THEN  
    DMIA%XFRD2_TSWI = XUNDEF
    DMIA%XFRD2_TWG  = XUNDEF
    DMIA%XFRD2_TWGI = XUNDEF
    DMIA%XFRD3_TSWI = XUNDEF
    DMIA%XFRD3_TWG  = XUNDEF
    DMIA%XFRD3_TWGI = XUNDEF 
  ENDIF 
  !
ELSE
  ALLOCATE(DMIA%XFRD2_TSWI(0))
  ALLOCATE(DMIA%XFRD2_TWG (0))
  ALLOCATE(DMIA%XFRD2_TWGI(0))
  ALLOCATE(DMIA%XFRD3_TSWI(0))
  ALLOCATE(DMIA%XFRD3_TWG (0))
  ALLOCATE(DMIA%XFRD3_TWGI(0))          
ENDIF
!
IF (LHOOK) CALL DR_HOOK('DIAG_ISBA_INIT_N:ALLOC_MISC_BUD',1,ZHOOK_HANDLE)
!
END SUBROUTINE ALLOC_MISC_BUD
!
SUBROUTINE ALLOC_EVAP_BUD(DEA,KLUA,KLUAP)
!
TYPE(DIAG_EVAP_ISBA_t), INTENT(INOUT) :: DEA
INTEGER, INTENT(IN) :: KLUA
INTEGER, INTENT(IN) :: KLUAP
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
IF (LHOOK) CALL DR_HOOK('DIAG_ISBA_INIT_N:ALLOC_EVAP_BUD',0,ZHOOK_HANDLE)
!
ALLOCATE(DEA%XLEG       (KLUA))
ALLOCATE(DEA%XLEGI      (KLUA))
ALLOCATE(DEA%XLEV       (KLUA))
ALLOCATE(DEA%XLES       (KLUA))
!
ALLOCATE(DEA%XLESL      (KLUA))
ALLOCATE(DEA%XSNDRIFT   (KLUA))
!
ALLOCATE(DEA%XLER       (KLUA))
ALLOCATE(DEA%XLETR      (KLUA))
!
ALLOCATE(DEA%XDRAIN     (KLUA))
ALLOCATE(DEA%XRUNOFF    (KLUA))
ALLOCATE(DEA%XDRIP      (KLUA))
ALLOCATE(DEA%XRRVEG     (KLUA))
ALLOCATE(DEA%XMELT      (KLUA))
!
ALLOCATE(DEA%XIRRIG_FLUX(KLUA))
!
ALLOCATE(DEA%XGPP       (KLUA))
ALLOCATE(DEA%XRESP_AUTO (KLUA))
ALLOCATE(DEA%XRESP_ECO  (KLUA)) 
!
ALLOCATE(DEA%XQSB       (KLUA))
ALLOCATE(DEA%XHORT      (KLUA)) 
!
ALLOCATE(DEA%XIFLOOD   (KLUA))
ALLOCATE(DEA%XPFLOOD   (KLUA))
ALLOCATE(DEA%XLE_FLOOD (KLUA))
ALLOCATE(DEA%XLEI_FLOOD(KLUA))
!
ALLOCATE(DEA%XRN_SN_FR   (KLUAP))
ALLOCATE(DEA%XH_SN_FR    (KLUAP))
ALLOCATE(DEA%XLEI_SN_FR  (KLUAP))
ALLOCATE(DEA%XLE_SN_FR   (KLUAP))
ALLOCATE(DEA%XGFLUX_SN_FR(KLUAP))
ALLOCATE(DEA%XLEG_SN_FR  (KLUAP))
ALLOCATE(DEA%XLEGI_SN_FR (KLUAP))
ALLOCATE(DEA%XLEV_SN_FR  (KLUAP))
ALLOCATE(DEA%XLETR_SN_FR (KLUAP))
ALLOCATE(DEA%XUSTAR_SN_FR(KLUAP))
ALLOCATE(DEA%XLER_SN_FR  (KLUAP))
!
ALLOCATE(DEA%XMELTADV    (KLUAP))
ALLOCATE(DEA%XRESTORE    (KLUAP))
!
IF (KLUA>0) THEN
  DEA%XLEG        = XUNDEF
  DEA%XLEGI       = XUNDEF
  DEA%XLEV        = XUNDEF
  DEA%XLES        = XUNDEF
  !
  DEA%XLESL       = XUNDEF
  DEA%XSNDRIFT    = XUNDEF
  !  
  DEA%XLER        = XUNDEF
  DEA%XLETR       = XUNDEF
  !
  DEA%XDRAIN      = XUNDEF
  DEA%XRUNOFF     = XUNDEF
  DEA%XDRIP       = XUNDEF
  DEA%XRRVEG      = XUNDEF
  DEA%XMELT       = XUNDEF
  !  
  DEA%XIRRIG_FLUX = XUNDEF
  !
  DEA%XGPP        = XUNDEF
  DEA%XRESP_AUTO  = XUNDEF
  DEA%XRESP_ECO   = XUNDEF  
  !
  DEA%XQSB        = XUNDEF
  DEA%XHORT       = XUNDEF
  !  
  DEA%XIFLOOD    = XUNDEF
  DEA%XPFLOOD    = XUNDEF
  DEA%XLE_FLOOD  = XUNDEF
  DEA%XLEI_FLOOD = XUNDEF
  !
ENDIF
!
IF (KLUAP>0) THEN
  DEA%XRN_SN_FR    = XUNDEF
  DEA%XH_SN_FR     = XUNDEF
  DEA%XLEI_SN_FR   = XUNDEF
  DEA%XLE_SN_FR    = XUNDEF
  DEA%XGFLUX_SN_FR = XUNDEF
  DEA%XLEG_SN_FR   = XUNDEF
  DEA%XLEGI_SN_FR  = XUNDEF
  DEA%XLEV_SN_FR   = XUNDEF
  DEA%XLETR_SN_FR  = XUNDEF
  DEA%XUSTAR_SN_FR = XUNDEF
  DEA%XLER_SN_FR   = XUNDEF
  !
  DEA%XMELTADV     = XUNDEF  
  DEA%XRESTORE     = XUNDEF
ENDIF
!
IF (LHOOK) CALL DR_HOOK('DIAG_ISBA_INIT_N:ALLOC_EVAP_BUD',1,ZHOOK_HANDLE)
!
END SUBROUTINE ALLOC_EVAP_BUD
!
SUBROUTINE ALLOC_MEB_BUD(DEA,KLUA)
!
TYPE(DIAG_EVAP_ISBA_t), INTENT(INOUT) :: DEA
INTEGER, INTENT(IN) :: KLUA
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
IF (LHOOK) CALL DR_HOOK('DIAG_ISBA_INIT_N:ALLOC_MEB_BUD',0,ZHOOK_HANDLE)
!
ALLOCATE(DEA%XLEVCV  (KLUA))
ALLOCATE(DEA%XLESC   (KLUA))
ALLOCATE(DEA%XLETRGV (KLUA))
ALLOCATE(DEA%XLETRCV (KLUA))
ALLOCATE(DEA%XLERGV  (KLUA))
ALLOCATE(DEA%XLELITTER (KLUA))
ALLOCATE(DEA%XLELITTERI(KLUA))
ALLOCATE(DEA%XDRIPLIT  (KLUA))
ALLOCATE(DEA%XRRLIT  (KLUA))
ALLOCATE(DEA%XLERCV  (KLUA))
ALLOCATE(DEA%XLE_C_A (KLUA))
ALLOCATE(DEA%XLE_V_C (KLUA))
ALLOCATE(DEA%XLE_G_C (KLUA))
ALLOCATE(DEA%XLE_N_C (KLUA))
!
ALLOCATE(DEA%XSWNET_V    (KLUA))
ALLOCATE(DEA%XSWNET_G    (KLUA))
ALLOCATE(DEA%XSWNET_N    (KLUA))
ALLOCATE(DEA%XSWNET_NS   (KLUA))
ALLOCATE(DEA%XLWNET_V    (KLUA))
ALLOCATE(DEA%XLWNET_G    (KLUA))
ALLOCATE(DEA%XLWNET_N    (KLUA))
ALLOCATE(DEA%XSWDOWN_GN  (KLUA))
ALLOCATE(DEA%XLWDOWN_GN  (KLUA))
ALLOCATE(DEA%XH_V_C      (KLUA))
ALLOCATE(DEA%XH_G_C      (KLUA))
ALLOCATE(DEA%XH_C_A      (KLUA))
ALLOCATE(DEA%XH_N_C      (KLUA))
ALLOCATE(DEA%XSR_GN      (KLUA))
ALLOCATE(DEA%XMELTCV     (KLUA))
ALLOCATE(DEA%XFRZCV      (KLUA))
!
IF (KLUA>0) THEN
  DEA%XLEVCV         = XUNDEF
  DEA%XLESC          = XUNDEF
  DEA%XLETRGV        = XUNDEF
  DEA%XLETRCV        = XUNDEF
  DEA%XLERGV         = XUNDEF
  DEA%XLELITTER      = XUNDEF
  DEA%XLELITTERI     = XUNDEF
  DEA%XDRIPLIT       = XUNDEF
  DEA%XRRLIT         = XUNDEF
  DEA%XLERCV         = XUNDEF
  DEA%XLE_C_A        = XUNDEF
  DEA%XLE_V_C        = XUNDEF
  DEA%XLE_G_C        = XUNDEF
  DEA%XLE_N_C        = XUNDEF
  !
  DEA%XSWNET_V       = XUNDEF
  DEA%XSWNET_G       = XUNDEF
  DEA%XSWNET_N       = XUNDEF
  DEA%XSWNET_NS      = XUNDEF
  DEA%XLWNET_V       = XUNDEF
  DEA%XLWNET_G       = XUNDEF
  DEA%XLWNET_N       = XUNDEF
  DEA%XSWDOWN_GN     = XUNDEF
  DEA%XLWDOWN_GN     = XUNDEF
  DEA%XH_V_C         = XUNDEF
  DEA%XH_G_C         = XUNDEF
  DEA%XH_C_A         = XUNDEF
  DEA%XH_N_C         = XUNDEF
  DEA%XSR_GN         = XUNDEF
  DEA%XMELTCV        = XUNDEF
  DEA%XFRZCV         = XUNDEF
ENDIF
!
IF (LHOOK) CALL DR_HOOK('DIAG_ISBA_INIT_N:ALLOC_MEB_BUD',1,ZHOOK_HANDLE)
!
END SUBROUTINE ALLOC_MEB_BUD
!
SUBROUTINE ALLOC_WATER_BUD(DEA,KLUA)
!
TYPE(DIAG_EVAP_ISBA_t), INTENT(INOUT) :: DEA
INTEGER, INTENT(IN) :: KLUA
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
IF (LHOOK) CALL DR_HOOK('DIAG_ISBA_INIT_N:ALLOC_WATER_BUD',0,ZHOOK_HANDLE)
!
ALLOCATE(DEA%XDWG   (KLUA))
ALLOCATE(DEA%XDWGI  (KLUA))
ALLOCATE(DEA%XDWR   (KLUA))
ALLOCATE(DEA%XDSWE  (KLUA))
ALLOCATE(DEA%XWATBUD(KLUA))
!
IF (KLUA>0) THEN
  DEA%XDWG    = XUNDEF
  DEA%XDWGI   = XUNDEF
  DEA%XDWR    = XUNDEF
  DEA%XDSWE   = XUNDEF
  DEA%XWATBUD = XUNDEF
ENDIF
!
IF (LHOOK) CALL DR_HOOK('DIAG_ISBA_INIT_N:ALLOC_WATER_BUD',1,ZHOOK_HANDLE)
!
END SUBROUTINE ALLOC_WATER_BUD
!
!-------------------------------------------------------------------------------
!
END SUBROUTINE DIAG_ISBA_INIT_n
