!     #########
      SUBROUTINE DIAG_INIT_n (DG,DGC,DS,OREAD_BUDGETC,HPROGRAM,KLU,KSW,HTERM)
!     #####################
!
!!****  *DIAG_INIT_n* - routine to initialize SEAFLUX diagnostic variables
!!
!!    PURPOSE
!!    -------
!!
!!**  METHOD
!!    ------
!!
!!    EXTERNAL
!!    --------
!!
!!
!!    IMPLICIT ARGUMENTS
!!    ------------------
!!
!!    REFERENCE
!!    ---------
!!
!!
!!    AUTHOR
!!    ------
!!      V. Masson   *Meteo France*
!!
!!    MODIFICATIONS
!!    -------------
!!      Original    01/2004 
!!      Modified    01/2006 : sea flux parameterization.
!!      Modified    08/2009 : cumulative sea flux 
!!      B. decharme 04/2013 : Add EVAP and SUBL diag
!!      S.Senesi    01/2014 : introduce fractional seaice 
!-------------------------------------------------------------------------------
!
!*       0.    DECLARATIONS
!              ------------
!
USE MODD_DIAG_n, ONLY : DIAG_t, DIAG_OPTIONS_t
!
#ifdef SFX_OL
USE MODN_IO_OFFLINE,     ONLY : LRESTART
#endif
USE MODD_SURF_PAR,       ONLY : XUNDEF
!
USE MODI_READ_SURF
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE
!
!*       0.1   Declarations of arguments
!              -------------------------
!
TYPE(DIAG_t), INTENT(INOUT) :: DG
TYPE(DIAG_t), INTENT(INOUT) :: DGC
TYPE(DIAG_OPTIONS_t), INTENT(INOUT) :: DS
LOGICAL, INTENT(IN) :: OREAD_BUDGETC
!
INTEGER, INTENT(IN) :: KLU   ! size of arrays
INTEGER, INTENT(IN) :: KSW   ! number of SW spectral bands
 CHARACTER(LEN=6), INTENT(IN):: HPROGRAM  ! program calling
 CHARACTER(LEN=*), INTENT(IN) :: HTERM
!
!*       0.2   Declarations of local variables
!              -------------------------------
!
INTEGER           :: IVERSION
INTEGER           :: IRESP          ! IRESP  : return-code if a problem appears
CHARACTER(LEN=12) :: YREC           ! Name of the article to be read
!
REAL(KIND=JPRB)   :: ZHOOK_HANDLE
!
!-------------------------------------------------------------------------------
!
!* surface energy budget
!
IF (LHOOK) CALL DR_HOOK('DIAG_INIT_N',0,ZHOOK_HANDLE)
!
DG%XTS    = XUNDEF
DG%XTSRAD = XUNDEF
!
IF (DS%LSURF_BUDGET.OR.DS%LSURF_BUDGETC) THEN
  ALLOCATE(DG%XRN     (KLU))
  ALLOCATE(DG%XH      (KLU))
  ALLOCATE(DG%XLE     (KLU))
  ALLOCATE(DG%XLEI    (KLU))
  ALLOCATE(DG%XGFLUX  (KLU))
  ALLOCATE(DG%XEVAP   (KLU))
  ALLOCATE(DG%XSUBL   (KLU))
  ALLOCATE(DG%XSWD    (KLU))
  ALLOCATE(DG%XSWU    (KLU))
  ALLOCATE(DG%XLWD    (KLU))
  ALLOCATE(DG%XLWU    (KLU))
  ALLOCATE(DG%XSWBD   (KLU,KSW))
  ALLOCATE(DG%XSWBU   (KLU,KSW))
  ALLOCATE(DG%XFMU    (KLU))
  ALLOCATE(DG%XFMV    (KLU))
  ALLOCATE(DG%XALBT   (KLU))  
  !
  DG%XRN      = XUNDEF
  DG%XH       = XUNDEF
  DG%XLE      = XUNDEF
  DG%XLEI     = XUNDEF
  DG%XGFLUX   = XUNDEF
  DG%XEVAP    = XUNDEF
  DG%XSUBL    = XUNDEF  
  DG%XSWD     = XUNDEF
  DG%XSWU     = XUNDEF
  DG%XLWD     = XUNDEF
  DG%XLWU     = XUNDEF
  DG%XSWBD    = XUNDEF
  DG%XSWBU    = XUNDEF
  DG%XFMU     = XUNDEF
  DG%XFMV     = XUNDEF
  DG%XALBT    = XUNDEF  
  !
ELSE
  ALLOCATE(DG%XRN     (0))
  ALLOCATE(DG%XH      (0))
  ALLOCATE(DG%XLE     (0))
  ALLOCATE(DG%XLEI    (0))
  ALLOCATE(DG%XGFLUX  (0))
  ALLOCATE(DG%XEVAP   (0))
  ALLOCATE(DG%XSUBL   (0))  
  ALLOCATE(DG%XSWD    (0))
  ALLOCATE(DG%XSWU    (0))
  ALLOCATE(DG%XLWD    (0))
  ALLOCATE(DG%XLWU    (0))
  ALLOCATE(DG%XSWBD   (0,0))
  ALLOCATE(DG%XSWBU   (0,0))
  ALLOCATE(DG%XFMU    (0))
  ALLOCATE(DG%XFMV    (0))
  ALLOCATE(DG%XALBT   (0))  
ENDIF
!
!* cumulative surface energy budget
!
#ifdef SFX_OL
IF (DS%LSURF_BUDGETC .OR. (LRESTART .AND. .NOT.DS%LRESET_BUDGETC)) THEN
#else
IF (DS%LSURF_BUDGETC .OR. .NOT.DS%LRESET_BUDGETC) THEN
#endif
!        
  ALLOCATE(DGC%XRN   (KLU))
  ALLOCATE(DGC%XH    (KLU))
  ALLOCATE(DGC%XLE   (KLU))
  ALLOCATE(DGC%XLEI  (KLU))
  ALLOCATE(DGC%XGFLUX(KLU))
  ALLOCATE(DGC%XEVAP (KLU))
  ALLOCATE(DGC%XSUBL (KLU))  
  ALLOCATE(DGC%XSWD  (KLU))
  ALLOCATE(DGC%XSWU  (KLU))
  ALLOCATE(DGC%XLWD  (KLU))
  ALLOCATE(DGC%XLWU  (KLU))
  ALLOCATE(DGC%XFMU  (KLU))
  ALLOCATE(DGC%XFMV  (KLU))
!
  IF (.NOT. OREAD_BUDGETC) THEN        
     DGC%XRN   = 0.0
     DGC%XH    = 0.0
     DGC%XLE   = 0.0
     DGC%XLEI  = 0.0
     DGC%XGFLUX= 0.0
     DGC%XEVAP = 0.0
     DGC%XSUBL = 0.0
     DGC%XSWD  = 0.0
     DGC%XSWU  = 0.0
     DGC%XLWD  = 0.0
     DGC%XLWU  = 0.0
     DGC%XFMU  = 0.0
     DGC%XFMV  = 0.0
  ELSEIF (OREAD_BUDGETC.AND.DS%LRESET_BUDGETC) THEN
     DGC%XRN   = 0.0
     DGC%XH    = 0.0
     DGC%XLE   = 0.0
     DGC%XLEI  = 0.0
     DGC%XGFLUX= 0.0
     DGC%XEVAP = 0.0
     DGC%XSUBL = 0.0     
     DGC%XSWD  = 0.0
     DGC%XSWU  = 0.0
     DGC%XLWD  = 0.0
     DGC%XLWU  = 0.0
     DGC%XFMU  = 0.0
     DGC%XFMV  = 0.0
  ELSE
     CALL READ_SURF(HPROGRAM,'VERSION',IVERSION,IRESP)    
     YREC='RNC'//TRIM(HTERM)
     CALL READ_SURF(HPROGRAM,YREC,DGC%XRN,IRESP)
     YREC='HC'//TRIM(HTERM)
     CALL READ_SURF(HPROGRAM,YREC,DGC%XH,IRESP)
     YREC='LEC'//TRIM(HTERM)
     CALL READ_SURF(HPROGRAM,YREC,DGC%XLE,IRESP)
     YREC='LEIC'//TRIM(HTERM)
     CALL READ_SURF(HPROGRAM,YREC,DGC%XLEI,IRESP) 
     YREC='GFLUXC'//TRIM(HTERM)
     CALL READ_SURF(HPROGRAM,YREC,DGC%XGFLUX,IRESP)
     YREC='SWDC'//TRIM(HTERM)
     CALL READ_SURF(HPROGRAM,YREC,DGC%XSWD,IRESP)
     YREC='SWUC'//TRIM(HTERM)
     CALL READ_SURF(HPROGRAM,YREC,DGC%XSWU,IRESP)
     YREC='LWDC'//TRIM(HTERM)
     CALL READ_SURF(HPROGRAM,YREC,DGC%XLWD,IRESP)
     YREC='LWUC'//TRIM(HTERM)
     CALL READ_SURF(HPROGRAM,YREC,DGC%XLWU,IRESP)
     YREC='FMUC'//TRIM(HTERM)
     CALL READ_SURF(HPROGRAM,YREC,DGC%XFMU,IRESP)
     YREC='FMVC'//TRIM(HTERM)
     CALL READ_SURF(HPROGRAM,YREC,DGC%XFMV,IRESP)
     IF (IVERSION<8)THEN
        DGC%XEVAP     = 0.0
        DGC%XSUBL     = 0.0              
     ELSE
        !
        YREC='EVAPC'//TRIM(HTERM)
        CALL READ_SURF(HPROGRAM,YREC,DGC%XEVAP,IRESP)
        YREC='SUBLC'//TRIM(HTERM)
        CALL READ_SURF(HPROGRAM,YREC,DGC%XSUBL,IRESP)
     ENDIF
  ENDIF   
ELSE
  ALLOCATE(DGC%XRN   (0))
  ALLOCATE(DGC%XH    (0))
  ALLOCATE(DGC%XLE   (0))
  ALLOCATE(DGC%XLEI  (0))
  ALLOCATE(DGC%XEVAP (0))
  ALLOCATE(DGC%XSUBL (0))  
  ALLOCATE(DGC%XSWD  (0))
  ALLOCATE(DGC%XSWU  (0))
  ALLOCATE(DGC%XLWD  (0))
  ALLOCATE(DGC%XLWU  (0))
  ALLOCATE(DGC%XFMU  (0))
  ALLOCATE(DGC%XFMV  (0))
ENDIF
!
!* parameters at 2m
!
IF (DS%N2M>=1) THEN
  ALLOCATE(DG%XRI      (KLU))
  ALLOCATE(DG%XT2M     (KLU))
  ALLOCATE(DG%XT2M_MIN (KLU))
  ALLOCATE(DG%XT2M_MAX (KLU))
  ALLOCATE(DG%XQ2M     (KLU))
  ALLOCATE(DG%XHU2M    (KLU))
  ALLOCATE(DG%XHU2M_MIN(KLU))
  ALLOCATE(DG%XHU2M_MAX(KLU))
  ALLOCATE(DG%XZON10M  (KLU))
  ALLOCATE(DG%XMER10M  (KLU))
  ALLOCATE(DG%XWIND10M (KLU))
  ALLOCATE(DG%XWIND10M_MAX(KLU))
  !
  DG%XRI      = XUNDEF
  DG%XT2M     = XUNDEF
  DG%XT2M_MIN = XUNDEF
  DG%XT2M_MAX = 0.0
  DG%XQ2M     = XUNDEF
  DG%XHU2M    = XUNDEF
  DG%XHU2M_MIN= XUNDEF
  DG%XHU2M_MAX=-XUNDEF
  DG%XZON10M  = XUNDEF
  DG%XMER10M  = XUNDEF
  DG%XWIND10M = XUNDEF
  DG%XWIND10M_MAX = 0.0
ELSE
  ALLOCATE(DG%XRI      (0))
  ALLOCATE(DG%XT2M     (0))
  ALLOCATE(DG%XT2M_MIN (0))
  ALLOCATE(DG%XT2M_MAX (0))
  ALLOCATE(DG%XQ2M     (0))
  ALLOCATE(DG%XHU2M    (0))
  ALLOCATE(DG%XHU2M_MIN(0))
  ALLOCATE(DG%XHU2M_MAX(0))
  ALLOCATE(DG%XZON10M  (0))
  ALLOCATE(DG%XMER10M  (0))
  ALLOCATE(DG%XWIND10M (0))
  ALLOCATE(DG%XWIND10M_MAX(0))
END IF
!
!* transfer coefficients
!
IF (DS%LCOEF) THEN
  ALLOCATE(DG%XCD     (KLU))
  ALLOCATE(DG%XCH     (KLU))
  ALLOCATE(DG%XCE     (KLU))
  ALLOCATE(DG%XZ0     (KLU))
  ALLOCATE(DG%XZ0H    (KLU))
  !
  DG%XCD      = XUNDEF
  DG%XCH      = XUNDEF
  DG%XCE      = XUNDEF
  DG%XZ0      = XUNDEF
  DG%XZ0H     = XUNDEF
ELSE
  ALLOCATE(DG%XCD     (0))
  ALLOCATE(DG%XCH     (0))
  ALLOCATE(DG%XCE     (0))
  ALLOCATE(DG%XZ0     (0))
  ALLOCATE(DG%XZ0H    (0))
END IF
!
!
!* surface humidity
!
IF (DS%LSURF_VARS) THEN
  ALLOCATE(DG%XQS     (KLU))
  !
  DG%XQS      = XUNDEF
ELSE
  ALLOCATE(DG%XQS     (0))
END IF
!
IF (LHOOK) CALL DR_HOOK('DIAG_INIT_N',1,ZHOOK_HANDLE)
!
!-------------------------------------------------------------------------------
!
END SUBROUTINE DIAG_INIT_n
