!     #########
      SUBROUTINE FLAG_DIAG_UPDATE(OFRAC, ODIAG_GRID, K2M, OSURF_BUDGET, ORAD_BUDGET, OCOEF,  &
                                  OSURF_VARS, KBEQ, KDSTEQ, ODIAG_OCEAN, ODIAG_SEAICE,       &
                                  OWATER_PROFILE,                                            &
                                  OSURF_EVAP_BUDGET, OFLOOD,  OPGD_ISBA, OCH_NO_FLUX_ISBA,   &
                                  OSURF_MISC_BUDGET_ISBA, OPGD_TEB, OSURF_MISC_BUDGET_TEB    )
!     ############################################################
!
!!****  *FLAG_DIAG_UPDATE* - routine to modify selection of output fields
!!
!!    PURPOSE
!!    -------
!!
!!**  METHOD
!!    ------
!!
!!    EXTERNAL
!!    --------
!!
!!
!!    IMPLICIT ARGUMENTS
!!    ------------------
!!
!!    REFERENCE
!!    ---------
!!
!!
!!    AUTHOR
!!    ------
!!	P. Le Moigne   *Meteo France*	
!!
!!    MODIFICATIONS
!!    -------------
!!      Original    02/2008 
!
!       B.Decharme  10/2009 flag to desactivate writing of pgd 
!!      Modified    04/2013, P. Le Moigne: FLake chemistry
!!      Modified    01/2014, S. Senesi   : introduce sea-ice model
!-------------------------------------------------------------------------------
!
!*       0.    DECLARATIONS
!              ------------
!
USE MODD_DIAG_SURF_ATM_n, ONLY : DGU => DIAG_SURF_ATM
!
USE MODD_SURF_ATM_n, ONLY : U => SURF_ATM
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE
!
!*       0.1   Declarations of arguments
!              -------------------------
!
LOGICAL, INTENT(IN) :: OFRAC
LOGICAL, INTENT(IN) :: ODIAG_GRID
INTEGER, INTENT(IN) :: K2M
LOGICAL, INTENT(IN) :: OSURF_BUDGET
LOGICAL, INTENT(IN) :: ORAD_BUDGET
LOGICAL, INTENT(IN) :: OCOEF
LOGICAL, INTENT(IN) :: OSURF_VARS
!
INTEGER, INTENT(IN) :: KBEQ
INTEGER, INTENT(IN) :: KDSTEQ
!
LOGICAL, INTENT(IN) :: ODIAG_OCEAN
LOGICAL, INTENT(IN) :: ODIAG_SEAICE
LOGICAL, INTENT(IN) :: OWATER_PROFILE
LOGICAL, INTENT(IN) :: OSURF_EVAP_BUDGET
LOGICAL, INTENT(IN) :: OFLOOD
LOGICAL, INTENT(IN) :: OSURF_MISC_BUDGET_ISBA
LOGICAL, INTENT(IN) :: OCH_NO_FLUX_ISBA
LOGICAL, INTENT(IN) :: OPGD_ISBA
LOGICAL, INTENT(IN) :: OSURF_MISC_BUDGET_TEB
LOGICAL, INTENT(IN) :: OPGD_TEB
!
!*       0.2   Declarations of local variables
!              -------------------------------
!
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!-------------------------------------------------------------------------------
IF (LHOOK) CALL DR_HOOK('FLAG_DIAG_UPDATE',0,ZHOOK_HANDLE)
!
DGU%LFRAC = OFRAC
DGU%LDIAG_GRID = ODIAG_GRID
DGU%N2M = K2M
DGU%LSURF_BUDGET = OSURF_BUDGET
DGU%LRAD_BUDGET = ORAD_BUDGET
DGU%LCOEF = OCOEF
DGU%LSURF_VARS = OSURF_VARS
!
IF (.NOT.DGU%LRESET_BUDGETC) DGU%LSURF_BUDGETC = .TRUE.
!
IF (U%CSEA   =='SEAFLX') CALL FLAG_SEA_UPDATE(KBEQ, ODIAG_OCEAN, ODIAG_SEAICE, &
                                            DGU%LSURF_BUDGETC, K2M)
IF (U%CWATER =='FLAKE ') CALL FLAG_FLAKE_UPDATE(KBEQ, OWATER_PROFILE, DGU%LSURF_BUDGETC ,K2M)
IF (U%CWATER =='WATFLX') CALL FLAG_WATER_UPDATE(KBEQ, DGU%LSURF_BUDGETC ,K2M)
IF (U%CNATURE=='ISBA  ') CALL FLAG_ISBA_UPDATE(KBEQ, KDSTEQ, OSURF_EVAP_BUDGET, OFLOOD, &
                                OPGD_ISBA, OCH_NO_FLUX_ISBA, OSURF_MISC_BUDGET_ISBA,&
                                DGU%LSURF_BUDGETC, K2M)
IF (U%CTOWN  =='TEB   ') CALL FLAG_TEB_UPDATE(KBEQ, OPGD_TEB, OSURF_MISC_BUDGET_TEB, K2M)
!
IF (LHOOK) CALL DR_HOOK('FLAG_DIAG_UPDATE',1,ZHOOK_HANDLE)
!-------------------------------------------------------------------------------
CONTAINS
!
SUBROUTINE FLAG_SEA_UPDATE(KBEQ, ODIAG_OCEAN, ODIAG_SEAICE, OSURF_BUDGETC, K2M)
!
USE MODD_CH_SEAFLUX_n, ONLY : CHS => CH_SEAFLUX
USE MODD_DIAG_OCEAN_n, ONLY : DGO => DIAG_OCEAN
USE MODD_DIAG_SEAICE_n, ONLY : DGSI => DIAG_SEAICE
USE MODD_DIAG_SEAFLUX_n, ONLY : DGS => DIAG_SEAFLUX
!
IMPLICIT NONE
!
INTEGER, INTENT(IN) :: KBEQ
LOGICAL, INTENT(IN) :: ODIAG_OCEAN
LOGICAL, INTENT(IN) :: ODIAG_SEAICE
LOGICAL, INTENT(IN) :: OSURF_BUDGETC
INTEGER, INTENT(IN) :: K2M
!
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
IF (LHOOK) CALL DR_HOOK('FLAG_DIAG_UPDATE:FLAG_SEA_UPDATE',0,ZHOOK_HANDLE)
CHS%NBEQ = KBEQ
DGO%LDIAG_OCEAN = ODIAG_OCEAN
DGSI%LDIAG_SEAICE = ODIAG_SEAICE
DGS%LSURF_BUDGETC = OSURF_BUDGETC
DGS%N2M = K2M
IF (LHOOK) CALL DR_HOOK('FLAG_DIAG_UPDATE:FLAG_SEA_UPDATE',1,ZHOOK_HANDLE)
!
END SUBROUTINE FLAG_SEA_UPDATE
!
SUBROUTINE FLAG_WATER_UPDATE(KBEQ, OSURF_BUDGETC, K2M)
!
USE MODD_CH_WATFLUX_n, ONLY : CHW => CH_WATFLUX
USE MODD_DIAG_WATFLUX_n, ONLY : DGW => DIAG_WATFLUX
!
IMPLICIT NONE
!
INTEGER, INTENT(IN) :: KBEQ
LOGICAL, INTENT(IN) :: OSURF_BUDGETC
INTEGER, INTENT(IN) :: K2M
!
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
IF (LHOOK) CALL DR_HOOK('FLAG_DIAG_UPDATE:FLAG_WATER_UPDATE',0,ZHOOK_HANDLE)
CHW%NBEQ = KBEQ
DGW%LSURF_BUDGETC = OSURF_BUDGETC
DGW%N2M = K2M
IF (LHOOK) CALL DR_HOOK('FLAG_DIAG_UPDATE:FLAG_WATER_UPDATE',1,ZHOOK_HANDLE)
!
END SUBROUTINE FLAG_WATER_UPDATE
!
SUBROUTINE FLAG_FLAKE_UPDATE(KBEQ, OWATER_PROFILE, OSURF_BUDGETC, K2M)
!
USE MODD_CH_FLAKE_n, ONLY : CHF => CH_FLAKE
USE MODD_DIAG_MISC_FLAKE_n, ONLY : DGMF => DIAG_MISC_FLAKE
USE MODD_DIAG_FLAKE_n, ONLY : DGF => DIAG_FLAKE
!
IMPLICIT NONE
!
INTEGER, INTENT(IN) :: KBEQ
LOGICAL, INTENT(IN) :: OWATER_PROFILE
LOGICAL, INTENT(IN) :: OSURF_BUDGETC
INTEGER, INTENT(IN) :: K2M
!
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
IF (LHOOK) CALL DR_HOOK('FLAG_DIAG_UPDATE:FLAG_FLAKE_UPDATE',0,ZHOOK_HANDLE)
CHF%NBEQ = KBEQ
DGMF%LWATER_PROFILE = OWATER_PROFILE
DGF%LSURF_BUDGETC = OSURF_BUDGETC
DGF%N2M = K2M
IF (LHOOK) CALL DR_HOOK('FLAG_DIAG_UPDATE:FLAG_FLAKE_UPDATE',1,ZHOOK_HANDLE)
!
END SUBROUTINE FLAG_FLAKE_UPDATE
!
!
SUBROUTINE FLAG_ISBA_UPDATE(KBEQ, KDSTEQ, OSURF_EVAP_BUDGET, OFLOOD, &
                            OPGD, OCH_NO_FLUX, OSURF_MISC_BUDGET, &
                            OSURF_BUDGETC, K2M)
!
USE MODD_CH_ISBA_n, ONLY : CHI => CH_ISBA
USE MODD_DIAG_EVAP_ISBA_n, ONLY : DGEI => DIAG_EVAP_ISBA
USE MODD_DIAG_ISBA_n, ONLY : DGI => DIAG_ISBA
USE MODD_ISBA_n, ONLY : I => ISBA
USE MODD_DIAG_MISC_ISBA_n, ONLY : DGMI => DIAG_MISC_ISBA
!
IMPLICIT NONE
!
INTEGER, INTENT(IN) :: KBEQ
INTEGER, INTENT(IN) :: KDSTEQ
LOGICAL, INTENT(IN) :: OSURF_EVAP_BUDGET
LOGICAL, INTENT(IN) :: OFLOOD
LOGICAL, INTENT(IN) :: OPGD
LOGICAL, INTENT(IN) :: OCH_NO_FLUX
LOGICAL, INTENT(IN) :: OSURF_MISC_BUDGET
LOGICAL, INTENT(IN) :: OSURF_BUDGETC
INTEGER, INTENT(IN) :: K2M
!
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
IF (LHOOK) CALL DR_HOOK('FLAG_DIAG_UPDATE:FLAG_ISBA_UPDATE',0,ZHOOK_HANDLE)
CHI%NBEQ = KBEQ
CHI%NDSTEQ = KDSTEQ
DGEI%LSURF_EVAP_BUDGET = OSURF_EVAP_BUDGET
I%LFLOOD = OFLOOD
DGI%LPGD = OPGD
CHI%LCH_NO_FLUX = OCH_NO_FLUX
DGMI%LSURF_MISC_BUDGET = OSURF_MISC_BUDGET
DGEI%LSURF_BUDGETC = OSURF_BUDGETC
DGI%LPATCH_BUDGET = OSURF_BUDGETC
DGI%N2M = K2M
IF (LHOOK) CALL DR_HOOK('FLAG_DIAG_UPDATE:FLAG_ISBA_UPDATE',1,ZHOOK_HANDLE)
!
END SUBROUTINE FLAG_ISBA_UPDATE
!
SUBROUTINE FLAG_TEB_UPDATE(KBEQ, OPGD, OSURF_MISC_BUDGET, K2M)
!
USE MODD_CH_TEB_n, ONLY : CHT => CH_TEB
USE MODD_DIAG_TEB_n, ONLY : DGT => DIAG_TEB
USE MODD_DIAG_MISC_TEB_OPTION_n, ONLY : DGMTO => DIAG_MISC_TEB_OPTIONS
!
IMPLICIT NONE
!
INTEGER, INTENT(IN) :: KBEQ
LOGICAL, INTENT(IN) :: OPGD
LOGICAL, INTENT(IN) :: OSURF_MISC_BUDGET
INTEGER, INTENT(IN) :: K2M
!
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
IF (LHOOK) CALL DR_HOOK('FLAG_DIAG_UPDATE:FLAG_TEB_UPDATE',0,ZHOOK_HANDLE)
CHT%NBEQ = KBEQ
DGT%LPGD = OPGD
DGMTO%LSURF_MISC_BUDGET = OSURF_MISC_BUDGET
DGT%N2M = K2M
IF (LHOOK) CALL DR_HOOK('FLAG_DIAG_UPDATE:FLAG_TEB_UPDATE',1,ZHOOK_HANDLE)
!
END SUBROUTINE FLAG_TEB_UPDATE
!
END SUBROUTINE FLAG_DIAG_UPDATE

