!     #########
    SUBROUTINE FLAG_DIAG_TEB_GARDEN
!   ##########################################################################
!
USE MODD_TEB_n,           ONLY : XGARDEN
USE MODD_TEB_GARDEN_n
USE MODD_DIAG_TEB_GARDEN_n
USE MODD_AGRI_GARDEN_n
USE MODD_SURF_PAR,        ONLY : XUNDEF
!
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE
!
INTEGER :: JL
!
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
!-------------------------------------------------------------------------------
!
! Diagnostic variables:
!
IF (LHOOK) CALL DR_HOOK('FLAG_DIAG_TEB_GARDEN',0,ZHOOK_HANDLE)
WHERE (XGARDEN==0.) XRI = XUNDEF
WHERE (XGARDEN==0.) XCD = XUNDEF 
WHERE (XGARDEN==0.) XCH = XUNDEF 
WHERE (XGARDEN==0.) XRN = XUNDEF 
WHERE (XGARDEN==0.) XH  = XUNDEF 
WHERE (XGARDEN==0.) XGFLUX = XUNDEF
WHERE (XGARDEN==0.) XQS = XUNDEF 
!
WHERE (XGARDEN==0.) XLEI= XUNDEF 
WHERE (XGARDEN==0.) XLEG= XUNDEF 
WHERE (XGARDEN==0.) XLEGI = XUNDEF
WHERE (XGARDEN==0.) XLEV= XUNDEF 
WHERE (XGARDEN==0.) XLES= XUNDEF 
WHERE (XGARDEN==0.) XLER= XUNDEF 
WHERE (XGARDEN==0.) XLETR = XUNDEF
WHERE (XGARDEN==0.) XEVAP = XUNDEF
WHERE (XGARDEN==0.) XDRAIN = XUNDEF
WHERE (XGARDEN==0.) XRUNOFF = XUNDEF
WHERE (XGARDEN==0.) XHORT = XUNDEF
WHERE (XGARDEN==0.) XDRIP = XUNDEF
WHERE (XGARDEN==0.) XRRVEG = XUNDEF
WHERE (XGARDEN==0.) XMELT = XUNDEF

WHERE (XGARDEN==0.) XCG = XUNDEF 
WHERE (XGARDEN==0.) XC1 = XUNDEF 
WHERE (XGARDEN==0.) XC2 = XUNDEF 
WHERE (XGARDEN==0.) XWGEQ = XUNDEF
WHERE (XGARDEN==0.) XCT = XUNDEF 
WHERE (XGARDEN==0.) XRS = XUNDEF 
WHERE (XGARDEN==0.) XCDN= XUNDEF 
WHERE (XGARDEN==0.) XHU = XUNDEF 
WHERE (XGARDEN==0.) XHUG= XUNDEF 
WHERE (XGARDEN==0.) XRESTORE = XUNDEF
WHERE (XGARDEN==0.) XUSTAR = XUNDEF
DO JL=1,SIZE(XIACAN,2)
  WHERE (XGARDEN==0.) XIACAN(:,JL) = XUNDEF
END DO
!
DO JL=1,SIZE(XSNOWTEMP,2)
  WHERE (XGARDEN==0.) XSNOWTEMP(:,JL)   = XUNDEF
  WHERE (XGARDEN==0.) XSNOWLIQ (:,JL)   = XUNDEF
  WHERE (XGARDEN==0.) XSNOWDZ  (:,JL)   = XUNDEF
END DO
WHERE (XGARDEN==0.) XSNOWHMASS  = XUNDEF
WHERE (XGARDEN==0.) XMELTADV    = XUNDEF
!
WHERE (XGARDEN==0.) XHV      = XUNDEF
WHERE (XGARDEN==0.) XALBT    = XUNDEF
WHERE (XGARDEN==0.) XEMIST   = XUNDEF
WHERE (XGARDEN==0.) XSNOWFREE_ALB      = XUNDEF
WHERE (XGARDEN==0.) XSNOWFREE_ALB_VEG  = XUNDEF
WHERE (XGARDEN==0.) XSNOWFREE_ALB_SOIL = XUNDEF
IF (LHOOK) CALL DR_HOOK('FLAG_DIAG_TEB_GARDEN',1,ZHOOK_HANDLE)
!
!
END SUBROUTINE FLAG_DIAG_TEB_GARDEN
