MODULE MODI_GATHER_AND_WRITE_MPI_K4
!
INTERFACE GATHER_AND_WRITE_MPI_K4
!
SUBROUTINE GATHER_AND_WRITE_MPI_X1D0(PWORK,PWORK2,KMASK)
!
REAL, DIMENSION(:), INTENT(IN) :: PWORK
REAL, DIMENSION(:), INTENT(OUT) :: PWORK2
!
INTEGER, DIMENSION(:), INTENT(IN), OPTIONAL :: KMASK
!
END SUBROUTINE GATHER_AND_WRITE_MPI_X1D0
!
SUBROUTINE GATHER_AND_WRITE_MPI_X2D0(PWORK,PWORK2,KMASK)
!
REAL, DIMENSION(:,:), INTENT(IN) :: PWORK
REAL, DIMENSION(:,:), INTENT(OUT) :: PWORK2
!
INTEGER, DIMENSION(:), INTENT(IN), OPTIONAL :: KMASK
!
END SUBROUTINE GATHER_AND_WRITE_MPI_X2D0
!
END INTERFACE
!
END MODULE MODI_GATHER_AND_WRITE_MPI_K4
!
!**************************************************************************
!
SUBROUTINE GATHER_AND_WRITE_MPI_X1D0(PWORK,PWORK2,KMASK)
!
USE MODD_SURFEX_MPI, ONLY : NINDEX, NPROC, NRANK, NCOMM, NPIO, NSIZE, &
                            XTIME_COMM_WRITE, XTIME_CALC_WRITE, &
                            XTIME_OMP_BARR, IDX_W, WLOG_MPI
USE MODD_SURFEX_OMP, ONLY : NINDX1, NINDX2, XWORK
!
USE MODI_UNPACK_SAME_RANK
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE
!
#ifdef OL
INCLUDE "mpif.h"
#endif
!
REAL, DIMENSION(:), INTENT(IN) :: PWORK
REAL, DIMENSION(:), INTENT(OUT) :: PWORK2
!
INTEGER, DIMENSION(:), INTENT(IN), OPTIONAL :: KMASK
!
REAL, DIMENSION(NSIZE) :: ZINTER
DOUBLE PRECISION   :: XTIME0
!
INTEGER, DIMENSION(MPI_STATUS_SIZE) :: ISTATUS
INTEGER :: ICPT
INTEGER :: I,J
INTEGER :: INFOMPI
!
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
!
IF (LHOOK) CALL DR_HOOK('GATHER_AND_WRITE_MPI_X1D0',0,ZHOOK_HANDLE)
!
XWORK(NINDX1:NINDX2) = 0.
!
XTIME0 = MPI_WTIME()
!
IF (PRESENT(KMASK)) THEN
  CALL UNPACK_SAME_RANK(KMASK,PWORK,XWORK(NINDX1:NINDX2))
ELSE
  XWORK(NINDX1:NINDX2) = PWORK(:)
ENDIF
!
XTIME_CALC_WRITE = XTIME_CALC_WRITE + (MPI_WTIME() - XTIME0)
!
XTIME0 = MPI_WTIME()
!
!$OMP BARRIER
!
XTIME_OMP_BARR = XTIME_OMP_BARR + (MPI_WTIME() - XTIME0)
!
IF (NRANK/=NPIO) THEN
  !
!$OMP SINGLE
  ! 
  IDX_W = IDX_W + 1
  !
#ifdef OL
  XTIME0 = MPI_WTIME()
  CALL MPI_SEND(XWORK,SIZE(XWORK)*KIND(XWORK)/4,MPI_REAL,NPIO,IDX_W,NCOMM,INFOMPI)
  XTIME_COMM_WRITE = XTIME_COMM_WRITE + (MPI_WTIME() - XTIME0)
#endif
  !
!$OMP END SINGLE
  !
ELSE
  !
!$OMP SINGLE
  !  
  IDX_W = IDX_W + 1
  !
  DO I=1,NPROC
    !
#ifdef OL    
    XTIME0 = MPI_WTIME()
#endif    
    !
    IF (I<NPROC) THEN
#ifdef OL
      CALL MPI_RECV(ZINTER,SIZE(ZINTER)*KIND(ZINTER)/4,MPI_REAL,I,IDX_W,NCOMM,ISTATUS,INFOMPI)
#endif
    ELSE
      ZINTER(1:SIZE(XWORK)) = XWORK(:)
    ENDIF
    !
#ifdef OL    
    XTIME_COMM_WRITE = XTIME_COMM_WRITE + (MPI_WTIME() - XTIME0)
    !
    XTIME0 = MPI_WTIME()
#endif     
    !    
    ICPT = 0
    !
    DO J=1,SIZE(NINDEX)
      !
      IF ( NINDEX(J)==MOD(I,NPROC) ) THEN
        ICPT = ICPT + 1
        PWORK2(J) = ZINTER(ICPT)
      ENDIF
      !
    ENDDO
    !
#ifdef OL     
    XTIME_CALC_WRITE = XTIME_CALC_WRITE + (MPI_WTIME() - XTIME0)
#endif      
    !
  ENDDO
  !
!$OMP END SINGLE COPYPRIVATE(PWORK2)
  !
ENDIF
!
IF (LHOOK) CALL DR_HOOK('GATHER_AND_WRITE_MPI_X1D0',1,ZHOOK_HANDLE)
!
END SUBROUTINE GATHER_AND_WRITE_MPI_X1D0
!
!**************************************************************************
!
SUBROUTINE GATHER_AND_WRITE_MPI_X2D0(PWORK,PWORK2,KMASK)
!
USE MODD_SURFEX_MPI, ONLY : NINDEX, NPROC, NRANK, NCOMM, NPIO, NSIZE, &
                            XTIME_COMM_WRITE, XTIME_OMP_BARR,  &
                            XTIME_CALC_WRITE, IDX_W, WLOG_MPI
USE MODD_SURFEX_OMP, ONLY : NINDX1, NINDX2, XWORK2
!
USE MODI_UNPACK_SAME_RANK
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE
!
#ifdef OL
INCLUDE "mpif.h"
#endif
!
REAL, DIMENSION(:,:), INTENT(IN) :: PWORK
REAL, DIMENSION(:,:), INTENT(OUT) :: PWORK2
!
INTEGER, DIMENSION(:), INTENT(IN), OPTIONAL :: KMASK
!
REAL, DIMENSION(NSIZE,SIZE(PWORK,2)) :: ZINTER
DOUBLE PRECISION   :: XTIME0
!
INTEGER, DIMENSION(MPI_STATUS_SIZE) :: ISTATUS
INTEGER :: ICPT, IS2
INTEGER :: I,J
INTEGER :: INFOMPI
!
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
!
IF (LHOOK) CALL DR_HOOK('GATHER_AND_WRITE_MPI_X2D0',0,ZHOOK_HANDLE)
!
IS2 = SIZE(PWORK,2)
!
!$OMP SINGLE
!
IF (IS2>SIZE(XWORK2,2)) THEN
  DEALLOCATE(XWORK2)
  ALLOCATE(XWORK2(NSIZE,IS2))
ENDIF
!
!$OMP END SINGLE
!
XWORK2(NINDX1:NINDX2,1:IS2) = 0.
!
XTIME0 = MPI_WTIME()
!
IF (PRESENT(KMASK)) THEN
  CALL UNPACK_SAME_RANK(KMASK,PWORK,XWORK2(NINDX1:NINDX2,1:IS2))
ELSE
  XWORK2(NINDX1:NINDX2,1:IS2) = PWORK(:,:)
ENDIF
!
XTIME_CALC_WRITE = XTIME_CALC_WRITE + (MPI_WTIME() - XTIME0)
!
XTIME0 = MPI_WTIME()
!
!$OMP BARRIER
!
XTIME_OMP_BARR = XTIME_OMP_BARR + (MPI_WTIME() - XTIME0)
!
IF (NRANK/=NPIO) THEN
  !
!$OMP SINGLE
  !  
  IDX_W = IDX_W + 1
  !
#ifdef OL
  XTIME0 = MPI_WTIME()
  CALL MPI_SEND(XWORK2(:,1:IS2),NSIZE*IS2*KIND(XWORK2)/4,MPI_REAL,NPIO,IDX_W,NCOMM,INFOMPI)
  XTIME_COMM_WRITE = XTIME_COMM_WRITE + (MPI_WTIME() - XTIME0)
#endif
  !
!$OMP END SINGLE
  !
ELSE
  !
!$OMP SINGLE
  !
  IDX_W = IDX_W + 1
!  !
  DO I=1,NPROC
!    !
!    !
#ifdef OL    
    XTIME0 = MPI_WTIME()
#endif    
!    !    
    IF (I<NPROC) THEN
#ifdef OL
      CALL MPI_RECV(ZINTER,SIZE(ZINTER)*KIND(ZINTER)/4,MPI_REAL,I,IDX_W,NCOMM,ISTATUS,INFOMPI)
#endif
    ELSE
      ZINTER(:,:) = XWORK2(:,1:IS2)
    ENDIF
!    !
#ifdef OL     
    XTIME_COMM_WRITE = XTIME_COMM_WRITE + (MPI_WTIME() - XTIME0)
    !
    XTIME0 = MPI_WTIME()
#endif     
    !    
    ICPT = 0
    !    
    DO J=1,SIZE(NINDEX)
      !
      IF ( NINDEX(J)==MOD(I,NPROC) ) THEN
        ICPT = ICPT + 1
        PWORK2(J,:) = ZINTER(ICPT,:)
      ENDIF
      !
    ENDDO
!    !
#ifdef OL      
    XTIME_CALC_WRITE = XTIME_CALC_WRITE + (MPI_WTIME() - XTIME0)
#endif      
!    !    
  ENDDO
  !
!$OMP END SINGLE COPYPRIVATE(PWORK2)
  !
ENDIF
!
IF (LHOOK) CALL DR_HOOK('GATHER_AND_WRITE_MPI_X2D0',1,ZHOOK_HANDLE)
!
!
END SUBROUTINE GATHER_AND_WRITE_MPI_X2D0
!
!**************************************************************************
