SUBROUTINE GET_SIZES_PARALLEL (BOP, BDD, CHE, CHI, CHS, CHN, CHU, CHT, CHW, DTCO, DTS, &
                                DTT, DTZ, DGEI, DGF, DGI, DGMI, DGMTO, DGO, DGS, DGSI, DGU, &
                                DGT, DGUT, DGW, F, FSB, GB, ICP, I, O, S, SSB, &
                                SV, TCP, TGD, TGDO, TGR, TGRO, T, TOP, TVG, W, WSB, &
                                IOB, &
                                UG, U, &
                               KPROC,KSIZE,KPROCMIN,KSIZE_TASK,OSHADOWS)
!
!
! Modified by B. Decharme  (08/2013): bug in KSIZE_TASK
!
! Modif Matthieu Lafaysse 04/2014
! For shadows routines, we need strictly rectangular subdomains

!
!
!
USE MODD_SURF_ATM_GRID_n, ONLY : SURF_ATM_GRID_t
USE MODD_SURF_ATM_n, ONLY : SURF_ATM_t
!
!
USE MODD_IO_BUFF_n, ONLY : IO_BUFF_t
!
!
USE MODD_BEM_OPTION_n, ONLY : BEM_OPTIONS_t
USE MODD_BLD_DESCRIPTION_n, ONLY : BLD_DESC_t
USE MODD_CH_EMIS_FIELD_n, ONLY : CH_EMIS_FIELD_t
USE MODD_CH_ISBA_n, ONLY : CH_ISBA_t
USE MODD_CH_SEAFLUX_n, ONLY : CH_SEAFLUX_t
USE MODD_CH_SNAP_n, ONLY : CH_EMIS_SNAP_t
USE MODD_CH_SURF_n, ONLY : CH_SURF_t
USE MODD_CH_TEB_n, ONLY : CH_TEB_t
USE MODD_CH_WATFLUX_n, ONLY : CH_WATFLUX_t
USE MODD_DATA_COVER_n, ONLY : DATA_COVER_t
USE MODD_DATA_SEAFLUX_n, ONLY : DATA_SEAFLUX_t
USE MODD_DATA_TEB_n, ONLY : DATA_TEB_t
USE MODD_DATA_TSZ0_n, ONLY : DATA_TSZ0_t
USE MODD_DIAG_EVAP_ISBA_n, ONLY : DIAG_EVAP_ISBA_t
USE MODD_DIAG_FLAKE_n, ONLY : DIAG_FLAKE_t
USE MODD_DIAG_ISBA_n, ONLY : DIAG_ISBA_t
USE MODD_DIAG_MISC_ISBA_n, ONLY : DIAG_MISC_ISBA_t
USE MODD_DIAG_MISC_TEB_OPTION_n, ONLY : DIAG_MISC_TEB_OPTIONS_t
USE MODD_DIAG_OCEAN_n, ONLY : DIAG_OCEAN_t
USE MODD_DIAG_SEAFLUX_n, ONLY : DIAG_SEAFLUX_t
USE MODD_DIAG_SEAICE_n, ONLY : DIAG_SEAICE_t
USE MODD_DIAG_SURF_ATM_n, ONLY : DIAG_SURF_ATM_t
USE MODD_DIAG_TEB_n, ONLY : DIAG_TEB_t
USE MODD_DIAG_UTCI_TEB_n, ONLY : DIAG_UTCI_TEB_t
USE MODD_DIAG_WATFLUX_n, ONLY : DIAG_WATFLUX_t
USE MODD_FLAKE_n, ONLY : FLAKE_t
USE MODD_FLAKE_SBL_n, ONLY : FLAKE_SBL_t
USE MODD_GR_BIOG_n, ONLY : GR_BIOG_t
USE MODD_ISBA_CANOPY_n, ONLY : ISBA_CANOPY_t
USE MODD_ISBA_n, ONLY : ISBA_t
USE MODD_OCEAN_n, ONLY : OCEAN_t
USE MODD_SEAFLUX_n, ONLY : SEAFLUX_t
USE MODD_SEAFLUX_SBL_n, ONLY : SEAFLUX_SBL_t
USE MODD_SV_n, ONLY : SV_t
USE MODD_TEB_CANOPY_n, ONLY : TEB_CANOPY_t
USE MODD_TEB_GARDEN_n, ONLY : TEB_GARDEN_t
USE MODD_TEB_GARDEN_OPTION_n, ONLY : TEB_GARDEN_OPTIONS_t
USE MODD_TEB_GREENROOF_n, ONLY : TEB_GREENROOF_t
USE MODD_TEB_GREENROOF_OPTION_n, ONLY : TEB_GREENROOF_OPTIONS_t
USE MODD_TEB_n, ONLY : TEB_t
USE MODD_TEB_OPTION_n, ONLY : TEB_OPTIONS_t
USE MODD_TEB_VEG_n, ONLY : TEB_VEG_OPTIONS_t
USE MODD_WATFLUX_n, ONLY : WATFLUX_t
USE MODD_WATFLUX_SBL_n, ONLY : WATFLUX_SBL_t
!
#ifdef SFX_OL
USE MODD_SLOPE_EFFECT, ONLY : NIX,NIY
USE MODN_IO_OFFLINE, ONLY : CSURF_FILETYPE
#endif
USE MODI_INIT_IO_SURF_n
USE MODI_READ_SURF
USE MODI_READ_GRIDTYPE
USE MODI_GET_GRID_DIM
!RJ: missing modi
USE MODI_END_IO_SURF_n
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE
!
!
!
!
TYPE(BEM_OPTIONS_t), INTENT(INOUT) :: BOP
TYPE(BLD_DESC_t), INTENT(INOUT) :: BDD
TYPE(CH_EMIS_FIELD_t), INTENT(INOUT) :: CHE
TYPE(CH_ISBA_t), INTENT(INOUT) :: CHI
TYPE(CH_SEAFLUX_t), INTENT(INOUT) :: CHS
TYPE(CH_EMIS_SNAP_t), INTENT(INOUT) :: CHN
TYPE(CH_SURF_t), INTENT(INOUT) :: CHU
TYPE(CH_TEB_t), INTENT(INOUT) :: CHT
TYPE(CH_WATFLUX_t), INTENT(INOUT) :: CHW
TYPE(DATA_COVER_t), INTENT(INOUT) :: DTCO
TYPE(DATA_SEAFLUX_t), INTENT(INOUT) :: DTS
TYPE(DATA_TEB_t), INTENT(INOUT) :: DTT
TYPE(DATA_TSZ0_t), INTENT(INOUT) :: DTZ
TYPE(DIAG_EVAP_ISBA_t), INTENT(INOUT) :: DGEI
TYPE(DIAG_FLAKE_t), INTENT(INOUT) :: DGF
TYPE(DIAG_ISBA_t), INTENT(INOUT) :: DGI
TYPE(DIAG_MISC_ISBA_t), INTENT(INOUT) :: DGMI
TYPE(DIAG_MISC_TEB_OPTIONS_t), INTENT(INOUT) :: DGMTO
TYPE(DIAG_OCEAN_t), INTENT(INOUT) :: DGO
TYPE(DIAG_SEAFLUX_t), INTENT(INOUT) :: DGS
TYPE(DIAG_SEAICE_t), INTENT(INOUT) :: DGSI
TYPE(DIAG_SURF_ATM_t), INTENT(INOUT) :: DGU
TYPE(DIAG_TEB_t), INTENT(INOUT) :: DGT
TYPE(DIAG_UTCI_TEB_t), INTENT(INOUT) :: DGUT
TYPE(DIAG_WATFLUX_t), INTENT(INOUT) :: DGW
TYPE(FLAKE_t), INTENT(INOUT) :: F
TYPE(FLAKE_SBL_t), INTENT(INOUT) :: FSB
TYPE(GR_BIOG_t), INTENT(INOUT) :: GB
TYPE(ISBA_CANOPY_t), INTENT(INOUT) :: ICP
TYPE(ISBA_t), INTENT(INOUT) :: I
TYPE(OCEAN_t), INTENT(INOUT) :: O
TYPE(SEAFLUX_t), INTENT(INOUT) :: S
TYPE(SEAFLUX_SBL_t), INTENT(INOUT) :: SSB
TYPE(SV_t), INTENT(INOUT) :: SV
TYPE(TEB_CANOPY_t), INTENT(INOUT) :: TCP
TYPE(TEB_GARDEN_t), INTENT(INOUT) :: TGD
TYPE(TEB_GARDEN_OPTIONS_t), INTENT(INOUT) :: TGDO
TYPE(TEB_GREENROOF_t), INTENT(INOUT) :: TGR
TYPE(TEB_GREENROOF_OPTIONS_t), INTENT(INOUT) :: TGRO
TYPE(TEB_t), INTENT(INOUT) :: T
TYPE(TEB_OPTIONS_t), INTENT(INOUT) :: TOP
TYPE(TEB_VEG_OPTIONS_t), INTENT(INOUT) :: TVG
TYPE(WATFLUX_t), INTENT(INOUT) :: W
TYPE(WATFLUX_SBL_t), INTENT(INOUT) :: WSB
!
TYPE(IO_BUFF_t), INTENT(INOUT) :: IOB
!
TYPE(SURF_ATM_GRID_t), INTENT(INOUT) :: UG
TYPE(SURF_ATM_t), INTENT(INOUT) :: U
!
INTEGER, INTENT(IN) :: KPROC
INTEGER, INTENT(IN) :: KSIZE
INTEGER, INTENT(IN) :: KPROCMIN
LOGICAL, INTENT(IN),OPTIONAL :: OSHADOWS

LOGICAL::GSHADOWS

LOGICAL :: GRECT

INTEGER, DIMENSION(0:KPROC-1), INTENT(OUT) :: KSIZE_TASK
!

INTEGER::IRESP

INTEGER :: ISIZE, IRESTE, INRESTE
INTEGER :: J, IPROC
INTEGER :: ISIZE_Y,INY_THREAD,INY_RESTE

REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
IF (LHOOK) CALL DR_HOOK('GET_SIZES_PARALLEL',0,ZHOOK_HANDLE)
!

IF (PRESENT(OSHADOWS)) THEN
  GSHADOWS=OSHADOWS
ELSE
  GSHADOWS=.FALSE.
ENDIF

IF (GSHADOWS) THEN
  ! We want only rectangular subdomains
  
  ! Get x and y dimension lengths
#ifdef SFX_OL
!$OMP SINGLE
  IF (NIX==0) THEN

    !CALL SET_SURFEX_FILEIN(CSURF_FILETYPE,'PREP ') ! not necessary, it works with PGD or PREP file
    CALL INIT_IO_SURF_n(BOP, BDD, CHE, CHI, CHS, CHN, CHU, CHT, CHW, &
                      DTCO, DTS, DTT, DTZ, DGEI, DGF, DGI, DGMI, DGMTO, DGO, DGS, DGSI, DGU, DGT, DGUT, DGW, &
                      F, FSB, GB, IOB, ICP, I, O, S, SSB, UG, U, SV, &
                      TCP, TGD, TGDO, TGR, TGRO, T, TOP, TVG, W, WSB, &
                        CSURF_FILETYPE,'FULL  ','SURF  ','READ ')
    CALL READ_SURF(IOB, &
                   CSURF_FILETYPE,'GRID_TYPE',UG%CGRID,IRESP,HDIR='A')
    CALL READ_GRIDTYPE(IOB, &
                       CSURF_FILETYPE,UG%CGRID,UG%NGRID_PAR,U%NDIM_FULL,.FALSE.,HDIR="A")
    ALLOCATE(UG%XGRID_FULL_PAR(UG%NGRID_PAR))
    CALL READ_GRIDTYPE(IOB, &
                       CSURF_FILETYPE,UG%CGRID,UG%NGRID_PAR,U%NDIM_FULL,.TRUE.,UG%XGRID_FULL_PAR,IRESP,HDIR="A")  
    CALL END_IO_SURF_n(CSURF_FILETYPE)
    CALL GET_GRID_DIM(UG%CGRID,SIZE(UG%XGRID_FULL_PAR),UG%XGRID_FULL_PAR,GRECT,NIX,NIY)  
    UG%XGRID_FULL_PAR=>NULL()
  ENDIF
!$OMP END SINGLE  

  !If get_sizes_parallel is called by init_index_mpi
  !ISIZE_Y represents the number of lines of the total domain
  !INY_THREAD represents the number of lines for 1 MPI thread
  !If get_sizes_parallel is called by offline
  !ISIZE_Y represents the number of lines of 1 MPI thread
  !INY_THREAD represent the number of lines for 1 OPEN-MP thread
  
  ISIZE_Y=KSIZE/NIX

  ! Number of lines (y) for one thread
  INY_THREAD=ISIZE_Y/KPROC
  INY_RESTE=ISIZE_Y-KPROC*INY_THREAD
  
  KSIZE_TASK(:)=INY_THREAD*NIX
  
  DO J=KPROCMIN+KPROC-INY_RESTE,KPROCMIN+KPROC-1
    KSIZE_TASK(MOD(J,KPROC))=KSIZE_TASK(MOD(J,KPROC))+NIX
  END DO
#endif
ELSE
  ISIZE = CEILING(KSIZE*1./KPROC) !nb of points by task

  INRESTE = KPROC*ISIZE - KSIZE ! nb of tasks containing ireste points
  IF (INRESTE>0) THEN
    IRESTE = ISIZE - 1
  ELSE
    IRESTE = ISIZE
  ENDIF
!
  KSIZE_TASK(:) = ISIZE
  IF (INRESTE>0) THEN
    DO J = KPROCMIN+KPROC-INRESTE,KPROCMIN+KPROC-1
      KSIZE_TASK(MOD(J,KPROC)) = IRESTE
    ENDDO
  ENDIF
!
!so:
!(nproc-nreste)*isize + nreste*ireste = ndim_full
!if nreste==1: 
!(nproc-1)*isize + ireste = 
!(nproc-1)*isize + NDIM_FULL - (nproc-1)*isize = NDIM_FULL
!if (ireste==isize-1):
!nproc*isize - nreste*isize + nreste*isize - nreste = 
!nproc*isize - nreste = NDIM_FULL


ENDIF
!
IF (LHOOK) CALL DR_HOOK('GET_SIZES_PARALLEL',1,ZHOOK_HANDLE)
!
END SUBROUTINE GET_SIZES_PARALLEL
