SUBROUTINE GET_SIZES_PARALLEL (IOB, &
                                UG, U, &
                               KPROC,KSIZE,KPROCMIN,KSIZE_TASK,OSHADOWS)
!
!
! Modified by B. Decharme  (08/2013): bug in KSIZE_TASK
!
! Modif Matthieu Lafaysse 04/2014
! For shadows routines, we need strictly rectangular subdomains

!
!
USE MODD_BEM_OPTION_n, ONLY : BOP => BEM_OPTIONS
USE MODD_BLD_DESCRIPTION_n, ONLY : BDD => BLD_DESC
USE MODD_CH_EMIS_FIELD_n, ONLY : CHE => CH_EMIS_FIELD
USE MODD_CH_ISBA_n, ONLY : CHI => CH_ISBA
USE MODD_CH_SEAFLUX_n, ONLY : CHS => CH_SEAFLUX
USE MODD_CH_SNAP_n, ONLY : CHN => CH_EMIS_SNAP
USE MODD_CH_SURF_n, ONLY : CHU => CH_SURF
USE MODD_CH_TEB_n, ONLY : CHT => CH_TEB
USE MODD_CH_WATFLUX_n, ONLY : CHW => CH_WATFLUX
USE MODD_DATA_COVER_n, ONLY : DTCO => DATA_COVER
USE MODD_DATA_SEAFLUX_n, ONLY : DTS => DATA_SEAFLUX
USE MODD_DATA_TEB_n, ONLY : DTT => DATA_TEB
USE MODD_DATA_TSZ0_n, ONLY : DTZ => DATA_TSZ0
USE MODD_DIAG_EVAP_ISBA_n, ONLY : DGEI => DIAG_EVAP_ISBA
USE MODD_DIAG_FLAKE_n, ONLY : DGF => DIAG_FLAKE
USE MODD_DIAG_ISBA_n, ONLY : DGI => DIAG_ISBA
USE MODD_DIAG_MISC_ISBA_n, ONLY : DGMI => DIAG_MISC_ISBA
USE MODD_DIAG_MISC_TEB_OPTION_n, ONLY : DGMTO => DIAG_MISC_TEB_OPTIONS
USE MODD_DIAG_OCEAN_n, ONLY : DGO => DIAG_OCEAN
USE MODD_DIAG_SEAFLUX_n, ONLY : DGS => DIAG_SEAFLUX
USE MODD_DIAG_SEAICE_n, ONLY : DGSI => DIAG_SEAICE
USE MODD_DIAG_SURF_ATM_n, ONLY : DGU => DIAG_SURF_ATM
USE MODD_DIAG_TEB_n, ONLY : DGT => DIAG_TEB
USE MODD_DIAG_UTCI_TEB_n, ONLY : DGUT => DIAG_UTCI_TEB
USE MODD_DIAG_WATFLUX_n, ONLY : DGW => DIAG_WATFLUX
USE MODD_FLAKE_n, ONLY : F => FLAKE
USE MODD_FLAKE_SBL_n, ONLY : FSB => FLAKE_SBL
USE MODD_GR_BIOG_n, ONLY : GB => GR_BIOG
USE MODD_ISBA_CANOPY_n, ONLY : ICP => ISBA_CANOPY
USE MODD_ISBA_n, ONLY : I => ISBA
USE MODD_OCEAN_n, ONLY : O => OCEAN
USE MODD_SEAFLUX_n, ONLY : S => SEAFLUX
USE MODD_SEAFLUX_SBL_n, ONLY : SSB => SEAFLUX_SBL
USE MODD_SV_n, ONLY : SV => SV
USE MODD_TEB_CANOPY_n, ONLY : TCP => TEB_CANOPY
USE MODD_TEB_GARDEN_n, ONLY : TGD => TEB_GARDEN
USE MODD_TEB_GARDEN_OPTION_n, ONLY : TGDO => TEB_GARDEN_OPTIONS
USE MODD_TEB_GREENROOF_n, ONLY : TGR => TEB_GREENROOF
USE MODD_TEB_GREENROOF_OPTION_n, ONLY : TGRO => TEB_GREENROOF_OPTIONS
USE MODD_TEB_n, ONLY : T => TEB
USE MODD_TEB_OPTION_n, ONLY : TOP => TEB_OPTIONS
USE MODD_TEB_VEG_n, ONLY : TVG => TEB_VEG_OPTIONS
USE MODD_WATFLUX_n, ONLY : W => WATFLUX
USE MODD_WATFLUX_SBL_n, ONLY : WSB => WATFLUX_SBL
!
USE MODD_SURF_ATM_GRID_n, ONLY : SURF_ATM_GRID_t
USE MODD_SURF_ATM_n, ONLY : SURF_ATM_t
!
!
USE MODD_IO_BUFF_n, ONLY : IO_BUFF_t
!
#ifdef SFX_OL
USE MODD_SLOPE_EFFECT, ONLY : NIX,NIY
USE MODN_IO_OFFLINE, ONLY : CSURF_FILETYPE
#endif
USE MODI_INIT_IO_SURF_n
USE MODI_READ_SURF
USE MODI_READ_GRIDTYPE
USE MODI_GET_GRID_DIM
!RJ: missing modi
USE MODI_END_IO_SURF_n
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE
!
!
!
TYPE(IO_BUFF_t), INTENT(INOUT) :: IOB
!
TYPE(SURF_ATM_GRID_t), INTENT(INOUT) :: UG
TYPE(SURF_ATM_t), INTENT(INOUT) :: U
!
INTEGER, INTENT(IN) :: KPROC
INTEGER, INTENT(IN) :: KSIZE
INTEGER, INTENT(IN) :: KPROCMIN
LOGICAL, INTENT(IN),OPTIONAL :: OSHADOWS

LOGICAL::GSHADOWS

LOGICAL :: GRECT

INTEGER, DIMENSION(0:KPROC-1), INTENT(OUT) :: KSIZE_TASK
!

INTEGER::IRESP

INTEGER :: ISIZE, IRESTE, INRESTE
INTEGER :: J, IPROC
INTEGER :: ISIZE_Y,INY_THREAD,INY_RESTE

REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
IF (LHOOK) CALL DR_HOOK('GET_SIZES_PARALLEL',0,ZHOOK_HANDLE)
!

IF (PRESENT(OSHADOWS)) THEN
  GSHADOWS=OSHADOWS
ELSE
  GSHADOWS=.FALSE.
ENDIF

IF (GSHADOWS) THEN
  ! We want only rectangular subdomains
  
  ! Get x and y dimension lengths
#ifdef SFX_OL
!$OMP SINGLE
  IF (NIX==0) THEN

    !CALL SET_SURFEX_FILEIN(CSURF_FILETYPE,'PREP ') ! not necessary, it works with PGD or PREP file
    CALL INIT_IO_SURF_n(BOP, BDD, CHE, CHI, CHS, CHN, CHU, CHT, CHW, &
                      DTCO, DTS, DTT, DTZ, DGEI, DGF, DGI, DGMI, DGMTO, DGO, DGS, DGSI, DGU, DGT, DGUT, DGW, &
                      F, FSB, GB, IOB, ICP, I, O, S, SSB, UG, U, SV, &
                      TCP, TGD, TGDO, TGR, TGRO, T, TOP, TVG, W, WSB, &
                        CSURF_FILETYPE,'FULL  ','SURF  ','READ ')
    CALL READ_SURF(IOB, &
                   CSURF_FILETYPE,'GRID_TYPE',UG%CGRID,IRESP,HDIR='A')
    CALL READ_GRIDTYPE(IOB, &
                       CSURF_FILETYPE,UG%CGRID,UG%NGRID_PAR,U%NDIM_FULL,.FALSE.,HDIR="A")
    ALLOCATE(UG%XGRID_FULL_PAR(UG%NGRID_PAR))
    CALL READ_GRIDTYPE(IOB, &
                       CSURF_FILETYPE,UG%CGRID,UG%NGRID_PAR,U%NDIM_FULL,.TRUE.,UG%XGRID_FULL_PAR,IRESP,HDIR="A")  
    CALL END_IO_SURF_n(CSURF_FILETYPE)
    CALL GET_GRID_DIM(UG%CGRID,SIZE(UG%XGRID_FULL_PAR),UG%XGRID_FULL_PAR,GRECT,NIX,NIY)  
    UG%XGRID_FULL_PAR=>NULL()
  ENDIF
!$OMP END SINGLE  

  !If get_sizes_parallel is called by init_index_mpi
  !ISIZE_Y represents the number of lines of the total domain
  !INY_THREAD represents the number of lines for 1 MPI thread
  !If get_sizes_parallel is called by offline
  !ISIZE_Y represents the number of lines of 1 MPI thread
  !INY_THREAD represent the number of lines for 1 OPEN-MP thread
  
  ISIZE_Y=KSIZE/NIX

  ! Number of lines (y) for one thread
  INY_THREAD=ISIZE_Y/KPROC
  INY_RESTE=ISIZE_Y-KPROC*INY_THREAD
  
  KSIZE_TASK(:)=INY_THREAD*NIX
  
  DO J=KPROCMIN+KPROC-INY_RESTE,KPROCMIN+KPROC-1
    KSIZE_TASK(MOD(J,KPROC))=KSIZE_TASK(MOD(J,KPROC))+NIX
  END DO
#endif
ELSE
  ISIZE = CEILING(KSIZE*1./KPROC) !nb of points by task

  INRESTE = KPROC*ISIZE - KSIZE ! nb of tasks containing ireste points
  IF (INRESTE>0) THEN
    IRESTE = ISIZE - 1
  ELSE
    IRESTE = ISIZE
  ENDIF
!
  KSIZE_TASK(:) = ISIZE
  IF (INRESTE>0) THEN
    DO J = KPROCMIN+KPROC-INRESTE,KPROCMIN+KPROC-1
      KSIZE_TASK(MOD(J,KPROC)) = IRESTE
    ENDDO
  ENDIF
!
!so:
!(nproc-nreste)*isize + nreste*ireste = ndim_full
!if nreste==1: 
!(nproc-1)*isize + ireste = 
!(nproc-1)*isize + NDIM_FULL - (nproc-1)*isize = NDIM_FULL
!if (ireste==isize-1):
!nproc*isize - nreste*isize + nreste*isize - nreste = 
!nproc*isize - nreste = NDIM_FULL


ENDIF
!
IF (LHOOK) CALL DR_HOOK('GET_SIZES_PARALLEL',1,ZHOOK_HANDLE)
!
END SUBROUTINE GET_SIZES_PARALLEL
