SUBROUTINE GOTO_WRAPPER_TEB_PATCH(B, DGCT, DGMT, T, TGDR, TGDMT, TGRR, TGRMT, KTO_PATCH)
!
USE MODD_DIAG_CUMUL_TEB_n, ONLY : DIAG_CUMUL_TEB_t, DIAG_CUMUL_TEB_GOTO_PATCH
USE MODD_DIAG_MISC_TEB_n, ONLY : DIAG_MISC_TEB_t, DIAG_MISC_TEB_GOTO_PATCH
USE MODD_TEB_n, ONLY : TEB_t, TEB_GOTO_PATCH
USE MODD_BEM_n, ONLY : BEM_t, BEM_GOTO_PATCH
USE MODD_TEB_VEG_n, ONLY : TEB_VEG_PROG_t, TEB_VEG_PROG_GOTO_PATCH
USE MODD_TEB_VEG_PARAM_n, ONLY : TEB_VEG_PARAM_TIME_t, TEB_VEG_PARAM_TIME_GOTO_PATCH
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE 
!
TYPE(BEM_t), INTENT(INOUT) :: B
TYPE(DIAG_CUMUL_TEB_t), INTENT(INOUT) :: DGCT
TYPE(DIAG_MISC_TEB_t), INTENT(INOUT) :: DGMT
TYPE(TEB_t), INTENT(INOUT) :: T
TYPE(TEB_VEG_PROG_t), INTENT(INOUT) :: TGDR
TYPE(TEB_VEG_PARAM_TIME_t), INTENT(INOUT) :: TGDMT
TYPE(TEB_VEG_PROG_t), INTENT(INOUT) :: TGRR
TYPE(TEB_VEG_PARAM_TIME_t), INTENT(INOUT) :: TGRMT
!
INTEGER,INTENT(IN) :: KTO_PATCH
!
INTEGER            :: ICURRENT_PATCH
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
IF (LHOOK) CALL DR_HOOK('GOTO_WRAPPER_TEB_PATCH',0,ZHOOK_HANDLE)
!
 CALL DIAG_CUMUL_TEB_GOTO_PATCH(DGCT,KTO_PATCH)
 CALL DIAG_MISC_TEB_GOTO_PATCH(DGMT,KTO_PATCH)
 CALL TEB_GOTO_PATCH(T,KTO_PATCH)
 CALL BEM_GOTO_PATCH(B,KTO_PATCH)
 CALL TEB_VEG_PROG_GOTO_PATCH(TGDR,KTO_PATCH)
 CALL TEB_VEG_PARAM_TIME_GOTO_PATCH(TGDMT,KTO_PATCH)
 CALL TEB_VEG_PROG_GOTO_PATCH(TGRR,KTO_PATCH)
 CALL TEB_VEG_PARAM_TIME_GOTO_PATCH(TGRMT,KTO_PATCH) 
!
IF (LHOOK) CALL DR_HOOK('GOTO_WRAPPER_TEB_PATCH',1,ZHOOK_HANDLE)
!
END SUBROUTINE GOTO_WRAPPER_TEB_PATCH
