SUBROUTINE GOTO_WRAPPER_TEB_PATCH(KTO_PATCH, B, DMTC, DMT, T)
!
USE MODD_DIAG_MISC_TEB_n, ONLY : DIAG_MISC_TEB_t, DIAG_MISC_TEB_GOTO_PATCH
USE MODD_TEB_n, ONLY : TEB_t, TEB_GOTO_PATCH
USE MODD_BEM_n, ONLY : BEM_t, BEM_GOTO_PATCH
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE 
!
INTEGER,INTENT(IN) :: KTO_PATCH
!
TYPE(BEM_t), INTENT(INOUT), OPTIONAL :: B
TYPE(DIAG_MISC_TEB_t), INTENT(INOUT), OPTIONAL :: DMTC
TYPE(DIAG_MISC_TEB_t), INTENT(INOUT), OPTIONAL :: DMT
TYPE(TEB_t), INTENT(INOUT), OPTIONAL :: T
!
INTEGER            :: ICURRENT_PATCH
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
IF (LHOOK) CALL DR_HOOK('GOTO_WRAPPER_TEB_PATCH',0,ZHOOK_HANDLE)
!
IF (PRESENT(T)) CALL TEB_GOTO_PATCH(T,KTO_PATCH)
IF (PRESENT(B))  CALL BEM_GOTO_PATCH(B,KTO_PATCH)
IF (PRESENT(DMTC)) CALL DIAG_MISC_TEB_GOTO_PATCH(DMTC,KTO_PATCH)
IF (PRESENT(DMT)) CALL DIAG_MISC_TEB_GOTO_PATCH(DMT,KTO_PATCH) 
!
IF (LHOOK) CALL DR_HOOK('GOTO_WRAPPER_TEB_PATCH',1,ZHOOK_HANDLE)
!
END SUBROUTINE GOTO_WRAPPER_TEB_PATCH
