!#############################################################
SUBROUTINE INIT_VEG_PGD_GARDEN_n(HPROGRAM, KLUOUT, KI, KGROUND_LAYER, KMONTH,        &
                        PVEGTYPE, PTDEEP, PGAMMAT, HPHOTO, HINIT, OTR_ML,   &
                        KNBIOMASS, PCO2, PRHOA, PABC, PPOI,  &
                        PGMES, PGC, PDMAX, PANMAX, PFZERO, PEPSO, PGAMM, PQDGAMM,   &
                        PQDGMES, PT1GMES, PT2GMES, PAMAX, PQDAMAX, PT1AMAX, PT2AMAX,&
                        PAH, PBH,                   &
                        KSV, HSV, KBEQ, HSVO, KAEREQ, KSV_CHSBEG, KSV_CHSEND,       &
                        KSV_AERBEG, KSV_AEREND, HCH_NAMES, HAER_NAMES, KDSTEQ,      &
                        KSV_DSTBEG, KSV_DSTEND, KSLTEQ, KSV_SLTBEG, KSV_SLTEND,     &
                        HDSTNAMES, HSLTNAMES, HCHEM_SURF_FILE,                      &
                        PCLAY, PSAND, HPEDOTF,                                      &
                        PCONDSAT, PMPOTSAT, PBCOEF, PWWILT, PWFC, PW33, PWSAT,      &
                        PTAUICE, PCGSAT, PC1SAT, PC2REF, PC3, PC4B, PACOEF, PPCOEF, &
                        PC4REF, PPCPS, PPLVTT, PPLSTT,                              &
                        HSCOND, HISBA, PHCAPSOIL, PCONDDRY, PCONDSLD, HCPSURF,      &
                        PDG, PDROOT, PDG2, PROOTFRAC, PRUNOFFD, PDZG, PDZDIF,       &
                        PSOILWGHT, KWG_LAYER, KLAYER_HORT, KLAYER_DUN, PD_ICE,      &
                        PKSAT_ICE, PALBNIR_DRY, PALBVIS_DRY, PALBUV_DRY,            &
                        PALBNIR_WET, PALBVIS_WET, PALBUV_WET, PBSLAI_NITRO,         &
                        PCE_NITRO, PCNA_NITRO, PCF_NITRO                            )  
!#############################################################
!
!!****  *INIT_VEG_PGD_GARDEN_n* - routine to initialize ISBA
!!
!!    PURPOSE
!!    -------
!!
!!**  METHOD
!!    ------
!!
!!    EXTERNAL
!!    --------
!!
!!
!!    IMPLICIT ARGUMENTS
!!    ------------------
!!
!!    REFERENCE
!!    ---------
!!
!!
!!    AUTHOR
!!    ------
!!	V. Masson   *Meteo France*	
!!
!!    MODIFICATIONS
!!    -------------
!!
!-------------------------------------------------------------------------------
!
!*       0.    DECLARATIONS
!              ------------
!
USE MODI_INIT_VEG_PGD_n
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE
!
!*       0.1   Declarations of arguments
!              -------------------------
!
CHARACTER(LEN=6), INTENT(IN)  :: HPROGRAM  ! program calling surf. schemes
INTEGER, INTENT(IN)  :: KLUOUT
!
INTEGER, INTENT(IN)  :: KI
INTEGER, INTENT(IN)  :: KGROUND_LAYER
INTEGER, INTENT(IN)  :: KMONTH
!
REAL, DIMENSION(:,:), POINTER :: PVEGTYPE
!
REAL, DIMENSION(:), POINTER :: PTDEEP
REAL, DIMENSION(:), POINTER :: PGAMMAT
!
!
CHARACTER(LEN=3), INTENT(IN) :: HPHOTO
CHARACTER(LEN=3), INTENT(IN) :: HINIT
LOGICAL, INTENT(IN) :: OTR_ML
INTEGER, INTENT(IN) :: KNBIOMASS
REAL, DIMENSION(:), INTENT(IN) :: PCO2
REAL, DIMENSION(:), INTENT(IN) :: PRHOA
REAL, DIMENSION(:), POINTER :: PABC
REAL, DIMENSION(:), POINTER :: PPOI
REAL, DIMENSION(:), POINTER :: PGMES
REAL, DIMENSION(:), POINTER :: PGC
REAL, DIMENSION(:), POINTER :: PDMAX
REAL, DIMENSION(:), POINTER :: PANMAX
REAL, DIMENSION(:), POINTER :: PFZERO
REAL, DIMENSION(:), POINTER :: PEPSO
REAL, DIMENSION(:), POINTER :: PGAMM
REAL, DIMENSION(:), POINTER :: PQDGAMM
REAL, DIMENSION(:), POINTER :: PQDGMES
REAL, DIMENSION(:), POINTER :: PT1GMES
REAL, DIMENSION(:), POINTER :: PT2GMES
REAL, DIMENSION(:), POINTER :: PAMAX
REAL, DIMENSION(:), POINTER :: PQDAMAX
REAL, DIMENSION(:), POINTER :: PT1AMAX
REAL, DIMENSION(:), POINTER :: PT2AMAX
REAL, DIMENSION(:), POINTER :: PAH
REAL, DIMENSION(:), POINTER :: PBH
!
INTEGER,                          INTENT(IN) :: KSV      ! number of scalars
CHARACTER(LEN=6), DIMENSION(KSV), INTENT(IN) :: HSV      ! name of all scalar variables
INTEGER,                         INTENT(OUT) :: KBEQ     ! number of chemical variables
CHARACTER(LEN=6), DIMENSION(:), POINTER :: HSVO          ! name of scalar species without # and @
INTEGER,                         INTENT(OUT) :: KAEREQ  ! number of aerosol variables
INTEGER,                         INTENT(OUT) :: KSV_CHSBEG  ! first chemical var.
INTEGER,                         INTENT(OUT) :: KSV_CHSEND  ! last  chemical var.
INTEGER,                         INTENT(OUT) :: KSV_AERBEG  ! first aerosol var.
INTEGER,                         INTENT(OUT) :: KSV_AEREND  ! last  aerosol var.
CHARACTER(LEN=6), DIMENSION(:), POINTER :: HCH_NAMES
CHARACTER(LEN=6), DIMENSION(:), POINTER :: HAER_NAMES     
INTEGER,                         INTENT(OUT) :: KDSTEQ     ! number of chemical variables
INTEGER,                         INTENT(OUT) :: KSV_DSTBEG  ! first chemical var.
INTEGER,                         INTENT(OUT) :: KSV_DSTEND  ! last  chemical var.
INTEGER,                         INTENT(OUT) :: KSLTEQ     ! number of chemical variables
INTEGER,                         INTENT(OUT) :: KSV_SLTBEG  ! first chemical var.
INTEGER,                         INTENT(OUT) :: KSV_SLTEND  ! last  chemical var.
CHARACTER(LEN=6), DIMENSION(:), POINTER, OPTIONAL :: HDSTNAMES
CHARACTER(LEN=6), DIMENSION(:), POINTER, OPTIONAL :: HSLTNAMES
!
CHARACTER(LEN=28), INTENT(OUT) :: HCHEM_SURF_FILE
!
REAL, DIMENSION(:,:), INTENT(IN) :: PCLAY
REAL, DIMENSION(:,:), INTENT(IN) :: PSAND
CHARACTER(LEN=4), INTENT(IN) :: HPEDOTF
REAL, DIMENSION(:,:), POINTER :: PCONDSAT
REAL, DIMENSION(:,:), POINTER :: PMPOTSAT
REAL, DIMENSION(:,:), POINTER :: PBCOEF
REAL, DIMENSION(:,:), POINTER :: PWWILT
REAL, DIMENSION(:,:), POINTER :: PWFC
REAL, DIMENSION(:,:), POINTER :: PW33
REAL, DIMENSION(:,:), POINTER :: PWSAT
REAL, DIMENSION(:), POINTER :: PTAUICE
REAL, DIMENSION(:), POINTER :: PCGSAT
REAL, DIMENSION(:), POINTER :: PC1SAT
REAL, DIMENSION(:), POINTER :: PC2REF
REAL, DIMENSION(:,:), POINTER :: PC3
REAL, DIMENSION(:), POINTER :: PC4B
REAL, DIMENSION(:), POINTER :: PACOEF
REAL, DIMENSION(:), POINTER :: PPCOEF
REAL, DIMENSION(:), POINTER :: PC4REF
!
REAL, DIMENSION(:), POINTER :: PPCPS
REAL, DIMENSION(:), POINTER :: PPLVTT
REAL, DIMENSION(:), POINTER :: PPLSTT
!
CHARACTER(LEN=4), INTENT(IN) :: HSCOND
CHARACTER(LEN=3), INTENT(IN) :: HISBA
REAL, DIMENSION(:,:), POINTER :: PHCAPSOIL
REAL, DIMENSION(:,:), POINTER :: PCONDDRY
REAL, DIMENSION(:,:), POINTER :: PCONDSLD
CHARACTER(LEN=3), INTENT(IN) :: HCPSURF
!
REAL, DIMENSION(:,:), INTENT(IN) :: PDG
REAL, DIMENSION(:), INTENT(IN) :: PDROOT
REAL, DIMENSION(:), INTENT(IN) :: PDG2
REAL, DIMENSION(:,:), INTENT(IN) :: PROOTFRAC
REAL, DIMENSION(:), POINTER :: PRUNOFFD
REAL, DIMENSION(:,:), POINTER :: PDZG
REAL, DIMENSION(:,:), POINTER :: PDZDIF
REAL, DIMENSION(:,:), POINTER :: PSOILWGHT
INTEGER, DIMENSION(:), INTENT(IN) :: KWG_LAYER
INTEGER, INTENT(OUT) :: KLAYER_HORT
INTEGER, INTENT(OUT) :: KLAYER_DUN
!
REAL, DIMENSION(:), INTENT(INOUT) :: PD_ICE
REAL, DIMENSION(:), POINTER :: PKSAT_ICE
!
REAL, DIMENSION(:), POINTER :: PALBNIR_DRY
REAL, DIMENSION(:), POINTER :: PALBVIS_DRY
REAL, DIMENSION(:), POINTER :: PALBUV_DRY
REAL, DIMENSION(:), POINTER :: PALBNIR_WET
REAL, DIMENSION(:), POINTER :: PALBVIS_WET
REAL, DIMENSION(:), POINTER :: PALBUV_WET
!
REAL, DIMENSION(:), POINTER :: PBSLAI_NITRO
REAL, DIMENSION(:), INTENT(IN) :: PCE_NITRO
REAL, DIMENSION(:), INTENT(IN) :: PCNA_NITRO
REAL, DIMENSION(:), INTENT(IN) :: PCF_NITRO
!
!*       0.2   Declarations of local variables
!              -------------------------------
!
REAL, DIMENSION(:,:), POINTER :: ZPATCH=>NULL()
REAL, DIMENSION(:,:,:), POINTER :: ZVEGTYPE_PATCH=>NULL()
INTEGER, DIMENSION(:), POINTER :: ISIZE_NATURE_P=>NULL()
INTEGER, DIMENSION(:,:), POINTER :: IR_NATURE_P=>NULL()
REAL, DIMENSION(0) :: ZTDEEP_CLI, ZGAMMAT_CLI, ZTHRESHOLD
INTEGER, DIMENSION(:,:), POINTER :: IIRRINUM=>NULL()
LOGICAL, DIMENSION(:,:), POINTER :: GIRRIDAY=>NULL()
LOGICAL, DIMENSION(:,:), POINTER :: GIRRIGATE=>NULL()
REAL, DIMENSION(:,:), POINTER :: ZTHRESHOLDSPT=>NULL()
REAL, DIMENSION(:,:,:), POINTER :: ZINCREASE=>NULL()
REAL, DIMENSION(:,:,:), POINTER :: ZTURNOVER=>NULL()
REAL, DIMENSION(:,:,:), POINTER :: ZSFDST=>NULL()
REAL, DIMENSION(:,:,:), POINTER :: ZSFDSTM=>NULL()
REAL, DIMENSION(:,:,:), POINTER :: ZSFSLT=>NULL()
REAL, DIMENSION(0) :: ZAOSIP, ZAOSIM, ZAOSJP, ZAOSJM
REAL, DIMENSION(0) :: ZHO2IP, ZHO2IM, ZHO2JP, ZHO2JM
REAL, DIMENSION(0,0) :: ZZ0
REAL, DIMENSION(:,:), POINTER :: ZZ0EFFIP=>NULL()
REAL, DIMENSION(:,:), POINTER :: ZZ0EFFIM=>NULL()
REAL, DIMENSION(:,:), POINTER :: ZZ0EFFJP=>NULL()
REAL, DIMENSION(:,:), POINTER :: ZZ0EFFJM=>NULL()
REAL, DIMENSION(:), POINTER :: ZZ0REL=>NULL()
!
REAL, DIMENSION(:,:), POINTER :: ZC1SAT=>NULL()
REAL, DIMENSION(:,:), POINTER :: ZC2REF=>NULL()
REAL, DIMENSION(:,:), POINTER :: ZC4REF=>NULL()
REAL, DIMENSION(:,:,:), POINTER :: ZC3=>NULL()
!
REAL, DIMENSION(:,:), POINTER :: ZPCPS=>NULL()
REAL, DIMENSION(:,:), POINTER :: ZPLVTT=>NULL()
REAL, DIMENSION(:,:), POINTER :: ZPLSTT=>NULL()
!
REAL, DIMENSION(:,:), POINTER :: ZKSAT_ICE=>NULL()
REAL, DIMENSION(:,:,:), POINTER :: ZDZG=>NULL()
REAL, DIMENSION(:,:,:), POINTER :: ZDZDIF=>NULL()
REAL, DIMENSION(:,:,:), POINTER :: ZSOILWGHT=>NULL()
REAL, DIMENSION(:,:,:), POINTER :: ZCONDSAT=>NULL()
REAL, DIMENSION(:,:), POINTER :: ZRUNOFFD=>NULL()
REAL, DIMENSION(:,:), POINTER :: ZBSLAI_NITRO=>NULL()
REAL, DIMENSION(:,:), POINTER :: ZANMAX=>NULL()
REAL, DIMENSION(:,:), POINTER :: ZFZERO=>NULL()
REAL, DIMENSION(:,:), POINTER :: ZEPSO=>NULL()
REAL, DIMENSION(:,:), POINTER :: ZGAMM=>NULL()
REAL, DIMENSION(:,:), POINTER :: ZQDGAMM=>NULL()
REAL, DIMENSION(:,:), POINTER :: ZQDGMES=>NULL()
REAL, DIMENSION(:,:), POINTER :: ZT1GMES=>NULL()
REAL, DIMENSION(:,:), POINTER :: ZT2GMES=>NULL()
REAL, DIMENSION(:,:), POINTER :: ZAMAX=>NULL()
REAL, DIMENSION(:,:), POINTER :: ZQDAMAX=>NULL()
REAL, DIMENSION(:,:), POINTER :: ZT1AMAX=>NULL()
REAL, DIMENSION(:,:), POINTER :: ZT2AMAX=>NULL()
REAL, DIMENSION(:,:), POINTER :: ZAH=>NULL()
REAL, DIMENSION(:,:), POINTER :: ZBH=>NULL()
REAL, DIMENSION(:,:), POINTER :: ZTAU_WOOD=>NULL()
!
REAL, DIMENSION(SIZE(PDG,1),SIZE(PDG,2),1) :: ZDG
REAL, DIMENSION(SIZE(PDROOT),1) :: ZDROOT
REAL, DIMENSION(SIZE(PDG2),1) :: ZDG2
REAL, DIMENSION(SIZE(PD_ICE),1) :: ZD_ICE
REAL, DIMENSION(SIZE(PROOTFRAC,1),SIZE(PROOTFRAC,2),1) :: ZROOTFRAC
REAL, DIMENSION(SIZE(PCE_NITRO),1) :: ZCE_NITRO
REAL, DIMENSION(SIZE(PCNA_NITRO),1) :: ZCNA_NITRO
REAL, DIMENSION(SIZE(PCF_NITRO),1) :: ZCF_NITRO
REAL, DIMENSION(SIZE(PGMES),1) :: ZGMES
REAL, DIMENSION(SIZE(PGC),1) :: ZGC
REAL, DIMENSION(SIZE(PDMAX),1) :: ZDMAX
INTEGER, DIMENSION(SIZE(KWG_LAYER),1) :: IWG_LAYER
!
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
!-------------------------------------------------------------------------------
!               Initialisation for IO
!
IF (LHOOK) CALL DR_HOOK('INIT_VEG_PGD_GARDEN_n',0,ZHOOK_HANDLE)
!
!*       2.4    Fraction of each tile
!               ---------------------
!
ZDG(:,:,1) = PDG(:,:)
ZROOTFRAC(:,:,1) = PROOTFRAC(:,:)
ZDROOT(:,1) = PDROOT(:)
ZDG2(:,1) = PDG2(:)
ZD_ICE(:,1) = PD_ICE(:)
IWG_LAYER(:,1) = KWG_LAYER(:)
ZCE_NITRO(:,1) = PCE_NITRO(:)
ZCNA_NITRO(:,1) = PCNA_NITRO(:)
ZCF_NITRO(:,1) = PCF_NITRO(:)
ZGMES(:,1) = PGMES(:)
ZGC(:,1) = PGC(:)
ZDMAX(:,1) = PDMAX(:)
!
CALL INIT_VEG_PGD_n(HPROGRAM, KLUOUT, KI, 1, KGROUND_LAYER, KMONTH,   &
                  PVEGTYPE, ZPATCH, ZVEGTYPE_PATCH, ISIZE_NATURE_P, IR_NATURE_P,    &
                  0.0, &
                  .FALSE., .FALSE., ZTDEEP_CLI, ZGAMMAT_CLI, PTDEEP, PGAMMAT,   &
                  .FALSE., ZTHRESHOLD, IIRRINUM, GIRRIDAY, GIRRIGATE, ZTHRESHOLDSPT, &
                  HPHOTO, HINIT, OTR_ML, KNBIOMASS, PCO2, PRHOA, PABC, PPOI,  &
                  ZGMES, ZGC, ZDMAX, ZANMAX, ZFZERO, ZEPSO, ZGAMM, ZQDGAMM,   &
                  ZQDGMES, ZT1GMES, ZT2GMES, ZAMAX, ZQDAMAX, ZT1AMAX, ZT2AMAX,&
                  ZAH, ZBH, ZTAU_WOOD, ZINCREASE, ZTURNOVER,                  &
                  KSV, HSV, KBEQ, HSVO, KAEREQ, KSV_CHSBEG, KSV_CHSEND,       &
                  KSV_AERBEG, KSV_AEREND, HCH_NAMES, HAER_NAMES, KDSTEQ,      &
                  KSV_DSTBEG, KSV_DSTEND, KSLTEQ, KSV_SLTBEG, KSV_SLTEND,     &
                  HDSTNAMES, HSLTNAMES, HCHEM_SURF_FILE,                      &
                  ZSFDST, ZSFDSTM, ZSFSLT,                                    &
                  ZAOSIP, ZAOSIM, ZAOSJP, ZAOSJM, ZHO2IP, ZHO2IM, ZHO2JP,     &
                  ZHO2JM, ZZ0, ZZ0EFFIP, ZZ0EFFIM, ZZ0EFFJP, ZZ0EFFJM, ZZ0REL,&
                  PCLAY, PSAND, HPEDOTF,                                      &
                  ZCONDSAT, PMPOTSAT, PBCOEF, PWWILT, PWFC, PW33, PWSAT,      &
                  PTAUICE, PCGSAT, ZC1SAT, ZC2REF, ZC3, PC4B, PACOEF, PPCOEF, &
                  ZC4REF, ZPCPS, ZPLVTT, ZPLSTT,                              &
                  HSCOND, HISBA, PHCAPSOIL, PCONDDRY, PCONDSLD, HCPSURF,      &
                  ZDG, ZDROOT, ZDG2, ZROOTFRAC, ZRUNOFFD, ZDZG, ZDZDIF,       &
                  ZSOILWGHT, IWG_LAYER, KLAYER_HORT, KLAYER_DUN, ZD_ICE,      &
                  ZKSAT_ICE, PALBNIR_DRY, PALBVIS_DRY, PALBUV_DRY,            &
                  PALBNIR_WET, PALBVIS_WET, PALBUV_WET, ZBSLAI_NITRO,         &
                  ZCE_NITRO, ZCNA_NITRO, ZCF_NITRO                            )
!
ALLOCATE(PPCPS(SIZE(ZPCPS,1)))
PPCPS(:) = ZPCPS(:,1)
ALLOCATE(PPLVTT(SIZE(ZPLVTT,1)))
PPLVTT(:) = ZPLVTT(:,1)
ALLOCATE(PPLSTT(SIZE(ZPLSTT,1)))
PPLSTT(:) = ZPLSTT(:,1)
PD_ICE(:) = ZD_ICE(:,1)
ALLOCATE(PKSAT_ICE(SIZE(ZKSAT_ICE,1)))
PKSAT_ICE(:) = ZKSAT_ICE(:,1)
ALLOCATE(PDZG(SIZE(ZDZG,1),SIZE(ZDZG,2)))
PDZG(:,:) = ZDZG(:,:,1)
ALLOCATE(PDZDIF(SIZE(ZDZDIF,1),SIZE(ZDZDIF,2)))
PDZDIF(:,:) = ZDZDIF(:,:,1)
ALLOCATE(PSOILWGHT(SIZE(ZSOILWGHT,1),SIZE(ZSOILWGHT,2)))
PSOILWGHT(:,:) = ZSOILWGHT(:,:,1)
ALLOCATE(PCONDSAT(SIZE(ZCONDSAT,1),SIZE(ZCONDSAT,2)))
PCONDSAT(:,:) = ZCONDSAT(:,:,1)
ALLOCATE(PC1SAT(SIZE(ZC1SAT,1)))
PC1SAT(:) = ZC1SAT(:,1)
ALLOCATE(PC2REF(SIZE(ZC2REF,1)))
PC2REF(:) = ZC2REF(:,1)
ALLOCATE(PC4REF(SIZE(ZC4REF,1)))
PC4REF(:) = ZC4REF(:,1)
ALLOCATE(PC3(SIZE(ZC3,1),SIZE(ZC3,2)))
PC3(:,:) = ZC3(:,:,1)
ALLOCATE(PRUNOFFD(SIZE(ZRUNOFFD,1)))
PRUNOFFD(:) = ZRUNOFFD(:,1) 
ALLOCATE(PBSLAI_NITRO(SIZE(ZBSLAI_NITRO,1)))
PBSLAI_NITRO(:) =  ZBSLAI_NITRO(:,1)
ALLOCATE(PANMAX(SIZE(ZANMAX,1)))
PANMAX(:) = ZANMAX(:,1)
ALLOCATE(PFZERO(SIZE(ZFZERO,1)))
PFZERO(:) = ZFZERO(:,1)
ALLOCATE(PEPSO(SIZE(ZEPSO,1)))
PEPSO(:) = ZEPSO(:,1)
ALLOCATE(PGAMM(SIZE(ZGAMM,1)))
PGAMM(:) = ZGAMM(:,1)
ALLOCATE(PQDGAMM(SIZE(ZQDGAMM,1)))
PQDGAMM(:) = ZQDGAMM(:,1)
ALLOCATE(PQDGMES(SIZE(ZQDGMES,1)))
PQDGMES(:) = ZQDGMES(:,1)
ALLOCATE(PT1GMES(SIZE(ZT1GMES,1)))
PT1GMES(:) = ZT1GMES(:,1)
ALLOCATE(PT2GMES(SIZE(ZT2GMES,1)))
PT2GMES(:) = ZT2GMES(:,1)
ALLOCATE(PAMAX(SIZE(ZAMAX,1)))
PAMAX(:) = ZAMAX(:,1)
ALLOCATE(PQDAMAX(SIZE(ZQDAMAX,1)))
PQDAMAX(:) = ZQDAMAX(:,1)
ALLOCATE(PT1AMAX(SIZE(ZT1AMAX,1)))
PT1AMAX(:) = ZT1AMAX(:,1)
ALLOCATE(PT2AMAX(SIZE(ZT2AMAX,1)))
PT2AMAX(:) = ZT2AMAX(:,1)
ALLOCATE(PAH(SIZE(ZAH,1)))
PAH(:) = ZAH(:,1)
ALLOCATE(PBH(SIZE(ZBH,1)))
PBH(:) = ZBH(:,1)
!
IF (LHOOK) CALL DR_HOOK('INIT_VEG_PGD_GARDEN_n',1,ZHOOK_HANDLE)
!
END SUBROUTINE INIT_VEG_PGD_GARDEN_n
