SUBROUTINE MAKE_CHOICE_ARRAY(HPROGRAM, KPATCH, ODIM, HRECFM, PWORK, HDIR)
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
USE MODI_READ_SURF
!
IMPLICIT NONE
!
 CHARACTER(LEN=*), INTENT(IN) :: HPROGRAM
INTEGER, INTENT(IN) :: KPATCH
LOGICAL, INTENT(IN) :: ODIM
 CHARACTER(LEN=*), INTENT(IN) :: HRECFM
REAL, DIMENSION(:,:), INTENT(INOUT) :: PWORK
!
 CHARACTER(LEN=*), INTENT(IN), OPTIONAL :: HDIR
!
 CHARACTER(LEN=12) :: YRECFM
INTEGER :: JP, IRESP
 CHARACTER(LEN=1) :: YDIR
 CHARACTER(LEN=2) :: YPAT
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
IF (LHOOK) CALL DR_HOOK('MAKE_CHOICE_ARRAY',0,ZHOOK_HANDLE)
!
YDIR = 'H'
IF (PRESENT(HDIR)) YDIR = HDIR
!
IF (ODIM) THEN
  DO JP=1,KPATCH
    WRITE(YPAT,'(I2)') JP
    YRECFM=ADJUSTL(HRECFM(:LEN_TRIM(HRECFM)))//'P'//ADJUSTL(YPAT(:LEN_TRIM(YPAT)))
    CALL READ_SURF(HPROGRAM,YRECFM,PWORK(:,JP),IRESP,HDIR=YDIR)
  ENDDO
ELSE
  CALL READ_SURF(HPROGRAM,HRECFM,PWORK(:,:),IRESP,HDIR=YDIR)
ENDIF
!
IF (LHOOK) CALL DR_HOOK('MAKE_CHOICE_ARRAY',1,ZHOOK_HANDLE)
!
END SUBROUTINE MAKE_CHOICE_ARRAY

