!     #####################
      MODULE MODD_GR_BIOG_n
!     ######################
!
!!
!!!!****  *MODD_GR_BIOG_n* - Declaration of variables for biogenic emissions 
!
!!
!!**  IMPLICIT ARGUMENTS
!!    ------------------
!!      None 
!!
!!    REFERENCE
!!    ---------
!!    AUTHOR
!!    ------
!!      F. Solmon  *LA*
!!
!!    MODIFICATIONS
!!    -------------
!!    P. Tulet  30/07/03 externalisation of biogenics fluxes
!!     
!*       0.   DECLARATIONS
!             ----------
!
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE

TYPE GR_BIOG_t
!
!
!
!* Emission potential for isoprene and monoterpenes 
  REAL, DIMENSION(:), POINTER :: XISOPOT 
  REAL, DIMENSION(:), POINTER :: XMONOPOT 
!
!* Radiation at different level(cf Gauss) in the canopy
  REAL, DIMENSION(:,:,:),POINTER ::XIACAN ! PAR at 3 gauss level for each patch
!
!* XFISO  = isoprene emission flux (ppp.m.s-1)
!  XFMONO = monoterpenes emission flux (ppp m s-1)
  REAL, DIMENSION(:), POINTER :: XFISO, XFMONO
!SOILNOX
  REAL, DIMENSION(:), POINTER :: XNOFLUX
!
!
END TYPE GR_BIOG_t

TYPE(GR_BIOG_t), ALLOCATABLE, TARGET, SAVE :: GR_BIOG_MODEL(:)

TYPE(GR_BIOG_t), POINTER :: GR_BIOG => NULL()
!$OMP THREADPRIVATE(GR_BIOG)

CONTAINS

SUBROUTINE GR_BIOG_GOTO_MODEL(KFROM, KTO, LKFROM)
LOGICAL, INTENT(IN) :: LKFROM
INTEGER, INTENT(IN) :: KFROM, KTO
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
! Current model is set to model KTO
IF (LHOOK) CALL DR_HOOK('MODD_GR_BIOG_N:GR_BIOG_GOTO_MODEL',0,ZHOOK_HANDLE)

GR_BIOG => GR_BIOG_MODEL(KTO)

IF (LHOOK) CALL DR_HOOK('MODD_GR_BIOG_N:GR_BIOG_GOTO_MODEL',1,ZHOOK_HANDLE)

END SUBROUTINE GR_BIOG_GOTO_MODEL

SUBROUTINE GR_BIOG_ALLOC(KMODEL)
INTEGER, INTENT(IN) :: KMODEL
INTEGER :: J
REAL(KIND=JPRB) :: ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK("MODD_GR_BIOG_N:GR_BIOG_ALLOC",0,ZHOOK_HANDLE)
ALLOCATE(GR_BIOG_MODEL(KMODEL))
GR_BIOG => GR_BIOG_MODEL(KMODEL)
DO J=1,KMODEL
  NULLIFY(GR_BIOG_MODEL(J)%XISOPOT)
  NULLIFY(GR_BIOG_MODEL(J)%XMONOPOT)
  NULLIFY(GR_BIOG_MODEL(J)%XIACAN)
  NULLIFY(GR_BIOG_MODEL(J)%XFISO)
  NULLIFY(GR_BIOG_MODEL(J)%XFMONO)
  NULLIFY(GR_BIOG_MODEL(J)%XNOFLUX)
ENDDO
IF (LHOOK) CALL DR_HOOK("MODD_GR_BIOG_N:GR_BIOG_ALLOC",1,ZHOOK_HANDLE)
END SUBROUTINE GR_BIOG_ALLOC

SUBROUTINE GR_BIOG_DEALLO
REAL(KIND=JPRB) :: ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK("MODD_GR_BIOG_N:GR_BIOG_DEALLO",0,ZHOOK_HANDLE)
IF (ALLOCATED(GR_BIOG_MODEL)) DEALLOCATE(GR_BIOG_MODEL)
IF (ASSOCIATED(GR_BIOG)) NULLIFY(GR_BIOG)
IF (LHOOK) CALL DR_HOOK("MODD_GR_BIOG_N:GR_BIOG_DEALLO",1,ZHOOK_HANDLE)
END SUBROUTINE GR_BIOG_DEALLO

END MODULE MODD_GR_BIOG_n
