!     ############################
      MODULE MODD_DIAG_MISC_TEB_OPTION_n
!     ############################
!
!!****  *MODD_DIAG_MISC_TEB - declaration of packed surface parameters for TEB scheme
!!
!!    PURPOSE
!!    -------
!
!!
!!**  IMPLICIT ARGUMENTS
!!    ------------------
!!      None 
!!
!!    REFERENCE
!!    ---------
!!
!!    AUTHOR
!!    ------
!!      P. Le Moigne   *Meteo France*
!!
!!    MODIFICATIONS
!!    -------------
!!      Original       07/10/04
!!      C de Munck        02/13  adding runoff contributions for teb garden  
!!      V. Masson      06/2013 splits module in two
!
!
!*       0.   DECLARATIONS
!             ------------
!
!
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE

TYPE DIAG_MISC_TEB_OPTIONS_t
!------------------------------------------------------------------------------
!
  LOGICAL :: LSURF_MISC_BUDGET   ! flag for miscellaneous terms of teb scheme
  LOGICAL :: LSURF_EVAP_BUDGET   ! flag for all terms of evaporation
  LOGICAL :: LSURF_DIAG_ALBEDO   ! flag to write out diagnostic albedo  
!
END TYPE DIAG_MISC_TEB_OPTIONS_t
!

TYPE(DIAG_MISC_TEB_OPTIONS_t), ALLOCATABLE, TARGET, SAVE :: DIAG_MISC_TEB_OPTIONS_MODEL(:)

LOGICAL, POINTER :: LSURF_MISC_BUDGET=>NULL()
!$OMP THREADPRIVATE(LSURF_MISC_BUDGET)
LOGICAL, POINTER :: LSURF_EVAP_BUDGET=>NULL()
!$OMP THREADPRIVATE(LSURF_EVAP_BUDGET)
LOGICAL, POINTER :: LSURF_DIAG_ALBEDO=>NULL()
!$OMP THREADPRIVATE(LSURF_DIAG_ALBEDO)

CONTAINS

SUBROUTINE DIAG_MISC_TEB_OPTIONS_GOTO_MODEL(KFROM, KTO, LKFROM)
LOGICAL, INTENT(IN) :: LKFROM
INTEGER, INTENT(IN) :: KFROM, KTO
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
! Save current state for allocated arrays
IF (LKFROM) THEN
ENDIF
!
! Current model is set to model KTO
IF (LHOOK) CALL DR_HOOK('MODD_DIAG_MISC_TEB_N:DIAG_MISC_TEB_OPTIONS_GOTO_MODEL',0,ZHOOK_HANDLE)
!
LSURF_MISC_BUDGET=>DIAG_MISC_TEB_OPTIONS_MODEL(KTO)%LSURF_MISC_BUDGET
LSURF_EVAP_BUDGET=>DIAG_MISC_TEB_OPTIONS_MODEL(KTO)%LSURF_EVAP_BUDGET
LSURF_DIAG_ALBEDO=>DIAG_MISC_TEB_OPTIONS_MODEL(KTO)%LSURF_DIAG_ALBEDO
IF (LHOOK) CALL DR_HOOK('MODD_DIAG_MISC_TEB_N:DIAG_MISC_TEB_OPTIONS_GOTO_MODEL',1,ZHOOK_HANDLE)

END SUBROUTINE DIAG_MISC_TEB_OPTIONS_GOTO_MODEL

SUBROUTINE DIAG_MISC_TEB_OPTIONS_ALLOC(KMODEL)
INTEGER, INTENT(IN) :: KMODEL
INTEGER :: J
REAL(KIND=JPRB) :: ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK("MODD_DIAG_MISC_TEB_N:DIAG_MISC_TEB_OPTIONS_ALLOC",0,ZHOOK_HANDLE)
ALLOCATE(DIAG_MISC_TEB_OPTIONS_MODEL(KMODEL))
DIAG_MISC_TEB_OPTIONS_MODEL(:)%LSURF_MISC_BUDGET=.FALSE.
DIAG_MISC_TEB_OPTIONS_MODEL(:)%LSURF_EVAP_BUDGET=.FALSE.
DIAG_MISC_TEB_OPTIONS_MODEL(:)%LSURF_DIAG_ALBEDO=.FALSE.
IF (LHOOK) CALL DR_HOOK("MODD_DIAG_MISC_TEB_N:DIAG_MISC_TEB_OPTIONS_ALLOC",1,ZHOOK_HANDLE)
END SUBROUTINE DIAG_MISC_TEB_OPTIONS_ALLOC

SUBROUTINE DIAG_MISC_TEB_OPTIONS_DEALLO
REAL(KIND=JPRB) :: ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK("MODD_DIAG_MISC_TEB_N:DIAG_MISC_TEB_OPTIONS_DEALLO",0,ZHOOK_HANDLE)
IF (ALLOCATED(DIAG_MISC_TEB_OPTIONS_MODEL)) DEALLOCATE(DIAG_MISC_TEB_OPTIONS_MODEL)
IF (LHOOK) CALL DR_HOOK("MODD_DIAG_MISC_TEB_N:DIAG_MISC_TEB_OPTIONS_DEALLO",1,ZHOOK_HANDLE)
END SUBROUTINE DIAG_MISC_TEB_OPTIONS_DEALLO

END MODULE MODD_DIAG_MISC_TEB_OPTION_n
