!     ######################
      MODULE MODD_SURFEX_MPI
!     ######################
!
!!****  *MODD_SURFEX_MPI
!!
!!    PURPOSE
!!    -------
!
!!
!!**  IMPLICIT ARGUMENTS
!!    ------------------
!!      None 
!!
!!    REFERENCE
!!    ---------
!!
!!    AUTHOR
!!    ------
!!	S. Faroux   *Meteo France*
!!
!!    MODIFICATIONS
!!    -------------
!!      Original       04/06/12
!
!*       0.   DECLARATIONS
!             ------------
!
USE MODD_SURFEX_OMP, ONLY : NBLOCK
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE
!-------------------------------------------------------------------------------
!
INTEGER, DIMENSION(:), ALLOCATABLE :: NINDEX
INTEGER, DIMENSION(:), ALLOCATABLE :: NSIZE_TASK
!
INTEGER, DIMENSION(:,:), ALLOCATABLE :: NWG_LAYER_TOT
!
INTEGER :: NWG_SIZE
!
INTEGER :: NPROC = 1
INTEGER :: NRANK = 0
INTEGER :: NCOMM = -1
INTEGER :: NPIO  = 0
INTEGER :: NSIZE = 0
!
INTEGER :: IDX_R = 0
INTEGER :: IDX_W = 0
!
DOUBLE PRECISION, DIMENSION(5) :: XTIME_WRITE
!$OMP THREADPRIVATE(XTIME_WRITE)
DOUBLE PRECISION, DIMENSION(6) :: XTIME_CALC
!$OMP THREADPRIVATE(XTIME_CALC)
DOUBLE PRECISION :: XTIME_NPIO_READ=0
!$OMP THREADPRIVATE(XTIME_NPIO_READ)
DOUBLE PRECISION :: XTIME_NPIO_WRITE=0
!$OMP THREADPRIVATE(XTIME_NPIO_WRITE)
DOUBLE PRECISION :: XTIME_COMM_READ=0
!$OMP THREADPRIVATE(XTIME_COMM_READ)
DOUBLE PRECISION :: XTIME_CALC_READ=0
!$OMP THREADPRIVATE(XTIME_CALC_READ)
DOUBLE PRECISION :: XTIME_COMM_WRITE=0
!$OMP THREADPRIVATE(XTIME_COMM_WRITE)
DOUBLE PRECISION :: XTIME_CALC_WRITE=0
!$OMP THREADPRIVATE(XTIME_CALC_WRITE)
DOUBLE PRECISION :: XTIME_OMP_BARR=0
!$OMP THREADPRIVATE(XTIME_OMP_BARR)
!
DOUBLE PRECISION :: XTIME_INIT_SEA=0
!$OMP THREADPRIVATE(XTIME_INIT_SEA)
DOUBLE PRECISION :: XTIME_INIT_WATER=0
!$OMP THREADPRIVATE(XTIME_INIT_WATER)
DOUBLE PRECISION :: XTIME_INIT_NATURE=0
!$OMP THREADPRIVATE(XTIME_INIT_NATURE)
DOUBLE PRECISION :: XTIME_INIT_TOWN=0
!$OMP THREADPRIVATE(XTIME_INIT_TOWN)
!
DOUBLE PRECISION :: XTIME_SEA=0
!$OMP THREADPRIVATE(XTIME_SEA)
DOUBLE PRECISION :: XTIME_WATER=0
!$OMP THREADPRIVATE(XTIME_WATER)
DOUBLE PRECISION :: XTIME_NATURE=0
!$OMP THREADPRIVATE(XTIME_NATURE)
DOUBLE PRECISION :: XTIME_TOWN=0
!$OMP THREADPRIVATE(XTIME_TOWN)
!
CONTAINS
!
SUBROUTINE WLOG_MPI(HLOG,PLOG,KLOG,KLOG2,OLOG)
!
IMPLICIT NONE
!
 CHARACTER(LEN=*), INTENT(IN) :: HLOG
DOUBLE PRECISION, INTENT(IN),OPTIONAL :: PLOG
INTEGER, INTENT(IN), OPTIONAL :: KLOG
INTEGER, INTENT(IN), OPTIONAL :: KLOG2
LOGICAL, INTENT(IN), OPTIONAL :: OLOG
!
INTEGER :: IUNIT
!
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
IF (LHOOK) CALL DR_HOOK('MODD_SURFEX_MPI:WLOG_MPI',0,ZHOOK_HANDLE)
!
IUNIT=100000+NRANK
!
IF (PRESENT(OLOG)) THEN
  IF (PRESENT(PLOG)) THEN
    IF (PRESENT(KLOG)) THEN
      IF (PRESENT(KLOG2)) THEN
        WRITE(IUNIT,*) NBLOCK, HLOG, KLOG, KLOG2, PLOG, OLOG
      ELSE
        WRITE(IUNIT,*) NBLOCK, HLOG, KLOG, PLOG, OLOG
      ENDIF
    ELSE
      WRITE(IUNIT,*) NBLOCK, HLOG, PLOG, OLOG
    ENDIF
  ELSEIF (PRESENT(KLOG)) THEN
    IF (PRESENT(KLOG2)) THEN
      WRITE(IUNIT,*) NBLOCK, HLOG, KLOG, KLOG2, OLOG
    ELSE
      WRITE(IUNIT,*) NBLOCK, HLOG, KLOG, OLOG
    ENDIF
  ELSE
    WRITE(IUNIT,*) NBLOCK, HLOG, OLOG
  ENDIF
ELSEIF (PRESENT(PLOG)) THEN
  IF (PRESENT(KLOG)) THEN
    IF (PRESENT(KLOG2)) THEN
      WRITE(IUNIT,*) NBLOCK, HLOG, KLOG, KLOG2, PLOG
    ELSE
      WRITE(IUNIT,*) NBLOCK, HLOG, KLOG, PLOG
    ENDIF
  ELSE
    WRITE(IUNIT,*) NBLOCK, HLOG, PLOG
  ENDIF
ELSEIF (PRESENT(KLOG)) THEN
  IF (PRESENT(KLOG2)) THEN
    WRITE(IUNIT,*) NBLOCK, HLOG, KLOG, KLOG2
  ELSE
    WRITE(IUNIT,*) NBLOCK, HLOG, KLOG
  ENDIF
ELSE
  WRITE(IUNIT,*) NBLOCK, HLOG
ENDIF
!
IF (LHOOK) CALL DR_HOOK('MODD_SURFEX_MPI:WLOG_MPI',1,ZHOOK_HANDLE)
!
END SUBROUTINE WLOG_MPI
!
SUBROUTINE PREP_LOG_MPI
!
 CHARACTER(LEN=100) :: YNAME
INTEGER :: IUNIT
!
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
IF (LHOOK) CALL DR_HOOK('MODD_SURFEX_MPI:PREP_LOG_MPI',0,ZHOOK_HANDLE)
!
IF (NRANK>=10) THEN
  WRITE(YNAME,FMT='(A3,I2)') 'log',NRANK
ELSE
  WRITE(YNAME,FMT='(A3,I1)') 'log',NRANK
ENDIF
!
IUNIT=100000+NRANK
!
!$OMP SINGLE
OPEN(UNIT=IUNIT,FILE=YNAME,FORM='FORMATTED')
WRITE(IUNIT,*) "Log offline pour proc ",NRANK
!$OMP END SINGLE
!
IF (LHOOK) CALL DR_HOOK('MODD_SURFEX_MPI:PREP_LOG_MPI',1,ZHOOK_HANDLE)
!
END SUBROUTINE PREP_LOG_MPI
!
SUBROUTINE END_LOG_MPI
!
INTEGER :: IUNIT
!
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
IF (LHOOK) CALL DR_HOOK('MODD_SURFEX_MPI:END_LOG_MPI',0,ZHOOK_HANDLE)
!
IUNIT=100000+NRANK
!
!$OMP SINGLE
WRITE(IUNIT,*) "End log offline pour proc ",NRANK
CLOSE(UNIT=IUNIT)
!$OMP END SINGLE
!
IF (LHOOK) CALL DR_HOOK('MODD_SURFEX_MPI:END_LOG_MPI',1,ZHOOK_HANDLE)
!
END SUBROUTINE END_LOG_MPI
!-------------------------------------------------------------------------------
!
END MODULE MODD_SURFEX_MPI

