!     ################
      MODULE MODD_TEB_IRRIG_n
!     ################
!
!!****  *MODD_TEB_IRRIG_n - declaration of surface parameters for urban canopy
!!
!!    PURPOSE
!!    -------
!     Declaration of surface parameters
!
!!
!!**  IMPLICIT ARGUMENTS
!!    ------------------
!!      None 
!!
!!    REFERENCE
!!    ---------
!!
!!    AUTHOR
!!    ------
!!      V. Masson   *Meteo France*
!!
!!    MODIFICATIONS
!!    -------------
!!      Original       07/2006
!
!*       0.   DECLARATIONS
!             ------------
!
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE

TYPE TEB_IRRIG_t
!
  LOGICAL                        :: LTEB_IRRIG        ! flag to use irrigation for gardens or greenroofs
  LOGICAL                        :: LPAR_GD_IRRIG     ! flag to use prescribed irrigation for gardens
  LOGICAL                        :: LPAR_GR_IRRIG     ! flag to use prescribed irrigation for greenroofs
  LOGICAL                        :: LPAR_RD_IRRIG     ! flag to use prescribed irrigation for roads
  REAL,    POINTER, DIMENSION(:) :: XGD_START_MONTH   ! gardens : start month for irrigation (included)
  REAL,    POINTER, DIMENSION(:) :: XGD_END_MONTH     ! gardens : end   month for irrigation (included)
  REAL,    POINTER, DIMENSION(:) :: XGD_START_HOUR    ! gardens : start solar hour for irrigation (included, hour)
  REAL,    POINTER, DIMENSION(:) :: XGD_END_HOUR      ! gardens : end   solar hour for irrigation (excluded, hour)
  REAL,    POINTER, DIMENSION(:) :: XGD_24H_IRRIG     ! gardens : total irrigation over 24 hours (kg/m2)
  REAL,    POINTER, DIMENSION(:) :: XGR_START_MONTH   ! greenroofs : start month for irrigation (included)
  REAL,    POINTER, DIMENSION(:) :: XGR_END_MONTH     ! greenroofs : end   month for irrigation (included)
  REAL,    POINTER, DIMENSION(:) :: XGR_START_HOUR    ! greenroofs : start solar hour for irrigation (included, hour)
  REAL,    POINTER, DIMENSION(:) :: XGR_END_HOUR      ! greenroofs : end   solar hour for irrigation (excluded, hour)
  REAL,    POINTER, DIMENSION(:) :: XGR_24H_IRRIG     ! greenroofs : total irrigation over 24 hours (kg/m2)
  REAL,    POINTER, DIMENSION(:) :: XRD_START_MONTH   ! roads : start month for irrigation (included)
  REAL,    POINTER, DIMENSION(:) :: XRD_END_MONTH     ! roads : end   month for irrigation (included)
  REAL,    POINTER, DIMENSION(:) :: XRD_START_HOUR    ! roads : start solar hour for irrigation (included, hour)
  REAL,    POINTER, DIMENSION(:) :: XRD_END_HOUR      ! roads : end   solar hour for irrigation (excluded, hour)
  REAL,    POINTER, DIMENSION(:) :: XRD_24H_IRRIG     ! roads : total irrigation over 24 hours (kg/m2)
!
END TYPE TEB_IRRIG_t

TYPE(TEB_IRRIG_t), ALLOCATABLE, TARGET, SAVE :: TEB_IRRIG_MODEL(:)

!RJ: missing null() for logicals that create ICE on ifort with '-fpic -openmp -openmp-threadprivate=compat'
LOGICAL, POINTER               :: LTEB_IRRIG=>NULL()
!$OMP THREADPRIVATE(LTEB_IRRIG)
LOGICAL, POINTER               :: LPAR_GD_IRRIG=>NULL()
!$OMP THREADPRIVATE(LPAR_GD_IRRIG)
LOGICAL, POINTER               :: LPAR_GR_IRRIG=>NULL()
!$OMP THREADPRIVATE(LPAR_GR_IRRIG)
LOGICAL, POINTER               :: LPAR_RD_IRRIG=>NULL()
!$OMP THREADPRIVATE(LPAR_RD_IRRIG)
REAL,    POINTER, DIMENSION(:) :: XGD_START_MONTH=>NULL()
!$OMP THREADPRIVATE(XGD_START_MONTH)
REAL,    POINTER, DIMENSION(:) :: XGD_END_MONTH=>NULL()
!$OMP THREADPRIVATE(XGD_END_MONTH)
REAL,    POINTER, DIMENSION(:) :: XGD_START_HOUR=>NULL()
!$OMP THREADPRIVATE(XGD_START_HOUR)
REAL,    POINTER, DIMENSION(:) :: XGD_END_HOUR=>NULL()
!$OMP THREADPRIVATE(XGD_END_HOUR)
REAL,    POINTER, DIMENSION(:) :: XGD_24H_IRRIG=>NULL()
!$OMP THREADPRIVATE(XGD_24H_IRRIG)
REAL,    POINTER, DIMENSION(:) :: XGR_START_MONTH=>NULL()
!$OMP THREADPRIVATE(XGR_START_MONTH)
REAL,    POINTER, DIMENSION(:) :: XGR_END_MONTH=>NULL()
!$OMP THREADPRIVATE(XGR_END_MONTH)
REAL,    POINTER, DIMENSION(:) :: XGR_START_HOUR=>NULL()
!$OMP THREADPRIVATE(XGR_START_HOUR)
REAL,    POINTER, DIMENSION(:) :: XGR_END_HOUR=>NULL()
!$OMP THREADPRIVATE(XGR_END_HOUR)
REAL,    POINTER, DIMENSION(:) :: XGR_24H_IRRIG=>NULL()
!$OMP THREADPRIVATE(XGR_24H_IRRIG)
REAL,    POINTER, DIMENSION(:) :: XRD_START_MONTH=>NULL()
!$OMP THREADPRIVATE(XRD_START_MONTH)
REAL,    POINTER, DIMENSION(:) :: XRD_END_MONTH=>NULL()
!$OMP THREADPRIVATE(XRD_END_MONTH)
REAL,    POINTER, DIMENSION(:) :: XRD_START_HOUR=>NULL()
!$OMP THREADPRIVATE(XRD_START_HOUR)
REAL,    POINTER, DIMENSION(:) :: XRD_END_HOUR=>NULL()
!$OMP THREADPRIVATE(XRD_END_HOUR)
REAL,    POINTER, DIMENSION(:) :: XRD_24H_IRRIG=>NULL()
!$OMP THREADPRIVATE(XRD_24H_IRRIG)

CONTAINS

SUBROUTINE TEB_IRRIG_GOTO_MODEL(KFROM, KTO, LKFROM)
LOGICAL, INTENT(IN) :: LKFROM
INTEGER, INTENT(IN) :: KFROM, KTO
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
! Save current state for allocated arrays
IF (LKFROM) THEN
TEB_IRRIG_MODEL(KFROM)%XGD_START_MONTH=>XGD_START_MONTH
TEB_IRRIG_MODEL(KFROM)%XGD_END_MONTH=>XGD_END_MONTH
TEB_IRRIG_MODEL(KFROM)%XGD_START_HOUR=>XGD_START_HOUR
TEB_IRRIG_MODEL(KFROM)%XGD_END_HOUR=>XGD_END_HOUR
TEB_IRRIG_MODEL(KFROM)%XGD_24H_IRRIG=>XGD_24H_IRRIG
TEB_IRRIG_MODEL(KFROM)%XGR_START_MONTH=>XGR_START_MONTH
TEB_IRRIG_MODEL(KFROM)%XGR_END_MONTH=>XGR_END_MONTH
TEB_IRRIG_MODEL(KFROM)%XGR_START_HOUR=>XGR_START_HOUR
TEB_IRRIG_MODEL(KFROM)%XGR_END_HOUR=>XGR_END_HOUR
TEB_IRRIG_MODEL(KFROM)%XGR_24H_IRRIG=>XGR_24H_IRRIG
TEB_IRRIG_MODEL(KFROM)%XRD_START_MONTH=>XRD_START_MONTH
TEB_IRRIG_MODEL(KFROM)%XRD_END_MONTH=>XRD_END_MONTH
TEB_IRRIG_MODEL(KFROM)%XRD_START_HOUR=>XRD_START_HOUR
TEB_IRRIG_MODEL(KFROM)%XRD_END_HOUR=>XRD_END_HOUR
TEB_IRRIG_MODEL(KFROM)%XRD_24H_IRRIG=>XRD_24H_IRRIG
ENDIF
!
! Current model is set to model KTO
IF (LHOOK) CALL DR_HOOK('MODD_TEB_IRRIG_N:TEB_IRRIG_GOTO_MODEL',0,ZHOOK_HANDLE)
LTEB_IRRIG=>TEB_IRRIG_MODEL(KTO)%LTEB_IRRIG
LPAR_GD_IRRIG=>TEB_IRRIG_MODEL(KTO)%LPAR_GD_IRRIG
LPAR_GR_IRRIG=>TEB_IRRIG_MODEL(KTO)%LPAR_GR_IRRIG
LPAR_RD_IRRIG=>TEB_IRRIG_MODEL(KTO)%LPAR_RD_IRRIG
XGD_START_MONTH=>TEB_IRRIG_MODEL(KTO)%XGD_START_MONTH
XGD_END_MONTH=>TEB_IRRIG_MODEL(KTO)%XGD_END_MONTH
XGD_START_HOUR=>TEB_IRRIG_MODEL(KTO)%XGD_START_HOUR
XGD_END_HOUR=>TEB_IRRIG_MODEL(KTO)%XGD_END_HOUR
XGD_24H_IRRIG=>TEB_IRRIG_MODEL(KTO)%XGD_24H_IRRIG
XGR_START_MONTH=>TEB_IRRIG_MODEL(KTO)%XGR_START_MONTH
XGR_END_MONTH=>TEB_IRRIG_MODEL(KTO)%XGR_END_MONTH
XGR_START_HOUR=>TEB_IRRIG_MODEL(KTO)%XGR_START_HOUR
XGR_END_HOUR=>TEB_IRRIG_MODEL(KTO)%XGR_END_HOUR
XGR_24H_IRRIG=>TEB_IRRIG_MODEL(KTO)%XGR_24H_IRRIG
XRD_START_MONTH=>TEB_IRRIG_MODEL(KTO)%XRD_START_MONTH
XRD_END_MONTH=>TEB_IRRIG_MODEL(KTO)%XRD_END_MONTH
XRD_START_HOUR=>TEB_IRRIG_MODEL(KTO)%XRD_START_HOUR
XRD_END_HOUR=>TEB_IRRIG_MODEL(KTO)%XRD_END_HOUR
XRD_24H_IRRIG=>TEB_IRRIG_MODEL(KTO)%XRD_24H_IRRIG
IF (LHOOK) CALL DR_HOOK('MODD_TEB_IRRIG_N:TEB_IRRIG_GOTO_MODEL',1,ZHOOK_HANDLE)

END SUBROUTINE TEB_IRRIG_GOTO_MODEL

SUBROUTINE TEB_IRRIG_ALLOC(KMODEL)
INTEGER, INTENT(IN) :: KMODEL
INTEGER :: J
REAL(KIND=JPRB) :: ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK("MODD_TEB_IRRIG_N:TEB_IRRIG_ALLOC",0,ZHOOK_HANDLE)
ALLOCATE(TEB_IRRIG_MODEL(KMODEL))
DO J=1,KMODEL
  NULLIFY(TEB_IRRIG_MODEL(J)%XGD_START_MONTH)
  NULLIFY(TEB_IRRIG_MODEL(J)%XGD_END_MONTH)
  NULLIFY(TEB_IRRIG_MODEL(J)%XGD_START_HOUR)
  NULLIFY(TEB_IRRIG_MODEL(J)%XGD_END_HOUR)
  NULLIFY(TEB_IRRIG_MODEL(J)%XGD_24H_IRRIG)
  NULLIFY(TEB_IRRIG_MODEL(J)%XGR_START_MONTH)
  NULLIFY(TEB_IRRIG_MODEL(J)%XGR_END_MONTH)
  NULLIFY(TEB_IRRIG_MODEL(J)%XGR_START_HOUR)
  NULLIFY(TEB_IRRIG_MODEL(J)%XGR_END_HOUR)
  NULLIFY(TEB_IRRIG_MODEL(J)%XGR_24H_IRRIG)
  NULLIFY(TEB_IRRIG_MODEL(J)%XRD_START_MONTH)
  NULLIFY(TEB_IRRIG_MODEL(J)%XRD_END_MONTH)
  NULLIFY(TEB_IRRIG_MODEL(J)%XRD_START_HOUR)
  NULLIFY(TEB_IRRIG_MODEL(J)%XRD_END_HOUR)
  NULLIFY(TEB_IRRIG_MODEL(J)%XRD_24H_IRRIG)
ENDDO
TEB_IRRIG_MODEL(:)%LTEB_IRRIG = .FALSE.
TEB_IRRIG_MODEL(:)%LPAR_GD_IRRIG = .FALSE.
TEB_IRRIG_MODEL(:)%LPAR_GR_IRRIG = .FALSE.
TEB_IRRIG_MODEL(:)%LPAR_RD_IRRIG = .FALSE.
IF (LHOOK) CALL DR_HOOK("MODD_TEB_IRRIG_N:TEB_IRRIG_ALLOC",1,ZHOOK_HANDLE)
END SUBROUTINE TEB_IRRIG_ALLOC

SUBROUTINE TEB_IRRIG_DEALLO
REAL(KIND=JPRB) :: ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK("MODD_TEB_IRRIG_N:TEB_IRRIG_DEALLO",0,ZHOOK_HANDLE)
IF (ALLOCATED(TEB_IRRIG_MODEL)) DEALLOCATE(TEB_IRRIG_MODEL)
IF (LHOOK) CALL DR_HOOK("MODD_TEB_IRRIG_N:TEB_IRRIG_DEALLO",1,ZHOOK_HANDLE)
END SUBROUTINE TEB_IRRIG_DEALLO

END MODULE MODD_TEB_IRRIG_n
