!     ################
      MODULE MODD_ISBA_CANOPY_n
!     ################
!
!!****  *MODD_ISBA_CANOPY_n - declaration of surface parameters for urban canopy
!!
!!    PURPOSE
!!    -------
!     Declaration of surface parameters
!
!!
!!**  IMPLICIT ARGUMENTS
!!    ------------------
!!      None 
!!
!!    REFERENCE
!!    ---------
!!
!!    AUTHOR
!!    ------
!!      V. Masson   *Meteo France*
!!
!!    MODIFICATIONS
!!    -------------
!!      Original       07/2006
!
!*       0.   DECLARATIONS
!             ------------
!
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE

TYPE ISBA_CANOPY_t
!
  INTEGER                       :: NLVL ! number      of levels in canopy
  REAL, POINTER, DIMENSION(:,:) :: XZ   ! height of middle of each level grid   (m)
  REAL, POINTER, DIMENSION(:,:) :: XU   ! wind        at each level in canopy   (m/s)
  REAL, POINTER, DIMENSION(:,:) :: XT   ! temperature at each level in canopy   (m/s)
  REAL, POINTER, DIMENSION(:,:) :: XQ   ! humidity    at each level in canopy   (kg/m3)
  REAL, POINTER, DIMENSION(:,:) :: XTKE ! Tke         at each level in canopy   (m2/s2)
  REAL, POINTER, DIMENSION(:)   :: XLMO ! Monin-Obhukov length                  (m)
  REAL, POINTER, DIMENSION(:,:) :: XP   ! pressure    at each level in canopy   (kg/m3)
!
  REAL, POINTER, DIMENSION(:,:) :: XDZ  ! depth       of each level in canopy   (m)
  REAL, POINTER, DIMENSION(:,:) :: XZF  ! height of bottom of each level grid   (m)
  REAL, POINTER, DIMENSION(:,:) :: XDZF ! depth between  each level in canopy   (m)
!
END TYPE ISBA_CANOPY_t

TYPE(ISBA_CANOPY_t), ALLOCATABLE, TARGET, SAVE :: ISBA_CANOPY_MODEL(:)

TYPE(ISBA_CANOPY_t), POINTER :: ISBA_CANOPY => NULL()
!$OMP THREADPRIVATE(ISBA_CANOPY)

CONTAINS

SUBROUTINE ISBA_CANOPY_GOTO_MODEL(KFROM, KTO, LKFROM)
LOGICAL, INTENT(IN) :: LKFROM
INTEGER, INTENT(IN) :: KFROM, KTO
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
! Current model is set to model KTO
IF (LHOOK) CALL DR_HOOK('MODD_ISBA_CANOPY_N:ISBA_CANOPY_GOTO_MODEL',0,ZHOOK_HANDLE)

ISBA_CANOPY => ISBA_CANOPY_MODEL(KTO)

IF (LHOOK) CALL DR_HOOK('MODD_ISBA_CANOPY_N:ISBA_CANOPY_GOTO_MODEL',1,ZHOOK_HANDLE)

END SUBROUTINE ISBA_CANOPY_GOTO_MODEL

SUBROUTINE ISBA_CANOPY_ALLOC(KMODEL)
INTEGER, INTENT(IN) :: KMODEL
INTEGER :: J
REAL(KIND=JPRB) :: ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK("MODD_ISBA_CANOPY_N:ISBA_CANOPY_ALLOC",0,ZHOOK_HANDLE)
ALLOCATE(ISBA_CANOPY_MODEL(KMODEL))
ISBA_CANOPY => ISBA_CANOPY_MODEL(KMODEL)
DO J=1,KMODEL
  NULLIFY(ISBA_CANOPY_MODEL(J)%XZ)
  NULLIFY(ISBA_CANOPY_MODEL(J)%XU)
  NULLIFY(ISBA_CANOPY_MODEL(J)%XT)
  NULLIFY(ISBA_CANOPY_MODEL(J)%XQ)
  NULLIFY(ISBA_CANOPY_MODEL(J)%XTKE)
  NULLIFY(ISBA_CANOPY_MODEL(J)%XLMO)
  NULLIFY(ISBA_CANOPY_MODEL(J)%XP)
  NULLIFY(ISBA_CANOPY_MODEL(J)%XDZ)
  NULLIFY(ISBA_CANOPY_MODEL(J)%XZF)
  NULLIFY(ISBA_CANOPY_MODEL(J)%XDZF)
ENDDO
ISBA_CANOPY_MODEL(:)%NLVL=0
IF (LHOOK) CALL DR_HOOK("MODD_ISBA_CANOPY_N:ISBA_CANOPY_ALLOC",1,ZHOOK_HANDLE)
END SUBROUTINE ISBA_CANOPY_ALLOC

SUBROUTINE ISBA_CANOPY_DEALLO
REAL(KIND=JPRB) :: ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK("MODD_ISBA_CANOPY_N:ISBA_CANOPY_DEALLO",0,ZHOOK_HANDLE)
IF (ALLOCATED(ISBA_CANOPY_MODEL)) DEALLOCATE(ISBA_CANOPY_MODEL)
IF (ASSOCIATED(ISBA_CANOPY)) NULLIFY(ISBA_CANOPY)
IF (LHOOK) CALL DR_HOOK("MODD_ISBA_CANOPY_N:ISBA_CANOPY_DEALLO",1,ZHOOK_HANDLE)
END SUBROUTINE ISBA_CANOPY_DEALLO

END MODULE MODD_ISBA_CANOPY_n
