!     ##################
      MODULE MODD_OCEAN_REL_n
!     ##################
!
!     Author : P. Peyrille
!!    Date: 01/2012
!! 
!!  declaration of relaxation field, flag for ocean model
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE
!
TYPE OCEAN_REL_t
!
 REAL                :: XTAU_REL   ! Time of relaxation  (s)
!
 REAL                :: XQCORR     ! correction coefficient  for surface fluxes  (BArnier et al. 1998) typcial val: 100.
!
 LOGICAL                            :: LREL_CUR   ! flag for  relxation on current
 LOGICAL                            :: LREL_TS    ! flag for relaxation on ocean temperature
 LOGICAL                            :: LFLUX_NULL ! Flag for testing zero  incoming flux at the surface 
!
 LOGICAL                            :: LFLX_CORR  ! Flag for  flux  correction 
 LOGICAL                            :: LDIAPYCNAL ! Flag for diapycnal mixing activation
!
 REAL, POINTER, DIMENSION(:,:) :: XSEAU_REL  ! ref. U current  profile (C)
 REAL, POINTER, DIMENSION(:,:) :: XSEAV_REL  ! ref. V current  profile (C)
 REAL, POINTER, DIMENSION(:,:) :: XSEAT_REL  ! ref. temperature  profile (C)
 REAL, POINTER, DIMENSION(:,:) :: XSEAS_REL  ! ---- salinity   ---------- (%)
!
END TYPE OCEAN_REL_t
!
TYPE(OCEAN_REL_t), ALLOCATABLE, TARGET, SAVE :: OCEAN_REL_MODEL(:)

TYPE(OCEAN_REL_t), POINTER :: OCEAN_REL => NULL()
!$OMP THREADPRIVATE(OCEAN_REL)

CONTAINS
!
SUBROUTINE OCEAN_REL_GOTO_MODEL(KFROM, KTO, LKFROM)
LOGICAL, INTENT(IN) :: LKFROM
INTEGER, INTENT(IN) :: KFROM, KTO
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
! Current model is set to model KTO
IF (LHOOK) CALL DR_HOOK('MODD_OCEAN_REL_N:OCEAN_REL_GOTO_MODEL',0,ZHOOK_HANDLE)

OCEAN_REL => OCEAN_REL_MODEL(KTO)

IF (LHOOK) CALL DR_HOOK('MODD_OCEAN_REL_N:OCEAN_REL_GOTO_MODEL',1,ZHOOK_HANDLE)
!
END SUBROUTINE OCEAN_REL_GOTO_MODEL
!
SUBROUTINE OCEAN_REL_ALLOC(KMODEL)
INTEGER, INTENT(IN) :: KMODEL
INTEGER :: J
REAL(KIND=JPRB) :: ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK("MODD_OCEAN_REL_N:OCEAN_REL_ALLOC",0,ZHOOK_HANDLE)
ALLOCATE(OCEAN_REL_MODEL(KMODEL))
OCEAN_REL => OCEAN_REL_MODEL(KMODEL)
DO J=1,KMODEL
  NULLIFY(OCEAN_REL_MODEL(J)%XSEAT_REL)
  NULLIFY(OCEAN_REL_MODEL(J)%XSEAS_REL)
  NULLIFY(OCEAN_REL_MODEL(J)%XSEAU_REL)
  NULLIFY(OCEAN_REL_MODEL(J)%XSEAV_REL)
ENDDO
OCEAN_REL_MODEL(:)%XTAU_REL=0.
OCEAN_REL_MODEL(:)%XQCORR=0.
OCEAN_REL_MODEL(:)%LREL_CUR=.FALSE.
OCEAN_REL_MODEL(:)%LREL_TS=.FALSE.
OCEAN_REL_MODEL(:)%LFLUX_NULL=.FALSE.
OCEAN_REL_MODEL(:)%LFLX_CORR=.FALSE.
OCEAN_REL_MODEL(:)%LDIAPYCNAL=.FALSE.
!
IF (LHOOK) CALL DR_HOOK("MODD_OCEAN_REL_N:OCEAN_REL_ALLOC",1,ZHOOK_HANDLE)
END SUBROUTINE OCEAN_REL_ALLOC
!
SUBROUTINE OCEAN_REL_DEALLO
REAL(KIND=JPRB) :: ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK("MODD_OCEAN_REL_N:OCEAN_DEALLO_REL",0,ZHOOK_HANDLE)
IF (ALLOCATED(OCEAN_REL_MODEL)) DEALLOCATE(OCEAN_REL_MODEL)
IF (ASSOCIATED(OCEAN_REL)) NULLIFY(OCEAN_REL)
IF (LHOOK) CALL DR_HOOK("MODD_OCEAN_REL_N:OCEAN_REL_DEALLO",1,ZHOOK_HANDLE)
END SUBROUTINE OCEAN_REL_DEALLO
!
END MODULE MODD_OCEAN_REL_n
