!##################
MODULE MODD_TEB_VEG_n
!##################
!
!!****  *MODD_ISBA - declaration of packed surface parameters for ISBA scheme
!!
!!    PURPOSE
!!    -------
!
!!
!!**  IMPLICIT ARGUMENTS
!!    ------------------
!!      None 
!!
!!    REFERENCE
!!    ---------
!!
!!    AUTHOR
!!    ------
!!      A. Boone   *Meteo France*
!!
!!    MODIFICATIONS
!!    -------------
!!      Original       20/09/02
!!      A.L. Gibelin    04/2009 : BIOMASS and RESP_BIOMASS arrays 
!!      A.L. Gibelin    04/2009 : TAU_WOOD for NCB option 
!!      A.L. Gibelin    05/2009 : Add carbon spinup
!!      A.L. Gibelin    06/2009 : Soil carbon variables for CNT option
!!      A.L. Gibelin    07/2009 : Suppress RDK and transform GPP as a diagnostic
!!      A.L. Gibelin    07/2009 : Suppress PPST and PPSTF as outputs
!!      P. Samuelsson   02/2012 : MEB
!!
!-------------------------------------------------------------------------------
!
!*       0.   DECLARATIONS
!             ------------
!
USE MODD_TEB_VEG_PARAM_n
!
USE MODD_ISBA_OPTIONS_n
USE MODD_ISBA_PGD_n
USE MODD_ISBA_PARAM1_n
USE MODD_ISBA_INIT1_n
USE MODD_ISBA1_n, ONLY : ISBA_PROG_1P_t, ISBA_PROG_1P_INIT
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE
!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
TYPE TEB_VEG_PROG_t
  !
  TYPE(ISBA_PROG_1P_t), POINTER :: ALP(:) => NULL()
  TYPE(ISBA_PROG_1P_t), POINTER :: CUR => NULL()
  !
END TYPE TEB_VEG_PROG_t
!
TYPE TEB_VEG_t
!
TYPE(ISBA_OPTIONS_t) :: O
TYPE(ISBA_PGD_t) :: P
TYPE(ISBA_INIT_1P_t) :: I
TYPE(ISBA_INIT_PGD_1P_t) :: IP
!
TYPE(TEB_VEG_PARAM_t) :: M
TYPE(TEB_VEG_PROG_t) :: R
!
END TYPE TEB_VEG_t
!
CONTAINS
!
SUBROUTINE TEB_VEG_PROG_GOTO_PATCH(YTEB_VEG_PROG,KTO_PATCH)
TYPE(TEB_VEG_PROG_t), INTENT(INOUT) :: YTEB_VEG_PROG
INTEGER, INTENT(IN) :: KTO_PATCH
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
! Current patch is set to patch KTO_PATCH
IF (LHOOK) CALL DR_HOOK('MODD_TEB_VEG_N:TEB_VEG_PROG_GOTO_PATCH',0,ZHOOK_HANDLE)

YTEB_VEG_PROG%CUR => YTEB_VEG_PROG%ALP(KTO_PATCH)

IF (LHOOK) CALL DR_HOOK('MODD_TEB_VEG_N:TEB_VEG_PROG_GOTO_PATCH',1,ZHOOK_HANDLE)
!
END SUBROUTINE TEB_VEG_PROG_GOTO_PATCH

SUBROUTINE TEB_VEG_PROG_INIT(YTEB_VEG_PROG,KPATCH)
TYPE(TEB_VEG_PROG_t), INTENT(INOUT) :: YTEB_VEG_PROG
INTEGER, INTENT(IN) :: KPATCH
INTEGER :: JP
REAL(KIND=JPRB) :: ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK("MODD_TEB_VEG_N:TEB_VEG_PROG_INIT",0,ZHOOK_HANDLE)
 ALLOCATE(YTEB_VEG_PROG%ALP(KPATCH))
 YTEB_VEG_PROG%CUR => YTEB_VEG_PROG%ALP(1)
DO JP=1,KPATCH
  CALL ISBA_PROG_1P_INIT(YTEB_VEG_PROG%ALP(JP))
ENDDO 
IF (LHOOK) CALL DR_HOOK("MODD_TEB_VEG_N:TEB_VEG_PROG_INIT",1,ZHOOK_HANDLE)
END SUBROUTINE TEB_VEG_PROG_INIT
!
SUBROUTINE TEB_VEG_INIT(YTEB_VEG,KPATCH)
TYPE(TEB_VEG_t), INTENT(INOUT) :: YTEB_VEG
INTEGER, INTENT(IN) :: KPATCH
INTEGER :: JP
REAL(KIND=JPRB) :: ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK("MODD_TEB_VEG_N:TEB_VEG_INIT",0,ZHOOK_HANDLE)
!
CALL TEB_VEG_PROG_INIT(YTEB_VEG%R,KPATCH)
CALL TEB_VEG_PARAM_TIME_INIT(YTEB_VEG%M%T,KPATCH)
!
CALL ISBA_INIT_1P_INIT(YTEB_VEG%I)
CALL ISBA_PARAM_1P_INIT(YTEB_VEG%M%X,YTEB_VEG%M%M,YTEB_VEG%M%A,YTEB_VEG%M%I)
CALL ISBA_PGD_INIT(YTEB_VEG%P)
CALL ISBA_OPTIONS_INIT(YTEB_VEG%O)
!
IF (LHOOK) CALL DR_HOOK("MODD_TEB_VEG_N:TEB_VEG_INIT",1,ZHOOK_HANDLE)
END SUBROUTINE TEB_VEG_INIT
!
END MODULE MODD_TEB_VEG_n
