MODULE MODD_SURFEX_n
!
USE MODD_AGRI_n, ONLY : AGRI_t
USE MODD_BEM_OPTION_n, ONLY : BEM_OPTIONS_t
USE MODD_BLD_DESCRIPTION_n, ONLY : BLD_DESC_t
USE MODD_CH_EMIS_FIELD_n, ONLY : CH_EMIS_FIELD_t
USE MODD_CH_FLAKE_n, ONLY : CH_FLAKE_t
USE MODD_CH_ISBA_n, ONLY : CH_ISBA_t
USE MODD_CH_SEAFLUX_n, ONLY : CH_SEAFLUX_t
USE MODD_CH_SNAP_n, ONLY : CH_EMIS_SNAP_t
USE MODD_CH_SURF_n, ONLY : CH_SURF_t
USE MODD_CH_TEB_n, ONLY : CH_TEB_t
USE MODD_CH_WATFLUX_n, ONLY : CH_WATFLUX_t
USE MODD_DATA_BEM_n, ONLY : DATA_BEM_t
USE MODD_DATA_COVER_n, ONLY : DATA_COVER_t
USE MODD_DATA_ISBA_n, ONLY : DATA_ISBA_t
USE MODD_DATA_SEAFLUX_n, ONLY : DATA_SEAFLUX_t
USE MODD_DATA_TEB_n, ONLY : DATA_TEB_t
USE MODD_DATA_TSZ0_n, ONLY : DATA_TSZ0_t
USE MODD_DIAG_EVAP_ISBA_n, ONLY : DIAG_EVAP_ISBA_t, DIAG_EVAP_ISBA_PATCH_t
USE MODD_DIAG_n, ONLY : DIAG_t, DIAG_PATCH_t, DIAG_OPTIONS_t
USE MODD_DIAG_MISC_FLAKE_n, ONLY : DIAG_MISC_FLAKE_t
USE MODD_DIAG_MISC_ISBA_n, ONLY : DIAG_MISC_ISBA_t, DIAG_MISC_ISBA_PATCH_t
USE MODD_DIAG_MISC_TEB_OPTION_n, ONLY : DIAG_MISC_TEB_OPTIONS_t
USE MODD_DIAG_OCEAN_n, ONLY : DIAG_OCEAN_t
USE MODD_DIAG_MISC_SEAICE_n, ONLY : DIAG_MISC_SEAICE_t
USE MODD_DIAG_UTCI_TEB_n, ONLY : DIAG_UTCI_TEB_t
USE MODD_DST_n, ONLY : DST_t
USE MODD_DUMMY_SURF_FIELDS_n, ONLY : DUMMY_SURF_FIELDS_t
USE MODD_EMIS_GR_FIELD_n, ONLY : EMIS_GR_FIELD_t
USE MODD_GRID_n, ONLY : GRID_t
USE MODD_FLAKE_n, ONLY : FLAKE_t
USE MODD_GR_BIOG_n, ONLY : GR_BIOG_t
USE MODD_IDEAL_n, ONLY : IDEAL_t
USE MODD_CANOPY_n, ONLY : CANOPY_t
USE MODD_ISBA_n, ONLY : ISBA_t
USE MODD_TEB_VEG_n, ONLY : TEB_VEG_t
USE MODD_OCEAN_n, ONLY : OCEAN_t
USE MODD_OCEAN_REL_n, ONLY : OCEAN_REL_t
USE MODD_PACK_CH_ISBA, ONLY : PACK_CH_ISBA_t
USE MODD_PACK_DIAG_ISBA, ONLY : PACK_DIAG_ISBA_t
USE MODD_PACK_ISBA, ONLY : PACK_ISBA_t
USE MODD_SEAFLUX_n, ONLY : SEAFLUX_t
USE MODD_SLT_n, ONLY : SLT_t
USE MODD_SURF_ATM_GRID_n, ONLY : SURF_ATM_GRID_t
USE MODD_SURF_ATM_n, ONLY : SURF_ATM_t
USE MODD_SSO_n, ONLY : SSO_t
USE MODD_SV_n, ONLY : SV_t
USE MODD_TEB_IRRIG_n, ONLY : TEB_IRRIG_t
USE MODD_TEB_OPTION_n, ONLY : TEB_OPTIONS_t
USE MODD_TEB_PANEL_n, ONLY : TEB_PANEL_t
USE MODD_WATFLUX_n, ONLY : WATFLUX_t
!
USE MODD_BEM_n, ONLY : BEM_t
USE MODD_DIAG_CUMUL_TEB_n, ONLY : DIAG_CUMUL_TEB_t
USE MODD_DIAG_MISC_TEB_n, ONLY : DIAG_MISC_TEB_t
USE MODD_TEB_n, ONLY : TEB_t
!
!
!---------------------------------------------------------------------------
!
TYPE FLAKE_MODEL_t
!
TYPE(CH_FLAKE_t) :: CHF
TYPE(DIAG_OPTIONS_t) :: DFO
TYPE(DIAG_t) :: DGF
TYPE(DIAG_t) :: DGFC
TYPE(DIAG_MISC_FLAKE_t) :: DGMF
TYPE(FLAKE_t) :: F
TYPE(GRID_t) :: FG
TYPE(CANOPY_t) :: FSB
!
END TYPE FLAKE_MODEL_t
!
TYPE WATFLUX_MODEL_t
!
TYPE(CH_WATFLUX_t) :: CHW
TYPE(DIAG_OPTIONS_t) :: DWO
TYPE(DIAG_t) :: DGW 
TYPE(DIAG_t) :: DGWC
TYPE(GRID_t) :: WG
TYPE(WATFLUX_t) :: W 
TYPE(CANOPY_t) :: WSB
!
END TYPE WATFLUX_MODEL_t
!
TYPE SEAFLUX_DIAG_t
!
TYPE(DIAG_OPTIONS_t) :: O
TYPE(DIAG_t) :: D
TYPE(DIAG_t) :: DC
TYPE(DIAG_t) :: DI
TYPE(DIAG_t) :: DIC
TYPE(DIAG_OCEAN_t) :: GO
TYPE(DIAG_MISC_SEAICE_t) :: DMI 
!
END TYPE SEAFLUX_DIAG_t
!
TYPE SEAFLUX_MODEL_t
!
TYPE(CH_SEAFLUX_t) :: CHS
TYPE(DATA_SEAFLUX_t) :: DTS
TYPE(SEAFLUX_DIAG_t) :: DGS
TYPE(OCEAN_t) :: O
TYPE(OCEAN_REL_t) :: OR
TYPE(GRID_t) :: SG
TYPE(SEAFLUX_t) :: S 
TYPE(CANOPY_t) :: SSB
!
END TYPE SEAFLUX_MODEL_t
!
TYPE ISBA_DIAG_t
!
TYPE(DIAG_OPTIONS_t) :: O
TYPE(DIAG_t) :: D
TYPE(DIAG_t) :: DC
TYPE(DIAG_PATCH_t) :: DP
TYPE(DIAG_PATCH_t) :: DPC
TYPE(DIAG_EVAP_ISBA_t) :: DE
TYPE(DIAG_EVAP_ISBA_t) :: DEC
TYPE(DIAG_EVAP_ISBA_PATCH_t) :: DEP
TYPE(DIAG_EVAP_ISBA_PATCH_t) :: DEPC
TYPE(DIAG_MISC_ISBA_t) :: DM
TYPE(DIAG_MISC_ISBA_PATCH_t) :: DMP
!
END TYPE ISBA_DIAG_t
!
TYPE ISBA_MODEL_t
!
TYPE(AGRI_t) :: AG
TYPE(CH_ISBA_t) :: CHI
TYPE(DATA_ISBA_t) :: DTI
TYPE(ISBA_DIAG_t) :: DGI
TYPE(GR_BIOG_t) :: GB
TYPE(CANOPY_t) :: ICP
TYPE(SSO_t) :: ISS 
TYPE(GRID_t) :: IG
TYPE(ISBA_t) :: I
TYPE(PACK_CH_ISBA_t) :: PKCI
TYPE(PACK_DIAG_ISBA_t) :: PKD
TYPE(PACK_ISBA_t) :: PK
!
END TYPE ISBA_MODEL_t
!
TYPE TEB_VEG_DIAG_t
!
TYPE(DIAG_EVAP_ISBA_t) :: E
TYPE(DIAG_EVAP_ISBA_t) :: EP
TYPE(DIAG_t) :: D
TYPE(DIAG_t) :: DP
TYPE(DIAG_MISC_ISBA_t) :: M
!
END TYPE TEB_VEG_DIAG_t
!
TYPE TEB_GARDEN_MODEL_t
!
TYPE(DATA_ISBA_t) :: DTI
TYPE(GR_BIOG_t) :: GB
TYPE(TEB_VEG_DIAG_t) :: VD
TYPE(TEB_VEG_t) :: TV
TYPE(TEB_IRRIG_t) :: TIR
!
END TYPE TEB_GARDEN_MODEL_t
!
TYPE TEB_GREENROOF_MODEL_t
!
TYPE(DATA_ISBA_t) :: DTI
TYPE(GR_BIOG_t) :: GB
TYPE(TEB_VEG_DIAG_t) :: VD
TYPE(TEB_VEG_t) :: TV
!
END TYPE TEB_GREENROOF_MODEL_t
!
TYPE TEB_DIAG_t
!
TYPE(DIAG_MISC_TEB_OPTIONS_t) :: MO
TYPE(DIAG_OPTIONS_t) :: O
TYPE(DIAG_t) :: D 
TYPE(DIAG_UTCI_TEB_t) :: U
TYPE(DIAG_CUMUL_TEB_t) :: C
TYPE(DIAG_MISC_TEB_t) :: M
!
END TYPE TEB_DIAG_t
!
TYPE TEB_MODEL_t
!
TYPE(CH_TEB_t) :: CHT 
TYPE(DATA_TEB_t) :: DTT
TYPE(CANOPY_t) :: TCP
TYPE(GRID_t) :: TG
TYPE(TEB_OPTIONS_t) :: TOP
TYPE(TEB_PANEL_t) :: TPN
TYPE(TEB_t) :: T
!
TYPE(TEB_DIAG_t) :: TD
!
TYPE(BLD_DESC_t) :: BDD
TYPE(BEM_OPTIONS_t) :: BOP 
TYPE(DATA_BEM_t) :: DTB
TYPE(BEM_t) :: B
!
END TYPE TEB_MODEL_t
!
TYPE SURFEX_t 
!
TYPE(DATA_COVER_t) :: DTCO
TYPE(DATA_TSZ0_t) :: DTZ
TYPE(DUMMY_SURF_FIELDS_t) :: DUU
!
TYPE(SURF_ATM_GRID_t) :: UG 
TYPE(SURF_ATM_t) :: U
TYPE(DIAG_OPTIONS_t) :: DUO
TYPE(DIAG_t) :: DGU 
TYPE(DIAG_t) :: DGUC
TYPE(DIAG_PATCH_t) :: DGUP
TYPE(DIAG_PATCH_t) :: DGUPC
TYPE(SSO_t) :: USS 
TYPE(CANOPY_t) :: SSCP
!
TYPE(DIAG_OPTIONS_t) :: DLO
TYPE(DIAG_t) :: DGL
TYPE(DIAG_t) :: DGLC
TYPE(IDEAL_t) :: L
!
TYPE(SV_t) :: SV 
TYPE(CH_SURF_t) :: CHU
TYPE(CH_EMIS_FIELD_t) :: CHE
TYPE(CH_EMIS_SNAP_t) :: CHN
TYPE(EMIS_GR_FIELD_t) :: EGF
TYPE(DST_t) :: DST 
TYPE(SLT_t) :: SLT 
!
TYPE(FLAKE_MODEL_t) :: FM
TYPE(WATFLUX_MODEL_t) :: WM
TYPE(SEAFLUX_MODEL_t) :: SM
TYPE(ISBA_MODEL_t) :: IM
TYPE(TEB_MODEL_t) :: TM
TYPE(TEB_GARDEN_MODEL_t) :: GDM
TYPE(TEB_GREENROOF_MODEL_t) :: GRM
!
END TYPE SURFEX_t
!
END MODULE MODD_SURFEX_n
