!     ############################
      MODULE MODD_DIAG_UTCI_TEB_n
!     ############################
!
!!****  *MODD_DIAG_UTCI_TEB - declaration of confort from TEB scheme
!!
!!    PURPOSE
!!    -------
!
!!
!!**  IMPLICIT ARGUMENTS
!!    ------------------
!!      None 
!!
!!    REFERENCE
!!    ---------
!!
!!    AUTHOR
!!    ------
!!      P. Le Moigne   *Meteo France*
!!
!!    MODIFICATIONS
!!    -------------
!!      Original       07/10/04
!
!
!*       0.   DECLARATIONS
!             ------------
!
!
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE

TYPE DIAG_UTCI_TEB_t
!------------------------------------------------------------------------------
!
  LOGICAL :: LUTCI                               ! flag to compute UTCI quantities
  REAL, POINTER, DIMENSION(:)   :: XUTCI_IN      ! UTCI for person indoor
  REAL, POINTER, DIMENSION(:)   :: XUTCI_OUTSUN  ! UTCI for person outdoor at sun
  REAL, POINTER, DIMENSION(:)   :: XUTCI_OUTSHADE! UTCI for person outdoor at shade
  REAL, POINTER, DIMENSION(:)   :: XTRAD_SUN! Mean radiant temperature seen by person at sun (K)
  REAL, POINTER, DIMENSION(:)   :: XTRAD_SHADE! Mean radiant temperature seen by person in shade (K)
  REAL, POINTER, DIMENSION(:,:) :: XUTCIC_IN      ! Cumulated UTCI stress for person indoor
  REAL, POINTER, DIMENSION(:,:) :: XUTCIC_OUTSUN  ! Cumulated UTCI stress for person outdoor at sun
  REAL, POINTER, DIMENSION(:,:) :: XUTCIC_OUTSHADE! Cumulated UTCI stress for person outdoor at shade
!
END TYPE DIAG_UTCI_TEB_t
!

TYPE(DIAG_UTCI_TEB_t), ALLOCATABLE, TARGET, SAVE :: DIAG_UTCI_TEB_MODEL(:)

TYPE(DIAG_UTCI_TEB_t), POINTER :: DIAG_UTCI_TEB => NULL()
!$OMP THREADPRIVATE(DIAG_UTCI_TEB)

CONTAINS

SUBROUTINE DIAG_UTCI_TEB_GOTO_MODEL(KFROM, KTO, LKFROM)
LOGICAL, INTENT(IN) :: LKFROM
INTEGER, INTENT(IN) :: KFROM, KTO
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
! Current model is set to model KTO
IF (LHOOK) CALL DR_HOOK('MODD_DIAG_UTCI_TEB_N:DIAG_UTCI_TEB_GOTO_MODEL',0,ZHOOK_HANDLE)

DIAG_UTCI_TEB => DIAG_UTCI_TEB_MODEL(KTO)

IF (LHOOK) CALL DR_HOOK('MODD_DIAG_UTCI_TEB_N:DIAG_UTCI_TEB_GOTO_MODEL',1,ZHOOK_HANDLE)

END SUBROUTINE DIAG_UTCI_TEB_GOTO_MODEL

SUBROUTINE DIAG_UTCI_TEB_ALLOC(KMODEL)
INTEGER, INTENT(IN) :: KMODEL
INTEGER :: J
REAL(KIND=JPRB) :: ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK("MODD_DIAG_UTCI_TEB_N:DIAG_UTCI_TEB_ALLOC",0,ZHOOK_HANDLE)
ALLOCATE(DIAG_UTCI_TEB_MODEL(KMODEL))
DIAG_UTCI_TEB => DIAG_UTCI_TEB_MODEL(KMODEL)
DIAG_UTCI_TEB_MODEL(:)%LUTCI=.FALSE.
DO J=1,KMODEL
  NULLIFY(DIAG_UTCI_TEB_MODEL(J)%XUTCI_IN)
  NULLIFY(DIAG_UTCI_TEB_MODEL(J)%XUTCI_OUTSUN)
  NULLIFY(DIAG_UTCI_TEB_MODEL(J)%XUTCI_OUTSHADE)
  NULLIFY(DIAG_UTCI_TEB_MODEL(J)%XTRAD_SUN)
  NULLIFY(DIAG_UTCI_TEB_MODEL(J)%XTRAD_SHADE)
  NULLIFY(DIAG_UTCI_TEB_MODEL(J)%XUTCIC_IN)
  NULLIFY(DIAG_UTCI_TEB_MODEL(J)%XUTCIC_OUTSUN)
  NULLIFY(DIAG_UTCI_TEB_MODEL(J)%XUTCIC_OUTSHADE)
END DO
IF (LHOOK) CALL DR_HOOK("MODD_DIAG_UTCI_TEB_N:DIAG_UTCI_TEB_ALLOC",1,ZHOOK_HANDLE)
END SUBROUTINE DIAG_UTCI_TEB_ALLOC

SUBROUTINE DIAG_UTCI_TEB_DEALLO
REAL(KIND=JPRB) :: ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK("MODD_DIAG_UTCI_TEB_OTPIONS_N:DIAG_UTCI_TEB_OTPIONS_DEALLO",0,ZHOOK_HANDLE)
IF (ALLOCATED(DIAG_UTCI_TEB_MODEL)) DEALLOCATE(DIAG_UTCI_TEB_MODEL)
IF (ASSOCIATED(DIAG_UTCI_TEB)) NULLIFY(DIAG_UTCI_TEB)
IF (LHOOK) CALL DR_HOOK("MODD_DIAG_UTCI_TEB_OTPIONS_N:DIAG_UTCI_TEB_OTPIONS_DEALLO",1,ZHOOK_HANDLE)
END SUBROUTINE DIAG_UTCI_TEB_DEALLO


END MODULE MODD_DIAG_UTCI_TEB_n
