!     #################
      MODULE MODD_SEAFLUX_n
!     #################
!
!!****  *MODD_SEAFLUX_n - declaration of surface parameters for an inland water surface
!!
!!    PURPOSE
!!    -------
!     Declaration of surface parameters
!
!!
!!**  IMPLICIT ARGUMENTS
!!    ------------------
!!      None 
!!
!!    REFERENCE
!!    ---------
!!
!!    AUTHOR
!!    ------
!!      V. Masson   *Meteo France*
!!
!!    MODIFICATIONS
!!    -------------
!!      Original      01/2004
!!      S. Senesi     01/2014  adapt to fractional seaice, and to seaice scheme
!!      S. Belamari   03/2014  Include NZ0
!
!*       0.   DECLARATIONS
!             ------------
!
USE MODD_SURF_PAR,   ONLY : XUNDEF
USE MODD_TYPE_DATE_SURF
!
USE MODD_TYPES_GLT,   ONLY : T_GLT
!
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE

TYPE SEAFLUX_t
!
! General surface: 
!
  REAL, POINTER, DIMENSION(:)   :: XZS     ! orography
  REAL, POINTER, DIMENSION(:,:) :: XCOVER  ! fraction of each ecosystem       (-)
  LOGICAL, POINTER, DIMENSION(:):: LCOVER  ! GCOVER(i)=T --> ith cover field is not 0.
  LOGICAL                       :: LSBL    ! T: SBL scheme between sea and atm. forcing level
!                                          ! F: no atmospheric layers below forcing level      
  LOGICAL                       :: LHANDLE_SIC ! T: we do weight seaice and open sea fluxes
  CHARACTER(LEN=6)              :: CSEAICE_SCHEME! Name of the seaice scheme 
  REAL, POINTER, DIMENSION(:)   :: XSEABATHY   ! bathymetry
!
  LOGICAL                       :: LINTERPOL_SST ! Quadratic interpolation of monthly SST
  CHARACTER(LEN=6)              :: CINTERPOL_SST ! Quadratic interpolation of monthly SST
  LOGICAL                       :: LINTERPOL_SSS ! Quadratic interpolation of monthly SSS
  CHARACTER(LEN=6)              :: CINTERPOL_SSS ! Quadratic interpolation of monthly SSS
  LOGICAL                       :: LINTERPOL_SIC ! Quadratic interpolation of monthly SIC
  CHARACTER(LEN=6)              :: CINTERPOL_SIC ! Quadratic interpolation of monthly SIC
  LOGICAL                       :: LINTERPOL_SIT ! Quadratic interpolation of monthly SIT
  CHARACTER(LEN=6)              :: CINTERPOL_SIT ! Quadratic interpolation of monthly SIT
  REAL                          :: XFREEZING_SST ! Value marking frozen sea in SST data
  REAL                          :: XSIC_EFOLDING_TIME ! For damping of SIC (days)
  REAL                          :: XSIT_EFOLDING_TIME ! For damping of SIT (days)
  REAL                          :: XSEAICE_TSTEP ! Sea ice model time step
  REAL                          :: XCD_ICE_CST   ! Turbulent exchange coefficient for seaice
  REAL                          :: XSI_FLX_DRV   ! Derivative of fluxes on seaice w.r.t to the temperature (W m-2 K-1)
  
!
! Type of formulation for the fluxes
!
  CHARACTER(LEN=6)                  :: CSEA_FLUX   ! type of flux computation
  CHARACTER(LEN=4)                  :: CSEA_ALB    ! type of albedo
  LOGICAL                           :: LPWG        ! flag for gust
  LOGICAL                           :: LPRECIP     ! flag for precip correction
  LOGICAL                           :: LPWEBB      ! flag for Webb correction
  INTEGER                           :: NZ0         ! set to 0,1 or 2 according to Z0 formulation
                                                   ! 0= ARPEGE / 1= Smith (1988) / 2= Direct
  INTEGER                           :: NGRVWAVES   ! set to 0,1 or 2 according to the 
                                                   ! gravity waves model used in coare30_flux
  REAL                              :: XICHCE      ! CE coef calculation for ECUME
  LOGICAL                           :: LPERTFLUX   ! flag for stochastic flux perturbation
!
! Sea/Ocean:
!
  REAL, POINTER, DIMENSION(:) :: XSST    ! sea surface temperature
  REAL, POINTER, DIMENSION(:) :: XSSS    ! sea surface salinity
  REAL, POINTER, DIMENSION(:) :: XTICE   ! sea ice temperature
  REAL, POINTER, DIMENSION(:) :: XSIC    ! sea ice concentration ( constraint for seaice scheme )
  REAL, POINTER, DIMENSION(:) :: XSST_INI! initial sea surface temperature
  REAL, POINTER, DIMENSION(:) :: XZ0     ! roughness length
  REAL, POINTER, DIMENSION(:) :: XZ0H    ! roughness length for heat
  REAL, POINTER, DIMENSION(:) :: XEMIS   ! emissivity
  REAL, POINTER, DIMENSION(:) :: XDIR_ALB! direct albedo
  REAL, POINTER, DIMENSION(:) :: XSCA_ALB! diffuse albedo
  REAL, POINTER, DIMENSION(:) :: XICE_ALB! sea-ice albedo from seaice model (ESM or embedded)
  REAL, POINTER, DIMENSION(:) :: XUMER   ! U component of sea current (for ESM coupling)
  REAL, POINTER, DIMENSION(:) :: XVMER   ! V component of sea current (for ESM coupling)
!
  REAL, POINTER, DIMENSION(:,:) :: XSST_MTH! monthly sea surface temperature (precedent, current and next)
  REAL, POINTER, DIMENSION(:,:) :: XSSS_MTH! monthly sea surface salinity    (precedent, current and next)
  REAL, POINTER, DIMENSION(:,:) :: XSIC_MTH! monthly sea ice cover           (precedent, current and next)
  REAL, POINTER, DIMENSION(:,:) :: XSIT_MTH! monthly sea ice thickness       (precedent, current and next)
  REAL, POINTER, DIMENSION(:)   :: XFSIC   ! nudging (or forcing) sea ice cover
  REAL, POINTER, DIMENSION(:)   :: XFSIT   ! nudging sea ice thickness
!
  REAL, POINTER, DIMENSION(:) :: XCPL_SEA_WIND ! 10m wind speed for ESM coupling
  REAL, POINTER, DIMENSION(:) :: XCPL_SEA_FWSU ! zonal wind stress for ESM coupling
  REAL, POINTER, DIMENSION(:) :: XCPL_SEA_FWSV ! meridian wind stress for ESM coupling
  REAL, POINTER, DIMENSION(:) :: XCPL_SEA_SNET ! Solar net heat flux
  REAL, POINTER, DIMENSION(:) :: XCPL_SEA_HEAT ! Non solar net heat flux
  REAL, POINTER, DIMENSION(:) :: XCPL_SEA_EVAP ! Evaporation for ESM coupling
  REAL, POINTER, DIMENSION(:) :: XCPL_SEA_RAIN ! Rainfall for ESM coupling
  REAL, POINTER, DIMENSION(:) :: XCPL_SEA_SNOW ! Snowfall for ESM coupling
  REAL, POINTER, DIMENSION(:) :: XCPL_SEA_FWSM ! wind stress for ESM coupling
!  
  REAL, POINTER, DIMENSION(:) :: XCPL_SEAICE_SNET ! Solar net heat flux for ESM coupling
  REAL, POINTER, DIMENSION(:) :: XCPL_SEAICE_HEAT ! Non solar net heat flux
  REAL, POINTER, DIMENSION(:) :: XCPL_SEAICE_EVAP ! Ice sublimation for ESM coupling
!
  REAL, POINTER, DIMENSION(:) :: XPERTFLUX     ! Stochastic flux perturbation pattern
!
! Sea-ice :
!
  TYPE(T_GLT)                        :: TGLT ! Sea-ice state , diagnostics and auxilliaries
                                             ! for the case of embedded Gelato Seaice model
!
! Date:
!
  TYPE (DATE_TIME)                      :: TTIME   ! current date and time
  TYPE (DATE_TIME)                      :: TZTIME  
  LOGICAL                               :: LTZTIME_DONE
  INTEGER                               :: JSX
!
! Time-step:
!
  REAL                                  :: XTSTEP  ! time step
!
  REAL                                  :: XOUT_TSTEP  ! output writing time step
!
!
!
END TYPE SEAFLUX_t

TYPE(SEAFLUX_t), ALLOCATABLE, TARGET, SAVE :: SEAFLUX_MODEL(:)

REAL, POINTER, DIMENSION(:)   :: XZS=>NULL()
!$OMP THREADPRIVATE(XZS)
REAL, POINTER, DIMENSION(:,:) :: XCOVER=>NULL()
!$OMP THREADPRIVATE(XCOVER)
LOGICAL, POINTER, DIMENSION(:):: LCOVER=>NULL()
!$OMP THREADPRIVATE(LCOVER)
LOGICAL, POINTER :: LSBL=>NULL()
!$OMP THREADPRIVATE(LSBL)
LOGICAL, POINTER :: LHANDLE_SIC=>NULL()
!$OMP THREADPRIVATE(LHANDLE_SIC)
 CHARACTER(LEN=6), POINTER :: CSEAICE_SCHEME=>NULL()
!$OMP THREADPRIVATE(CSEAICE_SCHEME)
REAL, POINTER, DIMENSION(:)   :: XSEABATHY=>NULL()
!$OMP THREADPRIVATE(XSEABATHY)

LOGICAL, POINTER :: LINTERPOL_SST=>NULL()
!$OMP THREADPRIVATE(LINTERPOL_SST)
 CHARACTER(LEN=6), POINTER :: CINTERPOL_SST=>NULL()
!$OMP THREADPRIVATE(CINTERPOL_SST)
LOGICAL, POINTER :: LINTERPOL_SSS=>NULL()
!$OMP THREADPRIVATE(LINTERPOL_SSS)
 CHARACTER(LEN=6), POINTER :: CINTERPOL_SSS=>NULL()
!$OMP THREADPRIVATE(CINTERPOL_SSS)
LOGICAL, POINTER :: LINTERPOL_SIC=>NULL()
!$OMP THREADPRIVATE(LINTERPOL_SIC)
 CHARACTER(LEN=6), POINTER :: CINTERPOL_SIC=>NULL()
!$OMP THREADPRIVATE(CINTERPOL_SIC)
LOGICAL, POINTER :: LINTERPOL_SIT=>NULL()
!$OMP THREADPRIVATE(LINTERPOL_SIT)
 CHARACTER(LEN=6), POINTER :: CINTERPOL_SIT=>NULL()
!$OMP THREADPRIVATE(CINTERPOL_SIT)
REAL, POINTER     :: XFREEZING_SST=>NULL()
!$OMP THREADPRIVATE(XFREEZING_SST)
REAL, POINTER  :: XSIC_EFOLDING_TIME=>NULL()
!$OMP THREADPRIVATE(XSIC_EFOLDING_TIME)
REAL, POINTER  :: XSIT_EFOLDING_TIME=>NULL()
!$OMP THREADPRIVATE(XSIT_EFOLDING_TIME)
REAL, POINTER  :: XSEAICE_TSTEP=>NULL()
!$OMP THREADPRIVATE(XSEAICE_TSTEP)
REAL, POINTER  :: XCD_ICE_CST=>NULL()
!$OMP THREADPRIVATE(XCD_ICE_CST)
REAL, POINTER  :: XSI_FLX_DRV=>NULL()
!$OMP THREADPRIVATE(XSI_FLX_DRV)

 CHARACTER(LEN=6), POINTER :: CSEA_FLUX=>NULL()
!$OMP THREADPRIVATE(CSEA_FLUX)
 CHARACTER(LEN=4), POINTER :: CSEA_ALB=>NULL()
!$OMP THREADPRIVATE(CSEA_ALB)
LOGICAL, POINTER :: LPWG=>NULL()
!$OMP THREADPRIVATE(LPWG)
LOGICAL, POINTER :: LPRECIP=>NULL()
!$OMP THREADPRIVATE(LPRECIP)
LOGICAL, POINTER :: LPWEBB=>NULL()
!$OMP THREADPRIVATE(LPWEBB)
INTEGER, POINTER :: NZ0=>NULL()
!$OMP THREADPRIVATE(NZ0)
INTEGER, POINTER :: NGRVWAVES=>NULL()
!$OMP THREADPRIVATE(NGRVWAVES)
REAL, POINTER :: XICHCE=>NULL()
!$OMP THREADPRIVATE(XICHCE)
LOGICAL, POINTER :: LPERTFLUX=>NULL()
!$OMP THREADPRIVATE(LPERTFLUX)
REAL, POINTER, DIMENSION(:) :: XSST=>NULL()
!$OMP THREADPRIVATE(XSST)
REAL, POINTER, DIMENSION(:) :: XSSS=>NULL()
!$OMP THREADPRIVATE(XSSS)
REAL, POINTER, DIMENSION(:) :: XTICE=>NULL()
!$OMP THREADPRIVATE(XTICE)
REAL, POINTER, DIMENSION(:) :: XSIC=>NULL()
!$OMP THREADPRIVATE(XSIC)
REAL, POINTER, DIMENSION(:,:) :: XSST_MTH=>NULL()
!$OMP THREADPRIVATE(XSST_MTH)
REAL, POINTER, DIMENSION(:,:) :: XSSS_MTH=>NULL()
!$OMP THREADPRIVATE(XSSS_MTH)
REAL, POINTER, DIMENSION(:,:) :: XSIC_MTH=>NULL()
!$OMP THREADPRIVATE(XSIC_MTH)
REAL, POINTER, DIMENSION(:,:) :: XSIT_MTH=>NULL()
!$OMP THREADPRIVATE(XSIT_MTH)
REAL, POINTER, DIMENSION(:) :: XFSIC=>NULL()
!$OMP THREADPRIVATE(XFSIC)
REAL, POINTER, DIMENSION(:) :: XFSIT=>NULL()
!$OMP THREADPRIVATE(XFSIT)
REAL, POINTER, DIMENSION(:) :: XSST_INI=>NULL()
!$OMP THREADPRIVATE(XSST_INI)
REAL, POINTER, DIMENSION(:) :: XZ0=>NULL()
!$OMP THREADPRIVATE(XZ0)
REAL, POINTER, DIMENSION(:) :: XZ0H=>NULL()
!$OMP THREADPRIVATE(XZ0H)
REAL, POINTER, DIMENSION(:) :: XEMIS=>NULL()
!$OMP THREADPRIVATE(XEMIS)
REAL, POINTER, DIMENSION(:) :: XDIR_ALB=>NULL()
!$OMP THREADPRIVATE(XDIR_ALB)
REAL, POINTER, DIMENSION(:) :: XSCA_ALB=>NULL()
!$OMP THREADPRIVATE(XSCA_ALB)
REAL, POINTER, DIMENSION(:) :: XICE_ALB=>NULL()
!$OMP THREADPRIVATE(XICE_ALB)
REAL, POINTER, DIMENSION(:) :: XUMER=>NULL()
!$OMP THREADPRIVATE(XUMER)
REAL, POINTER, DIMENSION(:) :: XVMER=>NULL()
!$OMP THREADPRIVATE(XVMER)
REAL, POINTER, DIMENSION(:) :: XCPL_SEA_WIND=>NULL()
!$OMP THREADPRIVATE(XCPL_SEA_WIND)
REAL, POINTER, DIMENSION(:) :: XCPL_SEA_FWSU=>NULL()
!$OMP THREADPRIVATE(XCPL_SEA_FWSU)
REAL, POINTER, DIMENSION(:) :: XCPL_SEA_FWSV=>NULL()
!$OMP THREADPRIVATE(XCPL_SEA_FWSV)
REAL, POINTER, DIMENSION(:) :: XCPL_SEA_SNET=>NULL()
!$OMP THREADPRIVATE(XCPL_SEA_SNET)
REAL, POINTER, DIMENSION(:) :: XCPL_SEA_HEAT=>NULL()
!$OMP THREADPRIVATE(XCPL_SEA_HEAT)
REAL, POINTER, DIMENSION(:) :: XCPL_SEA_EVAP=>NULL()
!$OMP THREADPRIVATE(XCPL_SEA_EVAP)
REAL, POINTER, DIMENSION(:) :: XCPL_SEA_RAIN=>NULL()
!$OMP THREADPRIVATE(XCPL_SEA_RAIN)
REAL, POINTER, DIMENSION(:) :: XCPL_SEA_SNOW=>NULL()
!$OMP THREADPRIVATE(XCPL_SEA_SNOW)
REAL, POINTER, DIMENSION(:) :: XCPL_SEA_FWSM=>NULL()
!$OMP THREADPRIVATE(XCPL_SEA_FWSM)
REAL, POINTER, DIMENSION(:) :: XCPL_SEAICE_SNET=>NULL()
!$OMP THREADPRIVATE(XCPL_SEAICE_SNET)
REAL, POINTER, DIMENSION(:) :: XCPL_SEAICE_HEAT=>NULL()
!$OMP THREADPRIVATE(XCPL_SEAICE_HEAT)
REAL, POINTER, DIMENSION(:) :: XCPL_SEAICE_EVAP=>NULL()
!$OMP THREADPRIVATE(XCPL_SEAICE_EVAP)
REAL, POINTER, DIMENSION(:) :: XPERTFLUX=>NULL()
!$OMP THREADPRIVATE(XPERTFLUX)
TYPE(T_GLT), POINTER :: TGLT=>NULL()
!$OMP THREADPRIVATE(TGLT)
TYPE (DATE_TIME), POINTER :: TTIME=>NULL()
!$OMP THREADPRIVATE(TTIME)
TYPE (DATE_TIME), POINTER :: TZTIME=>NULL()
!$OMP THREADPRIVATE(TZTIME)
LOGICAL, POINTER :: LTZTIME_DONE=>NULL()
!$OMP THREADPRIVATE(LTZTIME_DONE)
INTEGER, POINTER :: JSX=>NULL()
!$OMP THREADPRIVATE(JSX)
REAL, POINTER :: XTSTEP=>NULL()
!$OMP THREADPRIVATE(XTSTEP)
REAL, POINTER :: XOUT_TSTEP=>NULL()
!$OMP THREADPRIVATE(XOUT_TSTEP)

CONTAINS

SUBROUTINE SEAFLUX_GOTO_MODEL(KFROM, KTO, LKFROM)
LOGICAL, INTENT(IN) :: LKFROM
INTEGER, INTENT(IN) :: KFROM, KTO
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
! Save current state for allocated arrays
IF (LKFROM) THEN
SEAFLUX_MODEL(KFROM)%XZS=>XZS
SEAFLUX_MODEL(KFROM)%XCOVER=>XCOVER
SEAFLUX_MODEL(KFROM)%LCOVER=>LCOVER
SEAFLUX_MODEL(KFROM)%XSEABATHY=>XSEABATHY
SEAFLUX_MODEL(KFROM)%XSST=>XSST
SEAFLUX_MODEL(KFROM)%XSSS=>XSSS
SEAFLUX_MODEL(KFROM)%XTICE=>XTICE
SEAFLUX_MODEL(KFROM)%XSIC=>XSIC
SEAFLUX_MODEL(KFROM)%XSST_MTH=>XSST_MTH
SEAFLUX_MODEL(KFROM)%XSSS_MTH=>XSSS_MTH
SEAFLUX_MODEL(KFROM)%XSIC_MTH=>XSIC_MTH
SEAFLUX_MODEL(KFROM)%XSIT_MTH=>XSIT_MTH
SEAFLUX_MODEL(KFROM)%XFSIC=>XFSIC
SEAFLUX_MODEL(KFROM)%XFSIT=>XFSIT
SEAFLUX_MODEL(KFROM)%XSST_INI=>XSST_INI
SEAFLUX_MODEL(KFROM)%XZ0=>XZ0
SEAFLUX_MODEL(KFROM)%XZ0H=>XZ0H
SEAFLUX_MODEL(KFROM)%XEMIS=>XEMIS
SEAFLUX_MODEL(KFROM)%XDIR_ALB=>XDIR_ALB
SEAFLUX_MODEL(KFROM)%XSCA_ALB=>XSCA_ALB
SEAFLUX_MODEL(KFROM)%XICE_ALB=>XICE_ALB
SEAFLUX_MODEL(KFROM)%XUMER=>XUMER
SEAFLUX_MODEL(KFROM)%XVMER=>XVMER
SEAFLUX_MODEL(KFROM)%XCPL_SEA_WIND=>XCPL_SEA_WIND
SEAFLUX_MODEL(KFROM)%XCPL_SEA_FWSU=>XCPL_SEA_FWSU
SEAFLUX_MODEL(KFROM)%XCPL_SEA_FWSV=>XCPL_SEA_FWSV
SEAFLUX_MODEL(KFROM)%XCPL_SEA_SNET=>XCPL_SEA_SNET
SEAFLUX_MODEL(KFROM)%XCPL_SEA_HEAT=>XCPL_SEA_HEAT
SEAFLUX_MODEL(KFROM)%XCPL_SEA_EVAP=>XCPL_SEA_EVAP
SEAFLUX_MODEL(KFROM)%XCPL_SEA_RAIN=>XCPL_SEA_RAIN
SEAFLUX_MODEL(KFROM)%XCPL_SEA_SNOW=>XCPL_SEA_SNOW
SEAFLUX_MODEL(KFROM)%XCPL_SEA_FWSM=>XCPL_SEA_FWSM
SEAFLUX_MODEL(KFROM)%XCPL_SEAICE_SNET=>XCPL_SEAICE_SNET
SEAFLUX_MODEL(KFROM)%XCPL_SEAICE_HEAT=>XCPL_SEAICE_HEAT
SEAFLUX_MODEL(KFROM)%XCPL_SEAICE_EVAP=>XCPL_SEAICE_EVAP
SEAFLUX_MODEL(KFROM)%XPERTFLUX=>XPERTFLUX
ENDIF
!
! Current model is set to model KTO
IF (LHOOK) CALL DR_HOOK('MODD_SEAFLUX_N:SEAFLUX_GOTO_MODEL',0,ZHOOK_HANDLE)
XZS=>SEAFLUX_MODEL(KTO)%XZS
XCOVER=>SEAFLUX_MODEL(KTO)%XCOVER
LCOVER=>SEAFLUX_MODEL(KTO)%LCOVER
LSBL=>SEAFLUX_MODEL(KTO)%LSBL
LHANDLE_SIC=>SEAFLUX_MODEL(KTO)%LHANDLE_SIC
CSEAICE_SCHEME=>SEAFLUX_MODEL(KTO)%CSEAICE_SCHEME
XSEABATHY=>SEAFLUX_MODEL(KTO)%XSEABATHY
CSEA_FLUX=>SEAFLUX_MODEL(KTO)%CSEA_FLUX
CSEA_ALB=>SEAFLUX_MODEL(KTO)%CSEA_ALB
LPWG=>SEAFLUX_MODEL(KTO)%LPWG
LPRECIP=>SEAFLUX_MODEL(KTO)%LPRECIP
LINTERPOL_SST=>SEAFLUX_MODEL(KTO)%LINTERPOL_SST
CINTERPOL_SST=>SEAFLUX_MODEL(KTO)%CINTERPOL_SST
LINTERPOL_SSS=>SEAFLUX_MODEL(KTO)%LINTERPOL_SSS
CINTERPOL_SSS=>SEAFLUX_MODEL(KTO)%CINTERPOL_SSS
LINTERPOL_SIC=>SEAFLUX_MODEL(KTO)%LINTERPOL_SIC
CINTERPOL_SIC=>SEAFLUX_MODEL(KTO)%CINTERPOL_SIC
LINTERPOL_SIT=>SEAFLUX_MODEL(KTO)%LINTERPOL_SIT
CINTERPOL_SIT=>SEAFLUX_MODEL(KTO)%CINTERPOL_SIT
XSIC_EFOLDING_TIME=>SEAFLUX_MODEL(KTO)%XSIC_EFOLDING_TIME
XSIT_EFOLDING_TIME=>SEAFLUX_MODEL(KTO)%XSIT_EFOLDING_TIME
XSEAICE_TSTEP=>SEAFLUX_MODEL(KTO)%XSEAICE_TSTEP
XCD_ICE_CST=>SEAFLUX_MODEL(KTO)%XCD_ICE_CST
XSI_FLX_DRV=>SEAFLUX_MODEL(KTO)%XSI_FLX_DRV
XFREEZING_SST=>SEAFLUX_MODEL(KTO)%XFREEZING_SST
LPWEBB=>SEAFLUX_MODEL(KTO)%LPWEBB
NZ0=>SEAFLUX_MODEL(KTO)%NZ0
NGRVWAVES=>SEAFLUX_MODEL(KTO)%NGRVWAVES
XICHCE=>SEAFLUX_MODEL(KTO)%XICHCE
LPERTFLUX=>SEAFLUX_MODEL(KTO)%LPERTFLUX
XSST=>SEAFLUX_MODEL(KTO)%XSST
XSSS=>SEAFLUX_MODEL(KTO)%XSSS
XTICE=>SEAFLUX_MODEL(KTO)%XTICE
XSIC=>SEAFLUX_MODEL(KTO)%XSIC
XSST_MTH=>SEAFLUX_MODEL(KTO)%XSST_MTH
XSSS_MTH=>SEAFLUX_MODEL(KTO)%XSSS_MTH
XSIC_MTH=>SEAFLUX_MODEL(KTO)%XSIC_MTH
XSIT_MTH=>SEAFLUX_MODEL(KTO)%XSIT_MTH
XFSIC=>SEAFLUX_MODEL(KTO)%XFSIC
XFSIT=>SEAFLUX_MODEL(KTO)%XFSIT
XSST_INI=>SEAFLUX_MODEL(KTO)%XSST_INI
XZ0=>SEAFLUX_MODEL(KTO)%XZ0
XZ0H=>SEAFLUX_MODEL(KTO)%XZ0H
XEMIS=>SEAFLUX_MODEL(KTO)%XEMIS
XDIR_ALB=>SEAFLUX_MODEL(KTO)%XDIR_ALB
XSCA_ALB=>SEAFLUX_MODEL(KTO)%XSCA_ALB
XICE_ALB=>SEAFLUX_MODEL(KTO)%XICE_ALB
XUMER=>SEAFLUX_MODEL(KTO)%XUMER
XVMER=>SEAFLUX_MODEL(KTO)%XVMER
XCPL_SEA_WIND=>SEAFLUX_MODEL(KTO)%XCPL_SEA_WIND
XCPL_SEA_FWSU=>SEAFLUX_MODEL(KTO)%XCPL_SEA_FWSU
XCPL_SEA_FWSV=>SEAFLUX_MODEL(KTO)%XCPL_SEA_FWSV
XCPL_SEA_SNET=>SEAFLUX_MODEL(KTO)%XCPL_SEA_SNET
XCPL_SEA_HEAT=>SEAFLUX_MODEL(KTO)%XCPL_SEA_HEAT
XCPL_SEA_EVAP=>SEAFLUX_MODEL(KTO)%XCPL_SEA_EVAP
XCPL_SEA_RAIN=>SEAFLUX_MODEL(KTO)%XCPL_SEA_RAIN
XCPL_SEA_SNOW=>SEAFLUX_MODEL(KTO)%XCPL_SEA_SNOW
XCPL_SEA_FWSM=>SEAFLUX_MODEL(KTO)%XCPL_SEA_FWSM
XCPL_SEAICE_SNET=>SEAFLUX_MODEL(KTO)%XCPL_SEAICE_SNET
XCPL_SEAICE_HEAT=>SEAFLUX_MODEL(KTO)%XCPL_SEAICE_HEAT
XCPL_SEAICE_EVAP=>SEAFLUX_MODEL(KTO)%XCPL_SEAICE_EVAP
XPERTFLUX=>SEAFLUX_MODEL(KTO)%XPERTFLUX
TGLT=>SEAFLUX_MODEL(KTO)%TGLT
TTIME=>SEAFLUX_MODEL(KTO)%TTIME
TZTIME=>SEAFLUX_MODEL(KTO)%TZTIME
LTZTIME_DONE=>SEAFLUX_MODEL(KTO)%LTZTIME_DONE
JSX=>SEAFLUX_MODEL(KTO)%JSX
XTSTEP=>SEAFLUX_MODEL(KTO)%XTSTEP
XOUT_TSTEP=>SEAFLUX_MODEL(KTO)%XOUT_TSTEP
IF (LHOOK) CALL DR_HOOK('MODD_SEAFLUX_N:SEAFLUX_GOTO_MODEL',1,ZHOOK_HANDLE)

END SUBROUTINE SEAFLUX_GOTO_MODEL

SUBROUTINE SEAFLUX_ALLOC(KMODEL)
INTEGER, INTENT(IN) :: KMODEL
INTEGER :: J
REAL(KIND=JPRB) :: ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK("MODD_SEAFLUX_N:SEAFLUX_ALLOC",0,ZHOOK_HANDLE)
ALLOCATE(SEAFLUX_MODEL(KMODEL))
DO J=1,KMODEL
  NULLIFY(SEAFLUX_MODEL(J)%XZS)
  NULLIFY(SEAFLUX_MODEL(J)%XCOVER)
  NULLIFY(SEAFLUX_MODEL(J)%LCOVER)
  NULLIFY(SEAFLUX_MODEL(J)%XSEABATHY)
  NULLIFY(SEAFLUX_MODEL(J)%XSST)
  NULLIFY(SEAFLUX_MODEL(J)%XSSS)
  NULLIFY(SEAFLUX_MODEL(J)%XSIC)
  NULLIFY(SEAFLUX_MODEL(J)%XTICE)
  NULLIFY(SEAFLUX_MODEL(J)%XSST_INI)
  NULLIFY(SEAFLUX_MODEL(J)%XZ0)
  NULLIFY(SEAFLUX_MODEL(J)%XZ0H)
  NULLIFY(SEAFLUX_MODEL(J)%XEMIS)
  NULLIFY(SEAFLUX_MODEL(J)%XDIR_ALB)
  NULLIFY(SEAFLUX_MODEL(J)%XSCA_ALB)
  NULLIFY(SEAFLUX_MODEL(J)%XICE_ALB)
  NULLIFY(SEAFLUX_MODEL(J)%XUMER)
  NULLIFY(SEAFLUX_MODEL(J)%XVMER)
  NULLIFY(SEAFLUX_MODEL(J)%XSST_MTH)
  NULLIFY(SEAFLUX_MODEL(J)%XSSS_MTH)
  NULLIFY(SEAFLUX_MODEL(J)%XSIC_MTH)
  NULLIFY(SEAFLUX_MODEL(J)%XSIT_MTH)
  NULLIFY(SEAFLUX_MODEL(J)%XFSIC)
  NULLIFY(SEAFLUX_MODEL(J)%XFSIT)
  NULLIFY(SEAFLUX_MODEL(J)%XCPL_SEA_WIND)
  NULLIFY(SEAFLUX_MODEL(J)%XCPL_SEA_FWSU)
  NULLIFY(SEAFLUX_MODEL(J)%XCPL_SEA_FWSV)
  NULLIFY(SEAFLUX_MODEL(J)%XCPL_SEA_SNET)
  NULLIFY(SEAFLUX_MODEL(J)%XCPL_SEA_HEAT)
  NULLIFY(SEAFLUX_MODEL(J)%XCPL_SEA_EVAP)
  NULLIFY(SEAFLUX_MODEL(J)%XCPL_SEA_RAIN)
  NULLIFY(SEAFLUX_MODEL(J)%XCPL_SEA_SNOW)
  NULLIFY(SEAFLUX_MODEL(J)%XCPL_SEA_FWSM)
  NULLIFY(SEAFLUX_MODEL(J)%XCPL_SEAICE_SNET)
  NULLIFY(SEAFLUX_MODEL(J)%XCPL_SEAICE_HEAT)
  NULLIFY(SEAFLUX_MODEL(J)%XCPL_SEAICE_EVAP)
  NULLIFY(SEAFLUX_MODEL(J)%XPERTFLUX)
ENDDO
SEAFLUX_MODEL(:)%LSBL=.FALSE.
SEAFLUX_MODEL(:)%LHANDLE_SIC=.FALSE.
SEAFLUX_MODEL(:)%CSEAICE_SCHEME='NONE  '
SEAFLUX_MODEL(:)%LINTERPOL_SST=.FALSE.
SEAFLUX_MODEL(:)%CINTERPOL_SST=' '
SEAFLUX_MODEL(:)%LINTERPOL_SSS=.FALSE.
SEAFLUX_MODEL(:)%CINTERPOL_SSS=' '
SEAFLUX_MODEL(:)%LINTERPOL_SIC=.FALSE.
SEAFLUX_MODEL(:)%CINTERPOL_SIC=' '
SEAFLUX_MODEL(:)%LINTERPOL_SIT=.FALSE.
SEAFLUX_MODEL(:)%CINTERPOL_SIT=' '
SEAFLUX_MODEL(:)%XFREEZING_SST=-1.8
SEAFLUX_MODEL(:)%XSIC_EFOLDING_TIME=0. ! means : no damping
SEAFLUX_MODEL(:)%XSIT_EFOLDING_TIME=0. ! means : no damping
SEAFLUX_MODEL(:)%XSEAICE_TSTEP=XUNDEF 
SEAFLUX_MODEL(:)%XCD_ICE_CST=0.
SEAFLUX_MODEL(:)%XSI_FLX_DRV=-20. 
SEAFLUX_MODEL(:)%CSEA_FLUX=' '
SEAFLUX_MODEL(:)%CSEA_ALB=' '
SEAFLUX_MODEL(:)%LPWG=.FALSE.
SEAFLUX_MODEL(:)%LPRECIP=.FALSE.
SEAFLUX_MODEL(:)%LPWEBB=.FALSE.
SEAFLUX_MODEL(:)%NZ0=0
SEAFLUX_MODEL(:)%NGRVWAVES=0
SEAFLUX_MODEL(:)%XICHCE=0.
SEAFLUX_MODEL(:)%LPERTFLUX=.FALSE.
SEAFLUX_MODEL(:)%JSX=0
SEAFLUX_MODEL(:)%LTZTIME_DONE = .FALSE.
SEAFLUX_MODEL(:)%XTSTEP=0.
SEAFLUX_MODEL(:)%XOUT_TSTEP=0.
IF (LHOOK) CALL DR_HOOK("MODD_SEAFLUX_N:SEAFLUX_ALLOC",1,ZHOOK_HANDLE)
END SUBROUTINE SEAFLUX_ALLOC

SUBROUTINE SEAFLUX_DEALLO
REAL(KIND=JPRB) :: ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK("MODD_SEAFLUX_N:SEAFLUX_DEALLO",0,ZHOOK_HANDLE)
IF (ALLOCATED(SEAFLUX_MODEL)) DEALLOCATE(SEAFLUX_MODEL)
IF (LHOOK) CALL DR_HOOK("MODD_SEAFLUX_N:SEAFLUX_DEALLO",1,ZHOOK_HANDLE)
END SUBROUTINE SEAFLUX_DEALLO

END MODULE MODD_SEAFLUX_n
