!     ######################
      MODULE MODD_DIAG_SEAICE_n
!     ######################
!
!!****  *MODD_DIAG_SEAICE - declaration of diagnostics for sea ice model 
!!
!!    PURPOSE
!!    -------
!
!!
!!**  IMPLICIT ARGUMENTS
!!    ------------------
!!      None 
!!
!!    REFERENCE
!!    ---------
!!
!!    AUTHOR
!!    ------
!!      S.Sénési   *Meteo France*
!!
!!    MODIFICATIONS
!!    -------------
!!      Original       08/2013
!
!*       0.   DECLARATIONS
!             ------------
!
!
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE

TYPE DIAG_SEAICE_t
!------------------------------------------------------------------------------
!
  LOGICAL :: LDIAG_SEAICE                    ! flag for SeaIce variables
!
!* averaged variables
!
  REAL, POINTER, DIMENSION(:)   :: XSIT  ! Sea ice thickness 
  REAL, POINTER, DIMENSION(:)   :: XSND  ! Sea ice snow depth 
  REAL, POINTER, DIMENSION(:)   :: XMLT  ! Sea mixed layer temp. seen by Gelato 
!------------------------------------------------------------------------------
!

END TYPE DIAG_SEAICE_t

TYPE(DIAG_SEAICE_t), ALLOCATABLE, TARGET, SAVE :: DIAG_SEAICE_MODEL(:)

TYPE(DIAG_SEAICE_t), POINTER :: DIAG_SEAICE => NULL()
!$OMP THREADPRIVATE(DIAG_SEAICE)

CONTAINS

SUBROUTINE DIAG_SEAICE_GOTO_MODEL(KFROM, KTO, LKFROM)
LOGICAL, INTENT(IN) :: LKFROM
INTEGER, INTENT(IN) :: KFROM, KTO
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!

! Current model is set to model KTO
IF (LHOOK) CALL DR_HOOK('MODD_DIAG_SEAICE_N:DIAG_SEAICE_GOTO_MODEL',0,ZHOOK_HANDLE)

DIAG_SEAICE => DIAG_SEAICE_MODEL(KTO)

IF (LHOOK) CALL DR_HOOK('MODD_DIAG_SEAICE_N:DIAG_SEAICE_GOTO_MODEL',1,ZHOOK_HANDLE)

END SUBROUTINE DIAG_SEAICE_GOTO_MODEL

SUBROUTINE DIAG_SEAICE_ALLOC(KMODEL) 
INTEGER, INTENT(IN) :: KMODEL
INTEGER :: J
REAL(KIND=JPRB) :: ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK("MODD_DIAG_SEAICE_N:DIAG_SEAICE_ALLOC",0,ZHOOK_HANDLE)
ALLOCATE(DIAG_SEAICE_MODEL(KMODEL))
DO J=1,KMODEL
  NULLIFY(DIAG_SEAICE_MODEL(J)%XSIT)
  NULLIFY(DIAG_SEAICE_MODEL(J)%XSND)
  NULLIFY(DIAG_SEAICE_MODEL(J)%XMLT)
ENDDO
DIAG_SEAICE_MODEL(:)%LDIAG_SEAICE=.FALSE.
IF (LHOOK) CALL DR_HOOK("MODD_DIAG_SEAICE_N:DIAG_SEAICE_ALLOC",1,ZHOOK_HANDLE)
END SUBROUTINE DIAG_SEAICE_ALLOC

SUBROUTINE DIAG_SEAICE_DEALLO
REAL(KIND=JPRB) :: ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK("MODD_DIAG_SEAICE_N:DIAG_SEAICE_DEALLO",0,ZHOOK_HANDLE)
IF (ALLOCATED(DIAG_SEAICE_MODEL)) DEALLOCATE(DIAG_SEAICE_MODEL)
IF (ASSOCIATED(DIAG_SEAICE)) NULLIFY(DIAG_SEAICE)
IF (LHOOK) CALL DR_HOOK("MODD_DIAG_SEAICE_N:DIAG_SEAICE_DEALLO",1,ZHOOK_HANDLE)
END SUBROUTINE DIAG_SEAICE_DEALLO

END MODULE MODD_DIAG_SEAICE_n
