!##################
MODULE MODD_TEB_GREENROOF_n
!##################
!
!!****  *MODD_TEB_GREENROOF - declaration of ISBA scheme packed surface parameters for urban green roofs
!!
!!    PURPOSE
!!    -------
!
!!
!!**  IMPLICIT ARGUMENTS
!!    ------------------
!!      None 
!!
!!    REFERENCE
!!    ---------
!!
!!    AUTHOR
!!    ------
!!	A. Lemonsu *Meteo France*
!!
!!    MODIFICATIONS
!!    -------------
!!      Original       09/2009
!!      C. de Munck     06/2011 
!!      V. Masson       06/2013  splits module in 4
!!
!-------------------------------------------------------------------------------
!
!*       0.   DECLARATIONS
!             ------------
!
USE MODD_TYPE_SNOW
!
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE

TYPE TEB_GREENROOF_t
!-------------------------------------------------------------------------------
!
! Prognostic variables:
!
! - Snow Cover:
!
  TYPE(SURF_SNOW)                :: TSNOW            ! snow state: 
                                                     ! scheme type/option                      (-)
                                                     ! number of layers                        (-)
                                                     ! snow (& liq. water) content             (kg/m2)
                                                     ! heat content                            (J/m2)
                                                     ! temperature                             (K)
                                                     ! density                                 (kg m-3)
!
! - Soil and vegetation heat and water:
!
  REAL, POINTER, DIMENSION(:)    :: XWR              ! liquid water retained on the
                                                     ! foliage of the vegetation
                                                     ! canopy                                  (kg/m2)
  REAL, POINTER, DIMENSION(:,:)  :: XTG              ! surface and sub-surface soil 
                                                     ! temperature profile                     (K)
  REAL, POINTER, DIMENSION(:,:)  :: XWG              ! soil volumetric water content profile   (m3/m3)
  REAL, POINTER, DIMENSION(:,:)  :: XWGI             ! soil liquid water equivalent volumetric 
                                                     ! ice content profile                     (m3/m3)
  REAL, POINTER, DIMENSION(:)    :: XRESA            ! aerodynamic resistance                  (s/m)
!

! - Vegetation: Ags Prognostic (YPHOTO = 'AGS', 'LAI', 'AST', 'LST', 'NIT', 'NCB')
!
  REAL, POINTER, DIMENSION(:)    :: XAN              ! net CO2 assimilation                    (mg/m2/s)
  REAL, POINTER, DIMENSION(:)    :: XANDAY           ! daily net CO2 assimilation              (mg/m2)
  REAL, POINTER, DIMENSION(:)    :: XANFM            ! maximum leaf assimilation               (mg/m2/s)
  REAL, POINTER, DIMENSION(:)    :: XLE              ! evapotranspiration                      (W/m2)
  REAL, POINTER, DIMENSION(:)     :: XFAPARC       ! Fapar of vegetation (cumul)
  REAL, POINTER, DIMENSION(:)     :: XFAPIRC       ! Fapir of vegetation (cumul)
  REAL, POINTER, DIMENSION(:)     :: XLAI_EFFC     ! Effective LAI (cumul)
  REAL, POINTER, DIMENSION(:)     :: XMUS          ! cos zenithal angle (cumul)    
!
! - Vegetation: Ags Prognostic (YPHOTO = 'NIT', 'NCB')
!
  REAL, POINTER, DIMENSION(:,:)  :: XRESP_BIOMASS    ! daily cumulated respiration of 
                                                     ! biomass                              (kg/m2/s)
  REAL, POINTER, DIMENSION(:,:)  :: XBIOMASS         ! biomass of previous day              (kg/m2) 
!
!-------------------------------------------------------------------------------
!
! - Snow and flood fractions and total albedo at time t:
!
  REAL, POINTER, DIMENSION(:)    :: XPSNG              ! Snow fraction over ground
  REAL, POINTER, DIMENSION(:)    :: XPSNV              ! Snow fraction over vegetation
  REAL, POINTER, DIMENSION(:)    :: XPSNV_A            ! Snow fraction over vegetation
  REAL, POINTER, DIMENSION(:)    :: XPSN               ! Total Snow fraction
! 
  REAL, POINTER, DIMENSION(:)    :: XSNOWFREE_ALB      ! snow free albedo                        (-)
  REAL, POINTER, DIMENSION(:)    :: XSNOWFREE_ALB_VEG  ! snow free albedo for vegetation         (-)
  REAL, POINTER, DIMENSION(:)    :: XSNOWFREE_ALB_SOIL ! snow free albedo for soil               (-)
!
!-------------------------------------------------------------------------------
!
END TYPE TEB_GREENROOF_t



TYPE(TEB_GREENROOF_t),         ALLOCATABLE, TARGET, SAVE :: TEB_GREENROOF_MODEL(:,:)



TYPE(SURF_SNOW), POINTER          :: TSNOW=>NULL()
!$OMP THREADPRIVATE(TSNOW)
REAL, POINTER, DIMENSION(:)       :: XWR=>NULL()
!$OMP THREADPRIVATE(XWR)
REAL, POINTER, DIMENSION(:,:)     :: XTG=>NULL()
!$OMP THREADPRIVATE(XTG)
REAL, POINTER, DIMENSION(:,:)     :: XWG=>NULL()
!$OMP THREADPRIVATE(XWG)
REAL, POINTER, DIMENSION(:,:)     :: XWGI=>NULL()
!$OMP THREADPRIVATE(XWGI)
REAL, POINTER, DIMENSION(:)       :: XRESA=>NULL()
!$OMP THREADPRIVATE(XRESA)
REAL, POINTER, DIMENSION(:)       :: XAN=>NULL()
!$OMP THREADPRIVATE(XAN)
REAL, POINTER, DIMENSION(:)       :: XANDAY=>NULL()
!$OMP THREADPRIVATE(XANDAY)
REAL, POINTER, DIMENSION(:)       :: XANFM=>NULL()
!$OMP THREADPRIVATE(XANFM)
REAL, POINTER, DIMENSION(:)       :: XLE=>NULL()
!$OMP THREADPRIVATE(XLE)
REAL, POINTER, DIMENSION(:)     :: XFAPARC=>NULL()
!$OMP THREADPRIVATE(XFAPARC)
REAL, POINTER, DIMENSION(:)     :: XFAPIRC=>NULL()
!$OMP THREADPRIVATE(XFAPIRC)
REAL, POINTER, DIMENSION(:)     :: XLAI_EFFC=>NULL()
!$OMP THREADPRIVATE(XLAI_EFFC)
REAL, POINTER, DIMENSION(:)     :: XMUS=>NULL()
!$OMP THREADPRIVATE(XMUS)
REAL, POINTER, DIMENSION(:,:)     :: XRESP_BIOMASS=>NULL()
!$OMP THREADPRIVATE(XRESP_BIOMASS)
REAL, POINTER, DIMENSION(:,:)     :: XBIOMASS=>NULL()
!$OMP THREADPRIVATE(XBIOMASS)
REAL, POINTER, DIMENSION(:)       :: XPSNG=>NULL()
!$OMP THREADPRIVATE(XPSNG)
REAL, POINTER, DIMENSION(:)       :: XPSNV=>NULL()
!$OMP THREADPRIVATE(XPSNV)
REAL, POINTER, DIMENSION(:)       :: XPSNV_A=>NULL()
!$OMP THREADPRIVATE(XPSNV_A)
REAL, POINTER, DIMENSION(:)       :: XPSN=>NULL()
!$OMP THREADPRIVATE(XPSN)
REAL, POINTER, DIMENSION(:)       :: XSNOWFREE_ALB=>NULL()
!$OMP THREADPRIVATE(XSNOWFREE_ALB)
REAL, POINTER, DIMENSION(:)       :: XSNOWFREE_ALB_VEG=>NULL()
!$OMP THREADPRIVATE(XSNOWFREE_ALB_VEG)
REAL, POINTER, DIMENSION(:)       :: XSNOWFREE_ALB_SOIL=>NULL()
!$OMP THREADPRIVATE(XSNOWFREE_ALB_SOIL)
!
CONTAINS

SUBROUTINE TEB_GREENROOF_GOTO_MODEL(KFROM, KTO, LKFROM, KFROM_PATCH, KTO_PATCH)
LOGICAL, INTENT(IN) :: LKFROM
INTEGER, INTENT(IN) :: KFROM, KTO
INTEGER, INTENT(IN) :: KFROM_PATCH, KTO_PATCH
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
! Save current state for allocated arrays
IF (LKFROM) THEN
TEB_GREENROOF_MODEL(KFROM,KFROM_PATCH)%XWR=>XWR
TEB_GREENROOF_MODEL(KFROM,KFROM_PATCH)%XTG=>XTG
TEB_GREENROOF_MODEL(KFROM,KFROM_PATCH)%XWG=>XWG
TEB_GREENROOF_MODEL(KFROM,KFROM_PATCH)%XWGI=>XWGI
TEB_GREENROOF_MODEL(KFROM,KFROM_PATCH)%XRESA=>XRESA
TEB_GREENROOF_MODEL(KFROM,KFROM_PATCH)%XAN=>XAN
TEB_GREENROOF_MODEL(KFROM,KFROM_PATCH)%XANDAY=>XANDAY
TEB_GREENROOF_MODEL(KFROM,KFROM_PATCH)%XANFM=>XANFM
TEB_GREENROOF_MODEL(KFROM,KFROM_PATCH)%XLE=>XLE
TEB_GREENROOF_MODEL(KFROM,KFROM_PATCH)%XFAPARC=>XFAPARC
TEB_GREENROOF_MODEL(KFROM,KFROM_PATCH)%XFAPIRC=>XFAPIRC
TEB_GREENROOF_MODEL(KFROM,KFROM_PATCH)%XLAI_EFFC=>XLAI_EFFC
TEB_GREENROOF_MODEL(KFROM,KFROM_PATCH)%XMUS=>XMUS
TEB_GREENROOF_MODEL(KFROM,KFROM_PATCH)%XRESP_BIOMASS=>XRESP_BIOMASS
TEB_GREENROOF_MODEL(KFROM,KFROM_PATCH)%XBIOMASS=>XBIOMASS
TEB_GREENROOF_MODEL(KFROM,KFROM_PATCH)%XPSNG=>XPSNG
TEB_GREENROOF_MODEL(KFROM,KFROM_PATCH)%XPSNV_A=>XPSNV_A
TEB_GREENROOF_MODEL(KFROM,KFROM_PATCH)%XPSNV=>XPSNV
TEB_GREENROOF_MODEL(KFROM,KFROM_PATCH)%XPSN=>XPSN
TEB_GREENROOF_MODEL(KFROM,KFROM_PATCH)%XSNOWFREE_ALB=>XSNOWFREE_ALB
TEB_GREENROOF_MODEL(KFROM,KFROM_PATCH)%XSNOWFREE_ALB_VEG=>XSNOWFREE_ALB_VEG
TEB_GREENROOF_MODEL(KFROM,KFROM_PATCH)%XSNOWFREE_ALB_SOIL=>XSNOWFREE_ALB_SOIL
ENDIF
!
! Current model is set to model KTO
IF (LHOOK) CALL DR_HOOK('MODD_TEB_GREENROOF_N:TEB_GREENROOF_GOTO_MODEL',0,ZHOOK_HANDLE)
TSNOW=>TEB_GREENROOF_MODEL(KTO,KTO_PATCH)%TSNOW
XWR=>TEB_GREENROOF_MODEL(KTO,KTO_PATCH)%XWR
XTG=>TEB_GREENROOF_MODEL(KTO,KTO_PATCH)%XTG
XWG=>TEB_GREENROOF_MODEL(KTO,KTO_PATCH)%XWG
XWGI=>TEB_GREENROOF_MODEL(KTO,KTO_PATCH)%XWGI
XRESA=>TEB_GREENROOF_MODEL(KTO,KTO_PATCH)%XRESA
XAN=>TEB_GREENROOF_MODEL(KTO,KTO_PATCH)%XAN
XANDAY=>TEB_GREENROOF_MODEL(KTO,KTO_PATCH)%XANDAY
XANFM=>TEB_GREENROOF_MODEL(KTO,KTO_PATCH)%XANFM
XLE=>TEB_GREENROOF_MODEL(KTO,KTO_PATCH)%XLE
XFAPARC=>TEB_GREENROOF_MODEL(KTO,KTO_PATCH)%XFAPARC
XFAPIRC=>TEB_GREENROOF_MODEL(KTO,KTO_PATCH)%XFAPIRC
XLAI_EFFC=>TEB_GREENROOF_MODEL(KTO,KTO_PATCH)%XLAI_EFFC
XMUS=>TEB_GREENROOF_MODEL(KTO,KTO_PATCH)%XMUS
XRESP_BIOMASS=>TEB_GREENROOF_MODEL(KTO,KTO_PATCH)%XRESP_BIOMASS
XBIOMASS=>TEB_GREENROOF_MODEL(KTO,KTO_PATCH)%XBIOMASS
XPSNG=>TEB_GREENROOF_MODEL(KTO,KTO_PATCH)%XPSNG
XPSNV_A=>TEB_GREENROOF_MODEL(KTO,KTO_PATCH)%XPSNV_A
XPSNV=>TEB_GREENROOF_MODEL(KTO,KTO_PATCH)%XPSNV
XPSN=>TEB_GREENROOF_MODEL(KTO,KTO_PATCH)%XPSN
XSNOWFREE_ALB=>TEB_GREENROOF_MODEL(KTO,KTO_PATCH)%XSNOWFREE_ALB
XSNOWFREE_ALB_VEG=>TEB_GREENROOF_MODEL(KTO,KTO_PATCH)%XSNOWFREE_ALB_VEG
XSNOWFREE_ALB_SOIL=>TEB_GREENROOF_MODEL(KTO,KTO_PATCH)%XSNOWFREE_ALB_SOIL
IF (LHOOK) CALL DR_HOOK('MODD_TEB_GREENROOF_N:TEB_GREENROOF_GOTO_MODEL',1,ZHOOK_HANDLE)
!
END SUBROUTINE TEB_GREENROOF_GOTO_MODEL

SUBROUTINE TEB_GREENROOF_ALLOC(KMODEL,KPATCH)
INTEGER, INTENT(IN) :: KMODEL, KPATCH
INTEGER :: J, JP
REAL(KIND=JPRB) :: ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK("MODD_TEB_GREENROOF_N:TEB_GREENROOF_ALLOC",0,ZHOOK_HANDLE)
ALLOCATE(TEB_GREENROOF_MODEL(KMODEL,KPATCH))
DO J=1,KMODEL
 DO JP=1,KPATCH
  NULLIFY(TEB_GREENROOF_MODEL(J,JP)%XWR)
  NULLIFY(TEB_GREENROOF_MODEL(J,JP)%XTG)
  NULLIFY(TEB_GREENROOF_MODEL(J,JP)%XWG)
  NULLIFY(TEB_GREENROOF_MODEL(J,JP)%XWGI)
  NULLIFY(TEB_GREENROOF_MODEL(J,JP)%XRESA)
  NULLIFY(TEB_GREENROOF_MODEL(J,JP)%XAN)
  NULLIFY(TEB_GREENROOF_MODEL(J,JP)%XANDAY)
  NULLIFY(TEB_GREENROOF_MODEL(J,JP)%XANFM)
  NULLIFY(TEB_GREENROOF_MODEL(J,JP)%XLE)
  NULLIFY(TEB_GREENROOF_MODEL(J,JP)%XFAPARC)
  NULLIFY(TEB_GREENROOF_MODEL(J,JP)%XFAPIRC)
  NULLIFY(TEB_GREENROOF_MODEL(J,JP)%XLAI_EFFC)  
  NULLIFY(TEB_GREENROOF_MODEL(J,JP)%XMUS)     
  NULLIFY(TEB_GREENROOF_MODEL(J,JP)%XRESP_BIOMASS)
  NULLIFY(TEB_GREENROOF_MODEL(J,JP)%XBIOMASS)
  NULLIFY(TEB_GREENROOF_MODEL(J,JP)%XPSNG)
  NULLIFY(TEB_GREENROOF_MODEL(J,JP)%XPSNV)
  NULLIFY(TEB_GREENROOF_MODEL(J,JP)%XPSNV_A)
  NULLIFY(TEB_GREENROOF_MODEL(J,JP)%XPSN)
  NULLIFY(TEB_GREENROOF_MODEL(J,JP)%XSNOWFREE_ALB)
  NULLIFY(TEB_GREENROOF_MODEL(J,JP)%XSNOWFREE_ALB_VEG)
  NULLIFY(TEB_GREENROOF_MODEL(J,JP)%XSNOWFREE_ALB_SOIL)
 ENDDO
ENDDO
IF (LHOOK) CALL DR_HOOK("MODD_TEB_GREENROOF_N:TEB_GREENROOF_ALLOC",1,ZHOOK_HANDLE)
END SUBROUTINE TEB_GREENROOF_ALLOC

SUBROUTINE TEB_GREENROOF_DEALLO
REAL(KIND=JPRB) :: ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK("MODD_TEB_GREENROOF_N:TEB_GREENROOF_DEALLO",0,ZHOOK_HANDLE)
IF (ALLOCATED(TEB_GREENROOF_MODEL)) DEALLOCATE(TEB_GREENROOF_MODEL)
IF (LHOOK) CALL DR_HOOK("MODD_TEB_GREENROOF_N:TEB_GREENROOF_DEALLO",1,ZHOOK_HANDLE)
END SUBROUTINE TEB_GREENROOF_DEALLO

END MODULE MODD_TEB_GREENROOF_n
