!     ################
      MODULE MODD_DATA_BEM_n
!     ################
!
!!****  *MODD_DATA_BEM_n - declaration of surface parameters for BEM
!!
!!    PURPOSE
!!    -------
!     Declaration of surface parameters
!
!!
!!**  IMPLICIT ARGUMENTS
!!    ------------------
!!      None 
!!
!!    REFERENCE
!!    ---------
!!
!!    AUTHOR
!!    ------
!!      G. Pigeon   *Meteo France*
!!
!!    MODIFICATIONS
!!    -------------
!!      Original       08/2011
!
!*       0.   DECLARATIONS
!             ------------
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE

TYPE DATA_BEM_t
  !
  LOGICAL :: LDATA_TCOOL_TARGET 
  LOGICAL :: LDATA_THEAT_TARGET 
  LOGICAL :: LDATA_F_WASTE_CAN   
  LOGICAL :: LDATA_EFF_HEAT   
  LOGICAL :: LDATA_HC_FLOOR     
  LOGICAL :: LDATA_TC_FLOOR     
  LOGICAL :: LDATA_D_FLOOR 
  LOGICAL :: LDATA_QIN          
  LOGICAL :: LDATA_QIN_FRAD     
  LOGICAL :: LDATA_SHGC         
  LOGICAL :: LDATA_U_WIN        
  LOGICAL :: LDATA_GR           
  LOGICAL :: LDATA_SHGC_SH
  LOGICAL :: LDATA_FLOOR_HEIGHT 
  LOGICAL :: LDATA_INF  
  LOGICAL :: LDATA_F_WATER_COND  
  LOGICAL :: LDATA_SHADE
  LOGICAL :: LDATA_NATVENT
  LOGICAL :: LDATA_QIN_FLAT     
  LOGICAL :: LDATA_HR_TARGET    
  LOGICAL :: LDATA_V_VENT   
  LOGICAL :: LDATA_CAP_SYS_HEAT 
  LOGICAL :: LDATA_CAP_SYS_RAT  
  LOGICAL :: LDATA_T_ADP        
  LOGICAL :: LDATA_M_SYS_RAT    
  LOGICAL :: LDATA_COP_RAT      
  LOGICAL :: LDATA_T_SIZE_MAX    
  LOGICAL :: LDATA_T_SIZE_MIN  
!
! Number of layers in the specification of thermal characteristics
!
  INTEGER                    :: NPAR_FLOOR_LAYER   ! number of layers in roofs
!
!
! Parameters:
!
  REAL, POINTER, DIMENSION(:)   :: XPAR_TCOOL_TARGET ! cooling setpoint of indoor air
  REAL, POINTER, DIMENSION(:)   :: XPAR_THEAT_TARGET ! heating setpoint of indoor air
  REAL, POINTER, DIMENSION(:)   :: XPAR_F_WASTE_CAN  ! fraction of waste heat into the canyon
  REAL, POINTER, DIMENSION(:)   :: XPAR_EFF_HEAT     ! efficiency of the heating system
  REAL, POINTER, DIMENSION(:,:) :: XPAR_HC_FLOOR     ! heat capacity of floor layers [J m-3 K-1]
  REAL, POINTER, DIMENSION(:,:) :: XPAR_TC_FLOOR     ! thermal conductivity of floor layers [W m-1 K-1]
  REAL, POINTER, DIMENSION(:,:) :: XPAR_D_FLOOR      ! thickness of floor layers [m]
  REAL, POINTER, DIMENSION(:)   :: XPAR_QIN          ! internal heat gains [W m-2(floor)]
  REAL, POINTER, DIMENSION(:)   :: XPAR_QIN_FRAD     ! radiant fraction of internal heat gains
  REAL, POINTER, DIMENSION(:)   :: XPAR_SHGC         ! solar transmitance of windows
  REAL, POINTER, DIMENSION(:)   :: XPAR_U_WIN        ! glazing thermal resistance [K m W-2]
  REAL, POINTER, DIMENSION(:)   :: XPAR_GR           ! glazing ratio
  REAL, POINTER, DIMENSION(:)   :: XPAR_SHGC_SH      ! solar transmitance of windows + shading
  REAL, POINTER, DIMENSION(:)   :: XPAR_FLOOR_HEIGHT ! building floor height [m]
  REAL, POINTER, DIMENSION(:)   :: XPAR_INF          ! infiltration/ventilation flow rate [AC/H]
!
  REAL, POINTER, DIMENSION(:)   :: XPAR_F_WATER_COND ! fraction of evaporation for condensers
  REAL, POINTER, DIMENSION(:)   :: XPAR_SHADE        ! Flag to activate shading devices 0->inactivated , 1->activated
  REAL, POINTER, DIMENSION(:)   :: XPAR_NATVENT      ! Flag to describe bld surventilation solution 0-> NONE ; 1 -> MANU ; 2-> AUTO
  REAL, POINTER, DIMENSION(:)   :: XPAR_QIN_FLAT     ! Latent franction of internal heat gains
  REAL, POINTER, DIMENSION(:)   :: XPAR_HR_TARGET    ! Relative humidity setpoint
  REAL, POINTER, DIMENSION(:)   :: XPAR_V_VENT       ! Ventilation flow rate [AC/H]
  REAL, POINTER, DIMENSION(:)   :: XPAR_CAP_SYS_HEAT ! Capacity of the heating system 
                                                     ! [W m-2(bld)]
  REAL, POINTER, DIMENSION(:)   :: XPAR_CAP_SYS_RAT  ! Rated capacity of the cooling system
                                                     ! [W m-2(bld)]
  REAL, POINTER, DIMENSION(:)   :: XPAR_T_ADP        ! Apparatus dewpoint temperature of the
                                                     ! cooling coil [K]
  REAL, POINTER, DIMENSION(:)   :: XPAR_M_SYS_RAT    ! Rated HVAC mass flow rate 
                                                     ! [kg s-1 m-2(bld)]
  REAL, POINTER, DIMENSION(:)   :: XPAR_COP_RAT      ! Rated COP of the cooling system
  REAL, POINTER, DIMENSION(:)   :: XPAR_T_SIZE_MAX   ! 
  REAL, POINTER, DIMENSION(:)   :: XPAR_T_SIZE_MIN   ! 
!
END TYPE DATA_BEM_t

TYPE(DATA_BEM_t), ALLOCATABLE, TARGET, SAVE :: DATA_BEM_MODEL(:)

TYPE(DATA_BEM_t), POINTER :: DATA_BEM => NULL()
!$OMP THREADPRIVATE(DATA_BEM)

CONTAINS

SUBROUTINE DATA_BEM_GOTO_MODEL(KFROM, KTO, LKFROM)
INTEGER, INTENT(IN) :: KFROM, KTO
LOGICAL, INTENT(IN) :: LKFROM
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
! Current model is set to model KTO
!
IF (LHOOK) CALL DR_HOOK('MODD_DATA_BEM_N:DATA_BEM_GOTO_MODEL',0,ZHOOK_HANDLE)

DATA_BEM => DATA_BEM_MODEL(KTO)

IF (LHOOK) CALL DR_HOOK('MODD_DATA_BEM_N:DATA_BEM_GOTO_MODEL',1,ZHOOK_HANDLE)
!
END SUBROUTINE DATA_BEM_GOTO_MODEL
!
SUBROUTINE DATA_BEM_ALLOC(KMODEL)
INTEGER, INTENT(IN) :: KMODEL
INTEGER :: J
REAL(KIND=JPRB) :: ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK("MODD_DATA_BEM_N:DATA_BEM_ALLOC",0,ZHOOK_HANDLE)
ALLOCATE(DATA_BEM_MODEL(KMODEL))
DO J=1,KMODEL
  NULLIFY(DATA_BEM_MODEL(J)%XPAR_TCOOL_TARGET)
  NULLIFY(DATA_BEM_MODEL(J)%XPAR_THEAT_TARGET)
  NULLIFY(DATA_BEM_MODEL(J)%XPAR_F_WASTE_CAN)  
  NULLIFY(DATA_BEM_MODEL(J)%XPAR_EFF_HEAT)
  NULLIFY(DATA_BEM_MODEL(J)%XPAR_HC_FLOOR)
  NULLIFY(DATA_BEM_MODEL(J)%XPAR_TC_FLOOR)
  NULLIFY(DATA_BEM_MODEL(J)%XPAR_D_FLOOR)
  NULLIFY(DATA_BEM_MODEL(J)%XPAR_QIN)
  NULLIFY(DATA_BEM_MODEL(J)%XPAR_QIN_FRAD)
  NULLIFY(DATA_BEM_MODEL(J)%XPAR_SHGC) 
  NULLIFY(DATA_BEM_MODEL(J)%XPAR_U_WIN)
  NULLIFY(DATA_BEM_MODEL(J)%XPAR_GR)
  NULLIFY(DATA_BEM_MODEL(J)%XPAR_FLOOR_HEIGHT)
  NULLIFY(DATA_BEM_MODEL(J)%XPAR_INF)
  NULLIFY(DATA_BEM_MODEL(J)%XPAR_F_WATER_COND)
  NULLIFY(DATA_BEM_MODEL(J)%XPAR_QIN_FLAT)
  NULLIFY(DATA_BEM_MODEL(J)%XPAR_HR_TARGET)
  NULLIFY(DATA_BEM_MODEL(J)%XPAR_V_VENT)
  NULLIFY(DATA_BEM_MODEL(J)%XPAR_CAP_SYS_HEAT)
  NULLIFY(DATA_BEM_MODEL(J)%XPAR_CAP_SYS_RAT)
  NULLIFY(DATA_BEM_MODEL(J)%XPAR_T_ADP)
  NULLIFY(DATA_BEM_MODEL(J)%XPAR_M_SYS_RAT)
  NULLIFY(DATA_BEM_MODEL(J)%XPAR_COP_RAT)
  NULLIFY(DATA_BEM_MODEL(J)%XPAR_T_SIZE_MAX)
  NULLIFY(DATA_BEM_MODEL(J)%XPAR_T_SIZE_MIN)
  NULLIFY(DATA_BEM_MODEL(J)%XPAR_SHADE)
  NULLIFY(DATA_BEM_MODEL(J)%XPAR_NATVENT)
ENDDO
DATA_BEM_MODEL(:)%LDATA_TCOOL_TARGET = .FALSE.
DATA_BEM_MODEL(:)%LDATA_THEAT_TARGET = .FALSE. 
DATA_BEM_MODEL(:)%LDATA_F_WASTE_CAN  = .FALSE.   
DATA_BEM_MODEL(:)%LDATA_EFF_HEAT     = .FALSE.   
DATA_BEM_MODEL(:)%LDATA_HC_FLOOR     = .FALSE.     
DATA_BEM_MODEL(:)%LDATA_TC_FLOOR     = .FALSE.     
DATA_BEM_MODEL(:)%LDATA_D_FLOOR      = .FALSE. 
DATA_BEM_MODEL(:)%LDATA_QIN          = .FALSE.          
DATA_BEM_MODEL(:)%LDATA_QIN_FRAD     = .FALSE.     
DATA_BEM_MODEL(:)%LDATA_SHGC         = .FALSE.         
DATA_BEM_MODEL(:)%LDATA_U_WIN        = .FALSE.        
DATA_BEM_MODEL(:)%LDATA_GR           = .FALSE.           
DATA_BEM_MODEL(:)%LDATA_SHGC_SH      = .FALSE.
DATA_BEM_MODEL(:)%LDATA_FLOOR_HEIGHT = .FALSE. 
DATA_BEM_MODEL(:)%LDATA_INF          = .FALSE.  
DATA_BEM_MODEL(:)%LDATA_F_WATER_COND = .FALSE.  
DATA_BEM_MODEL(:)%LDATA_SHADE        = .FALSE.
DATA_BEM_MODEL(:)%LDATA_NATVENT      = .FALSE.
DATA_BEM_MODEL(:)%LDATA_V_VENT       = .FALSE.   
DATA_BEM_MODEL(:)%LDATA_QIN_FLAT     = .FALSE.     
DATA_BEM_MODEL(:)%LDATA_HR_TARGET    = .FALSE.    
DATA_BEM_MODEL(:)%LDATA_CAP_SYS_HEAT = .FALSE. 
DATA_BEM_MODEL(:)%LDATA_CAP_SYS_RAT  = .FALSE.  
DATA_BEM_MODEL(:)%LDATA_T_ADP        = .FALSE.        
DATA_BEM_MODEL(:)%LDATA_M_SYS_RAT    = .FALSE.    
DATA_BEM_MODEL(:)%LDATA_COP_RAT      = .FALSE.      
DATA_BEM_MODEL(:)%LDATA_T_SIZE_MAX   = .FALSE.    
DATA_BEM_MODEL(:)%LDATA_T_SIZE_MIN   = .FALSE.
DATA_BEM_MODEL(:)%NPAR_FLOOR_LAYER   =0

IF (LHOOK) CALL DR_HOOK("MODD_DATA_BEM_N:DATA_BEM_ALLOC",1,ZHOOK_HANDLE)
END SUBROUTINE DATA_BEM_ALLOC
!
SUBROUTINE DATA_BEM_DEALLO
REAL(KIND=JPRB) :: ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK("MODD_DATA_BEM_N:DATA_BEM_DEALLO",0,ZHOOK_HANDLE)
IF (ALLOCATED(DATA_BEM_MODEL)) DEALLOCATE(DATA_BEM_MODEL)
IF (ASSOCIATED(DATA_BEM)) NULLIFY(DATA_BEM)
IF (LHOOK) CALL DR_HOOK("MODD_DATA_BEM_N:DATA_BEM_DEALLO",1,ZHOOK_HANDLE)
END SUBROUTINE DATA_BEM_DEALLO
!
END MODULE MODD_DATA_BEM_n
