!     ################
      MODULE MODD_SEAFLUX_SBL_n
!     ################
!
!!****  *MODD_SEAFLUX_SBL_n - declaration of surface parameters for SBL scheme
!!
!!    PURPOSE
!!    -------
!     Declaration of surface parameters
!
!!
!!**  IMPLICIT ARGUMENTS
!!    ------------------
!!      None 
!!
!!    REFERENCE
!!    ---------
!!
!!    AUTHOR
!!    ------
!!      V. Masson   *Meteo France*
!!
!!    MODIFICATIONS
!!    -------------
!!      Original       07/2006
!
!*       0.   DECLARATIONS
!             ------------
!
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE

TYPE SEAFLUX_SBL_t
!
  INTEGER                       :: NLVL ! number      of levels in SBL
  REAL, POINTER, DIMENSION(:,:) :: XZ   ! height of middle of each level grid   (m)
  REAL, POINTER, DIMENSION(:,:) :: XU   ! wind        at each level in SBL      (m/s)
  REAL, POINTER, DIMENSION(:,:) :: XT   ! temperature at each level in SBL      (m/s)
  REAL, POINTER, DIMENSION(:,:) :: XQ   ! humidity    at each level in SBL      (kg/m3)
  REAL, POINTER, DIMENSION(:,:) :: XTKE ! Tke         at each level in SBL      (m2/s2)
  REAL, POINTER, DIMENSION(:)   :: XLMO ! Monin-Obhukov length                  (m)
  REAL, POINTER, DIMENSION(:,:) :: XP   ! pressure    at each level in SBL      (kg/m3)
!
  REAL, POINTER, DIMENSION(:,:) :: XDZ  ! depth       of each level in SBL      (m)
  REAL, POINTER, DIMENSION(:,:) :: XZF  ! height of bottom of each level grid   (m)
  REAL, POINTER, DIMENSION(:,:) :: XDZF ! depth between  each level in SBL      (m)
!
END TYPE SEAFLUX_SBL_t

TYPE(SEAFLUX_SBL_t), ALLOCATABLE, TARGET, SAVE :: SEAFLUX_SBL_MODEL(:)

TYPE(SEAFLUX_SBL_t), POINTER :: SEAFLUX_SBL => NULL()
!$OMP THREADPRIVATE(SEAFLUX_SBL)

CONTAINS

SUBROUTINE SEAFLUX_SBL_GOTO_MODEL(KFROM, KTO, LKFROM)
LOGICAL, INTENT(IN) :: LKFROM
INTEGER, INTENT(IN) :: KFROM, KTO
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
! Current model is set to model KTO
IF (LHOOK) CALL DR_HOOK('MODD_SEAFLUX_SBL_N:SEAFLUX_SBL_GOTO_MODEL',0,ZHOOK_HANDLE)

SEAFLUX_SBL => SEAFLUX_SBL_MODEL(KTO)

IF (LHOOK) CALL DR_HOOK('MODD_SEAFLUX_SBL_N:SEAFLUX_SBL_GOTO_MODEL',1,ZHOOK_HANDLE)

END SUBROUTINE SEAFLUX_SBL_GOTO_MODEL

SUBROUTINE SEAFLUX_SBL_ALLOC(KMODEL)
INTEGER, INTENT(IN) :: KMODEL
INTEGER :: J
REAL(KIND=JPRB) :: ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK("MODD_SEAFLUX_SBL_N:SEAFLUX_SBL_ALLOC",0,ZHOOK_HANDLE)
ALLOCATE(SEAFLUX_SBL_MODEL(KMODEL))
DO J=1,KMODEL
  NULLIFY(SEAFLUX_SBL_MODEL(J)%XZ)
  NULLIFY(SEAFLUX_SBL_MODEL(J)%XU)
  NULLIFY(SEAFLUX_SBL_MODEL(J)%XT)
  NULLIFY(SEAFLUX_SBL_MODEL(J)%XQ)
  NULLIFY(SEAFLUX_SBL_MODEL(J)%XTKE)
  NULLIFY(SEAFLUX_SBL_MODEL(J)%XLMO)
  NULLIFY(SEAFLUX_SBL_MODEL(J)%XP)
  NULLIFY(SEAFLUX_SBL_MODEL(J)%XDZ)
  NULLIFY(SEAFLUX_SBL_MODEL(J)%XZF)
  NULLIFY(SEAFLUX_SBL_MODEL(J)%XDZF)
ENDDO
SEAFLUX_SBL_MODEL(:)%NLVL=0
IF (LHOOK) CALL DR_HOOK("MODD_SEAFLUX_SBL_N:SEAFLUX_SBL_ALLOC",1,ZHOOK_HANDLE)
END SUBROUTINE SEAFLUX_SBL_ALLOC

SUBROUTINE SEAFLUX_SBL_DEALLO
REAL(KIND=JPRB) :: ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK("MODD_SEAFLUX_SBL_N:SEAFLUX_SBL_DEALLO",0,ZHOOK_HANDLE)
IF (ALLOCATED(SEAFLUX_SBL_MODEL)) DEALLOCATE(SEAFLUX_SBL_MODEL)
IF (ASSOCIATED(SEAFLUX_SBL)) NULLIFY(SEAFLUX_SBL)
IF (LHOOK) CALL DR_HOOK("MODD_SEAFLUX_SBL_N:SEAFLUX_SBL_DEALLO",1,ZHOOK_HANDLE)
END SUBROUTINE SEAFLUX_SBL_DEALLO

END MODULE MODD_SEAFLUX_SBL_n
