!######################
MODULE MODD_PACK_ISBA
!######################
!
!!****  *MODD_PACK_ISBA - declaration of packed surface parameters for ISBA scheme
!!
!!    PURPOSE
!!    -------
!
!!
!!**  IMPLICIT ARGUMENTS
!!    ------------------
!!      None 
!!
!!    REFERENCE
!!    ---------
!!
!!    AUTHOR
!!    ------
!!      A. Boone   *Meteo France*
!!
!!    MODIFICATIONS
!!    -------------
!!      Original       20/09/02
!!      A.L. Gibelin    04/2009 : BIOMASS and RESP_BIOMASS arrays 
!!      A.L. Gibelin    04/2009 : TAU_WOOD for NCB option 
!!      A.L. Gibelin    05/2009 : Add carbon spinup
!!      A.L. Gibelin    06/2009 : Soil carbon variables for CNT option
!!      A.L. Gibelin    07/2009 : Suppress RDK and transform GPP as a diagnostic
!!      A.L. Gibelin    07/2009 : Suppress PPST and PPSTF as outputs
!!      P. Samuelsson   10/2014 : MEB and additional snow albedos
!!
!-------------------------------------------------------------------------------
!
!*       0.   DECLARATIONS
!             ------------
!
USE MODD_TYPE_DATE_SURF
!
USE MODD_ISBA_n, ONLY : ISBA_t    
USE MODD_AGRI_n, ONLY : AGRI_t
USE MODD_GRID_n, ONLY : GRID_t
USE MODD_SSO_n, ONLY : SSO_t
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE
!-------------------------------------------------------------------------------
!
TYPE PACK_ISBA_t

  INTEGER :: NSIZE_LSIMPLE
  INTEGER :: NSIZE_L0
  INTEGER :: NSIZE_NSIMPLE
  INTEGER :: NSIZE_N0
  INTEGER :: NSIZE_TSIMPLE
  INTEGER :: NSIZE_T0
  INTEGER :: NSIZE_SIMPLE
  INTEGER :: NSIZE_GROUND
  INTEGER :: NSIZE_VEGTYPE
  INTEGER :: NSIZE_TG
  INTEGER :: NSIZE_SNOW
  INTEGER :: NSIZE_ALB
  INTEGER :: NSIZE_2
  INTEGER :: NSIZE_BIOMASS
  INTEGER :: NSIZE_SOILCARB
  INTEGER :: NSIZE_LITTLEVS
  INTEGER :: NSIZE_LITTER
  INTEGER :: NSIZE_0
  INTEGER :: NSIZE_00
  INTEGER :: NSIZE_000
  INTEGER :: NSIZE_01
  LOGICAL, POINTER, DIMENSION(:,:) :: LBLOCK_SIMPLE 
  LOGICAL, POINTER, DIMENSION(:,:) :: LBLOCK_0
  INTEGER, POINTER, DIMENSION(:,:) :: NBLOCK_SIMPLE 
  INTEGER, POINTER, DIMENSION(:,:) :: NBLOCK_0
  TYPE(DATE_TIME), POINTER, DIMENSION(:,:) :: TBLOCK_SIMPLE
  TYPE(DATE_TIME), POINTER, DIMENSION(:,:) :: TBLOCK_0
  REAL, POINTER, DIMENSION(:,:) :: XBLOCK_SIMPLE
  REAL, POINTER, DIMENSION(:,:,:) :: XBLOCK_GROUND
  REAL, POINTER, DIMENSION(:,:,:) :: XBLOCK_VEGTYPE
  REAL, POINTER, DIMENSION(:,:,:) :: XBLOCK_TG
  REAL, POINTER, DIMENSION(:,:,:) :: XBLOCK_SNOW
  REAL, POINTER, DIMENSION(:,:,:) :: XBLOCK_ALB
  REAL, POINTER, DIMENSION(:,:,:) :: XBLOCK_2
  REAL, POINTER, DIMENSION(:,:,:) :: XBLOCK_BIOMASS
  REAL, POINTER, DIMENSION(:,:,:) :: XBLOCK_SOILCARB
  REAL, POINTER, DIMENSION(:,:,:) :: XBLOCK_LITTLEVS
  REAL, POINTER, DIMENSION(:,:,:,:) :: XBLOCK_LITTER
  REAL, POINTER, DIMENSION(:,:) :: XBLOCK_0
  REAL, POINTER, DIMENSION(:,:,:) :: XBLOCK_00
  REAL, POINTER, DIMENSION(:,:,:,:) :: XBLOCK_000
  REAL, POINTER, DIMENSION(:,:,:) :: XBLOCK_01
!
  TYPE(ISBA_t) :: I
  
  TYPE(AGRI_t) :: AG

  TYPE(GRID_t) :: G

  TYPE(SSO_t) :: ISS

END TYPE PACK_ISBA_t
!
!-------------------------------------------------------------------------------
!
CONTAINS
!
!
SUBROUTINE PACK_ISBA_INIT(YPACK_ISBA)
TYPE(PACK_ISBA_t), INTENT(INOUT) :: YPACK_ISBA
REAL(KIND=JPRB) :: ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK("MODD_PACK_ISBA_N:PACK_ISBA_INIT",0,ZHOOK_HANDLE)
  NULLIFY(YPACK_ISBA%LBLOCK_SIMPLE)
  NULLIFY(YPACK_ISBA%LBLOCK_0)
  NULLIFY(YPACK_ISBA%NBLOCK_SIMPLE)
  NULLIFY(YPACK_ISBA%NBLOCK_0)
  NULLIFY(YPACK_ISBA%TBLOCK_SIMPLE)
  NULLIFY(YPACK_ISBA%TBLOCK_0)
  NULLIFY(YPACK_ISBA%XBLOCK_SIMPLE)
  NULLIFY(YPACK_ISBA%XBLOCK_GROUND)
  NULLIFY(YPACK_ISBA%XBLOCK_VEGTYPE)
  NULLIFY(YPACK_ISBA%XBLOCK_TG)
  NULLIFY(YPACK_ISBA%XBLOCK_SNOW)
  NULLIFY(YPACK_ISBA%XBLOCK_ALB)
  NULLIFY(YPACK_ISBA%XBLOCK_2)
  NULLIFY(YPACK_ISBA%XBLOCK_BIOMASS)
  NULLIFY(YPACK_ISBA%XBLOCK_SOILCARB)
  NULLIFY(YPACK_ISBA%XBLOCK_LITTLEVS)
  NULLIFY(YPACK_ISBA%XBLOCK_LITTER)
  NULLIFY(YPACK_ISBA%XBLOCK_0)
  NULLIFY(YPACK_ISBA%XBLOCK_00)
  NULLIFY(YPACK_ISBA%XBLOCK_000)
  NULLIFY(YPACK_ISBA%XBLOCK_01)
IF (LHOOK) CALL DR_HOOK("MODD_PACK_ISBA_N:PACK_ISBA_INIT",1,ZHOOK_HANDLE)
END SUBROUTINE PACK_ISBA_INIT


END MODULE MODD_PACK_ISBA
