!     #########
MODULE MODE_DIAG
!   #####################
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
USE MODD_SURF_PAR, ONLY : XUNDEF
USE MODD_DIAG_n, ONLY : DIAG_t, DIAG_OPTIONS_t
!
IMPLICIT NONE
!
CONTAINS 
!
SUBROUTINE ALLOC_SURF_BUD(DGIA,KLUA,KLUAC,KSWA)
!
TYPE(DIAG_t), INTENT(INOUT) :: DGIA
INTEGER, INTENT(IN) :: KLUA
INTEGER, INTENT(IN) :: KLUAC
INTEGER, INTENT(IN) :: KSWA
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
IF (LHOOK) CALL DR_HOOK('MODE_DIAG:ALLOC_SURF_BUD',0,ZHOOK_HANDLE)
!
ALLOCATE(DGIA%XRN           (KLUAC))
ALLOCATE(DGIA%XH            (KLUAC))
ALLOCATE(DGIA%XLE           (KLUAC))
ALLOCATE(DGIA%XLEI          (KLUAC))
ALLOCATE(DGIA%XGFLUX        (KLUAC))
ALLOCATE(DGIA%XEVAP      (KLUAC))
ALLOCATE(DGIA%XSUBL      (KLUAC))
!
ALLOCATE(DGIA%XSWD          (KLUAC))
ALLOCATE(DGIA%XSWU          (KLUAC))
ALLOCATE(DGIA%XLWD          (KLUAC))
ALLOCATE(DGIA%XLWU          (KLUAC))
ALLOCATE(DGIA%XFMU          (KLUAC))
ALLOCATE(DGIA%XFMV          (KLUAC))
!
IF (KLUAC>0) THEN
  DGIA%XRN      = XUNDEF
  DGIA%XH       = XUNDEF
  DGIA%XLE      = XUNDEF
  DGIA%XLEI     = XUNDEF
  DGIA%XGFLUX   = XUNDEF
  DGIA%XEVAP       = XUNDEF
  DGIA%XSUBL       = XUNDEF  
  DGIA%XSWD     = XUNDEF
  DGIA%XSWU     = XUNDEF
  DGIA%XLWD     = XUNDEF
  DGIA%XLWU     = XUNDEF
  DGIA%XFMU     = XUNDEF
  DGIA%XFMV     = XUNDEF
ENDIF
!
ALLOCATE(DGIA%XSWBD         (KLUA,KSWA))
ALLOCATE(DGIA%XSWBU         (KLUA,KSWA))
!
IF (KLUA>0) THEN
  DGIA%XSWBD    = XUNDEF
  DGIA%XSWBU    = XUNDEF
ENDIF
!
IF (LHOOK) CALL DR_HOOK('MODE_DIAG:ALLOC_SURF_BUD',1,ZHOOK_HANDLE)
!
END SUBROUTINE ALLOC_SURF_BUD
!
SUBROUTINE ALLOC_N2M_BUD(DGIA,KLUA)
!
TYPE(DIAG_t), INTENT(INOUT) :: DGIA
INTEGER, INTENT(IN) :: KLUA
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
IF (LHOOK) CALL DR_HOOK('MODE_DIAG:ALLOC_N2M_BUD',0,ZHOOK_HANDLE)
!
ALLOCATE(DGIA%XRI           (KLUA))
ALLOCATE(DGIA%XT2M          (KLUA))
ALLOCATE(DGIA%XT2M_MIN      (KLUA))
ALLOCATE(DGIA%XT2M_MAX      (KLUA))
ALLOCATE(DGIA%XQ2M          (KLUA))
ALLOCATE(DGIA%XHU2M         (KLUA))
ALLOCATE(DGIA%XHU2M_MIN     (KLUA))
ALLOCATE(DGIA%XHU2M_MAX     (KLUA))
ALLOCATE(DGIA%XZON10M       (KLUA))
ALLOCATE(DGIA%XMER10M       (KLUA))
ALLOCATE(DGIA%XWIND10M      (KLUA))
ALLOCATE(DGIA%XWIND10M_MAX  (KLUA))
ALLOCATE(DGIA%XSFCO2        (KLUA))
!
IF (KLUA>0) THEN
  DGIA%XRI      = XUNDEF
  DGIA%XT2M     = XUNDEF
  DGIA%XT2M_MIN = XUNDEF
  DGIA%XT2M_MAX = -XUNDEF
  DGIA%XQ2M     = XUNDEF
  DGIA%XHU2M    = XUNDEF
  DGIA%XHU2M_MIN= XUNDEF
  DGIA%XHU2M_MAX= -XUNDEF
  DGIA%XZON10M  = XUNDEF
  DGIA%XMER10M  = XUNDEF
  DGIA%XWIND10M = XUNDEF
  DGIA%XWIND10M_MAX = 0.0
  DGIA%XSFCO2       = XUNDEF
ENDIF
!
IF (LHOOK) CALL DR_HOOK('MODE_DIAG:ALLOC_N2M_BUD',1,ZHOOK_HANDLE)
!
END SUBROUTINE ALLOC_N2M_BUD
!
SUBROUTINE ALLOC_COEF_BUD(DGIA,KLUA)
!
TYPE(DIAG_t), INTENT(INOUT) :: DGIA
INTEGER, INTENT(IN) :: KLUA
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
IF (LHOOK) CALL DR_HOOK('MODE_DIAG:ALLOC_COEF_BUD',0,ZHOOK_HANDLE)
!
ALLOCATE(DGIA%XCD   (KLUA))
ALLOCATE(DGIA%XCH   (KLUA))
ALLOCATE(DGIA%XCE   (KLUA))
ALLOCATE(DGIA%XZ0   (KLUA))
ALLOCATE(DGIA%XZ0H  (KLUA))
ALLOCATE(DGIA%XZ0EFF(KLUA))
!
IF (KLUA>0) THEN
  DGIA%XCD      = XUNDEF
  DGIA%XCH      = XUNDEF
  DGIA%XCE      = XUNDEF
  DGIA%XZ0      = XUNDEF
  DGIA%XZ0H     = XUNDEF
  DGIA%XZ0EFF   = XUNDEF
ENDIF

IF (LHOOK) CALL DR_HOOK('MODE_DIAG:ALLOC_COEF_BUD',1,ZHOOK_HANDLE)
!
END SUBROUTINE ALLOC_COEF_BUD
!
SUBROUTINE INIT_BUD(DGO,DGIA,DGIAC,PVAL)
!
TYPE(DIAG_OPTIONS_t), INTENT(IN) :: DGO
TYPE(DIAG_t), INTENT(INOUT) :: DGIA
TYPE(DIAG_t), INTENT(INOUT) :: DGIAC
REAL, INTENT(IN) :: PVAL
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
IF (LHOOK) CALL DR_HOOK('MODE_DIAG:INIT_BUD',0,ZHOOK_HANDLE)
!
IF (DGO%LSURF_BUDGET) CALL INIT_SURF_BUD(DGIA,PVAL)
IF (DGO%LSURF_BUDGETC) CALL INIT_SURF_BUD(DGIAC,PVAL)
IF (DGO%N2M>=1) CALL INIT_N2M_BUD(DGIA,PVAL)
IF (DGO%LCOEF) CALL INIT_COEF_BUD(DGIA,PVAL)
DGIA%XTS = PVAL
!
IF (LHOOK) CALL DR_HOOK('MODE_DIAG:INIT_BUD',1,ZHOOK_HANDLE)
!
END SUBROUTINE INIT_BUD

!
SUBROUTINE INIT_SURF_BUD(DGIA,PVAL)
!
TYPE(DIAG_t), INTENT(INOUT) :: DGIA
REAL, INTENT(IN) :: PVAL
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
IF (LHOOK) CALL DR_HOOK('MODE_DIAG:INIT_SURF_BUD',0,ZHOOK_HANDLE)
!
DGIA%XRN      = PVAL
DGIA%XH       = PVAL
DGIA%XLE      = PVAL
DGIA%XLEI     = PVAL
DGIA%XGFLUX   = PVAL
DGIA%XEVAP    = PVAL
DGIA%XSUBL    = PVAL
DGIA%XSWD     = PVAL
DGIA%XSWU     = PVAL
DGIA%XLWD     = PVAL
DGIA%XLWU     = PVAL
DGIA%XFMU     = PVAL
DGIA%XFMV     = PVAL
!
IF (SIZE(DGIA%XSWBD)>0) THEN
  DGIA%XSWBD    = PVAL
  DGIA%XSWBU    = PVAL
ENDIF
!
IF (LHOOK) CALL DR_HOOK('MODE_DIAG:INIT_SURF_BUD',1,ZHOOK_HANDLE)
!
END SUBROUTINE INIT_SURF_BUD
!
SUBROUTINE INIT_N2M_BUD(DGIA,PVAL)
!
TYPE(DIAG_t), INTENT(INOUT) :: DGIA
REAL, INTENT(IN) :: PVAL
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
IF (LHOOK) CALL DR_HOOK('MODE_DIAG:INIT_N2M_BUD',0,ZHOOK_HANDLE)
!
DGIA%XRI      = PVAL
DGIA%XT2M     = PVAL
DGIA%XT2M_MIN = PVAL
DGIA%XT2M_MAX = PVAL
DGIA%XQ2M     = PVAL
DGIA%XHU2M    = PVAL
DGIA%XHU2M_MIN= PVAL
DGIA%XHU2M_MAX= PVAL
DGIA%XZON10M  = PVAL
DGIA%XMER10M  = PVAL
DGIA%XWIND10M = PVAL
DGIA%XWIND10M_MAX = PVAL
DGIA%XSFCO2       = PVAL
!
IF (LHOOK) CALL DR_HOOK('MODE_DIAG:INIT_N2M_BUD',1,ZHOOK_HANDLE)
!
END SUBROUTINE INIT_N2M_BUD
!
SUBROUTINE INIT_COEF_BUD(DGIA,PVAL)
!
TYPE(DIAG_t), INTENT(INOUT) :: DGIA
REAL, INTENT(IN) :: PVAL
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
IF (LHOOK) CALL DR_HOOK('MODE_DIAG:INIT_COEF_BUD',0,ZHOOK_HANDLE)
!
DGIA%XCD      = PVAL
DGIA%XCH      = PVAL
DGIA%XCE      = PVAL
DGIA%XZ0      = PVAL
DGIA%XZ0H     = PVAL
DGIA%XZ0EFF   = PVAL
!
IF (LHOOK) CALL DR_HOOK('MODE_DIAG:INIT_COEF_BUD',1,ZHOOK_HANDLE)
!
END SUBROUTINE INIT_COEF_BUD
!
SUBROUTINE DIAG_EVAP(DGO, DG, DGC, HPROGRAM, DGUP, DGUPC, KMASK )
!
IMPLICIT NONE
!
TYPE(DIAG_OPTIONS_t), INTENT(IN) :: DGO
TYPE(DIAG_t), INTENT(INOUT) :: DG
TYPE(DIAG_t), INTENT(INOUT) :: DGC
 CHARACTER(LEN=6),   INTENT(IN)  :: HPROGRAM ! program calling surf. schemes
TYPE(DIAG_t), INTENT(INOUT) :: DGUP
TYPE(DIAG_t), INTENT(INOUT) :: DGUPC
INTEGER, DIMENSION(:), INTENT(IN) :: KMASK
!
INTEGER :: JJ, ISIZE
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
IF (LHOOK) CALL DR_HOOK('MODE_DIAG:DIAG_EVAP',0,ZHOOK_HANDLE)
!
ISIZE = SIZE(KMASK)
!
 CALL DIAG_CUMUL(DGO, DG, DGC, HPROGRAM, DGUP, DGUPC, KMASK)
!
IF (DGO%LSURF_BUDGET) THEN
  DO JJ=1,ISIZE
    DGUP%XEVAP    (KMASK(JJ))  = DG%XEVAP     (JJ)
    DGUP%XSUBL    (KMASK(JJ))  = DG%XSUBL     (JJ)
  ENDDO
END IF
!
IF (LHOOK) CALL DR_HOOK('MODE_DIAG:DIAG_EVAP',1,ZHOOK_HANDLE)
!
END SUBROUTINE DIAG_EVAP
!
SUBROUTINE DIAG_CUMUL(DGO, DG, DGC, HPROGRAM, DGUP, DGUPC, KMASK )
!
IMPLICIT NONE
!
TYPE(DIAG_OPTIONS_t), INTENT(IN) :: DGO
TYPE(DIAG_t), INTENT(INOUT) :: DG
TYPE(DIAG_t), INTENT(INOUT) :: DGC
 CHARACTER(LEN=6),   INTENT(IN)  :: HPROGRAM ! program calling surf. schemes
TYPE(DIAG_t), INTENT(INOUT) :: DGUP
TYPE(DIAG_t), INTENT(INOUT) :: DGUPC
INTEGER, DIMENSION(:), INTENT(IN) :: KMASK
!
INTEGER :: JJ, ISIZE
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
IF (LHOOK) CALL DR_HOOK('MODE_DIAG:DIAG_CUMUL',0,ZHOOK_HANDLE)
!
ISIZE = SIZE(KMASK)
!
 CALL DIAG(DGO, DG, HPROGRAM, DGUP, KMASK)
!
IF (DGO%LSURF_BUDGETC) THEN
  DO JJ=1,ISIZE
    DGUPC%XRN      (KMASK(JJ))  = DGC%XRN       (JJ)
    DGUPC%XH       (KMASK(JJ))  = DGC%XH        (JJ)
    DGUPC%XLE      (KMASK(JJ))  = DGC%XLE       (JJ)
    DGUPC%XLEI     (KMASK(JJ))  = DGC%XLEI      (JJ)
    DGUPC%XGFLUX   (KMASK(JJ))  = DGC%XGFLUX    (JJ)
    DGUPC%XEVAP    (KMASK(JJ))  = DGC%XEVAP     (JJ)
    DGUPC%XSUBL    (KMASK(JJ))  = DGC%XSUBL     (JJ)
    DGUPC%XSWD     (KMASK(JJ))  = DGC%XSWD      (JJ)
    DGUPC%XSWU     (KMASK(JJ))  = DGC%XSWU      (JJ)
    DGUPC%XLWD     (KMASK(JJ))  = DGC%XLWD      (JJ)
    DGUPC%XLWU     (KMASK(JJ))  = DGC%XLWU      (JJ)
    DGUPC%XFMU     (KMASK(JJ))  = DGC%XFMU      (JJ)
    DGUPC%XFMV     (KMASK(JJ))  = DGC%XFMV      (JJ)
  ENDDO        
END IF
!
IF (LHOOK) CALL DR_HOOK('MODE_DIAG:DIAG_CUMUL',1,ZHOOK_HANDLE)
!
END SUBROUTINE DIAG_CUMUL
!
SUBROUTINE DIAG(DGO, DG, HPROGRAM, DGUP, KMASK )
!
IMPLICIT NONE
!
TYPE(DIAG_OPTIONS_t), INTENT(IN) :: DGO
TYPE(DIAG_t), INTENT(INOUT) :: DG
 CHARACTER(LEN=6),   INTENT(IN)  :: HPROGRAM ! program calling surf. schemes
TYPE(DIAG_t), INTENT(INOUT) :: DGUP
INTEGER, DIMENSION(:), INTENT(IN) :: KMASK
!
INTEGER :: JJ, ISIZE
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
IF (LHOOK) CALL DR_HOOK('MODE_DIAG:DIAG',0,ZHOOK_HANDLE)
!
ISIZE = SIZE(KMASK)
!
IF (DGO%LSURF_BUDGET) THEN
  DO JJ=1,ISIZE
    DGUP%XRN      (KMASK(JJ))  = DG%XRN       (JJ)
    DGUP%XH       (KMASK(JJ))  = DG%XH        (JJ)
    DGUP%XLE      (KMASK(JJ))  = DG%XLE       (JJ)
    DGUP%XLEI     (KMASK(JJ))  = DG%XLEI      (JJ)
    DGUP%XGFLUX   (KMASK(JJ))  = DG%XGFLUX    (JJ)
    DGUP%XSWD     (KMASK(JJ))  = DG%XSWD      (JJ)
    DGUP%XSWU     (KMASK(JJ))  = DG%XSWU      (JJ)
    DGUP%XLWD     (KMASK(JJ))  = DG%XLWD      (JJ)
    DGUP%XLWU     (KMASK(JJ))  = DG%XLWU      (JJ)
    DGUP%XFMU     (KMASK(JJ))  = DG%XFMU      (JJ)
    DGUP%XFMV     (KMASK(JJ))  = DG%XFMV      (JJ)
    DGUP%XSWBD    (KMASK(JJ),:) = DG%XSWBD     (JJ,:)
    DGUP%XSWBU    (KMASK(JJ),:) = DG%XSWBU     (JJ,:)
  ENDDO
END IF
!
IF (DGO%N2M>=1 .OR. DGO%LSURF_BUDGET) THEN
  DO JJ=1,ISIZE
    DGUP%XTS       (KMASK(JJ))  = DG%XTS      (JJ)
  ENDDO        
ENDIF
!
IF (DGO%N2M>=1) THEN
  DO JJ=1,ISIZE
    DGUP%XRI      (KMASK(JJ))  = DG%XRI       (JJ)
    DGUP%XT2M     (KMASK(JJ))  = DG%XT2M      (JJ)
    DGUP%XT2M_MIN (KMASK(JJ))  = DG%XT2M_MIN  (JJ)
    DGUP%XT2M_MAX (KMASK(JJ))  = DG%XT2M_MAX  (JJ)
    DGUP%XQ2M     (KMASK(JJ))  = DG%XQ2M      (JJ)
    DGUP%XHU2M    (KMASK(JJ))  = DG%XHU2M     (JJ)
    DGUP%XHU2M_MIN(KMASK(JJ))  = DG%XHU2M_MIN (JJ)
    DGUP%XHU2M_MAX(KMASK(JJ))  = DG%XHU2M_MAX (JJ)
    DGUP%XZON10M  (KMASK(JJ))  = DG%XZON10M   (JJ)
    DGUP%XMER10M  (KMASK(JJ))  = DG%XMER10M   (JJ)
    DGUP%XWIND10M (KMASK(JJ))  = DG%XWIND10M   (JJ)
    DGUP%XWIND10M_MAX (KMASK(JJ))  = DG%XWIND10M_MAX   (JJ)
  ENDDO        
END IF 
!
IF (DGO%LCOEF) THEN
  DO JJ=1,ISIZE
    DGUP%XCD      (KMASK(JJ))  = DG%XCD       (JJ)
    DGUP%XCH      (KMASK(JJ))  = DG%XCH       (JJ)
    DGUP%XCE      (KMASK(JJ))  = DG%XCE       (JJ)
    DGUP%XQS      (KMASK(JJ))  = DG%XQS       (JJ)
    DGUP%XZ0      (KMASK(JJ))  = DG%XZ0       (JJ)
    DGUP%XZ0H     (KMASK(JJ))  = DG%XZ0H      (JJ)
  ENDDO        
END IF
!
IF (DGO%LSURF_VARS) THEN
  DO JJ=1,ISIZE
    DGUP%XQS      (KMASK(JJ))  = DG%XQS       (JJ)
  ENDDO          
ENDIF
!
IF (LHOOK) CALL DR_HOOK('MODE_DIAG:DIAG',1,ZHOOK_HANDLE)
!
END SUBROUTINE DIAG
!
!-------------------------------------------------------------------------------
!
END MODULE MODE_DIAG
