!     ##################
      MODULE MODN_SEAFLUX_n
!     ##################
!
!!****  *MODN_SEAFLUX_n* - declaration of namelist NAM_SEAFLUXn
!!
!!    PURPOSE
!!    -------
!       The purpose of this module is to specify  the namelist NAM_SEAFLUX_n
!
!!
!!**  IMPLICIT ARGUMENTS
!!    ------------------
!!
!!    REFERENCE
!!    ---------
!!
!!       
!!    AUTHOR
!!    ------
!!	V. Masson    *Meteo France*
!!
!!    MODIFICATIONS
!!    -------------
!!      Original    01/2004                    
!!      Modified    01/2006 : sea flux parameterization.
!!      Modified    08/2009 : LSURF_BUDGETC
!!      Modified    01/2014 : S. Senesi : introduce sea-ice model
!!      Modified    03/2014 : S. Belamari - add NZ0 (to choose PZ0SEA formulation)
!-------------------------------------------------------------------------------
!
!*       0.   DECLARATIONS
!             ------------
!

USE MODD_CH_SEAFLUX_n, ONLY: &
           CCH_DRY_DEP_n => CCH_DRY_DEP  
USE MODD_SEAFLUX_n, ONLY: &
           XTSTEP_n => XTSTEP, &
           XOUT_TSTEP_n => XOUT_TSTEP, &
           CSEA_FLUX_n => CSEA_FLUX, &
           CSEA_ALB_n => CSEA_ALB,   &
           LPWG_n => LPWG,           &
           LPRECIP_n => LPRECIP,     &
           CINTERPOL_SST_n => CINTERPOL_SST,   &
           CINTERPOL_SSS_n => CINTERPOL_SSS,   &
           CINTERPOL_SIC_n => CINTERPOL_SIC,   &
           CINTERPOL_SIT_n => CINTERPOL_SIT,   &
           XFREEZING_SST_n => XFREEZING_SST,   &
           XSIC_EFOLDING_TIME_n => XSIC_EFOLDING_TIME ,&
           XSIT_EFOLDING_TIME_n => XSIT_EFOLDING_TIME ,&
           XSEAICE_TSTEP_n => XSEAICE_TSTEP, &
           XCD_ICE_CST_n => XCD_ICE_CST, &
           XSI_FLX_DRV_n => XSI_FLX_DRV, &
           CSEAICE_SCHEME_n => CSEAICE_SCHEME,   &
           LPWEBB_n => LPWEBB,       &
           NZ0_n => NZ0,             &
           NGRVWAVES_n => NGRVWAVES, &
           XICHCE_n => XICHCE,       &
           LPERTFLUX_n => LPERTFLUX
USE MODD_DIAG_SEAFLUX_n, ONLY: &
           XDIAG_TSTEP_n => XDIAG_TSTEP, &
           N2M_n => N2M,                   &
           L2M_MIN_ZS_n => L2M_MIN_ZS, &
           LSURF_BUDGET_n => LSURF_BUDGET, &
           LRAD_BUDGET_n => LRAD_BUDGET, &
           LSURF_BUDGETC_n => LSURF_BUDGETC, &
           LRESET_BUDGETC_n => LRESET_BUDGETC,  &
           LCOEF_n => LCOEF, &
           LSURF_VARS_n => LSURF_VARS  
USE MODD_OCEAN_n, ONLY: &
           LPROGSST_n => LPROGSST,           &
           NTIME_COUPLING_n => NTIME_COUPLING  
USE MODD_DIAG_OCEAN_n, ONLY: &
           LDIAG_OCEAN_n => LDIAG_OCEAN  
USE MODD_DIAG_SEAICE_n, ONLY: &
           LDIAG_SEAICE_n => LDIAG_SEAICE
!
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE
!
 CHARACTER(LEN=6)  :: CSEA_FLUX
 CHARACTER(LEN=4)  :: CSEA_ALB
REAL     :: XTSTEP
REAL     :: XOUT_TSTEP
REAL     :: XDIAG_TSTEP
INTEGER  :: N2M
LOGICAL  :: L2M_MIN_ZS         
LOGICAL  :: LSURF_BUDGET
LOGICAL  :: LRAD_BUDGET
LOGICAL  :: LSURF_BUDGETC
LOGICAL  :: LRESET_BUDGETC
LOGICAL  :: LCOEF
LOGICAL  :: LSURF_VARS
LOGICAL  :: LPWG
LOGICAL  :: LPRECIP
LOGICAL  :: LPWEBB
LOGICAL  :: LDIAG_OCEAN
LOGICAL  :: LDIAG_SEAICE
CHARACTER(LEN=6)  :: CSEAICE_SCHEME
INTEGER  :: NZ0
INTEGER  :: NGRVWAVES
REAL     :: XICHCE
CHARACTER(LEN=6)  :: CCH_DRY_DEP
LOGICAL  :: LPROGSST
LOGICAL  :: LPERTFLUX              ! True = stochastic flux perturbation (default:False)
INTEGER  :: NTIME_COUPLING
CHARACTER(LEN=6)  :: CINTERPOL_SST
CHARACTER(LEN=6)  :: CINTERPOL_SSS
CHARACTER(LEN=6)  :: CINTERPOL_SIC
CHARACTER(LEN=6)  :: CINTERPOL_SIT
REAL     :: XFREEZING_SST
REAL     :: XSIC_EFOLDING_TIME
REAL     :: XSIT_EFOLDING_TIME
REAL     :: XSEAICE_TSTEP
REAL     :: XCD_ICE_CST
REAL     :: XSI_FLX_DRV
!
NAMELIST/NAM_SEAFLUXn/CSEA_FLUX,CSEA_ALB, LPWG, LPRECIP, LPWEBB, NGRVWAVES, &
                      NZ0, LPROGSST, NTIME_COUPLING, XICHCE, CINTERPOL_SST, &
                      CINTERPOL_SSS, LPERTFLUX
NAMELIST/NAM_DIAG_SURFn/N2M,L2M_MIN_ZS,LSURF_BUDGET,LRAD_BUDGET, &
                          LSURF_BUDGETC,LRESET_BUDGETC,LCOEF,LSURF_VARS  
NAMELIST/NAM_CH_SEAFLUXn/CCH_DRY_DEP
NAMELIST/NAM_DIAG_OCEANn/LDIAG_OCEAN
NAMELIST/NAM_SEAICEn/LDIAG_SEAICE, CINTERPOL_SIC, CINTERPOL_SIT,           &
                     XFREEZING_SST, XSIC_EFOLDING_TIME, XSIT_EFOLDING_TIME,&
                     XSEAICE_TSTEP, XCD_ICE_CST, XSI_FLX_DRV
!
CONTAINS
!
SUBROUTINE INIT_NAM_SEAFLUXn

  REAL(KIND=JPRB) :: ZHOOK_HANDLE

  IF (LHOOK) CALL DR_HOOK('MODN_SEAFLUX_N:INIT_NAM_SEAFLUXN',0,ZHOOK_HANDLE)
  XTSTEP = XTSTEP_n
  XOUT_TSTEP = XOUT_TSTEP_n
  CSEA_FLUX = CSEA_FLUX_n
  CSEA_ALB = CSEA_ALB_n
  LPWG = LPWG_n
  LPRECIP = LPRECIP_n
  CINTERPOL_SST = CINTERPOL_SST_n
  CINTERPOL_SSS = CINTERPOL_SSS_n
  LPWEBB = LPWEBB_n
  NZ0 = NZ0_n
  NGRVWAVES = NGRVWAVES_n
  LPROGSST = LPROGSST_n
  NTIME_COUPLING = NTIME_COUPLING_n
  XICHCE = XICHCE_n
  LPERTFLUX = LPERTFLUX_n
IF (LHOOK) CALL DR_HOOK('MODN_SEAFLUX_N:INIT_NAM_SEAFLUXN',1,ZHOOK_HANDLE)
END SUBROUTINE INIT_NAM_SEAFLUXn

SUBROUTINE UPDATE_NAM_SEAFLUXn

  REAL(KIND=JPRB) :: ZHOOK_HANDLE

  IF (LHOOK) CALL DR_HOOK('MODN_SEAFLUX_N:UPDATE_NAM_SEAFLUXN',0,ZHOOK_HANDLE)
  XTSTEP_n = XTSTEP
  XOUT_TSTEP_n = XOUT_TSTEP  
  CSEA_FLUX_n = CSEA_FLUX
  CSEA_ALB_n = CSEA_ALB
  LPWG_n = LPWG
  LPRECIP_n = LPRECIP
  CINTERPOL_SST_n = CINTERPOL_SST
  CINTERPOL_SSS_n = CINTERPOL_SSS
  LPWEBB_n = LPWEBB
  NZ0_n = NZ0
  NGRVWAVES_n = NGRVWAVES
  LPROGSST_n = LPROGSST
  NTIME_COUPLING_n = NTIME_COUPLING
  XICHCE_n = XICHCE
  LPERTFLUX_n = LPERTFLUX
IF (LHOOK) CALL DR_HOOK('MODN_SEAFLUX_N:UPDATE_NAM_SEAFLUXN',1,ZHOOK_HANDLE)
END SUBROUTINE UPDATE_NAM_SEAFLUXn
!
SUBROUTINE INIT_NAM_DIAG_SURFn

  REAL(KIND=JPRB) :: ZHOOK_HANDLE

  IF (LHOOK) CALL DR_HOOK('MODN_SEAFLUX_N:INIT_NAM_DIAG_SURFN',0,ZHOOK_HANDLE)
  XDIAG_TSTEP = XDIAG_TSTEP_n  
  N2M = N2M_n
  L2M_MIN_ZS = L2M_MIN_ZS_n
  LSURF_BUDGET = LSURF_BUDGET_n
  LRAD_BUDGET = LRAD_BUDGET_n
  LSURF_BUDGETC = LSURF_BUDGETC_n
  LRESET_BUDGETC = LRESET_BUDGETC_n  
  LCOEF = LCOEF_n
  LSURF_VARS = LSURF_VARS_n
IF (LHOOK) CALL DR_HOOK('MODN_SEAFLUX_N:INIT_NAM_DIAG_SURFN',1,ZHOOK_HANDLE)
END SUBROUTINE INIT_NAM_DIAG_SURFn

SUBROUTINE UPDATE_NAM_DIAG_SURFn

  REAL(KIND=JPRB) :: ZHOOK_HANDLE

  IF (LHOOK) CALL DR_HOOK('MODN_SEAFLUX_N:UPDATE_NAM_DIAG_SURFN',0,ZHOOK_HANDLE)
  XDIAG_TSTEP_n = XDIAG_TSTEP  
  N2M_n = N2M
  L2M_MIN_ZS_n = L2M_MIN_ZS
  LSURF_BUDGET_n = LSURF_BUDGET
  LRAD_BUDGET_n = LRAD_BUDGET 
  LSURF_BUDGETC_n = LSURF_BUDGETC
  LRESET_BUDGETC_n = LRESET_BUDGETC  
  LCOEF_n = LCOEF
  LSURF_VARS_n = LSURF_VARS
IF (LHOOK) CALL DR_HOOK('MODN_SEAFLUX_N:UPDATE_NAM_DIAG_SURFN',1,ZHOOK_HANDLE)
END SUBROUTINE UPDATE_NAM_DIAG_SURFn
!
SUBROUTINE INIT_NAM_CH_SEAFLUXn

  REAL(KIND=JPRB) :: ZHOOK_HANDLE

  IF (LHOOK) CALL DR_HOOK('MODN_SEAFLUX_N:INIT_NAM_CH_SEAFLUXN',0,ZHOOK_HANDLE)
  CCH_DRY_DEP = CCH_DRY_DEP_n
IF (LHOOK) CALL DR_HOOK('MODN_SEAFLUX_N:INIT_NAM_CH_SEAFLUXN',1,ZHOOK_HANDLE)
END SUBROUTINE INIT_NAM_CH_SEAFLUXn

SUBROUTINE UPDATE_NAM_CH_SEAFLUXn

  REAL(KIND=JPRB) :: ZHOOK_HANDLE

  IF (LHOOK) CALL DR_HOOK('MODN_SEAFLUX_N:UPDATE_NAM_CH_SEAFLUXN',0,ZHOOK_HANDLE)
  CCH_DRY_DEP_n = CCH_DRY_DEP
IF (LHOOK) CALL DR_HOOK('MODN_SEAFLUX_N:UPDATE_NAM_CH_SEAFLUXN',1,ZHOOK_HANDLE)
END SUBROUTINE UPDATE_NAM_CH_SEAFLUXn

SUBROUTINE INIT_NAM_DIAG_OCEANn

  REAL(KIND=JPRB) :: ZHOOK_HANDLE

  IF (LHOOK) CALL DR_HOOK('MODN_SEAFLUX_N:INIT_NAM_DIAG_OCEANN',0,ZHOOK_HANDLE)
  LDIAG_OCEAN = LDIAG_OCEAN_n
IF (LHOOK) CALL DR_HOOK('MODN_SEAFLUX_N:INIT_NAM_DIAG_OCEANN',1,ZHOOK_HANDLE)
END SUBROUTINE INIT_NAM_DIAG_OCEANn

SUBROUTINE UPDATE_NAM_DIAG_OCEANn

  REAL(KIND=JPRB) :: ZHOOK_HANDLE

  IF (LHOOK) CALL DR_HOOK('MODN_SEAFLUX_N:UPDATE_NAM_DIAG_OCEANN',0,ZHOOK_HANDLE)
  LDIAG_OCEAN_n = LDIAG_OCEAN
IF (LHOOK) CALL DR_HOOK('MODN_SEAFLUX_N:UPDATE_NAM_DIAG_OCEANN',1,ZHOOK_HANDLE)
END SUBROUTINE UPDATE_NAM_DIAG_OCEANn

SUBROUTINE INIT_NAM_SEAICEn

  REAL(KIND=JPRB) :: ZHOOK_HANDLE

  IF (LHOOK) CALL DR_HOOK('MODN_SEAFLUX_N:INIT_NAM_SEAICEN',0,ZHOOK_HANDLE)
  LDIAG_SEAICE = LDIAG_SEAICE_n
  CSEAICE_SCHEME = CSEAICE_SCHEME_n
  CINTERPOL_SIC = CINTERPOL_SIC_n
  CINTERPOL_SIT = CINTERPOL_SIT_n
  XSIC_EFOLDING_TIME=XSIC_EFOLDING_TIME_n
  XSIT_EFOLDING_TIME=XSIT_EFOLDING_TIME_n
  XSEAICE_TSTEP=XSEAICE_TSTEP_n
  XFREEZING_SST = XFREEZING_SST_n
  XCD_ICE_CST = XCD_ICE_CST_n
  XSI_FLX_DRV = XSI_FLX_DRV_n
IF (LHOOK) CALL DR_HOOK('MODN_SEAFLUX_N:INIT_NAM_SEAICEN',1,ZHOOK_HANDLE)
END SUBROUTINE INIT_NAM_SEAICEn

SUBROUTINE UPDATE_NAM_SEAICEn

  REAL(KIND=JPRB) :: ZHOOK_HANDLE

  IF (LHOOK) CALL DR_HOOK('MODN_SEAFLUX_N:UPDATE_NAM_SEAICEN',0,ZHOOK_HANDLE)
  LDIAG_SEAICE_n = LDIAG_SEAICE
  CSEAICE_SCHEME_n = CSEAICE_SCHEME
  CINTERPOL_SIC_n = CINTERPOL_SIC
  CINTERPOL_SIT_n = CINTERPOL_SIT
  XSIC_EFOLDING_TIME_n = XSIC_EFOLDING_TIME
  XSIT_EFOLDING_TIME_n = XSIT_EFOLDING_TIME
  XSEAICE_TSTEP_n = XSEAICE_TSTEP
  XFREEZING_SST_n = XFREEZING_SST
  XCD_ICE_CST_n = XCD_ICE_CST
  XSI_FLX_DRV_n = XSI_FLX_DRV
IF (LHOOK) CALL DR_HOOK('MODN_SEAFLUX_N:UPDATE_NAM_SEAICEN',1,ZHOOK_HANDLE)
END SUBROUTINE UPDATE_NAM_SEAICEn

END MODULE MODN_SEAFLUX_n
