!     #########
SUBROUTINE PACK_DIAG_PATCH_GET_SIZE_n (DGEI, DIO, DGMI, IO, HSNOW_SCHEME, PKD, KPATCH)
!##############################################
!
!!****  *PACK_DIAG_PATCH_GET_SIZE_n* - packs ISBA diagnostics
!!
!!    PURPOSE
!!    -------
!
!!**  METHOD
!!    ------
!!
!!    REFERENCE
!!    ---------
!!      
!!
!!    AUTHOR
!!    ------
!!     V. Masson 
!!
!!    MODIFICATIONS
!!    -------------
!!      Original    01/2004
!!      Modified    10/2004 by P. Le Moigne: Halstead coefficient
!!      Modified    10/2005 by P. Le Moigne: Allocation (not EBA case)
!!      Modified       2008 by B. Decharme : Allocation for the floodplains
!!      Modified      04-09 by A.L. Gibelin : Add carbon diagnostics
!!      Modified      10-14 by P. Samuelsson: MEB
!!
!!------------------------------------------------------------------
!
!
!
!
USE MODD_DIAG_EVAP_ISBA_n, ONLY : DIAG_EVAP_ISBA_t
USE MODD_DIAG_n, ONLY : DIAG_OPTIONS_t
USE MODD_DIAG_MISC_ISBA_n, ONLY : DIAG_MISC_ISBA_t
USE MODD_ISBA_OPTIONS_n, ONLY : ISBA_OPTIONS_t
USE MODD_PACK_DIAG_ISBA, ONLY : PACK_DIAG_ISBA_t
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE
!
!
TYPE(DIAG_EVAP_ISBA_t), INTENT(INOUT) :: DGEI
TYPE(DIAG_OPTIONS_t), INTENT(INOUT) :: DIO
TYPE(DIAG_MISC_ISBA_t), INTENT(INOUT) :: DGMI
TYPE(ISBA_OPTIONS_t), INTENT(INOUT) :: IO
 CHARACTER(LEN=*), INTENT(IN) :: HSNOW_SCHEME
TYPE(PACK_DIAG_ISBA_t), INTENT(INOUT) :: PKD
!
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
INTEGER, INTENT(IN)               :: KPATCH
!------------------------------------------------------------------------
IF (LHOOK) CALL DR_HOOK('PACK_DIAG_PATCH_GET_SIZE_N',0,ZHOOK_HANDLE)
!
PKD%NSIZE_SIMPLE=59
PKD%NSIZE_GROUND=0
PKD%NSIZE_SNOW=0
PKD%NSIZE_KSW=2
PKD%NSIZE_ABC=0
PKD%NSIZE_0=0
PKD%NSIZE_00=0
!
IF (HSNOW_SCHEME=='3-L' .OR. HSNOW_SCHEME=='CRO') THEN
  PKD%NSIZE_SIMPLE=PKD%NSIZE_SIMPLE+25
  PKD%NSIZE_SNOW=PKD%NSIZE_SNOW+2
ELSE
  PKD%NSIZE_0=PKD%NSIZE_0+25
  PKD%NSIZE_00=PKD%NSIZE_00+2 
ENDIF
!
IF(HSNOW_SCHEME/='EBA') THEN
  PKD%NSIZE_SNOW=PKD%NSIZE_SNOW+1 
ELSE
  PKD%NSIZE_00=PKD%NSIZE_00+1 
ENDIF
!
IF(HSNOW_SCHEME=='EBA') THEN
  PKD%NSIZE_SIMPLE=PKD%NSIZE_SIMPLE+2 
ELSE
  PKD%NSIZE_0=PKD%NSIZE_0+2 
ENDIF
!
IF (IO%LTR_ML) THEN
  PKD%NSIZE_SIMPLE=PKD%NSIZE_SIMPLE+4
ELSE
  PKD%NSIZE_0=PKD%NSIZE_0+4
ENDIF
!
IF (IO%CPHOTO/='NON') THEN
  PKD%NSIZE_ABC=PKD%NSIZE_ABC+1 
ELSE
  PKD%NSIZE_00=PKD%NSIZE_00+1
ENDIF
!
IF (DIO%N2M>=1) THEN
  PKD%NSIZE_SIMPLE=PKD%NSIZE_SIMPLE+5 
ELSE
  PKD%NSIZE_0=PKD%NSIZE_0+5 
ENDIF
!
IF (DGMI%LSURF_MISC_BUDGET) THEN
  PKD%NSIZE_GROUND=PKD%NSIZE_GROUND+2 
  PKD%NSIZE_SIMPLE=PKD%NSIZE_SIMPLE+2 
ELSE
  PKD%NSIZE_00=PKD%NSIZE_00+2 
  PKD%NSIZE_0=PKD%NSIZE_0+2 
ENDIF
!
IF(IO%LGLACIER)THEN
  PKD%NSIZE_SIMPLE=PKD%NSIZE_SIMPLE+1 
ELSE
  PKD%NSIZE_0=PKD%NSIZE_0+1 
ENDIF
!
! MEB STUFF START
IF (IO%LMEB_PATCH(KPATCH))THEN
!  NSIZE_SIMPLE=NSIZE_SIMPLE+27
  PKD%NSIZE_SIMPLE=PKD%NSIZE_SIMPLE+29
ELSE
!  NSIZE_0=NSIZE_0+27
  PKD%NSIZE_0=PKD%NSIZE_0+29
ENDIF
PKD%NSIZE_0=PKD%NSIZE_0+2
! MEB STUFF END
!
IF(DGEI%LWATER_BUDGET)THEN
  PKD%NSIZE_SIMPLE=PKD%NSIZE_SIMPLE+5 
ELSE
  PKD%NSIZE_0=PKD%NSIZE_0+5 
ENDIF
!
IF (LHOOK) CALL DR_HOOK('PACK_DIAG_PATCH_GET_SIZE_N',1,ZHOOK_HANDLE)
!------------------------------------------------------------------------
!
END SUBROUTINE PACK_DIAG_PATCH_GET_SIZE_n
