!     #########
SUBROUTINE PACK_ISBA_PATCH_GET_SIZE_n (I, PK, &
                                       KPATCH)
!##############################################
!
!
!!****  *PACK_ISBA_PATCH_GET_SIZE_n * - packs ISBA variables
!!
!!    PURPOSE
!!    -------
!
!!**  METHOD
!!    ------
!!
!!    REFERENCE
!!    ---------
!!      
!!
!!    AUTHOR
!!    ------
!!     V. Masson and A. boone
!!
!!    MODIFICATIONS
!!    -------------
!!      Original    01/2004
!!      B. Decharme    2008 floodplains
!!      B. Decharme 01/2009 Good dim for XP_TG
!!      A.L. Gibelin 04/2009 : BIOMASS and RESP_BIOMASS arrays 
!!      A.L. Gibelin 04/2009 : TAU_WOOD for NCB option 
!!      A.L. Gibelin 05/2009 : Add carbon spinup
!!      A.L. Gibelin 06/2009 : Soil carbon variables for CNT option
!!      A.L. Gibelin 07/2009 : Suppress RDK and transform GPP as a diagnostic
!!      A.L. Gibelin 07/2009 : Suppress PPST and PPSTF as outputs
!!      B. Decharme  04/2013 : DIF lateral subsurface drainage
!!                             water table / surface coupling
!!      P Samuelsson 10/2014 : MEB
!!
!!------------------------------------------------------------------
!
!
USE MODD_ISBA_n, ONLY : ISBA_t
USE MODD_PACK_ISBA, ONLY : PACK_ISBA_t
!
USE MODD_DATA_COVER_PAR,  ONLY : NVEGTYPE
!
USE MODD_AGRI,        ONLY : LAGRIP
USE MODD_TREEDRAG,    ONLY : LTREEDRAG
!
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE
!
!
TYPE(ISBA_t), INTENT(INOUT) :: I
TYPE(PACK_ISBA_t), INTENT(INOUT) :: PK
!
INTEGER, INTENT(IN)               :: KPATCH
!
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!------------------------------------------------------------------------
IF (LHOOK) CALL DR_HOOK('PACK_ISBA_PATCH_GET_SIZE_N',0,ZHOOK_HANDLE)
!
PK%NSIZE_LSIMPLE=0
PK%NSIZE_L0=0
!
PK%NSIZE_NSIMPLE=0
PK%NSIZE_N0=0
!
PK%NSIZE_TSIMPLE=0
PK%NSIZE_T0=0
!
PK%NSIZE_SIMPLE=67
PK%NSIZE_GROUND=11
PK%NSIZE_VEGTYPE=1
PK%NSIZE_TG=1
PK%NSIZE_SNOW=2
PK%NSIZE_ALB=2
PK%NSIZE_2=0
PK%NSIZE_BIOMASS=0
PK%NSIZE_LITTER=0
PK%NSIZE_SOILCARB=0
PK%NSIZE_LITTLEVS=0
!
PK%NSIZE_0=0
PK%NSIZE_00=0
PK%NSIZE_000=0
PK%NSIZE_01=0
!
IF (I%R%TSNOW%SCHEME=='EBA') THEN
  PK%NSIZE_SIMPLE=PK%NSIZE_SIMPLE+1
ELSE 
  PK%NSIZE_0=PK%NSIZE_0+1
ENDIF
!
IF (I%R%TSNOW%SCHEME=='3-L' .OR. I%R%TSNOW%SCHEME=='CRO') THEN
  PK%NSIZE_SIMPLE=PK%NSIZE_SIMPLE+4
  PK%NSIZE_SNOW=PK%NSIZE_SNOW+2
ELSE
  PK%NSIZE_0=PK%NSIZE_0+4
  PK%NSIZE_00=PK%NSIZE_00+2
ENDIF
!
IF(I%R%TSNOW%SCHEME=='CRO') THEN
  PK%NSIZE_SNOW=PK%NSIZE_SNOW+3
ELSE
  PK%NSIZE_00=PK%NSIZE_00+3
ENDIF
!
IF(I%O%LGLACIER) THEN
  PK%NSIZE_SIMPLE=PK%NSIZE_SIMPLE+1
ELSE
  PK%NSIZE_0=PK%NSIZE_0+1
ENDIF
!
IF (I%O%CSCOND=='PL98'.OR.I%O%CISBA=='DIF') THEN
  PK%NSIZE_GROUND=PK%NSIZE_GROUND+3
ELSE
  PK%NSIZE_01=PK%NSIZE_01+3
ENDIF
!
IF (I%O%CISBA=='2-L' .OR. I%O%CISBA=='3-L') THEN
  PK%NSIZE_SIMPLE=PK%NSIZE_SIMPLE+7
  PK%NSIZE_2=PK%NSIZE_2+1
ELSE
  PK%NSIZE_0=PK%NSIZE_0+7
  PK%NSIZE_00=PK%NSIZE_00+1
ENDIF
!
IF (I%O%CISBA=='DIF') THEN
  PK%NSIZE_GROUND=PK%NSIZE_GROUND+4
  PK%NSIZE_NSIMPLE=PK%NSIZE_NSIMPLE+1
  PK%NSIZE_SIMPLE=PK%NSIZE_SIMPLE+2
ELSE
  PK%NSIZE_01=PK%NSIZE_01+4
  PK%NSIZE_N0=PK%NSIZE_N0+1
  PK%NSIZE_0=PK%NSIZE_0+2
ENDIF
!
IF (I%O%CISBA=='DIF'.AND.I%O%CRUNOFF=='SGH') THEN
  PK%NSIZE_GROUND=PK%NSIZE_GROUND+1
ELSE
  PK%NSIZE_01=PK%NSIZE_01+1
ENDIF
!
IF (I%O%LTR_ML) THEN
  PK%NSIZE_SIMPLE = PK%NSIZE_SIMPLE+4
ELSE
  PK%NSIZE_0 = PK%NSIZE_0+4
ENDIF
!
IF (I%O%CPHOTO=='NON') THEN
  PK%NSIZE_SIMPLE=PK%NSIZE_SIMPLE+1
ELSE
  PK%NSIZE_0 = PK%NSIZE_0+1
ENDIF
!
IF (I%O%CPHOTO/='NON'.OR.LTREEDRAG) THEN
  PK%NSIZE_SIMPLE=PK%NSIZE_SIMPLE+1        
ELSE
  PK%NSIZE_0 = PK%NSIZE_0+1        
ENDIF
!
IF (I%O%CPHOTO/='NON') THEN
  PK%NSIZE_SIMPLE=PK%NSIZE_SIMPLE+22
  PK%NSIZE_BIOMASS=PK%NSIZE_BIOMASS+2
ELSE
  PK%NSIZE_0=PK%NSIZE_0+22
  PK%NSIZE_00=PK%NSIZE_00+2
ENDIF
!
IF (I%O%CPHOTO=='AST' .OR. I%O%CPHOTO=='LST' .OR. I%O%CPHOTO=='NIT' .OR. I%O%CPHOTO=='NCB') THEN
  PK%NSIZE_LSIMPLE=PK%NSIZE_LSIMPLE+1
  PK%NSIZE_SIMPLE=PK%NSIZE_SIMPLE+4
ELSE
  PK%NSIZE_L0=PK%NSIZE_L0+1
  PK%NSIZE_0=PK%NSIZE_0+4
ENDIF
!
IF (LAGRIP .AND. (I%O%CPHOTO=='LAI' .OR. I%O%CPHOTO=='LST' .OR. I%O%CPHOTO=='NIT' .OR. I%O%CPHOTO=='NCB')) THEN
  PK%NSIZE_SIMPLE=PK%NSIZE_SIMPLE+3
  PK%NSIZE_TSIMPLE=PK%NSIZE_TSIMPLE+2
  PK%NSIZE_LSIMPLE=PK%NSIZE_LSIMPLE+2
ELSE
  PK%NSIZE_L0=PK%NSIZE_L0+2
  PK%NSIZE_0=PK%NSIZE_0+3
  PK%NSIZE_T0=PK%NSIZE_T0+2
ENDIF
!
IF(I%O%CPHOTO=='NIT' .OR. I%O%CPHOTO=='NCB') THEN
  PK%NSIZE_SIMPLE=PK%NSIZE_SIMPLE+4
ELSE
  PK%NSIZE_0=PK%NSIZE_0+4
ENDIF
!
IF (I%O%CPHOTO=='NCB') THEN
  PK%NSIZE_BIOMASS=PK%NSIZE_BIOMASS+1
  PK%NSIZE_SIMPLE=PK%NSIZE_SIMPLE+1
ELSE
  PK%NSIZE_00=PK%NSIZE_00+1
  PK%NSIZE_0=PK%NSIZE_0+1
ENDIF
!
IF (I%O%CRESPSL=='CNT') THEN
  PK%NSIZE_LITTER=PK%NSIZE_LITTER+1
  PK%NSIZE_SOILCARB=PK%NSIZE_SOILCARB+1
  PK%NSIZE_LITTLEVS=PK%NSIZE_LITTLEVS+1
  PK%NSIZE_BIOMASS=PK%NSIZE_BIOMASS+1
ELSE
  PK%NSIZE_000=PK%NSIZE_000+1
  PK%NSIZE_00=PK%NSIZE_00+3
ENDIF
!
IF (I%O%CRAIN=='SGH') THEN
  PK%NSIZE_SIMPLE=PK%NSIZE_SIMPLE+1
ELSE
  PK%NSIZE_0=PK%NSIZE_0+1
ENDIF
! MEB STUFF START
IF (I%O%LMEB_PATCH(KPATCH))THEN
  PK%NSIZE_SIMPLE=PK%NSIZE_SIMPLE+12
!  NSIZE_GROUND=NSIZE_GROUND+1
ELSE
  PK%NSIZE_0=PK%NSIZE_0+12
!  NSIZE_01=NSIZE_01+1
ENDIF
! Old MEB varibales now eliminated
PK%NSIZE_0=PK%NSIZE_0+7
PK%NSIZE_01=PK%NSIZE_01+1
! MEB STUFF END
!
IF (LHOOK) CALL DR_HOOK('PACK_ISBA_PATCH_GET_SIZE_N',1,ZHOOK_HANDLE)
!------------------------------------------------------------------------
END SUBROUTINE PACK_ISBA_PATCH_GET_SIZE_n
