!     #########
SUBROUTINE PACK_ISBA_PATCH_n (AG, IG, ISS, IO, P, IP, INI, IPM, IR, PK, KMASK, KSIZE, KPATCH)
!##############################################
!
!
!!****  *PACK_ISBA_PATCH_n * - packs ISBA variables
!!
!!    PURPOSE
!!    -------
!
!!**  METHOD
!!    ------
!!
!!    REFERENCE
!!    ---------
!!      
!!
!!    AUTHOR
!!    ------
!!     V. Masson and A. boone
!!
!!    MODIFICATIONS
!!    -------------
!!      Original    01/2004
!!      B. Decharme    2008 floodplains
!!      B. Decharme 01/2009 Good dim for XP_TG
!!      A.L. Gibelin 04/2009 : BIOMASS and RESP_BIOMASS arrays 
!!      A.L. Gibelin 04/2009 : TAU_WOOD for NCB option 
!!      A.L. Gibelin 05/2009 : Add carbon spinup
!!      A.L. Gibelin 06/2009 : Soil carbon variables for CNT option
!!      A.L. Gibelin 07/2009 : Suppress RDK and transform GPP as a diagnostic
!!      A.L. Gibelin 07/2009 : Suppress PPST and PPSTF as outputs
!!      B. Decharme  04/2013 : DIF lateral subsurface drainage
!!                             water table / surface coupling
!!      P Samuelsson 10/2014 : MEB
!!      P Samuelsson 10/2014 : Additional snow albedos
!!
!!------------------------------------------------------------------
!
!
USE MODD_AGRI_n, ONLY : AGRI_t
USE MODD_GRID_n, ONLY : GRID_t
USE MODD_SSO_n, ONLY : SSO_t
!
USE MODD_ISBA_OPTIONS_n, ONLY : ISBA_OPTIONS_t
USE MODD_ISBA_PGD_n, ONLY : ISBA_PGD_t
USE MODD_ISBA_INIT_n, ONLY : ISBA_INIT_PGD_t, ISBA_INIT_t
USE MODD_ISBA_PARAM_n, ONLY : ISBA_PARAM_t
USE MODD_ISBA_n, ONLY : ISBA_PROG_t
!
USE MODD_PACK_ISBA, ONLY : PACK_ISBA_t
!
USE MODD_DATA_COVER_PAR,  ONLY : NVEGTYPE
!
USE MODD_TREEDRAG,    ONLY : LTREEDRAG
USE MODD_AGRI,        ONLY : LAGRIP
                             

!
USE MODD_CSTS,       ONLY : XLVTT, XLSTT, XCPD
!
USE MODI_ABOR1_SFX
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE
!
!
TYPE(AGRI_t), INTENT(INOUT) :: AG
TYPE(GRID_t), INTENT(INOUT) :: IG
TYPE(SSO_t), INTENT(INOUT) :: ISS
TYPE(ISBA_OPTIONS_t), INTENT(INOUT) :: IO
TYPE (ISBA_PGD_t), INTENT(INOUT) :: P
TYPE(ISBA_INIT_PGD_t), INTENT(INOUT) :: IP
TYPE(ISBA_INIT_t), INTENT(INOUT) :: INI
TYPE(ISBA_PARAM_t), INTENT(INOUT) :: IPM
TYPE(ISBA_PROG_t), INTENT(INOUT) :: IR
TYPE(PACK_ISBA_t), INTENT(INOUT) :: PK
!
INTEGER, INTENT(IN)               :: KSIZE, KPATCH
INTEGER, DIMENSION(:), INTENT(IN) :: KMASK
!
INTEGER :: ISLP, ISL0, ISTP, IST0, ISP, ISG, ISV, IST, ISW, ISA,    &
           IS2, ISB, ISC, ISLTV, ISLT, IS0, IS00,IS000, IS01,     &
           ISNP, ISN0
!
INTEGER :: JK, JL 
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
!------------------------------------------------------------------------
IF (LHOOK) CALL DR_HOOK('PACK_ISBA_PATCH_N',0,ZHOOK_HANDLE)
!
ALLOCATE(PK%LBLOCK_SIMPLE(KSIZE,PK%NSIZE_LSIMPLE))
ALLOCATE(PK%LBLOCK_0(0,PK%NSIZE_L0))
ALLOCATE(PK%NBLOCK_SIMPLE(KSIZE,PK%NSIZE_NSIMPLE))
ALLOCATE(PK%NBLOCK_0(0,PK%NSIZE_N0))
ALLOCATE(PK%TBLOCK_SIMPLE(KSIZE,PK%NSIZE_TSIMPLE))
ALLOCATE(PK%TBLOCK_0(0,PK%NSIZE_T0))
ALLOCATE(PK%XBLOCK_SIMPLE(KSIZE,PK%NSIZE_SIMPLE))
ALLOCATE(PK%XBLOCK_GROUND(KSIZE,IO%NGROUND_LAYER,PK%NSIZE_GROUND))
ALLOCATE(PK%XBLOCK_VEGTYPE(KSIZE,NVEGTYPE,PK%NSIZE_VEGTYPE))
ALLOCATE(PK%XBLOCK_TG(KSIZE,SIZE(IR%XTG,2),PK%NSIZE_TG))
ALLOCATE(PK%XBLOCK_SNOW(KSIZE,IR%TSNOW%NLAYER,PK%NSIZE_SNOW))
ALLOCATE(PK%XBLOCK_ALB(KSIZE,SIZE(INI%XDIR_ALB_WITH_SNOW,2),PK%NSIZE_ALB))
ALLOCATE(PK%XBLOCK_2(KSIZE,2,PK%NSIZE_2))
ALLOCATE(PK%XBLOCK_BIOMASS(KSIZE,IO%NNBIOMASS,PK%NSIZE_BIOMASS))
ALLOCATE(PK%XBLOCK_SOILCARB(KSIZE,IO%NNSOILCARB,PK%NSIZE_SOILCARB))
ALLOCATE(PK%XBLOCK_LITTLEVS(KSIZE,IO%NNLITTLEVS,PK%NSIZE_LITTLEVS))
ALLOCATE(PK%XBLOCK_LITTER(KSIZE,IO%NNLITTER,IO%NNLITTLEVS,PK%NSIZE_LITTER))
ALLOCATE(PK%XBLOCK_0(0,PK%NSIZE_0))
ALLOCATE(PK%XBLOCK_00(0,0,PK%NSIZE_00))
ALLOCATE(PK%XBLOCK_000(0,0,0,PK%NSIZE_000))
ALLOCATE(PK%XBLOCK_01(0,1,PK%NSIZE_01))
!
ISLP=0
ISL0=0
ISNP=0
ISN0=0
ISTP=0
IST0=0
ISP=0
ISG=0
ISV=0
IST=0
ISW=0
ISA=0
IS2=0
ISB=0
ISLT=0
ISC=0
ISLTV=0
IS0=0
IS00=0
IS000=0
IS01=0
!
!IMX
!
ISG = ISG + 1
PK%I%M%X%XDG        => PK%XBLOCK_GROUND(:,:,ISG:ISG)
IF (IO%CISBA=='DIF') THEN
  ISG = ISG + 1
   PK%I%M%X%XROOTFRAC   => PK%XBLOCK_GROUND(:,:,ISG:ISG) 
  ISNP = ISNP + 1
   PK%I%M%X%NWG_LAYER   => PK%NBLOCK_SIMPLE(:,ISNP:ISNP)
ELSE
  IS01 = IS01 + 1
  PK%I%M%X%XROOTFRAC   => PK%XBLOCK_01(:,:,IS01:IS01) 
  ISN0 = ISN0 + 1
   PK%I%M%X%NWG_LAYER   => PK%NBLOCK_0(:,ISN0:ISN0)
END IF
!
ISP = ISP + 1
PK%I%M%X%XD_ICE     => PK%XBLOCK_SIMPLE(:,ISP:ISP)
IF (IO%CPHOTO/='NON'.OR.LTREEDRAG) THEN
  ISP = ISP + 1
  PK%I%M%X%XH_TREE  => PK%XBLOCK_SIMPLE(:,ISP:ISP)
ELSE
  IS0 = IS0 + 1
  PK%I%M%X%XH_TREE  => PK%XBLOCK_0(:,IS0:IS0)       
ENDIF
!
ISP = ISP + 1
PK%I%M%X%XZ0_O_Z0H  => PK%XBLOCK_SIMPLE(:,ISP:ISP)
IF (IO%CPHOTO/='NON') THEN
  ISP = ISP + 1
   PK%I%M%X%XRE25    => PK%XBLOCK_SIMPLE(:,ISP:ISP)
ELSE
  IS0 = IS0 + 1
  PK%I%M%X%XRE25    => PK%XBLOCK_0(:,IS0:IS0)
END IF
!
IF (IO%CPHOTO=='AST' .OR. IO%CPHOTO=='LST' .OR. IO%CPHOTO=='NIT' .OR. IO%CPHOTO=='NCB') THEN
  ISP = ISP + 1
   PK%I%M%X%XDMAX    => PK%XBLOCK_SIMPLE(:,ISP:ISP)
ELSE
  IS0 = IS0 + 1
  PK%I%M%X%XDMAX    => PK%XBLOCK_0(:,IS0:IS0)
END IF

!
! IMT
!
ISP = ISP + 1
PK%I%M%T%XVEG       => PK%XBLOCK_SIMPLE(:,ISP:ISP) 
ISP = ISP + 1
PK%I%M%T%XLAI       => PK%XBLOCK_SIMPLE(:,ISP:ISP) 
ISP = ISP + 1
PK%I%M%T%XEMIS      => PK%XBLOCK_SIMPLE(:,ISP:ISP)
ISP = ISP + 1
PK%I%M%T%XZ0        => PK%XBLOCK_SIMPLE(:,ISP:ISP) 
!
IF (IO%CPHOTO=='NON') THEN
  ISP = ISP + 1
   PK%I%M%T%XRSMIN   => PK%XBLOCK_SIMPLE(:,ISP:ISP)
ELSE
  IS0 = IS0 + 1
  PK%I%M%T%XRSMIN   => PK%XBLOCK_0(:,IS0:IS0)
END IF
!
ISP = ISP + 1
PK%I%M%T%XGAMMA     => PK%XBLOCK_SIMPLE(:,ISP:ISP)
ISP = ISP + 1
PK%I%M%T%XWRMAX_CF  => PK%XBLOCK_SIMPLE(:,ISP:ISP)
ISP = ISP + 1
PK%I%M%T%XRGL       => PK%XBLOCK_SIMPLE(:,ISP:ISP)
ISP = ISP + 1
PK%I%M%T%XCV        => PK%XBLOCK_SIMPLE(:,ISP:ISP)
!
IF (IO%CPHOTO/='NON') THEN
  ISP = ISP + 1
   PK%I%M%T%XLAIMIN  => PK%XBLOCK_SIMPLE(:,ISP:ISP)
  ISP = ISP + 1
   PK%I%M%T%XSEFOLD  => PK%XBLOCK_SIMPLE(:,ISP:ISP)
  ISP = ISP + 1
   PK%I%M%T%XGMES    => PK%XBLOCK_SIMPLE(:,ISP:ISP)
  ISP = ISP + 1
   PK%I%M%T%XGC      => PK%XBLOCK_SIMPLE(:,ISP:ISP)
ELSE
  IS0 = IS0 + 1
  PK%I%M%T%XLAIMIN  => PK%XBLOCK_0(:,IS0:IS0)
  IS0 = IS0 + 1
  PK%I%M%T%XSEFOLD  => PK%XBLOCK_0(:,IS0:IS0)
  IS0 = IS0 + 1
  PK%I%M%T%XGMES    => PK%XBLOCK_0(:,IS0:IS0)  
  IS0 = IS0 + 1
  PK%I%M%T%XGC      => PK%XBLOCK_0(:,IS0:IS0)
END IF
!
IF (IO%CPHOTO=='AST' .OR. IO%CPHOTO=='LST' .OR. IO%CPHOTO=='NIT' .OR. IO%CPHOTO=='NCB') THEN
  ISLP = ISLP + 1
  PK%I%M%T%LSTRESS  => PK%LBLOCK_SIMPLE(:,ISLP:ISLP)
  ISP = ISP + 1
   PK%I%M%T%XF2I     => PK%XBLOCK_SIMPLE(:,ISP:ISP)
ELSE
  ISL0 = ISL0 + 1
  PK%I%M%T%LSTRESS  => PK%LBLOCK_0(:,ISL0:ISL0)
  IS0 = IS0 + 1
  PK%I%M%T%XF2I     => PK%XBLOCK_0(:,IS0:IS0)
END IF
!
IF (IO%CPHOTO/='NON' .OR. IO%LMEB_PATCH(KPATCH)) THEN
  ISP = ISP + 1
   PK%I%M%T%XBSLAI   => PK%XBLOCK_SIMPLE(:,ISP:ISP)
ELSE
  IS0 = IS0 + 1
  PK%I%M%T%XBSLAI   => PK%XBLOCK_0(:,IS0:IS0)
ENDIF
!
IF(IO%CPHOTO=='NIT' .OR. IO%CPHOTO=='NCB') THEN
  ISP = ISP + 1
   PK%I%M%T%XCE_NITRO    => PK%XBLOCK_SIMPLE(:,ISP:ISP)
  ISP = ISP + 1
   PK%I%M%T%XCF_NITRO    => PK%XBLOCK_SIMPLE(:,ISP:ISP)
  ISP = ISP + 1
   PK%I%M%T%XCNA_NITRO   => PK%XBLOCK_SIMPLE(:,ISP:ISP)
ELSE
  IS0 = IS0 + 1
  PK%I%M%T%XCE_NITRO    => PK%XBLOCK_0(:,IS0:IS0)
  IS0 = IS0 + 1
  PK%I%M%T%XCF_NITRO    => PK%XBLOCK_0(:,IS0:IS0)
  IS0 = IS0 + 1
  PK%I%M%T%XCNA_NITRO   => PK%XBLOCK_0(:,IS0:IS0)
END IF
!
ISP = ISP + 1
PK%I%M%T%XALBNIR_VEG   => PK%XBLOCK_SIMPLE(:,ISP:ISP)
ISP = ISP + 1
PK%I%M%T%XALBVIS_VEG   => PK%XBLOCK_SIMPLE(:,ISP:ISP)
ISP = ISP + 1
PK%I%M%T%XALBUV_VEG => PK%XBLOCK_SIMPLE(:,ISP:ISP)
!
ISP = ISP + 1
PK%I%M%T%XALBNIR    => PK%XBLOCK_SIMPLE(:,ISP:ISP)
ISP = ISP + 1
PK%I%M%T%XALBVIS    => PK%XBLOCK_SIMPLE(:,ISP:ISP)
ISP = ISP + 1
PK%I%M%T%XALBUV     => PK%XBLOCK_SIMPLE(:,ISP:ISP)
!
!IMA
!
ISP = ISP + 1
PK%I%M%A%XALBNIR_SOIL  => PK%XBLOCK_SIMPLE(:,ISP:ISP)
ISP = ISP + 1
PK%I%M%A%XALBVIS_SOIL  => PK%XBLOCK_SIMPLE(:,ISP:ISP)
ISP = ISP + 1
PK%I%M%A%XALBUV_SOIL   => PK%XBLOCK_SIMPLE(:,ISP:ISP)
!
! IMM
!
IF (IO%LMEB_PATCH(KPATCH))THEN
  ISP = ISP + 1
  PK%I%M%M%XH_VEG    => PK%XBLOCK_SIMPLE(:,ISP:ISP)
  ISP = ISP + 1
  PK%I%M%M%XGNDLITTER   => PK%XBLOCK_SIMPLE(:,ISP:ISP)
  ISP = ISP + 1
  PK%I%M%M%XZ0LITTER => PK%XBLOCK_SIMPLE(:,ISP:ISP)
ELSE
  IS0 = IS0 + 1
  PK%I%M%M%XH_VEG    => PK%XBLOCK_0(:,IS0:IS0)
  IS0 = IS0 + 1
  PK%I%M%M%XGNDLITTER   => PK%XBLOCK_0(:,IS0:IS0)
  IS0 = IS0 + 1
  PK%I%M%M%XZ0LITTER => PK%XBLOCK_0(:,IS0:IS0)
ENDIF
!
IS0 = IS0 + 1
PK%I%M%M%XLAIGV     => PK%XBLOCK_0(:,IS0:IS0)
IS0 = IS0 + 1
PK%I%M%M%XRSMINGV   => PK%XBLOCK_0(:,IS0:IS0)
IS0 = IS0 + 1
PK%I%M%M%XGAMMAGV   => PK%XBLOCK_0(:,IS0:IS0)
IS0 = IS0 + 1
PK%I%M%M%XWRMAX_CFGV   => PK%XBLOCK_0(:,IS0:IS0)
IS0 = IS0 + 1
PK%I%M%M%XRGLGV     => PK%XBLOCK_0(:,IS0:IS0)
IS0 = IS0 + 1
PK%I%M%M%XZ0GV      => PK%XBLOCK_0(:,IS0:IS0)
IS01 = IS01 + 1
PK%I%M%M%XROOTFRACGV   => PK%XBLOCK_01(:,:,IS01:IS01)
!
! IP
!
!xpatch
ISV = ISV + 1
PK%I%IP%XVEGTYPE_PATCH => PK%XBLOCK_VEGTYPE(:,:,ISV:ISV)
!
!nsize_nature_p
!nr_nature_p
!xpatch_old
ISP = ISP + 1
PK%I%IP%XTDEEP     => PK%XBLOCK_SIMPLE(:,ISP)
ISP = ISP + 1
PK%I%IP%XGAMMAT    => PK%XBLOCK_SIMPLE(:,ISP)
!
!xabc 
!xpoi
IF (IO%CPHOTO/='NON') THEN
  ISP = ISP + 1
   PK%I%IP%XANMAX   => PK%XBLOCK_SIMPLE(:,ISP:ISP)
  ISP = ISP + 1
   PK%I%IP%XFZERO   => PK%XBLOCK_SIMPLE(:,ISP:ISP)
  ISP = ISP + 1
   PK%I%IP%XEPSO    => PK%XBLOCK_SIMPLE(:,ISP:ISP)
  ISP = ISP + 1
   PK%I%IP%XGAMM    => PK%XBLOCK_SIMPLE(:,ISP:ISP)
  ISP = ISP + 1
   PK%I%IP%XQDGAMM  => PK%XBLOCK_SIMPLE(:,ISP:ISP)
  ISP = ISP + 1
   PK%I%IP%XQDGMES  => PK%XBLOCK_SIMPLE(:,ISP:ISP)   
  ISP = ISP + 1
   PK%I%IP%XT1GMES  => PK%XBLOCK_SIMPLE(:,ISP:ISP)
  ISP = ISP + 1
   PK%I%IP%XT2GMES  => PK%XBLOCK_SIMPLE(:,ISP:ISP)   
  ISP = ISP + 1
   PK%I%IP%XAMAX    => PK%XBLOCK_SIMPLE(:,ISP:ISP)
  ISP = ISP + 1
   PK%I%IP%XQDAMAX  => PK%XBLOCK_SIMPLE(:,ISP:ISP)
  ISP = ISP + 1
   PK%I%IP%XT1AMAX  => PK%XBLOCK_SIMPLE(:,ISP:ISP)
  ISP = ISP + 1
   PK%I%IP%XT2AMAX  => PK%XBLOCK_SIMPLE(:,ISP:ISP)
ELSE
  IS0 = IS0 + 1
  PK%I%IP%XANMAX   => PK%XBLOCK_0(:,IS0:IS0)
  IS0 = IS0 + 1
  PK%I%IP%XFZERO   => PK%XBLOCK_0(:,IS0:IS0)
  IS0 = IS0 + 1
  PK%I%IP%XEPSO    => PK%XBLOCK_0(:,IS0:IS0)
  IS0 = IS0 + 1
  PK%I%IP%XGAMM    => PK%XBLOCK_0(:,IS0:IS0)
  IS0 = IS0 + 1
  PK%I%IP%XQDGAMM  => PK%XBLOCK_0(:,IS0:IS0)
  IS0 = IS0 + 1
  PK%I%IP%XQDGMES  => PK%XBLOCK_0(:,IS0:IS0)
  IS0 = IS0 + 1
  PK%I%IP%XT1GMES  => PK%XBLOCK_0(:,IS0:IS0)
  IS0 = IS0 + 1
  PK%I%IP%XT2GMES  => PK%XBLOCK_0(:,IS0:IS0)
  IS0 = IS0 + 1
  PK%I%IP%XAMAX    => PK%XBLOCK_0(:,IS0:IS0)
  IS0 = IS0 + 1
  PK%I%IP%XQDAMAX  => PK%XBLOCK_0(:,IS0:IS0)
  IS0 = IS0 + 1
  PK%I%IP%XT1AMAX  => PK%XBLOCK_0(:,IS0:IS0)
  IS0 = IS0 + 1
  PK%I%IP%XT2AMAX  => PK%XBLOCK_0(:,IS0:IS0)
END IF
!
IF (IO%CPHOTO=='AST' .OR. IO%CPHOTO=='LST' .OR. IO%CPHOTO=='NIT' .OR. IO%CPHOTO=='NCB') THEN
  ISP = ISP + 1
   PK%I%IP%XAH      => PK%XBLOCK_SIMPLE(:,ISP:ISP)
  ISP = ISP + 1
   PK%I%IP%XBH      => PK%XBLOCK_SIMPLE(:,ISP:ISP)
ELSE
  IS0 = IS0 + 1
  PK%I%IP%XAH      => PK%XBLOCK_0(:,IS0:IS0)
  IS0 = IS0 + 1
  PK%I%IP%XBH      => PK%XBLOCK_0(:,IS0:IS0)
END IF
!
IF (IO%CPHOTO=='NCB') THEN
  ISB = ISB + 1
  PK%I%IP%XINCREASE  => PK%XBLOCK_BIOMASS(:,:,ISB:ISB)
  ISP = ISP + 1
   PK%I%IP%XTAU_WOOD  => PK%XBLOCK_SIMPLE(:,ISP:ISP)  
ELSE
  IS00 = IS00 + 1
  PK%I%IP%XINCREASE  => PK%XBLOCK_00(:,:,IS00:IS00)
  IS0 = IS0 + 1
  PK%I%IP%XTAU_WOOD  => PK%XBLOCK_0(:,IS0:IS0)
ENDIF
!
IF (IO%CRESPSL=='CNT') THEN
  ISB = ISB + 1
  PK%I%IP%XTURNOVER    => PK%XBLOCK_BIOMASS(:,:,ISB:ISB)
ELSE
  IS00 = IS00 + 1
  PK%I%IP%XTURNOVER    => PK%XBLOCK_00(:,:,IS00:IS00)
END IF
!
ISG = ISG + 1
PK%I%IP%XCONDSAT   => PK%XBLOCK_GROUND(:,:,ISG:ISG)
ISG = ISG + 1
PK%I%IP%XMPOTSAT => PK%XBLOCK_GROUND(:,:,ISG)
ISG = ISG + 1
PK%I%IP%XBCOEF   => PK%XBLOCK_GROUND(:,:,ISG)
ISG = ISG + 1
PK%I%IP%XWWILT     => PK%XBLOCK_GROUND(:,:,ISG)
ISG = ISG + 1
PK%I%IP%XWFC       => PK%XBLOCK_GROUND(:,:,ISG)
ISG = ISG + 1
PK%I%IP%XWSAT      => PK%XBLOCK_GROUND(:,:,ISG)
ISP = ISP + 1
PK%I%IP%XTAUICE    => PK%XBLOCK_SIMPLE(:,ISP)
!
IF (IO%CISBA=='2-L' .OR. IO%CISBA=='3-L') THEN   
  ISP = ISP + 1
  PK%I%IP%XCGSAT     => PK%XBLOCK_SIMPLE(:,ISP) 
  ISP = ISP + 1
  PK%I%IP%XC1SAT     => PK%XBLOCK_SIMPLE(:,ISP:ISP) 
  ISP = ISP + 1
  PK%I%IP%XC2REF     => PK%XBLOCK_SIMPLE(:,ISP:ISP) 
  IS2 = IS2 + 1
  PK%I%IP%XC3        => PK%XBLOCK_2(:,:,IS2:IS2)
  ISP = ISP + 1
   PK%I%IP%XC4B   => PK%XBLOCK_SIMPLE(:,ISP) 
  ISP = ISP + 1
   PK%I%IP%XACOEF => PK%XBLOCK_SIMPLE(:,ISP)
 ISP = ISP + 1
   PK%I%IP%XPCOEF => PK%XBLOCK_SIMPLE(:,ISP)
  ISP = ISP + 1
   PK%I%IP%XC4REF     => PK%XBLOCK_SIMPLE(:,ISP:ISP)   
ELSE
  IS0 = IS0 + 1
  PK%I%IP%XCGSAT     => PK%XBLOCK_0(:,IS0) 
  IS0 = IS0 + 1
  PK%I%IP%XC1SAT     => PK%XBLOCK_0(:,IS0:IS0) 
  IS0 = IS0 + 1
  PK%I%IP%XC2REF     => PK%XBLOCK_0(:,IS0:IS0)   
  IS00 = IS00 + 1
  PK%I%IP%XC3        => PK%XBLOCK_00(:,:,IS00:IS00)
  IS0 = IS0 + 1
  PK%I%IP%XC4B       => PK%XBLOCK_0(:,IS0)
  IS0 = IS0 + 1
  PK%I%IP%XACOEF     => PK%XBLOCK_0(:,IS0) 
  IS0 = IS0 + 1
  PK%I%IP%XPCOEF     => PK%XBLOCK_0(:,IS0)
  IS0 = IS0 + 1
  PK%I%IP%XC4REF     => PK%XBLOCK_0(:,IS0:IS0)  
 
END IF
!
!wd0 
!kaniso
ISP = ISP + 1
PK%I%IP%XPCPS       => PK%XBLOCK_SIMPLE(:,ISP:ISP)
ISP = ISP + 1
PK%I%IP%XPLVTT      => PK%XBLOCK_SIMPLE(:,ISP:ISP)
ISP = ISP + 1
PK%I%IP%XPLSTT      => PK%XBLOCK_SIMPLE(:,ISP:ISP)
!
IF (IO%CSCOND=='PL98'.OR.IO%CISBA=='DIF') THEN
  ISG = ISG + 1
   PK%I%IP%XHCAPSOIL   => PK%XBLOCK_GROUND(:,:,ISG)
  ISG = ISG + 1
   PK%I%IP%XCONDDRY => PK%XBLOCK_GROUND(:,:,ISG)
  ISG = ISG + 1
   PK%I%IP%XCONDSLD => PK%XBLOCK_GROUND(:,:,ISG)   
ELSE
  IS01 = IS01 + 1
  PK%I%IP%XHCAPSOIL   => PK%XBLOCK_01(:,:,IS01)
  IS01 = IS01 + 1
  PK%I%IP%XCONDDRY => PK%XBLOCK_01(:,:,IS01)
  IS01 = IS01 + 1
  PK%I%IP%XCONDSLD => PK%XBLOCK_01(:,:,IS01)
END IF
!
ISP = ISP + 1
PK%I%IP%XRUNOFFD   => PK%XBLOCK_SIMPLE(:,ISP:ISP)
!
IF (IO%CISBA=='DIF') THEN
!
  ISG = ISG + 1
   PK%I%IP%XDZG     => PK%XBLOCK_GROUND(:,:,ISG:ISG)
  ISG = ISG + 1
   PK%I%IP%XDZDIF   => PK%XBLOCK_GROUND(:,:,ISG:ISG) 
  ISG = ISG + 1
   PK%I%IP%XSOILWGHT   => PK%XBLOCK_GROUND(:,:,ISG:ISG)
! 
  ISP = ISP + 1  
   PK%I%IP%XFWTD=> PK%XBLOCK_SIMPLE(:,ISP)
  ISP = ISP + 1  
   PK%I%IP%XWTD=> PK%XBLOCK_SIMPLE(:,ISP)
!
ELSE
!
  IS01 = IS01 + 1
  PK%I%IP%XDZG     => PK%XBLOCK_01(:,:,IS01:IS01)
  IS01 = IS01 + 1
  PK%I%IP%XDZDIF   => PK%XBLOCK_01(:,:,IS01:IS01)
  IS01 = IS01 + 1
  PK%I%IP%XSOILWGHT   => PK%XBLOCK_01(:,:,IS01:IS01)  
!  
  IS0 = IS0 + 1
   PK%I%IP%XFWTD=> PK%XBLOCK_0(:,IS0)
  IS0 = IS0 + 1
   PK%I%IP%XWTD=> PK%XBLOCK_0(:,IS0)
!
END IF
!
ISP = ISP + 1
PK%I%IP%XKSAT_ICE  => PK%XBLOCK_SIMPLE(:,ISP:ISP)
!
ISP = ISP + 1
PK%I%IP%XALBNIR_DRY   => PK%XBLOCK_SIMPLE(:,ISP)
ISP = ISP + 1
PK%I%IP%XALBVIS_DRY   => PK%XBLOCK_SIMPLE(:,ISP)
ISP = ISP + 1
PK%I%IP%XALBUV_DRY => PK%XBLOCK_SIMPLE(:,ISP)
ISP = ISP + 1
PK%I%IP%XALBNIR_WET   => PK%XBLOCK_SIMPLE(:,ISP)
ISP = ISP + 1
PK%I%IP%XALBVIS_WET   => PK%XBLOCK_SIMPLE(:,ISP)
ISP = ISP + 1
PK%I%IP%XALBUV_WET => PK%XBLOCK_SIMPLE(:,ISP)
!
IF(IO%CPHOTO=='NIT' .OR. IO%CPHOTO=='NCB') THEN
  ISP = ISP + 1
   PK%I%IP%XBSLAI_NITRO => PK%XBLOCK_SIMPLE(:,ISP:ISP)
ELSE
  IS0 = IS0 + 1
  PK%I%IP%XBSLAI_NITRO => PK%XBLOCK_0(:,IS0:IS0)
END IF
!
!
! ISS
!
ISP = ISP + 1
PK%ISS%XAOSIP     => PK%XBLOCK_SIMPLE(:,ISP)
ISP = ISP + 1
PK%ISS%XAOSIM     => PK%XBLOCK_SIMPLE(:,ISP)
ISP = ISP + 1
PK%ISS%XAOSJP     => PK%XBLOCK_SIMPLE(:,ISP)
ISP = ISP + 1
PK%ISS%XAOSJM     => PK%XBLOCK_SIMPLE(:,ISP)
ISP = ISP + 1
PK%ISS%XHO2IP     => PK%XBLOCK_SIMPLE(:,ISP)
ISP = ISP + 1
PK%ISS%XHO2IM     => PK%XBLOCK_SIMPLE(:,ISP)
ISP = ISP + 1
PK%ISS%XHO2JP     => PK%XBLOCK_SIMPLE(:,ISP)
ISP = ISP + 1
PK%ISS%XHO2JM     => PK%XBLOCK_SIMPLE(:,ISP)
ISP = ISP + 1
PK%ISS%XZ0EFFIP   => PK%XBLOCK_SIMPLE(:,ISP:ISP)
ISP = ISP + 1
PK%ISS%XZ0EFFIM   => PK%XBLOCK_SIMPLE(:,ISP:ISP)
ISP = ISP + 1
PK%ISS%XZ0EFFJP   => PK%XBLOCK_SIMPLE(:,ISP:ISP)
ISP = ISP + 1
PK%ISS%XZ0EFFJM   => PK%XBLOCK_SIMPLE(:,ISP:ISP)
!xz0effjpdir
ISP = ISP + 1
PK%ISS%XZ0REL     => PK%XBLOCK_SIMPLE(:,ISP)
ISP = ISP + 1
PK%ISS%XSSO_SLOPE => PK%XBLOCK_SIMPLE(:,ISP)
!xsso_anis, xsso_dir, xsso_stdev, xavg_zs, xsil_zs, xmax_zs, xmin_zs
!
! IR
!
ISG = ISG + 1
PK%I%R%XWG        => PK%XBLOCK_GROUND(:,:,ISG:ISG)
ISG = ISG + 1
PK%I%R%XWGI       => PK%XBLOCK_GROUND(:,:,ISG:ISG)
ISP = ISP + 1
PK%I%R%XWR        => PK%XBLOCK_SIMPLE(:,ISP:ISP)
IST = IST + 1
PK%I%R%XTG        => PK%XBLOCK_TG(:,:,IST:IST)
!
ISW = ISW + 1
PK%I%R%TSNOW%WSNOW  => PK%XBLOCK_SNOW(:,:,ISW:ISW)
ISW = ISW + 1
PK%I%R%TSNOW%RHO   => PK%XBLOCK_SNOW(:,:,ISW:ISW)
!
IF (IR%TSNOW%SCHEME=='3-L' .OR. IR%TSNOW%SCHEME=='CRO') THEN
  ISW = ISW + 1
   PK%I%R%TSNOW%HEAT   => PK%XBLOCK_SNOW(:,:,ISW:ISW)
  ISP = ISP + 1
   PK%I%R%TSNOW%EMIS   => PK%XBLOCK_SIMPLE(:,ISP:ISP)
  ISW = ISW + 1
   PK%I%R%TSNOW%AGE => PK%XBLOCK_SNOW(:,:,ISW:ISW)
  ISP = ISP + 1
   PK%I%R%TSNOW%ALBVIS   => PK%XBLOCK_SIMPLE(:,ISP:ISP) 
  ISP = ISP + 1
   PK%I%R%TSNOW%ALBNIR   => PK%XBLOCK_SIMPLE(:,ISP:ISP) 
  ISP = ISP + 1
   PK%I%R%TSNOW%ALBFIR   => PK%XBLOCK_SIMPLE(:,ISP:ISP) 
ELSE
  IS00 = IS00 + 1
  PK%I%R%TSNOW%HEAT   => PK%XBLOCK_00(:,:,IS00:IS00) 
  IS0 = IS0 + 1
  PK%I%R%TSNOW%EMIS   => PK%XBLOCK_0(:,IS0:IS0)
  IS00 = IS00 + 1
  PK%I%R%TSNOW%AGE => PK%XBLOCK_00(:,:,IS00:IS00)
  IS0 = IS0 + 1
  PK%I%R%TSNOW%ALBVIS   => PK%XBLOCK_0(:,IS0:IS0) 
  IS0 = IS0 + 1
  PK%I%R%TSNOW%ALBNIR   => PK%XBLOCK_0(:,IS0:IS0) 
  IS0 = IS0 + 1
  PK%I%R%TSNOW%ALBFIR   => PK%XBLOCK_0(:,IS0:IS0) 
END IF
!
IF(IR%TSNOW%SCHEME=='CRO') THEN
  ISW = ISW + 1
   PK%I%R%TSNOW%GRAN1  => PK%XBLOCK_SNOW(:,:,ISW:ISW)
  ISW = ISW + 1
   PK%I%R%TSNOW%GRAN2  => PK%XBLOCK_SNOW(:,:,ISW:ISW)
  ISW = ISW + 1
   PK%I%R%TSNOW%HIST   => PK%XBLOCK_SNOW(:,:,ISW:ISW)
ELSE      
  IS00 = IS00 + 1
  PK%I%R%TSNOW%GRAN1  => PK%XBLOCK_00(:,:,IS00:IS00)  
  IS00 = IS00 + 1
  PK%I%R%TSNOW%GRAN2  => PK%XBLOCK_00(:,:,IS00:IS00) 
  IS00 = IS00 + 1
  PK%I%R%TSNOW%HIST   => PK%XBLOCK_00(:,:,IS00:IS00) 
END IF
!
ISP = ISP + 1
PK%I%R%TSNOW%ALB   => PK%XBLOCK_SIMPLE(:,ISP:ISP) 
!
IF(IO%LGLACIER)THEN  
  ISP = ISP + 1  
   PK%I%R%XICE_STO  => PK%XBLOCK_SIMPLE(:,ISP:ISP)
ELSE     
  IS0 = IS0 + 1
  PK%I%R%XICE_STO  => PK%XBLOCK_0(:,IS0:IS0)
ENDIF
!
! MEB STUFF START
!
! Note that here the understory ground vegetation (GV) that was part of the original
! MEB development has been eliminated. The reason is to avoid a composite
! of vegetation and soil. Thus, most varibales with old extension V
! (representing canopy vegetation) are now unassociated. Instead, the classical ISBA
! variables (e.g. RGL, GAMMA, ...) will represent a composite vegetation in the
! MEB case. We still keep the GV-variables in the system for future needs.
! Code is commented with "nogv" in appropriate places.
!
IF (IO%LMEB_PATCH(KPATCH))THEN
!
  ISP = ISP + 1
  PK%I%R%XWRL      => PK%XBLOCK_SIMPLE(:,ISP:ISP)
  ISP = ISP + 1
  PK%I%R%XWRLI      => PK%XBLOCK_SIMPLE(:,ISP:ISP)
  ISP = ISP + 1
  PK%I%R%XWRVN     => PK%XBLOCK_SIMPLE(:,ISP:ISP)
  ISP = ISP + 1
  PK%I%R%XTV       => PK%XBLOCK_SIMPLE(:,ISP:ISP)
  ISP = ISP + 1
  PK%I%R%XTL       => PK%XBLOCK_SIMPLE(:,ISP:ISP)
  ISP = ISP + 1
  PK%I%R%XTC       => PK%XBLOCK_SIMPLE(:,ISP:ISP)
  ISP = ISP + 1
  PK%I%R%XQC       => PK%XBLOCK_SIMPLE(:,ISP:ISP)
ELSE
  IS0 = IS0 + 1
  PK%I%R%XWRL      => PK%XBLOCK_0(:,IS0:IS0)
  IS0 = IS0 + 1
  PK%I%R%XWRLI      => PK%XBLOCK_0(:,IS0:IS0)
  IS0 = IS0 + 1
  PK%I%R%XWRVN     => PK%XBLOCK_0(:,IS0:IS0)
  IS0 = IS0 + 1
  PK%I%R%XTV       => PK%XBLOCK_0(:,IS0:IS0)
  IS0 = IS0 + 1
  PK%I%R%XTL       => PK%XBLOCK_0(:,IS0:IS0)
  IS0 = IS0 + 1
  PK%I%R%XTC       => PK%XBLOCK_0(:,IS0:IS0)
  IS0 = IS0 + 1
  PK%I%R%XQC       => PK%XBLOCK_0(:,IS0:IS0)
ENDIF
!
ISP = ISP + 1
PK%I%R%XRESA      => PK%XBLOCK_SIMPLE(:,ISP:ISP) 
!TSRAD_NAT
!
IF (IO%CPHOTO/='NON') THEN
  ISP = ISP + 1
   PK%I%R%XAN      => PK%XBLOCK_SIMPLE(:,ISP:ISP) 
  ISP = ISP + 1
   PK%I%R%XANDAY   => PK%XBLOCK_SIMPLE(:,ISP:ISP) 
  ISP = ISP + 1
   PK%I%R%XANFM    => PK%XBLOCK_SIMPLE(:,ISP:ISP) 
  ISB = ISB + 1
  PK%I%R%XBIOMASS     => PK%XBLOCK_BIOMASS(:,:,ISB:ISB)
  ISB = ISB + 1 
  PK%I%R%XRESP_BIOMASS   => PK%XBLOCK_BIOMASS(:,:,ISB:ISB)
ELSE
  IS0 = IS0 + 1
  PK%I%R%XAN      => PK%XBLOCK_0(:,IS0:IS0)
  IS0 = IS0 + 1
  PK%I%R%XANDAY   => PK%XBLOCK_0(:,IS0:IS0)
  IS0 = IS0 + 1
  PK%I%R%XANFM    => PK%XBLOCK_0(:,IS0:IS0)
  IS00 = IS00 + 1
  PK%I%R%XBIOMASS     => PK%XBLOCK_00(:,:,IS00:IS00)
  IS00 = IS00 + 1
  PK%I%R%XRESP_BIOMASS   => PK%XBLOCK_00(:,:,IS00:IS00)
END IF
!
ISP = ISP + 1
PK%I%R%XLE        => PK%XBLOCK_SIMPLE(:,ISP:ISP) 
!
IF (IO%LTR_ML) THEN
  ISP = ISP + 1
  PK%I%R%XFAPARC => PK%XBLOCK_SIMPLE(:,ISP:ISP)
  ISP = ISP + 1
  PK%I%R%XFAPIRC => PK%XBLOCK_SIMPLE(:,ISP:ISP)
  ISP = ISP + 1
  PK%I%R%XLAI_EFFC => PK%XBLOCK_SIMPLE(:,ISP:ISP)
  ISP = ISP + 1
  PK%I%R%XMUS => PK%XBLOCK_SIMPLE(:,ISP:ISP)  
ELSE
  IS0 = IS0 + 1
  PK%I%R%XFAPARC => PK%XBLOCK_0(:,IS0:IS0)
  IS0 = IS0 + 1
  PK%I%R%XFAPIRC => PK%XBLOCK_0(:,IS0:IS0)
  IS0 = IS0 + 1
  PK%I%R%XLAI_EFFC => PK%XBLOCK_0(:,IS0:IS0)
  IS0 = IS0 + 1
  PK%I%R%XMUS => PK%XBLOCK_0(:,IS0:IS0)
ENDIF
!
IF (IO%CRESPSL=='CNT') THEN
  ISLT = ISLT + 1
  PK%I%R%XLITTER      => PK%XBLOCK_LITTER(:,:,:,ISLT:ISLT)
  ISC = ISC + 1
  PK%I%R%XSOILCARB    => PK%XBLOCK_SOILCARB(:,:,ISC:ISC)
  ISLTV = ISLTV + 1
  PK%I%R%XLIGNIN_STRUC   => PK%XBLOCK_LITTLEVS(:,:,ISLTV:ISLTV)
ELSE
  IS000 = IS000 + 1
  PK%I%R%XLITTER      => PK%XBLOCK_000(:,:,:,IS000:IS000)
  IS00 = IS00 + 1
  PK%I%R%XSOILCARB    => PK%XBLOCK_00(:,:,IS00:IS00)
  IS00 = IS00 + 1
  PK%I%R%XLIGNIN_STRUC   => PK%XBLOCK_00(:,:,IS00:IS00)
END IF
!
ISP = ISP + 1
PK%I%R%XPSN       => PK%XBLOCK_SIMPLE(:,ISP:ISP)
ISP = ISP + 1
PK%I%R%XPSNG      => PK%XBLOCK_SIMPLE(:,ISP:ISP)
ISP = ISP + 1
PK%I%R%XPSNV      => PK%XBLOCK_SIMPLE(:,ISP:ISP)
!
IF(IR%TSNOW%SCHEME=='EBA') THEN
  ISP = ISP + 1
   PK%I%R%XPSNV_A   => PK%XBLOCK_SIMPLE(:,ISP:ISP)
ELSE
  IS0 = IS0 + 1
  PK%I%R%XPSNV_A    => PK%XBLOCK_0(:,IS0:IS0)
ENDIF
! xsnowfree_alb, xsnoxfree_alb_veg, xsnowfree_alb_soil, xred_noise, xincr
!
!
! P
!
ISG = ISG + 1
PK%I%P%XSAND      => PK%XBLOCK_GROUND(:,:,ISG)
ISG = ISG + 1
PK%I%P%XCLAY      => PK%XBLOCK_GROUND(:,:,ISG)
ISP = ISP + 1
PK%I%P%XRUNOFFB   => PK%XBLOCK_SIMPLE(:,ISP)
ISP = ISP + 1
PK%I%P%XWDRAIN    => PK%XBLOCK_SIMPLE(:,ISP)
!
!
! G
ISP = ISP + 1
PK%G%XLAT     => PK%XBLOCK_SIMPLE(:,ISP)
ISP = ISP + 1
PK%G%XLON     => PK%XBLOCK_SIMPLE(:,ISP)
!
! I
!
IF (IO%CISBA=='DIF'.AND.IO%CRUNOFF=='SGH') THEN
!
  ISG = ISG + 1
  PK%I%I%XTOPQS => PK%XBLOCK_GROUND(:,:,ISG:ISG)
!  
ELSE
!
  IS01 = IS01 + 1
  PK%I%I%XTOPQS   => PK%XBLOCK_01(:,:,IS01:IS01)
!   
END IF
!
IF (IO%CRAIN=='SGH')THEN
  ISP = ISP + 1
   PK%I%I%XMUF => PK%XBLOCK_SIMPLE(:,ISP)
ELSE
  IS0 = IS0 + 1
  PK%I%I%XMUF=> PK%XBLOCK_0(:,IS0)
ENDIF
!
ISP = ISP + 1
PK%I%I%XFSAT      => PK%XBLOCK_SIMPLE(:,ISP)
!
ISP = ISP + 1
PK%I%I%XFFLOOD    => PK%XBLOCK_SIMPLE(:,ISP)
ISP = ISP + 1
PK%I%I%XPIFLOOD   => PK%XBLOCK_SIMPLE(:,ISP)
ISP = ISP + 1
PK%I%I%XFF        => PK%XBLOCK_SIMPLE(:,ISP:ISP)
ISP = ISP + 1
PK%I%I%XFFG       => PK%XBLOCK_SIMPLE(:,ISP:ISP)
ISP = ISP + 1
PK%I%I%XFFV       => PK%XBLOCK_SIMPLE(:,ISP:ISP)
ISP = ISP + 1
PK%I%I%XFFROZEN   => PK%XBLOCK_SIMPLE(:,ISP:ISP)
ISP = ISP + 1
PK%I%I%XALBF      => PK%XBLOCK_SIMPLE(:,ISP:ISP)
ISP = ISP + 1
PK%I%I%XEMISF     => PK%XBLOCK_SIMPLE(:,ISP:ISP)
!
ISA = ISA + 1
PK%I%I%XDIR_ALB_WITH_SNOW=> PK%XBLOCK_ALB(:,:,ISA:ISA)
ISA = ISA + 1
PK%I%I%XSCA_ALB_WITH_SNOW=> PK%XBLOCK_ALB(:,:,ISA:ISA)
!
!
! IMI  + AG
!
IF (LAGRIP .AND. (IO%CPHOTO=='LAI' .OR. IO%CPHOTO=='LST' .OR. IO%CPHOTO=='NIT' .OR. IO%CPHOTO=='NCB')) THEN
  ISTP = ISTP + 1
  PK%I%M%I%TSEED        => PK%TBLOCK_SIMPLE(:,ISTP:ISTP)
  ISTP = ISTP + 1
  PK%I%M%I%TREAP        => PK%TBLOCK_SIMPLE(:,ISTP:ISTP)
  ISP = ISP + 1
   PK%I%M%I%XIRRIG       => PK%XBLOCK_SIMPLE(:,ISP:ISP)
  ISP = ISP + 1
   PK%I%M%I%XWATSUP      => PK%XBLOCK_SIMPLE(:,ISP:ISP)
  ISLP = ISLP + 1
   PK%AG%LIRRIDAY    => PK%LBLOCK_SIMPLE(:,ISLP:ISLP)
  ISP = ISP + 1
   PK%AG%XTHRESHOLDSPT   => PK%XBLOCK_SIMPLE(:,ISP:ISP)
  ISLP = ISLP + 1
   PK%AG%LIRRIGATE   => PK%LBLOCK_SIMPLE(:,ISLP:ISLP)
ELSE
  IST0 = IST0 + 1
  PK%I%M%I%TSEED        => PK%TBLOCK_0(:,IST0:IST0)
  IST0 = IST0 + 1
  PK%I%M%I%TREAP        => PK%TBLOCK_0(:,IST0:IST0)
  IS0 = IS0 + 1
  PK%I%M%I%XIRRIG       => PK%XBLOCK_0(:,IS0:IS0)
  IS0 = IS0 + 1
  PK%I%M%I%XWATSUP      => PK%XBLOCK_0(:,IS0:IS0)
  ISL0 = ISL0 + 1
  PK%AG%LIRRIDAY    => PK%LBLOCK_0(:,ISL0:ISL0)
  IS0 = IS0 + 1
  PK%AG%XTHRESHOLDSPT   => PK%XBLOCK_0(:,IS0:IS0)
  ISL0 = ISL0 + 1
  PK%AG%LIRRIGATE   => PK%LBLOCK_0(:,ISL0:ISL0)
ENDIF
!
!
!
! MEB STUFF END
!
!
IF (ISP.GT.PK%NSIZE_SIMPLE) &
  CALL ABOR1_SFX("PACK_ISBA_PATCH_n: PROBLEM DEFINING SIZE_SIMPLE / NUMBER OF FIELDS")
IF (ISG.GT.PK%NSIZE_GROUND) &
  CALL ABOR1_SFX("PACK_ISBA_PATCH_n: PROBLEM DEFINING SIZE_GROUND / NUMBER OF FIELDS")
IF (ISV.GT.PK%NSIZE_VEGTYPE) &
  CALL ABOR1_SFX("PACK_ISBA_PATCH_n: PROBLEM DEFINING SIZE_VEGTYPE / NUMBER OF FIELDS")
IF (IST.GT.PK%NSIZE_TG) &
  CALL ABOR1_SFX("PACK_ISBA_PATCH_n: PROBLEM DEFINING SIZE_TG / NUMBER OF FIELDS")
IF (ISW.GT.PK%NSIZE_SNOW) &
  CALL ABOR1_SFX("PACK_ISBA_PATCH_n: PROBLEM DEFINING SIZE_SNOW / NUMBER OF FIELDS")
IF (ISA.GT.PK%NSIZE_ALB) &
  CALL ABOR1_SFX("PACK_ISBA_PATCH_n: PROBLEM DEFINING SIZE_ALB / NUMBER OF FIELDS")
IF (IS0.GT.PK%NSIZE_0) &
  CALL ABOR1_SFX("PACK_ISBA_PATCH_n: PROBLEM DEFINING SIZE_0 / NUMBER OF FIELDS")
IF (IS00.GT.PK%NSIZE_00) &
  CALL ABOR1_SFX("PACK_ISBA_PATCH_n: PROBLEM DEFINING SIZE_00 / NUMBER OF FIELDS")
IF (IS01.GT.PK%NSIZE_01) &
  CALL ABOR1_SFX("PACK_ISBA_PATCH_n: PROBLEM DEFINING SIZE_01 / NUMBER OF FIELDS")
IF (IS2.GT.PK%NSIZE_2) &
  CALL ABOR1_SFX("PACK_ISBA_PATCH_n: PROBLEM DEFINING SIZE_2 / NUMBER OF FIELDS")
IF (ISB.GT.PK%NSIZE_BIOMASS) &
  CALL ABOR1_SFX("PACK_ISBA_PATCH_n: PROBLEM DEFINING SIZE_BIOMASS / NUMBER OF FIELDS")
IF (ISLT.GT.PK%NSIZE_LITTER) &
  CALL ABOR1_SFX("PACK_ISBA_PATCH_n: PROBLEM DEFINING SIZE_LITTER / NUMBER OF FIELDS")
IF (ISC.GT.PK%NSIZE_SOILCARB) &
  CALL ABOR1_SFX("PACK_ISBA_PATCH_n: PROBLEM DEFINING SIZE_SOILCARB / NUMBER OF FIELDS")
IF (ISLTV.GT.PK%NSIZE_LITTLEVS) &
  CALL ABOR1_SFX("PACK_ISBA_PATCH_n: PROBLEM DEFINING SIZE_LITTLEVS / NUMBER OF FIELDS")
IF (IS000.GT.PK%NSIZE_000) &
  CALL ABOR1_SFX("PACK_ISBA_PATCH_n: PROBLEM DEFINING SIZE_000 / NUMBER OF FIELDS")
IF (ISTP.GT.PK%NSIZE_TSIMPLE) &
  CALL ABOR1_SFX("PACK_ISBA_PATCH_n: PROBLEM DEFINING SIZE_TSIMPLE / NUMBER OF FIELDS")
IF (IST0.GT.PK%NSIZE_T0) &
  CALL ABOR1_SFX("PACK_ISBA_PATCH_n: PROBLEM DEFINING SIZE_T0 / NUMBER OF FIELDS")
IF (ISLP.GT.PK%NSIZE_LSIMPLE) &
  CALL ABOR1_SFX("PACK_ISBA_PATCH_n: PROBLEM DEFINING SIZE_LSIMPLE / NUMBER OF FIELDS")
IF (ISL0.GT.PK%NSIZE_L0) &
  CALL ABOR1_SFX("PACK_ISBA_PATCH_n: PROBLEM DEFINING SIZE_L0 / NUMBER OF FIELDS")
IF (ISN0.GT.PK%NSIZE_N0) &
  CALL ABOR1_SFX("PACK_ISBA_PATCH_n: PROBLEM DEFINING SIZE_N0 / NUMBER OF FIELDS")  
!
!------------------------------------------------------------------------
!
print*,KMASK
PK%I%M%X%XZ0_O_Z0H   (:,1) = IPM%X%XZ0_O_Z0H   (KMASK(:), KPATCH)
PK%I%M%T%XEMIS       (:,1) = IPM%T%XEMIS       (KMASK(:), KPATCH)
PK%I%M%T%XALBNIR     (:,1) = IPM%T%XALBNIR     (KMASK(:), KPATCH)
PK%I%M%T%XALBVIS     (:,1) = IPM%T%XALBVIS     (KMASK(:), KPATCH)
PK%I%M%T%XALBUV      (:,1) = IPM%T%XALBUV      (KMASK(:), KPATCH)
PK%I%M%T%XALBNIR_VEG (:,1) = IPM%T%XALBNIR_VEG (KMASK(:), KPATCH)
PK%I%M%T%XALBVIS_VEG (:,1) = IPM%T%XALBVIS_VEG (KMASK(:), KPATCH)
PK%I%M%T%XALBUV_VEG  (:,1) = IPM%T%XALBUV_VEG  (KMASK(:), KPATCH)
PK%I%M%A%XALBNIR_SOIL(:,1) = IPM%A%XALBNIR_SOIL(KMASK(:), KPATCH)
PK%I%M%A%XALBVIS_SOIL(:,1) = IPM%A%XALBVIS_SOIL(KMASK(:), KPATCH)
PK%I%M%A%XALBUV_SOIL (:,1) = IPM%A%XALBUV_SOIL (KMASK(:), KPATCH)
PK%I%M%T%XZ0         (:,1) = IPM%T%XZ0         (KMASK(:), KPATCH)
PK%I%M%T%XWRMAX_CF   (:,1) = IPM%T%XWRMAX_CF   (KMASK(:), KPATCH)
PK%I%M%T%XGAMMA      (:,1) = IPM%T%XGAMMA      (KMASK(:), KPATCH)
PK%I%M%T%XCV         (:,1) = IPM%T%XCV         (KMASK(:), KPATCH)
PK%I%M%T%XRGL        (:,1) = IPM%T%XRGL        (KMASK(:), KPATCH)
PK%I%IP%XRUNOFFD     (:,1) =  IP%XRUNOFFD      (KMASK(:), KPATCH)
PK%ISS%XZ0EFFIP      (:,1) =  ISS%XZ0EFFIP     (KMASK(:), KPATCH)
PK%ISS%XZ0EFFIM      (:,1) =  ISS%XZ0EFFIM     (KMASK(:), KPATCH)
PK%ISS%XZ0EFFJP      (:,1) =  ISS%XZ0EFFJP     (KMASK(:), KPATCH)
PK%ISS%XZ0EFFJM      (:,1) =  ISS%XZ0EFFJM     (KMASK(:), KPATCH)  
PK%I%R%XWR           (:,1) =  IR%XWR           (KMASK(:), KPATCH) 
PK%I%M%T%XLAI        (:,1) = IPM%T%XLAI        (KMASK(:), KPATCH) 
PK%I%R%XRESA         (:,1) =  IR%XRESA         (KMASK(:), KPATCH) 
PK%I%IP%XPCPS        (:,1) =  IP%XPCPS         (KMASK(:), KPATCH)
PK%I%IP%XPLVTT       (:,1) =  IP%XPLVTT        (KMASK(:), KPATCH)
PK%I%IP%XPLSTT       (:,1) =  IP%XPLSTT        (KMASK(:), KPATCH)
PK%I%M%T%XVEG        (:,1) = IPM%T%XVEG        (KMASK(:), KPATCH) 
PK%I%R%TSNOW%ALB     (:,1) =  IR%TSNOW%ALB     (KMASK(:), KPATCH) 
PK%I%R%XLE           (:,1) =  IR%XLE           (KMASK(:), KPATCH) 
PK%I%R%XPSN          (:,1) =  IR%XPSN          (KMASK(:), KPATCH)
PK%I%R%XPSNG         (:,1) =  IR%XPSNG         (KMASK(:), KPATCH)
PK%I%R%XPSNV         (:,1) =  IR%XPSNV         (KMASK(:), KPATCH)    
PK%I%IP%XALBNIR_DRY  (:) =  IP%XALBNIR_DRY   (KMASK(:))
PK%I%IP%XALBVIS_DRY  (:) =  IP%XALBVIS_DRY   (KMASK(:))
PK%I%IP%XALBUV_DRY   (:) =  IP%XALBUV_DRY    (KMASK(:))
PK%I%IP%XALBNIR_WET  (:) =  IP%XALBNIR_WET   (KMASK(:))
PK%I%IP%XALBVIS_WET  (:) =  IP%XALBVIS_WET   (KMASK(:))
PK%I%IP%XALBUV_WET   (:) =  IP%XALBUV_WET    (KMASK(:))    
PK%I%P%XRUNOFFB      (:) =  P%XRUNOFFB       (KMASK(:))
PK%I%P%XWDRAIN       (:) =  P%XWDRAIN        (KMASK(:))
PK%I%IP%XTAUICE      (:) =  IP%XTAUICE       (KMASK(:))
PK%ISS%XZ0REL        (:) =  ISS%XZ0REL       (KMASK(:))
PK%ISS%XAOSIP        (:) =  ISS%XAOSIP       (KMASK(:))
PK%ISS%XAOSIM        (:) =  ISS%XAOSIM       (KMASK(:))
PK%ISS%XAOSJP        (:) =  ISS%XAOSJP       (KMASK(:))
PK%ISS%XAOSJM        (:) =  ISS%XAOSJM       (KMASK(:))
PK%ISS%XHO2IP        (:) =  ISS%XHO2IP       (KMASK(:))
PK%ISS%XHO2IM        (:) =  ISS%XHO2IM       (KMASK(:))
PK%ISS%XHO2JP        (:) =  ISS%XHO2JP       (KMASK(:))
PK%ISS%XHO2JM        (:) =  ISS%XHO2JM       (KMASK(:))
PK%ISS%XSSO_SLOPE    (:) =  ISS%XSSO_SLOPE   (KMASK(:))
PK%I%IP%XGAMMAT      (:) =  IP%XGAMMAT       (KMASK(:))
PK%I%IP%XTDEEP       (:) =  IP%XTDEEP        (KMASK(:)) 
PK%G%XLAT            (:) =  IG%XLAT          (KMASK(:))
PK%G%XLON            (:) =  IG%XLON          (KMASK(:))    
PK%I%I%XFSAT         (:) =  INI%XFSAT        (KMASK(:))
!  
DO JK=1,IO%NGROUND_LAYER
  PK%I%P%XCLAY    (:,JK)   = P%XCLAY    (KMASK(:), JK)
  PK%I%P%XSAND    (:,JK)   = P%XSAND    (KMASK(:), JK)
  PK%I%IP%XWFC    (:,JK)   = IP%XWFC     (KMASK(:), JK)
  PK%I%IP%XWWILT  (:,JK)   = IP%XWWILT   (KMASK(:), JK)
  PK%I%IP%XWSAT   (:,JK)   = IP%XWSAT    (KMASK(:), JK)    
  PK%I%IP%XCONDSAT(:,JK,1) = IP%XCONDSAT (KMASK(:), JK, KPATCH)      
  PK%I%M%X%XDG    (:,JK,1) = IPM%X%XDG   (KMASK(:), JK, KPATCH)  
  PK%I%R%XWG      (:,JK,1) = IR%XWG      (KMASK(:), JK, KPATCH)
  PK%I%R%XWGI     (:,JK,1) = IR%XWGI     (KMASK(:), JK, KPATCH)
  PK%I%IP%XMPOTSAT(:, JK)  = IP%XMPOTSAT (KMASK(:), JK)
  PK%I%IP%XBCOEF  (:, JK)  = IP%XBCOEF   (KMASK(:), JK)         
ENDDO  
!  
PK%I%IP%XKSAT_ICE(:,1) = IP%XKSAT_ICE(KMASK(:),KPATCH)
PK%I%M%X%XD_ICE  (:,1) = IPM%X%XD_ICE (KMASK(:),KPATCH)
  !
DO JK=1,NVEGTYPE
  PK%I%IP%XVEGTYPE_PATCH(:,JK,1) = IP%XVEGTYPE_PATCH(KMASK(:), JK, KPATCH)
ENDDO  
!
DO JK=1,SIZE(IR%XTG,2)
  PK%I%R%XTG(:,JK,1) = IR%XTG(KMASK(:), JK, KPATCH)  
ENDDO
  !  
DO JK=1,IR%TSNOW%NLAYER
  PK%I%R%TSNOW%WSNOW(:,JK,1) = IR%TSNOW%WSNOW(KMASK(:), JK, KPATCH)
  PK%I%R%TSNOW%RHO  (:,JK,1) = IR%TSNOW%RHO  (KMASK(:), JK, KPATCH)
ENDDO  
!  
DO JK=1,SIZE(PK%I%I%XDIR_ALB_WITH_SNOW,2)
  PK%I%I%XDIR_ALB_WITH_SNOW (:,JK,1)= INI%XDIR_ALB_WITH_SNOW(KMASK(:),JK,KPATCH)
  PK%I%I%XSCA_ALB_WITH_SNOW (:,JK,1)= INI%XSCA_ALB_WITH_SNOW(KMASK(:),JK,KPATCH)
ENDDO
!
IF (IO%LFLOOD)THEN
  PK%I%I%XFFLOOD  (:)   = INI%XFFLOOD  (KMASK(:))
  PK%I%I%XPIFLOOD (:)   = INI%XPIFLOOD (KMASK(:))
  PK%I%I%XFF      (:,1) = INI%XFF      (KMASK(:),KPATCH)
  PK%I%I%XFFG     (:,1) = INI%XFFG     (KMASK(:),KPATCH)
  PK%I%I%XFFV     (:,1) = INI%XFFV     (KMASK(:),KPATCH)
  PK%I%I%XFFROZEN (:,1) = INI%XFFROZEN (KMASK(:),KPATCH)    
  PK%I%I%XALBF    (:,1) = INI%XALBF    (KMASK(:),KPATCH)
  PK%I%I%XEMISF   (:,1) = INI%XEMISF   (KMASK(:),KPATCH)       
ELSE
  PK%I%I%XFFLOOD  (:)   = 0.0
  PK%I%I%XPIFLOOD (:)   = 0.0
  PK%I%I%XFF      (:,1) = 0.0
  PK%I%I%XFFG     (:,1) = 0.0
  PK%I%I%XFFROZEN (:,1) = 0.0
  PK%I%I%XFFV     (:,1) = 0.0
  PK%I%I%XALBF    (:,1) = 0.0
  PK%I%I%XEMISF   (:,1) = 0.0
ENDIF
!
IF(IR%TSNOW%SCHEME=='EBA') THEN
  PK%I%R%XPSNV_A (:,1) = IR%XPSNV_A(KMASK(:), KPATCH)
END IF
!
IF (IR%TSNOW%SCHEME=='3-L' .OR. IR%TSNOW%SCHEME=='CRO') THEN
  DO JK=1,SIZE(PK%I%R%TSNOW%HEAT,2)
    PK%I%R%TSNOW%HEAT   (:, JK,1) =  IR%TSNOW%HEAT   (KMASK(:), JK, KPATCH)
    PK%I%R%TSNOW%AGE    (:, JK,1) =  IR%TSNOW%AGE    (KMASK(:), JK, KPATCH)
  END DO
  PK%I%R%TSNOW%ALBVIS   (:,1) =  IR%TSNOW%ALBVIS  (KMASK(:), KPATCH) 
  PK%I%R%TSNOW%ALBNIR   (:,1) =  IR%TSNOW%ALBNIR  (KMASK(:), KPATCH) 
  PK%I%R%TSNOW%ALBFIR   (:,1) =  IR%TSNOW%ALBFIR  (KMASK(:), KPATCH) 
END IF
!
IF (IR%TSNOW%SCHEME=='CRO') THEN
  DO JK=1,SIZE(PK%I%R%TSNOW%GRAN1,2)
    PK%I%R%TSNOW%GRAN1  (:, JK,1) =  IR%TSNOW%GRAN1  (KMASK(:), JK, KPATCH)
    PK%I%R%TSNOW%GRAN2  (:, JK,1) =  IR%TSNOW%GRAN2  (KMASK(:), JK, KPATCH)
    PK%I%R%TSNOW%HIST   (:, JK,1) =  IR%TSNOW%HIST   (KMASK(:), JK, KPATCH)
  ENDDO
END IF
!
IF(IO%LGLACIER)THEN
  PK%I%R%XICE_STO(:,1) = IR%XICE_STO  (KMASK(:),KPATCH)
ENDIF
!  
IF (IO%CSCOND=='PL98'.OR.IO%CISBA=='DIF') THEN
  DO JK=1,SIZE(IP%XHCAPSOIL,2)
    PK%I%IP%XHCAPSOIL   (:, JK) =  IP%XHCAPSOIL    (KMASK(:), JK)
    PK%I%IP%XCONDDRY    (:, JK) =  IP%XCONDDRY     (KMASK(:), JK)
    PK%I%IP%XCONDSLD    (:, JK) =  IP%XCONDSLD     (KMASK(:), JK)
  ENDDO
END IF
!
IF (IO%CISBA=='2-L' .OR. IO%CISBA=='3-L') THEN
  PK%I%IP%XC4B        (:) =  IP%XC4B          (KMASK(:))
  PK%I%IP%XACOEF      (:) =  IP%XACOEF        (KMASK(:))
  PK%I%IP%XPCOEF      (:) =  IP%XPCOEF        (KMASK(:))
  PK%I%IP%XCGSAT      (:) =  IP%XCGSAT        (KMASK(:)) 
  PK%I%IP%XC1SAT      (:,1) =  IP%XC1SAT        (KMASK(:), KPATCH)
  PK%I%IP%XC2REF      (:,1) =  IP%XC2REF        (KMASK(:), KPATCH)     
  PK%I%IP%XC4REF      (:,1) =  IP%XC4REF        (KMASK(:), KPATCH)      
  !
  DO JK=1,SIZE(IP%XC3,2)
    PK%I%IP%XC3         (:,JK,1)  =  IP%XC3           (KMASK(:), JK, KPATCH)
  ENDDO
END IF
!
DO JK=1,SIZE(IP%XBCOEF,2)
  PK%I%IP%XMPOTSAT (:, JK) =  IP%XMPOTSAT (KMASK(:), JK)
  PK%I%IP%XBCOEF   (:, JK) =  IP%XBCOEF   (KMASK(:), JK)
ENDDO
!
IF (IO%CISBA=='DIF') THEN
  DO JK=1,SIZE(IPM%X%XROOTFRAC,2)
    PK%I%M%X%XROOTFRAC   (:, JK,1) = IPM%X%XROOTFRAC   (KMASK(:), JK, KPATCH)
    PK%I%IP%XDZG        (:, JK,1) =  IP%XDZG        (KMASK(:), JK, KPATCH)
    PK%I%IP%XDZDIF      (:, JK,1) =  IP%XDZDIF      (KMASK(:), JK, KPATCH)
    PK%I%IP%XSOILWGHT   (:, JK,1) =  IP%XSOILWGHT   (KMASK(:), JK, KPATCH)
  ENDDO
  PK%I%M%X%NWG_LAYER (:,1)  = IPM%X%NWG_LAYER (KMASK(:),KPATCH)
  PK%I%IP%XFWTD     (:)  =  IP%XFWTD     (KMASK(:))
  PK%I%IP%XWTD      (:)  =  IP%XWTD      (KMASK(:))
ENDIF
!
IF (IO%CISBA=='DIF'.AND.IO%CRUNOFF=='SGH') THEN
  DO JK=1,SIZE(IPM%X%XROOTFRAC,2)
    PK%I%I%XTOPQS   (:, JK,1) =  INI%XTOPQS   (KMASK(:), JK, KPATCH)  
  ENDDO        
END IF
!
IF (IO%LTR_ML) THEN
  PK%I%R%XFAPARC      (:,1) =  IR%XFAPARC      (KMASK(:), KPATCH)
  PK%I%R%XFAPIRC      (:,1) =  IR%XFAPIRC      (KMASK(:), KPATCH)
  PK%I%R%XLAI_EFFC    (:,1) =  IR%XLAI_EFFC    (KMASK(:), KPATCH)
  PK%I%R%XMUS         (:,1) =  IR%XMUS         (KMASK(:), KPATCH)
ENDIF  
!
IF (IO%CPHOTO=='NON') THEN
  PK%I%M%T%XRSMIN      (:,1) = IPM%T%XRSMIN      (KMASK(:), KPATCH)
END IF
!
IF(IO%LMEB_PATCH(KPATCH))THEN
!
  PK%I%R%XWRL          (:,1) =  IR%XWRL          (KMASK(:), KPATCH) 
  PK%I%R%XWRLI         (:,1) =  IR%XWRLI         (KMASK(:), KPATCH) 
  PK%I%R%XWRVN         (:,1) =  IR%XWRVN         (KMASK(:), KPATCH) 
  PK%I%R%XTV           (:,1) =  IR%XTV           (KMASK(:), KPATCH) 
  PK%I%R%XTL           (:,1) =  IR%XTL           (KMASK(:), KPATCH) 
  PK%I%R%XTC           (:,1) =  IR%XTC           (KMASK(:), KPATCH) 
  PK%I%R%XQC           (:,1) =  IR%XQC           (KMASK(:), KPATCH) 
!
! Please note that secondary Ecoclimap parameters, i.e. those
! with postfix GV, are given to the corresponing original ISBA physiography
! parameters in the case of LMEB_PATCH/OMEB=true. And the original ISBA
! physiography parameters are given to the canopy vegetation parameters.
! E.g. XLAI -> XP_LAIV and XLAIGV -> XP_LAI
!
!
  PK%I%M%M%XH_VEG    (:,1) = IPM%M%XH_VEG    (KMASK(:), KPATCH)
  PK%I%M%M%XGNDLITTER(:,1) = IPM%M%XGNDLITTER(KMASK(:), KPATCH)
  PK%I%M%M%XZ0LITTER (:,1) = IPM%M%XZ0LITTER (KMASK(:), KPATCH)
ENDIF
!
IF(IO%CPHOTO/='NON' .OR. IO%LMEB_PATCH(KPATCH))THEN
  PK%I%M%T%XBSLAI(:,1) = IPM%T%XBSLAI(KMASK(:), KPATCH)
ENDIF
!
IF (IO%CPHOTO/='NON') THEN
  PK%I%M%T%XLAIMIN(:,1) = IPM%T%XLAIMIN(KMASK(:), KPATCH)
  PK%I%M%T%XSEFOLD(:,1) = IPM%T%XSEFOLD(KMASK(:), KPATCH)
  PK%I%M%X%XH_TREE(:,1) = IPM%X%XH_TREE(KMASK(:), KPATCH)
  PK%I%IP%XANMAX  (:,1) = IP%XANMAX    (KMASK(:), KPATCH)
  PK%I%IP%XFZERO  (:,1) = IP%XFZERO    (KMASK(:), KPATCH)
  PK%I%IP%XEPSO   (:,1) = IP%XEPSO     (KMASK(:), KPATCH)
  PK%I%IP%XGAMM   (:,1) = IP%XGAMM     (KMASK(:), KPATCH)
  PK%I%IP%XQDGAMM (:,1) = IP%XQDGAMM   (KMASK(:), KPATCH)
  PK%I%M%T%XGMES  (:,1) = IPM%T%XGMES  (KMASK(:), KPATCH)
  PK%I%M%X%XRE25  (:,1) = IPM%X%XRE25  (KMASK(:), KPATCH)
  PK%I%IP%XQDGMES (:,1) = IP%XQDGMES   (KMASK(:), KPATCH)
  PK%I%IP%XT1GMES (:,1) = IP%XT1GMES   (KMASK(:), KPATCH)
  PK%I%IP%XT2GMES (:,1) = IP%XT2GMES   (KMASK(:), KPATCH)
  PK%I%IP%XAMAX   (:,1) = IP%XAMAX     (KMASK(:), KPATCH)
  PK%I%IP%XQDAMAX (:,1) = IP%XQDAMAX   (KMASK(:), KPATCH)
  PK%I%IP%XT1AMAX (:,1) = IP%XT1AMAX   (KMASK(:), KPATCH)
  PK%I%IP%XT2AMAX (:,1) = IP%XT2AMAX   (KMASK(:), KPATCH)
  PK%I%R%XAN      (:,1) = IR%XAN       (KMASK(:), KPATCH) 
  PK%I%R%XANDAY   (:,1) = IR%XANDAY    (KMASK(:), KPATCH) 
  PK%I%R%XANFM    (:,1) = IR%XANFM     (KMASK(:), KPATCH) 
  PK%I%M%T%XGC    (:,1) = IPM%T%XGC    (KMASK(:), KPATCH)
  DO JK=1,SIZE(IR%XBIOMASS,2)
    PK%I%R%XBIOMASS     (:,JK,1) = IR%XBIOMASS     (KMASK(:),JK,KPATCH)
    PK%I%R%XRESP_BIOMASS(:,JK,1) = IR%XRESP_BIOMASS(KMASK(:),JK,KPATCH)
  END DO
END IF
!
IF (IO%CPHOTO=='AST' .OR. IO%CPHOTO=='LST' .OR. IO%CPHOTO=='NIT' .OR. IO%CPHOTO=='NCB') THEN
  PK%I%M%T%LSTRESS(:,1) = IPM%T%LSTRESS (KMASK(:), KPATCH)
  PK%I%M%T%XF2I   (:,1) = IPM%T%XF2I    (KMASK(:), KPATCH)
  PK%I%IP%XAH     (:,1) = IP%XAH        (KMASK(:), KPATCH)
  PK%I%IP%XBH     (:,1) = IP%XBH        (KMASK(:), KPATCH)
  PK%I%M%X%XDMAX  (:,1) = IPM%X%XDMAX   (KMASK(:), KPATCH)
END IF
!
IF(LAGRIP .AND. (IO%CPHOTO=='LAI' .OR. IO%CPHOTO=='LST' .OR. IO%CPHOTO=='NIT' .OR. IO%CPHOTO=='NCB')) THEN
  PK%I%M%I%TSEED     (:,1) = IPM%I%TSEED     (KMASK(:),KPATCH)
  PK%I%M%I%TREAP     (:,1) = IPM%I%TREAP     (KMASK(:),KPATCH)
  PK%I%M%I%XIRRIG    (:,1) = IPM%I%XIRRIG    (KMASK(:),KPATCH)
  PK%I%M%I%XWATSUP   (:,1) = IPM%I%XWATSUP   (KMASK(:),KPATCH)
  PK%AG%LIRRIDAY     (:,1) = AG%LIRRIDAY     (KMASK(:),KPATCH)
  PK%AG%XTHRESHOLDSPT(:,1) = AG%XTHRESHOLDSPT(KMASK(:),KPATCH)
  PK%AG%LIRRIGATE    (:,1) = AG%LIRRIGATE    (KMASK(:),KPATCH)
ENDIF
!
IF(IO%CPHOTO=='NIT' .OR. IO%CPHOTO=='NCB') THEN
  PK%I%M%T%XCE_NITRO  (:,1) = IPM%T%XCE_NITRO (KMASK(:),KPATCH)
  PK%I%M%T%XCF_NITRO  (:,1) = IPM%T%XCF_NITRO (KMASK(:),KPATCH)
  PK%I%M%T%XCNA_NITRO (:,1) = IPM%T%XCNA_NITRO(KMASK(:),KPATCH)
  PK%I%IP%XBSLAI_NITRO(:,1) =  IP%XBSLAI_NITRO(KMASK(:),KPATCH)      
END IF
!
IF (IO%CPHOTO=='NCB') THEN
  DO JK=1,SIZE(IP%XINCREASE,2)
    PK%I%IP%XINCREASE (:,JK,1) = IP%XINCREASE  (KMASK(:),JK,KPATCH)
  END DO
  PK%I%IP%XTAU_WOOD (:,1) = IP%XTAU_WOOD(KMASK(:),KPATCH)
END IF
!
IF (IO%CRESPSL=='CNT') THEN
  DO JL=1,SIZE(PK%I%R%XLITTER,3)
    DO JK=1,SIZE(PK%I%R%XLITTER,2)
      PK%I%R%XLITTER(:,JK,JL,1) = IR%XLITTER(KMASK(:),JK,JL,KPATCH)
    ENDDO
  ENDDO
  DO JK=1,SIZE(PK%I%R%XSOILCARB,2)
    PK%I%R%XSOILCARB(:,JK,1) = IR%XSOILCARB(KMASK(:),JK,KPATCH)
  ENDDO
  DO JK=1,SIZE(PK%I%R%XLIGNIN_STRUC,2)
    PK%I%R%XLIGNIN_STRUC(:,JK,1) = IR%XLIGNIN_STRUC(KMASK(:),JK,KPATCH)
  ENDDO
  DO JK=1,SIZE(PK%I%IP%XTURNOVER,2)
    PK%I%IP%XTURNOVER(:,JK,1) = IP%XTURNOVER(KMASK(:),JK,KPATCH)
  ENDDO
END IF
!
IF (IO%CRAIN=='SGH')THEN
  PK%I%I%XMUF(:) = INI%XMUF(KMASK(:))
ENDIF
!
IF (LHOOK) CALL DR_HOOK('PACK_ISBA_PATCH_N',1,ZHOOK_HANDLE)
!------------------------------------------------------------------------
END SUBROUTINE PACK_ISBA_PATCH_n
