!     #########
SUBROUTINE PACK_ISBA_PATCH_n (AG, IG, I, PK, &
                              KMASK,KSIZE,KPATCH)
!##############################################
!
!
!!****  *PACK_ISBA_PATCH_n * - packs ISBA variables
!!
!!    PURPOSE
!!    -------
!
!!**  METHOD
!!    ------
!!
!!    REFERENCE
!!    ---------
!!      
!!
!!    AUTHOR
!!    ------
!!     V. Masson and A. boone
!!
!!    MODIFICATIONS
!!    -------------
!!      Original    01/2004
!!      B. Decharme    2008 floodplains
!!      B. Decharme 01/2009 Good dim for XP_TG
!!      A.L. Gibelin 04/2009 : BIOMASS and RESP_BIOMASS arrays 
!!      A.L. Gibelin 04/2009 : TAU_WOOD for NCB option 
!!      A.L. Gibelin 05/2009 : Add carbon spinup
!!      A.L. Gibelin 06/2009 : Soil carbon variables for CNT option
!!      A.L. Gibelin 07/2009 : Suppress RDK and transform GPP as a diagnostic
!!      A.L. Gibelin 07/2009 : Suppress PPST and PPSTF as outputs
!!      B. Decharme  04/2013 : DIF lateral subsurface drainage
!!                             water table / surface coupling
!!      P Samuelsson 10/2014 : MEB
!!      P Samuelsson 10/2014 : Additional snow albedos
!!
!!------------------------------------------------------------------
!
!
USE MODD_AGRI_n, ONLY : AGRI_t
USE MODD_GRID_n, ONLY : GRID_t
USE MODD_ISBA_n, ONLY : ISBA_t
USE MODD_PACK_ISBA, ONLY : PACK_ISBA_t
!
USE MODD_DATA_COVER_PAR,  ONLY : NVEGTYPE
!
USE MODD_TREEDRAG,    ONLY : LTREEDRAG
USE MODD_AGRI,        ONLY : LAGRIP
                             

!
USE MODD_CSTS,       ONLY : XLVTT, XLSTT, XCPD
!
USE MODI_ABOR1_SFX
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE
!
!
TYPE(AGRI_t), INTENT(INOUT) :: AG
TYPE(GRID_t), INTENT(INOUT) :: IG
TYPE(ISBA_t), INTENT(INOUT) :: I
TYPE(PACK_ISBA_t), INTENT(INOUT) :: PK
!
INTEGER, INTENT(IN)               :: KSIZE, KPATCH
INTEGER, DIMENSION(:), INTENT(IN) :: KMASK
!
INTEGER :: ISIZE_LSIMPLE, ISIZE_L0, ISIZE_TSIMPLE, ISIZE_T0, ISIZE_SIMPLE,  &
           ISIZE_GROUND, ISIZE_VEGTYPE, ISIZE_TG, ISIZE_SNOW, ISIZE_ALB,    &
           ISIZE_2, ISIZE_BIOMASS, ISIZE_SOILCARB, ISIZE_LITTLEVS,          &
           ISIZE_LITTER, ISIZE_0, ISIZE_00,ISIZE_000, ISIZE_01,             &
           ISIZE_NSIMPLE, ISIZE_N0
!
INTEGER :: JJ, JI, JK, JL 
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
!------------------------------------------------------------------------
IF (LHOOK) CALL DR_HOOK('PACK_ISBA_PATCH_N',0,ZHOOK_HANDLE)
!
ALLOCATE(PK%LBLOCK_SIMPLE(KSIZE,PK%NSIZE_LSIMPLE))
ALLOCATE(PK%LBLOCK_0(0,PK%NSIZE_L0))
ALLOCATE(PK%NBLOCK_SIMPLE(KSIZE,PK%NSIZE_NSIMPLE))
ALLOCATE(PK%NBLOCK_0(0,PK%NSIZE_N0))
ALLOCATE(PK%TBLOCK_SIMPLE(KSIZE,PK%NSIZE_TSIMPLE))
ALLOCATE(PK%TBLOCK_0(0,PK%NSIZE_T0))
ALLOCATE(PK%XBLOCK_SIMPLE(KSIZE,PK%NSIZE_SIMPLE))
ALLOCATE(PK%XBLOCK_GROUND(KSIZE,I%O%NGROUND_LAYER,PK%NSIZE_GROUND))
ALLOCATE(PK%XBLOCK_VEGTYPE(KSIZE,NVEGTYPE,PK%NSIZE_VEGTYPE))
ALLOCATE(PK%XBLOCK_TG(KSIZE,SIZE(I%R%XTG,2),PK%NSIZE_TG))
ALLOCATE(PK%XBLOCK_SNOW(KSIZE,I%R%TSNOW%NLAYER,PK%NSIZE_SNOW))
ALLOCATE(PK%XBLOCK_ALB(KSIZE,SIZE(I%I%XDIR_ALB_WITH_SNOW,2),PK%NSIZE_ALB))
ALLOCATE(PK%XBLOCK_2(KSIZE,2,PK%NSIZE_2))
ALLOCATE(PK%XBLOCK_BIOMASS(KSIZE,I%O%NNBIOMASS,PK%NSIZE_BIOMASS))
ALLOCATE(PK%XBLOCK_SOILCARB(KSIZE,I%O%NNSOILCARB,PK%NSIZE_SOILCARB))
ALLOCATE(PK%XBLOCK_LITTLEVS(KSIZE,I%O%NNLITTLEVS,PK%NSIZE_LITTLEVS))
ALLOCATE(PK%XBLOCK_LITTER(KSIZE,I%O%NNLITTER,I%O%NNLITTLEVS,PK%NSIZE_LITTER))
ALLOCATE(PK%XBLOCK_0(0,PK%NSIZE_0))
ALLOCATE(PK%XBLOCK_00(0,0,PK%NSIZE_00))
ALLOCATE(PK%XBLOCK_000(0,0,0,PK%NSIZE_000))
ALLOCATE(PK%XBLOCK_01(0,1,PK%NSIZE_01))
!
ISIZE_LSIMPLE=0
ISIZE_L0=0
ISIZE_NSIMPLE=0
ISIZE_N0=0
ISIZE_TSIMPLE=0
ISIZE_T0=0
ISIZE_SIMPLE=0
ISIZE_GROUND=0
ISIZE_VEGTYPE=0
ISIZE_TG=0
ISIZE_SNOW=0
ISIZE_ALB=0
ISIZE_2=0
ISIZE_BIOMASS=0
ISIZE_LITTER=0
ISIZE_SOILCARB=0
ISIZE_LITTLEVS=0
ISIZE_0=0
ISIZE_00=0
ISIZE_000=0
ISIZE_01=0
!
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PK%I%M%X%XZ0_O_Z0H     => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PK%I%M%T%XEMIS         => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PK%I%M%T%XALBNIR       => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PK%I%M%T%XALBVIS       => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PK%I%M%T%XALBUV        => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PK%I%M%T%XALBNIR_VEG   => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PK%I%M%T%XALBVIS_VEG   => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PK%I%M%T%XALBUV_VEG    => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PK%I%M%A%XALBNIR_SOIL  => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PK%I%M%A%XALBVIS_SOIL  => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PK%I%M%A%XALBUV_SOIL   => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PK%I%M%T%XZ0           => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE) 
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PK%I%M%T%XWRMAX_CF     => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PK%I%M%T%XGAMMA        => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PK%I%M%T%XCV           => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PK%I%M%T%XRGL          => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PK%I%IP%XRUNOFFD      => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PK%I%IP%XZ0EFFIP      => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PK%I%IP%XZ0EFFIM      => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PK%I%IP%XZ0EFFJP      => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PK%I%IP%XZ0EFFJM      => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PK%I%R%XWR           => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PK%I%M%T%XLAI          => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE) 
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PK%I%R%XRESA         => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE) 
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PK%I%IP%XPCPS          => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PK%I%IP%XPLVTT         => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PK%I%IP%XPLSTT         => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PK%I%M%T%XVEG          => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE) 
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PK%I%R%TSNOW%ALB      => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE) 
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PK%I%R%XLE           => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE) 
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PK%I%R%XPSN          => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PK%I%R%XPSNG         => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PK%I%R%XPSNV         => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PK%I%IP%XALBNIR_DRY   => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PK%I%IP%XALBVIS_DRY   => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PK%I%IP%XALBUV_DRY    => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PK%I%IP%XALBNIR_WET   => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PK%I%IP%XALBVIS_WET   => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PK%I%IP%XALBUV_WET    => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PK%I%P%XRUNOFFB      => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PK%I%P%XWDRAIN       => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PK%I%IP%XTAUICE       => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PK%I%IP%XZ0REL        => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PK%I%P%XAOSIP        => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PK%I%P%XAOSIM        => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PK%I%P%XAOSJP        => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PK%I%P%XAOSJM        => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PK%I%P%XHO2IP        => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PK%I%P%XHO2IM        => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PK%I%P%XHO2JP        => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PK%I%P%XHO2JM        => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PK%I%P%XSSO_SLOPE    => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PK%I%IP%XGAMMAT       => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PK%I%IP%XTDEEP        => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PK%G%XLAT        => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PK%G%XLON        => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
!
ISIZE_GROUND = ISIZE_GROUND + 1
PK%I%P%XCLAY         => PK%XBLOCK_GROUND(:,:,ISIZE_GROUND)
ISIZE_GROUND = ISIZE_GROUND + 1
PK%I%P%XSAND         => PK%XBLOCK_GROUND(:,:,ISIZE_GROUND)
ISIZE_GROUND = ISIZE_GROUND + 1
PK%I%IP%XWFC          => PK%XBLOCK_GROUND(:,:,ISIZE_GROUND)
ISIZE_GROUND = ISIZE_GROUND + 1
PK%I%IP%XWWILT        => PK%XBLOCK_GROUND(:,:,ISIZE_GROUND)
ISIZE_GROUND = ISIZE_GROUND + 1
PK%I%IP%XWSAT         => PK%XBLOCK_GROUND(:,:,ISIZE_GROUND)
ISIZE_GROUND = ISIZE_GROUND + 1
PK%I%IP%XCONDSAT      => PK%XBLOCK_GROUND(:,:,ISIZE_GROUND:ISIZE_GROUND)
ISIZE_GROUND = ISIZE_GROUND + 1
PK%I%M%X%XDG           => PK%XBLOCK_GROUND(:,:,ISIZE_GROUND:ISIZE_GROUND)
ISIZE_GROUND = ISIZE_GROUND + 1
PK%I%R%XWG           => PK%XBLOCK_GROUND(:,:,ISIZE_GROUND:ISIZE_GROUND)
ISIZE_GROUND = ISIZE_GROUND + 1
PK%I%R%XWGI          => PK%XBLOCK_GROUND(:,:,ISIZE_GROUND:ISIZE_GROUND)
!
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PK%I%IP%XKSAT_ICE     => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PK%I%M%X%XD_ICE        => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE)
!
ISIZE_VEGTYPE = ISIZE_VEGTYPE + 1
PK%I%IP%XVEGTYPE_PATCH => PK%XBLOCK_VEGTYPE(:,:,ISIZE_VEGTYPE:ISIZE_VEGTYPE)
!
ISIZE_TG = ISIZE_TG + 1
PK%I%R%XTG           => PK%XBLOCK_TG(:,:,ISIZE_TG:ISIZE_TG)
!
ISIZE_SNOW = ISIZE_SNOW + 1
PK%I%R%TSNOW%WSNOW     => PK%XBLOCK_SNOW(:,:,ISIZE_SNOW:ISIZE_SNOW)
ISIZE_SNOW = ISIZE_SNOW + 1
PK%I%R%TSNOW%RHO      => PK%XBLOCK_SNOW(:,:,ISIZE_SNOW:ISIZE_SNOW)
!
ISIZE_ALB = ISIZE_ALB + 1
PK%I%I%XDIR_ALB_WITH_SNOW=> PK%XBLOCK_ALB(:,:,ISIZE_ALB:ISIZE_ALB)
ISIZE_ALB = ISIZE_ALB + 1
PK%I%I%XSCA_ALB_WITH_SNOW=> PK%XBLOCK_ALB(:,:,ISIZE_ALB:ISIZE_ALB)
!
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PK%I%I%XFFLOOD       => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PK%I%I%XPIFLOOD      => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PK%I%I%XFF           => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PK%I%I%XFFG          => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PK%I%I%XFFV          => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PK%I%I%XFFROZEN      => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PK%I%I%XALBF         => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PK%I%I%XEMISF        => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PK%I%I%XFSAT         => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
!
IF(I%R%TSNOW%SCHEME=='EBA') THEN
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
   PK%I%R%XPSNV_A      => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE)
ELSE
  ISIZE_0 = ISIZE_0 + 1
  PK%I%R%XPSNV_A       => PK%XBLOCK_0(:,ISIZE_0:ISIZE_0)
ENDIF
!
IF (I%R%TSNOW%SCHEME=='3-L' .OR. I%R%TSNOW%SCHEME=='CRO') THEN
  ISIZE_SNOW = ISIZE_SNOW + 1
   PK%I%R%TSNOW%HEAT   => PK%XBLOCK_SNOW(:,:,ISIZE_SNOW:ISIZE_SNOW)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
   PK%I%R%TSNOW%EMIS   => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE)
  ISIZE_SNOW = ISIZE_SNOW + 1
   PK%I%R%TSNOW%AGE    => PK%XBLOCK_SNOW(:,:,ISIZE_SNOW:ISIZE_SNOW)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
   PK%I%R%TSNOW%ALBVIS   => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE) 
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
   PK%I%R%TSNOW%ALBNIR   => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE) 
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
   PK%I%R%TSNOW%ALBFIR   => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE) 
ELSE
  ISIZE_00 = ISIZE_00 + 1
  PK%I%R%TSNOW%HEAT   => PK%XBLOCK_00(:,:,ISIZE_00:ISIZE_00) 
  ISIZE_0 = ISIZE_0 + 1
  PK%I%R%TSNOW%EMIS   => PK%XBLOCK_0(:,ISIZE_0:ISIZE_0)
  ISIZE_00 = ISIZE_00 + 1
  PK%I%R%TSNOW%AGE    => PK%XBLOCK_00(:,:,ISIZE_00:ISIZE_00)
  ISIZE_0 = ISIZE_0 + 1
  PK%I%R%TSNOW%ALBVIS   => PK%XBLOCK_0(:,ISIZE_0:ISIZE_0) 
  ISIZE_0 = ISIZE_0 + 1
  PK%I%R%TSNOW%ALBNIR   => PK%XBLOCK_0(:,ISIZE_0:ISIZE_0) 
  ISIZE_0 = ISIZE_0 + 1
  PK%I%R%TSNOW%ALBFIR   => PK%XBLOCK_0(:,ISIZE_0:ISIZE_0) 
END IF
!
IF(I%R%TSNOW%SCHEME=='CRO') THEN
  ISIZE_SNOW = ISIZE_SNOW + 1
   PK%I%R%TSNOW%GRAN1  => PK%XBLOCK_SNOW(:,:,ISIZE_SNOW:ISIZE_SNOW)
  ISIZE_SNOW = ISIZE_SNOW + 1
   PK%I%R%TSNOW%GRAN2  => PK%XBLOCK_SNOW(:,:,ISIZE_SNOW:ISIZE_SNOW)
  ISIZE_SNOW = ISIZE_SNOW + 1
   PK%I%R%TSNOW%HIST   => PK%XBLOCK_SNOW(:,:,ISIZE_SNOW:ISIZE_SNOW)
ELSE      
  ISIZE_00 = ISIZE_00 + 1
  PK%I%R%TSNOW%GRAN1  => PK%XBLOCK_00(:,:,ISIZE_00:ISIZE_00)  
  ISIZE_00 = ISIZE_00 + 1
  PK%I%R%TSNOW%GRAN2  => PK%XBLOCK_00(:,:,ISIZE_00:ISIZE_00) 
  ISIZE_00 = ISIZE_00 + 1
  PK%I%R%TSNOW%HIST   => PK%XBLOCK_00(:,:,ISIZE_00:ISIZE_00) 
END IF
!
IF(I%O%LGLACIER)THEN  
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1  
   PK%I%R%XICE_STO  => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE)
ELSE     
  ISIZE_0 = ISIZE_0 + 1
  PK%I%R%XICE_STO  => PK%XBLOCK_0(:,ISIZE_0:ISIZE_0)
ENDIF
!
IF (I%O%CSCOND=='PL98'.OR.I%O%CISBA=='DIF') THEN
  ISIZE_GROUND = ISIZE_GROUND + 1
   PK%I%IP%XHCAPSOIL   => PK%XBLOCK_GROUND(:,:,ISIZE_GROUND)
  ISIZE_GROUND = ISIZE_GROUND + 1
   PK%I%IP%XCONDDRY    => PK%XBLOCK_GROUND(:,:,ISIZE_GROUND)
  ISIZE_GROUND = ISIZE_GROUND + 1
   PK%I%IP%XCONDSLD    => PK%XBLOCK_GROUND(:,:,ISIZE_GROUND)   
ELSE
  ISIZE_01 = ISIZE_01 + 1
  PK%I%IP%XHCAPSOIL   => PK%XBLOCK_01(:,:,ISIZE_01)
  ISIZE_01 = ISIZE_01 + 1
  PK%I%IP%XCONDDRY    => PK%XBLOCK_01(:,:,ISIZE_01)
  ISIZE_01 = ISIZE_01 + 1
  PK%I%IP%XCONDSLD    => PK%XBLOCK_01(:,:,ISIZE_01)
END IF
!
IF (I%O%CISBA=='2-L' .OR. I%O%CISBA=='3-L') THEN   
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
   PK%I%IP%XC4B      => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE) 
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
   PK%I%IP%XACOEF    => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
 ISIZE_SIMPLE = ISIZE_SIMPLE + 1
   PK%I%IP%XPCOEF    => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
   PK%I%IP%XCGSAT        => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE) 
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
   PK%I%IP%XC1SAT        => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE) 
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
   PK%I%IP%XC2REF        => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE) 
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
   PK%I%IP%XC4REF        => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE)   
  ISIZE_2 = ISIZE_2 + 1
  PK%I%IP%XC3           => PK%XBLOCK_2(:,:,ISIZE_2:ISIZE_2)
ELSE
  ISIZE_0 = ISIZE_0 + 1
  PK%I%IP%XC4B          => PK%XBLOCK_0(:,ISIZE_0)
  ISIZE_0 = ISIZE_0 + 1
  PK%I%IP%XACOEF        => PK%XBLOCK_0(:,ISIZE_0) 
 ISIZE_0 = ISIZE_0 + 1
  PK%I%IP%XPCOEF        => PK%XBLOCK_0(:,ISIZE_0)
  ISIZE_0 = ISIZE_0 + 1
  PK%I%IP%XCGSAT        => PK%XBLOCK_0(:,ISIZE_0) 
  ISIZE_0 = ISIZE_0 + 1
  PK%I%IP%XC1SAT        => PK%XBLOCK_0(:,ISIZE_0:ISIZE_0) 
  ISIZE_0 = ISIZE_0 + 1
  PK%I%IP%XC2REF        => PK%XBLOCK_0(:,ISIZE_0:ISIZE_0)   
  ISIZE_0 = ISIZE_0 + 1
  PK%I%IP%XC4REF        => PK%XBLOCK_0(:,ISIZE_0:ISIZE_0)  
  ISIZE_00 = ISIZE_00 + 1
  PK%I%IP%XC3           => PK%XBLOCK_00(:,:,ISIZE_00:ISIZE_00)   
END IF
!
ISIZE_GROUND = ISIZE_GROUND + 1
PK%I%IP%XMPOTSAT    => PK%XBLOCK_GROUND(:,:,ISIZE_GROUND)
ISIZE_GROUND = ISIZE_GROUND + 1
PK%I%IP%XBCOEF      => PK%XBLOCK_GROUND(:,:,ISIZE_GROUND)
!
IF (I%O%CISBA=='DIF') THEN
!
  ISIZE_GROUND = ISIZE_GROUND + 1
   PK%I%M%X%XROOTFRAC   => PK%XBLOCK_GROUND(:,:,ISIZE_GROUND:ISIZE_GROUND) 
  ISIZE_GROUND = ISIZE_GROUND + 1
   PK%I%IP%XDZG        => PK%XBLOCK_GROUND(:,:,ISIZE_GROUND:ISIZE_GROUND)
  ISIZE_GROUND = ISIZE_GROUND + 1
   PK%I%IP%XDZDIF      => PK%XBLOCK_GROUND(:,:,ISIZE_GROUND:ISIZE_GROUND) 
  ISIZE_GROUND = ISIZE_GROUND + 1
   PK%I%IP%XSOILWGHT   => PK%XBLOCK_GROUND(:,:,ISIZE_GROUND:ISIZE_GROUND)
!
  ISIZE_NSIMPLE = ISIZE_NSIMPLE + 1
   PK%I%M%X%NWG_LAYER   => PK%NBLOCK_SIMPLE(:,ISIZE_NSIMPLE:ISIZE_NSIMPLE)
! 
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1  
   PK%I%IP%XFWTD=> PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1  
   PK%I%IP%XWTD=> PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
!
ELSE
!
  ISIZE_01 = ISIZE_01 + 1
  PK%I%M%X%XROOTFRAC   => PK%XBLOCK_01(:,:,ISIZE_01:ISIZE_01)
  ISIZE_01 = ISIZE_01 + 1
  PK%I%IP%XDZG        => PK%XBLOCK_01(:,:,ISIZE_01:ISIZE_01)
  ISIZE_01 = ISIZE_01 + 1
  PK%I%IP%XDZDIF      => PK%XBLOCK_01(:,:,ISIZE_01:ISIZE_01)
  ISIZE_01 = ISIZE_01 + 1
  PK%I%IP%XSOILWGHT   => PK%XBLOCK_01(:,:,ISIZE_01:ISIZE_01)  
!  
  ISIZE_N0 = ISIZE_N0 + 1
   PK%I%M%X%NWG_LAYER   => PK%NBLOCK_0(:,ISIZE_N0:ISIZE_N0)
!  
  ISIZE_0 = ISIZE_0 + 1
   PK%I%IP%XFWTD=> PK%XBLOCK_0(:,ISIZE_0)
  ISIZE_0 = ISIZE_0 + 1
   PK%I%IP%XWTD=> PK%XBLOCK_0(:,ISIZE_0)
!
END IF
!
IF (I%O%CISBA=='DIF'.AND.I%O%CRUNOFF=='SGH') THEN
!
  ISIZE_GROUND = ISIZE_GROUND + 1
  PK%I%I%XTOPQS => PK%XBLOCK_GROUND(:,:,ISIZE_GROUND:ISIZE_GROUND)
!  
ELSE
!
  ISIZE_01 = ISIZE_01 + 1
  PK%I%I%XTOPQS   => PK%XBLOCK_01(:,:,ISIZE_01:ISIZE_01)
!   
END IF
!
IF (I%O%LTR_ML) THEN
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
  PK%I%R%XFAPARC => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
  PK%I%R%XFAPIRC => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
  PK%I%R%XLAI_EFFC => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
  PK%I%R%XMUS => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE)  
ELSE
  ISIZE_0 = ISIZE_0 + 1
  PK%I%R%XFAPARC => PK%XBLOCK_0(:,ISIZE_0:ISIZE_0)
  ISIZE_0 = ISIZE_0 + 1
  PK%I%R%XFAPIRC => PK%XBLOCK_0(:,ISIZE_0:ISIZE_0)
  ISIZE_0 = ISIZE_0 + 1
  PK%I%R%XLAI_EFFC => PK%XBLOCK_0(:,ISIZE_0:ISIZE_0)
  ISIZE_0 = ISIZE_0 + 1
  PK%I%R%XMUS => PK%XBLOCK_0(:,ISIZE_0:ISIZE_0)
ENDIF
!
IF (I%O%CPHOTO=='NON') THEN
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
   PK%I%M%T%XRSMIN      => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE)
ELSE
  ISIZE_0 = ISIZE_0 + 1
  PK%I%M%T%XRSMIN      => PK%XBLOCK_0(:,ISIZE_0:ISIZE_0)
END IF
!
IF (I%O%CPHOTO/='NON' .OR. I%O%LMEB_PATCH(KPATCH)) THEN
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
   PK%I%M%T%XBSLAI      => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE)
ELSE
  ISIZE_0 = ISIZE_0 + 1
  PK%I%M%T%XBSLAI      => PK%XBLOCK_0(:,ISIZE_0:ISIZE_0)
ENDIF
!
IF (I%O%CPHOTO/='NON'.OR.LTREEDRAG) THEN
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
  PK%I%M%X%XH_TREE     => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE)
ELSE
  ISIZE_0 = ISIZE_0 + 1
  PK%I%M%X%XH_TREE     => PK%XBLOCK_0(:,ISIZE_0:ISIZE_0)       
ENDIF
!
IF (I%O%CPHOTO/='NON') THEN
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
   PK%I%M%T%XLAIMIN     => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
   PK%I%M%T%XSEFOLD     => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
   PK%I%IP%XANMAX      => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
   PK%I%IP%XFZERO      => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
   PK%I%IP%XEPSO       => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
   PK%I%IP%XGAMM       => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
   PK%I%IP%XQDGAMM     => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
   PK%I%M%T%XGMES       => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
   PK%I%M%X%XRE25       => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
   PK%I%IP%XQDGMES     => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
   PK%I%IP%XT1GMES     => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
   PK%I%IP%XT2GMES     => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
   PK%I%IP%XAMAX       => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
   PK%I%IP%XQDAMAX     => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
   PK%I%IP%XT1AMAX     => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
   PK%I%IP%XT2AMAX     => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
   PK%I%R%XAN         => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE) 
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
   PK%I%R%XANDAY      => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE) 
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
   PK%I%R%XANFM       => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE) 
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
   PK%I%M%T%XGC         => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE)
  ISIZE_BIOMASS = ISIZE_BIOMASS + 1
  PK%I%R%XBIOMASS        => PK%XBLOCK_BIOMASS(:,:,ISIZE_BIOMASS:ISIZE_BIOMASS)
  ISIZE_BIOMASS = ISIZE_BIOMASS + 1 
  PK%I%R%XRESP_BIOMASS   => PK%XBLOCK_BIOMASS(:,:,ISIZE_BIOMASS:ISIZE_BIOMASS)
ELSE
  ISIZE_0 = ISIZE_0 + 1
  PK%I%M%T%XLAIMIN     => PK%XBLOCK_0(:,ISIZE_0:ISIZE_0)
  ISIZE_0 = ISIZE_0 + 1
  PK%I%M%T%XSEFOLD     => PK%XBLOCK_0(:,ISIZE_0:ISIZE_0)
  ISIZE_0 = ISIZE_0 + 1
  PK%I%IP%XANMAX      => PK%XBLOCK_0(:,ISIZE_0:ISIZE_0)
  ISIZE_0 = ISIZE_0 + 1
  PK%I%IP%XFZERO      => PK%XBLOCK_0(:,ISIZE_0:ISIZE_0)
  ISIZE_0 = ISIZE_0 + 1
  PK%I%IP%XEPSO       => PK%XBLOCK_0(:,ISIZE_0:ISIZE_0)
  ISIZE_0 = ISIZE_0 + 1
  PK%I%IP%XGAMM       => PK%XBLOCK_0(:,ISIZE_0:ISIZE_0)
  ISIZE_0 = ISIZE_0 + 1
  PK%I%IP%XQDGAMM     => PK%XBLOCK_0(:,ISIZE_0:ISIZE_0)
  ISIZE_0 = ISIZE_0 + 1
  PK%I%M%T%XGMES       => PK%XBLOCK_0(:,ISIZE_0:ISIZE_0)
  ISIZE_0 = ISIZE_0 + 1
  PK%I%M%X%XRE25       => PK%XBLOCK_0(:,ISIZE_0:ISIZE_0)
  ISIZE_0 = ISIZE_0 + 1
  PK%I%IP%XQDGMES     => PK%XBLOCK_0(:,ISIZE_0:ISIZE_0)
  ISIZE_0 = ISIZE_0 + 1
  PK%I%IP%XT1GMES     => PK%XBLOCK_0(:,ISIZE_0:ISIZE_0)
  ISIZE_0 = ISIZE_0 + 1
  PK%I%IP%XT2GMES     => PK%XBLOCK_0(:,ISIZE_0:ISIZE_0)
  ISIZE_0 = ISIZE_0 + 1
  PK%I%IP%XAMAX       => PK%XBLOCK_0(:,ISIZE_0:ISIZE_0)
  ISIZE_0 = ISIZE_0 + 1
  PK%I%IP%XQDAMAX     => PK%XBLOCK_0(:,ISIZE_0:ISIZE_0)
  ISIZE_0 = ISIZE_0 + 1
  PK%I%IP%XT1AMAX     => PK%XBLOCK_0(:,ISIZE_0:ISIZE_0)
  ISIZE_0 = ISIZE_0 + 1
  PK%I%IP%XT2AMAX     => PK%XBLOCK_0(:,ISIZE_0:ISIZE_0)
  ISIZE_0 = ISIZE_0 + 1
  PK%I%R%XAN         => PK%XBLOCK_0(:,ISIZE_0:ISIZE_0)
  ISIZE_0 = ISIZE_0 + 1
  PK%I%R%XANDAY      => PK%XBLOCK_0(:,ISIZE_0:ISIZE_0)
  ISIZE_0 = ISIZE_0 + 1
  PK%I%R%XANFM       => PK%XBLOCK_0(:,ISIZE_0:ISIZE_0)
  ISIZE_0 = ISIZE_0 + 1
  PK%I%M%T%XGC         => PK%XBLOCK_0(:,ISIZE_0:ISIZE_0)
  ISIZE_00 = ISIZE_00 + 1
  PK%I%R%XBIOMASS        => PK%XBLOCK_00(:,:,ISIZE_00:ISIZE_00)
  ISIZE_00 = ISIZE_00 + 1
  PK%I%R%XRESP_BIOMASS   => PK%XBLOCK_00(:,:,ISIZE_00:ISIZE_00)
END IF
!
IF (I%O%CPHOTO=='AST' .OR. I%O%CPHOTO=='LST' .OR. I%O%CPHOTO=='NIT' .OR. I%O%CPHOTO=='NCB') THEN
  ISIZE_LSIMPLE = ISIZE_LSIMPLE + 1
  PK%I%M%T%LSTRESS     => PK%LBLOCK_SIMPLE(:,ISIZE_LSIMPLE:ISIZE_LSIMPLE)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
   PK%I%M%T%XF2I        => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
   PK%I%IP%XAH         => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
   PK%I%IP%XBH         => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
   PK%I%M%X%XDMAX       => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE)
ELSE
  ISIZE_L0 = ISIZE_L0 + 1
  PK%I%M%T%LSTRESS     => PK%LBLOCK_0(:,ISIZE_L0:ISIZE_L0)
  ISIZE_0 = ISIZE_0 + 1
  PK%I%M%T%XF2I        => PK%XBLOCK_0(:,ISIZE_0:ISIZE_0)
  ISIZE_0 = ISIZE_0 + 1
  PK%I%IP%XAH         => PK%XBLOCK_0(:,ISIZE_0:ISIZE_0)
  ISIZE_0 = ISIZE_0 + 1
  PK%I%IP%XBH         => PK%XBLOCK_0(:,ISIZE_0:ISIZE_0)
  ISIZE_0 = ISIZE_0 + 1
  PK%I%M%X%XDMAX       => PK%XBLOCK_0(:,ISIZE_0:ISIZE_0)
END IF
!
IF (LAGRIP .AND. (I%O%CPHOTO=='LAI' .OR. I%O%CPHOTO=='LST' .OR. I%O%CPHOTO=='NIT' .OR. I%O%CPHOTO=='NCB')) THEN
  ISIZE_TSIMPLE = ISIZE_TSIMPLE + 1
  PK%I%M%I%TSEED           => PK%TBLOCK_SIMPLE(:,ISIZE_TSIMPLE:ISIZE_TSIMPLE)
  ISIZE_TSIMPLE = ISIZE_TSIMPLE + 1
  PK%I%M%I%TREAP           => PK%TBLOCK_SIMPLE(:,ISIZE_TSIMPLE:ISIZE_TSIMPLE)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
   PK%I%M%I%XIRRIG          => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
   PK%I%M%I%XWATSUP         => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE)
  ISIZE_LSIMPLE = ISIZE_LSIMPLE + 1
   PK%AG%LIRRIDAY       => PK%LBLOCK_SIMPLE(:,ISIZE_LSIMPLE:ISIZE_LSIMPLE)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
   PK%AG%XTHRESHOLDSPT      => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE)
  ISIZE_LSIMPLE = ISIZE_LSIMPLE + 1
   PK%AG%LIRRIGATE      => PK%LBLOCK_SIMPLE(:,ISIZE_LSIMPLE:ISIZE_LSIMPLE)
ELSE
  ISIZE_T0 = ISIZE_T0 + 1
  PK%I%M%I%TSEED           => PK%TBLOCK_0(:,ISIZE_T0:ISIZE_T0)
  ISIZE_T0 = ISIZE_T0 + 1
  PK%I%M%I%TREAP           => PK%TBLOCK_0(:,ISIZE_T0:ISIZE_T0)
  ISIZE_0 = ISIZE_0 + 1
  PK%I%M%I%XIRRIG          => PK%XBLOCK_0(:,ISIZE_0:ISIZE_0)
  ISIZE_0 = ISIZE_0 + 1
  PK%I%M%I%XWATSUP         => PK%XBLOCK_0(:,ISIZE_0:ISIZE_0)
  ISIZE_L0 = ISIZE_L0 + 1
  PK%AG%LIRRIDAY       => PK%LBLOCK_0(:,ISIZE_L0:ISIZE_L0)
  ISIZE_0 = ISIZE_0 + 1
  PK%AG%XTHRESHOLDSPT   => PK%XBLOCK_0(:,ISIZE_0:ISIZE_0)
  ISIZE_L0 = ISIZE_L0 + 1
  PK%AG%LIRRIGATE      => PK%LBLOCK_0(:,ISIZE_L0:ISIZE_L0)
ENDIF
!
IF(I%O%CPHOTO=='NIT' .OR. I%O%CPHOTO=='NCB') THEN
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
   PK%I%M%T%XCE_NITRO       => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
   PK%I%M%T%XCF_NITRO       => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
   PK%I%M%T%XCNA_NITRO      => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
   PK%I%IP%XBSLAI_NITRO    => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE)
ELSE
  ISIZE_0 = ISIZE_0 + 1
  PK%I%M%T%XCE_NITRO       => PK%XBLOCK_0(:,ISIZE_0:ISIZE_0)
  ISIZE_0 = ISIZE_0 + 1
  PK%I%M%T%XCF_NITRO       => PK%XBLOCK_0(:,ISIZE_0:ISIZE_0)
  ISIZE_0 = ISIZE_0 + 1
  PK%I%M%T%XCNA_NITRO      => PK%XBLOCK_0(:,ISIZE_0:ISIZE_0)
  ISIZE_0 = ISIZE_0 + 1
  PK%I%IP%XBSLAI_NITRO    => PK%XBLOCK_0(:,ISIZE_0:ISIZE_0)
END IF
!
IF (I%O%CPHOTO=='NCB') THEN
  ISIZE_BIOMASS = ISIZE_BIOMASS + 1
  PK%I%IP%XINCREASE     => PK%XBLOCK_BIOMASS(:,:,ISIZE_BIOMASS:ISIZE_BIOMASS)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
   PK%I%IP%XTAU_WOOD     => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE)  
ELSE
  ISIZE_00 = ISIZE_00 + 1
  PK%I%IP%XINCREASE     => PK%XBLOCK_00(:,:,ISIZE_00:ISIZE_00)
  ISIZE_0 = ISIZE_0 + 1
  PK%I%IP%XTAU_WOOD     => PK%XBLOCK_0(:,ISIZE_0:ISIZE_0)
ENDIF
!
IF (I%O%CRESPSL=='CNT') THEN
  ISIZE_LITTER = ISIZE_LITTER + 1
  PK%I%R%XLITTER         => PK%XBLOCK_LITTER(:,:,:,ISIZE_LITTER:ISIZE_LITTER)
  ISIZE_SOILCARB = ISIZE_SOILCARB + 1
  PK%I%R%XSOILCARB       => PK%XBLOCK_SOILCARB(:,:,ISIZE_SOILCARB:ISIZE_SOILCARB)
  ISIZE_LITTLEVS = ISIZE_LITTLEVS + 1
  PK%I%R%XLIGNIN_STRUC   => PK%XBLOCK_LITTLEVS(:,:,ISIZE_LITTLEVS:ISIZE_LITTLEVS)
  ISIZE_BIOMASS = ISIZE_BIOMASS + 1
  PK%I%IP%XTURNOVER       => PK%XBLOCK_BIOMASS(:,:,ISIZE_BIOMASS:ISIZE_BIOMASS)
ELSE
  ISIZE_000 = ISIZE_000 + 1
  PK%I%R%XLITTER         => PK%XBLOCK_000(:,:,:,ISIZE_000:ISIZE_000)
  ISIZE_00 = ISIZE_00 + 1
  PK%I%R%XSOILCARB       => PK%XBLOCK_00(:,:,ISIZE_00:ISIZE_00)
  ISIZE_00 = ISIZE_00 + 1
  PK%I%R%XLIGNIN_STRUC   => PK%XBLOCK_00(:,:,ISIZE_00:ISIZE_00)
  ISIZE_00 = ISIZE_00 + 1
  PK%I%IP%XTURNOVER       => PK%XBLOCK_00(:,:,ISIZE_00:ISIZE_00)
END IF
!
IF (I%O%CRAIN=='SGH')THEN
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
   PK%I%I%XMUF => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
ELSE
  ISIZE_0 = ISIZE_0 + 1
  PK%I%I%XMUF=> PK%XBLOCK_0(:,ISIZE_0)
ENDIF
!
! MEB STUFF START
!
! Note that here the understory ground vegetation (GV) that was part of the original
! MEB development has been eliminated. The reason is to avoid a composite
! of vegetation and soil. Thus, most varibales with old extension V
! (representing canopy vegetation) are now unassociated. Instead, the classical ISBA
! variables (e.g. RGL, GAMMA, ...) will represent a composite vegetation in the
! MEB case. We still keep the GV-variables in the system for future needs.
! Code is commented with "nogv" in appropriate places.
!
IF (I%O%LMEB_PATCH(KPATCH))THEN
!
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
  PK%I%R%XWRL         => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
  PK%I%R%XWRLI         => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
  PK%I%R%XWRVN        => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
  PK%I%R%XTV          => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
  PK%I%R%XTL          => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
  PK%I%R%XTC          => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
  PK%I%R%XQC          => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE)
!nogv  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
!nogv  XP_RSMINV      => XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
  PK%I%M%M%XH_VEG       => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE)
!nogv  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
!nogv  XP_RGLV        => XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE)
!nogv  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
!nogv  XP_GAMMAV      => XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE)
!nogv  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
!nogv  XP_WRMAX_CFV   => XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE)
!nogv  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
!nogv  XP_LAIV        => XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE)
!nogv  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
!nogv  XP_Z0V         => XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
  PK%I%M%M%XGNDLITTER   => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
  PK%I%M%M%XZ0LITTER    => PK%XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE)
!
!nogv  ISIZE_GROUND = ISIZE_GROUND + 1
!nogv  XP_ROOTFRACV   => XBLOCK_GROUND(:,:,ISIZE_GROUND:ISIZE_GROUND)  
ELSE
  ISIZE_0 = ISIZE_0 + 1
  PK%I%R%XWRL         => PK%XBLOCK_0(:,ISIZE_0:ISIZE_0)
  ISIZE_0 = ISIZE_0 + 1
  PK%I%R%XWRLI         => PK%XBLOCK_0(:,ISIZE_0:ISIZE_0)
  ISIZE_0 = ISIZE_0 + 1
  PK%I%R%XWRVN        => PK%XBLOCK_0(:,ISIZE_0:ISIZE_0)
  ISIZE_0 = ISIZE_0 + 1
  PK%I%R%XTV          => PK%XBLOCK_0(:,ISIZE_0:ISIZE_0)
  ISIZE_0 = ISIZE_0 + 1
  PK%I%R%XTL          => PK%XBLOCK_0(:,ISIZE_0:ISIZE_0)
  ISIZE_0 = ISIZE_0 + 1
  PK%I%R%XTC          => PK%XBLOCK_0(:,ISIZE_0:ISIZE_0)
  ISIZE_0 = ISIZE_0 + 1
  PK%I%R%XQC          => PK%XBLOCK_0(:,ISIZE_0:ISIZE_0)
!nogv  ISIZE_0 = ISIZE_0 + 1
!nogv  XP_RSMINV      => XBLOCK_0(:,ISIZE_0:ISIZE_0)
  ISIZE_0 = ISIZE_0 + 1
  PK%I%M%M%XH_VEG       => PK%XBLOCK_0(:,ISIZE_0:ISIZE_0)
!nogv  ISIZE_0 = ISIZE_0 + 1
!nogv  XP_RGLV        => XBLOCK_0(:,ISIZE_0:ISIZE_0)
!nogv  ISIZE_0 = ISIZE_0 + 1
!nogv  XP_GAMMAV      => XBLOCK_0(:,ISIZE_0:ISIZE_0)
!nogv  ISIZE_0 = ISIZE_0 + 1
!nogv  XP_WRMAX_CFV   => XBLOCK_0(:,ISIZE_0:ISIZE_0)
!nogv  ISIZE_0 = ISIZE_0 + 1
!nogv  XP_LAIV        => XBLOCK_0(:,ISIZE_0:ISIZE_0)
!nogv  ISIZE_0 = ISIZE_0 + 1
!nogv  XP_Z0V         => XBLOCK_0(:,ISIZE_0:ISIZE_0)
  ISIZE_0 = ISIZE_0 + 1
  PK%I%M%M%XGNDLITTER   => PK%XBLOCK_0(:,ISIZE_0:ISIZE_0)
  ISIZE_0 = ISIZE_0 + 1
  PK%I%M%M%XZ0LITTER    => PK%XBLOCK_0(:,ISIZE_0:ISIZE_0)
!
!nogv  ISIZE_01 = ISIZE_01 + 1
!nogv  XP_ROOTFRACV   => XBLOCK_01(:,:,ISIZE_01:ISIZE_01)
ENDIF
ISIZE_0 = ISIZE_0 + 1
PK%I%M%M%XRSMINGV      => PK%XBLOCK_0(:,ISIZE_0:ISIZE_0)
ISIZE_0 = ISIZE_0 + 1
PK%I%M%M%XRGLGV        => PK%XBLOCK_0(:,ISIZE_0:ISIZE_0)
ISIZE_0 = ISIZE_0 + 1
PK%I%M%M%XGAMMAGV      => PK%XBLOCK_0(:,ISIZE_0:ISIZE_0)
ISIZE_0 = ISIZE_0 + 1
PK%I%M%M%XWRMAX_CFGV   => PK%XBLOCK_0(:,ISIZE_0:ISIZE_0)
ISIZE_0 = ISIZE_0 + 1
PK%I%M%M%XLAIGV        => PK%XBLOCK_0(:,ISIZE_0:ISIZE_0)
ISIZE_0 = ISIZE_0 + 1
PK%I%M%M%XZ0GV         => PK%XBLOCK_0(:,ISIZE_0:ISIZE_0)
ISIZE_01 = ISIZE_01 + 1
PK%I%M%M%XROOTFRACGV   => PK%XBLOCK_01(:,:,ISIZE_01:ISIZE_01)
! MEB STUFF END
!
!
IF (ISIZE_SIMPLE.GT.PK%NSIZE_SIMPLE) &
  CALL ABOR1_SFX("PACK_ISBA_PATCH_n: PROBLEM DEFINING SIZE_SIMPLE / NUMBER OF FIELDS")
IF (ISIZE_GROUND.GT.PK%NSIZE_GROUND) &
  CALL ABOR1_SFX("PACK_ISBA_PATCH_n: PROBLEM DEFINING SIZE_GROUND / NUMBER OF FIELDS")
IF (ISIZE_VEGTYPE.GT.PK%NSIZE_VEGTYPE) &
  CALL ABOR1_SFX("PACK_ISBA_PATCH_n: PROBLEM DEFINING SIZE_VEGTYPE / NUMBER OF FIELDS")
IF (ISIZE_TG.GT.PK%NSIZE_TG) &
  CALL ABOR1_SFX("PACK_ISBA_PATCH_n: PROBLEM DEFINING SIZE_TG / NUMBER OF FIELDS")
IF (ISIZE_SNOW.GT.PK%NSIZE_SNOW) &
  CALL ABOR1_SFX("PACK_ISBA_PATCH_n: PROBLEM DEFINING SIZE_SNOW / NUMBER OF FIELDS")
IF (ISIZE_ALB.GT.PK%NSIZE_ALB) &
  CALL ABOR1_SFX("PACK_ISBA_PATCH_n: PROBLEM DEFINING SIZE_ALB / NUMBER OF FIELDS")
IF (ISIZE_0.GT.PK%NSIZE_0) &
  CALL ABOR1_SFX("PACK_ISBA_PATCH_n: PROBLEM DEFINING SIZE_0 / NUMBER OF FIELDS")
IF (ISIZE_00.GT.PK%NSIZE_00) &
  CALL ABOR1_SFX("PACK_ISBA_PATCH_n: PROBLEM DEFINING SIZE_00 / NUMBER OF FIELDS")
IF (ISIZE_01.GT.PK%NSIZE_01) &
  CALL ABOR1_SFX("PACK_ISBA_PATCH_n: PROBLEM DEFINING SIZE_01 / NUMBER OF FIELDS")
IF (ISIZE_2.GT.PK%NSIZE_2) &
  CALL ABOR1_SFX("PACK_ISBA_PATCH_n: PROBLEM DEFINING SIZE_2 / NUMBER OF FIELDS")
IF (ISIZE_BIOMASS.GT.PK%NSIZE_BIOMASS) &
  CALL ABOR1_SFX("PACK_ISBA_PATCH_n: PROBLEM DEFINING SIZE_BIOMASS / NUMBER OF FIELDS")
IF (ISIZE_LITTER.GT.PK%NSIZE_LITTER) &
  CALL ABOR1_SFX("PACK_ISBA_PATCH_n: PROBLEM DEFINING SIZE_LITTER / NUMBER OF FIELDS")
IF (ISIZE_SOILCARB.GT.PK%NSIZE_SOILCARB) &
  CALL ABOR1_SFX("PACK_ISBA_PATCH_n: PROBLEM DEFINING SIZE_SOILCARB / NUMBER OF FIELDS")
IF (ISIZE_LITTLEVS.GT.PK%NSIZE_LITTLEVS) &
  CALL ABOR1_SFX("PACK_ISBA_PATCH_n: PROBLEM DEFINING SIZE_LITTLEVS / NUMBER OF FIELDS")
IF (ISIZE_000.GT.PK%NSIZE_000) &
  CALL ABOR1_SFX("PACK_ISBA_PATCH_n: PROBLEM DEFINING SIZE_000 / NUMBER OF FIELDS")
IF (ISIZE_TSIMPLE.GT.PK%NSIZE_TSIMPLE) &
  CALL ABOR1_SFX("PACK_ISBA_PATCH_n: PROBLEM DEFINING SIZE_TSIMPLE / NUMBER OF FIELDS")
IF (ISIZE_T0.GT.PK%NSIZE_T0) &
  CALL ABOR1_SFX("PACK_ISBA_PATCH_n: PROBLEM DEFINING SIZE_T0 / NUMBER OF FIELDS")
IF (ISIZE_LSIMPLE.GT.PK%NSIZE_LSIMPLE) &
  CALL ABOR1_SFX("PACK_ISBA_PATCH_n: PROBLEM DEFINING SIZE_LSIMPLE / NUMBER OF FIELDS")
IF (ISIZE_L0.GT.PK%NSIZE_L0) &
  CALL ABOR1_SFX("PACK_ISBA_PATCH_n: PROBLEM DEFINING SIZE_L0 / NUMBER OF FIELDS")
IF (ISIZE_N0.GT.PK%NSIZE_N0) &
  CALL ABOR1_SFX("PACK_ISBA_PATCH_n: PROBLEM DEFINING SIZE_N0 / NUMBER OF FIELDS")  
!
!------------------------------------------------------------------------
!
IF (I%O%NPATCH==1) THEN
  !
  !PK%I = I
  PK%I%M%X%XZ0_O_Z0H     (:,1)    =    I%M%X%XZ0_O_Z0H     (:, 1)
  PK%I%M%T%XEMIS         (:,1)    =    I%M%T%XEMIS         (:, 1)
  PK%I%M%T%XALBNIR       (:,1)    =    I%M%T%XALBNIR       (:, 1)
  PK%I%M%T%XALBVIS       (:,1)    =    I%M%T%XALBVIS       (:, 1)
  PK%I%M%T%XALBUV        (:,1)    =    I%M%T%XALBUV        (:, 1)
  PK%I%M%T%XALBNIR_VEG   (:,1)    =    I%M%T%XALBNIR_VEG   (:, 1)
  PK%I%M%T%XALBVIS_VEG   (:,1)    =    I%M%T%XALBVIS_VEG   (:, 1)
  PK%I%M%T%XALBUV_VEG    (:,1)    =    I%M%T%XALBUV_VEG    (:, 1)
  PK%I%M%A%XALBNIR_SOIL  (:,1)    =    I%M%A%XALBNIR_SOIL  (:, 1)
  PK%I%M%A%XALBVIS_SOIL  (:,1)    =    I%M%A%XALBVIS_SOIL  (:, 1)
  PK%I%M%A%XALBUV_SOIL   (:,1)    =    I%M%A%XALBUV_SOIL   (:, 1)
  PK%I%M%T%XZ0           (:,1)    =    I%M%T%XZ0           (:, 1)
  PK%I%M%T%XWRMAX_CF     (:,1)    =    I%M%T%XWRMAX_CF     (:, 1)
  PK%I%M%T%XGAMMA        (:,1)    =    I%M%T%XGAMMA        (:, 1)
  PK%I%M%T%XCV           (:,1)    =    I%M%T%XCV           (:, 1)
  PK%I%M%T%XRGL          (:,1)    =    I%M%T%XRGL          (:, 1)
  PK%I%IP%XRUNOFFD      (:,1)    =    I%IP%XRUNOFFD      (:, 1) 
  PK%I%IP%XZ0EFFIP      (:,1)    =    I%IP%XZ0EFFIP      (:, 1)
  PK%I%IP%XZ0EFFIM      (:,1)    =    I%IP%XZ0EFFIM      (:, 1)
  PK%I%IP%XZ0EFFJP      (:,1)    =    I%IP%XZ0EFFJP      (:, 1)
  PK%I%IP%XZ0EFFJM      (:,1)    =    I%IP%XZ0EFFJM      (:, 1)  
  PK%I%R%XWR           (:,1)    =    I%R%XWR           (:, 1)   
  PK%I%M%T%XLAI          (:,1)    =    I%M%T%XLAI          (:, 1) 
  PK%I%R%XRESA         (:,1)    =    I%R%XRESA         (:, 1)
  PK%I%IP%XPCPS          (:,1)    =    I%IP%XPCPS         (:, 1)
  PK%I%IP%XPLVTT         (:,1)    =    I%IP%XPLVTT        (:, 1)
  PK%I%IP%XPLSTT         (:,1)    =    I%IP%XPLSTT        (:, 1) 
  PK%I%M%T%XVEG          (:,1)    =    I%M%T%XVEG          (:, 1)  
  PK%I%R%TSNOW%ALB      (:,1)    =    I%R%TSNOW%ALB     (:, 1) 
  PK%I%R%XLE           (:,1)    =    I%R%XLE           (:, 1)  
  PK%I%R%XPSN          (:,1)    =    I%R%XPSN          (:, 1)
  PK%I%R%XPSNG         (:,1)    =    I%R%XPSNG         (:, 1)
  PK%I%R%XPSNV         (:,1)    =    I%R%XPSNV         (:, 1)  
  PK%I%IP%XALBNIR_DRY   (:)    =    I%IP%XALBNIR_DRY   (:)
  PK%I%IP%XALBVIS_DRY   (:)    =    I%IP%XALBVIS_DRY   (:)
  PK%I%IP%XALBUV_DRY    (:)    =    I%IP%XALBUV_DRY    (:)
  PK%I%IP%XALBNIR_WET   (:)    =    I%IP%XALBNIR_WET   (:)
  PK%I%IP%XALBVIS_WET   (:)    =    I%IP%XALBVIS_WET   (:)
  PK%I%IP%XALBUV_WET    (:)    =    I%IP%XALBUV_WET    (:)  
  PK%I%P%XRUNOFFB      (:)    =    I%P%XRUNOFFB      (:)
  PK%I%P%XWDRAIN       (:)    =    I%P%XWDRAIN       (:)
  PK%I%IP%XTAUICE       (:)    =    I%IP%XTAUICE       (:)
  PK%I%IP%XZ0REL        (:)    =    I%IP%XZ0REL        (:)
  PK%I%P%XAOSIP        (:)    =    I%P%XAOSIP        (:)
  PK%I%P%XAOSIM        (:)    =    I%P%XAOSIM        (:)
  PK%I%P%XAOSJP        (:)    =    I%P%XAOSJP        (:)
  PK%I%P%XAOSJM        (:)    =    I%P%XAOSJM        (:)
  PK%I%P%XHO2IP        (:)    =    I%P%XHO2IP        (:)
  PK%I%P%XHO2IM        (:)    =    I%P%XHO2IM        (:)
  PK%I%P%XHO2JP        (:)    =    I%P%XHO2JP        (:)
  PK%I%P%XHO2JM        (:)    =    I%P%XHO2JM        (:)
  PK%I%P%XSSO_SLOPE    (:)    =    I%P%XSSO_SLOPE    (:)
  PK%I%IP%XGAMMAT       (:)    =    I%IP%XGAMMAT       (:)
  PK%I%IP%XTDEEP        (:)    =    I%IP%XTDEEP        (:)  
  PK%G%XLAT          (:)    =    IG%XLAT          (:)
  PK%G%XLON          (:)    =    IG%XLON          (:)
  !
  PK%I%P%XCLAY         (:,:)  =    I%P%XCLAY         (:, :)
  PK%I%P%XSAND         (:,:)  =    I%P%XSAND         (:, :) 
  PK%I%IP%XWFC          (:, :) =    I%IP%XWFC          (:, :)
  PK%I%IP%XWWILT        (:, :) =    I%IP%XWWILT        (:, :)
  PK%I%IP%XWSAT         (:, :) =    I%IP%XWSAT         (:, :)
  PK%I%IP%XCONDSAT      (:, :, 1) =    I%IP%XCONDSAT      (:, :, 1)  
  PK%I%M%X%XDG           (:, :, 1) =    I%M%X%XDG           (:, :, 1)  
  PK%I%R%XWG           (:, :, 1) =    I%R%XWG           (:, :, 1)
  PK%I%R%XWGI          (:, :, 1) =    I%R%XWGI          (:, :, 1)
  PK%I%IP%XMPOTSAT      (:, :) =    I%IP%XMPOTSAT      (:, :) 
  PK%I%IP%XBCOEF        (:, :) =    I%IP%XBCOEF        (:, :)  
  !
  PK%I%IP%XKSAT_ICE     (:,1)    =    I%IP%XKSAT_ICE     (:, 1)
  PK%I%M%X%XD_ICE        (:,1)    =    I%M%X%XD_ICE        (:, 1)
  !
  PK%I%IP%XVEGTYPE_PATCH(:, :, 1) =    I%IP%XVEGTYPE_PATCH(:, :, 1)  
  !
  PK%I%R%XTG           (:, :, 1) =    I%R%XTG           (:, :, 1)  
  !  
  PK%I%R%TSNOW%WSNOW      (:, :, 1) =    I%R%TSNOW%WSNOW   (:, :, 1)
  PK%I%R%TSNOW%RHO      (:, :, 1) =    I%R%TSNOW%RHO     (:, :, 1)  
  !  
  PK%I%I%XDIR_ALB_WITH_SNOW (:,:, 1)= I%I%XDIR_ALB_WITH_SNOW(:, :, 1)
  PK%I%I%XSCA_ALB_WITH_SNOW (:,:, 1)= I%I%XSCA_ALB_WITH_SNOW(:, :, 1)
  !  
  PK%I%I%XFSAT(:)=I%I%XFSAT(:)
  !
  IF(I%O%LFLOOD)THEN
    PK%I%I%XFFLOOD  (:)=I%I%XFFLOOD  (:)
    PK%I%I%XPIFLOOD (:)=I%I%XPIFLOOD (:)
    PK%I%I%XFF      (:,1)=I%I%XFF      (:, 1)
    PK%I%I%XFFG     (:,1)=I%I%XFFG     (:, 1)
    PK%I%I%XFFV     (:,1)=I%I%XFFV     (:, 1)    
    PK%I%I%XFFROZEN (:,1)=I%I%XFFROZEN (:, 1)    
    PK%I%I%XALBF    (:,1)=I%I%XALBF    (:, 1)
    PK%I%I%XEMISF   (:,1)=I%I%XEMISF   (:, 1)
  ELSE
    PK%I%I%XFFLOOD  (:)= 0.0
    PK%I%I%XPIFLOOD (:)= 0.0
    PK%I%I%XFF      (:,1)= 0.0
    PK%I%I%XFFG     (:,1)= 0.0
    PK%I%I%XFFV     (:,1)= 0.0
    PK%I%I%XFFROZEN (:,1)= 0.0   
    PK%I%I%XALBF    (:,1)= 0.0
    PK%I%I%XEMISF   (:,1)= 0.0    
  ENDIF
  !
  IF(I%R%TSNOW%SCHEME=='EBA') THEN
    PK%I%R%XPSNV_A (:,1)    = I%R%XPSNV_A(:, 1)
  ENDIF
  !
  IF (I%R%TSNOW%SCHEME=='3-L' .OR. I%R%TSNOW%SCHEME=='CRO') THEN
    PK%I%R%TSNOW%HEAT   (:,:,1) =    I%R%TSNOW%HEAT  (:,:,1)
    PK%I%R%TSNOW%AGE    (:,:,1) =    I%R%TSNOW%AGE   (:,:,1)  
    PK%I%R%TSNOW%ALBVIS   (:,1)    =    I%R%TSNOW%ALBVIS  (:, 1) 
    PK%I%R%TSNOW%ALBNIR   (:,1)    =    I%R%TSNOW%ALBNIR  (:, 1) 
    PK%I%R%TSNOW%ALBFIR   (:,1)    =    I%R%TSNOW%ALBFIR  (:, 1) 
  END IF
  !
  IF(I%R%TSNOW%SCHEME=='CRO') THEN
    PK%I%R%TSNOW%GRAN1  (:,:,1) =     I%R%TSNOW%GRAN1  (:,:,1)
    PK%I%R%TSNOW%GRAN2  (:,:,1) =     I%R%TSNOW%GRAN2  (:,:,1)
    PK%I%R%TSNOW%HIST   (:,:,1) =     I%R%TSNOW%HIST   (:,:,1)  
  END IF
  !
  IF(I%O%LGLACIER)THEN
    PK%I%R%XICE_STO (:,1)= I%R%XICE_STO  (:,1)
  ENDIF
  !  
  IF (I%O%CSCOND=='PL98'.OR.I%O%CISBA=='DIF') THEN
    PK%I%IP%XHCAPSOIL(:, :) = I%IP%XHCAPSOIL    (:, :)
    PK%I%IP%XCONDDRY (:, :) = I%IP%XCONDDRY     (:, :)
    PK%I%IP%XCONDSLD (:, :) = I%IP%XCONDSLD     (:, :)    
  END IF
  !
  IF (I%O%CISBA=='2-L' .OR. I%O%CISBA=='3-L') THEN
    PK%I%IP%XC4B        (:)    =    I%IP%XC4B          (:)
    PK%I%IP%XACOEF      (:)    =    I%IP%XACOEF        (:)
    PK%I%IP%XPCOEF      (:)    =    I%IP%XPCOEF        (:)
    PK%I%IP%XCGSAT      (:)    =    I%IP%XCGSAT        (:) 
    PK%I%IP%XC1SAT      (:,1)    =    I%IP%XC1SAT        (:, 1)
    PK%I%IP%XC2REF      (:,1)    =    I%IP%XC2REF        (:, 1)    
    PK%I%IP%XC4REF      (:,1)    =    I%IP%XC4REF        (:, 1)    
    PK%I%IP%XC3         (:,:,1)  =    I%IP%XC3           (:,:,1)    
  END IF
  !
  IF (I%O%CISBA=='DIF') THEN
    PK%I%M%X%XROOTFRAC   (:, :,1) =    I%M%X%XROOTFRAC   (:, :, 1)
    PK%I%IP%XDZG        (:, :,1) =    I%IP%XDZG        (:, :, 1)
    PK%I%IP%XDZDIF      (:, :,1) =    I%IP%XDZDIF      (:, :, 1)
    PK%I%IP%XSOILWGHT   (:, :,1) =    I%IP%XSOILWGHT   (:, :, 1)
    PK%I%M%X%NWG_LAYER   (: ,1) =    I%M%X%NWG_LAYER   (:,    1)
    PK%I%IP%XFWTD       (:   ) =    I%IP%XFWTD       (:)
    PK%I%IP%XWTD        (:   ) =    I%IP%XWTD        (:)
  END IF
  !
  IF (I%O%CISBA=='DIF'.AND.I%O%CRUNOFF=='SGH') THEN
    PK%I%I%XTOPQS   (:, :,1) =    I%I%XTOPQS   (:, :, 1)
  END IF
  !
  IF (I%O%LTR_ML) THEN
    PK%I%R%XFAPARC     (:,1)   =     I%R%XFAPARC     (:, 1)
    PK%I%R%XFAPIRC     (:,1)   =     I%R%XFAPIRC     (:, 1)
    PK%I%R%XLAI_EFFC   (:,1)   =     I%R%XLAI_EFFC   (:, 1)
    PK%I%R%XMUS        (:,1)   =     I%R%XMUS        (:, 1)
  ENDIF
  !  
  IF (I%O%CPHOTO=='NON') THEN
    PK%I%M%T%XRSMIN      (:,1)    =    I%M%T%XRSMIN      (:, 1) 
  END IF
!!
!! For multi-energy balance (MEB):
!!
!! Note that here the understory ground vegetation (GV) that was part of the original
!! MEB development has been eliminated. The reason is to avoid a composite
!! of vegetation and soil. Thus, most varibales with old extension V
!! (representing canopy vegetation) are now unassociated. Instead, the classical ISBA
!! variables (e.g. RGL, GAMMA, ...) will represent a composite vegetation in the
!! MEB case. We still keep the GV-variables in the system for future needs.
!! Code is commented with "nogv" in appropriate places.
!!
  IF(I%O%LMEB_PATCH(1))THEN
!
    PK%I%R%XWRL          (:,1)    =    I%R%XWRL          (:, 1) 
    PK%I%R%XWRLI         (:,1)    =    I%R%XWRLI         (:, 1) 
    PK%I%R%XWRVN         (:,1)    =    I%R%XWRVN         (:, 1) 
    PK%I%R%XTV           (:,1)    =    I%R%XTV           (:, 1) 
    PK%I%R%XTL           (:,1)    =    I%R%XTL           (:, 1) 
    PK%I%R%XTC           (:,1)    =    I%R%XTC           (:, 1) 
    PK%I%R%XQC           (:,1)    =    I%R%XQC           (:, 1) 
!
! Please note that secondary Ecoclimap parameters, i.e. those
! with postfix GV, are given to the corresponing original ISBA physiography
! parameters in the case of LMEB_PATCH/OMEB=true. And the original ISBA
! physiography parameters are given to the canopy vegetation parameters.
! E.g. XLAI -> XP_LAIV and XLAIGV -> XP_LAI
!
!nogv    IF (CISBA=='DIF') THEN
!nogv      XP_ROOTFRACV         =  XP_ROOTFRAC
!nogv      XP_ROOTFRAC   (:, :) =  XROOTFRACGV   (:, :, 1)
!nogv    END IF
!nogv    IF (CPHOTO=='NON') THEN
!nogv      XP_RSMINV        = XP_RSMIN
!nogv      XP_RSMIN  (:)    = XRSMINGV  (:, 1)
!nogv    END IF
!
!nogv    XP_RGLV         (:)    =    XRGL          (:, 1)
!nogv    XP_GAMMAV       (:)    =    XGAMMA        (:, 1)
!nogv    XP_WRMAX_CFV    (:)    =    XWRMAX_CF     (:, 1)
!nogv    XP_LAIV         (:)    =    XLAI          (:, 1)
!nogv    XP_Z0V          (:,1)    =    XZ0           (:, 1)
    PK%I%M%M%XH_VEG        (:,1)    =    I%M%M%XH_VEG        (:, 1)
!
!nogv    XP_VEG          (:,1)    =    XGNDLITTER    (:, 1)
!nogv    XP_RGL          (:,1)    =    XRGLGV        (:, 1)
!nogv    XP_GAMMA        (:,1)    =    XGAMMAGV      (:, 1)
!nogv    XP_WRMAX_CF     (:,1)    =    XWRMAX_CFGV   (:, 1)
!nogv    XP_LAI          (:,1)    =    XLAIGV        (:, 1)
!nogv    XP_Z0           (:,1)    =    XZ0LITTER     (:, 1)
    PK%I%M%M%XGNDLITTER    (:,1)    =    I%M%M%XGNDLITTER    (:, 1)
    PK%I%M%M%XZ0LITTER     (:,1)    =    I%M%M%XZ0LITTER     (:, 1)
  ENDIF
!
  IF(I%O%CPHOTO/='NON' .OR. I%O%LMEB_PATCH(1))THEN
    PK%I%M%T%XBSLAI      (:,1)    =    I%M%T%XBSLAI      (:, 1)
  ENDIF
!
  IF (I%O%CPHOTO/='NON') THEN
    PK%I%M%T%XLAIMIN     (:,1)    =    I%M%T%XLAIMIN     (:, 1)
    PK%I%M%T%XSEFOLD     (:,1)    =    I%M%T%XSEFOLD     (:, 1)
    PK%I%M%X%XH_TREE     (:,1)    =    I%M%X%XH_TREE     (:, 1)
    PK%I%IP%XANMAX      (:,1)    =    I%IP%XANMAX      (:, 1)
    PK%I%IP%XFZERO      (:,1)    =    I%IP%XFZERO      (:, 1)
    PK%I%IP%XEPSO       (:,1)    =    I%IP%XEPSO       (:, 1)
    PK%I%IP%XGAMM       (:,1)    =    I%IP%XGAMM       (:, 1)
    PK%I%IP%XQDGAMM     (:,1)    =    I%IP%XQDGAMM     (:, 1)
    PK%I%M%T%XGMES       (:,1)    =    I%M%T%XGMES       (:, 1)
    PK%I%M%X%XRE25       (:,1)    =    I%M%X%XRE25       (:, 1)
    PK%I%IP%XQDGMES     (:,1)    =    I%IP%XQDGMES     (:, 1)
    PK%I%IP%XT1GMES     (:,1)    =    I%IP%XT1GMES     (:, 1)
    PK%I%IP%XT2GMES     (:,1)    =    I%IP%XT2GMES     (:, 1)
    PK%I%IP%XAMAX       (:,1)    =    I%IP%XAMAX       (:, 1)
    PK%I%IP%XQDAMAX     (:,1)    =    I%IP%XQDAMAX     (:, 1)
    PK%I%IP%XT1AMAX     (:,1)    =    I%IP%XT1AMAX     (:, 1)
    PK%I%IP%XT2AMAX     (:,1)    =    I%IP%XT2AMAX     (:, 1)
    PK%I%R%XAN         (:,1)    =    I%R%XAN         (:, 1) 
    PK%I%R%XANDAY      (:,1)    =    I%R%XANDAY      (:, 1) 
    PK%I%R%XANFM       (:,1)    =    I%R%XANFM       (:, 1) 
    PK%I%M%T%XGC         (:,1)    =    I%M%T%XGC         (:, 1)
    PK%I%R%XBIOMASS        (:,:,1)  =    I%R%XBIOMASS        (:,:,1)
    PK%I%R%XRESP_BIOMASS   (:,:,1)  =    I%R%XRESP_BIOMASS   (:,:,1)
  END IF
  !
  IF (I%O%CPHOTO=='AST' .OR. I%O%CPHOTO=='LST' .OR. I%O%CPHOTO=='NIT' .OR. I%O%CPHOTO=='NCB') THEN  
    PK%I%M%T%LSTRESS     (:,1)    =    I%M%T%LSTRESS     (:, 1)
    PK%I%M%T%XF2I        (:,1)    =    I%M%T%XF2I        (:, 1)
    PK%I%IP%XAH         (:,1)    =    I%IP%XAH         (:, 1)
    PK%I%IP%XBH         (:,1)    =    I%IP%XBH         (:, 1)
    PK%I%M%X%XDMAX       (:,1)    =    I%M%X%XDMAX       (:, 1)
  END IF
  !
  IF(LAGRIP .AND. (I%O%CPHOTO=='LAI' .OR. I%O%CPHOTO=='LST' .OR. I%O%CPHOTO=='NIT' .OR. I%O%CPHOTO=='NCB')) THEN
    PK%I%M%I%TSEED     (:,1) = I%M%I%TSEED     (:,1)
    PK%I%M%I%TREAP     (:,1) = I%M%I%TREAP     (:,1)
    PK%I%M%I%XIRRIG    (:,1) = I%M%I%XIRRIG    (:,1)
    PK%I%M%I%XWATSUP   (:,1) = I%M%I%XWATSUP   (:,1)
    PK%AG%LIRRIDAY (:,1) = AG%LIRRIDAY  (:,1)
    PK%AG%XTHRESHOLDSPT(:,1) = AG%XTHRESHOLDSPT(:,1)
    PK%AG%LIRRIGATE(:,1) = AG%LIRRIGATE (:,1)
  ENDIF
  !  
  IF(I%O%CPHOTO=='NIT' .OR. I%O%CPHOTO=='NCB') THEN 
     PK%I%M%T%XCE_NITRO       (:,1)  =    I%M%T%XCE_NITRO       (:,1)
     PK%I%M%T%XCF_NITRO       (:,1)  =    I%M%T%XCF_NITRO       (:,1)
     PK%I%M%T%XCNA_NITRO      (:,1)  =    I%M%T%XCNA_NITRO      (:,1)
     PK%I%IP%XBSLAI_NITRO    (:,1)    =    I%IP%XBSLAI_NITRO  (:,1)
  END IF
  !
  IF (I%O%CPHOTO=='NCB') THEN
     PK%I%IP%XINCREASE       (:,:,1)  =    I%IP%XINCREASE       (:,:,1)          
     PK%I%IP%XTAU_WOOD       (:,1)    =    I%IP%XTAU_WOOD       (:,1)
  END IF
  !
  IF (I%O%CRESPSL=='CNT') THEN
    PK%I%R%XLITTER         (:,:,:,1) =    I%R%XLITTER         (:,:,:,1)
    PK%I%R%XSOILCARB       (:,:,1)   =    I%R%XSOILCARB       (:,:,1)
    PK%I%R%XLIGNIN_STRUC   (:,:,1)   =    I%R%XLIGNIN_STRUC   (:,:,1)
    PK%I%IP%XTURNOVER       (:,:,1)   =    I%IP%XTURNOVER       (:,:,1)
  END IF
  !
  IF (I%O%CRAIN=='SGH') THEN
    PK%I%I%XMUF(:)=I%I%XMUF(:)
  ENDIF
!
!------------------------------------------------------------------------
ELSE
!------------------------------------------------------------------------
!
  DO JJ=1,KSIZE
    JI                      =    KMASK(JJ)
    PK%I%M%X%XZ0_O_Z0H     (JJ,1)    =    I%M%X%XZ0_O_Z0H     (JI, KPATCH)
    PK%I%M%T%XEMIS         (JJ,1)    =    I%M%T%XEMIS         (JI, KPATCH)
    PK%I%M%T%XALBNIR       (JJ,1)    =    I%M%T%XALBNIR       (JI, KPATCH)
    PK%I%M%T%XALBVIS       (JJ,1)    =    I%M%T%XALBVIS       (JI, KPATCH)
    PK%I%M%T%XALBUV        (JJ,1)    =    I%M%T%XALBUV        (JI, KPATCH)
    PK%I%M%T%XALBNIR_VEG   (JJ,1)    =    I%M%T%XALBNIR_VEG   (JI, KPATCH)
    PK%I%M%T%XALBVIS_VEG   (JJ,1)    =    I%M%T%XALBVIS_VEG   (JI, KPATCH)
    PK%I%M%T%XALBUV_VEG    (JJ,1)    =    I%M%T%XALBUV_VEG    (JI, KPATCH)
    PK%I%M%A%XALBNIR_SOIL  (JJ,1)    =    I%M%A%XALBNIR_SOIL  (JI, KPATCH)
    PK%I%M%A%XALBVIS_SOIL  (JJ,1)    =    I%M%A%XALBVIS_SOIL  (JI, KPATCH)
    PK%I%M%A%XALBUV_SOIL   (JJ,1)    =    I%M%A%XALBUV_SOIL   (JI, KPATCH)
    PK%I%M%T%XZ0           (JJ,1)    =    I%M%T%XZ0           (JI, KPATCH)
    PK%I%M%T%XWRMAX_CF     (JJ,1)    =    I%M%T%XWRMAX_CF     (JI, KPATCH)
    PK%I%M%T%XGAMMA        (JJ,1)    =    I%M%T%XGAMMA        (JI, KPATCH)
    PK%I%M%T%XCV           (JJ,1)    =    I%M%T%XCV           (JI, KPATCH)
    PK%I%M%T%XRGL          (JJ,1)    =    I%M%T%XRGL          (JI, KPATCH)
    PK%I%IP%XRUNOFFD      (JJ,1)    =    I%IP%XRUNOFFD      (JI, KPATCH)
    PK%I%IP%XZ0EFFIP      (JJ,1)    =    I%IP%XZ0EFFIP      (JI, KPATCH)
    PK%I%IP%XZ0EFFIM      (JJ,1)    =    I%IP%XZ0EFFIM      (JI, KPATCH)
    PK%I%IP%XZ0EFFJP      (JJ,1)    =    I%IP%XZ0EFFJP      (JI, KPATCH)
    PK%I%IP%XZ0EFFJM      (JJ,1)    =    I%IP%XZ0EFFJM      (JI, KPATCH)  
    PK%I%R%XWR           (JJ,1)    =    I%R%XWR           (JI, KPATCH) 
    PK%I%M%T%XLAI          (JJ,1)    =    I%M%T%XLAI          (JI, KPATCH) 
    PK%I%R%XRESA         (JJ,1)    =    I%R%XRESA         (JI, KPATCH) 
    PK%I%IP%XPCPS          (JJ,1)    =    I%IP%XPCPS         (JI, KPATCH)
    PK%I%IP%XPLVTT         (JJ,1)    =    I%IP%XPLVTT        (JI, KPATCH)
    PK%I%IP%XPLSTT         (JJ,1)    =    I%IP%XPLSTT        (JI, KPATCH)
    PK%I%M%T%XVEG          (JJ,1)    =    I%M%T%XVEG          (JI, KPATCH) 
    PK%I%R%TSNOW%ALB      (JJ,1)    =    I%R%TSNOW%ALB     (JI, KPATCH) 
    PK%I%R%XLE           (JJ,1)    =    I%R%XLE           (JI, KPATCH) 
    PK%I%R%XPSN          (JJ,1)    =    I%R%XPSN          (JI, KPATCH)
    PK%I%R%XPSNG         (JJ,1)    =    I%R%XPSNG         (JI, KPATCH)
    PK%I%R%XPSNV         (JJ,1)    =    I%R%XPSNV         (JI, KPATCH)    
    PK%I%IP%XALBNIR_DRY   (JJ)    =    I%IP%XALBNIR_DRY   (JI)
    PK%I%IP%XALBVIS_DRY   (JJ)    =    I%IP%XALBVIS_DRY   (JI)
    PK%I%IP%XALBUV_DRY    (JJ)    =    I%IP%XALBUV_DRY    (JI)
    PK%I%IP%XALBNIR_WET   (JJ)    =    I%IP%XALBNIR_WET   (JI)
    PK%I%IP%XALBVIS_WET   (JJ)    =    I%IP%XALBVIS_WET   (JI)
    PK%I%IP%XALBUV_WET    (JJ)    =    I%IP%XALBUV_WET    (JI)    
    PK%I%P%XRUNOFFB      (JJ)    =    I%P%XRUNOFFB      (JI)
    PK%I%P%XWDRAIN       (JJ)    =    I%P%XWDRAIN       (JI)
    PK%I%IP%XTAUICE       (JJ)    =    I%IP%XTAUICE       (JI)
    PK%I%IP%XZ0REL        (JJ)    =    I%IP%XZ0REL        (JI)
    PK%I%P%XAOSIP        (JJ)    =    I%P%XAOSIP        (JI)
    PK%I%P%XAOSIM        (JJ)    =    I%P%XAOSIM        (JI)
    PK%I%P%XAOSJP        (JJ)    =    I%P%XAOSJP        (JI)
    PK%I%P%XAOSJM        (JJ)    =    I%P%XAOSJM        (JI)
    PK%I%P%XHO2IP        (JJ)    =    I%P%XHO2IP        (JI)
    PK%I%P%XHO2IM        (JJ)    =    I%P%XHO2IM        (JI)
    PK%I%P%XHO2JP        (JJ)    =    I%P%XHO2JP        (JI)
    PK%I%P%XHO2JM        (JJ)    =    I%P%XHO2JM        (JI)
    PK%I%P%XSSO_SLOPE    (JJ)    =    I%P%XSSO_SLOPE    (JI)
    PK%I%IP%XGAMMAT       (JJ)    =    I%IP%XGAMMAT       (JI)
    PK%I%IP%XTDEEP        (JJ)    =    I%IP%XTDEEP        (JI) 
    PK%G%XLAT          (JJ)    =    IG%XLAT          (JI)
    PK%G%XLON          (JJ)    =    IG%XLON          (JI)    
    PK%I%I%XFSAT         (JJ)    =    I%I%XFSAT         (JI)
  ENDDO
  !  
  DO JK=1,I%O%NGROUND_LAYER
    DO JJ=1,KSIZE
      JI                       =    KMASK(JJ)
      PK%I%P%XCLAY         (JJ,JK)  =    I%P%XCLAY         (JI, JK)
      PK%I%P%XSAND         (JJ,JK)  =    I%P%XSAND         (JI, JK)
      PK%I%IP%XWFC          (JJ,JK)  =    I%IP%XWFC          (JI, JK)
      PK%I%IP%XWWILT        (JJ,JK)  =    I%IP%XWWILT        (JI, JK)
      PK%I%IP%XWSAT         (JJ,JK)  =    I%IP%XWSAT         (JI, JK)    
      PK%I%IP%XCONDSAT      (JJ,JK,1)  =    I%IP%XCONDSAT      (JI, JK, KPATCH)      
      PK%I%M%X%XDG           (JJ,JK,1)  =    I%M%X%XDG           (JI, JK, KPATCH)  
      PK%I%R%XWG           (JJ,JK,1)  =    I%R%XWG           (JI, JK, KPATCH)
      PK%I%R%XWGI          (JJ,JK,1)  =    I%R%XWGI          (JI, JK, KPATCH)
      PK%I%IP%XMPOTSAT      (JJ, JK) =    I%IP%XMPOTSAT      (JI, JK)
      PK%I%IP%XBCOEF        (JJ, JK) =    I%IP%XBCOEF        (JI, JK)      
    ENDDO    
  ENDDO  
  !  
  DO JJ=1,KSIZE
     JI              = KMASK(JJ)
     PK%I%IP%XKSAT_ICE(JJ,1) = I%IP%XKSAT_ICE(JI,KPATCH)
     PK%I%M%X%XD_ICE   (JJ,1) = I%M%X%XD_ICE   (JI,KPATCH)
  END DO
  !
  DO JK=1,NVEGTYPE
    DO JJ=1,KSIZE
      JI                      =    KMASK(JJ)
      PK%I%IP%XVEGTYPE_PATCH(JJ,JK,1) =    I%IP%XVEGTYPE_PATCH(JI, JK, KPATCH)
    ENDDO
  ENDDO  
  !
  DO JK=1,SIZE(I%R%XTG,2)
    DO JJ=1,KSIZE
      JI                       =    KMASK(JJ)
      PK%I%R%XTG           (JJ,JK,1)  =    I%R%XTG           (JI, JK, KPATCH)  
    ENDDO
  ENDDO
  !  
  DO JK=1,I%R%TSNOW%NLAYER
    DO JJ=1,KSIZE
      JI                       =    KMASK(JJ)
      PK%I%R%TSNOW%WSNOW       (JJ,JK,1)  =    I%R%TSNOW%WSNOW   (JI, JK, KPATCH)
      PK%I%R%TSNOW%RHO      (JJ,JK,1)  =    I%R%TSNOW%RHO     (JI, JK, KPATCH)
    ENDDO
  ENDDO  
  !  
  DO JK=1,SIZE(PK%I%I%XDIR_ALB_WITH_SNOW,2)
    DO JJ=1,KSIZE
      JI                          = KMASK(JJ)
      PK%I%I%XDIR_ALB_WITH_SNOW (JJ,JK,1)= I%I%XDIR_ALB_WITH_SNOW(JI,JK,KPATCH)
      PK%I%I%XSCA_ALB_WITH_SNOW (JJ,JK,1)= I%I%XSCA_ALB_WITH_SNOW(JI,JK,KPATCH)
    ENDDO
  ENDDO
  !
  IF (I%O%LFLOOD)THEN
    DO JJ=1,KSIZE
       JI             = KMASK(JJ)
       PK%I%I%XFFLOOD  (JJ)=I%I%XFFLOOD  (JI)
       PK%I%I%XPIFLOOD (JJ)=I%I%XPIFLOOD (JI)
       PK%I%I%XFF      (JJ,1)=I%I%XFF      (JI,KPATCH)
       PK%I%I%XFFG     (JJ,1)=I%I%XFFG     (JI,KPATCH)
       PK%I%I%XFFV     (JJ,1)=I%I%XFFV     (JI,KPATCH)
       PK%I%I%XFFROZEN (JJ,1)=I%I%XFFROZEN (JI,KPATCH)    
       PK%I%I%XALBF    (JJ,1)=I%I%XALBF    (JI,KPATCH)
       PK%I%I%XEMISF   (JJ,1)=I%I%XEMISF   (JI,KPATCH)       
    END DO
  ELSE
    PK%I%I%XFFLOOD  (:) = 0.0
    PK%I%I%XPIFLOOD (:) = 0.0
    PK%I%I%XFF      (:,1) = 0.0
    PK%I%I%XFFG     (:,1) = 0.0
    PK%I%I%XFFROZEN (:,1) = 0.0
    PK%I%I%XFFV     (:,1) = 0.0
    PK%I%I%XALBF    (:,1) = 0.0
    PK%I%I%XEMISF   (:,1) = 0.0
  ENDIF
!
  IF(I%R%TSNOW%SCHEME=='EBA') THEN
    DO JJ=1,KSIZE
       JI                = KMASK(JJ)
       PK%I%R%XPSNV_A (JJ,1)    = I%R%XPSNV_A(JI, KPATCH)
    END DO
  END IF
  !
  IF (I%R%TSNOW%SCHEME=='3-L' .OR. I%R%TSNOW%SCHEME=='CRO') THEN
    DO JK=1,SIZE(PK%I%R%TSNOW%HEAT,2)
      DO JJ=1,KSIZE
        JI                     =    KMASK(JJ)
        PK%I%R%TSNOW%HEAT   (JJ, JK,1) =    I%R%TSNOW%HEAT   (JI, JK, KPATCH)
        PK%I%R%TSNOW%AGE    (JJ, JK,1) =    I%R%TSNOW%AGE    (JI, JK, KPATCH)
      ENDDO
    END DO
    DO JJ=1,KSIZE
      JI                      =    KMASK(JJ)
      PK%I%R%TSNOW%ALBVIS   (JJ,1)    =    I%R%TSNOW%ALBVIS  (JI, KPATCH) 
      PK%I%R%TSNOW%ALBNIR   (JJ,1)    =    I%R%TSNOW%ALBNIR  (JI, KPATCH) 
      PK%I%R%TSNOW%ALBFIR   (JJ,1)    =    I%R%TSNOW%ALBFIR  (JI, KPATCH) 
    ENDDO
  END IF
  !
  IF (I%R%TSNOW%SCHEME=='CRO') THEN
    DO JK=1,SIZE(PK%I%R%TSNOW%GRAN1,2)
      DO JJ=1,KSIZE
        JI                     =    KMASK(JJ)  
        PK%I%R%TSNOW%GRAN1  (JJ, JK,1) =    I%R%TSNOW%GRAN1  (JI, JK, KPATCH)
        PK%I%R%TSNOW%GRAN2  (JJ, JK,1) =    I%R%TSNOW%GRAN2  (JI, JK, KPATCH)
        PK%I%R%TSNOW%HIST   (JJ, JK,1) =    I%R%TSNOW%HIST   (JI, JK, KPATCH)
      ENDDO
    END DO
  END IF
  !
  IF(I%O%LGLACIER)THEN
    DO JJ=1,KSIZE
       JI             = KMASK(JJ)
       PK%I%R%XICE_STO(JJ,1) = I%R%XICE_STO  (JI,KPATCH)
    ENDDO
  ENDIF
  !  
  IF (I%O%CSCOND=='PL98'.OR.I%O%CISBA=='DIF') THEN
    DO JK=1,SIZE(I%IP%XHCAPSOIL,2)
      DO JJ=1,KSIZE
        JI                    =    KMASK(JJ)
        PK%I%IP%XHCAPSOIL   (JJ, JK) =    I%IP%XHCAPSOIL    (JI, JK)
        PK%I%IP%XCONDDRY    (JJ, JK) =    I%IP%XCONDDRY     (JI, JK)
        PK%I%IP%XCONDSLD    (JJ, JK) =    I%IP%XCONDSLD     (JI, JK)
      ENDDO
    ENDDO
  END IF
  !
  IF (I%O%CISBA=='2-L' .OR. I%O%CISBA=='3-L') THEN
    DO JJ=1,KSIZE
      JI                    =    KMASK(JJ)
      PK%I%IP%XC4B        (JJ)    =    I%IP%XC4B          (JI)
      PK%I%IP%XACOEF      (JJ)    =    I%IP%XACOEF        (JI)
      PK%I%IP%XPCOEF      (JJ)    =    I%IP%XPCOEF        (JI)
      PK%I%IP%XCGSAT      (JJ)    =    I%IP%XCGSAT        (JI) 
      PK%I%IP%XC1SAT      (JJ,1)    =    I%IP%XC1SAT        (JI, KPATCH)
      PK%I%IP%XC2REF      (JJ,1)    =    I%IP%XC2REF        (JI, KPATCH)     
      PK%I%IP%XC4REF      (JJ,1)    =    I%IP%XC4REF        (JI, KPATCH)      
    ENDDO
    !
    DO JK=1,SIZE(I%IP%XC3,2)
      DO JJ=1,KSIZE
        JI                    =    KMASK(JJ)
        PK%I%IP%XC3         (JJ,JK,1)  =    I%IP%XC3           (JI, JK, KPATCH)
      ENDDO
    ENDDO
  END IF
  !
    DO JK=1,SIZE(I%IP%XBCOEF,2)
      DO JJ=1,KSIZE    
         JI                  =    KMASK(JJ)
         PK%I%IP%XMPOTSAT (JJ, JK) =    I%IP%XMPOTSAT (JI, JK)
         PK%I%IP%XBCOEF   (JJ, JK) =    I%IP%XBCOEF   (JI, JK)
      ENDDO
    ENDDO
  !
  IF (I%O%CISBA=='DIF') THEN
    DO JK=1,SIZE(I%M%X%XROOTFRAC,2)
      DO JJ=1,KSIZE
        JI                     =    KMASK(JJ)
        PK%I%M%X%XROOTFRAC   (JJ, JK,1) =    I%M%X%XROOTFRAC   (JI, JK, KPATCH)
        PK%I%IP%XDZG        (JJ, JK,1) =    I%IP%XDZG        (JI, JK, KPATCH)
        PK%I%IP%XDZDIF      (JJ, JK,1) =    I%IP%XDZDIF      (JI, JK, KPATCH)
        PK%I%IP%XSOILWGHT   (JJ, JK,1) =    I%IP%XSOILWGHT   (JI, JK, KPATCH)
      ENDDO
    ENDDO
    DO JJ=1,KSIZE
      JI                =  KMASK(JJ)
      PK%I%M%X%NWG_LAYER (JJ,1)  =  I%M%X%NWG_LAYER (JI,KPATCH)
      PK%I%IP%XFWTD     (JJ)  =  I%IP%XFWTD     (JI)
      PK%I%IP%XWTD      (JJ)  =  I%IP%XWTD      (JI)
    ENDDO
  ENDIF
  !
  IF (I%O%CISBA=='DIF'.AND.I%O%CRUNOFF=='SGH') THEN
    DO JK=1,SIZE(I%M%X%XROOTFRAC,2)
      DO JJ=1,KSIZE
        JI                     =    KMASK(JJ)
        PK%I%I%XTOPQS   (JJ, JK,1)    =    I%I%XTOPQS   (JI, JK, KPATCH)  
      ENDDO
    ENDDO        
  END IF
  !
  IF (I%O%LTR_ML) THEN
    DO JJ=1,KSIZE
      JI                    =    KMASK(JJ)
      PK%I%R%XFAPARC      (JJ,1)    =    I%R%XFAPARC      (JI, KPATCH)
      PK%I%R%XFAPIRC      (JJ,1)    =    I%R%XFAPIRC      (JI, KPATCH)
      PK%I%R%XLAI_EFFC    (JJ,1)    =    I%R%XLAI_EFFC    (JI, KPATCH)
      PK%I%R%XMUS         (JJ,1)    =    I%R%XMUS         (JI, KPATCH)
    ENDDO
  ENDIF  
  !
  IF (I%O%CPHOTO=='NON') THEN
    DO JJ=1,KSIZE
      JI                    =    KMASK(JJ)
      PK%I%M%T%XRSMIN      (JJ,1)    =    I%M%T%XRSMIN      (JI, KPATCH)
    END DO
  END IF
  !
  IF(I%O%LMEB_PATCH(KPATCH))THEN
!
    DO JJ=1,KSIZE
      JI                      =    KMASK(JJ)
      PK%I%R%XWRL          (JJ,1)    =    I%R%XWRL          (JI, KPATCH) 
      PK%I%R%XWRLI         (JJ,1)    =    I%R%XWRLI         (JI, KPATCH) 
      PK%I%R%XWRVN         (JJ,1)    =    I%R%XWRVN         (JI, KPATCH) 
      PK%I%R%XTV           (JJ,1)    =    I%R%XTV           (JI, KPATCH) 
      PK%I%R%XTL           (JJ,1)    =    I%R%XTL           (JI, KPATCH) 
      PK%I%R%XTC           (JJ,1)    =    I%R%XTC           (JI, KPATCH) 
      PK%I%R%XQC           (JJ,1)    =    I%R%XQC           (JI, KPATCH) 
    ENDDO
!
! Please note that secondary Ecoclimap parameters, i.e. those
! with postfix GV, are given to the corresponing original ISBA physiography
! parameters in the case of LMEB_PATCH/OMEB=true. And the original ISBA
! physiography parameters are given to the canopy vegetation parameters.
! E.g. XLAI -> XP_LAIV and XLAIGV -> XP_LAI
!
!nogv    IF (CISBA=='DIF') THEN
!nogv      XP_ROOTFRACV = XP_ROOTFRAC
!nogv      DO JK=1,SIZE(XROOTFRAC,2)
!nogv        DO JJ=1,KSIZE
!nogv          JI                    =    KMASK(JJ)
!nogv          XP_ROOTFRAC  (JJ, JK) =  XROOTFRACGV   (JI, JK, KPATCH)
!nogv        ENDDO
!nogv      ENDDO
!nogv    END IF
!
!nogv    IF (CPHOTO=='NON') THEN
!nogv      XP_RSMINV = XP_RSMIN
!nogv      DO JJ=1,KSIZE
!nogv        JI                    =    KMASK(JJ)
!nogv        XP_RSMIN      (JJ)    =    XRSMINGV      (JI, KPATCH)
!nogv      END DO
!nogv    END IF
!
    DO JJ=1,KSIZE
      JI                      =    KMASK(JJ)
      PK%I%M%M%XH_VEG        (JJ,1)    =    I%M%M%XH_VEG        (JI, KPATCH)
!nogv      XP_RGLV         (JJ,1)    =    XRGL          (JI, KPATCH)
!nogv      XP_GAMMAV       (JJ,1)    =    XGAMMA        (JI, KPATCH)
!nogv      XP_WRMAX_CFV    (JJ,1)    =    XWRMAX_CF     (JI, KPATCH)
!nogv      XP_LAIV         (JJ,1)    =    XLAI          (JI, KPATCH)
!nogv      XP_Z0V          (JJ,1)    =    XZ0           (JI, KPATCH)
!
!nogv      XP_VEG          (JJ,1)    =    XGNDLITTER    (JI, KPATCH)
!nogv      XP_RGL          (JJ,1)    =    XRGLGV        (JI, KPATCH)
!nogv      XP_GAMMA        (JJ,1)    =    XGAMMAGV      (JI, KPATCH)
!nogv      XP_WRMAX_CF     (JJ,1)    =    XWRMAX_CFGV   (JI, KPATCH)
!nogv      XP_LAI          (JJ,1)    =    XLAIGV        (JI, KPATCH)
!nogv      XP_Z0           (JJ,1)    =    XZ0LITTER     (JI, KPATCH)
      PK%I%M%M%XGNDLITTER    (JJ,1)    =    I%M%M%XGNDLITTER    (JI, KPATCH)
      PK%I%M%M%XZ0LITTER     (JJ,1)    =    I%M%M%XZ0LITTER     (JI, KPATCH)
    ENDDO
  ENDIF
!
  IF(I%O%CPHOTO/='NON' .OR. I%O%LMEB_PATCH(KPATCH))THEN
    DO JJ=1,KSIZE
      JI                    =    KMASK(JJ)
      PK%I%M%T%XBSLAI      (JJ,1)    =    I%M%T%XBSLAI      (JI, KPATCH)
    ENDDO
  ENDIF
!
  IF (I%O%CPHOTO/='NON') THEN
    DO JJ=1,KSIZE
      JI                    =    KMASK(JJ)
      PK%I%M%T%XLAIMIN     (JJ,1)    =    I%M%T%XLAIMIN     (JI, KPATCH)
      PK%I%M%T%XSEFOLD     (JJ,1)    =    I%M%T%XSEFOLD     (JI, KPATCH)
      PK%I%M%X%XH_TREE     (JJ,1)    =    I%M%X%XH_TREE     (JI, KPATCH)
      PK%I%IP%XANMAX      (JJ,1)    =    I%IP%XANMAX      (JI, KPATCH)
      PK%I%IP%XFZERO      (JJ,1)    =    I%IP%XFZERO      (JI, KPATCH)
      PK%I%IP%XEPSO       (JJ,1)    =    I%IP%XEPSO       (JI, KPATCH)
      PK%I%IP%XGAMM       (JJ,1)    =    I%IP%XGAMM       (JI, KPATCH)
      PK%I%IP%XQDGAMM     (JJ,1)    =    I%IP%XQDGAMM     (JI, KPATCH)
      PK%I%M%T%XGMES       (JJ,1)    =    I%M%T%XGMES       (JI, KPATCH)
      PK%I%M%X%XRE25       (JJ,1)    =    I%M%X%XRE25       (JI, KPATCH)
      PK%I%IP%XQDGMES     (JJ,1)    =    I%IP%XQDGMES     (JI, KPATCH)
      PK%I%IP%XT1GMES     (JJ,1)    =    I%IP%XT1GMES     (JI, KPATCH)
      PK%I%IP%XT2GMES     (JJ,1)    =    I%IP%XT2GMES     (JI, KPATCH)
      PK%I%IP%XAMAX       (JJ,1)    =    I%IP%XAMAX       (JI, KPATCH)
      PK%I%IP%XQDAMAX     (JJ,1)    =    I%IP%XQDAMAX     (JI, KPATCH)
      PK%I%IP%XT1AMAX     (JJ,1)    =    I%IP%XT1AMAX     (JI, KPATCH)
      PK%I%IP%XT2AMAX     (JJ,1)    =    I%IP%XT2AMAX     (JI, KPATCH)
      PK%I%R%XAN         (JJ,1)    =    I%R%XAN         (JI, KPATCH) 
      PK%I%R%XANDAY      (JJ,1)    =    I%R%XANDAY      (JI, KPATCH) 
      PK%I%R%XANFM       (JJ,1)    =    I%R%XANFM       (JI, KPATCH) 
      PK%I%M%T%XGC         (JJ,1)    =    I%M%T%XGC         (JI, KPATCH)
    ENDDO
    DO JK=1,SIZE(I%R%XBIOMASS,2)
      DO JJ=1,KSIZE
        JI                    =    KMASK(JJ)
        PK%I%R%XBIOMASS        (JJ,JK,1)  =    I%R%XBIOMASS        (JI,JK,KPATCH)
        PK%I%R%XRESP_BIOMASS   (JJ,JK,1)  =    I%R%XRESP_BIOMASS   (JI,JK,KPATCH)
      ENDDO
    END DO
  END IF
  !
  IF (I%O%CPHOTO=='AST' .OR. I%O%CPHOTO=='LST' .OR. I%O%CPHOTO=='NIT' .OR. I%O%CPHOTO=='NCB') THEN
    DO JJ=1,KSIZE
      JI                    =    KMASK(JJ)
      PK%I%M%T%LSTRESS     (JJ,1)    =    I%M%T%LSTRESS     (JI, KPATCH)
      PK%I%M%T%XF2I        (JJ,1)    =    I%M%T%XF2I        (JI, KPATCH)
      PK%I%IP%XAH         (JJ,1)    =    I%IP%XAH         (JI, KPATCH)
      PK%I%IP%XBH         (JJ,1)    =    I%IP%XBH         (JI, KPATCH)
      PK%I%M%X%XDMAX       (JJ,1)    =    I%M%X%XDMAX       (JI, KPATCH)
    END DO
  END IF
  !
  IF(LAGRIP .AND. (I%O%CPHOTO=='LAI' .OR. I%O%CPHOTO=='LST' .OR. I%O%CPHOTO=='NIT' .OR. I%O%CPHOTO=='NCB')) THEN
    DO JJ=1,KSIZE
      JI               = KMASK(JJ)
      PK%I%M%I%TSEED     (JJ,1) = I%M%I%TSEED     (JI,KPATCH)
      PK%I%M%I%TREAP     (JJ,1) = I%M%I%TREAP     (JI,KPATCH)
      PK%I%M%I%XIRRIG    (JJ,1) = I%M%I%XIRRIG    (JI,KPATCH)
      PK%I%M%I%XWATSUP   (JJ,1) = I%M%I%XWATSUP   (JI,KPATCH)
      PK%AG%LIRRIDAY (JJ,1) = AG%LIRRIDAY  (JI,KPATCH)
      PK%AG%XTHRESHOLDSPT(JJ,1) = AG%XTHRESHOLDSPT(JI,KPATCH)
      PK%AG%LIRRIGATE(JJ,1) = AG%LIRRIGATE (JI,KPATCH)
    ENDDO
  ENDIF
  !
  IF(I%O%CPHOTO=='NIT' .OR. I%O%CPHOTO=='NCB') THEN
    DO JJ=1,KSIZE
      JI                      =    KMASK(JJ)
      PK%I%M%T%XCE_NITRO       (JJ,1)  =    I%M%T%XCE_NITRO       (JI,KPATCH)
      PK%I%M%T%XCF_NITRO       (JJ,1)  =    I%M%T%XCF_NITRO       (JI,KPATCH)
      PK%I%M%T%XCNA_NITRO      (JJ,1)  =    I%M%T%XCNA_NITRO      (JI,KPATCH)
      PK%I%IP%XBSLAI_NITRO    (JJ,1)  =    I%IP%XBSLAI_NITRO    (JI,KPATCH)      
    END DO
  END IF
  !
  IF (I%O%CPHOTO=='NCB') THEN
    DO JK=1,SIZE(I%IP%XINCREASE,2)
      DO JJ=1,KSIZE
        JI                      =    KMASK(JJ)
        PK%I%IP%XINCREASE   (JJ,JK,1)   =    I%IP%XINCREASE       (JI,JK,KPATCH)
      ENDDO
    END DO
    DO JJ=1,KSIZE
      JI                      =    KMASK(JJ)
      PK%I%IP%XTAU_WOOD       (JJ,1)  =    I%IP%XTAU_WOOD       (JI,KPATCH)
    END DO  
  END IF
  !
  IF (I%O%CRESPSL=='CNT') THEN
    DO JL=1,SIZE(PK%I%R%XLITTER,3)
      DO JK=1,SIZE(PK%I%R%XLITTER,2)
        DO JJ=1,KSIZE
          JI                      =    KMASK(JJ)
          PK%I%R%XLITTER         (JJ,JK,JL,1) =    I%R%XLITTER         (JI,JK,JL,KPATCH)
        ENDDO
      ENDDO
    ENDDO
    DO JK=1,SIZE(PK%I%R%XSOILCARB,2)
      DO JJ=1,KSIZE
        JI                      =    KMASK(JJ)
        PK%I%R%XSOILCARB       (JJ,JK,1)   =    I%R%XSOILCARB       (JI,JK,KPATCH)
      ENDDO
    ENDDO
     DO JK=1,SIZE(PK%I%R%XLIGNIN_STRUC,2)
      DO JJ=1,KSIZE
        JI                      =    KMASK(JJ)
        PK%I%R%XLIGNIN_STRUC  (JJ,JK,1)   =    I%R%XLIGNIN_STRUC  (JI,JK,KPATCH)
      ENDDO
    ENDDO
    DO JK=1,SIZE(PK%I%IP%XTURNOVER,2)
      DO JJ=1,KSIZE
        JI                      =    KMASK(JJ)
        PK%I%IP%XTURNOVER      (JJ,JK,1)   =    I%IP%XTURNOVER       (JI,JK,KPATCH)
      ENDDO
    ENDDO
  END IF
!
  IF (I%O%CRAIN=='SGH')THEN
    DO JJ=1,KSIZE
       JI         = KMASK(JJ)
       PK%I%I%XMUF(JJ) = I%I%XMUF(JI)
    END DO
  ENDIF
!
!------------------------------------------------------------------------
END IF
IF (LHOOK) CALL DR_HOOK('PACK_ISBA_PATCH_N',1,ZHOOK_HANDLE)
!------------------------------------------------------------------------
END SUBROUTINE PACK_ISBA_PATCH_n
