!     #########
SUBROUTINE PACK_DIAG_PATCH_n (DGEI, DGI, DGMI, I, PK, PKD, &
                              KSIZE,KSW,KPATCH)
!##############################################
!
!!****  *PACK_DIAG_PATCH_n* - packs ISBA diagnostics
!!
!!    PURPOSE
!!    -------
!
!!**  METHOD
!!    ------
!!
!!    REFERENCE
!!    ---------
!!      
!!
!!    AUTHOR
!!    ------
!!     V. Masson 
!!
!!    MODIFICATIONS
!!    -------------
!!      Original    01/2004
!!      Modified    10/2004 by P. Le Moigne: Halstead coefficient
!!      Modified    10/2005 by P. Le Moigne: Allocation (not EBA case)
!!      Modified       2008 by B. Decharme : Allocation for the floodplains
!!      Modified      04-09 by A.L. Gibelin : Add carbon diagnostics
!!      B. Decharme 04/2013 DIF lateral subsurface drainage
!!                          Sublimation diag flux
!!      Modified      10-14 by P. Samuelsson: MEB
!!
!!------------------------------------------------------------------
!
!
!
!
                                  ! End For multi-energy balance


!
!
USE MODD_DIAG_EVAP_ISBA_n, ONLY : DIAG_EVAP_ISBA_t
USE MODD_DIAG_n, ONLY : DIAG_t
USE MODD_DIAG_MISC_ISBA_n, ONLY : DIAG_MISC_ISBA_t
USE MODD_ISBA_n, ONLY : ISBA_t
USE MODD_PACK_DIAG_ISBA, ONLY : PACK_DIAG_ISBA_t
USE MODD_PACK_ISBA, ONLY : PACK_ISBA_t
!
USE MODI_ABOR1_SFX
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE
!
!
TYPE(DIAG_EVAP_ISBA_t), INTENT(INOUT) :: DGEI
TYPE(DIAG_t), INTENT(INOUT) :: DGI
TYPE(DIAG_MISC_ISBA_t), INTENT(INOUT) :: DGMI
TYPE(ISBA_t), INTENT(INOUT) :: I
TYPE(PACK_ISBA_t), INTENT(INOUT) :: PK
TYPE(PACK_DIAG_ISBA_t), INTENT(INOUT) :: PKD
!
INTEGER, INTENT(IN)               :: KSIZE, KSW, KPATCH
!
INTEGER :: ISIZE_SIMPLE, ISIZE_GROUND, ISIZE_SNOW, ISIZE_KSW, &
           ISIZE_ABC, ISIZE_0, ISIZE_00
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
!------------------------------------------------------------------------
IF (LHOOK) CALL DR_HOOK('PACK_DIAG_PATCH_N',0,ZHOOK_HANDLE)
!
! Packed surface module variables:
!
ALLOCATE(PKD%XBLOCK_SIMPLE(KSIZE,PKD%NSIZE_SIMPLE))
ALLOCATE(PKD%XBLOCK_GROUND(KSIZE,I%O%NGROUND_LAYER,PKD%NSIZE_GROUND))
ALLOCATE(PKD%XBLOCK_SNOW(KSIZE,I%R%TSNOW%NLAYER,PKD%NSIZE_SNOW))
ALLOCATE(PKD%XBLOCK_KSW(KSIZE,KSW,PKD%NSIZE_KSW))
ALLOCATE(PKD%XBLOCK_ABC(KSIZE,SIZE(I%IP%XABC),PKD%NSIZE_ABC))
ALLOCATE(PKD%XBLOCK_0(0,PKD%NSIZE_0))
ALLOCATE(PKD%XBLOCK_00(0,0,PKD%NSIZE_00))
!
ISIZE_SIMPLE=0
ISIZE_GROUND=0
ISIZE_SNOW=0
ISIZE_KSW=0
ISIZE_ABC=0
ISIZE_0=0
ISIZE_00=0
!
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PKD%DGIP%XCH          => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PKD%DGIP%XCE          => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PKD%DGIP%XCD          => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PKD%DGIP%XCDN         => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PKD%DGIP%XRI          => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PKD%DGIP%XHU          => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PKD%DGIP%XHUG         => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PKD%DGIP%XALBT        => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
!

!
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PKD%DGEIP%XLEG         => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PKD%DGEIP%XLEGI        => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PKD%DGEIP%XLEV         => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PKD%DGEIP%XLES         => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PKD%DGEIP%XLER         => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PKD%DGEIP%XLETR        => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
!
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PKD%DGIP%XRN          => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PKD%DGIP%XH           => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PKD%DGIP%XLEI         => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PKD%DGIP%XGFLUX       => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
!
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PKD%DGIP%XEVAP        => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PKD%DGIP%XSUBL        => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PKD%DGEIP%XRESTORE     => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PKD%DGEIP%XDRAIN       => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PKD%DGEIP%XQSB         => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PKD%DGEIP%XRUNOFF      => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PKD%DGEIP%XMELT        => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PKD%DGEIP%XMELTADV     => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PKD%DGMI%XSRSFC       => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PKD%DGMI%XRRSFC       => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PK%I%R%XSNOWFREE_ALB=> PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE)
!
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PKD%DGEIP%XHORT      => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PKD%DGEIP%XDRIP      => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PKD%DGEIP%XRRVEG     => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PKD%DGEIP%XIRRIG_FLUX=> PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
!
ISIZE_KSW = ISIZE_KSW + 1
PKD%DGIP%XSWBD       => PKD%XBLOCK_KSW(:,:,ISIZE_KSW)
ISIZE_KSW = ISIZE_KSW + 1
PKD%DGIP%XSWBU       => PKD%XBLOCK_KSW(:,:,ISIZE_KSW)
!
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PKD%DGIP%XSWD         => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PKD%DGIP%XSWU         => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PKD%DGIP%XLWD         => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PKD%DGIP%XLWU         => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PKD%DGIP%XFMU         => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PKD%DGIP%XFMV         => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
!
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PKD%DGIP%XZ0 => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PKD%DGIP%XZ0H => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PKD%DGIP%XZ0EFF        => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
!
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PKD%DGMI%XCG          => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PKD%DGMI%XC1          => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PKD%DGMI%XC2          => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PKD%DGMI%XWGEQ        => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PKD%DGMI%XCT          => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PKD%DGMI%XRS          => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PKD%DGMI%XHV          => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PKD%DGIP%XQS          => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
!
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PKD%DGIP%XTS            => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PKD%DGIP%XTSRAD         => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
!
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PKD%DGEIP%XRESP_AUTO    => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PKD%DGEIP%XRESP_ECO     => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PKD%DGEIP%XGPP          => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
!
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PKD%DGEIP%XIFLOOD   => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PKD%DGEIP%XPFLOOD   => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PKD%DGEIP%XLE_FLOOD => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
ISIZE_SIMPLE = ISIZE_SIMPLE + 1
PKD%DGEIP%XLEI_FLOOD=> PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
!
IF (I%R%TSNOW%SCHEME=='3-L' .OR. I%R%TSNOW%SCHEME=='CRO') THEN
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
  PKD%DGMI%XRNSNOW    => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
  PKD%DGMI%XHSNOW     => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
  PKD%DGMI%XHPSNOW    => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
  PKD%DGMI%XGFLUXSNOW => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
  PKD%DGMI%XUSTARSNOW => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
  PKD%DGMI%XGRNDFLUX  => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
  PKD%DGEIP%XLESL      => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
  PKD%DGEIP%XSNDRIFT   => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
  PKD%DGMI%XCDSNOW    => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
  PKD%DGMI%XCHSNOW    => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
  PKD%DGMI%XSNOWHMASS => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
  !
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
  PKD%DGI%XRN   => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
  PKD%DGI%XH   => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
  PKD%DGI%XLE   => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
  PKD%DGI%XLEI  => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
  PKD%DGI%XGFLUX=> PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)  
  !
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
  PKD%DGEI%XLEG  => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
  PKD%DGEI%XLEGI => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1  
  PKD%DGEI%XLEV  => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
  PKD%DGEI%XLETR => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
  PKD%DGEI%XUSTAR=> PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
  PKD%DGEI%XLER  => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
  !
  ISIZE_SNOW = ISIZE_SNOW + 1
  PKD%DGMI%XSNOWLIQ   => PKD%XBLOCK_SNOW(:,:,ISIZE_SNOW)
  ISIZE_SNOW = ISIZE_SNOW + 1
  PKD%DGMI%XSNOWDZ    => PKD%XBLOCK_SNOW(:,:,ISIZE_SNOW)  
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
  PKD%DGEIP%XSWNET_N    => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
  PKD%DGEIP%XSWNET_NS    => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
  PKD%DGEIP%XLWNET_N    => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
ELSE
  ISIZE_0 = ISIZE_0 + 1
  PKD%DGMI%XRNSNOW    => PKD%XBLOCK_0(:,ISIZE_0)
  ISIZE_0 = ISIZE_0 + 1
  PKD%DGMI%XHSNOW     => PKD%XBLOCK_0(:,ISIZE_0)
  ISIZE_0 = ISIZE_0 + 1
  PKD%DGMI%XHPSNOW    => PKD%XBLOCK_0(:,ISIZE_0)
  ISIZE_0 = ISIZE_0 + 1
  PKD%DGMI%XGFLUXSNOW => PKD%XBLOCK_0(:,ISIZE_0)
  ISIZE_0 = ISIZE_0 + 1
  PKD%DGMI%XUSTARSNOW => PKD%XBLOCK_0(:,ISIZE_0)
  ISIZE_0 = ISIZE_0 + 1
  PKD%DGMI%XGRNDFLUX  => PKD%XBLOCK_0(:,ISIZE_0)
  ISIZE_0 = ISIZE_0 + 1
  PKD%DGEIP%XLESL      => PKD%XBLOCK_0(:,ISIZE_0)
  ISIZE_0 = ISIZE_0 + 1
  PKD%DGEIP%XSNDRIFT   => PKD%XBLOCK_0(:,ISIZE_0)  
  ISIZE_0 = ISIZE_0 + 1
  PKD%DGMI%XCDSNOW    => PKD%XBLOCK_0(:,ISIZE_0)
  ISIZE_0 = ISIZE_0 + 1
  PKD%DGMI%XCHSNOW    => PKD%XBLOCK_0(:,ISIZE_0)
  ISIZE_0 = ISIZE_0 + 1
  PKD%DGMI%XSNOWHMASS => PKD%XBLOCK_0(:,ISIZE_0)
  ISIZE_0 = ISIZE_0 + 1
  PKD%DGI%XRN   => PKD%XBLOCK_0(:,ISIZE_0)
  ISIZE_0 = ISIZE_0 + 1
  PKD%DGI%XH   => PKD%XBLOCK_0(:,ISIZE_0)
  ISIZE_0 = ISIZE_0 + 1
  PKD%DGI%XLE   => PKD%XBLOCK_0(:,ISIZE_0)
  ISIZE_0 = ISIZE_0 + 1
  PKD%DGI%XLEI  => PKD%XBLOCK_0(:,ISIZE_0)
  ISIZE_0 = ISIZE_0 + 1
  PKD%DGI%XGFLUX=> PKD%XBLOCK_0(:,ISIZE_0)  
  ISIZE_0 = ISIZE_0 + 1
  PKD%DGEI%XLEG  => PKD%XBLOCK_0(:,ISIZE_0)
  ISIZE_0 = ISIZE_0 + 1
  PKD%DGEI%XLEGI => PKD%XBLOCK_0(:,ISIZE_0)
  ISIZE_0 = ISIZE_0 + 1
  PKD%DGEI%XLEV  => PKD%XBLOCK_0(:,ISIZE_0)
  ISIZE_0 = ISIZE_0 + 1
  PKD%DGEI%XLETR => PKD%XBLOCK_0(:,ISIZE_0)
  ISIZE_0 = ISIZE_0 + 1
  PKD%DGEI%XUSTAR=> PKD%XBLOCK_0(:,ISIZE_0)
  ISIZE_0 = ISIZE_0 + 1
  PKD%DGEI%XLER  => PKD%XBLOCK_0(:,ISIZE_0)
  ISIZE_00 = ISIZE_00 + 1
  PKD%DGMI%XSNOWLIQ   => PKD%XBLOCK_00(:,:,ISIZE_00)
  ISIZE_00 = ISIZE_00 + 1
  PKD%DGMI%XSNOWDZ    => PKD%XBLOCK_00(:,:,ISIZE_00)
  ISIZE_0 = ISIZE_0 + 1
  PKD%DGEIP%XSWNET_N  => PKD%XBLOCK_0(:,ISIZE_0)
  ISIZE_0 = ISIZE_0 + 1
  PKD%DGEIP%XSWNET_NS  => PKD%XBLOCK_0(:,ISIZE_0)
  ISIZE_0 = ISIZE_0 + 1
  PKD%DGEIP%XLWNET_N  => PKD%XBLOCK_0(:,ISIZE_0)
END IF
!
IF(I%R%TSNOW%SCHEME/='EBA') THEN
  ISIZE_SNOW = ISIZE_SNOW + 1
  PKD%DGMI%XSNOWTEMP    => PKD%XBLOCK_SNOW(:,:,ISIZE_SNOW)
ELSE
  ISIZE_00 = ISIZE_00 + 1
  PKD%DGMI%XSNOWTEMP    => PKD%XBLOCK_00(:,:,ISIZE_00)
ENDIF
!
IF(I%R%TSNOW%SCHEME=='EBA') THEN
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
  PK%I%R%XSNOWFREE_ALB_VEG=> PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
  PK%I%R%XSNOWFREE_ALB_SOIL=> PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE:ISIZE_SIMPLE)
ELSE
  ISIZE_0 = ISIZE_0 + 1
  PK%I%R%XSNOWFREE_ALB_VEG=> PKD%XBLOCK_0(:,ISIZE_0:ISIZE_0)
  ISIZE_0 = ISIZE_0 + 1
  PK%I%R%XSNOWFREE_ALB_SOIL=> PKD%XBLOCK_0(:,ISIZE_0:ISIZE_0)
ENDIF
!
IF (I%O%LTR_ML) THEN
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
  PKD%DGMI%XFAPAR => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
  PKD%DGMI%XFAPIR => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
  PKD%DGMI%XFAPAR_BS => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
  PKD%DGMI%XFAPIR_BS => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
ELSE 
  ISIZE_0 = ISIZE_0 + 1
  PKD%DGMI%XFAPAR => PKD%XBLOCK_0(:,ISIZE_0)
  ISIZE_0 = ISIZE_0 + 1
  PKD%DGMI%XFAPIR => PKD%XBLOCK_0(:,ISIZE_0)
  ISIZE_0 = ISIZE_0 + 1
  PKD%DGMI%XFAPAR_BS => PKD%XBLOCK_0(:,ISIZE_0)
  ISIZE_0 = ISIZE_0 + 1
  PKD%DGMI%XFAPIR_BS => PKD%XBLOCK_0(:,ISIZE_0)
END IF
!
IF (I%O%CPHOTO/='NON') THEN
  ISIZE_ABC = ISIZE_ABC + 1
  PKD%GB%XIACAN => PKD%XBLOCK_ABC(:,:,ISIZE_ABC:ISIZE_ABC)
ELSE
  ISIZE_00 = ISIZE_00 + 1
  PKD%GB%XIACAN => PKD%XBLOCK_00(:,:,ISIZE_00:ISIZE_00)
END IF
!
IF (DGI%N2M>=1) THEN
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
  PKD%DGIP%XT2M         => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
  PKD%DGIP%XQ2M         => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
  PKD%DGIP%XHU2M        => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
  PKD%DGIP%XZON10M      => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
  PKD%DGIP%XMER10M      => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
ELSE
  ISIZE_0 = ISIZE_0 + 1
  PKD%DGIP%XT2M         => PKD%XBLOCK_0(:,ISIZE_0)
  ISIZE_0 = ISIZE_0 + 1
  PKD%DGIP%XQ2M         => PKD%XBLOCK_0(:,ISIZE_0)
  ISIZE_0 = ISIZE_0 + 1
  PKD%DGIP%XHU2M        => PKD%XBLOCK_0(:,ISIZE_0)
  ISIZE_0 = ISIZE_0 + 1
  PKD%DGIP%XZON10M      => PKD%XBLOCK_0(:,ISIZE_0)
  ISIZE_0 = ISIZE_0 + 1
  PKD%DGIP%XMER10M      => PKD%XBLOCK_0(:,ISIZE_0)
END IF
!
IF (DGMI%LSURF_MISC_BUDGET) THEN
  ISIZE_GROUND = ISIZE_GROUND + 1
  PKD%DGMI%XSWI          => PKD%XBLOCK_GROUND(:,:,ISIZE_GROUND)
  ISIZE_GROUND = ISIZE_GROUND + 1
  PKD%DGMI%XTSWI         => PKD%XBLOCK_GROUND(:,:,ISIZE_GROUND)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
  PKD%DGMI%XTWSNOW       => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
  PKD%DGMI%XTDSNOW       => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
ELSE
  ISIZE_00 = ISIZE_00 + 1
  PKD%DGMI%XSWI          => PKD%XBLOCK_00(:,:,ISIZE_00)
  ISIZE_00 = ISIZE_00 + 1
  PKD%DGMI%XTSWI         => PKD%XBLOCK_00(:,:,ISIZE_00)
  ISIZE_0 = ISIZE_0 + 1
  PKD%DGMI%XTWSNOW       => PKD%XBLOCK_0(:,ISIZE_0)
  ISIZE_0 = ISIZE_0 + 1
  PKD%DGMI%XTDSNOW       => PKD%XBLOCK_0(:,ISIZE_0)
ENDIF
!
IF(I%O%LGLACIER)THEN
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
  PKD%DGEIP%XICEFLUX=> PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
ELSE
  ISIZE_0 = ISIZE_0 + 1
  PKD%DGEIP%XICEFLUX=> PKD%XBLOCK_0(:,ISIZE_0)
ENDIF
!
! MEB STUFF START
IF (I%O%LMEB_PATCH(KPATCH))THEN
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
  PKD%DGEIP%XSWUP    => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
  PKD%DGEIP%XSWNET_V    => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
  PKD%DGEIP%XSWNET_G    => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
  PKD%DGEIP%XLWUP    => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
  PKD%DGEIP%XLWNET_V    => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
  PKD%DGEIP%XLWNET_G    => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
  PKD%DGEIP%XLEVCV    => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
  PKD%DGEIP%XLESC    => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
  PKD%DGEIP%XH_V_C    => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
  PKD%DGEIP%XH_G_C    => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
!  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
!  XP_LETRGV    => XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
  PKD%DGEIP%XLETRCV    => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
!  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
!  XP_LERGV    => XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
  PKD%DGEIP%XLELITTER    => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
  PKD%DGEIP%XLELITTERI    => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
  PKD%DGEIP%XDRIPLIT    => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
  PKD%DGEIP%XRRLIT    => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
  PKD%DGEIP%XLERCV    => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
  PKD%DGEIP%XH_C_A    => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
  PKD%DGEIP%XH_N_C    => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
  PKD%DGEIP%XLE_C_A    => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
  PKD%DGEIP%XLE_V_C    => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
  PKD%DGEIP%XLE_G_C    => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
  PKD%DGEIP%XLE_N_C    => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
  PKD%DGEIP%XEVAP_N_C    => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
  PKD%DGEIP%XEVAP_G_C    => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
  PKD%DGEIP%XSR_GN    => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
  PKD%DGEIP%XMELTCV    => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
  PKD%DGEIP%XFRZCV    => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
  PKD%DGEIP%XSWDOWN_GN    => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
  PKD%DGEIP%XLWDOWN_GN    => PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
ELSE
  ISIZE_0 = ISIZE_0 + 1
  PKD%DGEIP%XSWUP  => PKD%XBLOCK_0(:,ISIZE_0)
  ISIZE_0 = ISIZE_0 + 1
  PKD%DGEIP%XSWNET_V  => PKD%XBLOCK_0(:,ISIZE_0)
  ISIZE_0 = ISIZE_0 + 1
  PKD%DGEIP%XSWNET_G  => PKD%XBLOCK_0(:,ISIZE_0)
  ISIZE_0 = ISIZE_0 + 1
  PKD%DGEIP%XLWUP  => PKD%XBLOCK_0(:,ISIZE_0)
  ISIZE_0 = ISIZE_0 + 1
  PKD%DGEIP%XLWNET_V  => PKD%XBLOCK_0(:,ISIZE_0)
  ISIZE_0 = ISIZE_0 + 1
  PKD%DGEIP%XLWNET_G  => PKD%XBLOCK_0(:,ISIZE_0)
  ISIZE_0 = ISIZE_0 + 1
  PKD%DGEIP%XLEVCV  => PKD%XBLOCK_0(:,ISIZE_0)
  ISIZE_0 = ISIZE_0 + 1
  PKD%DGEIP%XLESC  => PKD%XBLOCK_0(:,ISIZE_0)
  ISIZE_0 = ISIZE_0 + 1
  PKD%DGEIP%XH_V_C  => PKD%XBLOCK_0(:,ISIZE_0)
  ISIZE_0 = ISIZE_0 + 1
  PKD%DGEIP%XH_G_C  => PKD%XBLOCK_0(:,ISIZE_0)
!  ISIZE_0 = ISIZE_0 + 1
!  XP_LETRGV  => XBLOCK_0(:,ISIZE_0)
  ISIZE_0 = ISIZE_0 + 1
  PKD%DGEIP%XLETRCV  => PKD%XBLOCK_0(:,ISIZE_0)
!  ISIZE_0 = ISIZE_0 + 1
!  XP_LERGV  => XBLOCK_0(:,ISIZE_0)
  ISIZE_0 = ISIZE_0 + 1
  PKD%DGEIP%XLELITTER  => PKD%XBLOCK_0(:,ISIZE_0)
  ISIZE_0 = ISIZE_0 + 1
  PKD%DGEIP%XLELITTERI  => PKD%XBLOCK_0(:,ISIZE_0)
  ISIZE_0 = ISIZE_0 + 1
  PKD%DGEIP%XDRIPLIT  => PKD%XBLOCK_0(:,ISIZE_0)
  ISIZE_0 = ISIZE_0 + 1
  PKD%DGEIP%XRRLIT  => PKD%XBLOCK_0(:,ISIZE_0)
  ISIZE_0 = ISIZE_0 + 1
  PKD%DGEIP%XLERCV  => PKD%XBLOCK_0(:,ISIZE_0)
  ISIZE_0 = ISIZE_0 + 1
  PKD%DGEIP%XH_C_A  => PKD%XBLOCK_0(:,ISIZE_0)
  ISIZE_0 = ISIZE_0 + 1
  PKD%DGEIP%XH_N_C  => PKD%XBLOCK_0(:,ISIZE_0)
  ISIZE_0 = ISIZE_0 + 1
  PKD%DGEIP%XLE_C_A  => PKD%XBLOCK_0(:,ISIZE_0)
  ISIZE_0 = ISIZE_0 + 1
  PKD%DGEIP%XLE_V_C  => PKD%XBLOCK_0(:,ISIZE_0)
  ISIZE_0 = ISIZE_0 + 1
  PKD%DGEIP%XLE_G_C  => PKD%XBLOCK_0(:,ISIZE_0)
  ISIZE_0 = ISIZE_0 + 1
  PKD%DGEIP%XLE_N_C  => PKD%XBLOCK_0(:,ISIZE_0)
  ISIZE_0 = ISIZE_0 + 1
  PKD%DGEIP%XEVAP_N_C  => PKD%XBLOCK_0(:,ISIZE_0)
  ISIZE_0 = ISIZE_0 + 1
  PKD%DGEIP%XEVAP_G_C  => PKD%XBLOCK_0(:,ISIZE_0)
  ISIZE_0 = ISIZE_0 + 1
  PKD%DGEIP%XSR_GN  => PKD%XBLOCK_0(:,ISIZE_0)
  ISIZE_0 = ISIZE_0 + 1
  PKD%DGEIP%XMELTCV  => PKD%XBLOCK_0(:,ISIZE_0)
  ISIZE_0 = ISIZE_0 + 1
  PKD%DGEIP%XFRZCV  => PKD%XBLOCK_0(:,ISIZE_0)
  ISIZE_0 = ISIZE_0 + 1
  PKD%DGEIP%XSWDOWN_GN  => PKD%XBLOCK_0(:,ISIZE_0)
  ISIZE_0 = ISIZE_0 + 1
  PKD%DGEIP%XLWDOWN_GN  => PKD%XBLOCK_0(:,ISIZE_0)
ENDIF
ISIZE_0 = ISIZE_0 + 1
PKD%DGEIP%XLETRGV  => PKD%XBLOCK_0(:,ISIZE_0)
ISIZE_0 = ISIZE_0 + 1
PKD%DGEIP%XLERGV  => PKD%XBLOCK_0(:,ISIZE_0)
!
IF(DGEI%LWATER_BUDGET)THEN
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
  PKD%DGEIP%XDWG=> PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
  PKD%DGEIP%XDWGI=> PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
  PKD%DGEIP%XDWR=> PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
  PKD%DGEIP%XDSWE=> PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)
  ISIZE_SIMPLE = ISIZE_SIMPLE + 1
  PKD%DGEIP%XWATBUD=> PKD%XBLOCK_SIMPLE(:,ISIZE_SIMPLE)  
ELSE
  ISIZE_0 = ISIZE_0 + 1
  PKD%DGEIP%XDWG=> PKD%XBLOCK_0(:,ISIZE_0) 
  ISIZE_0 = ISIZE_0 + 1
  PKD%DGEIP%XDWGI=> PKD%XBLOCK_0(:,ISIZE_0)
  ISIZE_0 = ISIZE_0 + 1
  PKD%DGEIP%XDWR=> PKD%XBLOCK_0(:,ISIZE_0)
  ISIZE_0 = ISIZE_0 + 1
  PKD%DGEIP%XDSWE=> PKD%XBLOCK_0(:,ISIZE_0)
  ISIZE_0 = ISIZE_0 + 1
  PKD%DGEIP%XWATBUD=> PKD%XBLOCK_0(:,ISIZE_0)
ENDIF
!
!
IF (ISIZE_SIMPLE.GT.PKD%NSIZE_SIMPLE) & 
  CALL ABOR1_SFX("PACK_DIAG_PATCH_n: PROBLEM DEFINING SIZE_SIMPLE / NUMBER OF FIELDS")
IF (ISIZE_GROUND.GT.PKD%NSIZE_GROUND) & 
  CALL ABOR1_SFX("PACK_DIAG_PATCH_n: PROBLEM DEFINING SIZE_GROUND / NUMBER OF FIELDS")
IF (ISIZE_SNOW.GT.PKD%NSIZE_SNOW) & 
  CALL ABOR1_SFX("PACK_DIAG_PATCH_n: PROBLEM DEFINING SIZE_SNOW / NUMBER OF FIELDS")
IF (ISIZE_KSW.GT.PKD%NSIZE_KSW) & 
  CALL ABOR1_SFX("PACK_DIAG_PATCH_n: PROBLEM DEFINING SIZE_KSW / NUMBER OF FIELDS")
IF (ISIZE_ABC.GT.PKD%NSIZE_ABC) & 
  CALL ABOR1_SFX("PACK_DIAG_PATCH_n: PROBLEM DEFINING SIZE_3 / NUMBER OF FIELDS")
IF (ISIZE_0.GT.PKD%NSIZE_0) & 
  CALL ABOR1_SFX("PACK_DIAG_PATCH_n: PROBLEM DEFINING SIZE_0 / NUMBER OF FIELDS")
IF (ISIZE_00.GT.PKD%NSIZE_00) & 
  CALL ABOR1_SFX("PACK_DIAG_PATCH_n: PROBLEM DEFINING SIZE_00 / NUMBER OF FIELDS") 
!
IF (LHOOK) CALL DR_HOOK('PACK_DIAG_PATCH_N',1,ZHOOK_HANDLE)
!------------------------------------------------------------------------
!
END SUBROUTINE PACK_DIAG_PATCH_n
