!     #########
      SUBROUTINE READ_PGD_ISBA_PAR_n (DTCO, U, DTV, KDIM, IO, &
                                      HPROGRAM,KSIZE,OLAND_USE,HDIR)
!     ################################################
!
!!****  *READ_PGD_ISBA_PAR_n* - reads ISBA physiographic fields                     
!!
!!    PURPOSE
!!    -------²
!!
!!**  METHOD
!!    ------
!!
!!    EXTERNAL
!!    --------
!!
!!
!!    IMPLICIT ARGUMENTS
!!    ------------------
!!
!!    REFERENCE
!!    ---------
!!
!!
!!    AUTHOR
!!    ------
!!      V. Masson   *Meteo France*
!!
!!    MODIFICATIONS
!!    -------------
!!      Original    01/2003 
!!      P. Le Moigne 12/2004 : add type of photosynthesis 
!!      P. Samuelsson 02/2012 : MEB
!-------------------------------------------------------------------------------
!
!*       0.    DECLARATIONS
!              ------------
!
!
!
!
!
USE MODD_DATA_COVER_n, ONLY : DATA_COVER_t
USE MODD_SURF_ATM_n, ONLY : SURF_ATM_t
!
USE MODD_DATA_ISBA_n, ONLY : DATA_ISBA_t
USE MODD_ISBA_OPTIONS_n, ONLY : ISBA_OPTIONS_t
!
USE MODD_ASSIM, ONLY : LREAD_ALL, LASSIM
!
USE MODD_DATA_COVER_PAR, ONLY : NVEGTYPE
USE MODD_PREP,           ONLY : LINTERP
!
!
USE MODI_GET_LUOUT
USE MODI_READ_SURF
USE MODI_HOR_INTERPOL
USE MODI_READ_SURF_ISBA_PAR_n
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE
!
!*       0.1   Declarations of arguments
!              -------------------------
!
!
!
TYPE(DATA_COVER_t), INTENT(INOUT) :: DTCO
TYPE(SURF_ATM_t), INTENT(INOUT) :: U
!
TYPE(DATA_ISBA_t), INTENT(INOUT) :: DTV
INTEGER, INTENT(IN) :: KDIM
TYPE(ISBA_OPTIONS_t), INTENT(INOUT) :: IO
!
CHARACTER(LEN=6),  INTENT(IN)  :: HPROGRAM ! program calling
INTEGER,           INTENT(IN)  :: KSIZE
LOGICAL,           INTENT(IN)  :: OLAND_USE ! 
CHARACTER(LEN=1),OPTIONAL,INTENT(IN)  :: HDIR       ! type of field :
!                                                   ! 'H' : field with
!                                                   !       horizontal spatial dim.
!                                                   ! '-' : no horizontal dim.
!
!*       0.2   Declarations of local variables
!              -------------------------------
!
REAL, DIMENSION(KSIZE,NVEGTYPE) :: ZFIELD
REAL,    DIMENSION(:,:), ALLOCATABLE :: ZWORK
INTEGER           :: ILUOUT
INTEGER           :: ITIME
INTEGER           :: IRESP          ! IRESP  : return-code if a problem appears
CHARACTER(LEN=12) :: YRECFM         ! Name of the article to be read
CHARACTER(LEN=16) :: YRECFM2
CHARACTER(LEN=100):: YCOMMENT       ! Comment string
CHARACTER(LEN=1)  :: YDIR
INTEGER           :: JTIME          ! loop index
INTEGER           :: JLAYER         ! loop index
INTEGER           :: JPATCH         ! loop index
INTEGER           :: IVERSION       ! surface version
INTEGER           :: IBUGFIX
INTEGER           :: ISIZE_LMEB_PATCH
!
LOGICAL :: GREAD_ALL
!
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
!-------------------------------------------------------------------------------
!
IF (LHOOK) CALL DR_HOOK('READ_PGD_ISBA_PAR_N',0,ZHOOK_HANDLE)
!
CALL GET_LUOUT(HPROGRAM,ILUOUT)
!
YDIR = 'H'
IF (PRESENT(HDIR)) YDIR = HDIR
!
IF (LASSIM) THEN
  GREAD_ALL = LREAD_ALL
  LREAD_ALL = .TRUE.
ENDIF
!
YRECFM='VERSION'
CALL READ_SURF(HPROGRAM,YRECFM,IVERSION,IRESP)
WRITE(ILUOUT,*) 'read version ',IVERSION
!
YRECFM='BUG'
CALL READ_SURF(HPROGRAM,YRECFM,IBUGFIX,IRESP)
!
ISIZE_LMEB_PATCH=COUNT(IO%LMEB_PATCH(:))
!
DTV%LDATA_MIXPAR = .FALSE. 
!
IF (IVERSION<7 .AND. .NOT.IO%LECOCLIMAP) THEN
  !
  DTV%LDATA_VEGTYPE=.TRUE.
  DTV%LDATA_VEG=.TRUE.
  DTV%LDATA_LAI=.TRUE.
  DTV%LDATA_Z0=.TRUE.
  DTV%LDATA_EMIS=.TRUE.
  DTV%LDATA_RSMIN=.TRUE.
  DTV%LDATA_GAMMA=.TRUE.
  DTV%LDATA_WRMAX_CF=.TRUE.
  DTV%LDATA_RGL=.TRUE.
  DTV%LDATA_CV=.TRUE.
  DTV%LDATA_Z0_O_Z0H=.TRUE.
  DTV%LDATA_DG=.TRUE.
  DTV%LDATA_ROOTFRAC=.TRUE.
  !
  DTV%LDATA_DICE=.FALSE.
  DTV%LDATA_GROUND_DEPTH=.FALSE.
  DTV%LDATA_ROOT_DEPTH=.FALSE.
  DTV%LDATA_ROOT_LIN=.FALSE.
  DTV%LDATA_ROOT_EXTINCTION=.FALSE.  
  !
  DTV%LDATA_ALBNIR_VEG=.TRUE.
  DTV%LDATA_ALBVIS_VEG=.TRUE.
  DTV%LDATA_ALBUV_VEG=.TRUE.
  DTV%LDATA_ALBNIR_SOIL=.TRUE.
  DTV%LDATA_ALBVIS_SOIL=.TRUE.
  DTV%LDATA_ALBUV_SOIL=.TRUE.
  DTV%LDATA_GMES=.TRUE.
  DTV%LDATA_BSLAI=.TRUE.
  DTV%LDATA_LAIMIN=.TRUE.
  DTV%LDATA_SEFOLD=.TRUE.
  DTV%LDATA_GC=.TRUE.
  DTV%LDATA_DMAX=.TRUE.
  DTV%LDATA_F2I=.TRUE.
  DTV%LDATA_STRESS=.TRUE.
  DTV%LDATA_H_TREE=.TRUE.
  DTV%LDATA_RE25=.TRUE.
  DTV%LDATA_CE_NITRO=.TRUE.
  DTV%LDATA_CF_NITRO=.TRUE.
  DTV%LDATA_CNA_NITRO=.TRUE.
  !
  DTV%LDATA_IRRIG=.FALSE.
  DTV%LDATA_WATSUP=.FALSE.
  !
ENDIF
!
IF ((IVERSION<8.AND..NOT.IO%LECOCLIMAP).OR.ISIZE_LMEB_PATCH==0.0) THEN
  !
  DTV%LDATA_GNDLITTER=.FALSE.
  DTV%LDATA_Z0LITTER=.FALSE.
  DTV%LDATA_H_VEG=.FALSE.
  !
ENDIF
!
IF (.NOT.OLAND_USE) THEN
  !
  IF (IVERSION>=7) THEN
    !
    YRECFM='L_VEGTYPE'
    YCOMMENT=YRECFM
    CALL READ_SURF(HPROGRAM,YRECFM,DTV%LDATA_VEGTYPE,IRESP,HCOMMENT=YCOMMENT)
    IF (DTV%LDATA_VEGTYPE) DTV%LDATA_MIXPAR = .TRUE.
    !
    YRECFM='L_VEG'
    YCOMMENT=YRECFM
    CALL READ_SURF(HPROGRAM,YRECFM,DTV%LDATA_VEG,IRESP,HCOMMENT=YCOMMENT)
    IF (DTV%LDATA_VEG) DTV%LDATA_MIXPAR = .TRUE.
    YRECFM='L_LAI'
    YCOMMENT=YRECFM
    CALL READ_SURF(HPROGRAM,YRECFM,DTV%LDATA_LAI,IRESP,HCOMMENT=YCOMMENT)
    IF (DTV%LDATA_LAI) DTV%LDATA_MIXPAR = .TRUE.
    YRECFM='L_Z0'
    YCOMMENT=YRECFM
    CALL READ_SURF(HPROGRAM,YRECFM,DTV%LDATA_Z0,IRESP,HCOMMENT=YCOMMENT)
    IF (DTV%LDATA_Z0) DTV%LDATA_MIXPAR = .TRUE.
    YRECFM='L_EMIS'
    YCOMMENT=YRECFM
    CALL READ_SURF(HPROGRAM,YRECFM,DTV%LDATA_EMIS,IRESP,HCOMMENT=YCOMMENT)
    IF (DTV%LDATA_EMIS) DTV%LDATA_MIXPAR = .TRUE.
    !
    YRECFM='L_RSMIN'
    YCOMMENT=YRECFM
    CALL READ_SURF(HPROGRAM,YRECFM,DTV%LDATA_RSMIN,IRESP,HCOMMENT=YCOMMENT)
    IF (DTV%LDATA_RSMIN) DTV%LDATA_MIXPAR = .TRUE.
    YRECFM='L_GAMMA'
    YCOMMENT=YRECFM
    CALL READ_SURF(HPROGRAM,YRECFM,DTV%LDATA_GAMMA,IRESP,HCOMMENT=YCOMMENT)
    IF (DTV%LDATA_GAMMA) DTV%LDATA_MIXPAR = .TRUE.
    YRECFM='L_WRMAX_CF'
    YCOMMENT=YRECFM
    CALL READ_SURF(HPROGRAM,YRECFM,DTV%LDATA_WRMAX_CF,IRESP,HCOMMENT=YCOMMENT)
    IF (DTV%LDATA_WRMAX_CF) DTV%LDATA_MIXPAR = .TRUE.
    YRECFM='L_RGL'
    YCOMMENT=YRECFM
    CALL READ_SURF(HPROGRAM,YRECFM,DTV%LDATA_RGL,IRESP,HCOMMENT=YCOMMENT)
    IF (DTV%LDATA_RGL) DTV%LDATA_MIXPAR = .TRUE.
    YRECFM='L_CV'
    YCOMMENT=YRECFM
    CALL READ_SURF(HPROGRAM,YRECFM,DTV%LDATA_CV,IRESP,HCOMMENT=YCOMMENT)
    IF (DTV%LDATA_CV) DTV%LDATA_MIXPAR = .TRUE.
    YRECFM='L_Z0_O_Z0H'
    YCOMMENT=YRECFM
    CALL READ_SURF(HPROGRAM,YRECFM,DTV%LDATA_Z0_O_Z0H,IRESP,HCOMMENT=YCOMMENT)
    IF (DTV%LDATA_Z0_O_Z0H) DTV%LDATA_MIXPAR = .TRUE.
    YRECFM='L_DG'
    YCOMMENT=YRECFM
    CALL READ_SURF(HPROGRAM,YRECFM,DTV%LDATA_DG,IRESP,HCOMMENT=YCOMMENT)
    IF (DTV%LDATA_DG) DTV%LDATA_MIXPAR = .TRUE.
    YRECFM='L_ROOTFRAC'
    YCOMMENT=YRECFM
    CALL READ_SURF(HPROGRAM,YRECFM,DTV%LDATA_ROOTFRAC,IRESP,HCOMMENT=YCOMMENT)
    IF (DTV%LDATA_ROOTFRAC) DTV%LDATA_MIXPAR = .TRUE.
    YRECFM='L_DICE'
    YCOMMENT=YRECFM
    CALL READ_SURF(HPROGRAM,YRECFM,DTV%LDATA_DICE,IRESP,HCOMMENT=YCOMMENT)
    IF (DTV%LDATA_DICE) DTV%LDATA_MIXPAR = .TRUE.
    !
    IF ( (IVERSION==7 .AND. IBUGFIX>=2) .OR. IVERSION>7 ) THEN
      YRECFM2='L_GROUND_DPT'
      YCOMMENT=YRECFM
      CALL READ_SURF(HPROGRAM,YRECFM2,DTV%LDATA_GROUND_DEPTH,IRESP,HCOMMENT=YCOMMENT)
      IF (DTV%LDATA_GROUND_DEPTH) DTV%LDATA_MIXPAR = .TRUE.
      YRECFM='L_ROOT_DEPTH'
      YCOMMENT=YRECFM
      CALL READ_SURF(HPROGRAM,YRECFM,DTV%LDATA_ROOT_DEPTH,IRESP,HCOMMENT=YCOMMENT)
      IF (DTV%LDATA_ROOT_DEPTH) DTV%LDATA_MIXPAR = .TRUE.
      YRECFM='L_ROOT_EXT'
      YCOMMENT=YRECFM
      CALL READ_SURF(HPROGRAM,YRECFM,DTV%LDATA_ROOT_EXTINCTION,IRESP,HCOMMENT=YCOMMENT)
      IF (DTV%LDATA_ROOT_EXTINCTION) DTV%LDATA_MIXPAR = .TRUE.
      YRECFM='L_ROOT_LIN'
      YCOMMENT=YRECFM
      CALL READ_SURF(HPROGRAM,YRECFM,DTV%LDATA_ROOT_LIN,IRESP,HCOMMENT=YCOMMENT)
      IF (DTV%LDATA_ROOT_LIN) DTV%LDATA_MIXPAR = .TRUE.
    ELSE
      DTV%LDATA_GROUND_DEPTH = .FALSE.
      DTV%LDATA_ROOT_DEPTH   = .FALSE.
      DTV%LDATA_ROOT_EXTINCTION = .FALSE.
      DTV%LDATA_ROOT_LIN = .FALSE.
    ENDIF
    !
    YRECFM='L_ALBNIR_VEG'
    YCOMMENT=YRECFM
    CALL READ_SURF(HPROGRAM,YRECFM,DTV%LDATA_ALBNIR_VEG,IRESP,HCOMMENT=YCOMMENT)
    IF (DTV%LDATA_ALBNIR_VEG) DTV%LDATA_MIXPAR = .TRUE.
    YRECFM='L_ALBVIS_VEG'
    YCOMMENT=YRECFM
    CALL READ_SURF(HPROGRAM,YRECFM,DTV%LDATA_ALBVIS_VEG,IRESP,HCOMMENT=YCOMMENT)
    IF (DTV%LDATA_ALBVIS_VEG) DTV%LDATA_MIXPAR = .TRUE.
    YRECFM='L_ALBUV_VEG'
    YCOMMENT=YRECFM
    CALL READ_SURF(HPROGRAM,YRECFM,DTV%LDATA_ALBUV_VEG,IRESP,HCOMMENT=YCOMMENT)
    IF (DTV%LDATA_ALBUV_VEG) DTV%LDATA_MIXPAR = .TRUE.
    YRECFM='L_ALBNIR_SOI'
    YCOMMENT=YRECFM
    CALL READ_SURF(HPROGRAM,YRECFM,DTV%LDATA_ALBNIR_SOIL,IRESP,HCOMMENT=YCOMMENT)
    IF (DTV%LDATA_ALBNIR_SOIL) DTV%LDATA_MIXPAR = .TRUE.
    YRECFM='L_ALBVIS_SOI'
    YCOMMENT=YRECFM
    CALL READ_SURF(HPROGRAM,YRECFM,DTV%LDATA_ALBVIS_SOIL,IRESP,HCOMMENT=YCOMMENT)
    IF (DTV%LDATA_ALBVIS_SOIL) DTV%LDATA_MIXPAR = .TRUE.
    YRECFM='L_ALBUV_SOI'
    YCOMMENT=YRECFM
    CALL READ_SURF(HPROGRAM,YRECFM,DTV%LDATA_ALBUV_SOIL,IRESP,HCOMMENT=YCOMMENT)
    IF (DTV%LDATA_ALBUV_SOIL) DTV%LDATA_MIXPAR = .TRUE.
    YRECFM='L_GMES'
    YCOMMENT=YRECFM
    CALL READ_SURF(HPROGRAM,YRECFM,DTV%LDATA_GMES,IRESP,HCOMMENT=YCOMMENT)
    IF (DTV%LDATA_GMES) DTV%LDATA_MIXPAR = .TRUE.
    YRECFM='L_BSLAI'
    YCOMMENT=YRECFM
    CALL READ_SURF(HPROGRAM,YRECFM,DTV%LDATA_BSLAI,IRESP,HCOMMENT=YCOMMENT)
    IF (DTV%LDATA_BSLAI) DTV%LDATA_MIXPAR = .TRUE.
    YRECFM='L_LAIMIN'
    YCOMMENT=YRECFM
    CALL READ_SURF(HPROGRAM,YRECFM,DTV%LDATA_LAIMIN,IRESP,HCOMMENT=YCOMMENT)
    IF (DTV%LDATA_LAIMIN) DTV%LDATA_MIXPAR = .TRUE.
    YRECFM='L_SEFOLD'
    YCOMMENT=YRECFM
    CALL READ_SURF(HPROGRAM,YRECFM,DTV%LDATA_SEFOLD,IRESP,HCOMMENT=YCOMMENT)
    IF (DTV%LDATA_SEFOLD) DTV%LDATA_MIXPAR = .TRUE.
    YRECFM='L_GC'
    YCOMMENT=YRECFM
    CALL READ_SURF(HPROGRAM,YRECFM,DTV%LDATA_GC,IRESP,HCOMMENT=YCOMMENT)
    IF (DTV%LDATA_GC) DTV%LDATA_MIXPAR = .TRUE.
    YRECFM='L_DMAX'
    YCOMMENT=YRECFM
    CALL READ_SURF(HPROGRAM,YRECFM,DTV%LDATA_DMAX,IRESP,HCOMMENT=YCOMMENT)
    IF (DTV%LDATA_DMAX) DTV%LDATA_MIXPAR = .TRUE.
    YRECFM='L_F2I'
    YCOMMENT=YRECFM
    CALL READ_SURF(HPROGRAM,YRECFM,DTV%LDATA_F2I,IRESP,HCOMMENT=YCOMMENT)
    IF (DTV%LDATA_F2I) DTV%LDATA_MIXPAR = .TRUE.
    YRECFM='L_STRESS'
    YCOMMENT=YRECFM
    CALL READ_SURF(HPROGRAM,YRECFM,DTV%LDATA_STRESS,IRESP,HCOMMENT=YCOMMENT)
    IF (DTV%LDATA_STRESS) DTV%LDATA_MIXPAR = .TRUE.
    YRECFM='L_H_TREE'
    YCOMMENT=YRECFM
    CALL READ_SURF(HPROGRAM,YRECFM,DTV%LDATA_H_TREE,IRESP,HCOMMENT=YCOMMENT)
    IF (DTV%LDATA_H_TREE) DTV%LDATA_MIXPAR = .TRUE.
    YRECFM='L_RE25'
    YCOMMENT=YRECFM
    CALL READ_SURF(HPROGRAM,YRECFM,DTV%LDATA_RE25,IRESP,HCOMMENT=YCOMMENT)
    IF (DTV%LDATA_RE25) DTV%LDATA_MIXPAR = .TRUE.
    YRECFM='L_CE_NITRO'
    YCOMMENT=YRECFM
    CALL READ_SURF(HPROGRAM,YRECFM,DTV%LDATA_CE_NITRO,IRESP,HCOMMENT=YCOMMENT)
    IF (DTV%LDATA_CE_NITRO) DTV%LDATA_MIXPAR = .TRUE.
    YRECFM='L_CF_NITRO'
    YCOMMENT=YRECFM
    CALL READ_SURF(HPROGRAM,YRECFM,DTV%LDATA_CF_NITRO,IRESP,HCOMMENT=YCOMMENT)
    IF (DTV%LDATA_CF_NITRO) DTV%LDATA_MIXPAR = .TRUE.
    YRECFM='L_CNA_NITRO'
    YCOMMENT=YRECFM
    CALL READ_SURF(HPROGRAM,YRECFM,DTV%LDATA_CNA_NITRO,IRESP,HCOMMENT=YCOMMENT)
    IF (DTV%LDATA_CNA_NITRO) DTV%LDATA_MIXPAR = .TRUE.
    YRECFM='L_IRRIG'
    YCOMMENT=YRECFM
    CALL READ_SURF(HPROGRAM,YRECFM,DTV%LDATA_IRRIG,IRESP,HCOMMENT=YCOMMENT)
    IF (DTV%LDATA_IRRIG) DTV%LDATA_MIXPAR = .TRUE.
    YRECFM='L_WATSUP'
    YCOMMENT=YRECFM
    CALL READ_SURF(HPROGRAM,YRECFM,DTV%LDATA_WATSUP,IRESP,HCOMMENT=YCOMMENT)
    IF (DTV%LDATA_WATSUP) DTV%LDATA_MIXPAR = .TRUE.
    !
  ENDIF
  !
  IF (IVERSION>=8.AND.ISIZE_LMEB_PATCH>0) THEN
    !
    YRECFM='L_H_VEG'
    YCOMMENT=YRECFM
    CALL READ_SURF(HPROGRAM,YRECFM,DTV%LDATA_H_VEG,IRESP,HCOMMENT=YCOMMENT)
    IF (DTV%LDATA_H_VEG) DTV%LDATA_MIXPAR = .TRUE.
    YRECFM='L_Z0LITTER'
    YCOMMENT=YRECFM
    CALL READ_SURF(HPROGRAM,YRECFM,DTV%LDATA_Z0LITTER,IRESP,HCOMMENT=YCOMMENT)
    IF (DTV%LDATA_Z0LITTER) DTV%LDATA_MIXPAR = .TRUE.
    YRECFM='L_GNDLITTER'
    YCOMMENT=YRECFM
    CALL READ_SURF(HPROGRAM,YRECFM,DTV%LDATA_GNDLITTER,IRESP,HCOMMENT=YCOMMENT)
    IF (DTV%LDATA_GNDLITTER) DTV%LDATA_MIXPAR = .TRUE.
    !
  ELSE
    !
    DTV%LDATA_GNDLITTER=.FALSE.
    DTV%LDATA_Z0LITTER=.FALSE.
    DTV%LDATA_H_VEG=.FALSE.
    !
  ENDIF          
  !
  IF (ALLOCATED(LINTERP)) LINTERP(:) = .TRUE.
  !
  IF (DTV%LDATA_VEGTYPE) THEN
    YRECFM='D_VEGTYPE'
    CALL READ_SURF(HPROGRAM,YRECFM,ZFIELD(:,:),IRESP,HCOMMENT=YCOMMENT,HDIR=YDIR)
    ALLOCATE(DTV%XPAR_VEGTYPE   (KDIM,NVEGTYPE))
    IF (KDIM/=KSIZE) THEN
      CALL HOR_INTERPOL(DTCO, U, ILUOUT,ZFIELD,DTV%XPAR_VEGTYPE)
    ELSE
      DTV%XPAR_VEGTYPE(:,:) = ZFIELD(:,:)
    ENDIF
  ENDIF
!
  IF (DTV%LDATA_LAI .OR. DTV%LDATA_VEG .OR. DTV%LDATA_Z0 .OR. DTV%LDATA_EMIS) THEN
    YRECFM='NDATA_TIME'
    CALL READ_SURF(HPROGRAM,YRECFM,DTV%NTIME,IRESP,HCOMMENT=YCOMMENT)
    ITIME = DTV%NTIME
  ELSE
    DTV%NTIME = 1
  ENDIF
!  
  IF (DTV%LDATA_VEG) THEN
    ALLOCATE(DTV%XPAR_VEG(KDIM,DTV%NTIME,NVEGTYPE))           
    DO JTIME=1,ITIME
      WRITE(YRECFM,FMT='(A7,I2.2)') 'D_VEG_T',JTIME
      CALL READ_SURF_ISBA_PAR_n(DTCO, U, IO%NPATCH, &
                                HPROGRAM,YRECFM,ILUOUT,KSIZE,DTV%XPAR_VEG(:,JTIME,:),IRESP,IVERSION,&
                                HCOMMENT=YCOMMENT,HDIR=YDIR)       
    END DO
  ENDIF
!
  IF (DTV%LDATA_LAI) THEN
    ALLOCATE(DTV%XPAR_LAI(KDIM,DTV%NTIME,NVEGTYPE))
    DO JTIME=1,ITIME
      WRITE(YRECFM,FMT='(A7,I2.2)') 'D_LAI_T',JTIME
      CALL READ_SURF_ISBA_PAR_n(DTCO, U, IO%NPATCH, &
                                HPROGRAM,YRECFM,ILUOUT,KSIZE,DTV%XPAR_LAI(:,JTIME,:),IRESP,IVERSION,&
                                HCOMMENT=YCOMMENT,HDIR=YDIR)
    END DO
  ENDIF
!
  IF (DTV%LDATA_H_VEG) THEN
    ALLOCATE(DTV%XPAR_H_VEG(KDIM,DTV%NTIME,NVEGTYPE))
    DO JTIME=1,ITIME
      WRITE(YRECFM,FMT='(A9,I2.2)') 'D_H_VEG_T',JTIME
      CALL READ_SURF_ISBA_PAR_n(DTCO, U, IO%NPATCH, &
                                HPROGRAM,YRECFM,ILUOUT,KSIZE,DTV%XPAR_H_VEG(:,JTIME,:),IRESP,IVERSION,&
                                HCOMMENT=YCOMMENT,HDIR=YDIR)
    END DO
  ENDIF
!
  IF (DTV%LDATA_GNDLITTER) THEN
    ALLOCATE(DTV%XPAR_GNDLITTER(KDIM,DTV%NTIME,NVEGTYPE))
    DO JTIME=1,ITIME
      WRITE(YRECFM,FMT='(A7,I2.2)') 'D_GNDLITTER',JTIME
      CALL READ_SURF_ISBA_PAR_n(DTCO, U, IO%NPATCH, &
                                HPROGRAM,YRECFM,ILUOUT,KSIZE,DTV%XPAR_GNDLITTER(:,JTIME,:),IRESP,IVERSION,&
                                HCOMMENT=YCOMMENT,HDIR=YDIR)
    END DO
  ENDIF
!
  IF (DTV%LDATA_Z0) THEN
    ALLOCATE(DTV%XPAR_Z0        (KDIM,DTV%NTIME,NVEGTYPE))
    DO JTIME=1,ITIME
      WRITE(YRECFM,FMT='(A6,I2.2)') 'D_Z0_T',JTIME
      CALL READ_SURF_ISBA_PAR_n(DTCO, U, IO%NPATCH, &
                                HPROGRAM,YRECFM,ILUOUT,KSIZE,DTV%XPAR_Z0(:,JTIME,:),IRESP,IVERSION,&
                                HCOMMENT=YCOMMENT,HDIR=YDIR)
    END DO
  ENDIF
!
  IF (DTV%LDATA_Z0LITTER) THEN
    ALLOCATE(DTV%XPAR_Z0LITTER        (KDIM,DTV%NTIME,NVEGTYPE))
    DO JTIME=1,ITIME
      WRITE(YRECFM,FMT='(A8,I2.2)') 'D_Z0LITTER_T',JTIME
      CALL READ_SURF_ISBA_PAR_n(DTCO, U, IO%NPATCH, &
                                HPROGRAM,YRECFM,ILUOUT,KSIZE,DTV%XPAR_Z0LITTER(:,JTIME,:),IRESP,IVERSION,&
                                HCOMMENT=YCOMMENT,HDIR=YDIR)
    END DO
  ENDIF
!
  IF (DTV%LDATA_EMIS) THEN
    ALLOCATE(DTV%XPAR_EMIS      (KDIM,DTV%NTIME,NVEGTYPE))
    DO JTIME=1,ITIME
      WRITE(YRECFM,FMT='(A8,I2.2)') 'D_EMIS_T',JTIME
      CALL READ_SURF_ISBA_PAR_n(DTCO, U, IO%NPATCH, &
                                HPROGRAM,YRECFM,ILUOUT,KSIZE,DTV%XPAR_EMIS(:,JTIME,:),IRESP,IVERSION,&
                                HCOMMENT=YCOMMENT,HDIR=YDIR)
    END DO
  ENDIF
!
  IF (DTV%LDATA_RSMIN) THEN
    ALLOCATE(DTV%XPAR_RSMIN     (KDIM,NVEGTYPE))
    YRECFM='D_RSMIN'
    CALL READ_SURF_ISBA_PAR_n(DTCO, U, IO%NPATCH, &
                                HPROGRAM,YRECFM,ILUOUT,KSIZE,DTV%XPAR_RSMIN(:,:),IRESP,IVERSION,&
                              HCOMMENT=YCOMMENT,HDIR=YDIR)
  ENDIF
!
  IF (DTV%LDATA_GAMMA) THEN
    ALLOCATE(DTV%XPAR_GAMMA     (KDIM,NVEGTYPE))
    YRECFM='D_GAMMA'
    CALL READ_SURF_ISBA_PAR_n(DTCO, U, IO%NPATCH, &
                                HPROGRAM,YRECFM,ILUOUT,KSIZE,DTV%XPAR_GAMMA(:,:),IRESP,IVERSION,&
                              HCOMMENT=YCOMMENT,HDIR=YDIR)
  ENDIF
!
  IF (DTV%LDATA_WRMAX_CF) THEN
    ALLOCATE(DTV%XPAR_WRMAX_CF  (KDIM,NVEGTYPE))
    YRECFM='D_WRMAX_CF'
    CALL READ_SURF_ISBA_PAR_n(DTCO, U, IO%NPATCH, &
                                HPROGRAM,YRECFM,ILUOUT,KSIZE,DTV%XPAR_WRMAX_CF(:,:),IRESP,IVERSION,&
                              HCOMMENT=YCOMMENT,HDIR=YDIR)
  ENDIF
!
  IF (DTV%LDATA_RGL) THEN
    ALLOCATE(DTV%XPAR_RGL       (KDIM,NVEGTYPE))
    YRECFM='D_RGL'
    CALL READ_SURF_ISBA_PAR_n(DTCO, U, IO%NPATCH, &
                                HPROGRAM,YRECFM,ILUOUT,KSIZE,DTV%XPAR_RGL(:,:),IRESP,IVERSION,&
                              HCOMMENT=YCOMMENT,HDIR=YDIR)
  ENDIF
!
  IF (DTV%LDATA_CV) THEN
    ALLOCATE(DTV%XPAR_CV        (KDIM,NVEGTYPE))
    YRECFM='D_CV'
    CALL READ_SURF_ISBA_PAR_n(DTCO, U, IO%NPATCH, &
                                HPROGRAM,YRECFM,ILUOUT,KSIZE,DTV%XPAR_CV(:,:),IRESP,IVERSION,&
                              HCOMMENT=YCOMMENT,HDIR=YDIR)
  ENDIF
!
  IF (DTV%LDATA_Z0_O_Z0H) THEN
    ALLOCATE(DTV%XPAR_Z0_O_Z0H  (KDIM,NVEGTYPE))
    YRECFM='D_Z0_O_Z0H'
    CALL READ_SURF_ISBA_PAR_n(DTCO, U, IO%NPATCH, &
                                HPROGRAM,YRECFM,ILUOUT,KSIZE,DTV%XPAR_Z0_O_Z0H(:,:),IRESP,IVERSION,&
                              HCOMMENT=YCOMMENT,HDIR=YDIR)
  ENDIF
!
  IF (DTV%LDATA_DG) THEN
    ALLOCATE(DTV%XPAR_DG        (KDIM,IO%NGROUND_LAYER,NVEGTYPE))
    ALLOCATE(ZWORK(SIZE(DTV%XPAR_DG,1),SIZE(DTV%XPAR_DG,3)))
    DO JLAYER=1,SIZE(DTV%XPAR_DG,2)
      IF (JLAYER<10)  WRITE(YRECFM,FMT='(A4,I1.1)') 'D_DG',JLAYER
      IF (JLAYER>=10) WRITE(YRECFM,FMT='(A4,I2.2)') 'D_DG',JLAYER
      CALL READ_SURF_ISBA_PAR_n(DTCO, U, IO%NPATCH, &
                                HPROGRAM,YRECFM,ILUOUT,KSIZE,ZWORK,IRESP,IVERSION,&
                                HCOMMENT=YCOMMENT,HDIR=YDIR)
      DO JPATCH=1,SIZE(DTV%XPAR_DG,3)
        DTV%XPAR_DG(:,JLAYER,JPATCH) = ZWORK(:,JPATCH)
      END DO
    END DO
    DEALLOCATE(ZWORK)
  ENDIF
!
  IF (DTV%LDATA_ROOTFRAC) THEN
    ALLOCATE(DTV%XPAR_ROOTFRAC  (KDIM,IO%NGROUND_LAYER,NVEGTYPE))
    ALLOCATE(ZWORK(SIZE(DTV%XPAR_ROOTFRAC,1),SIZE(DTV%XPAR_ROOTFRAC,3)))
    DO JLAYER=1,SIZE(DTV%XPAR_ROOTFRAC,2)
      IF (JLAYER<10)  WRITE(YRECFM,FMT='(A10,I1.1)') 'D_ROOTFRAC',JLAYER
      IF (JLAYER>=10) WRITE(YRECFM,FMT='(A10,I2.2)') 'D_ROOTFRAC',JLAYER
        CALL READ_SURF_ISBA_PAR_n(DTCO, U, IO%NPATCH, &
                                HPROGRAM,YRECFM,ILUOUT,KSIZE,ZWORK,IRESP,IVERSION,&
                                  HCOMMENT=YCOMMENT,HDIR=YDIR)
      DO JPATCH=1,SIZE(DTV%XPAR_ROOTFRAC,3)
        DTV%XPAR_ROOTFRAC(:,JLAYER,JPATCH) = ZWORK(:,JPATCH)
      END DO
    END DO
    DEALLOCATE(ZWORK)
  ENDIF
!
  IF (DTV%LDATA_DICE) THEN
    ALLOCATE(DTV%XPAR_DICE      (KDIM,NVEGTYPE))
    YRECFM='D_DICE'
    CALL READ_SURF_ISBA_PAR_n(DTCO, U, IO%NPATCH, &
                                HPROGRAM,YRECFM,ILUOUT,KSIZE,DTV%XPAR_DICE(:,:),IRESP,IVERSION,&
                              HCOMMENT=YCOMMENT,HDIR=YDIR)
  ENDIF
!
  IF (DTV%LDATA_GROUND_DEPTH) THEN
    ALLOCATE(DTV%XPAR_GROUND_DEPTH(KDIM,NVEGTYPE))
    YRECFM2='D_GROUND_DEPTH'
    IF (IVERSION>7 .OR. IVERSION==7 .AND. IBUGFIX>=3) YRECFM2='D_GROUND_DPT'
    CALL READ_SURF_ISBA_PAR_n(DTCO, U, IO%NPATCH, &
                                HPROGRAM,YRECFM2,ILUOUT,KSIZE,DTV%XPAR_GROUND_DEPTH(:,:),IRESP,IVERSION,&
                              HCOMMENT=YCOMMENT,HDIR=YDIR)
  ENDIF
!
  IF (DTV%LDATA_ROOT_DEPTH) THEN
    ALLOCATE(DTV%XPAR_ROOT_DEPTH(KDIM,NVEGTYPE))
    YRECFM='D_ROOT_DEPTH'
    CALL READ_SURF_ISBA_PAR_n(DTCO, U, IO%NPATCH, &
                                HPROGRAM,YRECFM,ILUOUT,KSIZE,DTV%XPAR_ROOT_DEPTH(:,:),IRESP,IVERSION,&
                              HCOMMENT=YCOMMENT,HDIR=YDIR)
  ENDIF
!
  IF (DTV%LDATA_ROOT_EXTINCTION) THEN
    ALLOCATE(DTV%XPAR_ROOT_EXTINCTION(KDIM,NVEGTYPE))
    YRECFM='D_ROOT_EXT'
    CALL READ_SURF_ISBA_PAR_n(DTCO, U, IO%NPATCH, &
                                HPROGRAM,YRECFM,ILUOUT,KSIZE,DTV%XPAR_ROOT_EXTINCTION(:,:),IRESP,IVERSION,&
                              HCOMMENT=YCOMMENT,HDIR=YDIR)
  ENDIF

  IF (DTV%LDATA_ROOT_LIN) THEN
    ALLOCATE(DTV%XPAR_ROOT_LIN(KDIM,NVEGTYPE))
    YRECFM='D_ROOT_LIN'
    CALL READ_SURF_ISBA_PAR_n(DTCO, U, IO%NPATCH, &
                                HPROGRAM,YRECFM,ILUOUT,KSIZE,DTV%XPAR_ROOT_LIN(:,:),IRESP,IVERSION,&
                              HCOMMENT=YCOMMENT,HDIR=YDIR)
  ENDIF
!
  IF (DTV%LDATA_ALBNIR_VEG) THEN
    ALLOCATE(DTV%XPAR_ALBNIR_VEG(KDIM,NVEGTYPE))
    YRECFM='D_ALBNIR_VEG'
    CALL READ_SURF_ISBA_PAR_n(DTCO, U, IO%NPATCH, &
                                HPROGRAM,YRECFM,ILUOUT,KSIZE,DTV%XPAR_ALBNIR_VEG(:,:),IRESP,IVERSION,&
                              HCOMMENT=YCOMMENT,HDIR=YDIR)
  ENDIF
!
  IF (DTV%LDATA_ALBVIS_VEG) THEN
    ALLOCATE(DTV%XPAR_ALBVIS_VEG(KDIM,NVEGTYPE))
    YRECFM='D_ALBVIS_VEG'
    CALL READ_SURF_ISBA_PAR_n(DTCO, U, IO%NPATCH, &
                                HPROGRAM,YRECFM,ILUOUT,KSIZE,DTV%XPAR_ALBVIS_VEG(:,:),IRESP,IVERSION,&
                              HCOMMENT=YCOMMENT,HDIR=YDIR)
  ENDIF
!
  IF (DTV%LDATA_ALBUV_VEG) THEN
    ALLOCATE(DTV%XPAR_ALBUV_VEG (KDIM,NVEGTYPE))
    YRECFM='D_ALBUV_VEG'
    CALL READ_SURF_ISBA_PAR_n(DTCO, U, IO%NPATCH, &
                                HPROGRAM,YRECFM,ILUOUT,KSIZE,DTV%XPAR_ALBUV_VEG(:,:),IRESP,IVERSION,&
                              HCOMMENT=YCOMMENT,HDIR=YDIR)
  ENDIF
!
  IF (DTV%LDATA_ALBNIR_SOIL) THEN
    ALLOCATE(DTV%XPAR_ALBNIR_SOIL(KDIM,NVEGTYPE))
    YRECFM='D_ALBNIR_SOI'
    CALL READ_SURF_ISBA_PAR_n(DTCO, U, IO%NPATCH, &
                                HPROGRAM,YRECFM,ILUOUT,KSIZE,DTV%XPAR_ALBNIR_SOIL(:,:),IRESP,IVERSION,&
                              HCOMMENT=YCOMMENT,HDIR=YDIR)
  ENDIF
!
  IF (DTV%LDATA_ALBVIS_SOIL) THEN
    ALLOCATE(DTV%XPAR_ALBVIS_SOIL(KDIM,NVEGTYPE))
    YRECFM='D_ALBVIS_SOI'
    CALL READ_SURF_ISBA_PAR_n(DTCO, U, IO%NPATCH, &
                                HPROGRAM,YRECFM,ILUOUT,KSIZE,DTV%XPAR_ALBVIS_SOIL(:,:),IRESP,IVERSION,&
                              HCOMMENT=YCOMMENT,HDIR=YDIR)
  ENDIF
!
  IF (DTV%LDATA_ALBUV_SOIL) THEN
    ALLOCATE(DTV%XPAR_ALBUV_SOIL (KDIM,NVEGTYPE))
    YRECFM='D_ALBUV_SOI'
    CALL READ_SURF_ISBA_PAR_n(DTCO, U, IO%NPATCH, &
                                HPROGRAM,YRECFM,ILUOUT,KSIZE,DTV%XPAR_ALBUV_SOIL(:,:),IRESP,IVERSION,&
                              HCOMMENT=YCOMMENT,HDIR=YDIR)
  ENDIF
!
  IF (DTV%LDATA_GMES) THEN
    ALLOCATE(DTV%XPAR_GMES      (KDIM,NVEGTYPE))
    YRECFM='D_GMES'
    CALL READ_SURF_ISBA_PAR_n(DTCO, U, IO%NPATCH, &
                                HPROGRAM,YRECFM,ILUOUT,KSIZE,DTV%XPAR_GMES(:,:),IRESP,IVERSION,&
                              HCOMMENT=YCOMMENT,HDIR=YDIR)
  ENDIF
!
  IF (DTV%LDATA_BSLAI) THEN
    ALLOCATE(DTV%XPAR_BSLAI     (KDIM,NVEGTYPE))
    YRECFM='D_BSLAI'
    CALL READ_SURF_ISBA_PAR_n(DTCO, U, IO%NPATCH, &
                                HPROGRAM,YRECFM,ILUOUT,KSIZE,DTV%XPAR_BSLAI(:,:),IRESP,IVERSION,&
                              HCOMMENT=YCOMMENT,HDIR=YDIR)
  ENDIF
!
  IF (DTV%LDATA_LAIMIN) THEN
    ALLOCATE(DTV%XPAR_LAIMIN    (KDIM,NVEGTYPE))
    YRECFM='D_LAIMIN'
    CALL READ_SURF_ISBA_PAR_n(DTCO, U, IO%NPATCH, &
                                HPROGRAM,YRECFM,ILUOUT,KSIZE,DTV%XPAR_LAIMIN(:,:),IRESP,IVERSION,&
                              HCOMMENT=YCOMMENT,HDIR=YDIR)
  ENDIF
!
  IF (DTV%LDATA_SEFOLD) THEN
    ALLOCATE(DTV%XPAR_SEFOLD    (KDIM,NVEGTYPE))
    YRECFM='D_SEFOLD'
    CALL READ_SURF_ISBA_PAR_n(DTCO, U, IO%NPATCH, &
                                HPROGRAM,YRECFM,ILUOUT,KSIZE,DTV%XPAR_SEFOLD(:,:),IRESP,IVERSION,&
                              HCOMMENT=YCOMMENT,HDIR=YDIR)
  ENDIF
!
  IF (DTV%LDATA_GC) THEN
    ALLOCATE(DTV%XPAR_GC        (KDIM,NVEGTYPE))
    YRECFM='D_GC'
    CALL READ_SURF_ISBA_PAR_n(DTCO, U, IO%NPATCH, &
                                HPROGRAM,YRECFM,ILUOUT,KSIZE,DTV%XPAR_GC(:,:),IRESP,IVERSION,&
                              HCOMMENT=YCOMMENT,HDIR=YDIR)
  ENDIF
!
  IF (DTV%LDATA_DMAX) THEN
    ALLOCATE(DTV%XPAR_DMAX      (KDIM,NVEGTYPE))
    YRECFM='D_DMAX'
    CALL READ_SURF_ISBA_PAR_n(DTCO, U, IO%NPATCH, &
                                HPROGRAM,YRECFM,ILUOUT,KSIZE,DTV%XPAR_DMAX(:,:),IRESP,IVERSION,&
                              HCOMMENT=YCOMMENT,HDIR=YDIR)
  ENDIF
!
  IF (DTV%LDATA_F2I) THEN
    ALLOCATE(DTV%XPAR_F2I       (KDIM,NVEGTYPE))
    YRECFM='D_F2I'
    CALL READ_SURF_ISBA_PAR_n(DTCO, U, IO%NPATCH, &
                                HPROGRAM,YRECFM,ILUOUT,KSIZE,DTV%XPAR_F2I(:,:),IRESP,IVERSION,&
                              HCOMMENT=YCOMMENT,HDIR=YDIR)
  ENDIF
!
  IF (DTV%LDATA_STRESS) THEN
    ALLOCATE(DTV%LPAR_STRESS   (KDIM,NVEGTYPE))
    ALLOCATE(ZWORK(SIZE(DTV%LPAR_STRESS,1),SIZE(DTV%LPAR_STRESS,2)))
    YRECFM='D_STRESS'
    CALL READ_SURF_ISBA_PAR_n(DTCO, U, IO%NPATCH, &
                                HPROGRAM,YRECFM,ILUOUT,KSIZE,ZWORK(:,:),IRESP,IVERSION,&
                              HCOMMENT=YCOMMENT,HDIR=YDIR)
    DTV%LPAR_STRESS = .FALSE.
    WHERE(ZWORK==1.) DTV%LPAR_STRESS = .TRUE.
    DEALLOCATE(ZWORK)
  ENDIF
!
  IF (DTV%LDATA_H_TREE) THEN
    ALLOCATE(DTV%XPAR_H_TREE    (KDIM,NVEGTYPE))
    YRECFM='D_H_TREE'
    CALL READ_SURF_ISBA_PAR_n(DTCO, U, IO%NPATCH, &
                                HPROGRAM,YRECFM,ILUOUT,KSIZE,DTV%XPAR_H_TREE(:,:),IRESP,IVERSION,&
                              HCOMMENT=YCOMMENT,HDIR=YDIR)
  ENDIF
!
  IF (DTV%LDATA_RE25) THEN
    ALLOCATE(DTV%XPAR_RE25      (KDIM,NVEGTYPE))
    YRECFM='D_RE25'
    CALL READ_SURF_ISBA_PAR_n(DTCO, U, IO%NPATCH, &
                                HPROGRAM,YRECFM,ILUOUT,KSIZE,DTV%XPAR_RE25(:,:),IRESP,IVERSION,&
                              HCOMMENT=YCOMMENT,HDIR=YDIR)
  ENDIF
!
  IF (DTV%LDATA_CE_NITRO) THEN
    ALLOCATE(DTV%XPAR_CE_NITRO  (KDIM,NVEGTYPE))
    YRECFM='D_CE_NITRO'
    CALL READ_SURF_ISBA_PAR_n(DTCO, U, IO%NPATCH, &
                                HPROGRAM,YRECFM,ILUOUT,KSIZE,DTV%XPAR_CE_NITRO(:,:),IRESP,IVERSION,&
                              HCOMMENT=YCOMMENT,HDIR=YDIR)
  ENDIF
!
  IF (DTV%LDATA_CF_NITRO) THEN
    ALLOCATE(DTV%XPAR_CF_NITRO  (KDIM,NVEGTYPE))
    YRECFM='D_CF_NITRO'
    CALL READ_SURF_ISBA_PAR_n(DTCO, U, IO%NPATCH, &
                                HPROGRAM,YRECFM,ILUOUT,KSIZE,DTV%XPAR_CF_NITRO(:,:),IRESP,IVERSION,&
                              HCOMMENT=YCOMMENT,HDIR=YDIR)
  ENDIF
!
  IF (DTV%LDATA_CNA_NITRO) THEN
    ALLOCATE(DTV%XPAR_CNA_NITRO (KDIM,NVEGTYPE))
    YRECFM='D_CNA_NITRO'
    CALL READ_SURF_ISBA_PAR_n(DTCO, U, IO%NPATCH, &
                                HPROGRAM,YRECFM,ILUOUT,KSIZE,DTV%XPAR_CNA_NITRO(:,:),IRESP,IVERSION,&
                              HCOMMENT=YCOMMENT,HDIR=YDIR)
  ENDIF
!
  IF (DTV%LDATA_IRRIG) THEN
    ALLOCATE(DTV%XPAR_IRRIG     (KDIM,DTV%NTIME,NVEGTYPE))
    DO JTIME=1,ITIME
      WRITE(YRECFM,FMT='(A9,I2.2)') 'D_IRRIG_T',JTIME
        CALL READ_SURF_ISBA_PAR_n(DTCO, U, IO%NPATCH, &
                                HPROGRAM,YRECFM,ILUOUT,KSIZE,DTV%XPAR_IRRIG(:,JTIME,:),IRESP,IVERSION,&
                                  HCOMMENT=YCOMMENT,HDIR=YDIR)
    END DO
  ENDIF
!
  IF (DTV%LDATA_WATSUP) THEN
    ALLOCATE(DTV%XPAR_WATSUP     (KDIM,DTV%NTIME,NVEGTYPE))
    DO JTIME=1,ITIME
      WRITE(YRECFM,FMT='(A10,I2.2)') 'D_WATSUP_T',JTIME
        CALL READ_SURF_ISBA_PAR_n(DTCO, U, IO%NPATCH, &
                                HPROGRAM,YRECFM,ILUOUT,KSIZE,DTV%XPAR_WATSUP(:,JTIME,:),IRESP,IVERSION,&
                                  HCOMMENT=YCOMMENT,HDIR=YDIR)
    END DO
  ENDIF
!
ENDIF
!
IF (LASSIM) LREAD_ALL = GREAD_ALL
!
IF (LHOOK) CALL DR_HOOK('READ_PGD_ISBA_PAR_N',1,ZHOOK_HANDLE)
!
!-------------------------------------------------------------------------------
!
END SUBROUTINE READ_PGD_ISBA_PAR_n
