!     #########
      SUBROUTINE READ_PGD_TEB_IRRIG_n(HPROGRAM)
!     ################################################
!
!!****  *READ_PGD_TEB_IRRIG_n* - reads ISBA physiographic fields
!!                        
!!
!!    PURPOSE
!!    -------
!!
!!**  METHOD
!!    ------
!!
!!    EXTERNAL
!!    --------
!!
!!
!!    IMPLICIT ARGUMENTS
!!    ------------------
!!
!!    REFERENCE
!!    ---------
!!
!!
!!    AUTHOR
!!    ------
!!	V. Masson   *Meteo France*	
!!
!!    MODIFICATIONS
!!    -------------
!!      Original    05/2005
!-------------------------------------------------------------------------------
!
!*       0.    DECLARATIONS
!              ------------
!
USE MODD_TEB_GRID_n, ONLY :   NDIM
USE MODD_TEB_IRRIG_n, ONLY : LPAR_GD_IRRIG, LPAR_GR_IRRIG, LPAR_RD_IRRIG,                                 &
                             XGD_START_MONTH, XGD_END_MONTH, XGD_START_HOUR, XGD_END_HOUR, XGD_24H_IRRIG, &
                             XRD_START_MONTH, XRD_END_MONTH, XRD_START_HOUR, XRD_END_HOUR, XRD_24H_IRRIG, &
                             XGR_START_MONTH, XGR_END_MONTH, XGR_START_HOUR, XGR_END_HOUR, XGR_24H_IRRIG
!
USE MODI_READ_SURF
USE MODI_GET_LUOUT
USE MODI_ABOR1_SFX
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE
!
!*       0.1   Declarations of arguments
!              -------------------------
!
 CHARACTER(LEN=6),  INTENT(IN)  :: HPROGRAM ! program calling
!
!*       0.2   Declarations of local variables
!              -------------------------------
!
INTEGER           :: ILUOUT         ! output listing logical unit
INTEGER           :: IRESP          ! IRESP  : return-code if a problem appears
 CHARACTER(LEN=12) :: YRECFM         ! Name of the article to be read
 CHARACTER(LEN=80) :: YCOMMENT       ! Comment of the article to be read
INTEGER           :: JLAYER         ! loop index
!
INTEGER           :: IVERSION       ! surface version
INTEGER           :: IBUGFIX        ! surface bugfix version
REAL, DIMENSION(NDIM) :: ZWORK      ! work array
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
!-------------------------------------------------------------------------------
IF (LHOOK) CALL DR_HOOK('READ_PGD_TEB_IRRIG_N',0,ZHOOK_HANDLE)
!
 CALL GET_LUOUT(HPROGRAM,ILUOUT)
!
YRECFM='VERSION'
 CALL READ_SURF(HPROGRAM,YRECFM,IVERSION,IRESP)
YRECFM='BUG'
 CALL READ_SURF(HPROGRAM,YRECFM,IBUGFIX,IRESP)
!
IF (IVERSION<7 .OR. (IVERSION==7 .AND. IBUGFIX<=3)) THEN
  !
  LPAR_GD_IRRIG = .FALSE.
  LPAR_GR_IRRIG = .FALSE.
  LPAR_RD_IRRIG = .FALSE.
  !
ELSE
  !
  YRECFM='L_PAR_GD_IRR'
  CALL READ_SURF(HPROGRAM,YRECFM,LPAR_GD_IRRIG,IRESP)
  YRECFM='L_PAR_GR_IRR'
  CALL READ_SURF(HPROGRAM,YRECFM,LPAR_GR_IRRIG,IRESP)
  YRECFM='L_PAR_RD_IRR'
  CALL READ_SURF(HPROGRAM,YRECFM,LPAR_RD_IRRIG,IRESP)
  !
ENDIF
!
!* read garden irrigation
!
IF (LPAR_GD_IRRIG) THEN
  ALLOCATE(XGD_START_MONTH(NDIM))
  YRECFM='D_GD_SM_IRR'
  CALL READ_SURF(HPROGRAM,YRECFM,XGD_START_MONTH(:),IRESP,HCOMMENT=YCOMMENT)
  !
  ALLOCATE(XGD_END_MONTH  (NDIM))
  YRECFM='D_GD_EM_IRR'
  CALL READ_SURF(HPROGRAM,YRECFM,XGD_END_MONTH  (:),IRESP,HCOMMENT=YCOMMENT)
  !
  ALLOCATE(XGD_START_HOUR (NDIM))
  YRECFM='D_GD_SH_IRR'
  CALL READ_SURF(HPROGRAM,YRECFM,XGD_START_HOUR (:),IRESP,HCOMMENT=YCOMMENT)
  !
  ALLOCATE(XGD_END_HOUR   (NDIM))
  YRECFM='D_GD_EH_IRR'
  CALL READ_SURF(HPROGRAM,YRECFM,XGD_END_HOUR   (:),IRESP,HCOMMENT=YCOMMENT)
  !
  ALLOCATE(XGD_24H_IRRIG  (NDIM))
  YRECFM='D_GD_IRRIG'
  CALL READ_SURF(HPROGRAM,YRECFM,XGD_24H_IRRIG  (:),IRESP,HCOMMENT=YCOMMENT)
ELSE
  ALLOCATE(XGD_START_MONTH(0))
  ALLOCATE(XGD_END_MONTH  (0))
  ALLOCATE(XGD_START_HOUR (0))
  ALLOCATE(XGD_END_HOUR   (0))
  ALLOCATE(XGD_24H_IRRIG  (0))
END IF
!
!* read greenroof irrigation
!
IF (LPAR_GR_IRRIG) THEN
  ALLOCATE(XGR_START_MONTH(NDIM))
  YRECFM='D_GR_SM_IRR'
  CALL READ_SURF(HPROGRAM,YRECFM,XGR_START_MONTH(:),IRESP,HCOMMENT=YCOMMENT)
  !
  ALLOCATE(XGR_END_MONTH  (NDIM))
  YRECFM='D_GR_EM_IRR'
  CALL READ_SURF(HPROGRAM,YRECFM,XGR_END_MONTH  (:),IRESP,HCOMMENT=YCOMMENT)
  !
  ALLOCATE(XGR_START_HOUR (NDIM))
  YRECFM='D_GR_SH_IRR'
  CALL READ_SURF(HPROGRAM,YRECFM,XGR_START_HOUR (:),IRESP,HCOMMENT=YCOMMENT)
  !
  ALLOCATE(XGR_END_HOUR   (NDIM))
  YRECFM='D_GR_EH_IRR'
  CALL READ_SURF(HPROGRAM,YRECFM,XGR_END_HOUR   (:),IRESP,HCOMMENT=YCOMMENT)
  !
  ALLOCATE(XGR_24H_IRRIG  (NDIM))
  YRECFM='D_GR_IRRIG'
  CALL READ_SURF(HPROGRAM,YRECFM,XGR_24H_IRRIG  (:),IRESP,HCOMMENT=YCOMMENT)
ELSE
  ALLOCATE(XGR_START_MONTH(0))
  ALLOCATE(XGR_END_MONTH  (0))
  ALLOCATE(XGR_START_HOUR (0))
  ALLOCATE(XGR_END_HOUR   (0))
  ALLOCATE(XGR_24H_IRRIG  (0))
END IF
!
!* read road watering
!
IF (LPAR_RD_IRRIG) THEN
  ALLOCATE(XRD_START_MONTH(NDIM))
  YRECFM='D_RD_SM_IRR'
  CALL READ_SURF(HPROGRAM,YRECFM,XRD_START_MONTH(:),IRESP,HCOMMENT=YCOMMENT)
  !
  ALLOCATE(XRD_END_MONTH  (NDIM))
  YRECFM='D_RD_EM_IRR'
  CALL READ_SURF(HPROGRAM,YRECFM,XRD_END_MONTH  (:),IRESP,HCOMMENT=YCOMMENT)
  !
  ALLOCATE(XRD_START_HOUR (NDIM))
  YRECFM='D_RD_SH_IRR'
  CALL READ_SURF(HPROGRAM,YRECFM,XRD_START_HOUR (:),IRESP,HCOMMENT=YCOMMENT)
  !
  ALLOCATE(XRD_END_HOUR   (NDIM))
  YRECFM='D_RD_EH_IRR'
  CALL READ_SURF(HPROGRAM,YRECFM,XRD_END_HOUR   (:),IRESP,HCOMMENT=YCOMMENT)
  !
  ALLOCATE(XRD_24H_IRRIG  (NDIM))
  YRECFM='D_RD_IRRIG'
  CALL READ_SURF(HPROGRAM,YRECFM,XRD_24H_IRRIG  (:),IRESP,HCOMMENT=YCOMMENT)
ELSE
  ALLOCATE(XRD_START_MONTH(0))
  ALLOCATE(XRD_END_MONTH  (0))
  ALLOCATE(XRD_START_HOUR (0))
  ALLOCATE(XRD_END_HOUR   (0))
  ALLOCATE(XRD_24H_IRRIG  (0))
END IF

!
IF (LHOOK) CALL DR_HOOK('READ_PGD_TEB_IRRIG_N',1,ZHOOK_HANDLE)
!
!-------------------------------------------------------------------------------
!
END SUBROUTINE READ_PGD_TEB_IRRIG_n
