!     #########
      SUBROUTINE READ_PGD_TEB_GARDEN_PAR_n (DGD, GDO, GDP, KDIM, HPROGRAM)
!     ################################################
!
!!****  *READ_PGD_TEB_GARDEN_PAR_n* - reads ISBA physiographic fields
!!                        
!!
!!    PURPOSE
!!    -------
!!
!!**  METHOD
!!    ------
!!
!!    EXTERNAL
!!    --------
!!
!!
!!    IMPLICIT ARGUMENTS
!!    ------------------
!!
!!    REFERENCE
!!    ---------
!!
!!
!!    AUTHOR
!!    ------
!!      V. Masson   *Meteo France*
!!
!!    MODIFICATIONS
!!    -------------
!!      Original    01/2003 
!!      P. Le Moigne 12/2004 : add type of photosynthesis
!!      R. Alkama    05/2012 : Add 7 new vegtypes (19 rather than 12)
!!      B. Decharme    05/13 : new param for equatorial forest
!-------------------------------------------------------------------------------
!
!*       0.    DECLARATIONS
!              ------------
!
!
!
!
!
USE MODD_DATA_ISBA_n, ONLY : DATA_ISBA_t
USE MODD_ISBA_OPTIONS_n, ONLY : ISBA_OPTIONS_t
USE MODD_ISBA_PGD_n, ONLY : ISBA_PGD_t
!
USE MODD_CSTS,              ONLY : XDAY
USE MODD_SURF_PAR,          ONLY : XUNDEF
USE MODD_ISBA_PAR,          ONLY : XOPTIMGRID, NOPTIMLAYER
USE MODD_DATA_COVER_PAR,    ONLY : NVT_NO, NVT_ROCK, NVT_SNOW, NVT_TEBD,     & 
                                     NVT_BONE, NVT_TRBE, NVT_C3, NVT_C4,     &
                                     NVT_IRR, NVT_GRAS, NVT_TROG,NVT_PARK,   &
                                     NVT_TRBD, NVT_TEBE, NVT_TENE, NVT_BOBD, &
                                     NVT_BOND, NVT_BOGR, NVT_SHRB, NVEGTYPE
!
USE MODI_READ_SURF
USE MODI_VEG_FROM_LAI
USE MODI_Z0V_FROM_LAI
USE MODI_EMIS_FROM_VEG
USE MODI_ABOR1_SFX
!
USE MODD_REPROD_OPER,    ONLY : XEVERG_RSMIN
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE
!
!*       0.1   Declarations of arguments
!              -------------------------
!
!
!
!
TYPE(DATA_ISBA_t), INTENT(INOUT) :: DGD
TYPE(ISBA_OPTIONS_t), INTENT(INOUT) :: GDO
TYPE(ISBA_PGD_t), INTENT(INOUT) :: GDP
INTEGER, INTENT(IN) :: KDIM
!
 CHARACTER(LEN=6),  INTENT(IN)  :: HPROGRAM ! program calling
!
!*       0.2   Declarations of local variables
!              -------------------------------
!
INTEGER                               :: IRESP          ! IRESP  : return-code if a problem appears
CHARACTER(LEN=12)                     :: YRECFM         ! Name of the article to be read
CHARACTER(LEN=100)                    :: YCOMMENT       ! Comment string
INTEGER                               :: JI, JLAYER     ! loop index
INTEGER                               :: JTIME          ! loop index
!
REAL, DIMENSION(KDIM,3)               :: ZDATA_RSMIN
REAL, DIMENSION(KDIM,3)               :: ZDATA_GAMMA
REAL, DIMENSION(KDIM,3)               :: ZDATA_WRMAX_CF
REAL, DIMENSION(KDIM,3)               :: ZDATA_RGL
REAL, DIMENSION(KDIM,3)               :: ZDATA_CV
REAL, DIMENSION(KDIM,GDO%NGROUND_LAYER,3) :: ZDATA_DG
REAL, DIMENSION(KDIM,3)               :: ZDATA_ALBNIR_VEG
REAL, DIMENSION(KDIM,3)               :: ZDATA_ALBVIS_VEG
REAL, DIMENSION(KDIM,3)               :: ZDATA_ALBUV_VEG
REAL, DIMENSION(KDIM,3)               :: ZDATA_GMES
REAL, DIMENSION(KDIM,3)               :: ZDATA_RE25
REAL, DIMENSION(KDIM,3)               :: ZDATA_BSLAI
REAL, DIMENSION(KDIM,3)               :: ZDATA_LAIMIN
REAL, DIMENSION(KDIM,3)               :: ZDATA_SEFOLD
REAL, DIMENSION(KDIM,3)               :: ZDATA_GC
REAL, DIMENSION(KDIM,3)               :: ZDATA_DMAX
REAL, DIMENSION(KDIM,3)               :: ZDATA_CE_NITRO
REAL, DIMENSION(KDIM,3)               :: ZDATA_CF_NITRO
REAL, DIMENSION(KDIM,3)               :: ZDATA_CNA_NITRO
!
LOGICAL :: GAGRI_TO_GRASS
!
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
!-------------------------------------------------------------------------------
!
!*       1.    Reading of PGD file
!              --------------------
!
IF (LHOOK) CALL DR_HOOK('READ_PGD_TEB_GARDEN_PAR_N',0,ZHOOK_HANDLE)
DGD%NTIME= 12
!
GAGRI_TO_GRASS=.FALSE.
!
YRECFM='GD_NTIME'
CALL READ_SURF(HPROGRAM,YRECFM,DGD%NTIME,IRESP,HCOMMENT=YCOMMENT)
!
ALLOCATE(DGD%XPAR_FRAC_HVEG (KDIM))
ALLOCATE(DGD%XPAR_FRAC_LVEG (KDIM))
ALLOCATE(DGD%XPAR_FRAC_NVEG (KDIM))
ALLOCATE(DGD%XPAR_LAI_HVEG  (KDIM,DGD%NTIME))
ALLOCATE(DGD%XPAR_LAI_LVEG  (KDIM,DGD%NTIME))
ALLOCATE(DGD%XPAR_H_HVEG    (KDIM))
!
! Read type of high vegetation
YRECFM='D_TYPE_HVEG'
 CALL READ_SURF(HPROGRAM,YRECFM,GDO%CTYPE_HVEG,IRESP,HCOMMENT=YCOMMENT)
!
! Read type of low vegetation
YRECFM='D_TYPE_LVEG'
 CALL READ_SURF(HPROGRAM,YRECFM,GDO%CTYPE_LVEG,IRESP,HCOMMENT=YCOMMENT)
!
! Read type of bare soil (no vegetation)
YRECFM='D_TYPE_NVEG'
 CALL READ_SURF(HPROGRAM,YRECFM,GDO%CTYPE_NVEG,IRESP,HCOMMENT=YCOMMENT)
!
! Read fraction of high vegetation
YRECFM='D_FRAC_HVEG'
 CALL READ_SURF(HPROGRAM,YRECFM,DGD%XPAR_FRAC_HVEG,IRESP,HCOMMENT=YCOMMENT)
!
! Read fraction of low vegetation
YRECFM='D_FRAC_LVEG'
 CALL READ_SURF(HPROGRAM,YRECFM,DGD%XPAR_FRAC_LVEG,IRESP,HCOMMENT=YCOMMENT)
!
! Read fraction of bare soil (no vegetation)
YRECFM='D_FRAC_NVEG'
 CALL READ_SURF(HPROGRAM,YRECFM,DGD%XPAR_FRAC_NVEG,IRESP,HCOMMENT=YCOMMENT)
!
! Read height of trees( for high vegetation)
YRECFM='D_H_HVEG'
 CALL READ_SURF(HPROGRAM,YRECFM,DGD%XPAR_H_HVEG,IRESP,HCOMMENT=YCOMMENT)
!
! Read LAI of high vegetation
DO JTIME=1,DGD%NTIME
  WRITE(YRECFM,FMT='(A10,I2.2)') 'D_LAI_HVEG',JTIME
  CALL READ_SURF(HPROGRAM,YRECFM,DGD%XPAR_LAI_HVEG(:,JTIME),IRESP,HCOMMENT=YCOMMENT)
  WRITE(YRECFM,FMT='(A10,I2.2)') 'D_LAI_LVEG',JTIME
  CALL READ_SURF(HPROGRAM,YRECFM,DGD%XPAR_LAI_LVEG(:,JTIME),IRESP,HCOMMENT=YCOMMENT)
END DO
!
!-------------------------------------------------------------------------------
!
!*       2.    Definition of ISBA parameters
!              -----------------------------
!
ALLOCATE(DGD%XPAR_LAI        (KDIM,DGD%NTIME,1))
ALLOCATE(DGD%XPAR_VEG        (KDIM,DGD%NTIME,1))
ALLOCATE(DGD%XPAR_RSMIN      (KDIM,1))
ALLOCATE(DGD%XPAR_GAMMA      (KDIM,1))
ALLOCATE(DGD%XPAR_WRMAX_CF   (KDIM,1))
ALLOCATE(DGD%XPAR_RGL        (KDIM,1))
ALLOCATE(DGD%XPAR_CV         (KDIM,1))
ALLOCATE(DGD%XPAR_DG         (KDIM,GDO%NGROUND_LAYER,1))
ALLOCATE(DGD%XPAR_ROOTFRAC   (KDIM,GDO%NGROUND_LAYER,1))
ALLOCATE(DGD%XPAR_DICE       (KDIM,1))
ALLOCATE(DGD%XPAR_Z0         (KDIM,DGD%NTIME,1))
ALLOCATE(DGD%XPAR_Z0_O_Z0H   (KDIM,1))
ALLOCATE(DGD%XPAR_ALBNIR_VEG (KDIM,1))
ALLOCATE(DGD%XPAR_ALBVIS_VEG (KDIM,1))
ALLOCATE(DGD%XPAR_ALBUV_VEG  (KDIM,1))
ALLOCATE(DGD%XPAR_ALBNIR_SOIL(KDIM,1))
ALLOCATE(DGD%XPAR_ALBVIS_SOIL(KDIM,1))
ALLOCATE(DGD%XPAR_ALBUV_SOIL (KDIM,1))
ALLOCATE(DGD%XPAR_EMIS       (KDIM,DGD%NTIME,1))
ALLOCATE(DGD%XPAR_VEGTYPE    (KDIM,NVEGTYPE))
ALLOCATE(DGD%XPAR_GMES       (KDIM,1))
ALLOCATE(DGD%XPAR_RE25       (KDIM,1))
ALLOCATE(DGD%XPAR_BSLAI      (KDIM,1))
ALLOCATE(DGD%XPAR_LAIMIN     (KDIM,1))
ALLOCATE(DGD%XPAR_SEFOLD     (KDIM,1))
ALLOCATE(DGD%XPAR_GC         (KDIM,1))
ALLOCATE(DGD%XPAR_DMAX       (KDIM,1))
ALLOCATE(DGD%XPAR_F2I        (KDIM,1))
ALLOCATE(DGD%LPAR_STRESS     (KDIM,1))
ALLOCATE(DGD%XPAR_H_TREE     (KDIM,1))
ALLOCATE(DGD%XPAR_CE_NITRO   (KDIM,1))
ALLOCATE(DGD%XPAR_CF_NITRO   (KDIM,1))
ALLOCATE(DGD%XPAR_CNA_NITRO  (KDIM,1))
!
DGD%XPAR_LAI        (:,:,:) = XUNDEF
DGD%XPAR_VEG        (:,:,:) = XUNDEF
DGD%XPAR_RSMIN        (:,:) = XUNDEF
DGD%XPAR_GAMMA        (:,:) = XUNDEF
DGD%XPAR_WRMAX_CF     (:,:) = XUNDEF
DGD%XPAR_RGL          (:,:) = XUNDEF
DGD%XPAR_CV           (:,:) = XUNDEF
DGD%XPAR_DG         (:,:,:) = XUNDEF
DGD%XPAR_DICE       (:,:)   = XUNDEF
DGD%XPAR_ROOTFRAC   (:,:,:) = XUNDEF
DGD%XPAR_Z0         (:,:,:) = XUNDEF
DGD%XPAR_Z0_O_Z0H     (:,:) = XUNDEF
DGD%XPAR_ALBNIR_VEG   (:,:) = XUNDEF
DGD%XPAR_ALBVIS_VEG   (:,:) = XUNDEF
DGD%XPAR_ALBUV_VEG    (:,:) = XUNDEF
DGD%XPAR_ALBNIR_SOIL  (:,:) = XUNDEF
DGD%XPAR_ALBVIS_SOIL  (:,:) = XUNDEF
DGD%XPAR_ALBUV_SOIL   (:,:) = XUNDEF
DGD%XPAR_EMIS       (:,:,:) = XUNDEF
DGD%XPAR_VEGTYPE    (:,:) = XUNDEF
DGD%XPAR_GMES         (:,:) = XUNDEF
DGD%XPAR_RE25         (:,:) = XUNDEF
DGD%XPAR_BSLAI        (:,:) = XUNDEF
DGD%XPAR_LAIMIN       (:,:) = XUNDEF
DGD%XPAR_SEFOLD       (:,:) = XUNDEF
DGD%XPAR_GC           (:,:) = XUNDEF
DGD%XPAR_DMAX         (:,:) = XUNDEF
DGD%XPAR_F2I          (:,:) = XUNDEF
DGD%LPAR_STRESS       (:,:) = .FALSE.
DGD%XPAR_H_TREE       (:,:) = XUNDEF
DGD%XPAR_CE_NITRO     (:,:) = XUNDEF
DGD%XPAR_CF_NITRO     (:,:) = XUNDEF
DGD%XPAR_CNA_NITRO    (:,:) = XUNDEF
!
! Vegtypes
DGD%XPAR_VEGTYPE(:,:) = 0.
IF (GDO%CTYPE_NVEG == 'NO  ') DGD%XPAR_VEGTYPE(:, NVT_NO  ) = DGD%XPAR_FRAC_NVEG(:)
IF (GDO%CTYPE_NVEG == 'ROCK') DGD%XPAR_VEGTYPE(:, NVT_ROCK) = DGD%XPAR_FRAC_NVEG(:)
IF (GDO%CTYPE_NVEG == 'SNOW') DGD%XPAR_VEGTYPE(:, NVT_SNOW) = DGD%XPAR_FRAC_NVEG(:)
IF (GDO%CTYPE_HVEG == 'TEBD') DGD%XPAR_VEGTYPE(:, NVT_TEBD) = DGD%XPAR_FRAC_HVEG(:)
IF (GDO%CTYPE_HVEG == 'TRBD') DGD%XPAR_VEGTYPE(:, NVT_TRBD) = DGD%XPAR_FRAC_HVEG(:)
IF (GDO%CTYPE_HVEG == 'TEBE') DGD%XPAR_VEGTYPE(:, NVT_TEBE) = DGD%XPAR_FRAC_HVEG(:)
IF (GDO%CTYPE_HVEG == 'BOBD') DGD%XPAR_VEGTYPE(:, NVT_BOBD) = DGD%XPAR_FRAC_HVEG(:)
IF (GDO%CTYPE_HVEG == 'SHRB') DGD%XPAR_VEGTYPE(:, NVT_SHRB) = DGD%XPAR_FRAC_HVEG(:)
IF (GDO%CTYPE_HVEG == 'BONE') DGD%XPAR_VEGTYPE(:, NVT_BONE) = DGD%XPAR_FRAC_HVEG(:)
IF (GDO%CTYPE_HVEG == 'TENE') DGD%XPAR_VEGTYPE(:, NVT_TENE) = DGD%XPAR_FRAC_HVEG(:)
IF (GDO%CTYPE_HVEG == 'BOND') DGD%XPAR_VEGTYPE(:, NVT_BOND) = DGD%XPAR_FRAC_HVEG(:)
IF (GDO%CTYPE_HVEG == 'TRBE') DGD%XPAR_VEGTYPE(:, NVT_TRBE) = DGD%XPAR_FRAC_HVEG(:)
IF (GDO%CTYPE_LVEG == 'C3  ') DGD%XPAR_VEGTYPE(:, NVT_C3  ) = DGD%XPAR_FRAC_LVEG(:)
IF (GDO%CTYPE_LVEG == 'C4  ') DGD%XPAR_VEGTYPE(:, NVT_C4  ) = DGD%XPAR_FRAC_LVEG(:)
IF (GDO%CTYPE_LVEG == 'IRR ') DGD%XPAR_VEGTYPE(:, NVT_IRR ) = DGD%XPAR_FRAC_LVEG(:)
IF (GDO%CTYPE_LVEG == 'GRAS') DGD%XPAR_VEGTYPE(:, NVT_GRAS) = DGD%XPAR_FRAC_LVEG(:)
IF (GDO%CTYPE_LVEG == 'BOGR') DGD%XPAR_VEGTYPE(:, NVT_BOGR) = DGD%XPAR_FRAC_LVEG(:)
IF (GDO%CTYPE_LVEG == 'TROG') DGD%XPAR_VEGTYPE(:, NVT_TROG) = DGD%XPAR_FRAC_LVEG(:)
IF (GDO%CTYPE_LVEG == 'PARK') DGD%XPAR_VEGTYPE(:, NVT_PARK) = DGD%XPAR_FRAC_LVEG(:)

!
! Height of trees
DGD%XPAR_H_TREE  (:,1) = DGD%XPAR_H_HVEG(:)
!
! Critical normilized soil water content for stress parameterisation
DGD%XPAR_F2I     (:,1) = 0.3
!
! Ratio between roughness length for momentum and heat
DGD%XPAR_Z0_O_Z0H(:,1) = 10.
!
! Defensive/offensive strategy (1/0)
DGD%LPAR_STRESS  (:,1) = .FALSE. 
!
DO JI=1,KDIM
!
! Near-IR, visible, and UV albedo (vegetation only)

 ZDATA_ALBNIR_VEG(JI,:)= 0.30
 IF(DGD%XPAR_VEGTYPE(JI,NVT_TEBD)>0. )  ZDATA_ALBNIR_VEG(JI,1)= 0.25
 IF(DGD%XPAR_VEGTYPE(JI,NVT_TRBD)>0. )  ZDATA_ALBNIR_VEG(JI,1)= 0.25
 IF(DGD%XPAR_VEGTYPE(JI,NVT_TEBE)>0. )  ZDATA_ALBNIR_VEG(JI,1)= 0.25
 IF(DGD%XPAR_VEGTYPE(JI,NVT_BOBD)>0. )  ZDATA_ALBNIR_VEG(JI,1)= 0.25
 IF(DGD%XPAR_VEGTYPE(JI,NVT_SHRB)>0. )  ZDATA_ALBNIR_VEG(JI,1)= 0.25
 IF(DGD%XPAR_VEGTYPE(JI,NVT_BONE)>0. )  ZDATA_ALBNIR_VEG(JI,1)= 0.15
 IF(DGD%XPAR_VEGTYPE(JI,NVT_TENE)>0. )  ZDATA_ALBNIR_VEG(JI,1)= 0.15
 IF(DGD%XPAR_VEGTYPE(JI,NVT_BOND)>0. )  ZDATA_ALBNIR_VEG(JI,1)= 0.15
 IF(DGD%XPAR_VEGTYPE(JI,NVT_TRBE)>0. )  ZDATA_ALBNIR_VEG(JI,1)= 0.21

 ZDATA_ALBVIS_VEG(JI,:)= 0.10
 IF(DGD%XPAR_VEGTYPE(JI,NVT_TEBD)>0. )  ZDATA_ALBVIS_VEG(JI,1)= 0.05
 IF(DGD%XPAR_VEGTYPE(JI,NVT_TRBD)>0. )  ZDATA_ALBVIS_VEG(JI,1)= 0.05
 IF(DGD%XPAR_VEGTYPE(JI,NVT_TEBE)>0. )  ZDATA_ALBVIS_VEG(JI,1)= 0.05
 IF(DGD%XPAR_VEGTYPE(JI,NVT_BOBD)>0. )  ZDATA_ALBVIS_VEG(JI,1)= 0.05
 IF(DGD%XPAR_VEGTYPE(JI,NVT_SHRB)>0. )  ZDATA_ALBVIS_VEG(JI,1)= 0.05
 IF(DGD%XPAR_VEGTYPE(JI,NVT_BONE)>0. )  ZDATA_ALBVIS_VEG(JI,1)= 0.05
 IF(DGD%XPAR_VEGTYPE(JI,NVT_TENE)>0. )  ZDATA_ALBVIS_VEG(JI,1)= 0.05
 IF(DGD%XPAR_VEGTYPE(JI,NVT_BOND)>0. )  ZDATA_ALBVIS_VEG(JI,1)= 0.05
 IF(DGD%XPAR_VEGTYPE(JI,NVT_TRBE)>0. )  ZDATA_ALBVIS_VEG(JI,1)= 0.05

 ZDATA_ALBUV_VEG (JI,:)= 0.06
 IF(DGD%XPAR_VEGTYPE(JI,NVT_TEBD)>0. )  ZDATA_ALBUV_VEG(JI,1)= 0.0525
 IF(DGD%XPAR_VEGTYPE(JI,NVT_TRBD)>0. )  ZDATA_ALBUV_VEG(JI,1)= 0.0525
 IF(DGD%XPAR_VEGTYPE(JI,NVT_TEBE)>0. )  ZDATA_ALBUV_VEG(JI,1)= 0.0525
 IF(DGD%XPAR_VEGTYPE(JI,NVT_BOBD)>0. )  ZDATA_ALBUV_VEG(JI,1)= 0.0525
 IF(DGD%XPAR_VEGTYPE(JI,NVT_SHRB)>0. )  ZDATA_ALBUV_VEG(JI,1)= 0.0525
 IF(DGD%XPAR_VEGTYPE(JI,NVT_BONE)>0. )  ZDATA_ALBUV_VEG(JI,1)= 0.0425
 IF(DGD%XPAR_VEGTYPE(JI,NVT_TENE)>0. )  ZDATA_ALBUV_VEG(JI,1)= 0.0425
 IF(DGD%XPAR_VEGTYPE(JI,NVT_BOND)>0. )  ZDATA_ALBUV_VEG(JI,1)= 0.0425
 IF(DGD%XPAR_VEGTYPE(JI,NVT_TRBE)>0. )  ZDATA_ALBUV_VEG(JI,1)= 0.0380 
 IF(DGD%XPAR_VEGTYPE(JI,NVT_GRAS)>0. )  ZDATA_ALBUV_VEG(JI,2)= 0.0800
 IF(DGD%XPAR_VEGTYPE(JI,NVT_BOGR)>0. )  ZDATA_ALBUV_VEG(JI,2)= 0.0800 
 IF(DGD%XPAR_VEGTYPE(JI,NVT_TROG)>0. )  ZDATA_ALBUV_VEG(JI,2)= 0.1250
 IF(DGD%XPAR_VEGTYPE(JI,NVT_IRR )>0. )  ZDATA_ALBUV_VEG(JI,2)= 0.0450
 IF(DGD%XPAR_VEGTYPE(JI,NVT_PARK)>0. )  ZDATA_ALBUV_VEG(JI,2)= 0.0450

 IF (DGD%XPAR_FRAC_HVEG(JI)+DGD%XPAR_FRAC_LVEG(JI) .GT. 0.) THEN
  DGD%XPAR_ALBNIR_VEG(JI,1) =  ( ZDATA_ALBNIR_VEG(JI,1)*DGD%XPAR_FRAC_HVEG(JI)   &
                            + ZDATA_ALBNIR_VEG(JI,2)*DGD%XPAR_FRAC_LVEG(JI) ) &
                          / ( DGD%XPAR_FRAC_HVEG(JI)+DGD%XPAR_FRAC_LVEG(JI)    )  
!
  DGD%XPAR_ALBVIS_VEG(JI,1) =  ( ZDATA_ALBVIS_VEG(JI,1)*DGD%XPAR_FRAC_HVEG(JI)   &
                            + ZDATA_ALBVIS_VEG(JI,2)*DGD%XPAR_FRAC_LVEG(JI) ) &
                          / ( DGD%XPAR_FRAC_HVEG(JI)+DGD%XPAR_FRAC_LVEG(JI)    )  
! 
  DGD%XPAR_ALBUV_VEG (JI,1) =  ( ZDATA_ALBUV_VEG (JI,1)*DGD%XPAR_FRAC_HVEG(JI)   &
                            + ZDATA_ALBUV_VEG (JI,2)*DGD%XPAR_FRAC_LVEG(JI) ) &
                          / ( DGD%XPAR_FRAC_HVEG (JI)+DGD%XPAR_FRAC_LVEG(JI)   )  
 ENDIF 
!
! Min stomatal resistance
 ZDATA_RSMIN(JI,:)= 40.
 IF(DGD%XPAR_VEGTYPE(JI,NVT_TEBD)>0. )  ZDATA_RSMIN(JI,1)= 150.
 IF(DGD%XPAR_VEGTYPE(JI,NVT_TRBD)>0. )  ZDATA_RSMIN(JI,1)= 150.
 IF(DGD%XPAR_VEGTYPE(JI,NVT_TEBE)>0. )  ZDATA_RSMIN(JI,1)= 150.
 IF(DGD%XPAR_VEGTYPE(JI,NVT_BOBD)>0. )  ZDATA_RSMIN(JI,1)= 150.
 IF(DGD%XPAR_VEGTYPE(JI,NVT_SHRB)>0. )  ZDATA_RSMIN(JI,1)= 150.
 IF(DGD%XPAR_VEGTYPE(JI,NVT_BONE)>0. )  ZDATA_RSMIN(JI,1)= 150.
 IF(DGD%XPAR_VEGTYPE(JI,NVT_TENE)>0. )  ZDATA_RSMIN(JI,1)= 150.
 IF(DGD%XPAR_VEGTYPE(JI,NVT_BOND)>0. )  ZDATA_RSMIN(JI,1)= 150.
 IF(DGD%XPAR_VEGTYPE(JI,NVT_TRBE)>0. )  ZDATA_RSMIN(JI,1)= XEVERG_RSMIN
 IF(DGD%XPAR_VEGTYPE(JI,NVT_TROG)>0. )  ZDATA_RSMIN(JI,2)= 120.
 IF(DGD%XPAR_VEGTYPE(JI,NVT_C4  )>0. )  ZDATA_RSMIN(JI,2)= 120.
 IF (DGD%XPAR_FRAC_HVEG(JI)+DGD%XPAR_FRAC_LVEG(JI) .GT. 0.)              &
    DGD%XPAR_RSMIN(JI,1) =  ( ZDATA_RSMIN(JI,1)*DGD%XPAR_FRAC_HVEG(JI)     &
                       + ZDATA_RSMIN(JI,2)*DGD%XPAR_FRAC_LVEG(JI)   ) &
                     / ( DGD%XPAR_FRAC_HVEG(JI)+DGD%XPAR_FRAC_LVEG(JI) )  
!
! Gamma parameter
 ZDATA_GAMMA(JI,:)= 0.
 IF(DGD%XPAR_VEGTYPE(JI,NVT_TEBD)>0. )  ZDATA_GAMMA(JI,1)= 0.04
 IF(DGD%XPAR_VEGTYPE(JI,NVT_TRBD)>0. )  ZDATA_GAMMA(JI,1)= 0.04
 IF(DGD%XPAR_VEGTYPE(JI,NVT_TEBE)>0. )  ZDATA_GAMMA(JI,1)= 0.04
 IF(DGD%XPAR_VEGTYPE(JI,NVT_BOBD)>0. )  ZDATA_GAMMA(JI,1)= 0.04
 IF(DGD%XPAR_VEGTYPE(JI,NVT_SHRB)>0. )  ZDATA_GAMMA(JI,1)= 0.04
 IF(DGD%XPAR_VEGTYPE(JI,NVT_BONE)>0. )  ZDATA_GAMMA(JI,1)= 0.04
 IF(DGD%XPAR_VEGTYPE(JI,NVT_TENE)>0. )  ZDATA_GAMMA(JI,1)= 0.04
 IF(DGD%XPAR_VEGTYPE(JI,NVT_BOND)>0. )  ZDATA_GAMMA(JI,1)= 0.04
 IF(DGD%XPAR_VEGTYPE(JI,NVT_TRBE)>0. )  ZDATA_GAMMA(JI,1)= 0.04
 IF (DGD%XPAR_FRAC_HVEG(JI)+DGD%XPAR_FRAC_LVEG(JI) .GT. 0.)              &
    DGD%XPAR_GAMMA(JI,1) =  ( ZDATA_GAMMA(JI,1)*DGD%XPAR_FRAC_HVEG(JI)     &
                       + ZDATA_GAMMA(JI,2)*DGD%XPAR_FRAC_LVEG(JI)   ) &
                     / ( DGD%XPAR_FRAC_HVEG(JI)+DGD%XPAR_FRAC_LVEG(JI) )  
!
! Wrmax_cf
 ZDATA_WRMAX_CF(JI,:)= 0.2
 IF(DGD%XPAR_VEGTYPE(JI,NVT_TEBD)>0. )  ZDATA_WRMAX_CF(JI,1)= 0.1
 IF(DGD%XPAR_VEGTYPE(JI,NVT_TRBD)>0. )  ZDATA_WRMAX_CF(JI,1)= 0.1
 IF(DGD%XPAR_VEGTYPE(JI,NVT_TEBE)>0. )  ZDATA_WRMAX_CF(JI,1)= 0.1
 IF(DGD%XPAR_VEGTYPE(JI,NVT_BOBD)>0. )  ZDATA_WRMAX_CF(JI,1)= 0.1
 IF(DGD%XPAR_VEGTYPE(JI,NVT_SHRB)>0. )  ZDATA_WRMAX_CF(JI,1)= 0.1
 IF(DGD%XPAR_VEGTYPE(JI,NVT_BONE)>0. )  ZDATA_WRMAX_CF(JI,1)= 0.1
 IF(DGD%XPAR_VEGTYPE(JI,NVT_TENE)>0. )  ZDATA_WRMAX_CF(JI,1)= 0.1
 IF(DGD%XPAR_VEGTYPE(JI,NVT_BOND)>0. )  ZDATA_WRMAX_CF(JI,1)= 0.1
 IF(DGD%XPAR_VEGTYPE(JI,NVT_TRBE)>0. )  ZDATA_WRMAX_CF(JI,1)= 0.1
 IF (DGD%XPAR_FRAC_HVEG(JI)+DGD%XPAR_FRAC_LVEG(JI) .GT. 0.)                    &
    DGD%XPAR_WRMAX_CF(JI,1) =  ( ZDATA_WRMAX_CF(JI,1)*DGD%XPAR_FRAC_HVEG(JI)     &
                          + ZDATA_WRMAX_CF(JI,2)*DGD%XPAR_FRAC_LVEG(JI)   ) &
                        / ( DGD%XPAR_FRAC_HVEG(JI)+DGD%XPAR_FRAC_LVEG(JI)    )  
!
! Rgl
 ZDATA_RGL(JI,:)= 100.
 IF(DGD%XPAR_VEGTYPE(JI,NVT_TEBD)>0. )  ZDATA_RGL(JI,1)= 30.
 IF(DGD%XPAR_VEGTYPE(JI,NVT_TRBD)>0. )  ZDATA_RGL(JI,1)= 30.
 IF(DGD%XPAR_VEGTYPE(JI,NVT_TEBE)>0. )  ZDATA_RGL(JI,1)= 30.
 IF(DGD%XPAR_VEGTYPE(JI,NVT_BOBD)>0. )  ZDATA_RGL(JI,1)= 30.
 IF(DGD%XPAR_VEGTYPE(JI,NVT_SHRB)>0. )  ZDATA_RGL(JI,1)= 30.
 IF(DGD%XPAR_VEGTYPE(JI,NVT_BONE)>0. )  ZDATA_RGL(JI,1)= 30.
 IF(DGD%XPAR_VEGTYPE(JI,NVT_TENE)>0. )  ZDATA_RGL(JI,1)= 30.
 IF(DGD%XPAR_VEGTYPE(JI,NVT_BOND)>0. )  ZDATA_RGL(JI,1)= 30.
 IF(DGD%XPAR_VEGTYPE(JI,NVT_TRBE)>0. )  ZDATA_RGL(JI,1)= 30.
 IF (DGD%XPAR_FRAC_HVEG(JI)+DGD%XPAR_FRAC_LVEG(JI) .GT. 0.)            &
    DGD%XPAR_RGL(JI,1) =  ( ZDATA_RGL(JI,1)*DGD%XPAR_FRAC_HVEG(JI)       &
                     + ZDATA_RGL(JI,2)*DGD%XPAR_FRAC_LVEG(JI)     ) &
                   / ( DGD%XPAR_FRAC_HVEG(JI)+DGD%XPAR_FRAC_LVEG(JI) )  
!
! Cv
 ZDATA_CV(JI,:)= 2.E-5
 IF(DGD%XPAR_VEGTYPE(JI,NVT_TEBD)>0. )  ZDATA_CV(JI,1)= 1.E-5
 IF(DGD%XPAR_VEGTYPE(JI,NVT_TRBD)>0. )  ZDATA_CV(JI,1)= 1.E-5
 IF(DGD%XPAR_VEGTYPE(JI,NVT_TEBE)>0. )  ZDATA_CV(JI,1)= 1.E-5
 IF(DGD%XPAR_VEGTYPE(JI,NVT_BOBD)>0. )  ZDATA_CV(JI,1)= 1.E-5
 IF(DGD%XPAR_VEGTYPE(JI,NVT_SHRB)>0. )  ZDATA_CV(JI,1)= 1.E-5
 IF(DGD%XPAR_VEGTYPE(JI,NVT_BONE)>0. )  ZDATA_CV(JI,1)= 1.E-5
 IF(DGD%XPAR_VEGTYPE(JI,NVT_TENE)>0. )  ZDATA_CV(JI,1)= 1.E-5
 IF(DGD%XPAR_VEGTYPE(JI,NVT_BOND)>0. )  ZDATA_CV(JI,1)= 1.E-5
 IF(DGD%XPAR_VEGTYPE(JI,NVT_TRBE)>0. )  ZDATA_CV(JI,1)= 1.E-5
 IF (DGD%XPAR_FRAC_HVEG(JI)+DGD%XPAR_FRAC_LVEG(JI) .GT. 0.)           &
    DGD%XPAR_CV(JI,1) =  ( ZDATA_CV(JI,1)*DGD%XPAR_FRAC_HVEG(JI)        &
                    + ZDATA_CV(JI,2)*DGD%XPAR_FRAC_LVEG(JI)      ) &
                  / ( DGD%XPAR_FRAC_HVEG(JI)+DGD%XPAR_FRAC_LVEG(JI) )  
!
! Mesophyll conductance (m s-1)
 ZDATA_GMES(JI,:)=0.020
 IF(DGD%XPAR_VEGTYPE(JI,NVT_TEBD)>0. )  ZDATA_GMES(JI,1)= 0.001
 IF(DGD%XPAR_VEGTYPE(JI,NVT_TRBD)>0. )  ZDATA_GMES(JI,1)= 0.001
 IF(DGD%XPAR_VEGTYPE(JI,NVT_TEBE)>0. )  ZDATA_GMES(JI,1)= 0.001
 IF(DGD%XPAR_VEGTYPE(JI,NVT_BOBD)>0. )  ZDATA_GMES(JI,1)= 0.001
 IF(DGD%XPAR_VEGTYPE(JI,NVT_SHRB)>0. )  ZDATA_GMES(JI,1)= 0.001
 IF(DGD%XPAR_VEGTYPE(JI,NVT_BONE)>0. )  ZDATA_GMES(JI,1)= 0.001
 IF(DGD%XPAR_VEGTYPE(JI,NVT_TENE)>0. )  ZDATA_GMES(JI,1)= 0.001
 IF(DGD%XPAR_VEGTYPE(JI,NVT_BOND)>0. )  ZDATA_GMES(JI,1)= 0.001
 IF(DGD%XPAR_VEGTYPE(JI,NVT_TRBE)>0. )  ZDATA_GMES(JI,1)= 0.001
 IF(DGD%XPAR_VEGTYPE(JI,NVT_C3  )>0. )  ZDATA_GMES(JI,2)= 0.003
 IF(DGD%XPAR_VEGTYPE(JI,NVT_C4  )>0. )  ZDATA_GMES(JI,2)= 0.003
 IF(DGD%XPAR_VEGTYPE(JI,NVT_IRR )>0. )  ZDATA_GMES(JI,2)= 0.003
 IF (DGD%XPAR_FRAC_HVEG(JI)+DGD%XPAR_FRAC_LVEG(JI) .GT. 0.)             &
    DGD%XPAR_GMES(JI,1) =  ( ZDATA_GMES(JI,1)*DGD%XPAR_FRAC_HVEG(JI)      &
                      + ZDATA_GMES(JI,2)*DGD%XPAR_FRAC_LVEG(JI)    ) &
                    / ( DGD%XPAR_FRAC_HVEG(JI)+DGD%XPAR_FRAC_LVEG(JI) )  
!
! Ecosystem Respiration (kg/kg.m.s-1)
 ZDATA_RE25(JI,:)= 3.0E-7 
 IF(DGD%XPAR_VEGTYPE(JI,NVT_BONE)>0. )  ZDATA_RE25(JI,1)= 1.5E-7
 IF(DGD%XPAR_VEGTYPE(JI,NVT_TENE)>0. )  ZDATA_RE25(JI,1)= 1.5E-7
 IF(DGD%XPAR_VEGTYPE(JI,NVT_BOND)>0. )  ZDATA_RE25(JI,1)= 1.5E-7
 IF(DGD%XPAR_VEGTYPE(JI,NVT_C4  )>0. )  ZDATA_RE25(JI,2)= 2.5E-7
 IF (DGD%XPAR_FRAC_HVEG(JI)+DGD%XPAR_FRAC_LVEG(JI) .GT. 0.)             &
    DGD%XPAR_RE25(JI,1) =  ( ZDATA_RE25(JI,1)*DGD%XPAR_FRAC_HVEG(JI)      &
                      + ZDATA_RE25(JI,2)*DGD%XPAR_FRAC_LVEG(JI)    ) &
                    / ( DGD%XPAR_FRAC_HVEG(JI)+DGD%XPAR_FRAC_LVEG(JI) )  
!
! Cuticular conductance (m s-1)
 ZDATA_GC(JI,:)=0.00025
 IF(DGD%XPAR_VEGTYPE(JI,NVT_TEBD)>0. )  ZDATA_GC(JI,1)= 0.00015
 IF(DGD%XPAR_VEGTYPE(JI,NVT_TRBD)>0. )  ZDATA_GC(JI,1)= 0.00015
 IF(DGD%XPAR_VEGTYPE(JI,NVT_TEBE)>0. )  ZDATA_GC(JI,1)= 0.00015
 IF(DGD%XPAR_VEGTYPE(JI,NVT_BOBD)>0. )  ZDATA_GC(JI,1)= 0.00015
 IF(DGD%XPAR_VEGTYPE(JI,NVT_SHRB)>0. )  ZDATA_GC(JI,1)= 0.00015
 IF(DGD%XPAR_VEGTYPE(JI,NVT_BONE)>0. )  ZDATA_GC(JI,1)= 0.
 IF(DGD%XPAR_VEGTYPE(JI,NVT_TENE)>0. )  ZDATA_GC(JI,1)= 0.
 IF(DGD%XPAR_VEGTYPE(JI,NVT_BOND)>0. )  ZDATA_GC(JI,1)= 0.
 IF(DGD%XPAR_VEGTYPE(JI,NVT_TRBE)>0. )  ZDATA_GC(JI,1)= 0.00015   
 IF (DGD%XPAR_FRAC_HVEG(JI)+DGD%XPAR_FRAC_LVEG(JI) .GT. 0.)           &
    DGD%XPAR_GC(JI,1) =  ( ZDATA_GC(JI,1)*DGD%XPAR_FRAC_HVEG(JI)        &
                    + ZDATA_GC(JI,2)*DGD%XPAR_FRAC_LVEG(JI)      ) &
                  / ( DGD%XPAR_FRAC_HVEG(JI)+DGD%XPAR_FRAC_LVEG(JI) )  
!
! Ratio d(biomass)/d(lai) (kg/m2)
 ZDATA_BSLAI(JI,:)=0.36 
 IF(DGD%XPAR_VEGTYPE(JI,NVT_TEBD)>0. )  ZDATA_BSLAI(JI,1)= 0.25
 IF(DGD%XPAR_VEGTYPE(JI,NVT_TRBD)>0. )  ZDATA_BSLAI(JI,1)= 0.25
 IF(DGD%XPAR_VEGTYPE(JI,NVT_TEBE)>0. )  ZDATA_BSLAI(JI,1)= 0.25
 IF(DGD%XPAR_VEGTYPE(JI,NVT_BOBD)>0. )  ZDATA_BSLAI(JI,1)= 0.25
 IF(DGD%XPAR_VEGTYPE(JI,NVT_SHRB)>0. )  ZDATA_BSLAI(JI,1)= 0.25
 IF(DGD%XPAR_VEGTYPE(JI,NVT_BONE)>0. )  ZDATA_BSLAI(JI,1)= 0.25
 IF(DGD%XPAR_VEGTYPE(JI,NVT_TENE)>0. )  ZDATA_BSLAI(JI,1)= 0.25
 IF(DGD%XPAR_VEGTYPE(JI,NVT_BOND)>0. )  ZDATA_BSLAI(JI,1)= 0.25
 IF(DGD%XPAR_VEGTYPE(JI,NVT_TRBE)>0. )  ZDATA_BSLAI(JI,1)= 0.25
 IF(DGD%XPAR_VEGTYPE(JI,NVT_C3  )>0. )  ZDATA_BSLAI(JI,2)= 0.06
 IF(DGD%XPAR_VEGTYPE(JI,NVT_C4  )>0. )  ZDATA_BSLAI(JI,2)= 0.06
 IF(DGD%XPAR_VEGTYPE(JI,NVT_IRR )>0. )  ZDATA_BSLAI(JI,2)= 0.06
 IF (DGD%XPAR_FRAC_HVEG(JI)+DGD%XPAR_FRAC_LVEG(JI) .GT. 0.)              &
    DGD%XPAR_BSLAI(JI,1) =  ( ZDATA_BSLAI(JI,1)*DGD%XPAR_FRAC_HVEG(JI)     &
                       + ZDATA_BSLAI(JI,2)*DGD%XPAR_FRAC_LVEG(JI)   ) &
                     / ( DGD%XPAR_FRAC_HVEG(JI)+DGD%XPAR_FRAC_LVEG(JI) )  
!
! Maximum air saturation deficit tolerate by vegetation (kg/kg)
 ZDATA_DMAX(JI,:) = 0.1
 IF(DGD%XPAR_VEGTYPE(JI,NVT_TEBD)>0. )  ZDATA_DMAX(JI,1)= 0.1
 IF(DGD%XPAR_VEGTYPE(JI,NVT_TRBD)>0. )  ZDATA_DMAX(JI,1)= 0.1
 IF(DGD%XPAR_VEGTYPE(JI,NVT_TEBE)>0. )  ZDATA_DMAX(JI,1)= 0.1
 IF(DGD%XPAR_VEGTYPE(JI,NVT_BOBD)>0. )  ZDATA_DMAX(JI,1)= 0.1
 IF(DGD%XPAR_VEGTYPE(JI,NVT_SHRB)>0. )  ZDATA_DMAX(JI,1)= 0.1
 IF(DGD%XPAR_VEGTYPE(JI,NVT_BONE)>0. )  ZDATA_DMAX(JI,1)= 0.1
 IF(DGD%XPAR_VEGTYPE(JI,NVT_TENE)>0. )  ZDATA_DMAX(JI,1)= 0.1
 IF(DGD%XPAR_VEGTYPE(JI,NVT_BOND)>0. )  ZDATA_DMAX(JI,1)= 0.1
 IF(DGD%XPAR_VEGTYPE(JI,NVT_TRBE)>0. )  ZDATA_DMAX(JI,1)= 0.1
 IF (DGD%XPAR_FRAC_HVEG(JI)+DGD%XPAR_FRAC_LVEG(JI) .GT. 0.)             &
    DGD%XPAR_DMAX(JI,1) =  ( ZDATA_DMAX(JI,1)*DGD%XPAR_FRAC_HVEG(JI)      &
                      + ZDATA_DMAX(JI,2)*DGD%XPAR_FRAC_LVEG(JI)    ) &
                    / ( DGD%XPAR_FRAC_HVEG(JI)+DGD%XPAR_FRAC_LVEG(JI) )  
!
! e-folding time for senescence (days)
 ZDATA_SEFOLD(JI,:)=90. * XDAY
 IF(DGD%XPAR_VEGTYPE(JI,NVT_TEBD)>0. )  ZDATA_SEFOLD(JI,1)= 365.* XDAY
 IF(DGD%XPAR_VEGTYPE(JI,NVT_TRBD)>0. )  ZDATA_SEFOLD(JI,1)= 365.* XDAY
 IF(DGD%XPAR_VEGTYPE(JI,NVT_TEBE)>0. )  ZDATA_SEFOLD(JI,1)= 365.* XDAY
 IF(DGD%XPAR_VEGTYPE(JI,NVT_BOBD)>0. )  ZDATA_SEFOLD(JI,1)= 365.* XDAY
 IF(DGD%XPAR_VEGTYPE(JI,NVT_SHRB)>0. )  ZDATA_SEFOLD(JI,1)= 365.* XDAY
 IF(DGD%XPAR_VEGTYPE(JI,NVT_BONE)>0. )  ZDATA_SEFOLD(JI,1)= 365.* XDAY
 IF(DGD%XPAR_VEGTYPE(JI,NVT_TENE)>0. )  ZDATA_SEFOLD(JI,1)= 365.* XDAY
 IF(DGD%XPAR_VEGTYPE(JI,NVT_BOND)>0. )  ZDATA_SEFOLD(JI,1)= 365.* XDAY
 IF(DGD%XPAR_VEGTYPE(JI,NVT_TRBE)>0. )  ZDATA_SEFOLD(JI,1)= 365.* XDAY
 IF(DGD%XPAR_VEGTYPE(JI,NVT_C3  )>0. )  ZDATA_SEFOLD(JI,2)=  60.* XDAY
 IF(DGD%XPAR_VEGTYPE(JI,NVT_C4  )>0. )  ZDATA_SEFOLD(JI,2)=  60.* XDAY
 IF(DGD%XPAR_VEGTYPE(JI,NVT_IRR )>0. )  ZDATA_SEFOLD(JI,2)=  60.* XDAY
 IF (DGD%XPAR_FRAC_HVEG(JI)+DGD%XPAR_FRAC_LVEG(JI) .GT. 0.)                &
    DGD%XPAR_SEFOLD(JI,1) =  ( ZDATA_SEFOLD(JI,1)*DGD%XPAR_FRAC_HVEG(JI)     &
                        + ZDATA_SEFOLD(JI,2)*DGD%XPAR_FRAC_LVEG(JI)   ) &
                      / ( DGD%XPAR_FRAC_HVEG(JI)+DGD%XPAR_FRAC_LVEG(JI)  )  
!
! Minimum LAI (m2/m2)
 ZDATA_LAIMIN (JI,:) = 0.3
 IF(DGD%XPAR_VEGTYPE(JI,NVT_BONE)>0. )  ZDATA_LAIMIN(JI,1)= 1.0
 IF(DGD%XPAR_VEGTYPE(JI,NVT_TENE)>0. )  ZDATA_LAIMIN(JI,1)= 1.0
 IF(DGD%XPAR_VEGTYPE(JI,NVT_BOND)>0. )  ZDATA_LAIMIN(JI,1)= 1.0
 IF(DGD%XPAR_VEGTYPE(JI,NVT_TRBE)>0. )  ZDATA_LAIMIN(JI,1)= 1.0
 IF (DGD%XPAR_FRAC_HVEG(JI)+DGD%XPAR_FRAC_LVEG(JI) .GT. 0.)                &
    DGD%XPAR_LAIMIN(JI,1) =  ( ZDATA_LAIMIN(JI,1)*DGD%XPAR_FRAC_HVEG(JI)     &
                        + ZDATA_LAIMIN(JI,2)*DGD%XPAR_FRAC_LVEG(JI)   ) &
                      / ( DGD%XPAR_FRAC_HVEG(JI)+DGD%XPAR_FRAC_LVEG(JI)  )  
!
! Leaf aera ratio sensitivity to nitrogen concentration
 ZDATA_CE_NITRO(JI,:)=7.68
 IF(DGD%XPAR_VEGTYPE(JI,NVT_TEBD)>0. )  ZDATA_CE_NITRO(JI,1)= 4.83
 IF(DGD%XPAR_VEGTYPE(JI,NVT_TRBD)>0. )  ZDATA_CE_NITRO(JI,1)= 4.83
 IF(DGD%XPAR_VEGTYPE(JI,NVT_TEBE)>0. )  ZDATA_CE_NITRO(JI,1)= 4.83
 IF(DGD%XPAR_VEGTYPE(JI,NVT_BOBD)>0. )  ZDATA_CE_NITRO(JI,1)= 4.83
 IF(DGD%XPAR_VEGTYPE(JI,NVT_SHRB)>0. )  ZDATA_CE_NITRO(JI,1)= 4.83
 IF(DGD%XPAR_VEGTYPE(JI,NVT_BONE)>0. )  ZDATA_CE_NITRO(JI,1)= 4.85
 IF(DGD%XPAR_VEGTYPE(JI,NVT_TENE)>0. )  ZDATA_CE_NITRO(JI,1)= 4.85
 IF(DGD%XPAR_VEGTYPE(JI,NVT_BOND)>0. )  ZDATA_CE_NITRO(JI,1)= 4.85
 IF(DGD%XPAR_VEGTYPE(JI,NVT_TRBE)>0. )  ZDATA_CE_NITRO(JI,1)= 4.83
 IF(DGD%XPAR_VEGTYPE(JI,NVT_C3  )>0. )  ZDATA_CE_NITRO(JI,2)= 3.79
 IF(DGD%XPAR_VEGTYPE(JI,NVT_GRAS)>0. )  ZDATA_CE_NITRO(JI,2)= 5.56
 IF(DGD%XPAR_VEGTYPE(JI,NVT_BOGR)>0. )  ZDATA_CE_NITRO(JI,2)= 5.56
 IF(DGD%XPAR_VEGTYPE(JI,NVT_PARK)>0. )  ZDATA_CE_NITRO(JI,2)= 5.56
 IF (DGD%XPAR_FRAC_HVEG(JI)+DGD%XPAR_FRAC_LVEG(JI) .GT. 0.)                    &
    DGD%XPAR_CE_NITRO(JI,1) =  ( ZDATA_CE_NITRO(JI,1)*DGD%XPAR_FRAC_HVEG(JI)     &
                          + ZDATA_CE_NITRO(JI,2)*DGD%XPAR_FRAC_LVEG(JI)   ) &
                        / ( DGD%XPAR_FRAC_HVEG(JI)+DGD%XPAR_FRAC_LVEG(JI)    )  
!
! Lethal minimum value of leaf area ratio
 ZDATA_CF_NITRO(JI,:)=-4.33
 IF(DGD%XPAR_VEGTYPE(JI,NVT_TEBD)>0. )  ZDATA_CF_NITRO(JI,1)= 2.53
 IF(DGD%XPAR_VEGTYPE(JI,NVT_TRBD)>0. )  ZDATA_CF_NITRO(JI,1)= 2.53
 IF(DGD%XPAR_VEGTYPE(JI,NVT_TEBE)>0. )  ZDATA_CF_NITRO(JI,1)= 2.53
 IF(DGD%XPAR_VEGTYPE(JI,NVT_BOBD)>0. )  ZDATA_CF_NITRO(JI,1)= 2.53
 IF(DGD%XPAR_VEGTYPE(JI,NVT_SHRB)>0. )  ZDATA_CF_NITRO(JI,1)= 2.53
 IF(DGD%XPAR_VEGTYPE(JI,NVT_BONE)>0. )  ZDATA_CF_NITRO(JI,1)= -0.24
 IF(DGD%XPAR_VEGTYPE(JI,NVT_TENE)>0. )  ZDATA_CF_NITRO(JI,1)= -0.24
 IF(DGD%XPAR_VEGTYPE(JI,NVT_BOND)>0. )  ZDATA_CF_NITRO(JI,1)= -0.24
 IF(DGD%XPAR_VEGTYPE(JI,NVT_TRBE)>0. )  ZDATA_CF_NITRO(JI,1)= 0.12
 IF(DGD%XPAR_VEGTYPE(JI,NVT_C3  )>0. )  ZDATA_CF_NITRO(JI,2)=  9.84
 IF(DGD%XPAR_VEGTYPE(JI,NVT_GRAS)>0. )  ZDATA_CF_NITRO(JI,2)=  6.73
 IF(DGD%XPAR_VEGTYPE(JI,NVT_BOGR)>0. )  ZDATA_CF_NITRO(JI,2)=  6.73 
 IF(DGD%XPAR_VEGTYPE(JI,NVT_PARK)>0. )  ZDATA_CF_NITRO(JI,2)=  6.73
 IF (DGD%XPAR_FRAC_HVEG(JI)+DGD%XPAR_FRAC_LVEG(JI) .GT. 0.)                    &
    DGD%XPAR_CF_NITRO(JI,1) =  ( ZDATA_CF_NITRO(JI,1)*DGD%XPAR_FRAC_HVEG(JI)     &
                          + ZDATA_CF_NITRO(JI,2)*DGD%XPAR_FRAC_LVEG(JI)   ) &
                        / ( DGD%XPAR_FRAC_HVEG(JI)+DGD%XPAR_FRAC_LVEG(JI)    )  
!
! Nitrogen concentration of active biomass
 ZDATA_CNA_NITRO(JI,:)=1.3
 IF(DGD%XPAR_VEGTYPE(JI,NVT_TEBD)>0. )  ZDATA_CNA_NITRO(JI,1)= 2.0
 IF(DGD%XPAR_VEGTYPE(JI,NVT_TRBD)>0. )  ZDATA_CNA_NITRO(JI,1)= 2.0
 IF(DGD%XPAR_VEGTYPE(JI,NVT_TEBE)>0. )  ZDATA_CNA_NITRO(JI,1)= 2.0
 IF(DGD%XPAR_VEGTYPE(JI,NVT_BOBD)>0. )  ZDATA_CNA_NITRO(JI,1)= 2.0
 IF(DGD%XPAR_VEGTYPE(JI,NVT_SHRB)>0. )  ZDATA_CNA_NITRO(JI,1)= 2.0
 IF(DGD%XPAR_VEGTYPE(JI,NVT_BONE)>0. )  ZDATA_CNA_NITRO(JI,1)= 2.8
 IF(DGD%XPAR_VEGTYPE(JI,NVT_TENE)>0. )  ZDATA_CNA_NITRO(JI,1)= 2.8
 IF(DGD%XPAR_VEGTYPE(JI,NVT_BOND)>0. )  ZDATA_CNA_NITRO(JI,1)= 2.8
 IF(DGD%XPAR_VEGTYPE(JI,NVT_TRBE)>0. )  ZDATA_CNA_NITRO(JI,1)= 1.7
 IF(DGD%XPAR_VEGTYPE(JI,NVT_C4  )>0. )  ZDATA_CNA_NITRO(JI,2)= 1.9
 IF(DGD%XPAR_VEGTYPE(JI,NVT_IRR )>0. )  ZDATA_CNA_NITRO(JI,2)= 1.9
 IF (DGD%XPAR_FRAC_HVEG(JI)+DGD%XPAR_FRAC_LVEG(JI) .GT. 0.)                      &
    DGD%XPAR_CNA_NITRO(JI,1) =  ( ZDATA_CNA_NITRO(JI,1)*DGD%XPAR_FRAC_HVEG(JI)     &
                           + ZDATA_CNA_NITRO(JI,2)*DGD%XPAR_FRAC_LVEG(JI)   ) &
                         / ( DGD%XPAR_FRAC_HVEG(JI)+DGD%XPAR_FRAC_LVEG(JI)     )  
!
! Ground layers
 IF (GDO%NGROUND_LAYER<=3) THEN
   ZDATA_DG(JI,1,:) = 0.01
   ZDATA_DG(JI,2,:) = 1.50
   IF(DGD%XPAR_VEGTYPE(JI,NVT_TEBD)>0. )  ZDATA_DG(JI,2,1)= 2.0
   IF(DGD%XPAR_VEGTYPE(JI,NVT_TRBD)>0. )  ZDATA_DG(JI,2,1)= 2.0
   IF(DGD%XPAR_VEGTYPE(JI,NVT_TEBE)>0. )  ZDATA_DG(JI,2,1)= 2.0
   IF(DGD%XPAR_VEGTYPE(JI,NVT_BOBD)>0. )  ZDATA_DG(JI,2,1)= 2.0
   IF(DGD%XPAR_VEGTYPE(JI,NVT_SHRB)>0. )  ZDATA_DG(JI,2,1)= 2.0
   IF(DGD%XPAR_VEGTYPE(JI,NVT_BONE)>0. )  ZDATA_DG(JI,2,1)= 2.0
   IF(DGD%XPAR_VEGTYPE(JI,NVT_TENE)>0. )  ZDATA_DG(JI,2,1)= 2.0
   IF(DGD%XPAR_VEGTYPE(JI,NVT_BOND)>0. )  ZDATA_DG(JI,2,1)= 2.0
   IF(DGD%XPAR_VEGTYPE(JI,NVT_TRBE)>0. )  ZDATA_DG(JI,2,1)= 2.0
   IF(DGD%XPAR_VEGTYPE(JI,NVT_NO  )>0. )  ZDATA_DG(JI,2,3)= 0.5
   IF(DGD%XPAR_VEGTYPE(JI,NVT_ROCK)>0. )  ZDATA_DG(JI,2,3)= 0.5
   IF(DGD%XPAR_VEGTYPE(JI,NVT_SNOW)>0. )  ZDATA_DG(JI,2,3)= 0.5
   IF (GDO%NGROUND_LAYER==3) THEN
      ZDATA_DG(JI,3,:) = 2.00
      IF(DGD%XPAR_VEGTYPE(JI,NVT_TEBD)>0. )  ZDATA_DG(JI,3,1)= 3.0
      IF(DGD%XPAR_VEGTYPE(JI,NVT_TRBD)>0. )  ZDATA_DG(JI,3,1)= 3.0
      IF(DGD%XPAR_VEGTYPE(JI,NVT_TEBE)>0. )  ZDATA_DG(JI,3,1)= 3.0
      IF(DGD%XPAR_VEGTYPE(JI,NVT_BOBD)>0. )  ZDATA_DG(JI,3,1)= 3.0
      IF(DGD%XPAR_VEGTYPE(JI,NVT_SHRB)>0. )  ZDATA_DG(JI,3,1)= 3.0
      IF(DGD%XPAR_VEGTYPE(JI,NVT_BONE)>0. )  ZDATA_DG(JI,3,1)= 3.0
      IF(DGD%XPAR_VEGTYPE(JI,NVT_TENE)>0. )  ZDATA_DG(JI,3,1)= 3.0
      IF(DGD%XPAR_VEGTYPE(JI,NVT_BOND)>0. )  ZDATA_DG(JI,3,1)= 3.0
      IF(DGD%XPAR_VEGTYPE(JI,NVT_TRBE)>0. )  ZDATA_DG(JI,3,1)= 3.0
      IF(DGD%XPAR_VEGTYPE(JI,NVT_NO  )>0. )  ZDATA_DG(JI,3,3)= 1.0
      IF(DGD%XPAR_VEGTYPE(JI,NVT_ROCK)>0. )  ZDATA_DG(JI,3,3)= 1.0
      IF(DGD%XPAR_VEGTYPE(JI,NVT_SNOW)>0. )  ZDATA_DG(JI,3,3)= 1.0
   ENDIF
   DGD%XPAR_DG(JI,:,1) =    ZDATA_DG(JI,:,1)*DGD%XPAR_FRAC_HVEG(JI)   &
                       + ZDATA_DG(JI,:,2)*DGD%XPAR_FRAC_LVEG(JI) &
                       + ZDATA_DG(JI,:,3)*DGD%XPAR_FRAC_NVEG(JI)  
 ELSEIF (GDO%NGROUND_LAYER<=NOPTIMLAYER) THEN
   DGD%XPAR_DG(JI,:,1) = XOPTIMGRID(:)
 ELSE
   CALL ABOR1_SFX("READ_PGD_TEB_GARDEN_PAR: WITH MORE THAN 14 SOIL LAYERS, "//&
     "WITHOUT ECOCLIMAP, GARDEN CANNOT RUN")
 ENDIF 
!
! Root fractions
 DGD%XPAR_ROOTFRAC(JI,GDO%NGROUND_LAYER,1) = 1.
 DGD%XPAR_ROOTFRAC(JI,1,1) = 0.20
 IF (GDO%NGROUND_LAYER>2) THEN
   DO JLAYER = GDO%NGROUND_LAYER-1,2,-1
     DGD%XPAR_ROOTFRAC(JI,JLAYER,1) = DGD%XPAR_ROOTFRAC(JI,JLAYER+1,1)-0.8/(GDO%NGROUND_LAYER-1)
   ENDDO
 ENDIF
!
 DGD%XPAR_DICE(JI,1) = DGD%XPAR_DG(JI,2,1)
!
 DO JTIME=1,DGD%NTIME
! Leaf Area Index
 IF (DGD%XPAR_FRAC_HVEG(JI)+DGD%XPAR_FRAC_LVEG(JI) .GT. 0.)                           &
     DGD%XPAR_LAI     (JI,JTIME,1) = ( DGD%XPAR_LAI_HVEG(JI,JTIME)*DGD%XPAR_FRAC_HVEG(JI)  &
                                + DGD%XPAR_LAI_LVEG(JI,JTIME)*DGD%XPAR_FRAC_LVEG(JI)) &
                               /( DGD%XPAR_FRAC_HVEG(JI)+DGD%XPAR_FRAC_LVEG(JI))  
! Fraction of vegetation
  DGD%XPAR_VEG     (JI,JTIME,1) = VEG_FROM_LAI  (DGD%XPAR_LAI    (JI,JTIME,1),       &
                                            DGD%XPAR_VEGTYPE(JI,:),GAGRI_TO_GRASS)  
! Roughness length for momentum
  DGD%XPAR_Z0      (JI,JTIME,1) = Z0V_FROM_LAI  (DGD%XPAR_LAI    (JI,JTIME,1),       &
                                            DGD%XPAR_H_TREE (JI,1),           &
                                            DGD%XPAR_VEGTYPE(JI,:),GAGRI_TO_GRASS)  
! Emissivity
  DGD%XPAR_EMIS    (JI,JTIME,1) = EMIS_FROM_VEG (DGD%XPAR_VEG    (JI,JTIME,1),       &
                                            DGD%XPAR_VEGTYPE(JI,:))
 END DO
!
ENDDO
IF (LHOOK) CALL DR_HOOK('READ_PGD_TEB_GARDEN_PAR_N',1,ZHOOK_HANDLE)
!
!-------------------------------------------------------------------------------
!
END SUBROUTINE READ_PGD_TEB_GARDEN_PAR_n
