MODULE ICE_NONE
USE ABSTRACT_ICE
IMPLICIT NONE
PRIVATE

TYPE, PUBLIC, EXTENDS(SEA_ICE_t) :: ICE_NONE_t
  CONTAINS
    PROCEDURE :: INIT
    PROCEDURE :: PREP
    PROCEDURE :: ASSIM
    PROCEDURE :: RUN
    PROCEDURE :: DEALLOC

    PROCEDURE :: READSURF
    PROCEDURE :: WRITESURF
    PROCEDURE :: WRITE_DIAG

    PROCEDURE :: GET_RESPONSE
END TYPE ICE_NONE_t

CONTAINS

SUBROUTINE INIT(THIS, HPROGRAM)
  CLASS(ICE_NONE_t) :: THIS
  CHARACTER(LEN=6), INTENT(IN)  :: HPROGRAM
END SUBROUTINE INIT

SUBROUTINE PREP(THIS, KLU, HPROGRAM, HATMFILE, HATMFILETYPE, HPGDFILE, HPGDFILETYPE)
  CLASS(ICE_NONE_t) :: THIS
  INTEGER, INTENT(IN) :: KLU
  CHARACTER(LEN=6),   INTENT(IN)  :: HPROGRAM  !< program calling surf. schemes
  CHARACTER(LEN=28),  INTENT(IN)  :: HATMFILE    !< name of the Atmospheric file
  CHARACTER(LEN=6),   INTENT(IN)  :: HATMFILETYPE!< type of the Atmospheric file
  CHARACTER(LEN=28),  INTENT(IN)  :: HPGDFILE    !< name of the PGD file
  CHARACTER(LEN=6),   INTENT(IN)  :: HPGDFILETYPE!< type of the PGD file
END SUBROUTINE PREP

SUBROUTINE ASSIM(THIS)
  CLASS(ICE_NONE_t) :: THIS
END SUBROUTINE ASSIM

SUBROUTINE RUN( &
    THIS, HPROGRAM, PTIMEC, PTSTEP, KSTEP, ESM_CPL, PFSIC, PFSIT, PSI_FLX_DRV, PFREEZING_SST, &
    PZENITH, PSW_TOT, PLW, &
    PPEW_A_COEF, PPEW_B_COEF, PPET_A_COEF, PPEQ_A_COEF, PPET_B_COEF, PPEQ_B_COEF)
  CLASS(ICE_NONE_t) :: THIS
  CHARACTER(LEN=6),    INTENT(IN) :: HPROGRAM  !< program calling surf. schemes
  REAL,                INTENT(IN) :: PTIMEC    !< current duration since start of the run (s)
  REAL,                INTENT(IN) :: PTSTEP    !< surface time-step (s)
  INTEGER, INTENT(IN) :: KSTEP !< number of ice time steps within a surface time-step
  TYPE(ESM_CPL_t), INTENT(INOUT) :: ESM_CPL
  REAL, INTENT(IN) :: PFSIC(:)
  REAL, INTENT(IN) :: PFSIT(:)
  REAL, INTENT(IN) :: PSI_FLX_DRV
  REAL, INTENT(IN) :: PFREEZING_SST

  REAL, INTENT(IN) :: PZENITH(:) !< Zenithal angle at t  (radian from the vertical)
  REAL, INTENT(IN) :: PSW_TOT(:) !< Shortwave radiation flux at the surface.
  REAL, INTENT(IN) :: PLW(:) !< Longwave radiation flux at the surface.

  REAL, INTENT(IN) :: PPEW_A_COEF(:) ! implicit coefficients   (m2s/kg)
  REAL, INTENT(IN) :: PPEW_B_COEF(:) ! needed if HCOUPLING='I' (m/s)
  REAL, INTENT(IN) :: PPET_A_COEF(:)
  REAL, INTENT(IN) :: PPEQ_A_COEF(:)
  REAL, INTENT(IN) :: PPET_B_COEF(:)
  REAL, INTENT(IN) :: PPEQ_B_COEF(:)
END SUBROUTINE RUN

SUBROUTINE DEALLOC(THIS)
  CLASS(ICE_NONE_t) :: THIS
END SUBROUTINE DEALLOC

SUBROUTINE READSURF(THIS, G, HPROGRAM, KLU, KLUOUT)
  USE MODD_SFX_GRID_n, ONLY : GRID_t
  CLASS(ICE_NONE_t) :: THIS
  TYPE(GRID_t), INTENT(INOUT)   :: G
  CHARACTER(LEN=6),  INTENT(IN) :: HPROGRAM !< calling program
  INTEGER,           INTENT(IN) :: KLU      !< number of sea patch point
  INTEGER,           INTENT(IN) :: KLUOUT
END SUBROUTINE READSURF

SUBROUTINE WRITESURF(THIS, HSELECT, HPROGRAM)
  USE MODD_SFX_GRID_n, ONLY : GRID_t
  CLASS(ICE_NONE_t) :: THIS
  CHARACTER(LEN=*), INTENT(IN) :: HSELECT(:)
  CHARACTER(LEN=6), INTENT(IN) :: HPROGRAM
END SUBROUTINE WRITESURF

SUBROUTINE WRITE_DIAG(THIS, HSELECT, HPROGRAM)
  USE MODD_SFX_GRID_n, ONLY : GRID_t
  CLASS(ICE_NONE_t) :: THIS
  CHARACTER(LEN=*), INTENT(IN) :: HSELECT(:)
  CHARACTER(LEN=6), INTENT(IN) :: HPROGRAM
END SUBROUTINE WRITE_DIAG

SUBROUTINE GET_RESPONSE(THIS, PSIC, PTICE, PICE_ALB)
  CLASS(ICE_NONE_t) :: THIS
  REAL, INTENT(OUT) :: PSIC(:)
  REAL, INTENT(OUT) :: PTICE(:)
  REAL, INTENT(OUT) :: PICE_ALB(:)
END SUBROUTINE GET_RESPONSE

END MODULE ICE_NONE