SUBROUTINE SURFEX_ALLOC(YDSURFEX)
!
USE MODD_TEB_PAR, ONLY : NTEB_PATCH_MAX
USE MODD_DATA_COVER_PAR, ONLY : NVEGTYPE, NTILESFC
!
USE MODD_SURFEX_n, ONLY : SURFEX_t
!
USE MODD_AGRI_n, ONLY : AGRI_INIT
USE MODD_BEM_OPTION_n, ONLY : BEM_OPTIONS_INIT
USE MODD_BLD_DESCRIPTION_n, ONLY : BLD_DESC_INIT
USE MODD_CH_EMIS_FIELD_n, ONLY : CH_EMIS_FIELD_INIT
USE MODD_CH_FLAKE_n, ONLY : CH_FLAKE_INIT
USE MODD_CH_ISBA_n, ONLY : CH_ISBA_INIT
USE MODD_CH_SEAFLUX_n, ONLY : CH_SEAFLUX_INIT
USE MODD_CH_SNAP_n, ONLY : CH_EMIS_SNAP_INIT
USE MODD_CH_SURF_n, ONLY : CH_SURF_INIT
USE MODD_CH_TEB_n, ONLY : CH_TEB_INIT
USE MODD_CH_WATFLUX_n, ONLY : CH_WATFLUX_INIT
USE MODD_DATA_BEM_n, ONLY : DATA_BEM_INIT
USE MODD_DATA_COVER_n, ONLY : DATA_COVER_INIT
USE MODD_DATA_ISBA_n, ONLY : DATA_ISBA_INIT
USE MODD_DATA_SEAFLUX_n, ONLY : DATA_SEAFLUX_INIT
USE MODD_DATA_TEB_GARDEN_n, ONLY : DATA_TEB_GARDEN_INIT
USE MODD_DATA_TEB_GREENROOF_n, ONLY : DATA_TEB_GREENROOF_INIT
USE MODD_DATA_TEB_n, ONLY : DATA_TEB_INIT
USE MODD_DATA_TSZ0_n, ONLY : DATA_TSZ0_INIT
USE MODD_DIAG_EVAP_ISBA_n, ONLY : DIAG_EVAP_ISBA_INIT, DIAG_EVAP_ISBA_PATCH_INIT
USE MODD_DIAG_n, ONLY : DIAG_INIT, DIAG_PATCH_INIT
USE MODD_DIAG_MISC_FLAKE_n, ONLY : DIAG_MISC_FLAKE_INIT
USE MODD_DIAG_MISC_ISBA_n, ONLY : DIAG_MISC_ISBA_INIT, DIAG_MISC_ISBA_PATCH_INIT
USE MODD_DIAG_MISC_TEB_OPTION_n, ONLY : DIAG_MISC_TEB_OPTIONS_INIT
USE MODD_DIAG_OCEAN_n, ONLY : DIAG_OCEAN_INIT
USE MODD_DIAG_MISC_SEAICE_n, ONLY : DIAG_MISC_SEAICE_INIT
USE MODD_DIAG_UTCI_TEB_n, ONLY : DIAG_UTCI_TEB_INIT
USE MODD_DST_n, ONLY : DST_INIT
USE MODD_DUMMY_SURF_FIELDS_n, ONLY : DUMMY_SURF_FIELDS_INIT
USE MODD_EMIS_GR_FIELD_n, ONLY : EMIS_GR_FIELD_INIT
USE MODD_GRID_n, ONLY : GRID_INIT
USE MODD_FLAKE_n, ONLY : FLAKE_INIT
USE MODD_GR_BIOG_GARDEN_n, ONLY : GR_BIOG_GARDEN_INIT
USE MODD_GR_BIOG_GREENROOF_n, ONLY : GR_BIOG_GREENROOF_INIT
USE MODD_GR_BIOG_n, ONLY : GR_BIOG_INIT
USE MODD_IDEAL_n, ONLY : IDEAL_INIT
USE MODD_CANOPY_n, ONLY : CANOPY_INIT
USE MODD_ISBA_n, ONLY : ISBA_INIT
USE MODD_OCEAN_n, ONLY : OCEAN_INIT
USE MODD_OCEAN_REL_n, ONLY : OCEAN_REL_INIT
USE MODD_PACK_CH_ISBA, ONLY : PACK_CH_ISBA_INIT
USE MODD_PACK_DIAG_ISBA, ONLY : PACK_DIAG_ISBA_INIT
USE MODD_PACK_ISBA, ONLY : PACK_ISBA_INIT
USE MODD_SEAFLUX_n, ONLY : SEAFLUX_INIT
USE MODD_SLT_n, ONLY : SLT_INIT
USE MODD_SURF_ATM_GRID_n, ONLY : SURF_ATM_GRID_INIT
USE MODD_SURF_ATM_n, ONLY : SURF_ATM_INIT
USE MODD_SURF_ATM_SSO_n, ONLY : SURF_ATM_SSO_INIT
USE MODD_SV_n, ONLY : SV_INIT
USE MODD_TEB_VEG_n, ONLY : TEB_VEG_INIT
USE MODD_TEB_IRRIG_n, ONLY : TEB_IRRIG_INIT
USE MODD_TEB_OPTION_n, ONLY : TEB_OPTIONS_INIT
USE MODD_TEB_PANEL_n, ONLY : TEB_PANEL_INIT
USE MODD_WATFLUX_n, ONLY : WATFLUX_INIT
!
USE MODD_BEM_n, ONLY : BEM_INIT
USE MODD_DIAG_CUMUL_TEB_n, ONLY : DIAG_CUMUL_TEB_INIT
USE MODD_DIAG_MISC_TEB_n, ONLY : DIAG_MISC_TEB_INIT
USE MODD_TEB_n, ONLY : TEB_INIT
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE
!
TYPE (SURFEX_t), INTENT (INOUT) :: YDSURFEX
REAL(KIND=JPRB) :: ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK("SURFEX_ALLOC",0,ZHOOK_HANDLE)
!
  CALL CH_FLAKE_INIT(YDSURFEX%FM%CHF)
  CALL DIAG_INIT(YDSURFEX%FM%DGF)
  CALL DIAG_INIT(YDSURFEX%FM%DGFC)
  CALL DIAG_MISC_FLAKE_INIT(YDSURFEX%FM%DGMF)
  CALL GRID_INIT(YDSURFEX%FM%FG)
  CALL FLAKE_INIT(YDSURFEX%FM%F)
  CALL CANOPY_INIT(YDSURFEX%FM%FSB)
  !  
  CALL CH_WATFLUX_INIT(YDSURFEX%WM%CHW)
  CALL DIAG_INIT(YDSURFEX%WM%DGW)
  CALL DIAG_INIT(YDSURFEX%WM%DGWC)
  CALL GRID_INIT(YDSURFEX%WM%WG)
  CALL WATFLUX_INIT(YDSURFEX%WM%W)
  CALL CANOPY_INIT(YDSURFEX%WM%WSB)
  !
  CALL CH_SEAFLUX_INIT(YDSURFEX%SM%CHS)
  CALL DATA_SEAFLUX_INIT(YDSURFEX%SM%DTS)
  CALL DIAG_OCEAN_INIT(YDSURFEX%SM%DGO)
  CALL DIAG_INIT(YDSURFEX%SM%DGS)
  CALL DIAG_INIT(YDSURFEX%SM%DGSC)
  CALL DIAG_INIT(YDSURFEX%SM%DGSI)
  CALL DIAG_INIT(YDSURFEX%SM%DGSIC)
  CALL DIAG_MISC_SEAICE_INIT(YDSURFEX%SM%DGMSI)
  CALL OCEAN_INIT(YDSURFEX%SM%O)
  CALL OCEAN_REL_INIT(YDSURFEX%SM%OR)
  CALL GRID_INIT(YDSURFEX%SM%SG)
  CALL SEAFLUX_INIT(YDSURFEX%SM%S)
  CALL CANOPY_INIT(YDSURFEX%SM%SSB)
  !
  CALL AGRI_INIT(YDSURFEX%IM%AG)
  CALL CH_ISBA_INIT(YDSURFEX%IM%CHI)
  CALL DATA_ISBA_INIT(YDSURFEX%IM%DTI)
  CALL DIAG_EVAP_ISBA_INIT(YDSURFEX%IM%DGEI)
  CALL DIAG_EVAP_ISBA_INIT(YDSURFEX%IM%DGEIC)
  CALL DIAG_EVAP_ISBA_PATCH_INIT(YDSURFEX%IM%DGEIP,NVEGTYPE)
  CALL DIAG_EVAP_ISBA_PATCH_INIT(YDSURFEX%IM%DGEIPC,NVEGTYPE)  
  CALL DIAG_INIT(YDSURFEX%IM%DGI)
  CALL DIAG_INIT(YDSURFEX%IM%DGIC)
  CALL DIAG_PATCH_INIT(YDSURFEX%IM%DGIP,NVEGTYPE)
  CALL DIAG_PATCH_INIT(YDSURFEX%IM%DGIPC,NVEGTYPE)
  CALL DIAG_MISC_ISBA_INIT(YDSURFEX%IM%DGMI)
  CALL DIAG_MISC_ISBA_PATCH_INIT(YDSURFEX%IM%DGMIP,NVEGTYPE)
  CALL GR_BIOG_INIT(YDSURFEX%IM%GB)
  CALL CANOPY_INIT(YDSURFEX%IM%ICP)
  CALL GRID_INIT(YDSURFEX%IM%IG)
  CALL ISBA_INIT(YDSURFEX%IM%I)
  CALL PACK_CH_ISBA_INIT(YDSURFEX%IM%PKCI)
  CALL PACK_DIAG_ISBA_INIT(YDSURFEX%IM%PKD)
  CALL DIAG_INIT(YDSURFEX%IM%PKD%DGI)
  CALL DIAG_INIT(YDSURFEX%IM%PKD%DGIP)
  CALL DIAG_EVAP_ISBA_INIT(YDSURFEX%IM%PKD%DGEI)
  CALL DIAG_EVAP_ISBA_INIT(YDSURFEX%IM%PKD%DGEIP)
  CALL DIAG_MISC_ISBA_INIT(YDSURFEX%IM%PKD%DGMI) 
  CALL GR_BIOG_INIT(YDSURFEX%IM%PKD%GB)
  CALL PACK_ISBA_INIT(YDSURFEX%IM%PK)
  CALL ISBA_INIT(YDSURFEX%IM%PK%I)
  CALL AGRI_INIT(YDSURFEX%IM%PK%AG)
  CALL GRID_INIT(YDSURFEX%IM%PK%G)
  !
  CALL DATA_ISBA_INIT(YDSURFEX%GDM%DTI)
  CALL DIAG_EVAP_ISBA_INIT(YDSURFEX%GDM%DGEI)
  CALL DIAG_EVAP_ISBA_INIT(YDSURFEX%GDM%DGEIC)
  CALL DIAG_INIT(YDSURFEX%GDM%DGI)
  CALL DIAG_INIT(YDSURFEX%GDM%DGIC)
  CALL DIAG_MISC_ISBA_INIT(YDSURFEX%GDM%DGMI)
  CALL GR_BIOG_INIT(YDSURFEX%GDM%GB)
  CALL TEB_VEG_INIT(YDSURFEX%GDM%TV,NTEB_PATCH_MAX)
  CALL TEB_IRRIG_INIT(YDSURFEX%GDM%TIR)    
  !
  CALL DATA_ISBA_INIT(YDSURFEX%GRM%DTI)
  CALL DIAG_EVAP_ISBA_INIT(YDSURFEX%GRM%DGEI)
  CALL DIAG_EVAP_ISBA_INIT(YDSURFEX%GRM%DGEIC)
  CALL DIAG_INIT(YDSURFEX%GRM%DGI)
  CALL DIAG_INIT(YDSURFEX%GRM%DGIC)
  CALL DIAG_MISC_ISBA_INIT(YDSURFEX%GRM%DGMI)
  CALL GR_BIOG_INIT(YDSURFEX%GRM%GB)
  CALL TEB_VEG_INIT(YDSURFEX%GRM%TV,NTEB_PATCH_MAX)   
  !
  CALL CH_TEB_INIT(YDSURFEX%TM%CHT)
  CALL DATA_TEB_INIT(YDSURFEX%TM%DTT)
  CALL DIAG_MISC_TEB_OPTIONS_INIT(YDSURFEX%TM%DGMTO)
  CALL DIAG_INIT(YDSURFEX%TM%DGT)
  CALL DIAG_UTCI_TEB_INIT(YDSURFEX%TM%DGUT)
  CALL CANOPY_INIT(YDSURFEX%TM%TCP)
  CALL GRID_INIT(YDSURFEX%TM%TG)
  CALL TEB_OPTIONS_INIT(YDSURFEX%TM%TOP)
  CALL TEB_PANEL_INIT(YDSURFEX%TM%TPN)
  CALL DIAG_CUMUL_TEB_INIT(YDSURFEX%TM%DGCT,NTEB_PATCH_MAX)
  CALL DIAG_MISC_TEB_INIT(YDSURFEX%TM%DGMT,NTEB_PATCH_MAX)
  CALL TEB_INIT(YDSURFEX%TM%T,NTEB_PATCH_MAX)  
  !
  CALL BLD_DESC_INIT(YDSURFEX%TM%BDD)
  CALL BEM_OPTIONS_INIT(YDSURFEX%TM%BOP)
  CALL DATA_BEM_INIT(YDSURFEX%TM%DTB)  
  CALL BEM_INIT(YDSURFEX%TM%B,NTEB_PATCH_MAX)  
  !
  CALL DATA_COVER_INIT(YDSURFEX%DTCO)
  CALL DATA_TSZ0_INIT(YDSURFEX%DTZ)
  CALL DUMMY_SURF_FIELDS_INIT(YDSURFEX%DUU)
  !
  CALL SURF_ATM_GRID_INIT(YDSURFEX%UG)
  CALL SURF_ATM_INIT(YDSURFEX%U)
  CALL DIAG_INIT(YDSURFEX%DGU) 
  CALL DIAG_INIT(YDSURFEX%DGUC)
  CALL DIAG_PATCH_INIT(YDSURFEX%DGUP,NTILESFC) 
  CALL DIAG_PATCH_INIT(YDSURFEX%DGUPC,NTILESFC)
  CALL SURF_ATM_SSO_INIT(YDSURFEX%USS)
  CALL CANOPY_INIT(YDSURFEX%SSCP)
  !
  CALL DIAG_INIT(YDSURFEX%DGL)
  CALL DIAG_INIT(YDSURFEX%DGLC)
  CALL IDEAL_INIT(YDSURFEX%L)
  !
  CALL SV_INIT(YDSURFEX%SV)
  CALL CH_SURF_INIT(YDSURFEX%CHU)  
  CALL CH_EMIS_FIELD_INIT(YDSURFEX%CHE)
  CALL CH_EMIS_SNAP_INIT(YDSURFEX%CHN)
  CALL EMIS_GR_FIELD_INIT(YDSURFEX%EGF)  
  CALL DST_INIT(YDSURFEX%DST)
  CALL SLT_INIT(YDSURFEX%SLT)
  !
IF (LHOOK) CALL DR_HOOK("SURFEX_ALLOC",1,ZHOOK_HANDLE)
!
END SUBROUTINE SURFEX_ALLOC
