SUBROUTINE SURFEX_DEALLO(YDSURFEX)
!
USE MODD_SURFEX_n, ONLY : SURFEX_t
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
USE MODI_DEALLOC_SURF_ATM_n
!
IMPLICIT NONE
!
TYPE (SURFEX_t), INTENT(INOUT) :: YDSURFEX
REAL(KIND=JPRB) :: ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK("MODD_OFF_SURFEX_n:SURFEX_DEALLO",0,ZHOOK_HANDLE)
!
CALL DEALLOC_SURF_ATM_n(YDSURFEX)
!
IF (LHOOK) CALL DR_HOOK("MODD_OFF_SURFEX_n:SURFEX_DEALLO",1,ZHOOK_HANDLE)
!
END SUBROUTINE SURFEX_DEALLO
