SUBROUTINE WRITE_TFIELD_1D_PATCH(HSELECT,HPROGRAM,HRECFM,HCOMMENT,KP,KMASK,TFIELD_IN,KSIZE)
!
USE MODD_TYPE_DATE_SURF
!
USE MODD_SURF_PAR, ONLY : XUNDEF, NUNDEF
!
USE MODI_UNPACK_SAME_RANK
USE MODI_WRITE_SURF
!
IMPLICIT NONE
!
 CHARACTER(LEN=*), DIMENSION(:), INTENT(IN) :: HSELECT
 CHARACTER(LEN=*), INTENT(IN) :: HPROGRAM
 CHARACTER(LEN=*), INTENT(IN) :: HRECFM
 CHARACTER(LEN=*), INTENT(IN) :: HCOMMENT
INTEGER, INTENT(IN) :: KP
INTEGER, DIMENSION(:), INTENT(IN) :: KMASK
TYPE(DATE_TIME), DIMENSION(:), INTENT(IN) :: TFIELD_IN
INTEGER, INTENT(IN) :: KSIZE
!
INTEGER, DIMENSION(SIZE(TFIELD_IN)) :: ZINT1
INTEGER, DIMENSION(KSIZE) :: ZINT2
REAL, DIMENSION(SIZE(TFIELD_IN)) :: ZINT1R
REAL, DIMENSION(KSIZE) :: ZINT2R
TYPE(DATE_TIME), DIMENSION(KSIZE) :: TZWORK
!
 CHARACTER(LEN=12) :: YRECFM
 CHARACTER(LEN=2) :: YPAT
INTEGER :: IRESP
!
WRITE(YPAT,'(I2)') KP
YRECFM=ADJUSTL(HRECFM(:LEN_TRIM(HRECFM)))//'P'//ADJUSTL(YPAT(:LEN_TRIM(YPAT)))
 ZINT1 = TFIELD_IN(:)%TDATE%YEAR
 CALL UNPACK_SAME_RANK(KMASK,ZINT1,ZINT2,NUNDEF)
 TZWORK(:)%TDATE%YEAR = ZINT2
 ZINT1 = TFIELD_IN(:)%TDATE%MONTH 
 CALL UNPACK_SAME_RANK(KMASK,ZINT1,ZINT2,NUNDEF)
 TZWORK(:)%TDATE%MONTH = ZINT2 
 ZINT1 = TFIELD_IN(:)%TDATE%DAY
 CALL UNPACK_SAME_RANK(KMASK,ZINT1,ZINT2,NUNDEF)
 TZWORK(:)%TDATE%DAY = ZINT2 
 ZINT1R = TFIELD_IN(:)%TIME
 CALL UNPACK_SAME_RANK(KMASK,ZINT1R,ZINT2R,XUNDEF)
 TZWORK(:)%TIME = ZINT2R
 CALL WRITE_SURF(HSELECT,HPROGRAM,YRECFM,TZWORK,IRESP,HCOMMENT=HCOMMENT)
!
END SUBROUTINE WRITE_TFIELD_1D_PATCH
