!     #########
      SUBROUTINE WRITE_DIAG_SEB_ISBA_n ( DTCO, DUO, U, CHI, DGI, DST, GB, &
                                         IO, IR, IP, IMX, HPROGRAM)
!     #################################
!
!!****  *WRITE_DIAG_SEB_ISBA* - writes the ISBA diagnostic fields
!!
!!    PURPOSE
!!    -------
!!
!!
!!**  METHOD
!!    ------
!!
!!    REFERENCE
!!    ---------
!!
!!
!!    AUTHOR
!!    ------
!!      V. Masson   *Meteo France*
!!
!!    MODIFICATIONS
!!    -------------
!!      Original    01/2004
!!      B. Decharme 06/2009  key to write (or not) patch result
!!      B. Decharme 08/2009  cumulative radiative budget
!!      B. Decharme  09/2012 : Bug in local variables declaration in PROVAR_TO_DIAG
!!      B. Decharme 09/2012  New diag :
!!                           carbon fluxes and reservoirs
!!                           soil liquid and ice water content in kg/m2 and m3/m3
!!      B. Decharme  06/13   Add diags (sublimation, lateral drainage)
!!                           All snow outputs noted SN
!!                           delete NWG_SIZE
!!      S. Belamari 06/2014 : Introduce GRESET to avoid errors due to NBLOCK=0
!!                            when coupled with ARPEGE/ALADIN/AROME
!!      P. Samuelsson 10/2014 MEB
!-------------------------------------------------------------------------------
!
!*       0.    DECLARATIONS
!              ------------
!
!
USE MODD_DATA_COVER_n, ONLY : DATA_COVER_t
USE MODD_DIAG_n, ONLY : DIAG_OPTIONS_t
USE MODD_SURF_ATM_n, ONLY : SURF_ATM_t
USE MODD_CH_ISBA_n, ONLY : CH_ISBA_t
USE MODD_SURFEX_n, ONLY : ISBA_DIAG_t
USE MODD_DST_n, ONLY : DST_t
USE MODD_GR_BIOG_n, ONLY : GR_BIOG_t
USE MODD_ISBA_OPTIONS_n, ONLY : ISBA_OPTIONS_t
USE MODD_ISBA_n, ONLY : ISBA_PROG_t
USE MODD_ISBA_PARAM_n, ONLY : ISBA_PARAM_FIX_t
USE MODD_ISBA_INIT_n, ONLY : ISBA_INIT_PGD_t
!
#ifdef SFX_ARO
USE MODD_IO_SURF_ARO,   ONLY : LCOUNTW
#endif
!
USE MODD_SURF_PAR,   ONLY : XUNDEF, NUNDEF
!
USE MODD_CSTS,       ONLY : XRHOLW, XTT, XLMTT
!
!
!
USE MODD_AGRI  ,     ONLY : LAGRIP
!
!
USE MODI_INIT_IO_SURF_n
USE MODI_WRITE_SURF
USE MODI_END_IO_SURF_n
!
USE MODD_DST_SURF
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE
!
!*       0.1   Declarations of arguments
!              -------------------------
!
!
TYPE(DATA_COVER_t), INTENT(INOUT) :: DTCO
TYPE(DIAG_OPTIONS_t), INTENT(INOUT) :: DUO
TYPE(SURF_ATM_t), INTENT(INOUT) :: U
TYPE(CH_ISBA_t), INTENT(INOUT) :: CHI
TYPE(ISBA_DIAG_t), INTENT(INOUT) :: DGI
TYPE(DST_t), INTENT(INOUT) :: DST
TYPE(GR_BIOG_t), INTENT(INOUT) :: GB
TYPE(ISBA_OPTIONS_t), INTENT(INOUT) :: IO
TYPE(ISBA_PROG_t), INTENT(INOUT) :: IR
TYPE(ISBA_INIT_PGD_t), INTENT(INOUT) :: IP
TYPE(ISBA_PARAM_FIX_t), INTENT(INOUT) :: IMX
!
 CHARACTER(LEN=6),  INTENT(IN)  :: HPROGRAM ! program calling
!
!*       0.2   Declarations of local variables
!              -------------------------------
!
REAL, DIMENSION(:,:), ALLOCATABLE :: ZWORK
INTEGER           :: IRESP          ! IRESP  : return-code if a problem appears
CHARACTER(LEN=12) :: YRECFM         ! Name of the article to be write
CHARACTER(LEN=100):: YCOMMENT       ! Comment string
CHARACTER(LEN=2)  :: YNUM
!
LOGICAL           :: GRESET
INTEGER           :: JSV, JSW, JPATCH
INTEGER           :: ISIZE_LMEB_PATCH   ! Number of patches where multi-energy balance should be applied
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
!-------------------------------------------------------------------------------
!
!         Initialisation for IO
!
IF (LHOOK) CALL DR_HOOK('WRITE_DIAG_SEB_ISBA_N',0,ZHOOK_HANDLE)
!
ISIZE_LMEB_PATCH=COUNT(IO%LMEB_PATCH(:))
!
GRESET=.TRUE.
#ifdef SFX_ARO
GRESET=(.NOT.LCOUNTW)
#endif

!
CALL INIT_IO_SURF_n(DTCO, U, HPROGRAM,'NATURE','ISBA  ','WRITE')
!
!-------------------------------------------------------------------------------
!
!*       2.     Richardson number :
!               -----------------
!
IF (DGI%O%N2M>=1) THEN
  !
  YRECFM='RI_ISBA'
  YCOMMENT='Richardson number over tile nature'
  CALL WRITE_SURF(DUO%CSELECT,HPROGRAM,YRECFM,DGI%D%XRI(:),IRESP,HCOMMENT=YCOMMENT)
  !
END IF
!
!*       3.     Energy fluxes :
!               -------------
!
IF (DGI%O%LSURF_BUDGET) THEN
  !
  !
  YRECFM='TALB_ISBA'
  YCOMMENT='total albedo over tile nature (-)'
  CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,DGI%D%XALBT(:),IRESP,HCOMMENT=YCOMMENT)
  !  
  YRECFM='RN_ISBA'
  YCOMMENT='Net radiation over tile nature'//' (W/m2)'
  CALL WRITE_SURF(DUO%CSELECT,HPROGRAM,YRECFM,DGI%D%XRN(:),IRESP,HCOMMENT=YCOMMENT)
  !
  YRECFM='H_ISBA'
  YCOMMENT='Sensible heat flux over tile nature'//' (W/m2)'
  CALL WRITE_SURF(DUO%CSELECT,HPROGRAM,YRECFM,DGI%D%XH(:),IRESP,HCOMMENT=YCOMMENT)
  !
  YRECFM='LE_ISBA'
  YCOMMENT='total latent heat flux over tile nature'//' (W/m2)'
  CALL WRITE_SURF(DUO%CSELECT,HPROGRAM,YRECFM,DGI%D%XLE(:),IRESP,HCOMMENT=YCOMMENT)
  !
  YRECFM='LEI_ISBA'
  YCOMMENT='sublimation latent heat flux over tile nature'//' (W/m2)'
  CALL WRITE_SURF(DUO%CSELECT,HPROGRAM,YRECFM,DGI%D%XLEI(:),IRESP,HCOMMENT=YCOMMENT)
  !
  YRECFM='GFLUX_ISBA'
  YCOMMENT='Ground flux over tile nature'//' (W/m2)'
  CALL WRITE_SURF(DUO%CSELECT,HPROGRAM,YRECFM,DGI%D%XGFLUX(:),IRESP,HCOMMENT=YCOMMENT)
  !
  YRECFM='EVAP_ISBA'
  YCOMMENT='total evaporative flux for tile nature'//' (Kg/m2/s)'
  CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,DGI%D%XEVAP(:),IRESP,HCOMMENT=YCOMMENT)
  !
  YRECFM='SUBL_ISBA'
  YCOMMENT='sublimation flux for tile nature'//' (Kg/m2/s)'
  CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,DGI%D%XSUBL(:),IRESP,HCOMMENT=YCOMMENT)
  ! 
  IF (DGI%O%LRAD_BUDGET  .OR. (DGI%O%LSURF_BUDGETC .AND. .NOT.DUO%LRESET_BUDGETC)) THEN
    !
    YRECFM='SWD_ISBA'
    YCOMMENT='short wave downward radiation over tile nature'//' (W/m2)'
    CALL WRITE_SURF(DUO%CSELECT,HPROGRAM,YRECFM,DGI%D%XSWD(:),IRESP,HCOMMENT=YCOMMENT)
    !
    YRECFM='SWU_ISBA'
    YCOMMENT='short wave upward radiation over tile nature'//' (W/m2)'
    CALL WRITE_SURF(DUO%CSELECT,HPROGRAM,YRECFM,DGI%D%XSWU(:),IRESP,HCOMMENT=YCOMMENT)
    !
    YRECFM='LWD_ISBA'
    YCOMMENT='long wave downward radiation over tile nature'//' (W/m2)'
    CALL WRITE_SURF(DUO%CSELECT,HPROGRAM,YRECFM,DGI%D%XLWD(:),IRESP,HCOMMENT=YCOMMENT)
    !
    YRECFM='LWU_ISBA'
    YCOMMENT='long wave upward radiation over tile nature'//' (W/m2)'
    CALL WRITE_SURF(DUO%CSELECT,HPROGRAM,YRECFM,DGI%D%XLWU(:),IRESP,HCOMMENT=YCOMMENT)
    !
    DO JSW=1, SIZE(DGI%D%XSWBD,2)
      YNUM=ACHAR(48+JSW)
      !
      YRECFM='SWD_ISBA_'//YNUM
      YCOMMENT='short wave downward radiation over tile nature for spectral band'//YNUM//' (W/m2)'
      CALL WRITE_SURF(DUO%CSELECT,HPROGRAM,YRECFM,DGI%D%XSWBD(:,JSW),IRESP,HCOMMENT=YCOMMENT)
      !
      YRECFM='SWU_ISBA_'//YNUM
      YCOMMENT='short wave upward radiation over tile nature for spectral band'//YNUM//' (W/m2)'
      CALL WRITE_SURF(DUO%CSELECT,HPROGRAM,YRECFM,DGI%D%XSWBU(:,JSW),IRESP,HCOMMENT=YCOMMENT)
      !
    ENDDO
    !
  ENDIF
  !
  YRECFM='FMU_ISBA'
  YCOMMENT='u component of wind stress'//' (Pa)'  
  CALL WRITE_SURF(DUO%CSELECT,HPROGRAM,YRECFM,DGI%D%XFMU(:),IRESP,HCOMMENT=YCOMMENT)
  !
  YRECFM='FMV_ISBA'
  YCOMMENT='v component of wind stress'//' (Pa)'  
  CALL WRITE_SURF(DUO%CSELECT,HPROGRAM,YRECFM,DGI%D%XFMV(:),IRESP,HCOMMENT=YCOMMENT)
  !
END IF
!
!*       4.    Specific Energy fluxes :(for each patch)
!              ----------------------------------------
!
IF (DGI%DE%LSURF_EVAP_BUDGET) CALL WRITE_EVAP_BUD(DGI%DE,"_ISBA ",.FALSE.)
!
!*       5.    Cumulated Energy fluxes
!              -----------------------
!
IF (DGI%O%LSURF_BUDGETC) THEN
  !
  CALL WRITE_EVAP_BUD(DGI%DEC,"C_ISBA",(DGI%O%LSURF_BUDGETC .AND. .NOT.DUO%LRESET_BUDGETC))
  !
  IF(IO%LGLACIER)THEN
    YRECFM='ICE_FC_ISBA'
    YCOMMENT='X_Y_'//YRECFM//' (Kg/m2)'
    CALL WRITE_SURF(DUO%CSELECT,HPROGRAM,YRECFM,DGI%DEC%XICEFLUX(:),IRESP,HCOMMENT=YCOMMENT)
  ENDIF
  !  
  YRECFM='RNC_ISBA'
  YCOMMENT='X_Y_'//YRECFM//' (J/m2)'
  CALL WRITE_SURF(DUO%CSELECT,HPROGRAM,YRECFM,DGI%DC%XRN(:),IRESP,HCOMMENT=YCOMMENT)
  !
  YRECFM='HC_ISBA'
  YCOMMENT='X_Y_'//YRECFM//' (J/m2)'
  CALL WRITE_SURF(DUO%CSELECT,HPROGRAM,YRECFM,DGI%DC%XH(:),IRESP,HCOMMENT=YCOMMENT)
  !
  YRECFM='LEC_ISBA'
  YCOMMENT='X_Y_'//YRECFM//' (J/m2)'
  CALL WRITE_SURF(DUO%CSELECT,HPROGRAM,YRECFM,DGI%DC%XLE(:),IRESP,HCOMMENT=YCOMMENT)
  !
  YRECFM='LEIC_ISBA'
  YCOMMENT='X_Y_'//YRECFM//' (J/m2)'
  CALL WRITE_SURF(DUO%CSELECT,HPROGRAM,YRECFM,DGI%DC%XLEI(:),IRESP,HCOMMENT=YCOMMENT)
  !
  YRECFM='GFLUXC_ISBA'
  YCOMMENT='X_Y_'//YRECFM//' (J/m2)'
  CALL WRITE_SURF(DUO%CSELECT,HPROGRAM,YRECFM,DGI%DC%XGFLUX(:),IRESP,HCOMMENT=YCOMMENT)
  !
  YRECFM='EVAPC_ISBA'
  YCOMMENT='total evaporative flux for tile nature'//' (Kg/m2/s)'
  CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,DGI%DC%XEVAP(:),IRESP,HCOMMENT=YCOMMENT)
  !
  YRECFM='SUBLC_ISBA'
  YCOMMENT='sublimation flux for tile nature'//' (Kg/m2/s)'
  CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,DGI%DC%XSUBL(:),IRESP,HCOMMENT=YCOMMENT)
  !  
  IF (DGI%O%LRAD_BUDGET .OR. (DGI%O%LSURF_BUDGETC .AND. .NOT.DUO%LRESET_BUDGETC)) THEN
    !
    YRECFM='SWDC_ISBA'
    YCOMMENT='X_Y_'//YRECFM//' (J/m2)'
    CALL WRITE_SURF(DUO%CSELECT,HPROGRAM,YRECFM,DGI%DC%XSWD(:),IRESP,HCOMMENT=YCOMMENT)
    !
    YRECFM='SWUC_ISBA'
    YCOMMENT='X_Y_'//YRECFM//' (J/m2)'
    CALL WRITE_SURF(DUO%CSELECT,HPROGRAM,YRECFM,DGI%DC%XSWU(:),IRESP,HCOMMENT=YCOMMENT)
    !
    YRECFM='LWDC_ISBA'
    YCOMMENT='X_Y_'//YRECFM//' (J/m2)'
    CALL WRITE_SURF(DUO%CSELECT,HPROGRAM,YRECFM,DGI%DC%XLWD(:),IRESP,HCOMMENT=YCOMMENT)
    !
    YRECFM='LWUC_ISBA'
    YCOMMENT='X_Y_'//YRECFM//' (J/m2)'
    CALL WRITE_SURF(DUO%CSELECT,HPROGRAM,YRECFM,DGI%DC%XLWU(:),IRESP,HCOMMENT=YCOMMENT)
    !
  ENDIF
  !
  YRECFM='FMUC_ISBA'
  YCOMMENT='X_Y_'//YRECFM//' (Pa.s)'  
  CALL WRITE_SURF(DUO%CSELECT,HPROGRAM,YRECFM,DGI%DC%XFMU(:),IRESP,HCOMMENT=YCOMMENT)
  !
  YRECFM='FMVC_ISBA'
  YCOMMENT='X_Y_'//YRECFM//' (Pa.s)'  
  CALL WRITE_SURF(DUO%CSELECT,HPROGRAM,YRECFM,DGI%DC%XFMV(:),IRESP,HCOMMENT=YCOMMENT)
  !
  !  
ENDIF
!
!*       6.     parameters at 2 and 10 meters :
!               -------------------------------
!
IF (DGI%O%N2M>=1) THEN
  !
  YRECFM='T2M_ISBA'
  YCOMMENT='X_Y_'//YRECFM//' (K)'
  CALL WRITE_SURF(DUO%CSELECT,HPROGRAM,YRECFM,DGI%D%XT2M(:),IRESP,HCOMMENT=YCOMMENT)
  !
  YRECFM='T2MMIN_ISBA'
  YCOMMENT='X_Y_'//YRECFM//' (K)'
  CALL WRITE_SURF(DUO%CSELECT,HPROGRAM,YRECFM,DGI%D%XT2M_MIN(:),IRESP,HCOMMENT=YCOMMENT)
  IF(GRESET)DGI%D%XT2M_MIN(:)=XUNDEF
  !
  YRECFM='T2MMAX_ISBA'
  YCOMMENT='X_Y_'//YRECFM//' (K)'
  CALL WRITE_SURF(DUO%CSELECT,HPROGRAM,YRECFM,DGI%D%XT2M_MAX(:),IRESP,HCOMMENT=YCOMMENT)
  IF(GRESET)DGI%D%XT2M_MAX(:)=-XUNDEF
  !
  YRECFM='Q2M_ISBA'
  YCOMMENT='X_Y_'//YRECFM//' (KG/KG)'
  CALL WRITE_SURF(DUO%CSELECT,HPROGRAM,YRECFM,DGI%D%XQ2M(:),IRESP,HCOMMENT=YCOMMENT)
  !
  YRECFM='HU2M_ISBA'
  YCOMMENT='X_Y_'//YRECFM//' (-)'
  CALL WRITE_SURF(DUO%CSELECT,HPROGRAM,YRECFM,DGI%D%XHU2M(:),IRESP,HCOMMENT=YCOMMENT)
  !
  YRECFM='HU2MMIN_ISBA'
  YCOMMENT='X_Y_'//YRECFM//' (-)'
  CALL WRITE_SURF(DUO%CSELECT,HPROGRAM,YRECFM,DGI%D%XHU2M_MIN(:),IRESP,HCOMMENT=YCOMMENT)
  IF(GRESET)DGI%D%XHU2M_MIN(:)=XUNDEF
  !
  YRECFM='HU2MMAX_ISBA'
  YCOMMENT='X_Y_'//YRECFM//' (-)'
  CALL WRITE_SURF(DUO%CSELECT,HPROGRAM,YRECFM,DGI%D%XHU2M_MAX(:),IRESP,HCOMMENT=YCOMMENT)
  IF(GRESET)DGI%D%XHU2M_MAX(:)=-XUNDEF
  !
  YRECFM='ZON10M_ISBA'
  YCOMMENT='X_Y_'//YRECFM//' (M/S)'
  CALL WRITE_SURF(DUO%CSELECT,HPROGRAM,YRECFM,DGI%D%XZON10M(:),IRESP,HCOMMENT=YCOMMENT)
  !
  YRECFM='MER10M_ISBA'
  YCOMMENT='X_Y_'//YRECFM//' (M/S)'
  CALL WRITE_SURF(DUO%CSELECT,HPROGRAM,YRECFM,DGI%D%XMER10M(:),IRESP,HCOMMENT=YCOMMENT)
  !
  YRECFM='W10M_ISBA'
  YCOMMENT='X_Y_'//YRECFM//' (M/S)'
  CALL WRITE_SURF(DUO%CSELECT,HPROGRAM,YRECFM,DGI%D%XWIND10M(:),IRESP,HCOMMENT=YCOMMENT)
  !
  YRECFM='W10MMAX_ISBA'
  YCOMMENT='X_Y_'//YRECFM//' (M/S)'
  CALL WRITE_SURF(DUO%CSELECT,HPROGRAM,YRECFM,DGI%D%XWIND10M_MAX(:),IRESP,HCOMMENT=YCOMMENT)
  IF(GRESET)DGI%D%XWIND10M_MAX(:)=0.0
  !
  YRECFM='SFCO2_ISBA'
  YCOMMENT='X_Y_'//YRECFM//' (M.kgCO2.S-1.kgAIR-1)'
  CALL WRITE_SURF(DUO%CSELECT,HPROGRAM,YRECFM,DGI%D%XSFCO2(:),IRESP,HCOMMENT=YCOMMENT)
  !  
END IF
!----------------------------------------------------------------------------
!
!*       7.     Transfer coefficients
!               ---------------------
!
IF (DGI%O%LCOEF) THEN
  !
  YRECFM='CD_ISBA'
  YCOMMENT='X_Y_'//YRECFM
  CALL WRITE_SURF(DUO%CSELECT,HPROGRAM,YRECFM,DGI%D%XCD(:),IRESP,HCOMMENT=YCOMMENT)
  !
  YRECFM='CH_ISBA'
  YCOMMENT='X_Y_'//YRECFM
  CALL WRITE_SURF(DUO%CSELECT,HPROGRAM,YRECFM,DGI%D%XCH(:),IRESP,HCOMMENT=YCOMMENT)
  !
  YRECFM='CE_ISBA'
  YCOMMENT='X_Y_'//YRECFM
  CALL WRITE_SURF(DUO%CSELECT,HPROGRAM,YRECFM,DGI%D%XCE(:),IRESP,HCOMMENT=YCOMMENT)
  !
  YRECFM='Z0_ISBA'
  YCOMMENT='X_Y_'//YRECFM//' (M)'
  CALL WRITE_SURF(DUO%CSELECT,HPROGRAM,YRECFM,DGI%D%XZ0(:),IRESP,HCOMMENT=YCOMMENT)
  !
  YRECFM='Z0H_ISBA'
  YCOMMENT='X_Y_'//YRECFM//' (M)'
  CALL WRITE_SURF(DUO%CSELECT,HPROGRAM,YRECFM,DGI%D%XZ0H(:),IRESP,HCOMMENT=YCOMMENT)
  !
ENDIF
!
!----------------------------------------------------------------------------
!
!*       8.     Surface humidity
!               ----------------
IF (DGI%O%LSURF_VARS) THEN
  !
  YRECFM='QS_ISBA'
  YCOMMENT='X_Y_'//YRECFM//' (KG/KG)'
  CALL WRITE_SURF(DUO%CSELECT,HPROGRAM,YRECFM,DGI%D%XQS(:),IRESP,HCOMMENT=YCOMMENT)
  !
ENDIF
!
!----------------------------------------------------------------------------
!
!*       9.     Diag of prognostic fields
!               -------------------------
!
IF (DUO%LPROVAR_TO_DIAG) CALL PROVAR_TO_DIAG
!
!----------------------------------------------------------------------------
!
!User want (or not) patch output
IF(DGI%O%LPATCH_BUDGET.AND.(IO%NPATCH >1))THEN
    !----------------------------------------------------------------------------
    !
    !*      10.     Richardson number (for each patch)
    !               -----------------
    !
    IF (DGI%O%N2M>=1) THEN
      !
      ALLOCATE(ZWORK(SIZE(DGI%DP%AL(1)%XRI(:)),IO%NPATCH))
      DO JPATCH=1,IO%NPATCH
        ZWORK(:,JPATCH) = DGI%DP%AL(JPATCH)%XRI(:)
      ENDDO
      YRECFM='RI_P'
      YCOMMENT='X_Y_'//YRECFM
      CALL WRITE_SURF(DUO%CSELECT,HPROGRAM,YRECFM,ZWORK(:,:),IRESP,HCOMMENT=YCOMMENT)
      DEALLOCATE(ZWORK)
      !
    END IF
    !
    !*       11.     Energy fluxes :(for each patch)
    !                -------------
    !
    IF (DGI%O%LSURF_BUDGET) THEN
      !
      ALLOCATE(ZWORK(SIZE(DGI%DP%AL(1)%XRN(:)),IO%NPATCH))
      !
      YRECFM='TALB'
      YCOMMENT='total albedo per patch'
      !
      DO JPATCH=1,IO%NPATCH
        ZWORK(:,JPATCH) = DGI%DP%AL(JPATCH)%XALBT(:)
      ENDDO
      CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,ZWORK,IRESP,HCOMMENT=YCOMMENT)
      
      DO JPATCH=1,IO%NPATCH
        ZWORK(:,JPATCH) = DGI%DP%AL(JPATCH)%XRN(:)
      ENDDO      
      YRECFM='RN_P'
      YCOMMENT='X_Y_'//YRECFM//' (W/m2)'
      CALL WRITE_SURF(DUO%CSELECT,HPROGRAM,YRECFM,ZWORK(:,:),IRESP,HCOMMENT=YCOMMENT)
      !
      DO JPATCH=1,IO%NPATCH
        ZWORK(:,JPATCH) = DGI%DP%AL(JPATCH)%XH(:)
      ENDDO      
      YRECFM='H_P'
      YCOMMENT='X_Y_'//YRECFM//' (W/m2)'
      CALL WRITE_SURF(DUO%CSELECT,HPROGRAM,YRECFM,ZWORK(:,:),IRESP,HCOMMENT=YCOMMENT)
      !
 
      YRECFM='LE_P'
      YCOMMENT='X_Y_'//YRECFM//' (W/m2)'
      CALL WRITE_SURF(DUO%CSELECT,HPROGRAM,YRECFM,IR%XLE(:,:),IRESP,HCOMMENT=YCOMMENT)
      !
      DO JPATCH=1,IO%NPATCH
        ZWORK(:,JPATCH) = DGI%DP%AL(JPATCH)%XLEI(:)
      ENDDO      
      YRECFM='LEI_P'
      YCOMMENT='X_Y_'//YRECFM//' (W/m2)'
      CALL WRITE_SURF(DUO%CSELECT,HPROGRAM,YRECFM,ZWORK(:,:),IRESP,HCOMMENT=YCOMMENT)
      !
      DO JPATCH=1,IO%NPATCH
        ZWORK(:,JPATCH) = DGI%DP%AL(JPATCH)%XGFLUX(:)
      ENDDO      
      YRECFM='GFLUX_P'
      YCOMMENT='X_Y_'//YRECFM//' (W/m2)'
      CALL WRITE_SURF(DUO%CSELECT,HPROGRAM,YRECFM,ZWORK(:,:),IRESP,HCOMMENT=YCOMMENT)
      !
      DO JPATCH=1,IO%NPATCH
        ZWORK(:,JPATCH) = DGI%DP%AL(JPATCH)%XEVAP(:)
      ENDDO           
      YRECFM='EVAP_P'
      YCOMMENT='X_Y_'//YRECFM//' (W/m2)'
      CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,ZWORK(:,:),IRESP,HCOMMENT=YCOMMENT)
      !
      DO JPATCH=1,IO%NPATCH
        ZWORK(:,JPATCH) = DGI%DP%AL(JPATCH)%XSUBL(:)
      ENDDO           
      YRECFM='SUBL_P'
      YCOMMENT='X_Y_'//YRECFM//' (W/m2)'
      CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,ZWORK(:,:),IRESP,HCOMMENT=YCOMMENT) 
      !     
      IF (DGI%O%LRAD_BUDGET .OR. (DGI%O%LSURF_BUDGETC .AND. .NOT.DUO%LRESET_BUDGETC)) THEN
        !
        DO JPATCH=1,IO%NPATCH
          ZWORK(:,JPATCH) = DGI%DP%AL(JPATCH)%XSWD(:)
        ENDDO          
        YRECFM='SWD_P'
        YCOMMENT='X_Y_'//YRECFM//' (W/m2)'
        CALL WRITE_SURF(DUO%CSELECT,HPROGRAM,YRECFM,ZWORK(:,:),IRESP,HCOMMENT=YCOMMENT)
        !
        DO JPATCH=1,IO%NPATCH
          ZWORK(:,JPATCH) = DGI%DP%AL(JPATCH)%XSWU(:)
        ENDDO         
        YRECFM='SWU_P'
        YCOMMENT='X_Y_'//YRECFM//' (W/m2)'
        CALL WRITE_SURF(DUO%CSELECT,HPROGRAM,YRECFM,ZWORK(:,:),IRESP,HCOMMENT=YCOMMENT)
        !
        DO JPATCH=1,IO%NPATCH
          ZWORK(:,JPATCH) = DGI%DP%AL(JPATCH)%XLWD(:)
        ENDDO         
        YRECFM='LWD_P'
        YCOMMENT='X_Y_'//YRECFM//' (W/m2)'
        CALL WRITE_SURF(DUO%CSELECT,HPROGRAM,YRECFM,ZWORK(:,:),IRESP,HCOMMENT=YCOMMENT)
        !
        DO JPATCH=1,IO%NPATCH
          ZWORK(:,JPATCH) = DGI%DP%AL(JPATCH)%XLWU(:)
        ENDDO         
        YRECFM='LWU_P'
        YCOMMENT='X_Y_'//YRECFM//' (W/m2)'
        CALL WRITE_SURF(DUO%CSELECT,HPROGRAM,YRECFM,ZWORK(:,:),IRESP,HCOMMENT=YCOMMENT)
        !
        DO JSW=1, SIZE(DGI%D%XSWBD,2)
          YNUM=ACHAR(48+JSW)
          !
          DO JPATCH=1,IO%NPATCH
            ZWORK(:,JPATCH) = DGI%DP%AL(JPATCH)%XSWBD(:,JSW)
          ENDDO           
          YRECFM='SWD_P'//YNUM
          YCOMMENT='X_Y_'//YRECFM//' (W/m2)'
          CALL WRITE_SURF(DUO%CSELECT,HPROGRAM,YRECFM,ZWORK(:,:),IRESP,HCOMMENT=YCOMMENT)
          !
          DO JPATCH=1,IO%NPATCH
            ZWORK(:,JPATCH) = DGI%DP%AL(JPATCH)%XSWBD(:,JSW)
          ENDDO           
          YRECFM='SWU_P'//YNUM
          YCOMMENT='X_Y_'//YRECFM//' (W/m2)'
          CALL WRITE_SURF(DUO%CSELECT,HPROGRAM,YRECFM,ZWORK(:,:),IRESP,HCOMMENT=YCOMMENT)
          !
        ENDDO
        !
      ENDIF
      !
      DO JPATCH=1,IO%NPATCH
        ZWORK(:,JPATCH) = DGI%DP%AL(JPATCH)%XFMU(:)
      ENDDO       
      YRECFM='FMU_P'
      YCOMMENT='X_Y_'//YRECFM//' (Pa)'     
      CALL WRITE_SURF(DUO%CSELECT,HPROGRAM,YRECFM,ZWORK(:,:),IRESP,HCOMMENT=YCOMMENT)
      !
      DO JPATCH=1,IO%NPATCH
        ZWORK(:,JPATCH) = DGI%DP%AL(JPATCH)%XFMV(:)
      ENDDO       
      YRECFM='FMV_P'
      YCOMMENT='X_Y_'//YRECFM//' (Pa)'      
      CALL WRITE_SURF(DUO%CSELECT,HPROGRAM,YRECFM,ZWORK(:,:),IRESP,HCOMMENT=YCOMMENT)
      !
      DEALLOCATE(ZWORK)
      !
    END IF
    !
    !*       12.    Specific Energy fluxes :(for each patch)
    !               ----------------------------------------
    !
    IF (DGI%DE%LSURF_EVAP_BUDGET) CALL WRITE_EVAP_BUD_PATCH(DGI%DEP,'_P ',.FALSE.)
    !
    !*       13.    surface temperature parameters at 2 and 10 meters (for each patch):
    !               -------------------------------------------------------------------
    !
    IF (DGI%O%N2M>=1) THEN
      !
      ALLOCATE(ZWORK(SIZE(DGI%DP%AL(1)%XT2M(:)),IO%NPATCH))
      !
      DO JPATCH=1,IO%NPATCH
        ZWORK(:,JPATCH) = DGI%DP%AL(JPATCH)%XT2M(:)
      ENDDO   
      YRECFM='T2M_P'
      YCOMMENT='X_Y_'//YRECFM//' (K)'
      CALL WRITE_SURF(DUO%CSELECT,HPROGRAM,YRECFM,ZWORK(:,:),IRESP,HCOMMENT=YCOMMENT)
      !
      DO JPATCH=1,IO%NPATCH
        ZWORK(:,JPATCH) = DGI%DP%AL(JPATCH)%XT2M_MIN(:)
      ENDDO      
      YRECFM='T2MMIN_P'
      YCOMMENT='X_Y_'//YRECFM//' (K)'
      CALL WRITE_SURF(DUO%CSELECT,HPROGRAM,YRECFM,ZWORK(:,:),IRESP,HCOMMENT=YCOMMENT)
      !
      DO JPATCH=1,IO%NPATCH
        DGI%DP%AL(JPATCH)%XT2M_MIN(:)=XUNDEF
        ZWORK(:,JPATCH) = DGI%DP%AL(JPATCH)%XT2M_MAX(:)
      ENDDO      
      YRECFM='T2MMAX_P'
      YCOMMENT='X_Y_'//YRECFM//' (K)'
      CALL WRITE_SURF(DUO%CSELECT,HPROGRAM,YRECFM,ZWORK(:,:),IRESP,HCOMMENT=YCOMMENT)
      !
      DO JPATCH=1,IO%NPATCH
        DGI%DP%AL(JPATCH)%XT2M_MAX(:)=0.0
        ZWORK(:,JPATCH) = DGI%DP%AL(JPATCH)%XQ2M(:)
      ENDDO      
      YRECFM='Q2M_P'
      YCOMMENT='X_Y_'//YRECFM//' (KG/KG)'
      CALL WRITE_SURF(DUO%CSELECT,HPROGRAM,YRECFM,ZWORK(:,:),IRESP,HCOMMENT=YCOMMENT)
      !
      DO JPATCH=1,IO%NPATCH
        ZWORK(:,JPATCH) = DGI%DP%AL(JPATCH)%XHU2M(:)
      ENDDO      
      YRECFM='HU2M_P'
      YCOMMENT='X_Y_'//YRECFM//' (PERCENT)'
      CALL WRITE_SURF(DUO%CSELECT,HPROGRAM,YRECFM,ZWORK(:,:),IRESP,HCOMMENT=YCOMMENT)
      !
      DO JPATCH=1,IO%NPATCH
        ZWORK(:,JPATCH) = DGI%DP%AL(JPATCH)%XZON10M(:)
      ENDDO       
      YRECFM='ZON10M_P'
      YCOMMENT='X_Y_'//YRECFM//' (M/S)'
      CALL WRITE_SURF(DUO%CSELECT,HPROGRAM,YRECFM,ZWORK(:,:),IRESP,HCOMMENT=YCOMMENT)
      !
      DO JPATCH=1,IO%NPATCH
        ZWORK(:,JPATCH) = DGI%DP%AL(JPATCH)%XMER10M(:)
      ENDDO      
      YRECFM='MER10M_P'
      YCOMMENT='X_Y_'//YRECFM//' (M/S)'
      CALL WRITE_SURF(DUO%CSELECT,HPROGRAM,YRECFM,ZWORK(:,:),IRESP,HCOMMENT=YCOMMENT)
      !
      DO JPATCH=1,IO%NPATCH
        ZWORK(:,JPATCH) = DGI%DP%AL(JPATCH)%XWIND10M(:)
      ENDDO      
      YRECFM='W10M_P'
      YCOMMENT='X_Y_'//YRECFM//' (M/S)'
      CALL WRITE_SURF(DUO%CSELECT,HPROGRAM,YRECFM,ZWORK(:,:),IRESP,HCOMMENT=YCOMMENT)
      !
      DEALLOCATE(ZWORK)
      !
    END IF
    !
    !*       14.    Cumulated Energy fluxes :(for each patch)
    !               -----------------------------------------
    !
    IF (DGI%O%LSURF_BUDGETC) THEN
      !
      CALL WRITE_EVAP_BUD_PATCH(DGI%DEPC,'C_P',(DGI%O%LSURF_BUDGETC .AND. .NOT.DUO%LRESET_BUDGETC))
      !  
      ALLOCATE(ZWORK(SIZE(DGI%DPC%AL(1)%XRN(:)),IO%NPATCH))
      !
      IF(IO%LGLACIER)THEN
        DO JPATCH=1,IO%NPATCH
          ZWORK(:,JPATCH) = DGI%DEPC%AL(JPATCH)%XICEFLUX(:)
        ENDDO                  
        YRECFM='ICE_FC_P'
        YCOMMENT='X_Y_'//YRECFM//' (Kg/m2)'
        CALL WRITE_SURF(DUO%CSELECT,HPROGRAM,YRECFM,ZWORK(:,:),IRESP,HCOMMENT=YCOMMENT)
      ENDIF
      !      
      DO JPATCH=1,IO%NPATCH
        ZWORK(:,JPATCH) = DGI%DPC%AL(JPATCH)%XRN(:)
      ENDDO      
      YRECFM='RNC_P'
      YCOMMENT='X_Y_'//YRECFM//' (J/m2)'
      CALL WRITE_SURF(DUO%CSELECT,HPROGRAM,YRECFM,ZWORK(:,:),IRESP,HCOMMENT=YCOMMENT)
      !
      DO JPATCH=1,IO%NPATCH
        ZWORK(:,JPATCH) = DGI%DPC%AL(JPATCH)%XH(:)
      ENDDO       
      YRECFM='HC_P'
      YCOMMENT='X_Y_'//YRECFM//' (J/m2)'
      CALL WRITE_SURF(DUO%CSELECT,HPROGRAM,YRECFM,ZWORK(:,:),IRESP,HCOMMENT=YCOMMENT)
      !
      DO JPATCH=1,IO%NPATCH
        ZWORK(:,JPATCH) = DGI%DPC%AL(JPATCH)%XLE(:)
      ENDDO       
      YRECFM='LEC_P'
      YCOMMENT='X_Y_'//YRECFM//' (J/m2)'
      CALL WRITE_SURF(DUO%CSELECT,HPROGRAM,YRECFM,ZWORK(:,:),IRESP,HCOMMENT=YCOMMENT)
      !
      DO JPATCH=1,IO%NPATCH
        ZWORK(:,JPATCH) = DGI%DPC%AL(JPATCH)%XLEI(:)
      ENDDO       
      YRECFM='LEIC_P'
      YCOMMENT='X_Y_'//YRECFM//' (J/m2)'
      CALL WRITE_SURF(DUO%CSELECT,HPROGRAM,YRECFM,ZWORK(:,:),IRESP,HCOMMENT=YCOMMENT)
      !
      DO JPATCH=1,IO%NPATCH
        ZWORK(:,JPATCH) = DGI%DPC%AL(JPATCH)%XGFLUX(:)
      ENDDO       
      YRECFM='GFLUXC_P'
      YCOMMENT='X_Y_'//YRECFM//' (J/m2)'
      CALL WRITE_SURF(DUO%CSELECT,HPROGRAM,YRECFM,ZWORK(:,:),IRESP,HCOMMENT=YCOMMENT)
      !
      DO JPATCH=1,IO%NPATCH
        ZWORK(:,JPATCH) = DGI%DPC%AL(JPATCH)%XEVAP(:)
      ENDDO           
      YRECFM='EVAPC_P'
      YCOMMENT='X_Y_'//YRECFM//' (W/m2)'
      CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,ZWORK(:,:),IRESP,HCOMMENT=YCOMMENT)
      !
      DO JPATCH=1,IO%NPATCH
        ZWORK(:,JPATCH) = DGI%DPC%AL(JPATCH)%XSUBL(:)
      ENDDO           
      YRECFM='SUBLC_P'
      YCOMMENT='X_Y_'//YRECFM//' (W/m2)'
      CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,ZWORK(:,:),IRESP,HCOMMENT=YCOMMENT) 
      !    
      IF (DGI%O%LRAD_BUDGET .OR. (DGI%O%LSURF_BUDGETC .AND. .NOT.DUO%LRESET_BUDGETC)) THEN
        !
        DO JPATCH=1,IO%NPATCH
          ZWORK(:,JPATCH) = DGI%DPC%AL(JPATCH)%XSWD(:)
        ENDDO
        YRECFM='SWDC_P'
        YCOMMENT='X_Y_'//YRECFM//' (J/m2)'
        CALL WRITE_SURF(DUO%CSELECT,HPROGRAM,YRECFM,ZWORK(:,:),IRESP,HCOMMENT=YCOMMENT)
        !
        DO JPATCH=1,IO%NPATCH
          ZWORK(:,JPATCH) = DGI%DPC%AL(JPATCH)%XSWU(:)
        ENDDO        
        YRECFM='SWUC_P'
        YCOMMENT='X_Y_'//YRECFM//' (J/m2)'
        CALL WRITE_SURF(DUO%CSELECT,HPROGRAM,YRECFM,ZWORK(:,:),IRESP,HCOMMENT=YCOMMENT)
        !
        DO JPATCH=1,IO%NPATCH
          ZWORK(:,JPATCH) = DGI%DPC%AL(JPATCH)%XLWD(:)
        ENDDO        
        YRECFM='LWDC_P'
        YCOMMENT='X_Y_'//YRECFM//' (J/m2)'
        CALL WRITE_SURF(DUO%CSELECT,HPROGRAM,YRECFM,ZWORK(:,:),IRESP,HCOMMENT=YCOMMENT)
        !
        DO JPATCH=1,IO%NPATCH
          ZWORK(:,JPATCH) = DGI%DPC%AL(JPATCH)%XLWU(:)
        ENDDO        
        YRECFM='LWUC_P'
        YCOMMENT='X_Y_'//YRECFM//' (J/m2)'
        CALL WRITE_SURF(DUO%CSELECT,HPROGRAM,YRECFM,ZWORK(:,:),IRESP,HCOMMENT=YCOMMENT)
        !
      ENDIF
      !
      DO JPATCH=1,IO%NPATCH
        ZWORK(:,JPATCH) = DGI%DPC%AL(JPATCH)%XFMU(:)
      ENDDO      
      YRECFM='FMUC_P'
      YCOMMENT='X_Y_'//YRECFM//' (Pa.s)'      
      CALL WRITE_SURF(DUO%CSELECT,HPROGRAM,YRECFM,ZWORK(:,:),IRESP,HCOMMENT=YCOMMENT)
      !
      DO JPATCH=1,IO%NPATCH
        ZWORK(:,JPATCH) = DGI%DPC%AL(JPATCH)%XFMV(:)
      ENDDO      
      YRECFM='FMVC_P'
      YCOMMENT='X_Y_'//YRECFM//' (Pa.s)'      
      CALL WRITE_SURF(DUO%CSELECT,HPROGRAM,YRECFM,ZWORK(:,:),IRESP,HCOMMENT=YCOMMENT)
      !
    ENDIF
    !
    DEALLOCATE(ZWORK)
    !-------------------------------------------------------------------------------
ENDIF
!User want (or not) patch output
!-------------------------------------------------------------------------------
!
!*       15.     chemical diagnostics:
!               --------------------
!
IF (CHI%SVI%NBEQ>0 .AND. CHI%CCH_DRY_DEP=="WES89 ") THEN
  !
  DO JSV = 1,SIZE(CHI%CCH_NAMES,1)
    YRECFM='DV_NAT_'//TRIM(CHI%CCH_NAMES(JSV))
    WRITE(YCOMMENT,'(A13,I3.3)')'(m/s) DV_NAT_',JSV
    CALL WRITE_SURF(DUO%CSELECT,HPROGRAM,YRECFM,CHI%XDEP(:,JSV,:),IRESP,HCOMMENT=YCOMMENT)
  END DO
  !
ENDIF
!
IF (CHI%SVI%NBEQ>0 .AND. CHI%LCH_BIO_FLUX) THEN
  !
  IF (ASSOCIATED(GB%XFISO)) THEN
    YRECFM='FISO'
    WRITE(YCOMMENT,'(A21)')'FISO (molecules/m2/s)'
    CALL WRITE_SURF(DUO%CSELECT,HPROGRAM,YRECFM,GB%XFISO(:),IRESP,HCOMMENT=YCOMMENT)
  END IF
  !
  IF (ASSOCIATED(GB%XFISO)) THEN
    YRECFM='FMONO'
    WRITE(YCOMMENT,'(A22)')'FMONO (molecules/m2/s)'
    CALL WRITE_SURF(DUO%CSELECT,HPROGRAM,YRECFM,GB%XFMONO(:),IRESP,HCOMMENT=YCOMMENT)
  END IF
  !
ENDIF
!
IF (CHI%LCH_NO_FLUX) THEN
  IF (ASSOCIATED(GB%XNOFLUX)) THEN
    YRECFM='NOFLUX'
    WRITE(YCOMMENT,'(A21)')'NOFLUX (molecules/m2/s)'
    CALL WRITE_SURF(DUO%CSELECT, &
                  HPROGRAM,YRECFM,GB%XNOFLUX(:),IRESP,HCOMMENT=YCOMMENT)
  END IF
END IF
!
IF (CHI%SVI%NDSTEQ > 0)THEN
  !
  DO JSV = 1,NDSTMDE ! for all dust modes
    WRITE(YRECFM,'(A7,I3.3)')'FLX_DST',JSV
    YCOMMENT='X_Y_'//YRECFM//' (kg/m2/s)'
    CALL WRITE_SURF(DUO%CSELECT,HPROGRAM,YRECFM,DST%XSFDST(:,JSV,:),IRESP,HCOMMENT=YCOMMENT)
  END DO
  !
ENDIF
!
!-------------------------------------------------------------------------------
!
!         End of IO
!
 CALL END_IO_SURF_n(HPROGRAM)
IF (LHOOK) CALL DR_HOOK('WRITE_DIAG_SEB_ISBA_N',1,ZHOOK_HANDLE)
!
CONTAINS
!
!-------------------------------------------------------------------------------
!
SUBROUTINE WRITE_EVAP_BUD(DGEIA,HTERM,OFLAG)
!
USE MODD_DIAG_EVAP_ISBA_n, ONLY : DIAG_EVAP_ISBA_t
!
TYPE(DIAG_EVAP_ISBA_t) :: DGEIA
 CHARACTER(LEN=6), INTENT(IN) :: HTERM
LOGICAL, INTENT(IN) :: OFLAG
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
IF (LHOOK) CALL DR_HOOK('WRITE_DIAG_SEB_ISBA_N:WRITE_EVAP_BUD',0,ZHOOK_HANDLE)
!
YRECFM='LEG'//TRIM(HTERM)
YCOMMENT='bare ground evaporation for tile nature'//' (W/m2)'
CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,DGEIA%XLEG(:),IRESP,HCOMMENT=YCOMMENT)
!
YRECFM='LEGI'//TRIM(HTERM)
YCOMMENT='bare ground sublimation for tile nature'//' (W/m2)'
CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,DGEIA%XLEGI(:),IRESP,HCOMMENT=YCOMMENT)
!
YRECFM='LEV'//TRIM(HTERM)
YCOMMENT='total vegetation evaporation for tile nature'//' (W/m2)'
CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,DGEIA%XLEV(:),IRESP,HCOMMENT=YCOMMENT)
  !
YRECFM='LES'//TRIM(HTERM)
YCOMMENT='snow sublimation for tile nature'//' (W/m2)'  
CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,DGEIA%XLES(:),IRESP,HCOMMENT=YCOMMENT)
  !
IF(IR%TSNOW%SCHEME=='3-L' .OR. IR%TSNOW%SCHEME=='CRO')THEN  
  YRECFM='LESL'//TRIM(HTERM)
  YCOMMENT='liquid water evaporation over snow for tile nature'//' (W/m2)'
  CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,DGEIA%XLESL(:),IRESP,HCOMMENT=YCOMMENT)
  YRECFM='SNDRIF'//TRIM(HTERM)
  YCOMMENT='blowing snow sublimation for tile nature'//' (Kg/m2/s)'
  CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,DGEIA%XSNDRIFT(:),IRESP,HCOMMENT=YCOMMENT)    
ENDIF
  !  
YRECFM='LER'//TRIM(HTERM)
YCOMMENT='canopy direct evaporation for tile nature'//' (W/m2)'
CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,DGEIA%XLER(:),IRESP,HCOMMENT=YCOMMENT)
  !
YRECFM='LETR'//TRIM(HTERM)
YCOMMENT='vegetation transpiration for tile nature'//' (W/m2)'
CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,DGEIA%XLETR(:),IRESP,HCOMMENT=YCOMMENT)
  !
YRECFM='DRAIN'//TRIM(HTERM)
YCOMMENT='drainage for tile nature'//' (Kg/m2/s)'
CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,DGEIA%XDRAIN(:),IRESP,HCOMMENT=YCOMMENT)
  !
IF(IO%CRUNOFF=='SGH'.AND.IO%CISBA=='DIF')THEN
  YRECFM='QSB'//TRIM(HTERM)
  YCOMMENT='lateral subsurface flow for tile nature'//' (Kg/m2/s)'
  CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,DGEIA%XQSB(:),IRESP,HCOMMENT=YCOMMENT)
ENDIF
  !
YRECFM='RUNOFF'//TRIM(HTERM)
YCOMMENT='runoff for tile nature'//' (Kg/m2/s)'
CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,DGEIA%XRUNOFF(:),IRESP,HCOMMENT=YCOMMENT)
  !
IF(IO%CHORT=='SGH'.OR.IO%CISBA=='DIF')THEN
  YRECFM='HORTON'//TRIM(HTERM)
  YCOMMENT='horton runoff for tile nature'//' (Kg/m2/s)'
  CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,DGEIA%XHORT(:),IRESP,HCOMMENT=YCOMMENT)
ENDIF
  !
YRECFM='DRIVEG'//TRIM(HTERM)
YCOMMENT='X_Y_'//YRECFM//' (Kg/m2/s)'
CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,DGEIA%XDRIP(:),IRESP,HCOMMENT=YCOMMENT)
  !
YRECFM='RRVEG'//TRIM(HTERM)
YCOMMENT='X_Y_'//YRECFM//' (Kg/m2/s)'
CALL WRITE_SURF(DUO%CSELECT, &
                  HPROGRAM,YRECFM,DGEIA%XRRVEG(:),IRESP,HCOMMENT=YCOMMENT)
  !
YRECFM='SNOMLT'//TRIM(HTERM)
YCOMMENT='snow melting rate'//' (Kg/m2/s)'
CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,DGEIA%XMELT(:),IRESP,HCOMMENT=YCOMMENT)
  !
IF(LAGRIP)THEN
  YRECFM='IRRIG'//TRIM(HTERM)
  YCOMMENT='irrigation rate'//' (Kg/m2/s)'
  CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,DGEIA%XIRRIG_FLUX(:),IRESP,HCOMMENT=YCOMMENT)
ENDIF  
! MEB STUFF
IF (ISIZE_LMEB_PATCH>0) THEN
  YRECFM='LEVCV'//TRIM(HTERM)
  YCOMMENT='X_Y_'//YRECFM//' (W/m2)'
  CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,DGEIA%XLEVCV(:),IRESP,HCOMMENT=YCOMMENT)
    !
  YRECFM='LESC'//TRIM(HTERM)
  YCOMMENT='X_Y_'//YRECFM//' (W/m2)'
  CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,DGEIA%XLESC(:),IRESP,HCOMMENT=YCOMMENT)
    !
  YRECFM='LETRGV'//TRIM(HTERM)
  YCOMMENT='X_Y_'//YRECFM//' (W/m2)'
  CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,DGEIA%XLETRGV(:),IRESP,HCOMMENT=YCOMMENT)
    !
  YRECFM='LETRCV'//TRIM(HTERM)
  YCOMMENT='X_Y_'//YRECFM//' (W/m2)'
  CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,DGEIA%XLETRCV(:),IRESP,HCOMMENT=YCOMMENT)
    !
  YRECFM='LERGV'//TRIM(HTERM)
  YCOMMENT='X_Y_'//YRECFM//' (W/m2)'
  CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,DGEIA%XLERGV(:),IRESP,HCOMMENT=YCOMMENT)
    !
  YRECFM='LELIT'//TRIM(HTERM)
  YCOMMENT='X_Y_'//YRECFM//' (W/m2)'
  CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,DGEIA%XLELITTER(:),IRESP,HCOMMENT=YCOMMENT)
    !
  YRECFM='LELITI'//TRIM(HTERM)
  YCOMMENT='X_Y_'//YRECFM//' (W/m2)'
  CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,DGEIA%XLELITTERI(:),IRESP,HCOMMENT=YCOMMENT)
    !
  YRECFM='DRIPLIT'//TRIM(HTERM)
  YCOMMENT='X_Y_'//YRECFM//' (W/m2)'
  CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,DGEIA%XDRIPLIT(:),IRESP,HCOMMENT=YCOMMENT)
    !
  YRECFM='RRLIT'//TRIM(HTERM)
  YCOMMENT='X_Y_'//YRECFM//' (W/m2)'
  CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,DGEIA%XRRLIT(:),IRESP,HCOMMENT=YCOMMENT)
    !
  YRECFM='LERCV'//TRIM(HTERM)
  YCOMMENT='X_Y_'//YRECFM//' (W/m2)'
  CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,DGEIA%XLERCV(:),IRESP,HCOMMENT=YCOMMENT)
    !
  YRECFM='LE_C_A'//TRIM(HTERM)
  YCOMMENT='X_Y_'//YRECFM//' (W/m2)'
  CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,DGEIA%XLE_C_A(:),IRESP,HCOMMENT=YCOMMENT)
    !
  YRECFM='LE_V_C'//TRIM(HTERM)
  YCOMMENT='X_Y_'//YRECFM//' (W/m2)'
  CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,DGEIA%XLE_V_C(:),IRESP,HCOMMENT=YCOMMENT)
    !
  YRECFM='LE_G_C'//TRIM(HTERM)
  YCOMMENT='X_Y_'//YRECFM//' (W/m2)'
  CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,DGEIA%XLE_G_C(:),IRESP,HCOMMENT=YCOMMENT)
    !
  YRECFM='LE_N_C'//TRIM(HTERM)
  YCOMMENT='X_Y_'//YRECFM//' (W/m2)'
  CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,DGEIA%XLE_N_C(:),IRESP,HCOMMENT=YCOMMENT)
    !
  YRECFM='SWNT_V'//TRIM(HTERM)
  YCOMMENT='X_Y_'//YRECFM//' (W/m2)'
  CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,DGEIA%XSWNET_V(:),IRESP,HCOMMENT=YCOMMENT)
    !
  YRECFM='SWNT_G'//TRIM(HTERM)
  YCOMMENT='X_Y_'//YRECFM//' (W/m2)'
  CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,DGEIA%XSWNET_G(:),IRESP,HCOMMENT=YCOMMENT)
    !
  YRECFM='SWNT_N'//TRIM(HTERM)
  YCOMMENT='X_Y_'//YRECFM//' (W/m2)'
  CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,DGEIA%XSWNET_N(:),IRESP,HCOMMENT=YCOMMENT)
    !
  YRECFM='SWNT_NS'//TRIM(HTERM)
  YCOMMENT='X_Y_'//YRECFM//' (W/m2)'
  CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,DGEIA%XSWNET_NS(:),IRESP,HCOMMENT=YCOMMENT)
    !
  YRECFM='LWNT_V'//TRIM(HTERM)
  YCOMMENT='X_Y_'//YRECFM//' (W/m2)'
  CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,DGEIA%XLWNET_V(:),IRESP,HCOMMENT=YCOMMENT)
    !
  YRECFM='LWNT_G'//TRIM(HTERM)
  YCOMMENT='X_Y_'//YRECFM//' (W/m2)'
  CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,DGEIA%XLWNET_G(:),IRESP,HCOMMENT=YCOMMENT)
    !
  YRECFM='LWNT_N'//TRIM(HTERM)
  YCOMMENT='X_Y_'//YRECFM//' (W/m2)'
  CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,DGEIA%XLWNET_N(:),IRESP,HCOMMENT=YCOMMENT)
    !
  YRECFM='SWDN_GN'//TRIM(HTERM)
  YCOMMENT='X_Y_'//YRECFM//' (W/m2)'
  CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,DGEIA%XSWDOWN_GN(:),IRESP,HCOMMENT=YCOMMENT)
    !
  YRECFM='LWDN_GN'//TRIM(HTERM)
  YCOMMENT='X_Y_'//YRECFM//' (W/m2)'
  CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,DGEIA%XLWDOWN_GN(:),IRESP,HCOMMENT=YCOMMENT)
    !
  YRECFM='H_V_C'//TRIM(HTERM)
  YCOMMENT='X_Y_'//YRECFM//' (W/m2)'
  CALL WRITE_SURF(DUO%CSELECT, &
                  HPROGRAM,YRECFM,DGEIA%XH_V_C(:),IRESP,HCOMMENT=YCOMMENT)
    !
  YRECFM='H_G_C'//TRIM(HTERM)
  YCOMMENT='X_Y_'//YRECFM//' (W/m2)'
  CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,DGEIA%XH_G_C(:),IRESP,HCOMMENT=YCOMMENT)
    !
  YRECFM='H_C_A'//TRIM(HTERM)
  YCOMMENT='X_Y_'//YRECFM//' (W/m2)'
  CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,DGEIA%XH_C_A(:),IRESP,HCOMMENT=YCOMMENT)
    !
  YRECFM='H_N_C'//TRIM(HTERM)
  YCOMMENT='X_Y_'//YRECFM//' (W/m2)'
  CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,DGEIA%XH_N_C(:),IRESP,HCOMMENT=YCOMMENT)
    !
  YRECFM='SR_GN'//TRIM(HTERM)
  YCOMMENT='X_Y_'//YRECFM//' (kg/m2/s)'
  CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,DGEIA%XSR_GN(:),IRESP,HCOMMENT=YCOMMENT)
    !
  YRECFM='MELTCV'//TRIM(HTERM)
  YCOMMENT='X_Y_'//YRECFM//' (kg/m2/s)'
  CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,DGEIA%XMELTCV(:),IRESP,HCOMMENT=YCOMMENT)
    !
  YRECFM='FRZCV'//TRIM(HTERM)
  YCOMMENT='X_Y_'//YRECFM//' (kg/m2/s)'
  CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,DGEIA%XFRZCV(:),IRESP,HCOMMENT=YCOMMENT)
ENDIF
  ! END MEB STUFF
  !
IF(IO%LFLOOD)THEN
  !        
  YRECFM='IFLOOD'//TRIM(HTERM)
  YCOMMENT='flood soil infiltration (Kg/m2/s)'    
  CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,DGEIA%XIFLOOD(:),IRESP,HCOMMENT=YCOMMENT)
    !
  YRECFM='PFLOOD'//TRIM(HTERM)
  YCOMMENT='intercepted precipitation by floodplains (Kg/m2/s)'    
  CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,DGEIA%XPFLOOD(:),IRESP,HCOMMENT=YCOMMENT)
    !
  YRECFM='LEF'//TRIM(HTERM)
  YCOMMENT='total floodplains evaporation (W/m2)'   
  CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,DGEIA%XLE_FLOOD(:),IRESP,HCOMMENT=YCOMMENT)
    !
  YRECFM='LEIF'//TRIM(HTERM)
  YCOMMENT='solid floodplains evaporation (W/m2)'    
  CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,DGEIA%XLEI_FLOOD(:),IRESP,HCOMMENT=YCOMMENT)
    !
ENDIF
  !
IF(IO%CPHOTO/='NON')THEN
    !
  YRECFM='GPP'//TRIM(HTERM)
  YCOMMENT='gross primary production over tile nature (kgCO2/m2/s)'
  CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,DGEIA%XGPP(:),IRESP,HCOMMENT=YCOMMENT)
    !
  IF (HTERM(1:1)=="C") THEN
    YRECFM='RC_AUTO'//TRIM(HTERM(2:))
  ELSE
    YRECFM='R_AUTO'//TRIM(HTERM)
  ENDIF      
  YCOMMENT='autotrophic respiration over tile nature (kgCO2/m2/s)'
  CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,DGEIA%XRESP_AUTO(:),IRESP,HCOMMENT=YCOMMENT)
    !
  IF (HTERM(1:1)=="C") THEN
    YRECFM='RC_ECO'//TRIM(HTERM(2:))
  ELSE
    YRECFM='R_ECO'//TRIM(HTERM)
  ENDIF      
  YCOMMENT='ecosystem respiration over tile nature (kgCO2/m2/s)'
  CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,DGEIA%XRESP_ECO(:),IRESP,HCOMMENT=YCOMMENT)
    !
ENDIF
!  
IF(DGI%DE%LWATER_BUDGET .OR. OFLAG)THEN 
    !
  YRECFM='RAINF'//TRIM(HTERM)
  YCOMMENT='input rainfall rate (Kg/m2/s)'
  CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,DGEIA%XRAINFALL(:),IRESP,HCOMMENT=YCOMMENT)
    !
  YRECFM='SNOWF'//TRIM(HTERM)
  YCOMMENT='input snowfall rate (Kg/m2/s)'
  CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,DGEIA%XSNOWFALL(:),IRESP,HCOMMENT=YCOMMENT)
    !
  YRECFM='DWG'//TRIM(HTERM)
  YCOMMENT='change in liquid soil moisture (Kg/m2/s)'
  CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,DGEIA%XDWG(:),IRESP,HCOMMENT=YCOMMENT)
    !
  YRECFM='DWGI'//TRIM(HTERM)
  YCOMMENT='change in solid soil moisture (Kg/m2/s)'
  CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,DGEIA%XDWGI(:),IRESP,HCOMMENT=YCOMMENT)
    !
  YRECFM='DWR'//TRIM(HTERM)
  YCOMMENT='change in water on canopy (Kg/m2/s)'
  CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,DGEIA%XDWR(:),IRESP,HCOMMENT=YCOMMENT)
    !
  YRECFM='DSWE'//TRIM(HTERM)
  YCOMMENT='change in snow water equivalent (Kg/m2/s)'
  CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,DGEIA%XDSWE(:),IRESP,HCOMMENT=YCOMMENT)
    !
  YRECFM='WATBUD'//TRIM(HTERM)
  YCOMMENT='isba water budget as residue (Kg/m2/s)'
  CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,DGEIA%XWATBUD(:),IRESP,HCOMMENT=YCOMMENT)
    !
ENDIF
!
IF (LHOOK) CALL DR_HOOK('WRITE_DIAG_SEB_ISBA_N:WRITE_EVAP_BUD',1,ZHOOK_HANDLE)
!
END SUBROUTINE WRITE_EVAP_BUD
!
SUBROUTINE WRITE_EVAP_BUD_PATCH(DGEIPA,HTERM,OFLAG)
!
USE MODD_DIAG_EVAP_ISBA_n, ONLY : DIAG_EVAP_ISBA_PATCH_t
!
TYPE(DIAG_EVAP_ISBA_PATCH_t) :: DGEIPA
 CHARACTER(LEN=3), INTENT(IN) :: HTERM
LOGICAL, INTENT(IN) :: OFLAG
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
IF (LHOOK) CALL DR_HOOK('WRITE_DIAG_SEB_ISBA_N:WRITE_EVAP_BUD_PATCH',0,ZHOOK_HANDLE)
!
ALLOCATE(ZWORK(SIZE(DGEIPA%AL(1)%XLEG(:)),IO%NPATCH))
!
DO JPATCH=1,IO%NPATCH
  ZWORK(:,JPATCH) = DGEIPA%AL(JPATCH)%XLEG(:)
ENDDO 
YRECFM='LEG'//TRIM(HTERM)
YCOMMENT='X_Y_'//YRECFM//' (W/m2)'
CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,ZWORK(:,:),IRESP,HCOMMENT=YCOMMENT)
!
DO JPATCH=1,IO%NPATCH
  ZWORK(:,JPATCH) = DGEIPA%AL(JPATCH)%XLEGI(:)
ENDDO   
YRECFM='LEGI'//TRIM(HTERM)
YCOMMENT='X_Y_'//YRECFM//' (W/m2)'
CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,ZWORK(:,:),IRESP,HCOMMENT=YCOMMENT)
!
DO JPATCH=1,IO%NPATCH
  ZWORK(:,JPATCH) = DGEIPA%AL(JPATCH)%XLEV(:)
ENDDO   
YRECFM='LEV'//TRIM(HTERM)
YCOMMENT='X_Y_'//YRECFM//' (W/m2)'
CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,ZWORK(:,:),IRESP,HCOMMENT=YCOMMENT)
!
DO JPATCH=1,IO%NPATCH
  ZWORK(:,JPATCH) = DGEIPA%AL(JPATCH)%XLES(:)
ENDDO   
YRECFM='LES'//TRIM(HTERM)
YCOMMENT='X_Y_'//YRECFM//' (W/m2)'
CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,ZWORK(:,:),IRESP,HCOMMENT=YCOMMENT)
!

IF(IR%TSNOW%SCHEME=='3-L' .OR. IR%TSNOW%SCHEME=='CRO')THEN 
  DO JPATCH=1,IO%NPATCH
    ZWORK(:,JPATCH) = DGEIPA%AL(JPATCH)%XLESL(:)
  ENDDO    
  YRECFM='LESL'//TRIM(HTERM)
  YCOMMENT='X_Y_'//YRECFM//' (W/m2)'
  CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,ZWORK(:,:),IRESP,HCOMMENT=YCOMMENT)
  DO JPATCH=1,IO%NPATCH
    ZWORK(:,JPATCH) = DGEIPA%AL(JPATCH)%XSNDRIFT(:)
  ENDDO
  YRECFM='SNDRIF'//TRIM(HTERM)
  YCOMMENT='X_Y_'//YRECFM//' (kg/m2/s)'
  CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,ZWORK(:,:),IRESP,HCOMMENT=YCOMMENT)
ENDIF
! 
DO JPATCH=1,IO%NPATCH
  ZWORK(:,JPATCH) = DGEIPA%AL(JPATCH)%XLER(:)
ENDDO  
YRECFM='LER'//TRIM(HTERM)
YCOMMENT='X_Y_'//YRECFM//' (W/m2)'
CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,ZWORK(:,:),IRESP,HCOMMENT=YCOMMENT)
!
DO JPATCH=1,IO%NPATCH
  ZWORK(:,JPATCH) = DGEIPA%AL(JPATCH)%XLETR(:)
ENDDO  
YRECFM='LETR'//TRIM(HTERM)
YCOMMENT='X_Y_'//YRECFM//' (W/m2)'
CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,ZWORK(:,:),IRESP,HCOMMENT=YCOMMENT)
!
DO JPATCH=1,IO%NPATCH
  ZWORK(:,JPATCH) = DGEIPA%AL(JPATCH)%XDRAIN(:)
ENDDO  
YRECFM='DRAIN'//TRIM(HTERM)
YCOMMENT='X_Y_'//YRECFM//' (Kg/m2/s)'
CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,ZWORK(:,:),IRESP,HCOMMENT=YCOMMENT)
!
DO JPATCH=1,IO%NPATCH
  ZWORK(:,JPATCH) = DGEIPA%AL(JPATCH)%XQSB(:)
ENDDO  
IF(IO%CRUNOFF=='SGH'.AND.IO%CISBA=='DIF')THEN
  YRECFM='QSB'//TRIM(HTERM)
  YCOMMENT='X_Y_'//YRECFM//' (Kg/m2/s)'
  CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,ZWORK(:,:),IRESP,HCOMMENT=YCOMMENT)
ENDIF
!
DO JPATCH=1,IO%NPATCH
  ZWORK(:,JPATCH) = DGEIPA%AL(JPATCH)%XRUNOFF(:)
ENDDO  
YRECFM='RUNOFF'//TRIM(HTERM)
YCOMMENT='X_Y_'//YRECFM//' (Kg/m2/s)'
CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,ZWORK(:,:),IRESP,HCOMMENT=YCOMMENT)
!
IF(IO%CHORT=='SGH'.OR.IO%CISBA=='DIF')THEN
  DO JPATCH=1,IO%NPATCH
    ZWORK(:,JPATCH) = DGEIPA%AL(JPATCH)%XHORT(:)
  ENDDO    
  YRECFM='HORTON'//TRIM(HTERM)
  YCOMMENT='X_Y_'//YRECFM//' (Kg/m2/s)'
  CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,ZWORK(:,:),IRESP,HCOMMENT=YCOMMENT)
ENDIF
!
DO JPATCH=1,IO%NPATCH
  ZWORK(:,JPATCH) = DGEIPA%AL(JPATCH)%XDRIP(:)
ENDDO  
YRECFM='DRIVEG'//TRIM(HTERM)
YCOMMENT='X_Y_'//YRECFM//' (Kg/m2/s)'
CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,ZWORK(:,:),IRESP,HCOMMENT=YCOMMENT)
!
DO JPATCH=1,IO%NPATCH
  ZWORK(:,JPATCH) = DGEIPA%AL(JPATCH)%XRRVEG(:)
ENDDO  
YRECFM='RRVEG'//TRIM(HTERM)
YCOMMENT='X_Y_'//YRECFM//' (Kg/m2/s)'
CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,ZWORK(:,:),IRESP,HCOMMENT=YCOMMENT)
!
DO JPATCH=1,IO%NPATCH
  ZWORK(:,JPATCH) = DGEIPA%AL(JPATCH)%XMELT(:)
ENDDO  
YRECFM='SNOMLT'//TRIM(HTERM)
YCOMMENT='X_Y_'//YRECFM//' (Kg/m2/s)'
CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,ZWORK(:,:),IRESP,HCOMMENT=YCOMMENT)
!
! MEB STUFF
IF (ISIZE_LMEB_PATCH>0) THEN
  DO JPATCH=1,IO%NPATCH
    ZWORK(:,JPATCH) = DGEIPA%AL(JPATCH)%XLEVCV(:)
  ENDDO    
  YRECFM='LEVCV'//TRIM(HTERM)
  YCOMMENT='X_Y_'//YRECFM//' (W/m2)'
  CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,ZWORK(:,:),IRESP,HCOMMENT=YCOMMENT)
  !
  DO JPATCH=1,IO%NPATCH
    ZWORK(:,JPATCH) = DGEIPA%AL(JPATCH)%XLESC(:)
  ENDDO  
  YRECFM='LESC'//TRIM(HTERM)
  YCOMMENT='X_Y_'//YRECFM//' (W/m2)'
  CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,ZWORK(:,:),IRESP,HCOMMENT=YCOMMENT)
  !
!  YRECFM='LETRGV'//TRIM(HTERM)
!  YCOMMENT='X_Y_'//YRECFM//' (W/m2)'
!  CALL WRITE_SURF(HPROGRAM,YRECFM,XLETRGV(:,:),IRESP,HCOMMENT=YCOMMENT)
  !
  DO JPATCH=1,IO%NPATCH
    ZWORK(:,JPATCH) = DGEIPA%AL(JPATCH)%XLETRCV(:)
  ENDDO  
  YRECFM='LETRCV'//TRIM(HTERM)
  YCOMMENT='X_Y_'//YRECFM//' (W/m2)'
  CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,ZWORK(:,:),IRESP,HCOMMENT=YCOMMENT)
  !
!  YRECFM='LERGV'//TRIM(HTERM)
!  YCOMMENT='X_Y_'//YRECFM//' (W/m2)'
!  CALL WRITE_SURF(DUO%CSELECT, !    HPROGRAM,YRECFM,DGEI%XLERGV(:,:),IRESP,HCOMMENT=YCOMMENT)
  !
  DO JPATCH=1,IO%NPATCH
    ZWORK(:,JPATCH) = DGEIPA%AL(JPATCH)%XLELITTER(:)
  ENDDO  
  YRECFM='LELITTER'//TRIM(HTERM)
  YCOMMENT='X_Y_'//YRECFM//' (W/m2)'
  CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,ZWORK(:,:),IRESP,HCOMMENT=YCOMMENT)
  !
  DO JPATCH=1,IO%NPATCH
    ZWORK(:,JPATCH) = DGEIPA%AL(JPATCH)%XLELITTERI(:)
  ENDDO  
  YRECFM='LELITTERI'//TRIM(HTERM)
  YCOMMENT='X_Y_'//YRECFM//' (W/m2)'
  CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,ZWORK(:,:),IRESP,HCOMMENT=YCOMMENT)
  !
  DO JPATCH=1,IO%NPATCH
    ZWORK(:,JPATCH) = DGEIPA%AL(JPATCH)%XDRIPLIT(:)
  ENDDO  
  YRECFM='DRIPLIT'//TRIM(HTERM)
  YCOMMENT='X_Y_'//YRECFM//' (W/m2)'
  CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,ZWORK(:,:),IRESP,HCOMMENT=YCOMMENT)
  !
  DO JPATCH=1,IO%NPATCH
    ZWORK(:,JPATCH) = DGEIPA%AL(JPATCH)%XRRLIT(:)
  ENDDO  
  YRECFM='RRLIT'//TRIM(HTERM)
  YCOMMENT='X_Y_'//YRECFM//' (W/m2)'
  CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,ZWORK(:,:),IRESP,HCOMMENT=YCOMMENT)
  !
  DO JPATCH=1,IO%NPATCH
    ZWORK(:,JPATCH) = DGEIPA%AL(JPATCH)%XLERCV(:)
  ENDDO  
  YRECFM='LERCV'//TRIM(HTERM)
  YCOMMENT='X_Y_'//YRECFM//' (W/m2)'
  CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,ZWORK(:,:),IRESP,HCOMMENT=YCOMMENT)
  !
  DO JPATCH=1,IO%NPATCH
    ZWORK(:,JPATCH) = DGEIPA%AL(JPATCH)%XLE_C_A(:)
  ENDDO  
  YRECFM='LE_C_A'//TRIM(HTERM)
  YCOMMENT='X_Y_'//YRECFM//' (W/m2)'
  CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,ZWORK(:,:),IRESP,HCOMMENT=YCOMMENT)
  !
  DO JPATCH=1,IO%NPATCH
    ZWORK(:,JPATCH) = DGEIPA%AL(JPATCH)%XLE_V_C(:)
  ENDDO  
  YRECFM='LE_V_C'//TRIM(HTERM)
  YCOMMENT='X_Y_'//YRECFM//' (W/m2)'
  CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,ZWORK(:,:),IRESP,HCOMMENT=YCOMMENT)
  !
  DO JPATCH=1,IO%NPATCH
    ZWORK(:,JPATCH) = DGEIPA%AL(JPATCH)%XLE_G_C(:)
  ENDDO  
  YRECFM='LE_G_C'//TRIM(HTERM)
  YCOMMENT='X_Y_'//YRECFM//' (W/m2)'
  CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,ZWORK(:,:),IRESP,HCOMMENT=YCOMMENT)
  !
  DO JPATCH=1,IO%NPATCH
    ZWORK(:,JPATCH) = DGEIPA%AL(JPATCH)%XLE_N_C(:)
  ENDDO  
  YRECFM='LE_N_C'//TRIM(HTERM)
  YCOMMENT='X_Y_'//YRECFM//' (W/m2)'
  CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,ZWORK(:,:),IRESP,HCOMMENT=YCOMMENT)
  !
  DO JPATCH=1,IO%NPATCH
    ZWORK(:,JPATCH) = DGEIPA%AL(JPATCH)%XSWNET_V(:)
  ENDDO  
  YRECFM='SWNT_V'//TRIM(HTERM)
  YCOMMENT='X_Y_'//YRECFM//' (W/m2)'
  CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,ZWORK(:,:),IRESP,HCOMMENT=YCOMMENT)
  !
  DO JPATCH=1,IO%NPATCH
    ZWORK(:,JPATCH) = DGEIPA%AL(JPATCH)%XSWNET_G(:)
  ENDDO  
  YRECFM='SWNT_G'//TRIM(HTERM)
  YCOMMENT='X_Y_'//YRECFM//' (W/m2)'
  CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,ZWORK(:,:),IRESP,HCOMMENT=YCOMMENT)
  !
  DO JPATCH=1,IO%NPATCH
    ZWORK(:,JPATCH) = DGEIPA%AL(JPATCH)%XSWNET_N(:)
  ENDDO  
  YRECFM='SWNT_N'//TRIM(HTERM)
  YCOMMENT='X_Y_'//YRECFM//' (W/m2)'
  CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,ZWORK(:,:),IRESP,HCOMMENT=YCOMMENT)
  !
  DO JPATCH=1,IO%NPATCH
    ZWORK(:,JPATCH) = DGEIPA%AL(JPATCH)%XSWNET_NS(:)
  ENDDO  
  YRECFM='SWNT_NS'//TRIM(HTERM)
  YCOMMENT='X_Y_'//YRECFM//' (W/m2)'
  CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,ZWORK(:,:),IRESP,HCOMMENT=YCOMMENT)
  !
  DO JPATCH=1,IO%NPATCH
    ZWORK(:,JPATCH) = DGEIPA%AL(JPATCH)%XLWNET_V(:)
  ENDDO  
  YRECFM='LWNT_V'//TRIM(HTERM)
  YCOMMENT='X_Y_'//YRECFM//' (W/m2)'
  CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,ZWORK(:,:),IRESP,HCOMMENT=YCOMMENT)
  !
  DO JPATCH=1,IO%NPATCH
    ZWORK(:,JPATCH) = DGEIPA%AL(JPATCH)%XLWNET_G(:)
  ENDDO  
  YRECFM='LWNT_G'//TRIM(HTERM)
  YCOMMENT='X_Y_'//YRECFM//' (W/m2)'
  CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,ZWORK(:,:),IRESP,HCOMMENT=YCOMMENT)
  !
  DO JPATCH=1,IO%NPATCH
    ZWORK(:,JPATCH) = DGEIPA%AL(JPATCH)%XLWNET_N(:)
  ENDDO  
  YRECFM='LWNT_N'//TRIM(HTERM)
  YCOMMENT='X_Y_'//YRECFM//' (W/m2)'
  CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,ZWORK(:,:),IRESP,HCOMMENT=YCOMMENT)
  !
  DO JPATCH=1,IO%NPATCH
    ZWORK(:,JPATCH) = DGEIPA%AL(JPATCH)%XSWDOWN_GN(:)
  ENDDO  
  YRECFM='SWDN_GN'//TRIM(HTERM)
  YCOMMENT='X_Y_'//YRECFM//' (W/m2)'
  CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,ZWORK(:,:),IRESP,HCOMMENT=YCOMMENT)
  !
  DO JPATCH=1,IO%NPATCH
    ZWORK(:,JPATCH) = DGEIPA%AL(JPATCH)%XLWDOWN_GN(:)
  ENDDO  
  YRECFM='LWDN_GN'//TRIM(HTERM)
  YCOMMENT='X_Y_'//YRECFM//' (W/m2)'
  CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,ZWORK(:,:),IRESP,HCOMMENT=YCOMMENT)
  !
  DO JPATCH=1,IO%NPATCH
    ZWORK(:,JPATCH) = DGEIPA%AL(JPATCH)%XH_V_C(:)
  ENDDO  
  YRECFM='H_V_C'//TRIM(HTERM)
  YCOMMENT='X_Y_'//YRECFM//' (W/m2)'
  CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,ZWORK(:,:),IRESP,HCOMMENT=YCOMMENT)
  !
  DO JPATCH=1,IO%NPATCH
    ZWORK(:,JPATCH) = DGEIPA%AL(JPATCH)%XH_G_C(:)
  ENDDO  
  YRECFM='H_G_C'//TRIM(HTERM)
  YCOMMENT='X_Y_'//YRECFM//' (W/m2)'
  CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,ZWORK(:,:),IRESP,HCOMMENT=YCOMMENT)
  !
  DO JPATCH=1,IO%NPATCH
    ZWORK(:,JPATCH) = DGEIPA%AL(JPATCH)%XH_C_A(:)
  ENDDO  
  YRECFM='H_C_A'//TRIM(HTERM)
  YCOMMENT='X_Y_'//YRECFM//' (W/m2)'
  CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,ZWORK(:,:),IRESP,HCOMMENT=YCOMMENT)
  !
  DO JPATCH=1,IO%NPATCH
    ZWORK(:,JPATCH) = DGEIPA%AL(JPATCH)%XH_N_C(:)
  ENDDO  
  YRECFM='H_N_C'//TRIM(HTERM)
  YCOMMENT='X_Y_'//YRECFM//' (W/m2)'
  CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,ZWORK(:,:),IRESP,HCOMMENT=YCOMMENT)
  !
  DO JPATCH=1,IO%NPATCH
    ZWORK(:,JPATCH) = DGEIPA%AL(JPATCH)%XSR_GN(:)
  ENDDO  
  YRECFM='SR_GN'//TRIM(HTERM)
  YCOMMENT='X_Y_'//YRECFM//' (kg/m2/s)'
  CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,ZWORK(:,:),IRESP,HCOMMENT=YCOMMENT)
  !
  DO JPATCH=1,IO%NPATCH
    ZWORK(:,JPATCH) = DGEIPA%AL(JPATCH)%XMELTCV(:)
  ENDDO  
  YRECFM='MELTCV'//TRIM(HTERM)
  YCOMMENT='X_Y_'//YRECFM//' (kg/m2/s)'
  CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,ZWORK(:,:),IRESP,HCOMMENT=YCOMMENT)
  !
  DO JPATCH=1,IO%NPATCH
    ZWORK(:,JPATCH) = DGEIPA%AL(JPATCH)%XFRZCV(:)
  ENDDO  
  YRECFM='FRZCV'//TRIM(HTERM)
  YCOMMENT='X_Y_'//YRECFM//' (kg/m2/s)'
  CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,ZWORK(:,:),IRESP,HCOMMENT=YCOMMENT)
ENDIF
! END MEB STUFF
!
IF(LAGRIP)THEN
  DO JPATCH=1,IO%NPATCH
    ZWORK(:,JPATCH) = DGEIPA%AL(JPATCH)%XIRRIG_FLUX(:)
  ENDDO  
  YRECFM='IRRIG'//TRIM(HTERM)
  YCOMMENT='X_Y_'//YRECFM//' (Kg/m2/s)'
  CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,ZWORK(:,:),IRESP,HCOMMENT=YCOMMENT)
ENDIF
!
IF(IO%LFLOOD)THEN
  !
  DO JPATCH=1,IO%NPATCH
    ZWORK(:,JPATCH) = DGEIPA%AL(JPATCH)%XIFLOOD(:)
  ENDDO  
  YRECFM='IFLOOD'//TRIM(HTERM)
  YCOMMENT='X_Y_'//YRECFM//' (Kg/m2/s)'
  CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,ZWORK(:,:),IRESP,HCOMMENT=YCOMMENT)
  !
  DO JPATCH=1,IO%NPATCH
    ZWORK(:,JPATCH) = DGEIPA%AL(JPATCH)%XPFLOOD(:)
  ENDDO  
  YRECFM='PFLOOD'//TRIM(HTERM)
  YCOMMENT='X_Y_'//YRECFM//' (Kg/m2/s)'
  CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,ZWORK(:,:),IRESP,HCOMMENT=YCOMMENT)
  !
  DO JPATCH=1,IO%NPATCH
    ZWORK(:,JPATCH) = DGEIPA%AL(JPATCH)%XLE_FLOOD(:)
  ENDDO  
  YRECFM='LEF'//TRIM(HTERM)
  YCOMMENT='X_Y_'//YRECFM//' (W/m2)'
  CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,ZWORK(:,:),IRESP,HCOMMENT=YCOMMENT)
  !
  DO JPATCH=1,IO%NPATCH
    ZWORK(:,JPATCH) = DGEIPA%AL(JPATCH)%XLEI_FLOOD(:)
  ENDDO  
  YRECFM='LEIF'//TRIM(HTERM)
  YCOMMENT='X_Y_'//YRECFM//' (W/m2)'
  CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,ZWORK(:,:),IRESP,HCOMMENT=YCOMMENT)
  !
ENDIF
!
IF(IO%CPHOTO/='NON')THEN
  !
  DO JPATCH=1,IO%NPATCH
    ZWORK(:,JPATCH) = DGEIPA%AL(JPATCH)%XGPP(:)
  ENDDO  
  YRECFM='GPP'//TRIM(HTERM)
  YCOMMENT='gross primary production per patch (kgCO2/m2/s)'
  CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,ZWORK(:,:),IRESP,HCOMMENT=YCOMMENT)
  !
  DO JPATCH=1,IO%NPATCH
    ZWORK(:,JPATCH) = DGEIPA%AL(JPATCH)%XRESP_AUTO(:)
  ENDDO  
  IF (HTERM(1:1)=="C") THEN
    YRECFM='RC_AUTO'//TRIM(HTERM(2:))
  ELSE
    YRECFM='R_AUTO'//TRIM(HTERM)
  ENDIF
  YCOMMENT='autotrophic respiration per patch (kgCO2/m2/s)'
  CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,ZWORK(:,:),IRESP,HCOMMENT=YCOMMENT)
  !
  DO JPATCH=1,IO%NPATCH
    ZWORK(:,JPATCH) = DGEIPA%AL(JPATCH)%XRESP_ECO(:)
  ENDDO 
  IF (HTERM(1:1)=="C") THEN
    YRECFM='RC_ECO'//TRIM(HTERM(2:))
  ELSE
    YRECFM='R_ECO'//TRIM(HTERM)
  ENDIF  
  YCOMMENT='ecosystem respiration per patch (kgCO2/m2/s)'
  CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,ZWORK(:,:),IRESP,HCOMMENT=YCOMMENT)
  !
ENDIF
!
IF(DGI%DE%LWATER_BUDGET .OR. OFLAG)THEN 
  !
  DO JPATCH=1,IO%NPATCH
    ZWORK(:,JPATCH) = DGEIPA%AL(JPATCH)%XDWG(:)
  ENDDO  
  YRECFM='DWG'//TRIM(HTERM)
  YCOMMENT='change in liquid soil moisture per patch (Kg/m2/s)'
  CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,ZWORK(:,:),IRESP,HCOMMENT=YCOMMENT)
  !
  DO JPATCH=1,IO%NPATCH
    ZWORK(:,JPATCH) = DGEIPA%AL(JPATCH)%XDWGI(:)
  ENDDO  
  YRECFM='DWGI'//TRIM(HTERM)
  YCOMMENT='change in solid soil moisture per patch (Kg/m2/s)'
  CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,ZWORK(:,:),IRESP,HCOMMENT=YCOMMENT)
  !
  DO JPATCH=1,IO%NPATCH
    ZWORK(:,JPATCH) = DGEIPA%AL(JPATCH)%XDWR(:)
  ENDDO  
  YRECFM='DWR'//TRIM(HTERM)
  YCOMMENT='change in water on canopy per patch (Kg/m2/s)'
  CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,ZWORK(:,:),IRESP,HCOMMENT=YCOMMENT)
  !
  DO JPATCH=1,IO%NPATCH
    ZWORK(:,JPATCH) = DGEIPA%AL(JPATCH)%XDSWE(:)
  ENDDO  
  YRECFM='DSWE'//TRIM(HTERM)
  YCOMMENT='change in snow water equivalent per patch (Kg/m2/s)'
  CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,ZWORK(:,:),IRESP,HCOMMENT=YCOMMENT)
  !
  DO JPATCH=1,IO%NPATCH
    ZWORK(:,JPATCH) = DGEIPA%AL(JPATCH)%XWATBUD(:)
  ENDDO  
  YRECFM='WATBUD'//TRIM(HTERM)
  YCOMMENT='isba water budget as residue per patch (Kg/m2/s)'
  CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,ZWORK(:,:),IRESP,HCOMMENT=YCOMMENT)
  !
ENDIF
!    
DEALLOCATE(ZWORK)
!
IF (LHOOK) CALL DR_HOOK('WRITE_DIAG_SEB_ISBA_N:WRITE_EVAP_BUD_PATCH',1,ZHOOK_HANDLE)
!
END SUBROUTINE WRITE_EVAP_BUD_PATCH
!
!
SUBROUTINE PROVAR_TO_DIAG
!
REAL, DIMENSION(SIZE(IR%XTG,1))             :: ZPATCH, ZWORK
REAL, DIMENSION(SIZE(IR%XWG,1),SIZE(IR%XWG,2)) :: ZWG
REAL, DIMENSION(SIZE(IR%XWG,1),SIZE(IR%XWG,2)) :: ZWGI
REAL, DIMENSION(SIZE(IR%XTG,1),SIZE(IR%XTG,2)) :: ZTG
REAL, DIMENSION(SIZE(IMX%XDG,1),SIZE(IMX%XDG,2)) :: ZDG_TOT
REAL, DIMENSION(SIZE(IMX%XDG,1),SIZE(IMX%XDG,2),SIZE(IMX%XDG,3)) :: ZDG
!
REAL, DIMENSION(SIZE(IMX%XDG,1),IO%NNBIOMASS)   :: ZBIOMASS
REAL, DIMENSION(SIZE(IMX%XDG,1),IO%NNSOILCARB)  :: ZSOILCARB
REAL, DIMENSION(SIZE(IMX%XDG,1),IO%NNLITTLEVS)  :: ZLIGNIN_STRUC
REAL, DIMENSION(SIZE(IMX%XDG,1),IO%NNLITTER,IO%NNLITTLEVS)  :: ZLITTER
!
CHARACTER(LEN=4 ) :: YLVL
REAL              :: ZMISS
INTEGER           :: JLAYER, JPATCH, JJ, INI, IWORK, IDEPTH
!
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
IF (LHOOK) CALL DR_HOOK('WRITE_DIAG_SEB_ISBA_N:PROVAR_TO_DIAG',0,ZHOOK_HANDLE)
!
INI=SIZE(IMX%XDG,1)
!
! * soil temperatures (K)
!
IF(IO%LTEMP_ARP)THEN
  IWORK=IO%NTEMPLAYER_ARP
ELSEIF(IO%CISBA/='DIF')THEN
  IWORK=2
ELSE
  IWORK=IO%NGROUND_LAYER
ENDIF
!
ZTG(:,:)=0.0
DO JPATCH=1,IO%NPATCH
   DO JLAYER=1,IWORK
      DO JJ=1,INI 
         ZTG(JJ,JLAYER) = ZTG(JJ,JLAYER) + IP%XPATCH(JJ,JPATCH) * IR%XTG(JJ,JLAYER,JPATCH)
      ENDDO
   ENDDO
ENDDO
!
DO JLAYER=1,IWORK
  WRITE(YLVL,'(I4)') JLAYER
  YRECFM='TG'//ADJUSTL(YLVL(:LEN_TRIM(YLVL)))
  YRECFM=YRECFM(:LEN_TRIM(YRECFM))//'_ISBA'
  YCOMMENT='X_Y_'//YRECFM//' (K)'
  CALL WRITE_SURF(DUO%CSELECT,HPROGRAM,YRECFM,ZTG(:,JLAYER),IRESP,HCOMMENT=YCOMMENT)
END DO
!
! * Compute soil liquid and ice water content (kg/m2 and m3/m3) 
!
ZWG (:,:)=0.0
ZWGI(:,:)=0.0
ZDG_TOT(:,:)=0.0
!  
IF(IO%CISBA=='DIF')THEN
  !
  DO JPATCH=1,IO%NPATCH
     DO JLAYER=1,IO%NGROUND_LAYER
        DO JJ=1,INI 
!
!          liquid and ice water content
           IDEPTH=IMX%NWG_LAYER(JJ,JPATCH)
           IF(JLAYER<=IDEPTH)THEN    
             ZWG    (JJ,JLAYER)=ZWG    (JJ,JLAYER)+&
                     IP%XPATCH(JJ,JPATCH)*IR%XWG (JJ,JLAYER,JPATCH)*IP%XDZG(JJ,JLAYER,JPATCH)
             ZWGI   (JJ,JLAYER)=ZWGI   (JJ,JLAYER)+&
                     IP%XPATCH(JJ,JPATCH)*IR%XWGI(JJ,JLAYER,JPATCH)*IP%XDZG(JJ,JLAYER,JPATCH)
             ZDG_TOT(JJ,JLAYER)=ZDG_TOT(JJ,JLAYER)+&
                     IP%XPATCH(JJ,JPATCH)*IP%XDZG(JJ,JLAYER,JPATCH)
           ENDIF
!                      
        ENDDO
     ENDDO
  ENDDO
!  
ELSE
  !
  ZDG(:,1,:) = IMX%XDG(:,1,:)
  ZDG(:,2,:) = IMX%XDG(:,2,:)
  IF(IO%CISBA=='3-L')THEN
    ZDG(:,3,:) = IMX%XDG(:,3,:)-IMX%XDG(:,2,:)
  ENDIF
!
  DO JPATCH=1,IO%NPATCH
     DO JLAYER=1,IO%NGROUND_LAYER
        DO JJ=1,INI 
           ZWG    (JJ,JLAYER)=ZWG    (JJ,JLAYER)+&
                   IP%XPATCH(JJ,JPATCH)*IR%XWG (JJ,JLAYER,JPATCH)*ZDG(JJ,JLAYER,JPATCH)
           ZWGI   (JJ,JLAYER)=ZWGI   (JJ,JLAYER)+&
                   IP%XPATCH(JJ,JPATCH)*IR%XWGI(JJ,JLAYER,JPATCH)*ZDG(JJ,JLAYER,JPATCH)
           ZDG_TOT(JJ,JLAYER)=ZDG_TOT(JJ,JLAYER)+&
                   IP%XPATCH(JJ,JPATCH)*ZDG(JJ,JLAYER,JPATCH)
        ENDDO
     ENDDO
  ENDDO
!  
ENDIF
!
IF(HPROGRAM=='AROME '.OR.HPROGRAM=='FA    ')THEN
  ZMISS=0.0
ELSE
  ZMISS=XUNDEF
ENDIF
!
WHERE(ZDG_TOT(:,:)>0.0)
      ZWG   (:,:)=ZWG (:,:)/ZDG_TOT(:,:)
      ZWGI  (:,:)=ZWGI(:,:)/ZDG_TOT(:,:)
ELSEWHERE
      ZWG   (:,:)=ZMISS
      ZWGI  (:,:)=ZMISS    
ENDWHERE
!
! * soil liquid water content (m3/m3) and soil moisture (kg/m2)
!
DO JLAYER=1,IO%NGROUND_LAYER
  WRITE(YLVL,'(I4)') JLAYER
  YRECFM='WG'//ADJUSTL(YLVL(:LEN_TRIM(YLVL)))
  YRECFM=YRECFM(:LEN_TRIM(YRECFM))//'_ISBA'
  YCOMMENT='Soil liquid water content (m3/m3)' 
  CALL WRITE_SURF(DUO%CSELECT,HPROGRAM,YRECFM,ZWG(:,JLAYER),IRESP,HCOMMENT=YCOMMENT)
END DO
!
! * soil ice water content (m3/m3) and soil ice mass (kg/m2)
!
IWORK=IO%NGROUND_LAYER
IF(IO%CISBA/='DIF')THEN
  IWORK=2 ! No ice in the FR 3-layers
ENDIF
!
DO JLAYER=1,IWORK
  WRITE(YLVL,'(I4)') JLAYER
  YRECFM='WGI'//ADJUSTL(YLVL(:LEN_TRIM(YLVL)))
  YRECFM=YRECFM(:LEN_TRIM(YRECFM))//'_ISBA'
  YCOMMENT='Soil solid water content (m3/m3)' 
  CALL WRITE_SURF(DUO%CSELECT,HPROGRAM,YRECFM,ZWGI(:,JLAYER),IRESP,HCOMMENT=YCOMMENT) 
END DO   
!
! * water intercepted on leaves (kg/m2)
!
ZWORK(:)=0.0
DO JPATCH=1,IO%NPATCH
   DO JJ=1,INI 
      ZWORK(JJ) = ZWORK(JJ) + IP%XPATCH(JJ,JPATCH) * IR%XWR(JJ,JPATCH)
   ENDDO
ENDDO
!
YRECFM='WR_ISBA'
YCOMMENT='X_Y_'//YRECFM//' (kg/m2)'
CALL WRITE_SURF(DUO%CSELECT,HPROGRAM,YRECFM,ZWORK(:),IRESP,HCOMMENT=YCOMMENT)
!
! * Glacier ice storage (semi-prognostic) (kg/m2)
!
IF(IO%LGLACIER)THEN
  !
  ZWORK(:)=0.0
  DO JPATCH=1,IO%NPATCH
    DO JJ=1,INI 
       ZWORK(JJ) = ZWORK(JJ) + IP%XPATCH(JJ,JPATCH) * IR%XICE_STO(JJ,JPATCH)
    ENDDO    
  ENDDO    
  !
  YRECFM='ICE_STO_ISBA'
  YCOMMENT='X_Y_'//YRECFM//' (kg/m2)'
  CALL WRITE_SURF(DUO%CSELECT,HPROGRAM,YRECFM,ZWORK(:),IRESP,HCOMMENT=YCOMMENT)
  !
ENDIF
!
! * Snow albedo (-) 
!
ZPATCH(:) = 0.0
ZWORK (:) = 0.0
DO JPATCH=1,IO%NPATCH
   DO JJ=1,INI 
      IF(IR%TSNOW%ALB(JJ,JPATCH)/=XUNDEF)THEN
        ZWORK (JJ) = ZWORK (JJ) + IP%XPATCH(JJ,JPATCH) * IR%TSNOW%ALB(JJ,JPATCH)
        ZPATCH(JJ) = ZPATCH(JJ) + IP%XPATCH(JJ,JPATCH)
      ENDIF
   ENDDO
ENDDO
!
WHERE(ZPATCH(:)>0.0)
  ZWORK(:) = ZWORK(:) / ZPATCH(:)
ELSEWHERE
  ZWORK(:) = XUNDEF
ENDWHERE
!
YRECFM='ASN_ISBA'
YCOMMENT='X_Y_'//YRECFM//' (-)'
CALL WRITE_SURF(DUO%CSELECT,HPROGRAM,YRECFM,ZWORK(:),IRESP,HCOMMENT=YCOMMENT)
!  
IF(IR%TSNOW%SCHEME=='3-L' .OR. IR%TSNOW%SCHEME=='CRO')THEN
  !
  ! * Snow reservoir (kg/m2) by layer
  !
  DO JLAYER = 1,IR%TSNOW%NLAYER
    !
    ZWORK(:)=0.0
    DO JPATCH=1,IO%NPATCH
       DO JJ=1,INI 
          ZWORK(JJ) = ZWORK(JJ) + IP%XPATCH(JJ,JPATCH) * IR%TSNOW%WSNOW(JJ,JLAYER,JPATCH)
       ENDDO
    ENDDO
    !
    WRITE(YLVL,'(I4)') JLAYER
    YRECFM='WSN_'//ADJUSTL(YLVL(:LEN_TRIM(YLVL)))
    YRECFM=YRECFM(:LEN_TRIM(YRECFM))//'_ISBA'
    YCOMMENT='X_Y_'//YRECFM//' (kg/m2)'
    CALL WRITE_SURF(DUO%CSELECT,HPROGRAM,YRECFM,ZWORK(:),IRESP,HCOMMENT=YCOMMENT)
    !
  ENDDO
  !
  ! * Snow depth (m)
  !
  DO JLAYER = 1,IR%TSNOW%NLAYER
    !
    ZWORK(:)=0.0
    DO JPATCH=1,IO%NPATCH
       DO JJ=1,INI 
         ZWORK(JJ) = ZWORK(JJ) + &
                 IP%XPATCH(JJ,JPATCH) * IR%TSNOW%WSNOW(JJ,JLAYER,JPATCH)/IR%TSNOW%RHO(JJ,JLAYER,JPATCH)
       ENDDO
    ENDDO
    !
    WRITE(YLVL,'(I4)') JLAYER
    YRECFM='DSN_'//ADJUSTL(YLVL(:LEN_TRIM(YLVL)))
    YRECFM=YRECFM(:LEN_TRIM(YRECFM))//'_ISBA'
    YCOMMENT='X_Y_'//YRECFM//' (kg/m2)'
    CALL WRITE_SURF(DUO%CSELECT,HPROGRAM,YRECFM,ZWORK(:),IRESP,HCOMMENT=YCOMMENT)
    !
  ENDDO
  !
  ! * Snow temperature (k)
  !  
  IF(HPROGRAM=='AROME '.OR.HPROGRAM=='FA    ')THEN
    ZMISS=XTT
  ELSE
    ZMISS=XUNDEF
  ENDIF
  !  
  DO JLAYER = 1,IR%TSNOW%NLAYER
    !
    ZWORK (:) = 0.0
    ZPATCH(:) = 0.0
    DO JPATCH=1,IO%NPATCH
       DO JJ=1,INI 
          IF(IR%TSNOW%WSNOW(JJ,JLAYER,JPATCH)>0.)THEN
             ZWORK (JJ) = ZWORK (JJ) + IP%XPATCH(JJ,JPATCH) * IR%TSNOW%TEMP(JJ,JLAYER,JPATCH) 
             ZPATCH(JJ) = ZPATCH(JJ) + IP%XPATCH(JJ,JPATCH)
          ENDIF
       ENDDO
    ENDDO
    !
    WHERE(ZPATCH(:)>0.0)
      ZWORK(:) = ZWORK(:) / ZPATCH(:)
    ELSEWHERE
      ZWORK(:) = ZMISS
    ENDWHERE
    !
    WRITE(YLVL,'(I4)') JLAYER
    YRECFM='TSN_'//ADJUSTL(YLVL(:LEN_TRIM(YLVL)))
    YRECFM=YRECFM(:LEN_TRIM(YRECFM))//'_ISBA'
    YCOMMENT='X_Y_'//YRECFM//' (K)'
    CALL WRITE_SURF(DUO%CSELECT,HPROGRAM,YRECFM,ZWORK(:),IRESP,HCOMMENT=YCOMMENT)
    !
  ENDDO
  !
  ! * Snow age (day)
  !    
  DO JLAYER = 1,IR%TSNOW%NLAYER
    !
    ZWORK (:) = 0.0
    ZPATCH(:) = 0.0
    DO JPATCH=1,IO%NPATCH
       DO JJ=1,INI 
          IF(IR%TSNOW%WSNOW(JJ,JLAYER,JPATCH)>0.)THEN    
             ZWORK (JJ) = ZWORK (JJ) + IP%XPATCH(JJ,JPATCH) * IR%TSNOW%AGE(JJ,JLAYER,JPATCH) 
             ZPATCH(JJ) = ZPATCH(JJ) + IP%XPATCH(JJ,JPATCH)
          ENDIF
       ENDDO
    ENDDO
    !
    WHERE(ZPATCH(:)>0.0)
      ZWORK(:) = ZWORK(:) / ZPATCH(:)
    ENDWHERE
    !
    WRITE(YLVL,'(I4)') JLAYER
    YRECFM='AGSN_'//ADJUSTL(YLVL(:LEN_TRIM(YLVL)))
    YRECFM=YRECFM(:LEN_TRIM(YRECFM))//'_ISBA'
    YCOMMENT='X_Y_'//YRECFM//' (day_since_snowfall)'
    CALL WRITE_SURF(DUO%CSELECT,HPROGRAM,YRECFM,ZWORK(:),IRESP,HCOMMENT=YCOMMENT)
    !
  ENDDO
  !
ENDIF
!
! * Isba-Ags biomass reservoir
!
IF(IO%CPHOTO=='NIT'.OR.IO%CPHOTO=='NCB')THEN
!
  ZBIOMASS(:,:)=0.0
  DO JPATCH=1,IO%NPATCH
     DO JLAYER=1,IO%NNBIOMASS
        DO JJ=1,INI 
         ZBIOMASS(JJ,JLAYER) = ZBIOMASS(JJ,JLAYER) + IP%XPATCH(JJ,JPATCH) * IR%XBIOMASS(JJ,JLAYER,JPATCH)
        ENDDO
     ENDDO
  ENDDO
!
  DO JLAYER = 1,IO%NNBIOMASS
    WRITE(YLVL,'(I4)') JLAYER
    YRECFM='BIOM'//ADJUSTL(YLVL(:LEN_TRIM(YLVL)))
    YRECFM=YRECFM(:LEN_TRIM(YRECFM))//'_ISBA'
    YCOMMENT='X_Y_'//YRECFM//' (kgDM/m2)'
    CALL WRITE_SURF(DUO%CSELECT,HPROGRAM,YRECFM,ZBIOMASS(:,JLAYER),IRESP,HCOMMENT=YCOMMENT)  
  ENDDO
!
ENDIF
!
! * Isba-CC carbon reservoir
!
IF(IO%CRESPSL=='CNT')THEN
!
  ZLITTER(:,:,:)=0.0
  ZLIGNIN_STRUC(:,:)=0.0
  DO JPATCH=1,IO%NPATCH
     DO JLAYER=1,IO%NNLITTLEVS
       DO JJ=1,INI 
          ZLITTER(JJ,1,JLAYER) = ZLITTER(JJ,1,JLAYER) + &
                  IP%XPATCH(JJ,JPATCH) * IR%XLITTER(JJ,1,JLAYER,JPATCH)
          ZLITTER(JJ,2,JLAYER) = ZLITTER(JJ,2,JLAYER) + &
                  IP%XPATCH(JJ,JPATCH) * IR%XLITTER(JJ,2,JLAYER,JPATCH)
          ZLIGNIN_STRUC(JJ,JLAYER) = ZLIGNIN_STRUC(JJ,JLAYER) + &
                  IP%XPATCH(JJ,JPATCH) * IR%XLIGNIN_STRUC(JJ,JLAYER,JPATCH)
       ENDDO
    ENDDO
  ENDDO
!       
  DO JLAYER=1,IO%NNLITTLEVS
     WRITE(YLVL,'(I4)') JLAYER
     YRECFM='LIT1_'//ADJUSTL(YLVL(:LEN_TRIM(YLVL)))
     YRECFM=YRECFM(:LEN_TRIM(YRECFM))//'_ISBA'
     YCOMMENT='X_Y_'//YRECFM//' (gC/m2)'
     CALL WRITE_SURF(DUO%CSELECT,HPROGRAM,YRECFM,ZLITTER(:,1,JLAYER),IRESP,HCOMMENT=YCOMMENT)  
     WRITE(YLVL,'(I4)') JLAYER
     YRECFM='LIT2_'//ADJUSTL(YLVL(:LEN_TRIM(YLVL)))
     YRECFM=YRECFM(:LEN_TRIM(YRECFM))//'_ISBA'
     YCOMMENT='X_Y_'//YRECFM//' (gC/m2)'
     CALL WRITE_SURF(DUO%CSELECT, &
                  HPROGRAM,YRECFM,ZLITTER(:,2,JLAYER),IRESP,HCOMMENT=YCOMMENT)
     WRITE(YLVL,'(I4)') JLAYER
     YRECFM='LIGSTR'//ADJUSTL(YLVL(:LEN_TRIM(YLVL)))
     YRECFM=YRECFM(:LEN_TRIM(YRECFM))//'_ISBA'
     YCOMMENT='X_Y_'//YRECFM//' (-)'
     CALL WRITE_SURF(DUO%CSELECT,HPROGRAM,YRECFM,ZLIGNIN_STRUC(:,JLAYER),IRESP,HCOMMENT=YCOMMENT)      
  END DO
!
  ZSOILCARB(:,:)=0.0
  DO JPATCH=1,IO%NPATCH
     DO JLAYER=1,IO%NNSOILCARB
       DO JJ=1,INI 
          ZSOILCARB(JJ,JLAYER) = ZSOILCARB(JJ,JLAYER) + IP%XPATCH(JJ,JPATCH) * IR%XSOILCARB(JJ,JLAYER,JPATCH)
       ENDDO
    ENDDO
  ENDDO
!
  DO JLAYER = 1,IO%NNSOILCARB
    WRITE(YLVL,'(I4)') JLAYER
    YRECFM='SCARB'//ADJUSTL(YLVL(:LEN_TRIM(YLVL)))
    YRECFM=YRECFM(:LEN_TRIM(YRECFM))//'_ISBA'
    YCOMMENT='X_Y_'//YRECFM//' (gC/m2)'
    CALL WRITE_SURF(DUO%CSELECT, HPROGRAM,YRECFM,ZSOILCARB(:,JLAYER),IRESP,HCOMMENT=YCOMMENT)  
  ENDDO
!
ENDIF
!
IF (LHOOK) CALL DR_HOOK('WRITE_DIAG_SEB_ISBA_N:PROVAR_TO_DIAG',1,ZHOOK_HANDLE)
!
END SUBROUTINE PROVAR_TO_DIAG
!
END SUBROUTINE WRITE_DIAG_SEB_ISBA_n
