!     #########
      SUBROUTINE DEF_VAR_NETCDF(KFILE_ID,HNAME,HLONG_NAME,KDIM_ID,HATT_TITLE,HATT_TEXT)
!
USE MODD_OL_FILEID,      ONLY : XVAR_TO_FILEOUT, XOUT
USE MODD_DIAG_SURF_ATM_n,ONLY : LSELECT, CSELECT
USE MODD_SURF_PAR,       ONLY : XUNDEF
!
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE
INCLUDE "netcdf.inc"

INTEGER,               INTENT(IN) :: KFILE_ID
CHARACTER(LEN=*),      INTENT(IN) :: HNAME
CHARACTER(LEN=*),      INTENT(IN) :: HLONG_NAME
INTEGER, DIMENSION(:), INTENT(IN) :: KDIM_ID
CHARACTER(LEN=*),DIMENSION(:),OPTIONAL, INTENT(IN) :: HATT_TITLE,HATT_TEXT
!
! ** local variables
!
CHARACTER(LEN=50) :: YPAS
CHARACTER(LEN=20), DIMENSION(:), ALLOCATABLE :: XTEMP
INTEGER :: JRET,IVAR_ID,IATT,JATT,ILEN,INDIM
INTEGER, DIMENSION(4) :: IRET
REAL    :: ZAVG
INTEGER :: IFIELD,JFIELD
LOGICAL :: NOWRITE
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!--------------------------------------
!
IF (LHOOK) CALL DR_HOOK('DEF_VAR_NETCDF',0,ZHOOK_HANDLE)
XOUT=XOUT+1
ALLOCATE(XTEMP(XOUT))
XTEMP(XOUT)=HNAME
IF (XOUT.GT.1) XTEMP(1:XOUT-1)=XVAR_TO_FILEOUT
!
DEALLOCATE(XVAR_TO_FILEOUT)
ALLOCATE(XVAR_TO_FILEOUT(XOUT))
XVAR_TO_FILEOUT=XTEMP
!
DEALLOCATE(XTEMP)
!
! if output fields selection is active, test if this field is to be written
IF ( HNAME/='xx'  .AND. HNAME/='yy' .AND. HNAME/='lon' .AND. &
     HNAME/='lat' .AND. LSELECT )  THEN
  IFIELD=COUNT(CSELECT /= '            ')
  NOWRITE=.TRUE.
  DO JFIELD=1,IFIELD
    IF ( TRIM(CSELECT(JFIELD))==TRIM(HNAME) ) THEN
      NOWRITE=.FALSE.
    ENDIF
  ENDDO
  IF ( NOWRITE  .AND. LHOOK) CALL DR_HOOK('DEF_VAR_NETCDF',1,ZHOOK_HANDLE)
  IF ( NOWRITE ) RETURN
ENDIF
!
! define mode
JRET=NF_REDEF(KFILE_ID)

!define variables in the netcdf file
INDIM=SIZE(KDIM_ID)
!
IRET(1) = NF_DEF_VAR      (KFILE_ID,HNAME,NF_DOUBLE,INDIM,KDIM_ID,IVAR_ID)
IRET(2) = NF_PUT_ATT_DOUBLE (KFILE_ID,IVAR_ID,'_FillValue',NF_DOUBLE,1,XUNDEF)
IF (HLONG_NAME.NE.'') IRET(2) = NF_PUT_ATT_TEXT (KFILE_ID,IVAR_ID,'long_name',LEN_TRIM(HLONG_NAME),HLONG_NAME)
! 
!Write optional attribute
IF (PRESENT(HATT_TITLE).AND.PRESENT(HATT_TEXT)) THEN  
  IATT=SIZE(HATT_TITLE)
  IF (IATT .EQ. SIZE(HATT_TEXT)) THEN
    DO JATT=1,IATT
      ILEN=LEN_TRIM(HATT_TEXT(JATT))
      YPAS=HATT_TEXT(JATT)
      JRET = NF_PUT_ATT_TEXT (KFILE_ID,IVAR_ID,HATT_TITLE(JATT),ILEN,HATT_TEXT(JATT))
    ENDDO
  ENDIF
ENDIF
!
! end define mode
IRET(3)=NF_ENDDEF(KFILE_ID)
!
IF (LHOOK) CALL DR_HOOK('DEF_VAR_NETCDF',1,ZHOOK_HANDLE)
!
END SUBROUTINE DEF_VAR_NETCDF
