SUBROUTINE ERROR_WRITE_SURF_LFI(HREC,KRESP)
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
!
USE MODD_IO_SURF_LFI, ONLY : NLUOUT
!
 CHARACTER(LEN=*), INTENT(IN):: HREC
INTEGER,          INTENT(IN):: KRESP
REAL(KIND=JPRB) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('MODI_ERROR_WRITE_SURF_LFI:ERROR_WRITE_SURF_LFI',0,ZHOOK_HANDLE)
IF (KRESP==0 .AND. LHOOK) CALL DR_HOOK('MODI_ERROR_WRITE_SURF_LFI:ERROR_WRITE_SURF_LFI',1,ZHOOK_HANDLE)
IF (KRESP==0) RETURN
!
WRITE(NLUOUT,*) ' '
WRITE(NLUOUT,*) 'WARNING'
WRITE(NLUOUT,*) '-------'
WRITE(NLUOUT,*) ' '
WRITE(NLUOUT,*) 'error when writing article', HREC
WRITE(NLUOUT,*) 'KRESP = ', KRESP
WRITE(NLUOUT,*) ' '
IF (LHOOK) CALL DR_HOOK('MODI_ERROR_WRITE_SURF_LFI:ERROR_WRITE_SURF_LFI',1,ZHOOK_HANDLE)

END SUBROUTINE ERROR_WRITE_SURF_LFI
