SUBROUTINE GET_SIZES_PARALLEL(PIO_FRAC,KPROC,KPIO,KSIZE,KSIZE_TASK)
!
USE MODD_SURFEX_MPI, ONLY : WLOG_MPI
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE
!
REAL, INTENT(IN) :: PIO_FRAC
INTEGER, INTENT(IN) :: KPROC
INTEGER, INTENT(IN) :: KPIO
INTEGER, INTENT(IN) :: KSIZE
INTEGER, DIMENSION(0:KPROC-1), INTENT(OUT) :: KSIZE_TASK
!
INTEGER :: ISIZE, IRESTE, INRESTE
INTEGER :: J, IPROC
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
IF (LHOOK) CALL DR_HOOK('GET_SIZES_PARALLEL',0,ZHOOK_HANDLE)
!
ISIZE = CEILING(KSIZE*1./(KPROC-1.+PIO_FRAC)) !nb of points by task
!
IRESTE = KSIZE - (ISIZE * (KPROC-1)) ! nb of points for task 0
!
IF (IRESTE<=0 .AND. PIO_FRAC/=0.) THEN
  IRESTE = ISIZE - 1
  INRESTE = KPROC*ISIZE - KSIZE !nb of tasks containing ireste points
ELSE
  INRESTE = 1
ENDIF
!
KSIZE_TASK(:) = ISIZE
DO J = KPIO,KPIO+INRESTE-1
  KSIZE_TASK(MOD(J,KPROC)) = IRESTE
ENDDO
!
IF (KPROC>1 .AND. PIO_FRAC/=1.) THEN
  !
  IPROC = KPIO
  DO WHILE( KSIZE_TASK(KPIO) > NINT(PIO_FRAC*ISIZE) )
    KSIZE_TASK(KPIO) = KSIZE_TASK(KPIO)-1
    IPROC = IPROC+1
    IF (MOD(IPROC,KPROC)==KPIO) ISIZE = ISIZE+1
    KSIZE_TASK(MOD(IPROC,KPROC)) = KSIZE_TASK(MOD(IPROC,KPROC))+1
  END DO 
  !
  IPROC = KPIO
  DO WHILE( KSIZE_TASK(KPIO) < NINT(PIO_FRAC*ISIZE) )
    KSIZE_TASK(KPIO) = KSIZE_TASK(KPIO)+1
    IPROC = IPROC+1
    IF (MOD(IPROC,KPROC)==KPIO) ISIZE = ISIZE-1
    KSIZE_TASK(MOD(IPROC,KPROC)) = KSIZE_TASK(MOD(IPROC,KPROC))-1
  END DO       
  !
ENDIF
!
!so:
!(nproc-nreste)*isize + nreste*ireste = 
!if nreste==1: 
!(nproc-1)*isize + ireste = 
!(nproc-1)*isize + NDIM_FULL - (nproc-1)*isize = NDIM_FULL
!if (ireste==isize-1):
!nproc*isize - nreste*isize + nreste*isize - nerste = 
!nproc*isize - nreste = NDIM_FULL
!
IF (LHOOK) CALL DR_HOOK('GET_SIZES_PARALLEL',1,ZHOOK_HANDLE)
!
END SUBROUTINE GET_SIZES_PARALLEL
