!     #########
      SUBROUTINE INIT_IO_SURF_OL_n (BOP, CHE, CHI, CHS, CHN, CHU, CHT, CHW, &
                                    DTCO, DGEI, DGF, DGI, DGMI, DGMTO, DGO, DGS, DGSI, DGU, DGT, DGUT, DGW, &
                                    F, FSB, GB, IOB, ICP, I, O, S, SSB, UG, U, SV, &
                                    TCP, TGD, TGDO, TGR, TGRO, T, TOP, TVG, W, WSB, &
                                    HPROGRAM,HMASK,HSCHEME,HACTION)
!     ######################
!
!!****  *INIT_IO_SURF_OL* Keep in memory the netcdf ID of the output files
!!
!!    PURPOSE
!!    -------
!
!!
!!**  IMPLICIT ARGUMENTS
!!    ------------------
!!      None 
!!
!!    REFERENCE
!!    ---------
!!
!!    AUTHOR
!!    ------
!!      F. Habets   *Meteo France*
!!
!!    MODIFICATIONS
!!    -------------
!!      modified 05/04 by P. LeMoigne *Meteo France*
!!      modified 06/10 by S. Faroux *Meteo France*
!!=================================================================
!
!*       0.   DECLARATIONS
!             ------------
!
USE MODD_BEM_OPTION_n, ONLY : BEM_OPTIONS_t
USE MODD_CH_EMIS_FIELD_n, ONLY : CH_EMIS_FIELD_t
USE MODD_CH_ISBA_n, ONLY : CH_ISBA_t
USE MODD_CH_SEAFLUX_n, ONLY : CH_SEAFLUX_t
USE MODD_CH_SNAP_n, ONLY : CH_EMIS_SNAP_t
USE MODD_CH_SURF_n, ONLY : CH_SURF_t
USE MODD_CH_TEB_n, ONLY : CH_TEB_t
USE MODD_CH_WATFLUX_n, ONLY : CH_WATFLUX_t
USE MODD_DATA_COVER_n, ONLY : DATA_COVER_t
USE MODD_DIAG_EVAP_ISBA_n, ONLY : DIAG_EVAP_ISBA_t
USE MODD_DIAG_FLAKE_n, ONLY : DIAG_FLAKE_t
USE MODD_DIAG_ISBA_n, ONLY : DIAG_ISBA_t
USE MODD_DIAG_MISC_ISBA_n, ONLY : DIAG_MISC_ISBA_t
USE MODD_DIAG_MISC_TEB_OPTION_n, ONLY : DIAG_MISC_TEB_OPTIONS_t
USE MODD_DIAG_OCEAN_n, ONLY : DIAG_OCEAN_t
USE MODD_DIAG_SEAFLUX_n, ONLY : DIAG_SEAFLUX_t
USE MODD_DIAG_SEAICE_n, ONLY : DIAG_SEAICE_t
USE MODD_DIAG_SURF_ATM_n, ONLY : DIAG_SURF_ATM_t
USE MODD_DIAG_TEB_n, ONLY : DIAG_TEB_t
USE MODD_DIAG_UTCI_TEB_n, ONLY : DIAG_UTCI_TEB_t
USE MODD_DIAG_WATFLUX_n, ONLY : DIAG_WATFLUX_t
USE MODD_FLAKE_n, ONLY : FLAKE_t
USE MODD_FLAKE_SBL_n, ONLY : FLAKE_SBL_t
USE MODD_GR_BIOG_n, ONLY : GR_BIOG_t
USE MODD_IO_BUFF_n, ONLY : IO_BUFF_t
USE MODD_ISBA_CANOPY_n, ONLY : ISBA_CANOPY_t
USE MODD_ISBA_n, ONLY : ISBA_t
USE MODD_OCEAN_n, ONLY : OCEAN_t
USE MODD_SEAFLUX_n, ONLY : SEAFLUX_t
USE MODD_SEAFLUX_SBL_n, ONLY : SEAFLUX_SBL_t
USE MODD_SURF_ATM_GRID_n, ONLY : SURF_ATM_GRID_t
USE MODD_SURF_ATM_n, ONLY : SURF_ATM_t
USE MODD_SV_n, ONLY : SV_t
USE MODD_TEB_CANOPY_n, ONLY : TEB_CANOPY_t
USE MODD_TEB_GARDEN_n, ONLY : TEB_GARDEN_t
USE MODD_TEB_GARDEN_OPTION_n, ONLY : TEB_GARDEN_OPTIONS_t
USE MODD_TEB_GREENROOF_n, ONLY : TEB_GREENROOF_t
USE MODD_TEB_GREENROOF_OPTION_n, ONLY : TEB_GREENROOF_OPTIONS_t
USE MODD_TEB_n, ONLY : TEB_t
USE MODD_TEB_OPTION_n, ONLY : TEB_OPTIONS_t
USE MODD_TEB_VEG_n, ONLY : TEB_VEG_OPTIONS_t
USE MODD_WATFLUX_n, ONLY : WATFLUX_t
USE MODD_WATFLUX_SBL_n, ONLY : WATFLUX_SBL_t
!
USE MODD_OL_FILEID, ONLY : XVAR_TO_FILEOUT,         &
                           XID, XOUT,               &
                           XVAR_SURF, XID_SURF,     &
                           XVAR_NATURE, XID_NATURE, &
                           XVAR_SEA, XID_SEA,       &
                           XVAR_WATER, XID_WATER,   &
                           XVAR_TOWN, XID_TOWN  
USE MODD_IO_SURF_OL
!
USE MODD_SURFEX_MPI, ONLY : NRANK, NPIO
!
USE MODN_IO_OFFLINE,    ONLY : XTSTEP_OUTPUT
!
USE MODI_GET_LUOUT
USE MODI_READ_SURF
USE MODI_GET_DIM_FULL_n
USE MODI_GET_SIZE_FULL_n
USE MODI_GET_TYPE_DIM_n
USE MODI_INIT_IO_SURF_MASK_n
USE MODI_INIT_OUTFN_FLAKE_n
USE MODI_INIT_OUTFN_ISBA_n
USE MODI_INIT_OUTFN_SEA_n
USE MODI_INIT_OUTFN_SURF_ATM_n
USE MODI_INIT_OUTFN_TEB_n
USE MODI_INIT_OUTFN_WATER_n
USE MODI_WRITE_SURF
!
USE MODD_SURFEX_MPI, ONLY : WLOG_MPI
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE
!
!
TYPE(BEM_OPTIONS_t), INTENT(INOUT) :: BOP
TYPE(CH_EMIS_FIELD_t), INTENT(INOUT) :: CHE
TYPE(CH_ISBA_t), INTENT(INOUT) :: CHI
TYPE(CH_SEAFLUX_t), INTENT(INOUT) :: CHS
TYPE(CH_EMIS_SNAP_t), INTENT(INOUT) :: CHN
TYPE(CH_SURF_t), INTENT(INOUT) :: CHU
TYPE(CH_TEB_t), INTENT(INOUT) :: CHT
TYPE(CH_WATFLUX_t), INTENT(INOUT) :: CHW
TYPE(DATA_COVER_t), INTENT(INOUT) :: DTCO
TYPE(DIAG_EVAP_ISBA_t), INTENT(INOUT) :: DGEI
TYPE(DIAG_FLAKE_t), INTENT(INOUT) :: DGF
TYPE(DIAG_ISBA_t), INTENT(INOUT) :: DGI
TYPE(DIAG_MISC_ISBA_t), INTENT(INOUT) :: DGMI
TYPE(DIAG_MISC_TEB_OPTIONS_t), INTENT(INOUT) :: DGMTO
TYPE(DIAG_OCEAN_t), INTENT(INOUT) :: DGO
TYPE(DIAG_SEAFLUX_t), INTENT(INOUT) :: DGS
TYPE(DIAG_SEAICE_t), INTENT(INOUT) :: DGSI
TYPE(DIAG_SURF_ATM_t), INTENT(INOUT) :: DGU
TYPE(DIAG_TEB_t), INTENT(INOUT) :: DGT
TYPE(DIAG_UTCI_TEB_t), INTENT(INOUT) :: DGUT
TYPE(DIAG_WATFLUX_t), INTENT(INOUT) :: DGW
TYPE(FLAKE_t), INTENT(INOUT) :: F
TYPE(FLAKE_SBL_t), INTENT(INOUT) :: FSB
TYPE(GR_BIOG_t), INTENT(INOUT) :: GB
TYPE(IO_BUFF_t), INTENT(INOUT) :: IOB
TYPE(ISBA_CANOPY_t), INTENT(INOUT) :: ICP
TYPE(ISBA_t), INTENT(INOUT) :: I
TYPE(OCEAN_t), INTENT(INOUT) :: O
TYPE(SEAFLUX_t), INTENT(INOUT) :: S
TYPE(SEAFLUX_SBL_t), INTENT(INOUT) :: SSB
TYPE(SURF_ATM_GRID_t), INTENT(INOUT) :: UG
TYPE(SURF_ATM_t), INTENT(INOUT) :: U
TYPE(SV_t), INTENT(INOUT) :: SV
TYPE(TEB_CANOPY_t), INTENT(INOUT) :: TCP
TYPE(TEB_GARDEN_t), INTENT(INOUT) :: TGD
TYPE(TEB_GARDEN_OPTIONS_t), INTENT(INOUT) :: TGDO
TYPE(TEB_GREENROOF_t), INTENT(INOUT) :: TGR
TYPE(TEB_GREENROOF_OPTIONS_t), INTENT(INOUT) :: TGRO
TYPE(TEB_t), INTENT(INOUT) :: T
TYPE(TEB_OPTIONS_t), INTENT(INOUT) :: TOP
TYPE(TEB_VEG_OPTIONS_t), INTENT(INOUT) :: TVG
TYPE(WATFLUX_t), INTENT(INOUT) :: W
TYPE(WATFLUX_SBL_t), INTENT(INOUT) :: WSB
!
 CHARACTER(LEN=6),  INTENT(IN)  :: HPROGRAM 
 CHARACTER(LEN=6),  INTENT(IN)  :: HMASK    
 CHARACTER(LEN=6),  INTENT(IN)  :: HSCHEME 
 CHARACTER(LEN=5),  INTENT(IN)  :: HACTION 
!
REAL              :: ZDEN
INTEGER           :: IRESP          ! IRESP  : return-code if a problem appears
 CHARACTER(LEN=100):: YCOMMENT       ! Comment string
INTEGER           :: ILU,IRET, IL, IFULL
INTEGER           :: ILUOUT
REAL(KIND=JPRB)  :: ZHOOK_HANDLE
!------------------------------------------------------------------------------ 
IF (LHOOK) CALL DR_HOOK('INIT_IO_SURF_OL_N',0,ZHOOK_HANDLE)
!
LMASK = .TRUE.
!
 CALL GET_LUOUT(HPROGRAM,ILUOUT)
!
!$OMP BARRIER
!
IF (HACTION=='READ') THEN
  CALL READ_SURF(IOB, &
                 'OFFLIN','DIM_FULL',IFULL,IRET)
ELSE 
  CALL GET_DIM_FULL_n(U, &
                      IFULL)
ENDIF
!
! size by MPI task. NINDEX is supposed to be initialized at this step.  
 CALL GET_SIZE_FULL_n(U, &
                      'OFFLIN',IFULL,ILU)
!
IL = ILU
 CALL GET_TYPE_DIM_n(DTCO, U, &
                     HMASK,IL)
 CALL INIT_IO_SURF_MASK_n(DTCO, U, &
                          HMASK, IL, ILUOUT, ILU, NMASK)
!
IF (HACTION=='READ' .AND. LHOOK) CALL DR_HOOK('INIT_IO_SURF_OL_N',1,ZHOOK_HANDLE)
IF (HACTION=='READ') RETURN
!
IF (NRANK==NPIO) THEN
  !
!$OMP SINGLE 
  !
  IF (.NOT. LDEFINED_SURF_ATM) THEN         
    CALL INIT_OUTFN_SURF_ATM_n(CHE, CHN, CHU, DGU, UG, U, SV, &
                               HPROGRAM,ILUOUT)
    CALL ALLOCATE_FILL_VAR(XVAR_SURF, XID_SURF)
    LDEFINED_SURF_ATM=.TRUE.
  ENDIF
  !
  IF (HMASK=='NATURE' .AND. .NOT. LDEFINED_NATURE) THEN
    IF (HSCHEME=='ISBA  ') THEN 
      CALL INIT_OUTFN_ISBA_n(CHI, DGEI, DGI, DGMI, DGU, GB, ICP, I, UG, U, &
                             HPROGRAM,ILUOUT)
      CALL ALLOCATE_FILL_VAR(XVAR_NATURE, XID_NATURE)
    ENDIF
    LDEFINED_NATURE=.TRUE.
  ENDIF
  !
  IF (HMASK=='SEA   ' .AND. .NOT. LDEFINED_SEA) THEN
    IF (HSCHEME=='SEAFLX') THEN 
      CALL INIT_OUTFN_SEA_n(CHS, DGO, DGS, DGSI, DGU, O, S, SSB, UG, U, &
                            HPROGRAM,ILUOUT)
      CALL ALLOCATE_FILL_VAR(XVAR_SEA, XID_SEA)
    ENDIF
    LDEFINED_SEA=.TRUE.
  ENDIF
  !
  IF (HMASK=='WATER ' .AND. .NOT. LDEFINED_WATER) THEN
    IF (HSCHEME=='WATFLX') CALL INIT_OUTFN_WATER_n(CHW, DGU, DGW, UG, U, W, WSB, &
                                                   HPROGRAM,ILUOUT)
    IF (HSCHEME=='FLAKE ') CALL INIT_OUTFN_FLAKE_n(CHW, DGF, DGU, F, FSB, UG, U, &
                                                   HPROGRAM,ILUOUT)
    IF (HSCHEME=='WATFLX' .OR. HSCHEME=='FLAKE') CALL ALLOCATE_FILL_VAR(XVAR_WATER, XID_WATER)
    LDEFINED_WATER=.TRUE.
  ENDIF
  !
  IF (HMASK=='TOWN  ' .AND. .NOT. LDEFINED_TOWN) THEN
    IF (HSCHEME=='TEB   ') THEN 
      CALL INIT_OUTFN_TEB_n(BOP, CHT, DGMTO, DGU, DGT, DGUT, UG, U, TCP, TGD, TGDO, TGR, TGRO, T, TOP, TVG, &
                            HPROGRAM,ILUOUT)
      CALL ALLOCATE_FILL_VAR(XVAR_TOWN, XID_TOWN)
    ENDIF
    LDEFINED_TOWN=.TRUE.
  ENDIF
  !
!$OMP END SINGLE
  !  
  YCOMMENT=''
  !
  IF (XTSTEP_OUTPUT == FLOOR(XTSTEP_OUTPUT/86400.)*86400) THEN 
    ZDEN = 86400.
  ELSEIF (XTSTEP_OUTPUT == FLOOR(XTSTEP_OUTPUT/3600.)*3600) THEN
    ZDEN = 3600.
  ELSEIF (XTSTEP_OUTPUT == FLOOR(XTSTEP_OUTPUT/60.)*60) THEN
    ZDEN = 60.
  ELSE
    ZDEN = 1.
  ENDIF
  !
  IF (.NOT.LTIME_WRITTEN(1)) THEN 
    XTYPE=1
    CALL WRITE_SURF(DGU, IOB, U, &
                    HPROGRAM,'time',XTSTEP_OUTPUT/ZDEN*XSTARTW,IRESP,HCOMMENT=YCOMMENT)
    LTIME_WRITTEN(1)=.TRUE.
  ENDIF
  !
  IF (HSCHEME.NE.'NONE  ') THEN
    !
    IF (HMASK=='NATURE' .AND. .NOT.LTIME_WRITTEN(2)) THEN
      XTYPE=2
      CALL WRITE_SURF(DGU, IOB, U, &
                    HPROGRAM,'time',XTSTEP_OUTPUT/ZDEN*XSTARTW,IRESP,HCOMMENT=YCOMMENT)
      LTIME_WRITTEN(2)=.TRUE.
    ENDIF
    !
    IF (HMASK=='SEA   ' .AND. .NOT.LTIME_WRITTEN(3)) THEN
      XTYPE=3
      CALL WRITE_SURF(DGU, IOB, U, &
                    HPROGRAM,'time',XTSTEP_OUTPUT/ZDEN*XSTARTW,IRESP,HCOMMENT=YCOMMENT)
      LTIME_WRITTEN(3)=.TRUE.
    ENDIF
    !
    IF (HMASK=='WATER ' .AND.  .NOT.LTIME_WRITTEN(4)) THEN  
      XTYPE=4
      CALL WRITE_SURF(DGU, IOB, U, &
                    HPROGRAM,'time',XTSTEP_OUTPUT/ZDEN*XSTARTW,IRESP,HCOMMENT=YCOMMENT)
      LTIME_WRITTEN(4)=.TRUE.
    ENDIF
    !
    IF (HMASK=='TOWN  ' .AND. .NOT.LTIME_WRITTEN(5)) THEN     
      XTYPE=5
      CALL WRITE_SURF(DGU, IOB, U, &
                    HPROGRAM,'time',XTSTEP_OUTPUT/ZDEN*XSTARTW,IRESP,HCOMMENT=YCOMMENT)
      LTIME_WRITTEN(5)=.TRUE.
    ENDIF
    !
  ENDIF
  !
ENDIF
!
!------------------------------------------------------------------------------
IF (LHOOK) CALL DR_HOOK('INIT_IO_SURF_OL_N',1,ZHOOK_HANDLE)
CONTAINS 
!------------------------------------------------------------------------------
SUBROUTINE ALLOCATE_FILL_VAR(HVAR, NVAR)
  
 CHARACTER(LEN=20),DIMENSION(:), POINTER :: HVAR
INTEGER*4, DIMENSION(:), POINTER :: NVAR
REAL(KIND=JPRB) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('ALLOCATE_FILL_VAR',0,ZHOOK_HANDLE)
ALLOCATE(HVAR(XOUT))
ALLOCATE(NVAR(XOUT))
HVAR(:)=XVAR_TO_FILEOUT(1:XOUT)
NVAR(:)=XID(1:XOUT)
IF (LHOOK) CALL DR_HOOK('ALLOCATE_FILL_VAR',1,ZHOOK_HANDLE)

END SUBROUTINE ALLOCATE_FILL_VAR
!------------------------------------------------------------------------------
!
END SUBROUTINE INIT_IO_SURF_OL_n
