SUBROUTINE INIT_INDEX_MPI (YSC, HPROGRAM,HINIT,HALG,PIO_FRAC,OSHADOWS)
!
! 04-2014 : Modifs Matthieu Lafaysse for shadows :
!        * OSHADOWS logical to pass to get_sizes_parallel
!        * disactivate the treatments relative to PIO_FRAC in case of shadows
!        * MPI_BCAST of NIX and NIY
!
USE MODD_SURFEX_n, ONLY : SURFEX_t
!
USE MODD_SURFEX_MPI, ONLY : NRANK, NPIO, NPROC, NCOMM, NINDEX, NSIZE_TASK, NSIZE, WLOG_MPI, &
                            NREQ, NNUM, NDIM_FULL_INIT
!
USE MODN_IO_OFFLINE, ONLY : LLAND_USE
!
USE MODD_SURF_CONF,       ONLY : CPROGNAME
USE MODD_MASK, ONLY : NMASK_FULL
!
USE MODD_SLOPE_EFFECT, ONLY : NIX,NIY
!
USE MODE_READ_SURF_COV, ONLY : READ_SURF_COV
!
USE MODI_INI_CSTS
USE MODI_PGD_GRID
USE MODI_GET_LUOUT
USE MODI_SET_SURFEX_FILEIN
USE MODI_INIT_IO_SURF_n
USE MODI_READ_SURF
USE MODI_READ_GRIDTYPE
USE MODI_END_IO_SURF_n
USE MODI_ABOR1_SFX
USE MODI_GET_SIZES_PARALLEL
USE MODI_GET_ADJACENT_MESHES
USE MODI_INI_DATA_COVER
USE MODI_READ_ARRANGE_COVER
USE MODI_READ_COVER_GARDEN
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE
!
#ifdef SFX_MPI
INCLUDE "mpif.h"
#endif
!
!
TYPE(SURFEX_t), INTENT(INOUT) :: YSC
!
 CHARACTER(LEN=6), INTENT(IN) :: HPROGRAM
 CHARACTER(LEN=3), INTENT(IN) :: HINIT 
 CHARACTER(LEN=4), INTENT(IN) :: HALG
REAL, INTENT(IN) :: PIO_FRAC
LOGICAL, INTENT(IN), OPTIONAL :: OSHADOWS
!
INTEGER, DIMENSION(:), ALLOCATABLE :: ILEFT   ! index of left   grid mesh 
INTEGER, DIMENSION(:), ALLOCATABLE :: IRIGHT  ! index of right  grid mesh 
INTEGER, DIMENSION(:), ALLOCATABLE :: ITOP    ! index of top    grid mesh 
INTEGER, DIMENSION(:), ALLOCATABLE :: IBOTTOM ! index of bottom grid mesh
!
INTEGER, DIMENSION(0:NPROC-1) :: INB
LOGICAL :: GSHADOWS
INTEGER, DIMENSION(0:NPROC-1) :: INBPTS
INTEGER :: IRESTE, INRESTE, IRANK, IPROC
INTEGER :: JJ, CPT, ILUOUT, INBMIN, IP0
INTEGER :: IRESP, INFOMPI
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
IF (LHOOK) CALL DR_HOOK('INIT_INDEX_MPI',0,ZHOOK_HANDLE)
!
ALLOCATE(NREQ((NPROC-1)*2))
!
IF (PRESENT(OSHADOWS)) THEN
  GSHADOWS = OSHADOWS
ELSE
  GSHADOWS = .FALSE.
ENDIF
!
IF ( NRANK==NPIO ) THEN
  !
  CALL GET_LUOUT(HPROGRAM,ILUOUT)
  !
  !*    1. Parameters of the grid
  !
  IF (HINIT=='PGD') THEN
    !
    CPROGNAME=HPROGRAM
    !
    CALL INI_CSTS
    !
    CALL PGD_GRID (YSC%UG, YSC%U%NDIM_FULL, HPROGRAM,'                            ','      ',&
                   .FALSE.,'A')
    !
  ELSE
    !
    CALL SET_SURFEX_FILEIN(HPROGRAM,'PGD ')
    CALL INIT_IO_SURF_n(YSC%DTCO, YSC%U, HPROGRAM,'FULL  ','SURF  ','READ ')
    !
    CALL READ_SURF(HPROGRAM,'DIM_FULL  ',YSC%U%NDIM_FULL,IRESP,HDIR='A')
    !
    CALL READ_ARRANGE_COVER(HPROGRAM,YSC%U%LWATER_TO_NATURE,YSC%U%LTOWN_TO_ROCK,'A')
    CALL READ_COVER_GARDEN(HPROGRAM,YSC%U%LGARDEN,'A')
    !
    CALL END_IO_SURF_n(HPROGRAM)
    DEALLOCATE(NMASK_FULL)
    !
    CALL SET_SURFEX_FILEIN(HPROGRAM,'PGD ') ! change input file name to pgd name
    CALL INIT_IO_SURF_n(YSC%DTCO, YSC%U, HPROGRAM,'FULL  ','SURF  ','READ ')
    !
    CALL READ_SURF(HPROGRAM,'GRID_TYPE',YSC%UG%G%CGRID,IRESP,HDIR='A')
    !
    CALL READ_GRIDTYPE(HPROGRAM,YSC%UG%G%CGRID,YSC%UG%NGRID_FULL_PAR,YSC%U%NDIM_FULL,.FALSE.,HDIR='A')
    !
    ALLOCATE(YSC%UG%XGRID_FULL_PAR(YSC%UG%NGRID_FULL_PAR))
    !
    CALL READ_GRIDTYPE(HPROGRAM,YSC%UG%G%CGRID,YSC%UG%NGRID_FULL_PAR,YSC%U%NDIM_FULL,.TRUE.,&
                       YSC%UG%XGRID_FULL_PAR,IRESP,HDIR='A')
    !
    !
    CALL END_IO_SURF_n(HPROGRAM)
    !
  ENDIF
  ! 
  NSIZE = YSC%U%NDIM_FULL
  !
ELSE
  YSC%U%NDIM_FULL = 0
ENDIF
!
IF (NPROC>1) THEN
#ifdef SFX_MPI
  IF (HINIT=='PGD' .OR. (HINIT=='OFF'.AND.LLAND_USE)) THEN
    CALL MPI_BCAST(YSC%UG%NGRID_FULL_PAR,KIND(YSC%UG%NGRID_FULL_PAR)/4,MPI_INTEGER,NPIO,NCOMM,INFOMPI)
    IF (NRANK/=NPIO) ALLOCATE(YSC%UG%XGRID_FULL_PAR(YSC%UG%NGRID_FULL_PAR))
    CALL MPI_BCAST(YSC%UG%XGRID_FULL_PAR,&
      SIZE(YSC%UG%XGRID_FULL_PAR)*KIND(YSC%UG%XGRID_FULL_PAR)/4,MPI_REAL,NPIO,NCOMM,INFOMPI)
  ENDIF
  CALL MPI_BCAST(YSC%U%NDIM_FULL,KIND(YSC%U%NDIM_FULL)/4,MPI_INTEGER,NPIO,NCOMM,INFOMPI)
#endif
ENDIF
!
NDIM_FULL_INIT = YSC%U%NDIM_FULL
!
!*     3. Points by task
!
IF (NRANK==NPIO .OR. HINIT=='PGD' .OR. (HINIT=='OFF' .AND. LLAND_USE)) THEN
  IF (.NOT.ALLOCATED(NINDEX)) ALLOCATE(NINDEX(YSC%U%NDIM_FULL))
  NINDEX(:) = -1
ELSEIF (.NOT.ALLOCATED(NINDEX)) THEN
  ALLOCATE(NINDEX(0))
ENDIF
!
IF (HALG=='LIN ') THEN
  !
  IF (NRANK==NPIO) CALL SET_NB_POINTS_LIN(NPROC,NPROC-1,YSC%U%NDIM_FULL,NINDEX,OSHADOWS)
  !
ELSEIF (HALG=='ADJ ' .OR. HALG=='TILA' .OR. HALG=='TILL') THEN
  !
  IF (HINIT=='PGD' .AND. (HALG=='TILA' .OR. HALG=='TILL')) THEN
     CALL ABOR1_SFX("INIT_INDEX_PGD: for PGD, TILA and TILL are forbidden, please choose LIN or ADJ")
  ENDIF
  !
  IF (NRANK==NPIO .AND. (HALG=='ADJ ' .OR. HALG=='TILA')) THEN
    ALLOCATE(ILEFT  (YSC%U%NDIM_FULL))
    ALLOCATE(IRIGHT (YSC%U%NDIM_FULL))
    ALLOCATE(IBOTTOM(YSC%U%NDIM_FULL))
    ALLOCATE(ITOP   (YSC%U%NDIM_FULL))
    CALL GET_ADJACENT_MESHES(YSC%UG%G%CGRID,YSC%UG%NGRID_FULL_PAR,YSC%U%NDIM_FULL,&
                              YSC%UG%XGRID_FULL_PAR,ILEFT,IRIGHT,ITOP,IBOTTOM)
  ELSE
    ALLOCATE(ILEFT  (0))
    ALLOCATE(IRIGHT (0))
    ALLOCATE(IBOTTOM(0))
    ALLOCATE(ITOP   (0))
  ENDIF
  !
  IF (HALG=='ADJ ') THEN
    IF (NRANK==NPIO) CALL SET_NB_POINTS_ADJ(NPROC,YSC%U%NDIM_FULL,YSC%U%NDIM_FULL,&
                                                ILEFT,IRIGHT,ITOP,IBOTTOM,NINDEX,OSHADOWS)
  ELSEIF (HALG=='TILA' .OR. HALG=='TILL') THEN
    IF (NRANK==NPIO) CALL INI_DATA_COVER(YSC%DTCO, YSC%U)
    CALL SET_NB_POINTS_TIL(HPROGRAM,HALG,NPROC,YSC%U%NDIM_FULL,ILEFT,IRIGHT,ITOP,IBOTTOM,NINDEX,OSHADOWS)
  ENDIF
  !
ELSE
  !
  CALL ABOR1_SFX("INIT_INDEX_MPI: ALG="//HALG//" not defined for the moment")
  !
ENDIF
!
IF (HINIT=='PGD'.OR.(HINIT=="OFF".AND.LLAND_USE)) THEN
  ALLOCATE(NNUM(YSC%U%NDIM_FULL))
  NNUM(:) = 0
ENDIF  
!
IF (NRANK==NPIO) THEN
  !
  IF (NPROC>1) THEN
    !
    INBPTS(:) = 0
    DO JJ=1,SIZE(NINDEX)
      INBPTS(NINDEX(JJ)) = INBPTS(NINDEX(JJ)) + 1
    ENDDO
    !   
    INBMIN = MINVAL(INBPTS)
    IP0 = MAXVAL(MINLOC(INBPTS)) - 1
    !   
    IF (.NOT. GSHADOWS) THEN
    ! Matthieu Lafaysse :
    ! With shadows we don't want the repartition of points to be modified by the following instructions
    
      DO WHILE( INBPTS(NPIO) > NINT(PIO_FRAC*INBMIN) )
        !
        DO JJ=1,SIZE(NINDEX)
          IF (NINDEX(JJ)==NPIO) THEN
            NINDEX(JJ) = IP0
            INBPTS(NPIO) = INBPTS(NPIO) - 1
            INBPTS(IP0) = INBPTS(IP0) + 1
            EXIT
          ENDIF
        ENDDO
      !
        INBMIN = MAXVAL(INBPTS)
        IP0 = 0
        DO JJ=0,NPROC-1
          IF (JJ/=NPIO .AND. INBPTS(JJ)<INBMIN) THEN
            INBMIN = INBPTS(JJ)
            IP0 = JJ
          ENDIF
        ENDDO
      !
      END DO
    
    END IF
    !
  ENDIF
  !
  IF (HINIT=='PGD'.OR.(HINIT=="OFF".AND.LLAND_USE)) THEN
    INB(:) = 0
    DO JJ=1,YSC%U%NDIM_FULL
      INB(NINDEX(JJ)) = INB(NINDEX(JJ))+1
      NNUM(JJ) = INB(NINDEX(JJ))
    ENDDO
  ENDIF
  !  
ENDIF
!
IF (NPROC>1) THEN
#ifdef SFX_MPI
  IF (HINIT=='PGD'.OR.(HINIT=="OFF".AND.LLAND_USE)) THEN
    CALL MPI_BCAST(NINDEX,SIZE(NINDEX)*KIND(NINDEX)/4,MPI_INTEGER,NPIO,NCOMM,INFOMPI) 
    CALL MPI_BCAST(NNUM,SIZE(NNUM)*KIND(NNUM)/4,MPI_INTEGER,NPIO,NCOMM,INFOMPI)
  ENDIF
  IF (GSHADOWS) THEN
  ! Matthieu Lafaysse :
  ! Each thread need to know NIX and NIY
    CALL MPI_BCAST(NIX,KIND(NIX)/4,MPI_INTEGER,NPIO,NCOMM,INFOMPI)
    CALL MPI_BCAST(NIY,KIND(NIY)/4,MPI_INTEGER,NPIO,NCOMM,INFOMPI)
  ENDIF
#endif
ENDIF
!
ALLOCATE(NSIZE_TASK(0:NPROC-1))
NSIZE_TASK(:) = 0
!
IF (NRANK==NPIO) THEN
  DO JJ=1,YSC%U%NDIM_FULL
    NSIZE_TASK(NINDEX(JJ)) = NSIZE_TASK(NINDEX(JJ)) + 1
  ENDDO
ENDIF
!
NSIZE = 0
IF (NPROC>1) THEN
#ifdef SFX_MPI
  CALL MPI_BCAST(NSIZE_TASK,SIZE(NSIZE_TASK)*KIND(NSIZE_TASK)/4,MPI_INTEGER,NPIO,NCOMM,INFOMPI)
#endif
  NSIZE = MAXVAL(NSIZE_TASK)
  DO JJ=0,NPROC-1
    CALL WLOG_MPI('SIZE_TASK ',KLOG=JJ,KLOG2=NSIZE_TASK(JJ))
  ENDDO
ELSE
  NSIZE = NSIZE_TASK(0)
ENDIF
!
IF (HINIT/='PGD'.AND..NOT.LLAND_USE) YSC%UG%XGRID_FULL_PAR=>NULL()
!
IF (LHOOK) CALL DR_HOOK('INIT_INDEX_MPI',1,ZHOOK_HANDLE)
!
CONTAINS
!
!***************************************************************
!
SUBROUTINE SET_NB_POINTS_LIN(KPROC,KPROCMIN,KSIZE,KINDEX,OSHADOWS)
!
IMPLICIT NONE
!
INTEGER, INTENT(IN) :: KPROC
INTEGER, INTENT(IN) :: KPROCMIN
INTEGER, INTENT(IN) :: KSIZE
INTEGER, DIMENSION(:), INTENT(INOUT) :: KINDEX
LOGICAL, INTENT(IN) :: OSHADOWS
!
INTEGER, DIMENSION(0:KPROC-1) :: ISIZE_TASK
INTEGER :: JI, JJ, CPT, IPROC1
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
IF (LHOOK) CALL DR_HOOK('INIT_INDEX_MPI:SET_NB_POINTS_LIN',0,ZHOOK_HANDLE)
!
 CALL GET_SIZES_PARALLEL(YSC%DTCO, YSC%UG, YSC%U, &
                         KPROC,KSIZE,KPROCMIN,ISIZE_TASK,OSHADOWS)
!
IPROC1 = KPROCMIN
!
CPT   = 0
!
DO JJ=1,SIZE(KINDEX) ! boucle sur les points du domaine
  !
  IF (KINDEX(JJ)==-1) THEN ! si le point doit être affecté à cette itération
    CPT = CPT + 1 ! on augmente le nombre de points affectés de 1
    DO WHILE( CPT>ISIZE_TASK(IPROC1) ) ! si on est hors les bornes permises par le proc en cours
      IF ( IPROC1.GE.KPROCMIN ) THEN ! d'abord, on va de IPROCMIN à IPROC-1
        IPROC1 = IPROC1+1
        IF ( IPROC1==KPROC ) IPROC1 = KPROCMIN-1 ! une fois qu'on est à IPROC-1,
      ELSE                                       ! on redescend sous IPROC1
        IPROC1 = IPROC1-1
      ENDIF
      CPT = 1
    ENDDO
    KINDEX(JJ) = IPROC1
  ENDIF
  !
ENDDO
!

IF (LHOOK) CALL DR_HOOK('INIT_INDEX_MPI:SET_NB_POINTS_LIN',1,ZHOOK_HANDLE)
!
END SUBROUTINE SET_NB_POINTS_LIN
!
!**************************************************************************
!
SUBROUTINE SET_NB_POINTS_ADJ(KPROC,KSIZE,KDIM_FULL,KLEFT,KRIGHT,KTOP,KBOTTOM,KINDEX,OSHADOWS)
!
IMPLICIT NONE
!
INTEGER, INTENT(IN) :: KPROC
INTEGER, INTENT(IN) :: KSIZE
INTEGER, INTENT(IN) :: KDIM_FULL
INTEGER, DIMENSION(KDIM_FULL), INTENT(IN) :: KLEFT
INTEGER, DIMENSION(KDIM_FULL), INTENT(IN) :: KRIGHT
INTEGER, DIMENSION(KDIM_FULL), INTENT(IN) :: KTOP 
INTEGER, DIMENSION(KDIM_FULL), INTENT(IN) :: KBOTTOM
INTEGER, DIMENSION(KDIM_FULL), INTENT(INOUT) :: KINDEX
LOGICAL, INTENT(IN) :: OSHADOWS
!
INTEGER, DIMENSION(:), ALLOCATABLE :: IMASK
INTEGER, DIMENSION(KDIM_FULL) :: IPOINT
INTEGER, DIMENSION(0:KPROC-1) :: ISIZE_TASK
INTEGER, DIMENSION(4) :: INEAR
INTEGER :: ICOUNT,ICPT,IDEB
INTEGER :: CPT_TOT, CPT_LOC, CPT_INTER, JI, JJ, JK
!
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
IF (LHOOK) CALL DR_HOOK('INIT_INDEX_MPI:SET_NB_POINTS_ADJ',0,ZHOOK_HANDLE)
!
 CALL GET_SIZES_PARALLEL(YSC%DTCO, YSC%UG, YSC%U, &
                         KPROC,KSIZE,NPIO,ISIZE_TASK,OSHADOWS)
!
ICOUNT = COUNT(KINDEX(:)==-1)
ALLOCATE(IMASK(ICOUNT))
ICPT = 0
DO JJ=1,KDIM_FULL
  IF (KINDEX(JJ)==-1) THEN
    ICPT = ICPT + 1
    IMASK(ICPT) = JJ
  ENDIF
ENDDO
IDEB = 1
!
DO JI=1,KPROC-1
  !
  CPT_INTER = 0
  CPT_LOC   = 0
  CPT_TOT   = 0
  !
  DO WHILE ( CPT_TOT < ISIZE_TASK(JI) )
    !
    IF (CPT_LOC < 1 ) THEN ! if no free point has been found in neighbours
      !
      DO JJ=IDEB,ICOUNT
        IF ( KINDEX(IMASK(JJ))==-1 ) THEN
          CPT_TOT = CPT_TOT + 1
          CPT_LOC = 1
          IPOINT(1) = IMASK(JJ)
          KINDEX(IMASK(JJ)) = JI
          EXIT
        ENDIF
      ENDDO
      IDEB = JJ+1
      !
    ENDIF
    !
    IPOINT(1:CPT_LOC-CPT_INTER) = IPOINT(CPT_INTER+1:CPT_LOC)
    CPT_LOC   = CPT_LOC - CPT_INTER
    CPT_INTER = CPT_LOC
    !
    B1 : DO JJ=1,CPT_INTER
      !
      INEAR(1) = KBOTTOM(IPOINT(JJ))
      INEAR(2) = KLEFT  (IPOINT(JJ))
      INEAR(3) = KRIGHT (IPOINT(JJ)) 
      INEAR(4) = KTOP   (IPOINT(JJ))    
      !
      DO JK=1,4
        !
        IF ( INEAR(JK).NE.0 ) THEN
          IF( KINDEX(INEAR(JK)).EQ.-1 ) THEN
            CPT_TOT = CPT_TOT + 1
            CPT_LOC = CPT_LOC + 1
            IF (CPT_TOT.GT.ISIZE_TASK(JI)) EXIT B1
            KINDEX(INEAR(JK)) = JI
            IPOINT(CPT_LOC) = INEAR(JK)
          ENDIF
        ENDIF
        !
      ENDDO
      !
    ENDDO B1
    !
  ENDDO
  !
ENDDO
!
DEALLOCATE(IMASK)
!
WHERE (KINDEX(:)==-1) KINDEX(:) = 0
!
IF (LHOOK) CALL DR_HOOK('INIT_INDEX_MPI:SET_NB_POINTS_ADJ',1,ZHOOK_HANDLE)
!
END SUBROUTINE SET_NB_POINTS_ADJ
!
!*****************************************************************
!
SUBROUTINE SET_NB_POINTS_TIL(HPROGRAM,HALG,KPROC,KDIM_FULL,KLEFT,KRIGHT,KTOP,KBOTTOM,KINDEX,OSHADOWS)
!
! modif 
! 05/14 B. Decharme Partion done according to patch and not vegtype (vegtype can be > to patch grid)
!
USE MODN_IO_OFFLINE, ONLY : LWR_VEGTYPE
!
USE MODD_DATA_COVER_PAR, ONLY : NVEGTYPE, JPCOVER
USE MODD_SURF_PAR,       ONLY : XUNDEF
!
USE MODI_AV_PGD
!
IMPLICIT NONE
!
 CHARACTER(LEN=6), INTENT(IN) :: HPROGRAM
 CHARACTER(LEN=4), INTENT(IN) :: HALG
INTEGER, INTENT(IN) :: KPROC
INTEGER, INTENT(IN) :: KDIM_FULL
INTEGER, DIMENSION(KDIM_FULL), INTENT(IN) :: KLEFT
INTEGER, DIMENSION(KDIM_FULL), INTENT(IN) :: KRIGHT
INTEGER, DIMENSION(KDIM_FULL), INTENT(IN) :: KTOP 
INTEGER, DIMENSION(KDIM_FULL), INTENT(IN) :: KBOTTOM
INTEGER, DIMENSION(KDIM_FULL), INTENT(INOUT) :: KINDEX
LOGICAL, INTENT(IN) :: OSHADOWS
!
REAL, DIMENSION(KDIM_FULL) :: ZSEA
REAL, DIMENSION(KDIM_FULL) :: ZWATER
REAL, DIMENSION(KDIM_FULL) :: ZNATURE
REAL, DIMENSION(KDIM_FULL) :: ZTOWN
REAL, DIMENSION(:,:), ALLOCATABLE  :: ZCOVER
REAL, DIMENSION(:,:), ALLOCATABLE :: ZVEGTYPE
INTEGER, DIMENSION(KDIM_FULL,2) :: ITYPE 
INTEGER, DIMENSION(KDIM_FULL) :: IINDEX
INTEGER, DIMENSION(0:KPROC-1) :: ISIZE_TASK
INTEGER, DIMENSION(0:KPROC-1) :: INBPTS
INTEGER, DIMENSION(1) :: IPROCMIN
INTEGER :: IFULL, IRESP, JJ, JI, JK, JVEGTYPE, CPT, IN1, IN2
INTEGER :: IDIM_NATURE
CHARACTER(LEN=6) :: YNATURE
LOGICAL, DIMENSION(JPCOVER) :: GCOVER
LOGICAL :: GDATA_VEGTYPE
!
CHARACTER(LEN=12) :: YRECFM         ! Name of the article to be read
INTEGER           :: IVERSION
!
REAL(KIND=JPRB) :: ZHOOK_HANDLE, ZHOOK_HANDLE_OMP
!
IF (LHOOK) CALL DR_HOOK('INIT_INDEX_MPI:SET_NB_POINTS_TIL',0,ZHOOK_HANDLE)
!
GDATA_VEGTYPE = .FALSE.
!
! Full read
!
 CALL SET_SURFEX_FILEIN(HPROGRAM,'PGD ')

 CALL INIT_IO_SURF_n(YSC%DTCO, YSC%U, HPROGRAM,'FULL  ','SURF  ','READ ')
!
 CALL READ_SURF(HPROGRAM,'FRAC_SEA   ',ZSEA,   IRESP, HDIR='A')
 CALL READ_SURF(HPROGRAM,'FRAC_NATURE',ZNATURE,IRESP, HDIR='A')
 CALL READ_SURF(HPROGRAM,'FRAC_WATER ',ZWATER, IRESP, HDIR='A')
 CALL READ_SURF(HPROGRAM,'FRAC_TOWN  ',ZTOWN,  IRESP, HDIR='A')
 CALL READ_SURF(HPROGRAM,'NATURE     ',YNATURE,IRESP, HDIR='-')
 CALL READ_SURF(HPROGRAM,'VERSION    ',IVERSION,IRESP, HDIR='-')
 CALL READ_SURF(HPROGRAM,'DIM_NATURE ',IDIM_NATURE,IRESP,HDIR='-')
!
 CALL END_IO_SURF_n(HPROGRAM)
!
!
! Algo
!
IF (NRANK==NPIO) THEN
  !
  ITYPE(:,:) = 0
  !
  DO JJ=1,KDIM_FULL
    !
    IF (ZSEA(JJ)/=0. .AND. ZNATURE(JJ)/=0. .AND. ZWATER(JJ)/=0. .AND. ZTOWN(JJ)/=0.) THEN ! 1 2 3 4
      ITYPE(JJ,1) = 1 
    ELSEIF (ZSEA(JJ)/=0. .AND. ZNATURE(JJ)/=0. .AND. ZWATER(JJ)/=0.) THEN ! 1 2 3
      ITYPE(JJ,1) = 2
    ELSEIF (ZSEA(JJ)/=0. .AND. ZNATURE(JJ)/=0. .AND. ZTOWN(JJ)/=0.) THEN ! 1 2 4
      ITYPE(JJ,1) = 3
    ELSEIF (ZSEA(JJ)/=0. .AND. ZWATER(JJ)/=0. .AND. ZTOWN(JJ)/=0.) THEN ! 1 3 4 
      ITYPE(JJ,1) = 4
    ELSEIF (ZNATURE(JJ)/=0. .AND. ZWATER(JJ)/=0. .AND. ZTOWN(JJ)/=0.) THEN ! 2 3 4
      ITYPE(JJ,1) = 5
    ELSEIF (ZSEA(JJ)/=0.) THEN 
      IF (ZNATURE(JJ)/=0.) THEN ! 1 2
        ITYPE(JJ,1) = 6
      ELSEIF (ZWATER(JJ)/=0.) THEN ! 1 3
        ITYPE(JJ,1) = 7
      ELSEIF (ZTOWN(JJ)/=0.) THEN ! 1 4
        ITYPE(JJ,1) = 8
      ELSE ! 1
        ITYPE(JJ,1) = 12
      ENDIF
    ELSEIF (ZNATURE(JJ)/=0.) THEN
      IF (ZWATER(JJ)/=0.) THEN ! 2 3
        ITYPE(JJ,1) = 9
      ELSEIF (ZTOWN(JJ)/=0.) THEN ! 2 4
        ITYPE(JJ,1) = 10
      ELSE ! 2
        ITYPE(JJ,1) = 13
      ENDIF
    ELSEIF (ZWATER(JJ)/=0.) THEN
      IF (ZTOWN(JJ)/=0.) THEN ! 3 4
        ITYPE(JJ,1) = 11
      ELSE ! 3
        ITYPE(JJ,1) = 14
      ENDIF
    ELSE ! 4
      ITYPE(JJ,1) = 15
    ENDIF
    !
  ENDDO
  !
ENDIF  
!
! Nature read
!
IF (YNATURE/='NONE' .AND. IDIM_NATURE>0) THEN
  !
  ALLOCATE(ZVEGTYPE(KDIM_FULL,NVEGTYPE))
  !
  CALL INIT_IO_SURF_n(YSC%DTCO, YSC%U, HPROGRAM,'NATURE','SURF  ','READ ')
  CALL READ_SURF(HPROGRAM,'L_VEGTYPE',GDATA_VEGTYPE,IRESP,HDIR='-')
  CALL END_IO_SURF_n(HPROGRAM)
  !
  CALL INIT_IO_SURF_n(YSC%DTCO, YSC%U, HPROGRAM,'FULL  ','SURF  ','READ ')
  !  
  IF (GDATA_VEGTYPE) THEN
    CALL READ_SURF(HPROGRAM,'D_VEGTYPE',ZVEGTYPE(:,:),IRESP,HDIR='A')
  ELSE
    IF (LWR_VEGTYPE) THEN
      CALL READ_SURF(HPROGRAM,'VEGTYPE',ZVEGTYPE(:,:),IRESP,HDIR='E')
    ELSE
      CALL READ_SURF(HPROGRAM,'COVER_LIST',GCOVER(:),IRESP,HDIR='-')
      ALLOCATE(ZCOVER(KDIM_FULL,COUNT(GCOVER)))
      CALL READ_SURF_COV(HPROGRAM,'COVER',ZCOVER(:,:),GCOVER,IRESP,HDIR='E')

      IF (NRANK==NPIO) THEN
        DO JVEGTYPE=1,NVEGTYPE
          CALL AV_PGD(YSC%DTCO, &
                     ZVEGTYPE(:,JVEGTYPE),ZCOVER,YSC%DTCO%XDATA_VEGTYPE(:,JVEGTYPE),'NAT','ARI',GCOVER)
        END DO
      ENDIF

      DEALLOCATE(ZCOVER)

    ENDIF

  ENDIF
!
  CALL END_IO_SURF_n(HPROGRAM)
!
  IF (NRANK==NPIO) THEN
    !we give numbers to the 40 types of vegtypes
    DO JJ=1,KDIM_FULL
      IN1 = COUNT(ZVEGTYPE(JJ,1:3)/=0.)
      IN2 = COUNT(ZVEGTYPE(JJ,4:NVEGTYPE)/=0.)
      ITYPE(JJ,2) = IN2*4 + IN1 + 1
    ENDDO
  ENDIF
  !
ELSE
  !
  IF (NRANK==NPIO) ITYPE(:,2) = 1
  !
ENDIF
!
!
!we give numbers to the 40 types of vegtypes
!
IF (NRANK==NPIO) THEN
  !
  KINDEX(:) = -1
  !
  DO JI = 1,15
    !
    DO JJ = 1,MAXVAL(MAXVAL(ITYPE,2))
      !
      !count of the points in the couple of types
      IINDEX(:) = -2
      DO JK=1,KDIM_FULL
        IF (ITYPE(JK,1)==JI .AND. ITYPE(JK,2)==JJ) IINDEX(JK) = -1
      ENDDO
      !
      IFULL = COUNT(IINDEX(:)==-1)
      !
      IF (IFULL.NE.0) THEN
        !
        INBPTS(:) = 0
        DO JK=1,SIZE(KINDEX)
          IF (KINDEX(JK)>-1) INBPTS(KINDEX(JK)) = INBPTS(KINDEX(JK)) + 1
        ENDDO
        IF (KPROC>1) THEN
          IPROCMIN = MINLOC(INBPTS(0:KPROC-1))-1
         ELSE
          IPROCMIN(:) = 0
        ENDIF
        !
        IF (HALG=='TILL') THEN
          CALL SET_NB_POINTS_LIN(KPROC,IPROCMIN(1),IFULL,IINDEX(:),OSHADOWS)
        ELSEIF (HALG=='TILA') THEN
          CALL SET_NB_POINTS_ADJ(KPROC,IFULL,KDIM_FULL,KLEFT,KRIGHT,KTOP,KBOTTOM,IINDEX(:),OSHADOWS)
        ENDIF
        !
        DO JK=1,KDIM_FULL
          IF ( IINDEX(JK)> -1 ) KINDEX(JK) = IINDEX(JK)
        ENDDO
        !
      ENDIF
      !
    ENDDO
    !
  ENDDO
  !
ENDIF
!
IF (LHOOK) CALL DR_HOOK('INIT_INDEX_MPI:SET_NB_POINTS_TIL',1,ZHOOK_HANDLE)
!
END SUBROUTINE SET_NB_POINTS_TIL
!
!
!
END SUBROUTINE INIT_INDEX_MPI
