!     #########
      SUBROUTINE INIT_IO_SURF_NC_n(HMASK,HACTION)
!     ######################
!
!!****  *INIT_IO_SURF_NC* Keep in memory the netcdf ID of the output files
!!
!!    PURPOSE
!!    -------
!
!!
!!**  IMPLICIT ARGUMENTS
!!    ------------------
!!      None 
!!
!!    REFERENCE
!!    ---------
!!
!!    AUTHOR
!!    ------
!!	F. Habets   *Meteo France*
!!
!!    MODIFICATIONS
!!    -------------
!!      modified 05/04 by P. LeMoigne *Meteo France*
!!      modified 06/10 by S. Faroux *Meteo France*
!!=================================================================
!
!*       0.   DECLARATIONS
!             ------------
!
USE MODD_SURF_CONF,      ONLY : CSOFTWARE
!
USE MODD_SURFEX_MPI, ONLY : NINDEX, NPIO, NRANK
!
USE MODD_OL_FILEID, ONLY : XVAR_TO_FILEOUT, XID, XOUT
!
USE MODD_DATA_COVER, ONLY : LDATA_IRRIG
USE MODD_DATA_COVER_PAR, ONLY : NVEGTYPE, JPCOVER
!
USE MODD_DATA_TSZ0_n, ONLY : XDATA_DTS
!
USE MODD_SURF_ATM_GRID_n, ONLY : CGRID, XGRID_PAR
!
USE MODD_CH_SURF_n,       ONLY : LCH_EMIS, CCH_EMIS
USE MODD_CH_EMIS_FIELD_n, ONLY : NEMIS_NBR, NTIME_MAX
USE MODD_CH_SNAP_n, ONLY : NSNAP_M, NSNAP_D, NSNAP_H, NEMIS_SNAP
!
USE MODD_IO_SURF_NC, ONLY : NMASK, CFILEIN_NC, CFILEOUT_NC, LMASK, NID_NC, &
                            CMASK, LCREATED, CFILEOUT_NC_SAVE, LDEF
!
USE MODN_IO_OFFLINE, ONLY : LRESTART
!
USE MODE_GRIDTYPE_GAUSS
!
USE MODI_GET_BLD_CONF_n
USE MODI_GET_DATA_SEAFLUX_CONF_n
USE MODI_GET_ISBA_CONF_n
USE MODI_OL_DEFINE_DIM
USE MODI_CREATE_FILE
USE MODI_READ_SURF
USE MODI_INIT_IO_SURF_MASK_n
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE
!
INCLUDE "netcdf.inc"
!
 CHARACTER(LEN=6),  INTENT(IN)  :: HMASK    
 CHARACTER(LEN=5),  INTENT(IN)  :: HACTION 
!
 CHARACTER(LEN=100), DIMENSION(:), POINTER :: YNAME_DIM
 CHARACTER(LEN=13),DIMENSION(1)  :: YUNIT1, YUNIT2
 CHARACTER(LEN=3)                 :: YISBA 
!
REAL,DIMENSION(:), POINTER       :: ZX, ZY
!
INTEGER, DIMENSION(:), POINTER   :: IDIMS, IDDIM
INTEGER           :: IDIM1, INDIMS
INTEGER          :: INI, INPATCH, INLVLD, INLVLS, INBIOMASS, &
                    INLITTER, INLITTLEVS, INSOILCARB
INTEGER          :: IDESC_ROOF_LAYER, IDESC_ROAD_LAYER, IDESC_WALL_LAYER, &
                    IDESC_FLOOR_LAYER, IDESC_CODE, IDESC_USE, IDESC_AGE, IDESC_BLD
INTEGER          :: ILU,IRET, IL, IFULL, ISNAP, INLATI
INTEGER          :: ILUOUT, IDIMID, ITIME, ITOT
!
LOGICAL          :: GEXIST, GOPENED, GSST_DATA
LOGICAL          :: GDATA_BLDTYPE, GDATA_BLD_AGE, GDATA_USETYPE
!
REAL(KIND=JPRB)  :: ZHOOK_HANDLE
!------------------------------------------------------------------------------ 
IF (LHOOK) CALL DR_HOOK('INIT_IO_SURF_NC_N',0,ZHOOK_HANDLE)
!
LMASK = .TRUE.
!
!$OMP BARRIER
!
IF (HACTION=='READ') THEN
  INQUIRE(FILE=CFILEIN_NC,EXIST=GEXIST)
  IF (GEXIST) THEN 
    IF (NRANK==NPIO) THEN
!$OMP SINGLE
      IRET = NF_OPEN(CFILEIN_NC,NF_NOWRITE,NID_NC)
!$OMP END SINGLE
    ENDIF
    CALL READ_SURF('NC    ','DIM_FULL',IFULL,IRET,HDIR='A')
  ENDIF
ELSE 
  CALL GET_DIM_FULL_n(IFULL)
  IF (NRANK==NPIO) THEN
!$OMP SINGLE
    INQUIRE(FILE=CFILEOUT_NC,EXIST=GEXIST)
    INQUIRE(FILE=CFILEOUT_NC,OPENED=GOPENED)
    IF (.NOT.GOPENED) THEN
      IRET = NF_OPEN(CFILEOUT_NC,NF_WRITE,NID_NC)
    ENDIF
    IF (.NOT.GEXIST .OR. .NOT.LCREATED .OR. CFILEOUT_NC/=CFILEOUT_NC_SAVE) THEN
      IF (CSOFTWARE=='PREP' .OR. CSOFTWARE=='OFFLINE' .OR. CSOFTWARE=='SODA') THEN
        CALL GET_ISBA_CONF_n(YISBA, INPATCH, INLVLD, INLVLS, INBIOMASS, &
                             INLITTER, INLITTLEVS, INSOILCARB)
      ELSEIF (CSOFTWARE=='PGD') THEN
        INPATCH = NVEGTYPE
      ENDIF
      CALL OL_DEFINE_DIM('NOTIME ', ILUOUT, IFULL, IDIM1, YUNIT1, YUNIT2, &
                     ZX, ZY, IDIMS, IDDIM, YNAME_DIM, KNPATCH=INPATCH)
      IF (ALLOCATED(XVAR_TO_FILEOUT)) DEALLOCATE(XVAR_TO_FILEOUT)
      IF (ALLOCATED(XID)) DEALLOCATE(XID)
      ALLOCATE(XID(0))
      XOUT=0
      CALL CREATE_FILE(CFILEOUT_NC,IDIMS,YNAME_DIM,NID_NC,IDDIM) 
      CFILEOUT_NC_SAVE = CFILEOUT_NC
      LCREATED = .TRUE.
      IF (CSOFTWARE=='PGD' .OR. ( CSOFTWARE=='OFFLINE' .AND. LRESTART ) ) THEN
        IRET = NF_DEF_DIM(NID_NC,"Number_of_covers",JPCOVER,IDIMID)
        IF (LDATA_IRRIG) IRET = NF_DEF_DIM(NID_NC,"Irrig_parameters",6,IDIMID)
        CALL GET_ISBA_CONF_n(YISBA, INPATCH, INLVLD, INLVLS, INBIOMASS, &
                             INLITTER, INLITTLEVS, INSOILCARB)
        IF (YISBA=='DIF') IRET = NF_DEF_DIM(NID_NC,"Nground_layers",INLVLD,IDIMID)
        CALL GET_DATA_SEAFLUX_CONF_n(GSST_DATA,ITIME)
        IF (GSST_DATA) IRET = NF_DEF_DIM(NID_NC,"Number_of_dates",ITIME,IDIMID)
        CALL GET_BLD_CONF_n(GDATA_BLDTYPE, GDATA_BLD_AGE, GDATA_USETYPE, &
                   IDESC_ROOF_LAYER, IDESC_ROAD_LAYER, IDESC_WALL_LAYER, &
                   IDESC_FLOOR_LAYER, IDESC_CODE, IDESC_USE, IDESC_AGE, IDESC_BLD)
        IF (GDATA_BLDTYPE .OR. GDATA_BLD_AGE .OR. GDATA_USETYPE) THEN
          ITOT = (21+3*IDESC_ROOF_LAYER+3*IDESC_ROAD_LAYER+3*IDESC_WALL_LAYER+3*IDESC_FLOOR_LAYER)&
                  *IDESC_CODE + 9*IDESC_USE+2*IDESC_AGE+IDESC_BLD
          IRET = NF_DEF_DIM(NID_NC,"Bld_dimensions  ",7,IDIMID)
          IRET = NF_DEF_DIM(NID_NC,"Bld_parameters  ",ITOT,IDIMID)
        ENDIF
        IF (LCH_EMIS) THEN
          IF (CCH_EMIS=='AGGR') THEN
            IF (NEMIS_NBR/=0) IRET = NF_DEF_DIM(NID_NC,"Temporal_emiss  ",NTIME_MAX,IDIMID)
          ELSE IF (CCH_EMIS=='SNAP') THEN
            ISNAP = MAX(NSNAP_M,NSNAP_D,NSNAP_H)
            IF (ISNAP/=0 .AND. NEMIS_SNAP/=0) THEN
              IRET = NF_DEF_DIM(NID_NC,"Nemis_snap",NEMIS_SNAP,IDIMID)
              IRET = NF_DEF_DIM(NID_NC,"Nsnap_temp",ISNAP,IDIMID)
            ENDIF
          ENDIF
        ENDIF
        IF (ASSOCIATED(XDATA_DTS)) THEN
          ITIME = SIZE(XDATA_DTS) 
          IF (ITIME/=0) IRET = NF_DEF_DIM(NID_NC,"Nforc_tsz0",ITIME,IDIMID)
        ENDIF
      ENDIF
      IF (CGRID=='GAUSS') THEN
        CALL GET_GRIDTYPE_GAUSS(XGRID_PAR,INLATI)
        IRET = NF_DEF_DIM(NID_NC,"Nlati",INLATI,IDIMID)
      ENDIF
    ELSE
      IF (LDEF) IRET = NF_REDEF(NID_NC)
    ENDIF
!$OMP END SINGLE
  ENDIF
ENDIF
!
! nindex is needed for call to get_size_full_n. In init_index_mpi, 
! it's not initialized for first readings.  
IF (.NOT.ALLOCATED(NINDEX)) THEN
  ALLOCATE(NINDEX(IFULL))
  NINDEX(:) = 0
ENDIF
!
! size by MPI task. NINDEX is supposed to be initialized at this step.  
 CALL GET_SIZE_FULL_n('OFFLIN',IFULL,ILU)
!
IL = ILU
 CALL GET_TYPE_DIM_n(HMASK,IL)
!
 CALL INIT_IO_SURF_MASK_n(HMASK, IL, ILUOUT, ILU, NMASK)
!
CMASK = HMASK
!
!$OMP BARRIER
!------------------------------------------------------------------------------
IF (LHOOK) CALL DR_HOOK('INIT_IO_SURF_NC_N',1,ZHOOK_HANDLE)
!------------------------------------------------------------------------------
!
END SUBROUTINE INIT_IO_SURF_NC_n
