!     #########
      SUBROUTINE INIT_IO_SURF_OL_n(HPROGRAM,HMASK,HSCHEME,HACTION)
!     ######################
!
!!****  *INIT_IO_SURF_OL* Keep in memory the netcdf ID of the output files
!!
!!    PURPOSE
!!    -------
!
!!
!!**  IMPLICIT ARGUMENTS
!!    ------------------
!!      None 
!!
!!    REFERENCE
!!    ---------
!!
!!    AUTHOR
!!    ------
!!      F. Habets   *Meteo France*
!!
!!    MODIFICATIONS
!!    -------------
!!      modified 05/04 by P. LeMoigne *Meteo France*
!!      modified 06/10 by S. Faroux *Meteo France*
!!=================================================================
!
!*       0.   DECLARATIONS
!             ------------
!
!
USE MODD_OL_FILEID, ONLY : XVAR_TO_FILEOUT,         &
                           XID, XOUT,               &
                           XVAR_SURF, XID_SURF,     &
                           XVAR_NATURE, XID_NATURE, &
                           XVAR_SEA, XID_SEA,       &
                           XVAR_WATER, XID_WATER,   &
                           XVAR_TOWN, XID_TOWN  
USE MODD_IO_SURF_OL
!
USE MODD_SURFEX_MPI, ONLY : NRANK, NPIO
!
USE MODN_IO_OFFLINE,    ONLY : XTSTEP_OUTPUT
!
USE MODI_GET_LUOUT
USE MODI_READ_SURF
USE MODI_GET_DIM_FULL_n
USE MODI_GET_SIZE_FULL_n
USE MODI_GET_TYPE_DIM_n
USE MODI_INIT_IO_SURF_MASK_n
USE MODI_INIT_OUTFN_FLAKE_n
USE MODI_INIT_OUTFN_ISBA_n
USE MODI_INIT_OUTFN_SEA_n
USE MODI_INIT_OUTFN_SURF_ATM_n
USE MODI_INIT_OUTFN_TEB_n
USE MODI_INIT_OUTFN_WATER_n
USE MODI_WRITE_SURF
!
USE MODD_SURFEX_MPI, ONLY : WLOG_MPI
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE
!
 CHARACTER(LEN=6),  INTENT(IN)  :: HPROGRAM 
 CHARACTER(LEN=6),  INTENT(IN)  :: HMASK    
 CHARACTER(LEN=6),  INTENT(IN)  :: HSCHEME 
 CHARACTER(LEN=5),  INTENT(IN)  :: HACTION 
!
REAL              :: ZDEN
INTEGER           :: IRESP          ! IRESP  : return-code if a problem appears
 CHARACTER(LEN=100):: YCOMMENT       ! Comment string
INTEGER           :: ILU,IRET, IL, IFULL
INTEGER           :: ILUOUT
REAL(KIND=JPRB)  :: ZHOOK_HANDLE
!------------------------------------------------------------------------------ 
IF (LHOOK) CALL DR_HOOK('INIT_IO_SURF_OL_N',0,ZHOOK_HANDLE)
!
LMASK = .TRUE.
!
 CALL GET_LUOUT(HPROGRAM,ILUOUT)
!
!$OMP BARRIER
!
IF (HACTION=='READ') THEN
  CALL READ_SURF('OFFLIN','DIM_FULL',IFULL,IRET)
ELSE 
  CALL GET_DIM_FULL_n(IFULL)
ENDIF
!
! size by MPI task. NINDEX is supposed to be initialized at this step.  
 CALL GET_SIZE_FULL_n('OFFLIN',IFULL,ILU)
!
IL = ILU
 CALL GET_TYPE_DIM_n(HMASK,IL)
 CALL INIT_IO_SURF_MASK_n(HMASK, IL, ILUOUT, ILU, NMASK)
!
IF (HACTION=='READ' .AND. LHOOK) CALL DR_HOOK('INIT_IO_SURF_OL_N',1,ZHOOK_HANDLE)
IF (HACTION=='READ') RETURN
!
IF (NRANK==NPIO) THEN
  !
!$OMP SINGLE 
  !
  IF (.NOT. LDEFINED_SURF_ATM) THEN         
    CALL INIT_OUTFN_SURF_ATM_n(HPROGRAM,ILUOUT)
    CALL ALLOCATE_FILL_VAR(XVAR_SURF, XID_SURF)
    LDEFINED_SURF_ATM=.TRUE.
  ENDIF
  !
  IF (HMASK=='NATURE' .AND. .NOT. LDEFINED_NATURE) THEN
    IF (HSCHEME=='ISBA  ') THEN 
      CALL INIT_OUTFN_ISBA_n(HPROGRAM,ILUOUT)
      CALL ALLOCATE_FILL_VAR(XVAR_NATURE, XID_NATURE)
    ENDIF
    LDEFINED_NATURE=.TRUE.
  ENDIF
  !
  IF (HMASK=='SEA   ' .AND. .NOT. LDEFINED_SEA) THEN
    IF (HSCHEME=='SEAFLX') THEN 
      CALL INIT_OUTFN_SEA_n(HPROGRAM,ILUOUT)
      CALL ALLOCATE_FILL_VAR(XVAR_SEA, XID_SEA)
    ENDIF
    LDEFINED_SEA=.TRUE.
  ENDIF
  !
  IF (HMASK=='WATER ' .AND. .NOT. LDEFINED_WATER) THEN
    IF (HSCHEME=='WATFLX') CALL INIT_OUTFN_WATER_n(HPROGRAM,ILUOUT)
    IF (HSCHEME=='FLAKE ') CALL INIT_OUTFN_FLAKE_n(HPROGRAM,ILUOUT)
    IF (HSCHEME=='WATFLX' .OR. HSCHEME=='FLAKE') CALL ALLOCATE_FILL_VAR(XVAR_WATER, XID_WATER)
    LDEFINED_WATER=.TRUE.
  ENDIF
  !
  IF (HMASK=='TOWN  ' .AND. .NOT. LDEFINED_TOWN) THEN
    IF (HSCHEME=='TEB   ') THEN 
      CALL INIT_OUTFN_TEB_n(HPROGRAM,ILUOUT)
      CALL ALLOCATE_FILL_VAR(XVAR_TOWN, XID_TOWN)
    ENDIF
    LDEFINED_TOWN=.TRUE.
  ENDIF
  !
!$OMP END SINGLE
  !  
  YCOMMENT=''
  !
  IF (XTSTEP_OUTPUT == FLOOR(XTSTEP_OUTPUT/86400.)*86400) THEN 
    ZDEN = 86400.
  ELSEIF (XTSTEP_OUTPUT == FLOOR(XTSTEP_OUTPUT/3600.)*3600) THEN
    ZDEN = 3600.
  ELSEIF (XTSTEP_OUTPUT == FLOOR(XTSTEP_OUTPUT/60.)*60) THEN
    ZDEN = 60.
  ELSE
    ZDEN = 1.
  ENDIF
  !
  IF (.NOT.LTIME_WRITTEN(1)) THEN 
    XTYPE=1
    CALL WRITE_SURF(HPROGRAM,'time',XTSTEP_OUTPUT/ZDEN*XSTARTW,IRESP,HCOMMENT=YCOMMENT)
    LTIME_WRITTEN(1)=.TRUE.
  ENDIF
  !
  IF (HSCHEME.NE.'NONE  ') THEN
    !
    IF (HMASK=='NATURE' .AND. .NOT.LTIME_WRITTEN(2)) THEN
      XTYPE=2
      CALL WRITE_SURF(HPROGRAM,'time',XTSTEP_OUTPUT/ZDEN*XSTARTW,IRESP,HCOMMENT=YCOMMENT)
      LTIME_WRITTEN(2)=.TRUE.
    ENDIF
    !
    IF (HMASK=='SEA   ' .AND. .NOT.LTIME_WRITTEN(3)) THEN
      XTYPE=3
      CALL WRITE_SURF(HPROGRAM,'time',XTSTEP_OUTPUT/ZDEN*XSTARTW,IRESP,HCOMMENT=YCOMMENT)
      LTIME_WRITTEN(3)=.TRUE.
    ENDIF
    !
    IF (HMASK=='WATER ' .AND.  .NOT.LTIME_WRITTEN(4)) THEN  
      XTYPE=4
      CALL WRITE_SURF(HPROGRAM,'time',XTSTEP_OUTPUT/ZDEN*XSTARTW,IRESP,HCOMMENT=YCOMMENT)
      LTIME_WRITTEN(4)=.TRUE.
    ENDIF
    !
    IF (HMASK=='TOWN  ' .AND. .NOT.LTIME_WRITTEN(5)) THEN     
      XTYPE=5
      CALL WRITE_SURF(HPROGRAM,'time',XTSTEP_OUTPUT/ZDEN*XSTARTW,IRESP,HCOMMENT=YCOMMENT)
      LTIME_WRITTEN(5)=.TRUE.
    ENDIF
    !
  ENDIF
  !
ENDIF
!
!------------------------------------------------------------------------------
IF (LHOOK) CALL DR_HOOK('INIT_IO_SURF_OL_N',1,ZHOOK_HANDLE)
CONTAINS 
!------------------------------------------------------------------------------
SUBROUTINE ALLOCATE_FILL_VAR(HVAR, NVAR)
  
 CHARACTER(LEN=20),DIMENSION(:), POINTER :: HVAR
INTEGER*4, DIMENSION(:), POINTER :: NVAR
REAL(KIND=JPRB) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('ALLOCATE_FILL_VAR',0,ZHOOK_HANDLE)
ALLOCATE(HVAR(XOUT))
ALLOCATE(NVAR(XOUT))
HVAR(:)=XVAR_TO_FILEOUT(1:XOUT)
NVAR(:)=XID(1:XOUT)
IF (LHOOK) CALL DR_HOOK('ALLOCATE_FILL_VAR',1,ZHOOK_HANDLE)

END SUBROUTINE ALLOCATE_FILL_VAR
!------------------------------------------------------------------------------
!
END SUBROUTINE INIT_IO_SURF_OL_n
