SUBROUTINE INIT_INDEX_MPI(HPROGRAM,HALG,PIO_FRAC)
!
USE MODD_SURFEX_MPI, ONLY : NRANK, NPIO, NPROC, NCOMM, NINDEX, NSIZE_TASK, NSIZE, WLOG_MPI
USE MODD_SURFEX_OMP, ONLY : NINDX2, NWORK, XWORK, XWORK2, NBLOCK
!
USE MODD_SURF_ATM_GRID_n, ONLY : CGRID, NGRID_PAR, XGRID_FULL_PAR
USE MODD_SURF_ATM_n, ONLY : NDIM_FULL
!
USE MODI_GET_LUOUT
USE MODI_SET_SURFEX_FILEIN
USE MODI_INIT_IO_SURF_n
USE MODI_READ_SURF
USE MODI_READ_GRIDTYPE
USE MODI_END_IO_SURF_n
USE MODI_ABOR1_SFX
USE MODI_GET_SIZES_PARALLEL
USE MODI_GET_ADJACENT_MESHES
USE MODI_GET_SIZE_FULL_n
USE MODI_INI_DATA_COVER
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE
!
#ifndef NOMPI
INCLUDE "mpif.h"
#endif
!
CHARACTER(LEN=6), INTENT(IN) :: HPROGRAM
CHARACTER(LEN=4), INTENT(IN) :: HALG
REAL, INTENT(IN) :: PIO_FRAC
!
INTEGER, DIMENSION(:), ALLOCATABLE :: ILEFT   ! index of left   grid mesh 
INTEGER, DIMENSION(:), ALLOCATABLE :: IRIGHT  ! index of right  grid mesh 
INTEGER, DIMENSION(:), ALLOCATABLE :: ITOP    ! index of top    grid mesh 
INTEGER, DIMENSION(:), ALLOCATABLE :: IBOTTOM ! index of bottom grid mesh
!
INTEGER :: IRESTE, INRESTE, IRANK, IPROC
INTEGER :: J, I, CPT, ILUOUT
INTEGER :: IRESP, INFOMPI
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
IF (LHOOK) CALL DR_HOOK('INIT_INDEX_MPI',0,ZHOOK_HANDLE)
!
IF ( NRANK==NPIO ) THEN
  !
  CALL GET_LUOUT(HPROGRAM,ILUOUT)
  !
  !*    1. Parameters of the grid
  !
  CALL SET_SURFEX_FILEIN(HPROGRAM,'PGD ')
  CALL INIT_IO_SURF_n(HPROGRAM,'FULL  ','SURF  ','READ ')
  !
  CALL READ_SURF(HPROGRAM,'DIM_FULL  ',NDIM_FULL,IRESP,HDIR='A')
  NINDX2 = NDIM_FULL
  !
  CALL READ_SURF(HPROGRAM,'GRID_TYPE',CGRID,IRESP,HDIR='A')
  !
  CALL READ_GRIDTYPE(HPROGRAM,CGRID,NGRID_PAR,NDIM_FULL,.FALSE.,HDIR='A')
  !
!!$OMP SINGLE
  ALLOCATE(XGRID_FULL_PAR(NGRID_PAR))
!!$OMP END SINGLE
  !
  CALL READ_GRIDTYPE(HPROGRAM,CGRID,NGRID_PAR,NDIM_FULL,.TRUE.,&
                     XGRID_FULL_PAR,IRESP,HDIR='A')
  !
  !
  CALL END_IO_SURF_n(HPROGRAM)
  !
ENDIF
!
IF (NPROC>1) THEN
!$OMP SINGLE
#ifndef NOMPI
  CALL MPI_BCAST(NDIM_FULL,KIND(NDIM_FULL)/4,MPI_INTEGER,NPIO,NCOMM,INFOMPI)
#endif
!$OMP END SINGLE COPYPRIVATE(NDIM_FULL)
ENDIF
!
!
!*     3. Points by task
!
IF (.NOT.ALLOCATED(NINDEX)) ALLOCATE(NINDEX(NDIM_FULL))
NINDEX(:) = -1
!
IF (HALG=='LIN ') THEN
  !
  IF (NRANK==NPIO) CALL SET_NB_POINTS_LIN(PIO_FRAC,NPROC,NPROC-1,NPIO,NDIM_FULL,NINDEX)
  !
ELSEIF (HALG=='ADJ ' .OR. HALG=='TILA' .OR. HALG=='TILL') THEN
  !
  IF (HALG=='ADJ ' .OR. HALG=='TILA') THEN
    IF (NRANK==NPIO) THEN
      ALLOCATE(ILEFT  (NDIM_FULL))
      ALLOCATE(IRIGHT (NDIM_FULL))
      ALLOCATE(IBOTTOM(NDIM_FULL))
      ALLOCATE(ITOP   (NDIM_FULL))
      CALL GET_ADJACENT_MESHES(CGRID,NGRID_PAR,NDIM_FULL,XGRID_FULL_PAR,ILEFT,IRIGHT,ITOP,IBOTTOM)
    ENDIF
  ELSE
    ALLOCATE(ILEFT  (0))
    ALLOCATE(IRIGHT (0))
    ALLOCATE(IBOTTOM(0))
    ALLOCATE(ITOP   (0))
  ENDIF
  !
  IF (HALG=='ADJ ') THEN
    IF (NRANK==NPIO) CALL SET_NB_POINTS_ADJ(PIO_FRAC,NPROC,NPIO,NDIM_FULL,NDIM_FULL,ILEFT,IRIGHT,ITOP,IBOTTOM,NINDEX)
  ELSEIF (HALG=='TILA' .OR. HALG=='TILL') THEN
    IF (NRANK==NPIO) THEN
      CALL INI_DATA_COVER
      CALL SET_NB_POINTS_TIL(HPROGRAM,HALG,PIO_FRAC,NPROC,NPIO,NDIM_FULL,ILEFT,IRIGHT,ITOP,IBOTTOM,NINDEX)
    ENDIF
  ENDIF
  !
  IF (ALLOCATED(ILEFT  )) DEALLOCATE(ILEFT  )
  IF (ALLOCATED(IRIGHT )) DEALLOCATE(IRIGHT )
  IF (ALLOCATED(ITOP   )) DEALLOCATE(ITOP   )
  IF (ALLOCATED(IBOTTOM)) DEALLOCATE(IBOTTOM)
  !
ELSE
  !
  CALL ABOR1_SFX("INIT_INDEX_MPI: ALG="//HALG//" not defined for the moment")
  !
ENDIF
!
IF (NPROC>1) THEN
!$OMP SINGLE
#ifndef NOMPI   
  CALL MPI_BCAST(NINDEX,SIZE(NINDEX)*KIND(NINDEX)/4,MPI_INTEGER,NPIO,NCOMM,INFOMPI)
#endif
!$OMP END SINGLE
ENDIF
!
ALLOCATE(NSIZE_TASK(0:NPROC-1))
NSIZE_TASK(:) = 0
!
CALL GET_SIZE_FULL_n(HPROGRAM,NDIM_FULL,NSIZE_TASK(NRANK))
NINDX2 = NSIZE_TASK(NRANK)
!
NSIZE = 0
IF (NPROC>1) THEN
!$OMP SINGLE
  DO J=0,NPROC-1
#ifndef NOMPI   
    CALL MPI_BCAST(NSIZE_TASK(J),KIND(NSIZE_TASK)/4,MPI_INTEGER,J,NCOMM,INFOMPI)
#endif    
    IF ( NSIZE_TASK(J)>NSIZE ) NSIZE = NSIZE_TASK(J)
    CALL WLOG_MPI('SIZE_TASK ',KLOG=J,KLOG2=NSIZE_TASK(J))
  ENDDO
!$OMP END SINGLE
ELSE
  NSIZE = NSIZE_TASK(0)
ENDIF
!
XGRID_FULL_PAR=>NULL()
!
ALLOCATE(NWORK(NSIZE))
ALLOCATE(XWORK(NSIZE))
ALLOCATE(XWORK2(NSIZE,10))
!
IF (LHOOK) CALL DR_HOOK('INIT_INDEX_MPI',1,ZHOOK_HANDLE)
!
CONTAINS
!
!***************************************************************
!
SUBROUTINE SET_NB_POINTS_LIN(PIO_FRAC,KPROC,KPROCMIN,KPIO,KSIZE,KINDEX)
!
IMPLICIT NONE
!
REAL, INTENT(IN) :: PIO_FRAC
INTEGER, INTENT(IN) :: KPROC
INTEGER, INTENT(IN) :: KPROCMIN
INTEGER, INTENT(IN) :: KPIO
INTEGER, INTENT(IN) :: KSIZE
INTEGER, DIMENSION(:), INTENT(INOUT) :: KINDEX
!
INTEGER, DIMENSION(0:KPROC-1) :: ISIZE_TASK
INTEGER :: I, J, CPT, IPROC1
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
IF (LHOOK) CALL DR_HOOK('INIT_INDEX_MPI:SET_NB_POINTS_LIN',0,ZHOOK_HANDLE)
!
CALL GET_SIZES_PARALLEL(PIO_FRAC,KPROC,KPIO,KSIZE,ISIZE_TASK)
!
IPROC1 = KPROCMIN
!
CPT   = 0
!
DO J=1,SIZE(KINDEX) ! boucle sur les points du domaine
  !
  IF (KINDEX(J)==-1) THEN ! si le point doit être affecté à cette itération
    CPT = CPT + 1 ! on augmente le nombre de points affectés de 1
    DO WHILE( CPT>ISIZE_TASK(IPROC1) ) ! si on est hors les bornes permises par le proc en cours
      IF ( IPROC1.GE.KPROCMIN ) THEN ! d'abord, on va de IPROCMIN à IPROC-1
        IPROC1 = IPROC1+1
        IF ( IPROC1==KPROC ) IPROC1 = KPROCMIN-1 ! une fois qu'on est à IPROC-1,
      ELSE                                       ! on redescend sous IPROC1
        IPROC1 = IPROC1-1
      ENDIF
      CPT = 1
    ENDDO
    KINDEX(J) = IPROC1
  ENDIF
  !
ENDDO
!
IF (LHOOK) CALL DR_HOOK('INIT_INDEX_MPI:SET_NB_POINTS_LIN',1,ZHOOK_HANDLE)
!
END SUBROUTINE SET_NB_POINTS_LIN
!
!**************************************************************************
!
SUBROUTINE SET_NB_POINTS_ADJ(PIO_FRAC,KPROC,KPIO,KSIZE,KSIZE_FULL,KLEFT,KRIGHT,KTOP,KBOTTOM,KINDEX)
!
IMPLICIT NONE
!
REAL, INTENT(IN) :: PIO_FRAC
INTEGER, INTENT(IN) :: KPROC
INTEGER, INTENT(IN) :: KPIO
INTEGER, INTENT(IN) :: KSIZE
INTEGER, INTENT(IN) :: KSIZE_FULL
INTEGER, DIMENSION(KSIZE_FULL), INTENT(IN) :: KLEFT
INTEGER, DIMENSION(KSIZE_FULL), INTENT(IN) :: KRIGHT
INTEGER, DIMENSION(KSIZE_FULL), INTENT(IN) :: KTOP 
INTEGER, DIMENSION(KSIZE_FULL), INTENT(IN) :: KBOTTOM
INTEGER, DIMENSION(KSIZE_FULL), INTENT(INOUT) :: KINDEX
!
INTEGER, DIMENSION(KSIZE_FULL) :: IPOINT
INTEGER, DIMENSION(0:KPROC-1) :: ISIZE_TASK
INTEGER, DIMENSION(4) :: INEAR
INTEGER :: CPT_TOT, CPT_LOC, CPT_INTER, I, J, K
!
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
IF (LHOOK) CALL DR_HOOK('INIT_INDEX_MPI:SET_NB_POINTS_ADJ',0,ZHOOK_HANDLE)
!
CALL GET_SIZES_PARALLEL(PIO_FRAC,KPROC,KPIO,KSIZE,ISIZE_TASK)
!
DO I=1,KPROC-1
  !
  CPT_INTER = 0
  CPT_LOC   = 0
  CPT_TOT   = 0
  !
  DO WHILE ( CPT_TOT < ISIZE_TASK(I) )
    !
    IF (CPT_LOC < 1 ) THEN ! if no free point has been found in neighbours
      !
      DO J=1,KSIZE_FULL
        IF ( KINDEX(J)==-1 ) THEN
          CPT_TOT = CPT_TOT + 1
          CPT_LOC = 1
          IPOINT(1) = J
          KINDEX(J) = I
          EXIT
        ENDIF
      ENDDO
      !
    ENDIF
    !
    IPOINT(1:CPT_LOC-CPT_INTER) = IPOINT(CPT_INTER+1:CPT_LOC)
    CPT_LOC   = CPT_LOC - CPT_INTER
    CPT_INTER = CPT_LOC
    !
    B1 : DO J=1,CPT_INTER
      !
      INEAR(1) = KBOTTOM(IPOINT(J))
      INEAR(2) = KLEFT  (IPOINT(J))
      INEAR(3) = KRIGHT (IPOINT(J)) 
      INEAR(4) = KTOP   (IPOINT(J))    
      !
      DO K=1,4
        !
        IF ( INEAR(K).NE.0 ) THEN
          IF( KINDEX(INEAR(K)).EQ.-1 ) THEN
            CPT_TOT = CPT_TOT + 1
            CPT_LOC = CPT_LOC + 1
            IF (CPT_TOT.GT.ISIZE_TASK(I)) EXIT B1
            KINDEX(INEAR(K)) = I
            IPOINT(CPT_LOC) = INEAR(K)
          ENDIF
        ENDIF
        !
      ENDDO
      !
    ENDDO B1
    !
  ENDDO
  !
ENDDO
!
WHERE (KINDEX(:)==-1) KINDEX(:) = 0
!
IF (LHOOK) CALL DR_HOOK('INIT_INDEX_MPI:SET_NB_POINTS_ADJ',1,ZHOOK_HANDLE)
!
END SUBROUTINE SET_NB_POINTS_ADJ
!
!*****************************************************************
!
SUBROUTINE SET_NB_POINTS_TIL(HPROGRAM,HALG,PIO_FRAC,KPROC,KPIO,KSIZE_FULL,KLEFT,KRIGHT,KTOP,KBOTTOM,KINDEX)
!
USE MODD_DATA_COVER_PAR, ONLY : NVEGTYPE, JPCOVER
USE MODD_DATA_COVER, ONLY : XDATA_VEGTYPE
!
USE MODI_AV_PGD
!
IMPLICIT NONE
!
CHARACTER(LEN=6), INTENT(IN) :: HPROGRAM
CHARACTER(LEN=4), INTENT(IN) :: HALG
REAL, INTENT(IN) :: PIO_FRAC
INTEGER, INTENT(IN) :: KPROC
INTEGER, INTENT(IN) :: KPIO
INTEGER, INTENT(IN) :: KSIZE_FULL
INTEGER, DIMENSION(KSIZE_FULL), INTENT(IN) :: KLEFT
INTEGER, DIMENSION(KSIZE_FULL), INTENT(IN) :: KRIGHT
INTEGER, DIMENSION(KSIZE_FULL), INTENT(IN) :: KTOP 
INTEGER, DIMENSION(KSIZE_FULL), INTENT(IN) :: KBOTTOM
INTEGER, DIMENSION(KSIZE_FULL), INTENT(INOUT) :: KINDEX
!
REAL, DIMENSION(KSIZE_FULL) :: ZSEA
REAL, DIMENSION(KSIZE_FULL) :: ZWATER
REAL, DIMENSION(KSIZE_FULL) :: ZNATURE
REAL, DIMENSION(KSIZE_FULL) :: ZTOWN
REAL, DIMENSION(KSIZE_FULL, JPCOVER) :: ZCOVER
REAL, DIMENSION(KSIZE_FULL, NVEGTYPE) :: ZVEGTYPE
INTEGER, DIMENSION(KSIZE_FULL,2) :: ITYPE 
INTEGER,DIMENSION(4,10) :: ITYPE0
INTEGER, DIMENSION(KSIZE_FULL) :: IINDEX
INTEGER, DIMENSION(0:KPROC-1) :: ISIZE_TASK
INTEGER, DIMENSION(0:KPROC-1) :: INBPTS
INTEGER, DIMENSION(1) :: IPROCMIN
INTEGER :: IFULL, IRESP, J, I, K, JVEGTYPE, CPT, IN1, IN2
LOGICAL, DIMENSION(JPCOVER) :: GCOVER
LOGICAL :: GDATA_VEGTYPE
!
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
IF (LHOOK) CALL DR_HOOK('INIT_INDEX_MPI:SET_NB_POINTS_TIL',0,ZHOOK_HANDLE)
!
CALL INIT_IO_SURF_n(HPROGRAM,'FULL  ','SURF  ','READ ')
!
CALL READ_SURF(HPROGRAM,'FRAC_SEA   ',ZSEA,   IRESP, HDIR='A')
CALL READ_SURF(HPROGRAM,'FRAC_NATURE',ZNATURE,IRESP, HDIR='A')
CALL READ_SURF(HPROGRAM,'FRAC_WATER ',ZWATER, IRESP, HDIR='A')
CALL READ_SURF(HPROGRAM,'FRAC_TOWN  ',ZTOWN,  IRESP, HDIR='A')
!
CALL END_IO_SURF_n(HPROGRAM)
CALL INIT_IO_SURF_n(HPROGRAM,'NATURE','SURF  ','READ ')
CALL READ_SURF(HPROGRAM,'L_VEGTYPE',GDATA_VEGTYPE,IRESP,HDIR='A')
!
IF (GDATA_VEGTYPE) THEN
  CALL READ_SURF(HPROGRAM,'D_VEGTYPE',ZVEGTYPE(:,:),IRESP,HDIR='A')
  CALL END_IO_SURF_n(HPROGRAM)
ELSE
  CALL END_IO_SURF_n(HPROGRAM)
  CALL INIT_IO_SURF_n(HPROGRAM,'FULL  ','SURF  ','READ ')
  CALL READ_SURF(HPROGRAM,'COVER_LIST',GCOVER(:),IRESP,HDIR='A')
  CALL READ_SURF(HPROGRAM,'COVER',ZCOVER(:,:),GCOVER,IRESP,HDIR='A')
  DO JVEGTYPE=1,NVEGTYPE
    CALL AV_PGD (ZVEGTYPE(:,JVEGTYPE),ZCOVER,XDATA_VEGTYPE(:,JVEGTYPE),'NAT','ARI')
  END DO
ENDIF
!
CALL END_IO_SURF_n(HPROGRAM)
!
ITYPE(:,:) = 0
!
DO J=1,KSIZE_FULL
  !
  IF (ZSEA(J)/=0. .AND. ZNATURE(J)/=0. .AND. ZWATER(J)/=0. .AND. ZTOWN(J)/=0.) THEN ! 1 2 3 4
    ITYPE(J,1) = 1 
  ELSEIF (ZSEA(J)/=0. .AND. ZNATURE(J)/=0. .AND. ZWATER(J)/=0.) THEN ! 1 2 3
    ITYPE(J,1) = 2
  ELSEIF (ZSEA(J)/=0. .AND. ZNATURE(J)/=0. .AND. ZTOWN(J)/=0.) THEN ! 1 2 4
    ITYPE(J,1) = 3
  ELSEIF (ZSEA(J)/=0. .AND. ZWATER(J)/=0. .AND. ZTOWN(J)/=0.) THEN ! 1 3 4 
    ITYPE(J,1) = 4
  ELSEIF (ZNATURE(J)/=0. .AND. ZWATER(J)/=0. .AND. ZTOWN(J)/=0.) THEN ! 2 3 4
    ITYPE(J,1) = 5
  ELSEIF (ZSEA(J)/=0.) THEN 
    IF (ZNATURE(J)/=0.) THEN ! 1 2
      ITYPE(J,1) = 6
    ELSEIF (ZWATER(J)/=0.) THEN ! 1 3
      ITYPE(J,1) = 7
    ELSEIF (ZTOWN(J)/=0.) THEN ! 1 4
      ITYPE(J,1) = 8
    ELSE ! 1
      ITYPE(J,1) = 12
    ENDIF
  ELSEIF (ZNATURE(J)/=0.) THEN
    IF (ZWATER(J)/=0.) THEN ! 2 3
      ITYPE(J,1) = 9
    ELSEIF (ZTOWN(J)/=0.) THEN ! 2 4
      ITYPE(J,1) = 10
    ELSE ! 2
      ITYPE(J,1) = 13
    ENDIF
  ELSEIF (ZWATER(J)/=0.) THEN
    IF (ZTOWN(J)/=0.) THEN ! 3 4
      ITYPE(J,1) = 11
    ELSE ! 3
      ITYPE(J,1) = 14
    ENDIF
  ELSE ! 4
    ITYPE(J,1) = 15
  ENDIF
  !
ENDDO
!
!we give numbers to the 40 types of vegtypes
CPT = 0
DO I = 1,SIZE(ITYPE0,1)
  DO J = 1,SIZE(ITYPE0,2)
    CPT = CPT + 1
    ITYPE0(I,J) = CPT
  ENDDO
ENDDO
!
DO J=1,KSIZE_FULL
  IN1 = 0
  IN2 = 0
  DO I=1,3
    IF (ZVEGTYPE(J,I)/=0.) IN1 = IN1 +1
  ENDDO
  DO I=4,NVEGTYPE
    IF (ZVEGTYPE(J,I)/=0.) IN2 = IN2 +1
  ENDDO
  ITYPE(J,2) = ITYPE0(IN1+1,IN2+1)
ENDDO
!
KINDEX(:) = -1
!
DO I = 1,15
  !
  DO J = 1,40
    !
    IINDEX(:) = -2
    DO K=1,KSIZE_FULL
      IF (ITYPE(K,1)==I .AND. ITYPE(K,2)==J) IINDEX(K) = -1
    ENDDO
    !
    IFULL = COUNT(IINDEX(:)==-1)
    !
    IF (IFULL.NE.0) THEN
      !
      INBPTS(:) = 0
      DO K=1,SIZE(KINDEX)
        IF (KINDEX(K)>-1) INBPTS(KINDEX(K)) = INBPTS(KINDEX(K)) + 1
      ENDDO
      IF (PIO_FRAC/=0.) THEN 
        INBPTS(NPIO) = NINT (INBPTS(NPIO) / PIO_FRAC)
        IPROCMIN = MINLOC(INBPTS(0:KPROC-1)) - 1
      ELSEIF (KPROC>1) THEN
        IPROCMIN = MINLOC(INBPTS(1:KPROC-1))
      ELSE
        IPROCMIN(:) = 0
      ENDIF
      !
      IF (HALG=='TILL') THEN
        CALL SET_NB_POINTS_LIN(PIO_FRAC,KPROC,IPROCMIN(1),KPIO,IFULL,IINDEX(:))
      ELSEIF (HALG=='TILA') THEN
        CALL SET_NB_POINTS_ADJ(PIO_FRAC,KPROC,KPIO,IFULL,KSIZE_FULL,KLEFT,KRIGHT,KTOP,KBOTTOM,IINDEX(:))
      ENDIF
      !
      DO K=1,KSIZE_FULL
        IF ( IINDEX(K)> -1 ) KINDEX(K) = IINDEX(K)
      ENDDO
      !
   
    ENDIF
    !
  ENDDO
  !
ENDDO
!
IF (LHOOK) CALL DR_HOOK('INIT_INDEX_MPI:SET_NB_POINTS_TIL',1,ZHOOK_HANDLE)
!
END SUBROUTINE SET_NB_POINTS_TIL
!
!
!
END SUBROUTINE INIT_INDEX_MPI
