MODULE MODD_OFF_SURFEX_n
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
USE MODD_TEB_PAR, ONLY : NTEB_PATCH_MAX
!
USE MODD_SURFEX_n, ONLY : SURFEX_t
!
USE MODD_AGRI_n, ONLY : AGRI_INIT
USE MODD_BEM_OPTION_n, ONLY : BEM_OPTIONS_INIT
USE MODD_BLD_DESCRIPTION_n, ONLY : BLD_DESC_INIT
USE MODD_CH_EMIS_FIELD_n, ONLY : CH_EMIS_FIELD_INIT
USE MODD_CH_FLAKE_n, ONLY : CH_FLAKE_INIT
USE MODD_CH_ISBA_n, ONLY : CH_ISBA_INIT
USE MODD_CH_SEAFLUX_n, ONLY : CH_SEAFLUX_INIT
USE MODD_CH_SNAP_n, ONLY : CH_EMIS_SNAP_INIT
USE MODD_CH_SURF_n, ONLY : CH_SURF_INIT
USE MODD_CH_TEB_n, ONLY : CH_TEB_INIT
USE MODD_CH_WATFLUX_n, ONLY : CH_WATFLUX_INIT
USE MODD_DATA_BEM_n, ONLY : DATA_BEM_INIT
USE MODD_DATA_COVER_n, ONLY : DATA_COVER_INIT
USE MODD_DATA_ISBA_n, ONLY : DATA_ISBA_INIT
USE MODD_DATA_SEAFLUX_n, ONLY : DATA_SEAFLUX_INIT
USE MODD_DATA_TEB_GARDEN_n, ONLY : DATA_TEB_GARDEN_INIT
USE MODD_DATA_TEB_GREENROOF_n, ONLY : DATA_TEB_GREENROOF_INIT
USE MODD_DATA_TEB_n, ONLY : DATA_TEB_INIT
USE MODD_DATA_TSZ0_n, ONLY : DATA_TSZ0_INIT
USE MODD_DIAG_EVAP_ISBA_n, ONLY : DIAG_EVAP_ISBA_INIT
USE MODD_DIAG_FLAKE_n, ONLY : DIAG_FLAKE_INIT
USE MODD_DIAG_IDEAL_n, ONLY : DIAG_IDEAL_INIT
USE MODD_DIAG_ISBA_n, ONLY : DIAG_ISBA_INIT
USE MODD_DIAG_MISC_FLAKE_n, ONLY : DIAG_MISC_FLAKE_INIT
USE MODD_DIAG_MISC_ISBA_n, ONLY : DIAG_MISC_ISBA_INIT
USE MODD_DIAG_MISC_TEB_OPTION_n, ONLY : DIAG_MISC_TEB_OPTIONS_INIT
USE MODD_DIAG_OCEAN_n, ONLY : DIAG_OCEAN_INIT
USE MODD_DIAG_SEAFLUX_n, ONLY : DIAG_SEAFLUX_INIT
USE MODD_DIAG_SEAICE_n, ONLY : DIAG_SEAICE_INIT
USE MODD_DIAG_SURF_ATM_n, ONLY : DIAG_SURF_ATM_INIT
USE MODD_DIAG_TEB_GARDEN_n, ONLY : DIAG_TEB_GARDEN_INIT
USE MODD_DIAG_TEB_GREENROOF_n, ONLY : DIAG_TEB_GREENROOF_INIT
USE MODD_DIAG_TEB_n, ONLY : DIAG_TEB_INIT
USE MODD_DIAG_UTCI_TEB_n, ONLY : DIAG_UTCI_TEB_INIT
USE MODD_DIAG_WATFLUX_n, ONLY : DIAG_WATFLUX_INIT
USE MODD_DST_n, ONLY : DST_INIT
USE MODD_DUMMY_SURF_FIELDS_n, ONLY : DUMMY_SURF_FIELDS_INIT
USE MODD_EMIS_GR_FIELD_n, ONLY : EMIS_GR_FIELD_INIT
USE MODD_FLAKE_GRID_n, ONLY : FLAKE_GRID_INIT
USE MODD_FLAKE_n, ONLY : FLAKE_INIT
USE MODD_FLAKE_SBL_n, ONLY : FLAKE_SBL_INIT
USE MODD_GR_BIOG_GARDEN_n, ONLY : GR_BIOG_GARDEN_INIT
USE MODD_GR_BIOG_GREENROOF_n, ONLY : GR_BIOG_GREENROOF_INIT
USE MODD_GR_BIOG_n, ONLY : GR_BIOG_INIT
USE MODD_IDEAL_n, ONLY : IDEAL_INIT
USE MODD_ISBA_CANOPY_n, ONLY : ISBA_CANOPY_INIT
USE MODD_ISBA_GRID_n, ONLY : ISBA_GRID_INIT
USE MODD_ISBA_n, ONLY : ISBA_INIT
USE MODD_OCEAN_n, ONLY : OCEAN_INIT
USE MODD_OCEAN_REL_n, ONLY : OCEAN_REL_INIT
USE MODD_PACK_CH_ISBA, ONLY : PACK_CH_ISBA_INIT
USE MODD_PACK_DIAG_ISBA, ONLY : PACK_DIAG_ISBA_INIT
USE MODD_PACK_ISBA, ONLY : PACK_ISBA_INIT
USE MODD_SEAFLUX_GRID_n, ONLY : SEAFLUX_GRID_INIT
USE MODD_SEAFLUX_n, ONLY : SEAFLUX_INIT
USE MODD_SEAFLUX_SBL_n, ONLY : SEAFLUX_SBL_INIT
USE MODD_SLT_n, ONLY : SLT_INIT
USE MODD_SSO_CANOPY_n, ONLY : SSO_CANOPY_INIT
USE MODD_SURF_ATM_GRID_n, ONLY : SURF_ATM_GRID_INIT
USE MODD_SURF_ATM_n, ONLY : SURF_ATM_INIT
USE MODD_SURF_ATM_SSO_n, ONLY : SURF_ATM_SSO_INIT
USE MODD_SV_n, ONLY : SV_INIT
USE MODD_TEB_CANOPY_n, ONLY : TEB_CANOPY_INIT
USE MODD_TEB_GARDEN_OPTION_n, ONLY : TEB_GARDEN_OPTIONS_INIT
USE MODD_TEB_GARDEN_PGD_n, ONLY : TEB_GARDEN_PGD_INIT
USE MODD_TEB_GREENROOF_OPTION_n, ONLY : TEB_GREENROOF_OPTIONS_INIT
USE MODD_TEB_GREENROOF_PGD_n, ONLY : TEB_GREENROOF_PGD_INIT
USE MODD_TEB_GRID_n, ONLY : TEB_GRID_INIT
USE MODD_TEB_IRRIG_n, ONLY : TEB_IRRIG_INIT
USE MODD_TEB_OPTION_n, ONLY : TEB_OPTIONS_INIT
USE MODD_TEB_PANEL_n, ONLY : TEB_PANEL_INIT
USE MODD_TEB_VEG_n, ONLY : TEB_VEG_OPTIONS_INIT
USE MODD_TRIP, ONLY : TRIP_INIT
USE MODD_TRIP_GRID, ONLY : TRIP_GRID_INIT
USE MODD_TRIP_DIAG, ONLY : TRIP_DIAG_INIT
USE MODD_WATFLUX_GRID_n, ONLY : WATFLUX_GRID_INIT
USE MODD_WATFLUX_n, ONLY : WATFLUX_INIT
USE MODD_WATFLUX_SBL_n, ONLY : WATFLUX_SBL_INIT
!
USE MODD_BEM_n, ONLY : BEM_INIT
USE MODD_DIAG_CUMUL_TEB_n, ONLY : DIAG_CUMUL_TEB_INIT
USE MODD_DIAG_MISC_TEB_n, ONLY : DIAG_MISC_TEB_INIT
USE MODD_TEB_GARDEN_n, ONLY : TEB_GARDEN_INIT
USE MODD_TEB_GARDEN_PGD_EVOL_n, ONLY : TEB_GARDEN_PGD_EVOL_INIT
USE MODD_TEB_GREENROOF_n, ONLY : TEB_GREENROOF_INIT
USE MODD_TEB_GREENROOF_PGD_EVOL_n, ONLY : TEB_GREENROOF_PGD_EVOL_INIT
USE MODD_TEB_n, ONLY : TEB_INIT
!
USE MODE_MODELN_SURFEX_HANDLER 
!
TYPE(SURFEX_t), ALLOCATABLE, TARGET, SAVE :: YSURF_LIST(:)
TYPE(SURFEX_t), POINTER :: YSURF_CUR => NULL()
!$OMP THREADPRIVATE(YSURF_CUR)
!
CONTAINS
!
SUBROUTINE GOTO_MODEL(KMODEL)

INTEGER, INTENT(IN) :: KMODEL
REAL(KIND=JPRB) :: ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK("MODD_OFF_SURFEX_n:GOTO_MODEL",0,ZHOOK_HANDLE)
!
YSURF_CUR => YSURF_LIST(KMODEL)
ICURRENT_MODEL = KMODEL
!
IF (LHOOK) CALL DR_HOOK("MODD_OFF_SURFEX_n:GOTO_MODEL",1,ZHOOK_HANDLE)
!
END SUBROUTINE GOTO_MODEL
!
!
SUBROUTINE SURFEX_ALLOC(KMODEL)
!
INTEGER, INTENT(IN) :: KMODEL
INTEGER :: J
REAL(KIND=JPRB) :: ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK("MODD_OFF_SURFEX_n:SURFEX_ALLOC",0,ZHOOK_HANDLE)
!
CALL INIT_CURRENT_MODEL_INDEX_SURFEX()
!
ALLOCATE(YSURF_LIST(KMODEL))
!
DO J = 1,KMODEL
  !
  CALL AGRI_INIT(YSURF_LIST(J)%AG)
  CALL BEM_OPTIONS_INIT(YSURF_LIST(J)%BOP)
  CALL BLD_DESC_INIT(YSURF_LIST(J)%BDD)
  CALL CH_EMIS_FIELD_INIT(YSURF_LIST(J)%CHE)
  CALL CH_FLAKE_INIT(YSURF_LIST(J)%CHF)
  CALL CH_ISBA_INIT(YSURF_LIST(J)%CHI)
  CALL CH_SEAFLUX_INIT(YSURF_LIST(J)%CHS)
  CALL CH_EMIS_SNAP_INIT(YSURF_LIST(J)%CHN)
  CALL CH_SURF_INIT(YSURF_LIST(J)%CHU)
  CALL CH_TEB_INIT(YSURF_LIST(J)%CHT)
  CALL CH_WATFLUX_INIT(YSURF_LIST(J)%CHW)
  CALL DATA_BEM_INIT(YSURF_LIST(J)%DTB)
  CALL DATA_COVER_INIT(YSURF_LIST(J)%DTCO)
  CALL DATA_ISBA_INIT(YSURF_LIST(J)%DTI)
  CALL DATA_SEAFLUX_INIT(YSURF_LIST(J)%DTS)
  CALL DATA_TEB_GARDEN_INIT(YSURF_LIST(J)%DTGD)
  CALL DATA_TEB_GREENROOF_INIT(YSURF_LIST(J)%DTGR)
  CALL DATA_TEB_INIT(YSURF_LIST(J)%DTT)
  CALL DATA_TSZ0_INIT(YSURF_LIST(J)%DTZ)
  CALL DIAG_EVAP_ISBA_INIT(YSURF_LIST(J)%DGEI)
  CALL DIAG_FLAKE_INIT(YSURF_LIST(J)%DGF)
  CALL DIAG_IDEAL_INIT(YSURF_LIST(J)%DGL)
  CALL DIAG_ISBA_INIT(YSURF_LIST(J)%DGI)
  CALL DIAG_MISC_FLAKE_INIT(YSURF_LIST(J)%DGMF)
  CALL DIAG_MISC_ISBA_INIT(YSURF_LIST(J)%DGMI)
  CALL DIAG_MISC_TEB_OPTIONS_INIT(YSURF_LIST(J)%DGMTO)
  CALL DIAG_OCEAN_INIT(YSURF_LIST(J)%DGO)
  CALL DIAG_SEAFLUX_INIT(YSURF_LIST(J)%DGS)
  CALL DIAG_SEAICE_INIT(YSURF_LIST(J)%DGSI)
  CALL DIAG_SURF_ATM_INIT(YSURF_LIST(J)%DGU)
  CALL DIAG_TEB_GARDEN_INIT(YSURF_LIST(J)%DGTGD)
  CALL DIAG_TEB_GREENROOF_INIT(YSURF_LIST(J)%DGTGR)
  CALL DIAG_TEB_INIT(YSURF_LIST(J)%DGT)
  CALL DIAG_UTCI_TEB_INIT(YSURF_LIST(J)%DGUT)
  CALL DIAG_WATFLUX_INIT(YSURF_LIST(J)%DGW)
  CALL DST_INIT(YSURF_LIST(J)%DST)
  CALL DUMMY_SURF_FIELDS_INIT(YSURF_LIST(J)%DUU)
  CALL EMIS_GR_FIELD_INIT(YSURF_LIST(J)%EGF)
  CALL FLAKE_GRID_INIT(YSURF_LIST(J)%FG)
  CALL FLAKE_INIT(YSURF_LIST(J)%F)
  CALL FLAKE_SBL_INIT(YSURF_LIST(J)%FSB)
  CALL GR_BIOG_GARDEN_INIT(YSURF_LIST(J)%GBGD)
  CALL GR_BIOG_GREENROOF_INIT(YSURF_LIST(J)%GBGR)
  CALL GR_BIOG_INIT(YSURF_LIST(J)%GB)
  CALL IDEAL_INIT(YSURF_LIST(J)%L)
  CALL ISBA_CANOPY_INIT(YSURF_LIST(J)%ICP)
  CALL ISBA_GRID_INIT(YSURF_LIST(J)%IG)
  CALL ISBA_INIT(YSURF_LIST(J)%I)
  CALL OCEAN_INIT(YSURF_LIST(J)%O)
  CALL OCEAN_REL_INIT(YSURF_LIST(J)%OR)
  CALL PACK_CH_ISBA_INIT(YSURF_LIST(J)%PKCI)
  CALL PACK_DIAG_ISBA_INIT(YSURF_LIST(J)%PKDI)
  CALL PACK_ISBA_INIT(YSURF_LIST(J)%PKI)
  CALL SEAFLUX_GRID_INIT(YSURF_LIST(J)%SG)
  CALL SEAFLUX_INIT(YSURF_LIST(J)%S)
  CALL SEAFLUX_SBL_INIT(YSURF_LIST(J)%SSB)
  CALL SLT_INIT(YSURF_LIST(J)%SLT)
  CALL SSO_CANOPY_INIT(YSURF_LIST(J)%SSCP)
  CALL SURF_ATM_GRID_INIT(YSURF_LIST(J)%UG)
  CALL SURF_ATM_INIT(YSURF_LIST(J)%U)
  CALL SURF_ATM_SSO_INIT(YSURF_LIST(J)%USS)
  CALL SV_INIT(YSURF_LIST(J)%SV)
  CALL TEB_CANOPY_INIT(YSURF_LIST(J)%TCP)
  CALL TEB_GARDEN_OPTIONS_INIT(YSURF_LIST(J)%TGDO)
  CALL TEB_GARDEN_PGD_INIT(YSURF_LIST(J)%TGDP)
  CALL TEB_GREENROOF_OPTIONS_INIT(YSURF_LIST(J)%TGRO)
  CALL TEB_GREENROOF_PGD_INIT(YSURF_LIST(J)%TGRP)
  CALL TEB_GRID_INIT(YSURF_LIST(J)%TG)
  CALL TEB_IRRIG_INIT(YSURF_LIST(J)%TIR)
  CALL TEB_OPTIONS_INIT(YSURF_LIST(J)%TOP)
  CALL TEB_PANEL_INIT(YSURF_LIST(J)%TPN)
  CALL TEB_VEG_OPTIONS_INIT(YSURF_LIST(J)%TVG)
  CALL TRIP_INIT(YSURF_LIST(J)%TP)
  CALL TRIP_GRID_INIT(YSURF_LIST(J)%TPG)
  CALL TRIP_DIAG_INIT(YSURF_LIST(J)%TPDG)
  CALL WATFLUX_GRID_INIT(YSURF_LIST(J)%WG)
  CALL WATFLUX_INIT(YSURF_LIST(J)%W)
  CALL WATFLUX_SBL_INIT(YSURF_LIST(J)%WSB)
  !
  CALL BEM_INIT(YSURF_LIST(J)%B,NTEB_PATCH_MAX)
  CALL DIAG_CUMUL_TEB_INIT(YSURF_LIST(J)%DGCT,NTEB_PATCH_MAX)
  CALL DIAG_MISC_TEB_INIT(YSURF_LIST(J)%DGMT,NTEB_PATCH_MAX)
  CALL TEB_GARDEN_INIT(YSURF_LIST(J)%TGD,NTEB_PATCH_MAX)
  CALL TEB_GARDEN_PGD_EVOL_INIT(YSURF_LIST(J)%TGDPE,NTEB_PATCH_MAX)
  CALL TEB_GREENROOF_INIT(YSURF_LIST(J)%TGR,NTEB_PATCH_MAX)
  CALL TEB_GREENROOF_PGD_EVOL_INIT(YSURF_LIST(J)%TGRPE,NTEB_PATCH_MAX)
  CALL TEB_INIT(YSURF_LIST(J)%T,NTEB_PATCH_MAX)  
  !
ENDDO
!
IF (LHOOK) CALL DR_HOOK("MODD_OFF_SURFEX_n:SURFEX_ALLOC",1,ZHOOK_HANDLE)
!
END SUBROUTINE SURFEX_ALLOC
!
SUBROUTINE SURFEX_DEALLO
!
REAL(KIND=JPRB) :: ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK("MODD_OFF_SURFEX_n:SURFEX_DEALLO",0,ZHOOK_HANDLE)
!
IF (ALLOCATED(YSURF_LIST)) DEALLOCATE(YSURF_LIST)
IF (ASSOCIATED(YSURF_CUR)) NULLIFY(YSURF_CUR)
!
IF (LHOOK) CALL DR_HOOK("MODD_OFF_SURFEX_n:SURFEX_DEALLO",1,ZHOOK_HANDLE)
!
END SUBROUTINE SURFEX_DEALLO
!
END MODULE MODD_OFF_SURFEX_n
