MODULE MODD_OFF_SURFEX_n
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
USE MODD_TEB_PAR, ONLY : NTEB_PATCH_MAX
!
USE MODD_SURFEX_n, ONLY : SURFEX_t
!
USE MODD_AGRI_n, ONLY : AGRI_INIT
USE MODD_BEM_OPTION_n, ONLY : BEM_OPTIONS_INIT
USE MODD_BLD_DESCRIPTION_n, ONLY : BLD_DESC_INIT
USE MODD_CH_EMIS_FIELD_n, ONLY : CH_EMIS_FIELD_INIT
USE MODD_CH_FLAKE_n, ONLY : CH_FLAKE_INIT
USE MODD_CH_ISBA_n, ONLY : CH_ISBA_INIT
USE MODD_CH_SEAFLUX_n, ONLY : CH_SEAFLUX_INIT
USE MODD_CH_SNAP_n, ONLY : CH_EMIS_SNAP_INIT
USE MODD_CH_SURF_n, ONLY : CH_SURF_INIT
USE MODD_CH_TEB_n, ONLY : CH_TEB_INIT
USE MODD_CH_WATFLUX_n, ONLY : CH_WATFLUX_INIT
USE MODD_DATA_BEM_n, ONLY : DATA_BEM_INIT
USE MODD_DATA_COVER_n, ONLY : DATA_COVER_INIT
USE MODD_DATA_ISBA_n, ONLY : DATA_ISBA_INIT
USE MODD_DATA_SEAFLUX_n, ONLY : DATA_SEAFLUX_INIT
USE MODD_DATA_TEB_GARDEN_n, ONLY : DATA_TEB_GARDEN_INIT
USE MODD_DATA_TEB_GREENROOF_n, ONLY : DATA_TEB_GREENROOF_INIT
USE MODD_DATA_TEB_n, ONLY : DATA_TEB_INIT
USE MODD_DATA_TSZ0_n, ONLY : DATA_TSZ0_INIT
USE MODD_DIAG_EVAP_ISBA_n, ONLY : DIAG_EVAP_ISBA_INIT
USE MODD_DIAG_FLAKE_n, ONLY : DIAG_FLAKE_INIT
USE MODD_DIAG_IDEAL_n, ONLY : DIAG_IDEAL_INIT
USE MODD_DIAG_ISBA_n, ONLY : DIAG_ISBA_INIT
USE MODD_DIAG_MISC_FLAKE_n, ONLY : DIAG_MISC_FLAKE_INIT
USE MODD_DIAG_MISC_ISBA_n, ONLY : DIAG_MISC_ISBA_INIT
USE MODD_DIAG_MISC_TEB_OPTION_n, ONLY : DIAG_MISC_TEB_OPTIONS_INIT
USE MODD_DIAG_OCEAN_n, ONLY : DIAG_OCEAN_INIT
USE MODD_DIAG_SEAFLUX_n, ONLY : DIAG_SEAFLUX_INIT
USE MODD_DIAG_SEAICE_n, ONLY : DIAG_SEAICE_INIT
USE MODD_DIAG_SURF_ATM_n, ONLY : DIAG_SURF_ATM_INIT
USE MODD_DIAG_TEB_GARDEN_n, ONLY : DIAG_TEB_GARDEN_INIT
USE MODD_DIAG_TEB_GREENROOF_n, ONLY : DIAG_TEB_GREENROOF_INIT
USE MODD_DIAG_TEB_n, ONLY : DIAG_TEB_INIT
USE MODD_DIAG_UTCI_TEB_n, ONLY : DIAG_UTCI_TEB_INIT
USE MODD_DIAG_WATFLUX_n, ONLY : DIAG_WATFLUX_INIT
USE MODD_DST_n, ONLY : DST_INIT
USE MODD_DUMMY_SURF_FIELDS_n, ONLY : DUMMY_SURF_FIELDS_INIT
USE MODD_EMIS_GR_FIELD_n, ONLY : EMIS_GR_FIELD_INIT
USE MODD_FLAKE_GRID_n, ONLY : FLAKE_GRID_INIT
USE MODD_FLAKE_n, ONLY : FLAKE_INIT
USE MODD_FLAKE_SBL_n, ONLY : FLAKE_SBL_INIT
USE MODD_GR_BIOG_GARDEN_n, ONLY : GR_BIOG_GARDEN_INIT
USE MODD_GR_BIOG_GREENROOF_n, ONLY : GR_BIOG_GREENROOF_INIT
USE MODD_GR_BIOG_n, ONLY : GR_BIOG_INIT
USE MODD_IDEAL_n, ONLY : IDEAL_INIT
USE MODD_ISBA_CANOPY_n, ONLY : ISBA_CANOPY_INIT
USE MODD_ISBA_GRID_n, ONLY : ISBA_GRID_INIT
USE MODD_ISBA_n, ONLY : ISBA_INIT
USE MODD_OCEAN_n, ONLY : OCEAN_INIT
USE MODD_OCEAN_REL_n, ONLY : OCEAN_REL_INIT
USE MODD_PACK_CH_ISBA, ONLY : PACK_CH_ISBA_INIT
USE MODD_PACK_DIAG_ISBA, ONLY : PACK_DIAG_ISBA_INIT
USE MODD_PACK_ISBA, ONLY : PACK_ISBA_INIT
USE MODD_SEAFLUX_GRID_n, ONLY : SEAFLUX_GRID_INIT
USE MODD_SEAFLUX_n, ONLY : SEAFLUX_INIT
USE MODD_SEAFLUX_SBL_n, ONLY : SEAFLUX_SBL_INIT
USE MODD_SLT_n, ONLY : SLT_INIT
USE MODD_SSO_CANOPY_n, ONLY : SSO_CANOPY_INIT
USE MODD_SURF_ATM_GRID_n, ONLY : SURF_ATM_GRID_INIT
USE MODD_SURF_ATM_n, ONLY : SURF_ATM_INIT
USE MODD_SURF_ATM_SSO_n, ONLY : SURF_ATM_SSO_INIT
USE MODD_SV_n, ONLY : SV_INIT
USE MODD_TEB_CANOPY_n, ONLY : TEB_CANOPY_INIT
USE MODD_TEB_GARDEN_OPTION_n, ONLY : TEB_GARDEN_OPTIONS_INIT
USE MODD_TEB_GARDEN_PGD_n, ONLY : TEB_GARDEN_PGD_INIT
USE MODD_TEB_GREENROOF_OPTION_n, ONLY : TEB_GREENROOF_OPTIONS_INIT
USE MODD_TEB_GREENROOF_PGD_n, ONLY : TEB_GREENROOF_PGD_INIT
USE MODD_TEB_GRID_n, ONLY : TEB_GRID_INIT
USE MODD_TEB_IRRIG_n, ONLY : TEB_IRRIG_INIT
USE MODD_TEB_OPTION_n, ONLY : TEB_OPTIONS_INIT
USE MODD_TEB_PANEL_n, ONLY : TEB_PANEL_INIT
USE MODD_TEB_VEG_n, ONLY : TEB_VEG_OPTIONS_INIT
USE MODD_TRIP, ONLY : TRIP_INIT
USE MODD_TRIP_GRID, ONLY : TRIP_GRID_INIT
USE MODD_TRIP_DIAG, ONLY : TRIP_DIAG_INIT
USE MODD_WATFLUX_GRID_n, ONLY : WATFLUX_GRID_INIT
USE MODD_WATFLUX_n, ONLY : WATFLUX_INIT
USE MODD_WATFLUX_SBL_n, ONLY : WATFLUX_SBL_INIT
!
USE MODD_BEM_n, ONLY : BEM_INIT
USE MODD_DIAG_CUMUL_TEB_n, ONLY : DIAG_CUMUL_TEB_INIT
USE MODD_DIAG_MISC_TEB_n, ONLY : DIAG_MISC_TEB_INIT
USE MODD_TEB_GARDEN_n, ONLY : TEB_GARDEN_INIT
USE MODD_TEB_GARDEN_PGD_EVOL_n, ONLY : TEB_GARDEN_PGD_EVOL_INIT
USE MODD_TEB_GREENROOF_n, ONLY : TEB_GREENROOF_INIT
USE MODD_TEB_GREENROOF_PGD_EVOL_n, ONLY : TEB_GREENROOF_PGD_EVOL_INIT
USE MODD_TEB_n, ONLY : TEB_INIT
!
USE MODE_MODELN_SURFEX_HANDLER 
!
TYPE(SURFEX_t), ALLOCATABLE, TARGET, SAVE :: YSURF_LIST(:)
TYPE(SURFEX_t), POINTER :: YSURF_CUR => NULL()
!$OMP THREADPRIVATE(YSURF_CUR)
!
CONTAINS
!
SUBROUTINE GOTO_MODEL(KMODEL)

INTEGER, INTENT(IN) :: KMODEL
REAL(KIND=JPRB) :: ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK("MODD_OFF_SURFEX_n:GOTO_MODEL",0,ZHOOK_HANDLE)
!
YSURF_CUR => YSURF_LIST(KMODEL)
ICURRENT_MODEL = KMODEL
!
IF (LHOOK) CALL DR_HOOK("MODD_OFF_SURFEX_n:GOTO_MODEL",1,ZHOOK_HANDLE)
!
END SUBROUTINE GOTO_MODEL
!
!
SUBROUTINE SURFEX_ALLOC(KMODEL)
!
INTEGER, INTENT(IN) :: KMODEL
INTEGER :: J
REAL(KIND=JPRB) :: ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK("MODD_OFF_SURFEX_n:SURFEX_ALLOC",0,ZHOOK_HANDLE)
!
CALL INIT_CURRENT_MODEL_INDEX_SURFEX()
!
ALLOCATE(YSURF_LIST(KMODEL))
!
DO J = 1,KMODEL
  !
  CALL CH_FLAKE_INIT(YSURF_LIST(J)%FM%CHF)
  CALL DIAG_FLAKE_INIT(YSURF_LIST(J)%FM%DGF)
  CALL DIAG_MISC_FLAKE_INIT(YSURF_LIST(J)%FM%DGMF)
  CALL FLAKE_GRID_INIT(YSURF_LIST(J)%FM%FG)
  CALL FLAKE_INIT(YSURF_LIST(J)%FM%F)
  CALL FLAKE_SBL_INIT(YSURF_LIST(J)%FM%FSB)
  !  
  CALL CH_WATFLUX_INIT(YSURF_LIST(J)%WM%CHW)
  CALL DIAG_WATFLUX_INIT(YSURF_LIST(J)%WM%DGW)
  CALL WATFLUX_GRID_INIT(YSURF_LIST(J)%WM%WG)
  CALL WATFLUX_INIT(YSURF_LIST(J)%WM%W)
  CALL WATFLUX_SBL_INIT(YSURF_LIST(J)%WM%WSB)
  !
  CALL CH_SEAFLUX_INIT(YSURF_LIST(J)%SM%CHS)
  CALL DATA_SEAFLUX_INIT(YSURF_LIST(J)%SM%DTS)
  CALL DIAG_OCEAN_INIT(YSURF_LIST(J)%SM%DGO)
  CALL DIAG_SEAFLUX_INIT(YSURF_LIST(J)%SM%DGS)
  CALL DIAG_SEAICE_INIT(YSURF_LIST(J)%SM%DGSI)
  CALL OCEAN_INIT(YSURF_LIST(J)%SM%O)
  CALL OCEAN_REL_INIT(YSURF_LIST(J)%SM%OR)
  CALL SEAFLUX_GRID_INIT(YSURF_LIST(J)%SM%SG)
  CALL SEAFLUX_INIT(YSURF_LIST(J)%SM%S)
  CALL SEAFLUX_SBL_INIT(YSURF_LIST(J)%SM%SSB)
  !
  CALL AGRI_INIT(YSURF_LIST(J)%IM%AG)
  CALL CH_ISBA_INIT(YSURF_LIST(J)%IM%CHI)
  CALL DATA_ISBA_INIT(YSURF_LIST(J)%IM%DTI)
  CALL DIAG_EVAP_ISBA_INIT(YSURF_LIST(J)%IM%DGEI)
  CALL DIAG_ISBA_INIT(YSURF_LIST(J)%IM%DGI)
  CALL DIAG_MISC_ISBA_INIT(YSURF_LIST(J)%IM%DGMI)
  CALL GR_BIOG_INIT(YSURF_LIST(J)%IM%GB)
  CALL ISBA_CANOPY_INIT(YSURF_LIST(J)%IM%ICP)
  CALL ISBA_GRID_INIT(YSURF_LIST(J)%IM%IG)
  CALL ISBA_INIT(YSURF_LIST(J)%IM%I)
  CALL PACK_CH_ISBA_INIT(YSURF_LIST(J)%IM%PKCI)
  CALL PACK_DIAG_ISBA_INIT(YSURF_LIST(J)%IM%PKDI)
  CALL PACK_ISBA_INIT(YSURF_LIST(J)%IM%PKI)
  !
  CALL TEB_VEG_OPTIONS_INIT(YSURF_LIST(J)%GDM%TVG)    
  CALL DATA_TEB_GARDEN_INIT(YSURF_LIST(J)%GDM%DTGD)
  CALL DIAG_TEB_GARDEN_INIT(YSURF_LIST(J)%GDM%DGTGD)
  CALL GR_BIOG_GARDEN_INIT(YSURF_LIST(J)%GDM%GBGD)
  CALL TEB_GARDEN_OPTIONS_INIT(YSURF_LIST(J)%GDM%TGDO)
  CALL TEB_GARDEN_PGD_INIT(YSURF_LIST(J)%GDM%TGDP)
  CALL TEB_GARDEN_INIT(YSURF_LIST(J)%GDM%TGD,NTEB_PATCH_MAX)
  CALL TEB_GARDEN_PGD_EVOL_INIT(YSURF_LIST(J)%GDM%TGDPE,NTEB_PATCH_MAX) 
  CALL TEB_IRRIG_INIT(YSURF_LIST(J)%GDM%TIR)    
  !
  CALL DATA_TEB_GREENROOF_INIT(YSURF_LIST(J)%GRM%DTGR)
  CALL DIAG_TEB_GREENROOF_INIT(YSURF_LIST(J)%GRM%DGTGR)
  CALL GR_BIOG_GREENROOF_INIT(YSURF_LIST(J)%GRM%GBGR)  
  CALL TEB_GREENROOF_OPTIONS_INIT(YSURF_LIST(J)%GRM%TGRO)
  CALL TEB_GREENROOF_PGD_INIT(YSURF_LIST(J)%GRM%TGRP)
  CALL TEB_GREENROOF_INIT(YSURF_LIST(J)%GRM%TGR,NTEB_PATCH_MAX)
  CALL TEB_GREENROOF_PGD_EVOL_INIT(YSURF_LIST(J)%GRM%TGRPE,NTEB_PATCH_MAX)
  !
  CALL CH_TEB_INIT(YSURF_LIST(J)%TM%CHT)
  CALL DATA_TEB_INIT(YSURF_LIST(J)%TM%DTT)
  CALL DIAG_MISC_TEB_OPTIONS_INIT(YSURF_LIST(J)%TM%DGMTO)
  CALL DIAG_TEB_INIT(YSURF_LIST(J)%TM%DGT)
  CALL DIAG_UTCI_TEB_INIT(YSURF_LIST(J)%TM%DGUT)
  CALL TEB_CANOPY_INIT(YSURF_LIST(J)%TM%TCP)
  CALL TEB_GRID_INIT(YSURF_LIST(J)%TM%TG)
  CALL TEB_OPTIONS_INIT(YSURF_LIST(J)%TM%TOP)
  CALL TEB_PANEL_INIT(YSURF_LIST(J)%TM%TPN)
  CALL DIAG_CUMUL_TEB_INIT(YSURF_LIST(J)%TM%DGCT,NTEB_PATCH_MAX)
  CALL DIAG_MISC_TEB_INIT(YSURF_LIST(J)%TM%DGMT,NTEB_PATCH_MAX)
  CALL TEB_INIT(YSURF_LIST(J)%TM%T,NTEB_PATCH_MAX)  
  !
  CALL BLD_DESC_INIT(YSURF_LIST(J)%TM%BDD)
  CALL BEM_OPTIONS_INIT(YSURF_LIST(J)%TM%BOP)
  CALL DATA_BEM_INIT(YSURF_LIST(J)%TM%DTB)  
  CALL BEM_INIT(YSURF_LIST(J)%TM%B,NTEB_PATCH_MAX)  
  !
  CALL DATA_COVER_INIT(YSURF_LIST(J)%DTCO)
  CALL DATA_TSZ0_INIT(YSURF_LIST(J)%DTZ)
  CALL DUMMY_SURF_FIELDS_INIT(YSURF_LIST(J)%DUU)
  !
  CALL SURF_ATM_GRID_INIT(YSURF_LIST(J)%UG)
  CALL SURF_ATM_INIT(YSURF_LIST(J)%U)
  CALL DIAG_SURF_ATM_INIT(YSURF_LIST(J)%DGU)  
  CALL SURF_ATM_SSO_INIT(YSURF_LIST(J)%USS)
  CALL SSO_CANOPY_INIT(YSURF_LIST(J)%SSCP)
  !
  CALL DIAG_IDEAL_INIT(YSURF_LIST(J)%DGL)
  CALL IDEAL_INIT(YSURF_LIST(J)%L)
  !
  CALL SV_INIT(YSURF_LIST(J)%SV)
  CALL CH_SURF_INIT(YSURF_LIST(J)%CHU)  
  CALL CH_EMIS_FIELD_INIT(YSURF_LIST(J)%CHE)
  CALL CH_EMIS_SNAP_INIT(YSURF_LIST(J)%CHN)
  CALL EMIS_GR_FIELD_INIT(YSURF_LIST(J)%EGF)  
  CALL DST_INIT(YSURF_LIST(J)%DST)
  CALL SLT_INIT(YSURF_LIST(J)%SLT)
  !
  CALL TRIP_INIT(YSURF_LIST(J)%TP)
  CALL TRIP_GRID_INIT(YSURF_LIST(J)%TPG)
  CALL TRIP_DIAG_INIT(YSURF_LIST(J)%TPDG)
  !
  !
ENDDO
!
IF (LHOOK) CALL DR_HOOK("MODD_OFF_SURFEX_n:SURFEX_ALLOC",1,ZHOOK_HANDLE)
!
END SUBROUTINE SURFEX_ALLOC
!
SUBROUTINE SURFEX_DEALLO
!
USE MODI_DEALLOC_SURF_ATM_n
!
REAL(KIND=JPRB) :: ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK("MODD_OFF_SURFEX_n:SURFEX_DEALLO",0,ZHOOK_HANDLE)
!
CALL DEALLOC_SURF_ATM_n(YSURF_CUR)
IF (ALLOCATED(YSURF_LIST)) DEALLOCATE(YSURF_LIST)
IF (ASSOCIATED(YSURF_CUR)) NULLIFY(YSURF_CUR)
!
IF (LHOOK) CALL DR_HOOK("MODD_OFF_SURFEX_n:SURFEX_DEALLO",1,ZHOOK_HANDLE)
!
END SUBROUTINE SURFEX_DEALLO
!
END MODULE MODD_OFF_SURFEX_n
