PROGRAM OI_MAIN
!
USE MODI_OI_CONTROL
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE
!
REAL (KIND=JPRB) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('OI_MAIN',0,ZHOOK_HANDLE)

CALL OI_CONTROL (LDINLINE = .FALSE.)

IF (LHOOK) CALL DR_HOOK('OI_MAIN',1,ZHOOK_HANDLE)

END PROGRAM OI_MAIN
