SUBROUTINE SET_SURFEX_FILE_NAME_LFI(HNAME_IN,HNAME_OUT)
!
USE MODD_IO_SURF_LFI, ONLY : CFILEIN_LFI
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE
!
 CHARACTER(LEN=28), OPTIONAL, INTENT(IN)     :: HNAME_IN
 CHARACTER(LEN=28), OPTIONAL, INTENT(OUT)    :: HNAME_OUT
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
IF (LHOOK) CALL DR_HOOK('SET_SURFEX_FILE_NAME_LFI',0,ZHOOK_HANDLE)
!
IF (PRESENT(HNAME_IN)) THEN
  CFILEIN_LFI=HNAME_IN
ELSEIF (PRESENT(HNAME_OUT)) THEN
  HNAME_OUT=CFILEIN_LFI
ENDIF
!
IF (LHOOK) CALL DR_HOOK('SET_SURFEX_FILE_NAME_LFI',1,ZHOOK_HANDLE)
!
END SUBROUTINE SET_SURFEX_FILE_NAME_LFI
