SUBROUTINE TRIP_DEALLO(YDTRIP)
!
USE MODD_SURFEX_TRIP_n, ONLY : TRIP_MODEL_t
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK, JPHOOK
!
USE MODI_DEALLOC_TRIP
!
IMPLICIT NONE
!
TYPE (TRIP_MODEL_t), INTENT(INOUT) :: YDTRIP
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK("TRIP_DEALLO",0,ZHOOK_HANDLE)
!
 CALL DEALLOC_TRIP
!
IF (LHOOK) CALL DR_HOOK("TRIP_DEALLO",1,ZHOOK_HANDLE)
!
END SUBROUTINE TRIP_DEALLO
