MODULE DEALLOCATE_IF_ASSOCIATED_MOD

!**** DEALLOCATE_IF_ASSOCIATED_MOD

!     Purpose.
!     --------
!     The pattern "IF (ASSOCIATED(<pointer>)) DEALLOCATE(>pointer>)"
!     occurs all over the IFS. With this module, we can just do
!     "CALL DEALLOCATE_IF_ASSOCIATED(<pointer>)".

!**   Interface.
!     ----------

!        CALL DEALLOCATE_IF_ASSOCIATED(P)

!        Input required arguments :
!        -------------------------
!           P        -  A pointer to an array

!     Author.
!     -------
!        Mike Fisher  ECMWF

!     Modifications.
!     --------------
!        Original: 2012-03-01

!     ------------------------------------------------------------------

USE PARKIND1  ,ONLY : JPIM     ,JPRB
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK

SAVE
PRIVATE
PUBLIC  DEALLOCATE_IF_ASSOCIATED

INTERFACE DEALLOCATE_IF_ASSOCIATED
  MODULE PROCEDURE DEALLOCATE_IF_ASSOCIATED_REAL_1D, &
                 & DEALLOCATE_IF_ASSOCIATED_REAL_2D, &
                 & DEALLOCATE_IF_ASSOCIATED_REAL_3D, &
                 & DEALLOCATE_IF_ASSOCIATED_REAL_4D, &
                 & DEALLOCATE_IF_ASSOCIATED_REAL_5D, &
                 & DEALLOCATE_IF_ASSOCIATED_INTEGER_1D, &
                 & DEALLOCATE_IF_ASSOCIATED_INTEGER_2D, &
                 & DEALLOCATE_IF_ASSOCIATED_INTEGER_3D, &
                 & DEALLOCATE_IF_ASSOCIATED_LOGICAL_1D, &
                 & DEALLOCATE_IF_ASSOCIATED_LOGICAL_2D
END INTERFACE

!     ------------------------------------------------------------------

CONTAINS

!     ------------------------------------------------------------------

SUBROUTINE DEALLOCATE_IF_ASSOCIATED_REAL_1D (ZOBJ)
  IMPLICIT NONE
  REAL(KIND=JPRB), DIMENSION(:), POINTER :: ZOBJ
  REAL(KIND=JPRB) :: ZHOOK_HANDLE

  IF (LHOOK) CALL DR_HOOK ('DEALLOCATE_IF_ASSOCIATED_MOD:DEALLOCATE_IF_ASSOCIATED_REAL_1D', &
                         & 0,ZHOOK_HANDLE)
  IF (ASSOCIATED(ZOBJ)) DEALLOCATE(ZOBJ)
  IF (LHOOK) CALL DR_HOOK ('DEALLOCATE_IF_ASSOCIATED_MOD:DEALLOCATE_IF_ASSOCIATED_REAL_1D', &
                         & 1,ZHOOK_HANDLE)
END SUBROUTINE DEALLOCATE_IF_ASSOCIATED_REAL_1D

!     ------------------------------------------------------------------

SUBROUTINE DEALLOCATE_IF_ASSOCIATED_REAL_2D (ZOBJ)
  IMPLICIT NONE
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER :: ZOBJ
  REAL(KIND=JPRB) :: ZHOOK_HANDLE

  IF (LHOOK) CALL DR_HOOK ('DEALLOCATE_IF_ASSOCIATED_MOD:DEALLOCATE_IF_ASSOCIATED_REAL_2D', &
                         & 0,ZHOOK_HANDLE)
  IF (ASSOCIATED(ZOBJ)) DEALLOCATE(ZOBJ)
  IF (LHOOK) CALL DR_HOOK ('DEALLOCATE_IF_ASSOCIATED_MOD:DEALLOCATE_IF_ASSOCIATED_REAL_2D', &
                         & 1,ZHOOK_HANDLE)
END SUBROUTINE DEALLOCATE_IF_ASSOCIATED_REAL_2D

!     ------------------------------------------------------------------

SUBROUTINE DEALLOCATE_IF_ASSOCIATED_REAL_3D (ZOBJ)
  IMPLICIT NONE
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER :: ZOBJ
  REAL(KIND=JPRB) :: ZHOOK_HANDLE

  IF (LHOOK) CALL DR_HOOK ('DEALLOCATE_IF_ASSOCIATED_MOD:DEALLOCATE_IF_ASSOCIATED_REAL_3D', &
                         & 0,ZHOOK_HANDLE)
  IF (ASSOCIATED(ZOBJ)) DEALLOCATE(ZOBJ)
  IF (LHOOK) CALL DR_HOOK ('DEALLOCATE_IF_ASSOCIATED_MOD:DEALLOCATE_IF_ASSOCIATED_REAL_3D', &
                         & 1,ZHOOK_HANDLE)
END SUBROUTINE DEALLOCATE_IF_ASSOCIATED_REAL_3D

!     ------------------------------------------------------------------

SUBROUTINE DEALLOCATE_IF_ASSOCIATED_REAL_4D (ZOBJ)
  IMPLICIT NONE
  REAL(KIND=JPRB), DIMENSION(:,:,:,:), POINTER :: ZOBJ
  REAL(KIND=JPRB) :: ZHOOK_HANDLE

  IF (LHOOK) CALL DR_HOOK ('DEALLOCATE_IF_ASSOCIATED_MOD:DEALLOCATE_IF_ASSOCIATED_REAL_4D', &
                         & 0,ZHOOK_HANDLE)
  IF (ASSOCIATED(ZOBJ)) DEALLOCATE(ZOBJ)
  IF (LHOOK) CALL DR_HOOK ('DEALLOCATE_IF_ASSOCIATED_MOD:DEALLOCATE_IF_ASSOCIATED_REAL_4D', &
                         & 1,ZHOOK_HANDLE)
END SUBROUTINE DEALLOCATE_IF_ASSOCIATED_REAL_4D

!     ------------------------------------------------------------------

SUBROUTINE DEALLOCATE_IF_ASSOCIATED_REAL_5D (ZOBJ)
  IMPLICIT NONE
  REAL(KIND=JPRB), DIMENSION(:,:,:,:,:), POINTER :: ZOBJ
  REAL(KIND=JPRB) :: ZHOOK_HANDLE

  IF (LHOOK) CALL DR_HOOK ('DEALLOCATE_IF_ASSOCIATED_MOD:DEALLOCATE_IF_ASSOCIATED_REAL_5D', &
                         & 0,ZHOOK_HANDLE)
  IF (ASSOCIATED(ZOBJ)) DEALLOCATE(ZOBJ)
  IF (LHOOK) CALL DR_HOOK ('DEALLOCATE_IF_ASSOCIATED_MOD:DEALLOCATE_IF_ASSOCIATED_REAL_5D', &
                         & 1,ZHOOK_HANDLE)
END SUBROUTINE DEALLOCATE_IF_ASSOCIATED_REAL_5D

!     ------------------------------------------------------------------

SUBROUTINE DEALLOCATE_IF_ASSOCIATED_INTEGER_1D (KOBJ)
  IMPLICIT NONE
  INTEGER(KIND=JPIM), DIMENSION(:), POINTER :: KOBJ
  REAL(KIND=JPRB) :: ZHOOK_HANDLE

  IF (LHOOK) CALL DR_HOOK ('DEALLOCATE_IF_ASSOCIATED_MOD:DEALLOCATE_IF_ASSOCIATED_INTEGER_1D', &
                         & 0,ZHOOK_HANDLE)
  IF (ASSOCIATED(KOBJ)) DEALLOCATE(KOBJ)
  IF (LHOOK) CALL DR_HOOK ('DEALLOCATE_IF_ASSOCIATED_MOD:DEALLOCATE_IF_ASSOCIATED_INTEGER_1D', &
                         & 1,ZHOOK_HANDLE)
END SUBROUTINE DEALLOCATE_IF_ASSOCIATED_INTEGER_1D

!     ------------------------------------------------------------------

SUBROUTINE DEALLOCATE_IF_ASSOCIATED_INTEGER_2D (KOBJ)
  IMPLICIT NONE
  INTEGER(KIND=JPIM), DIMENSION(:,:), POINTER :: KOBJ
  REAL(KIND=JPRB) :: ZHOOK_HANDLE

  IF (LHOOK) CALL DR_HOOK ('DEALLOCATE_IF_ASSOCIATED_MOD:DEALLOCATE_IF_ASSOCIATED_INTEGER_2D', &
                         & 0,ZHOOK_HANDLE)
  IF (ASSOCIATED(KOBJ)) DEALLOCATE(KOBJ)
  IF (LHOOK) CALL DR_HOOK ('DEALLOCATE_IF_ASSOCIATED_MOD:DEALLOCATE_IF_ASSOCIATED_INTEGER_2D', &
                         & 1,ZHOOK_HANDLE)
END SUBROUTINE DEALLOCATE_IF_ASSOCIATED_INTEGER_2D

!     ------------------------------------------------------------------

SUBROUTINE DEALLOCATE_IF_ASSOCIATED_INTEGER_3D (KOBJ)
  IMPLICIT NONE
  INTEGER(KIND=JPIM), DIMENSION(:,:,:), POINTER :: KOBJ
  REAL(KIND=JPRB) :: ZHOOK_HANDLE

  IF (LHOOK) CALL DR_HOOK ('DEALLOCATE_IF_ASSOCIATED_MOD:DEALLOCATE_IF_ASSOCIATED_INTEGER_3D', &
                         & 0,ZHOOK_HANDLE)
  IF (ASSOCIATED(KOBJ)) DEALLOCATE(KOBJ)
  IF (LHOOK) CALL DR_HOOK ('DEALLOCATE_IF_ASSOCIATED_MOD:DEALLOCATE_IF_ASSOCIATED_INTEGER_3D', &
                         & 1,ZHOOK_HANDLE)
END SUBROUTINE DEALLOCATE_IF_ASSOCIATED_INTEGER_3D

!     ------------------------------------------------------------------

SUBROUTINE DEALLOCATE_IF_ASSOCIATED_LOGICAL_1D (LDOBJ)
  IMPLICIT NONE
  LOGICAL, DIMENSION(:), POINTER :: LDOBJ
  REAL(KIND=JPRB) :: ZHOOK_HANDLE

  IF (LHOOK) CALL DR_HOOK ('DEALLOCATE_IF_ASSOCIATED_MOD:DEALLOCATE_IF_ASSOCIATED_LOGICAL_1D', &
                         & 0,ZHOOK_HANDLE)
  IF (ASSOCIATED(LDOBJ)) DEALLOCATE(LDOBJ)
  IF (LHOOK) CALL DR_HOOK ('DEALLOCATE_IF_ASSOCIATED_MOD:DEALLOCATE_IF_ASSOCIATED_LOGICAL_1D', &
                         & 1,ZHOOK_HANDLE)
END SUBROUTINE DEALLOCATE_IF_ASSOCIATED_LOGICAL_1D

!     ------------------------------------------------------------------

SUBROUTINE DEALLOCATE_IF_ASSOCIATED_LOGICAL_2D (LDOBJ)
  IMPLICIT NONE
  LOGICAL, DIMENSION(:,:), POINTER :: LDOBJ
  REAL(KIND=JPRB) :: ZHOOK_HANDLE

  IF (LHOOK) CALL DR_HOOK ('DEALLOCATE_IF_ASSOCIATED_MOD:DEALLOCATE_IF_ASSOCIATED_LOGICAL_2D', &
                         & 0,ZHOOK_HANDLE)
  IF (ASSOCIATED(LDOBJ)) DEALLOCATE(LDOBJ)
  IF (LHOOK) CALL DR_HOOK ('DEALLOCATE_IF_ASSOCIATED_MOD:DEALLOCATE_IF_ASSOCIATED_LOGICAL_2D', &
                         & 1,ZHOOK_HANDLE)
END SUBROUTINE DEALLOCATE_IF_ASSOCIATED_LOGICAL_2D

!     ------------------------------------------------------------------

END MODULE DEALLOCATE_IF_ASSOCIATED_MOD
