!
!       Fonction servant a l'adressage 1D dans les tableaux CNOMAR,
!     MLGPOS et MDES1D, MTAMPD.
!
INTEGER (KIND=JPLIKB) FUNCTION IXT (IUVWXY,IZABCD,IEFGHI)
INTEGER (KIND=JPLIKB) :: IUVWXY,IZABCD,IEFGHI
IXT = IUVWXY + LFI%JPLARD * (LFI%MFACTM(IEFGHI) * IZABCD + LFI%JPNPDF * (IEFGHI - 1_JPLIKB))
END FUNCTION
