! Oct-2012 P. Marguinaud 64b LFI
! Jan-2011 P. Marguinaud Thread-safe LFI

SUBROUTINE LFIDEB_FORT               &
&                     (LFI, LDEBUG )
USE LFIMOD, ONLY : LFICOM
USE PARKIND1, ONLY : JPRB
USE YOMHOOK , ONLY : LHOOK, DR_HOOK
USE LFI_PRECISION
IMPLICIT NONE
!****
!        CE SOUS-PROGRAMME D'ACTIVER OU DE DESACTIVER LE MODE
!     "MISE AU POINT DU LOGICIEL". ( PAR DEFAUT, INACTIF )
!**
!        ARGUMENT : LDEBUG (ENTREE) ==> VRAI SI ON DOIT ACTIVER CE MODE.
!
!
TYPE(LFICOM) :: LFI
INTEGER (KIND=JPLIKB) INUMER, IREP, INIMES
!
LOGICAL LDEBUG
CHARACTER(LEN=LFI%JPLSPX) CLNSPR
CHARACTER(LEN=LFI%JPLMES) CLMESS
CHARACTER(LEN=LFI%JPLFTX) CLACTI

!
REAL(KIND=JPRB) :: ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK('LFIDEB_FORT',0,ZHOOK_HANDLE)
CLACTI=''
IF (LFI%LFIDEB_LLPREA) THEN
  CALL LFIINI_FORT                 &
&                 (LFI, 2_JPLIKB )
  LFI%LFIDEB_LLPREA=.FALSE.
ENDIF
!
LFI%LMISOP=LDEBUG
!
!        MESSAGERIE EVENTUELLE .
!
IF (LFI%NIMESG.NE.2)  THEN 
  IF (LHOOK) CALL DR_HOOK('LFIDEB_FORT',1,ZHOOK_HANDLE)
  RETURN
ENDIF
INUMER=LFI%JPNIL
INIMES=2
IREP=0
CLNSPR='LFIDEB'
WRITE (UNIT=CLMESS,FMT='(''LDEBUG= '',L1)') LDEBUG
CALL LFIEMS_FORT                                  &
&               (LFI, INUMER,INIMES,IREP,.FALSE., &
&                CLMESS,CLNSPR,CLACTI)
!
IF (LHOOK) CALL DR_HOOK('LFIDEB_FORT',1,ZHOOK_HANDLE)
END SUBROUTINE LFIDEB_FORT



! Oct-2012 P. Marguinaud 64b LFI
SUBROUTINE LFIDEB64           &
&           (LDEBUG)
USE LFIMOD, ONLY : LFI => LFICOM_DEFAULT, &
&                   LFICOM_DEFAULT_INIT,   &
&                   NEW_LFI_DEFAULT
USE LFI_PRECISION
IMPLICIT NONE
! Arguments
LOGICAL                LDEBUG                                 ! IN   

IF (.NOT. LFICOM_DEFAULT_INIT) CALL NEW_LFI_DEFAULT ()

CALL LFIDEB_FORT            &
&           (LFI, LDEBUG)

END SUBROUTINE LFIDEB64

SUBROUTINE LFIDEB             &
&           (LDEBUG)
USE LFIMOD, ONLY : LFI => LFICOM_DEFAULT, &
&                   LFICOM_DEFAULT_INIT,   &
&                   NEW_LFI_DEFAULT
USE LFI_PRECISION
IMPLICIT NONE
! Arguments
LOGICAL                LDEBUG                                 ! IN   

IF (.NOT. LFICOM_DEFAULT_INIT) CALL NEW_LFI_DEFAULT ()

CALL LFIDEB_MT             &
&           (LFI, LDEBUG)

END SUBROUTINE LFIDEB

SUBROUTINE LFIDEB_MT             &
&           (LFI, LDEBUG)
USE LFIMOD, ONLY : LFICOM
USE LFI_PRECISION
IMPLICIT NONE
! Arguments
TYPE (LFICOM)          LFI                                    ! INOUT
LOGICAL                LDEBUG                                 ! IN   
! Local integers
! Convert arguments


CALL LFIDEB_FORT            &
&           (LFI, LDEBUG)


END SUBROUTINE LFIDEB_MT

!INTF LDEBUG        IN    
