! Oct-2012 P. Marguinaud 64b LFI
! Jan-2011 P. Marguinaud Thread-safe LFI

SUBROUTINE LFINIM_FORT                             &
&                     (LFI, KREP, KNUMER, KNIMES )
USE LFIMOD, ONLY : LFICOM
USE PARKIND1, ONLY : JPRB
USE YOMHOOK , ONLY : LHOOK, DR_HOOK
USE LFI_PRECISION
IMPLICIT NONE
!****
!        CE SOUS-PROGRAMME PERMET D'AJUSTER LE NIVEAU DE MESSAGERIE
!     PROPRE AUX ACTIONS FAITES SUR UN FICHIER PARTICULIER, OUVERT POUR
!     LE LOGICIEL LFI.
!        CEPENDANT, TANT QUE LE NIVEAU DE MESSAGERIE GLOBAL *LFI%NIMESG*
!     VAUT 0 OU 2, LE NIVEAU PROPRE AU FICHIER EST INOPERANT.
!     *LFI%NIMESG* VAUT PAR DEFAUT 1, ET EST REGLABLE VIA LE S/P "LFINMG".
!**
!     ARGUMENTS : KREP   (SORTIE) ==> CODE-REPONSE DU SOUS-PROGRAMME;
!                 KNUMER (ENTREE) ==> LFI%NUMERO D'UNITE LOGIQUE CONCERNEE;
!                 KNIMES (ENTREE) ==> NIVEAU DE MESSAGERIE SOUHAITE.
!
!
TYPE(LFICOM) :: LFI
INTEGER (KIND=JPLIKB) KREP, KNUMER, KNIMES, IRANG
INTEGER (KIND=JPLIKB) IREP, INIMES, INIMEX
!
CHARACTER(LEN=LFI%JPLSPX) CLNSPR
CHARACTER(LEN=LFI%JPLMES) CLMESS
CHARACTER(LEN=LFI%JPLFTX) CLACTI
LOGICAL LLFATA

!
REAL(KIND=JPRB) :: ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK('LFINIM_FORT',0,ZHOOK_HANDLE)
CLACTI=''
CALL LFINUM_FORT                    &
&               (LFI, KNUMER,IRANG)
INIMEX=0
!
IF (IRANG.EQ.0) THEN
  IREP=-1
ELSEIF (KNIMES.GE.0.AND.KNIMES.LE.2) THEN
  INIMEX=IXNIMS (IRANG)
  LFI%NIVMES(IRANG)=KNIMES
  LFI%NDEROP(IRANG)=5
  IREP=0
ELSE
  IREP=-2
ENDIF
!
KREP=IREP
LLFATA=LLMOER (IREP,IRANG)
!
IF (LLFATA.OR.MAX (IXNIMS (IRANG),INIMEX).EQ.2) THEN
  INIMES=2
ELSE
  IF (LHOOK) CALL DR_HOOK('LFINIM_FORT',1,ZHOOK_HANDLE)
  RETURN
ENDIF
!
CLNSPR='LFINIM'
WRITE (UNIT=CLMESS,FMT='(''KREP='',I4,'', KNUMER='',I3, &
&       '', KNIMES='',I3)') KREP,KNUMER,KNIMES
CALL LFIEMS_FORT                                 &
&               (LFI, KNUMER,INIMES,IREP,LLFATA, &
&                CLMESS,CLNSPR,CLACTI)
!
IF (LHOOK) CALL DR_HOOK('LFINIM_FORT',1,ZHOOK_HANDLE)

CONTAINS

#include "lficom2.ixnims.h"
#include "lficom2.llmoer.h"

END SUBROUTINE LFINIM_FORT



! Oct-2012 P. Marguinaud 64b LFI
SUBROUTINE LFINIM64              &
&           (KREP, KNUMER, KNIMES)
USE LFIMOD, ONLY : LFI => LFICOM_DEFAULT, &
&                   LFICOM_DEFAULT_INIT,   &
&                   NEW_LFI_DEFAULT
USE LFI_PRECISION
IMPLICIT NONE
! Arguments
INTEGER (KIND=JPLIKB)  KREP                                   !   OUT
INTEGER (KIND=JPLIKB)  KNUMER                                 ! IN   
INTEGER (KIND=JPLIKB)  KNIMES                                 ! IN   

IF (.NOT. LFICOM_DEFAULT_INIT) CALL NEW_LFI_DEFAULT ()

CALL LFINIM_FORT                       &
&           (LFI, KREP, KNUMER, KNIMES)

END SUBROUTINE LFINIM64

SUBROUTINE LFINIM                &
&           (KREP, KNUMER, KNIMES)
USE LFIMOD, ONLY : LFI => LFICOM_DEFAULT, &
&                   LFICOM_DEFAULT_INIT,   &
&                   NEW_LFI_DEFAULT
USE LFI_PRECISION
IMPLICIT NONE
! Arguments
INTEGER (KIND=JPLIKM)  KREP                                   !   OUT
INTEGER (KIND=JPLIKM)  KNUMER                                 ! IN   
INTEGER (KIND=JPLIKM)  KNIMES                                 ! IN   

IF (.NOT. LFICOM_DEFAULT_INIT) CALL NEW_LFI_DEFAULT ()

CALL LFINIM_MT                        &
&           (LFI, KREP, KNUMER, KNIMES)

END SUBROUTINE LFINIM

SUBROUTINE LFINIM_MT                  &
&           (LFI, KREP, KNUMER, KNIMES)
USE LFIMOD, ONLY : LFICOM
USE LFI_PRECISION
IMPLICIT NONE
! Arguments
TYPE (LFICOM)          LFI                                    ! INOUT
INTEGER (KIND=JPLIKM)  KREP                                   !   OUT
INTEGER (KIND=JPLIKM)  KNUMER                                 ! IN   
INTEGER (KIND=JPLIKM)  KNIMES                                 ! IN   
! Local integers
INTEGER (KIND=JPLIKB)  IREP                                   !   OUT
INTEGER (KIND=JPLIKB)  INUMER                                 ! IN   
INTEGER (KIND=JPLIKB)  INIMES                                 ! IN   
! Convert arguments

INUMER     = INT (    KNUMER, JPLIKB)
INIMES     = INT (    KNIMES, JPLIKB)

CALL LFINIM_FORT                       &
&           (LFI, IREP, INUMER, INIMES)

KREP       = INT (      IREP, JPLIKM)

END SUBROUTINE LFINIM_MT

!INTF KREP            OUT 
!INTF KNUMER        IN    
!INTF KNIMES        IN    
