SUBROUTINE LFISEE (LFI, KFPDESC, KOFFSET, KFACTM, KREC, KREP)
USE PARKIND1, ONLY : JPRB, JPIB, JPIM, JPIA
USE YOMHOOK, ONLY : LHOOK, DR_HOOK
USE LFIMOD, ONLY : LFICOM
USE LFI_PRECISION
IMPLICIT NONE

TYPE (LFICOM) :: LFI
INTEGER (KIND=JPLIKB) KFACTM, KREC, KREP
INTEGER (KIND=JPIA)   KFPDESC
INTEGER (KIND=JPIB)   KOFFSET

INTEGER (KIND=JPIB)   IOFFSET
INTEGER (KIND=JPLIKB) ILOREC
INTEGER (KIND=JPIM)   IREP4
REAL (KIND=JPRB) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('LFISEE',0,ZHOOK_HANDLE)

ILOREC=LFI%JPRECL*KFACTM

IOFFSET=INT (ILOREC*(KREC-1), JPIB)

IF (IOFFSET /= KOFFSET) THEN

  CALL FI_FSEEK (IREP4, KFPDESC, IOFFSET, 0_JPIB)
  KREP = INT (IREP4, JPLIKB)
  IF (KREP /= 0) RETURN

  KOFFSET = IOFFSET

ENDIF

IF (LHOOK) CALL DR_HOOK('LFISEE',1,ZHOOK_HANDLE)

END SUBROUTINE LFISEE
