! Oct-2012 P. Marguinaud 64b LFI
#include "lfisuffix.h"
! Jan-2011 P. Marguinaud Thread-safe FA
SUBROUTINE FAICOR_MT_BB          &
&                     (FA)
USE FA_MOD, ONLY : FA_COM
USE PARKIND1, ONLY : JPRB
USE YOMHOOK , ONLY : LHOOK, DR_HOOK
USE LFI_PRECISION, ONLY : JPDBLE, JPDBLR, JPLIKB, JPLIKM
IMPLICIT NONE
!****
!      Sous-programme INTERNE du logiciel de Fichiers ARPEGE:
!      Initialisation des tableaux permettant la correspondance
!      entre nom du champ dans FA et ses descripteurs GRIB.
!
!      **  FA%NBPARC ne doit pas depasser FA%JPXPAR !! **
!**
!
TYPE(FA_COM) :: FA
INTEGER (KIND=JPLIKB) J, INB, INBPAR

!**
!     1.  -  TRAITEMENT DES CHAMPS MONO NIVEAU
!-----------------------------------------------------------------------
!
!     1.1 -  Champs "profond"
!
REAL(KIND=JPRB) :: ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK('FAICOR_MT',0,ZHOOK_HANDLE)
INBPAR = 0
FA%NBPARC = INBPAR + 7
IF (FA%NBPARC.GT.FA%JPXPAR) GOTO 1001
DO J=INBPAR+1,FA%NBPARC
  FA%CIPREF(J) = 'PROF'
ENDDO
FA%CISUFF(INBPAR+1 ) = 'TEMPERATURE'
FA%CISUFF(INBPAR+2 ) = 'RESERV.GLACE'
FA%CISUFF(INBPAR+3 ) = 'RESERV.EAU'
FA%CISUFF(INBPAR+4 ) = 'RUISSELLEMEN'
FA%CISUFF(INBPAR+5 ) = 'FLUX DE GEL'
FA%CISUFF(INBPAR+6 ) = 'PROP.RMAX.EA'
FA%CISUFF(INBPAR+7 ) = 'XRUISSELLEME'
FA%NCODPA(INBPAR+1 ,1:6) = (/   1_JPLIKB ,  11_JPLIKB ,   &
&      111_JPLIKB ,  10_JPLIKB ,   0_JPLIKB , 0_JPLIKB  /)
FA%NCODPA(INBPAR+2 ,1:6) = (/   1_JPLIKB , 152_JPLIKB ,   &
&      112_JPLIKB ,   0_JPLIKB , 250_JPLIKB , 0_JPLIKB  /)
FA%NCODPA(INBPAR+3 ,1:6) = (/   1_JPLIKB ,  86_JPLIKB ,   &
&      112_JPLIKB ,   0_JPLIKB , 250_JPLIKB , 0_JPLIKB  /)
FA%NCODPA(INBPAR+4 ,1:6) = (/ 149_JPLIKB ,   2_JPLIKB ,   &
&      112_JPLIKB ,  10_JPLIKB , 300_JPLIKB , 4_JPLIKB  /)
FA%NCODPA(INBPAR+5 ,1:6) = (/ 149_JPLIKB ,  73_JPLIKB ,   &
&      112_JPLIKB ,  10_JPLIKB , 300_JPLIKB , 4_JPLIKB  /)
FA%NCODPA(INBPAR+6 ,1:6) = (/ 149_JPLIKB ,  77_JPLIKB ,   &
&      112_JPLIKB ,  10_JPLIKB , 300_JPLIKB , 0_JPLIKB  /)
FA%NCODPA(INBPAR+7 ,1:6) = (/ 149_JPLIKB ,  85_JPLIKB ,   &
&      112_JPLIKB ,  10_JPLIKB , 300_JPLIKB , 0_JPLIKB  /)

!
!     1.2 -  Champs de surface
!
INBPAR = FA%NBPARC
FA%NBPARC = INBPAR + 83
IF (FA%NBPARC.GT.FA%JPXPAR) GOTO 1001
DO J=INBPAR+1,FA%NBPARC
  FA%CIPREF(J) = 'SURF'
ENDDO
FA%CISUFF(INBPAR+1 ) = 'PRESSION'
FA%CISUFF(INBPAR+2 ) = 'GEOPOTENTIEL'
FA%CISUFF(INBPAR+3 ) = 'TEMPERATURE'
FA%CISUFF(INBPAR+4 ) = 'FLU.MSUBL.NE'
FA%CISUFF(INBPAR+5 ) = 'FLU.MEVAP.EA'
FA%CISUFF(INBPAR+6 ) = 'PREC.EAU.GEC'
FA%CISUFF(INBPAR+7 ) = 'PREC.EAU.CON'
FA%CISUFF(INBPAR+8 ) = 'RESERV.NEIGE'
FA%CISUFF(INBPAR+9 ) = 'NEBUL.TOTALE'
FA%CISUFF(INBPAR+10) = 'NEBUL.CONVEC'
FA%CISUFF(INBPAR+11) = 'NEBUL.BASSE'
FA%CISUFF(INBPAR+12) = 'NEBUL.MOYENN'
FA%CISUFF(INBPAR+13) = 'NEBUL.HAUTE'
FA%CISUFF(INBPAR+14) = 'PREC.NEI.CON'
FA%CISUFF(INBPAR+15) = 'PREC.NEI.GEC'
FA%CISUFF(INBPAR+16) = 'IND.TERREMER'
FA%CISUFF(INBPAR+17) = 'Z0.FOIS.G'
FA%CISUFF(INBPAR+18) = 'ALBEDO'
FA%CISUFF(INBPAR+19) = 'PROP.VEGETAT'
FA%CISUFF(INBPAR+20) = 'FLU.RAY.SOLA'
FA%CISUFF(INBPAR+21) = 'FLU.RAY.THER'
FA%CISUFF(INBPAR+22) = 'FLU.LAT.MEVA'
FA%CISUFF(INBPAR+23) = 'FLU.LAT.MSUB'
FA%CISUFF(INBPAR+24) = 'FLU.CHA.SENS'
FA%CISUFF(INBPAR+25) = 'ETA.GEOPOTEN'
FA%CISUFF(INBPAR+26) = 'ETP.GEOPOTEN'
FA%CISUFF(INBPAR+27) = 'TENS.DMOG.ZO'
FA%CISUFF(INBPAR+28) = 'TENS.TURB.ZO'
FA%CISUFF(INBPAR+29) = 'TENS.DMOG.ME'
FA%CISUFF(INBPAR+30) = 'TENS.TURB.ME'
FA%CISUFF(INBPAR+31) = 'RESERV.GLACE'
FA%CISUFF(INBPAR+32) = 'RESERV.EAU'
FA%CISUFF(INBPAR+33) = 'RAYT.LUNE.DE'
FA%CISUFF(INBPAR+34) = 'CAPE.MOD.XFU'
FA%CISUFF(INBPAR+35) = 'TOT.WAT.VAPO'
! Debut des champs pour Mocage :
!DP: champ TCO3 remplace par O3_TOT le 18 oct 2004 par coherence
! avec la BDAP qui venait de proceder au changement.
FA%CISUFF(INBPAR+36) = 'O3_TOT'
FA%CISUFF(INBPAR+37) = 'CH4_TOT'
FA%CISUFF(INBPAR+38) = 'NO_TOT'
FA%CISUFF(INBPAR+39) = 'NO2_TOT'
FA%CISUFF(INBPAR+40) = 'CO_TOT'
! Fin des champs pour Mocage
FA%CISUFF(INBPAR+41) = 'ALBEDO NEIGE'
FA%CISUFF(INBPAR+42) = 'ALBEDO HISTO'
FA%CISUFF(INBPAR+43) = 'ALBEDO.SOLNU'
FA%CISUFF(INBPAR+44) = 'ALBEDO.VEG'
FA%CISUFF(INBPAR+45) = 'EMISSIVITE'
FA%CISUFF(INBPAR+46) = 'ET.GEOPOTENT'
FA%CISUFF(INBPAR+47) = 'VAR.GEOP.ANI'
FA%CISUFF(INBPAR+48) = 'VAR.GEOP.DIR'
FA%CISUFF(INBPAR+49) = 'IND.VEG.DOMI'
FA%CISUFF(INBPAR+50) = 'RESI.STO.MIN'
FA%CISUFF(INBPAR+51) = 'PROP.ARGILE'
FA%CISUFF(INBPAR+52) = 'PROP.SABLE'
FA%CISUFF(INBPAR+53) = 'EPAIS.SOL'
FA%CISUFF(INBPAR+54) = 'IND.FOLIAIRE'
FA%CISUFF(INBPAR+55) = 'RES.EVAPOTRA'
FA%CISUFF(INBPAR+56) = 'GZ0.THERM'
FA%CISUFF(INBPAR+57) = 'RESERV.INTER'
FA%CISUFF(INBPAR+58) = 'FL.Q TURBUL'
FA%CISUFF(INBPAR+59) = 'FL.CT TURBUL'
FA%CISUFF(INBPAR+60) = 'FONTE NEIGE'
FA%CISUFF(INBPAR+61) = 'CHAL. DS SOL'
FA%CISUFF(INBPAR+62) = 'EAU DANS SOL'
FA%CISUFF(INBPAR+63) = 'RUISSELLEMEN'
FA%CISUFF(INBPAR+64) = 'EVAPOTRANSPI'
FA%CISUFF(INBPAR+65) = 'TRANSPIRATIO'
FA%CISUFF(INBPAR+66) = 'RUISS. INTER'
FA%CISUFF(INBPAR+67) = 'FLUX DE GEL'
FA%CISUFF(INBPAR+68) = 'RAYT DIR SUR'
FA%CISUFF(INBPAR+69) = 'RAYT DIFF DE'
FA%CISUFF(INBPAR+70) = 'RAYT THER DE'
FA%CISUFF(INBPAR+71) = 'PROP.RMAX.EA'
FA%CISUFF(INBPAR+72) = 'DENSIT.NEIGE'
FA%CISUFF(INBPAR+73) = 'CFU.Q.TURBUL'
FA%CISUFF(INBPAR+74) = 'CFU.CT.TURBU'
FA%CISUFF(INBPAR+75) = 'TIME.PREC.TO'
FA%CISUFF(INBPAR+76) = 'XFONTE NEIGE'
FA%CISUFF(INBPAR+77) = 'XCHAL. DS SO'
FA%CISUFF(INBPAR+78) = 'XEAU DANS SO'
FA%CISUFF(INBPAR+79) = 'XFLU.MEVAP.E'
FA%CISUFF(INBPAR+80) = 'XRUISSELLEME'
FA%CISUFF(INBPAR+81) = 'XEVAPOTRANSP'
FA%CISUFF(INBPAR+82) = 'XTRANSPIRATI'
FA%CISUFF(INBPAR+83) = 'XRUISS. INTE'
FA%NCODPA(INBPAR+1 ,1:6) = (/   1_JPLIKB ,   1_JPLIKB ,    &
&        1_JPLIKB ,   0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+2 ,1:6) = (/   1_JPLIKB ,   8_JPLIKB ,    &
&        1_JPLIKB ,   0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+3 ,1:6) = (/   1_JPLIKB ,  11_JPLIKB ,    &
&        1_JPLIKB ,   0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+4 ,1:6) = (/ 149_JPLIKB ,  45_JPLIKB ,    &
&        1_JPLIKB ,   0_JPLIKB , 0_JPLIKB ,   4_JPLIKB  /)
FA%NCODPA(INBPAR+5 ,1:6) = (/ 149_JPLIKB ,  46_JPLIKB ,    &
&        1_JPLIKB ,   0_JPLIKB , 0_JPLIKB ,   4_JPLIKB  /)
FA%NCODPA(INBPAR+6 ,1:6) = (/   1_JPLIKB ,  62_JPLIKB ,    &
&        1_JPLIKB ,   0_JPLIKB , 0_JPLIKB ,   4_JPLIKB  /)
FA%NCODPA(INBPAR+7 ,1:6) = (/   1_JPLIKB ,  63_JPLIKB ,    &
&        1_JPLIKB ,   0_JPLIKB , 0_JPLIKB ,   4_JPLIKB  /)
FA%NCODPA(INBPAR+8 ,1:6) = (/   1_JPLIKB ,  65_JPLIKB ,    &
&        1_JPLIKB ,   0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+9 ,1:6) = (/   1_JPLIKB ,  71_JPLIKB ,    &
&        1_JPLIKB ,   0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+10,1:6) = (/   1_JPLIKB ,  72_JPLIKB ,    &
&        1_JPLIKB ,   0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+11,1:6) = (/   1_JPLIKB ,  73_JPLIKB ,    &
&        1_JPLIKB ,   0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+12,1:6) = (/   1_JPLIKB ,  74_JPLIKB ,    &
&        1_JPLIKB ,   0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+13,1:6) = (/   1_JPLIKB ,  75_JPLIKB ,    &
&        1_JPLIKB ,   0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+14,1:6) = (/   1_JPLIKB ,  78_JPLIKB ,    &
&        1_JPLIKB ,   0_JPLIKB , 0_JPLIKB ,   4_JPLIKB  /)
FA%NCODPA(INBPAR+15,1:6) = (/   1_JPLIKB ,  79_JPLIKB ,    &
&        1_JPLIKB ,   0_JPLIKB , 0_JPLIKB ,   4_JPLIKB  /)
FA%NCODPA(INBPAR+16,1:6) = (/   1_JPLIKB ,  81_JPLIKB ,    &
&        1_JPLIKB ,   0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+17,1:6) = (/ 149_JPLIKB ,  47_JPLIKB ,    &
&        1_JPLIKB ,   0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+18,1:6) = (/   1_JPLIKB ,  84_JPLIKB ,    &
&        1_JPLIKB ,   0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+19,1:6) = (/   1_JPLIKB ,  87_JPLIKB ,    &
&        1_JPLIKB ,   0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+20,1:6) = (/ 128_JPLIKB , 111_JPLIKB ,    &
&        1_JPLIKB ,   0_JPLIKB , 0_JPLIKB ,   4_JPLIKB  /)
FA%NCODPA(INBPAR+21,1:6) = (/ 128_JPLIKB , 112_JPLIKB ,    &
&        1_JPLIKB ,   0_JPLIKB , 0_JPLIKB ,   4_JPLIKB  /)
FA%NCODPA(INBPAR+22,1:6) = (/ 149_JPLIKB ,  52_JPLIKB ,    &
&        1_JPLIKB ,   0_JPLIKB , 0_JPLIKB ,   4_JPLIKB  /)
FA%NCODPA(INBPAR+23,1:6) = (/ 149_JPLIKB ,  53_JPLIKB ,    &
&        1_JPLIKB ,   0_JPLIKB , 0_JPLIKB ,   4_JPLIKB  /)
FA%NCODPA(INBPAR+24,1:6) = (/ 128_JPLIKB , 122_JPLIKB ,    &
&        1_JPLIKB ,   0_JPLIKB , 0_JPLIKB ,   4_JPLIKB  /)
FA%NCODPA(INBPAR+25,1:6) = (/ 149_JPLIKB ,  54_JPLIKB ,    &
&        1_JPLIKB ,   0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+26,1:6) = (/ 149_JPLIKB ,  55_JPLIKB ,    &
&        1_JPLIKB ,   0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+27,1:6) = (/ 149_JPLIKB ,  56_JPLIKB ,    &
&        1_JPLIKB ,   0_JPLIKB , 0_JPLIKB ,   4_JPLIKB  /)
FA%NCODPA(INBPAR+28,1:6) = (/ 149_JPLIKB ,  57_JPLIKB ,    &
&        1_JPLIKB ,   0_JPLIKB , 0_JPLIKB ,   4_JPLIKB  /)
FA%NCODPA(INBPAR+29,1:6) = (/ 149_JPLIKB ,  58_JPLIKB ,    &
&        1_JPLIKB ,   0_JPLIKB , 0_JPLIKB ,   4_JPLIKB  /)
FA%NCODPA(INBPAR+30,1:6) = (/ 149_JPLIKB ,  59_JPLIKB ,    &
&        1_JPLIKB ,   0_JPLIKB , 0_JPLIKB ,   4_JPLIKB  /)
FA%NCODPA(INBPAR+31,1:6) = (/   1_JPLIKB , 152_JPLIKB ,    &
&        1_JPLIKB ,   0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+32,1:6) = (/   1_JPLIKB ,  86_JPLIKB ,    &
&        1_JPLIKB ,   0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+33,1:6) = (/   1_JPLIKB , 158_JPLIKB ,    &
&        1_JPLIKB ,   0_JPLIKB , 0_JPLIKB ,   4_JPLIKB  /)
FA%NCODPA(INBPAR+34,1:6) = (/   1_JPLIKB , 160_JPLIKB ,    &
&        1_JPLIKB ,   0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+35,1:6) = (/   1_JPLIKB , 167_JPLIKB ,    &
&        1_JPLIKB ,   0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+36,1:6) = (/   1_JPLIKB ,  10_JPLIKB ,    &
&        1_JPLIKB ,   0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+37,1:6) = (/ 159_JPLIKB ,  21_JPLIKB ,    &
&        1_JPLIKB ,   0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+38,1:6) = (/ 159_JPLIKB ,  22_JPLIKB ,    &
&        1_JPLIKB ,   0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+39,1:6) = (/ 159_JPLIKB ,  23_JPLIKB ,    &
&        1_JPLIKB ,   0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+40,1:6) = (/ 159_JPLIKB ,  24_JPLIKB ,    &
&        1_JPLIKB ,   0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+41,1:6) = (/ 149_JPLIKB ,   5_JPLIKB ,    &
&        1_JPLIKB ,   0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+42,1:6) = (/ 149_JPLIKB ,  48_JPLIKB ,    &
&        1_JPLIKB ,   0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+43,1:6) = (/ 149_JPLIKB ,  49_JPLIKB ,    &
&        1_JPLIKB ,   0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+44,1:6) = (/ 149_JPLIKB ,  50_JPLIKB ,    &
&        1_JPLIKB ,   0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+45,1:6) = (/ 149_JPLIKB ,  60_JPLIKB ,    &
&        1_JPLIKB ,   0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+46,1:6) = (/ 149_JPLIKB ,  93_JPLIKB ,    &
&        1_JPLIKB ,   0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+47,1:6) = (/ 128_JPLIKB , 161_JPLIKB ,    &
&        1_JPLIKB ,   0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+48,1:6) = (/ 128_JPLIKB , 162_JPLIKB ,    &
&        1_JPLIKB ,   0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+49,1:6) = (/ 149_JPLIKB ,  61_JPLIKB ,    &
&        1_JPLIKB ,   0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+50,1:6) = (/ 149_JPLIKB ,  62_JPLIKB ,    &
&        1_JPLIKB ,   0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+51,1:6) = (/ 149_JPLIKB ,  63_JPLIKB ,    &
&        1_JPLIKB ,   0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+52,1:6) = (/ 149_JPLIKB ,  64_JPLIKB ,    &
&        1_JPLIKB ,   0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+53,1:6) = (/ 149_JPLIKB ,  51_JPLIKB ,    &
&        1_JPLIKB ,   0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+54,1:6) = (/ 149_JPLIKB ,  65_JPLIKB ,    &
&        1_JPLIKB ,   0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+55,1:6) = (/ 149_JPLIKB ,  66_JPLIKB ,    &
&        1_JPLIKB ,   0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+56,1:6) = (/ 149_JPLIKB ,  67_JPLIKB ,    &
&        1_JPLIKB ,   0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+57,1:6) = (/ 149_JPLIKB ,  68_JPLIKB ,    &
&        1_JPLIKB ,   0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+58,1:6) = (/ 149_JPLIKB ,  69_JPLIKB ,    &
&        1_JPLIKB ,   0_JPLIKB , 0_JPLIKB ,   4_JPLIKB  /)
FA%NCODPA(INBPAR+59,1:6) = (/ 149_JPLIKB ,  70_JPLIKB ,    &
&        1_JPLIKB ,   0_JPLIKB , 0_JPLIKB ,   4_JPLIKB  /)
FA%NCODPA(INBPAR+60,1:6) = (/   1_JPLIKB ,  99_JPLIKB ,    &
&        1_JPLIKB ,   0_JPLIKB , 0_JPLIKB ,   4_JPLIKB  /)
FA%NCODPA(INBPAR+61,1:6) = (/ 149_JPLIKB ,   8_JPLIKB ,    &
&        1_JPLIKB ,   0_JPLIKB , 0_JPLIKB ,   4_JPLIKB  /)
FA%NCODPA(INBPAR+62,1:6) = (/   1_JPLIKB , 150_JPLIKB ,    &
&        1_JPLIKB ,   0_JPLIKB , 0_JPLIKB ,   4_JPLIKB  /)
FA%NCODPA(INBPAR+63,1:6) = (/ 149_JPLIKB ,   2_JPLIKB ,    &
&        1_JPLIKB ,   0_JPLIKB , 0_JPLIKB ,   4_JPLIKB  /)
FA%NCODPA(INBPAR+64,1:6) = (/   1_JPLIKB , 168_JPLIKB ,    &
&        1_JPLIKB ,   0_JPLIKB , 0_JPLIKB ,   4_JPLIKB  /)
FA%NCODPA(INBPAR+65,1:6) = (/ 149_JPLIKB ,  71_JPLIKB ,    &
&        1_JPLIKB ,   0_JPLIKB , 0_JPLIKB ,   4_JPLIKB  /)
FA%NCODPA(INBPAR+66,1:6) = (/ 149_JPLIKB ,  72_JPLIKB ,    &
&        1_JPLIKB ,   0_JPLIKB , 0_JPLIKB ,   4_JPLIKB  /)
FA%NCODPA(INBPAR+67,1:6) = (/ 149_JPLIKB ,  73_JPLIKB ,    &
&        1_JPLIKB ,   0_JPLIKB , 0_JPLIKB ,   4_JPLIKB  /)
FA%NCODPA(INBPAR+68,1:6) = (/ 149_JPLIKB ,  74_JPLIKB ,    &
&        1_JPLIKB ,   0_JPLIKB , 0_JPLIKB ,   4_JPLIKB  /)
FA%NCODPA(INBPAR+69,1:6) = (/ 149_JPLIKB ,  75_JPLIKB ,    &
&        1_JPLIKB ,   0_JPLIKB , 0_JPLIKB ,   4_JPLIKB  /)
FA%NCODPA(INBPAR+70,1:6) = (/ 149_JPLIKB ,  76_JPLIKB ,    &
&        1_JPLIKB ,   0_JPLIKB , 0_JPLIKB ,   4_JPLIKB  /)
FA%NCODPA(INBPAR+71,1:6) = (/ 149_JPLIKB ,  77_JPLIKB ,    &
&        1_JPLIKB ,   0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+72,1:6) = (/ 149_JPLIKB ,   3_JPLIKB ,    &
&        1_JPLIKB ,   0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+73,1:6) = (/ 149_JPLIKB ,  78_JPLIKB ,    &
&        1_JPLIKB ,   0_JPLIKB , 0_JPLIKB ,   4_JPLIKB  /)
FA%NCODPA(INBPAR+74,1:6) = (/ 149_JPLIKB ,  79_JPLIKB ,    &
&        1_JPLIKB ,   0_JPLIKB , 0_JPLIKB ,   4_JPLIKB  /)
FA%NCODPA(INBPAR+75,1:6) = (/ 149_JPLIKB ,  80_JPLIKB ,    &
&        1_JPLIKB ,   0_JPLIKB , 0_JPLIKB ,   4_JPLIKB  /)
FA%NCODPA(INBPAR+76,1:6) = (/ 149_JPLIKB ,  81_JPLIKB ,    &
&        1_JPLIKB ,   0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+77,1:6) = (/ 149_JPLIKB ,  82_JPLIKB ,    &
&        1_JPLIKB ,   0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+78,1:6) = (/ 149_JPLIKB ,  83_JPLIKB ,    &
&        1_JPLIKB ,   0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+79,1:6) = (/ 149_JPLIKB ,  84_JPLIKB ,    &
&        1_JPLIKB ,   0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+80,1:6) = (/ 149_JPLIKB ,  85_JPLIKB ,    &
&        1_JPLIKB ,   0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+81,1:6) = (/ 149_JPLIKB ,  86_JPLIKB ,    &
&        1_JPLIKB ,   0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+82,1:6) = (/ 149_JPLIKB ,  87_JPLIKB ,    &
&        1_JPLIKB ,   0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+83,1:6) = (/ 149_JPLIKB ,  88_JPLIKB ,    &
&        1_JPLIKB ,   0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
!
!  Geopotentiel de surface en spectral (relief)
!
INBPAR = FA%NBPARC
FA%NBPARC = INBPAR + 1
IF (FA%NBPARC.GT.FA%JPXPAR) GOTO 1001
DO J=INBPAR+1,FA%NBPARC
  FA%CIPREF(J) = 'SPECSURF'
ENDDO
FA%CISUFF(INBPAR+1) = 'GEOPOTEN'
FA%NCODPA(INBPAR+1 ,1:6) = (/   1_JPLIKB ,   8_JPLIKB ,    &
&        1_JPLIKB ,   0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
!
!     1.3 -  Champs au sommet
!
INBPAR = FA%NBPARC
FA%NBPARC = INBPAR + 2
IF (FA%NBPARC.GT.FA%JPXPAR) GOTO 1001
DO J=INBPAR+1,FA%NBPARC
  FA%CIPREF(J) = 'SOMM'
ENDDO
FA%CISUFF(INBPAR+1 ) = 'FLU.RAY.SOLA'
FA%CISUFF(INBPAR+2 ) = 'FLU.RAY.THER'
FA%NCODPA(INBPAR+1 ,1:6) = (/ 128_JPLIKB , 113_JPLIKB ,    &
&        8_JPLIKB , 0_JPLIKB ,   0_JPLIKB ,   4_JPLIKB  /)
FA%NCODPA(INBPAR+2 ,1:6) = (/ 128_JPLIKB , 114_JPLIKB ,    &
&        8_JPLIKB , 0_JPLIKB ,   0_JPLIKB ,   4_JPLIKB  /)
!
!     1.4 -  Champs de la Couche Limite de Surface
!
INBPAR = FA%NBPARC
FA%NBPARC = INBPAR + 11
IF (FA%NBPARC.GT.FA%JPXPAR) GOTO 1001
DO J=INBPAR+1,FA%NBPARC
  FA%CIPREF(J) = 'CLS'
ENDDO
FA%CISUFF(INBPAR+1 ) = 'TEMPERATURE'
FA%CISUFF(INBPAR+2 ) = 'MAXI.TEMPERAT'
FA%CISUFF(INBPAR+3 ) = 'MINI.TEMPERAT'
FA%CISUFF(INBPAR+4 ) = 'VENT.ZONAL'
FA%CISUFF(INBPAR+5 ) = 'VENT.MERIDIEN'
FA%CISUFF(INBPAR+6 ) = 'HUMI.SPECIFIQ'
FA%CISUFF(INBPAR+7 ) = 'HUMI.RELATIVE'
FA%CISUFF(INBPAR+8 ) = 'MAXI.HUMI.REL'
FA%CISUFF(INBPAR+9 ) = 'MINI.HUMI.REL'
FA%CISUFF(INBPAR+10) = 'U.RAF.MOD.XFU'
FA%CISUFF(INBPAR+11) = 'V.RAF.MOD.XFU'
FA%NCODPA(INBPAR+1 ,1:6) = (/   1_JPLIKB ,  11_JPLIKB ,   &
&       105_JPLIKB ,  2_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+2 ,1:6) = (/   1_JPLIKB ,  15_JPLIKB ,   &
&       105_JPLIKB ,  2_JPLIKB , 0_JPLIKB ,   2_JPLIKB  /)
FA%NCODPA(INBPAR+3 ,1:6) = (/   1_JPLIKB ,  16_JPLIKB ,   &
&       105_JPLIKB ,  2_JPLIKB , 0_JPLIKB ,   2_JPLIKB  /)
FA%NCODPA(INBPAR+4 ,1:6) = (/   1_JPLIKB ,  33_JPLIKB ,   &
&       105_JPLIKB ,  1_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+5 ,1:6) = (/   1_JPLIKB ,  34_JPLIKB ,   &
&       105_JPLIKB ,  1_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+6 ,1:6) = (/   1_JPLIKB ,  51_JPLIKB ,   &
&       105_JPLIKB ,  2_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+7 ,1:6) = (/   1_JPLIKB ,  52_JPLIKB ,   &
&       105_JPLIKB ,  2_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+8 ,1:6) = (/ 149_JPLIKB ,  90_JPLIKB ,   &
&       105_JPLIKB ,  2_JPLIKB , 0_JPLIKB ,   2_JPLIKB  /)
FA%NCODPA(INBPAR+9 ,1:6) = (/ 149_JPLIKB ,  91_JPLIKB ,   &
&       105_JPLIKB ,  2_JPLIKB , 0_JPLIKB ,   2_JPLIKB  /)
FA%NCODPA(INBPAR+10,1:6) = (/   1_JPLIKB , 163_JPLIKB ,   &
&       105_JPLIKB ,  1_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+11,1:6) = (/   1_JPLIKB , 164_JPLIKB ,   &
&       105_JPLIKB ,  1_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
!
!     1.5 -  Champs au niveau tropopause
!
INBPAR = FA%NBPARC
FA%NBPARC = INBPAR + 2
IF (FA%NBPARC.GT.FA%JPXPAR) GOTO 1001
DO J=INBPAR+1,FA%NBPARC
  FA%CIPREF(J) = 'ICAO'
ENDDO
FA%CISUFF(INBPAR+1 ) = 'TROP.PRESSUR'
FA%CISUFF(INBPAR+2 ) = 'TROP.TEMPERA'
FA%NCODPA(INBPAR+1 ,1:6) = (/   1_JPLIKB ,   1_JPLIKB ,    &
&         7_JPLIKB ,  0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+2 ,1:6) = (/   1_JPLIKB ,  11_JPLIKB ,    &
&         7_JPLIKB ,  0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
!
!     1.6 -  Champs au niveau jet
!
INBPAR = FA%NBPARC
FA%NBPARC = INBPAR + 3
IF (FA%NBPARC.GT.FA%JPXPAR) GOTO 1001
DO J=INBPAR+1,FA%NBPARC
  FA%CIPREF(J) = 'JET'
ENDDO
FA%CISUFF(INBPAR+1 ) = 'PRESSURE'
FA%CISUFF(INBPAR+2 ) = 'VENT_ZONAL'
FA%CISUFF(INBPAR+3 ) = 'VENT_MERIDIEN'
FA%NCODPA(INBPAR+1 ,1:6) = (/   1_JPLIKB ,   1_JPLIKB ,    &
&         6_JPLIKB ,  0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+2 ,1:6) = (/   1_JPLIKB ,  33_JPLIKB ,    &
&         6_JPLIKB ,  0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+3 ,1:6) = (/   1_JPLIKB ,  34_JPLIKB ,    &
&         6_JPLIKB ,  0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
!
!     1.7 -  Champs pour la Couche Limite Planetaire
!
INBPAR = FA%NBPARC
FA%NBPARC = INBPAR + 2
IF (FA%NBPARC.GT.FA%JPXPAR) GOTO 1001
DO J=INBPAR+1,FA%NBPARC
  FA%CIPREF(J) = 'CLP'
ENDDO
FA%CISUFF(INBPAR+1 ) = 'MHAUT.MOD.XFU'
FA%CISUFF(INBPAR+2 ) = 'MOCON.MOD.XFU'
FA%NCODPA(INBPAR+1 ,1:6) = (/   1_JPLIKB , 165_JPLIKB ,    &
&         1_JPLIKB ,  0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+2 ,1:6) = (/   1_JPLIKB , 166_JPLIKB ,    &
&         1_JPLIKB ,  0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
!
!     1.8 -  Champs au niveau mer
!
INBPAR = FA%NBPARC
FA%NBPARC = INBPAR + 1
IF (FA%NBPARC.GT.FA%JPXPAR) GOTO 1001
DO J=INBPAR+1,FA%NBPARC
  FA%CIPREF(J) = 'MSL'
ENDDO
FA%CISUFF(INBPAR+1 ) = 'PRESSURE'
FA%NCODPA(INBPAR+1 ,1:6) = (/   1_JPLIKB ,   2_JPLIKB ,   &
&       102_JPLIKB ,  0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
!
!     1.9 - Relief
!
INBPAR = FA%NBPARC
FA%NBPARC = INBPAR + 1
IF (FA%NBPARC.GT.FA%JPXPAR) GOTO 1001
DO J=INBPAR+1,FA%NBPARC
  FA%CIPREF(J) = 'INT'
ENDDO
FA%CISUFF(INBPAR+1 ) = 'SURFGEOPOTENT'
FA%NCODPA(INBPAR+1 ,1:6) = (/   1_JPLIKB ,   8_JPLIKB ,    &
&         1_JPLIKB ,  0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
!
!     1.10- ATMO
!
INBPAR = FA%NBPARC
FA%NBPARC = INBPAR + 4
IF (FA%NBPARC.GT.FA%JPXPAR) GOTO 1001
DO J=INBPAR+1,FA%NBPARC
  FA%CIPREF(J) = 'ATMO'
ENDDO
FA%CISUFF(INBPAR+1 ) = 'NEBUL.CONVEC'
FA%CISUFF(INBPAR+2 ) = 'NEBUL.BASSE'
FA%CISUFF(INBPAR+3 ) = 'NEBUL.MOYENN'
FA%CISUFF(INBPAR+4 ) = 'NEBUL.HAUTE'
FA%NCODPA(INBPAR+1 ,1:6) = (/ 128_JPLIKB ,  72_JPLIKB ,    &
&         1_JPLIKB ,  0_JPLIKB , 0_JPLIKB ,   4_JPLIKB  /)
FA%NCODPA(INBPAR+2 ,1:6) = (/ 128_JPLIKB ,  73_JPLIKB ,    &
&         1_JPLIKB ,  0_JPLIKB , 0_JPLIKB ,   4_JPLIKB  /)
FA%NCODPA(INBPAR+3 ,1:6) = (/ 128_JPLIKB ,  74_JPLIKB ,    &
&         1_JPLIKB ,  0_JPLIKB , 0_JPLIKB ,   4_JPLIKB  /)
FA%NCODPA(INBPAR+4 ,1:6) = (/ 128_JPLIKB ,  75_JPLIKB ,    &
&         1_JPLIKB ,  0_JPLIKB , 0_JPLIKB ,   4_JPLIKB  /)
!
!     1.11- TOP
!
INBPAR = FA%NBPARC
FA%NBPARC = INBPAR + 1
IF (FA%NBPARC.GT.FA%JPXPAR) GOTO 1001
DO J=INBPAR+1,FA%NBPARC
  FA%CIPREF(J) = 'TOP'
ENDDO
FA%CISUFF(INBPAR+1 ) = 'RAYT DIR SOM'
FA%NCODPA(INBPAR+1 ,1:6) = (/ 149_JPLIKB , 174_JPLIKB ,    &
&         8_JPLIKB ,  0_JPLIKB , 0_JPLIKB ,   4_JPLIKB  /)
!**
!     2.  -  TRAITEMENT DES CHAMPS SUR NIVEAUX
!-----------------------------------------------------------------------
!
!     2.1 -  Champs sur un niveau isobare
!
!  ATTENTION: comme les champs HAUTEUR sont tres proches
!             des champs ISOBARE, un copier-coller sera fait
!             pour les INB champs suivants:
!             Revoir la methode si un champ PRESSION ne suivait
!             pas cette regle !!
INB = 32
INBPAR = FA%NBPARC
FA%NBPARC = INBPAR + INB
IF (FA%NBPARC.GT.FA%JPXPAR) GOTO 1001
DO J=INBPAR+1,FA%NBPARC
  FA%CIPREF(J) = 'P'
ENDDO
FA%CISUFF(INBPAR+1 ) = 'POT_VORTIC'
FA%CISUFF(INBPAR+2 ) = 'GEOPOTENTI'
FA%CISUFF(INBPAR+3 ) = 'TEMPERATUR'
FA%CISUFF(INBPAR+4 ) = 'TEMPE_POTE'
FA%CISUFF(INBPAR+5 ) = 'THETA_PRIM'
FA%CISUFF(INBPAR+6 ) = 'VENT_ZONAL'
FA%CISUFF(INBPAR+7 ) = 'VENT_MERID'
FA%CISUFF(INBPAR+8 ) = 'VITESSE_VE'
FA%CISUFF(INBPAR+9 ) = 'ABS_VORTIC'
FA%CISUFF(INBPAR+10) = 'DIVERGENCE'
FA%CISUFF(INBPAR+11) = 'HUMI.SPECI'
FA%CISUFF(INBPAR+12) = 'HUMI_RELAT'
! Debut des champs pour Mocage :
FA%CISUFF(INBPAR+13) = 'O3'
FA%CISUFF(INBPAR+14) = 'NO2'
FA%CISUFF(INBPAR+15) = 'NO'
FA%CISUFF(INBPAR+16) = 'PAN'
FA%CISUFF(INBPAR+17) = 'HNO3'
FA%CISUFF(INBPAR+18) = 'SO2'
FA%CISUFF(INBPAR+19) = 'CO'
FA%CISUFF(INBPAR+20) = 'CH4'
FA%CISUFF(INBPAR+21) = 'C2H6'
FA%CISUFF(INBPAR+22) = 'NC4H10'
FA%CISUFF(INBPAR+23) = 'C2H4'
FA%CISUFF(INBPAR+24) = 'C3H6'
FA%CISUFF(INBPAR+25) = 'OXYL'
FA%CISUFF(INBPAR+26) = 'C5H8'
FA%CISUFF(INBPAR+27) = 'APINEN'
FA%CISUFF(INBPAR+28) = 'HCHO'
FA%CISUFF(INBPAR+29) = 'CH3CHO'
FA%CISUFF(INBPAR+30) = 'GLYOX'
FA%CISUFF(INBPAR+31) = 'MGLYOX'
FA%CISUFF(INBPAR+32) = 'CH3COE'
! Fin des champs pour Mocage
FA%NCODPA(INBPAR+1 ,1:6) = (/   1_JPLIKB ,   4_JPLIKB ,   &
&       100_JPLIKB ,  0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+2 ,1:6) = (/   1_JPLIKB ,   6_JPLIKB ,   &
&       100_JPLIKB ,  0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+3 ,1:6) = (/   1_JPLIKB ,  11_JPLIKB ,   &
&       100_JPLIKB ,  0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+4 ,1:6) = (/   1_JPLIKB ,  13_JPLIKB ,   &
&       100_JPLIKB ,  0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+5 ,1:6) = (/   1_JPLIKB ,  15_JPLIKB ,   &
&       100_JPLIKB ,  0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+6 ,1:6) = (/   1_JPLIKB ,  33_JPLIKB ,   &
&       100_JPLIKB ,  0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+7 ,1:6) = (/   1_JPLIKB ,  34_JPLIKB ,   &
&       100_JPLIKB ,  0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+8 ,1:6) = (/   1_JPLIKB ,  39_JPLIKB ,   &
&       100_JPLIKB ,  0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+9 ,1:6) = (/   1_JPLIKB ,  41_JPLIKB ,   &
&       100_JPLIKB ,  0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+10,1:6) = (/   1_JPLIKB ,  44_JPLIKB ,   &
&       100_JPLIKB ,  0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+11,1:6) = (/   1_JPLIKB ,  51_JPLIKB ,   &
&       100_JPLIKB ,  0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+12,1:6) = (/   1_JPLIKB ,  52_JPLIKB ,   &
&       100_JPLIKB ,  0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+13,1:6) = (/ 159_JPLIKB ,   1_JPLIKB ,   &
&       100_JPLIKB ,  0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+14,1:6) = (/ 159_JPLIKB ,   2_JPLIKB ,   &
&       100_JPLIKB ,  0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+15,1:6) = (/ 159_JPLIKB ,   3_JPLIKB ,   &
&       100_JPLIKB ,  0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+16,1:6) = (/ 159_JPLIKB ,   4_JPLIKB ,   &
&       100_JPLIKB ,  0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+17,1:6) = (/ 159_JPLIKB ,   5_JPLIKB ,   &
&       100_JPLIKB ,  0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+18,1:6) = (/ 159_JPLIKB ,   6_JPLIKB ,   &
&       100_JPLIKB ,  0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+19,1:6) = (/ 159_JPLIKB ,   7_JPLIKB ,   &
&       100_JPLIKB ,  0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+20,1:6) = (/ 159_JPLIKB ,   8_JPLIKB ,   &
&       100_JPLIKB ,  0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+21,1:6) = (/ 159_JPLIKB ,   9_JPLIKB ,   &
&       100_JPLIKB ,  0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+22,1:6) = (/ 159_JPLIKB ,  10_JPLIKB ,   &
&       100_JPLIKB ,  0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+23,1:6) = (/ 159_JPLIKB ,  11_JPLIKB ,   &
&       100_JPLIKB ,  0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+24,1:6) = (/ 159_JPLIKB ,  12_JPLIKB ,   &
&       100_JPLIKB ,  0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+25,1:6) = (/ 159_JPLIKB ,  13_JPLIKB ,   &
&       100_JPLIKB ,  0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+26,1:6) = (/ 159_JPLIKB ,  14_JPLIKB ,   &
&       100_JPLIKB ,  0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+27,1:6) = (/ 159_JPLIKB ,  15_JPLIKB ,   &
&       100_JPLIKB ,  0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+28,1:6) = (/ 159_JPLIKB ,  16_JPLIKB ,   &
&       100_JPLIKB ,  0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+29,1:6) = (/ 159_JPLIKB ,  17_JPLIKB ,   &
&       100_JPLIKB ,  0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+30,1:6) = (/ 159_JPLIKB ,  18_JPLIKB ,   &
&       100_JPLIKB ,  0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+31,1:6) = (/ 159_JPLIKB ,  19_JPLIKB ,   &
&       100_JPLIKB ,  0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+32,1:6) = (/ 159_JPLIKB ,  20_JPLIKB ,   &
&       100_JPLIKB ,  0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
!
!     2.2 -  Champs sur un niveau hauteur
!
!   ATTENTION: on reprend les INB definitions du niveau ISOBARE!!
!
INBPAR = FA%NBPARC
FA%NBPARC = INBPAR + INB
IF (FA%NBPARC.GT.FA%JPXPAR) GOTO 1001
DO J=INBPAR+1,FA%NBPARC
  FA%CIPREF(J) = 'H'
  FA%CISUFF(J) = FA%CISUFF(J-INB)
  FA%NCODPA(J,1:2) = FA%NCODPA(J-INB,1:2)
  FA%NCODPA(J,3) = 105
  FA%NCODPA(J,4:6) = FA%NCODPA(J-INB,4:6)
ENDDO
!
!     2.3 -  Champs sur un niveau iso-tourbillon-potentiel
!
!  ATTENTION: comme les champs ISENTROPE sont tres proches
!             des champs ISO-PV, un copier-coller sera fait
!             pour les INB champs suivants:
!             Revoir la methode si un champ ISO-PV ne suivait
!             pas cette regle !!
INB = 10
INBPAR = FA%NBPARC
FA%NBPARC = INBPAR + INB
IF (FA%NBPARC.GT.FA%JPXPAR) GOTO 1001
DO J=INBPAR+1,FA%NBPARC
  FA%CIPREF(J) = 'V'
ENDDO
FA%CISUFF(INBPAR+1 ) = 'GEOPOTENTIEL'
FA%CISUFF(INBPAR+2 ) = 'TEMPERATURE'
FA%CISUFF(INBPAR+3 ) = 'TEMPE_POTENT'
FA%CISUFF(INBPAR+4 ) = 'VENT_ZONAL'
FA%CISUFF(INBPAR+5 ) = 'VENT_MERIDIE'
FA%CISUFF(INBPAR+6 ) = 'VITESSE_VE'
FA%CISUFF(INBPAR+7 ) = 'ABS_VORTICIT'
FA%CISUFF(INBPAR+8 ) = 'DIVERGENCE'
FA%CISUFF(INBPAR+9 ) = 'HUMI.SPECI'
FA%CISUFF(INBPAR+10) = 'HUMI_RELAT'
FA%NCODPA(INBPAR+1 ,1:6) = (/   1_JPLIKB ,   6_JPLIKB ,   &
&       117_JPLIKB ,  0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+2 ,1:6) = (/   1_JPLIKB ,  11_JPLIKB ,   &
&       117_JPLIKB ,  0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+3 ,1:6) = (/   1_JPLIKB ,  13_JPLIKB ,   &
&       117_JPLIKB ,  0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+4 ,1:6) = (/   1_JPLIKB ,  33_JPLIKB ,   &
&       117_JPLIKB ,  0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+5 ,1:6) = (/   1_JPLIKB ,  34_JPLIKB ,   &
&       117_JPLIKB ,  0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+6 ,1:6) = (/   1_JPLIKB ,  39_JPLIKB ,   &
&       117_JPLIKB ,  0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+7 ,1:6) = (/   1_JPLIKB ,  41_JPLIKB ,   &
&       117_JPLIKB ,  0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+8 ,1:6) = (/   1_JPLIKB ,  44_JPLIKB ,   &
&       117_JPLIKB ,  0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+9 ,1:6) = (/   1_JPLIKB ,  51_JPLIKB ,   &
&       117_JPLIKB ,  0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+10,1:6) = (/   1_JPLIKB ,  52_JPLIKB ,   &
&       117_JPLIKB ,  0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)

!
!     2.4 -  Champs sur un niveau isentrope
!
!   ATTENTION: on reprend les INB definitions du niveau ISO-PV!!
!
INBPAR = FA%NBPARC
FA%NBPARC = INBPAR + INB
IF (FA%NBPARC.GT.FA%JPXPAR) GOTO 1001
DO J=INBPAR+1,FA%NBPARC
  FA%CIPREF(J) = 'T'
  FA%CISUFF(J) = FA%CISUFF(J-INB)
  FA%NCODPA(J,1:2) = FA%NCODPA(J-INB,1:2)
  FA%NCODPA(J,3) = 113
  FA%NCODPA(J,4:6) = FA%NCODPA(J-INB,4:6)
ENDDO
! Champs suppl differents de ceux d'ISO-PV
INBPAR = FA%NBPARC
FA%NBPARC = INBPAR + 1
IF (FA%NBPARC.GT.FA%JPXPAR) GOTO 1001
DO J=INBPAR+1,FA%NBPARC
  FA%CIPREF(J) = 'T'
ENDDO
FA%CISUFF(INBPAR+1) = 'POT_VORTICIT'
FA%NCODPA(INBPAR+1 ,1:6) = (/   1_JPLIKB ,   4_JPLIKB ,   &
&       113_JPLIKB ,  0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
!
!     2.5 -  Champs sur un niveau modele
!
!
INBPAR = FA%NBPARC
FA%NBPARC = INBPAR + 12
IF (FA%NBPARC.GT.FA%JPXPAR) GOTO 1001
DO J=INBPAR+1,FA%NBPARC
  FA%CIPREF(J) = 'S'
ENDDO
FA%CISUFF(INBPAR+1 ) = 'TEMPERATURE'
FA%CISUFF(INBPAR+2 ) = 'WIND.U.PHYS'
FA%CISUFF(INBPAR+3 ) = 'VENT_ZONAL'
FA%CISUFF(INBPAR+4 ) = 'WIND.V.PHYS'
FA%CISUFF(INBPAR+5 ) = 'VENT_MERIDIE'
FA%CISUFF(INBPAR+6 ) = 'FONC.COURANT'
FA%CISUFF(INBPAR+7 ) = 'POT.VITESSE'
FA%CISUFF(INBPAR+8 ) = 'VORTICITY'
FA%CISUFF(INBPAR+9 ) = 'DIVERGENCE'
FA%CISUFF(INBPAR+10) = 'HUMI.SPECIFI'
FA%CISUFF(INBPAR+11) = 'VERTIC.DIVER'
FA%CISUFF(INBPAR+12) = 'PRESS.DEPART'
FA%NCODPA(INBPAR+1 ,1:6) = (/   1_JPLIKB ,  11_JPLIKB ,   &
&       109_JPLIKB ,  0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+2 ,1:6) = (/   1_JPLIKB ,  33_JPLIKB ,   &
&       109_JPLIKB ,  0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+3 ,1:6) = (/   1_JPLIKB ,  33_JPLIKB ,   &
&       109_JPLIKB ,  0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+4 ,1:6) = (/   1_JPLIKB ,  34_JPLIKB ,   &
&       109_JPLIKB ,  0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+5 ,1:6) = (/   1_JPLIKB ,  34_JPLIKB ,   &
&       109_JPLIKB ,  0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+6 ,1:6) = (/   1_JPLIKB ,  35_JPLIKB ,   &
&       109_JPLIKB ,  0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+7 ,1:6) = (/   1_JPLIKB ,  36_JPLIKB ,   &
&       109_JPLIKB ,  0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+8 ,1:6) = (/   1_JPLIKB ,  43_JPLIKB ,   &
&       109_JPLIKB ,  0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+9 ,1:6) = (/   1_JPLIKB ,  44_JPLIKB ,   &
&       109_JPLIKB ,  0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+10,1:6) = (/   1_JPLIKB ,  51_JPLIKB ,   &
&       109_JPLIKB ,  0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+11,1:6) = (/ 149_JPLIKB ,  91_JPLIKB ,   &
&       109_JPLIKB ,  0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
FA%NCODPA(INBPAR+12,1:6) = (/ 149_JPLIKB ,  92_JPLIKB ,   &
&       109_JPLIKB ,  0_JPLIKB , 0_JPLIKB ,   0_JPLIKB  /)
!
!**
!    10.  -  PHASE TERMINALE
!-----------------------------------------------------------------------
!
IF (LHOOK) CALL DR_HOOK('FAICOR_MT',1,ZHOOK_HANDLE)
RETURN
!
1001 CONTINUE
WRITE (UNIT=FA%NULOUT,FMT=*)                                      &
&            'FAICOR: ERROR, ',FA%NBPARC,' fields are initialized'
WRITE (UNIT=FA%NULOUT,FMT=*)                               &
&            '        but only ',FA%JPXPAR,' are possible.'
WRITE (UNIT=FA%NULOUT,FMT=*)'        Change FA%JPXPAR in famodu.F'
STOP
!
END SUBROUTINE



! Oct-2012 P. Marguinaud 64b LFI
SUBROUTINE FAICOR_BB          &
&           ()
USE FA_MOD, ONLY : FA => FA_COM_DEFAULT, &
&                   FA_COM_DEFAULT_INIT,  &
&                   NEW_FA_DEFAULT
USE LFI_PRECISION, ONLY : JPDBLE, JPDBLR, JPLIKB, JPLIKM
IMPLICIT NONE
! Arguments

IF (.NOT. FA_COM_DEFAULT_INIT) CALL NEW_FA_DEFAULT ()

CALL FAICOR_MT_BB          &
&           (FA)

END SUBROUTINE

SUBROUTINE FAICOR_MM          &
&           ()
USE FA_MOD, ONLY : FA => FA_COM_DEFAULT, &
&                   FA_COM_DEFAULT_INIT,  &
&                   NEW_FA_DEFAULT
USE LFI_PRECISION, ONLY : JPDBLE, JPDBLR, JPLIKB, JPLIKM
IMPLICIT NONE
! Arguments

IF (.NOT. FA_COM_DEFAULT_INIT) CALL NEW_FA_DEFAULT ()

CALL FAICOR_MT_MM          &
&           (FA)

END SUBROUTINE

SUBROUTINE FAICOR_MT_MM          &
&           (FA)
USE FA_MOD, ONLY : FA_COM,              &
&                   FA_COM_DEFAULT_INIT, &
&                   NEW_FA_DEFAULT
USE LFI_PRECISION, ONLY : JPDBLE, JPDBLR, JPLIKB, JPLIKM
IMPLICIT NONE
! Arguments
TYPE (FA_COM)          FA                                     ! INOUT
! Local integers
! Convert arguments


CALL FAICOR_MT_BB          &
&           (FA)


END SUBROUTINE
