SUBROUTINE DR_HOOK_PROCINFO(KMYPROC, KNPROC)
USE PARKIND1  ,ONLY : JPIM     ,JPRB
#ifdef SFX_MPI
USE MPL_MODULE, ONLY : MPL_RANK,MPL_NUMPROC
#endif
IMPLICIT NONE
INTEGER(KIND=JPIM),INTENT(OUT) :: KMYPROC, KNPROC
#ifdef SFX_MPI
KMYPROC = MPL_RANK
KNPROC = MPL_NUMPROC
#else
KMYPROC = 0
KNPROC = 1
#endif
END SUBROUTINE DR_HOOK_PROCINFO
