SUBROUTINE ABOR1(CDTEXT)

USE PARKIND1  ,ONLY : JPIM     ,JPRB
USE YOMLUN_IFSAUX, ONLY : NULOUT,NULERR
!RJ USE MPL_MODULE, ONLY : MPL_ABORT, MPL_RANK, MPL_NUMPROC
USE SDL_MODULE, ONLY : SDL_TRACEBACK, SDL_SRLABORT

#ifdef AIX64
!$ USE OMP_LIB
#endif
!
IMPLICIT NONE
!
#ifndef AIX64
!$ INCLUDE 'omp_lib.h'
#endif

#ifdef SFX_MPI
INCLUDE 'mpif.h'
#endif

CHARACTER(LEN=*), INTENT(IN) :: CDTEXT
INTEGER(KIND=JPIM) :: ILEN

INTEGER(KIND=JPIM) :: IRNK,ITID,IERR
INTEGER(KIND=JPIM) :: IRETURN_CODE
LOGICAL :: LLINIT

ILEN=LEN(CDTEXT)
IF (NULOUT >= 0) WRITE(NULOUT,'(1X,A)') 'ABOR1 CALLED'

ITID=1
!$ ITID=OMP_GET_THREAD_NUM()+1
IRNK=0
#ifdef SFX_MPI
CALL MPI_INITIALIZED(LLINIT, IERR)
IF(LLINIT) CALL MPI_COMM_RANK(MPI_COMM_WORLD,IRNK,IERR)
#endif

IF(ILEN <= 512) THEN
  IF (NULOUT >= 0) WRITE(NULOUT,'(1X,A)') CDTEXT
  WRITE(0,'(1x,A,1x,I6,1x,A,1x,I6,1x,A)') 'ABORT! ',IRNK,' THRD',ITID,CDTEXT
ELSE
  WRITE(0,'(A,I6,A,I6,A)') 'ABORT! ',IRNK,' THRD',ITID,&
   & 'ABOR1 CALLED WITHOUT TEXT STRING'
ENDIF

IF (NULOUT >= 0) THEN
  CALL FLUSH(NULOUT)
  IF (NULOUT /= 0 .and. NULOUT /= 6) CLOSE(NULOUT)
ENDIF

CALL FLUSH(0)
CALL SYSTEM("sleep 1")
!$OMP SINGLE
CALL SDL_TRACEBACK(ITID)
CALL FLUSH(0)
CALL SYSTEM("sleep 1")
!$OMP END SINGLE
! ------All threads wait till traceback done
CALL FLUSH(0)
CALL SYSTEM("sleep 1")

#ifdef SFX_MPI
IRETURN_CODE=1
CALL MPI_ABORT(MPI_COMM_WORLD,IRETURN_CODE,IERR)
#endif
CALL SDL_SRLABORT

END SUBROUTINE ABOR1

SUBROUTINE ABOR1FL(CDFILE, KLINENUM, CDTEXT)
USE PARKIND1  ,ONLY : JPIM
USE YOMLUN_IFSAUX, ONLY : NULOUT,NULERR
IMPLICIT NONE
CHARACTER(LEN=*), INTENT(IN) :: CDFILE,CDTEXT
INTEGER(KIND=JPIM), INTENT(IN) :: KLINENUM
IF (LEN(CDFILE) > 0 .AND. KLINENUM > 0 .AND. NULERR >= 0) THEN
 1000 FORMAT(1X,A,A,":",I6.6)
  WRITE(NULERR,1000) 'ABOR1FL HAS BEEN CALLED AT ',CDFILE,KLINENUM
  CALL FLUSH(NULERR)
ENDIF
CALL ABOR1(CDTEXT)
END SUBROUTINE ABOR1FL
