SUBROUTINE DR_HOOK_PROCINFO(KMYPROC, KNPROC)
USE PARKIND1  ,ONLY : JPIM     ,JPRB
#ifdef SFX_MPL
USE MPL_MODULE, ONLY : MPL_RANK,MPL_NUMPROC
#endif
IMPLICIT NONE
#ifdef SFX_MPI
INCLUDE 'mpif.h'
#endif
INTEGER(KIND=JPIM),INTENT(OUT) :: KMYPROC, KNPROC
INTEGER(KIND=JPIM) :: IRNK,ISZ,IERR
LOGICAL :: LLINIT
#ifdef SFX_MPL
KMYPROC = MPL_RANK
KNPROC = MPL_NUMPROC
#else
IRNK=0
ISZ=1
#ifdef SFX_MPI
CALL MPI_INITIALIZED(LLINIT, IERR)
IF(LLINIT) THEN
  CALL MPI_COMM_RANK(MPI_COMM_WORLD,IRNK,IERR)
  CALL MPI_COMM_SIZE(MPI_COMM_WORLD,ISZ,IERR)
ENDIF
#endif
KMYPROC = IRNK+1
KNPROC = ISZ
#endif
END SUBROUTINE DR_HOOK_PROCINFO
