INTERFACE
SUBROUTINE COMPACT(PVALCO_COMPACT,KNELEM,KBITEXPONENT,KBITRADICAL,KPACK)

USE PARKIND1 , ONLY : JPRB
USE YOMHOOK  , ONLY : LHOOK, DR_HOOK

IMPLICIT NONE

INTEGER(KIND=4) :: KNELEM
REAL(KIND=8) :: PVALCO_COMPACT(KNELEM)
REAL(KIND=8) :: ZCOEF,VALMIN,VALMAX
INTEGER(KIND=4) :: KBITEXPONENT,KBITRADICAL
REAL(KIND=8) :: KPACK(KNELEM)
END SUBROUTINE COMPACT
END INTERFACE
