!define ISRCHFLTPV_N
!define ISRCHFLTPV_ARRAY(I)
!define ISRCHFLTPV_INC
!define ISRCHFLTPV_TARGET
!define ISRCHFLTPV_NBITER
!define ISRCHFLTPV_RESULT
      ISRCHFLTPV_RESULT = -1
      IF (ISRCHFLTPV_N.LE.0) THEN
        ISRCHFLTPV_RESULT=0
      ELSE


        IF (ISRCHFLTPV_NBITER.EQ.8) THEN

        DO ISRCHFLTPV_I=1,ISRCHFLTPV_N-ISRCHFLTPV_NBITER
          IF ( ISRCHFLTPV_ARRAY(1+ISRCHFLTPV_INC*(ISRCHFLTPV_I-1)).LT.ISRCHFLTPV_TARGET ) THEN
          IF ( ISRCHFLTPV_ARRAY(1+ISRCHFLTPV_INC*(ISRCHFLTPV_I)).LT.ISRCHFLTPV_TARGET ) THEN
          IF ( ISRCHFLTPV_ARRAY(1+ISRCHFLTPV_INC*(ISRCHFLTPV_I+1)).LT.ISRCHFLTPV_TARGET ) THEN
          IF ( ISRCHFLTPV_ARRAY(1+ISRCHFLTPV_INC*(ISRCHFLTPV_I+2)).LT.ISRCHFLTPV_TARGET ) THEN
          IF ( ISRCHFLTPV_ARRAY(1+ISRCHFLTPV_INC*(ISRCHFLTPV_I+3)).LT.ISRCHFLTPV_TARGET ) THEN
          IF ( ISRCHFLTPV_ARRAY(1+ISRCHFLTPV_INC*(ISRCHFLTPV_I+4)).LT.ISRCHFLTPV_TARGET ) THEN
          IF ( ISRCHFLTPV_ARRAY(1+ISRCHFLTPV_INC*(ISRCHFLTPV_I+5)).LT.ISRCHFLTPV_TARGET ) THEN
          IF ( ISRCHFLTPV_ARRAY(1+ISRCHFLTPV_INC*(ISRCHFLTPV_I+6)).LT.ISRCHFLTPV_TARGET ) THEN
          IF ( ISRCHFLTPV_ARRAY(1+ISRCHFLTPV_INC*(ISRCHFLTPV_I+7)).LT.ISRCHFLTPV_TARGET ) THEN
             ISRCHFLTPV_RESULT=ISRCHFLTPV_I
             EXIT
          ENDIF
          ENDIF
          ENDIF
          ENDIF
          ENDIF
          ENDIF
          ENDIF
          ENDIF
          ENDIF
        ENDDO

        IF (ISRCHFLTPV_RESULT .LT. 0) THEN
          DO ISRCHFLTPV_I=ISRCHFLTPV_N-ISRCHFLTPV_NBITER+1,ISRCHFLTPV_N
            IF ( ISRCHFLTPV_ARRAY(1+ISRCHFLTPV_INC*(ISRCHFLTPV_I-1))&
            &.LT.ISRCHFLTPV_TARGET ) THEN
              ISRCHFLTPV_RESULT=ISRCHFLTPV_I
              EXIT
            ENDIF
          ENDDO
        ENDIF


        ELSEIF (ISRCHFLTPV_NBITER.EQ.6) THEN

        DO ISRCHFLTPV_I=1,ISRCHFLTPV_N-ISRCHFLTPV_NBITER
          IF ( ISRCHFLTPV_ARRAY(1+ISRCHFLTPV_INC*(ISRCHFLTPV_I-1)).LT.ISRCHFLTPV_TARGET ) THEN
          IF ( ISRCHFLTPV_ARRAY(1+ISRCHFLTPV_INC*(ISRCHFLTPV_I)).LT.ISRCHFLTPV_TARGET ) THEN
          IF ( ISRCHFLTPV_ARRAY(1+ISRCHFLTPV_INC*(ISRCHFLTPV_I+1)).LT.ISRCHFLTPV_TARGET ) THEN
          IF ( ISRCHFLTPV_ARRAY(1+ISRCHFLTPV_INC*(ISRCHFLTPV_I+2)).LT.ISRCHFLTPV_TARGET ) THEN
          IF ( ISRCHFLTPV_ARRAY(1+ISRCHFLTPV_INC*(ISRCHFLTPV_I+3)).LT.ISRCHFLTPV_TARGET ) THEN
          IF ( ISRCHFLTPV_ARRAY(1+ISRCHFLTPV_INC*(ISRCHFLTPV_I+4)).LT.ISRCHFLTPV_TARGET ) THEN
          IF ( ISRCHFLTPV_ARRAY(1+ISRCHFLTPV_INC*(ISRCHFLTPV_I+5)).LT.ISRCHFLTPV_TARGET ) THEN
             ISRCHFLTPV_RESULT=ISRCHFLTPV_I
             EXIT
          ENDIF
          ENDIF
          ENDIF
          ENDIF
          ENDIF
          ENDIF
          ENDIF
        ENDDO

        IF (ISRCHFLTPV_RESULT .LT. 0) THEN
          DO ISRCHFLTPV_I=ISRCHFLTPV_N-ISRCHFLTPV_NBITER+1,ISRCHFLTPV_N
            IF ( ISRCHFLTPV_ARRAY(1+ISRCHFLTPV_INC*(ISRCHFLTPV_I-1))&
            &.LT.ISRCHFLTPV_TARGET ) THEN
              ISRCHFLTPV_RESULT=ISRCHFLTPV_I
              EXIT
            ENDIF
          ENDDO
        ENDIF

        ELSEIF (ISRCHFLTPV_NBITER.EQ.5) THEN

        DO ISRCHFLTPV_I=1,ISRCHFLTPV_N-ISRCHFLTPV_NBITER
          IF ( ISRCHFLTPV_ARRAY(1+ISRCHFLTPV_INC*(ISRCHFLTPV_I-1))&
          &.LT.ISRCHFLTPV_TARGET ) THEN
          IF ( ISRCHFLTPV_ARRAY(1+ISRCHFLTPV_INC*(ISRCHFLTPV_I))&
          &.LT.ISRCHFLTPV_TARGET ) THEN
          IF ( ISRCHFLTPV_ARRAY(1+ISRCHFLTPV_INC*(ISRCHFLTPV_I+1))&
          &.LT.ISRCHFLTPV_TARGET ) THEN
          IF ( ISRCHFLTPV_ARRAY(1+ISRCHFLTPV_INC*(ISRCHFLTPV_I+2))&
          &.LT.ISRCHFLTPV_TARGET ) THEN
           IF ( ISRCHFLTPV_ARRAY(1+ISRCHFLTPV_INC*(ISRCHFLTPV_I+3))&
          &.LT.ISRCHFLTPV_TARGET ) THEN
           IF ( ISRCHFLTPV_ARRAY(1+ISRCHFLTPV_INC*(ISRCHFLTPV_I+4))&
          &.LT.ISRCHFLTPV_TARGET ) THEN
            ISRCHFLTPV_RESULT=ISRCHFLTPV_I
            EXIT
          ENDIF
          ENDIF
          ENDIF
          ENDIF
          ENDIF
          ENDIF
        ENDDO

        IF (ISRCHFLTPV_RESULT .LT. 0) THEN
          DO ISRCHFLTPV_I=ISRCHFLTPV_N-ISRCHFLTPV_NBITER+1,ISRCHFLTPV_N
            IF ( ISRCHFLTPV_ARRAY(1+ISRCHFLTPV_INC*(ISRCHFLTPV_I-1))&
            &.LT.ISRCHFLTPV_TARGET ) THEN
              ISRCHFLTPV_RESULT=ISRCHFLTPV_I
              EXIT
            ENDIF
          ENDDO
        ENDIF



        ELSEIF (ISRCHFLTPV_NBITER.EQ.4) THEN

        DO ISRCHFLTPV_I=1,ISRCHFLTPV_N-ISRCHFLTPV_NBITER
          IF ( ISRCHFLTPV_ARRAY(1+ISRCHFLTPV_INC*(ISRCHFLTPV_I-1))&
          &.LT.ISRCHFLTPV_TARGET ) THEN
          IF ( ISRCHFLTPV_ARRAY(1+ISRCHFLTPV_INC*(ISRCHFLTPV_I))&
          &.LT.ISRCHFLTPV_TARGET ) THEN
          IF ( ISRCHFLTPV_ARRAY(1+ISRCHFLTPV_INC*(ISRCHFLTPV_I+1))&
          &.LT.ISRCHFLTPV_TARGET ) THEN
          IF ( ISRCHFLTPV_ARRAY(1+ISRCHFLTPV_INC*(ISRCHFLTPV_I+2))&
          &.LT.ISRCHFLTPV_TARGET ) THEN
           IF ( ISRCHFLTPV_ARRAY(1+ISRCHFLTPV_INC*(ISRCHFLTPV_I+3))&
          &.LT.ISRCHFLTPV_TARGET ) THEN

            ISRCHFLTPV_RESULT=ISRCHFLTPV_I
            EXIT
          ENDIF
          ENDIF
          ENDIF
          ENDIF
          ENDIF
        ENDDO

        IF (ISRCHFLTPV_RESULT .LT. 0) THEN
          DO ISRCHFLTPV_I=ISRCHFLTPV_N-ISRCHFLTPV_NBITER+1,ISRCHFLTPV_N
            IF ( ISRCHFLTPV_ARRAY(1+ISRCHFLTPV_INC*(ISRCHFLTPV_I-1))&
            &.LT.ISRCHFLTPV_TARGET ) THEN
              ISRCHFLTPV_RESULT=ISRCHFLTPV_I
              EXIT
            ENDIF
          ENDDO
        ENDIF


        ELSEIF (ISRCHFLTPV_NBITER.EQ.3) THEN

        DO ISRCHFLTPV_I=1,ISRCHFLTPV_N-ISRCHFLTPV_NBITER
          IF ( ISRCHFLTPV_ARRAY(1+ISRCHFLTPV_INC*(ISRCHFLTPV_I-1))&
          &.LT.ISRCHFLTPV_TARGET ) THEN
          IF ( ISRCHFLTPV_ARRAY(1+ISRCHFLTPV_INC*(ISRCHFLTPV_I))&
          &.LT.ISRCHFLTPV_TARGET ) THEN
          IF ( ISRCHFLTPV_ARRAY(1+ISRCHFLTPV_INC*(ISRCHFLTPV_I+1))&
          &.LT.ISRCHFLTPV_TARGET ) THEN
          IF ( ISRCHFLTPV_ARRAY(1+ISRCHFLTPV_INC*(ISRCHFLTPV_I+2))&
          &.LT.ISRCHFLTPV_TARGET ) THEN
            ISRCHFLTPV_RESULT=ISRCHFLTPV_I
            EXIT
          ENDIF
          ENDIF
          ENDIF
          ENDIF
        ENDDO

        IF (ISRCHFLTPV_RESULT .LT. 0) THEN
          DO ISRCHFLTPV_I=ISRCHFLTPV_N-ISRCHFLTPV_NBITER+1,ISRCHFLTPV_N
            IF ( ISRCHFLTPV_ARRAY(1+ISRCHFLTPV_INC*(ISRCHFLTPV_I-1))&
            &.LT.ISRCHFLTPV_TARGET ) THEN
              ISRCHFLTPV_RESULT=ISRCHFLTPV_I
              EXIT
            ENDIF
          ENDDO
        ENDIF

        ELSEIF (ISRCHFLTPV_NBITER.EQ.2) THEN

        DO ISRCHFLTPV_I=1,ISRCHFLTPV_N-ISRCHFLTPV_NBITER
          IF ( ISRCHFLTPV_ARRAY(1+ISRCHFLTPV_INC*(ISRCHFLTPV_I-1))&
          &.LT.ISRCHFLTPV_TARGET ) THEN
          IF ( ISRCHFLTPV_ARRAY(1+ISRCHFLTPV_INC*(ISRCHFLTPV_I))&
          &.LT.ISRCHFLTPV_TARGET ) THEN
          IF ( ISRCHFLTPV_ARRAY(1+ISRCHFLTPV_INC*(ISRCHFLTPV_I+1))&
          &.LT.ISRCHFLTPV_TARGET ) THEN
            ISRCHFLTPV_RESULT=ISRCHFLTPV_I
            EXIT
          ENDIF
          ENDIF
          ENDIF
        ENDDO

        IF (ISRCHFLTPV_RESULT .LT. 0) THEN
          DO ISRCHFLTPV_I=ISRCHFLTPV_N-ISRCHFLTPV_NBITER+1,ISRCHFLTPV_N
            IF ( ISRCHFLTPV_ARRAY(1+ISRCHFLTPV_INC*(ISRCHFLTPV_I-1))&
            &.LT.ISRCHFLTPV_TARGET ) THEN
              ISRCHFLTPV_RESULT=ISRCHFLTPV_I
              EXIT
            ENDIF
          ENDDO
        ENDIF

        ELSEIF (ISRCHFLTPV_NBITER.EQ.1) THEN

        DO ISRCHFLTPV_I=1,ISRCHFLTPV_N-ISRCHFLTPV_NBITER
          IF ( ISRCHFLTPV_ARRAY(1+ISRCHFLTPV_INC*(ISRCHFLTPV_I-1))&
          &.LT.ISRCHFLTPV_TARGET ) THEN
          IF ( ISRCHFLTPV_ARRAY(1+ISRCHFLTPV_INC*(ISRCHFLTPV_I))&
          &.LT.ISRCHFLTPV_TARGET ) THEN
            ISRCHFLTPV_RESULT=ISRCHFLTPV_I
            EXIT
          ENDIF
          ENDIF
        ENDDO

        IF (ISRCHFLTPV_RESULT .LT. 0) THEN
          DO ISRCHFLTPV_I=ISRCHFLTPV_N-ISRCHFLTPV_NBITER+1,ISRCHFLTPV_N
            IF ( ISRCHFLTPV_ARRAY(1+ISRCHFLTPV_INC*(ISRCHFLTPV_I-1))&
            &.LT.ISRCHFLTPV_TARGET ) THEN
              ISRCHFLTPV_RESULT=ISRCHFLTPV_I
              EXIT
            ENDIF
          ENDDO
        ENDIF

        ELSEIF (ISRCHFLTPV_NBITER.EQ.0) THEN

        DO ISRCHFLTPV_I=1,ISRCHFLTPV_N-ISRCHFLTPV_NBITER
          IF ( ISRCHFLTPV_ARRAY(1+ISRCHFLTPV_INC*(ISRCHFLTPV_I-1))&
          &.LT.ISRCHFLTPV_TARGET ) THEN
            ISRCHFLTPV_RESULT=ISRCHFLTPV_I
            EXIT
          ENDIF
        ENDDO

        ELSE
        CALL ABOR1('ISRCHFLTPV: ERROR WITH NBITER VALUE')
        ENDIF

        IF (ISRCHFLTPV_RESULT .LT. 0) THEN
        ISRCHFLTPV_RESULT=ISRCHFLTPV_N+1
        ENDIF

      ENDIF
