INTERFACE
SUBROUTINE SUFFTP(KDLON,KFFTP0,LDODD)
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM), INTENT(IN) :: KDLON
INTEGER(KIND=JPIM), INTENT(OUT) :: KFFTP0(KDLON)
LOGICAL, INTENT(IN) :: LDODD
END SUBROUTINE SUFFTP
END INTERFACE
