! Jan-2011 P. Marguinaud Thread-safe FA
SUBROUTINE FAAUTO_FORT  (FA, KNUMER, LDLFI)
USE FA_MOD, ONLY : FA_COM, JPNIIL
USE PARKIND1, ONLY : JPRB
USE YOMHOOK , ONLY : LHOOK, DR_HOOK
USE LFI_PRECISION
USE SDL_MOD, ONLY : SDL_SRLABORT
IMPLICIT NONE
!****
!        Sous-programme de recherche d'une unite libre.
!
!**
!     ARGUMENTS : 
!                 KNUMER (Sortie) ==> Unite logique libre
!
!
TYPE(FA_COM) :: FA
INTEGER (KIND=JPLIKB) KNUMER
LOGICAL               LDLFI
INTEGER (KIND=JPLIKB) IRANGF
LOGICAL               LLOPEN

REAL(KIND=JPRB) :: ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK('FAAUTO_MT',0,ZHOOK_HANDLE)

IF (ALL (FA%FICHIER%NULOGI.NE.JPNIIL)) THEN
  CALL SDL_SRLABORT
ENDIF

KNUMER=-1000

DO

  CALL FANUMU_FORT  (FA, KNUMER, IRANGF)

  IF (ASSOCIATED (FA%LFI) .AND. LDLFI) THEN
    CALL LFIPRO_MT64 (FA%LFI, KNUMER, LLOPEN)
  ELSE
    LLOPEN = .FALSE.
  ENDIF

  IF ((.NOT. LLOPEN) .AND. (IRANGF == 0)) EXIT

  KNUMER=KNUMER-1

ENDDO

IF (LHOOK) CALL DR_HOOK('FAAUTO_MT',1,ZHOOK_HANDLE)

END SUBROUTINE
