INTERFACE
SUBROUTINE FAGRIBEX (KSEC0,KSEC1,KSEC2,PSEC2,KSEC3,PSEC3,KSEC4, &
&                    PSEC4,KLENP,KGRIB,KLENG,KWORD,HOPER,KRET)
USE LFI_PRECISION
IMPLICIT NONE
INTEGER (KIND=JPLIKB) :: KSEC0 (:)
INTEGER (KIND=JPLIKB) :: KSEC1 (:)
INTEGER (KIND=JPLIKB) :: KSEC2 (:)
INTEGER (KIND=JPLIKB) :: KSEC3 (:)
INTEGER (KIND=JPLIKB) :: KSEC4 (:)
INTEGER (KIND=JPLIKB) :: KGRIB (*)
INTEGER (KIND=JPLIKB) :: KLENP
INTEGER (KIND=JPLIKB) :: KLENG
INTEGER (KIND=JPLIKB) :: KWORD 
INTEGER (KIND=JPLIKB) :: KRET
REAL (KIND=JPDBLR)    :: PSEC2 (:) 
REAL (KIND=JPDBLR)    :: PSEC3 (:) 
REAL (KIND=JPDBLR)    :: PSEC4 (*)
CHARACTER(LEN=*)      :: HOPER
END SUBROUTINE
END INTERFACE

