!! Oct-2012 P. Marguinaud 64b LFI
SUBROUTINE FAGRIBEX (KSEC0,KSEC1,KSEC2,PSEC2,KSEC3,PSEC3,KSEC4, &
&                     PSEC4,KLENP,KGRIB,KLENG,KWORD,HOPER,KRET)
!USE LFI_PRECISION
!IMPLICIT NONE
!INTEGER (KIND=JPLIKB) :: KSEC0 (:)
!INTEGER (KIND=JPLIKB) :: KSEC1 (:)
!INTEGER (KIND=JPLIKB) :: KSEC2 (:)
!INTEGER (KIND=JPLIKB) :: KSEC3 (:)
!INTEGER (KIND=JPLIKB) :: KSEC4 (:)
!INTEGER (KIND=JPDBLR) :: KGRIB (*)
!INTEGER (KIND=JPLIKB) :: KLENP
!INTEGER (KIND=JPLIKB) :: KLENG
!INTEGER (KIND=JPLIKB) :: KWORD 
!INTEGER (KIND=JPLIKB) :: KRET
!REAL (KIND=JPDBLR)    :: PSEC2 (:) 
!REAL (KIND=JPDBLR)    :: PSEC3 (:) 
!REAL (KIND=JPDBLR)    :: PSEC4 (*)
!CHARACTER(LEN=*)      :: HOPER
!!
!INTEGER (KIND=JPLIKM) :: ISEC0 (SIZE(KSEC0))
!INTEGER (KIND=JPLIKM) :: ISEC1 (SIZE(KSEC1))
!INTEGER (KIND=JPLIKM) :: ISEC2 (SIZE(KSEC2))
!INTEGER (KIND=JPLIKM) :: ISEC3 (SIZE(KSEC3))
!INTEGER (KIND=JPLIKM) :: ISEC4 (SIZE(KSEC4))
!INTEGER (KIND=JPLIKM) :: ILENP
!INTEGER (KIND=JPLIKM) :: ILENG
!INTEGER (KIND=JPLIKM) :: IWORD 
!INTEGER (KIND=JPLIKM) :: IRET
!!
!ISEC0 = INT (KSEC0, JPLIKM)
!ISEC1 = INT (KSEC1, JPLIKM)
!ISEC2 = INT (KSEC2, JPLIKM)
!ISEC3 = INT (KSEC3, JPLIKM)
!ISEC4 = INT (KSEC4, JPLIKM)
!ILENP = INT (KLENP, JPLIKM)
!ILENG = INT (KLENG, JPLIKM)
!IWORD = INT (KWORD, JPLIKM)
!IRET  = INT (KRET , JPLIKM)
!
!CALL GRIBEX (ISEC0,ISEC1,ISEC2,PSEC2,ISEC3,PSEC3,ISEC4, &
!&             PSEC4,ILENP,KGRIB,ILENG,IWORD,HOPER,IRET)
!
!KSEC0 = INT (ISEC0, JPLIKB)
!KSEC1 = INT (ISEC1, JPLIKB)
!KSEC2 = INT (ISEC2, JPLIKB)
!KSEC3 = INT (ISEC3, JPLIKB)
!KSEC4 = INT (ISEC4, JPLIKB)
!KLENP = INT (ILENP, JPLIKB)
!KLENG = INT (ILENG, JPLIKB)
!KWORD = INT (IWORD, JPLIKB)
!KRET  = INT (IRET , JPLIKB)
!
END SUBROUTINE FAGRIBEX
