INTERFACE

SUBROUTINE FANFAN_FORT                                             &
                     (FA,  KREP, KNUMER, CDPREF, KNIVAU, CDSUFF,  &
                      CDNOMA, KLNOMA)
USE FA_MOD, ONLY : FA_COM
USE LFI_PRECISION
IMPLICIT NONE
TYPE(FA_COM) :: FA
INTEGER (KIND=JPLIKB) KREP, KNUMER, KNIVAU, KLNOMA
CHARACTER CDPREF*(*), CDSUFF*(*), CDNOMA*(*)
END SUBROUTINE FANFAN_FORT

END INTERFACE
