FUNCTION GET_PROC_ID() RESULT(PID)

USE PARKIND1  ,ONLY : JPIM
#ifdef SFX_MPI
USE MPL_MODULE, ONLY : MPL_RANK
#endif
IMPLICIT NONE
INTEGER(KIND=JPIM) :: PID
#ifdef SFX_MPI
PID = MPL_RANK
#else
PID = 0
#endif

END FUNCTION GET_PROC_ID
