SUBROUTINE GOTO_WRAPPER_PACK (KFROM, KTO, LKFROM)
USE MODD_PACK_CH_ISBA
USE MODD_PACK_DIAG_ISBA
USE MODD_PACK_ISBA
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE 
LOGICAL, INTENT(IN) :: LKFROM
INTEGER,INTENT(IN) :: KFROM,KTO
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
IF (LHOOK) CALL DR_HOOK('GOTO_WRAPPER_PACK',0,ZHOOK_HANDLE)
 CALL PACK_CH_ISBA_GOTO_MODEL(KFROM, KTO, LKFROM)
 CALL PACK_DIAG_ISBA_GOTO_MODEL(KFROM, KTO, LKFROM)
 CALL PACK_ISBA_GOTO_MODEL(KFROM, KTO, LKFROM)
IF (LHOOK) CALL DR_HOOK('GOTO_WRAPPER_PACK',1,ZHOOK_HANDLE)
!
END SUBROUTINE GOTO_WRAPPER_PACK
