!     ######################
      MODULE MODD_PACK_CH_ISBA
!     ######################
!
!!****  *MODD_PACK_CH_ISBA - declaration of packed surface parameters for chemistry
!!
!!    PURPOSE
!!    -------
!
!!
!!**  IMPLICIT ARGUMENTS
!!    ------------------
!!      None 
!!
!!    REFERENCE
!!    ---------
!!
!!    AUTHOR
!!    ------
!!      A. Boone   *Meteo France*
!!
!!    MODIFICATIONS
!!    -------------
!!      Original       20/09/02
!
!*       0.   DECLARATIONS
!             ------------
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE
!
!-------------------------------------------------------------------------------
!
TYPE PACK_CH_ISBA_t

  REAL, POINTER, DIMENSION(:,:) :: XBLOCK_SIMPLE
  REAL, POINTER, DIMENSION(:)   :: XP_SOILRC_SO2 ! for SO2 deposition
  REAL, POINTER, DIMENSION(:)   :: XP_SOILRC_O3  ! for SO2 deposition
  REAL, POINTER, DIMENSION(:,:) :: XP_DEP        ! deposition velocity

END TYPE PACK_CH_ISBA_t
!
!-------------------------------------------------------------------------------
!
TYPE(PACK_CH_ISBA_t), ALLOCATABLE, TARGET, SAVE :: PACK_CH_ISBA_MODEL(:)

TYPE(PACK_CH_ISBA_t), POINTER :: PACK_CH_ISBA => NULL()
!$OMP THREADPRIVATE(PACK_CH_ISBA)

CONTAINS

SUBROUTINE PACK_CH_ISBA_GOTO_MODEL(KFROM, KTO, LKFROM)
LOGICAL, INTENT(IN) :: LKFROM
!
INTEGER, INTENT(IN) :: KFROM, KTO
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
! Current model is set to model KTO
IF (LHOOK) CALL DR_HOOK('MODD_PACK_CH_ISBA_N:PACK_CH_ISBA_GOTO_MODEL',0,ZHOOK_HANDLE)

PACK_CH_ISBA => PACK_CH_ISBA_MODEL(KTO)

IF (LHOOK) CALL DR_HOOK('MODD_PACK_CH_ISBA_N:PACK_CH_ISBA_GOTO_MODEL',1,ZHOOK_HANDLE)

END SUBROUTINE PACK_CH_ISBA_GOTO_MODEL

SUBROUTINE PACK_CH_ISBA_ALLOC(KMODEL)
INTEGER, INTENT(IN) :: KMODEL
INTEGER :: J
REAL(KIND=JPRB) :: ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK("MODD_PACK_CH_ISBA_N:PACK_CH_ISBA_ALLOC",0,ZHOOK_HANDLE)
ALLOCATE(PACK_CH_ISBA_MODEL(KMODEL))
PACK_CH_ISBA => PACK_CH_ISBA_MODEL(KMODEL)
DO J=1,KMODEL
  NULLIFY(PACK_CH_ISBA_MODEL(J)%XBLOCK_SIMPLE)
  NULLIFY(PACK_CH_ISBA_MODEL(J)%XP_SOILRC_SO2)
  NULLIFY(PACK_CH_ISBA_MODEL(J)%XP_SOILRC_O3)
  NULLIFY(PACK_CH_ISBA_MODEL(J)%XP_DEP)
ENDDO
IF (LHOOK) CALL DR_HOOK("MODD_PACK_CH_ISBA_N:PACK_CH_ISBA_ALLOC",1,ZHOOK_HANDLE)
END SUBROUTINE PACK_CH_ISBA_ALLOC

SUBROUTINE PACK_CH_ISBA_DEALLO
REAL(KIND=JPRB) :: ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK("MODD_PACK_CH_ISBA_N:PACK_CH_ISBA_DEALLO",0,ZHOOK_HANDLE)
IF (ALLOCATED(PACK_CH_ISBA_MODEL)) DEALLOCATE(PACK_CH_ISBA_MODEL)
IF (ASSOCIATED(PACK_CH_ISBA)) NULLIFY(PACK_CH_ISBA)
IF (LHOOK) CALL DR_HOOK("MODD_PACK_CH_ISBA_N:PACK_CH_ISBA_DEALLO",1,ZHOOK_HANDLE)
END SUBROUTINE PACK_CH_ISBA_DEALLO

END MODULE MODD_PACK_CH_ISBA
