!##################
MODULE MODD_TEB_GREENROOF_PGD_EVOL_n
!##################
!
!!****  *MODD_TEB_GREENROOF - declaration of ISBA scheme packed surface parameters for urban green roofs
!!
!!    PURPOSE
!!    -------
!
!!
!!**  IMPLICIT ARGUMENTS
!!    ------------------
!!      None 
!!
!!    REFERENCE
!!    ---------
!!
!!    AUTHOR
!!    ------
!!      A. Lemonsu *Meteo France*
!!
!!    MODIFICATIONS
!!    -------------
!!      Original       09/2009
!!      C. de Munck     06/2011 
!!      V. Masson       06/2013  splits module in 4
!!
!-------------------------------------------------------------------------------
!
!*       0.   DECLARATIONS
!             ------------
!
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE

TYPE TEB_GREENROOF_PGD_EVOL_1P_t
! - Vegetation: Ags Prognostic (YPHOTO = ('LAI', 'LST', or 'NIT') or prescribed (YPHOTO='NON', 'AGS' or 'LST')
!
  REAL, POINTER, DIMENSION(:)   :: XLAI              ! Leaf Area Index                         (m2/m2)
  REAL, POINTER, DIMENSION(:)   :: XVEG              ! vegetation cover fraction               (-)
  REAL, POINTER, DIMENSION(:)   :: XALBNIR           ! near-infra-red albedo                   (-)
  REAL, POINTER, DIMENSION(:)   :: XALBVIS           ! visible albedo                          (-)
  REAL, POINTER, DIMENSION(:)   :: XALBUV            ! UV albedo                               (-)
  REAL, POINTER, DIMENSION(:)   :: XEMIS             ! surface emissivity                      (-)
  REAL, POINTER, DIMENSION(:)   :: XZ0               ! surface roughness length                (m)
!
END TYPE TEB_GREENROOF_PGD_EVOL_1P_t

TYPE TEB_GREENROOF_PGD_EVOL_t
  !
  TYPE(TEB_GREENROOF_PGD_EVOL_1P_t), POINTER :: ALP(:) => NULL()
  TYPE(TEB_GREENROOF_PGD_EVOL_1P_t), POINTER :: CUR => NULL()
  !
END TYPE TEB_GREENROOF_PGD_EVOL_t

TYPE(TEB_GREENROOF_PGD_EVOL_t),ALLOCATABLE, TARGET, SAVE :: TEB_GREENROOF_PGD_EVOL_MODEL(:)

TYPE(TEB_GREENROOF_PGD_EVOL_t), POINTER :: TEB_GREENROOF_PGD_EVOL => NULL()
!$OMP THREADPRIVATE(TEB_GREENROOF_PGD_EVOL)

CONTAINS

SUBROUTINE TEB_GREENROOF_PGD_EVOL_GOTO_MODEL(KFROM, KTO, LKFROM)
LOGICAL, INTENT(IN) :: LKFROM
INTEGER, INTENT(IN) :: KFROM, KTO
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
! Current model is set to model KTO
IF (LHOOK) CALL DR_HOOK('MODD_TEB_GREENROOF_N:TEB_GREENROOF_PGD_EVOL_GOTO_MODEL',0,ZHOOK_HANDLE)

TEB_GREENROOF_PGD_EVOL => TEB_GREENROOF_PGD_EVOL_MODEL(KTO)

IF (LHOOK) CALL DR_HOOK('MODD_TEB_GREENROOF_N:TEB_GREENROOF_PGD_EVOL_GOTO_MODEL',1,ZHOOK_HANDLE)
!
END SUBROUTINE TEB_GREENROOF_PGD_EVOL_GOTO_MODEL

SUBROUTINE TEB_GREENROOF_PGD_EVOL_GOTO_PATCH(KTO_PATCH)
INTEGER, INTENT(IN) :: KTO_PATCH
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
! Current patch is set to patch KTO_PATCH
IF (LHOOK) CALL DR_HOOK('MODD_TEB_GREENROOF_PGD_EVOL_N:TEB_GREENROOF_PGD_EVOL_GOTO_PATCH',0,ZHOOK_HANDLE)

TEB_GREENROOF_PGD_EVOL%CUR => TEB_GREENROOF_PGD_EVOL%ALP(KTO_PATCH)

IF (LHOOK) CALL DR_HOOK('MODD_TEB_GREENROOF_PGD_EVOL_N:TEB_GREENROOF_PGD_EVOL_GOTO_PATCH',1,ZHOOK_HANDLE)
!
END SUBROUTINE TEB_GREENROOF_PGD_EVOL_GOTO_PATCH

SUBROUTINE TEB_GREENROOF_PGD_EVOL_ALLOC(KMODEL,KPATCH)
INTEGER, INTENT(IN) :: KMODEL, KPATCH
INTEGER :: J, JP
REAL(KIND=JPRB) :: ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK("MODD_TEB_GREENROOF_N:TEB_GREENROOF_PGD_EVOL_ALLOC",0,ZHOOK_HANDLE)
ALLOCATE(TEB_GREENROOF_PGD_EVOL_MODEL(KMODEL))
TEB_GREENROOF_PGD_EVOL => TEB_GREENROOF_PGD_EVOL_MODEL(KMODEL)
DO J=1,KMODEL
 ALLOCATE(TEB_GREENROOF_PGD_EVOL_MODEL(J)%ALP(KPATCH))
 DO JP=1,KPATCH
NULLIFY(TEB_GREENROOF_PGD_EVOL_MODEL(J)%ALP(JP)%XALBNIR)
NULLIFY(TEB_GREENROOF_PGD_EVOL_MODEL(J)%ALP(JP)%XALBVIS)
NULLIFY(TEB_GREENROOF_PGD_EVOL_MODEL(J)%ALP(JP)%XALBUV)
NULLIFY(TEB_GREENROOF_PGD_EVOL_MODEL(J)%ALP(JP)%XEMIS)
NULLIFY(TEB_GREENROOF_PGD_EVOL_MODEL(J)%ALP(JP)%XZ0)
NULLIFY(TEB_GREENROOF_PGD_EVOL_MODEL(J)%ALP(JP)%XVEG)
NULLIFY(TEB_GREENROOF_PGD_EVOL_MODEL(J)%ALP(JP)%XLAI)
 ENDDO
ENDDO
IF (LHOOK) CALL DR_HOOK("MODD_TEB_GREENROOF_N:TEB_GREENROOF_PGD_EVOL_ALLOC",1,ZHOOK_HANDLE)
END SUBROUTINE TEB_GREENROOF_PGD_EVOL_ALLOC

SUBROUTINE TEB_GREENROOF_PGD_EVOL_DEALLO
REAL(KIND=JPRB) :: ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK("MODD_TEB_GREENROOF_N:TEB_GREENROOF_PGD_EVOL_DEALLO",0,ZHOOK_HANDLE)
IF (ALLOCATED(TEB_GREENROOF_PGD_EVOL_MODEL)) DEALLOCATE(TEB_GREENROOF_PGD_EVOL_MODEL)
IF (ASSOCIATED(TEB_GREENROOF_PGD_EVOL)) NULLIFY(TEB_GREENROOF_PGD_EVOL)
IF (LHOOK) CALL DR_HOOK("MODD_TEB_GREENROOF_N:TEB_GREENROOF_PGD_EVOL_DEALLO",1,ZHOOK_HANDLE)
END SUBROUTINE TEB_GREENROOF_PGD_EVOL_DEALLO

END MODULE MODD_TEB_GREENROOF_PGD_EVOL_n
