!     #########
SUBROUTINE READ_ALL_NAMELISTS (CHF, CHI, CHS, CHU, CHT, CHW, &
                               DGEI, DGF, DGL, DGI, DGMF, DGMI, DGMTO, DGO, DGS, DGSI, DGU, DGT, DGUT, DGW, &
                               F, I, O, S, USS, TGRO, T, TOP, TVG, W, &
                               HPROGRAM,HINIT,ONAM_READ)
!
!
!
!
!
!
!
!
!
!
USE MODD_CH_FLAKE_n, ONLY : CH_FLAKE_t
USE MODD_CH_ISBA_n, ONLY : CH_ISBA_t
USE MODD_CH_SEAFLUX_n, ONLY : CH_SEAFLUX_t
USE MODD_CH_SURF_n, ONLY : CH_SURF_t
USE MODD_CH_TEB_n, ONLY : CH_TEB_t
USE MODD_CH_WATFLUX_n, ONLY : CH_WATFLUX_t
USE MODD_DIAG_EVAP_ISBA_n, ONLY : DIAG_EVAP_ISBA_t
USE MODD_DIAG_FLAKE_n, ONLY : DIAG_FLAKE_t
USE MODD_DIAG_IDEAL_n, ONLY : DIAG_IDEAL_t
USE MODD_DIAG_ISBA_n, ONLY : DIAG_ISBA_t
USE MODD_DIAG_MISC_FLAKE_n, ONLY : DIAG_MISC_FLAKE_t
USE MODD_DIAG_MISC_ISBA_n, ONLY : DIAG_MISC_ISBA_t
USE MODD_DIAG_MISC_TEB_OPTION_n, ONLY : DIAG_MISC_TEB_OPTIONS_t
USE MODD_DIAG_OCEAN_n, ONLY : DIAG_OCEAN_t
USE MODD_DIAG_SEAFLUX_n, ONLY : DIAG_SEAFLUX_t
USE MODD_DIAG_SEAICE_n, ONLY : DIAG_SEAICE_t
USE MODD_DIAG_SURF_ATM_n, ONLY : DIAG_SURF_ATM_t
USE MODD_DIAG_TEB_n, ONLY : DIAG_TEB_t
USE MODD_DIAG_UTCI_TEB_n, ONLY : DIAG_UTCI_TEB_t
USE MODD_DIAG_WATFLUX_n, ONLY : DIAG_WATFLUX_t
USE MODD_FLAKE_n, ONLY : FLAKE_t
USE MODD_ISBA_n, ONLY : ISBA_t
USE MODD_OCEAN_n, ONLY : OCEAN_t
USE MODD_SEAFLUX_n, ONLY : SEAFLUX_t
USE MODD_SURF_ATM_SSO_n, ONLY : SURF_ATM_SSO_t
USE MODD_TEB_GREENROOF_OPTION_n, ONLY : TEB_GREENROOF_OPTIONS_t
USE MODD_TEB_n, ONLY : TEB_t
USE MODD_TEB_OPTION_n, ONLY : TEB_OPTIONS_t
USE MODD_TEB_VEG_n, ONLY : TEB_VEG_OPTIONS_t
USE MODD_WATFLUX_n, ONLY : WATFLUX_t
!
USE MODD_READ_NAMELIST, ONLY : LNAM_READ
!
USE MODI_INIT_READ_DATA_COVER
!
USE MODI_READ_NAMELISTS_SURF_n
USE MODI_READ_NAMELISTS_SURF
USE MODI_READ_NAMELISTS_FLAKE_n
USE MODI_READ_NAMELISTS_WATFLUX_n
USE MODI_READ_NAMELISTS_SEAFLUX_n
USE MODI_READ_NAMELISTS_ISBA_n
USE MODI_READ_NAMELISTS_ISBA
USE MODI_READ_NAMELISTS_TEB_n
USE MODI_READ_NAMELISTS_IDEAL_n
USE MODI_READ_NAMELISTS_IDEAL
USE MODI_READ_NAMELISTS_SLT
USE MODI_READ_NAMELISTS_DST
USE MODI_READ_NAMELISTS_ASSIM
USE MODI_READ_NAMELISTS_TOPD
!
USE MODI_READ_NAM_PREP_FLAKE_n
USE MODI_READ_NAM_PREP_GARDEN_n
USE MODI_READ_NAM_PREP_GREENROOF_n
USE MODI_READ_NAM_PREP_ISBA_n
USE MODI_READ_NAM_PREP_SEAFLUX_n
USE MODI_READ_NAM_PREP_SURF_n
USE MODI_READ_NAM_PREP_TEB_n
USE MODI_READ_NAM_PREP_WATFLUX_n
!
!--------------------------------------------------
!
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE
!
!
TYPE(CH_FLAKE_t), INTENT(INOUT) :: CHF
TYPE(CH_ISBA_t), INTENT(INOUT) :: CHI
TYPE(CH_SEAFLUX_t), INTENT(INOUT) :: CHS
TYPE(CH_SURF_t), INTENT(INOUT) :: CHU
TYPE(CH_TEB_t), INTENT(INOUT) :: CHT
TYPE(CH_WATFLUX_t), INTENT(INOUT) :: CHW
TYPE(DIAG_EVAP_ISBA_t), INTENT(INOUT) :: DGEI
TYPE(DIAG_FLAKE_t), INTENT(INOUT) :: DGF
TYPE(DIAG_IDEAL_t), INTENT(INOUT) :: DGL
TYPE(DIAG_ISBA_t), INTENT(INOUT) :: DGI
TYPE(DIAG_MISC_FLAKE_t), INTENT(INOUT) :: DGMF
TYPE(DIAG_MISC_ISBA_t), INTENT(INOUT) :: DGMI
TYPE(DIAG_MISC_TEB_OPTIONS_t), INTENT(INOUT) :: DGMTO
TYPE(DIAG_OCEAN_t), INTENT(INOUT) :: DGO
TYPE(DIAG_SEAFLUX_t), INTENT(INOUT) :: DGS
TYPE(DIAG_SEAICE_t), INTENT(INOUT) :: DGSI
TYPE(DIAG_SURF_ATM_t), INTENT(INOUT) :: DGU
TYPE(DIAG_TEB_t), INTENT(INOUT) :: DGT
TYPE(DIAG_UTCI_TEB_t), INTENT(INOUT) :: DGUT
TYPE(DIAG_WATFLUX_t), INTENT(INOUT) :: DGW
TYPE(FLAKE_t), INTENT(INOUT) :: F
TYPE(ISBA_t), INTENT(INOUT) :: I
TYPE(OCEAN_t), INTENT(INOUT) :: O
TYPE(SEAFLUX_t), INTENT(INOUT) :: S
TYPE(SURF_ATM_SSO_t), INTENT(INOUT) :: USS
TYPE(TEB_GREENROOF_OPTIONS_t), INTENT(INOUT) :: TGRO
TYPE(TEB_t), INTENT(INOUT) :: T
TYPE(TEB_OPTIONS_t), INTENT(INOUT) :: TOP
TYPE(TEB_VEG_OPTIONS_t), INTENT(INOUT) :: TVG
TYPE(WATFLUX_t), INTENT(INOUT) :: W
!
 CHARACTER(LEN=6),  INTENT(IN)   :: HPROGRAM  ! program calling surf. schemes
 CHARACTER(LEN=3),   INTENT(IN)  :: HINIT     ! choice of fields to initialize
LOGICAL,INTENT(IN)              :: ONAM_READ
!
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
!----------------------------------------
!namelists always read here
!
IF (LHOOK) CALL DR_HOOK('READ_ALL_NAMELISTS',0,ZHOOK_HANDLE)
LNAM_READ=.TRUE.
!
 CALL INIT_READ_DATA_COVER(HPROGRAM)
!
 CALL READ_NAMELISTS_SURF(HPROGRAM)
 CALL READ_NAMELISTS_ISBA(HPROGRAM)
 CALL READ_NAMELISTS_SLT(HPROGRAM)
 CALL READ_NAMELISTS_DST(HPROGRAM)
 CALL READ_NAMELISTS_IDEAL(HPROGRAM)
 CALL READ_NAMELISTS_ASSIM(HPROGRAM)
 CALL READ_NAMELISTS_TOPD(HPROGRAM)
!
IF (HPROGRAM=='AROME ') THEN
#ifdef SFX_ARO
  CALL READ_NAMELISTS_IO(HPROGRAM)
#endif
ENDIF
!
LNAM_READ = ONAM_READ
!
!namelists that can be reread in surfex code
!
IF (.NOT.LNAM_READ) THEN
! 
  LNAM_READ=.TRUE.
  !
  CALL READ_NAMELISTS_SURF_n(CHU, DGU, USS, &
                             HPROGRAM,HINIT)
  !
  CALL READ_NAMELISTS_FLAKE_n(CHF, DGF, DGMF, F, &
                              HPROGRAM,HINIT)
  CALL READ_NAMELISTS_WATFLUX_n(CHW, DGW, W, &
                                HPROGRAM,HINIT)
  CALL READ_NAMELISTS_SEAFLUX_n(CHS, DGO, DGS, DGSI, O, S, &
                                HPROGRAM,HINIT)
  CALL READ_NAMELISTS_ISBA_n(CHI, DGEI, DGI, DGMI, I, &
                             HPROGRAM,HINIT)
  CALL READ_NAMELISTS_TEB_n(CHT, DGMTO, DGT, DGUT, TGRO, T, TOP, TVG, &
                            HPROGRAM,HINIT)
  CALL READ_NAMELISTS_IDEAL_n(DGL, &
                              HPROGRAM)
  !
  LNAM_READ=.FALSE.
  !
  !prep namelists, to be read even if reread in surfex code, 
  !because only partially reread
  !
ELSEIF (HINIT=='PRE') THEN
  !
  CALL READ_NAM_PREP_SURF_n(HPROGRAM)
  CALL READ_NAM_PREP_FLAKE_n(HPROGRAM)
  CALL READ_NAM_PREP_WATFLUX_n(HPROGRAM)
  CALL READ_NAM_PREP_SEAFLUX_n(HPROGRAM) 
  CALL READ_NAM_PREP_ISBA_n(HPROGRAM)
  CALL READ_NAM_PREP_GARDEN_n(HPROGRAM)
  CALL READ_NAM_PREP_GREENROOF_n(HPROGRAM)
  CALL READ_NAM_PREP_TEB_n(HPROGRAM)
  !
ENDIF
!
IF (LHOOK) CALL DR_HOOK('READ_ALL_NAMELISTS',1,ZHOOK_HANDLE)
!-------------------------------------------
END SUBROUTINE READ_ALL_NAMELISTS
