#!/bin/bash
#
if test $# -ne 1
then
  echo " "
  echo "Syntaxe : $0 name_of_user_directory"
  echo " "
  exit
fi
#
NAME=$1
#
export VERSION_BUG=0
#
export VER_MPI="MPIAUTO"
#
export VERSION_MASTER="SFX-V8-0"
export VERSION_XYZ=${VERSION_MASTER}-${VERSION_BUG}
export VER_USER=$NAME
#
TARG=$(uname -s -n)
case "$TARG" in
'Linux lx'*|'Linux sx'*|'Linux px'*) #PC
	export ARCH=${ARCH:-LXgfortran}
        ;;
'Linux beaufix'*) #BEAUFIX     
        export ARCH=${ARCH:-LXifort} 	
        ;;
esac	
#
#export OPTLEVEL="DEBUG"
export OPTLEVEL="O2"
#
./configure
#
. ../conf/profile_surfex-$ARCH-$VERSION_XYZ-$NAME-$VER_MPI-$OPTLEVEL
#
iflag=0
#
make user || { iflag=1 ; }
if [ $iflag -eq 1 ] ; then
    echo " "
    echo "              ###########################"
    echo "              Probleme compilation surfex" $NAME
    echo "              ###########################"
    echo " "
    exit 1
fi 
#
make installuser
#
exit
