!     #################################################################################
SUBROUTINE DEALLOC_TEB_n
!     #################################################################################
!
!!****  *DEALLOC_TEB_n * - Deallocate all arrays
!!
!!    PURPOSE
!!    -------
!
!!**  METHOD
!!    ------
!!
!!    REFERENCE
!!    ---------
!!      
!!
!!    AUTHOR
!!    ------
!!     V. Masson 
!!
!!    MODIFICATIONS
!!    -------------
!!      Original    01/2004
!!------------------------------------------------------------------
!

!
USE MODD_TEB_n,      ONLY : LCOVER, XCOVER, XZS,                                     &
                              XH_TRAFFIC, XLE_TRAFFIC, XH_INDUSTRY, XLE_INDUSTRY,      &
                              XZ0_TOWN, XBLD, XGARDEN, XVEG_ROOF,                      &
                              XBLD_HEIGHT, XWALL_O_HOR, XCAN_HW_RATIO,                 &
                              XALB_ROOF, XEMIS_ROOF, XHC_ROOF,XTC_ROOF, XD_ROOF,       &
                              XALB_ROAD, XEMIS_ROAD, XHC_ROAD,XTC_ROAD, XD_ROAD,       &
                              XALB_WALL, XEMIS_WALL, XHC_WALL,XTC_WALL, XD_WALL,       &
                              XSVF_ROAD, XSVF_WALL, TSNOW_ROOF, TSNOW_ROAD,            &
                              NROOF_LAYER, NROAD_LAYER, NWALL_LAYER,                   &
                              XT_ROOF, XT_ROAD, XT_WALL,                               &
                              XAC_ROOF, XAC_ROAD, XAC_WALL, XAC_TOP,                   &
                              XAC_ROOF_WAT, XAC_ROAD_WAT,                              &
                              XQSAT_ROOF, XQSAT_ROAD, XDELT_ROOF, XDELT_ROAD  
USE MODD_TEB_GRID_n, ONLY : XGRID_PAR, XLAT, XLON, XMESH_SIZE
USE MODD_CH_TEB_n,   ONLY : XDEP, CCH_NAMES, CSV
!
USE MODD_DATA_TEB_n, ONLY : XPAR_Z0_TOWN, XPAR_BLD, XPAR_ALB_ROOF,         &
                              XPAR_EMIS_ROOF, XPAR_HC_ROOF, XPAR_TC_ROOF,  &
                              XPAR_D_ROOF, XPAR_ALB_ROAD, XPAR_EMIS_ROAD,  &
                              XPAR_HC_ROAD, XPAR_TC_ROAD, XPAR_D_ROAD,     &
                              XPAR_ALB_WALL, XPAR_EMIS_WALL, XPAR_HC_WALL, &
                              XPAR_TC_WALL, XPAR_D_WALL, XPAR_BLD_HEIGHT,  &
                              XPAR_WALL_O_HOR,                             &
                              XPAR_H_TRAFFIC, XPAR_LE_TRAFFIC,             &
                              XPAR_H_INDUSTRY, XPAR_LE_INDUSTRY ,          &
                              XPAR_VEG_ROOF, XPAR_GARDEN, XPAR_URBTYPE
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE
!
!*      0.1    declarations of arguments
!
!
!*      0.2    declarations of local variables
!
!-------------------------------------------------------------------------------------
!

REAL(KIND=JPRB) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('DEALLOC_TEB_N',0,ZHOOK_HANDLE)
IF (ASSOCIATED(LCOVER ))  DEALLOCATE(LCOVER )
IF (ASSOCIATED(XCOVER ))  DEALLOCATE(XCOVER )
IF (ASSOCIATED(XZS    ))  DEALLOCATE(XZS    )
!
!-------------------------------------------------------------------------------------
!
IF (ASSOCIATED(XGRID_PAR )) DEALLOCATE(XGRID_PAR )
IF (ASSOCIATED(XLAT      )) DEALLOCATE(XLAT      )
IF (ASSOCIATED(XLON      )) DEALLOCATE(XLON      )
IF (ASSOCIATED(XMESH_SIZE)) DEALLOCATE(XMESH_SIZE)
!
!-------------------------------------------------------------------------------------
!
IF(ASSOCIATED(XZ0_TOWN     )) DEALLOCATE(XZ0_TOWN     )
IF(ASSOCIATED(XALB_ROOF    )) DEALLOCATE(XALB_ROOF    )
IF(ASSOCIATED(XEMIS_ROOF   )) DEALLOCATE(XEMIS_ROOF   )
IF(ASSOCIATED(XALB_ROAD    )) DEALLOCATE(XALB_ROAD    )
IF(ASSOCIATED(XEMIS_ROAD   )) DEALLOCATE(XEMIS_ROAD   )
IF(ASSOCIATED(XALB_WALL    )) DEALLOCATE(XALB_WALL    )
IF(ASSOCIATED(XEMIS_WALL   )) DEALLOCATE(XEMIS_WALL   )
IF(ASSOCIATED(XBLD         )) DEALLOCATE(XBLD         )
IF(ASSOCIATED(XGARDEN      )) DEALLOCATE(XGARDEN      )
IF(ASSOCIATED(XVEG_ROOF    )) DEALLOCATE(XVEG_ROOF    )
IF(ASSOCIATED(XBLD_HEIGHT  )) DEALLOCATE(XBLD_HEIGHT  )
IF(ASSOCIATED(XWALL_O_HOR  )) DEALLOCATE(XWALL_O_HOR  )
IF(ASSOCIATED(XCAN_HW_RATIO)) DEALLOCATE(XCAN_HW_RATIO)
IF(ASSOCIATED(XH_TRAFFIC   )) DEALLOCATE(XH_TRAFFIC   )
IF(ASSOCIATED(XLE_TRAFFIC  )) DEALLOCATE(XLE_TRAFFIC  )
IF(ASSOCIATED(XH_INDUSTRY  )) DEALLOCATE(XH_INDUSTRY  )
IF(ASSOCIATED(XLE_INDUSTRY )) DEALLOCATE(XLE_INDUSTRY )
IF(ASSOCIATED(XHC_ROOF )) DEALLOCATE(XHC_ROOF )
IF(ASSOCIATED(XTC_ROOF )) DEALLOCATE(XTC_ROOF )
IF(ASSOCIATED(XD_ROOF  )) DEALLOCATE(XD_ROOF  )
IF(ASSOCIATED(XHC_ROAD )) DEALLOCATE(XHC_ROAD )
IF(ASSOCIATED(XTC_ROAD )) DEALLOCATE(XTC_ROAD )
IF(ASSOCIATED(XD_ROAD  )) DEALLOCATE(XD_ROAD  )
IF(ASSOCIATED(XHC_WALL )) DEALLOCATE(XHC_WALL )
IF(ASSOCIATED(XTC_WALL )) DEALLOCATE(XTC_WALL )
IF(ASSOCIATED(XD_WALL  )) DEALLOCATE(XD_WALL  )
IF(ASSOCIATED(XSVF_ROAD)) DEALLOCATE(XSVF_ROAD)
IF(ASSOCIATED(XSVF_WALL)) DEALLOCATE(XSVF_WALL)
!
!-------------------------------------------------------------------------------------
!
IF(ASSOCIATED(XAC_ROOF    ))  DEALLOCATE(XAC_ROOF    )
IF(ASSOCIATED(XAC_ROAD    ))  DEALLOCATE(XAC_ROAD    )
IF(ASSOCIATED(XAC_WALL    ))  DEALLOCATE(XAC_WALL    )
IF(ASSOCIATED(XAC_TOP     ))  DEALLOCATE(XAC_TOP     )
IF(ASSOCIATED(XAC_ROOF_WAT))  DEALLOCATE(XAC_ROOF_WAT)
IF(ASSOCIATED(XAC_ROAD_WAT))  DEALLOCATE(XAC_ROAD_WAT)
IF(ASSOCIATED(XQSAT_ROOF  ))  DEALLOCATE(XQSAT_ROOF  )
IF(ASSOCIATED(XQSAT_ROAD  ))  DEALLOCATE(XQSAT_ROAD  )
IF(ASSOCIATED(XDELT_ROOF  ))  DEALLOCATE(XDELT_ROOF  )
IF(ASSOCIATED(XDELT_ROAD  ))  DEALLOCATE(XDELT_ROAD  )
!
!-------------------------------------------------------------------------------------
!
IF(ASSOCIATED(XDEP))      DEALLOCATE(XDEP)
IF(ASSOCIATED(CCH_NAMES)) DEALLOCATE(CCH_NAMES)
IF(ASSOCIATED(CSV))       DEALLOCATE(CSV)
!
!-------------------------------------------------------------------------------------
!
IF(ASSOCIATED(XPAR_Z0_TOWN    )) DEALLOCATE(XPAR_Z0_TOWN    )
IF(ASSOCIATED(XPAR_BLD        )) DEALLOCATE(XPAR_BLD        )
IF(ASSOCIATED(XPAR_ALB_ROOF   )) DEALLOCATE(XPAR_ALB_ROOF   )
IF(ASSOCIATED(XPAR_EMIS_ROOF  )) DEALLOCATE(XPAR_EMIS_ROOF  )
IF(ASSOCIATED(XPAR_HC_ROOF    )) DEALLOCATE(XPAR_HC_ROOF    )
IF(ASSOCIATED(XPAR_TC_ROOF    )) DEALLOCATE(XPAR_TC_ROOF    )
IF(ASSOCIATED(XPAR_D_ROOF     )) DEALLOCATE(XPAR_D_ROOF     )
IF(ASSOCIATED(XPAR_ALB_ROAD   )) DEALLOCATE(XPAR_ALB_ROAD   )
IF(ASSOCIATED(XPAR_EMIS_ROAD  )) DEALLOCATE(XPAR_EMIS_ROAD  )
IF(ASSOCIATED(XPAR_HC_ROAD    )) DEALLOCATE(XPAR_HC_ROAD    )
IF(ASSOCIATED(XPAR_TC_ROAD    )) DEALLOCATE(XPAR_TC_ROAD    )
IF(ASSOCIATED(XPAR_D_ROAD     )) DEALLOCATE(XPAR_D_ROAD     )
IF(ASSOCIATED(XPAR_ALB_WALL   )) DEALLOCATE(XPAR_ALB_WALL   )
IF(ASSOCIATED(XPAR_EMIS_WALL  )) DEALLOCATE(XPAR_EMIS_WALL  )
IF(ASSOCIATED(XPAR_HC_WALL    )) DEALLOCATE(XPAR_HC_WALL    )
IF(ASSOCIATED(XPAR_TC_WALL    )) DEALLOCATE(XPAR_TC_WALL    )
IF(ASSOCIATED(XPAR_D_WALL     )) DEALLOCATE(XPAR_D_WALL     )
IF(ASSOCIATED(XPAR_BLD_HEIGHT )) DEALLOCATE(XPAR_BLD_HEIGHT )
IF(ASSOCIATED(XPAR_WALL_O_HOR )) DEALLOCATE(XPAR_WALL_O_HOR )
IF(ASSOCIATED(XPAR_H_TRAFFIC  )) DEALLOCATE(XPAR_H_TRAFFIC  )
IF(ASSOCIATED(XPAR_LE_TRAFFIC )) DEALLOCATE(XPAR_LE_TRAFFIC )
IF(ASSOCIATED(XPAR_H_INDUSTRY )) DEALLOCATE(XPAR_H_INDUSTRY )
IF(ASSOCIATED(XPAR_LE_INDUSTRY)) DEALLOCATE(XPAR_LE_INDUSTRY)
IF(ASSOCIATED(XPAR_VEG_ROOF   )) DEALLOCATE(XPAR_VEG_ROOF   )
IF(ASSOCIATED(XPAR_GARDEN     )) DEALLOCATE(XPAR_GARDEN     )
IF(ASSOCIATED(XPAR_URBTYPE    )) DEALLOCATE(XPAR_URBTYPE    )
!
IF (LHOOK) CALL DR_HOOK('DEALLOC_TEB_N',1,ZHOOK_HANDLE)
!
!-------------------------------------------------------------------------------------
!
END SUBROUTINE DEALLOC_TEB_n


