SUBROUTINE EXTRAPOL_FIELDS(HPROGRAM,HSFTYPE,KLUOUT)
!!
!!    PURPOSE
!!    -------
!!  parameters defined by cover need to be extrapolated if LDATA_VEGTYPE and NOT LDATA_"PARAM"
!!  all ten-day periods are calculated one time for all, then written in PGD.txt
!!
!!    METHOD
!!    ------ 
!!  these parameters are: LAI, HT, DG, ROOTFRAC, IRRIG, WATSUP
!!  Parameters are calculated as in ecoclimap, by vegtype, and then extrapolated
!
!!    EXTERNAL
!!    --------
!!
!!    IMPLICIT ARGUMENTS
!!    ------------------
!!
!!    REFERENCE
!!    ---------
!!
!!    AUTHOR
!!    ------
!!
!!    S. Faroux        Meteo-France
!!
!!    MODIFICATION
!!    ------------
!!
!!    Original    16/11/10
!!
!!    DECLARATIONS
!!
USE MODD_SURF_PAR,       ONLY : XUNDEF
!
USE MODD_ISBA_n,         ONLY : XCOVER
USE MODD_DATA_COVER,     ONLY : XDATA_LAI, XDATA_DG, XDATA_H_TREE, XDATA_CUM_ROOT_FRAC, &
                                XDATA_IRRIG, XDATA_WATSUP,                              &
                                XDATA_GARDEN, XDATA_NATURE,                             &
                                XDATA_ROOT_DEPTH, XDATA_GROUND_DEPTH,                   &
                                XDATA_ROOT_EXTINCTION, XDATA_ROOT_LIN
USE MODD_DATA_ISBA_n,    ONLY : XPAR_LAI, XPAR_H_TREE, XPAR_DG, XPAR_ROOTFRAC, &
                                XPAR_IRRIG, XPAR_WATSUP, &
                                LDATA_VEGTYPE, LDATA_LAI, LDATA_H_TREE, LDATA_DG, &
                                LDATA_ROOTFRAC, LDATA_IRRIG, LDATA_WATSUP    
USE MODD_ISBA_n,         ONLY : CISBA, NGROUND_LAYER
!
USE MODI_AV_PGD
USE MODI_INI_DATA_SOIL
USE MODI_INI_VAR_FROM_VEGTYPE_DATA

USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB

IMPLICIT NONE

CHARACTER(LEN=6), INTENT(IN) :: HPROGRAM  ! host program
INTEGER, INTENT(IN) :: KLUOUT
CHARACTER(LEN=*),       INTENT(IN)    :: HSFTYPE ! nature / garden
CHARACTER(LEN=3)  :: YTREE, YNAT, YVEG
INTEGER :: JTIME, JLAYER
REAL, DIMENSION(SIZE(XPAR_LAI,3)) :: ZDEF

REAL(KIND=JPRB) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('EXTRAPOL_FIELDS',0,ZHOOK_HANDLE)

IF (HSFTYPE=='NAT') THEN
  YNAT='NAT'
  YTREE='TRE'
  YVEG='VEG'
ELSEIF (HSFTYPE=='GRD') THEN
  YNAT='GRD'
  YTREE='GRT'
  YVEG='GRV'
ENDIF
!
!            2. Extrapolations for land use
!            ------------------------------
!
!   LAI
!   ---
IF (.NOT.LDATA_LAI) THEN
  ZDEF(1:3)=0.
  ZDEF(4:6)=2.
  ZDEF(7:9)=1.5
  ZDEF(10:12)=1.5
  DO JTIME=1,36 
    CALL AV_PGD(XPAR_LAI(:,JTIME,:),XCOVER,XDATA_LAI(:,JTIME,:),YVEG,'ARI',KDECADE=JTIME)
    CALL INI_VAR_FROM_VEGTYPE_DATA(HPROGRAM,KLUOUT,'LAI: leaf area index',XPAR_LAI(:,JTIME,:),PDEF=ZDEF)
    !XPAR_LAI(:,:,1:3)=XUNDEF
  ENDDO
  LDATA_LAI=.TRUE.
ENDIF
!
!   H_TREE
!   ------
IF (.NOT.LDATA_H_TREE) THEN
  ZDEF(:)=0.
  ZDEF(4:6)=10.
  CALL AV_PGD(XPAR_H_TREE,XCOVER,XDATA_H_TREE,YTREE,'ARI')
  CALL INI_VAR_FROM_VEGTYPE_DATA(HPROGRAM,KLUOUT,'H_TREE: height of trees',XPAR_H_TREE,PDEF=ZDEF)
  LDATA_H_TREE=.TRUE.
ENDIF
!
!   DG
!   --
IF (.NOT.LDATA_DG) THEN

   ALLOCATE(XDATA_DG(SIZE(XDATA_ROOT_DEPTH,1),NGROUND_LAYER,SIZE(XDATA_ROOT_DEPTH,2)))
   ALLOCATE(XDATA_CUM_ROOT_FRAC(SIZE(XDATA_ROOT_DEPTH,1),NGROUND_LAYER,SIZE(XDATA_ROOT_DEPTH,2)))

   CALL INI_DATA_SOIL(CISBA,PSURF=XDATA_NATURE,PSURF2=XDATA_GARDEN,PROOT_DEPTH=XDATA_ROOT_DEPTH,&
      PGROUND_DEPTH=XDATA_GROUND_DEPTH,PROOT_EXTINCTION=XDATA_ROOT_EXTINCTION,&
      PROOT_LIN=XDATA_ROOT_LIN,PDG_OUT=XDATA_DG,PCUM_ROOT_FRAC=XDATA_CUM_ROOT_FRAC)

  DO JLAYER=1,NGROUND_LAYER
    IF (JLAYER==1) THEN
      ZDEF(:)=0.01
    ELSEIF (JLAYER==2) THEN
      ZDEF(1)=0.5
      ZDEF(2)=0.2
      ZDEF(3)=0.2
      ZDEF(4:6)=2.
      ZDEF(7:12)=1.5
    ELSE
      ZDEF(1)=ZDEF(1)+0.5
      ZDEF(2:3)=ZDEF(2:3)+0.1
      ZDEF(4:6)=ZDEF(4:6)+1.
      ZDEF(7:12)=ZDEF(7:12)+0.5
    ENDIF
    CALL AV_PGD (XPAR_DG(:,JLAYER,:),XCOVER,XDATA_DG(:,JLAYER,:),YNAT,'ARI')
    CALL INI_VAR_FROM_VEGTYPE_DATA(HPROGRAM,KLUOUT,'DG: ground depth', XPAR_DG(:,JLAYER,:),PDEF=ZDEF)
  ENDDO
  LDATA_DG=.TRUE.
!
!   ROOTFRAC
!   --------
  IF (.NOT.LDATA_ROOTFRAC) THEN
          
    ZDEF(:)=0.3
    DO JLAYER=1,NGROUND_LAYER
      CALL AV_PGD (XPAR_ROOTFRAC(:,JLAYER,:),XCOVER,XDATA_CUM_ROOT_FRAC(:,JLAYER,:),YNAT,'ARI')
      IF (CISBA=='DIF') &
        CALL INI_VAR_FROM_VEGTYPE_DATA(HPROGRAM,KLUOUT,'ROOTFRAC: root fraction',XPAR_ROOTFRAC(:,JLAYER,:),PDEF=ZDEF)
    ENDDO
    LDATA_ROOTFRAC=.TRUE.

  ENDIF

  DEALLOCATE(XDATA_DG)
  DEALLOCATE(XDATA_CUM_ROOT_FRAC)

ENDIF
!
!  IRRIG
!  -----
IF (.NOT.LDATA_IRRIG) THEN
  ZDEF(:)=0.
  DO JTIME=1,36
    CALL AV_PGD(XPAR_IRRIG(:,JTIME,:),XCOVER,XDATA_IRRIG,YVEG,'ARI',KDECADE=JTIME)
    CALL INI_VAR_FROM_VEGTYPE_DATA(HPROGRAM,KLUOUT,'IRRIG  ', XPAR_IRRIG(:,JTIME,:), PDEF=ZDEF)
  ENDDO
  LDATA_IRRIG=.TRUE.
ENDIF
!
!   WATSUP
!   ------
IF (.NOT.LDATA_WATSUP) THEN
  ZDEF(:)=0.
  DO JTIME=1,36
    CALL AV_PGD(XPAR_WATSUP(:,JTIME,:),XCOVER,XDATA_WATSUP,YVEG,'ARI',KDECADE=JTIME)  
    CALL INI_VAR_FROM_VEGTYPE_DATA(HPROGRAM,KLUOUT,'WATSUP  ', XPAR_WATSUP(:,JTIME,:), PDEF=ZDEF)
  ENDDO
  LDATA_WATSUP=.TRUE.
ENDIF
!
IF (LHOOK) CALL DR_HOOK('EXTRAPOL_FIELDS',1,ZHOOK_HANDLE)
!
END SUBROUTINE EXTRAPOL_FIELDS
