SUBROUTINE GOTO_WRAPPER_TEB(KFROM,KTO, LKFROM)
USE MODD_CH_TEB_n
USE MODD_DIAG_MISC_TEB_n
USE MODD_DIAG_TEB_n
USE MODD_TEB_GRID_n
USE MODD_TEB_n
USE MODD_DATA_TEB_n
USE MODD_DATA_TEB_GARDEN_n
USE MODD_TEB_CANOPY_n
USE MODD_TEB_GARDEN_n
USE MODD_DIAG_TEB_GARDEN_n
USE MODD_AGRI_GARDEN_n
USE MODD_GR_BIOG_GARDEN_n
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE 
LOGICAL, INTENT(IN) :: LKFROM
INTEGER,INTENT(IN) :: KFROM,KTO
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
IF (LHOOK) CALL DR_HOOK('GOTO_WRAPPER_TEB',0,ZHOOK_HANDLE)
CALL CH_TEB_GOTO_MODEL(KFROM, KTO, LKFROM)
CALL DIAG_MISC_TEB_GOTO_MODEL(KFROM, KTO, LKFROM)
CALL DIAG_TEB_GOTO_MODEL(KFROM, KTO, LKFROM)
CALL TEB_GRID_GOTO_MODEL(KFROM, KTO, LKFROM)
CALL TEB_GOTO_MODEL(KFROM, KTO, LKFROM)
CALL DATA_TEB_GOTO_MODEL(KFROM, KTO, LKFROM)
CALL DATA_TEB_GARDEN_GOTO_MODEL(KFROM, KTO, LKFROM)
CALL TEB_CANOPY_GOTO_MODEL(KFROM, KTO, LKFROM)
CALL TEB_GARDEN_GOTO_MODEL(KFROM, KTO, LKFROM)
CALL DIAG_TEB_GARDEN_GOTO_MODEL(KFROM, KTO, LKFROM)
CALL AGRI_GARDEN_GOTO_MODEL(KFROM, KTO, LKFROM)
CALL GR_BIOG_GARDEN_GOTO_MODEL(KFROM, KTO, LKFROM)
IF (LHOOK) CALL DR_HOOK('GOTO_WRAPPER_TEB',1,ZHOOK_HANDLE)
!
END SUBROUTINE GOTO_WRAPPER_TEB
