MODULE MODD_SURFEX_HOST

IMPLICIT NONE

TYPE, ABSTRACT :: SURFEX_HOST_T

CONTAINS

PROCEDURE :: WRITE_SURFX0
PROCEDURE :: WRITE_SURFX1
PROCEDURE :: WRITE_SURFX2
PROCEDURE :: WRITE_SURFN0
PROCEDURE :: WRITE_SURFN1
PROCEDURE :: WRITE_SURFC0
PROCEDURE :: WRITE_SURFL0
PROCEDURE :: WRITE_SURFL1
PROCEDURE :: WRITE_SURFT0
PROCEDURE :: WRITE_SURFT1

PROCEDURE :: READ_SURFX0
PROCEDURE :: READ_SURFX1
PROCEDURE :: READ_SURFX2
PROCEDURE :: READ_SURFN0
PROCEDURE :: READ_SURFN1
PROCEDURE :: READ_SURFC0
PROCEDURE :: READ_SURFL0
PROCEDURE :: READ_SURFL1
PROCEDURE :: READ_SURFT0
PROCEDURE :: READ_SURFT1

PROCEDURE :: READ_COVER

PROCEDURE :: GET_BUFC0
PROCEDURE :: GET_BUFN0
PROCEDURE :: GET_BUFN1
PROCEDURE :: GET_BUFX0
PROCEDURE :: GET_BUFX1

PROCEDURE :: INIT_IO_SURF
PROCEDURE :: END_IO_SURF 

PROCEDURE :: OPEN_AUX_IO_SURF 
PROCEDURE :: CLOSE_AUX_IO_SURF 

PROCEDURE :: OPEN_WRITE_COVER_TEX 
PROCEDURE :: CLOSE_WRITE_COVER_TEX 

PROCEDURE :: OPEN_NAMELIST 
PROCEDURE :: CLOSE_NAMELIST

PROCEDURE :: GET_LUOUT

PROCEDURE :: OI_HOR_EXTRAPOL_SURF

PROCEDURE :: SET_GRESET

PROCEDURE :: ABORT

PROCEDURE :: DETECT_FIELD

PROCEDURE :: GET_DESFM

PROCEDURE :: HAS_FIELD 

PROCEDURE :: SET_BLOCK 

PROCEDURE :: RECORD_OUTPUT 

PROCEDURE :: ALLOCATE_OUTPUT 

PROCEDURE :: GET_SIZE_FULL

PROCEDURE :: SUM_ON_ALL_PROCS 

PROCEDURE :: READ_SURF_LAYER 

PROCEDURE :: ASSIM_DIST_FIELD 

PROCEDURE :: ASSIM_GATHER_FIELD

PROCEDURE :: ASSIM_GET_SIZE_GLOBAL 

PROCEDURE :: PROPAGATE_ICE 

PROCEDURE :: GET_NUMBER_OF_BLOCKS 

END TYPE

CLASS (SURFEX_HOST_T), POINTER :: YRSURFEX_HOST => NULL ()

PRIVATE

PUBLIC :: SURFEX_HOST_T
PUBLIC :: YRSURFEX_HOST

CONTAINS

SUBROUTINE WRITE_SURFX0 (SELF,HREC,PFIELD,KRESP,HCOMMENT)

CLASS (SURFEX_HOST_T) :: SELF
CHARACTER(LEN=*)    ,INTENT(IN)               :: HREC     
REAL                ,INTENT(IN)               :: PFIELD   
INTEGER             ,INTENT(OUT)              :: KRESP    
CHARACTER(LEN=100)  ,INTENT(IN)               :: HCOMMENT 

STOP 'NOT IMPLMENTED'

END SUBROUTINE WRITE_SURFX0 

SUBROUTINE WRITE_SURFX1 (SELF,HREC,KL,PFIELD,KRESP,HCOMMENT,HDIR)

CLASS (SURFEX_HOST_T) :: SELF
CHARACTER(LEN=*)    ,INTENT(IN)               :: HREC     
INTEGER             ,INTENT(IN)               :: KL       
REAL                ,INTENT(IN)               :: PFIELD(KL)
INTEGER             ,INTENT(OUT)              :: KRESP    
CHARACTER(LEN=100)  ,INTENT(IN)               :: HCOMMENT 
CHARACTER(LEN=1)    ,INTENT(IN)               :: HDIR     

STOP 'NOT IMPLMENTED'

END SUBROUTINE WRITE_SURFX1 

SUBROUTINE WRITE_SURFX2 (SELF,HREC,KL1,KL2,PFIELD,KRESP,HCOMMENT,HDIR)

CLASS (SURFEX_HOST_T) :: SELF
CHARACTER(LEN=*)    ,INTENT(IN)               :: HREC     
INTEGER             ,INTENT(IN)               :: KL1      
INTEGER             ,INTENT(IN)               :: KL2      
REAL                ,INTENT(IN)               :: PFIELD(KL1,KL2) 
INTEGER             ,INTENT(OUT)              :: KRESP    
CHARACTER(LEN=100)  ,INTENT(IN)               :: HCOMMENT 
CHARACTER(LEN=1)    ,INTENT(IN)               :: HDIR     

STOP 'NOT IMPLMENTED'

END SUBROUTINE WRITE_SURFX2 

SUBROUTINE WRITE_SURFN0 (SELF,HREC,KFIELD,KRESP,HCOMMENT)

CLASS (SURFEX_HOST_T) :: SELF
CHARACTER(LEN=*)    ,INTENT(IN)               :: HREC     
INTEGER             ,INTENT(IN)               :: KFIELD   
INTEGER             ,INTENT(OUT)              :: KRESP    
CHARACTER(LEN=100)  ,INTENT(IN)               :: HCOMMENT 

STOP 'NOT IMPLMENTED'

END SUBROUTINE WRITE_SURFN0 

SUBROUTINE WRITE_SURFN1 (SELF,HREC,KL,KFIELD,KRESP,HCOMMENT,HDIR)

CLASS (SURFEX_HOST_T) :: SELF
CHARACTER(LEN=*)    ,INTENT(IN)               :: HREC     
INTEGER             ,INTENT(IN)               :: KL       
INTEGER             ,INTENT(IN)               :: KFIELD(KL)
INTEGER             ,INTENT(OUT)              :: KRESP    
CHARACTER(LEN=100)  ,INTENT(IN)               :: HCOMMENT 
CHARACTER(LEN=1)    ,INTENT(IN)               :: HDIR     

STOP 'NOT IMPLMENTED'

END SUBROUTINE WRITE_SURFN1 

SUBROUTINE WRITE_SURFC0 (SELF,HREC,HFIELD,KRESP,HCOMMENT)

CLASS (SURFEX_HOST_T) :: SELF
CHARACTER(LEN=*)    ,INTENT(IN)               :: HREC     
CHARACTER(LEN=40)   ,INTENT(IN)               :: HFIELD   
INTEGER             ,INTENT(OUT)              :: KRESP    
CHARACTER(LEN=100)  ,INTENT(IN)               :: HCOMMENT 

STOP 'NOT IMPLMENTED'

END SUBROUTINE WRITE_SURFC0 

SUBROUTINE WRITE_SURFL0 (SELF,HREC,OFIELD,KRESP,HCOMMENT)

CLASS (SURFEX_HOST_T) :: SELF
CHARACTER(LEN=*)    ,INTENT(IN)               :: HREC     
LOGICAL             ,INTENT(IN)               :: OFIELD   
INTEGER             ,INTENT(OUT)              :: KRESP    
CHARACTER(LEN=100)  ,INTENT(IN)               :: HCOMMENT 

STOP 'NOT IMPLMENTED'

END SUBROUTINE WRITE_SURFL0 

SUBROUTINE WRITE_SURFL1 (SELF,HREC,KL,OFIELD,KRESP,HCOMMENT,HDIR)

CLASS (SURFEX_HOST_T) :: SELF
CHARACTER(LEN=*)    ,INTENT(IN)               :: HREC     
INTEGER             ,INTENT(IN)               :: KL       
LOGICAL             ,INTENT(IN)               :: OFIELD(KL)
INTEGER             ,INTENT(OUT)              :: KRESP    
CHARACTER(LEN=100)  ,INTENT(IN)               :: HCOMMENT 
CHARACTER(LEN=1)    ,INTENT(IN)               :: HDIR     

STOP 'NOT IMPLMENTED'

END SUBROUTINE WRITE_SURFL1 

SUBROUTINE WRITE_SURFT0 (SELF,HREC,KYEAR,KMONTH,KDAY,PTIME,KRESP,HCOMMENT)

CLASS (SURFEX_HOST_T) :: SELF
CHARACTER(LEN=*)    ,INTENT(IN)               :: HREC     
INTEGER             ,INTENT(IN)               :: KYEAR    
INTEGER             ,INTENT(IN)               :: KMONTH   
INTEGER             ,INTENT(IN)               :: KDAY     
REAL                ,INTENT(IN)               :: PTIME    
INTEGER             ,INTENT(OUT)              :: KRESP    
CHARACTER(LEN=100)  ,INTENT(IN)               :: HCOMMENT 

STOP 'NOT IMPLMENTED'

END SUBROUTINE WRITE_SURFT0 

SUBROUTINE WRITE_SURFT1 (SELF,HREC,KL1,KYEAR,KMONTH,KDAY,PTIME,KRESP,HCOMMENT)

CLASS (SURFEX_HOST_T) :: SELF
CHARACTER(LEN=*)    ,INTENT(IN)               :: HREC     
INTEGER             ,INTENT(IN)               :: KL1      
INTEGER             ,INTENT(IN)               :: KYEAR(KL1)
INTEGER             ,INTENT(IN)               :: KMONTH(KL1) 
INTEGER             ,INTENT(IN)               :: KDAY(KL1) 
REAL                ,INTENT(INOUT)            :: PTIME(KL1) 
INTEGER             ,INTENT(OUT)              :: KRESP    
CHARACTER(LEN=100)  ,INTENT(IN)               :: HCOMMENT 

STOP 'NOT IMPLMENTED'

END SUBROUTINE WRITE_SURFT1 

SUBROUTINE READ_SURFX0 (SELF,HREC,PFIELD,KRESP,HCOMMENT)

CLASS (SURFEX_HOST_T) :: SELF
CHARACTER(LEN=*)    ,INTENT(IN)               :: HREC     
REAL                ,INTENT(OUT)              :: PFIELD   
INTEGER             ,INTENT(OUT)              :: KRESP    
CHARACTER(LEN=100)  ,INTENT(OUT)              :: HCOMMENT 

STOP 'NOT IMPLMENTED'

END SUBROUTINE READ_SURFX0 

SUBROUTINE READ_SURFX1 (SELF,HREC,KL,PFIELD,KRESP,HCOMMENT,HDIR)

CLASS (SURFEX_HOST_T) :: SELF
CHARACTER(LEN=*)    ,INTENT(IN)               :: HREC     
INTEGER             ,INTENT(IN)               :: KL       
REAL                ,INTENT(OUT)              :: PFIELD(KL)
INTEGER             ,INTENT(OUT)              :: KRESP    
CHARACTER(LEN=100)  ,INTENT(OUT)              :: HCOMMENT 
CHARACTER(LEN=1)    ,INTENT(IN)               :: HDIR     

STOP 'NOT IMPLMENTED'

END SUBROUTINE READ_SURFX1 

SUBROUTINE READ_SURFX2 (SELF,HREC,KL1,KL2,PFIELD,KRESP,HCOMMENT,HDIR)

CLASS (SURFEX_HOST_T) :: SELF
CHARACTER(LEN=*)    ,INTENT(IN)               :: HREC     
INTEGER             ,INTENT(IN)               :: KL1      
INTEGER             ,INTENT(IN)               :: KL2      
REAL                ,INTENT(OUT)              :: PFIELD(KL1,KL2)
INTEGER             ,INTENT(OUT)              :: KRESP    
CHARACTER(LEN=100)  ,INTENT(OUT)              :: HCOMMENT 
CHARACTER(LEN=1)    ,INTENT(IN)               :: HDIR     

STOP 'NOT IMPLMENTED'

END SUBROUTINE READ_SURFX2 

SUBROUTINE READ_SURFN0 (SELF,HREC,KFIELD,KRESP,HCOMMENT)

CLASS (SURFEX_HOST_T) :: SELF
CHARACTER(LEN=*)    ,INTENT(IN)               :: HREC     
INTEGER             ,INTENT(OUT)              :: KFIELD   
INTEGER             ,INTENT(OUT)              :: KRESP    
CHARACTER(LEN=100)  ,INTENT(OUT)              :: HCOMMENT 

STOP 'NOT IMPLMENTED'

END SUBROUTINE READ_SURFN0 

SUBROUTINE READ_SURFN1 (SELF,HREC,KL,KFIELD,KRESP,HCOMMENT,HDIR)

CLASS (SURFEX_HOST_T) :: SELF
CHARACTER(LEN=*)    ,INTENT(IN)               :: HREC     
INTEGER             ,INTENT(IN)               :: KL       
INTEGER             ,INTENT(OUT)              :: KFIELD(KL)
INTEGER             ,INTENT(OUT)              :: KRESP    
CHARACTER(LEN=100)  ,INTENT(OUT)              :: HCOMMENT 
CHARACTER(LEN=1)    ,INTENT(IN)               :: HDIR     

STOP 'NOT IMPLMENTED'

END SUBROUTINE READ_SURFN1 

SUBROUTINE READ_SURFC0 (SELF,HREC,HFIELD,KRESP,HCOMMENT)

CLASS (SURFEX_HOST_T) :: SELF
CHARACTER(LEN=*)    ,INTENT(IN)               :: HREC      
CHARACTER(LEN=40)   ,INTENT(OUT)              :: HFIELD    
INTEGER             ,INTENT(OUT)              :: KRESP     
CHARACTER(LEN=100)  ,INTENT(OUT)              :: HCOMMENT  

STOP 'NOT IMPLMENTED'

END SUBROUTINE READ_SURFC0 

SUBROUTINE READ_SURFL0 (SELF,HREC,OFIELD,KRESP,HCOMMENT)

CLASS (SURFEX_HOST_T) :: SELF
CHARACTER(LEN=*)    ,INTENT(IN)               :: HREC     
LOGICAL             ,INTENT(OUT)              :: OFIELD   
INTEGER             ,INTENT(OUT)              :: KRESP    
CHARACTER(LEN=100)  ,INTENT(OUT)              :: HCOMMENT 

STOP 'NOT IMPLMENTED'

END SUBROUTINE READ_SURFL0 

SUBROUTINE READ_SURFL1 (SELF,HREC,KL,OFIELD,KRESP,HCOMMENT,HDIR)

CLASS (SURFEX_HOST_T) :: SELF
CHARACTER(LEN=*)    ,INTENT(IN)               :: HREC    
INTEGER             ,INTENT(IN)               :: KL      
LOGICAL             ,INTENT(OUT)              :: OFIELD(KL)
INTEGER             ,INTENT(OUT)              :: KRESP   
CHARACTER(LEN=100)  ,INTENT(OUT)              :: HCOMMENT
CHARACTER(LEN=1)    ,INTENT(IN)               :: HDIR     

STOP 'NOT IMPLMENTED'

END SUBROUTINE READ_SURFL1 

SUBROUTINE READ_SURFT0 (SELF,HREC,KYEAR,KMONTH,KDAY,PTIME,KRESP,HCOMMENT)

CLASS (SURFEX_HOST_T) :: SELF
CHARACTER(LEN=*)    ,INTENT(IN)               :: HREC     
INTEGER             ,INTENT(OUT)              :: KYEAR    
INTEGER             ,INTENT(OUT)              :: KMONTH   
INTEGER             ,INTENT(OUT)              :: KDAY     
REAL                ,INTENT(OUT)              :: PTIME    
INTEGER             ,INTENT(OUT)              :: KRESP    
CHARACTER(LEN=100)  ,INTENT(OUT)              :: HCOMMENT 

STOP 'NOT IMPLMENTED'

END SUBROUTINE READ_SURFT0 

SUBROUTINE READ_SURFT1 (SELF,HREC,KL1,KYEAR,KMONTH,KDAY,PTIME,KRESP,HCOMMENT)

CLASS (SURFEX_HOST_T) :: SELF
CHARACTER(LEN=*)    ,INTENT(IN)               :: HREC     
INTEGER             ,INTENT(IN)               :: KL1      
INTEGER             ,INTENT(OUT)              :: KYEAR(KL1) 
INTEGER             ,INTENT(OUT)              :: KMONTH(KL1) 
INTEGER             ,INTENT(OUT)              :: KDAY(KL1) 
REAL                ,INTENT(OUT)              :: PTIME(KL1) 
INTEGER             ,INTENT(OUT)              :: KRESP    
CHARACTER(LEN=100)  ,INTENT(OUT)              :: HCOMMENT

STOP 'NOT IMPLMENTED'

END SUBROUTINE READ_SURFT1 

SUBROUTINE READ_COVER (SELF,HREC,KL,PFIELD,KRESP,HCOMMENT,HDIR)

CLASS (SURFEX_HOST_T) :: SELF
CHARACTER(LEN=*)    ,INTENT(IN)               :: HREC     
INTEGER             ,INTENT(IN)               :: KL       
REAL                ,INTENT(OUT)              :: PFIELD(KL)
INTEGER             ,INTENT(OUT)              :: KRESP    
CHARACTER(LEN=100)  ,INTENT(OUT)              :: HCOMMENT 
CHARACTER(LEN=1)    ,INTENT(IN)               :: HDIR     

STOP 'NOT IMPLMENTED'

END SUBROUTINE READ_COVER 

SUBROUTINE OPEN_AUX_IO_SURF(SELF,HFILE,HFILETYPE,HMASK)

CLASS (SURFEX_HOST_T) :: SELF
CHARACTER(LEN=28)   ,INTENT(IN)               :: HFILE     
CHARACTER(LEN=6)    ,INTENT(IN)               :: HFILETYPE 
CHARACTER(LEN=6)    ,INTENT(IN)               :: HMASK

STOP 'NOT IMPLMENTED'

END SUBROUTINE OPEN_AUX_IO_SURF

SUBROUTINE CLOSE_AUX_IO_SURF(SELF,HFILE,HFILETYPE)

CLASS (SURFEX_HOST_T) :: SELF
CHARACTER(LEN=28)   ,INTENT(IN)               :: HFILE     
CHARACTER(LEN=6)    ,INTENT(IN)               :: HFILETYPE 

STOP 'NOT IMPLMENTED'

END SUBROUTINE CLOSE_AUX_IO_SURF

SUBROUTINE OPEN_WRITE_COVER_TEX (SELF,KTEX)

CLASS (SURFEX_HOST_T) :: SELF
INTEGER             ,INTENT(OUT)              :: KTEX 

STOP 'NOT IMPLMENTED'

END SUBROUTINE OPEN_WRITE_COVER_TEX

SUBROUTINE CLOSE_WRITE_COVER_TEX(SELF,KTEX)

CLASS (SURFEX_HOST_T) :: SELF
INTEGER             ,INTENT(IN)               :: KTEX 

STOP 'NOT IMPLMENTED'

END SUBROUTINE CLOSE_WRITE_COVER_TEX

SUBROUTINE GET_LUOUT(SELF,HPROGRAM,KLUOUT)

CLASS (SURFEX_HOST_T) :: SELF
CHARACTER(LEN=6)    ,INTENT(IN)               :: HPROGRAM 
INTEGER             ,INTENT(OUT)              :: KLUOUT   

STOP 'NOT IMPLMENTED'

END SUBROUTINE GET_LUOUT

SUBROUTINE OI_HOR_EXTRAPOL_SURF(SELF,NDIM,PLAT_IN,PLON_IN,PFIELD_IN, &
                                   PLAT,PLON,PFIELD,OINTERP,PZS,NDIM2)  

CLASS (SURFEX_HOST_T) :: SELF
INTEGER             ,INTENT(IN)               :: NDIM            ! dimension of arrays
REAL                ,INTENT(IN)               :: PLAT_IN(NDIM)   ! input lat. of each grid mesh.
REAL                ,INTENT(IN)               :: PLON_IN(NDIM)   ! input lon. of each grid mesh.
REAL                ,INTENT(IN)               :: PFIELD_IN(NDIM) ! input field on grid mesh
REAL                ,INTENT(IN)               :: PLAT(NDIM)      ! latitude of each grid mesh.
REAL                ,INTENT(IN)               :: PLON(NDIM)      ! longitude of each grid mesh.
REAL                ,INTENT(INOUT)            :: PFIELD(NDIM)    ! field on grid mesh
LOGICAL             ,INTENT(IN)               :: OINTERP(NDIM)   ! .true. where physical value is needed
REAL                ,INTENT(IN)    ,OPTIONAL  :: PZS(NDIM)       ! surface height
INTEGER             ,INTENT(IN)    ,OPTIONAL  :: NDIM2           ! Optional subdomain to search in

STOP 'NOT IMPLMENTED'

END SUBROUTINE OI_HOR_EXTRAPOL_SURF

SUBROUTINE GET_BUFC0(SELF,HNAME,HFIELD,KLEN,KRET)

CLASS (SURFEX_HOST_T) :: SELF
INTEGER             ,INTENT(IN)               :: KLEN      ! length of HFIELD
CHARACTER(LEN=6)    ,INTENT(IN)               :: HNAME     ! name of field
CHARACTER(LEN=KLEN) ,INTENT(OUT)              :: HFIELD    ! data
INTEGER             ,INTENT(OUT)              :: KRET      ! error code

STOP 'NOT IMPLMENTED'

END SUBROUTINE GET_BUFC0

SUBROUTINE GET_BUFN0(SELF,HNAME,KFIELD,KRET)

CLASS (SURFEX_HOST_T) :: SELF
CHARACTER(LEN=6)    ,INTENT(IN)               :: HNAME     ! name of field
INTEGER             ,INTENT(OUT)              :: KFIELD    ! data
INTEGER             ,INTENT(OUT)              :: KRET      !  error code

STOP 'NOT IMPLMENTED'

END SUBROUTINE GET_BUFN0

SUBROUTINE GET_BUFN1(SELF,HNAME,KDIM,KFIELD,KRET)

CLASS (SURFEX_HOST_T) :: SELF
CHARACTER(LEN=6)    ,INTENT(IN)               :: HNAME        ! name of field
INTEGER             ,INTENT(IN)               :: KDIM         ! number of points
INTEGER             ,INTENT(OUT)              :: KFIELD(KDIM) ! array containing the data field
INTEGER             ,INTENT(OUT)              :: KRET         ! error code

STOP 'NOT IMPLMENTED'

END SUBROUTINE GET_BUFN1

SUBROUTINE GET_BUFX0(SELF,HNAME,PFIELD,KRET)

CLASS (SURFEX_HOST_T) :: SELF
CHARACTER(LEN=6)    ,INTENT(IN)               :: HNAME     ! name of field
REAL                ,INTENT(OUT)              :: PFIELD    ! data
INTEGER             ,INTENT(OUT)              :: KRET      ! error code

STOP 'NOT IMPLMENTED'

END SUBROUTINE GET_BUFX0

SUBROUTINE GET_BUFX1(SELF,HNAME,KDIM,PFIELD,KRET)

CLASS (SURFEX_HOST_T) :: SELF
CHARACTER(LEN=*)    ,INTENT(IN)               :: HNAME           ! name of field
INTEGER             ,INTENT(IN)               :: KDIM            ! number of points
REAL                ,INTENT(OUT)              :: PFIELD(KDIM)    ! array containing the data field
INTEGER             ,INTENT(OUT)              :: KRET            ! error code

STOP 'NOT IMPLMENTED'

END SUBROUTINE GET_BUFX1

SUBROUTINE SET_GRESET (SELF, LDRESETMINMAX, ORESET)

CLASS (SURFEX_HOST_T) :: SELF
LOGICAL             ,INTENT(IN)               :: LDRESETMINMAX
LOGICAL             ,INTENT(OUT)              :: ORESET

STOP 'NOT IMPLMENTED'

END SUBROUTINE SET_GRESET

SUBROUTINE INIT_IO_SURF(SELF,HPROGRAM,HMASK,HACTION)

CLASS (SURFEX_HOST_T) :: SELF
CHARACTER(LEN=6)    ,INTENT(IN)               :: HPROGRAM ! main program
CHARACTER(LEN=6)    ,INTENT(IN)               :: HMASK
CHARACTER(LEN=5)    ,INTENT(IN)               :: HACTION  ! action performed ('READ ','WRITE')

STOP 'NOT IMPLMENTED'

END SUBROUTINE INIT_IO_SURF

SUBROUTINE END_IO_SURF(SELF,HPROGRAM)

CLASS (SURFEX_HOST_T) :: SELF
CHARACTER(LEN=6)    ,INTENT(IN)               :: HPROGRAM ! main program

STOP 'NOT IMPLMENTED'

END SUBROUTINE END_IO_SURF

SUBROUTINE ABORT (SELF, CDMESS)

CLASS (SURFEX_HOST_T) :: SELF
CHARACTER(LEN=*)    ,INTENT(IN)               :: CDMESS

STOP 'NOT IMPLMENTED'

END SUBROUTINE ABORT

SUBROUTINE OPEN_NAMELIST(SELF,HPROGRAM,KLUNAM,HFILE)

CLASS (SURFEX_HOST_T) :: SELF
CHARACTER(LEN=6)    ,INTENT(IN)               :: HPROGRAM ! main program
INTEGER             ,INTENT(OUT)              :: KLUNAM   ! logical unit of namelist
CHARACTER(LEN=28)   ,INTENT(IN)               :: HFILE    ! ASCII file to open

STOP 'NOT IMPLMENTED'

END SUBROUTINE OPEN_NAMELIST

SUBROUTINE CLOSE_NAMELIST(SELF,HPROGRAM,KLUNAM)

CLASS (SURFEX_HOST_T) :: SELF
CHARACTER(LEN=6)    ,INTENT(IN)               :: HPROGRAM ! main program
INTEGER             ,INTENT(IN)               :: KLUNAM   ! logical unit of namelist

STOP 'NOT IMPLMENTED'

END SUBROUTINE CLOSE_NAMELIST

SUBROUTINE DETECT_FIELD (SELF,HPROGRAM,KI,KJ,PFIELD,OITSHERE)

CLASS (SURFEX_HOST_T) :: SELF
CHARACTER(LEN=6)    ,INTENT(IN)               :: HPROGRAM          ! program
INTEGER             ,INTENT(IN)               :: KI                ! 1st size of array
INTEGER             ,INTENT(IN)               :: KJ                ! 2nd size of array
REAL                ,INTENT(IN)               :: PFIELD(KI,KJ)     ! array containing the data field
LOGICAL             ,INTENT(OUT)              :: OITSHERE          ! T --> PFIELD is non zero somewhere

STOP 'NOT IMPLMENTED'

END SUBROUTINE DETECT_FIELD

SUBROUTINE GET_DESFM (SELF,HACTION,KLUDES)

CLASS (SURFEX_HOST_T) :: SELF
CHARACTER(LEN=5)    ,INTENT(IN)               :: HACTION ! 'READ ', 'WRITE'
INTEGER             ,INTENT(OUT)              :: KLUDES  ! logical unit of .des file

STOP 'NOT IMPLMENTED'

END SUBROUTINE GET_DESFM

SUBROUTINE SET_BLOCK (SELF, KBLOCK)

CLASS (SURFEX_HOST_T) :: SELF
INTEGER             ,INTENT(IN)               :: KBLOCK

STOP 'NOT IMPLMENTED'

END SUBROUTINE SET_BLOCK

LOGICAL FUNCTION HAS_FIELD (SELF, CDNAME)

CLASS (SURFEX_HOST_T) :: SELF
CHARACTER(LEN=*)    ,INTENT(IN)               :: CDNAME

STOP 'NOT IMPLMENTED'

END FUNCTION HAS_FIELD

LOGICAL FUNCTION RECORD_OUTPUT (SELF)

CLASS (SURFEX_HOST_T) :: SELF

STOP 'NOT IMPLMENTED'

END FUNCTION RECORD_OUTPUT

SUBROUTINE ALLOCATE_OUTPUT (SELF)

CLASS (SURFEX_HOST_T) :: SELF

STOP 'NOT IMPLMENTED'

END SUBROUTINE ALLOCATE_OUTPUT

SUBROUTINE GET_SIZE_FULL(SELF,HPROGRAM,KDIM_FULL,KSIZE_FULL)

CLASS (SURFEX_HOST_T) :: SELF
CHARACTER(LEN=6)    ,INTENT(IN)               :: HPROGRAM   ! main program
INTEGER             ,INTENT(IN)               :: KDIM_FULL  ! total number of points
INTEGER             ,INTENT(OUT)              :: KSIZE_FULL ! total number of points on this proc

STOP 'NOT IMPLMENTED'

END SUBROUTINE GET_SIZE_FULL

SUBROUTINE READ_SURF_LAYER (SELF, HPROGRAM, KNPATCH, ODIM, HRECFM, PWORK, HDIR, KPATCH, KRESP)

CLASS (SURFEX_HOST_T) :: SELF
CHARACTER(LEN=*)    ,INTENT(IN)               :: HPROGRAM
INTEGER             ,INTENT(IN)               :: KNPATCH
LOGICAL             ,INTENT(IN)               :: ODIM
CHARACTER(LEN=*)    ,INTENT(IN)               :: HRECFM
REAL                ,INTENT(INOUT)            :: PWORK(:,:)
CHARACTER(LEN=*)    ,INTENT(IN)    ,OPTIONAL  :: HDIR
INTEGER             ,INTENT(IN)    ,OPTIONAL  :: KPATCH
INTEGER             ,INTENT(OUT)   ,OPTIONAL  :: KRESP

STOP 'NOT IMPLMENTED'

END SUBROUTINE READ_SURF_LAYER

INTEGER FUNCTION SUM_ON_ALL_PROCS (SELF,HGRID,OIN,YNAME)

CLASS (SURFEX_HOST_T) :: SELF
CHARACTER(LEN=10)   ,INTENT(IN)               :: HGRID    ! grid type
LOGICAL             ,INTENT(IN)               :: OIN(:)
CHARACTER(LEN=3)    ,INTENT(IN)    ,OPTIONAL  :: YNAME

STOP 'NOT IMPLMENTED'

END FUNCTION SUM_ON_ALL_PROCS

SUBROUTINE ASSIM_DIST_FIELD (SELF,PFIELDG,PFIELDL)

CLASS (SURFEX_HOST_T) :: SELF
REAL                ,INTENT(IN)               :: PFIELDG(:)
REAL                ,INTENT(OUT)              :: PFIELDL(:)

STOP 'NOT IMPLMENTED'

END SUBROUTINE ASSIM_DIST_FIELD

INTEGER FUNCTION ASSIM_GET_SIZE_GLOBAL (SELF, PFIELD_IN)

CLASS (SURFEX_HOST_T) :: SELF
REAL                ,INTENT(IN)               :: PFIELD_IN(:)

STOP 'NOT IMPLMENTED'

END FUNCTION ASSIM_GET_SIZE_GLOBAL

SUBROUTINE ASSIM_GATHER_FIELD (SELF, PFIELDL, PFIELDG)

CLASS (SURFEX_HOST_T) :: SELF
REAL                ,INTENT(IN)               :: PFIELDL(:)
REAL                ,INTENT(INOUT)            :: PFIELDG(:)

STOP 'NOT IMPLMENTED'

END SUBROUTINE ASSIM_GATHER_FIELD

SUBROUTINE PROPAGATE_ICE (SELF, KSIZE, KNUM_LAYERS, PLON, PLAT, PSIC_OLD, PSIC_NEW, &
                           &  PTICE, PZICE, PSDF, OMISSING_OLD_ICE, PICE_EDGE_THK)

CLASS (SURFEX_HOST_T) :: SELF
INTEGER             ,INTENT(IN)               :: KSIZE
INTEGER             ,INTENT(IN)               :: KNUM_LAYERS
REAL                ,INTENT(IN)               :: PLON(KSIZE)             
REAL                ,INTENT(IN)               :: PLAT(KSIZE)             
REAL                ,INTENT(IN)               :: PSIC_OLD(KSIZE)             
REAL                ,INTENT(IN)               :: PSIC_NEW(KSIZE)             
REAL                ,INTENT(INOUT)            :: PTICE(KSIZE,KNUM_LAYERS) 
REAL                ,INTENT(INOUT)            :: PZICE(KSIZE)             
REAL                ,INTENT(OUT)              :: PSDF(KSIZE)             
LOGICAL             ,INTENT(OUT)              :: OMISSING_OLD_ICE
REAL                ,INTENT(OUT)              :: PICE_EDGE_THK

STOP 'NOT IMPLMENTED'

END SUBROUTINE PROPAGATE_ICE

INTEGER FUNCTION GET_NUMBER_OF_BLOCKS (SELF)

CLASS (SURFEX_HOST_T) :: SELF

STOP 'NOT IMPLMENTED'

END FUNCTION GET_NUMBER_OF_BLOCKS

END MODULE MODD_SURFEX_HOST

