!     ############################
      MODULE MODD_DIAG_MISC_TEB_n
!     ############################
!
!!****  *MODD_DIAG_MISC_TEB - declaration of packed surface parameters for TEB scheme
!!
!!    PURPOSE
!!    -------
!
!!
!!**  IMPLICIT ARGUMENTS
!!    ------------------
!!      None 
!!
!!    REFERENCE
!!    ---------
!!
!!    AUTHOR
!!    ------
!!	P. Le Moigne   *Meteo France*
!!
!!    MODIFICATIONS
!!    -------------
!!      Original       07/10/04
!
!
!*       0.   DECLARATIONS
!             ------------
!
!
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE

TYPE DIAG_MISC_TEB_t
!------------------------------------------------------------------------------
!
  LOGICAL :: LSURF_MISC_BUDGET   ! flag for miscellaneous terms of teb scheme
  LOGICAL :: LSURF_BUDGETC       ! flag for surface cumulated energy budget
  LOGICAL :: LRESET_BUDGETC      ! flag for surface cumulated energy budget
  LOGICAL :: LSURF_EVAP_BUDGET   ! flag for all terms of evaporation
  LOGICAL :: LSURF_DIAG_ALBEDO   ! flag to write out diagnostic albedo  
!
!* miscellaneous variables
!
  REAL, POINTER, DIMENSION(:)   :: XZ0_TOWN  ! town roughness length
  REAL, POINTER, DIMENSION(:)   :: XQF_BLD   ! domestic heating
  REAL, POINTER, DIMENSION(:)   :: XQF_BLDWFR! domestic heating
  REAL, POINTER, DIMENSION(:)   :: XFLX_BLD ! heat flux from bld
  REAL, POINTER, DIMENSION(:)   :: XTI_BLD_EQ ! internal temperature
                                              ! without heating
  REAL, POINTER, DIMENSION(:)   :: XTI_BLDWFR ! internal temperature
                                              ! without heating
  REAL, POINTER, DIMENSION(:)   :: XQF_TOWN  ! total anthropogenic heat
  REAL, POINTER, DIMENSION(:)   :: XDQS_TOWN ! storage inside building
!
  REAL, POINTER, DIMENSION(:)   :: XH_WALL     ! wall sensible heat flux          (W/m2)
  REAL, POINTER, DIMENSION(:)   :: XH_ROOF     ! roof sensible heat flux          (W/m2)
  REAL, POINTER, DIMENSION(:)   :: XH_ROAD     ! road sensible heat flux          (W/m2)
  REAL, POINTER, DIMENSION(:)   :: XH_GARDEN   ! green area sensible heat flux    (W/m2)
  REAL, POINTER, DIMENSION(:)   :: XH_BLT      ! built surf sensible heat flux    (W/m2)
  REAL, POINTER, DIMENSION(:)   :: XRN_WALL    ! net radiation at wall            (W/m2)
  REAL, POINTER, DIMENSION(:)   :: XRN_ROOF    ! net radiation at roof            (W/m2)
  REAL, POINTER, DIMENSION(:)   :: XRN_ROAD    ! net radiation at road            (W/m2)
  REAL, POINTER, DIMENSION(:)   :: XRN_GARDEN  ! net radiation at green areas     (W/m2)
  REAL, POINTER, DIMENSION(:)   :: XRN_BLT     ! net radiation at built surf      (W/m2)
  REAL, POINTER, DIMENSION(:)   :: XGFLUX_WALL ! net wall conduction flux      (W/m2)
  REAL, POINTER, DIMENSION(:)   :: XGFLUX_ROOF ! net roof conduction flux      (W/m2)                                         
  REAL, POINTER, DIMENSION(:)   :: XGFLUX_ROAD ! net road conduction flux      (W/m2)
  REAL, POINTER, DIMENSION(:)   :: XGFLUX_GARDEN!net green area conduction flux(W/m2)
  REAL, POINTER, DIMENSION(:)   :: XGFLUX_BLT  ! net built surf conduction flux(W/m2)
  REAL, POINTER, DIMENSION(:)   :: XLE_ROOF    ! roof latent heat flux            (W/m2)
  REAL, POINTER, DIMENSION(:)   :: XLE_ROAD    ! road latent heat flux            (W/m2)
  REAL, POINTER, DIMENSION(:)   :: XLE_GARDEN  ! green area latent heat flux      (W/m2)
  REAL, POINTER, DIMENSION(:)   :: XLE_BLT     ! built surf latent heat flux      (W/m2)
!
  REAL, POINTER, DIMENSION(:)   :: XRUNOFF  ! water runoff for town         (kg/m2/s)
  REAL, POINTER, DIMENSION(:)   :: XRUNOFFC ! water cumulated runoff for town (kg/m2)
!
  REAL, POINTER, DIMENSION(:)   :: XABS_SW_ROOF      ! Downward shortwave radiation over roofs
  REAL, POINTER, DIMENSION(:)   :: XABS_SW_SNOW_ROOF ! Downward longwave radiation over roofs
  REAL, POINTER, DIMENSION(:)   :: XABS_LW_ROOF      ! Upward shortwave radiation over roofs
  REAL, POINTER, DIMENSION(:)   :: XABS_LW_SNOW_ROOF ! Upward longwave radiation over roofs
  REAL, POINTER, DIMENSION(:)   :: XABS_SW_ROAD      ! Downward shortwave radiation over roads
  REAL, POINTER, DIMENSION(:)   :: XABS_SW_SNOW_ROAD ! Downward longwave radiation over roads
  REAL, POINTER, DIMENSION(:)   :: XABS_LW_ROAD      ! Upward shortwave radiation over roads
  REAL, POINTER, DIMENSION(:)   :: XABS_LW_SNOW_ROAD ! Upward longwave radiation over roads
  REAL, POINTER, DIMENSION(:)   :: XABS_SW_WALL      ! Downward shortwave radiation over walls
  REAL, POINTER, DIMENSION(:)   :: XABS_LW_WALL      ! Upward shortwave radiation over walls
  REAL, POINTER, DIMENSION(:)   :: XABS_SW_GARDEN    ! Downward shortwave radiation over green areas
  REAL, POINTER, DIMENSION(:)   :: XABS_LW_GARDEN    ! Upward shortwave radiation over green areas
!
!------------------------------------------------------------------------------
!

END TYPE DIAG_MISC_TEB_t

TYPE(DIAG_MISC_TEB_t), ALLOCATABLE, TARGET, SAVE :: DIAG_MISC_TEB_MODEL(:)

LOGICAL, POINTER :: LSURF_MISC_BUDGET=>NULL()
!$OMP THREADPRIVATE(LSURF_MISC_BUDGET)
LOGICAL, POINTER :: LSURF_BUDGETC=>NULL()
!$OMP THREADPRIVATE(LSURF_BUDGETC)
LOGICAL, POINTER :: LRESET_BUDGETC=>NULL()
!$OMP THREADPRIVATE(LRESET_BUDGETC)
LOGICAL, POINTER :: LSURF_EVAP_BUDGET=>NULL()
!$OMP THREADPRIVATE(LSURF_EVAP_BUDGET)
LOGICAL, POINTER :: LSURF_DIAG_ALBEDO=>NULL()
!$OMP THREADPRIVATE(LSURF_DIAG_ALBEDO)
REAL, POINTER, DIMENSION(:)   :: XZ0_TOWN=>NULL()
!$OMP THREADPRIVATE(XZ0_TOWN)
REAL, POINTER, DIMENSION(:)   :: XQF_BLD=>NULL()
!$OMP THREADPRIVATE(XQF_BLD)
REAL, POINTER, DIMENSION(:)   :: XQF_BLDWFR=>NULL()
!$OMP THREADPRIVATE(XQF_BLDWFR)
REAL, POINTER, DIMENSION(:)   :: XFLX_BLD=>NULL()
!$OMP THREADPRIVATE(XFLX_BLD)
REAL, POINTER, DIMENSION(:)   :: XTI_BLD_EQ=>NULL()
!$OMP THREADPRIVATE(XTI_BLD_EQ)
REAL, POINTER, DIMENSION(:)   :: XTI_BLDWFR=>NULL()
!$OMP THREADPRIVATE(XTI_BLDWFR)
REAL, POINTER, DIMENSION(:)   :: XQF_TOWN=>NULL()
!$OMP THREADPRIVATE(XQF_TOWN)
REAL, POINTER, DIMENSION(:)   :: XDQS_TOWN=>NULL()
!$OMP THREADPRIVATE(XDQS_TOWN)
REAL, POINTER, DIMENSION(:)   :: XH_WALL=>NULL()
!$OMP THREADPRIVATE(XH_WALL)
REAL, POINTER, DIMENSION(:)   :: XH_ROOF=>NULL()
!$OMP THREADPRIVATE(XH_ROOF)
REAL, POINTER, DIMENSION(:)   :: XH_ROAD=>NULL()
!$OMP THREADPRIVATE(XH_ROAD)
REAL, POINTER, DIMENSION(:)   :: XRN_WALL=>NULL()
!$OMP THREADPRIVATE(XRN_WALL)
REAL, POINTER, DIMENSION(:)   :: XRN_ROOF=>NULL()
!$OMP THREADPRIVATE(XRN_ROOF)
REAL, POINTER, DIMENSION(:)   :: XRN_ROAD=>NULL()
!$OMP THREADPRIVATE(XRN_ROAD)
REAL, POINTER, DIMENSION(:)   :: XRN_GARDEN=>NULL()
!$OMP THREADPRIVATE(XRN_GARDEN)
REAL, POINTER, DIMENSION(:)   :: XRN_BLT=>NULL()
!$OMP THREADPRIVATE(XRN_BLT)
REAL, POINTER, DIMENSION(:)   :: XH_GARDEN=>NULL()
!$OMP THREADPRIVATE(XH_GARDEN)
REAL, POINTER, DIMENSION(:)   :: XH_BLT=>NULL()
!$OMP THREADPRIVATE(XH_BLT)
REAL, POINTER, DIMENSION(:)   :: XGFLUX_WALL=>NULL()
!$OMP THREADPRIVATE(XGFLUX_WALL)
REAL, POINTER, DIMENSION(:)   :: XGFLUX_ROOF=>NULL()
!$OMP THREADPRIVATE(XGFLUX_ROOF)
REAL, POINTER, DIMENSION(:)   :: XGFLUX_ROAD=>NULL()
!$OMP THREADPRIVATE(XGFLUX_ROAD)
REAL, POINTER, DIMENSION(:)   :: XGFLUX_GARDEN=>NULL()
!$OMP THREADPRIVATE(XGFLUX_GARDEN)
REAL, POINTER, DIMENSION(:)   :: XGFLUX_BLT=>NULL()
!$OMP THREADPRIVATE(XGFLUX_BLT)
REAL, POINTER, DIMENSION(:)   :: XLE_ROOF=>NULL()
!$OMP THREADPRIVATE(XLE_ROOF)
REAL, POINTER, DIMENSION(:)   :: XLE_ROAD=>NULL()
!$OMP THREADPRIVATE(XLE_ROAD)
REAL, POINTER, DIMENSION(:)   :: XLE_GARDEN=>NULL()
!$OMP THREADPRIVATE(XLE_GARDEN)
REAL, POINTER, DIMENSION(:)   :: XLE_BLT=>NULL()
!$OMP THREADPRIVATE(XLE_BLT)
REAL, POINTER, DIMENSION(:)   :: XRUNOFF=>NULL()
!$OMP THREADPRIVATE(XRUNOFF)
REAL, POINTER, DIMENSION(:)   :: XRUNOFFC=>NULL()
!$OMP THREADPRIVATE(XRUNOFFC)
!
REAL, POINTER, DIMENSION(:)   :: XABS_SW_ROOF=>NULL()
!$OMP THREADPRIVATE(XABS_SW_ROOF)
REAL, POINTER, DIMENSION(:)   :: XABS_SW_SNOW_ROOF=>NULL()
!$OMP THREADPRIVATE(XABS_SW_SNOW_ROOF)
REAL, POINTER, DIMENSION(:)   :: XABS_LW_ROOF=>NULL()
!$OMP THREADPRIVATE(XABS_LW_ROOF)
REAL, POINTER, DIMENSION(:)   :: XABS_LW_SNOW_ROOF=>NULL()
!$OMP THREADPRIVATE(XABS_LW_SNOW_ROOF)
REAL, POINTER, DIMENSION(:)   :: XABS_SW_ROAD=>NULL()
!$OMP THREADPRIVATE(XABS_SW_ROAD)
REAL, POINTER, DIMENSION(:)   :: XABS_SW_SNOW_ROAD=>NULL()
!$OMP THREADPRIVATE(XABS_SW_SNOW_ROAD)
REAL, POINTER, DIMENSION(:)   :: XABS_LW_ROAD=>NULL()
!$OMP THREADPRIVATE(XABS_LW_ROAD)
REAL, POINTER, DIMENSION(:)   :: XABS_LW_SNOW_ROAD=>NULL()
!$OMP THREADPRIVATE(XABS_LW_SNOW_ROAD)
REAL, POINTER, DIMENSION(:)   :: XABS_SW_WALL=>NULL()
!$OMP THREADPRIVATE(XABS_SW_WALL)
REAL, POINTER, DIMENSION(:)   :: XABS_LW_WALL=>NULL()
!$OMP THREADPRIVATE(XABS_LW_WALL)
REAL, POINTER, DIMENSION(:)   :: XABS_SW_GARDEN=>NULL()
!$OMP THREADPRIVATE(XABS_SW_GARDEN)
REAL, POINTER, DIMENSION(:)   :: XABS_LW_GARDEN=>NULL()
!$OMP THREADPRIVATE(XABS_LW_GARDEN)

CONTAINS

SUBROUTINE DIAG_MISC_TEB_GOTO_MODEL(KFROM, KTO, LKFROM)
LOGICAL, INTENT(IN) :: LKFROM
INTEGER, INTENT(IN) :: KFROM, KTO
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
! Save current state for allocated arrays
IF (LKFROM) THEN
DIAG_MISC_TEB_MODEL(KFROM)%XZ0_TOWN=>XZ0_TOWN
DIAG_MISC_TEB_MODEL(KFROM)%XQF_BLD=>XQF_BLD
DIAG_MISC_TEB_MODEL(KFROM)%XQF_BLDWFR=>XQF_BLDWFR
DIAG_MISC_TEB_MODEL(KFROM)%XFLX_BLD=>XFLX_BLD
DIAG_MISC_TEB_MODEL(KFROM)%XTI_BLD_EQ=>XTI_BLD_EQ
DIAG_MISC_TEB_MODEL(KFROM)%XTI_BLDWFR=>XTI_BLDWFR
DIAG_MISC_TEB_MODEL(KFROM)%XQF_TOWN=>XQF_TOWN
DIAG_MISC_TEB_MODEL(KFROM)%XDQS_TOWN=>XDQS_TOWN
DIAG_MISC_TEB_MODEL(KFROM)%XH_WALL=>XH_WALL
DIAG_MISC_TEB_MODEL(KFROM)%XH_ROOF=>XH_ROOF
DIAG_MISC_TEB_MODEL(KFROM)%XH_ROAD=>XH_ROAD
DIAG_MISC_TEB_MODEL(KFROM)%XH_GARDEN=>XH_GARDEN
DIAG_MISC_TEB_MODEL(KFROM)%XH_BLT=>XH_BLT
DIAG_MISC_TEB_MODEL(KFROM)%XRN_WALL=>XRN_WALL
DIAG_MISC_TEB_MODEL(KFROM)%XRN_ROOF=>XRN_ROOF
DIAG_MISC_TEB_MODEL(KFROM)%XRN_ROAD=>XRN_ROAD
DIAG_MISC_TEB_MODEL(KFROM)%XRN_GARDEN=>XRN_GARDEN
DIAG_MISC_TEB_MODEL(KFROM)%XRN_BLT=>XRN_BLT
DIAG_MISC_TEB_MODEL(KFROM)%XGFLUX_WALL=>XGFLUX_WALL
DIAG_MISC_TEB_MODEL(KFROM)%XGFLUX_ROOF=>XGFLUX_ROOF
DIAG_MISC_TEB_MODEL(KFROM)%XGFLUX_ROAD=>XGFLUX_ROAD
DIAG_MISC_TEB_MODEL(KFROM)%XGFLUX_GARDEN=>XGFLUX_GARDEN
DIAG_MISC_TEB_MODEL(KFROM)%XGFLUX_BLT=>XGFLUX_BLT
DIAG_MISC_TEB_MODEL(KFROM)%XLE_ROOF=>XLE_ROOF
DIAG_MISC_TEB_MODEL(KFROM)%XLE_ROAD=>XLE_ROAD
DIAG_MISC_TEB_MODEL(KFROM)%XLE_GARDEN=>XLE_GARDEN
DIAG_MISC_TEB_MODEL(KFROM)%XLE_BLT=>XLE_BLT
DIAG_MISC_TEB_MODEL(KFROM)%XRUNOFF=>XRUNOFF
DIAG_MISC_TEB_MODEL(KFROM)%XRUNOFFC=>XRUNOFFC
!
DIAG_MISC_TEB_MODEL(KFROM)%XABS_SW_ROOF=>XABS_SW_ROOF
DIAG_MISC_TEB_MODEL(KFROM)%XABS_SW_SNOW_ROOF=>XABS_SW_SNOW_ROOF
DIAG_MISC_TEB_MODEL(KFROM)%XABS_LW_ROOF=>XABS_LW_ROOF
DIAG_MISC_TEB_MODEL(KFROM)%XABS_LW_SNOW_ROOF=>XABS_LW_SNOW_ROOF
DIAG_MISC_TEB_MODEL(KFROM)%XABS_SW_ROAD=>XABS_SW_ROAD
DIAG_MISC_TEB_MODEL(KFROM)%XABS_SW_SNOW_ROAD=>XABS_SW_SNOW_ROAD
DIAG_MISC_TEB_MODEL(KFROM)%XABS_LW_ROAD=>XABS_LW_ROAD
DIAG_MISC_TEB_MODEL(KFROM)%XABS_LW_SNOW_ROAD=>XABS_LW_SNOW_ROAD
DIAG_MISC_TEB_MODEL(KFROM)%XABS_SW_WALL=>XABS_SW_WALL
DIAG_MISC_TEB_MODEL(KFROM)%XABS_LW_WALL=>XABS_LW_WALL
DIAG_MISC_TEB_MODEL(KFROM)%XABS_SW_GARDEN=>XABS_SW_GARDEN
DIAG_MISC_TEB_MODEL(KFROM)%XABS_LW_GARDEN=>XABS_LW_GARDEN
ENDIF
!
! Current model is set to model KTO
IF (LHOOK) CALL DR_HOOK('MODD_DIAG_MISC_TEB_N:DIAG_MISC_TEB_GOTO_MODEL',0,ZHOOK_HANDLE)
LSURF_MISC_BUDGET=>DIAG_MISC_TEB_MODEL(KTO)%LSURF_MISC_BUDGET
LSURF_BUDGETC=>DIAG_MISC_TEB_MODEL(KTO)%LSURF_BUDGETC
LRESET_BUDGETC=>DIAG_MISC_TEB_MODEL(KTO)%LRESET_BUDGETC
LSURF_EVAP_BUDGET=>DIAG_MISC_TEB_MODEL(KTO)%LSURF_EVAP_BUDGET
LSURF_DIAG_ALBEDO=>DIAG_MISC_TEB_MODEL(KTO)%LSURF_DIAG_ALBEDO
XZ0_TOWN=>DIAG_MISC_TEB_MODEL(KTO)%XZ0_TOWN
XQF_BLD=>DIAG_MISC_TEB_MODEL(KTO)%XQF_BLD
XQF_BLDWFR=>DIAG_MISC_TEB_MODEL(KTO)%XQF_BLDWFR
XFLX_BLD=>DIAG_MISC_TEB_MODEL(KTO)%XFLX_BLD
XTI_BLD_EQ=>DIAG_MISC_TEB_MODEL(KTO)%XTI_BLD_EQ
XTI_BLDWFR=>DIAG_MISC_TEB_MODEL(KTO)%XTI_BLDWFR
XQF_TOWN=>DIAG_MISC_TEB_MODEL(KTO)%XQF_TOWN
XDQS_TOWN=>DIAG_MISC_TEB_MODEL(KTO)%XDQS_TOWN
XH_WALL=>DIAG_MISC_TEB_MODEL(KTO)%XH_WALL
XH_ROOF=>DIAG_MISC_TEB_MODEL(KTO)%XH_ROOF
XH_ROAD=>DIAG_MISC_TEB_MODEL(KTO)%XH_ROAD
XH_GARDEN=>DIAG_MISC_TEB_MODEL(KTO)%XH_GARDEN
XH_BLT=>DIAG_MISC_TEB_MODEL(KTO)%XH_BLT
XRN_WALL=>DIAG_MISC_TEB_MODEL(KTO)%XRN_WALL
XRN_ROOF=>DIAG_MISC_TEB_MODEL(KTO)%XRN_ROOF
XRN_ROAD=>DIAG_MISC_TEB_MODEL(KTO)%XRN_ROAD
XRN_GARDEN=>DIAG_MISC_TEB_MODEL(KTO)%XRN_GARDEN
XRN_BLT=>DIAG_MISC_TEB_MODEL(KTO)%XRN_BLT
XGFLUX_WALL=>DIAG_MISC_TEB_MODEL(KTO)%XGFLUX_WALL
XGFLUX_ROOF=>DIAG_MISC_TEB_MODEL(KTO)%XGFLUX_ROOF
XGFLUX_ROAD=>DIAG_MISC_TEB_MODEL(KTO)%XGFLUX_ROAD
XGFLUX_GARDEN=>DIAG_MISC_TEB_MODEL(KTO)%XGFLUX_GARDEN
XGFLUX_BLT=>DIAG_MISC_TEB_MODEL(KTO)%XGFLUX_BLT
XLE_ROOF=>DIAG_MISC_TEB_MODEL(KTO)%XLE_ROOF
XLE_ROAD=>DIAG_MISC_TEB_MODEL(KTO)%XLE_ROAD
XLE_GARDEN=>DIAG_MISC_TEB_MODEL(KTO)%XLE_GARDEN
XLE_BLT=>DIAG_MISC_TEB_MODEL(KTO)%XLE_BLT
XRUNOFF=>DIAG_MISC_TEB_MODEL(KTO)%XRUNOFF
XRUNOFFC=>DIAG_MISC_TEB_MODEL(KTO)%XRUNOFFC
!
XABS_SW_ROOF=>DIAG_MISC_TEB_MODEL(KTO)%XABS_SW_ROOF
XABS_SW_SNOW_ROOF=>DIAG_MISC_TEB_MODEL(KTO)%XABS_SW_SNOW_ROOF
XABS_LW_ROOF=>DIAG_MISC_TEB_MODEL(KTO)%XABS_LW_ROOF
XABS_LW_SNOW_ROOF=>DIAG_MISC_TEB_MODEL(KTO)%XABS_LW_SNOW_ROOF
XABS_SW_ROAD=>DIAG_MISC_TEB_MODEL(KTO)%XABS_SW_ROAD
XABS_SW_SNOW_ROAD=>DIAG_MISC_TEB_MODEL(KTO)%XABS_SW_SNOW_ROAD
XABS_LW_ROAD=>DIAG_MISC_TEB_MODEL(KTO)%XABS_LW_ROAD
XABS_LW_SNOW_ROAD=>DIAG_MISC_TEB_MODEL(KTO)%XABS_LW_SNOW_ROAD
XABS_SW_WALL=>DIAG_MISC_TEB_MODEL(KTO)%XABS_SW_WALL
XABS_LW_WALL=>DIAG_MISC_TEB_MODEL(KTO)%XABS_LW_WALL
XABS_SW_GARDEN=>DIAG_MISC_TEB_MODEL(KTO)%XABS_SW_GARDEN
XABS_LW_GARDEN=>DIAG_MISC_TEB_MODEL(KTO)%XABS_LW_GARDEN
IF (LHOOK) CALL DR_HOOK('MODD_DIAG_MISC_TEB_N:DIAG_MISC_TEB_GOTO_MODEL',1,ZHOOK_HANDLE)

END SUBROUTINE DIAG_MISC_TEB_GOTO_MODEL

SUBROUTINE DIAG_MISC_TEB_ALLOC(KMODEL)
INTEGER, INTENT(IN) :: KMODEL
INTEGER :: J
REAL(KIND=JPRB) :: ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK("MODD_DIAG_MISC_TEB_N:DIAG_MISC_TEB_ALLOC",0,ZHOOK_HANDLE)
ALLOCATE(DIAG_MISC_TEB_MODEL(KMODEL))
DO J=1,KMODEL
  NULLIFY(DIAG_MISC_TEB_MODEL(J)%XZ0_TOWN)
  NULLIFY(DIAG_MISC_TEB_MODEL(J)%XQF_BLD)
  NULLIFY(DIAG_MISC_TEB_MODEL(J)%XQF_BLDWFR)
  NULLIFY(DIAG_MISC_TEB_MODEL(J)%XFLX_BLD)
  NULLIFY(DIAG_MISC_TEB_MODEL(J)%XTI_BLD_EQ)
  NULLIFY(DIAG_MISC_TEB_MODEL(J)%XTI_BLDWFR)
  NULLIFY(DIAG_MISC_TEB_MODEL(J)%XQF_TOWN)
  NULLIFY(DIAG_MISC_TEB_MODEL(J)%XDQS_TOWN)
  NULLIFY(DIAG_MISC_TEB_MODEL(J)%XH_WALL)
  NULLIFY(DIAG_MISC_TEB_MODEL(J)%XH_ROOF)
  NULLIFY(DIAG_MISC_TEB_MODEL(J)%XH_ROAD)
  NULLIFY(DIAG_MISC_TEB_MODEL(J)%XH_GARDEN)
  NULLIFY(DIAG_MISC_TEB_MODEL(J)%XH_BLT)
  NULLIFY(DIAG_MISC_TEB_MODEL(J)%XRN_WALL)
  NULLIFY(DIAG_MISC_TEB_MODEL(J)%XRN_ROOF)
  NULLIFY(DIAG_MISC_TEB_MODEL(J)%XRN_ROAD)
  NULLIFY(DIAG_MISC_TEB_MODEL(J)%XRN_GARDEN)
  NULLIFY(DIAG_MISC_TEB_MODEL(J)%XRN_BLT)
  NULLIFY(DIAG_MISC_TEB_MODEL(J)%XGFLUX_WALL)
  NULLIFY(DIAG_MISC_TEB_MODEL(J)%XGFLUX_ROOF)
  NULLIFY(DIAG_MISC_TEB_MODEL(J)%XGFLUX_ROAD)
  NULLIFY(DIAG_MISC_TEB_MODEL(J)%XGFLUX_GARDEN)
  NULLIFY(DIAG_MISC_TEB_MODEL(J)%XGFLUX_BLT)
  NULLIFY(DIAG_MISC_TEB_MODEL(J)%XLE_ROOF)
  NULLIFY(DIAG_MISC_TEB_MODEL(J)%XLE_ROAD)
  NULLIFY(DIAG_MISC_TEB_MODEL(J)%XLE_GARDEN)
  NULLIFY(DIAG_MISC_TEB_MODEL(J)%XLE_BLT)
  NULLIFY(DIAG_MISC_TEB_MODEL(J)%XRUNOFF)
  NULLIFY(DIAG_MISC_TEB_MODEL(J)%XRUNOFFC)
  NULLIFY(DIAG_MISC_TEB_MODEL(J)%XABS_SW_ROOF)
  NULLIFY(DIAG_MISC_TEB_MODEL(J)%XABS_SW_SNOW_ROOF)
  NULLIFY(DIAG_MISC_TEB_MODEL(J)%XABS_LW_ROOF)
  NULLIFY(DIAG_MISC_TEB_MODEL(J)%XABS_LW_SNOW_ROOF)
  NULLIFY(DIAG_MISC_TEB_MODEL(J)%XABS_SW_ROAD)
  NULLIFY(DIAG_MISC_TEB_MODEL(J)%XABS_SW_SNOW_ROAD)
  NULLIFY(DIAG_MISC_TEB_MODEL(J)%XABS_LW_ROAD)
  NULLIFY(DIAG_MISC_TEB_MODEL(J)%XABS_LW_SNOW_ROAD)
  NULLIFY(DIAG_MISC_TEB_MODEL(J)%XABS_SW_WALL)
  NULLIFY(DIAG_MISC_TEB_MODEL(J)%XABS_LW_WALL)
  NULLIFY(DIAG_MISC_TEB_MODEL(J)%XABS_SW_GARDEN)
  NULLIFY(DIAG_MISC_TEB_MODEL(J)%XABS_LW_GARDEN)
ENDDO
DIAG_MISC_TEB_MODEL(:)%LSURF_MISC_BUDGET=.FALSE.
DIAG_MISC_TEB_MODEL(:)%LSURF_BUDGETC=.FALSE.
DIAG_MISC_TEB_MODEL(:)%LRESET_BUDGETC=.FALSE.
DIAG_MISC_TEB_MODEL(:)%LSURF_EVAP_BUDGET=.FALSE.
DIAG_MISC_TEB_MODEL(:)%LSURF_DIAG_ALBEDO=.FALSE.
IF (LHOOK) CALL DR_HOOK("MODD_DIAG_MISC_TEB_N:DIAG_MISC_TEB_ALLOC",1,ZHOOK_HANDLE)
END SUBROUTINE DIAG_MISC_TEB_ALLOC

SUBROUTINE DIAG_MISC_TEB_DEALLO
REAL(KIND=JPRB) :: ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK("MODD_DIAG_MISC_TEB_N:DIAG_MISC_TEB_DEALLO",0,ZHOOK_HANDLE)
IF (ALLOCATED(DIAG_MISC_TEB_MODEL)) DEALLOCATE(DIAG_MISC_TEB_MODEL)
IF (LHOOK) CALL DR_HOOK("MODD_DIAG_MISC_TEB_N:DIAG_MISC_TEB_DEALLO",1,ZHOOK_HANDLE)
END SUBROUTINE DIAG_MISC_TEB_DEALLO

END MODULE MODD_DIAG_MISC_TEB_n
