!     ##################
      MODULE MODD_AGRI_GARDEN_n
!     ##################
!
!!****  *MODD_AGRI_GARDEN_n - declaration of SEEDING date for summer crops 
!!      
!!    PURPOSE
!!    -------
!
!!
!!**  IMPLICIT ARGUMENTS
!!    ------------------
!!      None 
!!
!!    REFERENCE
!!    ---------
!!
!!    AUTHOR
!!    ------
!!	P. LE MOIGNE   *Meteo France*
!!
!!    MODIFICATIONS
!!    -------------
!!      Original       06/2006
!
!*       0.   DECLARATIONS
!             ------------
!
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE
!
!-------------------------------------------------------------------------------
TYPE AGRI_GARDEN_t
!                                          
INTEGER, POINTER, DIMENSION (:,:)   :: NIRRINUM       
                                        ! Stage for Irrigation (4 stages)
!
LOGICAL, POINTER,DIMENSION(:,:)     :: LIRRIGATE 
                                        ! True if irrigation performed
!
LOGICAL, POINTER,DIMENSION(:,:)     :: LIRRIDAY 
                                        ! True if irrigation occurs during present day
!                                          
REAL, POINTER, DIMENSION(:,:)       :: XTHRESHOLDSPT 
                                        ! Spatialized threshold

END TYPE AGRI_GARDEN_t
!-------------------------------------------------------------------------------

TYPE(AGRI_GARDEN_t), ALLOCATABLE, TARGET, SAVE :: AGRI_GARDEN_MODEL(:)

INTEGER, POINTER, DIMENSION (:,:)   :: NIRRINUM=>NULL()
!$OMP THREADPRIVATE(NIRRINUM)
LOGICAL, POINTER, DIMENSION (:,:)   :: LIRRIGATE=>NULL()
!$OMP THREADPRIVATE(LIRRIGATE)
LOGICAL, POINTER, DIMENSION (:,:)   :: LIRRIDAY=>NULL()
!$OMP THREADPRIVATE(LIRRIDAY)
REAL, POINTER, DIMENSION (:,:)   :: XTHRESHOLDSPT=>NULL()
!$OMP THREADPRIVATE(XTHRESHOLDSPT)

CONTAINS

SUBROUTINE AGRI_GARDEN_GOTO_MODEL(KFROM,KTO, LKFROM)                                        
LOGICAL, INTENT(IN) :: LKFROM
!
INTEGER, INTENT(IN) :: KFROM, KTO
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
! Save current state for allocated arrays
IF (LKFROM) THEN
AGRI_GARDEN_MODEL(KFROM)%NIRRINUM=>NIRRINUM
AGRI_GARDEN_MODEL(KFROM)%LIRRIGATE=>LIRRIGATE
AGRI_GARDEN_MODEL(KFROM)%LIRRIDAY=>LIRRIDAY
AGRI_GARDEN_MODEL(KFROM)%XTHRESHOLDSPT=>XTHRESHOLDSPT
ENDIF
!
! Current model is set to model KTO
IF (LHOOK) CALL DR_HOOK('MODD_AGRI_GARDEN_N:AGRI_GARDEN_GOTO_MODEL',0,ZHOOK_HANDLE)
NIRRINUM=>AGRI_GARDEN_MODEL(KTO)%NIRRINUM          
LIRRIGATE=>AGRI_GARDEN_MODEL(KTO)%LIRRIGATE          
LIRRIDAY=>AGRI_GARDEN_MODEL(KTO)%LIRRIDAY          
XTHRESHOLDSPT=>AGRI_GARDEN_MODEL(KTO)%XTHRESHOLDSPT          
IF (LHOOK) CALL DR_HOOK('MODD_AGRI_GARDEN_N:AGRI_GARDEN_GOTO_MODEL',1,ZHOOK_HANDLE)
                                        
END SUBROUTINE AGRI_GARDEN_GOTO_MODEL

SUBROUTINE AGRI_GARDEN_ALLOC(KMODEL)
INTEGER, INTENT(IN) :: KMODEL
INTEGER :: J
REAL(KIND=JPRB) :: ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK("MODD_AGRI_GARDEN_N:AGRI_GARDEN_ALLOC",0,ZHOOK_HANDLE)
ALLOCATE(AGRI_GARDEN_MODEL(KMODEL))
DO J=1,KMODEL
  NULLIFY(AGRI_GARDEN_MODEL(J)%NIRRINUM)
  NULLIFY(AGRI_GARDEN_MODEL(J)%LIRRIGATE)
  NULLIFY(AGRI_GARDEN_MODEL(J)%LIRRIDAY)
  NULLIFY(AGRI_GARDEN_MODEL(J)%XTHRESHOLDSPT)
ENDDO
IF (LHOOK) CALL DR_HOOK("MODD_AGRI_GARDEN_N:AGRI_GARDEN_ALLOC",1,ZHOOK_HANDLE)
END SUBROUTINE AGRI_GARDEN_ALLOC

SUBROUTINE AGRI_GARDEN_DEALLO
REAL(KIND=JPRB) :: ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK("MODD_AGRI_GARDEN_N:AGRI_GARDEN_DEALLO",0,ZHOOK_HANDLE)
IF (ALLOCATED(AGRI_GARDEN_MODEL)) DEALLOCATE(AGRI_GARDEN_MODEL)
IF (LHOOK) CALL DR_HOOK("MODD_AGRI_GARDEN_N:AGRI_GARDEN_DEALLO",1,ZHOOK_HANDLE)
END SUBROUTINE AGRI_GARDEN_DEALLO
!-------------------------------------------------------------------------------
!
END MODULE MODD_AGRI_GARDEN_n
