MODULE MODD_SLT_n

!Purpose: 
!Declare variables and constants necessary to do the sea salt calculations
!Here are only the variables which depend on the grid!

!Author: Alf Grini / Pierre Tulet

!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE

TYPE SLT_t
  !
  !
  INTEGER, DIMENSION(:), POINTER     :: NVT_SLT=>NULL()           !MASK: sea salt vegetation number to vegetation number
  INTEGER, DIMENSION(:,:), POINTER   :: NSIZE_PATCH_SLT=>NULL()   !Number of points for a patch and a vegetation class
  INTEGER, DIMENSION(:,:,:), POINTER :: NR_PATCH_SLT=>NULL()      !Mask from patch-points to sea salt-points
  REAL,DIMENSION(:), POINTER         :: Z0_EROD_SLT=>NULL()       !Roughness length momentum over erodible sea salt emitter sfc
  CHARACTER(LEN=6), DIMENSION(:), POINTER  :: CSV_SLT =>NULL()          !Name of scalar variables 
  REAL, DIMENSION(:,:,:),POINTER    :: XSFSLT=>NULL()            !Sea Salt variables to be send to output
  REAL,DIMENSION(:), POINTER   :: XEMISRADIUS_SLT =>NULL()               !Number median radius for each source mode
  REAL,DIMENSION(:), POINTER   :: XEMISSIG_SLT  =>NULL()                 !sigma for each source mode
END TYPE SLT_t

TYPE(SLT_t), ALLOCATABLE, TARGET, SAVE :: SLT_MODEL(:)

INTEGER, DIMENSION(:), POINTER     :: NVT_SLT=>NULL()
!$OMP THREADPRIVATE(NVT_SLT)
INTEGER, DIMENSION(:,:), POINTER   :: NSIZE_PATCH_SLT=>NULL()
!$OMP THREADPRIVATE(NSIZE_PATCH_SLT)
INTEGER, DIMENSION(:,:,:), POINTER :: NR_PATCH_SLT=>NULL()
!$OMP THREADPRIVATE(NR_PATCH_SLT)
REAL,DIMENSION(:), POINTER         :: Z0_EROD_SLT=>NULL()
!$OMP THREADPRIVATE(Z0_EROD_SLT)
CHARACTER(LEN=6), DIMENSION(:), POINTER   :: CSV_SLT=>NULL()
!$OMP THREADPRIVATE(CSV_SLT)
REAL, DIMENSION(:,:,:),POINTER     :: XSFSLT=>NULL()
!$OMP THREADPRIVATE(XSFSLT)
REAL,DIMENSION(:), POINTER   :: XEMISRADIUS_SLT=>NULL()
!$OMP THREADPRIVATE(XEMISRADIUS_SLT)
REAL,DIMENSION(:), POINTER   :: XEMISSIG_SLT=>NULL()
!$OMP THREADPRIVATE(XEMISSIG_SLT)

CONTAINS

SUBROUTINE SLT_GOTO_MODEL(KFROM, KTO, LKFROM)
LOGICAL, INTENT(IN) :: LKFROM
INTEGER, INTENT(IN) :: KFROM, KTO
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
! Save current state for allocated arrays
IF (LKFROM) THEN
SLT_MODEL(KFROM)%NVT_SLT=>NVT_SLT
SLT_MODEL(KFROM)%NSIZE_PATCH_SLT=>NSIZE_PATCH_SLT
SLT_MODEL(KFROM)%NR_PATCH_SLT=>NR_PATCH_SLT
SLT_MODEL(KFROM)%Z0_EROD_SLT=>Z0_EROD_SLT
SLT_MODEL(KFROM)%CSV_SLT=>CSV_SLT
SLT_MODEL(KFROM)%XSFSLT=>XSFSLT
SLT_MODEL(KFROM)%XEMISRADIUS_SLT=>XEMISRADIUS_SLT
SLT_MODEL(KFROM)%XEMISSIG_SLT=>XEMISSIG_SLT
ENDIF
!
! Current model is set to model KTO
IF (LHOOK) CALL DR_HOOK('MODD_SLT_N:SLT_GOTO_MODEL',0,ZHOOK_HANDLE)
NVT_SLT=>SLT_MODEL(KTO)%NVT_SLT
NSIZE_PATCH_SLT=>SLT_MODEL(KTO)%NSIZE_PATCH_SLT
NR_PATCH_SLT=>SLT_MODEL(KTO)%NR_PATCH_SLT
Z0_EROD_SLT=>SLT_MODEL(KTO)%Z0_EROD_SLT
CSV_SLT=>SLT_MODEL(KTO)%CSV_SLT
XSFSLT=>SLT_MODEL(KTO)%XSFSLT
XEMISRADIUS_SLT=>SLT_MODEL(KTO)%XEMISRADIUS_SLT
XEMISSIG_SLT=>SLT_MODEL(KTO)%XEMISSIG_SLT
IF (LHOOK) CALL DR_HOOK('MODD_SLT_N:SLT_GOTO_MODEL',1,ZHOOK_HANDLE)

END SUBROUTINE SLT_GOTO_MODEL

SUBROUTINE SLT_ALLOC(KMODEL)
INTEGER, INTENT(IN) :: KMODEL
REAL(KIND=JPRB) :: ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK("MODD_SLT_N:SLT_ALLOC",0,ZHOOK_HANDLE)
ALLOCATE(SLT_MODEL(KMODEL))
IF (LHOOK) CALL DR_HOOK("MODD_SLT_N:SLT_ALLOC",1,ZHOOK_HANDLE)
END SUBROUTINE SLT_ALLOC

SUBROUTINE SLT_DEALLO
REAL(KIND=JPRB) :: ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK("MODD_SLT_N:SLT_DEALLO",0,ZHOOK_HANDLE)
IF (ALLOCATED(SLT_MODEL)) DEALLOCATE(SLT_MODEL)
IF (LHOOK) CALL DR_HOOK("MODD_SLT_N:SLT_DEALLO",1,ZHOOK_HANDLE)
END SUBROUTINE SLT_DEALLO

END MODULE MODD_SLT_n
