!     ######spl
      MODULE MODE_SOIL_VG 
!     ################
!
!!****  *MODE_SOIL_VG * - contains soil characteristics functions for Van Genuchten scheme
!!
!!    PURPOSE
!!    -------
!
!!**  METHOD
!!    ------
!!    
!!    All clay and sand proportions are given in FRACTION (not in percentages)
!!    while organic matter is gicen in % and dray density in g/m3
!!    
!!
!!    EXTERNAL
!!    --------
!!       
!!    IMPLICIT ARGUMENTS
!!    ------------------ 
!!
!!    REFERENCE
!!    ---------
!!    Carsel and Parrish, WATER RESOURCES RESEARCH, 24, 755-769
!!    Wosten et al. 1999, GEODERMA, 90, 169-185
!!      
!!
!!    AUTHOR
!!    ------
!!	B. Decharme       * Meteo France *
!!
!!    MODIFICATIONS
!!    -------------
!!      Original        05/2010
!-----------------------------------------------------------------------------
!
!*       0.    DECLARATIONS
!
!
INTERFACE WSAT_VG
  MODULE PROCEDURE WSAT_VG_2D
  MODULE PROCEDURE WSAT_VG_1D
END INTERFACE
INTERFACE WWILT_VG
  MODULE PROCEDURE WWILT_VG_2D
  MODULE PROCEDURE WWILT_VG_1D
END INTERFACE
INTERFACE WFC_VG
  MODULE PROCEDURE WFC_VG_2D
  MODULE PROCEDURE WFC_VG_1D
END INTERFACE
INTERFACE WRES_VG
  MODULE PROCEDURE WRES_VG_2D
  MODULE PROCEDURE WRES_VG_1D
END INTERFACE
INTERFACE NCOEF_VG
  MODULE PROCEDURE NCOEF_VG_2D
  MODULE PROCEDURE NCOEF_VG_1D
END INTERFACE
INTERFACE LCOEF_VG
  MODULE PROCEDURE LCOEF_VG_2D
  MODULE PROCEDURE LCOEF_VG_1D
END INTERFACE
INTERFACE ALPHA_VG
  MODULE PROCEDURE ALPHA_VG_2D
  MODULE PROCEDURE ALPHA_VG_1D
END INTERFACE
INTERFACE HYDCONDSAT_VG
  MODULE PROCEDURE HYDCONDSAT_VG_2D
  MODULE PROCEDURE HYDCONDSAT_VG_1D
END INTERFACE
!-------------------------------------------------------------------------------
CONTAINS
!
   FUNCTION WSAT_VG_2D(PCLAY,PSAND,PMO,PDENS,PTOPSOIL,HPEDOTF)
   USE MODD_SURF_PAR,   ONLY : XUNDEF
   USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
   USE PARKIND1  ,ONLY : JPRB
   IMPLICIT NONE
   REAL, DIMENSION(:,:), INTENT(IN)     :: PCLAY,PSAND,PMO,PDENS,PTOPSOIL
   CHARACTER(LEN=4),     INTENT(IN)     :: HPEDOTF
   REAL, DIMENSION(SIZE(PCLAY,1),SIZE(PCLAY,2)) :: ZSILT
   REAL, DIMENSION(SIZE(PCLAY,1),SIZE(PCLAY,2)) :: WSAT_VG_2D
   REAL(KIND=JPRB) :: ZHOOK_HANDLE
   !
   IF (LHOOK) CALL DR_HOOK('MODE_SOIL_VG:WSAT_VG_2D',0,ZHOOK_HANDLE)
   SELECT CASE (HPEDOTF)
          CASE ('CP88')
               WHERE(PCLAY/=XUNDEF)
                    WSAT_VG_2D = 0.4874391874-0.0673307510*PSAND-0.1974384849*PCLAY
               END WHERE
          CASE ('WO99')
               WHERE(PCLAY/=XUNDEF)
                    ZSILT=1.0-PCLAY-PSAND
                    WSAT_VG_2D = 0.7919+0.1691*PCLAY-0.29619*(PDENS/1000.)-0.01491*(ZSILT**2)+0.0000821*(PMO**2)   &
                                + 0.0002427/PCLAY+0.0001113/ZSILT+0.01472*LOG(ZSILT*100.)-0.00733*PMO*PCLAY         &
                                - 0.0619*(PDENS/1000.)*PCLAY-0.001183*(PDENS/1000.)*PMO-0.01664*PTOPSOIL*ZSILT 
               END WHERE
   END SELECT
   !                 
   WHERE(PCLAY==XUNDEF)
     WSAT_VG_2D = XUNDEF
   END WHERE
   IF (LHOOK) CALL DR_HOOK('MODE_SOIL_VG:WSAT_VG_2D',1,ZHOOK_HANDLE)
   !
   END FUNCTION WSAT_VG_2D
   !
   !
   !
   FUNCTION WWILT_VG_2D(PWSAT,PALPHA,PN,PM,PWR,HPEDOTF)
   USE MODD_SURF_PAR,   ONLY : XUNDEF
   USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
   USE PARKIND1  ,ONLY : JPRB
   IMPLICIT NONE
   REAL, DIMENSION(:,:), INTENT(IN)     :: PWSAT,PALPHA,PN,PM,PWR
   CHARACTER(LEN=4),     INTENT(IN)     :: HPEDOTF
   REAL, DIMENSION(SIZE(PWSAT,1),SIZE(PWSAT,2)) :: WWILT_VG_2D
   REAL(KIND=JPRB) :: ZHOOK_HANDLE
   !
   ! Wilting point is calculated as the water content at a tension of 150m (15 bars)
   !
   IF (LHOOK) CALL DR_HOOK('MODE_SOIL_VG:WWILT_VG_2D',0,ZHOOK_HANDLE)
   SELECT CASE (HPEDOTF)
          CASE ('CP88')
               WHERE(PWSAT/=XUNDEF)
                    WWILT_VG_2D = PWR+(PWSAT-PWR)*(1.0/(1.0+(PALPHA*150.)**PN))**PM
               END WHERE
          CASE ('WO99')
               WHERE(PWSAT/=XUNDEF)
                    WWILT_VG_2D = PWSAT*(1.0/(1.0+(PALPHA*150.)**PN))**PM
               END WHERE
   END SELECT
   !                 
   WHERE(PWSAT==XUNDEF)
     WWILT_VG_2D = XUNDEF
   END WHERE
   IF (LHOOK) CALL DR_HOOK('MODE_SOIL_VG:WWILT_VG_2D',1,ZHOOK_HANDLE)
   !
   END FUNCTION WWILT_VG_2D
   !
   !
   !
   FUNCTION WFC_VG_2D(PWSAT,PKSAT,PN,PWR,HPEDOTF)
   USE MODD_SURF_PAR,   ONLY : XUNDEF
   USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
   USE PARKIND1  ,ONLY : JPRB   
   IMPLICIT NONE
   REAL, DIMENSION(:,:), INTENT(IN)             :: PWSAT,PKSAT,PN,PWR
   CHARACTER(LEN=4),     INTENT(IN)             :: HPEDOTF
   REAL, DIMENSION(SIZE(PWSAT,1),SIZE(PWSAT,2)) :: ZKSAT
   REAL, DIMENSION(SIZE(PWSAT,1),SIZE(PWSAT,2)) :: WFC_VG_2D
   REAL(KIND=JPRB) :: ZHOOK_HANDLE
   !
   IF (LHOOK) CALL DR_HOOK('MODE_SOIL_VG:WFC_VG_2D',0,ZHOOK_HANDLE)
   SELECT CASE (HPEDOTF)
          CASE ('CP88')
               WHERE(PWSAT/=XUNDEF)
                    ZKSAT     = PKSAT*8640000. !cm/d
                    WFC_VG_2D = PWR+(PWSAT-PWR)*PN**(-0.6*(2.+LOG10(ZKSAT)))
               END WHERE
          CASE ('WO99')
               WHERE(PWSAT/=XUNDEF)
                    ZKSAT     = PKSAT*8640000. !cm/d
                    WFC_VG_2D = PWSAT*PN**(-0.6*(2.+LOG10(ZKSAT)))
               END WHERE
   END SELECT
   !                 
   WHERE(PWSAT==XUNDEF)
     WFC_VG_2D = XUNDEF
   END WHERE
   IF (LHOOK) CALL DR_HOOK('MODE_SOIL_VG:WFC_VG_2D',1,ZHOOK_HANDLE)
   !
   END FUNCTION WFC_VG_2D   
   !
   !
   !   
   FUNCTION WRES_VG_2D(PCLAY,PSAND,HPEDOTF)
   USE MODD_SURF_PAR,   ONLY : XUNDEF
   USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
   USE PARKIND1  ,ONLY : JPRB   
   IMPLICIT NONE
   REAL, DIMENSION(:,:), INTENT(IN)     :: PCLAY,PSAND
   CHARACTER(LEN=4),     INTENT(IN)     :: HPEDOTF
   REAL, DIMENSION(SIZE(PCLAY,1),SIZE(PCLAY,2)) :: WRES_VG_2D
   REAL(KIND=JPRB) :: ZHOOK_HANDLE
   !
   IF (LHOOK) CALL DR_HOOK('MODE_SOIL_VG:WRES_VG_2D',0,ZHOOK_HANDLE)
   SELECT CASE (HPEDOTF)
          CASE ('CP88')
               WHERE(PCLAY/=XUNDEF)
                    WRES_VG_2D =10.0**(-1.7071507883+0.3091040189*PSAND+3.2272283707*PCLAY &
                                        -4.3251366693*(PCLAY**2)    ) 
               END WHERE
          CASE ('WO99')
               WHERE(PCLAY/=XUNDEF)
                    WRES_VG_2D = 0.0
               END WHERE
   END SELECT
   !                 
   WHERE(PCLAY==XUNDEF)
     WRES_VG_2D = XUNDEF
   END WHERE
   IF (LHOOK) CALL DR_HOOK('MODE_SOIL_VG:WRES_VG_2D',1,ZHOOK_HANDLE)
   !
   END FUNCTION WRES_VG_2D
   !
   !
   !
   FUNCTION NCOEF_VG_2D(PCLAY,PSAND,PMO,PDENS,PTOPSOIL,HPEDOTF)
   USE MODD_SURF_PAR,   ONLY : XUNDEF
   USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
   USE PARKIND1  ,ONLY : JPRB   
   IMPLICIT NONE
   REAL, DIMENSION(:,:), INTENT(IN)     :: PCLAY,PSAND,PMO,PDENS,PTOPSOIL
   CHARACTER(LEN=4),     INTENT(IN)     :: HPEDOTF
   REAL, DIMENSION(SIZE(PCLAY,1),SIZE(PCLAY,2)) :: ZSILT
   REAL, DIMENSION(SIZE(PCLAY,1),SIZE(PCLAY,2)) :: NCOEF_VG_2D
   REAL(KIND=JPRB) :: ZHOOK_HANDLE
   !
   IF (LHOOK) CALL DR_HOOK('MODE_SOIL_VG:NCOEF_VG_2D',0,ZHOOK_HANDLE)
   SELECT CASE (HPEDOTF)
          CASE ('CP88')
               WHERE(PCLAY/=XUNDEF)
                    NCOEF_VG_2D = 1.0+10.0**(-0.3389442219+0.7123318016*PSAND-0.7644550908*PCLAY &
                                              -0.1084756583*(PSAND**2)-1.4567297353*(PCLAY**2)    ) 
               END WHERE
          CASE ('WO99')
               WHERE(PCLAY/=XUNDEF)
                    ZSILT=1.0-PCLAY-PSAND
                    NCOEF_VG_2D = -25.23-2.195*PCLAY+0.74*ZSILT-0.194*PMO+45.5*(PDENS/1000.)-7.24*((PDENS/1000.)**2) &
                                 + 3.658*(PCLAY**2)+0.002885*(PMO**2)-12.81/(PDENS/1000.)-0.001524/ZSILT              &
                                 - 0.01958/PMO-0.2876*LOG(ZSILT*100.)-0.0709*LOG(PMO)-44.6*LOG((PDENS/1000.))         &
                                 - 2.264*(PDENS/1000.)*PCLAY+0.0896*PMO*(PDENS/1000.)+0.718*PTOPSOIL*PCLAY 
                    NCOEF_VG_2D = 1.0+EXP(NCOEF_VG_2D)
               END WHERE
   END SELECT
   !
   WHERE(PCLAY==XUNDEF)
     NCOEF_VG_2D = XUNDEF
   END WHERE
   IF (LHOOK) CALL DR_HOOK('MODE_SOIL_VG:NCOEF_VG_2D',1,ZHOOK_HANDLE)
   !
   END FUNCTION NCOEF_VG_2D
   !
   !
   !
   FUNCTION LCOEF_VG_2D(PCLAY,PSAND,PMO,PDENS,HPEDOTF)
   USE MODD_SURF_PAR,   ONLY : XUNDEF
   USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
   USE PARKIND1  ,ONLY : JPRB   
   IMPLICIT NONE
   REAL, DIMENSION(:,:), INTENT(IN)     :: PCLAY,PSAND,PMO,PDENS
   CHARACTER(LEN=4),     INTENT(IN)     :: HPEDOTF
   REAL, DIMENSION(SIZE(PCLAY,1),SIZE(PCLAY,2)) :: ZSILT
   REAL, DIMENSION(SIZE(PCLAY,1),SIZE(PCLAY,2)) :: LCOEF_VG_2D
   REAL(KIND=JPRB) :: ZHOOK_HANDLE
   !
   IF (LHOOK) CALL DR_HOOK('MODE_SOIL_VG:LCOEF_VG_2D',0,ZHOOK_HANDLE)
   SELECT CASE (HPEDOTF)
          CASE ('CP88')
               WHERE(PCLAY/=XUNDEF)
                    LCOEF_VG_2D = 0.5
               END WHERE
          CASE ('WO99')
               WHERE(PCLAY/=XUNDEF)
                    ZSILT=1.0-PCLAY-PSAND
                    LCOEF_VG_2D = 0.0202+6.193*(PCLAY**2)-0.001136*(PMO**2)-0.2316*LOG(PMO) &
                                 - 3.544*(PDENS/1000.)*PCLAY+0.283*(PDENS/1000.)*ZSILT       &
                                 +0.0488*(PDENS/1000.)*PMO 
                    LCOEF_VG_2D = 10.*(EXP(LCOEF_VG_2D)-1.0)/(EXP(LCOEF_VG_2D)+1.0)
               END WHERE
   END SELECT
   !
   WHERE(PCLAY==XUNDEF)
     LCOEF_VG_2D = XUNDEF
   END WHERE
   IF (LHOOK) CALL DR_HOOK('MODE_SOIL_VG:LCOEF_VG_2D',1,ZHOOK_HANDLE)
   !
   END FUNCTION LCOEF_VG_2D
   !
   !
   !
   FUNCTION ALPHA_VG_2D(PCLAY,PSAND,PMO,PDENS,PTOPSOIL,HPEDOTF)
   USE MODD_SURF_PAR,   ONLY : XUNDEF
   USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
   USE PARKIND1  ,ONLY : JPRB   
   IMPLICIT NONE
   REAL, DIMENSION(:,:), INTENT(IN)     :: PCLAY,PSAND,PMO,PDENS,PTOPSOIL
   CHARACTER(LEN=4),     INTENT(IN)     :: HPEDOTF
   REAL, DIMENSION(SIZE(PCLAY,1),SIZE(PCLAY,2)) :: ZSILT
   REAL, DIMENSION(SIZE(PDENS,1),SIZE(PDENS,2)) :: ALPHA_VG_2D
   REAL(KIND=JPRB) :: ZHOOK_HANDLE
   !
   IF (LHOOK) CALL DR_HOOK('MODE_SOIL_VG:ALPHA_VG_2D',0,ZHOOK_HANDLE)
   SELECT CASE (HPEDOTF)
          CASE ('CP88')
               WHERE(PCLAY/=XUNDEF)
                    ALPHA_VG_2D = 10.0**(0.1790380307+1.9495054331*PSAND-1.0889210975*PCLAY  &
                                          -0.9192936565*(PSAND**2)) 
               END WHERE
          CASE ('WO99')
               WHERE(PCLAY/=XUNDEF)
                    ZSILT=1.0-PCLAY-PSAND
                    ALPHA_VG_2D = -14.96+3.135*PCLAY+3.51*ZSILT+0.646*PMO+15.29*(PDENS/1000.)-0.192*PTOPSOIL &
                                 - 4.671*((PDENS/1000.)**2)-7.81*(PCLAY**2)-0.00687*(PMO**2)+0.0449/PMO       &
                                 + 0.0663*LOG(ZSILT*100.)+0.1482*LOG(PMO)-4.546*(PDENS/1000.)*ZSILT           &
                                 - 0.4852*(PDENS/1000.)*PMO+0.673*PTOPSOIL*PCLAY 
                    ALPHA_VG_2D = 100.*EXP(ALPHA_VG_2D)
               END WHERE
   END SELECT
   !
   WHERE(PCLAY==XUNDEF)
     ALPHA_VG_2D = XUNDEF
   END WHERE
   IF (LHOOK) CALL DR_HOOK('MODE_SOIL_VG:ALPHA_VG_2D',1,ZHOOK_HANDLE)
   !
   END FUNCTION ALPHA_VG_2D
   !
   !
   !
   FUNCTION HYDCONDSAT_VG_2D(PCLAY,PSAND,PMO,PDENS,PTOPSOIL,HPEDOTF)
   USE MODD_SURF_PAR,   ONLY : XUNDEF
   USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
   USE PARKIND1  ,ONLY : JPRB   
   IMPLICIT NONE
   REAL, DIMENSION(:,:), INTENT(IN)     :: PCLAY,PSAND,PMO,PDENS,PTOPSOIL
   CHARACTER(LEN=4),     INTENT(IN)     :: HPEDOTF
   REAL, DIMENSION(SIZE(PCLAY,1),SIZE(PCLAY,2)) :: ZSILT
   REAL, DIMENSION(SIZE(PCLAY,1),SIZE(PCLAY,2)) :: HYDCONDSAT_VG_2D
   REAL(KIND=JPRB) :: ZHOOK_HANDLE
   !
   IF (LHOOK) CALL DR_HOOK('MODE_SOIL_VG:HYDCONDSAT_VG_2D',0,ZHOOK_HANDLE)
   SELECT CASE (HPEDOTF)
          CASE ('CP88')
               WHERE(PCLAY/=XUNDEF)
                    HYDCONDSAT_VG_2D = 10.0**(2.1382547479-4.2871305871*PSAND+7.5040572488*PCLAY &
                                               +6.5767808336*(PSAND**0.5)-10.5119448914*(PCLAY**0.5)) 
                    HYDCONDSAT_VG_2D = HYDCONDSAT_VG_2D/8640000.   
               END WHERE
          CASE ('WO99')
               WHERE(PCLAY/=XUNDEF)
                    ZSILT=1.0-PCLAY-PSAND
                    HYDCONDSAT_VG_2D = 7.755+3.52*ZSILT+0.93*PTOPSOIL-0.967*((PDENS/1000.)**2)-4.84*(PCLAY**2) &
                                      - 3.22*(ZSILT**2)+0.00001/ZSILT-0.0748/PMO-0.643*LOG(ZSILT*100.)  &
                                      - 1.398*(PDENS/1000.)*PCLAY-0.1673*(PDENS/1000.)*PMO+2.986*PTOPSOIL*PCLAY         &
                                      - 3.305*PTOPSOIL*ZSILT 
                    HYDCONDSAT_VG_2D = EXP(HYDCONDSAT_VG_2D)/8640000.
               END WHERE
   END SELECT
   !
   WHERE(PCLAY==XUNDEF)
     HYDCONDSAT_VG_2D = XUNDEF
   END WHERE
   IF (LHOOK) CALL DR_HOOK('MODE_SOIL_VG:HYDCONDSAT_VG_2D',1,ZHOOK_HANDLE)
   !
   END FUNCTION HYDCONDSAT_VG_2D
!                                                          
!
!-------------------------------------------------------------------------------
!
   FUNCTION WSAT_VG_1D(PCLAY,PSAND,PMO,PDENS,PTOPSOIL,HPEDOTF)
   USE MODD_SURF_PAR,   ONLY : XUNDEF
   USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
   USE PARKIND1  ,ONLY : JPRB   
   IMPLICIT NONE
   REAL, DIMENSION(:), INTENT(IN)     :: PCLAY,PSAND,PMO,PDENS,PTOPSOIL
   CHARACTER(LEN=4),   INTENT(IN)     :: HPEDOTF
   REAL, DIMENSION(SIZE(PCLAY))       :: ZSILT
   REAL, DIMENSION(SIZE(PCLAY))       :: WSAT_VG_1D
   REAL(KIND=JPRB) :: ZHOOK_HANDLE
   !
   IF (LHOOK) CALL DR_HOOK('MODE_SOIL_VG:WSAT_VG_1D',0,ZHOOK_HANDLE)
   SELECT CASE (HPEDOTF)
          CASE ('CP88')
               WHERE(PCLAY/=XUNDEF)
                    WSAT_VG_1D = 0.4874391874-0.0673307510*PSAND-0.1974384849*PCLAY
               END WHERE
          CASE ('WO99')
               WHERE(PCLAY/=XUNDEF)
                    ZSILT=1.0-PCLAY-PSAND
                    WSAT_VG_1D = 0.7919+0.1691*PCLAY-0.29619*(PDENS/1000.)-0.01491*(ZSILT**2)+0.0000821*(PMO**2)   &
                                + 0.0002427/PCLAY+0.0001113/ZSILT+0.01472*LOG(ZSILT*100.)-0.00733*PMO*PCLAY &
                                - 0.0619*(PDENS/1000.)*PCLAY-0.001183*(PDENS/1000.)*PMO-0.01664*PTOPSOIL*ZSILT 
               END WHERE
   END SELECT
   !                 
   WHERE(PCLAY==XUNDEF)
     WSAT_VG_1D = XUNDEF
   END WHERE
   IF (LHOOK) CALL DR_HOOK('MODE_SOIL_VG:WSAT_VG_1D',1,ZHOOK_HANDLE)
   !
   END FUNCTION WSAT_VG_1D
   !
   !
   !
   FUNCTION WWILT_VG_1D(PWSAT,PALPHA,PN,PM,PWR,HPEDOTF)
   USE MODD_SURF_PAR,   ONLY : XUNDEF
   USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
   USE PARKIND1  ,ONLY : JPRB   
   IMPLICIT NONE
   REAL, DIMENSION(:), INTENT(IN)     :: PWSAT,PALPHA,PN,PM,PWR
   CHARACTER(LEN=4),     INTENT(IN)   :: HPEDOTF
   REAL, DIMENSION(SIZE(PWSAT))       :: WWILT_VG_1D
   REAL(KIND=JPRB) :: ZHOOK_HANDLE
   !
   ! Wilting point is calculated as the water content at a tension of 150m (15 bars)
   !
   IF (LHOOK) CALL DR_HOOK('MODE_SOIL_VG:WWILT_VG_1D',0,ZHOOK_HANDLE)
   SELECT CASE (HPEDOTF)
          CASE ('CP88')
               WHERE(PWSAT/=XUNDEF)
                    WWILT_VG_1D = PWR+(PWSAT-PWR)*(1.0/(1.0+(PALPHA*150.)**PN))**PM
               END WHERE
          CASE ('WO99')
               WHERE(PWSAT/=XUNDEF)
                    WWILT_VG_1D = PWSAT*(1.0/(1.0+(PALPHA*150.)**PN))**PM
               END WHERE
   END SELECT
   !                 
   WHERE(PWSAT==XUNDEF)
     WWILT_VG_1D = XUNDEF
   END WHERE
   IF (LHOOK) CALL DR_HOOK('MODE_SOIL_VG:WWILT_VG_1D',1,ZHOOK_HANDLE)
   !
   END FUNCTION WWILT_VG_1D
   !
   !
   !
   FUNCTION WFC_VG_1D(PWSAT,PKSAT,PN,PWR,HPEDOTF)
   USE MODD_SURF_PAR,   ONLY : XUNDEF
   USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
   USE PARKIND1  ,ONLY : JPRB   
   IMPLICIT NONE
   REAL, DIMENSION(:), INTENT(IN)       :: PWSAT,PKSAT,PN,PWR
   CHARACTER(LEN=4),     INTENT(IN)     :: HPEDOTF
   REAL, DIMENSION(SIZE(PWSAT))         :: ZKSAT
   REAL, DIMENSION(SIZE(PWSAT))         :: WFC_VG_1D
   REAL(KIND=JPRB) :: ZHOOK_HANDLE
   !
   IF (LHOOK) CALL DR_HOOK('MODE_SOIL_VG:WFC_VG_1D',0,ZHOOK_HANDLE)
   SELECT CASE (HPEDOTF)
          CASE ('CP88')
               WHERE(PWSAT/=XUNDEF)
                    ZKSAT     = PKSAT*8640000. !cm/d
                    WFC_VG_1D = PWR+(PWSAT-PWR)*PN**(-0.6*(2.+LOG10(ZKSAT)))
               END WHERE
          CASE ('WO99')
               WHERE(PWSAT/=XUNDEF)
                    ZKSAT     = PKSAT*8640000. !cm/d
                    WFC_VG_1D = PWSAT*PN**(-0.6*(2.+LOG10(ZKSAT)))
               END WHERE
   END SELECT
   !                 
   WHERE(PWSAT==XUNDEF)
     WFC_VG_1D = XUNDEF
   END WHERE
   IF (LHOOK) CALL DR_HOOK('MODE_SOIL_VG:WFC_VG_1D',1,ZHOOK_HANDLE)
   !
   END FUNCTION WFC_VG_1D   
   !
   !
   !   
   FUNCTION WRES_VG_1D(PCLAY,PSAND,HPEDOTF)
   USE MODD_SURF_PAR,   ONLY : XUNDEF
   USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
   USE PARKIND1  ,ONLY : JPRB   
   IMPLICIT NONE
   REAL, DIMENSION(:), INTENT(IN) :: PCLAY,PSAND
   CHARACTER(LEN=4),   INTENT(IN) :: HPEDOTF
   REAL, DIMENSION(SIZE(PCLAY))   :: WRES_VG_1D
   REAL(KIND=JPRB) :: ZHOOK_HANDLE
   !
   IF (LHOOK) CALL DR_HOOK('MODE_SOIL_VG:WRES_VG_1D',0,ZHOOK_HANDLE)
   SELECT CASE (HPEDOTF)
          CASE ('CP88')
               WHERE(PCLAY/=XUNDEF)
                    WRES_VG_1D =10.0**(-1.7071507883+0.3091040189*PSAND+3.2272283707*PCLAY &
                                        -4.3251366693*(PCLAY**2)    )   
               END WHERE
          CASE ('WO99')
               WHERE(PCLAY/=XUNDEF)
                    WRES_VG_1D = 0.0
               END WHERE
   END SELECT
   !                 
   WHERE(PCLAY==XUNDEF)
     WRES_VG_1D = XUNDEF
   END WHERE
   IF (LHOOK) CALL DR_HOOK('MODE_SOIL_VG:WRES_VG_1D',1,ZHOOK_HANDLE)
   !
   END FUNCTION WRES_VG_1D
   !
   !
   !
   FUNCTION NCOEF_VG_1D(PCLAY,PSAND,PMO,PDENS,PTOPSOIL,HPEDOTF)
   USE MODD_SURF_PAR,   ONLY : XUNDEF
   USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
   USE PARKIND1  ,ONLY : JPRB   
   IMPLICIT NONE
   REAL, DIMENSION(:), INTENT(IN) :: PCLAY,PSAND,PMO,PDENS,PTOPSOIL
   CHARACTER(LEN=4),   INTENT(IN) :: HPEDOTF
   REAL, DIMENSION(SIZE(PCLAY))   :: ZSILT
   REAL, DIMENSION(SIZE(PCLAY))   :: NCOEF_VG_1D
   REAL(KIND=JPRB) :: ZHOOK_HANDLE
   !
   IF (LHOOK) CALL DR_HOOK('MODE_SOIL_VG:NCOEF_VG_1D',0,ZHOOK_HANDLE)
   SELECT CASE (HPEDOTF)
          CASE ('CP88')
               WHERE(PCLAY/=XUNDEF)
                    NCOEF_VG_1D = 1.0+10.0**(-0.3389442219+0.7123318016*PSAND-0.7644550908*PCLAY &
                                              -0.1084756583*(PSAND**2)-1.4567297353*(PCLAY**2)    )   
               END WHERE
          CASE ('WO99')
               WHERE(PCLAY/=XUNDEF)
                    ZSILT=1.0-PCLAY-PSAND
                    NCOEF_VG_1D = -25.23-2.195*PCLAY+0.74*ZSILT-0.194*PMO+45.5*(PDENS/1000.)-7.24*((PDENS/1000.)**2) &
                                 + 3.658*(PCLAY**2)+0.002885*(PMO**2)-12.81/(PDENS/1000.)-0.001524/ZSILT              &
                                 - 0.01958/PMO-0.2876*LOG(ZSILT*100.)-0.0709*LOG(PMO)-44.6*LOG((PDENS/1000.))         &
                                 - 2.264*(PDENS/1000.)*PCLAY+0.0896*PMO*(PDENS/1000.)+0.718*PTOPSOIL*PCLAY 
                    NCOEF_VG_1D = 1.0+EXP(NCOEF_VG_1D)
               END WHERE
   END SELECT
   !
   WHERE(PCLAY==XUNDEF)
     NCOEF_VG_1D = XUNDEF
   END WHERE
   IF (LHOOK) CALL DR_HOOK('MODE_SOIL_VG:NCOEF_VG_1D',1,ZHOOK_HANDLE)
   !
   END FUNCTION NCOEF_VG_1D
   !
   !
   !
   FUNCTION LCOEF_VG_1D(PCLAY,PSAND,PMO,PDENS,HPEDOTF)
   USE MODD_SURF_PAR,   ONLY : XUNDEF
   USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
   USE PARKIND1  ,ONLY : JPRB   
   IMPLICIT NONE
   REAL, DIMENSION(:), INTENT(IN) :: PCLAY,PSAND,PMO,PDENS
   CHARACTER(LEN=4),   INTENT(IN) :: HPEDOTF
   REAL, DIMENSION(SIZE(PCLAY))   :: ZSILT
   REAL, DIMENSION(SIZE(PCLAY))   :: LCOEF_VG_1D
   REAL(KIND=JPRB) :: ZHOOK_HANDLE
   !
   IF (LHOOK) CALL DR_HOOK('MODE_SOIL_VG:LCOEF_VG_1D',0,ZHOOK_HANDLE)
   SELECT CASE (HPEDOTF)
          CASE ('CP88')
               WHERE(PCLAY/=XUNDEF)
                    LCOEF_VG_1D = 0.5
               END WHERE
          CASE ('WO99')
               WHERE(PCLAY/=XUNDEF)
                    ZSILT=1.0-PCLAY-PSAND
                    LCOEF_VG_1D = 0.0202+6.193*(PCLAY**2)-0.001136*(PMO**2)-0.2316*LOG(PMO) &
                                 - 3.544*(PDENS/1000.)*PCLAY+0.283*(PDENS/1000.)*ZSILT       &
                                 +0.0488*(PDENS/1000.)*PMO 
                    LCOEF_VG_1D = 10.*(EXP(LCOEF_VG_1D)-1.0)/(EXP(LCOEF_VG_1D)+1.0)
               END WHERE
   END SELECT
   !
   WHERE(PCLAY==XUNDEF)
     LCOEF_VG_1D = XUNDEF
   END WHERE
   IF (LHOOK) CALL DR_HOOK('MODE_SOIL_VG:LCOEF_VG_1D',1,ZHOOK_HANDLE)
   !
   END FUNCTION LCOEF_VG_1D
   !
   !
   !
   FUNCTION ALPHA_VG_1D(PCLAY,PSAND,PMO,PDENS,PTOPSOIL,HPEDOTF)
   USE MODD_SURF_PAR,   ONLY : XUNDEF
   USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
   USE PARKIND1  ,ONLY : JPRB   
   IMPLICIT NONE
   REAL, DIMENSION(:), INTENT(IN) :: PCLAY,PSAND,PMO,PDENS,PTOPSOIL
   CHARACTER(LEN=4),   INTENT(IN) :: HPEDOTF
   REAL, DIMENSION(SIZE(PCLAY))   :: ZSILT
   REAL, DIMENSION(SIZE(PDENS))   :: ALPHA_VG_1D
   REAL(KIND=JPRB) :: ZHOOK_HANDLE
   !
   IF (LHOOK) CALL DR_HOOK('MODE_SOIL_VG:ALPHA_VG_1D',0,ZHOOK_HANDLE)
   SELECT CASE (HPEDOTF)
          CASE ('CP88')
               WHERE(PCLAY/=XUNDEF)
                    ALPHA_VG_1D = 10.0**(0.1790380307+1.9495054331*PSAND-1.0889210975*PCLAY  &
                                          -0.9192936565*(PSAND**2))   
               END WHERE
          CASE ('WO99')
               WHERE(PCLAY/=XUNDEF)
                    ZSILT=1.0-PCLAY-PSAND
                    ALPHA_VG_1D = -14.96+3.135*PCLAY+3.51*ZSILT+0.646*PMO+15.29*(PDENS/1000.)-0.192*PTOPSOIL &
                                 - 4.671*((PDENS/1000.)**2)-7.81*(PCLAY**2)-0.00687*(PMO**2)+0.0449/PMO       &
                                 + 0.0663*LOG(ZSILT*100.)+0.1482*LOG(PMO)-4.546*(PDENS/1000.)*ZSILT           &
                                 - 0.4852*(PDENS/1000.)*PMO+0.673*PTOPSOIL*PCLAY 
                    ALPHA_VG_1D = 100.*EXP(ALPHA_VG_1D)
               END WHERE
   END SELECT
   !
   WHERE(PCLAY==XUNDEF)
     ALPHA_VG_1D = XUNDEF
   END WHERE
   IF (LHOOK) CALL DR_HOOK('MODE_SOIL_VG:ALPHA_VG_1D',1,ZHOOK_HANDLE)
   !
   END FUNCTION ALPHA_VG_1D
   !
   !
   !
   FUNCTION HYDCONDSAT_VG_1D(PCLAY,PSAND,PMO,PDENS,PTOPSOIL,HPEDOTF)
   USE MODD_SURF_PAR,   ONLY : XUNDEF
   USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
   USE PARKIND1  ,ONLY : JPRB   
   IMPLICIT NONE
   REAL, DIMENSION(:), INTENT(IN) :: PCLAY,PSAND,PMO,PDENS,PTOPSOIL
   CHARACTER(LEN=4),   INTENT(IN) :: HPEDOTF
   REAL, DIMENSION(SIZE(PCLAY))   :: ZSILT
   REAL, DIMENSION(SIZE(PCLAY))   :: HYDCONDSAT_VG_1D
   REAL(KIND=JPRB) :: ZHOOK_HANDLE
   !
   IF (LHOOK) CALL DR_HOOK('MODE_SOIL_VG:HYDCONDSAT_VG_1D',0,ZHOOK_HANDLE)
   SELECT CASE (HPEDOTF)
          CASE ('CP88')
               WHERE(PCLAY/=XUNDEF)
                    HYDCONDSAT_VG_1D = 10.0**(2.1382547479-4.2871305871*PSAND+7.5040572488*PCLAY &
                                               +6.5767808336*(PSAND**0.5)-10.5119448914*(PCLAY**0.5))    
                    HYDCONDSAT_VG_1D = HYDCONDSAT_VG_1D/8640000.   
               END WHERE
          CASE ('WO99')
               WHERE(PCLAY/=XUNDEF)
                    ZSILT=1.0-PCLAY-PSAND
                    HYDCONDSAT_VG_1D = 7.755+3.52*ZSILT+0.93*PTOPSOIL-0.967*((PDENS/1000.)**2)-4.84*(PCLAY**2) &
                                      - 3.22*(ZSILT**2)+0.00001/ZSILT-0.0748/PMO-0.643*LOG(ZSILT*100.)  &
                                      - 1.398*(PDENS/1000.)*PCLAY-0.1673*(PDENS/1000.)*PMO+2.986*PTOPSOIL*PCLAY         &
                                      - 3.305*PTOPSOIL*ZSILT 
                    HYDCONDSAT_VG_1D = EXP(HYDCONDSAT_VG_1D)/8640000.
               END WHERE
   END SELECT
   !
   WHERE(PCLAY==XUNDEF)
     HYDCONDSAT_VG_1D = XUNDEF
   END WHERE
   IF (LHOOK) CALL DR_HOOK('MODE_SOIL_VG:HYDCONDSAT_VG_1D',1,ZHOOK_HANDLE)
   !
   END FUNCTION HYDCONDSAT_VG_1D   
!                                                          
!
!-------------------------------------------------------------------------------
!
END MODULE MODE_SOIL_VG
