!##################
MODULE MODN_TEB_GARDEN_n
!##################
!
!!****  *MODN_TEB_GARDEN_n* - declaration of namelist NAM_TEB_GARDEN_n
!!
!!    PURPOSE
!!    -------
!       The purpose of this module is to specify  the namelist NAM_TEB_GARDEN_n
!     which concern the surface configuration of one nested  model.
!
!!
!!**  IMPLICIT ARGUMENTS
!!    ------------------
!!
!!    REFERENCE
!!    ---------
!!
!!       
!!    AUTHOR
!!    ------
!!	V. Masson    *Meteo France*
!!
!!    MODIFICATIONS
!!    -------------
!!      Original    01/2004                    
!-------------------------------------------------------------------------------
!
!*       0.   DECLARATIONS
!             ------------
!
USE MODD_CH_TEB_n, ONLY: &
           LCH_BIO_FLUX_n => LCH_BIO_FLUX, &
           CCH_DRY_DEP_n => CCH_DRY_DEP,   &
           CCHEM_SURF_FILE_n => CCHEM_SURF_FILE  
USE MODD_TEB_GARDEN_n, ONLY: &
           CC1DRY_n => CC1DRY, &
           CSCOND_n => CSCOND, &
           CSOILFRZ_n => CSOILFRZ, &
           CDIFSFCOND_n => CDIFSFCOND, &
           CSNOWRES_n => CSNOWRES, &
           CALBEDO_n => CALBEDO, &
           CROUGH_n => CROUGH, &
           CCPSURF_n => CCPSURF, &
           XCGMAX_n => XCGMAX, &
           CRUNOFF_n => CRUNOFF, &
           CTOPREG_n => CTOPREG, &
           CKSAT_n => CKSAT, &
           CHORT_n => CHORT, &
           LCANOPY_DRAG_n => LCANOPY_DRAG  

!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE
!
CHARACTER(LEN=4)  :: CC1DRY
CHARACTER(LEN=4)  :: CSCOND
CHARACTER(LEN=3)  :: CSOILFRZ
CHARACTER(LEN=4)  :: CDIFSFCOND
CHARACTER(LEN=3)  :: CSNOWRES
CHARACTER(LEN=4)  :: CALBEDO
CHARACTER(LEN=4)  :: CROUGH
CHARACTER(LEN=3)  :: CCPSURF
CHARACTER(LEN=4)  :: CRUNOFF
CHARACTER(LEN=3)  :: CTOPREG
CHARACTER(LEN=3)  :: CKSAT
CHARACTER(LEN=3)  :: CRAIN
CHARACTER(LEN=3)  :: CHORT         
REAL  :: XTSTEP
REAL  :: XOUT_TSTEP
REAL  :: XCGMAX
LOGICAL  :: LCH_BIO_FLUX
LOGICAL  :: LTRIP
LOGICAL  :: LFLOOD
LOGICAL  :: LGLACIER
LOGICAL  :: LVEGUPD
LOGICAL  :: LCANOPY_DRAG
CHARACTER(LEN=6)  :: CCH_DRY_DEP
CHARACTER(LEN=28) :: CCHEM_SURF_FILE
!
NAMELIST/NAM_ISBAn/CC1DRY,CSCOND,CSOILFRZ,CDIFSFCOND,CSNOWRES,CALBEDO,CROUGH,CCPSURF, &
                     XTSTEP,XCGMAX,LGLACIER, LCANOPY_DRAG, LVEGUPD  
NAMELIST/NAM_SGH_ISBAn/CRUNOFF,CTOPREG,CKSAT,CRAIN,CHORT,LTRIP,LFLOOD
NAMELIST/NAM_CH_CONTROLn/CCHEM_SURF_FILE
NAMELIST/NAM_CH_ISBAn/LCH_BIO_FLUX,CCH_DRY_DEP
!
CONTAINS
!
SUBROUTINE INIT_NAM_GARDENn

  REAL(KIND=JPRB) :: ZHOOK_HANDLE

  IF (LHOOK) CALL DR_HOOK('MODN_TEB_GARDEN_N:INIT_NAM_GARDENN',0,ZHOOK_HANDLE)
  CC1DRY = CC1DRY_n
  CSCOND = CSCOND_n
  CSOILFRZ = CSOILFRZ_n
  CDIFSFCOND = CDIFSFCOND_n
  CSNOWRES = CSNOWRES_n
  CALBEDO = CALBEDO_n
  CROUGH = CROUGH_n
  CCPSURF = CCPSURF_n
  XCGMAX = XCGMAX_n
  LCANOPY_DRAG = LCANOPY_DRAG_n
IF (LHOOK) CALL DR_HOOK('MODN_TEB_GARDEN_N:INIT_NAM_GARDENN',1,ZHOOK_HANDLE)
END SUBROUTINE INIT_NAM_GARDENn

SUBROUTINE UPDATE_NAM_GARDENn

  REAL(KIND=JPRB) :: ZHOOK_HANDLE

  IF (LHOOK) CALL DR_HOOK('MODN_TEB_GARDEN_N:UPDATE_NAM_GARDENN',0,ZHOOK_HANDLE)
  CC1DRY_n = CC1DRY
  CSCOND_n = CSCOND
  CSOILFRZ_n = CSOILFRZ
  CDIFSFCOND_n = CDIFSFCOND
  CSNOWRES_n = CSNOWRES
  CALBEDO_n = CALBEDO
  CROUGH_n = CROUGH
  CCPSURF_n = CCPSURF
  XCGMAX_n = XCGMAX
  LCANOPY_DRAG_n = LCANOPY_DRAG
IF (LHOOK) CALL DR_HOOK('MODN_TEB_GARDEN_N:UPDATE_NAM_GARDENN',1,ZHOOK_HANDLE)
END SUBROUTINE UPDATE_NAM_GARDENn


SUBROUTINE INIT_NAM_SGH_GARDENn

  REAL(KIND=JPRB) :: ZHOOK_HANDLE

  IF (LHOOK) CALL DR_HOOK('MODN_TEB_GARDEN_N:INIT_NAM_SGH_GARDENN',0,ZHOOK_HANDLE)
  CRUNOFF = CRUNOFF_n
  CTOPREG = CTOPREG_n
  CKSAT=CKSAT_n
  CHORT=CHORT_n
IF (LHOOK) CALL DR_HOOK('MODN_TEB_GARDEN_N:INIT_NAM_SGH_GARDENN',1,ZHOOK_HANDLE)
END SUBROUTINE INIT_NAM_SGH_GARDENn

SUBROUTINE UPDATE_NAM_SGH_GARDENn

  REAL(KIND=JPRB) :: ZHOOK_HANDLE

  IF (LHOOK) CALL DR_HOOK('MODN_TEB_GARDEN_N:UPDATE_NAM_SGH_GARDENN',0,ZHOOK_HANDLE)
  CRUNOFF_n=CRUNOFF
  CTOPREG_n=CTOPREG
  CKSAT_n=CKSAT
  CHORT_n=CHORT
IF (LHOOK) CALL DR_HOOK('MODN_TEB_GARDEN_N:UPDATE_NAM_SGH_GARDENN',1,ZHOOK_HANDLE)
END SUBROUTINE UPDATE_NAM_SGH_GARDENn

SUBROUTINE INIT_NAM_CH_CONTROLn

  REAL(KIND=JPRB) :: ZHOOK_HANDLE

  IF (LHOOK) CALL DR_HOOK('MODN_TEB_GARDEN_N:INIT_NAM_CH_CONTROLN',0,ZHOOK_HANDLE)
  CCHEM_SURF_FILE = CCHEM_SURF_FILE_n
IF (LHOOK) CALL DR_HOOK('MODN_TEB_GARDEN_N:INIT_NAM_CH_CONTROLN',1,ZHOOK_HANDLE)
END SUBROUTINE INIT_NAM_CH_CONTROLn

SUBROUTINE UPDATE_NAM_CH_CONTROLn

  REAL(KIND=JPRB) :: ZHOOK_HANDLE

  IF (LHOOK) CALL DR_HOOK('MODN_TEB_GARDEN_N:UPDATE_NAM_CH_CONTROLN',0,ZHOOK_HANDLE)
  CCHEM_SURF_FILE_n = CCHEM_SURF_FILE
IF (LHOOK) CALL DR_HOOK('MODN_TEB_GARDEN_N:UPDATE_NAM_CH_CONTROLN',1,ZHOOK_HANDLE)
END SUBROUTINE UPDATE_NAM_CH_CONTROLn

SUBROUTINE INIT_NAM_CH_GARDENn

  REAL(KIND=JPRB) :: ZHOOK_HANDLE

  IF (LHOOK) CALL DR_HOOK('MODN_TEB_GARDEN_N:INIT_NAM_CH_GARDENN',0,ZHOOK_HANDLE)
  LCH_BIO_FLUX = LCH_BIO_FLUX_n
  CCH_DRY_DEP = CCH_DRY_DEP_n
IF (LHOOK) CALL DR_HOOK('MODN_TEB_GARDEN_N:INIT_NAM_CH_GARDENN',1,ZHOOK_HANDLE)
END SUBROUTINE INIT_NAM_CH_GARDENn

SUBROUTINE UPDATE_NAM_CH_GARDENn

  REAL(KIND=JPRB) :: ZHOOK_HANDLE

  IF (LHOOK) CALL DR_HOOK('MODN_TEB_GARDEN_N:UPDATE_NAM_CH_GARDENN',0,ZHOOK_HANDLE)
  LCH_BIO_FLUX_n = LCH_BIO_FLUX
  CCH_DRY_DEP_n = CCH_DRY_DEP
IF (LHOOK) CALL DR_HOOK('MODN_TEB_GARDEN_N:UPDATE_NAM_CH_GARDENN',1,ZHOOK_HANDLE)
END SUBROUTINE UPDATE_NAM_CH_GARDENn

END MODULE MODN_TEB_GARDEN_n
