!     #########
      SUBROUTINE READ_PGD_TEB_PAR_n(HPROGRAM,KNI,HDIRIN)
!     ################################################
!
!!****  *READ_PGD_TEB_PAR_n* - reads ISBA physiographic fields
!!                        
!!
!!    PURPOSE
!!    -------
!!
!!**  METHOD
!!    ------
!!
!!    EXTERNAL
!!    --------
!!
!!
!!    IMPLICIT ARGUMENTS
!!    ------------------
!!
!!    REFERENCE
!!    ---------
!!
!!
!!    AUTHOR
!!    ------
!!	V. Masson   *Meteo France*	
!!
!!    MODIFICATIONS
!!    -------------
!!      Original    05/2005
!-------------------------------------------------------------------------------
!
!*       0.    DECLARATIONS
!              ------------
!
USE MODD_TEB_GRID_n, ONLY : NDIM
USE MODD_TEB_n,      ONLY : NROOF_LAYER, NROAD_LAYER, NWALL_LAYER,          &
                            LECOCLIMAP, LGARDEN  
USE MODD_DATA_TEB_n, ONLY : XPAR_URBTYPE, XPAR_Z0_TOWN, XPAR_BLD,           &
                              XPAR_GARDEN, XPAR_VEG_ROOF,                   &
                              XPAR_ALB_ROOF,                                &
                              XPAR_EMIS_ROOF, XPAR_HC_ROOF, XPAR_TC_ROOF,   &
                              XPAR_D_ROOF, XPAR_ALB_ROAD, XPAR_EMIS_ROAD,   &
                              XPAR_HC_ROAD, XPAR_TC_ROAD, XPAR_D_ROAD,      &
                              XPAR_ALB_WALL, XPAR_EMIS_WALL, XPAR_HC_WALL,  &
                              XPAR_TC_WALL, XPAR_D_WALL, XPAR_BLD_HEIGHT,   &
                              XPAR_WALL_O_HOR,                              &
                              XPAR_H_TRAFFIC, XPAR_LE_TRAFFIC,              &
                              XPAR_H_INDUSTRY, XPAR_LE_INDUSTRY,            &
                              LDATA_Z0_TOWN, LDATA_BLD, LDATA_ALB_ROOF,       &
                              LDATA_EMIS_ROOF, LDATA_HC_ROOF, LDATA_TC_ROOF,  &
                              LDATA_D_ROOF, LDATA_ALB_ROAD, LDATA_EMIS_ROAD,  &
                              LDATA_HC_ROAD, LDATA_TC_ROAD, LDATA_D_ROAD,     &
                              LDATA_ALB_WALL, LDATA_EMIS_WALL, LDATA_HC_WALL, &
                              LDATA_TC_WALL, LDATA_D_WALL, LDATA_BLD_HEIGHT,  &
                              LDATA_WALL_O_HOR,                             &
                              LDATA_H_TRAFFIC, LDATA_LE_TRAFFIC,           &
                              LDATA_H_INDUSTRY, LDATA_LE_INDUSTRY ,        &
                              LDATA_VEG_ROOF, LDATA_GARDEN, LDATA_URBTYPE
!
USE MODI_READ_SURF
USE MODI_GET_LUOUT
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE
!
!*       0.1   Declarations of arguments
!              -------------------------
!
CHARACTER(LEN=6),  INTENT(IN)  :: HPROGRAM ! program calling
INTEGER,           INTENT(IN)  :: KNI      ! size of the new domain
CHARACTER(LEN=1),  INTENT(IN)  :: HDIRIN
!
!*       0.2   Declarations of local variables
!              -------------------------------
!
INTEGER           :: ILUOUT         ! output listing logical unit
INTEGER           :: IRESP          ! IRESP  : return-code if a problem appears
CHARACTER(LEN=16) :: YRECFM         ! Name of the article to be read
INTEGER           :: JLAYER         ! loop index
!
INTEGER           :: IVERSION       ! surface version
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
!-------------------------------------------------------------------------------
IF (LHOOK) CALL DR_HOOK('READ_PGD_TEB_PAR_N',0,ZHOOK_HANDLE)
!
CALL GET_LUOUT(HPROGRAM,ILUOUT)
!
YRECFM='VERSION'
CALL READ_SURF(HPROGRAM,YRECFM,IVERSION,IRESP)
!
IF (IVERSION<7 .AND. .NOT.LECOCLIMAP) THEN
  !
  LDATA_URBTYPE=.FALSE.
  LDATA_Z0_TOWN=.TRUE.
  LDATA_BLD=.TRUE.
  LDATA_GARDEN=.TRUE.
  LDATA_VEG_ROOF=.TRUE.
  LDATA_ALB_ROOF=.TRUE.
  LDATA_EMIS_ROOF=.TRUE.
  LDATA_HC_ROOF=.TRUE.
  LDATA_TC_ROOF=.TRUE.
  LDATA_D_ROOF=.TRUE.
  LDATA_ALB_ROAD=.TRUE.
  LDATA_EMIS_ROAD=.TRUE.
  LDATA_HC_ROAD=.TRUE.
  LDATA_TC_ROAD=.TRUE.
  LDATA_D_ROAD=.TRUE.
  LDATA_ALB_WALL=.TRUE.
  LDATA_EMIS_WALL=.TRUE.
  LDATA_HC_WALL=.TRUE.
  LDATA_TC_WALL=.TRUE.
  LDATA_D_WALL=.TRUE.
  LDATA_BLD_HEIGHT=.TRUE.
  LDATA_WALL_O_HOR=.TRUE.
  LDATA_H_TRAFFIC=.TRUE.
  LDATA_LE_TRAFFIC=.TRUE.
  LDATA_H_INDUSTRY=.TRUE.
  LDATA_LE_INDUSTRY=.TRUE.
  !
ELSEIF (IVERSION>=7) THEN
  !
  YRECFM='L_URBTYPE'
  CALL READ_SURF(HPROGRAM,YRECFM,LDATA_URBTYPE,IRESP)
  YRECFM='L_Z0_TOWN'
  CALL READ_SURF(HPROGRAM,YRECFM,LDATA_Z0_TOWN,IRESP)
  YRECFM='L_BLD'
  CALL READ_SURF(HPROGRAM,YRECFM,LDATA_BLD,IRESP)
  IF (IVERSION>=6) THEN
    YRECFM='L_GARDEN'
    CALL READ_SURF(HPROGRAM,YRECFM,LDATA_GARDEN,IRESP)
    YRECFM='L_VEG_ROOF'
    CALL READ_SURF(HPROGRAM,YRECFM,LDATA_VEG_ROOF,IRESP)
  ENDIF
  YRECFM='L_ALB_ROOF'
  CALL READ_SURF(HPROGRAM,YRECFM,LDATA_ALB_ROOF,IRESP)
  YRECFM='L_EMIS_ROOF'
  CALL READ_SURF(HPROGRAM,YRECFM,LDATA_EMIS_ROOF,IRESP)
  YRECFM='L_HC_ROOF'
  CALL READ_SURF(HPROGRAM,YRECFM,LDATA_HC_ROOF,IRESP)
  YRECFM='L_TC_ROOF'
  CALL READ_SURF(HPROGRAM,YRECFM,LDATA_TC_ROOF,IRESP)
  YRECFM='L_D_ROOF'
  CALL READ_SURF(HPROGRAM,YRECFM,LDATA_D_ROOF,IRESP)
  YRECFM='L_ALB_ROAD'
  CALL READ_SURF(HPROGRAM,YRECFM,LDATA_ALB_ROAD,IRESP)
  YRECFM='L_EMIS_ROAD'
  CALL READ_SURF(HPROGRAM,YRECFM,LDATA_EMIS_ROAD,IRESP)
  YRECFM='L_HC_ROAD'
  CALL READ_SURF(HPROGRAM,YRECFM,LDATA_HC_ROAD,IRESP)
  YRECFM='L_TC_ROAD'
  CALL READ_SURF(HPROGRAM,YRECFM,LDATA_TC_ROAD,IRESP)
  YRECFM='L_D_ROAD'
  CALL READ_SURF(HPROGRAM,YRECFM,LDATA_D_ROAD,IRESP)
  YRECFM='L_ALB_WALL'
  CALL READ_SURF(HPROGRAM,YRECFM,LDATA_ALB_WALL,IRESP)
  YRECFM='L_EMIS_WALL'
  CALL READ_SURF(HPROGRAM,YRECFM,LDATA_EMIS_WALL,IRESP)
  YRECFM='L_HC_WALL'
  CALL READ_SURF(HPROGRAM,YRECFM,LDATA_HC_WALL,IRESP)
  YRECFM='L_TC_WALL'
  CALL READ_SURF(HPROGRAM,YRECFM,LDATA_TC_WALL,IRESP)
  YRECFM='L_D_WALL'
  CALL READ_SURF(HPROGRAM,YRECFM,LDATA_D_WALL,IRESP)
  YRECFM='L_BLD_HEIGHT'
  CALL READ_SURF(HPROGRAM,YRECFM,LDATA_BLD_HEIGHT,IRESP)
  YRECFM='L_WALL_O_HOR'
  CALL READ_SURF(HPROGRAM,YRECFM,LDATA_WALL_O_HOR,IRESP)
  YRECFM='L_H_TRAF'
  CALL READ_SURF(HPROGRAM,YRECFM,LDATA_H_TRAFFIC,IRESP)
  YRECFM='L_LE_TRAF'
  CALL READ_SURF(HPROGRAM,YRECFM,LDATA_LE_TRAFFIC,IRESP)
  YRECFM='L_H_IND'
  CALL READ_SURF(HPROGRAM,YRECFM,LDATA_H_INDUSTRY,IRESP)
  YRECFM='L_LE_IND'
  CALL READ_SURF(HPROGRAM,YRECFM,LDATA_LE_INDUSTRY,IRESP)
  !
ENDIF
!
IF (LDATA_URBTYPE) THEN
  ALLOCATE(XPAR_URBTYPE     (NDIM,1))    
  YRECFM='D_URBTYPE'
  CALL READ_FIELD(YRECFM,XPAR_URBTYPE(:,1),HDIRIN)
ENDIF
!
IF (LDATA_Z0_TOWN) THEN
  ALLOCATE(XPAR_Z0_TOWN     (NDIM))
  YRECFM='D_Z0_TOWN'
  CALL READ_FIELD(YRECFM,XPAR_Z0_TOWN,HDIRIN)
ENDIF
!
IF (LDATA_BLD) THEN
  ALLOCATE(XPAR_BLD         (NDIM))
  YRECFM='D_BLD'
  CALL READ_FIELD(YRECFM,XPAR_BLD,HDIRIN)
ENDIF
!
IF (IVERSION>=6) THEN
  IF (LDATA_GARDEN) THEN
    ALLOCATE(XPAR_GARDEN      (NDIM))
    YRECFM='D_GARDEN'
    CALL READ_FIELD(YRECFM,XPAR_GARDEN,HDIRIN)
  ENDIF
!
  IF (LDATA_VEG_ROOF) THEN
    ALLOCATE(XPAR_VEG_ROOF    (NDIM))
    YRECFM='D_VEG_ROOF'
    CALL READ_FIELD(YRECFM,XPAR_VEG_ROOF,HDIRIN)
  ENDIF
ENDIF
!
IF (LDATA_ALB_ROOF) THEN
  ALLOCATE(XPAR_ALB_ROOF    (NDIM))        
  YRECFM='D_ALB_ROOF'
  CALL READ_FIELD(YRECFM,XPAR_ALB_ROOF,HDIRIN)
ENDIF
!
IF (LDATA_EMIS_ROOF) THEN
  ALLOCATE(XPAR_EMIS_ROOF   (NDIM))        
  YRECFM='D_EMI_ROOF'
  CALL READ_FIELD(YRECFM,XPAR_EMIS_ROOF,HDIRIN)
ENDIF
!
IF (LDATA_HC_ROOF) THEN
  ALLOCATE(XPAR_HC_ROOF     (NDIM,NROOF_LAYER))
  DO JLAYER=1,NROOF_LAYER
    WRITE(YRECFM,FMT='(A9,I1.1)') 'D_HC_ROOF',JLAYER
    CALL READ_FIELD(YRECFM,XPAR_HC_ROOF(:,JLAYER),HDIRIN)
  END DO
ENDIF
!
IF (LDATA_TC_ROOF) THEN
  ALLOCATE(XPAR_TC_ROOF     (NDIM,NROOF_LAYER))
  DO JLAYER=1,NROOF_LAYER
    WRITE(YRECFM,FMT='(A9,I1.1)') 'D_TC_ROOF',JLAYER
    CALL READ_FIELD(YRECFM,XPAR_TC_ROOF(:,JLAYER),HDIRIN)
  END DO
ENDIF
!
IF (LDATA_D_ROOF) THEN
  ALLOCATE(XPAR_D_ROOF      (NDIM,NROOF_LAYER))
  DO JLAYER=1,NROOF_LAYER
    WRITE(YRECFM,FMT='(A8,I1.1)') 'D_D_ROOF',JLAYER
    CALL READ_FIELD(YRECFM,XPAR_D_ROOF(:,JLAYER),HDIRIN)
  END DO
ENDIF
!
IF (LDATA_ALB_ROAD) THEN
  ALLOCATE(XPAR_ALB_ROAD    (NDIM))
  YRECFM='D_ALB_ROAD'
  CALL READ_FIELD(YRECFM,XPAR_ALB_ROAD,HDIRIN)
ENDIF
!
IF (LDATA_EMIS_ROAD) THEN
  ALLOCATE(XPAR_EMIS_ROAD   (NDIM))
  YRECFM='D_EMI_ROAD'
  CALL READ_FIELD(YRECFM,XPAR_EMIS_ROAD,HDIRIN)
ENDIF
!
IF (LDATA_HC_ROAD) THEN
  ALLOCATE(XPAR_HC_ROAD     (NDIM,NROAD_LAYER))
  DO JLAYER=1,NROAD_LAYER
    WRITE(YRECFM,FMT='(A9,I1.1)') 'D_HC_ROAD',JLAYER
    CALL READ_FIELD(YRECFM,XPAR_HC_ROAD(:,JLAYER),HDIRIN)
  END DO
ENDIF
!
IF (LDATA_TC_ROAD) THEN
  ALLOCATE(XPAR_TC_ROAD     (NDIM,NROAD_LAYER))
  DO JLAYER=1,NROAD_LAYER
    WRITE(YRECFM,FMT='(A9,I1.1)') 'D_TC_ROAD',JLAYER
    CALL READ_FIELD(YRECFM,XPAR_TC_ROAD(:,JLAYER),HDIRIN)
  END DO
ENDIF
!
IF (LDATA_D_ROAD) THEN
  ALLOCATE(XPAR_D_ROAD      (NDIM,NROAD_LAYER))
  DO JLAYER=1,NROAD_LAYER
    WRITE(YRECFM,FMT='(A8,I1.1)') 'D_D_ROAD',JLAYER
    CALL READ_FIELD(YRECFM,XPAR_D_ROAD(:,JLAYER),HDIRIN)
  END DO
ENDIF
!
IF (LDATA_ALB_WALL) THEN
  ALLOCATE(XPAR_ALB_WALL    (NDIM))
  YRECFM='D_ALB_WALL'
  CALL READ_FIELD(YRECFM,XPAR_ALB_WALL,HDIRIN)
ENDIF
!
IF (LDATA_EMIS_WALL) THEN
  ALLOCATE(XPAR_EMIS_WALL   (NDIM))
  YRECFM='D_EMI_WALL'
  CALL READ_FIELD(YRECFM,XPAR_EMIS_WALL,HDIRIN)
ENDIF
!
IF (LDATA_HC_WALL) THEN
  ALLOCATE(XPAR_HC_WALL     (NDIM,NWALL_LAYER))
  DO JLAYER=1,NWALL_LAYER
    WRITE(YRECFM,FMT='(A9,I1.1)') 'D_HC_WALL',JLAYER
    CALL READ_FIELD(YRECFM,XPAR_HC_WALL(:,JLAYER),HDIRIN)
  END DO
ENDIF
!
IF (LDATA_TC_WALL) THEN
  ALLOCATE(XPAR_TC_WALL     (NDIM,NWALL_LAYER))
  DO JLAYER=1,NWALL_LAYER
    WRITE(YRECFM,FMT='(A9,I1.1)') 'D_TC_WALL',JLAYER
    CALL READ_FIELD(YRECFM,XPAR_TC_WALL(:,JLAYER),HDIRIN)
  END DO
ENDIF
!
IF (LDATA_D_WALL) THEN
  ALLOCATE(XPAR_D_WALL      (NDIM,NWALL_LAYER))
  DO JLAYER=1,NWALL_LAYER
    WRITE(YRECFM,FMT='(A8,I1.1)') 'D_D_WALL',JLAYER
    CALL READ_FIELD(YRECFM,XPAR_D_WALL(:,JLAYER),HDIRIN)
  END DO
ENDIF
!
IF (LDATA_BLD_HEIGHT) THEN
  ALLOCATE(XPAR_BLD_HEIGHT  (NDIM))
  YRECFM='D_BLD_HEIG'
  CALL READ_FIELD(YRECFM,XPAR_BLD_HEIGHT,HDIRIN)
ENDIF
!
IF (LDATA_WALL_O_HOR) THEN
  ALLOCATE(XPAR_WALL_O_HOR  (NDIM))
  YRECFM='D_WALL_O_H'
  CALL READ_FIELD(YRECFM,XPAR_WALL_O_HOR,HDIRIN)
ENDIF
!
IF (LDATA_H_TRAFFIC) THEN
  ALLOCATE(XPAR_H_TRAFFIC   (NDIM))
  YRECFM='D_H_TRAF'
  CALL READ_FIELD(YRECFM,XPAR_H_TRAFFIC,HDIRIN)
ENDIF
!
IF (LDATA_LE_TRAFFIC) THEN
  ALLOCATE(XPAR_LE_TRAFFIC  (NDIM))
  YRECFM='D_LE_TRAF'
  CALL READ_FIELD(YRECFM,XPAR_LE_TRAFFIC,HDIRIN)
ENDIF
!
IF (LDATA_H_INDUSTRY) THEN
  ALLOCATE(XPAR_H_INDUSTRY  (NDIM))
  YRECFM='D_H_IND'
  CALL READ_FIELD(YRECFM,XPAR_H_INDUSTRY,HDIRIN)
ENDIF
!
IF (LDATA_LE_INDUSTRY) THEN
  ALLOCATE(XPAR_LE_INDUSTRY (NDIM))
  YRECFM='D_LE_IND'
  CALL READ_FIELD(YRECFM,XPAR_LE_INDUSTRY,HDIRIN)
ENDIF
!
IF (LHOOK) CALL DR_HOOK('READ_PGD_TEB_PAR_N',1,ZHOOK_HANDLE)
!
!-------------------------------------------------------------------------------
CONTAINS
!
SUBROUTINE READ_FIELD(HRECFM,PFIELD,YDIR)
!
USE MODI_HOR_INTERPOL
!
IMPLICIT NONE
!
CHARACTER(LEN=*),     INTENT(IN)  :: HRECFM ! name of record in the file
REAL, DIMENSION(NDIM), INTENT(OUT) :: PFIELD
CHARACTER(LEN=1),     INTENT(IN)  :: YDIR
!
REAL, DIMENSION(KNI)              :: ZF
REAL, DIMENSION(:,:), POINTER     :: ZIN
REAL, DIMENSION(NDIM,1)            :: ZOUT
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
IF (LHOOK) CALL DR_HOOK('READ_PGD_TEB_PAR_N:READ_FIELD',0,ZHOOK_HANDLE)
!
IF (YDIR=='A') THEN
  !
  CALL READ_SURF(HPROGRAM,HRECFM,ZF,IRESP,HDIR='A')
  ALLOCATE(ZIN(KNI,1))
  ZIN(:,1) = ZF(:)
  CALL HOR_INTERPOL(ILUOUT,ZIN,ZOUT)
  DEALLOCATE(ZIN)
  PFIELD(:) = ZOUT(:,1)
  !
ELSE
  CALL READ_SURF(HPROGRAM,HRECFM,PFIELD,IRESP)
ENDIF
!
IF (LHOOK) CALL DR_HOOK('READ_PGD_TEB_PAR_N:READ_FIELD',1,ZHOOK_HANDLE)
!
END SUBROUTINE READ_FIELD
!_______________________________
!
END SUBROUTINE READ_PGD_TEB_PAR_n
