!     ####################################
      SUBROUTINE WRITE_SURF_ATM_n(HPROGRAM,HWRITE)
!     ####################################
!
!!****  *WRITE_SURF_ATM_n* - routine to write surface variables 
!!                           in their respective files or in file
!!
!!    PURPOSE
!!    -------
!!
!!**  METHOD
!!    ------
!!
!!    EXTERNAL
!!    --------
!!
!!
!!    IMPLICIT ARGUMENTS
!!    ------------------
!!
!!    REFERENCE
!!    ---------
!!
!!
!!    AUTHOR
!!    ------
!!	V. Masson   *Meteo France*	
!!
!!    MODIFICATIONS
!!    -------------
!!      Original    01/2003
!!      Modified    06/2007, P.LeMoigne: do not write pgd fields in
!!                                       historical files
!!      Modified    03/2009, B.Decharme: keys for arrange cover
!!      Modified    04/2009, B.Decharme: write precipitation forcing into the restart file for ARPEGE/ALADIN run
!       Modified    06/2009, B.Decharme: flag to desactivate writing of horizontal grid 
!       Modified    08/2009, B.Decharme: BUDGETC for all tiles
!-------------------------------------------------------------------------------
!
!*       0.    DECLARATIONS
!              ------------
!
USE MODD_SURF_CONF,       ONLY : CPROGNAME
USE MODD_SURF_PAR,        ONLY : NVERSION, NBUGFIX
USE MODD_WRITE_SURF_ATM,  ONLY : LNOWRITE_COVERS, LNOWRITE_CANOPY
USE MODD_SURF_ATM_GRID_n, ONLY : CGRID, XGRID_PAR, XLAT, XLON, XMESH_SIZE
USE MODD_SURF_ATM_n,      ONLY : NDIM_FULL, NDIM_SEA, NDIM_WATER, NDIM_TOWN, NDIM_NATURE, &
                                 XSEA, XTOWN, XNATURE, XWATER,                            &
                                 CSEA, CWATER, CNATURE, CTOWN, XCOVER, TTIME, LECOCLIMAP, &
                                 LWATER_TO_NATURE, LTOWN_TO_ROCK, LGARDEN
USE MODD_SURF_ATM_SSO_n,  ONLY : CROUGH, XZ0EFFJPDIR
USE MODD_DIAG_SURF_ATM_n, ONLY : TIME_BUDGETC,LSURF_BUDGETC,LPROVAR_TO_DIAG,LSELECT  
USE MODD_SV_n,            ONLY : NBEQ
USE MODD_CH_SURF_n,       ONLY : LCH_EMIS, LRW_CH_EMIS
!
USE MODI_INIT_IO_SURF_n
USE MODI_WRITE_SURF
USE MODI_WRITE_SEA_n
USE MODI_WRITE_INLAND_WATER_n
USE MODI_WRITE_NATURE_n
USE MODI_WRITE_TOWN_n
USE MODI_END_IO_SURF_n
!
USE MODI_WRITESURF_ATM_CONF_n
USE MODI_WRITESURF_COVER_n
USE MODI_WRITESURF_SSO_n
USE MODI_WRITESURF_SSO_CANOPY_n
USE MODI_WRITESURF_DUMMY_n
USE MODI_READWRITE_EMIS_FIELD_n
USE MODI_WRITESURF_CH_EMIS_n
USE MODI_WRITESURF_PRECIP_n
USE MODI_WRITE_GRID
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
USE MODI_WRITE_ECOCLIMAP2_DATA
!
IMPLICIT NONE
!
!*       0.1   Declarations of arguments
!              -------------------------
!
CHARACTER(LEN=6),    INTENT(IN)  :: HPROGRAM  ! program calling surf. schemes
CHARACTER(LEN=3),    INTENT(IN)  :: HWRITE    ! 'PGD' : only physiographic fields are written
!                                             ! 'ALL' : all fields are written
!
!*       0.2   Declarations of local variables
!              -------------------------------
!
CHARACTER(LEN=100) :: YCOMMENT
INTEGER            :: IRESP
LOGICAL            :: LSAVE_SELECT
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!-------------------------------------------------------------------------------
!
IF (LHOOK) CALL DR_HOOK('WRITE_SURF_ATM_N',0,ZHOOK_HANDLE)
CPROGNAME = HPROGRAM
!
!*       1.     Configuration and cover fields:
!               ------------------------------
!
!
!         Initialisation for IO
!
CALL INIT_IO_SURF_n(HPROGRAM,'FULL  ','SURF  ','WRITE')
!
LSAVE_SELECT=LSELECT
LSELECT     =.FALSE.
!
YCOMMENT='(-)'
CALL WRITE_SURF(HPROGRAM,'VERSION',NVERSION,IRESP,YCOMMENT)
CALL WRITE_SURF(HPROGRAM,'BUG    ',NBUGFIX ,IRESP,YCOMMENT)
CALL WRITE_SURF(HPROGRAM,'STORAGETYPE',HWRITE,IRESP,YCOMMENT)
!
CALL WRITE_SURF(HPROGRAM,'SEA   ',CSEA   ,IRESP,YCOMMENT)
CALL WRITE_SURF(HPROGRAM,'WATER ',CWATER ,IRESP,YCOMMENT)
CALL WRITE_SURF(HPROGRAM,'NATURE',CNATURE,IRESP,YCOMMENT)
CALL WRITE_SURF(HPROGRAM,'TOWN  ',CTOWN  ,IRESP,YCOMMENT)
!
CALL WRITE_SURF(HPROGRAM,'DIM_FULL  ',NDIM_FULL,  IRESP,HCOMMENT=YCOMMENT)
CALL WRITE_SURF(HPROGRAM,'DIM_SEA   ',NDIM_SEA,   IRESP,HCOMMENT=YCOMMENT)
CALL WRITE_SURF(HPROGRAM,'DIM_NATURE',NDIM_NATURE,IRESP,HCOMMENT=YCOMMENT)
CALL WRITE_SURF(HPROGRAM,'DIM_WATER ',NDIM_WATER, IRESP,HCOMMENT=YCOMMENT)
CALL WRITE_SURF(HPROGRAM,'DIM_TOWN  ',NDIM_TOWN,  IRESP,HCOMMENT=YCOMMENT)
CALL WRITE_SURF(HPROGRAM,'ECOCLIMAP ',LECOCLIMAP ,IRESP,YCOMMENT)
CALL WRITE_SURF(HPROGRAM,'WATER_TO_NAT',LWATER_TO_NATURE,IRESP,YCOMMENT)
CALL WRITE_SURF(HPROGRAM,'TOWN_TO_ROCK',LTOWN_TO_ROCK,IRESP,YCOMMENT)
CALL WRITE_SURF(HPROGRAM,'GARDEN',LGARDEN,IRESP,YCOMMENT)
IF (HPROGRAM.NE.'BINARY' .AND. HPROGRAM.NE.'TEXTE ') THEN
CALL WRITE_ECOCLIMAP2_DATA(HPROGRAM)
ENDIF
!
IF (HWRITE/='PGD') THEN
  YCOMMENT='s'
  CALL WRITE_SURF(HPROGRAM,'DTCUR',TTIME,IRESP,YCOMMENT)
END IF
!
LSELECT=LSAVE_SELECT
!
IF (LPROVAR_TO_DIAG)THEN
  CALL END_IO_SURF_n(HPROGRAM)
  IF (LHOOK) CALL DR_HOOK('WRITE_SURF_ATM_N',1,ZHOOK_HANDLE)
  RETURN
ENDIF
!
CALL WRITE_GRID(HPROGRAM,CGRID,XGRID_PAR,XLAT,XLON,XMESH_SIZE,IRESP,XZ0EFFJPDIR)
!
IF (HWRITE/='PGD') THEN
  CALL WRITESURF_ATM_CONF_n(HPROGRAM)
END IF
!
IF ((.NOT.LNOWRITE_COVERS)) THEN
  CALL WRITESURF_COVER_n(HPROGRAM)
  CALL WRITESURF_SSO_n(HPROGRAM)
  CALL WRITESURF_DUMMY_n(HPROGRAM)
END IF
!
CALL WRITESURF_SSO_CANOPY_n(HPROGRAM,(CROUGH=='BE04' .AND. .NOT. LNOWRITE_CANOPY))
!
CALL WRITESURF_PRECIP_n(HPROGRAM)
!
YCOMMENT='CH_EMIS'
CALL WRITE_SURF(HPROGRAM,'CH_EMIS',LCH_EMIS,IRESP,HCOMMENT=YCOMMENT)
!
IF (HWRITE/='PGD') THEN
!
  YCOMMENT='flag for accumulated variables'
  CALL WRITE_SURF(HPROGRAM,'BUDC',LSURF_BUDGETC,IRESP,HCOMMENT=YCOMMENT)
!
  IF (LSURF_BUDGETC) THEN
     YCOMMENT='time of beginning of accumulation'
     CALL WRITE_SURF(HPROGRAM,'TIME_BUDC',TIME_BUDGETC,IRESP,HCOMMENT=YCOMMENT)   
  END IF
!
END IF
!  
!         End of IO
!
CALL END_IO_SURF_n(HPROGRAM)
!
IF (LCH_EMIS .AND.       LRW_CH_EMIS) CALL READWRITE_EMIS_FIELD_n(HPROGRAM)
IF (LCH_EMIS .AND. .NOT. LRW_CH_EMIS) THEN
  CALL INIT_IO_SURF_n(HPROGRAM,'FULL  ','SURF  ','WRITE')
  CALL WRITESURF_CH_EMIS_n(HPROGRAM)
  CALL END_IO_SURF_n(HPROGRAM)
END IF
!
!
!*       2.     Sea
!               ---
!
IF (NDIM_SEA>0) CALL WRITE_SEA_n(HPROGRAM,HWRITE)
!
!
!*       3.     Inland water
!               ------------
!
IF (NDIM_WATER>0) CALL WRITE_INLAND_WATER_n(HPROGRAM,HWRITE)
!
!
!*       4.     Vegetation scheme
!               -----------------
!
IF (NDIM_NATURE>0) CALL WRITE_NATURE_n(HPROGRAM,HWRITE)
!
!
!*       5.     Urban scheme
!               ------------
!
IF (NDIM_TOWN>0) CALL WRITE_TOWN_n(HPROGRAM,HWRITE)
IF (LHOOK) CALL DR_HOOK('WRITE_SURF_ATM_N',1,ZHOOK_HANDLE)
!
!-------------------------------------------------------------------------------
!
END SUBROUTINE WRITE_SURF_ATM_n
