SUBROUTINE GET_FILE_NAME(KYEAR,KMONTH,KDAY,KHOUR,HMFILE)
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE
!
INTEGER, INTENT (IN) :: KYEAR, KMONTH, KDAY, KHOUR
 CHARACTER(LEN=50) :: YMONTH,YDAY,YYEAR,YHOUR
 CHARACTER(LEN=200), INTENT(INOUT) :: HMFILE
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
IF (LHOOK) CALL DR_HOOK('GET_FILE_NAME',0,ZHOOK_HANDLE)
!
 CALL TRANS_CHAINE(YMONTH,KMONTH,2)
 CALL TRANS_CHAINE(YDAY,KDAY,2)
 CALL TRANS_CHAINE(YYEAR,KYEAR,4)
 CALL TRANS_CHAINE(YHOUR,KHOUR,2)
IF (KHOUR.EQ.0 .OR. KHOUR.EQ.24 .OR. KHOUR.EQ.48) YHOUR='00'
!
HMFILE = TRIM(HMFILE)//YYEAR(3:4)
HMFILE = TRIM(HMFILE)//YMONTH
HMFILE = TRIM(HMFILE)//YDAY
HMFILE = TRIM(HMFILE)//'H'
HMFILE = TRIM(HMFILE)//YHOUR
HMFILE = TRIM(HMFILE)//'.DAT'
!
IF (LHOOK) CALL DR_HOOK('GET_FILE_NAME',1,ZHOOK_HANDLE)
!
CONTAINS
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
SUBROUTINE TRANS_CHAINE(HCHAINE,KENTIER,KOPTION)
!----------------------------------------------------------
!
! transforme l'entier 23416 en la chaine de caracteres '23416' 
! option est utilise si superieur a 0. Dans ce cas si l'entier
! a un nombre de digits inferieur a option, la difference est
! remplie avec des '0' dans chaine.
!
!
! ex: entier=256 option=0  ===>   chaine='256'
!     entier=256 option=2  ===>   chaine='256'
!     entier=256 option=7  ===>   chaine='0000256'
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE
!
 CHARACTER(LEN=*), INTENT(OUT) :: HCHAINE
INTEGER, INTENT(IN) :: KENTIER, KOPTION
!
CHARACTER :: YC
INTEGER :: IDIVI
INTEGER :: IRESTE, INBDIGIT, INUM
INTEGER:: I, J
!
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
IF (LHOOK) CALL DR_HOOK('GET_FILE_NAME:TRANS_CHAINE',0,ZHOOK_HANDLE)
!
HCHAINE = ''
!
IRESTE   = KENTIER
INBDIGIT = INT( LOG(KENTIER*1.)/LOG(10.)+0.001 ) + 1
!
IDIVI = 10**(INBDIGIT-1)
!
IF ( KOPTION.GT.MAX(0,INBDIGIT) ) THEN
  !
  DO I = 1, KOPTION-INBDIGIT
    HCHAINE(I:I) = '0'
  END DO
  !     
ENDIF
!
DO I = 1,INBDIGIT
!
  INUM = INT(IRESTE*1./IDIVI)
  YC = CHAR(INUM+48)
  IF (KOPTION.GT.0) THEN
    J = KOPTION-INBDIGIT+I
  ELSEIF (KOPTION.EQ.0) THEN
    J = I
  ENDIF
  HCHAINE(J:J) = YC
  IRESTE = IRESTE - INUM*IDIVI
  IDIVI = IDIVI/10
!
END DO
!
IF (LHOOK) CALL DR_HOOK('GET_FILE_NAME:TRANS_CHAINE',1,ZHOOK_HANDLE)
      !---------------
END SUBROUTINE TRANS_CHAINE
!
END SUBROUTINE GET_FILE_NAME

