SUBROUTINE GET_IOK_ASSIM(HREC,KOK)
!
USE MODD_ASSIM, ONLY : CVAR, COBS, CBIO
!
USE YOMHOOK ,ONLY : LHOOK, DR_HOOK
USE PARKIND1 ,ONLY : JPRB
!
IMPLICIT NONE
!
CHARACTER(LEN=16), INTENT(IN) :: HREC
INTEGER, INTENT(OUT) :: KOK
!
INTEGER :: ILEN
INTEGER :: J
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
IF (LHOOK) CALL DR_HOOK('GET_IOK_ASSIM',0,ZHOOK_HANDLE)
!
KOK = 0
!
DO J = 1,SIZE(CVAR)
  ILEN = LEN_TRIM(CVAR(J))
  IF (TRIM(HREC(1:ILEN))==TRIM(CVAR(J))) THEN
    KOK = 1
    EXIT
  ENDIF
ENDDO
!
IF (KOK==0) THEN
  DO J = 1,SIZE(COBS)   
    ILEN = LEN_TRIM(COBS(J)) 
    IF (TRIM(HREC(1:ILEN))==TRIM(COBS(J))) THEN
      KOK = 1
      EXIT
    ENDIF
  ENDDO
ENDIF
!
IF (KOK==0) THEN
  ILEN = LEN_TRIM(CBIO)
  IF (TRIM(HREC(1:ILEN))==TRIM(CBIO)) KOK=1
ENDIF
!
IF (KOK==0) THEN
  IF (HREC(1:4)=="WGI1") KOK=1
ENDIF
!
IF (LHOOK) CALL DR_HOOK('GET_IOK_ASSIM',1,ZHOOK_HANDLE)
!
END SUBROUTINE GET_IOK_ASSIM
