MODULE MODE_EKF
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
INTERFACE GET_FILE_NAME
  MODULE PROCEDURE GET_FILE_NAME
END INTERFACE
INTERFACE TRANS_CHAINE
  MODULE PROCEDURE TRANS_CHAINE
END INTERFACE
INTERFACE B_BIG_LOOP
  MODULE PROCEDURE B_BIG_LOOP
END INTERFACE
INTERFACE INVERSE_MATRIX
  MODULE PROCEDURE INVERSE_MATRIX
END INTERFACE
INTERFACE CHOLDC
  MODULE PROCEDURE CHOLDC
END INTERFACE
INTERFACE CHOLSL
  MODULE PROCEDURE CHOLSL
END INTERFACE
!
CONTAINS
!
SUBROUTINE GET_FILE_NAME(KYEAR,KMONTH,KDAY,KHOUR,HMFILE)
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE
!
INTEGER, INTENT (IN) :: KYEAR, KMONTH, KDAY, KHOUR
 CHARACTER(LEN=50) :: YMONTH,YDAY,YYEAR,YHOUR
 CHARACTER(LEN=200), INTENT(INOUT) :: HMFILE
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
IF (LHOOK) CALL DR_HOOK('MODE_EKF:GET_FILE_NAME',0,ZHOOK_HANDLE)
!
 CALL TRANS_CHAINE(YMONTH,KMONTH,2)
 CALL TRANS_CHAINE(YDAY,KDAY,2)
 CALL TRANS_CHAINE(YYEAR,KYEAR,4)
 CALL TRANS_CHAINE(YHOUR,KHOUR,2)
IF (KHOUR.EQ.0 .OR. KHOUR.EQ.24 .OR. KHOUR.EQ.48) YHOUR='00'
!
HMFILE = TRIM(HMFILE)//YYEAR(3:4)
HMFILE = TRIM(HMFILE)//YMONTH
HMFILE = TRIM(HMFILE)//YDAY
HMFILE = TRIM(HMFILE)//'H'
HMFILE = TRIM(HMFILE)//YHOUR
HMFILE = TRIM(HMFILE)
!
IF (LHOOK) CALL DR_HOOK('MODE_EKF:GET_FILE_NAME',1,ZHOOK_HANDLE)
!
END SUBROUTINE GET_FILE_NAME
!
!
SUBROUTINE TRANS_CHAINE(HCHAINE,KENTIER,KOPTION)
!----------------------------------------------------------
!
! transforme l'entier 23416 en la chaine de caracteres '23416' 
! option est utilise si superieur a 0. Dans ce cas si l'entier
! a un nombre de digits inferieur a option, la difference est
! remplie avec des '0' dans chaine.
!
!
! ex: entier=256 option=0  ===>   chaine='256'
!     entier=256 option=2  ===>   chaine='256'
!     entier=256 option=7  ===>   chaine='0000256'
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE
!
 CHARACTER(LEN=*), INTENT(OUT) :: HCHAINE
INTEGER, INTENT(IN) :: KENTIER, KOPTION
!
CHARACTER :: YC
INTEGER :: IDIVI
INTEGER :: IRESTE, INBDIGIT, INUM
INTEGER:: I, J
!
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
IF (LHOOK) CALL DR_HOOK('MODE_EKF:TRANS_CHAINE',0,ZHOOK_HANDLE)
!
HCHAINE = ''
!
IRESTE   = KENTIER
INBDIGIT = INT( LOG(KENTIER*1.)/LOG(10.)+0.001 ) + 1
!
IDIVI = 10**(INBDIGIT-1)
!
IF ( KOPTION.GT.MAX(0,INBDIGIT) ) THEN
  !
  DO I = 1, KOPTION-INBDIGIT
    HCHAINE(I:I) = '0'
  END DO
  !     
ENDIF
!
DO I = 1,INBDIGIT
!
  INUM = INT(IRESTE*1./IDIVI)
  YC = CHAR(INUM+48)
  IF (KOPTION.GT.0) THEN
    J = KOPTION-INBDIGIT+I
  ELSEIF (KOPTION.EQ.0) THEN
    J = I
  ENDIF
  HCHAINE(J:J) = YC
  IRESTE = IRESTE - INUM*IDIVI
  IDIVI = IDIVI/10
!
END DO
!
IF (LHOOK) CALL DR_HOOK('MODE_EKF:TRANS_CHAINE',1,ZHOOK_HANDLE)
!---------------
END SUBROUTINE TRANS_CHAINE
!
!
SUBROUTINE B_BIG_LOOP(HACTION,HFILE,PTAB,PTAB_IN)
!
CHARACTER(LEN=4), INTENT(IN) :: HACTION
CHARACTER(LEN=*), INTENT(IN) :: HFILE
REAL, DIMENSION(:,:,:), INTENT(INOUT) :: PTAB
REAL, DIMENSION(:), INTENT(IN), OPTIONAL :: PTAB_IN
INTEGER :: I,J,K,L,JJ,L1,K1
!
IF (HACTION=="READ" .OR. HACTION=="WRIT") THEN
  OPEN (UNIT=111,FILE=HFILE,STATUS='unknown',IOSTAT=ISTAT)
ELSE
  ICPT = 0
ENDIF
!
DO L = 1,NVAR   ! control variable (x at previous time step)
  DO K = 1,NVAR
    DO I = 1,KI
      DO J = 1,NPATCH   
        DO JJ = 1,NPATCH
          !
          L1 = J+NPATCH*(L-1)
          K1 = JJ+NPATCH*(K-1)
          !
          IF ( HACTION=="READ" ) THEN
            READ (111,*) PTAB(I,L1,K1)
          ELSEIF ( HACTION=="WRIT" ) THEN
            WRITE(111,*) PTAB(I,L1,K1)
          ELSE
            ICPT = ICPT+1
            PTAB(I,L1,K1) = PTAB_IN(ICPT)
          ENDIF
          ! 
        ENDDO
      ENDDO
    ENDDO
  ENDDO
ENDDO
!
IF (HACTION=="READ" .OR. HACTION=="WRIT") CLOSE(111)
!
END SUBROUTINE B_BIG_LOOP

SUBROUTINE INVERSE_MATRIX(KN,PA,PP)
!--------------------------------------------------------
!
! Explicit inversed matrix after Cholesky decomposition
!
!--------------------------------------------------------
IMPLICIT NONE
INTEGER, INTENT(IN) :: KN
REAL, DIMENSION (KN,KN), INTENT(INOUT) :: PA
REAL, DIMENSION (KN),    INTENT(IN)    :: PP
REAL :: ZSUM
INTEGER :: I, J, K
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
IF (LHOOK) CALL DR_HOOK('MODE_EKF:INVERSE_MATRIX',0,ZHOOK_HANDLE)
!
DO I = 1,KN
  PA(I,I)=1./PP(I)
  DO J = I+1,KN
    ZSUM = 0.
    DO K = I,J-1
      ZSUM = ZSUM - PA(J,K)*PA(K,I)
    ENDDO
    PA(J,I) = ZSUM/PP(J)
  ENDDO
ENDDO  
!
DO I = 1,KN
  DO J = I+1,KN
    PA(I,J) = 0.0
  ENDDO
ENDDO
!
PA = MATMUL(TRANSPOSE(PA),PA)
!
IF (LHOOK) CALL DR_HOOK('MODE_EKF:INVERSE_MATRIX',1,ZHOOK_HANDLE)
!
END SUBROUTINE INVERSE_MATRIX

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

SUBROUTINE CHOLDC(KN,PA,PP)
IMPLICIT NONE
INTEGER, INTENT(IN) :: KN
REAL, DIMENSION(KN,KN), INTENT(INOUT) :: PA
REAL, DIMENSION(KN), INTENT(OUT) :: PP
INTEGER :: I
REAL :: ZSUM
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
IF (LHOOK) CALL DR_HOOK('MODE_EKF:CHOLDC',0,ZHOOK_HANDLE)
!
DO I = 1,KN
  ZSUM = PA(I,I)- DOT_PRODUCT(PA(I,1:I-1),PA(I,1:I-1))
  IF ( ZSUM<=0.0 ) CALL ABOR1_SFX('MODE_EKF: ERROR IN CHOLDC')
  PP(I) = SQRT(ZSUM) 
  PA(I+1:KN,I) = ( PA(I,I+1:KN) - MATMUL(PA(I+1:KN,1:I-1),PA(I,1:I-1)) )/PP(I)
ENDDO
!
IF (LHOOK) CALL DR_HOOK('MODE_EKF:CHOLDC',1,ZHOOK_HANDLE)
!
END SUBROUTINE CHOLDC 

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

SUBROUTINE CHOLSL(KN,PA,PP,PB,PX)
IMPLICIT NONE
INTEGER, INTENT(IN) :: KN
REAL, DIMENSION (KN,KN), INTENT(IN) :: PA
REAL, DIMENSION (KN), INTENT(IN)    :: PP,PB
REAL, DIMENSION (KN), INTENT(INOUT) :: PX
INTEGER :: I
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
IF (LHOOK) CALL DR_HOOK('ASSIM_NATURE_ISBA_EKF:CHOLSL',0,ZHOOK_HANDLE)
!
DO I = 1,KN
  PX(I) = (PB(I) - DOT_PRODUCT(PA(I,1:I-1),PX(1:I-1)))/PP(I)
ENDDO
DO I = KN,1,-1
  PX(I) = (PX(I) - DOT_PRODUCT(PA(I+1:KN,I),PX(I+1:KN)))/PP(I)
ENDDO
!
IF (LHOOK) CALL DR_HOOK('ASSIM_NATURE_ISBA_EKF:CHOLSL',1,ZHOOK_HANDLE)
!
END SUBROUTINE CHOLSL
!
END MODULE MODE_EKF

