MODULE MODE_EKF
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
INTERFACE GET_FILE_NAME
  MODULE PROCEDURE GET_FILE_NAME
END INTERFACE
INTERFACE B_BIG_LOOP
  MODULE PROCEDURE B_BIG_LOOP
END INTERFACE
INTERFACE INVERSE_MATRIX
  MODULE PROCEDURE INVERSE_MATRIX
END INTERFACE
INTERFACE CHOLDC
  MODULE PROCEDURE CHOLDC
END INTERFACE
INTERFACE CHOLSL
  MODULE PROCEDURE CHOLSL
END INTERFACE
!
CONTAINS
!
SUBROUTINE GET_FILE_NAME(KYEAR,KMONTH,KDAY,KHOUR,HMFILE)
!
USE MODI_TRANS_CHAINE
!
IMPLICIT NONE
!
INTEGER, INTENT (IN) :: KYEAR, KMONTH, KDAY, KHOUR
 CHARACTER(LEN=50) :: YMONTH,YDAY,YYEAR,YHOUR
 CHARACTER(LEN=200), INTENT(INOUT) :: HMFILE
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
IF (LHOOK) CALL DR_HOOK('MODE_EKF:GET_FILE_NAME',0,ZHOOK_HANDLE)
!
 CALL TRANS_CHAINE(YMONTH,KMONTH,2)
 CALL TRANS_CHAINE(YDAY,KDAY,2)
 CALL TRANS_CHAINE(YYEAR,KYEAR,4)
 CALL TRANS_CHAINE(YHOUR,KHOUR,2)
IF (KHOUR.EQ.0 .OR. KHOUR.EQ.24 .OR. KHOUR.EQ.48) YHOUR='00'
!
HMFILE = TRIM(HMFILE)//YYEAR(3:4)
HMFILE = TRIM(HMFILE)//YMONTH
HMFILE = TRIM(HMFILE)//YDAY
HMFILE = TRIM(HMFILE)//'H'
HMFILE = TRIM(HMFILE)//YHOUR
HMFILE = TRIM(HMFILE)
!
IF (LHOOK) CALL DR_HOOK('MODE_EKF:GET_FILE_NAME',1,ZHOOK_HANDLE)
!
END SUBROUTINE GET_FILE_NAME
!
!
SUBROUTINE B_BIG_LOOP(HACTION,HFILE,PTAB,PTAB_IN)
!
USE MODD_ASSIM, ONLY : NVAR
USE MODD_ISBA_n, ONLY : I => ISBA
!
IMPLICIT NONE
!
CHARACTER(LEN=4), INTENT(IN) :: HACTION
CHARACTER(LEN=*), INTENT(IN) :: HFILE
REAL, DIMENSION(:,:,:), INTENT(INOUT) :: PTAB
REAL, DIMENSION(:), INTENT(IN), OPTIONAL :: PTAB_IN
INTEGER :: JI,JJ,JK,JL,JJJ,L1,K1
INTEGER :: IKI
!RJ: missing declarations
INTEGER :: ICPT,ISTAT
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
IF (LHOOK) CALL DR_HOOK('MODE_EKF:B_BIG_LOOP',0,ZHOOK_HANDLE)
!
IF (HACTION=="READ" .OR. HACTION=="WRIT") THEN
  OPEN (UNIT=111,FILE=HFILE,STATUS='unknown',IOSTAT=ISTAT)
ELSE
  ICPT = 0
ENDIF
!
IKI = SIZE(PTAB,1)
!
DO JL = 1,NVAR   ! control variable (x at previous time step)
  DO JK = 1,NVAR
    DO JI = 1,IKI
      DO JJ = 1,I%NPATCH   
        DO JJJ = 1,I%NPATCH
          !
          L1 = JJ+I%NPATCH*(JL-1)
          K1 = JJJ+I%NPATCH*(JK-1)
          !
          IF ( HACTION=="READ" ) THEN
            READ (111,*) PTAB(JI,L1,K1)
          ELSEIF ( HACTION=="WRIT" ) THEN
            WRITE(111,*) PTAB(JI,L1,K1)
          ELSE
            ICPT = ICPT+1
            PTAB(JI,L1,K1) = PTAB_IN(ICPT)
          ENDIF
          ! 
        ENDDO
      ENDDO
    ENDDO
  ENDDO
ENDDO
!
IF (HACTION=="READ" .OR. HACTION=="WRIT") CLOSE(111)
!
IF (LHOOK) CALL DR_HOOK('MODE_EKF:B_BIG_LOOP',1,ZHOOK_HANDLE)
!
END SUBROUTINE B_BIG_LOOP

SUBROUTINE INVERSE_MATRIX(KN,PA,PP)
!--------------------------------------------------------
!
! Explicit inversed matrix after Cholesky decomposition
!
!--------------------------------------------------------
!
IMPLICIT NONE
!
INTEGER, INTENT(IN) :: KN
REAL, DIMENSION (KN,KN), INTENT(INOUT) :: PA
REAL, DIMENSION (KN),    INTENT(IN)    :: PP
REAL :: ZSUM
INTEGER :: JI, JJ, JK
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
IF (LHOOK) CALL DR_HOOK('MODE_EKF:INVERSE_MATRIX',0,ZHOOK_HANDLE)
!
DO JI = 1,KN
  PA(JI,JI)=1./PP(JI)
  DO JJ = JI+1,KN
    ZSUM = 0.
    DO JK = JI,JJ-1
      ZSUM = ZSUM - PA(JJ,JK)*PA(JK,JI)
    ENDDO
    PA(JJ,JI) = ZSUM/PP(JJ)
  ENDDO
ENDDO  
!
DO JI = 1,KN
  DO JJ = JI+1,KN
    PA(JI,JJ) = 0.0
  ENDDO
ENDDO
!
PA = MATMUL(TRANSPOSE(PA),PA)
!
IF (LHOOK) CALL DR_HOOK('MODE_EKF:INVERSE_MATRIX',1,ZHOOK_HANDLE)
!
END SUBROUTINE INVERSE_MATRIX

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

SUBROUTINE CHOLDC(KN,PA,PP)
!
USE MODI_ABOR1_SFX        
!
IMPLICIT NONE
!
INTEGER, INTENT(IN) :: KN
REAL, DIMENSION(KN,KN), INTENT(INOUT) :: PA
REAL, DIMENSION(KN), INTENT(OUT) :: PP
INTEGER :: JI
REAL :: ZSUM
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
IF (LHOOK) CALL DR_HOOK('MODE_EKF:CHOLDC',0,ZHOOK_HANDLE)
!
DO JI = 1,KN
  ZSUM = PA(JI,JI)- DOT_PRODUCT(PA(JI,1:JI-1),PA(JI,1:JI-1))
  IF ( ZSUM<=0.0 ) CALL ABOR1_SFX('MODE_EKF: ERROR IN CHOLDC')
  PP(JI) = SQRT(ZSUM) 
  PA(JI+1:KN,JI) = ( PA(JI,JI+1:KN) - MATMUL(PA(JI+1:KN,1:JI-1),PA(JI,1:JI-1)) )/PP(JI)
ENDDO
!
IF (LHOOK) CALL DR_HOOK('MODE_EKF:CHOLDC',1,ZHOOK_HANDLE)
!
END SUBROUTINE CHOLDC 

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

SUBROUTINE CHOLSL(KN,PA,PP,PB,PX)
!
IMPLICIT NONE
!
INTEGER, INTENT(IN) :: KN
REAL, DIMENSION (KN,KN), INTENT(IN) :: PA
REAL, DIMENSION (KN), INTENT(IN)    :: PP,PB
REAL, DIMENSION (KN), INTENT(INOUT) :: PX
INTEGER :: JI
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
IF (LHOOK) CALL DR_HOOK('MODE_EKF:CHOLSL',0,ZHOOK_HANDLE)
!
DO JI = 1,KN
  PX(JI) = (PB(JI) - DOT_PRODUCT(PA(JI,1:JI-1),PX(1:JI-1)))/PP(JI)
ENDDO
DO JI = KN,1,-1
  PX(JI) = (PX(JI) - DOT_PRODUCT(PA(JI+1:KN,JI),PX(JI+1:KN)))/PP(JI)
ENDDO
!
IF (LHOOK) CALL DR_HOOK('MODE_EKF:CHOLSL',1,ZHOOK_HANDLE)
!
END SUBROUTINE CHOLSL
!
END MODULE MODE_EKF

