!     ##################
      MODULE MODN_ASSIM
!     ##################
!
!!****  *MODN_ASSIM - declaration of keys for ISBA assimilation scheme (2DVAR, Bouyssel et al.)
!!
!!    PURPOSE
!!    -------
!
!!
!!**  IMPLICIT ARGUMENTS
!!    ------------------
!!      None 
!!
!!    REFERENCE
!!    ---------
!!
!!    AUTHOR
!!    ------
!!      L. Jarlan   *Meteo France*
!!
!!    MODIFICATIONS
!!    -------------
!!      Original       23/02/05
!!      Merge assimilation   T. Aspelien met.no (04/2012)
!
!*       0.   DECLARATIONS
!             ------------
!
USE MODD_ASSIM, ONLY:  LASSIM,CASSIM,CASSIM_ISBA,NPRINTLEV,LAROME,LECSST,LAESST,LAESNM,LWATERTG2, &
                       LALADSURF,LREAD_SST_FROM_FILE,LEXTRAP_SEA,LEXTRAP_WATER,LEXTRAP_NATURE,    &
                       NECHGU,XRCLIMCA,XRCLISST,XSIGH2MO,XSIGT2MO,XSIGWGO,XSIGWGB,XSIGW2B,        &
                       LOBSWG,LOBS2M,LIMVEG,XSPRECIP2,XRTHR_QC,XSIGWGO_MAX,XRSCAL_JAC,CBIO,       &
                       LPRT,LBEV,LBFIXED,NOBSTYPE,XERROBS_M,NNCO,NIVAR,NVAR,CVAR_M,LSIM,          &
                       XSIGMA_M,XTPRT_M,NNCV,XSCALE_Q,XSCALE_QLAI,XALPH,LOBSFILE,NBOUTPUT,        &
                       CPREFIX_M,CPREFIX_BIO
!
IMPLICIT NONE
!
NAMELIST/NAM_ASSIM/LASSIM,CASSIM,CASSIM_ISBA,NPRINTLEV,LAROME,LECSST,LAESST,LAESNM,LALADSURF, &
                   LREAD_SST_FROM_FILE,LEXTRAP_SEA,LEXTRAP_WATER,LEXTRAP_NATURE,LWATERTG2, &
                   NBOUTPUT
NAMELIST/NAM_NACVEG/NECHGU,XRCLIMCA,XRCLISST,XSIGH2MO,XSIGT2MO,XSIGWGO,XSIGWGB,XSIGW2B,  &
                    LOBSWG,LOBS2M,LIMVEG,XSPRECIP2,XRTHR_QC,XSIGWGO_MAX,XRSCAL_JAC
NAMELIST/NAM_IO_VARASSIM/LPRT, LSIM, LBEV, LBFIXED
NAMELIST/NAM_OBS/NOBSTYPE, LOBSFILE, XERROBS_M, NNCO
NAMELIST/NAM_VAR/NIVAR, NVAR, CVAR_M, CPREFIX_M, XSIGMA_M, XTPRT_M, NNCV, XSCALE_Q, XSCALE_QLAI, CBIO, CPREFIX_BIO, XALPH
!
END MODULE MODN_ASSIM
