! *****************************************************************************************
SUBROUTINE SODA_CONTROL(     &
 & ODINLINE,                 &
 & P__SURFTEMPERATURE,       &
 & P__SURFPREC_EAU_CON,      &
 & P__SURFPREC_EAU_GEC,      &
 & P__SURFPREC_NEI_CON,      &
 & P__SURFPREC_NEI_GEC,      &
 & P__ATMONEBUL_BASSE,       &
 & P__SURFXEVAPOTRANSP,      &
 & P__SURFFLU_LAT_MEVA,      &
 & P__SURFACCPLUIE,          &
 & P__SURFACCNEIGE,          &
 & P__SURFACCGRAUPEL,        &
 & P__CLSTEMPERATURE,        &
 & P__CLSHUMI_RELATIVE,      &
 & P__CLSVENT_ZONAL,         &
 & P__CLSVENT_MERIDIEN,      &
 & P__SURFIND_TERREMER,      &
 & P__SURFRESERV_NEIGE,      &
 & P__LON,                   &
 & P__LAT,                   &
 & OD_MASKEXT)
! ******************************************************************************************
! ------------------------------------------------------------------------------------------
!!
!!    SODA: SURFEX Offline Data Assimilation
!!
!!    PURPOSE
!!    -------
!!    Program to perform surface data within SURFEX 
!!
!!
!!    METHOD
!!    ------
!!    Different methods for different tiles
!!
!!    EXTERNAL
!!    --------
!!
!!    IMPLICIT ARGUMENTS
!!    ------------------
!!
!!    REFERENCE
!!    ---------
!!
!!    AUTHOR
!!    ------
!!
!!    T. Aspelien                  met.no
!!
!!    MODIFICATION
!!    ------------
!!
!!    Original         04/2012
!!
!! 03/2014 E. Martin change indices names in OMP module according to GMAP changes
!----------------------------------------------------------------------------
!
USE MODD_SURFEX_MPI, ONLY : NRANK, NPIO
USE MODD_SURFEX_OMP, ONLY : NINDX2SFX, NWORK, XWORK, XWORK2, XWORK3, &
                            NWORK_FULL, XWORK_FULL, XWORK2_FULL
!
USE MODD_TYPE_DATE_SURF, ONLY : DATE_TIME
!
USE MODD_SURF_CONF, ONLY : CSOFTWARE
USE MODD_SURF_PAR,  ONLY : XUNDEF,NUNDEF
!
USE MODD_SURF_ATM_n, ONLY : NSIZE_NATURE, NSIZE_FULL
USE MODD_ISBA_n,     ONLY : NPATCH, XWG, XTG
!
USE MODD_ASSIM, ONLY : LASSIM, LAROME, LALADSURF, CASSIM_ISBA, LREAD_SST_FROM_FILE,  &
                       NVAR, XF, XF_PATCH, NOBSTYPE, XAT2M_ISBA,                     &
                       XAHU2M_ISBA, CVAR, COBS
!
USE MODD_FORC_ATM,       ONLY : CSV, XDIR_ALB, XSCA_ALB, XEMIS, XTSRAD, XTSUN, XZS, &
                                XZREF, XUREF, XTA, XQA, XSV, XU, XV, XSW_BANDS,     &
                                XZENITH, XAZIM, XCO2, XRHOA 
!
#ifdef ARO 
USE MODD_IO_SURF_ARO,ONLY : NGPTOT, NGPTOT_CAP, NPROMA, NINDX1, NINDX2, NBLOCK, NKPROMA
#endif
!
#ifdef NC
USE MODD_IO_SURF_NC,   ONLY : CFILEIN_NC, CFILEIN_NC_SAVE, CFILEPGD_NC, CFILEOUT_NC, LDEF, &
                              CLUOUT_NC
#endif
#ifdef ASC
USE MODD_IO_SURF_ASC,  ONLY : CFILEIN, CFILEIN_SAVE, CFILEPGD, CFILEOUT
#endif
#ifdef FA
USE MODD_IO_SURF_FA,   ONLY : CFILEIN_FA, CFILEIN_FA_SAVE, CFILEPGD_FA, CDNOMC, CFILEOUT_FA, &
                              NUNIT_FA, IVERBFA, LFANOCOMPACT
#endif
#ifdef LFI
USE MODD_IO_SURF_LFI,    ONLY : CFILEIN_LFI,CFILEIN_LFI_SAVE,&
       CFILEPGD_LFI,CFILE_LFI,CLUOUT_LFI,CFILEOUT_LFI 
#endif
!
USE MODN_IO_OFFLINE,     ONLY : NAM_IO_OFFLINE, CNAMELIST, CPGDFILE, CPREPFILE, CSURFFILE, &
                                CSURF_FILETYPE, CTIMESERIES_FILETYPE, LLAND_USE,           &
                                LDIAG_FA_NOCOMPACT, LOUT_TIMENAME
!
USE MODE_POS_SURF,  ONLY : POSNAM
!
USE MODI_ABOR1_SFX
USE MODI_ALLOC_SURFEX
USE MODI_DEALLOC_SURFEX
USE MODI_GOTO_SURFEX
USE MODI_GET_LUOUT
USE MODI_OPEN_NAMELIST
USE MODI_CLOSE_NAMELIST
USE MODI_READ_ALL_NAMELISTS
USE MODI_INIT_IO_SURF_n
USE MODI_END_IO_SURF_n
USE MODI_READ_SURF
USE MODI_IO_BUFF_CLEAN_n
USE MODI_GET_SIZE_FULL_n
USE MODI_INIT_SURF_ATM_n
USE MODI_ASSIM_SURF_ATM_n
USE MODI_WRITE_SURF_ATM_n
USE MODI_WRITE_DIAG_SURF_ATM_n
USE MODI_ASSIM_READ_SST_FROM_FILE
!
#ifdef OFF
USE MODI_FANDAR
#endif
!
USE YOMHOOK,             ONLY : LHOOK,DR_HOOK
USE PARKIND1,            ONLY : JPRB
!
IMPLICIT NONE
!
LOGICAL, INTENT (IN) :: ODINLINE
REAL(KIND=JPRB), OPTIONAL, DIMENSION (:) ::  P__SURFTEMPERATURE
REAL(KIND=JPRB), OPTIONAL, DIMENSION (:) ::  P__SURFPREC_EAU_CON
REAL(KIND=JPRB), OPTIONAL, DIMENSION (:) ::  P__SURFPREC_EAU_GEC
REAL(KIND=JPRB), OPTIONAL, DIMENSION (:) ::  P__SURFPREC_NEI_CON
REAL(KIND=JPRB), OPTIONAL, DIMENSION (:) ::  P__SURFPREC_NEI_GEC
REAL(KIND=JPRB), OPTIONAL, DIMENSION (:) ::  P__ATMONEBUL_BASSE
REAL(KIND=JPRB), OPTIONAL, DIMENSION (:) ::  P__SURFXEVAPOTRANSP
REAL(KIND=JPRB), OPTIONAL, DIMENSION (:) ::  P__SURFFLU_LAT_MEVA
REAL(KIND=JPRB), OPTIONAL, DIMENSION (:) ::  P__SURFACCPLUIE
REAL(KIND=JPRB), OPTIONAL, DIMENSION (:) ::  P__SURFACCNEIGE
REAL(KIND=JPRB), OPTIONAL, DIMENSION (:) ::  P__SURFACCGRAUPEL
REAL(KIND=JPRB), OPTIONAL, DIMENSION (:) ::  P__CLSTEMPERATURE
REAL(KIND=JPRB), OPTIONAL, DIMENSION (:) ::  P__CLSHUMI_RELATIVE
REAL(KIND=JPRB), OPTIONAL, DIMENSION (:) ::  P__CLSVENT_ZONAL
REAL(KIND=JPRB), OPTIONAL, DIMENSION (:) ::  P__CLSVENT_MERIDIEN
REAL(KIND=JPRB), OPTIONAL, DIMENSION (:) ::  P__SURFIND_TERREMER
REAL(KIND=JPRB), OPTIONAL, DIMENSION (:) ::  P__SURFRESERV_NEIGE
REAL(KIND=JPRB), OPTIONAL, DIMENSION (:) ::  P__LON
REAL(KIND=JPRB), OPTIONAL, DIMENSION (:) ::  P__LAT
LOGICAL,         OPTIONAL, DIMENSION (:) ::  OD_MASKEXT
!
!*    0.     Declaration of local variables
!            ------------------------------
!
CHARACTER(LEN=3), PARAMETER  :: YINIT        = 'ALL'
CHARACTER(LEN=2), PARAMETER  :: YTEST        = 'OK'          ! must be equal to 'OK'
CHARACTER(LEN=28)            :: YATMFILE  ='   '  ! name of the Atmospheric file
CHARACTER(LEN=6)             :: YATMFILETYPE ='      '                     ! type of the Atmospheric file
CHARACTER(LEN=28)            :: YLUOUT    ='LISTING_SODA                '  ! name of listing
CHARACTER(LEN=6)             :: YPROGRAM2 = 'FA    '
CHARACTER(LEN=28)            :: YFILEIN
CHARACTER(LEN=1)             :: YVAR
!
REAL,ALLOCATABLE, DIMENSION(:)   :: ZLSM                ! Land-Sea mask
REAL,ALLOCATABLE, DIMENSION(:)   :: ZCON_RAIN           ! Amount of convective liquid precipitation
REAL,ALLOCATABLE, DIMENSION(:)   :: ZSTRAT_RAIN         ! Amount of stratiform liquid precipitation
REAL,ALLOCATABLE, DIMENSION(:)   :: ZCON_SNOW           ! Amount of convective solid precipitation
REAL,ALLOCATABLE, DIMENSION(:)   :: ZSTRAT_SNOW         ! Amount of stratiform solid precipitation
REAL,ALLOCATABLE, DIMENSION(:)   :: ZCON_GRAUPEL        ! Amount of convective graupel pecipitation (AROME)
REAL,ALLOCATABLE, DIMENSION(:)   :: ZCLOUDS             ! Cloudcover
REAL,ALLOCATABLE, DIMENSION(:)   :: ZEVAPTR             ! Evaporation
REAL,ALLOCATABLE, DIMENSION(:)   :: ZEVAP               ! Evaporation
REAL,ALLOCATABLE, DIMENSION(:)   :: ZTSC                ! Climatological surface temperature
REAL,ALLOCATABLE, DIMENSION(:)   :: ZTS                 ! Surface temperature
REAL,ALLOCATABLE, DIMENSION(:)   :: ZT2M                ! Screen level temperature
REAL,ALLOCATABLE, DIMENSION(:)   :: ZHU2M               ! Screen level relative humidity
REAL,ALLOCATABLE, DIMENSION(:)   :: ZSNC
REAL,ALLOCATABLE, DIMENSION(:)   :: ZSWE                ! Snow water equvivalent (amount of snow on the ground)
REAL,ALLOCATABLE, DIMENSION(:)   :: ZSWEC               ! Climatological snow water equvivalent (amount of snow on the ground)
REAL,ALLOCATABLE, DIMENSION(:)   :: ZUCLS
REAL,ALLOCATABLE, DIMENSION(:)   :: ZVCLS
REAL,ALLOCATABLE, DIMENSION(:)   :: ZSST                ! SST from external file
REAL,ALLOCATABLE, DIMENSION(:)   :: ZSIC                ! SIC from external file
REAL,ALLOCATABLE, DIMENSION(:)   :: ZLAT
REAL,ALLOCATABLE, DIMENSION(:)   :: ZLON
!
REAL    :: ZTIME
REAL    :: ZTIME_OUT           ! output time since start of the run (s)
REAL(KIND=JPRB)                  :: ZHOOK_HANDLE
!
LOGICAL, ALLOCATABLE, DIMENSION(:) :: GD_MASKEXT
LOGICAL :: GFOUND
!
TYPE (DATE_TIME)                 :: TTIME               ! Current date and time  
!
INTEGER, DIMENSION(11)  :: IDATEF
INTEGER :: INI, ISIZE          ! grid dimension
INTEGER :: ISV                 ! Number of scalar species
INTEGER :: ISW                 ! Number of radiative bands 
INTEGER :: IYEAR, IMONTH, IDAY
INTEGER :: IYEAR_OUT, IMONTH_OUT, IDAY_OUT
INTEGER :: IIVAR,ITIMES
INTEGER :: INW, JNW
INTEGER :: IVAR_COUNT
INTEGER :: IOBS
INTEGER :: IGPCOMP
INTEGER :: ILUOUT
INTEGER :: ILUNAM
INTEGER :: IRET, INB
INTEGER :: IRESP               ! Response value
!
IF (LHOOK) CALL DR_HOOK('SODA',0,ZHOOK_HANDLE)

WRITE(*,*)
WRITE(*,*) '   ------------------------------------'
WRITE(*,*) '   |               SODA               |'
WRITE(*,*) '   | SURFEX OFFLINE DATA ASSIMILATION |'
WRITE(*,*) '   ------------------------------------'
WRITE(*,*)

CSOFTWARE = 'SODA'

! Read offline specific things
CALL OPEN_NAMELIST('ASCII ',ILUNAM,CNAMELIST)
CALL POSNAM(ILUNAM,'NAM_IO_OFFLINE',GFOUND)
IF (GFOUND) READ (UNIT=ILUNAM,NML=NAM_IO_OFFLINE)
CALL CLOSE_NAMELIST('ASCII ',ILUNAM)

! Open ascii outputfile for writing
#ifdef LFI
CLUOUT_LFI =  ADJUSTL(ADJUSTR(YLUOUT)//'.txt')
#endif
#ifdef NC
CLUOUT_NC = ADJUSTL(ADJUSTR(YLUOUT)//'.txt')
#endif
CALL GET_LUOUT(CSURF_FILETYPE,ILUOUT)
OPEN(UNIT=ILUOUT,FILE=ADJUSTL(ADJUSTR(YLUOUT)//'.txt'),FORM='FORMATTED',ACTION='WRITE')


! Reading all namelist (also assimilation)
CALL READ_ALL_NAMELISTS(CSURF_FILETYPE,'ALL',.FALSE.)

IF (ODINLINE) THEN
  CSURF_FILETYPE = 'AROME'
#ifdef ARO   
  IGPCOMP = MIN (NGPTOT, NGPTOT_CAP) 
  NBLOCK   = 1
  NINDX1   = 1 + (NBLOCK - 1) * NPROMA
  NINDX2   = MIN (NBLOCK * NPROMA, IGPCOMP)
  NKPROMA  = NINDX2 - NINDX1 + 1
  CALL GOTO_SURFEX (NBLOCK, .TRUE.)
#endif
ELSE
! Go to SURFEX
  CALL ALLOC_SURFEX(1)
  CALL GOTO_SURFEX(1,.TRUE.)
ENDIF

! Setting input files read from namelist
IF ( CSURF_FILETYPE == "LFI   " ) THEN
#ifdef LFI
  CFILEIN_LFI      = CPREPFILE
  CFILE_LFI        = CPREPFILE
  CFILEIN_LFI_SAVE = CPREPFILE
  CFILEPGD_LFI     = CPGDFILE
  IF (.NOT.ODINLINE) CFILEOUT_LFI = CSURFFILE
#endif
ELSEIF ( CSURF_FILETYPE == "FA    " ) THEN
#ifdef FA
  CFILEIN_FA      = ADJUSTL(ADJUSTR(CPREPFILE)//'.fa')
  CFILEIN_FA_SAVE = ADJUSTL(ADJUSTR(CPREPFILE)//'.fa')
  CFILEPGD_FA     = ADJUSTL(ADJUSTR(CPGDFILE)//'.fa')
  IF (.NOT.ODINLINE) CFILEOUT_FA  = ADJUSTL(ADJUSTR(CSURFFILE)//'.fa')
#endif
ELSEIF ( CSURF_FILETYPE == "ASCII " ) THEN
#ifdef ASC
  CFILEIN      = ADJUSTL(ADJUSTR(CPREPFILE)//'.txt')
  CFILEIN_SAVE = ADJUSTL(ADJUSTR(CPREPFILE)//'.txt')
  CFILEPGD     = ADJUSTL(ADJUSTR(CPGDFILE)//'.txt')
  IF (.NOT.ODINLINE) CFILEOUT = ADJUSTL(ADJUSTR(CSURFFILE)//'.txt')
#endif
ELSEIF ( CSURF_FILETYPE == "NC    " ) THEN
#ifdef ASC
  CFILEIN_NC      = ADJUSTL(ADJUSTR(CPREPFILE)//'.nc')
  CFILEIN_NC_SAVE = ADJUSTL(ADJUSTR(CPREPFILE)//'.nc')
  CFILEPGD_NC     = ADJUSTL(ADJUSTR(CPGDFILE)//'.nc')
  IF (.NOT.ODINLINE) CFILEOUT_NC = ADJUSTL(ADJUSTR(CSURFFILE)//'.nc')
#endif
ELSE
  CALL ABOR1_SFX(TRIM(CSURF_FILETYPE)//" is not implemented!")
ENDIF

! Initialize time information
IYEAR    = NUNDEF
IMONTH   = NUNDEF
IDAY     = NUNDEF
ZTIME    = XUNDEF
CALL INIT_IO_SURF_n(CSURF_FILETYPE,'FULL  ','SURF  ','READ ')
CALL READ_SURF(CSURF_FILETYPE,'DIM_FULL  ',INI,  IRESP)
CALL READ_SURF(CSURF_FILETYPE,'DTCUR     ',TTIME,  IRESP)
CALL END_IO_SURF_n(CSURF_FILETYPE)
!
NINDX2SFX = INI
ALLOCATE(NWORK(INI))
ALLOCATE(XWORK(INI))
ALLOCATE(XWORK2(INI,10))
ALLOCATE(XWORK3(INI,10,10))
IF (NRANK==NPIO) THEN
  ALLOCATE(NWORK_FULL(INI))
  ALLOCATE(XWORK_FULL(INI))
  ALLOCATE(XWORK2_FULL(INI,10))
ELSE
  ALLOCATE(NWORK_FULL(0))
  ALLOCATE(XWORK_FULL(0))
  ALLOCATE(XWORK2_FULL(0,0))
ENDIF
!
IYEAR  = TTIME%TDATE%YEAR
IMONTH = TTIME%TDATE%MONTH
IDAY   = TTIME%TDATE%DAY
ZTIME  = TTIME%TIME
!
ISW = 0
ISV = 0
ALLOCATE(CSV(ISV))
ALLOCATE(XCO2(INI))
ALLOCATE(XRHOA(INI))
ALLOCATE(XZENITH(INI))
ALLOCATE(XAZIM(INI))
ALLOCATE(XSW_BANDS(ISW))
ALLOCATE(XDIR_ALB(INI,ISW))
ALLOCATE(XSCA_ALB(INI,ISW))
ALLOCATE(XEMIS(INI))
ALLOCATE(XTSRAD(INI))
!
! Indicate that zenith and azimuth angles are not initialized
XZENITH = XUNDEF
XAZIM   = XUNDEF
!
IF ( CASSIM_ISBA == 'EKF  ' ) THEN
 ! Has to do initialization for all the perturbations + 
 ! control + the real run at last
 ITIMES = NVAR + 2
ELSE
 ITIMES = 1
ENDIF

WRITE(*,*) "INITIALIZING SURFEX..."
!
DO IVAR_COUNT = 1,ITIMES

  ! If we have more than one initialization to do
  IF ( ITIMES > 1 ) THEN
    IF (IVAR_COUNT /= ITIMES ) THEN
      ! For last initialization, we must re-do the first.
      ! Could be avoided by introducing knowlegde of LASSIM on this level
      WRITE(YVAR,'(I1.1)') IVAR_COUNT-1
      !
      IF ( CSURF_FILETYPE == "LFI   " ) THEN
        YFILEIN = "PREP_EKF_PERT"//YVAR
      ELSEIF ( CSURF_FILETYPE == "FA    " ) THEN
        YFILEIN = "PREP_EKF_PERT"//ADJUSTL(ADJUSTR(YVAR)//'.fa')
      ELSEIF ( CSURF_FILETYPE == "ASCII " ) THEN
        YFILEIN = "PREP_EKF_PERT"//ADJUSTL(ADJUSTR(YVAR)//'.txt')
      ELSEIF ( CSURF_FILETYPE == "NC    " ) THEN
        YFILEIN = "PREP_EKF_PERT"//ADJUSTL(ADJUSTR(YVAR)//'.nc')
      ELSE
        CALL ABOR1_SFX(TRIM(CSURF_FILETYPE)//" is not implemented!")
      ENDIF
    ELSE
      IF ( CSURF_FILETYPE == "LFI   " ) THEN
        YFILEIN = CPREPFILE
      ELSEIF ( CSURF_FILETYPE == "FA    " ) THEN
        YFILEIN = ADJUSTL(ADJUSTR(CPREPFILE)//'.fa')
      ELSEIF ( CSURF_FILETYPE == "ASCII " ) THEN
        YFILEIN = ADJUSTL(ADJUSTR(CPREPFILE)//'.txt')
      ELSEIF ( CSURF_FILETYPE == "NC    " ) THEN
        YFILEIN = ADJUSTL(ADJUSTR(CPREPFILE)//'.nc')
      ELSE
        CALL ABOR1_SFX(TRIM(CSURF_FILETYPE)//" is not implemented!")
      ENDIF
    ENDIF            
    !  
    IF ( CSURF_FILETYPE == "LFI   " ) THEN
#ifdef LFI
      CFILEIN_LFI      = YFILEIN 
      CFILE_LFI        = YFILEIN
      CFILEIN_LFI_SAVE = YFILEIN
#endif
    ELSEIF ( CSURF_FILETYPE == "FA    " ) THEN
#ifdef FA
      CFILEIN_FA      = YFILEIN
      CFILEIN_FA_SAVE = YFILEIN
#endif
    ELSEIF ( CSURF_FILETYPE == "ASCII " ) THEN
#ifdef ASC
      CFILEIN      = YFILEIN
      CFILEIN_SAVE = YFILEIN
#endif
    ELSEIF ( CSURF_FILETYPE == "NC    " ) THEN
#ifdef NC
      CFILEIN_NC      = YFILEIN
      CFILEIN_NC_SAVE = YFILEIN
#endif
    ELSE
      CALL ABOR1_SFX(TRIM(CSURF_FILETYPE)//" is not implemented!")
    ENDIF
    !
  ENDIF
  !
  ! Initialize the SURFEX interface
  CALL IO_BUFF_CLEAN_n
  CALL INIT_SURF_ATM_n(CSURF_FILETYPE,YINIT, LLAND_USE, INI, ISV, ISW,  &
                       CSV, XCO2, XRHOA, XZENITH, XAZIM, XSW_BANDS,     &
                       XDIR_ALB, XSCA_ALB, XEMIS, XTSRAD,               &
                       IYEAR, IMONTH, IDAY, ZTIME,                      &
                        YATMFILE, YATMFILETYPE, YTEST              )
  !
  IF ( CASSIM_ISBA == 'EKF  ' ) THEN
    !
    IF ( IVAR_COUNT == 1 ) THEN
      ALLOCATE(XF      (NSIZE_NATURE,NPATCH,NVAR+1,NVAR    ))
      ALLOCATE(XF_PATCH(NSIZE_NATURE,NPATCH,NVAR+1,NOBSTYPE))
    ENDIF
    !
    IF ( IVAR_COUNT>0 .AND. IVAR_COUNT<ITIMES )  THEN
      !
      ! Set the global state values for this control value
      DO IOBS = 1,NOBSTYPE
        SELECT CASE (TRIM(COBS(IOBS)))
          CASE("T2M")
            XF_PATCH(:,:,IVAR_COUNT,IOBS) = XAT2M_ISBA(:,:)
          CASE("HU2M")
            XF_PATCH(:,:,IVAR_COUNT,IOBS) = XAHU2M_ISBA(:,:)
          CASE("WG1")
            XF_PATCH(:,:,IVAR_COUNT,IOBS) = XWG(:,1,:)
          CASE DEFAULT
            CALL ABOR1_SFX("Mapping of "//COBS(IOBS)//" is not defined in AROINI_SURFC!")
        END SELECT
      ENDDO
      !
      ! Prognostic fields for assimilation (Control vector)
      DO IIVAR = 1,NVAR
        SELECT CASE (TRIM(CVAR(IIVAR)))
          CASE("TG1")
            XF(:,:,IVAR_COUNT,IIVAR) = XTG(:,1,:)
          CASE("TG2")
            XF(:,:,IVAR_COUNT,IIVAR) = XTG(:,2,:)
          CASE("WG1")
            XF(:,:,IVAR_COUNT,IIVAR) = XWG(:,1,:)
          CASE("WG2")
            XF(:,:,IVAR_COUNT,IIVAR) = XWG(:,2,:)
          CASE DEFAULT
            CALL ABOR1_SFX("Mapping of "//TRIM(CVAR(IIVAR))//" is not defined in AROINI_SURFC!")
        END SELECT
      ENDDO
    ENDIF
  ENDIF
ENDDO
!
CALL GET_SIZE_FULL_n(CSURF_FILETYPE,INI,NSIZE_FULL)
!
IF (ODINLINE) THEN
  ISIZE = NSIZE_FULL
ELSE
  ISIZE = INI
ENDIF
!
WRITE(*,*) "READING input files..."
! Normal reading of needed FA fields
ALLOCATE(ZLSM        (ISIZE))
ALLOCATE(ZCON_RAIN   (ISIZE))
ALLOCATE(ZSTRAT_RAIN (ISIZE))
ALLOCATE(ZCON_SNOW   (ISIZE))
ALLOCATE(ZSTRAT_SNOW (ISIZE))
ALLOCATE(ZCON_GRAUPEL(ISIZE))
ALLOCATE(ZCLOUDS     (ISIZE))
ALLOCATE(ZEVAPTR     (ISIZE))
ALLOCATE(ZEVAP       (ISIZE))
ALLOCATE(ZTSC        (ISIZE))
ALLOCATE(ZSWE        (ISIZE))
ALLOCATE(ZSWEC       (ISIZE))
ALLOCATE(ZTS         (ISIZE))
ALLOCATE(ZT2M        (ISIZE))
ALLOCATE(ZHU2M       (ISIZE))
ALLOCATE(ZUCLS       (ISIZE))
ALLOCATE(ZVCLS       (ISIZE))
ALLOCATE(ZSST        (ISIZE))
ALLOCATE(ZSIC        (ISIZE))

IF (.NOT. ODINLINE) THEN
!  Read atmospheric forecast fields from FA files 
#ifdef FA
  CFILEIN_FA = 'FG_OI_MAIN'
  CDNOMC     = 'oimain'                  ! new frame name
#endif
!  Open FA file (LAM version with extension zone)
  CALL INIT_IO_SURF_n(YPROGRAM2,'EXTZON','SURF  ','READ ')
ENDIF
!
!  Read model forecast quantities
IF (LAROME) THEN
  IF (ODINLINE) THEN
    ZCON_RAIN   (:) = P__SURFACCPLUIE   (1:ISIZE)
    ZCON_SNOW   (:) = P__SURFACCNEIGE   (1:ISIZE)
    ZCON_GRAUPEL(:) = P__SURFACCGRAUPEL (1:ISIZE)
  ELSE        
    CALL READ_SURF(YPROGRAM2,'SURFACCPLUIE',    ZCON_RAIN    ,IRESP)
    CALL READ_SURF(YPROGRAM2,'SURFACCNEIGE',    ZCON_SNOW    ,IRESP)
    CALL READ_SURF(YPROGRAM2,'SURFACCGRAUPEL',  ZCON_GRAUPEL ,IRESP)
    ! So far graupel has not been used
    !ZCON_SNOW=ZCON_SNOW+ZCON_GRAUPEL
  ENDIF
  ZSTRAT_RAIN(:) = 0.0
  ZSTRAT_SNOW(:) = 0.0  
ELSE
  IF (ODINLINE) THEN
    ZCON_RAIN  (:) = P__SURFPREC_EAU_CON (1:ISIZE)
    ZSTRAT_RAIN(:) = P__SURFPREC_EAU_GEC (1:ISIZE)
    ZCON_SNOW  (:) = P__SURFPREC_NEI_CON (1:ISIZE)
    ZSTRAT_SNOW(:) = P__SURFPREC_NEI_GEC (1:ISIZE)
  ELSE        
    CALL READ_SURF(YPROGRAM2,'SURFPREC.EAU.CON',ZCON_RAIN    ,IRESP)
    CALL READ_SURF(YPROGRAM2,'SURFPREC.EAU.GEC',ZSTRAT_RAIN  ,IRESP)
    CALL READ_SURF(YPROGRAM2,'SURFPREC.NEI.CON',ZCON_SNOW    ,IRESP)
    CALL READ_SURF(YPROGRAM2,'SURFPREC.NEI.GEC',ZSTRAT_SNOW  ,IRESP)
  ENDIF
  ZCON_GRAUPEL(:) = 0.0
ENDIF
!
IF (ODINLINE) THEN
  ZCLOUDS(:) = P__ATMONEBUL_BASSE  (1:ISIZE)
  ZLSM   (:) = P__SURFIND_TERREMER (1:ISIZE)
  ZEVAP  (:) = P__SURFFLU_LAT_MEVA (1:ISIZE)
ELSE
  CALL READ_SURF(YPROGRAM2,'ATMONEBUL.BASSE ',ZCLOUDS,IRESP)
  CALL READ_SURF(YPROGRAM2,'SURFIND.TERREMER',ZLSM   ,IRESP)
  CALL READ_SURF(YPROGRAM2,'SURFFLU.LAT.MEVA',ZEVAP  ,IRESP) ! accumulated fluxes (not available in LFI)
ENDIF
!
IF (.NOT.LALADSURF) THEN
  IF (ODINLINE) THEN
    ZEVAPTR(:) = P__SURFXEVAPOTRANSP (1:ISIZE)
  ELSE        
    CALL READ_SURF(YPROGRAM2,'SURFXEVAPOTRANSP',ZEVAPTR,IRESP) ! not in ALADIN SURFEX
  ENDIF
ELSE
  ZEVAPTR(:) = 0.0
ENDIF

IF (.NOT. ODINLINE) THEN
!  Close FA file
  CALL END_IO_SURF_n(YPROGRAM2)
  CALL IO_BUFF_CLEAN_n
  WRITE(*,*)'READ FG_OI_MAIN OK'
ENDIF

IF (.NOT. ODINLINE) THEN
!  Define FA file name for CANARI analysis
#ifdef FA
  CFILEIN_FA = 'CANARI'        ! input CANARI analysis
  CDNOMC     = 'canari'                  ! new frame name
#endif
!  Open FA file 
  CALL INIT_IO_SURF_n(YPROGRAM2,'EXTZON','SURF  ','READ ')
ENDIF

IF (ODINLINE) THEN
  ZT2M (:) = P__CLSTEMPERATURE   (1:ISIZE)
  ZHU2M(:) = P__CLSHUMI_RELATIVE (1:ISIZE)
  ZTS  (:) = P__SURFTEMPERATURE  (1:ISIZE)
  ZSWE (:) = P__SURFRESERV_NEIGE (1:ISIZE)
  ZUCLS(:) = P__CLSVENT_ZONAL    (1:ISIZE)
  ZVCLS(:) = P__CLSVENT_MERIDIEN (1:ISIZE)
ELSE
!  Read CANARI analysis
  CALL READ_SURF(YPROGRAM2,'CLSTEMPERATURE  ',ZT2M ,IRESP)
  CALL READ_SURF(YPROGRAM2,'CLSHUMI.RELATIVE',ZHU2M,IRESP)
  CALL READ_SURF(YPROGRAM2,'SURFTEMPERATURE ',ZTS  ,IRESP)
  CALL READ_SURF(YPROGRAM2,'SURFRESERV.NEIGE',ZSWE ,IRESP)
  CALL READ_SURF(YPROGRAM2,'CLSVENT.ZONAL   ',ZUCLS,IRESP)
  CALL READ_SURF(YPROGRAM2,'CLSVENT.MERIDIEN',ZVCLS,IRESP)  
ENDIF

IF (.NOT. ODINLINE) THEN
!  Close CANARI file
  CALL END_IO_SURF_n(YPROGRAM2)
  CALL IO_BUFF_CLEAN_n
  WRITE(*,*) 'READ CANARI OK'
ENDIF

IF (.NOT. ODINLINE) THEN
!  Define FA file name for surface climatology
#ifdef FA
  CFILEIN_FA = 'clim_isba'               ! input climatology
  CDNOMC     = 'climat'                  ! new frame name
#endif
!  Open FA file 
  CALL INIT_IO_SURF_n(YPROGRAM2,'EXTZON','SURF  ','READ ')
ENDIF

IF (ODINLINE) THEN
  ZSWEC(:) = P__SURFRESERV_NEIGE (1:ISIZE)
  ZTSC (:) = P__SURFTEMPERATURE  (1:ISIZE)
ELSE
!  Read climatology file
  CALL READ_SURF(YPROGRAM2,'SURFRESERV.NEIGE',ZSWEC,IRESP)
  CALL READ_SURF(YPROGRAM2,'SURFTEMPERATURE' ,ZTSC ,IRESP)
ENDIF

IF (.NOT. ODINLINE) THEN
!  Close climatology file
  CALL END_IO_SURF_n(YPROGRAM2)
  CALL IO_BUFF_CLEAN_n
  WRITE(*,*) 'READ CLIMATOLOGY OK'
ENDIF

IF ( LREAD_SST_FROM_FILE ) CALL ASSIM_READ_SST_FROM_FILE(NSIZE_FULL,ZLSM,ZSST,ZSIC,YTEST)

IF ( .NOT. LASSIM ) CALL ABOR1_SFX("YOU CAN'T RUN SODA WITHOUT SETTING LASSIM=.TRUE. IN THE ASSIM NAMELIST")

IF (PRESENT(OD_MASKEXT)) THEN
  ALLOCATE(GD_MASKEXT(SIZE(OD_MASKEXT)))
  GD_MASKEXT(:) = OD_MASKEXT(:)
ELSE
  ALLOCATE(GD_MASKEXT(0))
ENDIF
!
IF (ODINLINE) THEN
  ALLOCATE(ZLON(SIZE(P__LON)))
  ALLOCATE(ZLAT(SIZE(P__LAT)))
  ZLON(:) = P__LON(:)
  ZLAT(:) = P__LAT(:)        
ELSE
  ALLOCATE(ZLON(0))
  ALLOCATE(ZLAT(0))        
ENDIF
!
WRITE(*,*) 'PERFORMIMG OFFLINE SURFEX DATA ASSIMILATION...'
CALL ASSIM_SURF_ATM_n(CSURF_FILETYPE,ISIZE,   &
                      ZCON_RAIN,  ZSTRAT_RAIN, ZCON_SNOW, ZSTRAT_SNOW, &
                      ZCLOUDS,    ZLSM,        ZEVAPTR,   ZEVAP,       &
                      ZSWEC,      ZTSC,       &
                      ZTS,        ZT2M,        ZHU2M,     ZSWE,        &
                      ZSST,       ZSIC,       &
                      YTEST, ODINLINE, GD_MASKEXT, ZLON, ZLAT )

DEALLOCATE(ZCON_RAIN)
DEALLOCATE(ZSTRAT_RAIN)
DEALLOCATE(ZCON_SNOW)
DEALLOCATE(ZSTRAT_SNOW)
DEALLOCATE(ZCON_GRAUPEL)
DEALLOCATE(ZCLOUDS)
DEALLOCATE(ZLSM)
DEALLOCATE(ZEVAPTR)
DEALLOCATE(ZEVAP)
DEALLOCATE(ZTSC)
DEALLOCATE(ZSWEC)
DEALLOCATE(ZTS)
DEALLOCATE(ZT2M)
DEALLOCATE(ZHU2M)
DEALLOCATE(ZSWE)
DEALLOCATE(ZUCLS)
DEALLOCATE(ZVCLS)
DEALLOCATE(ZSST)
DEALLOCATE(ZSIC)
!
INW = 1
IF (CSURF_FILETYPE=="NC    ") INW = 2
!
ZTIME_OUT  = ZTIME
IDAY_OUT   = IDAY
IMONTH_OUT = IMONTH
IYEAR_OUT  = IYEAR
!
IF(LOUT_TIMENAME)THEN
  ! if true, change the name of output file at the end of a day
  ! (ex: 19860502_00h00 -> 19860501_24h00)                     
  IF(ZTIME==0.0)THEN
    ZTIME_OUT = 86400.
    IDAY_OUT   = IDAY-1
    IF(IDAY_OUT==0)THEN
      IMONTH_OUT = IMONTH - 1
      IF(IMONTH_OUT==0)THEN
        IMONTH_OUT=12
        IYEAR_OUT = IYEAR - 1
      ENDIF
      SELECT CASE (IMONTH_OUT)
        CASE(4,6,9,11)
          IDAY_OUT=30
        CASE(1,3,5,7:8,10,12)
          IDAY_OUT=31
        CASE(2)
          IF( ((MOD(IYEAR_OUT,4)==0).AND.(MOD(IYEAR_OUT,100)/=0)) .OR. (MOD(IYEAR_OUT,400)==0))THEN 
            IDAY_OUT=29
          ELSE
            IDAY_OUT=28
          ENDIF
      END SELECT
    ENDIF
  ENDIF
  !
ENDIF

IF (CTIMESERIES_FILETYPE=='FA    ') THEN
  CDNOMC = 'header'
  LFANOCOMPACT = LDIAG_FA_NOCOMPACT
  IDATEF(1)= IYEAR_OUT
  IDATEF(2)= IMONTH_OUT
  IDATEF(3)= IDAY_OUT
  IDATEF(4)= FLOOR(ZTIME_OUT/3600.)
  IDATEF(5)= FLOOR(ZTIME_OUT/60.) - IDATEF(4) * 60 
  IDATEF(6)= NINT(ZTIME_OUT) - IDATEF(4) * 3600 - IDATEF(5) * 60
  IDATEF(7:11) = 0
  IF (CSURF_FILETYPE/='FA    ') THEN
    CALL WRITE_HEADER_FA(CSURF_FILETYPE,'ALL')
  ELSE
    CALL FAITOU(IRET,NUNIT_FA,.TRUE.,CFILEOUT_FA,'UNKNOWN',.TRUE.,.FALSE.,IVERBFA,0,INB,CDNOMC)
  ENDIF
  CALL FANDAR(IRET,NUNIT_FA,IDATEF)
END IF
!
LDEF = .TRUE.
DO JNW = 1,INW
  ! Store results from assimilation
  CALL WRITE_SURF_ATM_n(CSURF_FILETYPE,'ALL',LLAND_USE)
  CALL WRITE_DIAG_SURF_ATM_n(CSURF_FILETYPE,'ALL')
  LDEF = .FALSE.
  CALL IO_BUFF_CLEAN_n
  !
ENDDO  
!
IF (CTIMESERIES_FILETYPE=='FA    ') THEN
  CALL FAIRME(IRET,NUNIT_FA,'UNKNOWN')
END IF
!
!*    3.     Close parallelized I/O
!            ----------------------
!
WRITE(ILUOUT,*) ' '
WRITE(ILUOUT,*) '    -----------------------'
WRITE(ILUOUT,*) '    | SODA ENDS CORRECTLY |'
WRITE(ILUOUT,*) '    -----------------------'
!
WRITE(*,*) ' '
WRITE(*,*) '    -----------------------'
WRITE(*,*) '    | SODA ENDS CORRECTLY |'
WRITE(*,*) '    -----------------------'
!
CLOSE(ILUOUT)
!
DEALLOCATE(NWORK)
DEALLOCATE(XWORK)
DEALLOCATE(XWORK2)
DEALLOCATE(XWORK3)
DEALLOCATE(NWORK_FULL)
DEALLOCATE(XWORK_FULL)
DEALLOCATE(XWORK2_FULL)
!
CALL DEALLOC_SURFEX
IF (LHOOK) CALL DR_HOOK('SODA',1,ZHOOK_HANDLE)
!
!-------------------------------------------------------------------------------
!
END SUBROUTINE SODA_CONTROL
