SUBROUTINE LFIARTICLES(CARTICLES,KARTICLES)
USE LFIMOD, ONLY : LFI => LFICOM_DEFAULT, &
                 & LFICOM_DEFAULT_INIT,   &
                 & NEW_LFI_DEFAULT
USE LFI_PRECISION, ONLY : JPLIKM
IMPLICIT NONE

INTEGER (KIND=JPLIKM) I,KARTICLES
CHARACTER(LEN=*) CARTICLES(KARTICLES)

IF (.NOT. LFICOM_DEFAULT_INIT) CALL NEW_LFI_DEFAULT ()

DO I=1,KARTICLES
  CARTICLES(I)=LFI%CNOMAR(I)
  IF (LFI%CNOMAR(I)=="**FIN D'INDEX**") EXIT
END DO

END SUBROUTINE LFIARTICLES

SUBROUTINE LFINARTICLES(KARTICLES)
USE LFIMOD, ONLY : LFI => LFICOM_DEFAULT, &
                 & LFICOM_DEFAULT_INIT,   &
                 & NEW_LFI_DEFAULT
USE LFI_PRECISION, ONLY : JPLIKM
IMPLICIT NONE

INTEGER (KIND=JPLIKM) I,KARTICLES

IF (.NOT. LFICOM_DEFAULT_INIT) CALL NEW_LFI_DEFAULT ()

DO I=1,LFI%JPNXNA*LFI%JPNXPI
  IF (LFI%CNOMAR(I)=="**FIN D'INDEX**") EXIT
END DO
KARTICLES=I-1

END SUBROUTINE LFINARTICLES
