!
!       Fonction servant a l'adressage 1D dans les tableaux CNOMAR,
!     MLGPOS et MDES1D, MTAMPD.
!
INTEGER (KIND=JPLIKB) FUNCTION IXM (IKLMNO,IPQRST)
INTEGER (KIND=JPLIKB) :: IKLMNO,IPQRST
IXM = IKLMNO + LFI%JPLARD * (IPQRST - 1_JPLIKB)
END FUNCTION

