!
!       Fonction servant a l'adressage 1D dans les tableaux CNOMAR,
!     MLGPOS et MDES1D, MTAMPD.
!
INTEGER (KIND=JPLIKB) FUNCTION IXC (IABCDE,IFGHIJ)
INTEGER (KIND=JPLIKB) :: IABCDE, IFGHIJ
IXC = IABCDE + LFI%JPNXNA * (IFGHIJ - 1_JPLIKB)
END FUNCTION
