! Oct-2012 P. Marguinaud 64b LFI
#include "lfisuffix.h"
! Jan-2011 P. Marguinaud Thread-safe LFI
SUBROUTINE LFIDEB_MT_BB            &
&                     (LFI, LDEBUG )
USE LFIMOD, ONLY : LFICOM
USE PARKIND1, ONLY : JPRB
USE YOMHOOK , ONLY : LHOOK, DR_HOOK
USE LFI_PRECISION, ONLY : JPDBLE, JPDBLR, JPLIKB, JPLIKM
IMPLICIT NONE
!****
!        CE SOUS-PROGRAMME D'ACTIVER OU DE DESACTIVER LE MODE
!     "MISE AU POINT DU LOGICIEL". ( PAR DEFAUT, INACTIF )
!**
!        ARGUMENT : LDEBUG (ENTREE) ==> VRAI SI ON DOIT ACTIVER CE MODE.
!
!
TYPE(LFICOM) :: LFI
INTEGER (KIND=JPLIKB) INUMER, IREP, INIMES
!
LOGICAL LDEBUG
CHARACTER(LEN=LFI%JPLSPX) CLNSPR
CHARACTER(LEN=LFI%JPLMES) CLMESS
CHARACTER(LEN=LFI%JPLFTX) CLACTI

!
REAL(KIND=JPRB) :: ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK('LFIDEB_MT',0,ZHOOK_HANDLE)
CLACTI=''
IF (LFI%LFIDEB_LLPREA) THEN
  CALL LFIINI_MT_BB              &
&                 (LFI, 2_JPLIKB )
  LFI%LFIDEB_LLPREA=.FALSE.
ENDIF
!
LFI%LMISOP=LDEBUG
!
!        MESSAGERIE EVENTUELLE .
!
IF (LFI%NIMESG.NE.2)  THEN 
  IF (LHOOK) CALL DR_HOOK('LFIDEB_MT',1,ZHOOK_HANDLE)
  RETURN
ENDIF
INUMER=LFI%JPNIL
INIMES=2
IREP=0
CLNSPR='LFIDEB'
WRITE (UNIT=CLMESS,FMT='(''LDEBUG= '',L1)') LDEBUG
CALL LFIEMS_MT_BB                               &
&               (LFI, INUMER,INIMES,IREP,.FALSE., &
&                CLMESS,CLNSPR,CLACTI)
!
IF (LHOOK) CALL DR_HOOK('LFIDEB_MT',1,ZHOOK_HANDLE)
END SUBROUTINE



! Oct-2012 P. Marguinaud 64b LFI
SUBROUTINE LFIDEB_BB          &
&           (LDEBUG)
USE LFIMOD, ONLY : LFI => LFICOM_DEFAULT, &
&                   LFICOM_DEFAULT_INIT,   &
&                   NEW_LFI_DEFAULT
USE LFI_PRECISION, ONLY : JPDBLE, JPDBLR, JPLIKB, JPLIKM
IMPLICIT NONE
! Arguments
LOGICAL                LDEBUG                                 ! IN   

IF (.NOT. LFICOM_DEFAULT_INIT) CALL NEW_LFI_DEFAULT ()

CALL LFIDEB_MT_BB          &
&           (LFI, LDEBUG)

END SUBROUTINE

SUBROUTINE LFIDEB_MM          &
&           (LDEBUG)
USE LFIMOD, ONLY : LFI => LFICOM_DEFAULT, &
&                   LFICOM_DEFAULT_INIT,   &
&                   NEW_LFI_DEFAULT
USE LFI_PRECISION, ONLY : JPDBLE, JPDBLR, JPLIKB, JPLIKM
IMPLICIT NONE
! Arguments
LOGICAL                LDEBUG                                 ! IN   

IF (.NOT. LFICOM_DEFAULT_INIT) CALL NEW_LFI_DEFAULT ()

CALL LFIDEB_MT_MM          &
&           (LFI, LDEBUG)

END SUBROUTINE

SUBROUTINE LFIDEB_MT_MM          &
&           (LFI, LDEBUG)
USE LFIMOD, ONLY : LFICOM,              &
&                   LFICOM_DEFAULT_INIT, &
&                   NEW_LFI_DEFAULT
USE LFI_PRECISION, ONLY : JPDBLE, JPDBLR, JPLIKB, JPLIKM
IMPLICIT NONE
! Arguments
TYPE (LFICOM)          LFI                                    ! INOUT
LOGICAL                LDEBUG                                 ! IN   
! Local integers
! Convert arguments


CALL LFIDEB_MT_BB          &
&           (LFI, LDEBUG)


END SUBROUTINE

!INTF LDEBUG        IN    
